### ISSUE TITLE
github.action description is wrong

### ISSUE THREAD

**Issue by emilyseville7cfg** [github/docs#10017]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)

### What part(s) of the article would you like to see updated?

github.action description to match my [GitHub Action execution results](https://github.com/alvinseville7cf/GitHubContextTest/runs/3585538956?check_suite_focus=true).

**Comment by ramyaparimi** [comment]
@alvinseville7cf Sorry about that! I am triaging the PR for the writer's review 👀 ⚡

**Comment by lecoursen** [comment]
Hi @emilyseville7cf, the documentation seems to match your output to me. Can you clarify the specific differences you're seeing? Thanks!

**Comment by emilyseville7cf** [comment]
@lecoursen, instead of `run` I see `__run` (value of github.action) and instead of `run2` I see `__run_2` .
