### ISSUE TITLE
Blank page when loading docs.github.com

### ISSUE THREAD

**Issue by frodeaa** [github/docs#10026]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Suspect every page has this issue.... the page becoms blank after page load

```
DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
    at O (https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:62181)
    at https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:63455
    at _ (https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:63547)

main-01c5fd917a69a18b1bf5.js:1 Error rendering page:  TypeError: Cannot read property 'cookies' of undefined
    at p (_app-f6933939bae38985e31b.js:1)
    at _app-f6933939bae38985e31b.js:1
    at l (main-01c5fd917a69a18b1bf5.js:1)
    at Generator._invoke (main-01c5fd917a69a18b1bf5.js:1)
```

### What changes are you suggesting?

Don't fail the page load if sendBeacon is unavailable or failed...

**Comment by ramyaparimi** [comment]
@frodeaa 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by P-DUBB** [comment]
``DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
    at O (https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:62181)
    at https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:63455
    at _ (https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:63547)

main-01c5fd917a69a18b1bf5.js:1 Error rendering page:  TypeError: Cannot read property 'cookies' of undefined
    at p (_app-f6933939bae38985e31b.js:1)
    at _app-f6933939bae38985e31b.js:1
    at l (main-01c5fd917a69a18b1bf5.(b)js:1)
    at Generator._invoke (main-01c5fd917a69a18b1bf5.(b)js:1)

**Comment by lee-dohm** [comment]
Thanks for reaching out. We don't maintain https://docs.dintero.com, so I don't think there's anything we can do specifically about this. If you're running into this problem on https://docs.github.com, please let us know the following:

1. On what page you're encountering this problem
2. What browser and version you're using
3. What OS and version you're running into this on

Let us know!

**Comment by frodeaa** [comment]
there was a typo in the title, issue is with any page on docs.github.com 

> Thanks for reaching out. We don't maintain https://docs.dintero.com, so I don't think there's anything we can do specifically about this. If you're running into this problem on https://docs.github.com, please let us know the following:
> 
> 1. On what page you're encountering this problem

https://docs.github.com/en

> 2. What browser and version you're using

qutebrowser v1.13.1
Git commit:
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

> 3. What OS and version you're running into this on

Platform: Linux-5.8.0-63-generic-x86_64-with-glibc2.32, 64bit
Linux distribution: Ubuntu 20.10 (ubuntu)

**Comment by frodeaa** [comment]
The page is show a split second before it "crash" and becomes blank...

**Comment by gracepark** [comment]
@frodea - I highly recommend upgrading to the latest (v2.3.1) - I'm not seeing any issues there!

**Comment by Luimoll** [comment]
https://community.atlassian.com/tnckb94959/rss/search?q=tags:(confluence-cloud)
