### ISSUE TITLE
More precise description of dependabot's Gradle support

### ISSUE THREAD

**Issue by zbynek** [github/docs#10042]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

### What part(s) of the article would you like to see updated?

> [1] Dependabot doesn't run Gradle but supports updates to the following files: build.gradle and build.gradle.kts (for Kotlin projects).

This is no longer precise, Dependabot can also update e.g. `dependencies.gradle`.

### Additional information

https://github.com/dependabot/dependabot-core/pull/4155#issuecomment-918500360

**Comment by ramyaparimi** [comment]
@zbynek 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
