### ISSUE TITLE
Include information regarding the Let's Encrypt 64 character limitation for CN

### ISSUE THREAD

**Issue by Fuzzwah** [github/docs#10087]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

### What part(s) of the article would you like to see updated?

The generation of Let's Encrypt certification for a Pages custom domain that has a Common Name longer than 64 characters will fail without a clear message being returned to the user.

This limitation should be noted in the Securing your GitHub Pages site with HTTPS documentation.

**Comment by ramyaparimi** [comment]
@Fuzzwah 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @Fuzzwah! Let's add that limitation to the "About" section of that article. You or anyone else is welcome to open a PR doing so! ⚡

**Comment by ExtremeSport** [comment]
53de51e
