### ISSUE TITLE
Relationship between user status and team review assignment is not documented

### ISSUE THREAD

**Issue by bendrucker** [github/docs#10112]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile#setting-a-status

### What part(s) of the article would you like to see updated?

The settings page for each team contains the following note:

> Note: this won't assign members who have committed to the pull request or have set their status to Busy.

However, regular members (i.e. not `maintainer` or org `owner`) cannot see this view. The documentation never explicitly mentions the interaction between these two features.

At a minimum the code review assignment article should describe the fact that "Busy" users will not be selected for automatic assignment. It's probably worth linking back from the profile article as well.

### Additional information

PR incoming!

**Comment by lecoursen** [comment]
Thanks @bendrucker! I agree that we should mention this limitation in "Managing code review assignment for your team". You or anyone else is welcome to open a PR doing so. ⚡

**Comment by lecoursen** [comment]
Whoops, just noticed you already opened a PR! I'll review that now. 😄
