### ISSUE TITLE
Query Variables pane in the GraphQL Explorer wipes contents unexpectedly

### ISSUE THREAD

**Issue by QuintinWillison** [github/docs#10130]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/overview/explorer

### What changes are you suggesting?

I was expecting that I could define a variable in the query pane and then use it in the query.

Both panes almost appear to be unaware of one another. Also, the Query Variables pane seems to randomly delete all the contents I put in there - reverting to empty object `{}`.

### Additional information

<img width="1481" alt="Screenshot 2021-09-17 at 10 25 58" src="https://user-images.githubusercontent.com/8318344/133760538-bd6dbdb6-3b0e-458b-92c4-59f78de0475b.png">

Hovering over the red underline in the query pane shows the same message twice:

```
Variable "$org" is not defined.
Variable "$org" is not defined.
```

Hovering over the red underline in the query variables pane shows this message:

```
Variable "$org" does not appear in any GraphQL query.
```

If I replace `$org` in my query with `"ably"` (my starting point) then the query works.

**Comment by Kurt-von-Laven** [comment]
I have also experienced the variable pane repeatedly wiping its contents. This occurred whenever the query pane was edited, so I learned to make very certain that my query was correct before entering any variables. This substantially reduces the utility of the tool since it is intended to show real-time results as a query as modified.

**Comment by QuintinWillison** [comment]
@Kurt-von-Laven it sounds like you got it working, at least. Would you be able to share a screen shot of it working as I find that very curious (I understand if you're unable to share). Also, if it adds any, I was also using latest version of Chrome, albeit on latest version of macOS (11.6).

**Comment by Kurt-von-Laven** [comment]
@QuintinWillison, I didn't notice this initially, so I'm glad you reached out. I believe there is an issue to be fixed by GitHub here as I mentioned above, but also the query in your screenshot is missing the function prototype. Here is a corrected version of the query that I tested keeping the variables pane as you had it:

```js
query LabelsInUse($org: String!) {
  organization(login: $org) {
    repositories(privacy: PUBLIC, first: 2) {
      nodes {
        labels(first: 100) {
          nodes {
            name
          }
        }
      }
    }
  }
}
```

**Comment by QuintinWillison** [comment]
Thanks @Kurt-von-Laven ... I'm still learning / probing GraphQL so the need for this wasn't immediately obvious to me. As far as I can tell, in the GitHub docs, there isn't a concrete example of a query using variables. But then I may be looking in the wrong places or not looking hard enough.

As you state, however, there's still an issue with the variable pane wiping contents. Just now I got it to do it by pressing the 'Prettify' button after running my originally stated query with the fix you pointed me to. My query now looks like:

```graphql
query LabelsInUse($org: String!) {
  organization(login: $org) {
    repositories(privacy: PUBLIC, first: 2) {
      nodes {
        labels(first: 100) {
          nodes {
            name
          }
        }
      }
    }
  }
}
```

**Comment by ramyaparimi** [comment]
@QuintinWillison 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Kurt-von-Laven** [comment]
I highly recommend [the GraphQL docs](https://graphql.org/learn/queries/) as some of the best software documentation I have ever encountered, and that has many interactive examples of queries with variables. [Here](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#working-with-variables)  is an example of a query with variables from the GitHub Docs.

**Comment by rachmari** [comment]
@QuintinWillison @Kurt-von-Laven thank you for reporting the issue with the GraphQL Explorer. I've opened an internal issue to fix this. @QuintinWillison could you let me know what browser and version you're seeing this in? 

I'm able to reproduce the clearing of the query window when I click the explorer button. But I'm not able to reproduce it by clicking in the query window after I run a query.

**Comment by Kurt-von-Laven** [comment]
In the meantime until @QuintinWillison gets a chance to respond, I'm on Chrome 94.0.4606.54 for Linux. I can reproduce the clearing of the query variables by clicking in the query window before I run a query.

**Comment by QuintinWillison** [comment]
Sorry for late response, @rachmari - it's been a busy week!

I'm _currently_ using Chrome `93.0.4577.82 (Official Build) (x86_64)` on macOS `11.6 (20G165)`. Though, of course, when I reported this issue I was more than likely on earlier versions of both.

@Kurt-von-Laven thanks for your [follow-up comment](https://github.com/github/docs/issues/10130#issuecomment-923126968) - in case it wasn't clear, the code I quoted in [my comment](https://github.com/github/docs/issues/10130#issuecomment-922693321) _is working_ ... so you're absolutely right, there is no difference between our queries now (thanks to you! 😄).

**Comment by rachmari** [comment]
Thank you @Kurt-von-Laven and @QuintinWillison. I'll add that information to our issue and I'm sorry for the inconvenience until this is fixed. 🙇‍♀️

**Comment by Kurt-von-Laven** [comment]
This issue doesn't appear to have been fixed.

**Comment by ramyaparimi** [comment]
Sorry about that!! Seems like the stale bot is a little wonky. I am reopening the issue 💖

**Comment by Kurt-von-Laven** [comment]
It looks like stale bot is ignoring the never-stale label?

**Comment by rachmari** [comment]
@Kurt-von-Laven thank you for your patience and for pointing this out! Stalebot is being a little overzealous. I've created a pull request to fix the issue here: https://github.com/github/docs/pull/16799.

**Comment by Kurt-von-Laven** [comment]
Thank you for opening that pull request, @rachmari!

**Comment by mark-mxwl** [comment]
Hi @QuintinWillison, @Kurt-von-Laven, and @rachmari! It seems that in the time since this issue was last commented on, it has been resolved. I tested the GraphQL Explorer on the latest versions of Chrome for macOS/Linux(120.0.6099.109) and Windows(120.0.6099.110), and everything works as expected. Query editor is stable and does not clear unexpectedly.

Unless there are any objections, I would recommend that this issue be marked as closed.

**Comment by QuintinWillison** [comment]
Thanks, @mark-mxwl. I'm not working on anything involving GraphQL or GitHub APIs at the moment, so am years out of context on this, so not positioned to validate this quickly. Equally, no objections to someone who has or can verify marking it as closed. Thanks for checking in. 😁

**Comment by nguyenalex836** [comment]
I second @mark-mxwl - this appears to be fixed when I attempt to reproduce the issue on Chrome as well 💛 closing out this issue!

**Comment by Kurt-von-Laven** [comment]
I was also unable to reproduce the issue and noted the GraphQL Explorer has gotten much faster over the past two years. Kudos to the team for making such a noticeable improvement.

**Comment by nguyenalex836** [comment]
@Kurt-von-Laven I'll be sure to relay this to our team - thank you for the kind words! 💛
