### ISSUE TITLE
CỨ NÓI ĐI ĐỪNG NGẠI

### ISSUE THREAD

**Issue by Tuananh11021986** [github/docs#10168]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Hãy thẳng thắn với nhau trong giao tiếp xã hội. Tôi thích bạn và chơi với ban vậy thôi chứ ko phải vì bạn giống tôi ở 1 vài điểm chung, hay do bạn giàu, bố mẹ bạn là ông này bà kia ....đơn giản chì vì tôi thích còn bạn mà ko thích thì mình chia tay

### What part(s) of the article would you like to see updated?

Toàn bộ 

### Additional information

https://user-images.githubusercontent.com/83211630/133909077-50b7d970-e36c-4dad-904b-00878ea4408b.mp4

**Comment by mateo8032** [comment]
Sent from Android device18 wrz 2021 23:35 Tuananh11021986 ***@***.***> napisał(a):

Code of Conduct

 I have read and agree to the GitHub Docs project's Code of Conduct

What article on docs.github.com is affected?

Hãy thẳng thắn với nhau trong giao tiếp xã hội. Tôi thích bạn và chơi với ban vậy thôi chứ ko phải vì bạn giống tôi ở 1 vài điểm chung, hay do bạn giàu, bố mẹ bạn là ông này bà kia ....đơn giản chì vì tôi thích còn bạn mà ko thích thì mình chia tay

What part(s) of the article would you like to see updated?

Toàn bộ

Additional information

https://user-images.githubusercontent.com/83211630/133909077-50b7d970-e36c-4dad-904b-00878ea4408b.mp4
