### ISSUE TITLE
Rename default branch for `github/.github`

### ISSUE THREAD

**Issue by QuintinWillison** [github/docs#10166]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#about-your-organizations-profile-readme

### What part(s) of the article would you like to see updated?

This isn't actually something to do with that article directly, but instead a problem with [the `github/.github` repository](https://github.com/github/.github) that it naturally leads me to investigate, as I was curious as to how you were implementing your own org's README in terms of best practice (GitHub leading by example).

I'm disappointed to find that the default branch on the repository serving your root org README is still `master`. I'm unable to open issues on that repository so am reporting this here instead. Perhaps you could move to using `main` instead, please.

**Comment by ramyaparimi** [comment]
@QuintinWillison 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Thanks for reporting this, @QuintinWillison. I've opened an issue internally for us to get this changed. It should be changed soon.

Because this isn't actually a docs issue, I'll close this issue.

**Comment by QuintinWillison** [comment]
Related: https://github.com/actions/virtual-environments/issues/4189
