### ISSUE TITLE
Document Version of Feather Icons In Use

### ISSUE THREAD

**Issue by Kurt-von-Laven** [github/docs#10177]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Metadata syntax for GitHub Actions
](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#brandingicon)

### What part(s) of the article would you like to see updated?

The documentation clearly conveys that `branding.icon` should be a Feather icon, and explicitly lists all 257 icons that may be used, helpfully linking to [the Feather icons website](https://feathericons.com/). Considering the number of options available, it is easy to overlook the fact that the latest version of Feather icons, v4.28.0, offers an additional 29 icons that are not listed in the GitHub Docs. Particularly since the Feather icons website has a search box and displays the icons themselves, it is easy to make the mistake of selecting one of those 29 unsupported icons if you get unlucky. This raises the question of which version of Feather icons is in use, which has no answer. There is no point in the version history of Feather icons that corresponds to the exact list of icons in use, and it's not clear to me why those specific icons were removed beyond the fact that some of them are for specific software products. In light of this, it would be helpful to mention explicitly the 29 unsupported icons or at least the fact that only the listed icons are supported. (Or better yet, to support all 286 icons, and list them all along with the version of Feather icons in use.)

### Additional information

[This pull request](https://github.com/SchemaStore/schemastore/pull/1834) lists the corresponding changes I think should eventually be made to the schema of GitHub Actions once the missing non-brand icons are supported.

**Comment by ramyaparimi** [comment]
@Kurt-von-Laven 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felipeadmin** [comment]
Aceito sugestões de melhoria sempre.

**Comment by skedwards88** [comment]
Thanks for opening this issue! I reached out to the team to see what version of feather icons Actions supports.

**Comment by skedwards88** [comment]
The supported icons are from an older vesion of the feather icon library and have brand-specific icons removed. Here is the full list of supported icons:

```
      [
        "activity",
        "airplay",
        "alert-circle",
        "alert-octagon",
        "alert-triangle",
        "align-center",
        "align-justify",
        "align-left",
        "align-right",
        "anchor",
        "aperture",
        "archive",
        "arrow-down-circle",
        "arrow-down-left",
        "arrow-down-right",
        "arrow-down",
        "arrow-left-circle",
        "arrow-left",
        "arrow-right-circle",
        "arrow-right",
        "arrow-up-circle",
        "arrow-up-left",
        "arrow-up-right",
        "arrow-up",
        "at-sign",
        "award",
        "bar-chart-2",
        "bar-chart",
        "battery-charging",
        "battery",
        "bell-off",
        "bell",
        "bluetooth",
        "bold",
        "book-open",
        "book",
        "bookmark",
        "box",
        "briefcase",
        "calendar",
        "camera-off",
        "camera",
        "cast",
        "check-circle",
        "check-square",
        "check",
        "chevron-down",
        "chevron-left",
        "chevron-right",
        "chevron-up",
        "chevrons-down",
        "chevrons-left",
        "chevrons-right",
        "chevrons-up",
        "circle",
        "clipboard",
        "clock",
        "cloud-drizzle",
        "cloud-lightning",
        "cloud-off",
        "cloud-rain",
        "cloud-snow",
        "cloud",
        "code",
        "command",
        "compass",
        "copy",
        "corner-down-left",
        "corner-down-right",
        "corner-left-down",
        "corner-left-up",
        "corner-right-down",
        "corner-right-up",
        "corner-up-left",
        "corner-up-right",
        "cpu",
        "credit-card",
        "crop",
        "crosshair",
        "database",
        "delete",
        "disc",
        "dollar-sign",
        "download-cloud",
        "download",
        "droplet",
        "edit-2",
        "edit-3",
        "edit",
        "external-link",
        "eye-off",
        "eye",
        "facebook",
        "fast-forward",
        "feather",
        "file-minus",
        "file-plus",
        "file-text",
        "file",
        "film",
        "filter",
        "flag",
        "folder-minus",
        "folder-plus",
        "folder",
        "gift",
        "git-branch",
        "git-commit",
        "git-merge",
        "git-pull-request",
        "globe",
        "grid",
        "hard-drive",
        "hash",
        "headphones",
        "heart",
        "help-circle",
        "home",
        "image",
        "inbox",
        "info",
        "italic",
        "layers",
        "layout",
        "life-buoy",
        "link-2",
        "link",
        "list",
        "loader",
        "lock",
        "log-in",
        "log-out",
        "mail",
        "map-pin",
        "map",
        "maximize-2",
        "maximize",
        "menu",
        "message-circle",
        "message-square",
        "mic-off",
        "mic",
        "minimize-2",
        "minimize",
        "minus-circle",
        "minus-square",
        "minus",
        "monitor",
        "moon",
        "more-horizontal",
        "more-vertical",
        "move",
        "music",
        "navigation-2",
        "navigation",
        "octagon",
        "package",
        "paperclip",
        "pause-circle",
        "pause",
        "percent",
        "phone-call",
        "phone-forwarded",
        "phone-incoming",
        "phone-missed",
        "phone-off",
        "phone-outgoing",
        "phone",
        "pie-chart",
        "play-circle",
        "play",
        "plus-circle",
        "plus-square",
        "plus",
        "pocket",
        "power",
        "printer",
        "radio",
        "refresh-ccw",
        "refresh-cw",
        "repeat",
        "rewind",
        "rotate-ccw",
        "rotate-cw",
        "rss",
        "save",
        "scissors",
        "search",
        "send",
        "server",
        "settings",
        "share-2",
        "share",
        "shield-off",
        "shield",
        "shopping-bag",
        "shopping-cart",
        "shuffle",
        "sidebar",
        "skip-back",
        "skip-forward",
        "slash",
        "sliders",
        "smartphone",
        "speaker",
        "square",
        "star",
        "stop-circle",
        "sun",
        "sunrise",
        "sunset",
        "tablet",
        "tag",
        "target",
        "terminal",
        "thermometer",
        "thumbs-down",
        "thumbs-up",
        "toggle-left",
        "toggle-right",
        "trash-2",
        "trash",
        "trending-down",
        "trending-up",
        "triangle",
        "truck",
        "tv",
        "type",
        "umbrella",
        "underline",
        "unlock",
        "upload-cloud",
        "upload",
        "user-check",
        "user-minus",
        "user-plus",
        "user-x",
        "user",
        "users",
        "video-off",
        "video",
        "voicemail",
        "volume-1",
        "volume-2",
        "volume-x",
        "volume",
        "watch",
        "wifi-off",
        "wifi",
        "wind",
        "x-circle",
        "x-square",
        "x",
        "zap-off",
        "zap",
        "zoom-in",
        "zoom-out",
      ]
```

You or anyone else is welcome to open a PR to do any or all of the following:
- update the list of supported icons to match the list above
- make it clear that only a subset of icons are supported
- include icon images in the list of supported icons (this might be tricky/not realistic due to markdown table formatting)

If there is a newer icon that you think should be added, we can probably update the supported list.

**Comment by Kurt-von-Laven** [comment]
Thank you for such a helpful answer, @skedwards88, and apologies for the slow reply. I confirmed that the list you provided matches the current documentation. Here is a list of all 29 Feather v4.28.0 icons that aren't currently supported:

```
chrome
codepen
codesandbox
coffee
columns
divide-circle
divide-square
divide
dribbble
figma
framer
frown
github
gitlab
hexagon
instagram
key
linkedin
meh
mouse-pointer
pen-tool
slack
smile
tool
trello
twitch
twitter
x-octagon
youtube
```

Here is the list of the 13 missing icons that remain after brand-specific icons removed. I wasn't sure whether pen-tool should also be included since it's a tool in Adobe Illustrator.

```
coffee
columns
divide-circle
divide-square
divide
frown
hexagon
key
meh
mouse-pointer
smile
tool
x-octagon
```

It would be great if those 13 missing icons could be added. Coffee and tool, in particular, would make great logos for community-contributed GitHub Actions.

**Comment by skedwards88** [comment]
Thank you for this detailed research! I opened an issue with the Actions team to add the missing icons and to verify whether the Facebook icon should be removed.
