### ISSUE TITLE
Make GHSA and CVE publication more distinct

### ISSUE THREAD

**Issue by darakian** [github/docs#10209]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/security-advisories/publishing-a-security-advisory

### What part(s) of the article would you like to see updated?

I would like that the CVE number be made more clearly optional.

**Comment by HarryBO881** [comment]
cool
