### ISSUE TITLE
Chinese version for Github Action Quickstart have an error

### ISSUE THREAD

**Issue by whiteroomelite** [github/docs#1027]
### What article on docs.github.com is affected?
[https://docs.github.com/cn/free-pro-team@latest/actions/quickstart](https://docs.github.com/cn/free-pro-team@latest/actions/quickstart)

### What part(s) of the article would you like to see updated?

There's a line
> 从 GitHub 上的仓库，在 .github/workflow 目录中创建一个名为 superlinter.yml 的新文件。 更多信息请参阅“创建新文件”。

It should be 

> 从 GitHub 上的仓库，在 .github/workflows 目录中创建一个名为 superlinter.yml 的新文件。 更多信息请参阅“创建新文件”。

Lack of an **s** makes great difference

### Additional information
None

**Comment by janiceilene** [comment]
Thank you so much for opening an issue @whiteroomelite! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

In the meantime, I've opened an internal issue for our translators.

**Comment by whiteroomelite** [comment]
Thank you very much!
