### ISSUE TITLE
Docs pages display HTML source code snippets instead of rendering the HTML

### ISSUE THREAD

**Issue by tshddx** [github/docs#10295]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The problem occurs throughout the GraphQL documentation, for example:

- https://docs.github.com/en/graphql/reference/unions
- https://docs.github.com/en/graphql/reference/interfaces

From what I can tell, these HTML source code snippets are intended to be actual HTML in the page that gets properly rendered by the browser. Here's a screenshot:

![Unions - GitHub Docs 2021-09-24 11-27-52](https://user-images.githubusercontent.com/307393/134723174-2b837561-1fc6-4841-80a0-f26fe628fc78.png)

### What changes are you suggesting?

These HTML snippets are likely intended to be compiled directly into the HTML of the documentation page and rendered by the browser, instead of being compiled onto the page as a source code snippet.

**Comment by ramyaparimi** [comment]
@tshddx 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by rachmari** [comment]
@tshddx thank you for reporting this! This should be fixed, but if you're still seeing anything that looks odd please reopen this issue. 🙇‍♀️
