### ISSUE TITLE
Pinned issues for https://github.com/github/docs/issues is stale

### ISSUE THREAD

**Issue by jsoref** [github/docs#10321]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/issues

### What part(s) of the article would you like to see updated?

The pinned issue above the issues box for this repository:
![image](https://user-images.githubusercontent.com/2119212/134791084-2126a302-0227-4971-b52a-d52cba2be72a.png)

### Additional information

We're no longer in July, and #7901 is closed.

**Comment by Finezze2020** [comment]
#10268

**Comment by lee-dohm** [comment]
Fixed.
