### ISSUE TITLE
Fix typographical errors on Contributing.md file

### ISSUE THREAD

**Issue by LuluNwenyi** [github/docs#10333]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I have spotted a minor typographical error on the contributing.md file in this repo.

### What part(s) of the article would you like to see updated?

I would like to fix this error as well as review the file for other errors.

**Comment by ramyaparimi** [comment]
@LuluNwenyi 
Thanks so much for opening an issue! You can open a PR with the fix and link it to this issue when ready ✨

**Comment by LuluNwenyi** [comment]
Hi @ramyaparimi, I have fixed this issue. See [Contributing.md PR](https://github.com/github/docs/pull/10431)
