### ISSUE TITLE
Update 'Blocking a user from your personal account' content

### ISSUE THREAD

**Issue by megbird** [github/docs#1035]
### What feature or product is affected?

GitHub.com

### What is the new or expected behavior?

Add a bullet point to the `When you block a user:` section stating something like:

- The user is not able to join any organizations you are an owner of.

### How is the old or inaccurate behavior currently documented?

If an organization owner has a user blocked from their personal account, that user is unable to be invited to the organization. While this behavior makes sense, it would be great if we noted it somewhere in the documentation on [blocking a user from your personal account](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/blocking-a-user-from-your-personal-account#about-blocking-users). 

### Who does this affect?

100% of GitHub.com users that use the blocking feature.

### Additional information 

in a support ticket we had a customer reach about not being able to invite a user to their organization. They received the error message `User is blocked`. 

This was a result of one of the organization owner's having blocked the user from their personal account.

**Comment by therobgirl** [comment]
💛✝💤

**Comment by Justka89** [comment]
programmer04:patch-1git@github.com:github/docs.gitgit@github.com:progit/progit2.git

**Comment by Justka89** [comment]
@bruce 

- [ ] @Justka89 #653

**Comment by kotujoki72** [comment]
Contoh artikel untuk membuat issues...?
