### ISSUE TITLE
Multi-OS terminal reusable seems incorrect

### ISSUE THREAD

**Issue by CyberFlameGO** [github/docs#10350]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent on the macOS tab

### What part(s) of the article would you like to see updated?

Just Terminal instead of TerminalGit BashTerminal being shown

### Additional information

https://github.com/github/docs/blob/main/data/reusables/command_line/open_the_multi_os_terminal.md

**Comment by ramyaparimi** [comment]
@CyberFlameGO 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Slack88** [comment]
![IMG_20210915_181542](https://user-images.githubusercontent.com/86712560/135143842-b6379b82-6f2e-4871-9ccb-390809a8357c.jpg)

**Comment by mattpollard** [comment]
Thanks for the report, @CyberFlameGO! This [renders properly for me](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key) in Safari 15.0 (15612.1.29.41.4, 15612) and Brave 1.30.86.

<img width="789" alt="Screen Shot 2021-09-30 at 14 22 10" src="https://user-images.githubusercontent.com/1894408/135454487-ccf7c29d-e67c-4c1e-9e42-a670a87c82d6.png">

Though the [rendered view of this reusable](https://github.com/github/docs/blob/main/data/reusables/command_line/open_the_multi_os_terminal.md) on GitHub.com displays as "Open TerminalTerminalGit Bash", the reusable uses `<span>` to specify the platform, so we can use the same reusable across the platform picker tabs. Here's the plain view.

https://github.com/github/docs/blob/c2476124153c2d38a0e815c835826a15d28cfb8e/data/reusables/command_line/open_the_multi_os_terminal.md#L1

If you're seeing "Open TerminalTerminalGit Bash" in your browser, could you provide some more details to help us troubleshoot?

1. A screenshot would be great.
2. We'd like any further details about the browser you're using.
3. It'd help to know if you experience this bug in your browser's "safe mode", with any extensions or plugins disabled.

**Comment by CyberFlameGO** [comment]
Hmm, I was just about to screenshot it but it doesn't happen anymore haha, though I do notice it happening for 2 seconds when I reload the page, but it reloads quickly after and then appears as just "Terminal".
https://user-images.githubusercontent.com/24910512/135541418-aac05e5f-f236-4250-8edf-bd5fd523f734.mov

**Comment by mattpollard** [comment]
Thanks for the video 🙇🏻 I can also see "Open TerminalTerminalGit Bash" for a split second in a browser that uses Chromium, like Brave. Safari's fine on my Mac and other Apple devices. This behavior probably depends on the rendering engine and the system you're using.

Right now, we won't devote engineering effort to changing the behavior. If this breaks again and the text render as just "Terminal" like it should, please let us know! Appreciate the report and keen observation 🦅👀
