### ISSUE TITLE
typo: support github runner page zh docs typo

### ISSUE THREAD

**Issue by chyroc** [github/docs#10384]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/cn/actions/reference/workflow-syntax-for-github-actions

> 警告：Ubuntu 16.04 即将被启用。 如果您的任何工作流程使用 Ubuntu 16.04，请迁移到 Ubuntu 20.04 或 18.04。 更多信息请参阅博客帖子。

### What part(s) of the article would you like to see updated?

启用 -> 弃用

**Comment by ramyaparimi** [comment]
@chyroc Thanks for opening this pull request! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.
