### ISSUE TITLE
The right partner 

### ISSUE THREAD

**Issue by vinomeran** [github/docs#10465]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

#10320

### What changes are you suggesting?

Finishing good and right

### Additional information

The games are too much

**Comment by Luimoll** [comment]
Duplicate of  Luimoll-patch-2 (#8)
