### ISSUE TITLE
Pull Request Template has outdated self-review link

### ISSUE THREAD

**Issue by bgrainger** [github/docs#10609]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The Pull Request Template.

### What changes are you suggesting?

https://github.com/github/docs/blob/main/.github/PULL_REQUEST_TEMPLATE.md contains the following Markdown:

```markdown
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).
```

The destination of the link is wrong.

### Additional information

In https://github.com/github/docs/commit/8405f003ab2ccde882ca0a61296421056b30c74e#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L159 the self-review section was deleted from `CONTRIBUTING.md`, and in https://github.com/github/docs/commit/bb3accf80d78462d086005833f29c6fe9e3d0bb9#diff-4eb3fe3bb17e371765bc1f0a8787415a72b2ab515aa4ff97fc9339e1888c387f it was added to a new file.

**Comment by ramyaparimi** [comment]
@bgrainger Thanks for opening this issue 🐬 You or anyone else is welcome to open a PR with the fix ✨
