### ISSUE TITLE
Pre-receive hooks/$GITHUB_VIA

### ISSUE THREAD

**Issue by blastedt** [github/docs#1082]
### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/admin/policies/creating-a-pre-receive-hook-script.md

### What part(s) of the article would you like to see updated?

The environment variable $GITHUB_VIA has a list of possible values.

1) This list needs an explanation of the meaning of each value (ex: `slumlord`, `stafftools`, etc are unclear)
2) This list needs to be updated to be current.  For example, editing a file in Github's editor gives the value `blob#save` which isn't listed in the table at all.
3) This list needs to make clear that remote pushes (end user running `git push` in their local terminal) will not have `$GITHUB_VIA` set, and to list what other situations this variable will not be set.

### Additional information

I would make this change myself but I honestly am having trouble determining the intended behavior! A docs update would be a great help to me.

**Comment by bankZrowe** [comment]
![Screenshot_20201105-013248](https://user-images.githubusercontent.com/63451951/98219924-a5225200-1f1b-11eb-8c5d-39f01a1d3761.png)

**Comment by blastedt** [comment]
Sorry, not sure how to respond to that!  Could you let me know what you need more clearly please?

**Comment by janiceilene** [comment]
The `welcome bot` comment is just intended to let you know that we'll look at your issue soon, no response necessary! 

Thank so much for letting us know about this @blastedt! I'll have some folks internally take a look at this and see what updates we might be able to make 💛 In the meantime, I'll add a `help wanted` label and maybe someone out there will have some ideas to address your concerns 🤞

**Comment by blastedt** [comment]
Thanks Janice, I appreciate it. Tim

**Comment by guaxy94** [comment]
Hello is this Real?

**Comment by blastedt** [comment]
Hey Matt, thanks for closing this out!  The docs look super helpful now. Tim

**Comment by mattpollard** [comment]
👋🏻 Thanks for creating this issue, @blastedt 🙏🏻 And thanks for your patience while I did some research and prioritized the changes. Let us know if you see any further opportunities to improve this or other documentation 🚀
