### ISSUE TITLE
Directions for creating a new SSH key are inconsistent and fail if run as documented

### ISSUE THREAD

**Issue by DavidAnson** [github/docs#1086]
### What article on docs.github.com is affected?

Generating a new SSH key and adding it to the ssh-agent
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

### What part(s) of the article would you like to see updated?

On Linux, the user is told:

    > Enter a file in which to save the key (/home/you/.ssh/id_ed25519): [Press enter]

And:

    $ ssh-add ~/.ssh/id_rsa

These are inconsistent - the file in the second case should be `id_ed25519`.

I'd have submitted a PR, but there's inconsistent use of `{% data reusables.ssh.add-ssh-key-to-ssh-agent-commandline %}` here and I don't know where that's defined.

### Additional information

Results of the second command if run as documented:

```
pi@pi:~ $ ssh-add ~/.ssh/id_rsa
/home/pi/.ssh/id_rsa: No such file or directory
```

**Comment by nschonni** [comment]
There are 2 pending PRs to fix it https://github.com/github/docs/pull/1074 and https://github.com/github/docs/pull/1063

**Comment by bankZrowe** [comment]
![Screenshot_20201105-004126](https://user-images.githubusercontent.com/63451951/98203402-fe7d8780-1f01-11eb-97a8-630bea07ca36.png)
![Screenshot_20201105-002224](https://user-images.githubusercontent.com/63451951/98203436-16eda200-1f02-11eb-8145-d8f85ad6daf9.png)
![Uploading Screenshot_20201105-002210.png…]()
![Uploading Screenshot_20201105-001041.png…]()

**Comment by bankZrowe** [comment]
![Uploading Screenshot_20201105-001757.png…]()
![Uploading Screenshot_20201105-000447.png…]()

**Comment by bankZrowe** [comment]
![Screenshot_20201105-001724](https://user-images.githubusercontent.com/63451951/98203453-1bb25600-1f02-11eb-8346-bdc85d813377.png)
![Screenshot_20201105-001535](https://user-images.githubusercontent.com/63451951/98203455-1c4aec80-1f02-11eb-9148-1ca3e757da90.png)
![Screenshot_20201105-000556](https://user-images.githubusercontent.com/63451951/98203457-1ce38300-1f02-11eb-85ab-775259941f8e.png)
![Uploading Screenshot_20201105-002228.png…]()
![Uploading Screenshot_20201104-235900.png…]()

**Comment by bankZrowe** [comment]
![Screenshot_20201105-001903](https://user-images.githubusercontent.com/63451951/98203465-1ead4680-1f02-11eb-88ed-408ee4e0aa42.png)
![Screenshot_20201105-001717](https://user-images.githubusercontent.com/63451951/98203467-1f45dd00-1f02-11eb-9752-5be0a8cb04d6.png)
![Uploading Screenshot_20201105-001802.png…]()

**Comment by bankZrowe** [comment]
![Screenshot_20201105-001819](https://user-images.githubusercontent.com/63451951/98203474-210fa080-1f02-11eb-8fa7-1dae83231740.png)
![Screenshot_20201105-001807](https://user-images.githubusercontent.com/63451951/98203478-21a83700-1f02-11eb-8d08-f2bdcca1affc.png)
![Screenshot_20201105-002219](https://user-images.githubusercontent.com/63451951/98203482-2240cd80-1f02-11eb-82da-c171707f82d9.png)
![Screenshot_20201105-001751](https://user-images.githubusercontent.com/63451951/98203485-22d96400-1f02-11eb-88b7-081e6224a35b.png)
![Screenshot_20201105-001333](https://user-images.githubusercontent.com/63451951/98203486-2371fa80-1f02-11eb-86cb-c08c80e81d10.png)
[@BankZrowez](www.linkedin.com)

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by airairair20** [comment]
history

**Comment by shati-patel** [comment]
Thank you for reporting the bug and helping us improve our docs, @DavidAnson! 🎉

This has now been fixed.
