### ISSUE TITLE
caught with Webhook payload not exist error while using workflow_run

### ISSUE THREAD

**Issue by santhoshbackup** [github/docs#10871]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run

### What part(s) of the article would you like to see updated?

i wanted to run workflows in a particular order,so i come to know about workflow_run. but while using workflow_run i caught with webhook payload is not found error. can somebody help with this?

**Comment by Yellappachakali** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run
> 
> ### What part(s) of the article would you like to see updated?
> i wanted to run workflows in a particular order,so i come to know about workflow_run. but while using workflow_run i caught with webhook payload is not found error. can somebody help with this?
> 
> ### Additional information
> _No response_

**Comment by skedwards88** [comment]
Thanks for opening this issue! I think [GitHub support](https://support.github.com/contact) or [GitHub Support Community](https://github.community/) would be the best place to ask this question.
