### ISSUE TITLE
Use real examples in API code examples

### ISSUE THREAD

**Issue by jidanni** [github/docs#1093]
Please change
```
    "last_read_at":"last_read_at"
```
to
```
   "last_read_at":"2014-11-07T22:01:45Z"
```

They occur in
$ w3m -dump https://docs.github.com/en/free-pro-team@latest/rest/reference/activity | grep -n last_read_at.*:.*last_read_at
```
973:  -d '{"last_read_at":"last_read_at"}'
978:  last_read_at: 'last_read_at'
1524:  -d '{"last_read_at":"last_read_at"}'
1531:  last_read_at: 'last_read_at'
```

However they are not accessible from
https://github.com/github/docs/edit/main/content/rest/reference/activity.md
for me to edit. Nor does Search find what file they are in. Therefore
please make the edit for me. Thanks.

**Comment by janiceilene** [comment]
Thanks for opening an issue @jidanni! I believe that information is autogenerated 🤔 but I'll triage this for someone with more knowledge on our rest documentation 💛

**Comment by lucascosti** [comment]
👋 @jidanni.

Our API documentation is autogenerated from the API code, which is why you can't find it in the source in this docs repo.

> Please change
> 
> ```
>     "last_read_at":"last_read_at"
> ```

I assume you're referring to the code examples? e.g [here](https://docs.github.com/en/free-pro-team@latest/rest/reference/activity#mark-notifications-as-read--code-samples)

These are also autogenerated and at the moment just have placeholder values. We do have plans to generate these with proper examples rather than the placeholders you see.

I'll rename this issue and tag in docs engineering too 🙂

**Comment by jidanni** [comment]
> I assume you're referring to...

Yes.

I don't see why impossible/non-working code sample are used, when [directly below it](https://docs.github.com/en/free-pro-team@latest/rest/reference/activity#get-a-thread--code-samples) real/working ones are used.

**Comment by lucascosti** [comment]
> I don't see why impossible/non-working code sample are used, when [directly below it](https://docs.github.com/en/free-pro-team@latest/rest/reference/activity#get-a-thread--code-samples) real/working ones are used.

For integers in examples, it always uses `42` as the number in the code samples. For strings, our generator just defaults to just using the name of the parameter as the example string.

We have plans to improve this to use real examples generated from our schema, so stay tuned! 🙂

**Comment by umutduyum** [comment]
GET /repos/{owner}/{repo}/actions/artifacts

**Comment by Aggrord09** [comment]
Nice

**Comment by Aneudy1187** [comment]
> 

- [ ] `[
Duplicate of #](url)`

**Comment by runleonarun** [comment]
_moved this to docs engineering to prioritize_

**Comment by chiedo** [comment]
👋🏿  @jidanni we're working on this internally, so I'm going to close this issue up. Thanks so much for your passion about docs! We're aiming at having an improved API examples experience for you in the future!
