### ISSUE TITLE
"Make a contribution" button vs. includes

### ISSUE THREAD

**Issue by jidanni** [github/docs#1094]
In #1093 we see the user (me) saw a problem in
https://docs.github.com/en/free-pro-team@latest/rest/reference/activity
and pressed "Make a contribution", leading to
https://github.com/github/docs/edit/main/content/rest/reference/activity.md
however, due to includes, was not able to find the text he intended to
edit. Nor did https://github.com/github/docs/search?q=last_read_at find
it. So he gave up and asked others to make the edit for him.
Probably the file containing "last_read_at" is located off site or something.
(Not in https://github.com/github/docs/tree/main/includes or
https://github.com/github/docs at all. According to Search.)

**Comment by janiceilene** [comment]
👋 Thanks for opening an issue @jidanni! That definitely seems like a frustrating experience. Are there any particular changes that could improve it?

**Comment by jidanni** [comment]
Mmmm, just have the UX team follow each step I listed and see what needs to be fixed.
P.S., I never did find where you folks put the file.

**Comment by janiceilene** [comment]
Thanks @jidanni! I'm going to triage this to the ecosystem team for now. I think the first thing we should do is add something to the `contributing.md` and maybe the `readme.md` explaining how these generated docs work.
