### ISSUE TITLE
Changed organization's Settings sidebar "Block a user".

### ISSUE THREAD

**Issue by taku333** [github/docs#10943]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/maintaining-your-safety-on-github/unblocking-a-user-from-your-organization#unblocking-a-user-in-the-organization-settings

Unblocking a user in the organization settings
3.In your organization's Settings sidebar, click Blocked users.

### What changes are you suggesting?

The Organaization settings have been changed to "click Moderation settings > Blocked users".
<img width="273" alt="スクリーンショット 2021-10-08 16 48 06" src="https://user-images.githubusercontent.com/16697482/136518448-38f17b50-5bab-4c8a-820c-267a6f0dec27.png">

### Additional information

I stopped creating my own pull requests for PR because I didn't know how to highlight the click buttons on images, etc., and it would lose uniformity.

---
_Added by a maintainer_

### Content design plan

1. Update the resuable: [`organizations/block_users.md`](https://github.com/github/docs/blob/main/data/reusables/organizations/block_users.md) to tell users to click **Moderation settings**. Since the blocked users information is shown by default, we don't need a step to tell users to click **Blocked users**.
2. Replace the image used by this reusable with the new image below:

   ![image](https://user-images.githubusercontent.com/1877141/136915213-dcf22c09-db6b-4ab1-85dc-0763057016bd.png)

This will correct the procedures for all three affected articles:
- [Blocking a user from your organization](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization)
- [Unblocking a user from your organization](https://docs.github.com/en/communities/maintaining-your-safety-on-github/unblocking-a-user-from-your-organization)
- [Viewing users who are blocked from your organization](https://docs.github.com/en/communities/maintaining-your-safety-on-github/viewing-users-who-are-blocked-from-your-organization)

**Comment by utliluom33** [comment]
> Cảm ơn bạn đã mở vấn đề này. Một thành viên trong nhóm tài liệu GitHub sẽ sớm đưa ra phản hồi. Trong thời gian chờ đợi, vui lòng xem các [nguyên tắc đóng góp](https://github.com/github/docs/blob/main/CONTRIBUTING.md) .

**Comment by taku333** [comment]
@felicitymay 
Thanks for answer!

>I'll include a screenshot in the content design plan so that you can create a pull request for this issue if you're still interested.
→I would appreciate it if you could give me an image so that I can create a pull request.

**Comment by felicitymay** [comment]
Hi @taku333. 👋🏻 
I included an image in the summary of this issue. You should be able to click on the image to open it in a new tab and download it to your computer.
