### ISSUE TITLE
Code block showing issue_comment PR vs issue differentiation not appearing correctly in docs

### ISSUE THREAD

**Issue by mskelton** [github/docs#1096]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issue_comment

### What part(s) of the article would you like to see updated?

Code block showing the `if: ${{ github.event.issue.pull_request }}` conditional is not appearing on the docs site.  A possible solution would be to omit the `${{` and `}}` since according [to the docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif), that is not required for `if` blocks.

### Additional information

This was added in https://github.com/github/docs/pull/1000

<img width="511" alt="Screen Shot 2020-11-05 at 9 22 58 AM" src="https://user-images.githubusercontent.com/25914066/98260090-838b8f80-1f48-11eb-90f6-5d31696f0d00.png">

**Comment by janiceilene** [comment]
Thanks for opening an issue @mskelton! I'll triage this for a look 👀

**Comment by lucascosti** [comment]
Thanks for reporting this, @mskelton! Yep, those `${{` and `}}` are being stripped out by the liquid processing.

You are right in that they're not necessary in the conditions, but there is another example in the `run` command. We can escape them by wrapping the code block in `{% raw %}` tags to prevent them from being processed.

I'll open a PR for this 👍
