### ISSUE TITLE
Provide detailed instructions on how to check for `ssh-agent` on Windows with OpenSSH

### ISSUE THREAD

**Issue by mavaddat** [github/docs#10967]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

| Description | Link |
| --- | --- |
| Source article | <https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey> |
| Nearest ancestral anchor point | [&hellip;#make-sure-you-have-a-key-that-is-being-used](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey#make-sure-you-have-a-key-that-is-being-used) |
| Specific part | [&hellip;If you are using Git Bash, turn on ssh-agent:&hellip;](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey#:~:text=%23%20start%20the%20ssh-agent%20in%20the%20background%0A%24%20eval%20%22%24(ssh-agent%20-s)%22%0A%3E%20Agent%20pid%2059566) |
<details>
<summary>Screenshot of entire page using Edge Web Capture</summary>

![screenshot of the current page contents with red-dashed outline around incomplete instructions](https://user-images.githubusercontent.com/5055400/136499119-92a56229-9b1b-46c0-a349-a01a2df10ca5.png)

</details>

### What changes are you suggesting?

When OpenSSH is [installed using the Settings](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) (Window 10 build 1809 and later; or Windows Server 2019), the `ssh-agent` runs as a background system service rather than returning a stringified batch script that needs to be `eval`'d.

See also [2019 update to top answer on "How to run ssh-add on windows?"](https://stackoverflow.com/questions/18683092/how-to-run-ssh-add-on-windows#:~:text=Update%202019%20-%20A%20better%20solution%20if%20you%27re%20using%20Windows%2010%3A%20OpenSSH%20is%20available%20as%20part%20of%20Windows%2010%20which%20makes%20using%20SSH%20from%20cmd/powershell%20much%20easier%20in%20my%20opinion.%20It%20also%20doesn%27t%20rely%20on%20having%20git%20installed%2C%20unlike%20my%20previous%20solution.)

This means that the status quo instructions promoting either `eval $(ssh-agent -s)` or `eval "$(ssh-agent -s)"` will not work for some users, but will also not provide useful output. For me, either above command does nothing in PowerShell or cmd.

### Additional information

A succinct emendation is to recommend `Get-Service -Name ssh-agent | Get-Process` in a PowerShell host to find the `ssh-agent` process ID.

A more detailed suggestion is to walk the reader through scrupulously determining what is providing `ssh-agent`, if anything.

--- 
edited by maintainer.
### Content Plan
Here is the [writer's review](https://github.com/github/docs/issues/10967#issuecomment-952931722) for this issue.

**Comment by billybob3659** [comment]
Tweaker tweaker 1 9erOn Oct 8, 2021 2:58 PM, "welcome[bot]" ***@***.***> wrote:
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the contributing guidelines.

**Comment by samichycombd** [comment]
[](url)facebook.com/SamiChyBD

**Comment by samichycombd** [comment]
facebook.com/SamiChyBD

**Comment by Anika-Roy** [comment]
Hi! Im participating in Hacktoberfest and I'd like to know if this issue is counted in Hacktoberfest and if I can work on it?

**Comment by admin-01-web** [comment]
`https://youtu.be/ggoJFaE71W8`
+admin-01-web/1-md-
[mailer-daemon@googlemail.com]
@admin-01-web/1-md
+14582322679

**Comment by admin-01-web** [comment]
> wave @Anika-Roy - Feel free to work on any of our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues for Hacktoberfest! jack_o_lantern

https://github.com/github/docs/issues/10967#comment-1319748668

**Comment by admin-01-web** [comment]
@mavaddat

**Comment by Antanukumar** [comment]
i want to work on this issues please assign me this issues

**Comment by babarmeer** [comment]
> i want to work on this issues please assign me this issues

**Comment by cmwilson21** [comment]
👋 @Antanukumar - You or anyone else are welcome to submit a PR for this issue 👍

**Comment by ashutosh887** [comment]
Let me work on this @mavaddat

**Comment by cmwilson21** [comment]
@ashutosh887 You or anyone else are welcome to work on this ⚡

**Comment by Book56** [comment]
How to fix cookies and get identity fast

**Comment by belindabithell** [comment]
hi , please let me work on this as it my first go on docks @mavaddat

**Comment by cmwilson21** [comment]
@belindabithell You, or anyone else, are welcome to work on this issue ⚡ 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

**Comment by arjunsingh27** [comment]
Can you please do me a favor? As I am a beginner, I understand everything, but I am not able to distinguish what to do. Could you please explain to me what I need to do or provide me with any references that I can read and understand.

**Comment by belindabithell** [comment]
hi
I am a beginner as well and i feel very lost . I am trying to teach myself
but at times like today ...i am not sure where to start .I think we are in
the same boat . please help me as well, if you can.

**Comment by ashutosh887** [comment]
> @ashutosh887 You or anyone else are welcome to work on this ⚡

@cmwilson21 Is there a public channel to discuss with the team regarding my approach/any difficulty

**Comment by mavaddat** [comment]
@ashutosh887 You can seek help or discuss your efforts on the discussions forum: https://github.com/github/docs/discussions

Note that the purpose of [GitHub Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) is to notify the developers of problems with their product or project. If you're seeking advice for how to implement a solution or learn how to accomplish a task, that's not typically [what GitHub issues is intended to address](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde).
You may also try posting your question on a site like [Stackoverflow](https://stackoverflow.com/questions/tagged/github), [Quora](https://www.quora.com/topic/GitHub?q=github) or [Reddit r/learnprogramming](https://www.reddit.com/r/learnprogramming).

**Comment by ashutosh887** [comment]
I completely agree to you @mavaddat 
Will surely check them soon

**Comment by cmwilson21** [comment]
👋 Hey @ashutosh887, @mavaddat is correct! You can also begin your PR, submit it (could also submit as a draft if you prefer), and ask any questions in your PR. A lot of questions get answered during the review process. 👍
