### ISSUE TITLE
A space should be added after a dot

### ISSUE THREAD

**Issue by gaoyaoxin** [github/docs#1099]
### What article on docs.github.com is affected?

[Managing a custom domain for your GitHub Pages site](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site)

### What part(s) of the article would you like to see updated?

For a better format, there should be a space after the dot that sentence "For more information about how to create the correct record, see your DNS provider's documentation." ends with.

### Additional information

![dot](https://user-images.githubusercontent.com/20694974/98328028-cd9b7080-202f-11eb-8daf-a6f62ec53417.png)

**Comment by gaoyaoxin** [comment]
Pull request opened as #1100.

**Comment by mchammer01** [comment]
Closing this issue as I've now merged the related [PR](https://github.com/github/docs/pull/1100).
Thanks again 👍🏻
