### ISSUE TITLE
Explicit mention of having to use the baptiste preview

### ISSUE THREAD

**Issue by fenske** [github/docs#1104]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#update-a-repository

### What part(s) of the article would you like to see updated?

An explicit mention for when passing the `is_template` parameter, the `baptiste` mediaType has to be used.

### Additional information

I know that it's specified at the very top of the page, but at first, I didn't manage to find it (I assume I'm not alone). Even had to create https://github.com/octokit/rest.js/issues/1931 to get help. 😅

**Comment by janiceilene** [comment]
Thanks for opening an issue @fenske! I'll triage this for someone to take a look at 👀

**Comment by lucascosti** [comment]
Thanks for opening this issue, @fenske! Yep, a mention of the preview header in the parameter description would be helpful. Our API docs are sourced directly from the API code, so we'll have to update this internally 👍

**Comment by janiceilene** [comment]
This is being tracked internally, so I'm going to close this issue! Thanks so much 💖
