### ISSUE TITLE
Missing documentation for `head_ref_force_pushed` issue event

### ISSUE THREAD

**Issue by Fs00** [github/docs#11129]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types

### What part(s) of the article would you like to see updated?

In the responses returned by the _Timeline events_ and _Issue events_ APIs for PRs that have been force-pushed, events of type `head_ref_force_pushed` can be found. However, this kind of event is not documented in the Issue event types page.

### Additional information
---
edited  by maintainer:
Here is [the writer's review](https://github.com/github/docs/issues/11129#issuecomment-964596043) for this issue.

**Comment by linodejesusmonarrazliz** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types
> 
> ### What part(s) of the article would you like to see updated?
> In the responses returned by the _Timeline events_ and _Issue events_ APIs for PRs that have been force-pushed, events of type `head_ref_force_pushed` can be found. However, this kind of event is not documented in the Issue event types page.
> 
> ### Additional information
> _No response_

https://github.com/github/docs/issues/11129#issue-1023999560

**Comment by linodejesusmonarrazliz** [comment]
Servicio.linode.com

**Comment by linodejesusmonarrazliz** [comment]
Es algo nuebo e inobador

**Comment by skedwards88** [comment]
Thank you for opening this issue! You or anyone else is welcome to open a PR to add the `head_ref_force_pushed` to https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types.

**Comment by IMPranshu** [comment]
I have made PR #14910. Please check and suggest changes.
