### ISSUE TITLE
npm's documentation site is not linked to from docs.github.com

### ISSUE THREAD

**Issue by ethomson** [github/docs#11159]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[GitHub Documentation](https://docs.github.com/)

### What part(s) of the article would you like to see updated?

The navigation / links to external sites should include [docs.npmjs.com](https://docs.npmjs.com).

**Comment by danBamikiya** [comment]
@ethomson is this up for contributing to? I'll love to contribute to this!
