### ISSUE TITLE
Redundant Section for PR Forks in [Learn Github Actions / Events That Trigger Workflows]

### ISSUE THREAD

**Issue by MattRudy** [github/docs#11212]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows

### What part(s) of the article would you like to see updated?

redundant sections should be removed to improve clarity of documentation for readers.

### Additional information

![image](https://user-images.githubusercontent.com/42589600/137593877-8c31b58f-1ba7-4905-812b-136ff80fb0ee.png)

**Comment by ramyaparimi** [comment]
@MattRudy Closing this issue as this is being [addressed internally](https://github.com/github/docs/pull/11213#issuecomment-946676299).

Thanks so much for your passion in contributing to the GitHub docs 💖
