### ISSUE TITLE
GitHub Actions YAML should be placed under workflows directory (not workflow) [Building and testing Python]

### ISSUE THREAD

**Issue by ftnext** [github/docs#11236]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Building and testing Python](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py)

### What part(s) of the article would you like to see updated?

The path `.github/workflow/example.yml` seems wrong.

![image](https://user-images.githubusercontent.com/21273221/137620027-d5e85543-4c93-4795-9b9b-c80ddc6acb8c.png)

The path should be `.github/workflows/example.yml`.

In body:
>To get started quickly, add the template to the .github/workflows directory of your repository.

### Additional information

In Node.js tab, there is no need to change.

![image](https://user-images.githubusercontent.com/21273221/137620019-c32da935-5201-42f6-9612-37b0509a16af.png)

**Comment by skedwards88** [comment]
Thank you for catching this! You are correct that the path should be `.github/workflows`. You or anyone else is welcome to open a PR to address this.
