### ISSUE TITLE
Use HTML kbd tag for keyboard information

### ISSUE THREAD

**Issue by volkantash** [github/docs#11237]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Selâm ola (Hi).

Şu örkteki yazıda tuşlar için **HTML code** kullanıldığını gördüm. (I saw that **HTML code** is used for keys in the article at this link.)
https://docs.github.com/en/issues/trying-out-the-new-projects-experience/customizing-your-project-views

### What part(s) of the article would you like to see updated?

HTML code yerine HTML kbd kullanılması gerekiyor (HTML kbd should be used instead of HTML code).

Bilgi için (For information)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd

### Additional information

Ayrıca bu etiket CSS ile özelleştirilerek başka görünüşlere büründürülebilir (In addition, this tag can be customized with CSS to take on other appearances).

Teşekkürler (Thanks).

---
Edited by maintainer. Check out [this comment](https://github.com/github/docs/issues/11237#issuecomment-967567942) for a writer's review on this issue.

**Comment by ramyaparimi** [comment]
@volkantash 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by heiskr** [comment]
I don't think there's a way to use <kbd> in markdown other than the keys. I don't think this change is necessary personally, but that would be a content decision.

**Comment by volkantash** [comment]
Örnek için (For example)
![resim](https://user-images.githubusercontent.com/25375593/139723062-e1380b38-a65e-4f2c-931a-35e8dcce0cc9.png)

**Comment by lecoursen** [comment]
Thanks @volkantash! We do use `<kbd>` in "[Keyboard shortcuts](https://docs.github.com/en/get-started/using-github/keyboard-shortcuts)" and we could use that tag in this article, too, with the existing styling. However, we won't be updating the CSS for this issue. You or anyone else is welcome to open a PR making that change.

**Comment by P-DUBB** [comment]
Haimstjyeboykn

**Comment by nguoithulinh2021** [comment]
lequangtrung.200691@gmail.com

**Comment by AnilSeervi** [comment]
This issue was closed in d8979e5c37cb1d96eb69ab6da3bbc3c645360dbb #13908.
@ramyaparimi, You can close this issue now.
