### ISSUE TITLE
Elaborate on concurrency in GitHub actions

### ISSUE THREAD

**Issue by kristof-mattei** [github/docs#11374]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency

### What part(s) of the article would you like to see updated?

I am dealing with a situation of both concurrency and integrity. 

Assume a workflow with 4 actions:

* checkout
* set up dependencies
* build container
* push container

These run in a nice chain, as multiple jobs.

This workflow runs on `pull_request`. So every commit on a branch that is a PR triggers a new container to be built.

That container is then tagged with `pr-<number>-latest`, so that tag constantly moves to the latest version of the built of that PR.

Now, we have a PR open, number 3. 

We do a commit, which triggers the workflow, which we'll call workflow run A. We spot a non-build-breaking error and, change our code, and push a second commit, which triggers the workflow, this time workflow run B.

So we can do concurrency at the level of the workflow itself, which protects us from B ever finishing before A.

But how does it work when we do concurrency at an individual job level? When does it get evaluated? 

Let's look at our same flow again, but we move the concurrency to the level of `push container`.

So we have our new PR, number 4.

We do a commit, which triggers the workflow, workflow run A. We spot that non-build-breaking erroro again and we change our code, and push another commit, triggering workflow run B.

Now, because of some flaw in some external dependency the build part of workflow run A takes significantly longer, so that workflow run B actually builds and pushes BEFORE workflow run A. 

So going back to that concurrency at a **job** level:

Does it get checked when the **job** starts and it checks for same-named siblings?
Or does it also take in account the order in which they're added to the **workflow** queue?

**Comment by skedwards88** [comment]
Thank you for opening this detailed issue! 

> So going back to that concurrency at a job level:
> Does it get checked when the job starts and it checks for same-named siblings?
> Or does it also take in account the order in which they're added to the workflow queue?

I believe that a job using concurrency will not start if there is already a job/workflow in progress that uses the same concurrency group. Instead, the job will be paused and have the status pending. Additionally, if there is also a job pending in the same concurrency group, that job will be canceled. So you will have a maximum of one running and one pending job within the concurrency group. 

Does this answer your question? We recently added new docs about concurrency here: https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions#using-concurrency Let us know if you think we should add more details or examples to that article.
