### ISSUE TITLE
Improve table for Understanding the search syntax, exclude certain results

### ISSUE THREAD

**Issue by HonkingGoose** [github/docs#11396]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#exclude-certain-results

## Current table

Copy/pasted from source file: [^source]

Query  | Example
------------- | -------------
<code>-<em>QUALIFIER</em></code>  | **[cats stars:>10 -language:javascript](https://github.com/search?q=cats+stars%3A>10+-language%3Ajavascript&type=Repositories)** matches repositories with the word "cats" that have more than 10 stars but are not written in JavaScript.
 | **[mentions:defunkt -org:github](https://github.com/search?utf8=%E2%9C%93&q=mentions%3Adefunkt+-org%3Agithub&type=Issues)** matches issues mentioning @defunkt that are not in repositories in the GitHub organization

## Expected table

I was expecting the second row to look similar to this:

Query  | Example
------------- | -------------
<code>-<em>QUALIFIER</em></code>  | **[cats stars:>10 -language:javascript](https://github.com/search?q=cats+stars%3A>10+-language%3Ajavascript&type=Repositories)** matches repositories with the word "cats" that have more than 10 stars but are not written in JavaScript.
 | `mentions:defunkt -org:github` | matches issues mentioning @defunkt that are not in repositories in the GitHub organization

[^source]: https://github.com/github/docs/blob/main/content/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax.md

## Added by maintainer

These are two examples of the same qualifier, with a missing ` | ` which is messing up the formatting. We don't need two examples, and the `mentions:defunkt -org:github` example is a little simpler and more accessible,  so let's keep that one, moving it to where the `cats stars:>10 -language:javascript` example was, and remove the bottom row of the table.

**Comment by jules-p** [comment]
Thanks for opening this @HonkingGoose, you're right that this needs to be updated ✨ I've made an edit to the OP with a summary of what to change, you (or anyone else) is welcome to open a PR to address that change. Thank you 🎉

**Comment by HonkingGoose** [comment]
Thank you for the edit! I'll let somebody else fix this with a pull request.

**Comment by AnilSeervi** [comment]
Opened #11894 with the suggested changes by the maintainer.
