### ISSUE TITLE
Mention gh_color_mode for directly uploaded images?

### ISSUE THREAD

**Issue by ramyaparimi** [github/docs#11491]
### Discussed in https://github.com/github/docs/discussions/11479

<div type='discussions-op-text'>

<sup>Originally posted by **Andre601** October 27, 2021</sup>
Just recently discovered that you can append `gh_color_mode=light` or `gh_color_mode=dark` to a githubusercontent.com hosted image to only show it while the user is using the respective mode.

I feel like this should be mentioned in the docs somewhere, probably under the markdown syntax docs in the images section, so that people are aware of it.</div>

---
Edited by maintainer. Here is [the writer's review](https://github.com/github/docs/issues/11491#issuecomment-954984572) for this issue.

**Comment by lecoursen** [comment]
I agree that "[Basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images)" is the best place to document this!

**Comment by shreya024** [comment]
I would like  to work on this issue. Kindly assign

**Comment by ramyaparimi** [comment]
@shreya024 we generally don't assign issues. You are welcome to open a PR to an issue you would like to work one ✨ .

**Comment by stevecat** [comment]
As I mentioned in [the linked PR](https://github.com/github/docs/pull/16266#issuecomment-1082780564), it looks like this feature has already been documented since this issue was opened. I'm sorry for the confusion (and extra sorry to @shreya024 for the work put in!)
