### ISSUE TITLE
github-command-palette.md is missing from the repository

### ISSUE THREAD

**Issue by FahimFBA** [github/docs#11525]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

## github-command-palette.md is missing from the repository: main/content/get-started/using-github/

I want to make some changes (starting from typo to some editing) by contributing to GitHub Docs, but whenever I try to by using the `Make a contribution` button, a new tab appears saying that the Page can not be found. I manually went to the GitHub docs repo and didn't find the readme file either. I want to contribute to [this](https://docs.github.com/en/get-started/using-github/github-command-palette). 

### What part(s) of the article would you like to see updated?

I want `github-command-palette` to be updated, I mean, it should exist so that we can check and make contributions also. The github-command-palette.md should have been placed within the following directory:
https://github.com/github/docs/edit/main/content/get-started/using-github/github-command-palette.md
But this markdown file doesn't exist anymore although the docs site is still visible here: https://docs.github.com/en/get-started/using-github/github-command-palette

I want to fix typo from Linx to Linux first, and then I would try to change the `ctl` button to `Ctrl` 

### Additional information

I hope that it would be fixed soon. Thanks for the amazing works you all are doing for us.

**Comment by Gara312** [comment]
> ### Нормы поведения
> * [x] Я прочитал и согласен с [Кодексом поведения](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md) проекта GitHub Docs[](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### Какая статья на docs.github.com затронута?
> ## github-command-palette.md отсутствует в репозитории: main / content / get-start / using-github /
> Я хочу внести некоторые изменения (от опечатки до некоторого редактирования), внося свой вклад в GitHub Docs, но всякий раз, когда я пытаюсь сделать это с помощью `Make a contribution`кнопки, появляется новая вкладка, в которой говорится, что страница не может быть найдена. Я вручную зашел в репозиторий документации GitHub и не нашел файла readme. Я хочу внести в [это](https://docs.github.com/en/get-started/using-github/github-command-palette) свой вклад .
> 
> ### Какие части статьи вы хотели бы видеть обновленными?
> Я хочу `github-command-palette`быть в курсе, я имею в виду, он должен существовать, чтобы мы также могли проверять и вносить вклад. Github-command-palette.md должен был быть помещен в следующий каталог: https://github.com/github/docs/edit/main/content/get-started/using-github/github-command-palette.md Но этого файла уценки больше не существует, хотя сайт документации все еще виден здесь: https://docs.github.com/en/get-started/using-github/github-command-palette
> 
> Сначала я хочу исправить опечатку из Linx в Linux, а затем я попробую изменить `ctl`кнопку на`Ctrl`
> 
> ### Дополнительная информация
> Надеюсь, что скоро это исправят. Спасибо за прекрасную работу, которую вы все делаете для нас.

**Comment by Gara312** [comment]
> > ### Нормы поведения
> > 
> > * [x] Я прочитал и согласен с [Кодексом поведения](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md) проекта GitHub Docs
> > 
> > ### Какая статья на docs.github.com затронута?
> > ## github-command-palette.md отсутствует в репозитории: main / content / get-start / using-github /
> > Я хочу внести некоторые изменения (от опечатки до некоторого редактирования), внося свой вклад в GitHub Docs, но всякий раз, когда я пытаюсь сделать это с помощью `Make a contribution`кнопок, появляется новая вкладка, в которой говорится, что страница не может быть найдена. Я вручную зашел в репозиторий документации GitHub и не нашел файла readme. Я хочу внести в [это](https://docs.github.com/en/get-started/using-github/github-command-palette) свой вклад.
> > ### Какие части статьи вы хотели бы видеть обновленными?
> > Я хочу `github-command-palette`быть в курсе. Github-command-palette.md должен быть помещен в следующий каталог: https://github.com/github/docs/edit/main/content/get-started/using-github/github-command-palette.md Но этого файла уценки больше не существует, хотя сайт документации все еще виден здесь: https://docs.github.com/en/get-started/using-github/github-command-palette
> > Сначала я хочу исправить опечатку из Linx в Linux, а затем я попробую изменить `ctl`кнопку на`Ctrl`
> > ### Дополнительная информация
> > Надеюсь, что скоро это исправят. Спасибо за прекрасную работу, которую вы все делаете для нас.

**Comment by Gara312** [comment]
> @FahimFBA Большое спасибо за открытие выпуска! Я отсортирую это, чтобы команда посмотрела👀



> > @FahimFBA Большое спасибо за открытие выпуска! Я отсортирую это, чтобы команда посмотрела👀
> 
> Большое спасибо! Я с нетерпением жду этого!👀

**Comment by mchammer01** [comment]
@FahimFBA 👋🏻 - Thanks for creating this issue, and thanks for noticing these typos ✨ 
You are right, the file seems to be missing from the repository.

The source file should be in this directory but it's not: https://github.com/github/docs/tree/main/content/get-started/using-github

Let me investigate as we, GitHub Docs writers, make our contributions to an internal repo, and the `github/docs` repo in turn, gets synced with that repo. Perhaps there's an issue with the sync.

**Comment by mchammer01** [comment]
UPDATE: there's an issue with the repo sync, and this is currently being looked at. Thank you in advance for your patience 🙇🏻

**Comment by mchammer01** [comment]
@FahimFBA 👋🏻 - just to let you know that the repo sync happened and that the file is now in the repo.
Feel free to raise a PR with the typo fixes at your convenience, and thanks for your patience ✨

**Comment by FahimFBA** [comment]
Thanks a bunch, @mchammer01!

**Comment by FahimFBA** [comment]
I have made a pull request. Please let me know about that after checking that out! Thanks!

**Comment by Luiskiing** [comment]
OK.  Well.  How do you listen?  Listen, I listen problem.
