### ISSUE TITLE
Language menu hidden with the main part scrolled

### ISSUE THREAD

**Issue by noritada** [github/docs#11547]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en
(This is just one URL. I can observe all the articles that have a language menu as far as I checked.)

Brave browser 1.31.87 Chromium: 95.0.4638.54 (Official Build) (x86_64)
![ss 2021-10-30 23 10 17](https://user-images.githubusercontent.com/20850/139536579-57049626-1cc8-4594-8d56-9734420382ab.png)
![ss 2021-10-30 23 10 35](https://user-images.githubusercontent.com/20850/139536581-1710b1c8-1501-4c9a-aa3f-8db5beba1035.png)

Firefox 93.0 (x86_64)
![ss 2021-10-30 23 18 16](https://user-images.githubusercontent.com/20850/139536696-aae195c3-d3d5-4555-95d3-218f01f7f90c.png)
![ss 2021-10-30 23 18 25](https://user-images.githubusercontent.com/20850/139536702-22890722-7ddf-4bb5-913e-3d208d8b7c7c.png)

### What changes are you suggesting?

Currently behavior:
- When we don't scroll the main part, the language menu displays properly.
- When we scroll the main part, the language menu gets hidden.
- Opening the menu and then scrolling the document, or opening the menu after scrolling the document, does not change the behavior.

Expected behavior:
- The language menu displays properly whenever we scroll the main part or not.

Reason:
- I think current behavior is not expected by everyone.

**Comment by AnilSeervi** [comment]
`clip-path` property is being added on scroll-down to the header with value of `inset(-5px -5px -5px 0)`.
Taking off that property fixes it.

**Comment by heiskr** [comment]
The engineering team has a fix in queue.

**Comment by noritada** [comment]
Thank you for your response earlier in the week.

I just checked again with the browsers that I used to observe the problem, and it seems to be working properly.
Now I think this issue can be closed.
