### ISSUE TITLE
"macOS" should always be properly capitalized

### ISSUE THREAD

**Issue by stephenwade** [github/docs#1155]
### What article on docs.github.com is affected?

This affects several articles and one reusable note:

- [About actions](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions)
- [About self-hosted runners](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners)
- [Specifications for GitHub-hosted runners](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners)
- [Running CodeQL code scanning in a container](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/running-codeql-code-scanning-in-a-container)
- [Running CodeQL code scanning in your CI system](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/running-codeql-code-scanning-in-your-ci-system)
- [macos-runner-preview.md](https://github.com/github/docs/blob/main/data/reusables/github-actions/macos-runner-preview.md)

### What part(s) of the article would you like to see updated?

The name of Apple's desktop operating system should always be capitalized with a lowercase "m", like this:

> macOS

You can see this on Apple's website: [macOS Catalina](https://www.apple.com/macos/catalina/)

**Comment by brijeshchaudhary44** [comment]
`Bajram leading Brand `

**Comment by brijeshchaudhary44** [comment]
bajram leading Brand

**Comment by janiceilene** [comment]
Thanks @stephenwade! Anyone is welcome to open a PR and fix this one 👍

**Comment by stephenwade** [comment]
Sorry, I should have linked it in the issue description! I already opened https://github.com/github/docs/pull/1154 to fix this.
