### ISSUE TITLE
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by Philetran** [github/docs#11563]
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

_Originally posted by @welcome[bot] in https://github.com/github/docs/issues/11536#issuecomment-955095011_

**Comment by Philetran** [comment]
IT construction support

**Comment by Philetran** [comment]
:1st_place_medal:

**Comment by wesley31326** [comment]
@
