### ISSUE TITLE
Content viewing(PT) impaired on mobile devices

### ISSUE THREAD

**Issue by GabrielDSRodrigues** [github/docs#11568]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/pt and most if not all pages in pt.

![IMG_20211031_203928](https://user-images.githubusercontent.com/66338281/139605304-de464cb5-052e-4b09-8cf6-c5e2d2c2d963.jpg)

### What changes are you suggesting?

**• Details and Possible Improvements** 
The documents in pt have a broad description (the one presented above) which makes it difficult to view on mobile devices, it would be better if it were not fixed, so that if the user scrolls down the page, the description disappears.

**Comment by ramyaparimi** [comment]
@GabrielDSRodrigues 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by heiskr** [comment]
Engineering wouldn't be able to edit the string as we don't have a Portuguese speakers, we'll need our localization team to take a look.

**Comment by ramyaparimi** [comment]
@GabrielDSRodrigues 
Thanks for opening this issue! Unfortunately, we are not able to accept issues for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
