### ISSUE TITLE
The DEPLOYMENT section in the GitHub Actions cannot expand

### ISSUE THREAD

**Issue by SIkebe** [github/docs#11573]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.2/actions/deployment/about-deployments/about-continuous-deployment

### What part(s) of the article would you like to see updated?

When you select `Enterprise Server *` article version, you cannot expand the `DEPLOYMENT` section in the GitHub Actions docs. If you enter the url directly, you can see the page, though.

### Additional information

![deployment](https://user-images.githubusercontent.com/17608272/139625387-212eb7f2-768e-4eeb-913a-8cb2e2fa5b08.gif)

**Comment by ramyaparimi** [comment]
@SIkebe 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by heiskr** [comment]
We've made an issue to track this in our engineering backlog.

**Comment by ramyaparimi** [comment]
@SIkebe I am going to close this issue now as this is being tracked by an internal issue 💛 

Thanks so much for taking your time in contributing to the GitHub docs 💖
