### ISSUE TITLE
Impro

### ISSUE THREAD

**Issue by use931** [github/docs#1157]

**Comment by nicolepigg2** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).
>

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
