### ISSUE TITLE
Additional TOTP options

### ISSUE THREAD

**Issue by bkmgit** [github/docs#11603]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication

### What part(s) of the article would you like to see updated?

Need to add additional TOTP options

### Additional information

https://github.community/t/two-factor-authentication-without-mobile-phone/150738

**Comment by bkmgit** [comment]
@ramyaparimi Will there be any action taken on this? The rationale for the recommendations are unclear.

**Comment by ramyaparimi** [comment]
@bkmgit I apologize for the delay in responding to this issue. This list of TOTP recommendations is maintained by our security team, and we don't accept outside additions 💛 

Thanks so much for your time in contributing to our docs 💖
