### ISSUE TITLE
OIDC cloud-specific docs are missing environment variables

### ISSUE THREAD

**Issue by aripollak** [github/docs#11620]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

### What part(s) of the article would you like to see updated?

In the "Requesting the access token" section, the places that use environment variables just show `$` instead of the actual environment variables, like:
`          aws-region: $`
should show
`          aws-region: ${{ env.AWS_REGION }}`

**Comment by PythonInc2021** [comment]
#10017

**Comment by ramyaparimi** [comment]
@aripollak 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Kelventri** [comment]
> Gracias por abrir este número. Un miembro del equipo de documentos de GitHub debería estar cerca para enviar comentarios pronto. Mientras tanto, consulte las [pautas de contribución](https://github.com/github/docs/blob/main/CONTRIBUTING.md) .

**Comment by hubwriter** [comment]
@aripollak - Thanks for raising this issue.
This has been fixed now.
