### ISSUE TITLE
Inconsistency between SCIM support

### ISSUE THREAD

**Issue by meckhardt** [github/docs#11639]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[About identity and access management for your enterprise](https://docs.github.com/en/enterprise-cloud@latest/admin/authentication/managing-identity-and-access-for-your-enterprise/about-identity-and-access-management-for-your-enterprise#about-identity-and-access-management-for-your-enterprise) states

![grafik](https://user-images.githubusercontent.com/827666/140076632-53f9fe39-83ae-4245-9e55-db057a54e8b9.png)

[Managing team synchronization for organizations in your enterprise](https://docs.github.com/en/enterprise-cloud@latest/admin/authentication/managing-identity-and-access-for-your-enterprise/managing-team-synchronization-for-organizations-in-your-enterprise) states

![grafik](https://user-images.githubusercontent.com/827666/140076701-24a107ea-df97-4263-bbc0-882510df91e9.png)

What is correct?

Kind Regards,
Martin

### What part(s) of the article would you like to see updated?

See screens. What is the current SCIM support für Enterprise Accounts with Enterprise Managed Users? 

SCIM available for Enterprise Accounts and required for AAD Group / GH Teams synchronization? This is sth. that the _Enterprise Managed Users_ does not support?

---
Edited by maintainer. 

Here is the [content design plan](https://github.com/github/docs/issues/11639#issuecomment-974497080) for this issue by a writer.

**Comment by Ashrfmoh** [comment]
Hi

**Comment by Ashrfmoh** [comment]
Hvf

**Comment by Ashrfmoh** [comment]
> Hi

**Comment by Ashrfmoh** [comment]
https://github.com/github/docs/issues/11639#issuecomment-959735014

**Comment by Ashrfmoh** [comment]
B

**Comment by Ashrfmoh** [comment]
B

**Comment by ramyaparimi** [comment]
@meckhardt 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @meckhardt! SCIM support for enterprise accounts was only added recently and only if your enterprise is enabled for Enterprise Managed Users. We can update the sentence you reference in "About identity and access management for your enterprise" to clarify that SCIM is not available for non-EMU SAML, and potentially link to the "About Enterprise Managed Users" section below. You or anyone else is welcome to create a PR doing so!
