### ISSUE TITLE
Inconsistencies with security and analysis feature toggle docs

### ISSUE THREAD

**Issue by anweiss** [github/docs#11637]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-security-and-analysis-settings-for-your-repository#enabling-or-disabling-security-and-analysis-features-for-public-repositories

### What part(s) of the article would you like to see updated?

The screenshot in Step 4 shows that it's possible to disable secret scanning for public repos, however the Note in the blue box at https://docs.github.com/en/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories says that "Secret scanning is enabled by default on public repositories and cannot be turned off". As such, this same note should also be added to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-security-and-analysis-settings-for-your-repository#enabling-or-disabling-security-and-analysis-features-for-public-repositories and the screenshot should be corrected to properly depict this configuration page.

**Comment by ramyaparimi** [comment]
@anweiss 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by ramyaparimi** [comment]
@anweiss Thank you for opening this issue. This has to be fixed internally. I transferred this issue to an internal repo so, I am going to close this now 💛

**Comment by samiramiri88** [comment]
ok fij cool
