### ISSUE TITLE
The jobs.*.runs-on documentation seems incomplete

### ISSUE THREAD

**Issue by mpalmer** [github/docs#11729]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The [description of `jobs.*.runs-on` in the main article on workflow syntax](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on) reads, to me at least, as though the valid forms for `runs-on` are either:

1. a string, being one of the names of a GitHub-provided runner; or
2. an array, whose first element is the string `self-hosted`, followed by other arbitrary strings.

All of the examples I can find in the other pages relating to labels on self-hosted runners appear to follow this specification.

### What changes are you suggesting?

I would appreciate it if the documentation matched observed behaviour, describing what the *actual* requirements are for the `runs-on` field, so that the validation tool I maintain can accurately detect valid and invalid syntax.  From what I've seen, the valid syntax appears to be "any arbitrary string or array of strings", but I'm extrapolating from a very limited set of data points, as I don't use self-hosted runners myself.

### Additional information

I maintain a tool which [validates GitHub workflows against a JSON schema](https://github.com/mpalmer/action-validator) (amongst other checks), and I recently received [a bug report](https://github.com/mpalmer/action-validator/issues/5) that workflows that GitHub accepts as valid were being rejected by my tool, because the `runs-on` specification doesn't match the documented syntax.

As far as I can tell, the bug report is valid, insofar as [a workflow that does not match the published documentation](https://github.com/mathew-fleisch/github-actions-runner/blob/main/.github/workflows/build-container.yaml) does, indeed, appear to be accepted by GitHub and [run successfully](https://github.com/mathew-fleisch/docker-dev-env/runs/4069394685?check_suite_focus=true).

**Comment by ramyaparimi** [comment]
@mpalmer 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by mathew-fleisch** [comment]
Hey there @ramyaparimi I was the one that initially filed the bug report to @mpalmer
Please let me know if there is any other information I can give about this issue.

**Comment by lucascosti** [comment]
Hi @mpalmer! Thanks for letting us know about this. It looks like these docs were written for how we would want users to use this key, rather than what's possible. I agree that this isn't great, and I'll open a PR to fix what is the required syntax vs what we recommend for users.

**Comment by lucascosti** [comment]
PR opened: https://github.com/github/docs/pull/12504

**Comment by mathew-fleisch** [comment]
Hey @lucascosti thanks for looking into this. I'm still a little confused... If I have two self-hosted runners tied to the same repository, and I want to install different dependencies on each runner, I have been using the ['labels' parameter](https://github.com/mathew-fleisch/github-actions-runner/blob/main/entrypoint.sh#L72) in the entrypoint of my runners when spinning them up, to give each runner a unique label. Then I'll use those unique labels in the ['runs-on' section](https://github.com/mathew-fleisch/linter-runner/blob/main/.github/workflows/build-container.yaml#L14) of an action that I want to run on a self-hosted runner. If the desired functionality is to use self-hosted as a label, would I use both self-hosted and my custom label in the runs-on array? Is that array being evaluated as an OR or an AND between these values?

For instance, I'll have a runner with only linting tools that is small and light weight, and another runner dedicated to building containers that will have any and all tools my jobs might need.

**Comment by ethomson** [comment]
Hi @mathew-fleisch!  It's an AND.

All of your runners implicitly have a `self-hosted` label added to them.  You can add additional unique labels to your runners when you configure them.

The GitHub hosted runners will never have `self-hosted`, so if you want to target _any_ self-hosted runner, regardless of configuration, you can specify only `runs-on: self-hosted`.  This is really only useful if you have a single set of runner types, maybe even just a single runner, and you want to run your workflows on it.

You can also specify `runs-on: [ self-hosted, custom ]` to run on any self-hosted runner with the `custom` label (IOW, both the `self-hosted` AND `custom` labels).

**Comment by mathew-fleisch** [comment]
Sweet. thanks for the clarification. I'll give that syntax a try!

**Comment by mathew-fleisch** [comment]
Thanks @lucascosti I have confirmed this syntax works to isolate specific self-hosted runners by label.
@mpalmer This syntax also passes the action-validator 🎉
