### ISSUE TITLE
Use correct capitalization for PowerShell

### ISSUE THREAD

**Issue by skedwards88** [github/docs#11811]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All articles that use the word "Powershell" or "powershell".

### What part(s) of the article would you like to see updated?

As pointed out in [this issue](https://github.com/github/docs/issues/11336), the correct capitalization is "PowerShell" (P and S both capitalized).

**Comment by Febby14** [comment]
Code

**Comment by Febby14** [comment]
Money
