### ISSUE TITLE
composite example does not run in Windows

### ISSUE THREAD

**Issue by robert-s-lee** [github/docs#11849]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

### What part(s) of the article would you like to see updated?

[Creating an action metadata file
](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file) works for ubunut and mac.  For windows, `/` does not work.

suggest the following change:
```
        - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
          shell: bash          
        - run: goodbye.sh
          shell: bash
```

**Comment by ramyaparimi** [comment]
@robert-s-lee 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by hubwriter** [comment]
@robert-s-lee - Thank for raising this issue. I agree, your suggested change would avoid using the forward slash so would be usable across the OSs.

The change required is, therefore, as follows.

On lines 87-88 of the docs file `content/actions/creating-actions/creating-a-composite-action.md`, change:

```
- run: ${{ github.action_path }}/goodbye.sh
  shell: bash

```

to:
```
- run: echo "${{ github.action_path }}" >> $GITHUB_PATH
  shell: bash          
- run: goodbye.sh
  shell: bash
```

**Comment by kum9748ar** [comment]
Hi, can I get started with this issue

**Comment by Jackieg81710** [comment]
Ok. Patients people. I see what to do. I'm doing more than one thing. And learning everything on my own.

**Comment by VDNGDK** [comment]
Can i givr some help on this?

**Comment by lilcuteboy43** [comment]
Can y'all help me and update my
Profile

**Comment by hubwriter** [comment]
@kum9748ar 

> Hi, can I get started with this issue

Please do! 🙇‍♂️

**Comment by allprogrammers** [comment]
Hello, Can I please work on this?

**Comment by ramyaparimi** [comment]
@allprogrammers One of the writers reviewed and suggested a change for this issue in [this comment](https://github.com/github/docs/issues/11849#issuecomment-997974652). You can follow this writer's review to open a PR with a fix ✨
