### ISSUE TITLE
Recommend `gradle/gradle-build-action` for invoking Gradle in GitHub Actions

### ISSUE THREAD

**Issue by bigdaz** [github/docs#11875]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
- https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle

### What part(s) of the article would you like to see updated?

These 2 articles invoke Gradle directly. The Gradle team provides https://github.com/marketplace/actions/gradle-build-action which provides a better user experience. We'd like this to be the recommended way to run Gradle builds in GitHub Actions.

### Additional information

Related PRs:
https://github.com/github/docs/pull/11851
https://github.com/actions/starter-workflows/pull/1237

**Comment by ramyaparimi** [comment]
@bigdaz 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by P-DUBB** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> * https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
> * https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
> 
> ### What part(s) of the article would you like to see updated?
> These 2 articles invoke Gradle directly. The Gradle team provides https://github.com/marketplace/actions/gradle-build-action which provides a better user experience. We'd like this to be the recommended way to run Gradle builds in GitHub Actions.
> 
> ### Additional information
> Related PRs: #11851 [actions/starter-workflows#1237](https://github.com/actions/starter-workflows/pull/1236)
bigdaz:gradle-build-action-v2

**Comment by REDMI7AMM** [comment]
11

**Comment by REDMI7AMM** [comment]
12

**Comment by REDMI7AMM** [comment]
Android 11

**Comment by REDMI7AMM** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> * https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
> * https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
> 
> ### What part(s) of the article would you like to see updated?
> These 2 articles invoke Gradle directly. The Gradle team provides https://github.com/marketplace/actions/gradle-build-action which provides a better user experience. We'd like this to be the recommended way to run Gradle builds in GitHub Actions.
> 
> ### Additional information
> Related PRs: #11851 [actions/starter-workflows#1237](https://github.com/actions/starter-workflows/pull/1237)

**Comment by skedwards88** [comment]
@bigdaz Thanks for opening this issue! This proposal makes sense. I see that your corresponding PR is still in draft mode. Once it is ready for review, you can mark it as ready for review and someone on the team should review it.

**Comment by bigdaz** [comment]
@skedwards88 I've removed the "Draft" label on the PR. But in the end I think this will require some further collaboration between Gradle and GitHub. 
I received some initial questions from @ethomson on the Slack channel shared between Gradle and GitHub, which led me to question if there's a more idiomatic way for the `gradle-build-action` to operate. It would be great if we could sync up to agree on the best direction, which would influence whether we should recommend the action as-is, or wait for further changes before doing so.
