### ISSUE TITLE
SSH key fingerprints: listed ECDSA and Ed25519 not working

### ISSUE THREAD

**Issue by cyann** [github/docs#11888]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

### What part(s) of the article would you like to see updated?

Article extract:
> These keys will be supported beginning September 14, 2021:
>
>    SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM (ECDSA)
>    SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU (Ed25519)

As of 2021-11-12, these new fingerprints are now available.

### Additional information

Command used to test:

```shell
% ssh-keyscan -t rsa,ecdsa,ed25519 github.com 
# github.com:22 SSH-2.0-babeld-2aa5ef1f
github.com ssh-rsa AAAA...
# github.com:22 SSH-2.0-babeld-2aa5ef1f
# github.com:22 SSH-2.0-babeld-2aa5ef1f
```

**Comment by ramyaparimi** [comment]
@cyann 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
👋🏻  @cyann, can you please contact support about this? Thanks!

https://support.github.com

**Comment by cyann** [comment]
Typo: the new fingerprints are **not** available
