### ISSUE TITLE
Style update for REST API docs intro

### ISSUE THREAD

**Issue by megbird** [github/docs#1190]
### What feature or product is affected?

REST API reference docs 

### Expected changes 

Let's condense the sentences in the "[About APIs](https://docs.github.com/en/free-pro-team@latest/developers/overview/about-githubs-apis)" page into one paragraph.  A reviewer noted it looks awkward as three one-sentence paragraphs.

**Comment by pr0PM** [comment]
How about converting:
```
There are two stable versions of the GitHub API: the REST API and the GraphQL API.
When using the REST API, we encourage you to request v3 via the Accept header.
For information on using the GraphQL API, see the v4 docs.
```
to


You can use the stable GitHub API via:
- [GraphQL API](https://docs.github.com/en/free-pro-team@latest/v4)
- [REST API](https://docs.github.com/en/free-pro-team@latest/v3) where we encourage you to [request v3 via the `Accept` header.](https://docs.github.com/en/free-pro-team@latest/v3/media/#request-specific-version)

**Comment by pr0PM** [comment]
I'll make a PR if it helps :)

**Comment by janiceilene** [comment]
Thanks @pr0PM 💝  Feel free to open an PR!
