### ISSUE TITLE
Unlock the email

### ISSUE THREAD

**Issue by SamrithChenda** [github/docs#11929]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Please link to the article you'd like to see updated.

### What part(s) of the article would you like to see updated?

Give as much detail as you can to help us understand the change you want to see.

**Comment by SamrithChenda** [comment]
Add any other context or screenshots about the feature request here.

**Comment by Giwrgos-g1-96** [comment]
CODE_OF_CONDUCT.md
