### ISSUE TITLE
Update `gh repo create` documentation

### ISSUE THREAD

**Issue by meiji163** [github/docs#11931]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- [Create a repo](https://docs.github.com/en/get-started/quickstart/create-a-repo)
- [Adding an existing project to GitHub using the command line](https://docs.github.com/en/github/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line)
- [Creating GitHub CLI extensions](https://docs.github.com/en/github-cli/github-cli/creating-github-cli-extensions)

### What changes are you suggesting?

Update the documentation for `gh repo create` to reflect the new usage, which is set to be merged in the next release of GitHub CLI
Ref: https://github.com/cli/cli/pull/4578, https://github.com/cli/cli/issues/4567

**Comment by REDMI7AMM** [comment]
update new counect
