### ISSUE TITLE
[GitHub Desktop] Add delete tags functionality

### ISSUE THREAD

**Issue by janiceilene** [github/docs#1199]
Anyone is welcome to open a PR!

Use this Desktop issue, [Add delete tags functionality](https://github.com/desktop/desktop/pull/9796), to understand the context of this change. Download the [current beta version](https://github.com/desktop/desktop#beta-channel) of Desktop to take any screenshots.

Users can now right click on a tag they've added, but haven't pushed, to surface a context menu that enables them to delete it.

**Audience:** Tags are frequently used to indicate version numbers for a release, a feature more likely to be used by developers who have an understanding of Git and GitHub (so, not very new users).

In [Managing tags](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/managing-tags):
- [ ] Add a new section titled "Deleting a tag"
- [ ] Start with a sentence explaining you can only delete unpushed tags
- [ ] Create a procedural (using reusables wherever possible) to show folks how to delete tags (modeled after previous sections)
  - [ ] Include a step that starts with "Optionally, to delete more than one tag" and shows how to use the sub menu.

**Comment by Perkles** [comment]
Hey @janiceilene 👋 
I'll be working on this one.

**Comment by ethanpalm** [comment]
👋  Hi, I wrapped up this issue in https://github.com/github/docs/pull/3045, but along the way, I saw some other possible improvements to  [Managing tags](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/managing-tags), which are documented in this issue: https://github.com/github/docs/issues/3050.
