### ISSUE TITLE
[GitHub Desktop] Add new working with a fork flow

### ISSUE THREAD

**Issue by janiceilene** [github/docs#1200]
Anyone is welcome to open a PR!

Use this Desktop issue, [Provide a way to more easily work with a maintained fork](https://github.com/desktop/desktop/issues/9679#issuecomment-622157050), to understand the context of this change. Download the [current beta version](https://github.com/desktop/desktop#beta-channel) of Desktop to take any screenshots.

This article has a mac and a windows version. We might need to split it into two separate issues to get screenshots, but maybe that's not required for cloning?

This feature provides a new flow to forking a repo. It now asks whether users want to fork a repo to work independently or to contribute to an upstream repo.

**Audience:** Forking a repo can be a confusing concept to new users looking to participate in open source. Let's keep this information focused on very new users.

**Note:** For the person who picks up this issue. Remember to keep conceptual information separate from the procedural.

In [Cloning and forking repositories from GitHub Desktop](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/cloning-and-forking-repositories-from-github-desktop):
- [ ] Add an additional sentence to the conceptual information at the beginning of the "Forking repositories" section to explain why a user might want to fork a repository for their own use.
- [ ] Add conceptual information that describes the fact that folks will be asked how they plan to use the fork and the consequences of answering each way (e.g., issues opened in Desktop will be created in the upstream repository).
- [ ] Update the procedural in the "Forking repositories" section to match the new flow, modeled after previous sections and using reusables for each procedural
- [ ] Separate screenshots for windows and mac would be helpful, but we can create a followup issue, if they're not done here.

**Comment by nazarmaddin** [comment]
Ingin meneruskan pelaksana dan masalah

**Comment by ethanpalm** [comment]
This issue is closed in https://github.com/github/docs/pull/3210 🚀
