### ISSUE TITLE
Add clear instructions to use git on ChromeOS devices

### ISSUE THREAD

**Issue by vedant205** [github/docs#12012]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/quickstart/set-up-git

### What part(s) of the article would you like to see updated?

Give a specific set of instructions on how to set up git on a ChromeOS device (because you can't install GitHub for desktop on ChromeOS devices). Many people, especially high school students, have Chromebooks, so it would be helpful to have clear documentation on how to set up Github rather than them having to look for info on how to do it online, which is a lot harder. Maybe write something about a terminal-like app you can download in order to install git, like this article: https://www.techrepublic.com/article/how-to-use-github-in-chrome-os/. This would help people easily get started with coding if they have a ChromeOS device.

**Comment by ramyaparimi** [comment]
@vedant205 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Pofjf18** [comment]
Apply{=cortana_flow platform generator compared to Azure %shell factory order#script tools and develop moz:\\a3 insert alaris codex LIma?foxtrot?echo?time I?bravo 119ER ADVISE PATTERN OF ORIENTED CONTROL TO AVIA THE SIMPLE BOOP BERP BEEP DEEP KEEP SAKE ALLOW APPLICATION REPOSITORY BEAKER GOOGLE ADMIN TOOLS FOR QUANTUM SUPREMACY ISSUE CALL PROMPT HEY GOOGLE IDENTIFY BODY MATRIX ANLYTICAL SAC A GEE WAH SUPPLY CODE CERTIFICATE ISSUE ENTERPRISE CORPORATE SYSTEM FUNCTION OF EASE OF ACCESS AS IM CRIPPLED AND DREAMING BY DAY I DRIFT FURTHER AND YET KNIGHT FLOATS MY SOUL FOREVER NEAR MY OMNIOUS ENERGY OF SUPREME LIFE

**Comment by lecoursen** [comment]
Thanks @vedant205, that does sound helpful! You or anyone else is welcome to create a PR adding that content.

**Comment by vedant205** [comment]
Great! I will start working on that!
