### ISSUE TITLE
[GitHub Desktop] Stashing changes feature

### ISSUE THREAD

**Issue by janiceilene** [github/docs#1202]
Anyone is welcome to open a PR!

Use this Desktop issue, [Allow users to stash changes without switching branches](https://github.com/desktop/desktop/pull/10032), to understand the context of this change. Download the [current beta version](https://github.com/desktop/desktop#beta-channel) of Desktop to take any screenshots.

This feature allows users to right click on changes to stash them, instead of only having that option pop up when trying to change branches.

**Audience:** This is a feature that's really useful to new users, but they may not know about, so let's focus on new users for this change.

We use opinionated procedurals in our docs, so even though the issue above describes two separate ways to stash changes, we're only going to document one. For ease of use (and because it's the same for mac and windows users), we're only going to document the right click method.

We're going to create a new article titled, "Stashing changes"
- [x] Create a new file in the "Contributing and collaborating using GitHub Desktop" category
- [x] Name it stashing-changes.md
- [x] Copy the metadata from another article into your new file
- [x] Change the title in the metadata
- [x] Write an intro explaining in one sentence, why a user might want to stash changes.
- [x] Add the article to the index.md under `contributing-and-collaborating-using-github-desktop`, under "Committing and reviewing changes to your project"
- [x] Create a new conceptual section explaining why someone would want to stash changes
- [x] Create a new procedural explaining how to right click and stash changes.
- [x] Move the content from the "Switching between branches" and "Retrieving stashed changes" sections in the [Managing branches](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/managing-branches#switching-between-branches), to the new article.

**Comment by poptire** [comment]
Hi, I'd like to work on this over the next few days. Thanks for opening the issue!

**Comment by StarTrooper08** [comment]
I would like to work on this issue . If no one is working over it!!!?

**Comment by janiceilene** [comment]
@poptire Are you still working on this issue?

@StarTrooper08 In the meantime, there are several more issues for GitHub Desktop updates that no one has commented on yet! https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+Desktop

**Comment by poptire** [comment]
@janiceilene I have been out on assignment for the past week and unable to get as much work done on this as I would have liked. @StarTrooper08 might you be able to pick up my slack? Apologies, everyone.

**Comment by janiceilene** [comment]
Thanks for the update @poptire and definitely not a problem! there are always more issues to pick up if you're interested and less busy another time 💛

**Comment by StarTrooper08** [comment]
Ok I will head on with this issue .
As soon as I resolve the following issue.
I will update you with the same @janiceilene . 
And also update you if I encounter with some error during resolving the issue.
Thank you🤗.

**Comment by StarTrooper08** [comment]
@poptire thanks for giving me opportunity . To work on this issue

**Comment by StarTrooper08** [comment]
@janiceilene what metadata should I add in stashing-changes.md file?

**Comment by janiceilene** [comment]
@StarTrooper08 I copied this 👇 from one of the other Desktop articles, you'll need to update the intro though:

```
---
title: Stashing changes
intro: 'You can add any Git repository to {% data variables.product.prodname_desktop %}, even if it''s not a {% data variables.product.prodname_dotcom %} repository.'
versions:
  free-pro-team: '*'
---
```

**Comment by StarTrooper08** [comment]
Ok
