### ISSUE TITLE
Rendering issue in Configuring OpenID Connect in Google Cloud Platform

### ISSUE THREAD

**Issue by jfoote** [github/docs#12026]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform

### What part(s) of the article would you like to see updated?

Hello. The YAML example in the [Requesting the access token section](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform#requesting-the-access-token) does not seem to render properly. Rather than showing the name of the variable, a `$` is displayed in my browser.

I.e. rather than seeing

```
gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
```

I see

```
gcloud auth login --brief --cred-file="$"
```

The `uses` directive could also be updated to `google-github-actions/auth@v0.4.0` but I'm not sure if that is required (I didn't test the listed version).

### Additional information

![image](https://user-images.githubusercontent.com/2072203/141863865-24953c88-6e18-4a6a-89e6-c7eb91ddb028.png)

Chrome Version 95.0.4638.69 (Official Build) (x86_64)

**Comment by ramyaparimi** [comment]
@jfoote 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
@jfoote - many thanks for flagging this bug ✨ 

It looks as if we've forgotten to include the `{% raw %}` tags needed to protect the `{{...}}` elements in the example. I'll open a PR to fix this.

**Comment by felicitymay** [comment]
For more information, see: https://github.com/github/docs/blob/main/contributing/content-style-guide.md#code-blocks.

This will be fixed by https://github.com/github/docs/pull/12447

**Comment by felicitymay** [comment]
@jfoote - it will take a little while for the fix to be live in the public docs, but it should be there within 24 hours.

Thank you for providing such a clear and detailed issue when you spotted this bug 💖
