### ISSUE TITLE
Table with long words overlaps with sidebar

### ISSUE THREAD

**Issue by SijmenHuizenga** [github/docs#1205]
Hi there! Thanks so much for the great documentation <3

It seems #56 is back on another page. This time in a table with a word that is too long.

### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/autolinked-references-and-urls

### What part(s) of the article would you like to see updated?

The following table not overlap with the sidebar:

![image](https://user-images.githubusercontent.com/8008227/98603217-006c8f80-22e2-11eb-98ca-2b0593031714.png)

**Comment by janiceilene** [comment]
Thanks so much for letting us know @SijmenHuizenga!

**Comment by SleepyDrew2G** [comment]
Every thing
