### ISSUE TITLE
Code snippet in ja/working-with-ssh-key-passphrases.md  is wrong

### ISSUE THREAD

**Issue by moccos** [github/docs#12093]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ja/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases

### What part(s) of the article would you like to see updated?

Code snippet is wrong in ja-JP document.
https://docs.github.com/ja/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-git-for-windows
All other translations, es-ES, pt-BR and zh-CN are correct.

English:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-git-for-windows

**Comment by ramyaparimi** [comment]
@moccos 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
