### ISSUE TITLE
Undocumented `pull_request_review_comment` event

### ISSUE THREAD

**Issue by wolfy1339** [github/docs#12295]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

### What part(s) of the article would you like to see updated?

Add information about the new `pull_request_review_thread` event.

The event is currently sent when you mark a discussion on a pull request review is marked as `resolved`, or `unresolved`.

### Additional information

Example payloads can be found in octokit/webhooks#594
X-Ref: octokit/webhooks#594, octokit/webhooks#593

**Comment by ramyaparimi** [comment]
@wolfy1339 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by vgrl** [comment]
@wolfy1339 Thank you so much for the issue and example payloads. As these changes need to be made internally, I've transferred this issue to an internal repo. I'll go ahead and close this issue now 💛

**Comment by taisph** [comment]
The title is mentioning the `pull_request_review_comment` but is talking about `pull_request_review_thread` event. The latter event is still not documented at https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads. 🤔

**Comment by MitrichDot** [comment]
Пн, 28 марта 2022 г. в 11:01, Tais P. Hansen ***@***.***>:

**Comment by vgrl** [comment]
Thanks for pointing out that discrepancy @taisph , I'll update the title to reflect that it's the `pull_request_review_thread` webhook event that's undocumented.
