### ISSUE TITLE
Keyboard shortcut for Github Command Palette on Windows/Linux may be incorrect

### ISSUE THREAD

**Issue by elicavalheiro** [github/docs#12298]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I've noticed that into **Feature Preview** modal and https://docs.github.com/en/get-started/using-github/github-command-palette, the keyboard shortcut showed for Windows and Linux is incorrect.

It shows `ctrl + alt + k` instead of `ctrl + shift + k`.

### What part(s) of the article would you like to see updated?

I would like to see [Opening the Github Command Palette](https://docs.github.com/en/get-started/using-github/github-command-palette#opening-the-github-command-palette) keyboard shortcut for Windows and Linux updated from `ctrl + alt + k` to `ctrl + shift + k`

### Additional information

**Screenshot - Keyboard shortcut into [Docs - Github Command Palette](https://docs.github.com/en/get-started/using-github/github-command-palette#opening-the-github-command-palette)**
![image](https://user-images.githubusercontent.com/36828798/143140532-d74e9431-10d1-4705-a46a-de23dde475e2.png)

**Screenshot - Keyboard shortcut into _Freature Preview_**
![image](https://user-images.githubusercontent.com/36828798/143140676-5609a61c-8499-43c2-8cd8-ffaebcb1b376.png)

**Comment by zedgamer9128** [comment]
I have Arch Linux and when i type ctrl + k the command palette opens

**Comment by elicavalheiro** [comment]
@zedgamer9128 I think that the `ctrl + k` command has a different functionality than `ctrl + shift + k`. Same as `ctrl + p` and `ctrl + shift + p` inside VSCode.

**Comment by zedgamer9128** [comment]
There Are two modes

- Search Mode
- Command Mode

In The article it says to click `ctrl + k` to open command palette but it doesn't specify whether that open search mode or command mode as you scroll down you know `ctrl + shift + k` will get you to command mode 
and last of all it says `ctrl + k` or `ctrl + alt + k` which is totally reasonable maybe in some devices `ctrl + k` doesn't work but instead `ctrl + shift + p` works so using or is reasonable

**Comment by AnilSeervi** [comment]
<kbd>ctrl</kbd><kbd>atl</kbd><kbd>k</kbd> and <kbd>ctrl</kbd><kbd>k</kbd> is for navigation(`/`)

<kbd>ctrl</kbd><kbd>shift</kbd><kbd>k</kbd> is for running commands(`>`)

**Comment by ramyaparimi** [comment]
@elicavalheiro 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
@elicavalheiro - thanks for opening this issue with your concern about the documentation for the command palette ✨

I've just tested this on my Windows machine and both `ctrl + k` and `ctrl + alt + k` act as expected to open the command palette in search mode. I believe that we offer two key combinations for this as `ctrl + k` has other functions in some situations (like when you're editing a comment on an issue).

It sounds as if you're experiencing a different behavior when you use `ctrl + alt + k`. Could you tell us what happens and which operating system/browser you're using?

**Comment by dhztao68** [comment]
Thanks too

**Comment by elicavalheiro** [comment]
> @elicavalheiro - thanks for opening this issue with your concern about the documentation for the command palette sparkles
> 
> I've just tested this on my Windows machine and both `ctrl + k` and `ctrl + alt + k` act as expected to open the command palette in search mode. I believe that we offer two key combinations for this as `ctrl + k` has other functions in some situations (like when you're editing a comment on an issue).
> 
> It sounds as if you're experiencing a different behavior when you use `ctrl + alt + k`. Could you tell us what happens and which operating system/browser you're using?

@felicitymay Thank you for the answer! I'm using Linux with Kubuntu and Google Chrome as browser, when I press the command `ctrl + alt + k` does nothing. The `ctrl + k` command open search palette.

**Comment by felicitymay** [comment]
> @felicitymay Thank you for the answer! I'm using Linux with Kubuntu and Google Chrome as browser, when I press the command `ctrl + alt + k` does nothing. The `ctrl + k` command open search palette.

@elicavalheiro - thanks for getting back to me so quickly 🙇🏻‍♀️ 

It sounds as if this behavior might be best passed onto the development team as feedback. Would you mind dropping a note in the feedback channel: https://github.community/c/command-palette/71?

**Comment by felicitymay** [comment]
I think it makes sense to close this issue as I don't think we need a docs change here.
