### ISSUE TITLE
Correct workflow badge 'event' example to use 'on'

### ISSUE THREAD

**Issue by danielfdickinson** [github/docs#12329]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

### What part(s) of the article would you like to see updated?

The example at https://github.com/github/docs/blob/27d1c2622074eba7ad5f74ddb474ea995b7da04c/content/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge.md?plain=1#L41-L47 is incorrect.

Using a URL such as <https://github.com/github/docs/actions/workflows/main.yml/badge.svg?event=pull_request> shows no status, as with this repo:

![test-build-validate PR](https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?event=pull_request)

Changing it to a URL such as <https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request> shows the status of the event (in this case ``pull_request``)

![test-build-validate PR](https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request)

**Comment by ramyaparimi** [comment]
Closing this issue as the [linked PR was closed](https://github.com/github/docs/pull/12331)
