### ISSUE TITLE
Is it possible to migrate an OAuth app to Github app without asking users to re-authenticate?

### ISSUE THREAD

**Issue by jgimenez** [github/docs#1236]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/developers/apps/migrating-oauth-apps-to-github-apps

### What part(s) of the article would you like to see updated?

 * The migration guide explains how to create a new Github app to replace your old OAuth app
 * It's not clear to me if there's a way to move the users to the new app, so they don't need to re-authenticate (I guess there is not, but I think should be indicated)
 * It's not clear to me whether I should delete the old OAuth app. It's confusing to me, because it says we should encourage users to de-authorize the old app, but if the old app is no longer in use, it would make more sense to me to delete the app, so its credentials can not be abused in any way and all authorizations are revoked.

**Comment by lucascosti** [comment]
👋 @jgimenez 🙂  To answer your main question:

> It's not clear to me if there's a way to move the users to the new app, so they don't need to re-authenticate (I guess there is not, but I think should be indicated)

IIUC, no, this isn't possible. The new app is essentially a distinct installation, so it's access must be authenticated by the user. 

> It's not clear to me whether I should delete the old OAuth app. It's confusing to me, because it says we should encourage users to de-authorize the old app, but if the old app is no longer in use, it would make more sense to me to delete the app, so its credentials can not be abused in any way and all authorizations are revoked.

I think this was originally written implying that some users might still be using the old app. If all your users have transitioned off the old app, or if you're happy to delete the old app even though it might still have active users, then deleting the app makes sense 👍

We can definitely update the doc to be more clear about both these points. I'll open this issue up for anyone to take on 🙂

**Comment by duc811997** [comment]
[Uploading Account 0.txt…]()

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can anyone suggest me to get started?

**Comment by janiceilene** [comment]
👋 @prsmahajan You're welcome to open a PR following the plan outlined in https://github.com/github/docs/issues/1236#issuecomment-742257828. Let us know if you have any additional questions!

**Comment by prsmahajan** [comment]
What is the issue @janiceilene ?

**Comment by janiceilene** [comment]
> What is the issue @janiceilene ?

I'm sorry @prsmahajan, I'm not sure what you're question is. If you'd like to work on this issue, you're welcome to open a pull request following the instructions given in this [comment](https://github.com/github/docs/issues/1236#issuecomment-742257828).

Please let me know if there's additional information or clarification I can give 💛

**Comment by 123MwanjeMike** [comment]
> I think this was originally written implying that some users might still be using the old app. If all your users have transitioned off the old app, or if you're happy to delete the old app even though it might still have active users, then deleting the app makes sense +1
> 
> We can definitely update the doc to be more clear about both these points. I'll open this issue up for anyone to take on slightly_smiling_face

I failed to find an issue for the modifications suggested so I opened [this](https://github.com/github/docs/issues/8067#issue-941263258) issue and made changes in the linked [pull request](https://github.com/github/docs/pull/8068#issue-687193801)

**Comment by AnilSeervi** [comment]
- #8640 addresses this Issue.

**Comment by AnilSeervi** [comment]
thanks @janiceilene , and also #7901 can be closed as its august now or be renamed :)
