### ISSUE TITLE
Decrease size of strawberry emoji in REST API reference docs

### ISSUE THREAD

**Issue by HonkingGoose** [github/docs#12403]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/issues#create-a-label

## Problem description

The strawberry emoji takes up to much visual space compared to the text around the emoji. I think the image source or the page CSS needs to be edited so it takes up less visual space.

Icon as rendered on GitHub Docs: ![strawberry emoji](https://github.githubassets.com/images/icons/emoji/unicode/1f353.png)

Icon as rendered in GitHub Markdown: :strawberry:

## Preview of possible solution

![resized-emoji-to-2-rem](https://user-images.githubusercontent.com/34918129/143686141-cd174b4e-fde0-4a56-9b06-a24ccdde1f70.png)

I changed the `max-height` property to `2rem` to get this preview.

```css
.markdown-body img {
	max-height: 2rem; <-- This is the changed property
	padding: 0;
}
```
---
**edited by maintainer**
### Additional information
Please review your changes in staging to make sure the edits are not breaking any existing `img` tags

_No response_

**Comment by amin1419** [comment]
https://github.com/github/docs/projects/1#card-73749458

**Comment by zedgamer9128** [comment]
looks like it is not editable by us see [here](https://github.com/zedgamer9128/docs/blob/main/content/rest/README.md) since it is in reference which is not human editable.

**Comment by ramyaparimi** [comment]
@HonkingGoose This issue was fixed internally in the recent Primer/Component updates ✨ 

Thanks so much for your contribution to the GitHub docs 💖
