### ISSUE TITLE
GITHUB_TOKEN scope column doesn't have the literal scopes

### ISSUE THREAD

**Issue by nabeken** [github/docs#12410]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

### What part(s) of the article would you like to see updated?

There is a table that describes permissions we can specify in the workflow.

When I tried to add it for Pull Requests, I just copied `pull requests` in the configuration but it didn't work because it has to be `pull-requests`.

I can see there are several "permissions" that contains a space but it should be valid name for the workflow configuration.

**Comment by ramyaparimi** [comment]
@nabeken 
Thanks so much for opening a PR! I'll get this triaged for review :zap:
