### ISSUE TITLE
Error 503 certificate has expired - docs are down

### ISSUE THREAD

**Issue by guyschlider** [github/docs#12449]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The whole website is down

### What changes are you suggesting?

Fixing it :)

**Comment by ramyaparimi** [comment]
@guyschlider Thanks so much for opening this! This issue has been [resolved ](https://www.githubstatus.com/incidents/22y5yl6gcc6b)✨
