### ISSUE TITLE
Document how the Wiki Sidebar is generated

### ISSUE THREAD

**Issue by froboy** [github/docs#12456]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis

### What part(s) of the article would you like to see updated?

Add a little more info about the "Pages" sidebar in the wiki since it seems to do some special things:

- How are pages ordered (it seems like `Home` is special, are there other ordering rules?)
- How are inner-page heading links generated?
- Anything else special going on?

**Comment by ramyaparimi** [comment]
@froboy 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
@froboy - apologies for the delay in responding to your issue. I can see that there is some information about the sidebar in this article: https://docs.github.com/en/communities/documenting-your-project-with-wikis/creating-a-footer-or-sidebar-for-your-wiki#creating-a-sidebar.

I wasn't sure what you were asking with this question below, could you explain more, perhaps with an example:

> How are inner-page heading links generated?
