### ISSUE TITLE
[data reusables] Typo in command_line.open_the_multi_os_terminal?

### ISSUE THREAD

**Issue by aprotyas** [github/docs#12469]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All articles that use the macro `{% data reusables.command_line.open_the_multi_os_terminal %}`.

I stumbled across the unclear wording in [Generating a new GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key).

I've attached a screenshot with the text-in-question highlighted.

![image](https://user-images.githubusercontent.com/34530011/143987595-4ba6042a-2df7-4348-8334-754de74a267b.png)

### What changes are you suggesting?

On my browser, expansion of the `{% data reusables.command_line.open_the_multi_os_terminal %}` reads "**Open TerminalTerminalGit Bash.**". This does not sound correct, which is why I'm suggesting a change.

Given the data is titled "multi_os", I don't have a good cross-platform suggestion here other than maybe just "**Open Terminal/Git Bash.**"

The expected outcome is for that reusable sentence - which boils down to asking the user to open a terminal/Git bash with Git installed - to be less ambiguous.

**Comment by AnilSeervi** [comment]
The reusable file is available [here](https://github.com/github/docs/blob/main/data/reusables/command_line/open_the_multi_os_terminal.md).

You can see that there are actually 3 `<span>` tags with classes that are specifically designed to show based on the platform users are on(maybe using `navigator.platform`) and hide the others.
But in your case it seems like none of the span tags got hidden. I wonder what browser you are using :/

I personally think this is not the proper way cuz now if you open the same docs page on any other device(like android, iPad etc), it just hides all the span tags. weird.

**Comment by felicitymay** [comment]
@aprotyas - thank you so much for letting us know about this problem in the docs and for digging in to see where the problem was ✨ 

The docs engineering team have made several changes to how the site works recently and it seems as if those `<span>` tags were being ignored when you looked at that page. As far as I can tell, the page is now displaying correctly again. 

I'm going to close this issue, but if you find that the page still looks broken in your browser, please reopen it and we can investigate further.

**Comment by dhztao68** [comment]
CLOSED...

**Comment by aprotyas** [comment]
Just confirming that the page is displaying correctly on my end as well. Thank you!
