### ISSUE TITLE
Add a code sample for workflow_dispatch variables

### ISSUE THREAD

**Issue by n-hebert** [github/docs#12487]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[content/actions/learn-github-actions/workflow-syntax-for-github-actions.md](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions)

### What part(s) of the article would you like to see updated?

The workflow_dispatch variable usage is suggested, but not shown. An example should be used to help readers at a glance.

**Comment by Elrolon** [comment]
removed the triage label yesterday
