### ISSUE TITLE
Add filter out info (`-`) to issue/PR search documentation

### ISSUE THREAD

**Issue by Julian88Tex** [github/docs#1249]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests

### What part(s) of the article would you like to see updated?

- Adding filter out info (`-`) to search documentation with example: `state:open type:issue -author:octocat`

### Additional information

Attempted to navigate to https://github.com/github/docs-content/issues/new/choose but get a 404.

**Comment by janiceilene** [comment]
This was closed in https://github.com/github/docs/pull/1248 🎉
