### ISSUE TITLE
Explain how to use environment variables in a test matrix

### ISSUE THREAD

**Issue by martin389** [github/docs#1253]
This topic was suggested in https://twitter.com/Benoit_Tgt/status/1324684045712793601 🙇‍♂️ 🎉

### What article on docs.github.com is affected?

The ["Workflow syntax for GitHub Actions"](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions) documentation needs to explain how to add custom environment variables to a test matrix.

### What part(s) of the article would you like to see updated?

The proposed example could be a part of the [`jobs.<job_id>.strategy.matrix`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) docs.

### Additional information

Once this has been added to the main docs, we can look at adding something similar to the [Travis migration guide](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions).

**Comment by SleepyDrew2G** [comment]
I am help routers
