### ISSUE TITLE
"Security advisory credit" and "discussion(s) answered" missing from section "Displaying badges on your profile"

### ISSUE THREAD

**Issue by Schweinepriester** [github/docs#12556]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile#displaying-badges-on-your-profile

### What part(s) of the article would you like to see updated?

While there are some [entries listed](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile#displaying-badges-on-your-profile) which appear under "Highlights" on ones profile, for example "Developer Program Member" on [mine](https://github.com/Schweinepriester),  the "security advisory credit" ([example profile](https://github.com/robmcl4)) as well as the "discussion(s) answered" ([example profile](https://github.com/Forceu)) are missing.

So I'd like to see them added.
If there are more, those as well :)

**Comment by ramyaparimi** [comment]
@Schweinepriester 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @Schweinepriester, I agree that would be useful to add. You or anyone else is welcome to add the badges you've seen!

**Comment by Schweinepriester** [comment]
@lecoursen Thanks! I'm certainly happy to start the PR, but what about the badge assets (SVGs)? Should I just 'steal' that from the profiles, or do you have those like raw/better internally?
Also: Are there more missing than those two? 0:-)

**Comment by lecoursen** [comment]
> @lecoursen Thanks! I'm certainly happy to start the PR, but what about the badge assets (SVGs)? Should I just 'steal' that from the profiles, or do you have those like raw/better internally?

Great question! You can pull them from the profiles.

> Also: Are there more missing than those two? 0:-)

I'm not sure actually! I don't think we have the bandwidth to chase down the answer either. For now, let's add anything you've seen, and if we find out about more we can add them!

**Comment by Mannypi67** [comment]
Find anyone credit card account information
