### ISSUE TITLE
permissions list is missing value: pages 

### ISSUE THREAD

**Issue by GerryFerdinandus** [github/docs#12597]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions

### What changes are you suggesting?

add
`pages: read|write|none`
to the list

### Additional information

This PR https://github.com/SchemaStore/schemastore/pull/1960 add `pages` to the permission. But the GitHub doc is missing this info.

Also tested with Yaml file. It is accepted by the build server.
```
permissions:
  pages: read
```

**Comment by taufik0786** [comment]
I do this
