### ISSUE TITLE
Mention that composite actions can't access the `secrets` context

### ISSUE THREAD

**Issue by toast-gear** [github/docs#12705]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

### What part(s) of the article would you like to see updated?

Add in a section / column for composite actions which highlights what contexts are and aren't avaliable to them

--- 
edited by maintainer

### Content plan

Here is the [writer's review](https://github.com/github/docs/issues/12705#issuecomment-1026331636) for this issue

**Comment by bitmastercoin** [comment]
tree
    Turbulence on. 1==1
1--1
  And.  .   S.    Z.  
             \.   /|]
Okay.            \. /
                   \.   
                       -----
                             \__

**Comment by Dlocc23** [comment]
``

**Comment by bitmastercoin** [comment]
Lmao sorry bored

**Comment by bitmastercoin** [comment]
> tree
>     Turbines on. 1==1
> 1--1
>   And.  .   S.    Z.  
>              \.   /|]
> Okay.            \. /
>                    \.   
>                        -----
>                              \__
>

**Comment by bitmastercoin** [comment]
> tree
>     Turbines on. 1==1
> 1--1
>   And.  .   S.    Z.  
>              \.   /|]
> Okay.            \. /
>                    \.   
>                        -----
>                              \__
>

**Comment by lucascosti** [comment]
👋 @toast-gear, sorry for the delayed reply. I'm pretty sure that composite actions have the same access to contexts as any other action has, so I'm not sure a docs update would be needed here. I'll double-check with the engineering team.

**Comment by prashanthr** [comment]
Hi! 
I've created https://github.com/github/docs/pull/21596 to address the note that @lucascosti pointed out above. Thanks!
