### ISSUE TITLE
Permission on "contents" Commit comments POST :sha/comments (:read) is wrong

### ISSUE THREAD

**Issue by jsoref** [github/docs#12723]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents

### What part(s) of the article would you like to see updated?

> ## Commit comments

> [POST /repos/:owner/:repo/comments/:comment_id/reactions](https://docs.github.com/en/rest/reference/reactions#create-reaction-for-a-commit-comment) (:read)
[POST /repos/:owner/:repo/commits/:sha/comments](https://docs.github.com/en/rest/reference/repos#create-a-commit-comment) (:read)

Afaict, this text claims that one can use a `contents: read` token when using the `POST` API to the commit comments endpoint or the commit comment reactions endpoint.

The link for the latter goes to an api for **creating** a comment. The link to the former goes to the api for **creating** a reaction.

### Additional information

I tried giving a workflow only `contents: read` and asking it to post a comment, it didn't work:

https://github.com/jsoref/examples-testing/runs/4450983220?check_suite_focus=true#step:1:13
```yaml
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  PullRequests: write
```

https://github.com/jsoref/examples-testing/runs/4450983220?check_suite_focus=true#step:5:1564

```sh
  + curl -L -s -S -H 'Authorization: token ***' -H 'Content-Type: application/json' -H 'Accept: application/vnd.github.comfort-fade-preview+json' --data @/tmp/tmp.7SWv7A8UtC https://api.github.com/repos/jsoref/examples-testing/commits/4fa22a1d590c1c878d13c925be716bf31f1ed350/comments
  + '[' 0 -gt 0 ']'
  + '[' -n 1 ']'
  + cat /tmp/tmp.oXNHd50OoJ.json
  {
    "message": "Resource not accessible by integration",
    "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-commit-comment"
  ++ jq -r '.url // empty' /tmp/tmp.oXNHd50OoJ.json
  }
```

When the same workflow has `contents: write`, it can post a comment. This matches what one would expect if one didn't read this document.

I also use the reaction endpoint, but I only use it after creating a commit which absolutely needs `contents: write`, so I'm not really in a position to verify that one can't create a reaction w/ only `contents: read`, but, I'm guessing one can't even though the documentation here seems to indicate that one could.

**Comment by ramyaparimi** [comment]
@jsoref Thanks for opening this issue. We really appreciate that you clearly listed the APIs and what you tried that didn’t work. All the context you have provided is very clear and makes it easy for anyone to understand the issue :sparkles:.
I will get this triaged for a writer’s review :eyes:

**Comment by Jackieg81710** [comment]
I think I got it

**Comment by stevecat** [comment]
Thanks for opening this @jsoref! When I test this using a GitHub App with `read` on `contents`, I can create commit comments but can't add reactions to them. 

I'm not certain what the expected permissions are or if there's some special casing for the GITHUB_TOKEN. Regardless, we do need to make a change to clarify this.

I've opened an issue with our API engineering team and I'll follow up here once I hear back from them!

**Comment by stevecat** [comment]
Hi @jsoref, I wanted to update you on this. I've been talking with our engineering team and this is what both endpoints actually require:

* `POST /repos/:owner/:repo/comments/:comment_id/reactions` requires **`contents:write`**
*  `POST /repos/:owner/:repo/commits/:sha/comments` requires **`contents:read`** but in some situations, such as being triggered via an Action, requires **`contents:write`** (that's where the discrepancy between your test and my test came from!)

We've opened an internal issue to look at making these consistent. We're also looking at a complete refresh on this particular page. In the meantime, I'm going to update the article to reflect reality. I'll update this issue once that's merged! Thanks again for bringing this up.

**Comment by stevecat** [comment]
Those changes are merged and should be live shortly. Thanks again, @jsoref! ✨

**Comment by slowbuss** [comment]
SWEET THX!

**Comment by slowbuss** [comment]
THZ!
