### ISSUE TITLE
Mention Case Sensitivity In CODEOWNERS Docs

### ISSUE THREAD

**Issue by chrisgarber** [github/docs#12760]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What part(s) of the article would you like to see updated?

Some mention that codeowners file paths are case sensitive, even if developing on case insensitive systems. I've seen this in other articles, but I think it belongs in the official documentation.

It might also be good to list a few examples demonstrating the case sensitive behavior.

**Comment by ramyaparimi** [comment]
@chrisgarber

**Comment by skedwards88** [comment]
Thanks for opening this issue! This sounds like a good addition to the documentation. You or anyone else is welcome to open a PR to address this.

**Comment by Wadewas74** [comment]
[![Node.js Tests](https://github.com/github/docs/actions/workflows/test.yml/badge.svg)](https://github.com/github/docs/actions/workflows/test.yml)
