### ISSUE TITLE
Encountered a GitHub website error

### ISSUE THREAD

**Issue by yikf** [github/docs#12789]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

website

### What part(s) of the article would you like to see updated?

website

### Additional information

![image](https://user-images.githubusercontent.com/51110188/145401305-bd9b9163-e738-457c-abb6-8b98dbb62b59.png)

Sorry for report on this place, I don't find the place where issue of the website should be reported.

**Comment by ramyaparimi** [comment]
@yikf 
Thanks for opening this issue! [GitHub support](https://support.github.com/contact) or [GitHub Support Community](https://github.community/) would be the best place to ask this question 💛
