### ISSUE TITLE
PR: merge-graphs reference old default branch name

### ISSUE THREAD

**Issue by sundhaug92** [github/docs#12783]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github

### What part(s) of the article would you like to see updated?

The diagrams below mention the old default branch rather than the current default branch

### Additional information

https://docs.github.com/assets/images/help/pull_requests/standard-merge-commit-diagram.png
https://docs.github.com/assets/images/help/pull_requests/commit-squashing-diagram.png

**Comment by ramyaparimi** [comment]
@sundhaug92 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
@sundhaug92 - thank you for spotting this bug and telling us about it. I'm looking into where the source files are kept and finding out the best way to update the diagrams.

**Comment by yazdanidana** [comment]
***@***.*** 09392430244ارسال شده از دستگاه Galaxy من
-------- پیام اصلی --------از: Felicity Chapman ***@***.***> تاریخ: ۲۰۲۲/۱/۱۱  ۱۶:۰۹  (GMT+03:30) گیرنده: github/docs ***@***.***> گیرنده کپی: Subscribed ***@***.***> موضوع Re: [github/docs] PR: merge-graphs reference old default branch name
  (Issue #12783) 
@sundhaug92 - thank you for spotting this bug and telling us about it. I'm looking into where the source files are kept and finding out the best way to update the diagrams.

**Comment by felicitymay** [comment]
@sundhaug92 - it looks as if we need to fix this issue with an internal PR. We hope to have this fixed within the next week or so.

**Comment by felicitymay** [comment]
@sundhaug92 - you should find that the article now has now diagrams with the new default branch name: [About merge methods on GitHub](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github)

**Comment by sundhaug92** [comment]
LGTM
