### ISSUE TITLE
Get a release asset doesn't mention 503

### ISSUE THREAD

**Issue by jsoref** [github/docs#12782]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/repos#get-a-release-asset

### What part(s) of the article would you like to see updated?

The status section lists:

> Found
Status: 302 Found

> Resource not found
Status: 404 Not Found

> Preview header missing
Status: 415 Unsupported Media Type

It doesn't list 503, which is apparently a thing:
https://github.com/github/feedback/discussions/8535

### Additional information

As an aside, the docs.github.com parser does not appear to approve of this content:

> To download the asset's binary content, set the `Accept` header of the request to [`application/octet-stream`](https://docs.github.com/rest/overview/media-types). The API will either redirect the client to the location, or stream it directly if possible. API clients should handle both a `200` or `302` response.

As it's rendered like this:

![image](https://user-images.githubusercontent.com/2119212/145330973-036b6915-7bef-41c0-906e-6a86ae02a158.png)

Instead of getting a nice blue link.

---

I'm here because I was looking at:
https://github.community/t/github-returns-503/216370

**Comment by ramyaparimi** [comment]
@jsoref I reviewed with the team and this is not something we are looking to document, so I am going to close this issue now :yellow_heart:
