### ISSUE TITLE
Caching dependencies to speed up workflows: misleading documentation about using relative paths in actions/cache@v2

### ISSUE THREAD

**Issue by zmwangx** [github/docs#12852]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows

### What part(s) of the article would you like to see updated?

In the "Using the cache action" section, under "Input parameters for the cache action":

> `path`: Required The file path on the runner to cache or restore. The path can be an absolute path or relative to the working directory.

The "relative to the working directory" part is misleading. The base of a relative path is in fact the GitHub workspace directory; it is not affected by `run.working_directory` of the step. I found this out in a job where I have a custom `defaults.run.working_directory`.

**Comment by m-github-org** [comment]
> ### کد رفتار
> * [x] من [قوانین رفتار](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md) پروژه GitHub Docs را خوانده ام و با آن موافقم[](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### چه مقاله ای در docs.github.com تحت تأثیر قرار می گیرد؟
> https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows
> 
> ### دوست دارید کدام بخش از مقاله به روز شود؟
> در بخش «استفاده از عملکرد حافظه پنهان»، در بخش «پارامترهای ورودی برای عملکرد حافظه پنهان»:
> 
> > `path`: مورد نیاز مسیر فایل در runner برای ذخیره یا بازیابی. مسیر می تواند یک مسیر مطلق یا نسبت به دایرکتوری کاری باشد.
> 
> بخش "نسبت به فهرست کار" گمراه کننده است. پایه یک مسیر نسبی در واقع دایرکتوری فضای کاری GitHub است. تحت تأثیر `run.working_directory`مرحله قرار نمی گیرد . من این را در شغلی فهمیدم که در آن یک سفارش دارم `defaults.run.working_directory`.
> 
> ### اطلاعات تکمیلی
> _بدون پاسخ_

#12858 #12859 #12860 #12857 #12856

**Comment by Mdbevabepari** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows
> 
> ### What part(s) of the article would you like to see updated?
> In the "Using the cache action" section, under "Input parameters for the cache action":
> 
> > `path`: Required The file path on the runner to cache or restore. The path can be an absolute path or relative to the working directory.
> 
> The "relative to the working directory" part is misleading. The base of a relative path is in fact the GitHub workspace directory; it is not affected by `run.working_directory` of the step. I found this out in a job where I have a custom `defaults.run.working_directory`.
> 
> ### Additional information
> _No response_

Bangladesh
