### ISSUE TITLE
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by Ttila111111** [github/docs#12966]
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

_Originally posted by @welcome[bot] in https://github.com/github/docs/issues/12930#issuecomment-992352519_

**Comment by Tigra777** [comment]
Привет подойти к тебе и сказать что ты мне нужен и как я понимаю что я хочу тебя обнять
