### ISSUE TITLE
Step missing in `gh auth login` credential caching flow: `gh auth setup-git`

### ISSUE THREAD

**Issue by corneliusroemer** [github/docs#13011]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git

### What part(s) of the article would you like to see updated?

Step 3 here is missing: https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git

`gh auth setup-git` is necessary to configure git to use the cached credentials. I had to guess this command, it's nowhere mentioned.

**Comment by skedwards88** [comment]
closed via https://github.com/github/docs/pull/13012#pullrequestreview-845553770
