### ISSUE TITLE
Update docs to match the new implementation of issue template checkboxes

### ISSUE THREAD

**Issue by alexus37** [github/docs#13016]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#attributes-4

### What part(s) of the article would you like to see updated?

The attribute `label` is not _Optional_ anymore so it should be changed to _Required_.

**Comment by ramyaparimi** [comment]
@alexus37 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ramyaparimi** [comment]
@alexus37 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by parallelsertu** [comment]
thanks for using it. But how to be a visible and useful tool.

**Comment by lecoursen** [comment]
Thanks @alexus37! Thanks for letting us know! You or anyone else is welcome to update that to required.

**Comment by sambhavsaxena** [comment]
is this a valid issue @alexus37 ?
