### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by 0374143570dot** [github/docs#1302]

**Comment by 0374143570dot** [comment]
(#1302

**Comment by aj1988aj** [comment]
_Sent from my Galaxy S9+ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
