### ISSUE TITLE
Add new example to Actions Code examples

### ISSUE THREAD

**Issue by peaceiris** [github/docs#1303]
### What article on docs.github.com is affected?

- Site: https://docs.github.com/en/free-pro-team@latest/actions - Code examples section
- File: https://github.com/github/docs/blob/main/data/variables/action_code_examples.yml

### What part(s) of the article would you like to see updated?

Add the [GitHub Pages Action] which is listed at the [Actions topic].

[GitHub Pages Action]: https://github.com/peaceiris/actions-gh-pages
[Actions topic]: https://github.com/topics/actions

> Why should the docs be changed?

To provide a workflow example to deploy a website to GitHub Pages for GitHub Actions users.

> What use cases does it support?

A workflow to publish static files to GitHub Pages with GitHub Actions and Static Site Generator. (Jekyll, Hugo, MkDocs, mdBook, Gatsby, Next.js, Nuxt.js, Docusaurus, Eleventy, and so on.)

> What is the expected outcome?

Users can find a workflow example to deploy their website to GitHub Pages using GitHub Actions.

### Additional information

I have opened a draft pull-request #1304.

**Comment by felicitymay** [comment]
👋🏻 Hi @peaceiris - just spotted that your issue should have been closed when your PR was merged: https://github.com/github/docs/pull/1304.

Thanks for raising this issue and the fixing PR 💖
