### ISSUE TITLE
https://github.com/github/docs/tree/main/content/github/collaborating-with-issues-and-pull-requests

### ISSUE THREAD

**Issue by 0374143570dot** [github/docs#1305]

**Comment by 0374143570dot** [comment]
https://github.com/github/docs/tree/main/content/github/collaborating-with-issues-and-pull-requests

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
