### ISSUE TITLE
Update troubleshooting topic: UseSharedCompilation also applies to .NET Framework projects

### ISSUE THREAD

**Issue by hubwriter** [github/docs#1308]
### What article on docs.github.com is affected?

Page on website: https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/troubleshooting-the-codeql-workflow#no-code-found-during-the-build

Source file: https://github.com/github/docs/blob/main/content/github/finding-security-vulnerabilities-and-errors-in-your-code/troubleshooting-the-codeql-workflow.md

### What part(s) of the article would you like to see updated?

In step 5 of the "No code found during the build" section, the following statement can also apply to .NET Framework projects:

> For C# projects using either `dotnet build` or `msbuild` which target .NET Core 2, you should specify `/p:UseSharedCompilation=false` in your workflow's `run` step, when you build your code. The `UseSharedCompilation` flag isn't necessary for .NET Core 3.0 and later.

Change this to: 

> For .NET Framework projects, and for C# projects using either `dotnet build` or `msbuild` that target .NET Core 2, you should specify `/p:UseSharedCompilation=false` in your workflow's `run` step, when you build your code. The `UseSharedCompilation` flag isn't necessary for .NET Core 3.0 and later.

**Comment by Perkles** [comment]
Hey @hubwriter  👋 
Can i have this one ?

**Comment by RubyDevil** [comment]
hello do u need javascript/html/css here?
