### ISSUE TITLE
about-git-subtree-merges still uses git URLs for the example remotes

### ISSUE THREAD

**Issue by matta** [github/docs#13100]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/using-git/about-git-subtree-merges

### What part(s) of the article would you like to see updated?

Suggest using `https://github.com/octocat/Spoon-Knife.git` instead of `git@github.com:octocat/Spoon-Knife.git` in the example commands.

**Comment by arzpgh60** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/get-started/using-git/about-git-subtree-merges
> 
> ### What part(s) of the article would you like to see updated?
> Suggest using `https://github.com/octocat/Spoon-Knife.git` instead of `git@github.com:octocat/Spoon-Knife.git` in the example commands.
> 
> ### Additional information
> _No response_

https://github.com/google/webauthndemo

**Comment by arzpgh60** [comment]
[https://github.com/google/webauthndemo]() #
#13141 #13140
