### ISSUE TITLE
Add note on macOS latest in GitHub hosted runners

### ISSUE THREAD

**Issue by logankilpatrick** [github/docs#13156]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#github-hosted-runners

### What part(s) of the article would you like to see updated?

Add a note at the bottom saying that `-latest` points to the latest available version which GitHub provides, not the latest available version open to the public. This is quite confusing and can lead to a situation as described below where you think you are running on the latest available OS but you are not.

### Additional information

I also opened a discussion here: https://github.com/github/feedback/discussions/9052

**Comment by logankilpatrick** [comment]
Here's a quick poll (albeit not perfect science) which shows that many folks do not understand what macOS-latest points too: https://twitter.com/OfficialLoganK/status/1472231281429823493?s=20

**Comment by ramyaparimi** [comment]
@logankilpatrick 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Apologies for the delay, @logankilpatrick! I'll quickly add a mention now

**Comment by BlizzyRaptor** [comment]
K so I'm understanding all of this now. Github isn't the enomy and I'm not
crazy. LoL it's all about the advertising and the people that view and
watch me. So I'm kinda popular?
