### ISSUE TITLE
The jobs.*.runs-on documentation is confusing

### ISSUE THREAD

**Issue by sylc** [github/docs#13272]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on

### What part(s) of the article would you like to see updated?

The article seems to imply that you can pass an array of string for the github hosted runners.
for example I was trying to do the below
```
jobs:
  my-job:
    runs-on: [ubuntu-latest, windows-latest]
```

however this produce the below behaviour
![image](https://user-images.githubusercontent.com/10268458/146904267-aa651ae8-4b32-4e51-8af1-33c8f04995cb.png)

It seems that the array of string is only allowed for a self-hosted runner. (not sure why this restriction BTW)

thanks

**Comment by sylc** [comment]
I came to realised that I need to use the strategy to run multiple os.

```
runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
```

Maybe the documentation could have just one more sentence something like:

_to run multiple os see  [strategy](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategy)_

if you disagree, feel free to close. 😄

**Comment by ramyaparimi** [comment]
@sylc

**Comment by skedwards88** [comment]
Thanks for this issue! I have seen a couple of recent issues/discussions expressing confusion over this, so I went ahead an opened a PR to clarify: https://github.com/github/docs/pull/13509

**Comment by Al31176** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
> 
> ### What part(s) of the article would you like to see updated?
> The article seems to imply that you can pass an array of string for the github hosted runners. for example I was trying to do the below
> 
> ```
> jobs:
>   my-job:
>     runs-on: [ubuntu-latest, windows-latest]
> ```
> 
> however this produce the below behaviour ![image](https://user-images.githubusercontent.com/10268458/146904267-aa651ae8-4b32-4e51-8af1-33c8f04995cb.png)
> 
> It seems that the array of string is only allowed for a self-hosted runner. (not sure why this restriction BTW)
> 
> thanks
> 
> ### Additional information
> _No response_
git clone https://github.com/github/docs
cd docs
npm ci
npm run build
npm start

**Comment by totallylost-helpme** [comment]
jobs:
  my-job:
    runs-on: [ubuntu-latest, windows-latest]
I didn't know I was so lost until today lol.
