### ISSUE TITLE
Uncollapsed sidebar items are a bit confusing

### ISSUE THREAD

**Issue by rachmari** [github/docs#133]
### Issue overview

When I open the [actions help docs page](https://help.github.com/en/actions), I thought the categories in the sidebar were arbitrarily uncollapsed, but I learned that the first three categories are uncollapsed by default. 

I didn't find it very intuitive why the first three categories were uncollapsed when viewing the page. I actually assumed that maybe the browser was caching some previous configuration of my viewing of that page or something. 🤷‍♀ I find it much easier to see the hierarchy of the docs when all of the categories are collapsed or just the active category uncollapsed.  

### Products affected by this issue

- [x] Dotcom (all products)
  - [ ] GitHub Free
  - [ ] GitHub Pro
  - [ ] GitHub Team
- [ ] GitHub Enterprise Cloud
- [ ] GitHub Enterprise Server (Versions: )
- [ ] API
- [ ] Desktop

/cc @github/product-docs-engineering

**Comment by janiceilene** [comment]
@chiedo Should we close this one out as we work towards a redesign?

**Comment by chiedo** [comment]
Yes!
