### ISSUE TITLE
Broken GitHub hosted runner README links

### ISSUE THREAD

**Issue by domdomegg** [github/docs#13336]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

### What part(s) of the article would you like to see updated?

The README links listed under "For the overall list of included tools for each runner operating system, see the links below"

### Additional information

PR raised to fix this: https://github.com/github/docs/pull/13337

**Comment by km185190** [comment]
Good catch! Just FYI, there's a duplicate PR for this change [here](https://github.com/github/docs/pull/13319). Once one of these PRs gets merged, someone should close the other one.

**Comment by Oishijayme** [comment]
Thank you

**Comment by Oishijayme** [comment]
<

> Thank you
