### ISSUE TITLE
Missing dependabot dependency maintenance when used not standard files 

### ISSUE THREAD

**Issue by cricketsamya** [github/docs#13348]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates

### What part(s) of the article would you like to see updated?

The article should explain how to maintain dependencies outside of `build.gradle`.

### Additional information

I have already prepared a PR, Please have a look!

**Comment by ramyaparimi** [comment]
@cricketsamya 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ramyaparimi** [comment]
@cricketsamya 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
