### ISSUE TITLE
update steps described in Adding an organization profile README

### ISSUE THREAD

**Issue by kum9748ar** [github/docs#13376]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile

### What part(s) of the article would you like to see updated?

Add image slides that describes how to customize and add an organization's **profile README**

**Comment by kum9748ar** [comment]
I have worked on it

**Comment by ramyaparimi** [comment]
The linked PR is still open!
