### ISSUE TITLE
Deadlinks in Hosted runner in Actions

### ISSUE THREAD

**Issue by tnir** [github/docs#13388]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Some links are dead in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software

### What changes are you suggesting?

All links should be valid in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software

### Additional information

actions/virtual-environments#4794

**Comment by miketimofeev** [comment]
PR https://github.com/github/docs-internal/pull/23973
