### ISSUE TITLE
Ubuntu 18.04 and Ubuntu 20.04 image links are broken

### ISSUE THREAD

**Issue by xSAVIKx** [github/docs#13502]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

### What part(s) of the article would you like to see updated?

Ubuntu 18.04 and Ubuntu 20.04 image links are broken

**Comment by ramyaparimi** [comment]
@xSAVIKx Thank you for opening this issue. This is already being fixed internally, so I am going to close this issue and the linked PR 💛.

Thanks so much for your interest in contributing to the GitHub docs 💖
