### ISSUE TITLE
Adding your SSH key to the ssh-agent still shows "$ ssh-add ~/.ssh/id_rsa" when it should show "$ ssh-add ~/.ssh/id_ed25519"

### ISSUE THREAD

**Issue by okbrown** [github/docs#1352]
### What article on docs.github.com is affected?
[Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

### What part(s) of the article would you like to see updated?
[Adding your SSH key to the ssh-agent](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent)

As a Linux user (have not tested to see for other OS') I see this
<img src="https://i.imgur.com/t8H9erb.png"/>

As you can see it states to run the command `$ ssh-add ~/.ssh/id_rsa` however by this point you have created a `id_ed25519` ssh key so this will not work. For novices or people who like "TLDR" this will be confusing and create a bad user experience.

### Additional information
I did fork the docs repo in an attempt to update it, but then I came across an unexpected element I was not aware of. The .md files use templating and inject data into the view e.g. `{% data reusables.ssh.dsa-support %}`. 

After more digging, I found `https://github.com/github/docs/blob/main/data/reusables/ssh/add-ssh-key-to-ssh-agent-commandline.md` which is where it would appear its coming from.

- I would like someone to confirm does this [page](https://github.com/github/docs/edit/main/content/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account.md) toggle between different views based on operating systems ?
- changing the above ssh agent .md file would that change it for all views?
- just guessing here so apologies if I am wrong.

Thanks.

**Comment by janiceilene** [comment]
👋 @okbrown I think there are a few open PRs opened about this issue that are waiting for review (https://github.com/github/docs/pulls?q=is%3Apr+is%3Aopen+ssh), so hopefully this will be fixed up soon 🤞 

> I would like someone to confirm does this page toggle between different views based on operating systems ?

Yep! We add tags like `{% mac %}` and `{% endmac %}` to a page to allow toggling between the different operating systems.

> changing the above ssh agent .md file would that change it for all views?

It needs to be changed between each set of tags to change it for each operating system.

**Comment by punkan** [comment]
xpub6CHZXpMGHJ86fQh3gpeTc2gMcBpq12QBpm9YjW4svPH8j93ZyeXYzrc7yPmrwhuQ3uyJEXJCWN3xX2jpTDQYv4GwJa3rMt2u5zt25JjevBg

**Comment by shati-patel** [comment]
Thank you for reporting the bug and helping us improve our docs, @okbrown! 🎉 

This has now been fixed.
