### ISSUE TITLE
Code Review settings available on any public project; docs say otherwise

### ISSUE THREAD

**Issue by CaptainEmerson** [github/docs#13539]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

docs/content/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team.md

### What part(s) of the article would you like to see updated?

```
Code review settings are available with GitHub Team, GitHub Enterprise Server 2.20+, and GitHub Enterprise Cloud. For more information, see "GitHub's products."
```

### Additional information

I don't think the statement above is true. Code review settings are available for any public project. Private projects are probably subject to the above statement.

**Comment by lecoursen** [comment]
Thanks @CaptainEmerson! I'm checking in with the team internally to find out the details of this feature availability and will update this issue when I do!

**Comment by lecoursen** [comment]
@CaptainEmerson, according to the team, code review settings should be available in all public repositories owned by any organization, and all private repositories owned by organizations on Team and Enterprise Cloud or Enterprise Server. You or anyone else is welcome to open a PR updating that callout to clarify that!
