### ISSUE TITLE
Default the configuration page for self-hosted runners to Linux

### ISSUE THREAD

**Issue by jenschelkopf** [github/docs#136]
### Issue overview

The 'Configuring the self-hosted runner application as a service' page has tabs for specific instructions for Mac, Windows, and Linux.

Currently, the default tab is Mac.

Let's change the default to Linux, as this is the most common for our users.

![image](https://user-images.githubusercontent.com/1865328/82494939-f5ae0c00-9aaf-11ea-93a0-80dd439160ac.png)

### Products affected by this issue

_to be completed by the core product docs team first responder_

- [x] Dotcom (all products)
  - [ ] GitHub Free
  - [ ] GitHub Pro
  - [ ] GitHub Team
- [ ] GitHub Enterprise Cloud
- [ ] GitHub Enterprise Server (Versions: )
- [ ] API
- [ ] Desktop

_*Note:* The doctocat who triages this issue may invite you to open a PR to address it. Doing so is absolutely not required, though it's helpful for a speedy fix! Someone from our team will work with you to take your changes across the finish line._

/cc @github/product-docs-core

**Comment by Simran-B** [comment]
> it looks like Linux does appear first in the content

What determines the order of the tabs? If it's not the content, and if it's also not sorted alphabetically (it's Mac, Windows, Linux in above screenshot), then how does the current tab order come about?

**Comment by zeke** [comment]
> What determines the order of the tabs? 

Here's the HTML for the tabs: https://github.com/github/docs/blob/5395b9371056e7c8eb9b649e5c1de4de80613155/includes/article.html#L31:L40

Here's the JavaScript file that dynamically updates the tabs and the displayed content on page load: https://github.com/github/docs/blob/main/javascripts/display-platform-specific-content.js

Here's the file where tests should be added for any changes to the existing platform-switching behavior: https://github.com/github/docs/blob/main/tests/browser/browser.js (Note that the platform-switching feature was added before we added this Puppeteer headless browser testing capability, so there are no existing browser tests for the current platform-switching functionality)

I hope that helps, @Simran-B!

**Comment by Simran-B** [comment]
Thanks @zeke for all the information! I created a PR: #1917

> Currently, the default tab is Mac.

This isn't the case (anymore?), the default tab is based on the user's operating system, which falls back to Mac if it's none of the supported platforms.

**Comment by jenschelkopf** [comment]
IMO, the tab should not default to the user's OS. The user's OS is not related to the user's runner type. Linux is by far the most common runner type, so we should default to Linux always.

**Comment by Simran-B** [comment]
I agree that it does not make sense for runners, but what about pages like this one?
https://docs.github.com/en/free-pro-team@latest/desktop/installing-and-configuring-github-desktop/getting-started-with-github-desktop

For the actions docs, Linux can be set as defaultPlatform with my PR.

**Comment by janiceilene** [comment]
It looks like the work for this one was completed in https://github.com/github/docs/pull/1917, so I'm going to close this out!

**Comment by Simran-B** [comment]
Yup, see the documentation about the `defaultPlatform` frontmatter here: https://github.com/github/docs/blob/main/content/README.md#defaultplatform
