### ISSUE TITLE
Expressions: issues with "returns"

### ISSUE THREAD

**Issue by Arthur-Milchior** [github/docs#13615]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

 https://docs.github.com/en/actions/learn-github-actions/expressions 

### What part(s) of the article would you like to see updated?

sometime, there are issues with "returns"

In particular, for `format`, "returns" is given before the expression, which is strange to read. In all other examples, the returned value is given after the expression.
Also: 
`contains(github.event.issue.labels.*.name, 'bug')` does not indicate which value is returned. Since `github.event.issue.labels.*.name` is not obviously an array, and it's content is not clear unless you already know what is the value of this property. So this is not really a clear exemple. I believe using an explicit array here would be far better.

**Comment by Jackieg81710** [comment]
No returns

**Comment by Arthur-Milchior** [comment]
I beg your pardon @Jackieg81710 but I fear that I don't know what your answer mean.
Do you mean it's normal there is no return nor any explanation in the case for the `contains` with array? Does it mean that there should be no explanation of what the code "return" anywhere?

**Comment by Jackieg81710** [comment]
When I had first downloaded the app I was playing around with everything and accidentally created my own issue with that  and you are correct, that's not an answer.
