### ISSUE TITLE
As the year winds down and comes to a close, over the holidays many here at GitHub are going to be taking time off to relax, recuperate, spend time with their families and loved ones, and reflect on the year that’s gone before. Additionally, this year has continued to be particularly stressful, causing some open source projects to announce that they’re taking it slow for the final month of the year. We found [the example set by the Electron project in their blog post](https://www.electronjs.org/blog/a-quiet-place-21) to be particularly poignant. Following their example, we’ve decided that we also will be taking some extra time and may be slow to respond for the rest of the year.

### ISSUE THREAD

**Issue by Selena20191** [github/docs#13637]
As the year winds down and comes to a close, over the holidays many here at GitHub are going to be taking time off to relax, recuperate, spend time with their families and loved ones, and reflect on the year that’s gone before. Additionally, this year has continued to be particularly stressful, causing some open source projects to announce that they’re taking it slow for the final month of the year. We found [the example set by the Electron project in their blog post](https://www.electronjs.org/blog/a-quiet-place-21) to be particularly poignant. Following their example, we’ve decided that we also will be taking some extra time and may be slow to respond for the rest of the year.

In specific, for the rest of November and all of December 2021, we’ll continue to cover mission-critical activities, but full review of issues and PRs may have to wait until the new year. Please feel free to continue to contribute, we simply ask that you remain patient with us as we give everyone a well-deserved chance to pause, reflect, and recharge.

We wish each and every one of you the world over Happy Holidays and a peaceful and prosperous New Year!

_Originally posted by @ramyaparimi in https://github.com/github/docs/discussions/12249_

**Comment by MarzaElise** [comment]
huh
