### ISSUE TITLE
Replace localhost with 127.0.0.1 in OAuth examples

### ISSUE THREAD

**Issue by hickford** [github/docs#13651]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#localhost-redirect-urls
https://docs.github.com/en/rest/guides/basics-of-authentication#registering-your-app

### What part(s) of the article would you like to see updated?

Replace localhost with 127.0.0.1 in OAuth redirect/callback examples.

The OAuth spec https://datatracker.ietf.org/doc/html/rfc8252#section-8.3 recommends to use 127.0.0.1 instead of localhost:

>  While redirect URIs using localhost (i.e., "http://localhost:{port}/{path}") function similarly to loopback IP redirects described in Section 7.3, the use of localhost is NOT RECOMMENDED.  Specifying a redirect URI with the loopback IP literal rather than localhost avoids inadvertently listening on network interfaces other than the loopback interface.  It is also less susceptible to client-side firewalls and misconfigured host name resolution on the user's device.

**Comment by 88rogikl88** [comment]
237
H

вс, 2 янв. 2022 г., 17:49 welcome[bot] ***@***.***>:
