### ISSUE TITLE
Small screen resolution and icon display

### ISSUE THREAD

**Issue by mathieu-aubin** [github/docs#13662]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[docs/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository)

### What part(s) of the article would you like to see updated?

Precision on branch icon being hidden with some resultions which makes content irrelebant and confusing

### Additional information

tried to write a fix, see #13659

**Comment by Aymanramadan** [comment]
https://github.com/github/docs/pull/13659#issue-1092232724

**Comment by Aymanramadan** [comment]
Aymantalala@gmail.com
