### ISSUE TITLE
Improve the first step.  

### ISSUE THREAD

**Issue by scott-lydon** [github/docs#13683]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/edit/main/content/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.md

### What part(s) of the article would you like to see updated?

The first step provides insufficient information

"Copy the SSH public key to your clipboard." 

Where does one get this key? That might be helpful.

Or better yet.  Why not include the [first step](https://docs.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) as the first step instead of a preface/side note.  

### Additional information

na

**Comment by masumh** [comment]
Please help
