### ISSUE TITLE
Typo fixes for docs

### ISSUE THREAD

**Issue by AAugustine** [github/docs#13710]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.1/admin/github-actions/getting-started-with-github-actions-for-your-enterprise/introducing-github-actions-to-your-enterprise

### What part(s) of the article would you like to see updated?

Typos in two different sections titled "Governance and compliance" & "Security considerations for third-party actions"

**Comment by natiana21** [comment]
N/a
