### ISSUE TITLE
Missing detailed usage report on Codespaces billing docs

### ISSUE THREAD

**Issue by 2percentsilk** [github/docs#13723]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-billing-for-github-codespaces/viewing-your-codespaces-usage

### What part(s) of the article would you like to see updated?

Adding an additional step to export the data.

**Comment by wahidsetu26-eng** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/billing/managing-billing-for-github-codespaces/viewing-your-codespaces-usage
> 
> ### What part(s) of the article would you like to see updated?
> Adding an additional step to export the data.
> 
> ### Additional information
> _No response_

Thank you
