### ISSUE TITLE
Debugg
Intergrade 
Gnu
Mit
Release
Open source
Intellectual property righs

### ISSUE THREAD

**Issue by erc20pixel** [github/docs#13757]
https://github.com/binance/binance-api-swagger/releases/tag/v1.4.0

**Comment by erc20pixel** [comment]
[]()





      **
Debugg log 

Pull
Debugg

Merge
Debugg

Intergrade
Debugg

Debugg
Intertrade

Release

Binance

[]()

**Comment by PattanaiSgulrax** [comment]
Support ธนาคารแห่งประเทศไทย

**Comment by masumh** [comment]
Please help me
