### ISSUE TITLE
Document VM Architecture for GitHub Hosted Runners

### ISSUE THREAD

**Issue by bnb** [github/docs#13794]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

### What part(s) of the article would you like to see updated?

At present, it doesn't seem that there's any mention of the architectures (for example, x86, x64, armv7, arm64) that are supported. Even if there's only one supported (I wouldn't be shocked if they're all the same!), it would be really helpful to have that documented for use cases where an end-user is running a build where architecture matters.

### Additional information

I'm looking to cross-reference the GitHub Hosted Actions Runners with a support matrix for a major open source project to consider migrating to Actions as our primary CI rather than a self-hosted Jenkins instance. We support a very large number of architectures, so knowing which we'd need to set up self-hosted VMs for would be extremely helpful.

**Comment by ramyaparimi** [comment]
@bnb 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by bnb** [comment]
updated the additional information with some "why" context :)

**Comment by ethomson** [comment]
Hey @bnb !  It's all amd64 all the time.  😁  I agree that this is something that we should be more crisp on in our docs.  We'll put this in the backlog (but if you wanted to open a PR in the meantime, obviously we would be very grateful indeed! 🙏 )

**Comment by yadunandanbhat** [comment]
Can I work on this? but i might need some help.
So what needs to be updated is the "Supported hardware" in the GitHub hosted actions runners doc, where in the CPU section "amd64" should be added as the supported architecture of the systems. Right?
