### ISSUE TITLE
Are github.head_ref and github.base_ref null when not a pull request?

### ISSUE THREAD

**Issue by dlech** [github/docs#13810]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

### What part(s) of the article would you like to see updated?

> The base_ref or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.

Stating that the property is not available is ambiguous. If I use `${{ github.base_ref }}` in an action, does it return `null`, does it cause an error, or something else if the trigger is not a pull request?

### Additional information

The same clarification is needed for `github.base_ref`.

**Comment by ramyaparimi** [comment]
@dlech 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Yep! The docs have now .been updated to state this.

**Comment by YashNagayach95** [comment]
How to get the target branch on push event (Not a PR yet)?
Target branch here I mean is main branch from where I created my own foo branch.
I need the target branch so that I can calculate the baseBranchCoverage on every push event.
Any suggestions?

**Comment by cmwilson21** [comment]
@YashNagayach95 👋  This question would best be handled by our [support team](https://support.github.com/request). Please reach out to them.

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue. 💛

**Comment by malachid** [comment]
Coming across this a year later, I can say that the link in the original description is still ambiguous and does not appear to have actually been resolved.  It states that it is not available; it does not state how you validate whether it is set.
