### ISSUE TITLE
Actions Memory Recs are incorrect

### ISSUE THREAD

**Issue by kwacky1** [github/docs#13870]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.3/admin/installation/setting-up-a-github-enterprise-server-instance/installing-github-enterprise-server-on-vmware#minimum-requirements

### What part(s) of the article would you like to see updated?

The memory on these lines needs to be swapped

```
16 | 160 GB | 700 jobs
32 | 128 GB | 1300 jobs
```

**Comment by arnishat** [comment]
[ARNishatOfficial](https://youtube.com/c/ARNishatOfficial)
