### ISSUE TITLE
Use operationId for `#anchor` tags of REST API endpoint titles

### ISSUE THREAD

**Issue by gr2m** [github/docs#139]
### What feature or product is affected?

- [x] REST API

### What is the new or expected behavior?

Example

> https://docs.github.com/en/rest/reference/repos#check-if-vulnerability-alerts-are-enabled-for-a-repository

would become

> https://docs.github.com/en/rest/reference/repos#check-vulnerability-alerts

See OpenAPI spec at https://github.com/github/openapi/blob/347c7c385184352692d4118b7e8a266ccf9b7db7/definitions/operations/repos/check-vulnerability-alerts.yml#L6

### How is the old or inaccurate behavior currently documented?

n/a

### Who does this affect?

Every change to an `#anchor` name for endpoint titles requires a change in the code, due to the error handlers which include a URL to the documentation. The endpoint titles are more prone to changes, while operation IDs should be changed much less frequently, as they are consider a breaking change to some of the OpenAPI consumers, while the `"summary"` key is not. 

The problem with the title changes might also be amplified once translations are introduced.

@zeke sent me here, we shortly discussed it today:

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/39992/88490749-b76f1600-cf52-11ea-818f-439559206511.png">

### What is the impact to users?

n/a

### Content strategy and implementation

tbd

**Comment by chiedo** [comment]
@nschonni this one may be worth looking at if you decide to spend more time making improvements to the codebase!

**Comment by katelynnashley95icloudcom** [comment]
- [x] [Bayes](www.bayesashley2200@gmail.com)

**Comment by SaultanBeagama** [comment]
> هل يعني إجراء هذا التغيير أننا سنكسر روابط الإرساء التي وضع الأشخاص إشارة مرجعية عليها بالفعل ، وإذا كان الأمر كذلك ، فهل نحن موافقون على ذلك؟

**Comment by mohamaed530** [comment]
![image](https://user-images.githubusercontent.com/82192872/129637015-9dee492e-5446-43c5-9fe2-abf4ff2ad06b.jpeg)

**Comment by Mint-6263** [comment]
:blush:

**Comment by DiddiLeija** [comment]
Hi everybody! As I can see, this issue is not resolved.  Can I work on it?

**Comment by heiskr** [comment]
I suspect it would be fine to simply switch to using the "summary key" as long as there are no duplicates on any page. We would be happy to have an open source contributor help with this task, as we will likely not prioritize this internally.

**Comment by Mobibaba121** [comment]
Payment it

**Comment by 1alan91** [comment]
[Park+](onboarding) 

> fastag`1`

**Comment by cmwilson21** [comment]
👋 Thanks all for the feedback in this issue. I spoke with the team and we are going to work on this internally. So I'm going to go ahead and close this issue. 

Thanks again! 💛
