### ISSUE TITLE
workflow_run event sample json is missing workflow_run and workflow properties

### ISSUE THREAD

**Issue by jsoref** [github/docs#13951]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-50

### What part(s) of the article would you like to see updated?

The sample json is incomplete.

The [documentation above](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-51) says:
> Webhook payload object

Key | Type | Description | _Included in example json_
-- | -- | -- | --
action | string | The action that was performed. Can be one of requested or completed. | ✔️ 
workflow_run | object | The workflow run. Many workflow_run keys, such as head_branch, conclusion, and pull_requests are the same as those in a check_suite object. | ❌ 
workflow | object | The workflow that generated the workflow run. | ❌ 
organization | object | Webhook payloads contain the organization object when the webhook is configured for an organization or the event occurs from activity in a repository owned by an organization. | ✔️ 
repository | object | The repository where the event occurred. | ✔️ 
sender | object | The user that triggered the event. | ✔️ 

Here's a pretty collapsed view of the current JSON:
![image](https://user-images.githubusercontent.com/2119212/149017815-1c2c2b98-a716-491b-b6e6-e749e6eb3bb4.png)

### Additional information

I think #2767 added the referenced documentation.

If the sample json has multiple shapes, then it'd be nice if there were multiple examples of the distinct shapes, or at least some pointers explaining how someone could imagine the other shapes.

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for this issue! The docs now include these properties in the example payload.
