### ISSUE TITLE
LINKS: Not valid

### ISSUE THREAD

**Issue by bobychaudhary** [github/docs#13980]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/stylesheets/README.md

![gitDoc](https://user-images.githubusercontent.com/73424060/149178366-dc163ed0-7454-4af9-a340-08b221771abf.png)

### What changes are you suggesting?

# In the stylesheets blob,
[utility classes](https://styleguide.github.com/primer/utilities/) &

[styleguide.github.com/primer](https://styleguide.github.com/primer/)

**Comment by lucalves** [comment]
Hi @bobychaudhary! I went ahead and fixed them at #14006. Let's wait for the review.
