### ISSUE TITLE
Underdocumented CODEOWNERS syntax

### ISSUE THREAD

**Issue by rdelfin** [github/docs#1407]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax

### What part(s) of the article would you like to see updated?

The `CODEOWNERS syntax` seems to not document valid syntax properly. As we recently found on one of our repos, this is invalid:
```
/directory/to/code       @orgname/myteam-owners  # a comment
```
Because the inline comment syntax is unsupported. However, `.gitignore` files do seem to support these comment types. Are there any other exceptions to the `.gitignore` syntax that are not documented?

### Additional information

N/A

**Comment by johnmarkwayve** [comment]
N.B. the effect of any syntax error also appears to be that the enitre file is silently ignored, meaning these issues can persist for some time before being discovered

**Comment by janiceilene** [comment]
Does this line from the [CODEOWNERS syntax](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax) section cover the information you're looking for?

> If any line in your CODEOWNERS file contains invalid syntax, the file will not be detected and will not be used to request reviews. Invalid syntax includes inline comments and user or team names that do not exist on GitHub.

We could change the line at the beginning of that section from:

> A CODEOWNERS file uses a pattern that follows the same rules used in gitignore files.

To something like this:

> A CODEOWNERS file uses a pattern that follows most of the rules used in gitignore files.

Anyone is welcome to open a PR to update that line!

**Comment by StarTrooper08** [comment]
@janiceilene can I work on this issue #1407 ??

**Comment by rdelfin** [comment]
@janiceilene that would help clarify! Do you know where the full spec for a CODEOWNERS is? I'd be glad to put in a PR too, but I'm not sure where to look for what defines this syntax

**Comment by janiceilene** [comment]
@rdelfin I'm chatting with some folks internally to pull that together, but it'll take me until next week (lots of folks are out for the holidays). Please feel free to ping me a reminder in this issue to followup if I forget next week 💛

**Comment by rdelfin** [comment]
Appreciate you talking to people about this! I forget it's Thanksgiving over there. I'll ping you in a week as a reminder if you forget

**Comment by sanchaitriyasutt** [comment]
`slotxo/Cc+SL0985129186$$$$$`

**Comment by nitishgoukonde** [comment]
![Uploading image.png…]()

**Comment by ajs256** [comment]
Hey there @janiceilene, any updates on this?

**Comment by janiceilene** [comment]
Thanks for the reminder ping @ajs256! After chatting with some folks in engineering who read through the gitignore syntax docs, it looks like:

- we don't support the negation operator that gitignore does, where prefacing a pattern with `!` makes a negative match.
- we don't support using `[]` brackets to define a character range.
- we don't support starting a pattern with `#` by escaping it with `\` (so it isn't considered a line comment.)

If someone wants to add those exceptions (they need a bit of a rewrite and polish 💅 ) to [CODEOWNERS syntax](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax) that would be amazing!

**Comment by ajs256** [comment]
@janiceilene, just pushed to #1551! If you could look over it when you get a chance, that'd be great.

**Comment by hovox** [comment]
> Thanks for the reminder ping @ajs256! After chatting with some folks in engineering who read through the gitignore syntax docs, it looks like:
> 
> * we don't support the negation operator that gitignore does, where prefacing a pattern with `!` makes a negative match.
> * we don't support using `[]` brackets to define a character range.
> * we don't support starting a pattern with `#` by escaping it with `\` (so it isn't considered a line comment.)
> 
> If you want to add those exceptions (they need a bit of a rewrite and polish 💅 ) to [CODEOWNERS syntax](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax) that would be amazing!

I have found another case where gitignore format does not matches with CODEOWNERS format, here is the part coped from the doc:
 >  # The `docs/*` pattern will match files like
     # `docs/getting-started.md` but not further nested files like
     # `docs/build-app/troubleshooting.md`.
     docs/*  docs@example.com
In gitignore format `docs/*` should match  any files or folders below `docs`, e.g. `docs/build-app/troubleshooting.md` this should be a match by gitignore format, we can check that with https://www.npmjs.com/package/ignore lib too.
