### ISSUE TITLE
Something somewhere should describe the top right corner icons and how they work (notifications, repository menu, user menu)

### ISSUE THREAD

**Issue by bbarry** [github/docs#1408]
### What article on docs.github.com is affected?

maybe https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/about-your-personal-dashboard ??

maybe https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/managing-notifications-from-your-inbox

### What part(s) of the article would you like to see updated?

I opened up github this morning and had the little blue? (I'm colorblind and not really sure if that is right) icon over both the normal notifications button as well as on my user menu. The one on the user menu doesn't seem tied to any feature that I could figure out (got it eventually determined to be a feature preview notification by clicking around until it disappeared).

I am not sure if this is a docs issue or a UX issue or something else but there are probably others out there who have no idea what that overlay is trying to tell them and the only way I can see to figure it out is brute force.

**Comment by janiceilene** [comment]
👋 @bbarry Thanks for opening an issue! We have an article about feature preview, [Exploring early access releases with feature preview](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/about-your-personal-dashboard), but it doesn't include that notification. 

I think it could benefit from: 
- [ ] a new sentence explaining that the blue dot indicates a new available feature in feature preview, maybe with the conceptual information at the beginning of the "Exploring beta releases with feature preview" section.

**Comment by punkan** [comment]
> ### บทความใดใน docs.github.com ได้รับผลกระทบ
> อาจจะhttps://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/about-your-personal-dashboard ??
> 
> อาจจะhttps://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/managing-notifications-from-your-inbox
> 
> ### คุณต้องการดูส่วนใดของบทความที่อัปเดต
> ฉันเปิด github เมื่อเช้านี้และมีสีน้ำเงินเล็กน้อย? (ฉันตาบอดสีและไม่แน่ใจจริงๆว่าถูกต้องหรือเปล่า) บนปุ่มการแจ้งเตือนปกติและบนเมนูผู้ใช้ของฉัน รายการในเมนูผู้ใช้ดูเหมือนจะไม่เชื่อมโยงกับคุณสมบัติใด ๆ ที่ฉันคิดได้ (ในที่สุดก็ถูกกำหนดให้เป็นการแจ้งเตือนตัวอย่างฟีเจอร์โดยคลิกไปรอบ ๆ จนกว่าจะหายไป)
> 
> ฉันไม่แน่ใจว่านี่เป็นปัญหาเอกสารหรือปัญหา UX หรืออย่างอื่น แต่อาจมีคนอื่น ๆ ที่ไม่รู้ว่าการซ้อนทับนั้นพยายามบอกอะไรพวกเขาและวิธีเดียวที่ฉันเห็นเพื่อคิดออกคือกำลังดุร้าย .
> 
> ### Additional information

**Comment by punkan** [comment]
31a9e316-77d2-4c08-acc1-5c2a074b21cd

**Comment by ramyaparimi** [comment]
@bbarry Sorry it took this long 💛 This sounds like a UX issue, could you please contact https://support.github.com/contact/feedback 💛

Thanks so much for contributing to the GitHub docs 💖
