### ISSUE TITLE
Beta API graphql queries incorrect in documentation

### ISSUE THREAD

**Issue by sarina** [github/docs#14109]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Finding the node ID of an organizational project, both the single project and first 20 on [this page](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects#finding-the-node-id-of-an-organization-project)

When I run the query specified in the docs, subbing in my organization and board (public project, so should work for anyone authed):

```
gh api graphql -f query='                                                                                                                            
  query{                                                                                                                                             
    organization(login: "openedx"){                                                                                                                  
      projectNext(number: 8) {                                                                                                                       
           id                                                                                                                                        
      }                                                                                                                                              
    }                                                                                                                                                
  }'
```

I repeatedly get the following response:
```
{
  "data": {
    "organization": {
      "projectNext": null
    }
  }
}
```

I can't check out the rest of the API as I need node IDs moving forward

### What changes are you suggesting?

Update the documentation to the correct example queries

**Comment by ramyaparimi** [comment]
@sarina 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by sonofrangerSe11** [comment]
Hi there I could really use your help with something.  Sent from Yahoo Mail on Android 
 
  On Mon, Jan 17, 2022 at 4:54 AM, Ramya ***@***.***> wrote:   


@sarina
Thanks so much for opening an issue! I'll triage this for the team to take a look 👀

**Comment by sonofrangerSe11** [comment]
I'm going to get you bitch the fuck out of my account Sent from Yahoo Mail on AnOn Mon, Jan 17, 2022 at 6:37 AM, sonofrangerSe11
***@***.***> wrote:   


Hi there I could really use your help with something.  Sent from Yahoo Mail on Android 
 
 On Mon, Jan 17, 2022 at 4:54 AM, Ramya ***@***.***> wrote: 


@sarina
Thanks so much for opening an issue! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
Did you make sure to authenticate as described [here](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects#authentication)? If you still receive this error when properly authenticated, you will want to reach out in https://github.com/github/feedback/discussions/categories/issues-feedback
