### ISSUE TITLE
`workflow_run` action event documentation very unclear

### ISSUE THREAD

**Issue by saevarb** [github/docs#14205]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run

### What part(s) of the article would you like to see updated?

The former link above does not include any information whatsoever about this very strange limitation regarding `workflow_run` only running on the default branch. 

Moreover, if you do finally find the second link somehow, the *entirety* of the explanation you get is: 

> Note: This event will only trigger a workflow run if the workflow file is on the default branch.

Which honestly is super vague. What exactly does it mean? Does it mean that it will only run if you ensure that the new workflow file has been added to the default branch? Does it mean that `workflow_run` only ever works for workflows triggered by the default branch?

It turns out it's actually the latter, which IMO is the most unlikely of the explanations, because it feels like a very arbitrary(and incredibly tedious) limitation.

### Additional information

I've been trying to find more documentation on `workflow_run` but there is really not a lot to find except the two links above, and then various github issues and support threads with people roughly as confused as myself.

From what I have gathered, it seems as if `workflow_run` will only ever run for workflows triggered by the default branch. Is this really true? 

Getting workflows(or any CI pipeline) to work correctly is usually a really tedious process of trial and error where the only thing you can do is make changes, push, then wait X minutes until it's done or it fails, then rinse and repeat. There is really no reliable way around this from what I have gathered. Naturally, littering your git commit history with 100s of one-liner commits because you are messing with workflows is not acceptable, so the usual way that I go about it is to have a specific branch for it which I then force push to. This generally works fine.

But if I understand the `workflow_run` limitations, then the only way I can possibly get such a workflow running is to either 1) push 100s of garbage commits to my default branch so that I don't break history 2) actually force push to my default branch

Neither of these are acceptable solutions for what seems to be a very arbitrary limitation. I would really love to be proven wrong about this and/or pointed to some documentation about how to best to go about this.

**Comment by ramyaparimi** [comment]
@saevarb 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by skedwards88** [comment]
Your triggered workflow (the workflow that contains `on: workflow_run`) must be on the default branch. However, your triggering workflow can be on any branch (like in [this example](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#limiting-your-workflow-to-run-based-on-branches)).
