### ISSUE TITLE
Example link points to localhost:4000

### ISSUE THREAD

**Issue by TapTap21** [github/docs#14234]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
![image](https://user-images.githubusercontent.com/31740134/149915011-4d612460-5cc9-4af8-95dc-050ea23ba31c.png)

### What changes are you suggesting?

The "push event" hyperlink points to `http://localhost:4000/en/actions/learn-github-actions/events-that-trigger-workflows#push`

This should point to the push event documentation `https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push`

**Comment by ramyaparimi** [comment]
@TapTap21 Thanks for opening this issue ✨  You or anyone else is welcome to open a PR with a fix ✨

**Comment by Mr-Camargo** [comment]
Hello there!

As you may have noticed, I opened #14250 that resolves this issue, thank you for letting me help!
