### ISSUE TITLE
Improve double table of contents

### ISSUE THREAD

**Issue by hiimbex** [github/docs#1425]
### What is the current behavior?

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#contents is a particularly potent example, but this applies to `https://docs.github.com/en/free-pro-team@latest/rest/reference/*` as well

### What changes are you suggesting?

Right not there's this weird thing with the table of contents being on the left and the sub-table of contents being on the right, but the right hand portion does not scroll with where you are on the page.

I'd prefer to have a single pane of navigation rather than left and right table of contents; however, at a minimum I'd expect the right hand portion to be able to keep up with where I am scrolled on the page

**Comment by simpsoka** [comment]
Thanks for opening this @hiimbex! The left sidebar is the main navigation for the site, and it's contextual to the page (or section of docs) that you're reading about. I know it might be confusing, but it's not actually a table of contents for the page you're reading. For this reason, and others, we're actually re-vamping the navigation and will be deprecating the sidebar navigation for a top of page navigation that's more traditional. I don't have an issue open for this yet, but we can add one when we get closer to that project - but I believe this change will eliminate the confusion between the two navigational systems.
