### ISSUE TITLE
Broken filter pattern cheat sheet links on Triggering a workflow section

### ISSUE THREAD

**Issue by cerino-ligutom** [github/docs#14275]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

### What part(s) of the article would you like to see updated?

The filter pattern cheat sheet links on [Triggering a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow) section are currently broken. Looked around where this might be referring to and I'm guessing it's talking about [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).

**Comment by nikkobolima06** [comment]
![card](https://user-images.githubusercontent.com/98059119/150235207-73ef8f55-4392-40dc-9a87-3d55924e4a5c.png)

**Comment by nikkobolima06** [comment]
@
![GitHub_Logo](https://user-images.githubusercontent.com/98059119/150232967-686dec7f-b489-460c-b5e9-18ad82d2edb6.png)
