### ISSUE TITLE
Move lib/*.js files used only in tests to tests/lib (or something)

### ISSUE THREAD

**Issue by JasonEtco** [github/docs#143]
While reviewing github/docs-internal#15734, I had a difficult time grokking which code was used during runtime vs. only in tests/local scripts. I've thought that a couple of times - we don't currently have a clear separation of that code. Generally speaking, `lib` is used for runtime code - stuff to run the server. Code solely used for tests often lives in like a `tests/helpers` directory or something.

Interested in how y'all feel @github/docs-engineering, if this is just me or if others have felt this confusion as well.

**Comment by JamesMGreene** [comment]
NOTE: With this, we should also review which of are Node `dependencies` are actually `devDependencies` that should be moved in the `package.json`.
