### ISSUE TITLE
Actions doc is wrong about what macos-latest means

### ISSUE THREAD

**Issue by tuffnatty** [github/docs#14438]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

### What part(s) of the article would you like to see updated?

The docs say:

> The macos-latest label currently uses the macOS 10.15 runner image.

This seems to be wrong at the moment, the runner logs say OS is 11.6.2, so one has to use `macos-10.15` to get a compatible build.

**Comment by lucascosti** [comment]
Apologies for the delayed response, and thanks for reporting this, @tuffnatty.

This has been fixed and should now refer to the correct versions.
