### ISSUE TITLE
Expressions / Literals should mention include `'` and `"` and explicitly mention `double quotes`

### ISSUE THREAD

**Issue by jsoref** [github/docs#14519]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#literals

### What part(s) of the article would you like to see updated?

Data type | Literal value
-- | --
string | You must use single quotes. Escape literal single-quotes with a single quote.

```diff
-You must use single quotes. Escape literal single-quotes with a single quote.
+You must use single quotes (`'`). To use a literal single-quote (`'`), use a pair of single quotes (`''`). Double quotes (`"`) will not work but will result in a confusing error. 
```

### Additional information

I lost too much time trying to figure out why my double quoted strings weren't working.

> The workflow is not valid. .github/workflows/test.yml (Line: 84, Col: 11): Unexpected symbol: '"success"'. Located at position 28 within expression: (steps.retrieve.outcome == "success") || (steps.find.outcome == "success")

There are parsers that yield more friendly errors, some spit out their grammar, in the form of:
> expected `'`, `0-9`, `false`, or `true`

... or something like that.

Also, friendlier error reporting generally reports errors based on the cursor of the file and not a substring of.a substring. In case people are wondering, the cursor position for the `"` is not equal to `11 + 28`, the `${{ ` token doesn't appear to be considered.

**Comment by poptarteaters** [comment]
Y'all are all so cool!

**Comment by ramyaparimi** [comment]
@jsoref Thank you for opening this issue and giving all the relevant information ✨ . I will get this triaged for a writer's review 👀

**Comment by nimasahebkar40** [comment]
در تاریخ دوشنبه ۲۴ ژانویهٔ ۲۰۲۲،‏ ۹:۱۶ ب.ظ Ramya Parimi <
***@***.***> نوشت:

**Comment by skedwards88** [comment]
Thanks for opening this issue! You or anyone else is welcome to open a PR to add clarification and/or an example.
