### ISSUE TITLE
Would y'all like to meet Bertha and Daisy?!

### ISSUE THREAD

**Issue by poptarteaters** [github/docs#14547]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I bet y'all would love to see Bertha and Daisy for the first time!!!

### What part(s) of the article would you like to see updated?

Yep yep

### Additional information

Of course!

**Comment by Jebb4ver** [comment]
Look good to me
