### ISSUE TITLE
Explanation of using relative paths in an entrypoint causing confusion

### ISSUE THREAD

**Issue by nikola-jokic** [github/docs#14551]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Dockerfile support](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions)

### What part(s) of the article would you like to see updated?

[ENTRYPOINT](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#entrypoint)

Due to an issue filed at [actions/runner #1088](https://github.com/actions/runner/issues/1088), I am filing the issue to resolve confusion about the `workdir` in an entrypoint

As the issue stated, documentation should be updated to reduce the confusion when using ENTRYPOINT with the relative path.

There should be a clear explanation about using absolute path if you are using `WORKDIR` inside the Dockerfile, and how to use it with the workdir override `--workdir /github/workspace`

**Comment by Darius1999boop** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by ramyaparimi** [comment]
@nikola-jokic 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thank you for opening this issue! You or anyone else is welcome to open a PR to address this.

**Comment by skedwards88** [comment]
Actually, I see you already have a PR for this issue 😄 I'll go ahead and link the PR.

**Comment by Maseeullahz** [comment]
Hi I want Make Website But in afghanistan All bank account blocked Could u help me to Make for me Free website?

King_Mlz
