### ISSUE TITLE
Adding `previous` and `next` links for moving between articles

### ISSUE THREAD

**Issue by zeke** [github/docs#146]
In https://github.com/github/help-docs/pull/11410 we introduced breadcrumbs. Under the hood, the breadcrumbs are generated by a `currentTree` object that captures the entire hierarchy of the site, relative to the page you're currently viewing. We can use this new tree to infer what pages precede and follow a given article.

Let's consider adding [Previous] and [Next] links below each article, where appropriate. We'll have to iron out the details of when these links should and should NOT be displayed:

- should these links be displayed for articles that don't have a parent map topic?
- does an article at the end of a map topic link to the next map topic?
- does an article at the beginning of a map topic link to the previous map topic?
- does an article at the end of the last map topic have a [next] link?
- etc

cc @github/product-docs-engineering @github/product-docs-content-strategy

**Comment by janiceilene** [comment]
@chiedo @emilyistoofunky Is this still relevant or should we close it out?

**Comment by emilyistoofunky** [comment]
I think this may be part of the learning track designs - @chiedo do you know?

**Comment by chiedo** [comment]
Yeah we can close this one out! We've got it tracked elsewhere.
