### ISSUE TITLE
Document `id-token` permission

### ISSUE THREAD

**Issue by danielcompton** [github/docs#14626]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/automatic-token-authentication

### What part(s) of the article would you like to see updated?

I'm looking into setting up OIDC authentication with GitHub Actions and am wanting to understand how the `id-token` permission works. I couldn't find much documentation about it, other than documentation saying to set it to `write`, e.g. https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings.

The automatic token authentication article talks about `id-token` and that the "Maximum access by forked repos" is `read`. What does it mean to have `read` access to the `id-token`? What is the minimum permissions needed to use OIDC?

Specifically, can a PR opened by Dependabot obtain OIDC credentials?

**Comment by ramyaparimi** [comment]
@danielcompton 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by N-Usha** [comment]
To generate an OIDC id-token from a GitHub workflow it requires write permissions on `id-token` bit. When we add this permission to workflow it will set the following two env variables (url and token) in runner machine, which will be used by [Actions/scripts to generate id token](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#updating-your-actions-for-oidc):
ACTIONS_ID_TOKEN_REQUEST_URL,  ACTIONS_ID_TOKEN_REQUEST_TOKEN

Thanks @danielcompton for reporting this. We will add the above context to our docs to make this more clear.

**Comment by danielcompton** [comment]
Thanks @N-Usha! What does it mean to have `id-token: read` then?

**Comment by N-Usha** [comment]
It just means that OIDC tokens cant be generated in that workflow. And we made that as the default as we wanted to make OIDC an opt-in feature where workflows needs to explicitly set the bit to `write` to use the feature.

**Comment by danielcompton** [comment]
Thanks for the clarification. Sorry to belabour the point, but what is the difference then between `id-token: read` and `id-token: none`?

**Comment by danielcompton** [comment]
Thanks @lucascosti, it's still not clear to me what the difference is between `id-token: read` and `id-token: none`? Are you able to help clarify that?

**Comment by lucascosti** [comment]
> Thanks @lucascosti, it's still not clear to me what the difference is between `id-token: read` and `id-token: none`? Are you able to help clarify that?

Sorry, @danielcompton; I have a guess, but rather than potentially give out the wrong info, I'll let @N-Usha clarify 🙂

**Comment by danielcompton** [comment]
@N-Usha would you be able to help clarify what the difference is between `id-token: read` and `id-token: none`?

**Comment by danielcompton** [comment]
@N-Usha are you able to help with this? I'm still not sure what the security differences are between a workflow having `id-token: read` and `id-token: none`.

**Comment by N-Usha** [comment]
Apologies for delayed response on this.

@danielcompton - There is no difference between a workflow having id-token: read and id-token: none.
We have clarified this in [docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings) recently:

> The job or workflow run requires a permissions setting with [id-token: write](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). You won't be able to request the OIDC JWT ID token if the permissions setting for id-token is set to read or none.

Please confirm if that clarifies your query. Thanks

**Comment by danielcompton** [comment]
Thanks @N-Usha that's exactly what I was after!

**Comment by CHANDRAMA2** [comment]
Hello

Chandrama mahato

**Comment by jmandel** [comment]
This is a closed issue, but I'm struggling to understand what the word "write" means here. Why is the permission called "write"? Is something being written? If so, what and by whom? Or is the permission called "write" for some other reason (e.g., something historical, referential, or arcane)? It'd be great to explain this just a tiny bit more.

**Comment by ssbarnea** [comment]
I am quire curious how it comes that this is closed when this tag has zero documentation.

**Comment by jmandel** [comment]
https://github.com/github/docs/issues/25952

**Comment by vincerubinetti** [comment]
Fwiw I couldn't even figure out that this permission scope had something to do with OIDC. Had to google it and find this issue.
