### ISSUE TITLE
Missing Webhook Payload Example for `workflow_dispatch`

### ISSUE THREAD

**Issue by dhirschfeld** [github/docs#14641]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The webhook events and payloads article:
* https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch

### What part(s) of the article would you like to see updated?

The `workflow_dispatch` documentation is missing the ***webhook payload object*** section which documents what the parameters actually mean.

* https://github.com/github/docs/blob/7afe360e54790334ba43e460a51ac4b32542c9d0/content/developers/webhooks-and-events/webhooks/webhook-events-and-payloads.md?plain=1#L1436-L1450

A webhook payload *example* is given, but without the description of what the parameters actually mean it's left to the reader to guess.

### Additional information

It would be good to include a ***webhook payload object*** describing the parameters for the `workflow_dispatch` event.

---
Edited by maintainer

Here is [writer's review on the issue](https://github.com/github/docs/issues/14641#issuecomment-1026149338):
Thanks for opening this issue! You or anyone is welcome to open a PR to add this info. I've provided some info below:

- inputs: inputs to the workflow
- organization: same as other webhooks
- ref: The branch ref that the workflow was run from
- repository: same as other webhooks
- sender: same as other webhooks
- workflow: path to the workflow

**Comment by ramyaparimi** [comment]
@dhirschfeld 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! You or anyone is welcome to open a PR to add this info. I've provided some info below:

- inputs: inputs to the workflow
- organization: same as other webhooks
- ref: The branch ref that the workflow was run from
- repository: same as other webhooks
- sender: same as other webhooks
- workflow: path to the workflow
