### ISSUE TITLE
settings.xml auto-generation can cause issues when publishing via gradle

### ISSUE THREAD

**Issue by MT-Jacobs** [github/docs#14662]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle

### What part(s) of the article would you like to see updated?

The first sample yaml results in the creation of a settings.xml file that can mess with gradle build commands.

Per https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven (and https://github.com/actions/setup-java/issues/510), `setup-java` automatically creates a settings.xml file like so:

``` xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>github</id>
      <username>${env.GITHUB_ACTOR}</username>
      <password>${env.GITHUB_TOKEN}</password>
    </server>
  </servers>
</settings>
```

If this file is parsed by anything in Gradle (such as a plugin) and the developer doesn't pass along the listed environment variables, this can cause the build to fail. If you plan on doing, say, `./gradlew build` in one step and `./gradlew publish` in another, this can understandably cause issues.

**Comment by Ninja-mann** [comment]
thank you im insane ly scattered and new

**Comment by MT-Jacobs** [comment]
I found the root cause of my pain -

https://github.com/mark-vieira/gradle-maven-settings-plugin/blob/1b0ea218088f4e0a8d9a82ad4918eca697cee867/src/main/groovy/net/linguica/gradle/maven/settings/LocalMavenSettingsLoader.java#L102

A third-party plugin I was using, [`gradle-maven-settings-plugin`](https://github.com/mark-vieira/gradle-maven-settings-plugin), was manually parsing the file and throwing a misleading exception.

I, unfortunately, misidentified this exception as coming from gradle.

That said, this does raise another nice-to-have - if Gradle had an easier way to pull Maven settings and use it for registering maven repos, we could very easily use `setup-java`'s generated settings.xml _without_ resorting to a third-party plugin - but that's [already a ticket](https://issues.gradle.org/browse/GRADLE-2365) in Gradle and certainly out of scope for Github.

I'm closing this issue until I can find a solution that doesn't use that plugin.
