### ISSUE TITLE
ต้องการปิดการแคสหน้าจอทีวีของอุปกรรณ์นี้รวมถึงถอนโปรแกรม​ฝัง Android​ Auto​ ออกดว้ย

### ISSUE THREAD

**Issue by saechinthai83** [github/docs#14674]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

saechinthai@gmail.com
Android​ Auto

### What changes are you suggesting?

> Photos, videos, and music cannot be moved into a memeri card.

### Additional information

Cannot write read-only.
How do you write and read?

**Comment by saechinthai83** [comment]
ok

**Comment by saechinthai83** [comment]
saechinthai83@gmail.com​

**Comment by Amjid377** [comment]
#1483445
