### ISSUE TITLE
Buttons don't behave correctly on mobile

### ISSUE THREAD

**Issue by Arhell** [github/docs#1468]
### What is the current behavior?

![1](https://user-images.githubusercontent.com/26163841/99701689-72d92e80-2a9d-11eb-98d5-980dd7b248a8.jpg)

### What changes are you suggesting?
Do this way
![2](https://user-images.githubusercontent.com/26163841/99701804-a1570980-2a9d-11eb-8e31-7a8d2f1e9b3d.jpg)

### Additional information
I will do it soon

**Comment by khale11** [comment]
Using a mobile

**Comment by chiedo** [comment]
Closed in https://github.com/github/docs/pull/1476
