### ISSUE TITLE
permissions-required-for-github-apps, section permission-on-actions needs an update

### ISSUE THREAD

**Issue by larshp** [github/docs#14713]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-actions

### What part(s) of the article would you like to see updated?

It seems like the list under https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-actions is incomplete

Eg. https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event says "GitHub Apps must have the actions:write permission to use this endpoint.", but the endpoint is not listed under "Permission on "actions"

### Additional information

source file is https://github.com/github/docs/edit/main/content/rest/overview/permissions-required-for-github-apps.md

---
[maintainer edit]

### Content plan

Add the `workflow_dispatch` event with write permissions to the list under "Permissions on actions".

**Comment by ramyaparimi** [comment]
@larshp Thanks so much for opening this issue 🐬. You or anyone else is welcome to open a PR with a fix ✨
