### ISSUE TITLE
Inconsitency in example

### ISSUE THREAD

**Issue by Bibi56** [github/docs#14794]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.osmand.net/en/main@latest/osmand/map/raster-maps#download--update-tiles

### What part(s) of the article would you like to see updated?

Current version: 
<h3 id="magic-url-to-install-map-source"><a href="https://docs.osmand.net/en/main@latest/osmand/map/raster-maps#magic-url-to-install-map-source">Magic URL to install map source</a></h3>
<p>Online maps can be added with a special link to OsmAnd Raster map list. Click to this link and choose OsmAnd for opening:</p>
<p><a href="http://osmand.net/add-tile-source?name=TEST&amp;min_zoom=9&amp;max_zoom=20&amp;url_template=http://h0.ortho.tiles.virtualearth.net/tiles/h%7Bq%7D.jpg?g=45">http://osmand.net/add-tile-source?name=TEST&amp;min_zoom=9&amp;max_zoom=20&amp;url_template=http://h0.ortho.tiles.virtualearth.net/tiles/h{q}.jpg?g=45</a></p>

Parameter of link | Example
-- | --
[Constant part] | http://osmand.net/add-tile-source
[Separator] | ?
[Name] | name=TEST
[URL] | template=http://h0.ortho.tiles.virtualearth.net/tiles/h{q}.jpg?g=45
[Zoom levels] | min_zoom=9 / max_zoom=20
----
Issue: 

Link http://osmand.net/add-tile-source?name=TEST&amp;min_zoom=9&amp;max_zoom=20&amp;url_template=http://h0.ortho.tiles.virtualearth.net/tiles/h{q}.jpg?g=45 refers to `url_template` but the parameter below is supposed to be `template`. One is wrong, the latest probably.

**Comment by Mannypi67** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).
>

**Comment by Bibi56** [comment]
@ramyaparimi you tagged the issue as invalid. Do you mean that it's correct to have a parameter `url_template` in the link and to explain the parameter ` template` (not `url_template`)?

**Comment by ramyaparimi** [comment]
@Bibi56 The open-source repo is for [docs.github.com](https://docs.github.com/en). I closed the issue as invalid as it appeared that this issue was opened by mistake in this repo, since the docs links listed in the PR template don't [docs.github.com](https://docs.github.com/en) 💛.

**Comment by Bibi56** [comment]
@ramyaparimi  thanks, I'll check why the doc about OSMAND links to this repo! Copy/paste without update I guess. And probably two tickets then ;-) but on the other repo. Feel free to close this ticket.

**Comment by nyila** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> https://docs.osmand.net/en/main@latest/osmand/map/raster-maps#download--update-tiles
> 
> ### What part(s) of the article would you like to see updated?
> 
> Current version: 
> <h3 id="magic-url-to-install-map-source"><a href="https://docs.osmand.net/en/main@latest/osmand/map/raster-maps#magic-url-to-install-map-source">Magic URL to install map source</a></h3>
> <p>Online maps can be added with a special link to OsmAnd Raster map list. Click to this link and choose OsmAnd for opening:</p>
> <p><a href="http://osmand.net/add-tile-source?name=TEST&amp;min_zoom=9&amp;max_zoom=20&amp;url_template=http://h0.ortho.tiles.virtualearth.net/tiles/h%7Bq%7D.jpg?g=45">http://osmand.net/add-tile-source?name=TEST&amp;min_zoom=9&amp;max_zoom=20&amp;url_template=http://h0.ortho.tiles.virtualearth.net/tiles/h{q}.jpg?g=45</a></p>
> 
> Parameter of link | Example
> -- | --
> [Constant part] | http://osmand.net/add-tile-source
> [Separator] | ?
> [Name] | name=TEST
> [URL] | template=http://h0.ortho.tiles.virtualearth.net/tiles/h{q}.jpg?g=45
> [Zoom levels] | min_zoom=9 / max_zoom=20
> ----
> Issue: 
> 
> Link http://osmand.net/add-tile-source?name=TEST&amp;min_zoom=9&amp;max_zoom=20&amp;url_template=http://h0.ortho.tiles.virtualearth.net/tiles/h{q}.jpg?g=45 refers to `url_template` but the parameter below is supposed to be `template`. One is wrong, the latest probably.
> 
> ### Additional information
> 
> _No response_
