### ISSUE TITLE
POST access_tokens returns an access token

### ISSUE THREAD

**Issue by vincentisambart** [github/docs#14824]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/getting-started-with-apps/setting-up-your-development-environment-to-create-a-github-app#authenticating-as-a-github-app

### What part(s) of the article would you like to see updated?

On that page, the access token returned by `@app_client.create_app_installation_access_token(installation_id)` is used as a bearer token, not as an access token as it should.
```ruby
  @installation_client = Octokit::Client.new(bearer_token: installation_token)
```
should be:
```ruby
  @installation_client = Octokit::Client.new(access_token: installation_token)
```

The endpoint name suggests it is an access token, in https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-an-installation, it is used as an access token (`"Authorization: token YOUR_INSTALLATION_ACCESS_TOKEN"` – it would be `"Authorization: Bearer YOUR_INSTALLATION_ACCESS_TOKEN"` if it was a bearer token), and to be sure I also asked GitHub Support and was told it is indeed an access token.

### Additional information

In fact the token returned by that end point does seem to work as both an access token and a bearer token, but consistency would make it easier to follow.

**Comment by vincentisambart** [comment]
Found another place where a GitHub App installation **access token** is used as a Bearer token:
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
I'm not even sure what is correct...

**Comment by ramyaparimi** [comment]
@vincentisambart Thanks for opening this issue. I will triage the linked PR for a writer's review 👀

**Comment by stevecat** [comment]
Hi @vincentisambart! As Sophie mentioned in https://github.com/github/docs/pull/14825, we looked at your issue and suggestion and we've found that it's part of a larger discussion. I'm going to close this now but rest assured, we're speaking with our API team about this ✨
