### ISSUE TITLE
"Reverting a commit" screenshot should be updated

### ISSUE THREAD

**Issue by AustinConlon** [github/docs#14848]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit

### What part(s) of the article would you like to see updated?

Second screenshot. Minor issue but the text in the menu item is now "Revert Changes in Commit."

**Comment by ramyaparimi** [comment]
@AustinConlon 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by mchammer01** [comment]
@AustinConlon 👋🏻 - thanks for highlighting this inaccuracy in our docs ✨ 
This needs to be fixed internally so I'm going to close this issue now.
