### ISSUE TITLE
Clarify product tier requirement in 'Managing code review settings for your team > About Auto Assignment'

### ISSUE THREAD

**Issue by jonahgeorge** [github/docs#14851]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment

### What part(s) of the article would you like to see updated?

**About Auto Assignment**

> To further enhance your team's collaboration abilities, you can upgrade to GitHub Enterprise Cloud, which includes features like protected branches and code owners on private repositories. For more information about how you can try GitHub Enterprise Cloud for free, see "Setting up a trial of GitHub Enterprise Cloud."

Protected branches and code owners on private repositories are no longer features of just GHEC. Caused some confusion when trying to understand whether or not I could use these in my Github Team account.

**Comment by ramyaparimi** [comment]
@jonahgeorge 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @jonahgeorge! You're correct that there's no difference between Team and Cloud on those collaboration features, as you can see at https://github.com/pricing. You or anyone else is welcome to open a PR removing that line.

**Comment by Asmit2952** [comment]
Can I work on this?
