### ISSUE TITLE
Add reference to OSSF Scorecards in the GitHub Actions hardening guide

### ISSUE THREAD

**Issue by varunsh-coder** [github/docs#14855]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions

### What part(s) of the article would you like to see updated?

[OSSF Scorecards](https://github.com/ossf/scorecard) can find issues related to `token permissions` and `actions that are not pinned`. Adding a reference to Scorecards in the [token permissions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#restricting-permissions-for-tokens) and (optionally) [pin actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) sections of the hardening guide will help readers to take action to address these issues. 

https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/

**Comment by ramyaparimi** [comment]
@varunsh-coder 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
