### ISSUE TITLE
Update for latest release of `gradle/gradle-build-action`

### ISSUE THREAD

**Issue by bigdaz** [github/docs#14859]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle and https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle pages reference the SHA for an older release of https://github.com/gradle/gradle-build-action.

### What part(s) of the article would you like to see updated?

These docs should be updated to the latest release, v2.1.2.

PR for `starter-workflows`: https://github.com/actions/starter-workflows/pull/1375
PR for `docs`: https://github.com/github/docs/pull/14858

**Comment by ramyaparimi** [comment]
@bigdaz 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by bigdaz** [comment]
@ramyaparimi What's the best way to update the docs when we release a new version of of `gradle/gradle-build-action`? We are actively developing the actions and it would be great if the docs were kept updated with the latest-and-greatest.

For example, I'm about to put out a bug-fix release that will make my current PR obsolete.

Should I:
- Submit an issue together with PR for `docs` and `starter-workflows`
- Simply submit an issue with the updated version
- Only submit the PRs without the issue?

Just wondering the best way to streamline this process. Thanks.

**Comment by ramyaparimi** [comment]
@bigdaz You can only submit a PR without an issue ✨.  If this issue is not current anymore, you can close it in favor of the latest PR you would be opening 💖.
Thanks so very much for contributing to GitHub docs to keep them updated with your changes 💖

**Comment by bigdaz** [comment]
Thanks @ramyaparimi . I've opened #15030 which updates the docs for the latest release `gradle/gradle-build-action@v2.1.3`. I'll close this issue and the existing PR in favour of the new one.
