### ISSUE TITLE
for creating software documentation.  This is a living, breathing guide. If you’d like to contribute, take a look at the guidelines for contributing to the guide. If you have any questions about contributing, you can send them along to guide@writethedocs.org.  Also feel free to send us any additions in any format to support@writethedocs.org.  New to Caring About Documentation? A beginner’s guide to writing documentation Why write docs

### ISSUE THREAD

**Issue by Jepriko** [github/docs#14909]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

for creating software documentation.

This is a living, breathing guide. If you’d like to contribute, take a look at the guidelines for contributing to the guide. If you have any questions about contributing, you can send them along to guide@writethedocs.org.

Also feel free to send us any additions in any format to support@writethedocs.org.

New to Caring About Documentation?
A beginner’s guide to writing documentation
Why write docs

### What part(s) of the article would you like to see updated?

for creating software documentation.

This is a living, breathing guide. If you’d like to contribute, take a look at the guidelines for contributing to the guide. If you have any questions about contributing, you can send them along to guide@writethedocs.org.

Also feel free to send us any additions in any format to support@writethedocs.org.

New to Caring About Documentation?
A beginner’s guide to writing documentation
Why write docs

### Additional information

for creating software documentation.

This is a living, breathing guide. If you’d like to contribute, take a look at the guidelines for contributing to the guide. If you have any questions about contributing, you can send them along to guide@writethedocs.org.

Also feel free to send us any additions in any format to support@writethedocs.org.

New to Caring About Documentation?
A beginner’s guide to writing documentation
Why write docs

**Comment by mustafa-marah** [comment]
yardıma ihtiyacım var
