### ISSUE TITLE
What does "the official Octokit library" mean?

### ISSUE THREAD

**Issue by solvaholic** [github/docs#14926]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/libraries

### What part(s) of the article would you like to see updated?

I'd like to see clarification around what it means for Octokit to be an official library and/or removal of octokit/octokit.js as an official library.

When Dependabot calls out a vulnerability in octokit.js, it being documented as "the official Octokit library" suggests GitHub will do things to address the vulnerability. I'd like to see this document clarify whether that's the case.

### Additional information

I read "the official Octokit library" in GitHub's documentation to mean GitHub endorses and supports users' use of Octokit, and may sponsor maintenance of the library's projects. I struggle to imagine the official library being un-maintained.

Last year @gr2m [explained](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174):

> The JavaScript Octokit has no active maintainer as of this week.

Last week @wolfy1339 [added](https://github.com/octokit/core.js/pull/442#issuecomment-1023265599):

> Also, the octokit modules are unmaintained.

This raises concerns like https://github.com/octokit/core.js/pull/442#issuecomment-1023353053 about the viability of the project.

### Update and content plan
[Updates and plan](https://github.com/github/docs/issues/14926#issuecomment-1168901564)

**Comment by ramyaparimi** [comment]
@solvaholic 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! The octokit libraries are not currently maintained. This may change in the future. You or anyone else is welcome to open a PR to update the documentation to indicate that the octokit libraries are not currently maintained.

**Comment by mischa0083** [comment]
Octokit is temporarily unmaintained and per: https://github.com/github/c2c-actions/issues/3872 we will be hiring for headcount to support Octokit officially with an SDK team, with date TBD.  I think it would be worth adding a small text blurb mentioning its current state of support, though I'm not sure what the right wording for this would be.  Perhaps something akin to (which should also be added to the README of the repository):

> Note: Octokit is not actively maintained currently.  Please remain patient while we work on an announcement regarding the state of Octokit's future.

**Comment by imwiss** [comment]
Thanks everyone for chiming in. I posted an update about Octokit's future here: https://github.com/octokit/octokit.js/discussions/620#discussioncomment-2144643

**Comment by solvaholic** [comment]
> What does "the official Octokit library" mean?

I think it means _GitHub endorses and supports users' use of Octokit, and may sponsor maintenance of the library's projects_.

[The published doc](https://github.com/github/docs/blob/1f0d011173210de6c73a8ab983d29f8f4daa15f0/content/rest/overview/libraries.md#octokit-comes-in-many-flavors) currently lists 3 libraries as official. When users want help I think they may open issues or discussions in the project repositories, or they may contact GitHub Support. How _should_ users request help?

Whichever is the preferred approach, I'd like to see docs in each repo, for example [a SUPPORT.md](https://docs.github.com/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project), clearly state those expectations and instructions. What can I do to help make that happen?

**Comment by skedwards88** [comment]
Thanks everyone for this discussion! The Octokit libraries are now maintained again, and the maintainers are working on adding SUPPORT.md files, addressing security vulnerabilities, and cleaning up the projects.

- If you have a specific Octokit issue, you should open an issue in the corresponding Octokit repo. While these repos are maintained by GitHub, they are open source and community contribuitons are welcome.
- Anyone is welcome to open a pull request to add the info in this point ☝️ to https://docs.github.com/en/rest/overview/libraries

**Comment by adhammahdi** [comment]
[](url) admitad.banner

**Comment by adhammahdi** [comment]
Oh animal thief return my money or I will raise it in


تم الإرسال من Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cmwilson21** [comment]
Reopening as stale bot closed this a bit early.

**Comment by mokshadharma** [comment]
As a member of the [ecosystem squad](https://github.com/github/support-squad-ecosystem) I just wanted to chime in here and mention that we regularly get tickets from customers expecting support on octokit.

In such cases I've been telling such customers that GitHub Support does not support octokit and that we recommend opening an issue in the octokit repo instead.

It would be great if customers knew the right place to get support to begin with.
