### ISSUE TITLE
GraphQL Explorer is short height-wise

### ISSUE THREAD

**Issue by tyirvine** [github/docs#14925]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/overview/explorer

### What changes are you suggesting?

The GraphQL explorer itself I see is nested in an `iframe` with a height of `715px`. This is a little short height-wise and makes it difficult to use the explorer. I understand it's likely nested in there to interface with GitHub's authentication system. Maybe it's possible to increase the height of the `iframe`? 

<img width="624" alt="Screen Shot 2022-02-01 at 3 06 34 PM" src="https://user-images.githubusercontent.com/39813066/152043073-4eedf655-7387-4c14-95c7-48b1fce41ead.png">

<img width="2330" alt="Screen Shot 2022-02-01 at 3 10 15 PM" src="https://user-images.githubusercontent.com/39813066/152043548-ce768ecb-702a-4255-88be-31738de87140.png">

**Comment by ramyaparimi** [comment]
@tyirvine 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by rsese** [comment]
👋 !  I took a look and the iframe content has CSS that styles the height so even if we increase the iframe height it won't fill the space it looks like?  I also poked around and found there's an internal issue for the folks that maintain GraphQL Explorer with similar feedback so can mention that you reached out about this.

**Comment by tyirvine** [comment]
@rsese sweet ok! Thank you for looking into it! I appreciate it 🤙

**Comment by ramyaparimi** [comment]
@tyirvine I am going to close this issue since it is being tracked in an appropriate internal repo 💖 

Thanks so much for taking your time in contributing to GitHub docs 💖
