### ISSUE TITLE
Broken render of Markdown table - Chinese translation - Actions - Context availability

### ISSUE THREAD

**Issue by liyishuai** [github/docs#14956]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/cn/actions/learn-github-actions/contexts#context-availability

### What part(s) of the article would you like to see updated?

Render context availability table properly.

### Additional information

2022-02-02
Current status on [docs website](https://docs.github.com/cn/actions/learn-github-actions/contexts#context-availability): ![image](https://user-images.githubusercontent.com/7020805/152176551-c5e19aca-621f-4abb-8f9e-8525da6247fc.png)

The [source file](https://github.com/github/docs/blob/main/translations/zh-CN/content/actions/learn-github-actions/contexts.md) rendered fine on GitHub at 3535fb25322da9e39f9c788c080964d058b775de: ![image](https://user-images.githubusercontent.com/7020805/152177104-02da6cfc-a129-4ea2-bb9e-c0294d150312.png)

**Comment by ramyaparimi** [comment]
@liyishuai 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
