### ISSUE TITLE
Simplify content-only issue reporting process

### ISSUE THREAD

**Issue by liyishuai** [github/docs#14958]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Every non-English page where users hope to report a problem.

### What changes are you suggesting?

Allow users to report error in contents by selecting a paragraph and clicking "Report error".

### Additional information

I have enough confidence in my English to file a GitHub issue #14956. Meanwhile, for users that rely on translated documents, the issue guidelines in English might be too heavy. Consider these options:
- Make issue guidelines multilingual, or
- Provide simpler way of reporting error in contents.

**Comment by ramyaparimi** [comment]
@liyishuai 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
