### ISSUE TITLE
To add some html file and css to create god ui and better well look

### ISSUE THREAD

**Issue by athifbinu** [github/docs#14989]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

i am think in this repositery are improve at there style and well looking contend and to create a good content and create best look and feel.

### What part(s) of the article would you like to see updated?

At that in my updation is to add some styles and well created content.

### Additional information

To add style and html

**Comment by ramyaparimi** [comment]
@athifbinu 
This seems to be opened by accident, so I am going to close it now :yellow_heart: Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions :sparkles:
