### ISSUE TITLE
Include work around for wildcards in HTTP Proxy Exclusion list on GHES

### ISSUE THREAD

**Issue by mzzmjd** [github/docs#1502]
### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@2.21/admin/configuration/configuring-an-outbound-web-proxy-server

### What part(s) of the article would you like to see updated?

HTTP Proxy Exclusion.

The current instructions say to:
> type any hosts that do not require proxy access, separating hosts with commas.

There is no mention of wildcards. However, if you enter ```.mycompany.com``` it will exclude any server ending with .mycompany.com ( this would include server.mycompany.com , web.mycompany.com, etc.mycompany.com, etc.) 

### Additional information

This was mentioned by GitHub services. I have tested it and it works for me. We have been trying to fix this issue for over 4 years.

**Comment by Irenemad** [comment]
https://github.com/github/docs/issues/1502#issue-747578110
