### ISSUE TITLE
Incorrect command description in "adding GPG key" docs

### ISSUE THREAD

**Issue by vient** [github/docs#15129]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key

### What part(s) of the article would you like to see updated?

Command description should be rewritten in Mac point 5 "If you aren't using the GPG suite...", Linux point 5 "To add your GPG key to your bash profile..." sections.

These commands do not add GPG keys to shell profile, instead they add an instruction to shell profile to correctly set `GPG_TTY` environment variable on startup. Without it GPG won't be able to ask user for key's password.

**Comment by ramyaparimi** [comment]
@vient 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by vient** [comment]
Not fixed yet

**Comment by vgrl** [comment]
It looks like https://github.com/github/docs/pull/16181 may have resolved the concerns mentioned in this issue, so I'll close this now.
