### ISSUE TITLE
poetic

### ISSUE THREAD

**Issue by StrezlessMusick** [github/docs#15147]
https://github.com/Chad-Mowbray/iamb-classifier/blob/cleanup/dataprep/raw_files/elizabethan/eliz1.txt

**Comment by 4akill** [comment]
На?

вс, 6 февр. 2022 г., 04:28 welcome[bot] ***@***.***>:

**Comment by 69WileyCoyote69** [comment]
Well

**Comment by 69WileyCoyote69** [comment]
#
