### ISSUE TITLE
Creating a Docker actions incorrectly stating that you must declare inputs

### ISSUE THREAD

**Issue by nikola-jokic** [github/docs#15210]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

### What part(s) of the article would you like to see updated?

In the section [Creating an action metadata file](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file), it is stated that you need to specify inputs in order to pass them to the container. This is not exactly the case which is explained in runner [issue #499](https://github.com/actions/runner/issues/499). If you use `with.args`, arguments will be passed to the `entrypoint` regardless of input spec.
This is explained well in [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswithargs) part of the documentation but contradicts a bit with the part I am opening an issue for.
<img width="1374" alt="Screenshot 2022-02-07 at 17 18 58" src="https://user-images.githubusercontent.com/97525037/152828113-84206edf-af49-4076-ad03-ae86ab0ec299.png">

Note that this last part, ` . /env ; docker ...` is taken from issue#499

### Additional information

You can refer to my example in [test repository](https://github.com/nikola-jokic/test). Please note that in actions.yaml, there were no specified inputs, but if you pass inputs using `with.args`, they will be passed to the container. So this should be added to the docs as well.

**Comment by ramyaparimi** [comment]
@nikola-jokic 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
