### ISSUE TITLE
GITHUB_SHA on PRs refers to the merge commit, not the actual commit which triggered the PR

### ISSUE THREAD

**Issue by danielcompton** [github/docs#15302]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/environment-variables

### What part(s) of the article would you like to see updated?

The docs say that `GITHUB_SHA` is:

> The commit SHA that triggered the workflow. For example, `ffac537e6cbbf934b08745a378932722df287a53`.

This can be a bit misleading for PRs. As best as I can tell, the `GITHUB_SHA` used for PRs is the temporary merge commit GitHub makes against the base branch, i.e. `refs/remotes/pull/<id>/merge`.

When I read the docs, I assumed that "The commit SHA that triggered the workflow" was the SHA of the commit that _I_ pushed to the branch, not the SHA of GitHub's internal merge commit.

I think it would be helpful to mention that the SHA may not be the SHA that you pushed. Not quite sure how to word it, but thought I'd open an issue.

**Why is this important?**

In my case, I was trying to diff the current commit against the upstream branch. Using `GITHUB_SHA` felt like the right handle to use, but didn't work because GITHUB_SHA refers to a merge commit, so there is no diff.

### Additional information

Related issues:

* https://github.com/github/docs/issues/4574
* https://github.com/github/docs/issues/4422

**Comment by lucascosti** [comment]
👋 @danielcompton Thanks for opening this issue. The `GITHUB_SHA` that triggers a workflow is different depending on the event that the workflow was configured to run on. The value of `GITHUB_SHA` for each event is documented in [Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request). (According to that, you are correct about the merge commit for pull requests).

I think we could perhaps add a small sentence saying to the [Environment variable article's table](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) for `GITHUB_SHA`, saying like: 

> The commit SHA that triggered the workflow. The commit that is used depends on the event that triggered the workflow. For more information, see \<link to the Events that trigger workflows article>. For example, ffac537e6cbbf934b08745a378932722df287a53.

You (or anyone else) can feel free to open a PR for ☝️. 🙇‍♂️

**Comment by asbjornu** [comment]
Although the clarification is welcome, I'm still yearning for an explanation of how to find the SHA of the commit that was pushed when building a `pull_request` event. Is it at all available? In the `github.event` object somewhere, perhaps?

**Comment by asbjornu** [comment]
@cmwilson21, done: #30093.

**Comment by BORNEO00** [comment]
👍
