### ISSUE TITLE
Dark screenshots for dark mode of GitHub

### ISSUE THREAD

**Issue by yasarshaikh** [github/docs#15348]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/quickstart

### What part(s) of the article would you like to see updated?

The white/bright screenshots are causing eye strain in a dark-themed environment. I prefer to use dark theme editor/screen & even GitHub settings. 

I'd prefer to have those screenshots suitable for a dark theme if a user is enabled the dark theme.

![image](https://user-images.githubusercontent.com/20971327/153614448-732119f2-15f2-45d8-a46b-58fc25e56c2a.png)

**Comment by ramyaparimi** [comment]
@yasarshaikh Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Hi @yasarshaikh, I can definitely understand how light screenshots could seem jarring against a dark background! Unfortunately, our team doesn't have the bandwidth to create double the number of screenshots we're creating now, so I'm going to close this issue. Thanks for your interest in contributing to the docs!
