### ISSUE TITLE
Why should one add a license on a branch??

### ISSUE THREAD

**Issue by lars-hellstrom** [github/docs#15447]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[adding-a-license-to-a-repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

### What part(s) of the article would you like to see updated?

In [adding-a-license-to-a-repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository), point 8 states:

    Below the commit message fields, decide whether to add your commit 
    to the current branch or to a new branch. 
    If your current branch is the default branch, you should choose to create 
    a new branch for your commit and then create a pull request. 
    For more information, see "[Creating a new pull request](https://docs.github.com/en/articles/creating-a-pull-request)."

I'm questioning the use of "should" here. Unless the license text needs to be reviewed by several people, it make little-to-no sense to create a branch just for adding the license. Adding a license is a major step forward, so it ought to happen on the default branch.

As it stands, this doc file suggests an (AFAICT) unnecessarily convoluted way of performing a step, and provides no explanation of *why* it would be better to do it that way.

**Comment by ramyaparimi** [comment]
@lars-hellstrom Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by sophietheking** [comment]
Hi @lars-hellstrom 👋 thank you for opening this issue. ✨ The team decided we're not going to making this change. Thanks so much for taking your time in contributing to the GitHub docs. 💖
