### ISSUE TITLE
[Bug]: lack of legibility for "All Enterprise Server releases" link

### ISSUE THREAD

**Issue by adrianmg** [github/docs#15477]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

It's affecting the header for all the docs pages.

### What changes are you suggesting?

Making the link `white` when hovering as we do for the rest of items.

### Additional information

![image](https://user-images.githubusercontent.com/589285/153963355-4eb61810-d89d-43d9-a641-aa176317851c.png)

**Comment by ramyaparimi** [comment]
@adrianmg 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by gracepark** [comment]
Hi @adrianmg thanks for the heads up! We have a fix coming shortly! I'll close for now, but if you don't see an update in the next couple of days, please let me know.
