### ISSUE TITLE
Inconsistent Mermaid semicolons

### ISSUE THREAD

**Issue by 89z** [github/docs#15471]
On this page [1], you have this example:

![mermaid](https://github.blog/wp-content/uploads/2022/02/mvp2.png)

where the first line omit semicolon, but all others have it. This seems to run counter to the Mermaid docs, which either use all [2] or none [3].

1. https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid
2. https://mermaid-js.github.io/mermaid
3. https://mermaid-js.github.io/mermaid/#flowchart

**Comment by ramyaparimi** [comment]
@89z 
Thanks for opening this issue! The best place to send your feedback regarding this is at https://github.com/github/feedback/discussions/4539 💛
