### ISSUE TITLE
Provide consistent example yml for reusable workflows

### ISSUE THREAD

**Issue by Layoric** [github/docs#15480]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows

### What part(s) of the article would you like to see updated?

The docs currently state:

> Reusable workflows are YAML-formatted files, very similar to any other workflow file. As with other workflow files, you locate reusable workflows in the `.github/workflows` directory of a repository. Subdirectories of the `workflows` directory are not supported.

But the example yml then presents the path:

> uses: ./.github/**actions**/my-action

This doesn't follow the initial advice about location of workflow files, and creates confusion.

I'd like the example `yml` to reflect the written docs to reduce confusion please.

**Comment by 0566616453** [comment]
Leave a comment

**Comment by 0566616453** [comment]
Leave a comment

**Comment by 0566616453** [comment]
Leave a comment

**Comment by 0566616453** [comment]
Leave a comment

**Comment by ramyaparimi** [comment]
@Layoric 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
