### ISSUE TITLE
Issue with the home page of github

### ISSUE THREAD

**Issue by Jassi10000** [github/docs#15537]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

![image](https://user-images.githubusercontent.com/64856348/154313627-963b0a13-fc0c-4b9e-94e2-5eee93c15deb.png)
Idk why am getting this since morning , didnt' found a right repo to post about this bug , so just opened the issue here. Looking forward to get this bug solved soon.

### What part(s) of the article would you like to see updated?

Pls refer to the screenshot

**Comment by ramyaparimi** [comment]
@Jassi10000 
Thanks for opening this issue! I think [GitHub support](https://support.github.com/contact) or [GitHub Support Community](https://github.community/) would be the best place to ask this question 💛
