### ISSUE TITLE
Remove extra usage of 'repository' in understanding-github-actions.md

### ISSUE THREAD

**Issue by tmelliottjr** [github/docs#15555]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

### What part(s) of the article would you like to see updated?

The section on [workflows](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#workflows) uses the word 'repository' twice and makes the sentence less readable.

**Comment by suriyawutkhongprom** [comment]
> ### จรรยาบรรณ
> * [x] [ฉันได้อ่านและยอมรับ จรรยาบรรณของ](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)โครงการ GitHub Docs[](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### บทความใดใน docs.github.com ที่ได้รับผลกระทบ
> https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
> 
> ### ส่วนใดของบทความที่คุณต้องการอัปเดต
> ส่วนใน[เวิร์กโฟลว์](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#workflows)ใช้คำว่า 'ที่เก็บ' สองครั้งและทำให้ประโยคอ่านน้อยลง
> 
> ### ข้อมูลเพิ่มเติม
> _ไม่มีการตอบสนอง_
@zmoazeni
