### ISSUE TITLE
Text overflows its parent container for the pinned items on Profile page

### ISSUE THREAD

**Issue by tannerdolby** [github/docs#15581]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

No articles affected. I wasn't sure where to post this issue as it pertains to github.com and not the docs.github.com, but hopefully this is okay.

The [profile page](https://github.com/tannerdolby) contains pinned items and in those items, the descriptive text overflows because of the `white-space: nowrap` but the `text-overflow: ellipsis` doesn't seem to have any affect.

### What changes are you suggesting?

The `white-space: no-wrap` is what is causing the text to overflow and appear "cutoff" for each of the pinned items.

```css
.Truncate>.Truncate-text {
    min-width: 1ch;
    max-width: -moz-fit-content;
    max-width: fit-content;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```
<img width="470" alt="Screen Shot 2022-02-17 at 8 27 51 AM" src="https://user-images.githubusercontent.com/48612525/154525829-bd7a3d93-7ff6-4ef4-b6f4-4139e9e9d9a9.png">

If we remove the `white-space` declaration or change its value to `normal` / `inherit` then the text won't overflow as it did before, but that really isn't a "complete fix".

<img width="465" alt="Screen Shot 2022-02-17 at 9 20 55 AM" src="https://user-images.githubusercontent.com/48612525/154536040-5ffac3e1-5b8d-4076-afa3-00e14825eb72.png">

I'm assuming that your team wants to keep the `white-space: nowrap` around for applying ellipsis to single-line or multi-line text, but it seems that for the pinned items, the process for applying ellipsis either for single or multi line descriptions isn't behaving as expected.

### Additional information

I did notice that in the sort of "timeline" of contributions on a given user profile page, we have sort of the same HTML structure and styling happening, where multi-line text is truncated with ellipsis when it overflows:

<img width="794" alt="Screen Shot 2022-02-17 at 9 22 41 AM" src="https://user-images.githubusercontent.com/48612525/154536435-f12a9fa8-93fe-408b-a8be-ff83878ea85c.png">

_screenshot of the element in DevTools that has multi-line text truncated with ellipsis when overflowed_
<img width="1270" alt="Screen Shot 2022-02-17 at 9 28 29 AM" src="https://user-images.githubusercontent.com/48612525/154537314-b1334692-808e-4265-b4ab-952bdc95dc82.png">

This might be a good starting point to compare/investigate why the "pinned items" on the profile page are not replicating the same single/multi line ellipsis behavior like shown above in the "timeline" items. I know working with `text-overflow: ellipsis` can be tricky with multi-lines, this [StackOverflow post](https://stackoverflow.com/questions/33058004/applying-an-ellipsis-to-multiline-text/33061059#33061059) contains most all the methods/tricks I've seen or used and might be helpful.

Let me know if I can be of any assistance.

**Comment by mattpollard** [comment]
👋🏻 Thanks for the report, @tannerdolby! I'm looking into the best way to route this to an internal team here at GitHub, and I'll let you know when I've got more information.

**Comment by mattpollard** [comment]
@tannerdolby, the engineering team responsible for profiles is tracking this issue internally. I don't have an ETA for when they'll prioritize a fix, but they're aware of the problem. We've referenced your issue in our internal issue for visibility, so I'll close this for now. Thanks again for the heads up.

**Comment by dipree** [comment]
FYI: We are looking into this. Tracking issue https://github.com/github/special-projects/issues/944

**Comment by tannerdolby** [comment]
@mattpollard no problem! ok sounds like a plan, thanks for keeping me in the loop.
