### ISSUE TITLE
Japanese: don't translate close keyword

### ISSUE THREAD

**Issue by Dirain1700** [github/docs#15599]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[wrong article (Japanese)](https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
[correct article](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
![54E72F94-5C78-470E-ADE0-9D95DCAEA77F](https://user-images.githubusercontent.com/86363603/154611047-cdab0c7b-ee9c-4195-ae7f-71d3f5305266.jpeg)

### What changes are you suggesting?

Replace the word "解決" to "resolve"

**Comment by ramyaparimi** [comment]
@Dirain1700 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
