### ISSUE TITLE
The docs for hosted windows action runners show wrong version for `windows-latest`

### ISSUE THREAD

**Issue by piksel** [github/docs#15603]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

### What part(s) of the article would you like to see updated?

The table in the [Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) section lists the YAML workflow label for Windows 2019 as `windows-2019` *or* `windows-latest`. Additionally a note says that `windows-latest` maps to `windows-2019` on the Windows 2022 row.
The `-latest` image was changed to `-2022` in January, and the docs should reflect this change.

### Additional information

This change was [announced in the blog](https://github.blog/changelog/2022-01-11-github-actions-jobs-running-on-windows-latest-are-now-running-on-windows-server-2022/)

**Comment by ramyaparimi** [comment]
@piksel 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by ramyaparimi** [comment]
Closing this issue as per [this comment](https://github.com/github/docs/pull/15630#issuecomment-1047940505) in the linked PR
