### ISSUE TITLE
Favicon might be invisible

### ISSUE THREAD

**Issue by SharakPL** [github/docs#1560]
### What is the current behavior?

![obraz](https://user-images.githubusercontent.com/5007456/99965111-ae714280-2d94-11eb-828c-ffb983b36da8.png)

### What changes are you suggesting?
Make favicon black __and white__ across all GitHub services available from the browser. Otherwise it can be invisible when browser uses dark mode or a theme with dark colors.

**Comment by b4mboo** [comment]
I checked the favicon's behavior in dark mode in Safari and Chrome on macOS Catalina:

<img width="291" alt="favicon-in-dark-mode" src="https://user-images.githubusercontent.com/72066/108863707-c6ee3480-75f1-11eb-818e-326a817be067.png">

Can we close this issue?

**Comment by b4mboo** [comment]
@SharakPL Thanks again for opening this issue. ✨ 
While we won't be able to address all possible color schemes, I wonder whether you're able to produce a situation where enabling dark mode would render the favicon invisible? If so, please feel free to reopen this issue with more details.

It's worth mentioning that this repository only serves https://docs.github.com, so other GitHub-owned services or pages are out of scope.

**Comment by SharakPL** [comment]
@b4mboo maybe it works for Chrome/Edge and Safari because it relies on browser's dark mode feature, but Firefox doesn't seem to have that. Dark mode is enabled simply by activating dark theme and it looks even worse there:

![obraz](https://user-images.githubusercontent.com/5007456/108881205-5b14c780-7603-11eb-951a-6001ee6f6da2.png)

Adding a background-color to svg or `<circle ... fill="#fff">` element would fix the problem.

**Comment by b4mboo** [comment]
Your observation is correct. GitHub relies on the browser to communicate the dark mode flag. Changing this behavior, however, is beyond the scope of this open source repository, which only holds the content for GitHub's documentation.

**Comment by SharakPL** [comment]
@b4mboo I was aware it's not specific to @github Docs but couldn't find any better place as it does impact all sites the same way. Could you direct me to repository that can handle this issue?

**Comment by b4mboo** [comment]
@SharakPL The best way to request new features or enhancements like this one would be through GitHub's Support: https://support.github.com/contact

**Comment by SharakPL** [comment]
Thanks 😊
