### ISSUE TITLE
`repository-branches.md` Uses Incorrect Sidebar Section Name

### ISSUE THREAD

**Issue by jthodge** [github/docs#15614]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Specifically: [Managing a branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule)

Generally: Any article that uses the [`repository-branches.md` reusable](https://github.com/github/docs/blob/main/data/reusables/repositories/repository-branches.md).

### What part(s) of the article would you like to see updated?

**Currently** the [`repository-branches.md` reusable](https://github.com/github/docs/blob/main/data/reusables/repositories/repository-branches.md) instructs the reader to locate the "_Code & operations_" section of the sidebar. However, this instruction is outdated, as the section is now "_Code and automation_" and should read as such.

![CleanShot 2022-02-18 at 12 51 26](https://user-images.githubusercontent.com/17075617/154736073-a5b777de-862a-4189-8952-e5c85361b5d6.png)

**Comment by Tc1122** [comment]
Can you translate 'github' website to language malayalam
