### ISSUE TITLE
Bad Markdown syntax in translations/zh-CN/content/github/site-policy/github-community-guidelines.md

### ISSUE THREAD

**Issue by lwd-temp** [github/docs#15633]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/cn/github/site-policy/github-community-guidelines

### What part(s) of the article would you like to see updated?

Bad Markdown syntax in paragraph "不允许什么？"

For example,
```
####仇恨言论和歧视 虽然不禁止谈论年龄、身材、能力、种族、性别认同和表达、经验水平、国籍、外貌、民族、宗教或性认同和性取向等话题，但我们不允许基于身份特征攻击任何个人或群体。 只要认识到以一种侵略性或侮辱性的方式处理这些（及其他）敏感的专题，就可能使其他人感到不受欢迎甚至不安全。 虽然总是存在误解的可能性，但我们期望社区成员在讨论敏感问题时保持尊重和平静。
```
There should be a space between `####` and `仇恨言论和歧视`.

**Comment by ramyaparimi** [comment]
@lwd-temp 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
