### ISSUE TITLE
Slow to respond through December

### ISSUE THREAD

**Issue by janiceilene** [github/docs#1571]
Thank you so much for all the wonderful contributions to our repo 💖  We're so excited that you're here 🌟

We may be slow to respond from today (Monday, November 23rd) through the first week of January, as many people on the docs team will be taking time off.

**Comment by nitishgoukonde** [comment]
Thank you so much for all the wonderful contributions to our repo 💖 We're so excited that you're here 🌟

We may be slow to respond from today (Monday, November 23rd) through the first week of January, as many people on the docs team will be taking time off.

**Comment by Rungsungunkoom** [comment]
ขอบพระคุณครับ
ขอแสดงความนับถืออย่างสูง

**Comment by himanshu211raj** [comment]
I am a beginner on open source, as i need to contribute to open source so if you would suggest me how to contribute than this is beneficial for me as well as for open source.

**Comment by janiceilene** [comment]
@himanshu211raj Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions ✨

**Comment by machatman** [comment]
Is this my status I never updated yet?

**Comment by Realistman** [comment]
> Thank you so much for all the wonderful contributions to our repo  We're so excited that you're here 
> 
> We may be slow to respond from today (Monday, November 23rd) through the first week of January, as many people on the docs team will be taking time off.

**Comment by amein0** [comment]
سلام کمی بیشتر احتیاج به زمان داریم ما به صورت ناشناس کنار شما هستیم پرونده هنوز نواقص جزئی دارد و باید برسی شود ممنون از صبر و شکیبایی شما

**Comment by Jana-kasuar** [comment]
Hallo, Ich bin auch Beginner Open source code, aber man gibt es pull request. Thank you very much and happy New Year from Jana H. CZ, Děkuji😀🙋❤️🌼

**Comment by MikeMitStudentHU8** [comment]
JANICE
my health is important don't try and belittle me with all your bad feelings a distorted picture of other people who are vulnerable and insensitive to individuals like myself with disabilities and other issues.
It is not very good idea getting everybody going and saying and making things up with all your band of geeks misfits and keyboard warriors clever with it and other technology who follow like lost sheep giving people like myself who can't defend or deal with the stuff u are relentlessly are sending emails constantly 24/7 365
Very good game u playing Grow Up and Intimidating me all the time with you and your friends members like Americans all Big Gobbled Mouth Pricks Full Of Shit your all a Cult who fall under individuals like yourselves who then recruit and groom then brainwash the idiots in your strange views of the world and internet,


Definitely deluded and Sinister Individual Narcissistic Dangerous Slut
Hope You Get What Ever Karma
Thinks Is The Best Is For Your Rewards

Drop DEAD Quickly JANICE- SADNESS And Death I hope when BiteBack Happens Delusional SLUT SCUM Devil Worshiping Goading Shit Messiah Creepy Cunning Cunt get Help


u have a very bad attitude and the you  a Vile Horrible Disrespectful Gob Shite Full of Sadistic Unnecessary Viciously
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RodnyPHP** [comment]
Could say the same thing now to you, because I have cancer and have left maximum 5 years, so I( hope u will have a really good day! By the way speaking about the karma don’t worry, my life is almost over and I will be someones karma!

**Comment by Jana-kasuar** [comment]
I excusse for your health. I am greeting you health wellness - uzdravení - and very much success in New Year 2021. Thank you.
I am from Czech Republic, Central Europe. English is not my first language...
😊👩🎄🥨

**Comment by stevenans9859** [comment]
Oh, it's OK, I had just suffered from a bad car crash.... OK I know what I
shall do now is verify my personal details for you first then yes its time
for me to go business.

**Comment by stevenans9859** [comment]
Ok, take care.

**Comment by r0642879659th** [comment]
Thanks

**Comment by amein0** [comment]
Thank you for your patience .... You have a very big soul and you are a
very good person, you have a pure heart and I think you have a beautiful
future.  Hoping for a day without poverty and discrimination

در تاریخ سه‌شنبه ۲۹ دسامبر ۲۰۲۰،‏ ۲۰:۳۲ Jana Hranicka <
notifications@github.com> نوشت:

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Saturday, January 2, 2021 9:14:52 PM
To: GitHub <support@github.com>; GDS User Support <support+id4384825@govuk.zendesk.com>; github/docs <reply@reply.github.com>; BeNaughty <admin@benaughty.com>; TED Recommends <recommendations@ted.com>; ClickAndFlirt <admin@clickandflirt.com>; EbonBooty <admin@ebonbooty.com>; EbonyFlirt <admin@ebonyflirt.com>; Flirt <admin@flirt.com>; FlirtyDesires <admin@flirtydesires.com>
Subject: Hello PleaseCan Your Help Out For Tonight Saturday 2 January 2021 -unsubscribe-GitHub-Free & friend family Hello Evening Fun & Games Love From Flirt The Skir] > …s-and-teams/managing-access-to-your-organizations-repositories.md to المحتوى/جيثب/إنشاء وإ...


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Saturday, January 2, 2021 9:15:22 PM
To: GitHub <support@github.com>; GDS User Support <support+id4384825@govuk.zendesk.com>; github/docs <reply@reply.github.com>; BeNaughty <admin@benaughty.com>; TED Recommends <recommendations@ted.com>; ClickAndFlirt <admin@clickandflirt.com>; EbonBooty <admin@ebonbooty.com>; EbonyFlirt <admin@ebonyflirt.com>; Flirt <admin@flirt.com>; FlirtyDesires <admin@flirtydesires.com>
Subject: Re: Hello PleaseCan Your Help Out For Tonight Saturday 2 January 2021 -unsubscribe-GitHub-Free & friend family Hello Evening Fun & Games Love From Flirt The Skir] > …s-and-teams/managing-access-to-your-organizations-repositories.md to المحتوى/جيثب/إنشا...


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Saturday, January 2, 2021 9:14:52 PM
To: GitHub <support@github.com>; GDS User Support <support+id4384825@govuk.zendesk.com>; github/docs <reply@reply.github.com>; BeNaughty <admin@benaughty.com>; TED Recommends <recommendations@ted.com>; ClickAndFlirt <admin@clickandflirt.com>; EbonBooty <admin@ebonbooty.com>; EbonyFlirt <admin@ebonyflirt.com>; Flirt <admin@flirt.com>; FlirtyDesires <admin@flirtydesires.com>
Subject: Hello PleaseCan Your Help Out For Tonight Saturday 2 January 2021 -unsubscribe-GitHub-Free & friend family Hello Evening Fun & Games Love From Flirt The Skir] > …s-and-teams/managing-access-to-your-organizations-repositories.md to المحتوى/جيثب/إنشاء وإ...


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Rungsungunkoom** [comment]
Thankfully Thank you, everyone
Happy new year
Thank you for all

       Best  Regards
Mr.Rungsun  Gunkoom

ในวันที่ อา. 3 ม.ค. 2021 เวลา 04:17 MikeMitStudentHU8 <
notifications@github.com> เขียนว่า:

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
So sorry for all the inconvenience I have caused you all this time and sincerely apologies and promise to not make the same mistakes again I have noand caus




Get Outlook for<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:26 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Mistaken and Apologies To GitHub


So sorry for all the inconvenience I have caused you all this time and sincerely apologies and promise to not make the same mistakes again I have noand caus




Get Outlook for<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:51 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Re: Mistaken and Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:26 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Mistaken and Apologies To GitHub


So sorry for all the inconvenience I have caused you all this time and sincerely apologies and promise to not make the same mistakes again I have noand caus




Get Outlook for<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:43:52 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Re: Mistaken and Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:51 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Re: Mistaken and Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:26 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Mistaken and Apologies To GitHub


So sorry for all the inconvenience I have caused you all this time and sincerely apologies and promise to not make the same mistakes again I have noand caus




Get Outlook for<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Very sorry GitHub

Yours sincerely

Michael Mckenzie


Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:54:50 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:43:52 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Re: Mistaken and Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:51 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Re: Mistaken and Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:26 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Mistaken and Apologies To GitHub


So sorry for all the inconvenience I have caused you all this time and sincerely apologies and promise to not make the same mistakes again I have noand caus




Get Outlook for<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:57 am
To: github/docs; GitHub
Subject: Re: Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:54:50 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:43:52 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Re: Mistaken and Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:51 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Re: Mistaken and Apologies To GitHub


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mike Mckenzie <mmkmhull@outlook.com>
Sent: Sunday, January 3, 2021 8:42:26 AM
To: github/docs <reply@reply.github.com>; GitHub <support@github.com>
Subject: Mistaken and Apologies To GitHub


So sorry for all the inconvenience I have caused you all this time and sincerely apologies and promise to not make the same mistakes again I have noand caus




Get Outlook for<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Very sorry for everything

Yours sincerely

Mike Mckenzie

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by Jana-kasuar** [comment]
Hello,

Thanks very much for your work and have a good time to get to the repository. I wish you success in all New year.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jace4511** [comment]
> Thank you so much for all the wonderful contributions to our repo 💖 We're so excited that you're here 🌟
> 
> We may be slow to respond from today (Monday, November 23rd) through the first week of January, as many people on the docs team will be taking time off.

**Comment by jace4511** [comment]
> Thank you so much for all the wonderful contributions to our repo 💖 We're so excited that you're here 🌟
> 
> We may be slow to respond from today (Monday, November 23rd) through the first week of January, as many people on the docs team will be taking time off.

**Comment by MikeMitStudentHU8** [comment]
Some and I have had to get some things to do for my family soon,

Kind regards

Mike Mckenzie

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Hi xx,

Bringing the kid’s around later on for some snacks and games for a little bit of relaxing and chill out times .

Kind regards

Mike Mckenzie

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jana-kasuar** [comment]
Hi, Mike -😊

I Thank you very much, too. For your email and thanks and repos and writes.

I am only learning, master, my GitHub Enterprise is possibility enable through Azure Portal, it is maybe 19 Euros. I have too learn about PC and English Communicate with my intermediate friends or colleagues in master.

Thank you for your pleasant. I have not iTune, but Windows and android 9.

Ahoj Hello

Odesláno z aplikace Pošta<https://go.microsoft.com/fwlink/?LinkId=550986> pro Windows 10

Od: MikeMitStudentHU8<mailto:notifications@github.com>
Odesláno:neděle 3. ledna 2021 14:54
Komu: github/docs<mailto:docs@noreply.github.com>
Kopie: Jana Hranicka<mailto:janahranicka@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Předmět: Re: [github/docs] Slow to respond through December (#1571)

Hi xx,

Bringing the kid’s around later on for some snacks and games for a little bit of relaxing and chill out times .

Kind regards

Mike Mckenzie

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by janiceilene** [comment]
We are back! It'll take us some time to catch up with all of your wonderful contributions 💛
