### ISSUE TITLE
Add notice about limits for inputs` for a `workflow_dispatch` event

### ISSUE THREAD

**Issue by IMKnysh** [github/docs#15710]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I am trying to configure Github Action with more than 10 `inputs` for a `workflow_dispatch` event and I am getting the  error:

**[Invalid workflow file: .github/workflows/create_feature_branch.yml#L1](https://github.com/Lolo-Health/lolo-infrastructure/actions/runs/1878343346/workflow)
you may only define up to 10 `inputs` for a `workflow_dispatch` event**

### What changes are you suggesting?

We definitely need to add notice about such limit and increase it

**Comment by ramyaparimi** [comment]
@IMKnysh 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! You or anyone else is welcome to document this limit. To request an increase to this limit, you can open a discussion in https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback
