### ISSUE TITLE
'All activity' does not show content from starred/watched repositories

### ISSUE THREAD

**Issue by thsmdt** [github/docs#15745]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[About your personal dashboard > Staying updated with activity from the community](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/about-your-personal-dashboard#staying-updated-with-activity-from-the-community)

### What part(s) of the article would you like to see updated?

At the beginning of the linked-to paragraph, it states:

> In the "All activity" section of your news feed, you can view updates from repositories you're subscribed to and people you follow. The "All activity" section shows updates from repositories you watch or have starred, and from users you follow.

However, it appears the feature does (no longer?) work this way and only shows updates from users, not repositories one has starred.

Thus, I would recommend removing the mention of *updates from repositories you watch or have starred* in this paragraph 😄

### Additional information

To ensure that I understood the feature correctly, I opened a discussion on GitHub Support about [content of starred repositories in the activity feed](https://github.community/t/github-activity-feed-not-showing-starred-activity/230986) beforehand.

**Comment by ramyaparimi** [comment]
@thsmdt 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
