### ISSUE TITLE
Better explanation for "Used by" section

### ISSUE THREAD

**Issue by chamini2** [github/docs#15750]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#dependents-view

### What part(s) of the article would you like to see updated?

I think the process to getting your package recognized from GitHub is not really explained, it says

> If the dependency graph is enabled, and your repository contains a package that's published on a supported package ecosystem, GitHub displays a "Used by" section in the sidebar of the Code tab of your repository. For more information about the supported package ecosystems, see "[About the dependency graph](https://docs.github.com/en/github/visualizing-repository-data-with-graphs/about-the-dependency-graph#supported-package-ecosystems)."

But then when checking the [`About the dependency graph`](https://docs.github.com/en/github/visualizing-repository-data-with-graphs/about-the-dependency-graph#supported-package-ecosystems) link, it only states how to parse DEPENDENCIES of a project, not how to get your project recognized as a possible dependency.

### Additional information

<details><summary>Click to show the information used to debug this issue...</summary>

Currently I am trying to get a public repo of a PyPI library to show the `Used by` section and I have had no luck on making it pick up the package.

- [PyPI package](https://pypi.org/project/fal/)
- [Repository](https://github.com/fal-ai/fal)
- [Other repo using said package](https://github.com/fal-ai/fal_dbt_examples/network/dependencies)
<img width="536" alt="image" src="https://user-images.githubusercontent.com/2745502/155229442-ad93fa0b-4c60-46b6-b46c-cdf03cb01225.png">

</details>

---
_Update from a maintainer_

### Content changes needed

1. [Dependencies view](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#dependencies-view) - update the first paragraph to make it clear that links are only shown if the package manager for the dependency links to the source code in a public repository on GitHub.
2. [Changing the "Used by" package](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#changing-the-used-by-package) - revise the first paragraph to make it clear that the "Used by" section is shown only if:
    - Your repository contains a package that's published on a supported ecosystem.
    - In the ecosystem, your package has a link to the a public repository in GitHub where the source is stored.
    - Dependency graph is enabled for the repository.

**Comment by ramyaparimi** [comment]
@chamini2 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
Hi @chamini2 - I've asked an internal team about this and will let you know as soon as they get back to me.

**Comment by chamini2** [comment]
Great, thank you both!

**Comment by felicitymay** [comment]
Hi @chamini2 - the internal team confirms that the docs are correct and that you should not need to take any other steps for the dependent to show up as you expect. We've opened an internal issue for the team to investigate why your dependent isn't showing up.

**Comment by felicitymay** [comment]
Since this does not appear to be a problem with the docs, I'm going to close this issue.

**Comment by chamini2** [comment]
Ok @felicitymay, thank you very much.

**Comment by chamini2** [comment]
>  We've opened an internal issue for the team to investigate why your dependent isn't showing up.

Is there anywhere I should be reporting this sort of issue instead? Or a way to know about the results of this ticket?

**Comment by felicitymay** [comment]
That's a great question. The [GitHub Community](https://github.community/) is a great place to ask questions. For feedback or to let us know that something seems broken, I think the preferred place is the discussions in our [feedback repository](https://github.com/github/feedback/discussions/).

I've linked this issue to the internal issue and I would hope that they'd update this issue when they resolve the internal issue.

**Comment by chamini2** [comment]
OK, thank you! I had asked a [GitHub Community question with on answer](https://github.community/t/github-repo-not-showing-used-by-section/229655)  and now I just opened a discussion in feedback repo https://github.com/github/feedback/discussions/12101

**Comment by lseppala** [comment]
Hi @chamini2! Here's the explanation for why `fal` isn't being recognized with a link to the repository in GitHub: 

For the `fal` package, the reason there's no link to the repo in the Dependency Graph is because there is no `Source Code` URL set for the [package on PyPI](https://pypi.org/project/fal/). A button link to the source code repository will be rendered in the left sidebar of the package page when the URL is set. For instance, the `datadog_api_client` package [published in PyPI](https://pypi.org/project/datadog-api-client/) provides a `Source Code` URL to the GitHub repo. We are able to use this information to associate the package with the repository, even though the repo and package use different names.

We rely on information published with the public registries (like PyPI) to associate packages to their repositories. If the package in the registry doesn't provide this metadata, we typically don't try to assume where the source for this repository is (it could be anywhere!) 🙂 

The way to fix this would be to update the `fal` package in PyPI with a Source Code URL. The change will take time to take effect in our system (and it helps if there's a new version published in the registry that's used by a project, which triggers our system).

I see that it isn't clear that the package needs to specify a URL on it's registry page to be used in Dependency Graph. I am curious if @felicitymay has any ideas on ways to help people know what to do in this circumstance—it's tricky because there's a lot of registries, and it'd be a lot if we had to document all of them! 

I hope this helps!

**Comment by felicitymay** [comment]
@chamini2 - I'm going to reopen this issue and next week we can work out how to up date the docs to help people who run into the same problem.

**Comment by felicitymay** [comment]
@chamini2 - I'm wondering if the following changes to the docs would have helped you work out how to get your dependency to show up as expected (I'll also check them with our internal team to make sure that I've correctly understood).

1. [Dependencies view](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#dependencies-view) - update the first paragraph to make it clear that links are only shown if the package manager for the dependency links to the source code in a public repository on GitHub.
2. [Changing the "Used by" package](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#changing-the-used-by-package) - revise the first paragraph to make it clear that the "Used by" section is shown only if:
    - Your repository contains a package that's published on a supported ecosystem.
    - In the ecosystem, your package has a link to the a public repository in GitHub where the source is stored.
    - Dependency graph is enabled for the repository.

**Comment by lseppala** [comment]
@felicitymay Those are good updates. I'm always amazed how technical writers can simplify the mess of reasons that engineering gives out into something readable 😄 

@chamini2 Our system for trying to correlate repos and dependencies is fairly complex with a few different fall-backs. It may be that `dbt-core` previously published a Source Code link in previous versions, and we rely on the historical to associate the repo.

I see that `fal` now has a link in PyPI! Let me know in a couple of days if you don't see the link update for packages that dependend on `fal` (our process to get the metadata is on a schedule).

**Comment by chamini2** [comment]
@felicitymay , that would have helped for sure! Thank you

@lseppala OK, understood! I will let you know here again if it does not connect. Thanks for letting me know about the schedule.

**Comment by felicitymay** [comment]
Thanks @chamini2 and @lseppala for your help working out what the problem was and how we can make the docs clearer.

I've updated the issue summary with the proposed docs changes and I'll add a `help wanted` label to it.
