### ISSUE TITLE
Sample Conditions for OIDC Policy

### ISSUE THREAD

**Issue by matthewcarter95** [github/docs#15769]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#configuring-the-role-and-trust-policy

### What part(s) of the article would you like to see updated?

The addition of ForAllValues in the operator introduces the potential for some unexpected results. From the [docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html#reference_policies_multi-key-or-value-conditions):

> The condition returns true if every key value in the request matches at least one value in the policy. It also returns true if there are no keys in the request, or if the key values resolve to a null data set, such as an empty string.

I recognize that this was added to allow custom claims. I suggest a compromise of breaking sub into a separate condition.

```
"Condition": {
                "ForAllValues:StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringEquals": {
                    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
                }
            }
```

### Additional information

When policy validation is added for role trust policies, the FORALLVALUES_WITH_SINGLE_VALUED_KEY check would be triggered for the sample condition as written.

**Comment by ramyaparimi** [comment]
@matthewcarter95 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by ramyaparimi** [comment]
@matthewcarter95 Thanks so much for your patience. I spoke with the team and we are not going to accept this contribution :yellow_heart: . We really appreciate your time and interest in improving GitHub docs 💖 .
