### ISSUE TITLE
Document interaction between deploy keys and changes to a pull request branch created from a fork

### ISSUE THREAD

**Issue by jsoref** [github/docs#15760]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys

### What part(s) of the article would you like to see updated?

The texts in question say:

https://github.com/github/docs/blob/fb2aa91ca1dd9f7b60a63ce556edff292b24a811/data/reusables/repositories/deploy-keys-write-access.md#L1
>  Deploy keys with write access can perform the same actions as an organization member with admin access, or a collaborator on a personal repository. For more information, see "[Repository roles for an organization](/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization)" and "[Permission levels for a user account repository](/articles/permission-levels-for-a-user-account-repository/)." 

https://github.com/github/docs/blob/315b95a149be9cb1cf6791d5fde9ec5a6b39dc60/content/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork.md#L18-L22

>  You can only make commits on pull request branches that: 
> - are opened in a repository that you have push access to and that were created from a fork of that repository 
> - are on a user-owned fork 
> - have permission granted from the pull request creator 
> - don't have [branch restrictions](/github/administering-a-repository/about-protected-branches#restrict-who-can-push-to-matching-branches) that will prevent you from committing 

---

Resolutions:

* Add an extra bullet `when you are not using a deploy key` (I actually can't think of any way to write language here that isn't awkward)
* Update the deploy key text to clarify that they can't perform the same actions, but can perform similar actions limited to the specific repository for which they're assigned

* Alternatively, if you like the documentation (and I do), perhaps the implementation could be changed to match the documentation.

In the interim, this bug documents that the implementation and documentation do not appear to correspond.

### Additional information

Scenario:
* read-write deploy key in destination repository
* pull request created from a repository in the same fork network (neither are the root, but that's not technically a problem -- in the example, the destination is actually a fork of the source)
* source repository is owned by a user
* pull request includes permission grant

1. By definition, it has push access to the destination repository -- first half of first bullet
2. Pull request is from a fork of that repository -- second half of first bullet
3. Pull request is from a user fork (not an organization) -- second bullet
4. Pull request includes grant from pull request creator to update the PR -- third bullet
5. There is no branch protection on the source branch of the pr -- fourth bullet

---

1. I read the documentation as saying that a deploy key has the same permissions as an admin to the repository
2. I've added a read-write deploy key to a repository
3. I've created a pull request from a personal repository to the repository which has a workflow that uses that deploy key
4. I have checked `Allow edits and access to secrets by maintainers`:
    <img width="293" alt="image" src="https://user-images.githubusercontent.com/2119212/155256538-49fb345f-4fb1-4d41-b173-332f523219a2.png">
5. I created a comment per the workflow which triggered a comment event handler:
    - https://github.com/check-spelling/dovecot-documentation/pull/10#issuecomment-1048409394
6. The event triggered a workflow:

https://github.com/check-spelling/dovecot-documentation/runs/5298106411?check_suite_focus=true#step:3:68
```
From github.com:jsoref/dovecot-documentation
 * branch            9ac17754cc727f716206504061a3b98[69](https://github.com/check-spelling/dovecot-documentation/runs/5298106411?check_suite_focus=true#step:3:69)5b15f2d -> FETCH_HEAD
HEAD is now at a117c[73](https://github.com/check-spelling/dovecot-documentation/runs/5298106411?check_suite_focus=true#step:3:73) Add forbidden patterns
HEAD is now at 9ac17[75](https://github.com/check-spelling/dovecot-documentation/runs/5298106411?check_suite_focus=true#step:3:75) Add unknown word
[detached HEAD 93009b5] [check-spelling] Applying automated metadata updates
 Author: Josh Soref <jsoref@users.noreply.github.com>
 Date: Wed Feb 23 03:05:27 2022 +0000
 1 file changed, 1 insertion(+)
ERROR: Permission to jsoref/dovecot-documentation.git denied to deploy key
fatal: Could not read from remote repository.
Error: Failed to push to git@github.com:jsoref/dovecot-documentation.git

Please make sure you have the correct access rights
and the repository exists.
Error: Process completed with exit code 1.
```

**Comment by jsoref** [comment]
For comparison, the `GITHUB_TOKEN` documentation is explicit in noting that it can't be used outside its repository:

https://github.com/github/docs/blob/315b95a149be9cb1cf6791d5fde9ec5a6b39dc60/content/actions/security-guides/automatic-token-authentication.md#L24

>  When you enable {% data variables.product.prodname_actions %}, {% data variables.product.prodname_dotcom %} installs a {% data variables.product.prodname_github_app %} on your repository. The `GITHUB_TOKEN` secret is a {% data variables.product.prodname_github_app %} installation access token. You can use the installation access token to authenticate on behalf of the {% data variables.product.prodname_github_app %} installed on your repository. The token's permissions are limited to the repository that contains your workflow. For more information, see "[Permissions for the `GITHUB_TOKEN`](#permissions-for-the-github_token)." 

As exemplified by:
https://github.com/check-spelling/dovecot-documentation/runs/5299206913?check_suite_focus=true#step:3:68

```
From https://github.com/jsoref/dovecot-documentation
 * branch            9ac17754cc727f716206504061a3b98[69](https://github.com/check-spelling/dovecot-documentation/runs/5299206913?check_suite_focus=true#step:3:69)5b15f2d -> FETCH_HEAD
HEAD is now at a117c[73](https://github.com/check-spelling/dovecot-documentation/runs/5299206913?check_suite_focus=true#step:3:73) Add forbidden patterns
HEAD is now at 9ac17[75](https://github.com/check-spelling/dovecot-documentation/runs/5299206913?check_suite_focus=true#step:3:75) Add unknown word
[detached HEAD a6309f1] [check-spelling] Applying automated metadata updates
 Author: Josh Soref <jsoref@users.noreply.github.com>
 Date: Wed Feb 23 05:58:03 2022 +0000
 1 file changed, 1 insertion(+)
remote: Permission to jsoref/dovecot-documentation.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/jsoref/dovecot-documentation.git/': The requested URL returned error: 403
Error: Failed to push to https://github.com/jsoref/dovecot-documentation.git
Error: Process completed with exit code 1.
```

My personal preference would be for both of these workflows to work.

But short of that, the documentation for deploy keys should have text similar to the text for `GITHUB_TOKEN`.

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by chriskirkland** [comment]
For context, the coding team did a [great initial investigation and write up](https://github.slack.com/archives/CGK52DFEV/p1647294949181049?thread_ts=1646754284.970589&cid=CGK52DFEV) for what's going on here.  Namely, deploy keys are subject to fork-collab permissions [generically in Dotcom](https://github.com/github/github/blob/a7944949988209a4e0d09c5567fb3973b8a55931/app/models/repository/organizations_dependency.rb#L144-L163) (e.g. Action) but [not in GitAuth].(https://github.com/github/github/blob/a7944949988209a4e0d09c5567fb3973b8a55931/lib/git_auth/authorization.rb#L224-L230).  Updating the documentation feels like a bandaid; I think we need to reconcile those differences.

My initial impression is that we limit the scope of deploy keys to a single repository, which seems to be their original intent, to avoid granting unintended permissions.  A few initial questions:
1. Was the support for fork-collab permissions in deploy keys intentional?  (/cc @github/product-security-engineering)
2. Are there other cases where deploy key permissions extend beyond scope of single repository?
3. How widely is the usage of this "combination of features" today?  This may be hard to gather.

Depending on what how we answer those questions, we should retool this as an github.com/github/authentication issue.

**Comment by ramyaparimi** [comment]
@jsoref Thanks so much for opening this issue. An issue has been opened to track this internally so I am going to close this issue now 💛 .

Thanks so much for your passion in improving the GitHub docs 💖
