### ISSUE TITLE
Link rot in `creating-a-pull-request-template-for-your-repository`

### ISSUE THREAD

**Issue by dylmye** [github/docs#15815]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### What part(s) of the article would you like to see updated?

Link in para 2:

> For more information, see "[About automation for issues and pull requests with query parameters](https://docs.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters)."

This link now leads to a more general article, the relevant content is under a sub-heading that should be linked specifically so users are not lost: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query

### Additional information

By "link rot", I am referring to a change to the linked resource that was not expected in the place where it was linked.

**Comment by staffordduptey23** [comment]
Y

**Comment by staffordduptey23** [comment]
J

**Comment by selectwilliams** [comment]
k
