### ISSUE TITLE
[User feedback] Add new troubleshooting section to CodeQL article

### ISSUE THREAD

**Issue by felicitymay** [github/docs#15967]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Troubleshooting the CodeQL workflow](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow)

### What part(s) of the article would you like to see updated?

Question from user:

> "In my workload, analysis fails on generated code (which is thus known to be good). How can I suppress such false positives?"

Docs update needed:

[Troubleshooting the CodeQL workflow](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow)

- In the section "Reduce the amount of code being analyzed in a single workflow", convert the 2nd, 3rd and 4th paragraphs to a reusable.
- Add a new section called "Alerts found in generated code" use the new reusable.

For information about reusables, see [Reusables and variables](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#reusables-and-variables) and [docs/data/reusables/README.md](https://github.com/github/docs/blob/main/data/reusables/README.md)

### Additional information

Showing the same content twice in one article may seem strange. However, this will make it more discoverable for users who want to exclude code from analysis for reasons apart from their build taking too long.

**Comment by applnew777** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on [docs.github.com](http://docs.github.com) is affected?
> [Troubleshooting the CodeQL workflow](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow)
> 
> ### What part(s) of the article would you like to see updated?
> Question from user:
> 
> > "In my workload, analysis fails on generated code (which is thus known to be good). How can I suppress such false positives?"
> 
> Docs update needed:
> 
> [Troubleshooting the CodeQL workflow](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow)
> 
> * In the section "Reduce the amount of code being analyzed in a single workflow", convert the 2nd, 3rd and 4th paragraphs to a reusable.
> * Add a new section called "Alerts found in generated code" use the new reusable.
> 
> For information about reusables, see [Reusables and variables](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#reusables-and-variables) and [docs/data/reusables/README.md](https://github.com/github/docs/blob/main/data/reusables/README.md)
> 
> ### Additional information
> Showing the same content twice in one article may seem strange. However, this will make it more discoverable for users who want to exclude code from analysis for reasons apart from their build taking too long.

**Comment by Mondjoe** [comment]
Thank you so much guys!
