### ISSUE TITLE
700+ broken reference links for several days

### ISSUE THREAD

**Issue by metasean** [github/docs#15992]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps

As far as I can tell, **_every_** link listed under "Endpoints available for GitHub Apps" have been 404ing for several days.  The 404 page does state, "We track these errors automatically, but if the problem persists please feel free to contact us." —with **_just over 700 broken reference links_** that have been broken for days, it seemed appropriate to try and elevate this issue.

### What changes are you suggesting?

Fixing the links.

**Comment by ramyaparimi** [comment]
@metasean 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
Thank you so much for raising this @metasean - it looks as if some automation must have gone wrong 😞 

The engineering team are looking into.

**Comment by rachmari** [comment]
@metasean thanks for reporting this! ❤️ I believe this has been fixed. Let me know if you still see an issue. 🙇‍♀️

**Comment by peterbe** [comment]
THANK YOU @metasean !
We tracked this in another duplicate issue and forgot to make the PR auto-close *this* issue.

**Comment by MAC-ARTHUR-TRUE** [comment]
Madison chambers or Chamberlin POW MIA Afghanistan IRAC,  impersonated by Pamela mceandry, calling themselves Steve and Mary Female identity change to Paris Pichai or Pichilli Apaguasa. Secured identity with "memory" software accounts of DreamWorks high jacked used against her by known criminals and theives.Stalking of female documented with federal restraining order permanent. Paris 304 663 4110 Sent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/28/22  15:53  (GMT-05:00) To: ***@***.*** Subject: FW: Urgent HelpSent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/28/22  3:51 PM  (GMT-05:00) To: ***@***.*** Subject: FW: Urgent Data pushesMasked ipPhone info changesAll obsevedSent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/24/22  12:07 AM  (GMT-05:00) To: ***@***.*** Subject: Urgent Crime Sent from my  U.S.Cellular© SmartphoneSent from my  U.S.Cellular© Smartphone
-------- Original message --------From: Felicity Chapman ***@***.***> Date: 3/3/22  12:18  (GMT-05:00) To: github/docs ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [github/docs] 700+ broken reference links for several days (Issue #15992) 

Thank you so much for raising this @metasean - it looks as if some automation must have gone wrong 😞

The engineering team are looking into.
