### ISSUE TITLE
Reference pages seems to load in a random language sometimes

### ISSUE THREAD

**Issue by warnerpr** [github/docs#16006]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/webhooks for example, but seems to happen on other reference pages.

### What changes are you suggesting?

Would be great to stick to language selected :-) 

### Additional information

See screen shot, seen on `Chrome Version 98.0.4758.109 (Official Build) (x86_64)`, on Mac, but reproduced via Chrome on Linux and also Mac Safari.  I've seen it load in a mix of Japanese and English, and also in Spanish (or is it Portuguese?)

Seems to appear on other pages as well, see second screen shot.

It's intermittent, you may need to refresh a few times to see the issue.

I'm really sorry I'm not enough of a web developer to sort this one out right now.
If I get a chance I'll try to look in develop tools a bit.

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/1381291/156477242-9bfd84b2-8eef-4604-a0b6-3718e44f37cf.png">

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/1381291/156477666-00e2c67e-df91-4a4a-aac0-1ac489b9480e.png">

**Comment by ramyaparimi** [comment]
@warnerpr 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by rachmari** [comment]
@warnerpr I put a fix in for this last night. This should be fixed, but please let me know if you're still seeing this issue.

**Comment by warnerpr** [comment]
Thanks @rachmari, looks fixed to me!  
Looking at https://github.com/github/docs/commit/764966735bec4ef3238ea075e44b42a360d32359 I am really glad I didn't try to debug this!  I'll stick to back end for now!
Thanks again!

**Comment by Nikola29-d** [comment]
Thanks
