### ISSUE TITLE
The instruction in the article "Duplicating a repository" is a little confusing and can be made more clear.

### ISSUE THREAD

**Issue by deepansh96** [github/docs#16018]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository

### What part(s) of the article would you like to see updated?

https://user-images.githubusercontent.com/20169829/156549749-c2aa279a-c79c-4a68-aac5-e3e84bc55bb3.png

As you can see in the image above, this is not really correct.
When I `--bare` clone a repository, the folder that gets pulled into my local is `my_folder.git` instead of `my_folder`.

While reading this doc, it got me super confused as to which one to `cd` into and then which one to `rm -rf`.
Because in my case, I had a proper clone of a repo in a directory. Then I made a `--bare` clone in the repo. There were two directories `my_folder` and `my_folder.git` and it was not super clear to me which one to use.

**Comment by stevecat** [comment]
Closed in https://github.com/github/docs/issues/16017
