### ISSUE TITLE
Provide more visibility for the article on skipped but required checks

### ISSUE THREAD

**Issue by toonn** [github/docs#16048]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Handling skipped but required checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks)

### What part(s) of the article would you like to see updated?

This article is really hard to find. Maybe it can be part of the normal Actions documentation [here](https://docs.github.com/en/actions/learn-github-actions). I've been looking for a way to do this for months now and it didn't turn up until I asked someone else whether they knew if it was even possible.

**Comment by fejalpathan** [comment]
Helo word hi im new user for the github please help me 
Why this web use

**Comment by ramyaparimi** [comment]
@toonn 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by david-bain** [comment]
While you are at it can you please check the validity of the content or if there is a bug in the implementation?
I had a check that was skipped due to a `needs` job failing and the skip counted as a pass for merging, not what it said in the document. For clarity, the `needs` referred to a matrix job where some of the instances failed and I could reliably replicate this bug.

**Comment by skedwards88** [comment]
Thank you for opening this issue! I agree that it would be good to make this article more discoverable. I suggest adding a link to [Troubleshooting required status checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks) from [Triggering a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters), where we introduce filtering. You or anyone is welcome to open a PR to address this.

**Comment by skedwards88** [comment]
> While you are at it can you please check the validity of the content or if there is a bug in the implementation? I had a check that was skipped due to a `needs` job failing and the skip counted as a pass for merging, not what it said in the document. For clarity, the `needs` referred to a matrix job where some of the instances failed and I could reliably replicate this bug.

@david-bain Thanks for your question! It would be best if you open a new issue for your request and included links to workflow files/logs to demonstrate your situation. https://github.community/ is probably a better place to post your question. You can then open an issue here to update the docs.

**Comment by skedwards88** [comment]
> While you are at it can you please check the validity of the content or if there is a bug in the implementation? I had a check that was skipped due to a `needs` job failing and the skip counted as a pass for merging, not what it said in the document. For clarity, the `needs` referred to a matrix job where some of the instances failed and I could reliably replicate this bug.

@david-bain Thanks for your question! It would be best if you open a new issue for your request and included links to workflow files/logs to demonstrate your situation. https://github.community/ is probably a better place to post your question. You can then open an issue here to update the docs.

**Comment by donatocayurin** [comment]
thank you very much guys

**Comment by donatocayurin** [comment]
thank you

**Comment by donatocayurin** [comment]
thanks

**Comment by donatocayurin** [comment]
thanks

**Comment by donatocayurin** [comment]
thank you
