### ISSUE TITLE
managing-deploy-keys is outdated

### ISSUE THREAD

**Issue by nano-cube** [github/docs#16134]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/overview/managing-deploy-keys

says:

> From your repository, click Settings.
   In the sidebar, click Deploy Keys, then click `Add deploy key`.

But as you can see there is no `Add deploy key` section:

![image](https://user-images.githubusercontent.com/48186211/157209766-4f26521c-f120-4067-9371-d8d0fd941a72.png)

### What part(s) of the article would you like to see updated?

Where to find the deploy keys section.

**Comment by ramyaparimi** [comment]
@nano-cube 
Thanks for opening this issue! I think [GitHub support](https://support.github.com/contact) or [GitHub Support Community](https://github.community/) would be the best place to ask this question 💛

**Comment by nano-cube** [comment]
> @nano-cube Thanks for opening this issue! I think [GitHub support](https://support.github.com/contact) or [GitHub Support Community](https://github.community/) would be the best place to ask this question yellow_heart

Is it not an error in the documentation? In which case the docs would need to be fixed, not for support to be contacted.

**Comment by ramyaparimi** [comment]
@nano-cube I followed the instructions in the page and was able to find "Deploy keys" 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/33761166/157451466-4fa050c2-abaf-4e2c-a630-881e72c8053c.png">

and in that "Add deploy keys".
<img width="837" alt="image" src="https://user-images.githubusercontent.com/33761166/157451493-6ff2b342-ee1f-40f6-a63c-5c2844320ab1.png">

The support would be the right team to ask this questions 💛.
