### ISSUE TITLE
Instructions for cloning a VM with a self-hosted runner

### ISSUE THREAD

**Issue by ruvceskistefan** [github/docs#16142]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners

### What part(s) of the article would you like to see updated?

The customer encountered a bug while cloning a VM with a self-hosted runner. Since this can be complex for implementation on the runner itself, I suggest that the steps for workaround solution be listed in the documentation, as the new heading: **Cloning VM with self-hosted runner**.

The documentation needs to be changed because this can be a very useful thing for customers, especially if they would have detailed instructions for cloning VM with a self-hosted runner.

The expected outcome is that the documentation contains steps that explain to the customer how to clone a VM with a self-hosted runner, as this is a functionality that can be useful to a larger number of customers.

### Additional information

This is the original [issue](https://github.com/actions/runner/issues/1286) in actions/runner repo.
This is the proposed solution to be added to the documentation (with additional description for each step):

1. Clone a VM with a runner.
2. Start target VM.
3. Go to GitHub, create new Runner. DO NOT CLOSE THE PAGE.
4. Log on to target VM.
5. do `./config.sh remove`
6. When it asks, use the NEW TOKEN as the Runner Remove Token (from the page you didn't close)
7. Now that the runner's removed, configure it the normal way.
8. do `./config.sh --url https://github.com/yourorgOrRepoURL --token xx_TheNewToken_xx` with the token from the page you didn't close.
9. do `sudo ./svc.sh install`
10. do `sudo ./svc.sh start`

**Comment by ruvceskistefan** [comment]
In my opinion, the following instructions should be added to the documentation:

---------------------------------
### Cloning VM with self-hosted runner

 If you have virtual machine with a self-hosted runner installed, you may found it useful to clone that virtual machine. To successfully clone a virtual machine with a self-hosted runner installed, you need to do folowing steps:

 1. Clone a virtual machine with a self-hosted runner.
 2. Start target virtual machine.
 3. Go to GitHub.com and create a new runner.
 4. Log on to the target virtual machine.
 5. Remove self-hosted runner using the token from the step 3.
 6. Configure it using the token from the step 3.

 Now you can configure runner as a service.
 
 ---------------------------------
 
 I am willing to make a PR, but I had difficulties with changes in the documentation, so help would be welcome (if you agree with the proposed changes).

**Comment by ramyaparimi** [comment]
@ruvceskistefan 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Hi @ruvceskistefan, thanks for this suggestion. I think the problems that you are having is that you are cloning a VM that has already been added as a self-hosted runner. This is not a recommended approach.

For your VM image, it should be saved in a state where it is not already attached as a self hosted runner. The runner app can be pre-installed on the machine, but it shouldn't be added to a repository when it the VM image is saved.

As you've discovered, if a machine has already been added to a repo/org/enterprise as a self-hosted runner (and you want to add it to another repo/org/enterprise), you must first remove it from being a self-hosted runner in the original location.

This process isn't unique to VMs, so I don't think a new procedure is necessary. If you are doing this frequently, you might want to look into [an autoscaling solution](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners) or using [our API](https://docs.github.com/en/rest/reference/actions#self-hosted-runners).
