### ISSUE TITLE
Fix typo in portuguese translation

### ISSUE THREAD

**Issue by kamuango-elton** [github/docs#16197]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Criar pull request](https://docs.github.com/pt/get-started/quickstart/be-social#creating-pull-requests)

### What part(s) of the article would you like to see updated?

- The article
![2022-03-12_00-48](https://user-images.githubusercontent.com/89164979/157992247-dadfe0f6-013b-4f29-a440-b7563177bcf0.png)

From this :```Talvez você queira contribuir com o o projeto de outra pessoa, seja adicionando recursos, seja corrigindo erros.```

To this :`Talvez você queira contribuir com o projeto de outra pessoa, seja adicionando recursos, seja corrigindo erros.`

**Comment by SMIRKyy1** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> [Criar pull request](https://docs.github.com/pt/get-started/quickstart/be-social#creating-pull-requests)
> 
> ### What part(s) of the article would you like to see updated?
> * The article
>   ![2022-03-12_00-48](https://user-images.githubusercontent.com/89164979/157992247-dadfe0f6-013b-4f29-a440-b7563177bcf0.png)
> 
> From this :`Talvez você queira contribuir com o o projeto de outra pessoa, seja adicionando recursos, seja corrigindo erros.`
> 
> To this :`Talvez você queira contribuir com o projeto de outra pessoa, seja adicionando recursos, seja corrigindo erros.`
> 
> ### Additional information
> _No response_

**Comment by parkjimin19** [comment]
Tá certo

**Comment by ramyaparimi** [comment]
@kamuango-elton 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.

**Comment by kamuango-elton** [comment]
@ ramyaparimi
Thanks for your attention about this.

Em qua., 16 de mar. de 2022 às 14:13, Ramya Parimi ***@***.***>
escreveu:
