### ISSUE TITLE
Masked outputs are not passed and are considered as secrets

### ISSUE THREAD

**Issue by nikola-jokic** [github/docs#16274]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-log

### Additional information

There were multiple issues in the actions/runner repository ([1061](https://github.com/actions/runner/issues/1061),[1498](https://github.com/actions/runner/issues/1498)) and the community [discussion](https://github.community/t/skip-output-aws-account-id-since-it-may-contain-secret/123791) related to this update.

**Comment by bsgarage45** [comment]
#bsgaraj45
