### ISSUE TITLE
Use of invalid type in `workflow-dispatch-inputs.md`

### ISSUE THREAD

**Issue by SpraxDev** [github/docs#16284]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs

### What part(s) of the article would you like to see updated?

According to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype `environment` is not a valid input type. And when using it, it only shows up as an option select menu without anything to select.

As it is never used in the workflow, maybe it should be removed from the example or turned into a select with the value being provided to `runs-on` for the job.

### Additional information

File in question: `data/reusables/actions/workflow-dispatch-inputs.md`

**Comment by Bad-black-king-yo-jack** [comment]
Ok

**Comment by ramyaparimi** [comment]
@SpraxDev 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ethomson** [comment]
Hi @SpraxDev!

> According to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype environment is not a valid input type.

It's not a valid input type for `workflow_call` events, but it is a valid input type for `workflow_dispatch` events.

> when using it, it only shows up as an option select menu without anything to select.

This is true if you don't have any environments. If you do have environments configured, those should be in the select box.

I hope this clarifies a bit. But please do feel free to open a pull request with any improvements that you think could be made!

**Comment by SpraxDev** [comment]
Alright, thanks for the info!
