### ISSUE TITLE
`Build and Push Main Preview Env Docker Cache` workflow doesn't look before it leaps

### ISSUE THREAD

**Issue by jsoref** [github/docs#16306]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/jsoref/github-docs/runs/5564905922?check_suite_focus=true#step:2:10

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/2119212/158519181-295a1084-843b-44de-9271-62be2404ff8b.png">

### What changes are you suggesting?

An extra job should be added that exposes `env` for the `secrets` that are needed here:
https://github.com/github/docs/blob/039c4e465fbdbcc35887f619893758d5f9d28a21/.github/workflows/main-preview-docker-cache.yml#L25-L40

The job should set an output to `1` (or some other truthy value) to enable jobs to conditionally run.

The current job should `need` that job and be conditioned on the new job setting an output to `1`.

### Additional information

It's really frustrating getting notifications for failures when I update my repository's default branch.

**Comment by ramyaparimi** [comment]
@jsoref Could you also add link to the docs page that's to be changed in the issue template in the OP??

**Comment by jsoref** [comment]
@ramyaparimi this is a workflow problem, it isn't a content thing.

**Comment by Dukhtaar** [comment]
Build and Push Main Preview for workflow to operating issue

**Comment by peterbe** [comment]
I'm not sure what it means "doesn't look before it leaps". Perhaps you mean that it shouldn't run if the secrets aren't available. Something like:
`if: ${{ secrets.NONPROD_AZURE_CREDENTIALS }}`

Or more likely, you mean the action shouldn't run at all. In forks. We should fix that.

**Comment by jsoref** [comment]
You can't use an `if:` like that. Here's the documentation:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-secrets

But, yes, I mean that using a missing secret the way it's using it results in a build failure. It should ensure it doesn't blindly step off a cliff.

How this is fixed, i.e., whether it uses a condition on secrets being available or whether it just doesn't run in forks doesn't really matter to me. I could have left it as an implementation detail.

The reason I didn't is that I'd be willing to make a PR for what I'm proposing. And protocol here is to get signoff before making PRs.

I find it helpful to be able to point people to canonical examples of how to safely do things. And this repository being GitHub documentation works quite well for that purpose.
