### ISSUE TITLE
"In this article" hover effect incredibly low contrast in dark mode

### ISSUE THREAD

**Issue by simon-abbott** [github/docs#16365]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Any article that has an "In this article" side nav menu, so basically all of them.

<img width="447" alt="Screen Shot 2022-03-18 at 2 33 35 PM" src="https://user-images.githubusercontent.com/43803932/159072047-3581fd3c-f797-4182-8b77-664a91e3720c.png">

### What changes are you suggesting?

I would expect the hover effect to behave like it does in the light theme: an effect to know where you're hovering, but one that is subtle enough to still be able to actually read the text being selected.

<img width="447" alt="Screen Shot 2022-03-18 at 2 36 36 PM" src="https://user-images.githubusercontent.com/43803932/159072346-11e657c9-6f14-40ec-a56a-8b6196809691.png">

**Comment by ramyaparimi** [comment]
@simon-abbott 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by ramyaparimi** [comment]
Adding "waiting for review" label so the stale bot doesn't hit and close this issue 💖

**Comment by ramyaparimi** [comment]
@simon-abbott I noticed that there is an internal issue opened by the engineering team to track this issue, so I am going to close the issue in the open source repo💛. 

Thanks so much for your time in contributing to the GitHub docs 💖
