### ISSUE TITLE
Document limitations for the `event_type` length of the `repository_dispatch` event

### ISSUE THREAD

**Issue by bandantonio** [github/docs#16409]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

1. [Events that trigger workflows: `repository_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch)
1. [Create a repository dispatch event: Parameters](https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event--parameters)

### What part(s) of the article would you like to see updated?

Add a note to both articles telling that the `event_type` value is limited to 100 characters.

**I can fix the docs on my own**. However, I need guidance on how to add the note to the second page (Create a repository dispatch event: Parameters). It seems like API reference is generated automatically, as I can see only pre-made JSONs like, for example, `api.github.com.json` in the `lib/rest/static/decorated`

----

There is a related issue #15710 - I can fix it as well. Please assign it to me.

### Additional information

```
{
    "message": "Invalid request.\n\nOnly 100 characters are allowed; 101 were supplied.",
    "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"
}
```

Related issue: #15710

**Comment by bandantonio** [comment]
@ramyaparimi Could you help me with this part please:

> I need guidance on how to add the note to the second page (Create a repository dispatch event: Parameters). It seems like API reference is generated automatically, as I can see only pre-made JSONs like, for example, `api.github.com.json` in the `lib/rest/static/decorated`

**Comment by ramyaparimi** [comment]
@bandantonio Thanks you for pointing out this to me. I will get this issue triaged for our writers, so they can take a look and let you know how to proceed further 💖

**Comment by ramyaparimi** [comment]
@bandantonio Taking a closer look, updates to the REST API description must be made internally. If you could create a new separate issue with changes you would like to see in "[Create a repository dispatch event: Parameters](https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event--parameters)", I will copy it to appropriate internal repo for tracking 💖.

I apologize for missing this information in the earlier comment. Please let me know if there is anything else I can help you with 💖.

Thanks so much for taking your time in improving the GitHub docs ✨ .

**Comment by bandantonio** [comment]
@ramyaparimi Created the issue #16469 . Please have a look
