### ISSUE TITLE
Add transparency information to social preview documentation

### ISSUE THREAD

**Issue by aisgbnok** [github/docs#16417]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Customizing your repository's social media preview](https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview)

### What part(s) of the article would you like to see updated?

Github social preview supports using transparent PNGs, but this does not seem to be documented. Adding a small subsection about transparency would be welcome. Usage of transparent PNGs can be helpful for branding as many platforms support dark/light themes and transparent PNGs can work well with multiple themes.

### Additional information

You can read my general GitHub feedback here https://github.com/github/feedback/discussions/13109#discussion-3951682, for more information.

**Comment by devines417** [comment]
![Uploading Snapchat-2145266782.jpg…]()
