### ISSUE TITLE
Clean up old branches in this repo to reduce spam PRs

### ISSUE THREAD

**Issue by nschonni** [github/docs#1644]
### What is the current behavior?

As a visible repo for people looking at the docs, this repo attracts alot of spam PRs. Some of these come from old merged/closed branches from GitHubbers that are automatically in forked repos.

### What changes are you suggesting?

Delete old branches on https://github.com/github/docs/branches/all for Closed, Merged, and un-PR'd branches

### Additional information

Don't think all GitHubber contributions need to be directed internal fork in all cases, as showing an active PR can help show that someone is working on one of the issues and can be useful for others to learn. Cleaning up those branches afterwards is a good idea though 😄

**Comment by chiedo** [comment]
Deleted the really old ones! Left branches open that were created within the past couple weeks.

**Comment by nschonni** [comment]
Awesome!
I'd probably suggest this one too, since it is even with the main branch
![image](https://user-images.githubusercontent.com/1297909/100635878-0c56da80-32ff-11eb-85df-bf0bf6ad32bb.png)

**Comment by chiedo** [comment]
I'm not sure why but I can't delete that branch. 

![Screen Shot 2020-11-30 at 11 30 52 AM](https://user-images.githubusercontent.com/2156688/100636301-8dae6d00-32ff-11eb-9e50-4dac6eb803b2.png)

I can't find the corresponding pull request ¯\_(ツ)_/¯

**Comment by nschonni** [comment]
Looks like it's this PR https://github.com/github/docs/pull/351

**Comment by chiedo** [comment]
Yeah but it's closed so I don't understand why it's saying it can't be deleted due to an open PR. Maybe a bug. But not sure.

**Comment by nschonni** [comment]
Ah, gotcha.
Sounds like it's time to spin up an internal bug 😆

**Comment by nschonni** [comment]
I was thinking it might have been deletable from the actual PR page

**Comment by chiedo** [comment]
Haha yeah. I'll submit an internal bug! haha. Thanks for digging in here.

**Comment by per1234** [comment]
High time for another clean-up @chiedo
