### ISSUE TITLE
Managing disruptive comments is overly prescriptive

### ISSUE THREAD

**Issue by jsoref** [github/docs#16446]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md

### What part(s) of the article would you like to see updated?

This content:
https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L53

... feels more like instructions for how a specific project should operate, as opposed to the world at large. If it's the world at large, then it should be integrated into the tooling.

This should really have its own anchor, for `redacting` information:
https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L59

https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L64-L65

The content should also include a note that it's merely a suggestion.

https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L80

It's a bit late in the chronology to make this suggestion. I'd suggest it precede the information about deleting a comment (i.e. before `Deleting a comment is your last resort as a moderator.`). But, I want to be careful to not be too prescriptive (the current content suffers from this...).

There should be an anchor for the steps:
https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L88

### Additional information

Fwiw, while this information is interesting, it is definitely not complete.

I found this page because I was researching a behavior I noticed today which does not appear to be documented.

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by hubwriter** [comment]
I've mentioned this in an internal channel to get some expert 👀 on these suggestions.

**Comment by pratompron** [comment]
good

**Comment by hubwriter** [comment]
Hi @jsoref - Thanks again for raising this issue. Apologies it's taken a while to get back to you about this.

I've now heard back from an SME who has taken a look at this issue. They've said that your suggestions seem potentially valid, but they'd like to have a pull request with docs changes to review.

If you could open a PR with your suggested changes to the docs that would be great. Please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).
