### ISSUE TITLE
Scroll position doesn't navigate to top of page when moving between articles

### ISSUE THREAD

**Issue by Ruborcalor** [github/docs#16503]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I think all articles are affected.

I am experiencing issues on firefox and chrome.

Example article: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues

### What changes are you suggesting?

I expect to be directed to the top of a page when switching articles. Instead I am left at the bottom and need to scroll up.

**Comment by ramyaparimi** [comment]
@Ruborcalor 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Devilmummanay** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> I think all articles are affected.
> 
> I am experiencing issues on firefox and chrome.
> 
> Example article: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues
> 
> ### What changes are you suggesting?
> I expect to be directed to the top of a page when switching articles. Instead I am left at the bottom and need to scroll up.
> 
> ### Additional information
> _No response_

Hi

**Comment by peterbe** [comment]
@janiceilene We've filed similar issues elsewhere. I'm not sure if this matches the same description but clearly it's a bug. Perhaps when we work on that other issue (about disabling the sidebar scroll-down), this one will "automatically" resolve.

**Comment by peterbe** [comment]
> I expect to be directed to the top of a page when switching articles. Instead I am left at the bottom and need to scroll up.

@Ruborcalor When you say "switching articles" do you refer to clicking links in the left-hand sidebar or links within the page?

**Comment by ramyaparimi** [comment]
> (note, as a first-responder, I'm not sure what else there is to review at this point)
@peterbe if this in response to adding "waiting for review" label, all issues have "waiting for review" label to prevent the stale bot from closing these issues until the issues are either closed by maintainers or get a "help wanted" label 💖.

**Comment by Ruborcalor** [comment]
> @Ruborcalor Thanks so much for opening an issue! I'll triage this for the team to take a look eyes

Cool!

> > I expect to be directed to the top of a page when switching articles. Instead I am left at the bottom and need to scroll up.
> 
> @Ruborcalor When you say "switching articles" do you refer to clicking links in the left-hand sidebar or links within the page?

Hey Peter, to me more specific I would experience the issue under the following circumstances:
- I am visiting an article A
- I read through the article and find myself at the bottom of the page
- I click on an article B in the left-hand sidebar

I am redirected and left at the bottom of article B so I need to scroll up before I can start reading.

**Comment by peterbe** [comment]
Note-to-self; we're tracking this internally here too: https://github.com/github/docs-engineering/issues/1650

**Comment by janiceilene** [comment]
Thanks again for opening this issue @Ruborcalor! Since we've got an internal issue tracking this bug, I'm going to close this issue up 💛
