### ISSUE TITLE
Improve Screenshots in "Creating a GitHub App" Page

### ISSUE THREAD

**Issue by sarina** [github/docs#16539]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app

### Problem

On this page, we are looking to find the "GitHub Apps" option in the left sidebar. Step 2 does indeed say to click on "Developer Settings", but it's easy to miss - I've missed that on three separate occasions and now someone on my team just did, so I think it needs to be better called out. Why is this a problem? Currently, there _is_ a GitHub Apps link on the left sidebar as a first class member, and it looks very similar to the screenshot in Step 3.

Instructions the document provides:

![image](https://user-images.githubusercontent.com/1985317/160176114-f78e6eee-b82c-428d-bbe3-7e763e5ab52b.png)

The "incorrect" GitHub Apps sidebar option that we accidentally click on:

![image](https://user-images.githubusercontent.com/1985317/160176503-a626c5a6-706d-4bfe-99e6-c6f441094784.png)

### Proposed Solution

I suggest Step 2 have the following screenshot:

![image](https://user-images.githubusercontent.com/1985317/160176195-96957ab1-1aeb-4b3c-9811-3a2ae2b57b91.png)

and Step 3 is updated to what you actually see:

![image](https://user-images.githubusercontent.com/1985317/160176280-b4e53462-99ba-4a16-aaf5-f16af8d521a0.png)

This will prevent confusion of people like me!!

### Additional information

I would be happy to fix this but I suspect you have some standards around images that my screenshots may not be enough.

**Comment by ramyaparimi** [comment]
@sarina 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by mchammer01** [comment]
Thanks for raising this issue with our docs @sarina ✨ 
And thank you for confirming that the current instructions are also confusing for you @kdmccormick 👍🏻 
I am going to transfer this issue to our internal repo for one of the Docs team members to take a look at, as this touches screenshots, and the content you're asking us to amend is used in various other articles.

**Comment by dynamatikzgr** [comment]
N|₺n bu kadar çok il|tim raporu alıyorum
