### ISSUE TITLE
Make the 'Scroll to top' button size bigger

### ISSUE THREAD

**Issue by ilam-natarajan** [github/docs#16545]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All pages.
 for example: https://docs.github.com/en/rest/reference/gists#star-a-gist

### What changes are you suggesting?

Make the 'Scroll to top' button size bigger.

Since github docs is a long scroll site, **Scroll to top** button is very helpful. To make it more easily clickable, the size needs to be increased. Currently it takes more time to focus the mouse on to the button. 

### Additional information

If you decide to not increase the size all the time, at least make the button big when we scroll up so that it's more visible and easily clickable.

**Comment by mamutalib** [comment]
> 

Great suggestion.

**Comment by ramyaparimi** [comment]
@ilam-natarajan 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by gracepark** [comment]
Thank you so much! I've moved this to our Product team internally. Once the decision is made, engineering will make the necessary changes.

**Comment by ramyaparimi** [comment]
@ilam-natarajan There is an internal issue opened track this, so I am going to close this issue in the open source repo 💛.

Thanks so much for your efforts in improving the GitHub docs 💖 .
