### ISSUE TITLE
owu

### ISSUE THREAD

**Issue by Owa789** [github/docs#1655]
send me my coins

**Comment by ajs256** [comment]
Hey there @Owa789!

Thanks for opening an issue. Could you please fill out the issue template so the team can know what the problem is?

> Please note that I am not affiliated with the GitHub docs team.

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
