### ISSUE TITLE
Update topic on archiving repositories to cover code scanning

### ISSUE THREAD

**Issue by felicitymay** [github/docs#166]
## Content plan

Currently the topic on archiving repositories does not mention code scanning: [About archiving repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-archiving-repositories).

### Audience

Users who are considering archiving a repository will want to know exactly how this affects the repository.

### Content to update

Currently "[About archiving repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-archiving-repositories)" says: 

> When a repository is archived, its issues, pull requests, code, labels, milestones, projects, wiki, releases, commits, tags, branches, reactions, and comments become read-only.

Update this to include "code scanning alerts".

### Questions

None outstanding.

**Comment by casals** [comment]
In this scenario, are the code scanning alerts closed or marked as read-only?

**Comment by janiceilene** [comment]
I'm not sure @casals. @github/docs-content-dsp will be able to give an answer ✨

**Comment by felicitymay** [comment]
Great question @casals. I've checked back on the original feedback and the relevant development pull requests. The code scanning alerts are marked as read-only, in the same way as pull requests and issues.
