### ISSUE TITLE
Document how to unlist/unpublish an app from the marketplace

### ISSUE THREAD

**Issue by jsoref** [github/docs#16667]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/github-marketplace

### What part(s) of the article would you like to see updated?

A page should be added that explains how to remove an app from the marketplace. It could be similar to the content for removing an action from the marketplace, assuming the steps are similar. I don't know if they are, as I can't figure out (from the documentation) how to do it.

### Additional information

Reported here:
https://github.community/t/remove-app-from-marketplace-listing/241687

Information exists for actions:
https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#removing-an-action-from-github-marketplace

**Comment by caseyMFRyan** [comment]
What app is on there and why do u need it removed?

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by emad70** [comment]
https://drive.google.com/file/d/191tnzUNr4Tw3OvhY54cwljSWh0Bfneh3/view?usp=drivesdk

**Comment by emad70** [comment]
> https://drive.google.com/file/d/191tnzUNr4Tw3OvhY54cwljSWh0Bfneh3/view?usp=drivesdk

**Comment by emad70** [comment]
https://github.com/github/docs/issues/16667#issuecomment-1088261474

**Comment by emad70** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/developers/github-marketplace
> 
> ### What part(s) of the article would you like to see updated?
> A page should be added that explains how to remove an app from the marketplace. It could be similar to the content for removing an action from the marketplace, assuming the steps are similar. I don't know if they are, as I can't figure out (from the documentation) how to do it.
> 
> ### Additional information
> Reported here: https://github.community/t/remove-app-from-marketplace-listing/241687
> 
> Information exists for actions: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#removing-an-action-from-github-marketplace

**Comment by janiceilene** [comment]
Thanks so much @jsoref! I've spoken with the team and this one is something we're going to have bigger conversations with lots of folks internally. We've opened an internal issue to track that conversation, so I'm going to close this one now.

Thanks for pointing out this spot for improvement!
