### ISSUE TITLE
Rate limit doesn't promise it will always be a positive integer

### ISSUE THREAD

**Issue by jsoref** [github/docs#16683]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits

### What part(s) of the article would you like to see updated?

The current text (emphasis added) says:

> When you have been limited, use the `Retry-After` response header to slow down. The value of the `Retry-After` header will always be an _integer_, representing the number of seconds you should wait before making requests again. For example, `Retry-After: 30` means you should wait 30 seconds before sending more requests.

A number of other vendors (spotify/web-api#542, CiscoDevNet/webexteamssdk#52) have at times sent `retry-after: 0` when they in fact meant `retry-after: 1`.

In adding some code to deal w/ that case, I decided to check the documentation, and the documentation here doesn't promise that the server won't send `retry-after: -10` or `retry-after: 0`. 

I'm glad it's promising not to send the float `1.5`, the string `tomorrow`, or the date-time `2038-01-19T03:14:08Z`.

* If it will always be > 0, it'd be nice if the documentation either promised that the value would be a `positive integer`, or a `natural number`.
* If it might be `0`, it'd be nice if the documentation specified `whole number` and then explained what one should do when the value is `0`.
* If it could be negative, the documentation should explain what one should do when that happens.

### Additional information

I'm aware that this is a `best practices` guide. 

These are really the only pages I can find that generally discuss the subject:

* [Resources in the REST API (Rate limit HTTP headers)](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limit-http-headers)
* [Getting started with the REST API](https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api)
* [Best practices for integrators](https://docs.github.com/en/rest/guides/best-practices-for-integrators)

Of these pages, only [Best practices for integrators](https://docs.github.com/en/rest/guides/best-practices-for-integrators) actually talks about `retry-after`.

This repository used to have (non-user-facing) code that handled `429`: 704f699353dfbf5b4088e146f47b6f552153a49a

And it currently has:

* This comment (which would trigger a PR from my tooling for this line, but, I'm not sure if that'd be particularly welcome):
    https://github.com/github/docs/blob/ad3d0cd9652281edc31418e1fa42ce9fa18acf93/script/check-english-links.js#L8

* And this, which definitely isn't user facing:
    https://github.com/github/docs/blob/ad3d0cd9652281edc31418e1fa42ce9fa18acf93/script/check-english-links.js#L32

It'd be great if a user facing page explicitly mentioned `429`. (There's one REST API that mentions `429`, but I don't know why #16682.)

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by skedwards88** [comment]
Thanks for this issue. I discussed this with the API team. It's generally safe to assume that it will be a non-rational number with a value of 0 or greater. However, we don't plan to officially document this. Instead, users should write defensive code in the case that the return value does not meed the expected format (e.g. due to a system error on our part).
