### ISSUE TITLE
Events documentation and per_page param

### ISSUE THREAD

**Issue by wayofthepie** [github/docs#1668]
### What is the current behavior?

The docs for the [Events](https://docs.github.com/en/free-pro-team@latest/rest/reference/activity#events) API says the following:

> Events support pagination, however the per_page option is unsupported. The fixed page size is 30 items. Fetching up to ten pages is supported, for a total of 300 events. For information, see "Traversing with pagination."

However, each of the API's does document a `per_page` parameter and it does seem to work fine:

```shell
$ curl -s https://api.github.com/repos/wayofthepie/ctlogs-cli/events?per_page=12 | jq '. | length'
12
```

### What changes are you suggesting?
It seems like the section mentioning `per_page` is unsupported should be removed, if `per_page` is indeed meant to work for the `Events` API.

**Comment by janiceilene** [comment]
Thanks for opening an issue @wayofthepie! I'll triage this for the right team to take a look 👀

**Comment by skedwards88** [comment]
@wayofthepie Thanks for catching this discrepancy! You are correct that this paragraph should be removed. ✨ You or anyone else is welcome to open a PR to address this issue.

**Comment by KrKeshav09** [comment]
I am new with this could I able to contribute in this work as I am still learning

**Comment by janiceilene** [comment]
@KrKeshav09 Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions or check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. :sparkles:

**Comment by Vivek-Hotti** [comment]
Please check PR #4362
