### ISSUE TITLE
Need revision to limitations in listed Dataflow documentation

### ISSUE THREAD

**Issue by akangsha121** [github/docs#16696]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Two external documents have to update/revised

- [Use Machine Learning and Cognitive Services with dataflows - Power BI | Microsoft Docs] (https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-machine-learning-integration)

- [Dataflows Limitations, restrictions and supported connectors and features - Power BI | Microsoft Docs](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations)

### What part(s) of the article would you like to see updated?

Considerations and limitations: (Current List)
AI insights (Cognitive Services and Azure ML models) are not supported on machines with proxy authentication setup.
AzureML models are not supported for Guest users.

- *New Considerations and limitations to be added:

The AI features cannot be supported on the Power BI Gateway.

**Comment by ramyaparimi** [comment]
@akangsha121 This repository is for [docs.github.com](https://docs.github.com/en) and we don't handle chances made to Microsoft docs, so I am going to close this issue now 💛
