### ISSUE TITLE
Typo in environtments for deployment article

### ISSUE THREAD

**Issue by amendezm** [github/docs#16778]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/es/actions/deployment/targeting-different-environments/using-environments-for-deployment (spanish version)

### What part(s) of the article would you like to see updated?

typo: **configurr** should be **configurar**

### Additional information

![image](https://user-images.githubusercontent.com/26444448/161406304-efcffdf9-a093-4b77-9db2-5785b1e83d42.png)

**Comment by raihan-is** [comment]
> commented

#16778

**Comment by ramyaparimi** [comment]
@amendezm 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
