### ISSUE TITLE
Make entire sidebar collapsible

### ISSUE THREAD

**Issue by hamirmahal** [github/docs#16775]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This affects all articles where a sidebar is present.

In the screenshot I posted, I'm using Microsoft Edge.

I searched existing issues and, at the time of this writing, [the only result for "sidebar collapse"](https://github.com/github/docs/issues?q=is%3Aissue+sidebar+collapse+is%3Aclosed) isn't open and I think it deals with the collapsing of individual items in the sidebar, as opposed to hiding the sidebar altogether, which is what I would like to request with this issue.

### What changes are you suggesting?

It would be nice if readers could collapse, or hide, the entire lefthand sidebar, and not just individual items in the sidebar, to have more space available for viewing an article's content.

![image](https://user-images.githubusercontent.com/43425812/161402434-cb120d10-ca26-4913-ba50-4baed4397430.png)

### Additional information

A collapsible sidebar could improve the user experience. What do you all think?

**Comment by hamirmahal** [comment]
@ramyaparimi You're welcome! Thank you for triaging this.

**Comment by mikesurowiec** [comment]
pinging @janiceilene since this seems like a product request

**Comment by janiceilene** [comment]
Thanks so much for this feedback @hamirmahal! This is something that's come up before and is part of some larger conversations that we're tracking internally, so I'm going to close this issue.

Thanks again for your interest in improving the Docs 💖
