### ISSUE TITLE
Please document filtering repositories

### ISSUE THREAD

**Issue by jsoref** [github/docs#16782]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories

### What part(s) of the article would you like to see updated?

Afaict, nothing in this tree talks about filtering repositories.

https://docs.github.com/en/repositories?query=filter+repositories

<img width="506" alt="image" src="https://user-images.githubusercontent.com/2119212/161416733-72bbe15e-d855-4dce-9d71-342b66ca364c.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/2119212/161416739-54c8e8e1-9bd2-41d0-8c61-41c26dd73b96.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/2119212/161416750-f3026ab1-ee77-475d-b76e-eae21cd7eae2.png">

### Additional information

Note that there is documentation for filtering other objects.

https://github.com/orgs/github/repositories has a bunch of repositories:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/2119212/161416767-2dd52a35-b447-4b70-a81d-0256a5e8e8d2.png">
And a type widget:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2119212/161416773-1bbba02d-57de-40b6-b296-953dd0199a38.png">

With

### Select type

✔️| All
-|-
.|Public
.|Private
.|Sources
.|Forks
.|Archived
.|Mirrors
.|Templates

`Public` is interesting and doesn't really do what I was expecting.
https://github.com/orgs/docs/repositories?q=&type=public&language=&sort=
(It basically shows any repository that isn't private)
The item could include a link to explain `public` and `private` and include links for converting a repository from `public` to private`

`Private` more or less did what I was expecting, but it wasn't obvious that such a thing even existed (since I started by looking at an org that I wasn't a member of).
As w/ `Public`, it'd be nice if the docs explained `public`/`private` and included links for converting (the other way...)

`Archive` is interesting
https://github.com/orgs/docs/repositories?q=&type=archived&language=&sort=
It might even do what someone expects -- for the curious, it will list both public and private repositories if one is a member of the org and can thus see private archived repositories.
Similar to `mirrors` below, it could include a link to the docs for `archiving` a repository.

`Mirrors` -- I'm not sure what this does. I mean, I could guess what it should do, but I can't find any repository that actually matches this filter, so I'd love a definition to explain. And it'd be nice if it could then link to something that would explain how to mark a repository as a mirror.

`Forks` more or less did what I expected. I think. But, I could be wrong about what it's doing and what it does. So, documentation to explain what it does could be valuable.

`Templates` 
I'm not going to guess how this behaves. I'd rather read the docs.

`Sources` doesn't do what I expected. And the name isn't intuitive.
Specifically, if a repository is the root of a fork tree and is `archived`, it doesn't show up when filtering for `sources` even though per the documentation, one can still fork it. This surprising behavior at the very least should be documented.

Lastly, once you have a page that documents what these filters do, you could include an explanation of how to filter for things people might want.

I want all non-archived repositories.

Here's a simple org for which this task is not simple:
https://github.com/docs

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by janiceilene** [comment]
👋 @jsoref Thanks for opening an issue! I chatted with the team and we've logged your feedback internally as part of a wider project where we're considering some updates to the back end of our search 💖

**Comment by peterbe** [comment]
Hi @jsoref I just wanted to say that I'm super grateful for this filed issue. I hopefully will be working on this iteration to make problems like this go away. Your well documented issue will be a priority example. Thank you.

**Comment by jsoref** [comment]
Oh, about a week after I filed this, someone actually found an org w/ mirror repositories:
https://github.com/orgs/coreutils/repositories?q=&type=mirror&language=&sort=

<img width="997" alt="image" src="https://user-images.githubusercontent.com/2119212/169590655-0fecd4c7-07a5-46dd-af7d-262785f96b3a.png">

The notable thing about it is that these two are listed as `Public mirror`s which implies that there might be `Private mirror`s which this UX wouldn't let me filter for either...
