### ISSUE TITLE
Deploy keys permissions aren't documented for user account repositories

### ISSUE THREAD

**Issue by jsoref** [github/docs#16788]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository

### What part(s) of the article would you like to see updated?

Mention deploy keys and who can create them.

Compare:
https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role

Repository action | Read | Triage | Write | Maintain | Admin
-- | -- | -- | -- | -- | --
Manage webhooks and deploy keys |   |   |   |   | X

### Additional information

Both articles are linked from https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys:

Deploy keys with write access can perform the same actions as an organization member with admin access, or a collaborator on a personal repository. For more information, see "[Repository roles for an organization](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization)" and "[Permission levels for a user account repository](https://docs.github.com/en/articles/permission-levels-for-a-user-account-repository)."

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by GOFFERU** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository
> 
> ### What part(s) of the article would you like to see updated?
> 
> Mention deploy keys and who can create them.
> 
> Compare:
> https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role
> 
> Repository action | Read | Triage | Write | Maintain | Admin
> -- | -- | -- | -- | -- | --
> Manage webhooks and deploy keys |   |   |   |   | X
> 
> 
> ### Additional information
> 
> Both articles are linked from https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys:
> 
> Deploy keys with write access can perform the same actions as an organization member with admin access, or a collaborator on a personal repository. For more information, see "[Repository roles for an organization](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization)" and "[Permission levels for a user account repository](https://docs.github.com/en/articles/permission-levels-for-a-user-account-repository)."

**Comment by janiceilene** [comment]
👋 @jsoref Sorry for the abysmally long response time, it looks like this one got a little lost! Since we document those permissions in https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys, you or anyone else are welcome to open a PR to add those permissions to the table!

**Comment by jsoref** [comment]
@janiceilene: thanks.

1. I looked and it appears I'm a collaborator to someone else's repository, and I can't see an edit tab, so I'm going to assume it's limited to owners.

2. I can't actually find a good page for `manage webhooks`. The `manage deploy keys` page is really for managing _deploy keys_ not webhooks. -- There's a reusable, https://github.com/github/docs/blob/main/data/reusables/sponsors/manage-existing-webhooks.md but it's all sorts of strange (it's a "sponsors" webhook ...).

Setting up content for "manage webhooks" is well beyond the scope of this issue and way more work than I have the energy to produce. I'm going to naively copy the content from the other page and leave splitting out (and updating both pages) for someone else...

**Comment by felicitymay** [comment]
As discussed, I've raised an internal issue for your feedback on the need for an article about managing webhooks. It will be triaged and prioritised alongside our other work.
