### ISSUE TITLE
Incorrectly rendered apostrophe symbol in the Get Started page. Overall inconsistency.

### ISSUE THREAD

**Issue by bandantonio** [github/docs#16849]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started

## Overview

Generally, all the pages included into the Get Started, use a single quote symbol `'` as an apostrophe:

1. <a href="https://user-images.githubusercontent.com/16765690/161793850-7e5e546e-ab00-4e83-90e7-39742173e45d.png">Example 1</a>
1. <a href="https://user-images.githubusercontent.com/16765690/161793901-d4f09a5d-fc03-4b93-bb71-9a0be8a19fc4.png">Example 2</a>
1. <a href="https://user-images.githubusercontent.com/16765690/161793919-9d8f0276-2c32-4e6d-9bdf-b13745da8eba.png">Example 3</a>

----

However, at the bottom of the page, there is the **Learning about GitHub** with several inconsistencies:

<img width="280" alt="apostrophe" src="https://user-images.githubusercontent.com/16765690/161791643-f1e18ec8-6503-47fa-901d-2a9921e5950a.png">

The first article in the list uses an HTML entity to be rendered as a single quote; the second one uses the `&#8217;` symbol (Close curly quote) as an apostrophe.

## Thoughts

As my testing shown, text in links doesn't get replaced with HTML entities, so the usage of `&apos;`, `&#39;` or other stuff like that is faulty.

A kind of weird thing is that the title in [the GitHub's products page](https://github.com/github/docs/edit/main/content/get-started/learning-about-github/githubs-products.md) does use the single quote symbol:

```
title: GitHub's products
```

In contrary, the [FAQ about changes to GitHub’s plans](https://github.com/github/docs/edit/main/content/get-started/learning-about-github/faq-about-changes-to-githubs-plans.md) does use a faulty symbol:

```
title: FAQ about changes to GitHub’s plans
```

So, the issue with the `&apos;` does exist.

### What part(s) of the article would you like to see updated?

Keep apostrophes consistent: just replace all the weird symbols and HTML entities with the hard-coded `'` symbol, as it seems it doesn't break a thing.

### Additional information

I would like to create a PR to fix this inconsistency, but I need additional guidance on debugging this issue

**Comment by ramyaparimi** [comment]
@bandantonio 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by vedant205** [comment]
Hi! I was looking at this Github docs page locally on my machine and noticed that the apostrophes were rendered correctly, which I found odd since on the actual Github docs site it rendered incorrectly. Hopefully, this helps in solving the problem.

**Comment by mikesurowiec** [comment]
Thanks for this 🎉 

We have a small fix on the way that should address the problem. I'll post again when the fix goes out.

**Comment by mikesurowiec** [comment]
Fix is live: https://docs.github.com/en/get-started 🕺
