### ISSUE TITLE
Portuguese translation correction

### ISSUE THREAD

**Issue by franklaercio** [github/docs#1687]
### What article on docs.github.com is affected?
[Sobre  a autenticação no GitHub](https://docs.github.com/pt/free-pro-team@latest/github/authenticating-to-github/about-authentication-to-github)

#### In the first section (Sobre autenticação no GitHub) change this:

> To keep your account secure, you must authenticate before you can access certain resources on GitHub.

For this:

> Para manter sua conta segura, você deve autenticar antes de usar o GitHub.

And 

> Username and password with two-factor authentication

For this:

> Usuário e senha combinados com a autenticação de dois fatores

#### In the second section (Efetuar a autenticação no seu navegador) change this:

> You can authenticate to GitHub in your browser in different ways.

For this:

> Você pode se autenticar no GitHub em seu navegador de diferentes formas.

### Additional information

None

**Comment by janiceilene** [comment]
Thanks for opening this issue! Unfortunately, we are not able to update translated content in this repository. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.
