### ISSUE TITLE
Change legacy host container image in "creating services containers" docs

### ISSUE THREAD

**Issue by filip-dahlberg** [github/docs#16908]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-containerized-services/about-service-containers#creating-service-containers

### What part(s) of the article would you like to see updated?

The section with "Creating Service Container" use of job's host container on the field `container: node:10.18-jessie` should be replaced with a container image that is forwards compatible. 

The docker image node:10.18-jessie is outdated, it uses old version of git (< 2.18), i.e. its not compatible with git submodules.

See error pulling a submodule inside the node:10.18-jessie container. 

```sh
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Error: Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH.
```

**Comment by ethomson** [comment]
Thanks for letting us know @filip-dahlberg - I've asked the team to update this to a newer image.
