### ISSUE TITLE
👋 @beld78 The best folks to chat with about repository search API would be our wonderful [support team](https://support.github.com/contact)!

### ISSUE THREAD

**Issue by anygenier** [github/docs#16902]
👋 @beld78 The best folks to chat with about repository search API would be our wonderful [support team](https://support.github.com/contact)!

_Originally posted by @janiceilene in https://github.com/github/docs/discussions/6640#discussioncomment-787629_

**Comment by JoshuaSamuel144** [comment]
Am Joshua by name I love
