### ISSUE TITLE
Limitations of CODEOWNERS files with respect to Enterprise Managed Users are not detailed

### ISSUE THREAD

**Issue by ReidWeb** [github/docs#16910]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What part(s) of the article would you like to see updated?

From my understanding, when used with [Enterprise Managed User](https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/managing-iam-with-enterprise-managed-users/about-enterprise-managed-users) identities, CODEOWNERS files do not support the use of email addresses.

The current documentation does not currently indicate as such.

I would propose that the documentation be revised to indicate that email addresses cannot be used in the context of Enterprise Managed Users being in place.

### Additional information

N/A

**Comment by ramyaparimi** [comment]
@ReidWeb 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by lecoursen** [comment]
Hi @ReidWeb! I checked with the team, and you're right that the behavior you're describing is currently expected. We should definitely mention it in "About code owners", where we say that email addresses are supported. You or anyone else is welcome to create a PR doing so!

**Comment by ReidWeb** [comment]
Thanks I'll try to get this in if and when I can.
