### ISSUE TITLE
"Managing labels" topic doesn't mention triage permissions

### ISSUE THREAD

**Issue by felicitymay** [github/docs#1693]
### What article on docs.github.com is affected?

[Managing labels - GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/managing-labels)

### What part(s) of the article would you like to see updated?

The topic doesn't mention the ability for users with triage permissions to add and remove labels. It looks as if this might just need a small update to the "About labels" section.

### Additional information

I noticed this while reviewing: [Add entry to table "create, edit, delete labels"](https://github.com/github/docs/pull/1180).

**Comment by HonkingGoose** [comment]
Maybe language like _apply_ is better than adding/removing? 
_Adding/removing_ implies that Triage level permissions grant rights to change/edit/remove things from the list of labels for the repository...

Triage level permissions allow you to:

| Apply existing label | Un-apply existing label | Create new label | Edit existing label from list | Remove label from list |
| :-----------: | :--------------: | :-----------------: | :------------------: | :-----------------------: |
| yes| yes | no | no | no |

**Comment by felicitymay** [comment]
@HonkingGoose - that's a great point.

Apply is a much clearer term. I'm not that keen on "un-apply" as a term. Perhaps "dismiss" or "clear" would work?

**Comment by HonkingGoose** [comment]
Dismiss and clear are both fine. 👍 

I think the table we updated in #1180 can also be updated with the verbiage you decide on for "un-apply", to make clear that you can not only apply the label, but also "un-apply" it with Triage level rights. 😄
