### ISSUE TITLE
`outputs` doesn't declare how long an output can be

### ISSUE THREAD

**Issue by jsoref** [github/docs#16936]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-docker-container-and-javascript-actions
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions

Text should be added to indicate how long an output can be. Can it be GBs long? MBs? KBs?

Can it be binary? Or does it need to be ascii safe?

**Comment by KritsanaVeingin** [comment]
Max Transection-age = { UTX }
•support
•Waves ng

**Comment by ethomson** [comment]
Thanks, this seems like a thing that we should document. I'll take a look.

**Comment by lucascosti** [comment]
This was just fixed in an internal PR by @ethomson, and the content will be synced to this repo soon.

The changes detail the following limits for outputs:

> Outputs are Unicode strings, and can be a maximum of 1 MB. The total of all outputs in a workflow run can be a maximum of 50 MB.
