### ISSUE TITLE
Discuss community health files on "Create a repo" page

### ISSUE THREAD

**Issue by vedantsinghania05** [github/docs#16950]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/quickstart/create-a-repo

### What part(s) of the article would you like to see updated?

I think that in the notes section of this page, there should be something talking about community health files and linking to this github docs page: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

### Additional information

I'm not exactly sure where this new information would fit best on the page, so I'm opening this issue in hopes that the content will be added or that I can be given guidance on where to add it.

**Comment by alex00j** [comment]
Спасибо

**Comment by zc102388** [comment]
Thank you

**Comment by janiceilene** [comment]
Thanks so much for opening this issue @vedant205! You or anyone else are welcome to open a PR adding a new sentence with a link to the community health files article to the blue note at the top of the page.

**Comment by Ahmadkhojaev** [comment]
Hello Vedant Singhania. Thanks for opening a new issue. Good luck.

**Comment by Brokkies** [comment]
I would like to help with this ,but still new and don,t know where to start

**Comment by cmwilson21** [comment]
@Brokkies Thanks for your interest in helping out with this one! ✨ 

Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions or check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. :sparkles:

Thanks again for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by cmwilson21** [comment]
Looks like this one has been updated, I'm going to go ahead and close the issue now 💛
