### ISSUE TITLE
An error occurs when copying and executing the command at the time of setting up `CodeQL CLI`

### ISSUE THREAD

**Issue by soartec-lab** [github/docs#16998]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ja/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/installing-codeql-cli-in-your-ci-system#

### What part(s) of the article would you like to see updated?

I typed the command according to the documentation but I got the following error:

```
$ wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
$ tar -xvzf ../codeql-bundle-linux64.tar.gz
tar (child): ../codeql-bundle-linux64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

This problem is simple.
This is because the file specified in the argument of the `tar` command refers to` ../` and the directory one level higher.
The location to put the file downloaded with the `wget` command is the current directory.

The command can be copied and used as is by specifying a file in the current directory as follows:

```
$ wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
$ tar -xvzf ./codeql-bundle-linux64.tar.gz
```

**Comment by ramyaparimi** [comment]
@soartec-lab 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by felicitymay** [comment]
@soartec-lab - many thanks for raising this issue. I've just confirmed your diagnosis on my machine.
