### ISSUE TITLE
Mermaid markdown does not support links/actor menus

### ISSUE THREAD

**Issue by aiven-amartin** [github/docs#17007]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams

### What part(s) of the article would you like to see updated?

Explicitly explain which functionality of Mermaid is and isn't supported

### Additional information

This mermaid doc should have links, but it doesn't 
```mermaid
sequenceDiagram
    autonumber
    A ->> B: Hello
    links A: {"google": "https://google.com", "github", "https://github.com"}
```
Working example: https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNpdj7sOwjAMRX8l8lzonqFSEUjsDCxe0sRtI_KA1BlQ1X-nJWXBm4-P7OsZdDQEEiZ6ZQqazlYNSXkMYi2VOYbsO0qlb8WhacRJiis5F8U9JmfKxNnwmEQrxYwwxDg4QpACYWR-TrKuCzvq6BGqlQ-Wx9z9OV9WnAUDVOApeWXNGm_eziDwSH7fbKhX2TEChmVV89MopouxHBPIXrmJKtjy395Bg-SU6SftL-7W8gEFqFaT

**Comment by ramyaparimi** [comment]
@aiven-amartin 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by shqiza2** [comment]
[google.com](url)

**Comment by shqiza2** [comment]
[google.gg](url)
