### ISSUE TITLE
Clarify That GitHub Actions Don't Automatically Understand Semantic Versioning

### ISSUE THREAD

**Issue by Kurt-von-Laven** [github/docs#17071]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

### What part(s) of the article would you like to see updated?

> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.

This section can be read to imply that GitHub Actions understands semantic versioning, but it does not. In order for users to specify a major action version, the action maintainer has to tag it themselves. It would be good to clarify that tagging a major version only works if the maintainer chooses to support it. In my personal opinion, the risks of being broken by a bad release outweigh the benefits of always using the latest version of an action (at a specified major version). I would suggest pinning a specific version and using Dependabot to keep up-to-date instead.

**Comment by TibbY83** [comment]
``

**Comment by ethomson** [comment]
It's correct that actions does not "understand' semantic versioning, but we're clear in our suggestions that [action authors publish semantic versioned tags](https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions#example-developer-process).

Can you suggest some language that aligns these two things? Perhaps we should iterate in a pull request. 🙏

**Comment by ramyaparimi** [comment]
@Kurt-von-Laven Thank you for opening this issue. You or anyone else is welcome to open a PR as per the [SME review](https://github.com/github/docs/issues/17071#issuecomment-1106516939) ✨ .

**Comment by Kurt-von-Laven** [comment]
Thank you for the pointer to that doc! I found a related one previously that didn't mention authors publish all tags, but not that very clear one. I opened a PR; open to suggestions.

**Comment by Kurt-von-Laven** [comment]
@ramyaparimi, would you be able to reopen this issue since the associated pull request was accidentally closed?

**Comment by ramyaparimi** [comment]
@Kurt-von-Laven I see that this issue is already open, only the associated PR is closed. Would you like to create a new PR with a fix for this issue?

**Comment by Kurt-von-Laven** [comment]
Wow, clearly I needed more coffee :coffee: yesterday. Thank you! I opened a new PR.
