### ISSUE TITLE
Side-effect of changing username on codeowners is not declared

### ISSUE THREAD

**Issue by ReidWeb** [github/docs#17099]
[maintainer edit]
This issue is reserved for the MLH Fellowship program.

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/changing-your-github-username

### What part(s) of the article would you like to see updated?

This content is linked to on the change username screen of the account settings.

Some side effects are detailed, but not that this will impact `CODEOWNERS` files (at least from my understanding).

---
[maintainer edit]
### Content plan
Add to this article a section for CODEOWNERS files. These files will need to be manually updated. When viewing the CODEOWNERS file from the web, a warning will be shown if the file contains any unknown users or users without write access.

**Comment by ramyaparimi** [comment]
@ReidWeb 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by royd27** [comment]
Thanks for helping my wife to ruined my life anyway. You know I'd tried my very best to know how to be a developer 'coz I want to support my baby and my mama 'coz she's is stroke. But my wife forcing me to do some hard work. I know she's a developer, I do almost died when we are fighting 'coz she keep on insisting that she ain't. 

Anyway, I don't have have any hard feelings to anyone.. At least now, I know that I am right.
God bless.

**Comment by royd27** [comment]
Oh, I am sorry. it is just only my wife's fault. She just took your script for ruining me. I do apologize.

**Comment by sophietheking** [comment]
Hey @ReidWeb, thanks for opening this issue, looks great and should definitely be added to the docs! ✨ I triaged it and you (or anyone else) are welcome to open a PR.

**Comment by tranthithoa0803** [comment]
Ok

**Comment by cmwilson21** [comment]
Closing this with PR #23859
