### ISSUE TITLE
Table is not displayed properly(zh-CN)

### ISSUE THREAD

**Issue by lijianru** [github/docs#17190]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/cn/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-updates

![image](https://user-images.githubusercontent.com/28643081/163957841-18392904-20b2-4bb5-9124-e34b91da3668.png)

### What part(s) of the article would you like to see updated?

https://docs.github.com/cn/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-updates

Table is not displayed properly(zh-CN)

**Comment by ramyaparimi** [comment]
@lijianru 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.

**Comment by yi-Xu-0100** [comment]
@ramyaparimi I make a PR(#19392) to fix this issue. I know that changes to translation files are not accepted, but I submitted it anyway because it's not a translation issue, but a style issue, and hopefully it will be updated. :)
