### ISSUE TITLE
Broken table formatting on 'searching issues and pull requests' on pt-br translation

### ISSUE THREAD

**Issue by micalevisk** [github/docs#17219]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/pt/search-github/searching-on-github/searching-issues-and-pull-requests

### What part(s) of the article would you like to see updated?

table formatting is broken in the following sections:

- https://docs.github.com/pt/search-github/searching-on-github/searching-issues-and-pull-requests#filter-by-repository-visibility
- https://docs.github.com/pt/search-github/searching-on-github/searching-issues-and-pull-requests#search-for-draft-pull-requests

![image](https://user-images.githubusercontent.com/13461315/164146179-d2bb8142-1c8d-4710-9de4-7c90d48c4eac.png)

![image](https://user-images.githubusercontent.com/13461315/164146198-c89de541-063e-4240-98ad-2d7c0c592477.png)

**Comment by ramyaparimi** [comment]
@micalevisk 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
