### ISSUE TITLE
On all pages, the header moves when scrolling  

### ISSUE THREAD

**Issue by jaypavasiya** [github/docs#17256]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account

![image](https://user-images.githubusercontent.com/82635946/164392423-af70e323-dfb1-4885-9797-0eafb73d8586.png)

### What changes are you suggesting?

Headers should be positioned at the top of the page

**Comment by jaypavasiya** [comment]
https://user-images.githubusercontent.com/82635946/164393469-c40e2d9b-c38d-448f-bc41-d66e0ad8f8ab.mp4

**Comment by ramyaparimi** [comment]
@jaypavasiya 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce on the latest release Firefox and Chrome on macOS 11.6.5 -- can you share what browser and OS you're using?

**Comment by jaypavasiya** [comment]
> Thanks for the report! I'm unable to reproduce on the latest release Firefox and Chrome on macOS 11.6.5 -- can you share what browser and OS you're using?

I'm using **Version 102.0.4997.0** in Chrome Dev.

**Comment by jaypavasiya** [comment]
> Thanks for the report! I'm unable to reproduce on the latest release Firefox and Chrome on macOS 11.6.5 -- can you share what browser and OS you're using?

closing this issue - The issue seems to be with Chrome's beta version; I switched to Chrome production's latest version, and now it works fine
