### ISSUE TITLE
heredoc example is wrong

### ISSUE THREAD

**Issue by davidmaxwaterman** [github/docs#17261]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-2

### What part(s) of the article would you like to see updated?

```
      echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
      curl https://example.lab >> $GITHUB_ENV
      echo 'EOF' >> $GITHUB_ENV
```

It doesn't seem to work. IINM, it's missing an `=` and the technique is flawed anyway (setting an env doesn't read from stdin, nor a heredoc).

It should be something like the following - `cat` reads from stdin/heredoc, and it needs to be executed in a subshell, hence `$()`:

```
      echo 'JSON_RESPONSE=$(cat <<EOF' >> $GITHUB_ENV
      curl https://example.lab >> $GITHUB_ENV
      echo 'EOF' >> $GITHUB_ENV
      echo ')' >> $GITHUB_ENV
```

The poweshell example might well need some similar TLC (I have no experience of powershell, but it seems like it uses some kind of `@'....'@` syntax.

Ref:
https://stackoverflow.com/questions/1167746/how-to-assign-a-heredoc-value-to-a-variable-in-bash#answer-1167849
https://4sysops.com/archives/the-powershell-here-string-preserve-text-formatting/

**Comment by ethomson** [comment]
Hi @davidmaxwaterman - I'm not sure that I understand entirely. The `GITHUB_ENV` file is not parsed by the shell, it uses either `NAME=value` format _or_ the multiline `NAME<<DELIMITER` format, which will read up until `DELIMITER` is encountered on a bare line.

You should see that this snippet of a job:

```yaml
      - run: |
          echo "MULTI_LINE<<EOF" >> $GITHUB_ENV
          echo "line one" >> $GITHUB_ENV
          echo "line two" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - run: |
          env
```

produces the following output:

```
...
MULTI_LINE=line one
line two
...
```

**Comment by lucascosti** [comment]
It appears that the current docs are correct, so I'll close this issue.

**Comment by davidmaxwaterman** [comment]
Sorry, I must has missed @ethomson 's reply in my email.

This is what your example produces:

```
% echo "MULTI_LIN<<EOF"; echo "line one"; echo "line two"; echo "EOF"
MULTI_LINE<<EOF
line one
line two
EOF
```

However, that isn't valid script because a 'heredoc' is a way of redirecting text into STDIN, and a variable (MULTI_LINE is a variable) doesn't have STDIN. This can be see by attempting to run the generated script:

```
% MULTI_LINE<<EOF
line one
line two
EOF

zsh: command not found: MULTI_LINE
```

Only commands accept STDIN and similarly a HEREDOC, so you need to use a command to accept the HEREDOC:

```
$ MULTI_LINE=$(cat<<EOF
> line one
> line two
> EOF
> )
sh-3.2$ echo $MULTI_LINE
line one line two
```

Probably good to add a `;` in (or `&&`) there if making multiple commands:

```
sh-3.2$ MULTI_LINE=$(cat<<EOF
echo hello &&
echo world
EOF
)
sh-3.2$ eval $MULTI_LINE
hello
world
```

Please consider reopening this bug.

**Comment by ethomson** [comment]
> However, that isn't valid script because a 'heredoc' is a way of redirecting text into STDIN

It's not a heredoc. It's not shell. You need to literally put that text into the file described by `GITHUB_ENV`. GitHub Actions reads that file - in the syntax that we've described - and will set the Actions environment variable as you told it to.

It has nothing to do with bash or any other shell. You can write a C app that puts the data into the file in the format that was described here and it will work.

If you try my example that I posted for you I think that you will find it elucidating.

**Comment by davidmaxwaterman** [comment]
Ah, well that explains a lot.
Actually, I can't remember what took me to that document - probably some CI problem we were having.
In any case, but I can't try out your example because I'm not using github actions - it's someone else's responsibility, and I had been asked to help to find out what was wrong...or something...it was a while ago now and I've forgotten.
However, I think now you've understood what I was trying to say, and you've explained that I have a misunderstanding (due to the similar syntax, likely), so all good.
Thanks.
