### ISSUE TITLE
"Delete an artifact" - possible JS code sample typo

### ISSUE THREAD

**Issue by alanfriedman** [github/docs#17265]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Article: https://docs.github.com/en/rest/actions/artifacts#delete-an-artifact

I'm using Node v16.14.2 with the `@octokit/core` library.

### What changes are you suggesting?

I copied the code in the [JavaScript code sample](https://docs.github.com/en/rest/actions/artifacts#delete-an-artifact--code-samples) in the [Delete an Artifact](https://docs.github.com/en/rest/actions/artifacts#delete-an-artifact) article:

```js
await octokit.request('DELETE /repos/{owner}/{repo}/actions/artifacts/{artifact_id}', {
  owner: 'OWNER',
  repo: 'REPO',
  artifact_id: 'ARTIFACT_ID'
})
```

When executing the request, I receive a `422` error response with the message: `Invalid request.\n' +
        '\n' +
        '"artifact_id", "owner", "repo" are not permitted keys.`.

If I remove those keys from the request body, the request is successful.

It seems that those keys should be removed from the sample code.

**Comment by ramyaparimi** [comment]
@alanfriedman 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by skedwards88** [comment]
This example snippet works for me. The Octokit library pulls the path parameter values that you supply from the body. I suspect that you replaced the path parameters in both the path AND in the body. If you provide the parameter values in just the body, the example should work. For example:

```javascript
const out = await octokit.request('DELETE /repos/{owner}/{repo}/actions/artifacts/{artifact_id}', {
  owner: 'name-of-my-org',
  repo: 'name-of-my-repo',
  artifact_id: 'id-of-my-artifact'
})
```

I will bring this up with the team to see if we can make this clearer.
