### ISSUE TITLE
"In this article" section cut-off vertically, so it isn't obviously that there is more content

### ISSUE THREAD

**Issue by timrogers** [github/docs#17271]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

It seems to affect any article with a _long_ "In this article" section (i.e. table of contents), but I particularly spotted it in [this article](https://docs.github.com/en/rest/overview/resources-in-the-rest-api), using Chrome 100.0.4896.88 on macOS.
 

### What changes are you suggesting?

When a docs page has a long "In this article" section (i.e. table of contents), that table of contents is cut-off vertically and scrollable.

Where this happens, it might not be obvious that there are more headings in the table of contents than the ones you can initially see - that is, it isn't visible and clear that the content is cut-off and you can scroll.

You can see this in the following screenshot. It isn't obvious that there are more headings you can navigate to beyond "User agent required".

<img width="1333" alt="Screenshot 2022-04-21 at 18 03 40" src="https://user-images.githubusercontent.com/116134/164513318-ae26bb04-2979-47b3-a524-6410e0b2d30e.png">

I would suggest that we could either (a) allow the table of contents to expand further vertically or (b) look at options for forcing the display of scrollbars.

**Comment by ramyaparimi** [comment]
@timrogers 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by rsese** [comment]
ahh we coincidentally just opened an internal issue about the behavior of that sidebar -- I'll close this issue out in favor of our internal issue but I'll share your comments there as well so we can capture your notes.  But thanks again for the detailed feedback, much appreciated ❇️ !
