### ISSUE TITLE
GitHub Desktop v3.0 release

### ISSUE THREAD

**Issue by steveward** [github/docs#17302]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- Two new articles for GitHub Desktop: "Configuring notifications" and "Viewing and re-running checks"
- Two updated articles:
  - "[Viewing a pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/viewing-a-pull-request-in-github-desktop)" to display and reference added checks functionality 
  - "[Committing and reviewing changes to your project](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project)" with reference to new checks article

### What part(s) of the article would you like to see updated?

See content plan below.

#### New content

- [x] Create a new article "Configuring notifications"
  - [x] Add to "[Contributing and collaborating using GitHub Desktop](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop)" category's "[Work with your remote repo](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise)" map topic, after "[Viewing a pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/viewing-a-pull-request-in-github-desktop)"
  - [x] Add section: "About notifications in GitHub Desktop"
    - [x] Describe the context around the types of notifications that will be shown in GitHub Desktop
      - [x] Mention that notifications will only be shown for the selected repository
      - [x] Mention that notifications will be shown as system notifications
      - [x] Show examples with screenshots for two notification types:
        - [x] Pull request checks failed
        - [x] Pull request reviews
        - [x] Show that a notification will be given with the option to switch to a pull request branch when a new notification is received
    - [x] Reference "Viewing a pull request" article that describes how to check out a pull request
  - [x] Add procedural section: "Enabling notifications"
    - [x] Create macOS-specific guide for enabling system notifications: Navigate to System Preferences > Notifications and Focus > GitHub Desktop > Allow Notifications
    - [x] Create Windows-specific guide for enabling system notifications: Navigate to Start > Settings > System > Notifications
  - [x] Add referential section: "Further reading"
    - [x] Link to "[Change notification settings in Windows](https://support.microsoft.com/en-us/windows/change-notification-settings-in-windows-8942c744-6198-fe56-4639-34320cf9444e)" for Windows
    * [x] Link to "[Use notifications on your Mac](https://support.apple.com/en-us/HT204079)" for macOS

- [x] Create a new article "Viewing and re-running checks"
  - [x] Add to "[Contributing and collaborating using GitHub Desktop](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop)" category's "[Work with your remote repo](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise)" map topic, after "[Viewing a pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/viewing-a-pull-request-in-github-desktop)"
  - [x] Add section: "About checks in GitHub Desktop
    - [x] Give an overview of checks and why having them in GitHub Desktop is useful
    - [x] Reference "[About status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks)" article
  - [x] Add section: "Viewing and re-running checks"
    - [x] Walk though the process of navigating to a check and re-running it: check out the PR branch, select re-run checks
    - [x] Add step for re-running individual checks

#### Updated content
- [x] Add reference to new checks article in "[Viewing a pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/viewing-a-pull-request-in-github-desktop)"
- [x] Update screenshots in "[Viewing a pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/viewing-a-pull-request-in-github-desktop)" to display added checks functionality
- [x] Add reference to checks article in "[Committing and reviewing changes to your project](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project)"

**Comment by Jen-567** [comment]
Hallow @steveward
