### ISSUE TITLE
Document markdown color rendering

### ISSUE THREAD

**Issue by aisgbnok** [github/docs#17312]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

One of the following:

- [Basic writing and formatting syntax](https://docs.github.com/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
   - Under the "Quoting code" section OR
   - Under its own section
- [Working with advanced formatting](https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting) having its own page?

### What part(s) of the article would you like to see updated?

I have noticed recently that wrapping color in markdown code syntax renders the color. I'm not sure if this is new behavior, but either way, I don't believe this is documented anywhere. I thought it was cool, and it would be nice to have this documented. 

I'm not entirely sure the best location to put this. You can see my suggestions above, but I don't think this is extensive enough to have its own page? I wouldn't mind writing and opening a PR documenting this, but I first would love some feedback as to where this would be best placed. Thanks!

### Additional information

Below you can see an example list that shows colors being rendered when wrapped in markdown code syntax. Note that keeping a list of supported colors doesn't have to be in the documentation. I just wanted to list them all out to see what was working. 

#### Supported
- HEX `#3fb950`
- RGB `rgb(255, 233, 0)`
- HSL `hsl(128, 49%, 49%)`

#### Unsupported
- HSV `hsv(128, 66%, 73%)`
- CMYK `cmyk(66%, 0%, 57%, 27%)`
- HSB `hsb(128, 49%, 49%)`
- HSI `hsi(128, 42%, 43%)`
- HWB `hwb(128, 25%, 27%)`
- NCol `G14, 25%, 27%`
- CIELAB `CIELab(66.77, -55.25, 42.98)`
- CIEXYZ `xyz(20.8459, 36.3325, 13.504)`
- VEC4 `(0.25f, 0.73f, 0.31f, 1f)`

**Comment by ramyaparimi** [comment]
@aisgbnok 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @aisgbnok! You or anyone else are welcome to open a PR to add a new section to https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax, called "Supported color models." We should only include the syntax for the 3 supported formats, not any of the unsupported ones. 

Thanks for your interest and passion in improving the GitHub Docs!
