### ISSUE TITLE
The Website Scrolling behaviour is not smooth

### ISSUE THREAD

**Issue by shawavisek35** [github/docs#17362]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The go to top button in the website does not have a smooth scroll behaviour.

### What changes are you suggesting?

The go to top button in the website does not have a smooth scroll behaviour. I would like to contribute to this docs by updating the site so that it includes smooth scrolling when shifting to different sections of the content or just going to the top of the page using go to top button.

**Comment by GoogleCEOstevenking** [comment]
Yo

**Comment by dreamer820** [comment]
your world

**Comment by dreamer820** [comment]
⁸

**Comment by Drahcir234** [comment]
Yes

**Comment by rsese** [comment]
👋 ! We're tracking some of these UI type of behaviors internally so it's not something we would review a PR for right now --  but thanks again for your interest and let us know if you have any other feedback!
