### ISSUE TITLE
Incorrect word in Spanish translation

### ISSUE THREAD

**Issue by juanmesa2097** [github/docs#17405]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/translations/es-ES/data/release-notes/enterprise-server/3-2/3.yml

And

https://github.com/github/docs/blob/main/translations/es-ES/content/actions/managing-workflow-runs/re-running-workflows-and-jobs.md

### What part(s) of the article would you like to see updated?

Word "hubieron" is incorrect under that context and it should be replaced with "hubo"

### Additional information

![image](https://user-images.githubusercontent.com/64181348/165410492-cc49e634-7381-4278-a6da-dfe2c082a1d0.png)

**Comment by ramyaparimi** [comment]
@juanmesa2097 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
