### ISSUE TITLE
Creating a GitHub Pages site with Jekyll - Confuses USER with PROJECT pages/repositories.

### ISSUE THREAD

**Issue by akalenchuk** [github/docs#17410]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

### What part(s) of the article would you like to see updated?

Article starts (step 3, creating repository) by showing how to create a USER page, stating you must create a specifically named repository online: USERNAME.github.io

However the rest of the article (step 3, creating your site) explains how to create a PROJECT page with a local differing repository, referred to as REPOSITORY-NAME and octo-repo in the screenshot example (step 20).

You then remote this later repository (step 16) and try to push to it (step 17), however it does not exist online (not created in article), and you get a "remote: Repository not found" error. 

If you go online and create another repository with the proper REPOSITORY-NAME for the locally created Jekyll site (step not shown), you can then push to it, however it is not a USER page and it will not display at http://username.github.io.

I don't see any solution on how to push a locally created folder/repository to the specially USERNAME.github.io online repository.

The article is also unnecessarily complex by explaining branches (step 6), which aren't used in a USER page.

**Comment by ramyaparimi** [comment]
@akalenchuk 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by akalenchuk** [comment]
After some playing around I was able to get this to work -- i.e. locally create a repository and push to the online user page repository. I recommend the following changes:

(step 3, creating repository) -- remains the same
(step 3, creating your site and further) -- change commands to: 

git init USERNAME.github.io
cd USERNAME.github.io 
jekyll new --skip-bundle
<edit Gemfile as instructed>
bundle install
git add .
git commit -m 'Initial GitHub pages site with Jekyll'
 git remote add origin https://github.com/USERNAME/USERNAME.github.io.git
git push -u origin master

**Comment by lecoursen** [comment]
👋🏻 @akalenchuk, REPOSITORY-NAME is a placeholder which should be replaced by the actual name of your repository, which is mentioned in the instructions like this:

>If you haven't already, initialize a local Git repository, **replacing REPOSITORY-NAME with the name of your repository.**

 If you choose to create a user site, that repository name would be `akalenchuk.github.io`.

Let me know if you have any questions about that!
