### ISSUE TITLE
Top repositories do not drop off after 4 months w/out interaction, unlike what docs say

### ISSUE THREAD

**Issue by rschristian** [github/docs#17431]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/about-your-personal-dashboard#finding-your-top-repositories-and-teams

### What part(s) of the article would you like to see updated?

> The list of top repositories is automatically generated, and can include any repository you have interacted with, whether it's owned directly by your account or not. Interactions include making commits and opening or commenting on issues and pull requests. The list of top repositories cannot be edited, **but repositories will drop off the list 4 months after you last interacted with them.**

(emphasis mine)

As of a few weeks ago, this no longer seems to be the case. My repository list was reordered, with long untouched repositories now moved up near the top. One of my top repositories now is one I have not interacted with in well over a year.

I'm not sure if this is a regression in the ordering logic or if there was an intentional change that the documentation was not updated for. Someone with know of the new logic will need to update that statement, as I don't think that's exposed to the public?

![Screenshot of my own top repositories section](https://user-images.githubusercontent.com/33403762/165632775-0611bdff-4c62-4448-8924-2e73b0096398.PNG)

Link to verify: https://github.com/mutoe/preact-realworld-example-app

**Comment by ramyaparimi** [comment]
@rschristian 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by rschristian** [comment]
Closing this out as it seems to have been fixed on my end. I'm guessing it was just a regression that's now been resolved.
