### ISSUE TITLE
`ldap_dn` field missing from `docs.github.com`

### ISSUE THREAD

**Issue by GalaxyAllie** [github/docs#1743]
### What article on docs.github.com is affected?

[Create a team](https://docs.github.com/en/enterprise-server@2.22/rest/reference/teams#create-a-team) for GitHub Enterprise Server.

### What part(s) of the article would you like to see updated?

The `ldap_dn` field, which is specific to GitHub Enterprise Server, was documented on `developer.github.com` but is not documented on `docs.github.com`

**Comment by redminoat9s** [comment]
Idap-dn

**Comment by GalaxyAllie** [comment]
Closing this as I think this may be a mistake with `developer.github.com` that was fixed in `docs.github.com`

**Comment by GalaxyAllie** [comment]
Closing this to investigate how this field works.
