### ISSUE TITLE
Instructions to create a GH Pages site with Jekyll should indicate Ruby version

### ISSUE THREAD

**Issue by bewuethr** [github/docs#17504]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- [*Creating a GitHub Pages site with Jekyll*](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll)
- [*Testing your GitHub Pages site locally with Jekyll*](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll)

### What part(s) of the article would you like to see updated?

The articles describe how to create a Jekyll site for GitHub Pages from scratch and testing the site locally, including the installation of Ruby. Now, the gem used for GitHub Pages, `github-pages`, has Jekyll 3.9.0 as a dependency, and that version of Jekyll doesn't work with Ruby 3+ (see [here](https://talk.jekyllrb.com/t/error-no-implicit-conversion-of-hash-into-integer/5890) for the error when trying to build with Ruby 3).

Thus, the instructions should indicate that the Ruby version to install should be 2.x, and not 3.x.

**Comment by mmvvmm37123mgc** [comment]
mmvvmm37123mgc@gmail.com #
