### ISSUE TITLE
Add section to explain how to securely store API keys (client secrets, etc) for software on github that uses them

### ISSUE THREAD

**Issue by vedant205** [github/docs#17532]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I do not think this information is in any article, but it could be and I might have just missed it. 

### What part(s) of the article would you like to see updated?

I think a section describing how users can keep their API keys safe for their software on Github. For example, maybe explaining to not push api keys to public repositories or explaining how to develop locally using API keys (like storing them in a local config.json or something).
UPDATE: 
It seems like this information is actually on the GitGuardian blog at https://blog.gitguardian.com/secrets-api-management/ so maybe just linking to that somewhere (if it isn't already linked) on Github docs would be good?

**Comment by ramyaparimi** [comment]
@vedant205 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by vedant205** [comment]
Sounds good!

**Comment by Koudinka** [comment]
https://github.com/github/docs/issues/17532#issue-1222421195

**Comment by skedwards88** [comment]
Thank you for this suggestion! I agree that we should add this info, but we will open an internal issue for it so that we can have our security team review it before publishing. I'm going to close this out in favor of the internal issue that I will open pointing to this issue.
