### ISSUE TITLE
Indicate if runner names are temporaly unique within a given scope

### ISSUE THREAD

**Issue by jsoref** [github/docs#17589]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-50
https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/e93864362002a180c7ec17eefdb8cb49efea9e40/data/reusables/actions/runner-name-description.md?plain=1#L1

It'd be nice if something clearly indicated if a runner name is temporaly unique within a given scope.

i.e. Can two runners running jobs at the same time for the same repository have the same name?

I think the answer is no. But I'm not sure.

### Additional information

https://github.community/t/ref-head-in-reusable-workflows/203690/95?u=jsoref

**Comment by jww3** [comment]
I was able to register two runners with the same name, albeit at different levels.  First, I registered a runner named `runner1` at the repo level (in the repo's `Default` runner group).

Then, I went to an org-level runner group already shared with the repo where I registered `runner1`.  I was able to register a second runner named `runner1` within this org-level runner group.

At job-assignment time, both of those `runner1`'s are eligible to perform work on behalf of the repo.

**Comment by hubwriter** [comment]
@jsoref - The link https://github.community/t/ref-head-in-reusable-workflows/203690/95?u=jsoref is no longer working so I'm not sure the context of why this came up. It sounds like we could add a little detail here if it would provide value but we shouldn't add information unless it's genuinely going to help folks out (we're sometimes criticized in feedback for giving too much detail). 😃  

Maybe you could say a little more here about why this is needed?

**Comment by jsoref** [comment]
I have code that tries to find a running workflow and it's helpful to know if this field uniquely identifies a runner at a given point in time. Apparently, it does NOT, as while there might only be one runner by that name at a repository level, another could exist at the organization level and both could be running workflows for that repository at the same time.

**Comment by hubwriter** [comment]
@jsoref - Thanks for clarifying.

I agree it would be useful to clarify in [the reusable](https://github.com/github/docs/blob/e93864362002a180c7ec17eefdb8cb49efea9e40/data/reusables/actions/runner-name-description.md?plain=1#L1) that the name may not be unique in a workflow run as runners at repository and organization level could use the same name.

**Comment by electron97** [comment]
Hey @hubwriter,

I have raised a PR: https://github.com/github/docs/pull/27747 with the changes suggested by you.
Could you please take a look whenver you get a chance?

Also big thanks to @jsoref for addressing this issue.

Thanks!

**Comment by cmwilson21** [comment]
@electron97 - Thanks for the PR! I'll get it triaged and on the review board 👍
