### ISSUE TITLE
Suggested: update to GitHub's markdown support for Basic writing and formatting syntax section

### ISSUE THREAD

**Issue by LRANUL** [github/docs#17618]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Web link: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

### What part(s) of the article would you like to see updated?

Reason and outcome: This update will allow GitHub community to use more features supported by GitHub platform which aren't currently mentioned on the docs, this new addition will help the members working on mathematical and scientific fields on GitHub to use appropriate markup to represent relevant scientific and mathematical notations improving there repository more readable to the subject experts/audience.
e.g. The equation chemical notation of water could be interpreted as H<sub>2</sub>O by writing as `H<sub>2</sub>O`
Page section: **Styling text**

### Additional information

Page after suggested update: 
![image](https://user-images.githubusercontent.com/48907530/166711462-e5d5b02d-d89d-4b74-885e-2cd3e8595db7.png)

**Comment by ramyaparimi** [comment]
@LRANUL 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by LRANUL** [comment]
@ramyaparimi This issue got closed, with the removal of the forked repository on my profile, shall I reopen this issue another pull request for the same ?

**Comment by ramyaparimi** [comment]
@LRANUL I will go ahead and reopen this issue. Please create a PR for the issue at your convenience 💛 .

Thank you so much for your passion in improving GitHub docs 💖 .

**Comment by rachmari** [comment]
@LRANUL @ramyaparimi this certainly does look like a bug. I've opened an internal engineering issue to look into the problem. I apologize for the inconvenience.
