### ISSUE TITLE
Mention `Body cannot be empty` in `Common validation errors when creating issue forms`

### ISSUE THREAD

**Issue by jsoref** [github/docs#17629]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms

### What part(s) of the article would you like to see updated?

Add a section for `Body cannot be empty`

Ideally it should explain something about the error.

### Additional information

I created a file https://github.com/jsoref/choco/commit/f613096f4da2e1b7b01d018a9fa0ef96f93914a1

When I browse to it right now:
https://github.com/jsoref/choco/blob/develop/.github/ISSUE_TEMPLATE/ReportPackageIssue.yaml

I see:

There is a problem with this template

Body cannot be empty. [Learn more](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#body-cannot-be-empty-when-issue_body-is-false).

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/2119212/166817383-7028f99f-5ad6-4efa-bb7e-4344d7433356.png">

Fwiw, I tried to model the file after https://raw.githubusercontent.com/github/docs/main/.github/ISSUE_TEMPLATE/improve-existing-docs.yaml

**Comment by jsoref** [comment]
Fwiw, there's also

> There is a problem with this template
>
> YAML syntax error: (): mapping values are not allowed in this context at line 12 column 53. [Learn more](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms).

https://github.com/jsoref/choco/commit/6d2bc05103ef064c081293a86f02215c491ad84e

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/2119212/166818402-b5d2c5db-56c3-4d78-957c-a6b81e02fecf.png">

**Comment by ramyaparimi** [comment]
@jsoref Did you meant to have [this link ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#body-cannot-be-empty-when-issue_body-is-false) for "What article on docs.github.com is affected?" question?

**Comment by jsoref** [comment]
Sigh. Thanks. Clipboard fail trying to do three interrelated things at once.

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by cmwilson21** [comment]
👋 @jsoref Thank you for your patience on this one. 💛 

I’ve spoken with the team, we were able to reproduce this instance without the `Body cannot be empty error` populating. However, we did so without the `---` around the name and description, as the body tag is found externally here.

As for adding the error, you or anyone else are welcome to open a PR adding the error with a sentence similar to “The template body key:value pair must not be empty.” And for more info include a link to the “[Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)” article

**Comment by jsoref** [comment]
I probably should have explained that in my case, I'm pretty sure the reason for the error was the `---`. I'm not sure which will be more common: not having a body or for some reason copying a `---` and thus causing it not to be seen.

**Comment by aitemour79** [comment]
***@***.*** com

**Comment by cmwilson21** [comment]
Gotcha. Thanks for clarifying here. And for submitting a PR, I'll get it triaged ⚡
