### ISSUE TITLE
Hello, I work on an open-source project and we want to consistently, and without minimal specialization, check for all links in a collection of Markdown documents for our community and our staff developers. The are only a few of the latter, and want to be able to keep for user contributions as much as our own changes. It appears from GitHub Actions hosted runners (we don't do self-managed yet) we often get HTTP 403 errors and rate limited. This appears to be separate of _rate limiting for the API_ as [I discussed in github.community, where they also recommend I ask about it here](https://github.community/t/is-rate-limiting-for-docs-github-com-documented-anywhere/245830/4).

### ISSUE THREAD

**Issue by 91CH** [github/docs#17640]
Hello, I work on an open-source project and we want to consistently, and without minimal specialization, check for all links in a collection of Markdown documents for our community and our staff developers. The are only a few of the latter, and want to be able to keep for user contributions as much as our own changes. It appears from GitHub Actions hosted runners (we don't do self-managed yet) we often get HTTP 403 errors and rate limited. This appears to be separate of _rate limiting for the API_ as [I discussed in github.community, where they also recommend I ask about it here](https://github.community/t/is-rate-limiting-for-docs-github-com-documented-anywhere/245830/4).

This recently popped up again today.

https://github.com/usnistgov/OSCAL/runs/6290851865?check_suite_focus=true

So some questions and maybe I open up an improvement issue if you agree this is worthwhile.

1. Is this rate limiting from hosted GHA runners intentional?
2. Is the rate limiting able to lifted from GHA runners by passing an appropriate token? It appears initial test attempts suggest no.
3. If we ask you consider switching the rate limiting response error code in HTTP from 403 to 429, will that be something that is possible? [That seems to be appropriate for this context](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) and would allow us to use [a popular link checker for Markdown with existing configuration with `retryOn429` and `aliveStatusCodes` behavior](https://github.com/tcort/markdown-link-check#markdownlinkcheckmarkdown-opts-callback) that is more in line with the nature of the error response, and not a HTTP 403 response which is a little more blunt.

Again, we'd like to make this work with low effort for our team and not more specialized code for just docs.github.com, but not sure how to proceed. It broke builds enough we exempted all of docs.github.com, but that obviously doesn't help and kind of defeats the purpose if we change them or links for GH do change.

Sincerely,
Your Friends at NIST

_Originally posted by @aj-stein-nist in https://github.com/github/docs/discussions/17620_

**Comment by aj-stein-nist** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

Hello @91CH, are you one such docs team member, this has been failing our link checks in our builds of our public docs before a release a little more frequently than normal as of late. Does the conversion to an issue mean 404->429 is even something on the table for discussion?

**Comment by ramyaparimi** [comment]
@aj-stein-nist The author who shared your discussion is most likely a spammer and I am so sorry about this confusion. I have let the team our engineering team know about the discussion post you opened 💖. 

I will be closing this issue now since this is re-posted and considered spam. Thank you for your patience 💛 .

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist The author who shared your discussion is most likely a spammer and I am so sorry about this confusion. I have let the team our engineering team know about the discussion post you opened 💖.
> 
> I will be closing this issue now since this is re-posted and considered spam. Thank you for your patience 💛 .

All good, no worries! I will continue to follow the discussion posts instead. 👋
