### ISSUE TITLE
Investment

### ISSUE THREAD

**Issue by Estelle544** [github/docs#17658]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The open end

### What part(s) of the article would you like to see updated?

It needs to be updated

**Comment by billybob3659** [comment]
Yeah, I'm bout to take sure. Just threw up.
github/docs

________________________________
From: Estelle544 ***@***.***>
Sent: Friday, May 6, 2022, 5:20 AM
To: github/docs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [github/docs] Investment (Issue #17658)


Code of Condu

  *    I have read and agree to the GitHub Docs project's Code of Conduct<https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md>

What article on docs.github.com is affected?

The open end

What part(s) of the article would you like to see updated?

It needs to be updated

Additional information

No response
