### ISSUE TITLE
content trouble

### ISSUE THREAD

**Issue by zech564** [github/docs#1768]

**Comment by FREELANCEGITIT** [comment]
The entire set. All data thats gs  for sure 




On Thursday, December 3, 2020, 3:32 AM, zech564 <notifications@github.com> wrote:




What article on docs.github.com is affected?

What part(s) of the article would you like to see updated?

Additional information

**Comment by ajs256** [comment]
Hey there @zech564!

Thanks for opening an issue. Could you please fill out the issue template so the team can know what the problem is?

> Please note that I am not affiliated with the GitHub docs team.
