### ISSUE TITLE
Quickstart for GitHub Packages should discuss organization repositories

### ISSUE THREAD

**Issue by jsoref** [github/docs#17714]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/packages/quickstart

### What part(s) of the article would you like to see updated?

Possibly in

https://docs.github.com/en/packages/quickstart#introduction
> In this guide, you'll create a GitHub Actions workflow to test your code and then publish it to GitHub Packages.

or possibly at the bottom

Add a note:

While this document discusses repositories of the form `YOUR-USERNAME/YOUR-REPOSITORY`, if you're in an organization `YOUR-ORGANIZATION` with a repository `YOUR-REPOSITORY` (i.e. you have a reposiotry `YOUR-ORGANIZATION/YOUR-REPOSITORY`), just substitute `YOUR-ORGANIZATION` for `YOUR-USERNAME` in these instructions.

### Additional information

https://github.community/t/questions-on-quickstart/193642

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by janiceilene** [comment]
@jsoref Thanks for opening an issue! I've discussed it with the team and we're going to leave the docs as they are since they follow our style guide and conventions. Adding this additional content may confuse more users than it helps.

Thanks again!
