### ISSUE TITLE
Feature Request: API documentation should contain request body JSON schema

### ISSUE THREAD

**Issue by bostrick** [github/docs#17733]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/checks/runs#create-a-check-run

(As but one example of what this systemic change would address....)

### What part(s) of the article would you like to see updated?

The API helpfully provides the JSON schema of API responses.   It would also be helpful to provide JSON schema of request bodies, so that client unittesting could validate call parameters while still offline.

**Comment by ramyaparimi** [comment]
@bostrick 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by rachmari** [comment]
👋 @bostrick this is a great suggestion and I'm glad you find the response schemas helpful. That is a recent change we made. I've added this request to an internal tracking issue as a consideration to be done in the future for REST docs.

**Comment by rachmari** [comment]
@bostrick just one more note, the schema is public for all operations. This will include the schema for the whole operation, including the request body. For example, here is the dotcom version of the schema: https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.json

All versions of the OpenAPI schema are located here: https://github.com/github/rest-api-description/tree/main/descriptions

**Comment by bostrick** [comment]
Thanks for response, and good to know about schema blobs... I'd still argue that having a snippet of the Schema for the API call your're interested in easily available beats digging through a 3MB blob of JSON, but it's good to know these are there. 

Thanks! --b
