### ISSUE TITLE
Talk about credentials for importing repositories

### ISSUE THREAD

**Issue by jsoref** [github/docs#17750]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/importing-your-projects-to-github/importing-source-code-to-github/importing-a-repository-with-github-importer

### What part(s) of the article would you like to see updated?

Add a section that talks about entering credentials (it's part of the flow but not described at all).

Include a note indicating that if the source repository is guarded by 2FA or hosted by GitHub one probably needs to use a PAT instead of a password.

### Additional information

https://github.community/t/importing-repo-not-working/249593

Fwiw, I've personally tripped on this and mentioned it in a bug report about something related to this flow.

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by cmwilson21** [comment]
After checking with the team, it looks as though, shortly after this issue was opened, an internal PR was submitted that added the missing information into Step 6. I'm going to close this issue now. Thanks again for opening the issue! 💛
