### ISSUE TITLE
Document `github.secret_source` context value

### ISSUE THREAD

**Issue by gmaclennan** [github/docs#17752]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

### What part(s) of the article would you like to see updated?

The property name `github.secret_source` is not documented. As far as I can understand, the value can be `None | Actions | Dependabot`. It would be good to confirm that. It is included in the example, just not in the table that documents all properties.

**Comment by gmaclennan** [comment]
Just a gentle reminder, since this is still not documented, but appears to work and is intended to be documented.

**Comment by cmwilson21** [comment]
@gmaclennan thanks for checking in! We do appreciate your patience as we are working through our backlog 💛

**Comment by janiceilene** [comment]
Thanks so much for opening this issue @gmaclennan! We checked in with the team and this is a great addition. You or anyone else is welcome to open a PR 🎉
