### ISSUE TITLE
Typo in upstream URL

### ISSUE THREAD

**Issue by ckarampa** [github/docs#17785]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/quickstart/fork-a-repo

### What part(s) of the article would you like to see updated?

On the section [Configuring Git to sync your fork with the original repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo#configuring-git-to-sync-your-fork-with-the-original-repository) in bullet 6, the URL should point to the original owners repository and not its fork.

**Comment by ramyaparimi** [comment]
@ckarampa 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by ramyaparimi** [comment]
Just realized that there is a linked PR. I will be triaging the PR for a review and not the issue 💖 .
