### ISSUE TITLE
"Creating encrypted secrets for a repository" in "Encrypted Secrets" page is outdated

### ISSUE THREAD

**Issue by Andre601** [github/docs#17791]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

### What part(s) of the article would you like to see updated?

Right now are the mentioned steps as follows:

1. On GitHub.com, navigate to the main page of the repository.
2. Under your repository name, click **Settings**.
   ![image](https://docs.github.com/assets/cb-21851/images/help/repository/repo-actions-settings.png)
3. In the left sidebar, click **Secrets**.
4. Click **New repository secret**.
5. Type a name for your secret in the **Name** input box.
6. Enter the value for your secret.
7. Click **Add secret**.

The list is outdated by having the **Secrets** field now open a selection of options (Actions, Codespaces and Dependabot) rather than directly leading to a page where you can create the Repository Secret.

![image](https://user-images.githubusercontent.com/11576465/168086195-713080bb-38ed-42bb-ae6c-23766c2774e0.png)

**Comment by janiceilene** [comment]
Thanks so much for opening this issue @Andre601! You or anyone else is welcome to open a PR to make this fix ⚡
