### ISSUE TITLE
How are texts in `github/docs` translated?

### ISSUE THREAD

**Issue by lucalves** [github/docs#17797]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Hello all, everything good?

Some articles on github are translated with misspelled words.

I would like to know how I can contribute to work on these spelling corrections. Or if this is generated automatically.

For example, the title of this article in `Portuguese` is misspelled:

<img width="756" alt="Captura de Tela 2022-05-12 às 14 25 22" src="https://user-images.githubusercontent.com/17712401/168133750-0e6d416a-4c9d-4684-b6e7-55492a4c68ac.png">

Could someone clear my doubt? I would like to contribute with some corrections.

### What part(s) of the article would you like to see updated?

In this specific case, the **title** of the article.

**Comment by ramyaparimi** [comment]
@lucalves 
Thanks for opening this! Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.
