### ISSUE TITLE
Replace undated relative term `Recent` in `Using global node IDs`

### ISSUE THREAD

**Issue by jsoref** [github/docs#17810]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/guides/using-global-node-ids

### What part(s) of the article would you like to see updated?

The page says:

> You can access most objects in GitHub (users, issues, pull requests, etc.) using either the REST API or the GraphQL API. With a [recent update](https://developer.github.com/changes/2017-12-19-graphql-node-id/), you can find the global node ID of many objects from within the REST API and use these IDs in your GraphQL operations.

Today is 2022-May-12. That `recent update` isn't technically 5 years old, but it also isn't the kind of thing I should have to click to discover is not _recent_.

Fwiw, there is a newer GraphQL NodeID transition for which I'm hunting documentation, and while this was a high hit, it was a false positive, and it wasn't remotely obvious how bad of a false positive it was until I followed the link. It's pretty frustrating.

### Additional information

A quick look through:
https://cs.github.com/?scopeName=All+repos&scope=&q=repo%3Agithub%2Fdocs+%2F%5C%5B%5B%5E%5C%5D%5D*%5C%5D%5C%28%5B%5E%29%5D*developer.github.com.changes.2%2F+NOT+path%3A%2F%5Etranslations%5C%2F%2F

(n.b. this query was not fun to construct.)

... indicates this is the only instance of this specific problem (at least for markdown links to developer.github.com/changes), although `blog post` feels like the equivalent of "click `here`". -- It'd be nicer if those other pages included the blog post titles instead of using the generic term.

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! You are anyone else is welcome to make these changes. To summarize:
- Remove the "recent" wording
- Use the `For more information, see "[blog post title](link to blog post)"` format instead of an inline link
