### ISSUE TITLE
PR template referencing things not present

### ISSUE THREAD

**Issue by janbrasna** [github/docs#17811]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md

### What changes are you suggesting?

The PR template instructs me to some things that don't sound right, it may be just outdated terminology. Before addressing any of that in an actual PR I'm raising these for discussion:

1. "changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes"
   - I don't see anything "Modified" in the comment; there's a separate deployment timeline event, and the comment contains only "Preview", "Production" and empty "What's changed". Nothing more there to click. 🤷‍♂️ 
Was this meant to be something that's not there all the time, or has been removed/replaced?

2. The PR intro mentions linking a PR, that sounds like a place for referencing an issue to me, so maybe:

```diff
-By explaining why you're making a change (or linking to a pull request) and what changes you've made, …
+By explaining why you're making a change (or linking to an issue) and what changes you've made, …
```

3. The "local" links to `CONTRIBUTING.md` and `types-of-contributions.md` don't work in the context of a `/compare…` URL where the preview for new PR is being displayed, i. e. these two need to be converted to absolute like the others in the template.

I'll happily fix it if that's ok to touch the template file…

**Comment by ramyaparimi** [comment]
@janbrasna please go ahead and create a PR if the files are modifiable 💖 .

**Comment by thispsj** [comment]
@janbrasna thank you for highlighting those mistakes.

I have opened an PR for the fix.

**Comment by wiryallcserviceseducative** [comment]
![IMG_20220518_154011_485](https://user-images.githubusercontent.com/105491608/169712869-4608ff40-979d-41b8-a4dc-26505da0df61.jpg)
`
`

**Comment by wiryallcserviceseducative** [comment]
Wiryagans 
Work remote .
Teams World next level skill
