### ISSUE TITLE
Talk about query { nodes(ids: [...]) { ... } }

### ISSUE THREAD

**Issue by jsoref** [github/docs#17812]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/graphql/guides/migrating-graphql-global-node-ids.md#migrating-to-the-new-global-ids

### What part(s) of the article would you like to see updated?

There's a suggestion to use:

```sh
$ curl \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "X-Github-Next-Global-ID: 1" \
  https://api.github.com/graphql \
  -d '{ "query": "{ node(id: \"MDQ6VXNlcjM0MDczMDM=\") { id } }" }'
```

But, it'd be really helpful to suggest something fancier like the this graphql:

```sh
curl -v \
-H "Authorization: bearer $GITHUB_TOKEN" \
-H "X-Github-Next-Global-ID: 1" \
https://api.github.com/graphql \
-d \
'{"query":"query {\nnodes(ids: [\"MDEwOlJlcG9zaXRvcnkxODk2MjE2MDc=\", \"MDEyOk9yZ2FuaXphdGlvbjk5MTk=\", \"MDc6TGljZW5zZTA=\", \"MDM6QXBwMTUzNjg=\", \"MDQ6VXNlcjU4MzIzMQ==\",  ]) {\n\tid\n\t__typename\n}\n}"}'
```

<details><summary>Or even fancier</summary>

```graphql
query {
nodes(ids: ["MDEwOlJlcG9zaXRvcnkxODk2MjE2MDc=", "MDEyOk9yZ2FuaXphdGlvbjk5MTk=", "MDc6TGljZW5zZTA=", "MDM6QXBwMTUzNjg=", "MDQ6VXNlcjU4MzIzMQ==",  ]) {
	id
	__typename
	... on Repository {
	 nameWithOwner
	}
	... on Organization {
		name
	}
	... on User {
		name
	}
	... on License {
		name
	}
	... on App {
		name
	}
	... on Commit {
		repository {
			nameWithOwner
		}
	}
}
}
```
</details>

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by saputraGTX** [comment]
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>

<version core> ::= <major> "." <minor> "." <patch>

<major> ::= <numeric identifier>

<minor> ::= <numeric identifier>

<patch> ::= <numeric identifier>

<pre-release> ::= <dot-separated pre-release identifiers>

<dot-separated pre-release identifiers> ::= <pre-release identifier>
                                          | <pre-release identifier> "." <dot-separated pre-release identifiers>

<build> ::= <dot-separated build identifiers>

<dot-separated build identifiers> ::= <build identifier>
                                    | <build identifier> "." <dot-separated build identifiers>

<pre-release identifier> ::= <alphanumeric identifier>
                           | <numeric identifier>

<build identifier> ::= <alphanumeric identifier>
                     | <digits>

<alphanumeric identifier> ::= <non-digit>
                            | <non-digit> <identifier characters>
                            | <identifier characters> <non-digit>
                            | <identifier characters> <non-digit> <identifier characters>

<numeric identifier> ::= "0"
                       | <positive digit>
                       | <positive digit> <digits>

<identifier characters> ::= <identifier character>
                          | <identifier character> <identifier characters>

<identifier character> ::= <digit>
                         | <non-digit>

<non-digit> ::= <letter>
              | "-"

<digits> ::= <digit>
           | <digit> <digits>

<digit> ::= "0"
          | <positive digit>

<positive digit> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<letter> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"
           | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
           | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d"
           | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n"
           | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x"
           | "y" | "z"

**Comment by saputraGTX** [comment]
Start pojav lancher
Create a world 
100% loaded
Instantly crashes

**Comment by skedwards88** [comment]
We want to keep these examples readable so that a user can understand the query at a glance and then extrapolate to fit their use case. If you still think that these more complex examples should be added, can you say why you would find these cases helpful?

**Comment by jsoref** [comment]
* I don't think that the multi-node query feature previously existed
* On average, the people most likely to want to use this feature are going to want to query for multiple nodes -- certainly all the instances I've seen on github.community involved people who wanted multiple nodes and had to think about how to hack through w/ graphql to make that work.

Having to twist graphql in knots in order to do something for which there's a better function is really just cruel.
