### ISSUE TITLE
Create a repository section has wrong curl syntax

### ISSUE THREAD

**Issue by jatin837** [github/docs#17836]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Create a repository section (REST API)

### What part(s) of the article would you like to see updated?

Create a repository

### Additional information

![image](https://user-images.githubusercontent.com/63631162/168413637-21cbcd4d-fa42-495e-bc45-0eb8af55eb6f.png)
![image](https://user-images.githubusercontent.com/63631162/168413646-2f20f109-893a-4a59-b284-2c33ab0a4d3f.png)

**Comment by jatin837** [comment]
[Here's the fix](https://github.com/github/docs/pull/17835)

**Comment by thispsj** [comment]
@jatin837 absolutely right, anything within inverted commas (`"`) doesn't require a backslash or a new line seperator.

**Comment by skedwards88** [comment]
Closed via https://github.com/github/docs/pull/17835
