### ISSUE TITLE
i think there should be a link to a the github page instead of plain text 'github.com'

### ISSUE THREAD

**Issue by nzaih1999** [github/docs#17840]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#about-commit-email-addresses

### What changes are you suggesting?

the text should be changed to a link for better navigation

**Comment by steveward** [comment]
Thanks for the issue @nzaih1999! The 'GitHub.com' referenced in those articles is a [reusable](https://github.com/github/docs/tree/main/data/reusables#readme) that changes based on the currently-selected version of the docs site. It isn't intended to be a link, and as a result this isn't something that we would change. I'm going to close this out.

**Comment by nzaih1999** [comment]
Thanks for the feedback man
