### ISSUE TITLE
Possible confusion might be created in expression syntax docs

### ISSUE THREAD

**Issue by schalkneethling** [github/docs#17867]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions

### What part(s) of the article would you like to see updated?

So, in the fourth paragraph, the content reads:

> When you use expressions in an if conditional, you may omit the expression syntax (${{ }}) because GitHub automatically evaluates the if conditional as an expression.

From: https://github.com/github/docs/blob/main/data/reusables/actions/expression-syntax-if.md

The thing is the [first example](https://docs.github.com/en/actions/learn-github-actions/expressions#example-expression-in-an-if-conditional) uses expression syntax inside an `if` conditional. So, perhaps change that part of the docs as follows:

#### Example expression in an `if` conditional

```yaml
steps:
  - uses: actions/hello-world-javascript-action@v1.1
    if: <expression>
```

#### Example setting an environment variable

{% raw %}
```yaml
env:
  MY_ENV_VAR: ${{ <expression> }}
```
{% endraw %}

**Comment by lucascosti** [comment]
Closing as per this comment in the associated PR: https://github.com/github/docs/pull/17868#issuecomment-1140576015
