### ISSUE TITLE
Text about deleted/privatized fork roots doesn't appear to match actual implementation

### ISSUE THREAD

**Issue by jsoref** [github/docs#17876]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility

### What part(s) of the article would you like to see updated?

> [## Deleting a public repository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility#deleting-a-public-repository
)
> When you delete a public repository, one of the existing public forks is chosen to be the new parent repository. All other repositories are forked off of this new parent and subsequent pull requests go to this new parent.

> [## Changing a public repository to a private repository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility#changing-a-public-repository-to-a-private-repository)
> If a public repository is made private, its public forks are split off into a new network. As with deleting a public repository, one of the existing public forks is chosen to be the new parent repository and all other repositories are forked off of this new parent. Subsequent pull requests go to this new parent.

The way I read this seems to indicate that when a root of a fork network is deleted or privatized, some other repo in the network is (fairly arbitrarily) selected as the new root and any repositories that were forked from the now missing root are linked to that newly designated repository.

If my reading of the text is wrong (and the implementation is as intended), then the text should be clarified to indicate what's actually happening -- which I think is "dangling links are left randomly throughout the fork network resulting in confusion for users".

If the documentation is the intended behavior, then perhaps there is/was a bug in the implementation resulting in it diverging from the documentation and if the implementation is still errant, it should be fixed -- and either way, the dangling repositories should be fixed up.

### Additional information

<img width="195" alt="image" src="https://user-images.githubusercontent.com/2119212/168491430-769e2134-7531-4a9f-a56f-ebf5c2266a7a.png">

https://github.com/jsoref/libmdbx
> [jsoref](https://github.com/jsoref) / [libmdbx](https://github.com/jsoref/libmdbx) Public
forked from https://github.com/erthink/libmdbx

https://api.github.com/repos/erthink/libmdbx
> {
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}

**Comment by jsoref** [comment]
So, it turns out, there's a third possibility, which isn't documented in the page -- the user is gone:
https://api.github.com/users/erthink
```json
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-a-user"
}
```

So,
1. What happens when a user disappears should be documented
2. Ideally, the behavior would match the behaviors for delete repositories....

**Comment by steveward** [comment]
@jsoref thanks for the issue. Cases can exist where a user account has been flagged for a specific reason (i.e. trade compliance, ToS violations, etc.), and as a result returns a 404. The account has not been deleted so the fork network remains but the user's profile is not visible. I'm going to close this out.

**Comment by jsoref** [comment]
@steveward: would it not be reasonable to at least note cases as you've described where the fork root might not be reachable? It seems surprising and it would be much better if the documentation explained with text similar to what you provided here...

"It's possible for a repository that is a fork root to be associated with an account that is currently suspended, as such the account and its repository will be invisible, but the repository won't be deleted and thus won't be removed from the fork network."
