### ISSUE TITLE
Unclear documentation of secrets:inherit

### ISSUE THREAD

**Issue by scottwn** [github/docs#17893]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecretsinherit

### What part(s) of the article would you like to see updated?

The schema `on.workflow_call.secrets.inherit` suggests that `secrets: inherit` should be placed in the _called_ workflow, like this
```
on:
  workflow_call:
    secrets: inherit

jobs:
  my_job:
```

However, the [example](https://github.com/github/docs/pull/17354) present in the doc places `secrets: inherit` in a different hierarchy, specifically `jobs.<job_id>.secrets.inherit`, but this schema is not documented. The documented example should match the hierarchy and clarify where `inherit` should be placed.

**Comment by steveward** [comment]
Thanks for the issue @scottwn, I'll get this triaged for review.

**Comment by lucascosti** [comment]
👋 @scottwn This was noticed internally and recently fixed.

The docs for the correct key at `jobs.<job_id>.secrets.inherit`  are now at: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

Thanks for letting us know about this! 🙇‍♂️
