### ISSUE TITLE
Ambiguous example for `registry_package` workflow trigger

### ISSUE THREAD

**Issue by driimus** [github/docs#17905]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

From https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#registry_package

> For example, you can run a workflow when a package has been `published`.

could be updated to something more descriptive, such as:

>  For example, you can run a workflow when a new package version has been `published`.

It would also be helpful to further elaborate how the action types are triggered here:
- https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#package

### What part(s) of the article would you like to see updated?

Given the description for `action` types of a `registry_package` event:
https://github.com/github/docs/blob/07f59b3aa85b19085290a9ac7dce62c54667b74f/data/reusables/webhooks/package_properties.md?plain=1#L3

And the following example:
https://github.com/github/docs/blob/4263e058437f9ae6c525d2134a04d5ad99df704d/content/actions/using-workflows/events-that-trigger-workflows.md?plain=1#L1022

I would've expected `published` to act as a trigger for a **new** npm registry package being **created**. The use case being running a script only once in a package monorepo for any newly created package.

Instead, the `published` action is dispatched whenever a new version of a package is published, which includes the behavior I would've expected for `updated`. 

At this time I haven't been able to trigger `updated` actions to understand what differentiates it or what scenarios it supports. Perhaps another section of the docs that could be expanded.

**Comment by steveward** [comment]
Thanks for the issue @driimus, I'll get this triaged for review.

**Comment by lucascosti** [comment]
👋 @driimus. Yep, you are correct in your understanding that `published` means any new release of the package. This could be an entirely new package, or any new package version.

Feel free for yourself (or anyone else) to open a PR to clarify the wording 🙂
