### ISSUE TITLE
Create a main entry for `has been retired and cannot be reused`

### ISSUE THREAD

**Issue by jsoref** [github/docs#17913]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

* https://docs.github.com/en/enterprise-server@3.5/admin/github-actions/managing-access-to-actions-from-githubcom/manually-syncing-actions-from-githubcom#about-the-actions-sync-tool
* https://docs.github.com/en/enterprise-server@3.5/admin/github-actions/managing-access-to-actions-from-githubcom/enabling-automatic-access-to-githubcom-actions-using-github-connect#automatic-retirement-of-namespaces-for-actions-accessed-on-githubcom

### What part(s) of the article would you like to see updated?

There should be a page somewhere that explicitly talks about this error case.

It should cover a few items:

* If the retired repository name is only being used for "github pages", you can pick a new repository name, github pages only cares about the `CNAME` file.
* For a personal account, If the repository name corresponds to the account's name, then you should be able to file a ticket with support to get help, since it should be possible to use that name (or github should be able to make some provisions for using a different name, e.g. `.github` ...)
* In general it should explain circumstances under which a repository name is likely permanently dead
* It should explain what to do if a user would like to be able to use the repository name
* It should explain what triggers this

And ideally, the rename/delete dialogs should include a link to this page so that users can be forewarned about the consequences for a rename/delete.

### Additional information

* https://stackoverflow.com/questions/57436425/the-repository-myname-has-been-retired-and-cannot-be-reused
* https://stackoverflow.com/questions/62298084/the-repository-name-has-been-retired-and-cannot-be-reused
* https://solveforum.com/forums/threads/solved-the-repository-myname-has-been-retired-and-cannot-be-reused.694317/
* https://github.community/t/help-my-kid-deleted-my-github-pages-repo/144033
* https://github.community/t/bug-with-renaming-yourself-back/184426/5
* https://github.community/t/the-repository-name-has-been-retired-and-cannot-be-reused/204466
* https://github.community/t/im-getting-this-error-name-has-been-retired-and-cannot-be-reused/238418
* https://github.community/t/after-the-acount-username-changed-the-repository-name-has-been-retired-and-cannot-be-reused/248716
* https://github.community/t/the-repository-tanuj1811-has-been-retired-and-cannot-be-reused/250987
* https://github.community/t/the-repository-qweeznn-has-been-retired-and-cannot-be-reused/251099

**Comment by steveward** [comment]
Thanks @jsoref, I'll get this triaged for review.

**Comment by cmwilson21** [comment]
@jsoref Thanks for opening this issue. It will require conversations with other teams, so I'm going to close this issue and open one internally for team collaboration. Thanks again! ⚡
