### ISSUE TITLE
Add documentation for copying files into a Codespace

### ISSUE THREAD

**Issue by nikmd23** [github/docs#1792]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/developing-in-a-codespace

### What part(s) of the article would you like to see updated?

There's a bunch of good ways to do this, but perhaps adding a section to the document about getting files into the Codespace would be best? This can be accomplished by dragging files from the local file system, into VS Code's (web or desktop) File Explorer. 

### Additional information

This issue was originally opened at https://github.com/MicrosoftDocs/vscodespaces/issues/660

**Comment by janiceilene** [comment]
Thanks for opening an issue @nikmd23! I'll triage this for the team to take a look 👀

**Comment by mehdi-miner** [comment]
);
The hope of this address

**Comment by trangngo1801** [comment]
> Cảm ơn bạn đã mở vấn đề này. Một thành viên trong nhóm tài liệu GitHub nên sớm đưa ra phản hồi. Trong thời gian chờ đợi, vui lòng xem các [nguyên tắc đóng góp](https://github.com/github/docs/blob/main/CONTRIBUTING.md) .

**Comment by F22038299** [comment]
Bon bagay

**Comment by janiceilene** [comment]
Thanks so much for the feedback @nikmd23! I've passed your suggestion onto the team to consider the next time we're updating those docs ⚡

**Comment by mehdi-miner** [comment]
Aaaaa
