### ISSUE TITLE
Theme instructions display incorrectly

### ISSUE THREAD

**Issue by davaya** [github/docs#17941]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll

### What part(s) of the article would you like to see updated?

The css content of the above page is displayed as:
```
---
---

@import "";
```
which doesn't work.

The source for that page https://github.com/github/docs/blob/main/content/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll.md is correct:
```
---
---

@import "{{ site.theme }}";
```
but the site.theme is getting lost and presumably needs to be escaped to display correctly.

**Comment by steveward** [comment]
Thanks so much for opening this issue @davaya. You or anyone else can open a PR with a fix.

**Comment by khin1988htayi** [comment]
@steveward

**Comment by janbrasna** [comment]
Thanks for spotting this @davaya! Fix is ready #17979 (incl. previews so you can check the result is as expected)
