### ISSUE TITLE
Wrong "Repository permission levels for an organization"

### ISSUE THREAD

**Issue by curquiza** [github/docs#1795]
Unlike [this page](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) mentions, the maintainer permissions do not allow to:
- Enable wikis and restrict wiki editors
- Enable project boards
- Configure pull request merges
- Configure a publishing source for GitHub Pages
- Limit interactions in a repository

Because all those settings are accessible from the `Settings` tab that is only accessible when you are Admin, and not Maintainer.

But I might miss something!

I can make a PR if you want 😄

**Comment by hubwriter** [comment]
Hi @curquiza - Thanks for raising this issue.

I believe the documentation is currently correct. I checked this on github.com. Signing in as a user who has the "Maintain" role for a public repo in an organization on github.com I'm able to see the Settings tab and, from there, perform all of the activities you list.

Please come back with more information or questions if you want to discuss this. I'll leave this open for a few days and, if I don't hear back, I'll close this.

Thanks again for participating. 👍

**Comment by curquiza** [comment]
Hello! Thanks for this quick answer!!

I opened this issue because I had an issue with a Maintainer account that would not able to access these kinds of settings! I will retry asap then!

**Comment by curquiza** [comment]
I've just re-tried, it works now, sorry about the inconvenience, closing the issue then!
And thanks again for your reactivity!!
