### ISSUE TITLE
Misleading description for the `repository` field in the `push` webhook event

### ISSUE THREAD

**Issue by crqra** [github/docs#17960]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push

### What part(s) of the article would you like to see updated?

In the [Webhook payload object](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-38) for the [`push` event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push), the `repository` field has the following description:

> The [repository](https://docs.github.com/en/rest/reference/repos#get-a-repository) where the event occurred.

#### Why should the docs be changed?

Clicking on the repository link presented in the description, redirects the user to a page with the Repository object schema, that has a `organization` property with the following schema:

```json
{
  "anyOf": [
    {
      "type": "null"
    },
    {
      "title": "Simple User",
      "description": "Simple User",
      "type": "object",
      ...
    }
  ]
}
```

However, the `organization` property in the `repository` field of the `push` webhook event does not follow the same schema, as it returns a plain string instead of an object, which is undocumented in the referred repository schema.

This is misleading since people integrating with GitHub Webhooks might think that the `repository` in the payload is just like the same as in any other webhook event that has the same field only to find out it's not when deserializing the payload.

#### Expected Outcome

The link in the description referred above should redirect the user to a page with the exact schema of a Repository for that particular event.

---

Ideally I believe every webhook event with the same fields should return the same types. I'm not sure if this isn't actually a "bug" in the payload itself. Would appreciate if someone could point me to where I can report this behavior, please.

### Additional information

Please, let me know if any further details are required or if this isn't the best place for this issue.

Thanks in advance! :octocat:

**Comment by steveward** [comment]
Thanks for the issue @crqra! I'll get this triaged for review.

**Comment by skedwards88** [comment]
Thanks for flagging this! You are right: the documentation is incorrect, and the organization object is returned at the top level, not as part of the `repository` property. We are working on a fix internally, so I'm going to close this issue out.

**Comment by crqra** [comment]
Thanks @skedwards88!
