### ISSUE TITLE
Add reason to unverify work mail in mailing best practices

### ISSUE THREAD

**Issue by pixelbrackets** [github/docs#17991]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/best-practices-for-leaving-your-company

### What part(s) of the article would you like to see updated?

Best practice part about changing mail addresses

> Before you leave your company, make sure you update the following information in your personal account:
> […] Remove your work mail, add it again, but not verify it

### Why

Explain the reason why it is a good thing to remove the verified work mail address and then add it again without verifying it. → Unverified email addresses cannot receive further notifications or be used to reset your password.

Otherwise the reader asks himself „Why should I do this step? This seems superfluous.“.

**Comment by pixelbrackets** [comment]
Hey, to me this is no a reason to actually do this step as a user. I can keep my associated commits when I let the mail address stay verified. 
The actual reason why these steps make sense is the one you linked in the email settings page -> don't get any notifications or let somebody at work reset your password. In *addition* this workflow also still keeps the commits. 
At least this was a reason for me, while going trough this process.

**Comment by janiceilene** [comment]
Thanks @pixelbrackets I've talked with the team about the issue and the associated PR. We've decided not to make the suggested changes. If a person no longer works at a company, they won't be able to verify an email address because they wouldn't have access to the email account anymore.

Thanks so much for your interest and passion in improving the GitHub docs!
