### ISSUE TITLE
`Fields` for `ProjectV2Owner` looks wrong

### ISSUE THREAD

**Issue by jsoref** [github/docs#18008]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/reference/interfaces#projectv2owner

### What part(s) of the article would you like to see updated?

> <div style="box-sizing: border-box; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box;"><h2 id="projectv2owner" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-weight: 600; font-size: 1.5em; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); padding-top: 1rem; scroll-margin-top: 75px;">ProjectV2Owner</h2><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px;">Represents an owner of a project (beta).</p></div><div style="box-sizing: border-box;"><h4 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-weight: 600; font-size: 1em; line-height: 1.25; padding-top: 1rem;">Implemented by</h4><ul style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px;"><li style="box-sizing: border-box;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;"><a href="https://docs.github.com/en/graphql/reference/objects#issue" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: underline; text-underline-offset: 25%;">Issue</a></code></li><li style="box-sizing: border-box; margin-top: 0.25em;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;"><a href="https://docs.github.com/en/graphql/reference/objects#organization" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: underline; text-underline-offset: 25%;">Organization</a></code></li><li style="box-sizing: border-box; margin-top: 0.25em;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;"><a href="https://docs.github.com/en/graphql/reference/objects#pullrequest" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: underline; text-underline-offset: 25%;">PullRequest</a></code></li><li style="box-sizing: border-box; margin-top: 0.25em;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;"><a href="https://docs.github.com/en/graphql/reference/objects#user" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: underline; text-underline-offset: 25%;">User</a></code></li></ul><h4 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-weight: 600; font-size: 1em; line-height: 1.25; padding-top: 1rem;">Fields</h4>
>
> Name      Description
<img width="733" alt="image" src="https://user-images.githubusercontent.com/2119212/169357716-159e70e9-f819-4ddf-bc19-e50c55c64b01.png">

The `Name                Description` bit looks odd
- It looks like a rendering glitch
- I suppose I was expecting to see some items, or if no items at least some sort of explanation that there are no items

**Comment by steveward** [comment]
Thanks @jsoref, I'll get this triaged for review.
