### ISSUE TITLE
`GitHub Docs isn't available right now. Our team is on the case.`

### ISSUE THREAD

**Issue by jsoref** [github/docs#18045]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All

### What changes are you suggesting?

1. Decrease the frequency that this message is shown:
    ![image](https://user-images.githubusercontent.com/2119212/169575039-3697e62e-1047-4973-a47c-b69e81068fc2.png)

2. Change the message
    GitHub docs *are* available, that specific page might not be, but reloading it probably will fix the problem.

    So:
    > We're sorry, GitHub Docs couldn't load _this page right now_, you could try reloading or try back later. If the problem persists, consider filing an issue and referencing `<x-github-request-id>`.

### Additional information

I've started seeing this message quite regularly in the past two or so weeks. Reloading a page typically resolves the issue, but it's pretty frustrating.

**Comment by Rjcm19888888** [comment]
#18045

**Comment by janiceilene** [comment]
👋 @jsoref Thanks so much for opening this issue! I chatted with the team and it led to a great conversation about how often/why users have been seeing this message a bit more often. We didn't update the page at all, but did push out some changes that will hopefully mean you won't see this page nearly as often anymore 🤞 

I'm going to close this out now, but definitely let us know if you're still seeing the page a bunch 💖
