### ISSUE TITLE
Linking Issue [https://github.com/github/docs/pull/1807]

### ISSUE THREAD

**Issue by I-Cat** [github/docs#1808]
<--
HUBBERS BEWARE! THE GITHUB/DOCS REPO IS PUBLIC TO THE ENTIRE INTERNET. OPEN AN ISSUE IN GITHUB/DOCS-CONTENT INSTEAD.
-->

<--
For questions, ask in Discussions: https://github.com/github/docs/discussions

Before you file an issue read the:
+ [x] = Code of Conduct: https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md

+ [x] = Contributing guide: https://github.com/github/docs/blob/main/CONTRIBUTING.md

Check to make sure someone hasn't already opened a similar issue: https://github.com/github/docs/issues
-->

### What article on docs.github.com is affected?

PR https://github.com/github/docs/pull/1807

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
