### ISSUE TITLE
Clarify YAML config for automated release notes

### ISSUE THREAD

**Issue by katelovescode** [github/docs#18155]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)

### What part(s) of the article would you like to see updated?

Examples of the YAML configuration when trying to exclude labels from categories.  My use case is that we don't label PRs, but dependabot does.  When we generate release notes, I'd really love to see our feature updates before the dependabot labels, but it took me a long time to figure out how to configure the exclude key in the YAML to display my non-labeled Features first.

**Comment by Makosah30** [comment]
This will be failure system interface it may depend on the worker who is operating the system the person should be time and understand what he or she is doing try this and I hope this is going to solve the problem
