### ISSUE TITLE
Some problem with Pages Quickstart docs

### ISSUE THREAD

**Issue by gingerhot** [github/docs#18165]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/quickstart

### What part(s) of the article would you like to see updated?

The repository name and owner in step 2 are not consistent with those in step 3. That would be confused for some users.

<img width="762" alt="WX20220524-110052@2x" src="https://user-images.githubusercontent.com/1658618/169940728-234f47d7-6699-45df-ae12-f457efa48001.png">

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @gingerhot! That could be confusing 💛 You or anyone else are welcome to open a PR with a fix ⚡
