### ISSUE TITLE
Searching for `api.github.com/meta` doesn't work

### ISSUE THREAD

**Issue by jsoref** [github/docs#18180]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/meta

### What changes are you suggesting?

This search should work:
https://docs.github.com/en/rest/meta?query=api.github.com%2Fmeta
<img width="770" alt="image" src="https://user-images.githubusercontent.com/2119212/170068874-4b072dc4-250a-4441-8411-760d75aa3e32.png">

> Search results for: api.github.com/meta
Matches displayed: No results found

Specifically, it should at least find https://docs.github.com/en/rest/meta

Also, ideally this fairly non-sensical search should also work (it's basically searching for itself):
https://docs.github.com/en/rest/meta?query=https%3A%2F%2Fdocs.github.com%2Fen%2Frest%2Fmeta
<img width="769" alt="image" src="https://user-images.githubusercontent.com/2119212/170068745-05159ccc-33d8-4bec-8179-baef720b22e1.png">
> An error occurred trying to perform the search.

Specifically, it should find https://docs.github.com/en/rest/meta

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @jsoref! That is some really weird search behavior. I'll triage this for the team to take a look.

**Comment by peterbe** [comment]
The reason why any search with `:` fails is a known bug. It's related to how we use `Lunr` to do the search. (The search engine only expects `:` to be used when specifying topics like `topics:API` and so anything outside of that becomes an error)

But what you're ultimately proposing is that typing in a URL should find the page that has that URL. I'm not sure yet. What if there's a code example that mentions the URL? It feels like the ideal would be a bit of both. If the URL is a valid self-URL, we display it as the first search result. And if there are other documents that mention that as a URL, in the content, they show up too.

**Comment by jsoref** [comment]
Re: `Lunr`, cute. I'd hope you could at least preprocess to strip out `http:` and `https:`, that'd at least prevent normal users from tripping over it.

> But what you're ultimately proposing is that typing in a URL should find the page that has that URL. I'm not sure yet. What if there's a code example that mentions the URL? It feels like the ideal would be a bit of both.

Yes, sorry, **both**. I'm not saying _not to search for the url_. Definitely do that. But also show the page itself. 

> If the URL is a valid self-URL, we display it as the first search result. And if there are other documents that mention that as a URL, in the content, they show up too.

👍 

I'm constantly amused by the number of people who will search for things like `gmail` or `google`. (I saw a couple of people of various technical levels doing that this week).

**Comment by peterbe** [comment]
One thing I'm interested in keep an eye on is to include the URL path as part of the searchable text. For example, if you search for `meta foobar` it should give a slight leg up to matches on `/en/rest/meta` if that page also contains the word `foobar` compared to a page that *only* contains the word `foobar`. Thanks for the idea!

**Comment by cmwilson21** [comment]
Looks like these suggestions are being tracked internally. I will go ahead and close this issue. Thanks ✨
