### ISSUE TITLE
Talk about closing issues as completed

### ISSUE THREAD

**Issue by jsoref** [github/docs#18188]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/tracking-your-work-with-issues

### What part(s) of the article would you like to see updated?

A page to talk about closing issues in general (and probably about reopening them)

### Additional information

I've looked through the docs and can't find anything that talks about closed state: https://cs.github.com/?q=reason+closed+repo%3Agithub%2Fdocs

https://github.com/search/advanced#search_state_reason
<img width="383" alt="image" src="https://user-images.githubusercontent.com/2119212/170101420-b6c596c2-6c1d-4089-ada4-dc731ee540ff.png">

It'd be nice to have some sense of what `not planned` is and how to move something into this state, or similarly `completed`.

It turns out that this is available via a drop down in issues:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/2119212/170101686-1e9aa029-d20b-453d-9352-3c97c4868568.png">

But, I should be able to read documentation about this.

Searching the docs differently:
https://docs.github.com/en?query=%22close+as+not+planned%22

<img width="734" alt="image" src="https://user-images.githubusercontent.com/2119212/170101907-c153d895-4d1e-4d24-bbf0-0828643d859f.png">

I can see a way to use a bot to close issues:
https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

But, that's pretty advanced and skips the basics.

Note that there is a page for closing pull requests: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/closing-a-pull-request

**Comment by janiceilene** [comment]
@jsoref Thanks for opening an issue! I'll triage this for the team to take a look 💖

**Comment by felicitymay** [comment]
@jsoref - clearly great minds think alike. I've just reviewed a content design plan for a writer at GitHub who is working on adding a new article on closing issues to the docs ✨ 

I'll add a comment to our internal notes so that they can take a look at the context you've added here 😄
