### ISSUE TITLE
Explain that it's possible to see files from before a git-blame-ignore-revs change

### ISSUE THREAD

**Issue by jsoref** [github/docs#18195]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file

### What part(s) of the article would you like to see updated?

Users don't naturally understand how to see past a .git-blame-ignore-revs file:
https://github.com/github/feedback/discussions/5033#discussioncomment-2333741

It is possible to do it.

The steps are basically:
Open `/tree/<current-sha>` and browse to `.git-blame-ignore-revs` and click `History` to find the shas that applied layers (or you could use `Blame` to find the `<sha>` that introduced things to ignore that you don't want to ignore).

Then use `<that-sha>~` as the sha for the blame for the file that you want to view w/o the ignore rule.

**Comment by janiceilene** [comment]
@jsoref Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by lecoursen** [comment]
Thanks @jsoref, I agree that we could add this explanation to that article. You or anyone else is welcome to open a PR doing so!
