### ISSUE TITLE
JavaScript code samples in "Add labels to an issue" are wrong

### ISSUE THREAD

**Issue by jilgue** [github/docs#18208]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/issues/labels#add-labels-to-an-issue

### What part(s) of the article would you like to see updated?

The fields `owner`, `repo` and `issue_number` in the code example  are not needed.
```
// Octokit.js
// https://github.com/octokit/core.js#readme
const octokit = new Octokit({
  auth: 'personal-access-token123'
})

await octokit.request('POST /repos/{owner}/{repo}/issues/{issue_number}/labels', {
  owner: 'OWNER',
  repo: 'REPO',
  issue_number: 'ISSUE_NUMBER',
  labels: [
    'bug',
    'enhancement'
  ]
})
```

### Additional information

If you use the code sample
```
// Octokit.js
// https://github.com/octokit/core.js#readme
const octokit = new Octokit({
  auth: 'personal-access-token123'
})

await octokit.request('POST /repos/{owner}/{repo}/issues/{issue_number}/labels', {
  owner: 'OWNER',
  repo: 'REPO',
  issue_number: 'ISSUE_NUMBER',
  labels: [
    'bug',
    'enhancement'
  ]
})
```

it respond this error message:
```
message: 'Invalid request.\n' +
        '\n' +
        'No subschema in "anyOf" matched.\n' +
        `For 'anyOf/0', {"owner"=>"ThingsO2", "repo"=>"monom-manifests", "issue_number"=>"5", "labels"=>["micro-dos"]} is not an array.\n` +
        `For 'anyOf/1', {"owner"=>"ThingsO2", "repo"=>"monom-manifests", "issue_number"=>"5", "labels"=>["micro-dos"]} is not an array.\n` +
        '"issue_number", "owner", "repo" are not permitted keys.',
```

The fields `owner`, `repo` and `issue_number` have to be deleted for code works.

**Comment by janiceilene** [comment]
👋 @jilgue Thanks so much for opening an issue! I've chatted with the team and the example is correct. You can see more details in this [comment](https://github.com/github/docs/issues/17265#issuecomment-1129376182). I'm going to close issue 💛 

Thanks for your interest in improving the GitHub Docs ⚡
