### ISSUE TITLE
Docs on expressions with extra conditions not clear

### ISSUE THREAD

**Issue by alexbrazier** [github/docs#18269]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#failure

### What part(s) of the article would you like to see updated?

The docs mention how to use `failure()` to catch failing jobs and then goes on to say it's the same as `job.status == 'failure'` or `github.action_status == 'failure'`, however from my testing this isn't true.

Using either of the above fail to run after a failing job, e.g.

```yml
steps:
  - name: Fail demo
     run: exit 1
  - name: The job has failed
    if: ${{ job.status == 'failure' }}

```

The docs suggest `The job has failed` is meant to run here, but from my testing it doesn't. Not sure if this is a bug with github actions or the docs are just wrong or if I'm just missing something.

I think these broken examples should be removed and a practical example showing how to catch a specific failing job rather than all jobs would be useful here.

**Comment by Aloii88** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by albertoEnstein** [comment]
Open
