### ISSUE TITLE
Unclear text on Workflow syntax page

### ISSUE THREAD

**Issue by gsrohde** [github/docs#18298]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idname

### What part(s) of the article would you like to see updated?

There is a typo in the (single) sentence of this section, though it is not entirely clear what this sentence _should_ say:

> Use `jobs.<job_id>.name` to a name for the job, which is displayed on GitHub.

**Comment by cmwilson21** [comment]
@gsrohde Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by martin389** [comment]
Thanks for spotting this. I think it can be clarified to say: "[...] to set a name for the job, which is displayed in the GitHub UI."
