### ISSUE TITLE
CODEOWNERS doesn't talk about forks

### ISSUE THREAD

**Issue by jsoref** [github/docs#18353]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What part(s) of the article would you like to see updated?

There should be text that talks about how `CODEOWNERS` interacts w/ forks.

### Additional information

I have a forked repository, and I'm pulling in an upstream commit that includes `CODEOWNERS`, and it isn't remotely clear what will happen if I do this.

---
[maintainer edit]
Content plan [here](https://github.com/github/docs/issues/18353#issuecomment-1295229697)

**Comment by cmwilson21** [comment]
@jsoref Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Athayde3586** [comment]
There is no co owners there is only one owner

**Comment by Athayde3586** [comment]
And that is me

**Comment by dylanjha** [comment]
Did anyone figure this out? Wondering the same thing

**Comment by cmwilson21** [comment]
@dylanjha Thanks for checking in! This issue is up on the board and waiting for review. Someone will take a look at it soon 👀

**Comment by 07961596451nhjj** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> 
> ### What part(s) of the article would you like to see updated?
> 
> There should be text that talks about how `CODEOWNERS` interacts w/ forks.
> 
> ### Additional information
> 
> I have a forked repository, and I'm pulling in an upstream commit that includes `CODEOWNERS`, and it isn't remotely clear what will happen if I do this.

[](https://github.com/07961596451nhjj/explore/tree/main)

**Comment by 07961596451nhjj** [comment]
> > ### Code of Conduct
> > 
> > - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> > 
> > ### What article on docs.github.com is affected?
> > 
> > https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> > 
> > ### What part(s) of the article would you like to see updated?
> > 
> > There should be text that talks about how `CODEOWNERS` interacts w/ forks.
> > 
> > ### Additional information
> > 
> > I have a forked repository, and I'm pulling in an upstream commit that includes `CODEOWNERS`, and it isn't remotely clear what will happen if I do this.
> 
> [](https://github.com/07961596451nhjj/explore/tree/main)

**Comment by skedwards88** [comment]
Thanks for this suggestion! Below are some details about how CODEOWNERs interacts with forks. You or anyone else is welcome to open a pull request to document this info.

CODEOWNERS has two primary uses:
- It is used for triggering review requests for a pull request that modifies an owned file.
- It is used to see at a glance who is responsible for a given file.

Pull requests use the version of CODEOWNERS from the base branch of the pull request. (The base branch is the branch that the PR will modify if the PR is merged.) If the repo that you forked _from_ is the base of your PR, then the PR will use the CODEOWNERS file from the repo that you forked from. If your PR is targeting a branch _within_ your forked repo, then the PR will use the CODEOWNERS on that base branch in your forked repo.

When seeing who responsible for a file, the CODEOWNERS for whatever branch you're looking at on whatever repo you're looking at is used:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/25328854/198689796-bee8fbf2-b68b-468b-a506-f3eb0471908f.png">

**Comment by jsoref** [comment]
> The people you choose as code owners must have write permissions for the repository. When the code owner is a team, that team must be visible and it must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

It feels like it's worth noting something like: "in a fork, the accounts referenced in the upstream file which is the current version in the fork are unlikely to have these permissions, and thus are unlikely to be assigned, but if they have these permissions, then they would be."

**Comment by jsoref** [comment]
Maybe I'll look into picking this up in part...

**Comment by jsoref** [comment]
Sigh, there's an active PR

**Comment by jsoref** [comment]
Is it bad that I only now noticed that `because` is misspelled in the note?
