### ISSUE TITLE
Incorrect PowerShell Module Locations

### ISSUE THREAD

**Issue by tomas-pajurek** [github/docs#18377]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell

### What part(s) of the article would you like to see updated?

In [PowerShell Module Locations](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell#powershell-module-locations), there is an error in the table. 

The location for `PowerShell add-on modules / Ubuntu` is invalid: `/usr/local/share/powershell/Modules/*`.

The modules are located under `/usr/share/` in the subfolder `az_<version>`, e.g. `/usr/share/az_7.3.2`.

**Comment by cmwilson21** [comment]
@tomas-pajurek Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
👋  @tomas-pajurek, thanks for opening this issue. It looks like there are some modules present at the location currently documented (`/usr/local/share/powershell/Modules/*`), but the Azure modules do appear to be in the location you specified (/usr/share/az_<version>).

I'll try to get someone from the infrastructure team to clarify if this affects the other GitHub-hosted runner OSs too.

**Comment by SiaraMist** [comment]
Hi @tomas-pajurek, thank you for opening this issue!

It looks like the Azure modules are in the location you pointed out on Ubuntu runners, and other OS's are not impacted. For context, it is done this way to support the [AzurePowerShell task](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzurePowerShellV5/Utility.ps1#L9).

I think for this, we could add a note under the table to call this out, somethings similar to:

```
{% note %}

**Note**: On Ubuntu runners, Azure PowerShell modules are stored in `/usr/share`.

{% endnote %}
```

You, or anyone else, is welcome to open a PR to address this.

**Comment by alexis-opolka** [comment]
Hi,
Is it okay if I do it?

**Comment by SiaraMist** [comment]
@alexis-opolka Yes! Feel free to assign yourself this issue and open a PR. 🙂

**Comment by alexis-opolka** [comment]
@SiaraMist I don't have the rights to assign myself this issue but I'll be sure to open a PR. ^-^
