### ISSUE TITLE
Add example for mongo service in actions 

### ISSUE THREAD

**Issue by hannanel100** [github/docs#18392]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-containerized-services/about-service-containers

### What part(s) of the article would you like to see updated?

There should be another section after the postgresql example according to this: https://github.com/actions/example-services/tree/main/mongodb

**Comment by cmwilson21** [comment]
@hannanel100 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by myarb** [comment]
@hannanel100 Thanks so much for opening an issue! I've spoken with the team and we're not going to add any additional examples at this time :yellow_heart:

Thank you for your interest and passion in improving the GitHub Docs!
