### ISSUE TITLE
spelling Mistake of components on docs/stylesheets/README.md file

### ISSUE THREAD

**Issue by bishal7679** [github/docs#18437]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/tree/main/stylesheets

![Screenshot (104)](https://user-images.githubusercontent.com/70086051/172041760-05458c5b-af17-4456-b0df-b34d2eec271c.png)

### What part(s) of the article would you like to see updated?

spelling of compnents will be changed into components.

**Comment by bishal7679** [comment]
Can I make a PR for this issue?

**Comment by cmwilson21** [comment]
@bishal7679 Thanks so much for opening an issue!  :zap:

You or anyone else is welcome to open a PR with the fix.
