### ISSUE TITLE
In CodeSpaces docs include Twingate as an option for private network access

### ISSUE THREAD

**Issue by emrul** [github/docs#18474]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[https://docs.github.com/en/codespaces/developing-in-codespaces/connecting-to-a-private-network](https://docs.github.com/en/codespaces/developing-in-codespaces/connecting-to-a-private-network)

### What part(s) of the article would you like to see updated?

The page mentions third-party options for private network access and the list only includes Tailscale currently.  I recently published a GitHub repository showing how Twingate could work with Codespaces to allow Codespace users to access private resources hosted within Twingate.

I'm hoping that by adding Twingate to the list of options we can expand the options available to users for accessing private resources in a secure way.

**Comment by hubwriter** [comment]
@emrul - Many thanks for raising this issue.

Can you provide some more information please? 

> I recently published a GitHub repository showing how Twingate could work with Codespaces to allow Codespace users to access private resources hosted within Twingate.

Please provide a link to the documentation you're proposing linking to. If this is a page similar to [the page for Tailscale](https://tailscale.com/kb/1160/github-codespaces/) then this might be something it would be useful to link to.

Thanks again 👍

**Comment by emrul** [comment]
@hubwriter thanks for reaching out! I made a PR [here](https://github.com/github/docs/pull/18475#issuecomment-1151346936) that was closed without much detail and I asked for some feedback but didn't hear back.

We can certainly add a page on our docs site similar to the Tailscale page, let me go do that. Any other suggestions you'd like us to incorporate for this?

**Comment by hubwriter** [comment]
@emrul - Thanks for getting back about this. I didn't spot the PR 🤦 

I'll dig into this a little more and get back to you about this here.

**Comment by emrul** [comment]
Amazing!! Thanks @hubwriter, this is greatly appreciated. Will wait on an update 🤞🏽

**Comment by hubwriter** [comment]
@emrul - I've heard back from product management on this. That article is on the radar for an update, based on some work we've been doing in that area. We previously added the link to Tailscale after testing that solution internally here. We haven't done equivalent testing for Twingate. That's not to say that we wouldn't do that and add a link in future. However, at the moment, it's not clear whether links to third-party solutions will remain in that article once it's revised.

I hope this answer isn't too disappointing. Many thanks again for suggesting this and raising a PR.

**Comment by emrul** [comment]
@hubwriter - I really appreciate you taking the time to dig in and explain the situation to us.  Your answer is not disappointing and much appreciated in fact.

For what its worth, my perspective is that any tooling that can help users get more from GitHub should always be welcome in docs (I say this as a GitHub user, your docs are pretty great!).  Either way we'd love for you to test out Twingate internally and if third-party solutions do have a future on your docs site we'd love to work with you to get Twingate included - I'll keep an eye, but also please feel free to reach out.

Many thanks and take care!
