### ISSUE TITLE
`noreply` / `no-reply` consistency in email settings

### ISSUE THREAD

**Issue by DaveyJH** [github/docs#18528]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Setting your commit email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address)

### What part(s) of the article would you like to see updated?

Very minor and rather pedantic, but the `noreply` email address is referenced
as both:

- `noreply`
- `no-reply`

Example:  
![Example of both no-reply instances in one paragraph](https://user-images.githubusercontent.com/80708826/173001119-f8003f49-b0cd-440c-8c74-b34e352f9dbd.png)

I would like to remove the `-` in all instances. The email address that will be
provided does not contain `-` and so I believe it is incorrect to display
`no-reply`. Grammatically, it may be more correct so perhaps the first instance
could reference it in some way, i.e.:

> If you'd like to keep your personal email address private, you can use a
> no-reply (`noreply`) email address from GitHub...

As the other docs I have viewed do not make this distinction I believe it is
probably unnecessary to implement the pseudo-quoted text. My view is that
`noreply` is more appropriate considering the usage and there is a very small
chance that a user could use the wrong format in their config and/or
communications.

### Additional information

I have had a look at the relevant files and believe I would need to edit the
[doc itself](https://github.com/github/docs/blob/main/content/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address.md) as well as the [reusable user-setting](https://github.com/github/docs/blob/main/data/reusables/user-settings/set_your_email_address_in_git.md).
I would be interested to know if there is a quick way to find if that reusable
is used anywhere else as I would be happy to check for any other instances
within the docs that also could be changed. A pointer to any resources or a
direct answer regarding this would be much appreciated but not expected.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @DaveyJH! I agree that since the provided email address includes `noreply` without the `-` that it makes the most sense not to include it in this article. You're welcome to open a PR 💖 

For the reusable, I'd generally open my editor and do a search for `{% data reusables.user-settings.set_your_email_address_in_git %}`, that should bring up all the articles that also use this reusable. Thank you so much for thinking through a holistic, docs wide change!

**Comment by DaveyJH** [comment]
Thanks @janiceilene. Reading the second paragraph of your comment gave me an overwhelming sense of stupidity! I had been looking through the files on GitHub rather than in my editor - thanks for reminding me not to do that too often! 😅

It appears the reusable only appears in the one file; there is another, larger reusable that contains `noreply` as expected.

I have made a second branch that contains a further holistic edit but it doesn't quite stay within the scope of this issue. Also...I forgot to press `comment` when I wrote the first two paragraphs. I was clearly having a great day 😆

**Comment by janiceilene** [comment]
> I had been looking through the files on GitHub rather than in my editor - thanks for reminding me not to do that too often! 

I've done this so, so many times 🙈 

I've triaged your PR, but it may take us a while to review, as we've got lots of folks out for holidays over the next month 💛

**Comment by DaveyJH** [comment]
> I've done this so, so many times 🙈
I feel better knowing I am not alone in!

Should I raise a second issue for the continuation of the changes? (not specific to [Setting your commit email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address)) - you may have guessed I am fairly new into the industry and trying to develop good practices from the start rather than correcting poor ones later down the line 🤪

**Comment by janiceilene** [comment]
@DaveyJH Welcome to open source and thanks for spending some of your learning time with us 💖 

You're welcome to just open a second PR with more fixes, since it's a continuation of this same issue and not an entirely new topic/area of the docs.
