### ISSUE TITLE
`on.pull_request`: Document the default behavior of `pull_request` without any filters

### ISSUE THREAD

**Issue by PythonCoderAS** [github/docs#18551]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

`docs/content/actions/using-workflows/workflow-syntax-for-github-actions.md`
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore

### What part(s) of the article would you like to see updated?

I am trying to contribute to a repository that has a workflow file defined as such:

```yaml
name: test
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
...
```

However, it is not running for the PRs I contributed, nor is the "first-time contributor" notice showing up. I was investigating the documentation to find out if using `pull_request:` without specifying any branches defaulted to all branches or no branches, but the docs are unclear.

**Comment by janiceilene** [comment]
👋 @PythonCoderAS Thanks for opening an issue! The best place to get clarity about the workflow syntax is from our awesome [support team](https://support.github.com/contact). After that, if it looks like we should make an update to the docs, feel free to come back and comment in this issue or open a new one 💛 

Thank so so much for your interest in improving the GitHub Docs!
