### ISSUE TITLE
Broken Link in Learn GitHub Actions > Managing complex workflows

### ISSUE THREAD

**Issue by FabienSalles** [github/docs#1856]
### What is the current behavior?

In [Managing complex workflows](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows), there is a broken link for "Using databases and service containers."

### What changes are you suggesting?

I'm not sure where the link should go, may be [About service containers](https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers) ?

**Comment by janiceilene** [comment]
👋 @FabienSalles Thanks for opening an issue! In the section, [Using databases and service containers](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-databases-and-service-containers) of the article "Managing complex workflows," I see

> For more information, see "Using databases and service containers."

"Using databases and service containers" links to https://docs.github.com/en/free-pro-team@latest/actions/guides, which is working for me in both available versions of the article.

Are you looking at a different link or is that the one that isn't working for you?

**Comment by FabienSalles** [comment]
Thanks for your response. 

I expected to land on a specific page dealing only with the link title (like the other links on the page).
When, I saw this page I thought the landing page was no longer existing and I was redirected to a higher page.

I see now that the content at the end of the page corresponds to the link title. May be an anchor to "#using-service-containers-in-a-workflow" would be a little better ?

**Comment by janiceilene** [comment]
👍 Ah, I totally understand that confusion now! Let me triage this for the right team to take a look at and help figure out the best place to link to 👀

**Comment by runleonarun** [comment]
@FabienSalles It looks like we fixed this internally! Thank you for filing this issue 🙇

**Comment by FabienSalles** [comment]
Thanks for your times :)
