### ISSUE TITLE
"the" is misplaced in this sentence "It detects changes to files the in the translations folder "

### ISSUE THREAD

**Issue by bishal7679** [github/docs#18573]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/script/README.md
![Screenshot (122)](https://user-images.githubusercontent.com/70086051/173245438-92a0db08-8cc6-4940-992d-56f7093c0d7f.png)

### What part(s) of the article would you like to see updated?

This sentence should be - 
`It detects changes to the files  in the translations folder`

**Comment by janiceilene** [comment]
Thanks for opening an issue @bishal7679! You or anyone else are welcome to open a PR to fix this typo 💖

**Comment by bishal7679** [comment]
@janiceilene why it is showing not accepted in deployment time of my PR. You have approved this issue.

**Comment by janiceilene** [comment]
@bishal7679 I just tweaked the syntax in the OP of your PR so they're linked now! Thanks for opening that ✨

**Comment by bishal7679** [comment]
@janiceilene docs-engineering team will accept this changes?
