### ISSUE TITLE
Specify a page that will actually have user settings accessible in the top righthand corner

### ISSUE THREAD

**Issue by hamirmahal** [github/docs#18657]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

### What part(s) of the article would you like to see updated?

I saw `data/reusables/user-settings/access_settings.md` at https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-token.

That article said,
> In the upper-right corner of **any** page, click your profile photo, then click Settings.

The page that article was on did not have a user icon in the top righthand corner.

The end result is that it should be easier for readers to access their user settings to create a personal access token, or PAT, by directly linking to a page that will actually have those settings readily accessible.

### Additional information

![image](https://user-images.githubusercontent.com/43425812/173939675-fa447697-fc61-4910-8fff-8d681b268b91.png)

**Comment by janiceilene** [comment]
👋 @hamirmahal Thanks for opening an issue! We use this reusable on many, many pages throughout the docs. Since your profile photo is visible in the top right hand corner of any page on GitHub, we're not going to add a link at this time.
