### ISSUE TITLE
Code samples uses token as authentication method instead of Basic Authentication

### ISSUE THREAD

**Issue by joonvena** [github/docs#18665]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/apps/oauth-applications

### What changes are you suggesting?

As the linked docs page states:
You must use [Basic Authentication](https://docs.github.com/rest/overview/other-authentication-methods#basic-authentication) when accessing this endpoint, using the OAuth application's client_id and client_secret as the username and password

Now code examples uses the token instead of Basic Authentication.

**Comment by janiceilene** [comment]
@joonvena Thanks so much for opening an issue! I'll get this triaged for review ✨

**Comment by cmwilson21** [comment]
@joonvena updates to our REST API content have to be made internally. I've transferred this for internal review, so will close this issue out now. 

Thanks for your passion and interest in improving GitHub docs! 💛
