### ISSUE TITLE
Typo in japanese content of Enabling debug logging

### ISSUE THREAD

**Issue by yuki-js** [github/docs#18703]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ja/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging

### What part(s) of the article would you like to see updated?

There is a typo in the Japanese version of Enabling debug logging.

In section "ステップのデバッグロギングの有効化",  "酢鉄粉デバッグロギング" should be "ステップデバッグロギング".

### Additional information

Here is the point of typo.
![image](https://user-images.githubusercontent.com/20838151/174435193-6a7eb87b-14b8-4d38-af78-8d5b0f24e034.png)

English content is:
![image](https://user-images.githubusercontent.com/20838151/174435221-09cfe06c-1112-4272-8d10-8b7c16281e4a.png)

**Comment by janiceilene** [comment]
Thanks for opening an issue! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

I've opened an internal issue to let our translators know about the typo 💛
