### ISSUE TITLE
Remove overlap in suggested scopes of personal access token for GitHub GraphQL API

### ISSUE THREAD

**Issue by hamirmahal** [github/docs#18715]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/guides/forming-calls-with-graphql

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql

### Additional information

![image](https://user-images.githubusercontent.com/43425812/174494101-3df9d558-e858-46a9-a190-8c453eaf1c7b.png)

**Comment by skedwards88** [comment]
Closed via https://github.com/github/docs/pull/18716#issuecomment-1183761373
