### ISSUE TITLE
Missing spelling in the command in the Japanese page. 

### ISSUE THREAD

**Issue by ak2-lucky** [github/docs#18710]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ja/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors

### What part(s) of the article would you like to see updated?

missing command update

`git remot -v` => `git remote -v`

<img width="738" alt="スクリーンショット 2022-06-19 19 36 24" src="https://user-images.githubusercontent.com/56500037/174476854-f3d6017e-8c76-41d8-9725-794cb6c1acaf.png">

### Additional information

I made a pull request by mistake.(https://github.com/github/docs/pull/18709)
But it seems that pull requests for translated pages are not accepted.
So I created  issue

**Comment by janiceilene** [comment]
Thanks for opening this pull request! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

I've opened an internal issue with our translators 💛
