### ISSUE TITLE
Clarifying the source of a script file

### ISSUE THREAD

**Issue by abbylentz** [github/docs#18736]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service

### What part(s) of the article would you like to see updated?

This paragraph near the top.

> For Linux systems that use systemd, you can use the svc.sh script distributed with the self-hosted runner application to install and manage using the application as a service.

The `svc.sh` script isn't distributed with the runner application, it is created by the `config.sh` script which is.

### Additional information

Issue raised by customer in this ticket https://github.zendesk.com/agent/tickets/1663018

**Comment by janiceilene** [comment]
@abbylentz Thanks so much for opening an issue! I'll get this triaged for review 💖

**Comment by lucascosti** [comment]
👋 Sorry for the delay in triaging this.

There is this mention at the top:

> You must add a runner to GitHub before you can configure the self-hosted runner application as a service. For more information, see "[Adding self-hosted runners](https://docs.github.com/en/github/automating-your-workflow-with-github-actions/adding-self-hosted-runners)."

We could probably turn ☝️  into a note to make it more obvious, and update the Linux mention below to say that the script is created after successfully adding the runner. 

> For Linux systems that use systemd, you can use the svc.sh script distributed with the self-hosted runner application to install and manage using the application as a service.

**Comment by codewithdev** [comment]
This Issue has been resolved. Please approve and merge the PR https://github.com/github/docs/pull/20173
