### ISSUE TITLE
Create documentation for unarchiving-repositories

### ISSUE THREAD

**Issue by jsoref** [github/docs#18753]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

### What part(s) of the article would you like to see updated?

1. Create a page explaining how to unarchive a repository
2. Edit the archiving page to link to it in manner similar to how the [deleting a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository) page links to [restoring a deleted repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository).

### Additional information

Noted as missing here:
https://github.community/t/is-it-possible-to-unarchive-repository-one-it-is-archived/257681

**Comment by Walexero** [comment]
Has this issue been solved or do i still need to contribute

**Comment by jsoref** [comment]
No. In theory you could try to write a PR offering such content.

I tend not to make PRs for things until I get an indication from GitHub staff that they'll accept it. (But, that's a personal choice wrt managing my resources.)

**Comment by Benson665** [comment]
It's okay now but you can still help by cording easy and quick understanding

**Comment by cmwilson21** [comment]
@jsoref Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by janiceilene** [comment]
Thanks for opening an issue @jsoref! I've looked at this one with the team and we think it makes the most sense to just add a new section below "Archiving a repository" called "Unarchiving a repository." Several of the steps can just be reusables from the Archiving section. 

You or anyone else is welcome to open a PR with this update!
