### ISSUE TITLE
Secret scanning docs missing examples of signature validation in python

### ISSUE THREAD

**Issue by ckuethe** [github/docs#18778]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/developers/overview/secret-scanning-partner-program#implement-signature-verification-in-your-secret-alert-service

At the time of this writing, validation examples were provided in JavaScript, Ruby, and Go.

### What changes are you suggesting?

There should be an example signature validator in python.

This will help people (like myself) wishing to use the secret scanning service write notification endpoints that properly validate signatures.

**Comment by ckuethe** [comment]
Hello @janiceilene - do you know if anyone is reviewing my PR? It seems to have been useful to one other person recently.

**Comment by 99Edorde** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

Good ladi.[](url)
