### ISSUE TITLE
Branch search syntax is not documented

### ISSUE THREAD

**Issue by BBI-YggyKing** [github/docs#1880]
### What article on docs.github.com is affected?
The article on [searching pull requests ](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-based-on-whether-a-pull-request-is-merged-or-unmerged) has extensive information and examples about how to search pull requests, including the ability to search for PR's that have (or have not) been merged. There is no equivalent article for searching branches. It appears that branch search does not support `is:unmerged` or similar (though it would be great if this was supported), but there is no documentation to explain the branch search syntax.

### What part(s) of the article would you like to see updated?
I would like to see documentation on how to search branches, i.e. what is the query syntax for:
`https://github.com/myorganization/myrepo/branches/all?query=???`

**Comment by janiceilene** [comment]
👋 @BBI-YggyKing Thanks for opening this issue! I agree that an article like this would be beneficial. We'll need to get correct info from engineering on what syntax is supported. From there, we'll create a content strategy, we'll want the article to follow a similar format to our other search articles and also link to it from the branching content.

**Comment by rifatwoclan** [comment]
---
title: Configuring Docker for use with GitHub Packages
intro: 'You can configure the Docker client to use {% data variables.product.prodname_registry %} to publish and retrieve docker images.'
product: '{% data reusables.gated-features.packages %}'
redirect_from:
  - /articles/configuring-docker-for-use-with-github-package-registry
  - /github/managing-packages-with-github-package-registry/configuring-docker-for-use-with-github-package-registry
  - /github/managing-packages-with-github-packages/configuring-docker-for-use-with-github-packages
  - /packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages
versions:
  free-pro-team: '*'
  enterprise-server: '>=2.22'
---

{% data reusables.package_registry.packages-ghes-release-stage %}

{% data reusables.package_registry.admins-can-configure-package-types %}

### About Docker and {% data variables.product.prodname_registry %}

{% data reusables.package_registry.docker_registry_deprecation_status %}

When installing or publishing a docker image, {% data variables.product.prodname_registry %} does not currently support foreign layers, such as Windows images.

{% if enterpriseServerVersions contains currentVersion %}

Before you can use the Docker registry on {% data variables.product.prodname_registry %}, the site administrator for {% data variables.product.product_location %} must enable Docker support and subdomain isolation for your instance. For more information, see "[Managing GitHub Packages for your enterprise](/enterprise/admin/packages)."

{% endif %}

### Authenticating to {% data variables.product.prodname_registry %}

{% data reusables.package_registry.docker_registry_deprecation_status %}

{% data reusables.package_registry.authenticate-packages %}

#### Authenticating with a personal access token

{% data reusables.package_registry.required-scopes %}

You can authenticate to {% data variables.product.prodname_registry %} with Docker using the `docker` login command.

To keep your credentials secure, we recommend you save your personal access token in a local file on your computer and use Docker's `--password-stdin` flag, which reads your token from a local file.

{% if currentVersion == "free-pro-team@latest" %}
{% raw %}
  ```shell
  $ cat <em>~/TOKEN.txt</em> | docker login https://docker.pkg.github.com -u <em>USERNAME</em> --password-stdin
  ```
{% endraw %}
{% endif %}

{% if enterpriseServerVersions contains currentVersion %}
{% raw %}
 ```shell
 $ cat <em>~/TOKEN.txt</em> | docker login docker.HOSTNAME -u <em>USERNAME</em> --password-stdin
```
{% endraw %}
{% endif %}

To use this example login command, replace `USERNAME` with your {% data variables.product.product_name %} username{% if enterpriseServerVersions contains currentVersion %}, `HOSTNAME` with the URL for {% data variables.product.product_location %},{% endif %} and `~/TOKEN.txt` with the file path to your personal access token for {% data variables.product.product_name %}.

For more information, see "[Docker login](https://docs.docker.com/engine/reference/commandline/login/#provide-a-password-using-stdin)."

#### Authenticating with the `GITHUB_TOKEN`

{% data reusables.package_registry.package-registry-with-github-tokens %}

### Publishing an image

{% data reusables.package_registry.docker_registry_deprecation_status %}

{% note %}

**Note:** Image names must only use lowercase letters.

{% endnote %}

{% data variables.product.prodname_registry %} supports multiple top-level Docker images per repository. A repository can have any number of image tags. You may experience degraded service publishing or installing Docker images larger than 10GB, layers are capped at 5GB each. For more information, see "[Docker tag](https://docs.docker.com/engine/reference/commandline/tag/)" in the Docker documentation.

{% data reusables.package_registry.viewing-packages %}

1. Determine the image name and ID for your docker image using `docker images`.
  ```shell
  $ docker images
  > <&nbsp>
  > REPOSITORY        TAG        IMAGE ID       CREATED      SIZE
  > <em>IMAGE_NAME</em>        <em>VERSION</em>    <em>IMAGE_ID</em>       4 weeks ago  1.11MB
  ```
2. Using the Docker image ID, tag the docker image, replacing *OWNER* with the name of the user or organization account that owns the repository, *REPOSITORY* with the name of the repository containing your project, *IMAGE_NAME* with name of the package or image,{% if enterpriseServerVersions contains currentVersion %} *HOSTNAME* with the hostname of {% data variables.product.product_location %},{% endif %} and *VERSION* with package version at build time.
  {% if currentVersion == "free-pro-team@latest" %}
  ```shell
  $ docker tag <em>IMAGE_ID</em> docker.pkg.github.com/<em>OWNER/REPOSITORY/IMAGE_NAME:VERSION</em>
  ```
  {% else %}
  ```shell
  $ docker tag <em>IMAGE_ID</em> docker.<em>HOSTNAME/OWNER/REPOSITORY/IMAGE_NAME:VERSION</em>
  ```
  {% endif %}
3. If you haven't already built a docker image for the package, build the image, replacing *OWNER* with the name of the user or organization account that owns the repository, *REPOSITORY* with the name of the repository containing your project, *IMAGE_NAME* with name of the package or image, *VERSION* with package version at build time,{% if enterpriseServerVersions contains currentVersion %} *HOSTNAME* with the hostname of {% data variables.product.product_location %},{% endif %} and *PATH* to the image if it isn't in the current working directory.
  {% if currentVersion == "free-pro-team@latest" %}
  ```shell
  $ docker build -t docker.pkg.github.com/<em>OWNER/REPOSITORY/IMAGE_NAME:VERSION</em> <em>PATH</em>
  ```
  {% else %}
  ```shell
  $ docker build -t docker.<em>HOSTNAME/OWNER/REPOSITORY/IMAGE_NAME:VERSION</em> <em>PATH</em>
  ```
  {% endif %}
4. Publish the image to {% data variables.product.prodname_registry %}.
  {% if currentVersion == "free-pro-team@latest" %}
  ```shell
  $ docker push docker.pkg.github.com/<em>OWNER/REPOSITORY/IMAGE_NAME:VERSION</em>
  ```
  {% else %}
  ```shell
  $ docker push docker.<em>HOSTNAME/OWNER/REPOSITORY/IMAGE_NAME:VERSION</em>
  ```
  {% endif %}
  {% note %}

  **Note:** You must push your image using `IMAGE_NAME:VERSION` and not using `IMAGE_NAME:SHA`.

  {% endnote %}

#### Example publishing a Docker image

{% data reusables.package_registry.docker_registry_deprecation_status %}

You can publish version 1.0 of the `monalisa` image to the `octocat/octo-app` repository using an image ID.

{% if currentVersion == "free-pro-team@latest" %}
```shell
$ docker images

> REPOSITORY           TAG      IMAGE ID      CREATED      SIZE
> monalisa             1.0      c75bebcdd211  4 weeks ago  1.11MB

# Tag the image with <em>OWNER/REPO/IMAGE_NAME</em>
$ docker tag c75bebcdd211 docker.pkg.github.com/octocat/octo-app/monalisa:1.0

# Push the image to {% data variables.product.prodname_registry %}
$ docker push docker.pkg.github.com/octocat/octo-app/monalisa:1.0
```

{% else %}

```shell
$ docker images

> REPOSITORY           TAG      IMAGE ID      CREATED      SIZE
> monalisa             1.0      c75bebcdd211  4 weeks ago  1.11MB

# Tag the image with <em>OWNER/REPO/IMAGE_NAME</em>
$ docker tag c75bebcdd211 docker.<em>HOSTNAME</em>/octocat/octo-app/monalisa:1.0

# Push the image to {% data variables.product.prodname_registry %}
$ docker push docker.<em>HOSTNAME</em>/octocat/octo-app/monalisa:1.0
```

{% endif %}

You can publish a new Docker image for the first time and name it `monalisa`.

{% if currentVersion == "free-pro-team@latest" %}
```shell
# Build the image with docker.pkg.github.com/<em>OWNER/REPOSITORY/IMAGE_NAME:VERSION</em>
# Assumes Dockerfile resides in the current working directory (.)
$ docker build -t docker.pkg.github.com/octocat/octo-app/monalisa:1.0 .

# Push the image to {% data variables.product.prodname_registry %}
$ docker push docker.pkg.github.com/octocat/octo-app/monalisa:1.0
```

{% else %}
```shell
# Build the image with docker.<em>HOSTNAME/OWNER/REPOSITORY/IMAGE_NAME:VERSION</em>
# Assumes Dockerfile resides in the current working directory (.)
$ docker build -t docker.<em>HOSTNAME</em>/octocat/octo-app/monalisa:1.0 .

# Push the image to {% data variables.product.prodname_registry %}
$ docker push docker.<em>HOSTNAME</em>/octocat/octo-app/monalisa:1.0
```
{% endif %}

### Downloading an image

{% data reusables.package_registry.docker_registry_deprecation_status %}

You can use the `docker pull` command to install a docker image from {% data variables.product.prodname_registry %}, replacing *OWNER* with the name of the user or organization account that owns the repository, *REPOSITORY* with the name of the repository containing your project, *IMAGE_NAME* with name of the package or image,{% if enterpriseServerVersions contains currentVersion %}*HOSTNAME* with the host name of your {% data variables.product.prodname_ghe_server %} instance, {% endif %} and *TAG_NAME* with tag for the image you want to install. 

{% if currentVersion == "free-pro-team@latest" %}
```shell
$ docker pull docker.pkg.github.com/<em>OWNER/REPOSITORY/IMAGE_NAME:TAG_NAME</em>
```
{% else %}
```shell
$ docker pull docker.<em>HOSTNAME/OWNER/REPOSITORY/IMAGE_NAME:TAG_NAME</em>
```
{% endif %}

{% note %}

**Note:** You must pull the image using `IMAGE_NAME:VERSION` and not using `IMAGE_NAME:SHA`.

{% endnote %}

### Further reading

- "[Deleting a package](/packages/publishing-and-managing-packages/deleting-a-package/)"

**Comment by amein0** [comment]
> ### چه مقاله ای در docs.github.com تحت تأثیر قرار می گیرد؟
> مقاله مربوط به [جستجوی درخواست های کشش](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-based-on-whether-a-pull-request-is-merged-or-unmerged) دارای اطلاعات و مثالهای گسترده ای در مورد چگونگی جستجوی درخواستهای کشش است ، از جمله توانایی جستجو برای روابط عمومی ادغام شده (یا نشده). هیچ مقاله ای معادل برای جستجوی شعب وجود ندارد. به نظر می رسد که جستجوی شعبه پشتیبانی نمی کند `is:unmerged`یا موارد مشابه (اگرچه اگر این پشتیبانی شود بسیار خوب است) ، اما هیچ اسنادی برای توضیح نحو جستجوی شاخه وجود ندارد.
> 
> ### دوست دارید کدام قسمت از مقاله را به روز کنید؟
> من می خواهم اسنادی را در مورد نحوه جستجوی شاخه ها ببینم ، یعنی نحو پرس و جو برای چیست:
> `https://github.com/myorganization/myrepo/branches/all?query=???`
> 
> ### اطلاعات تکمیلی

پرونده هنوز احتیاج به برسی دارد کمی زمان  بر است و باید به دقت مرور شود نگران نباشید ما به صورت روح در حال برسی هستیم

**Comment by amein0** [comment]
@BBI-YggyKing 

> 👋 @ BBI-YggyKing با تشکر برای باز کردن این شماره! من موافقم که مقاله ای از این دست مفید خواهد بود. ما باید اطلاعات صحیحی را از مهندسی در مورد پشتیبانی از نحو دریافت کنیم. از آنجا ، ما یک استراتژی محتوا ایجاد خواهیم کرد ، ما می خواهیم مقاله از قالب مشابه سایر مقالات جستجوی ما پیروی کند و همچنین از محتوای انشعاب به آن پیوند دهد.

این مورد نیار به برسی دارد تمای شعب بانکهای جهان باید در دسترس باشند هیچ موردی استثنا نیست حتی کشورهایی که در تحریم هستند باید شعب آنها در دسترس باشند و تعلیق شعب بعد از اتمام پروژه به عهده نمایندگان دولتها و تصمیم نهایی را مدیر بانک جهانی خواهد گرفت لطفا از درگیرهای سیاسی پرهیز کنید 
من نیاز دچار فشار دولتها هستم اما درگیر مسائل سیاسی نیستم و از حقوق مردو و شهروندان دفاع میکنم این پروژه در راستای حقوق از مردم و شهروندان عادی است ن دفاع از دولتها
دقت داشته باشید اولویت ما پول الکترونیکی یعنی رمز ارزهای دیجیتال است ودرصد کمی را به پولهای رایج در پروژه قراد میدهیم.

**Comment by amein0** [comment]
@به استراتژی محتوا نیاز داریم

**Comment by janiceilene** [comment]
This is being triaged internally for now! For the writer who picks it up, please:

- Get the right syntax from engineering
- Create a simplified CS in this issue
- After the CS is reviewed, move this to the "available issues" column, add a `help wanted` and a `good first issue` label

**Comment by felicitymay** [comment]
Hi @BBI-YggyKing - thanks for raising this issue. You're right - this doesn't seem to be covered in the documentation at the moment.

I've just spoken to the engineering team who are responsible for the various search fields on GitHub. 

- When you search in the main search field in GitHub (in the top left of the menu bar), this search includes only the code in your default branch.

- It sounds as if you're describing the search box on the **branches** page of a repository ([Viewing branches in your repository](https://docs.github.com/en/github/administering-a-repository/viewing-branches-in-your-repository)). The engineering team have confirmed that this search field provides a simple, case-insensitive, sub-string search on the branch name. There is no additional syntax available currently.

I'm not entirely sure where best to cover the search on the branches page. The syntax is so simple that I'm not sure that it warrants a separate page among the other search topics. We could add a section about searching on the branches page to [Viewing branches in your repository](https://docs.github.com/en/github/administering-a-repository/viewing-branches-in-your-repository). This would be shown in the results if you searched for "searching branches".

Let me know what you think and we can update this issue with a content design plan to add the information.

**Comment by BBI-YggyKing** [comment]
You are correct, I was referring to the search box in the branches page. I had hoped there was syntax available there to find merged branches, unmerged branches, search by author, etc.

As far as documenting current behaviour, a short paragraph on the [Viewing branches in your repository](https://docs.github.com/en/github/administering-a-repository/viewing-branches-in-your-repository) page to explain the simple functionality of the search box seems appropriate.

I'm inclined to open a feature request for more full-featured search functionality, but I guess that's a separate issue. :)

**Comment by felicitymay** [comment]
> I'm inclined to open a feature request for more full-featured search functionality, but I guess that's a separate issue. :)

The best place to send your feedback is to https://support.github.com/contact/feedback :yellow_heart: they can make sure your feedback gets to the right product manager.

**Comment by felicitymay** [comment]
### Content design plan

Proposed content design plan to address this issue.

Topics to update:

[Viewing branches in your repository](https://docs.github.com/en/github/administering-a-repository/viewing-branches-in-your-repository)

- Add an extra step at the end of the procedure explaining how to do a simple sub-string search of branch names using the search field.

**Comment by felicitymay** [comment]
Thanks for chatting about this issue. It was really helpful being able to clarify what was missing.

This issue should now be ready for anyone to pick up if they'd like to fill in this gap in the docs 😄

**Comment by akshay4n** [comment]
@felicitymay Is the issue still open? I would like to work on this.
