### ISSUE TITLE
Typo in app code sample

### ISSUE THREAD

**Issue by rjbell4** [github/docs#18830]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/apps/apps#create-an-installation-access-token-for-an-app

### What part(s) of the article would you like to see updated?

Code sample

### Additional information

`respoitory` is a clear typo.  It should _at least_ be `repository`, but perhaps should be `repositories`, and the data an array.

**Comment by nawed2611** [comment]
<img width="218" alt="image" src="https://user-images.githubusercontent.com/83456083/176124620-c1d7b81a-36b9-496a-8ed8-dca28eb62624.png">

As you can see, there's a typo in the word ```respoitory```

I would like to fix this issue

**Comment by cmwilson21** [comment]
Hi @Paras-Saini 👋 Thanks for your interest in updating this file! Most of our rest documentation has to be updated internally.

Please take a look at the help wanted section of [our open source board](https://github.com/github/docs/projects/1#column-11564194) to find open issues you can work on.

Thank you for your passion and enthusiasm for improving our docs! 💖

**Comment by cmwilson21** [comment]
Since updates to the REST/GraphQL API description must be made internally. I have copied your issue to an internal issue, so I will close this issue.

Thank you for bringing this to our attention ✨
