### ISSUE TITLE
Ambiguity found in the GitHub Dependency Review doc

### ISSUE THREAD

**Issue by aidenwang9867** [github/docs#18831]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The [GitHub Dependency Review](https://docs.github.com/en/rest/dependency-graph/dependency-review#about-the-dependency-review-api) document.

### What part(s) of the article would you like to see updated?

According to the current description of the section [Get a diff of the dependencies between commits](https://docs.github.com/en/rest/dependency-graph/dependency-review#get-a-diff-of-the-dependencies-between-commits):

```Gets the diff of the dependency changes between two commits of a repository, based on the changes to the dependency manifests made in those commits.```

I suppose this API currently only supports checking dependency changes thru the `manifest file`, rather than the `lockfile`. If that's correct, maybe we should make the document clearer, change the words `dependency manifests` to `manifest files that contain dependencies` or else. Also, I think it's important to let users know that the Dependency Review API now cannot be used to check dependency changes using a `lockfile`.

### Additional information

I am not so sure about whether the API can use the `lockfile` for dependency analysis now. In my testcase, when I bump `tensorflow@2.1.0` to `tensorflow@2.6.0` with `pip.lockfile` (Python env), I only got dependency information of `tensorflow`, without those indirect dependencies (tensorflow's dependencies) such as `numpy`, `rsa`, `requests`.

Whatsoever, I still believe we should make the doc description more explicit, by pointing out the kind of files we are currently supporting (manifest file or lock file or both).

**Comment by janiceilene** [comment]
@aidenwang9867 Thanks so much for opening an issue! I'll get this triaged for review ⚡

**Comment by aidenwang9867** [comment]
Hi Janice @janiceilene, are there any updates on this issue? :D

**Comment by cmwilson21** [comment]
@aidenwang9867 Thanks for checking in! 👍  We are still a bit [slow to respond](https://github.com/github/docs/issues/18510) right now, but this is up on the review board. Someone will get eyes on it soon 👀 

Thank you for your patience! 💛

**Comment by cmwilson21** [comment]
@aidenwang9867 Thanks for your patience on this one! 💛 

I spoke with the team and something that was noticed was that `pip.lockfile` isn't supported but `pipfile.lock` is. See the article on [supported package ecosystems](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems) for more information.

For `tensorflow@2.6.0` and `2.1.0` the DG package DB does track `numpy` as a transitive dep, but not `requests` or `rsa`.

If `numpy` and other transitives show up in DG Insights and DR, then everything is working as expected.

I hope the information in the above article is helpful in this case. If that clears things up, I'll go ahead and close the issue as completed.

**Comment by aidenwang9867** [comment]
> @aidenwang9867 Thanks for your patience on this one! 💛
> 
> I spoke with the team and something that was noticed was that `pip.lockfile` isn't supported but `pipfile.lock` is. See the article on [supported package ecosystems](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems) for more information.
> 
> For `tensorflow@2.6.0` and `2.1.0` the DG package DB does track `numpy` as a transitive dep, but not `requests` or `rsa`.
> 
> If `numpy` and other transitives show up in DG Insights and DR, then everything is working as expected.
> 
> I hope the information in the above article is helpful in this case. If that clears things up, I'll go ahead and close the issue as completed.

Thank you so much for the detailed reply!
