### ISSUE TITLE
Add Progressive Web App functionality to all GitHub Pages sites

### ISSUE THREAD

**Issue by hello-smile6** [github/docs#1884]
# This would allow users to use GitHub Pages as a standalone app without installing the full app.
## The code would be:
```
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="GitHub Pages">
```
If the above code was appended to the `<head>` tag of all GitHub Pages webpages via a workflow, GitHub would take its first step toward being a PWA.

**Comment by janiceilene** [comment]
👋 @hello-smile6 This repository only contains the documentation website code and Markdown source files for docs.github.com,.

If you have a question or suggestion about GitHub itself, the best place to get started is on [our contact page](https://support.github.com/contact).
