### ISSUE TITLE
Inconsistent auth header in code sample

### ISSUE THREAD

**Issue by andyliau** [github/docs#18891]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/apps/apps#create-an-installation-access-token-for-an-app

### What part(s) of the article would you like to see updated?

[Create an installation access token for an app](https://docs.github.com/en/rest/apps/apps#create-an-installation-access-token-for-an-app)

Code sample section:
![image](https://user-images.githubusercontent.com/3623241/176620634-b4e83510-4a24-45ab-b43a-8682bf5a938c.png)

### Additional information

![image](https://user-images.githubusercontent.com/3623241/176620634-b4e83510-4a24-45ab-b43a-8682bf5a938c.png)

**Comment by cmwilson21** [comment]
@andyliau Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
Thank you for opening this issue! Updates to the REST/GraphQL API description must be made internally. I have copied your issue to an internal issue, so I will close this issue.
