### ISSUE TITLE
pt-BR translation error

### ISSUE THREAD

**Issue by quaresmateo** [github/docs#189]
### What is the current behavior?

There is a translation error in [translations/pt-BR/.../licensing-a-repository.md](https://github.com/github/docs/edit/main/translations/pt-BR/content/github/creating-cloning-and-archiving-repositories/licensing-a-repository.md). We don't translate `README` into Portuguese, we just call it README.

### What changes are you suggesting?

Change "LEIAME" to "README".

**Comment by janiceilene** [comment]
Thank you so much for letting us know @quaresmateo ✨ I'll close this issue, but let our localization team know!

**Comment by zeke** [comment]
Thanks for opening an issue @quaresmateo and thanks for following up @janiceilene ✨
