### ISSUE TITLE
Explain different default contexts (fx with and without branch protection)

### ISSUE THREAD

**Issue by alexgenaud** [github/docs#18936]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

### What part(s) of the article would you like to see updated?

Some note regarding "default" behavior explicitly, would be helpful.

The documentation may be strictly correct, but certain assumed or non-obvious interpretation of "default" is likely confusing (it was for me). I assume "default" means "always without any overriding setting there is one and only one presumed value". To my surprise, "default" is contextual and may mean the exact opposite in different contexts.

The specific example I ran into (though there are numerous examples):

By default, in both git and github, 'git push --force' is allowed, even to master.
However, with branch protection enabled, then by default 'git push --force' is not allowed, by default.
The documentation clearly states that allow_force_pushes = false is default.
But it's only default in that context and not default (opposite default) in the default context (no branch protection).

**Comment by Benson665** [comment]
All easy and quickly parts

**Comment by cmwilson21** [comment]
Closing this issue as it was resolved with the closing of [PR 18935](https://github.com/github/docs/pull/18935#issuecomment-1181482848)
