### ISSUE TITLE
Add a go to top button

### ISSUE THREAD

**Issue by siddhantvirus** [github/docs#1894]
### What is the current behavior?

Currently, there are no buttons to let a reader scroll back to the Table of Contents on any page on docs.github.com.
While this can be bypassed by a desktop/laptop by using the _home_ button, users using a mobile device do not have the same privilege 

### What changes are you suggesting?

I suggest adding a floating button on the bottom right corner at least the mobile view of the website which when clicked either takes the user back to the top of the page , or can be a linked to the href of the table of contents heading.

### Additional information

I believe the approach needs to be such , that it can be enabled on only the pages with actual documentation and that it doesn't need to be manually  added for every markdown page.

**Comment by umutduyum** [comment]
The topic is 512 Gb. an Androit supports and supports a memory card of 512 Gb. under normal conditions but Google Play, only 24Gb.  and also Androit stops the device from working, so there's only one precaution that can be taken on your ASSUMING SCAN without entering Google Play, so you can handle all your transactions without any problems. Sincerely[](url)https://photos.app.goo.gl/jCt2UCxQPirQKU6y9

**Comment by janiceilene** [comment]
@siddhantvirus Thanks for opening an issue! I'll triage this for the right team to take a look 👀

**Comment by Ylan96** [comment]
Is someone work on this issue?
I'm interested to contribute on the code part(if the design part is already defined).

**Comment by janiceilene** [comment]
👋 @Ylan-sayada We don't have any design specs created for this issue 💛 If you're looking for somewhere to contribute, there are quite a few issues with a [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label ✨

**Comment by Satsuk-yuuya** [comment]
Three PCs have already been ruined, but there are still some PCs that I have broken the LCD a little.  There is also a Video room that can be used in a private room on a PC.

**Comment by siddhantvirus** [comment]
@janiceilene could you please look into to why there are two random spammy comments on this issue from accounts which don't seem to have any activity whatsoever?
This seems to be highly suspicious and I can't seem to find other issues where the said issues have done the same

**Comment by FREELANCEGITIT** [comment]
> @janiceilene could you please look into to why there are two random spammy comments on this issue from accounts which don't seem to have any actual activity whatsoever?
> This seems to be highly suspicious and I can't seem to find other issues where the said users have done the same.
> Honestly I feel a little scared at this point.

The comments are directed at the owners?

**Comment by Ylan-sayada** [comment]
> @janiceilene could you please look into to why there are two random spammy comments on this issue from accounts which don't seem to have any actual activity whatsoever?
> This seems to be highly suspicious and I can't seem to find other issues where the said users have done the same.
> Honestly I feel a little scared at this point.

I'm not a bot if its what you think about.
Just not very active on github.

**Comment by cudak192** [comment]
Jop

pt., 11 gru 2020, 12:56 użytkownik Ylan Sayada <notifications@github.com>
napisał:

**Comment by siddhantvirus** [comment]
@FREELANCEGITIT ? I'm sorry but i wasn't referring to you in any of my comments 😅

**Comment by Satsuk-yuuya** [comment]
hi.Mr or Mis.

it's big act. I think it's my capacity over.so I can't finished debug now.
so if git member use it than need  attention.

I think you can debug. if do you have your time than, please do it.

thank you!


 from.Satsuki.Y



2020年12月11日(金) 16:21 Siddhant Tibrewal <notifications@github.com>:

**Comment by janiceilene** [comment]
@siddhantvirus I'm not sure why that was happening, but they should all be removed and reported now 💛

**Comment by kazuhitonakayama** [comment]
Hi , Nice to meet you.
I also want to contribute this issue...

Could I work on this issue with you??

If it would be good, what we will have to do is below?
・Make design idea
・do the code part

I would be happy to your reply!!
@Ylan-sayada @janiceilene

**Comment by AlSufyaniT1** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by kazuhitonakayama** [comment]
Happy New Year , every one!
I'm working on this issue at PR( https://github.com/github/docs/pull/2243 ).

**Comment by notebookmark** [comment]
Notebook

**Comment by heiskr** [comment]
Happened in https://github.com/github/docs/pull/2243
