### ISSUE TITLE
Add context about issue label and contribute page

### ISSUE THREAD

**Issue by SirSpidey** [github/docs#18952]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Setting guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

### What part(s) of the article would you like to see updated?

I didn't know about the `contribute` page and was wondering how to create it. Took me a bunch of searching to finally find the info that it's "automatically" created from a label at https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels (although I did infer the information from looking at GH issues that I found). 

I think that adding this context helps keep people on this page and focus on the point that the contributing guidelines show up on the contribute page.

> The link to the contributing guidelines also appears on your repository's contribute page. For an example of a contribute page, see [github/docs/contribute](https://github.com/github/docs/contribute).

**Comment by cmwilson21** [comment]
Closing out this issue now. Details in [PR 18953](https://github.com/github/docs/pull/18953#issuecomment-1182142770)

✨
