### ISSUE TITLE
Note on the use of square brackets in GitHub Actions workflows filter patterns

### ISSUE THREAD

**Issue by noritada** [github/docs#18969]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Following paragraphs:

[on.<pull_request|pull_request_target>.<branches|branches-ignore>](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore)

>The branches and branches-ignore keywords accept glob patterns that use characters like *, **, +, ?, ! and others to match more than one branch name. If a name contains any of these characters and you want a literal match, you need to escape each of these special characters with \. For more information about glob patterns, see the "[Filter pattern cheat sheet](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)."

[Filter pattern cheat sheet](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)

>The characters *, [, and ! are special characters in YAML. If you start a pattern with *, [, or !, you must enclose the pattern in quotes.

### What part(s) of the article would you like to see updated?

As in the case with three special characters at the beginning of a pattern, if you use `[` and/or `]` in a flow sequence, you must enclose them in quotes. Since there must be quite a few people who make such a statement, I think it would be a good idea to write a warning.

![ss 2022-07-10 23 08 52](https://user-images.githubusercontent.com/20850/178150605-cad6121e-a1fe-467d-8a35-20e12950b7f6.png)

- [Flow Sequences](https://yaml.org/spec/1.2.2/#flow-sequences) in the YAML specification

**Comment by Benson665** [comment]
All parts that will be more understandable easily and quickly
