### ISSUE TITLE
CODEOWNERS documentation claims that a user needs at least read access, but GitHub's built in linter claims the user needs write access

### ISSUE THREAD

**Issue by ScriptAutomate** [github/docs#18984]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What part(s) of the article would you like to see updated?

> The people you choose as code owners must have **read permissions** for the repository. When the code owner is a team, that team must be visible and it must have **write permissions**, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

I read this as:
- Only teams with at least write permissions can be listed
- Individual users can be listed as long as they have at least read permissions

The GitHub linter throws a `This CODEOWNERS file contains errors` message, for my users with at least read access, and says:
> Unknown owner: make sure `@octocat` exists and has write access to the repository

The problem is:
- The user exists
- The user has Outside Collaborator permissions for at least read
- Other users with triage permissions also get flagged
- The documentation states that read permissions is enough, even though GitHub flags it saying that write permissions are required for users

I can't tell whether the docs are wrong or the GitHub linter is wrong. This is why I'm raising this issue here.

### Additional information

Example from PR:
- https://github.com/saltstack/salt/pull/62325

![image](https://user-images.githubusercontent.com/5951023/178586269-7e3903c5-aa8e-431f-bda8-ce0bbef34354.png)

Problems:
- [`@ryan-lane`](https://github.com/ryan-lane) exists
- He has the `Read` role to the repository
- Docs state that `Read`, at a minimum (thus also `Triage`), should be enough for individuals

**Comment by cmwilson21** [comment]
@ScriptAutomate Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Benson665** [comment]
Thanks,I was carried away on my searching

**Comment by jaystyles** [comment]
@Dependably close

**Comment by lecoursen** [comment]
Thanks @ScriptAutomate, by coincidence this was actually just fixed internally and should be published shortly. 🙇🏻

**Comment by ScriptAutomate** [comment]
@lecoursen Hey! Just following up: when you say this was "fixed internally" does this mean that the documentation was correct? I am still experiencing this problem in the linting result of the codeowners file and I am uncertain as to how I should proceed. If I ignore the linter errors, is it just meant to work the way I am expecting it to work based off of the docs?

**Comment by ScriptAutomate** [comment]
Thanks!

For documentation purposes: It looks like the error was in the documentation, which has since been fixed. It does mean that only users with **Write** access can be used in the CODEOWNERS file.

Is there a route I can take for a feature request? With our open source project, we would love to be able to have community members with explicit **Read** permissions to be able to be assigned to review PRs.

**Comment by damon-atkins** [comment]
It would be nice to able to have people who can not merge code (write),  be apart of the review/notification/approval process for a PR.

**Comment by aitemour79** [comment]
***@***.*** com

**Comment by lecoursen** [comment]
> Is there a route I can take for a feature request?

Yes! You can provide product feedback [here](https://github.com/orgs/community/discussions/categories/pull-requests). Thanks for helping us improve GitHub! 💖

**Comment by damon-atkins** [comment]
ScriptAutomate has submitted the request, @lecoursen  can you please ensure it has the correct labels. Many thanks.

**Comment by lecoursen** [comment]
👋🏻 @damon-atkins, the GitHub community discussions are owned by a different team. (We only own this repo and [docs.github.com](http://docs.github.com/).)  :sparkling_heart: I'm sure the appropriate team will review the post shortly! 😊
