### ISSUE TITLE
Quypham

### ISSUE THREAD

**Issue by phamquangquy92vd** [github/docs#1899]

**Comment by phamquangquy92vd** [comment]
> 
> 
> 
> 
> ### What article on docs.github.com is affected?
> 
> 
> 
> ### What part(s) of the article would you like to see updated?
> 
> 
> 
> ### Additional information
> 
> 
> 

[]

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
