### ISSUE TITLE
Discuss Github Copilot/Intellicode Conflicts in VSCode

### ISSUE THREAD

**Issue by vedantsinghania05** [github/docs#19003]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-visual-studio-code

### What part(s) of the article would you like to see updated?

I'm not sure if this is relevant to the Github documentation, but discussing that using Github Copilot in VS Code will disable whole line completions by Intellicode completions if that extension is enabled might be beneficial to avoid confusion when a VS Code user has both extensions installed.

I have not found official VSCode documentation about this (though I'm sure it exists), but when I set up Github Copilot, VS Code notified me that whole line completions from Intellicode completions would be disabled while Github Copilot was active.

**Comment by jaystyles** [comment]
Thank you

**Comment by cmwilson21** [comment]
@vedantsinghania05 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by vedantsinghania05** [comment]
Thank you!

**Comment by jules-p** [comment]
Hi @vedantsinghania05 👋🏻 Thank you so much for opening this issue, we really appreciate you taking the time. The issue you're describing is outside the scope of our docs, but I can raise it with the Copilot team and see whether there might be another way for us to surface the information. As it won't be part of the docs, I'll close this issue for now, but thank you again for highlighting it! ✨

**Comment by TheHoleTree00Felix1** [comment]
I'll do my best to be aware of people I communicate with along with my surroundings. Meaning don't click on anything you don't trust. :-(
