### ISSUE TITLE
reorder advice in `Best practices for leaving your company`

### ISSUE THREAD

**Issue by jsoref** [github/docs#19042]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/best-practices-for-leaving-your-company

## (Before leaving)

Current:

> Before you leave your company, make sure you update the following information in your personal account:
> 1. Unverify your company email address by [deleting it in your Email settings](https://docs.github.com/en/articles/changing-your-primary-email-address). You can then re-add it without verifying to keep any associated commits linked to your account.
> 2. [Change your primary email address](https://docs.github.com/en/articles/changing-your-primary-email-address) from your company email to your personal email.
> 3. [Verify your new primary email address](https://docs.github.com/en/articles/verifying-your-email-address).
> 4. [Change your GitHub username](https://docs.github.com/en/articles/changing-your-github-username) to remove any references to your company or organization, if necessary.

Proposed:

> Before you leave your company, make sure you update the following information in your personal account:
> 1. If you haven't already added your personal email address, add it.
> 2. If you haven't already verified your personal email address, verify it.
> 3. [Change your primary email address](https://docs.github.com/en/articles/changing-your-primary-email-address) from your company email to your personal email.
> 4. Unverify your company email address by [deleting it in your Email settings](https://docs.github.com/en/articles/changing-your-primary-email-address). You can then re-add it without verifying to keep any associated commits linked to your account.
> 5. [Change your GitHub username](https://docs.github.com/en/articles/changing-your-github-username) to remove any references to your company or organization, if necessary.

Note that you should really verify your new thing before you make it your primary...

## Leaving organizations

Current:

> If you've been working with repositories that belong to an organization, you'll want to [remove yourself as a member of the organization](https://docs.github.com/en/articles/removing-yourself-from-an-organization). Note that if you are the organization owner, you should first [transfer ownership of the organization](https://docs.github.com/en/articles/transferring-organization-ownership) to another person.

> 1. If you are the organization owner, you should [transfer ownership of the organization](https://docs.github.com/en/articles/transferring-organization-ownership) to another person.
> 2. If you've been working with repositories that belong to an organization, you'll want to [remove yourself as a member of the organization](https://docs.github.com/en/articles/removing-yourself-from-an-organization).

Note that you *really* should not suggest leaving a thing before suggesting transferring ownership, that's incredibly dangerous.

## Removing professional associations with personal repositories

_This section is very confusing. I'd encourage someone to review it._

Current:

> * Delete local copies of your forks that may exist on your computer:
> ```
> $ rm -rf work_directory
> ```

Proposed:

> * Delete local copies of your forks that may exist on your computer:
>     ```
>      $ rm -rf work_directory
>      ```

### Additional information

This came up in:
https://github.community/t/using-one-account-for-all-your-projects/10197

It's probably worth reviewing the conversation...

**Comment by devjaiye** [comment]
Helpful 💯💯

**Comment by cmwilson21** [comment]
@jsoref Thanks so much for opening an issue! We appreciate the time and detail you've put into these suggestions. 💛 

I'll triage this for the team to take a look :eyes:

**Comment by janiceilene** [comment]
Wow, this is an old, outdated article that doesn't follow our style guide at all! Thanks so much for pointing this one out @jsoref ✨ We've opened an internal issue to update the whole thing (remove inline links and the `!` 😆 ), so I'm going to close this issue now.

Thanks again!
