### ISSUE TITLE
Unnecessary code backticks around <kbd> blocks

### ISSUE THREAD

**Issue by jnidzwetzki** [github/docs#19064]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

On the [Introduction to dev containers](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers#creating-a-custom-dev-container-configuration) page, the keyboard shortcuts use incorrect formatting.

According to the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#keyboard-shortcuts), the `<kbd>` tag should be used for keyboard shortcuts. However, on the page, the tag is included within code backticks, which leads to visible `<kbd>` tags in the output.

### What part(s) of the article would you like to see updated?

The formatting of the keyboard shortcuts should be changed and the code backticks should be removed.

### Additional information

<img width="704" alt="Bildschirmfoto 2022-07-17 um 19 46 03" src="https://user-images.githubusercontent.com/5753622/179418955-96005924-7c4d-43a0-89f5-fdb1beec10ae.png">

**Comment by cmwilson21** [comment]
@jnidzwetzki Thanks so much for opening an issue and linking your PR to it! 💖
