### ISSUE TITLE
"Viewing a project's contributors" needs a link to "List repository contributors"

### ISSUE THREAD

**Issue by tnir** [github/docs#19099]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- Viewing a project's contributors: https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors

### What part(s) of the article would you like to see updated?

[Viewing a project's contributors](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors) has a notation:

> Tip: To list all commit contributors in a repository, see "[Repositories](https://docs.github.com/en/rest/reference/repos#list-contributors)."

but that is too vague since it does not specify any specific REST API.

It links to [List repository contributors](https://docs.github.com/en/rest/repos/repos#list-repository-contributors): 
`https://docs.github.com/en/rest/repos/repos#list-repository-contributors`

**Comment by cmwilson21** [comment]
@tnir Thanks for opening this issue and linking it to your PR 💖
