### ISSUE TITLE
add section for "creating projects" using api

### ISSUE THREAD

**Issue by Priyankasaggu11929** [github/docs#19096]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Under the heading [`using the API to manage projects (beta)`](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects), add a sub-section with an example demonstrating "creating projects (using APIs)," because there are mutation apis available for ProjectV2 for creating a new project, [`mutations#createprojectv2`](https://docs.github.com/en/graphql/reference/mutations#createprojectv2), and having an example for its usage would be helpful.

<img width="376" alt="Screenshot 2022-07-18 at 3 18 30 PM" src="https://user-images.githubusercontent.com/30499743/179488419-f05c2e84-3c51-44a0-acc8-5cfcb17f008b.png">

### What changes are you suggesting?

Add a section with an example to create GitHub Project Beta using api

**Comment by cmwilson21** [comment]
@Priyankasaggu11929 Thanks for opening this issue and linking your PR to it! 💖

**Comment by Readywillingh-20** [comment]
Hello friends
