### ISSUE TITLE
Use latest shell commands for ssh-add key article

### ISSUE THREAD

**Issue by madbernard** [github/docs#19156]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

 https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

### What part(s) of the article would you like to see updated?

The instructions for storing your ssh passphrase in Mac OS keychain silently fail for OS greater than 12, which I believe is most of us these days. Thus, when following the instructions Github gives you, you end up still entering your SSH password with command line git every interaction. The modern shell commands are described here: https://apple.stackexchange.com/questions/48502/how-can-i-permanently-add-my-ssh-private-key-to-keychain-so-it-is-automatically/250572#250572

**Comment by cmwilson21** [comment]
@madbernard Thanks for creating this issue and linking it to your PR!

**Comment by madbernard** [comment]
bump
