### ISSUE TITLE
"Managing your Theme Settings" is not part of the repo while on @latest live-docs

### ISSUE THREAD

**Issue by Andre601** [github/docs#1915]
### What is the current behavior?
When accessing the [Managing your theme settings](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/managing-your-theme-settings) page on the live docs and then clicking on "Make a contribution" does it lead to a [404 error page](https://github.com/github/docs/edit/main/content/github/setting-up-and-managing-your-github-user-account/managing-your-theme-settings.md).

### What changes are you suggesting?
I'm not aware of how updates on this repo exactly work, but I assume that once an article is available on `@latest` in the live docs, that it also would be findable in this repository, which isn't the case for the above example.

If this is indeed how it should work, would I highly recommend to add the missing page to the repository, so that other people won't get confused as to why the page apparently doesn't exist.

**Comment by janiceilene** [comment]
@Andre601 Thanks so much for opening an issue and letting us know! I'll triage this for the engineering team to take a look 👀

Was there any content on that page you were hoping to contribute to or see updated?

**Comment by Andre601** [comment]
> Was there any content on that page you were hoping to contribute to or see updated?

Not really.
I actually just clicked it by accident and the 404 page appeared.

**Comment by janiceilene** [comment]
That button should be all fixed now! It sent me to https://github.com/github/docs/edit/main/content/github/setting-up-and-managing-your-github-user-account/managing-your-theme-settings.md when I clicked it. 

Please let me know if you run into any problems again 💖
