### ISSUE TITLE
Description in revision selection in "Comparing commits" is inadequate

### ISSUE THREAD

**Issue by tnir** [github/docs#19185]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits#comparisons-across-commits

### What part(s) of the article would you like to see updated?

In this page, "Comparisons across commits" section describes `^^^^^`, which is however equivalent to `~5`. Also the page misses the other specification `~` itself.

### Additional information

- [Ancestry References (in 7.1 Git Tools - Revision Selection)](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection)

### Intra-repo information
- Relevant tissue: #19184

**Comment by cmwilson21** [comment]
@tnir Thanks for opening an issue and PR! We appreciate you taking the time to research it and provide great details 💖
