### ISSUE TITLE
Some parts in "Comparing commits" do not work any more

### ISSUE THREAD

**Issue by tnir** [github/docs#19184]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits#comparisons-across-commits

### What part(s) of the article would you like to see updated?

In this page, now only "Comparisons across commits" asks a reader to type <rev> (commit sha1) on Web UI, but GitHub UI does not allow them to do so. You can remove that description:

```
As a shortcut, Git uses the ^ notation to mean "one commit prior."

You can use this notation to compare a single commit or branch against its immediate predecessors. For example, 96d29b7^^^^^ indicates five commits prior to 96d29b7, because there are five ^ marks. Typing 96d29b7^^^^^ in the base branch and 96d29b7 in the compare branch compares the five commits made before 96d29b7 with the 96d29b7 commit.
```

- 08ca047c87625c6706032f2e8ee668cea60ab32a (part of #17932) removes "type <rev>" from other section(s) on the page.
- Even as of disclosure of github/docs at 3df90fc9b811728a9b7ee45f598f9ae196783b54, there was already this explanation.

### Additional information

Current source code is available at:

https://github.com/github/docs/blob/94b4e599554687fc1d147d053cf528290819a918/content/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits.md?plain=1#L58-L64

**Comment by cmwilson21** [comment]
@tnir Thanks so much for opening an issue and a PR! We appreciate all the detailed information 💖
