### ISSUE TITLE
Clarify how the bash shell will be invoked if not specified explicitly for jobs.<job_id>.steps[*].shell

### ISSUE THREAD

**Issue by nikola-jokic** [github/docs#19191]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

### What part(s) of the article would you like to see updated?

Description for:
![image](https://user-images.githubusercontent.com/97525037/180164233-66773081-a844-4923-a095-90ae299d39b0.png)
should be extended to say that the `bash -e {0}` will be applied if the shell parameter is not specified explicitly.

### Additional information

This change is related to the [comment](https://github.com/actions/runner/issues/1955#issuecomment-1189337732) in the runner repo.

**Comment by cmwilson21** [comment]
@nikola-jokic Thanks for opening an issue and PR!
