### ISSUE TITLE
Mobile search results don't get enough space

### ISSUE THREAD

**Issue by jsoref** [github/docs#19214]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The docs search view on mobile reserves way too much space for the things above the search text.

### What changes are you suggesting?

When on mobile, of a user enters text into the search field, reduce the top bar to at most one line of text.  It's functionally about 10 lines. And with an input method editor up, it wasn't apparent that the search box did anything at all. 

### Additional information

![Screenshot_20220722-093641](https://user-images.githubusercontent.com/2119212/180451015-16154d03-4e18-4f93-af5b-cceea56dde42.png)

**Comment by cmwilson21** [comment]
@jsoref Thanks for opening an issue and bringing this to our attention. 👍 

I've let the team know and we are going to open this as an internal issue. So, I'll go ahead and close this one out. 

Thanks for the feedback! 💛
