### ISSUE TITLE
Arguments and options for `codeql database analyze` with `--download` example

### ISSUE THREAD

**Issue by horihiro** [github/docs#19239]
[maintainer edit]
This issue is reserved for the MLH Fellowship program.

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/configuring-codeql-cli-in-your-ci-system#basic-example-2

### What part(s) of the article would you like to see updated?

In the following example command in this article, I wonder if the order of arguments and options is correct because the repo `/codeql-dbs/example-repo` is located after `--download`.
Also `--github-auth-stdin` is needed because the token `$OCTO-ORG_ACCESS_TOKEN` is from stdin..

```sh
$ echo $OCTO-ORG_ACCESS_TOKEN | codeql database analyze --download /codeql-dbs/example-repo \
    octo-org/security-queries \
    octo-org/optional-security-queries@~1.0.1:queries/csrf.ql \
    --format=sarif-latest --output=/temp/example-repo-js.sarif
```

### Content Plan
See plan [here](https://github.com/github/docs/issues/19239#issuecomment-1212909221).

**Comment by cmwilson21** [comment]
@horihiro Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by mchammer01** [comment]
@horihiro 👋🏻 
We've checked with the CodeQL team and:
- The command-line parser we use allows flags and positional arguments to be intermixed freely, so the order of `--download` before the `/codeql-dbs/example-repo` path is allowed here. 

- The second point is a bit more nuanced in that the example you provide should include both `echo $TOKEN` and `--github-auth-stdin`, or neither. The team's preference was “neither” with the suggestion to add that the user should set the token in GITHUB_TOKEN:

- Neither - set the token in the env variable `GITHUB_TOKEN`, no `echo $TOKEN`, no `--github-auth-stdin`.
- Both - do nothing involving `GITHUB_TOKEN`, add `echo $TOKEN` and add `--github-auth-stdin`.

Also, to avoid confusion, the team suggests that the example just after [this one](https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/configuring-codeql-cli-in-your-ci-system#direct-download-of-codeql-packs) should also explicitly include `--github-auth-stdin`. 



A final suggestion is that, for best security practices, `echo $TOKEN` should really be `cat file-with-my-token`.

Does this make sense to you?

**Comment by cmwilson21** [comment]
@horihiro Thanks again for opening this issue. You or anyone else are welcome to work on this following the suggestions above 💖

**Comment by MdSabbirIsla** [comment]
Vivo V17 Pro

**Comment by mchammer01** [comment]
cc: ing @felicitymay for awareness that this has been closed.
