### ISSUE TITLE
Add `host key verification failed` to `Troubleshooting SSH`

### ISSUE THREAD

**Issue by jsoref** [github/docs#19283]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/troubleshooting-ssh

### What part(s) of the article would you like to see updated?

Create a new page for `host key verification failed`

* It should explain how to determine the current public keys for github, possibly by linking to: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints, although iirc there's also a server api which ideally should be reachable from that page but is not.

* It could provide a bit of information about the general state

* It should explain how to check, confirm, and accept the keys if they're correct.

### Additional information

* https://github.community/search?q=host%20key%20verification%20failed
* https://github.community/t/git-host-key-verification-failed/227295/1

**Comment by cmwilson21** [comment]
@jsoref Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @jsoref, I agree that would be a useful article to add. You or anyone else is welcome to open a PR doing so!

**Comment by jsoref** [comment]
Err, I didn't realize that there was a bot that killed todos.

**Comment by jsoref** [comment]
@cmwilson21...  I am I in the process of writing up a list of things that the bot gets wrong...

**Comment by cmwilson21** [comment]
@jsoref We are investigating the recent hiccups with stalebot. Sorry for the noise it's creating. We're looking into it! 👍
