### ISSUE TITLE
Language search tags displaying as empty when the repo contains code of that tag

### ISSUE THREAD

**Issue by tannerdolby** [github/docs#19280]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Steps to reproduce:
1. Visit 'https://github.com/tannerdolby/binary-messenger'
2. Click on the 'Java' from the languages section.
3. See error 'We couldn’t find any code matching '' in [tannerdolby/binary-messenger](https://github.com/tannerdolby/binary-messenger)'

Issues: 
- The search result doesn't display the language tag and instead just displays an empty string.
- The "java" language tag should display in the search results and show the expected files because the repo that I have shared a link for is all .java files outside of the README.md, .gitignore etc.

https://github.com/tannerdolby/binary-messenger/search?l=java

<img width="1271" alt="Screen Shot 2022-07-24 at 7 56 03 PM" src="https://user-images.githubusercontent.com/48612525/180688281-a75d8b01-18a9-4241-a778-a45dc84c7c1d.png">

### What part(s) of the article would you like to see updated?

I would like to see the language tag persist on the page even if the repo doesn't contain files of that language tag. And in this scenario, the code files aren't displaying when the "java" language is the majority of the repository.

### Additional information

I wasn't sure if this repo was the appropriate place to raise the issue, so feel free to direct me to the correct repo if that is the case. Thanks!

**Comment by tannerdolby** [comment]
This seems to be resolved now. I'm not sure if a patch was implemented or if my original issue was an anomaly, but I will keep this open for a few days before closing in case anymore discussion continues.

<img width="1273" alt="Screen Shot 2022-07-25 at 9 04 03 AM" src="https://user-images.githubusercontent.com/48612525/180823838-c1da04ca-10c2-4c4c-8e00-efb330968baa.png">

**Comment by cmwilson21** [comment]
@tannerdolby Thanks for opening the issue and reporting back on it as well. I'm happy to hear that it is resolved now! 🎉

This doesn't really fall within the reach of the Docs team. If this were to come up again, I think a better place to bring up the issue would be with our awesome [support team](https://support.github.com/request). I'll go ahead and close this issue now.

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue. 💛

**Comment by tannerdolby** [comment]
@cmwilson21 No problem! Thank you for the quick response. Yes, the issue seems to be resolved! 🎉

Okay, thanks for the clarification. I will make sure to bring up these types of issues with the [support team](https://support.github.com/request) if I ever encounter something like this again that doesn't fall into the reach of the Docs team.

I appreciate the info and will do! 👍

**Comment by cmwilson21** [comment]
Sounds great! Thanks, @tannerdolby! 👍
