### ISSUE TITLE
githubs-ssh-key-fingerprints should link to rest/meta

### ISSUE THREAD

**Issue by jsoref** [github/docs#19282]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

### What part(s) of the article would you like to see updated?

It might make sense to link to https://docs.github.com/en/rest/meta#get-github-meta-information and explain that it's related to `ssh_key_fingerprints`

### Additional information

```
SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 (RSA)
SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM (ECDSA)
SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU (Ed25519)
```

```
  "ssh_key_fingerprints": {
    "SHA256_RSA": "nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8",
    "SHA256_DSA": "br9IjFspm1vxR3iA35FWE+4VTyz1hYVLIE2t1/CeyWQ",
    "SHA256_ECDSA": "p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM",
    "SHA256_ED25519": "+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU"
  },
```

---
[maintainer edit]
### Content plan
Add the above link to the referenced doc. See the [links](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#links) section in the content guide for directions in adding links.

**Comment by cmwilson21** [comment]
@jsoref Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for this issue! You are anyone else is welcome to add this link to the docs.

**Comment by Alotibi11** [comment]
T

**Comment by Alotibi11** [comment]
K
