### ISSUE TITLE
`triggering_actor` is not listed in the `github` context

### ISSUE THREAD

**Issue by korosuke613** [github/docs#19307]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Contexts - GitHub Docs
https://docs.github.com/en/actions/learn-github-actions/contexts

https://github.com/github/docs/blob/b2f87cd6a0ddd32baba98455e0f56d7bc5a58fd0/content/actions/learn-github-actions/contexts.md

### What part(s) of the article would you like to see updated?

The recent changelog([Differentiating triggering actor from executing actor | GitHub Changelog](https://github.blog/changelog/2022-07-19-differentiating-triggering-actor-from-executing-actor/)) says that the `github` context has a triggering_actor field, but the contexts page does not have that information.

I would like to see a description of what kind of information `triggering_actor` has.

**Comment by cmwilson21** [comment]
@korosuke613 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by martin389** [comment]
👋 The docs have just been updated, and you'll be able to find an explanation of `github.triggering_actor` here: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

**Comment by korosuke613** [comment]
Thanks!
