### ISSUE TITLE
Fix docs to say that Github wiki Internal link format doesn't match MediaWiki link format

### ISSUE THREAD

**Issue by abdullin** [github/docs#19312]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content

### What changes are you suggesting?

Documentation says that github docs use MediaWiki syntax:

With MediaWiki syntax, the link syntax is [[Link Text|nameofwikipage]].
This is incorrect. While MediaWiki syntax is exactly the opposite, as documented in [MediaWiki Links](https://www.mediawiki.org/wiki/Help:Links): [[nameofwikipage|Link Text]]

I suggest to make it explicit that Github wiki uses an ad-hoc interpretation of wikilinks, that isn't compatible with [MediaWiki internal links](https://www.mediawiki.org/wiki/Help:Links#Internal_links) or [Wikipedia internal links](https://en.wikipedia.org/wiki/Help:Link#Wikilinks_(internal_links)).

**Comment by cmwilson21** [comment]
@abdullin Thanks for opening an issue - I'm not sure why the bot closed your first one out, but we appreciate you opening another! 💛 

I'll get this triaged for the team to take a look 👀

**Comment by abdullin** [comment]
@cmwilson21 thanks.

The bot was right - I forgot to fill the proper issue title :)

**Comment by cmwilson21** [comment]
@abdullin Gotcha! Thanks for letting me know. I was thinking our bot was on the fritz. 😄

**Comment by SiaraMist** [comment]
Thank you for your suggestion! ✨ You or anyone else can feel free to open a pull request to update the example in the Adding Links section to say `[[nameofwikipage|LinkText]]`, instead of the current order.

**Comment by matthew0420** [comment]
Submitted a fix at https://github.com/github/docs/compare/main...matthew0420:docs:patch-1

**Comment by cmwilson21** [comment]
@matthew0420 Thanks for making a fix. ✨ 

Can you open a [pull request](https://github.com/github/docs/blob/main/CONTRIBUTING.md#pull-request) for it? ⚡

**Comment by matthew0420** [comment]
@cmwilson21 Pull request should be up, link here: https://github.com/github/docs/pull/19710
