### ISSUE TITLE
Difficulty finding a post I just published from my Github Page

### ISSUE THREAD

**Issue by szunami** [github/docs#1933]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/adding-content-to-your-github-pages-site-using-jekyll

### What part(s) of the article would you like to see updated?

In the step by step instructions to create a post, it would be helpful to describe *where* the post gets published to. I found the publishing URL to be a bit unintuitive.

### Additional information

I opened https://github.com/github/docs/pull/1931 to address this.

**Comment by felicitymay** [comment]
Thank you so much for taking the time to raise an issue when you found a gap in the instructions - that's so helpful. 💖 

AND, you've raised a PR to fix it! 😄 🙇🏻‍♀️
