### ISSUE TITLE
Replace cross-marks ✖️ with tick-marks ✔️ to better represent permissions

### ISSUE THREAD

**Issue by pronoym99** [github/docs#19503]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Managing access to your organisations](https://docs.github.com/en/enterprise-server@3.6/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization)

### What part(s) of the article would you like to see updated?

- The tables describing the permissions for each role are better represented by ✔️ instead of the given ✖️ which would make them more intuitive to read.
- On a personal level, while reading the documentation, I felt that the crosses represented _permissions that weren't available_ as opposed to _which were_. The change would mitigate similar confusion in the future.
- The expected outcome is all the cross-marks replaced with checkmarks of theme-appropriate colour.

**Comment by cmwilson21** [comment]
@pronoym99 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
