### ISSUE TITLE
Update setup-java instructions to recommend Java 17 and Temurin

### ISSUE THREAD

**Issue by gdams** [github/docs#19526]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-java-with-ant
- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-java-with-maven
- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

### What part(s) of the article would you like to see updated?

The setup-java steps should recommend Java 17 as it's the latest LTS

Also switch to `temurin` as it has replaced `adopt`

**Comment by cmwilson21** [comment]
@gdams Thanks for opening an issue and linking it to your PR! 💛

**Comment by gdams** [comment]
CC @maxim-lobanov this one likely needs your approval. Also for added context this PR matches the basic suggested configuration on the setup-java docs https://github.com/marketplace/actions/setup-java-jdk#basic
