### ISSUE TITLE
Add help to install NuGet packages from a different repository

### ISSUE THREAD

**Issue by rafaelschlatter** [github/docs#19541]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry

### What part(s) of the article would you like to see updated?

The "Troubleshooting" needs an additional bulletpoint, explaining what to do to install a NuGet package from a different repository. This is important in my view since installing a package from a different repository is more common that publishing and installing the NuGet package from the same repository.

The way to solve this is by using a personal access token (PAT) in the `dotnet nuget add source` command. This would also clarify that using a PAT for authentication within a GitHub action is perfectly fine (the current structure of the doc indicates that using a PAT is only possible within a *nuget.config* file.

**Comment by cmwilson21** [comment]
@rafaelschlatter thanks for opening an issue and PR! 💖
