### ISSUE TITLE
Dropdown button is not readable on mouse hover

### ISSUE THREAD

**Issue by albinpk** [github/docs#19590]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The `Free, Pro & Team` dropdown button is not readable on mouse hover

**Page affected:** https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues

**Browser:** Brave 1.42.86

**Screenshot:**

![screenshot](https://user-images.githubusercontent.com/56157868/183340762-ab44501e-a2b6-4a77-8133-b05d406ee85b.jpeg)

### What changes are you suggesting?

Change the button hover style

**Comment by cmwilson21** [comment]
@albinpk Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by rachmari** [comment]
@albinpk thank you for reporting this! I've opened an internal issue to get this fixed. We'll let you know when we've got an update in place. 🙇

**Comment by albinpk** [comment]
You're welcome

**Comment by cmwilson21** [comment]
👋 Since this has been moved for internal work, I'm going to go ahead and close out this issue. 

Thanks again for your passion for improving our docs! 💖

**Comment by rachmari** [comment]
@albinpk we've put a fix in place. Thanks for reporting this, and please let us know if you're still seeing the issue.
