### ISSUE TITLE
outdated screenshot on renaming a repository page

### ISSUE THREAD

**Issue by brownsarahm** [github/docs#19605]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[renaming a repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository)

### What part(s) of the article would you like to see updated?

![outdated screenshot](https://docs.github.com/assets/cb-14983/images/help/repository/repository-name-change.png)
the screenshot for step 3 is outdated
- it shows the default branch setting below repository name instead of the toggles for tempalte and sign off
- it shows the default branch as "master"

An up  to date screenshot should match the current user experience and more importantly, match the change to `main` from master as the default branch. 

current: 
<img width="1111" alt="Screen Shot 2022-08-08 at 8 31 54 PM" src="https://user-images.githubusercontent.com/10656079/183537387-af901ba8-7fd7-4825-98dd-87590dfe60fb.png">
h

**Comment by cmwilson21** [comment]
@brownsarahm Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by mchammer01** [comment]
@brownsarahm - thanks so much for noticing that this screenshot was outdated 🙈 
I will fix this in our internal repo as this relates to screenshots ⚡

**Comment by mchammer01** [comment]
@cmwilson21 - I raised an internal issue for this and will fix this during my review hour today 😃 
Can I close this?

**Comment by cmwilson21** [comment]
SGTM! Thank you @mchammer01!! :tada:
