### ISSUE TITLE
Issue templates are only case insensitive initially. 

### ISSUE THREAD

**Issue by calebboyd** [github/docs#19655]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

### What part(s) of the article would you like to see updated?

>Issue template filenames are not case sensitive, and need a .md extension

It appears that the issue templates may be case in-sensivive initially, but do not work if the case changes at a later time.

### Additional information

For example, before [this commit](https://github.com/nexe/nexe/commit/1eeac1b538098352508b6af77faf71bd2409c55f) (after the original and before the revert) that changed the file name casing, the issue templates did not work.

**Comment by cmwilson21** [comment]
@calebboyd Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@calebboyd Thanks for your patience on this one as we are working through our backlog ✨ 

I spoke with the team and we noticed that in the commits linked above, it's the name of the folder that is being changed, not the template name itself. If the name of the folder is changed, the template cannot be selected anymore when an issue is created. 

I hope that helps. If not, please let us know. I'm going to go ahead and close this issue now. 💛
