### ISSUE TITLE
OIDC on AWS documentation improvement

### ISSUE THREAD

**Issue by baolsen** [github/docs#19656]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

### What part(s) of the article would you like to see updated?

IAM policy currently only shows a snippet and should have a full almost-working example

**Comment by baolsen** [comment]
I've submitted a PR, the build is failing because it is modifying restricted files.
However this issue requires those files to be modified... Happy for suggestions

**Comment by baolsen** [comment]
Relates to #15324

**Comment by cmwilson21** [comment]
@baolsen Thanks for opening an issue and PR!

**Comment by Eikyarkway** [comment]
plz
