### ISSUE TITLE
Search merges lines from tables w/o whitespace

### ISSUE THREAD

**Issue by jsoref** [github/docs#19667]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/environment-variables?query=macos

![image](https://user-images.githubusercontent.com/2119212/184026007-c2537d49-31cb-494d-931f-276f144b81d5.png)

Here's the highlighted source text in context:
https://docs.github.com/en/actions/learn-github-actions/environment-variables
![image](https://user-images.githubusercontent.com/2119212/184026038-52c01ed0-04f7-478f-aab6-38d89dd13303.png)

### What changes are you suggesting?

When drawing content from multiple table rows, include at least one whitespace between the content.

**Comment by tyntyn1** [comment]
@t-dedah @jsoref @jsoref @bruce

**Comment by cmwilson21** [comment]
@jsoref 👋 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by RamonaReitz** [comment]
https://vscode.dev/liveshare/377539EA169F43BA66091C8608121F955A35

**Comment by peterbe** [comment]
Thanks so much for opening an issue! We've got an internal issue tracking this, so I'm going to close this one ✨ 

(note-to-self; it's issue # 2019)
