### ISSUE TITLE
Dead link on Github Classroom: Leave feedback with pull requests

### ISSUE THREAD

**Issue by harryclegg** [github/docs#1969]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/education/manage-coursework-with-github-classroom/leave-feedback-with-pull-requests

### What part(s) of the article would you like to see updated?

In the Further Reading section, there is a link to a related page:

    "Integrate GitHub Classroom with an IDE"

The link points to `localhost:4000...`, presumably from when the page was being tested on a local machine, rather than to the [real page](https://docs.github.com/en/free-pro-team@latest/education/manage-coursework-with-github-classroom/integrate-github-classroom-with-an-ide).

### Additional information

N/A.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue to let us know @harryclegg! We'll get that fixed up soon ⚡

**Comment by felicitymay** [comment]
👋🏻 Hi @harryclegg 

Many thanks for letting us know about this broken link, it was a great help. ✨ 
We've fixed it as part of an internal bug bash.
