### ISSUE TITLE
Token for graphql explorer should have read:project access

### ISSUE THREAD

**Issue by marosset** [github/docs#19712]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql and https://docs.github.com/en/graphql/overview/explorer

### What part(s) of the article would you like to see updated?

Currently it is not possible to execute queries in the GraphQL explorer against `ProjectV2` resources because the signed in account has insufficient scope.

Executing the following query 

```json
{
  user(login: "some-repo") {
    projectV2(number: 1) {
      shortDescription
      id
    }
  }
}
```

yields the following error

```json
{
  "errors": [
    {
      "type": "INSUFFICIENT_SCOPES",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "message": "Your token has not been granted the required scopes to execute this query. The 'projectV2' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['read:discussion', 'read:enterprise', 'read:gpg_key', 'read:org', 'read:packages', 'read:public_key', 'read:repo_hook', 'repo', 'user'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens."
    },
    {
      "type": "INSUFFICIENT_SCOPES",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "message": "Your token has not been granted the required scopes to execute this query. The 'shortDescription' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['read:discussion', 'read:enterprise', 'read:gpg_key', 'read:org', 'read:packages', 'read:public_key', 'read:repo_hook', 'repo', 'user'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens."
    },
    {
      "type": "INSUFFICIENT_SCOPES",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "message": "Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['read:discussion', 'read:enterprise', 'read:gpg_key', 'read:org', 'read:packages', 'read:public_key', 'read:repo_hook', 'repo', 'user'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens."
    }
  ]
}
```

It would be great if we could use the graphql explorer to introspect project/projectv2 objects!

**Comment by marosset** [comment]
@omerbensaadon

**Comment by codingcodymiller** [comment]
Seconding this issue. I attempted to include an Authorization header manually in the GraphQL Explorer's pane for providing request headers, but those headers are not being applied to the request at all either (Actual token replaced with filler value for the sake of the visual). [This page of the documentation](https://docs.github.com/en/graphql/guides/using-the-explorer) seems to be covering an outdated way to apply headers in the Explorer, since the menu it showcases is not actually present in the Explorer.
![image](https://user-images.githubusercontent.com/32880187/18442461
![Screen Shot 2022-08-12 at 11 55 14 AM](https://user-images.githubusercontent.com/32880187/184425244-eb7f4dd0-ea76-42aa-bf6f-c963f27a1f21.png)
9-42f766e9-da8d-4a39-855c-e112a3723ef5.png)

**Comment by cmwilson21** [comment]
@marosset Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by timrogers** [comment]
👋🏻 Thanks for reporting this issue. It should now be fixed. You'll need to sign out of the GraphQL Explorer and then sign in again to make sure that the correct permissions are available.

**Comment by marosset** [comment]
@cmwilson21 @timrogers  - I signed out and in again and am able to query projectV2 objects via the GraphQL Explorer.
Thank you for the quick turnaround!
