### ISSUE TITLE
Missing 'runs.' on post-entrypoint configuration for dockefile actions

### ISSUE THREAD

**Issue by rlespinasse** [github/docs#19742]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#post-entrypoint

### What part(s) of the article would you like to see updated?

the 'runs for Docker container actions' part for the 'post-entrypoint' option

**Comment by cmwilson21** [comment]
@rlespinasse Thanks for opening an issue and linking it to your PR! 💖
