### ISSUE TITLE
Thanks very much for contributing! Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our [help wanted issues](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) :zap:

### ISSUE THREAD

**Issue by Fulya2133** [github/docs#19808]
Thanks very much for contributing! Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our [help wanted issues](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) :zap:

_Originally posted by @github-actions[bot] in https://github.com/github/docs/issues/6624#issuecomment-845463560_

**Comment by TeerasakSinghnoi17** [comment]
<!DOTYPE html>
<x-foo id="a"></x-foo>
<x-foo id="b"></x-foo>

<script>
//Defining enquees upgrade reactions for both "a"and"b"customElements.define security-camera-footage
cconstructor(){
super();
