### ISSUE TITLE
Examples of CODEOWNERS ! negation

### ISSUE THREAD

**Issue by jamesbraza** [github/docs#19818]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What changes are you suggesting?

Currently for negation, there is one mention of it in the docs:

> Using `!` to negate a pattern

There should be an example showing a negation.  I am struggling to figure out how to use this feature.

GitHub UI is saying "invalid pattern" for either of these:

```
!directory/* @some-owner
! directory/* @some-owner
```

I think an example would be a great way to spell out how to do negation.

**Comment by janiceilene** [comment]
👋 @jamesbraza The section of the docs that includes the `!` syntax says:

> Syntax exceptions
> There are some syntax rules for gitignore files that do not work in CODEOWNERS files:

> Escaping a pattern starting with # using \ so it is treated as a pattern and not a comment
> Using ! to negate a pattern
> Using [ ] to define a character range

The patterns listed there `\`, `!`, and `[ ]` do not work in CODEOWNERS files, so we are not going to add any examples.

Thanks so much for opening an issue!

**Comment by jamesbraza** [comment]
HA that is funny, I must have totally misread the docs.  Thank you @janiceilene!

**Comment by JasonWHowell** [comment]
Oddly, I misread the doc to say it worked, instead of NOT worked. It spent 30 minutes until I found this issue and reread it as "do not work". I wish each example said "Doesn't work at the end of the sentence. 

During my futile testing, I found using ! still validates. Is that a bug, or does it treat the ! as a literal?
![image](https://github.com/user-attachments/assets/043a1f49-734d-4f61-8920-895b189a9c5c)

**Comment by nguyenalex836** [comment]
> During my futile testing, I found using ! still validates. Is that a bug, or does it treat the ! as a literal?

@subatoi Would you have any insight on this? 🤔

**Comment by subatoi** [comment]
👋 Thanks for the ping. I'm hoping the following will help:

* I have no problem with creating an issue to add "doesn't work" to each of the three sentences, and opening it to contributors. We have a freeze this week, but can happily merge it next week if it's been raised by then

* The negation syntax will only "work" with a space between `!` and the target, so this will count as valid CODEOWNERS syntax—I'm hoping that my point above will clarify the situation for any future readers sufficiently, though (ie don't expect negation syntax to work at all)

**Comment by nguyenalex836** [comment]
> I have no problem with creating an issue to add "doesn't work" to each of the three sentences in question, and opening it to contributors.

I've opened the following issue to have the doc updated! https://github.com/github/docs/issues/34805
