### ISSUE TITLE
Best practices for security advisories doc should use positive statements

### ISSUE THREAD

**Issue by GeekTrainer** [github/docs#19825]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/code-security/repository-security-advisories/about-coordinated-disclosure-of-security-vulnerabilities#best-practices-for-vulnerability-reporters

### What part(s) of the article would you like to see updated?

Best practices should be updated to use positive statements rather than negative. Typically people are expecting a list of what *to* do, rather than what *not* to do.

**Comment by janiceilene** [comment]
We're going to keep the language, so I'm going to close this. See PR comments for details:
- https://github.com/github/docs/pull/19826#issuecomment-1216665424
- https://github.com/github/docs/pull/19826#issuecomment-1216677431
