### ISSUE TITLE
Github Action page CSS break

### ISSUE THREAD

**Issue by kanishak11-cyber** [github/docs#19862]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/guides

![image](https://user-images.githubusercontent.com/84625838/184939235-e615c845-3103-45f1-9477-57f78ddcd77a.png)

### What changes are you suggesting?

fixing the CSS of this pages by using Display properties.

**Comment by cmwilson21** [comment]
@kanishak11-cyber Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by kanishak11-cyber** [comment]
@cmwilson21 
![image](https://user-images.githubusercontent.com/84625838/185181163-64c1aef3-963b-4fee-84d2-712160511f9a.png)
I also facing this issue

**Comment by peterbe** [comment]
Unable to reproduce. Did I miss something @kanishak11-cyber ?

https://user-images.githubusercontent.com/26739/185217554-0948b6bb-5e52-40b1-a6d6-37908738206a.mov

**Comment by cmwilson21** [comment]
Maybe it's specific to dark mode? I'm getting a bit of it, too.

![Screen Shot 2022-08-17 at 2 44 53 PM](https://user-images.githubusercontent.com/77312589/185229018-b7aedcb4-0d25-4735-aeb4-d974af881042.png)

**Comment by aitemour79** [comment]
***@***.*** com

**Comment by aitemour79** [comment]
***@***.*** com

**Comment by kanishak11-cyber** [comment]
> Unable to reproduce. Did I miss something @kanishak11-cyber ?
> 
>  Screen.Recording.2022-08-17.at.2.39.37.PM.mov

Im using dark Theme maybe it is in dark theme
