### ISSUE TITLE
Update SSH Port 443 process to be useful.

### ISSUE THREAD

**Issue by rp-jasonp** [github/docs#19869]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port
https://docs.github.com/en/get-started/using-github/troubleshooting-connectivity-problems

### What changes are you suggesting?

- Missing alternative in general troubleshooting to promote use of SSH over port 443.
- Missing Emphasis that hostname changes to ssh.github.com
- Missing repository example for git client rewrite to use 443 (vs ssh config)
- Missing Known host changes that may be needed to use port 443.

**Comment by cmwilson21** [comment]
@rp-jasonp Thanks for opening an issue and PR! ⚡

**Comment by Mohsinmrs** [comment]
Mrs.d.com
Great day Job in Pakistan

**Comment by 62854444628** [comment]
``
