### ISSUE TITLE
Fix misleading example of reusable workflows

### ISSUE THREAD

**Issue by dne** [github/docs#19904]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows

### What part(s) of the article would you like to see updated?

The [example reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow) in this article can lead newcomers to mix up reusable workflows with [local actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow).

A recent change from #15481 made this worse/more misleading. I propose to at least revert c9186d07c3681362b9707d6a88f8678cee8ab3b1 and maybe add a comment that the example references an action not a reusable workflow.

### Additional information

I just spent some time trying (and failing) to use a reusable workflow as a step in a workflow job because I was mislead by this example, as have [other users](https://github.com/orgs/community/discussions/27362) apparently.

**Comment by cmwilson21** [comment]
@dne Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
👋 @dne, thanks a lot for pointing this out! You are 100% correct; feel free for yourself (or anyone) to open a PR. Otherwise I should get to it in the next few days.
