### ISSUE TITLE
Web commit signing docs mention a restriction that isn't necessary

### ISSUE THREAD

**Issue by darthwillis** [github/docs#19959]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-your-enterprise/configuring-web-commit-signing

### What part(s) of the article would you like to see updated?

The article says that you must use `web-flow` as the username when configuring the different aspects of web-commit signing. It turns out that there is no requirement for the username to be `web-flow`. There is only a requirement that the username is consistent across all of the steps.

We had a customer who was restricted from making a user named `web-flow` so they assumed they were blocked.

I would like to update the article to reflect the reality, and give web-flow as an example user name.

**Comment by cmwilson21** [comment]
👋 @darthwillis Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by darthwillis** [comment]
@cmwilson21 Thank you! I was actually working on a PR yesterday with a suggested update. I'll link it here if I finish it up and would appreciate any input or feedback!

**Comment by cmwilson21** [comment]
Sounds great! I'll mark it as "On hold" until you finish the PR, that way our reviewers know you are still working on it.

**Comment by lecoursen** [comment]
Thanks @darthwillis! I agree we should update the docs to clarify this. Definitely let us know when your PR is ready for review. 😊

**Comment by darthwillis** [comment]
Thanks @cmwilson21 and @lecoursen - I am First Responder this week so I got delayed on making the changes. I'll ping as soon as I have a PR up.

**Comment by darthwillis** [comment]
@cmwilson21 @lecoursen Hello! Sorry for the delay here. I have a PR up for this now: https://github.com/github/docs-internal/pull/30797
