### ISSUE TITLE
Fix ja-JP contexts.md layout

### ISSUE THREAD

**Issue by bells17** [github/docs#20026]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This page: https://docs.github.com/ja/actions/learn-github-actions/contexts#context-availability

### What part(s) of the article would you like to see updated?

layout bug

<img width="1668" alt="1コンテキスト_-_GitHub_Docs" src="https://user-images.githubusercontent.com/2158863/185787346-4eea33dc-02c5-4410-bb28-c60f231cdd49.png">

**Comment by bells17** [comment]
PR: https://github.com/github/docs/pull/20027

**Comment by cmwilson21** [comment]
@bells17 Thanks for opening an issue and linking it to your PR!

**Comment by cmwilson21** [comment]
Closing this now as I've submitted an internal issue to fix this. See my comment on the PR for more information 💛
