### ISSUE TITLE
Table layout is broken in the ja-JP of the document

### ISSUE THREAD

**Issue by tosaka-n** [github/docs#20075]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ja/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role

### What part(s) of the article would you like to see updated?

- like this https://github.com/github/docs/pull/20073
- I cannot make a contribution due to changes in the translation file only, but I believe that changes such as this PR are necessary

### Additional information

![](https://user-images.githubusercontent.com/31643545/186089942-12fcd82d-5e09-43e7-8af2-c5568247231f.png)

**Comment by cmwilson21** [comment]
Thanks for reporting this! Closing this issue now per [PR comment](https://github.com/github/docs/pull/20073#issuecomment-1224049876).
