### ISSUE TITLE
Github draft blog is out of date

### ISSUE THREAD

**Issue by bashirmindee** [github/docs#20078]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Step six here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request)

When someone wants to open a Draft Pull request, he can't find a button to do so. He will have to open the Pull request, and then make it Draft.
Also there is no documentation on the internet about where to find this button. And the documentation in https://github.blog/2019-02-14-introducing-draft-pull-requests/ is completely out of date. 

### What part(s) of the article would you like to see updated?

I would like to have the whole article removed and replaced by a new one

**Comment by cmwilson21** [comment]
@bashirmindee Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@bashirmindee Thanks again for opening this issue! ✨ 

The blog post you linked to is dated 2019. GitHub blogs are snapshots of a feature or improvement and will become outdated as the feature is updated. These blogs announce features as opposed to documenting them.

Draft pull requests are available in public repositories with GitHub Free for organizations and public and private repositories with GitHub Team, GitHub Enterprise Server 2.17+, and GitHub Enterprise Cloud. For more information, see "[Draft pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests)."

I hope that clears up any questions you have. I'm going to go ahead and close this issue now. 💛
