### ISSUE TITLE
dropdown content is outside the container

### ISSUE THREAD

**Issue by Arhell** [github/docs#2008]
### What is the current behavior?
dropdown content is slightly outside the container on tablet

![1](https://user-images.githubusercontent.com/26163841/101939285-74ee6300-3bed-11eb-9b30-1c55e9b1313a.jpg)

### What changes are you suggesting?
small ccs fix

**Comment by janiceilene** [comment]
Thanks for opening an issue @Arhell ✨ I'll triage this for the team to take a look 👀

**Comment by Arhell** [comment]
@janiceilene done in https://github.com/github/docs/pull/2021
