### ISSUE TITLE
Add a dev container configuration to your repository (Node.js)

### ISSUE THREAD

**Issue by timdeschryver** [github/docs#20094]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-project-for-codespaces

### What part(s) of the article would you like to see updated?

I was setting up my own codespace dev container, I followed the guide from the docs.
While following the guide I noticed that the screenshots and the code snippets are outdated and are based on an older version of Node.js.

To give some examples (notice the different Node.js versions that are used):

Docs:

![image](https://user-images.githubusercontent.com/28659384/186236174-81a59fcb-0bdb-401e-b2b3-3e6cb3947c77.png)

The dropdown we get to see today: 

![3](https://user-images.githubusercontent.com/28659384/186236273-90d5d801-2d2e-4f1c-8fb2-eeb7bf753dec.png)

Or the devcontainer.json version that is used in the docs:

```json
{
  "name": "Node.js",
  "build": {
    "dockerfile": "Dockerfile",
    // Update 'VARIANT' to pick a Node version: 10, 12, 14
    "args": { "VARIANT": "14" }
  }
}
```

Compared to the current version of the json:

```json
{
  "name": "Node.js",
  "build": {
    "dockerfile": "Dockerfile",
    // Update 'VARIANT' to pick a Node version: 18, 16, 14.
    // Append -bullseye or -buster to pin to an OS version.
    // Use -bullseye variants on local arm64/Apple Silicon.
    "args": { "VARIANT": "16-bullseye" }
  }
}
```

### Additional information

If approved, I can create a Pull Request to make the guide up-to-date with the latest screenshots and code snippets.

**Comment by cmwilson21** [comment]
@timdeschryver Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by hubwriter** [comment]
@timdeschryver - Many thanks for raising this issue.

We definitely need to get this updated. 👍 

We are due to be making changes to that page. I will therefore close this issue and take the information you have supplied above and copy it over into our internal issue for the other changes so that we do this at the same time.

Thanks again
