### ISSUE TITLE
Grammar fix on deployments page

### ISSUE THREAD

**Issue by michael-robertson** [github/docs#20112]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/deployments/deployments

### What part(s) of the article would you like to see updated?

"These events allows third-party integrations to receive respond to deployment requests"
Intent is clear, just needs a couple small fixes.

**Comment by cmwilson21** [comment]
@michael-robertson Thanks for opening an issue and linking it to your PR! ⚡
