### ISSUE TITLE
SSH config PubkeyAcceptedKeyTypes directive for Error: Permission denied (publickey)

### ISSUE THREAD

**Issue by srbdev** [github/docs#20137]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Error: Permission denied (publickey)](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey)

### What part(s) of the article would you like to see updated?

Creating a new section about adding the `PubkeyAcceptedKeyTypes +ssh-ed25519` directive to the user's `~/.ssh/config` file to fix the `Error: Permission denied (publickey)` issue, and this seems to affect macOS 12.3 with Git version 2.32.1.

**Comment by cmwilson21** [comment]
@srbdev Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by vtbassmatt** [comment]
👋 hi there from the product manager for Git Systems at GitHub. I don't have a 12.3 machine handy to test this out, and my searching failed to turn up much that was related. @srbdev do you have any links handy which showcase this problem and/or solution? I'm not looking for a high burden of "proof" here, but I want to understand how common it is, which versions of macOS / Git it's likely to span, and so on. Thanks!

**Comment by srbdev** [comment]
I believe I adjusted the solution from this StackOverflow post: https://stackoverflow.com/a/35681481. Note that I have run into this same issue with trying to SSH to other systems from newer clients (Fedora 36 when it was first released and this new mac) whereas I could still SSH into these same systems from "older" clients (Debian, older macOS, etc.). This is what makes me think that is a client issue, and maybe not a server configuration issue. Hope that helps!

**Comment by vtbassmatt** [comment]
🙇 thank you for the pointer. I saw plenty of cases where macOS deprecated DSA keys, and those steps were the workaround. In that case, the instructions are to bring back something macOS had taken away.

What I couldn't find was any discussion of a recent-ish macOS having trouble using Ed25519 keys. Those are newer, and I can't figure out when macOS first shipped an SSH version capable of using them. And it seems odd (to me, anyhow) for any macOS release to support that key type but have it turned off by default.

**Comment by adhammahdi** [comment]
غ

**Comment by cmwilson21** [comment]
👋 Hey all. I'm going to go ahead and close this issue out due to inactivity. If I'm missing the obvious "next steps" please feel free to ping me or reopen this issue. I'm also wondering if this issue has been fixed with the latest updates. Again, if the same problem persists, please reach back out 💖
