### ISSUE TITLE
Case of X-Hub-Signature-256 header is incorrect in "Securing your webhooks" topic

### ISSUE THREAD

**Issue by Jerry-AWS** [github/docs#20134]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

"Securing your webhooks" https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks

### What part(s) of the article would you like to see updated?

The HTTP headers that holds the request signature is given as `X-Hub-Signature-256`. It is actually sent by GitHub as `x-hub-signature-256`. In some environments, case matters. (In the Ruby example given, it doesn't matter, because the value is accessed through an Apache HTTP environment variable where the name gets mangled into all uppercase.)

My webhook is an AWS Lambda function and the headers are provided as part of the JSON event record, so I had to log the headers to see what the actual casing was when the documented header name didn't work.

**Comment by cmwilson21** [comment]
@Jerry-AWS thanks for opening an issue and linking it to your PR! ✨
