### ISSUE TITLE
Consistent use of the plural form of `repository`

### ISSUE THREAD

**Issue by rajbos** [github/docs#20136]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

A lot! Check this search: https://docs.github.com/en?query=repository's

### What part(s) of the article would you like to see updated?

Filenames (it's just strange) as well as the texts itself

### Additional information

Hi folks, I was going to edit [this page ](https://github.com/rajbos/docs/blob/patch-2/content/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview.md) to fix the name, since the plural of `repository` should be `repositories` in my opinion, and not `repository's`, but then I noticed more pages who suffer from this inconsistent use of the word. About a 10 pages have it in their content already, not sure about how many file names this is happening.

Therefor I wanted to reach out: what has the preference and can I start proposing PR's that link to this issue for this? 

I can image it is just updating the file name and add the original file path to the `redirect from` path. But is there anything else that needs an update then?

**Comment by codewithdev** [comment]
@rajbos Probably the use of "repository's" is correct in this page https://docs.github.com/en/repositories/releasing-projects-on-github/viewing-your-repositorys-releases-and-tags. However, the intro is only stating users to view releases and tags of a single repository.

**Comment by rajbos** [comment]
Indeed, there will be exceptions 😅. 

Question is more about the process to get this fixed 😀.

**Comment by cmwilson21** [comment]
👋 Hey @rajbos, thanks for opening an issue! I can definitely see how this could grab someone's attention. However, the references in the search titles are not plural but show possession of a single repository. So the files are correct with the singular form `repository` with an `'s` for possession. 

I hope that clears up things for the titles; I'm going to go ahead and close this issue 💛 

Thank you for your passion for improving the docs! ⚡
