### ISSUE TITLE
Managing Custom domain page > "Configuring a subdomain" > second example undifferentiated from first example

### ISSUE THREAD

**Issue by vincent-czi** [github/docs#20145]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

### What part(s) of the article would you like to see updated?

Current version of the "Configuring a subdomain" section has two different `www` subdomain examples, but I think the intention was for second subdomain example to be a non-`www` case. Looks like it was supposed to be `another` used as the subdomain in the second example, but instead the domain name was changed instead (`www.example.com` becoming `www.anotherexample.com`).

### Additional information

I've got a PR to fix this that will come hot on the heels of this issue (since the preference is to file an issue for every PR).

**Comment by cmwilson21** [comment]
@vincent-czi Thanks for opening and issue and submitting a PR! ✨
