### ISSUE TITLE
explain how to get LICENSE_KEYWORD 

### ISSUE THREAD

**Issue by 89z** [github/docs#20164]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-by-license

### What part(s) of the article would you like to see updated?

says use `license:LICENSE_KEYWORD`

but doesn't explain how to get that

for example, it says `Apache License 2.0` would be `apache-2.0`, does some list exist that shows keywords for all the major licenses?

**Comment by 89z** [comment]
Looks like this might work:

https://choosealicense.com/appendix

**Comment by cmwilson21** [comment]
@89z Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by 89z** [comment]
actually this looks way easier:

https://spdx.org/licenses

**Comment by cmwilson21** [comment]
@89z Thanks for bringing this up! In the sentence right before the example given, there's a link to "[Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)." From there, you can scroll down to "[Searching GitHub by license type](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type)" to see a list of common licenses and their keyword.

Thanks again for reaching out. I'm going to go ahead and close this issue. I hope this helps clear things up! 💛
