### ISSUE TITLE
UI Improvement: Issues with the navbar buttons and index sidebar

### ISSUE THREAD

**Issue by adarshajit** [github/docs#20182]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

![Screenshot from 2022-08-26 16-41-12](https://user-images.githubusercontent.com/50659234/186892342-de16c20b-02aa-48ab-9fd2-4555e41a6981.png)

### What changes are you suggesting?

Hi noticed some issues while going through this page.

- [ ] The text should still be visible after hover
- [ ] The text color of the index sidebar of the article is too light and hence difficult to read

Can I pick this up if it's okay?

### Additional information

I'm using `brave browser`

**Comment by cmwilson21** [comment]
@adarshajit Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by gracepark** [comment]
Hi @adarshajit - We're aware of the issue, and are looking into it. Thank you for reporting. This seems to be happening to a very small percentage of users whose OS color mode preference may be set different to GitHub. For e.g. we've seen this when the OS is set to dark and GitHub is set to light. Let me know if that is not the case!

**Comment by gracepark** [comment]
Awesome thanks for the confirmation. Since we are aware and looking through this, I'll close this issue for now. If anything else pops up please let us know! Thank you again!
