### ISSUE TITLE
Document how to accept an invitation to a repository/organization

### ISSUE THREAD

**Issue by jsoref** [github/docs#20191]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository
https://docs.github.com/en/organizations/managing-membership-in-your-organization/inviting-users-to-join-your-organization

### What part(s) of the article would you like to see updated?

There should be a page that explains how to accept invitations to repositories/organizations.

There are a couple of pieces to this:
1. There's probably an email _somewhere_, but if a user has multiple email accounts tied to their github account, the doc should explain which account(s) are likely to have that invitation
2. There's a way to see the invitation if you know the organization (or repository?) explicitly
3. There might be other ways, but as it isn't documented, and doesn't happen to me often, I can't speak to them.

If invitations will expire after some duration, that should be mentioned. If they won't expire, it's probably worth noting this as well.

If there are downsides to accepting an invitation (for instance, could someone's account get in trouble if they're left as the only owner of an organization whose content violates terms of service?), those should be mentioned (e.g. could their account be terminated?)

### Additional information

This comes up periodically, e.g.:
https://github.com/orgs/community/discussions/22529

---

It actually came up today for me as I just invited someone.
They were like "I don't see it".
I was like "yeah, I don't know where you'd find it. Check your email."
They responded with something like "Oh, it was in a different mailbox".

It felt like Mario:
![image](https://user-images.githubusercontent.com/2119212/186964248-4ff4dd27-bbce-498b-b1f6-c9adde85dd66.png)

**Comment by Akenndy** [comment]
SECURITY.md

**Comment by Akenndy** [comment]
SECURITY.md

**Comment by cmwilson21** [comment]
👋 @jsoref Thanks for opening an issue and for the Mario reference 🍄 

I'll triage this for the team to take a look! 👀

**Comment by cmwilson21** [comment]
👋 @jsoref I spoke with the team and we are not going to add this. Since notification settings differ from user to user, it would cause more confusion to document the various options.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by jsoref** [comment]
4. You can navigate directly to https://github.com/settings/organizations
