### ISSUE TITLE
Update  `issue_comment` link in GitHub Actions docs

### ISSUE THREAD

**Issue by jmarlena** [github/docs#2019]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issue_comment

### What part(s) of the article would you like to see updated?

<img width="1924" alt="issues" src="https://user-images.githubusercontent.com/31984004/101179511-9928cd80-364a-11eb-9393-ea5e018ef033.png">

 The redirect link as shown in the image above is not correct. The redirect link in `Issue_comment` should link to 

https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#issue_comment

instead of the current link.

### Additional information

In https://github.com/github/docs/blob/main/content/actions/reference/events-that-trigger-workflows.md: 
- [ ] Under `issue_comment`, update the webhook event link to https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#issue_comment

**Comment by Ashok314** [comment]
Thank you @jmarlena.
I have just created a PR #2030  fixing the previous link with the correct one.

**Comment by Rockwell79** [comment]
I need help fixing the issue
