### ISSUE TITLE
Clarify reporting abuse in comments when the user is not a contributor.

### ISSUE THREAD

**Issue by avalonv** [github/docs#20202]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam

### What changes are you suggesting?
The current doc states only collaborators may report comments on issues and PRs, which gives the impression non-collaborators cannot report specific instances of spam or harassment if they're not contributors. I think a clarification that you still can report a comment through the report user form might be useful for people that were confused about this implementation, such as myself.   

### Additional information

[maintainer edit]

### Content plan [here](https://github.com/github/docs/issues/20202#issuecomment-1252074141)

**Comment by avalonv** [comment]
Correction: I misunderstood the fact that the option to report abuse is only available to maintainers and collaborators. My bad.

**Comment by cmwilson21** [comment]
@avalonv Thanks for opening an issue and PR! ✨

**Comment by jules-p** [comment]
Hi @avalonv :wave: thank you for raising this issue. I think the pertinent information already exists in the article at line 14. What I would suggest we do is to move the paragraph at line 14 into a permissions statement in the front matter, which will give it more prominence. You can read more about that here: https://github.com/github/docs/blob/main/contributing/content-model.md#permissions-statements

You (or anyone else) are welcome to make that change in a new PR, and we will be happy to review it.

Thank you again for taking the time to contribute to our docs. :sparkles:

**Comment by oromogadaa** [comment]
Bkm

**Comment by oromogadaa** [comment]
Vintage
