### ISSUE TITLE
Remove extraneous `<em>` tags

### ISSUE THREAD

**Issue by PythonCoderAS** [github/docs#20217]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

### What part(s) of the article would you like to see updated?

A code block contains `<em>...</em>`, which I assume was functional prior to the port to Markdown but is no longer functional.

**Comment by cmwilson21** [comment]
@PythonCoderAS Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
