### ISSUE TITLE
Dismissing a review causes reviewed event to be in `dismissed` state

### ISSUE THREAD

**Issue by taylorhakes** [github/docs#20216]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#reviewed

### What changes are you suggesting?

Ideally change the behavior of the API to keep the state of the original review. Currently the state of the review is `dismissed` which is not a valid value in the enum. It is really important to keep the state of the original review somewhere, so we can see what happened.

### Additional information

To reproduce:
- Review a PR
- Have the author dismiss the review

The `reviewed` event is now in `dismissed` state instead of it's original review state

### Content plan [here](https://github.com/github/docs/issues/20216#issuecomment-1231996294)

**Comment by cmwilson21** [comment]
@taylorhakes Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@taylorhakes - Just for clarification, are you requesting a change in the documentation over dismissing a review? Or is this a request to update the behavior of the API?

**Comment by taylorhakes** [comment]
Hey @cmwilson21. I am requesting both. The immediate fix is to document this behavior in  the docs. It would be amazing to fix this behavior to show the original review state, but I don’t know how much work that would be because the code isn’t open source.

**Comment by cmwilson21** [comment]
Thanks for clarifying @taylorhakes! We can take a look at the documentation side. For the feature feedback, it would be best to leave that over in the [communities feedback discussions](https://github.com/community/community/discussions/categories/pull-requests).

We will check it out from the docs side of things. Thanks again for raising an issue! 💛

**Comment by skedwards88** [comment]
Thanks for this issue! You or anyone else is welcome to open a PR to update the docs to reflect that the `dismissed` state exists.

**Comment by nzbitcoinme** [comment]
Opensorce/runpandora/yh5aitec

**Comment by Anika-Roy** [comment]
Hi! I'd like to work on this. I'm not clear on what excactly needs to be changed. I'm just starting with open source so any help would be great:)

**Comment by cmwilson21** [comment]
@taylorhakes Sorry for the confusion - stalebot closed this one out when it shouldn't have been closed. Reopening and will triage your PR 👍

**Comment by pakonkiat2543** [comment]
ในวันที่ อ. 15 ส.ค. 2023 14:22 น. Ben Ahmady ***@***.***>
เขียนว่า:
