### ISSUE TITLE
Docs: Correct the word sprint to iteration

### ISSUE THREAD

**Issue by kashiwachen** [github/docs#20256]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[project-filters.md](https://github.com/github/docs/blob/main/data/reusables/projects/projects-filters.md) is gonna be affectet 

### What part(s) of the article would you like to see updated?

the document is using the word `iteration` instead of `sprint`, which makes the example(`sprint:@current`) not working.

### Additional information

Simply change the example to `interation:@current`

**Comment by cmwilson21** [comment]
@kashiwachen Thanks for opening an issue and PR! ⚡
