### ISSUE TITLE
Fix documentation of repository_visibility field in OIDC token

### ISSUE THREAD

**Issue by yogeshlonkar** [github/docs#20266]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token

### What part(s) of the article would you like to see updated?

Give as much detail as you can to help us understand the change you want to see.
- In _"Understanding the OIDC token"_ section example as well as field details contains wrong field name for repository visibility. The field `repo_visibility` should be `repository_visibility`

Why should the docs be changed? What use cases does it support?
- I spent more than couple of hour by referencing wrong field from from documentation. After debugging OIDC token I found the actual field name is different. This field is useful to configuring Workload identity federation with GCP and STS conditions in AWS to prevent from giving access to public repositories

What is the expected outcome?
- Providing correct information in documentation
- Saving development time

## Wrong references in example
<img width="990" alt="image" src="https://user-images.githubusercontent.com/10169201/187269270-78c64e46-ee84-43d6-9f15-67384beb5ded.png">

## Wrong references in field details
<img width="990" alt="image" src="https://user-images.githubusercontent.com/10169201/187269426-4b8e882c-6cb5-4477-a569-a4c8e369bac9.png">

## Actual JWT fields
<img width="562" alt="Screenshot 2022-08-29 at 20 14 29" src="https://user-images.githubusercontent.com/10169201/187270899-b291f507-5747-45aa-b846-63e7b2c46504.png">

**Comment by cmwilson21** [comment]
@yogeshlonkar Thanks for opening an issue! I see that you made a PR as well, but it's for a file in which we don't usually accept changes, so our bot closed it out. 💛 

I will get this issue triaged for review, and it will be fixed internally if approved.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by martin389** [comment]
Hi @yogeshlonkar, thanks for letting us know. I've now updated [the article](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect) in an internal PR 👍
