### ISSUE TITLE
'Attaching files' has missing important note

### ISSUE THREAD

**Issue by mbiesiad** [github/docs#20289]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

### What part(s) of the article would you like to see updated?

At this moment there is a `Warning` with info, but there is not mentioned about that - even if user will **Cancel** own changes, will **not** create an issue and so on so on, but just drag&drop a file during issue's creation process, it will be still uploaded. It looks quite dangerous (taking into account possible mistakes).

Example:
https://user-images.githubusercontent.com/18367606/187424575-d4a4e50d-7c57-40d6-ae40-1a29ba0868dd.png

Typical two ways for this:
- first one - if I drag & drop (so upload file process) I can edit or delete/remove this (mistake case) later
- second one - if I wanted to upload something and I will not to have an opportunity to delete it in easy way, I can see a confirmation window ("Are you sure?")

The user should be warned about that.

### Additional information

It's a little bit similar with: https://github.com/community/community/discussions/28316

Here it's focus on missing note about this.

Best wishes,

----
_Update from a maintainer_

The feedback about the product UI itself has been passed back to the product team.

### Content design plan to address this issue

The simplest way to make the current behavior more explicit is to update the warning as follows:

- Replace the initial words of the warning "If you attach" to "When you upload".
- At the end of the paragraph explaining how to attach a file to an issue etc., add a new sentence explaining that the attached file is uploaded to GitHub and the comment is updated to show the URL for the file.

**Comment by cmwilson21** [comment]
@mbiesiad Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment]
Hi @mbiesiad - thanks for flagging your concerns.

I agree that it would be helpful to update the article to mention the fact that the image is uploaded immediately, even if you ultimately decide not to add the comment, cancel the changes etc. I'll update the issue summary with a short content design plan that you, or someone else can follow to raise a pull request to update the article.

I also agree with you that this is valuable product feedback, as reported in https://github.com/orgs/community/discussions/28316. It's a pity that the discussion was opened as "general", I think it would be more visible to the relevant team if the discussion was updated to include an `Issues` label. I'll pass this feedback on.

**Comment by felicitymay** [comment]
Actually, on looking more into this, I think we'll need to consult with a subject matter expert to check how this works for GitHub Enterprise Server. Then we'll be able to suggest docs changes to make this article clearer.

**Comment by felicitymay** [comment]
@mbiesiad - I've discussed this with an internal team and passed on your feedback. 

I've added a content design plan to the issue summary with some small changes to the article that should make the current behavior clearer to users.

Thanks for bringing this to our attention ✨

**Comment by CapitainFlam** [comment]
As it is labeled **HELP WANTED**, PR is in progress. Wait for it.

**Comment by felicitymay** [comment]
Many thanks @CapitainFlam 💖 

I'm reviewing your pull requests. When they are both merged, this issue will be closed automatically. 🚀
