### ISSUE TITLE
Review and fix potential typo in git clone feedback text copy

### ISSUE THREAD

**Issue by hat-owl** [github/docs#20290]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Quickstart: Fork a Repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)

### What part(s) of the article would you like to see updated?

I compared the git clone progress text with the one in my terminal when I ran git clone on my fork of Spoon-Knife, in the way the instructions indicate. It appears that the "> remote ... remote ... remove: Total 10 (delta 1), reused 10 (delta 1)" contains a typo, with `remove` instead of `remote`.

### Additional information

Change `remove` to `remote` in the git clone feedback text printout if this is a typo. Otherwise leave as-is.

**Comment by cmwilson21** [comment]
@hat-owl Thanks for opening an issue and linking your PR to it! ✨

**Comment by Salamander098** [comment]
Thank you hat owl

from 👍 Salamander 098

**Comment by Salamander098** [comment]
I am salamander 098 @ mystery.com
