### ISSUE TITLE
Documentation for runner.os on Environment variables page

### ISSUE THREAD

**Issue by samsmithnz** [github/docs#2031]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

### What part(s) of the article would you like to see updated?

There is no documentation that I can find for runner.OS, and I believe it should probably be on this page. Can we add this and other system variables related to runners (are there other variables?). If you confirm, I'd be happy to take a shot at contributing.

As an example of a doc page done well, the Azure DevOps page has all environment variables, across builds, agents, etc. https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services

### Additional information

I can't find any GitHub documentation for runner.OS

**Comment by janiceilene** [comment]
Thanks for opening an issue @samsmithnz! I'll get this triaged for the right team to take a look 👀

**Comment by skedwards88** [comment]
Thank you for opening this issue! Is https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#runner-context what you are looking for?

**Comment by samsmithnz** [comment]
Yes! Not sure if this is a new article or has been recently updated, but this addresses my need. I'm going to close the issue.
