### ISSUE TITLE
Update Gmail buttons screenshot

### ISSUE THREAD

**Issue by aisgbnok** [github/docs#20325]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Configuring notifications](https://docs.github.com/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#customizing-your-email-notifications)

### What part(s) of the article would you like to see updated?

Customizing your email notifications, the `gmail-buttons.png` screenshot does not reflect how Gmail currently looks.

**Comment by cmwilson21** [comment]
@aisgbnok Thanks for opening an issue and linking it to your PR! ⚡

**Comment by hsoonslami** [comment]
Nsnsnznn
