### ISSUE TITLE
Empty default value for auto_merge parameter in Create a Deployment documentation

### ISSUE THREAD

**Issue by carflo** [github/docs#20356]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The [Create a Deployment](https://docs.github.com/en/rest/deployments/deployments#create-a-deployment) documentation shows an empty value for the `auto_merge` parameter when it should show `true` as defined in the [spec](https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.json).

![Empty default value](https://user-images.githubusercontent.com/47229246/188006226-89be8e8c-bb6c-4c11-af59-76cc221711ef.png)

![Screen Shot 2022-09-01 at 1 30 25 PM](https://user-images.githubusercontent.com/47229246/188007095-c718c50b-10e3-4e6f-85eb-684349875969.png)

### What changes are you suggesting?

The `auto_merge` parameter's default value should reflect the default value defined in the spec.

**Comment by cmwilson21** [comment]
@carflo Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
Thank you again for opening this issue! Updates to the REST/GraphQL API description must be made internally. I have copied your issue to an internal issue, so I will close this issue.
