### ISSUE TITLE
GPG supported key algorithms 

### ISSUE THREAD

**Issue by Zhong-z** [github/docs#20379]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

### What part(s) of the article would you like to see updated?

#generating-a-gpg-key

In the `supported-gpg-key-algorithms` section, it shows Github supports a list of algorithms including RSA. 

However in the `generating-a-gpg-key` section, it says 'Your key must use RSA', which suggests it is RSA only,  and contradicts with `supported-gpg-key-algorithms` section.

I didn't test the real behaviors, so not sure which one is outdated. But I expect to see them aligned or provided some context on why we must use 'RSA'.

### Additional information

<img width="790" alt="Screen Shot 2022-09-03 at 12 14 53" src="https://user-images.githubusercontent.com/5219229/188252081-b6470ae0-7312-4433-934d-d6a1f8c1729c.png">

**Comment by cmwilson21** [comment]
@Zhong-z Thanks for creating an issue and opening a PR! ✨
