### ISSUE TITLE
Word Space Missing

### ISSUE THREAD

**Issue by aravinthkumar** [github/docs#2038]
https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/viewing-contributions-on-your-profile

### What is the current behavior?

![image](https://user-images.githubusercontent.com/5385441/101986815-47b9b780-3cb6-11eb-88bc-50bdb76e3e19.png)

**Comment by OmkarPh** [comment]
May I take up this issue?

**Comment by janiceilene** [comment]
@OmkarPh You're welcome to open a PR to make this fix! Thank you 💝

**Comment by OmkarPh** [comment]
Can you have a look at the PR
