### ISSUE TITLE
Please provide complete reference schema for each subkey of the context accessible in a workflow

### ISSUE THREAD

**Issue by LongLiveCHIEF** [github/docs#2040]
The docs for the context have a gap, in that the immediate keys from the context have no documentation on _their_ keys. Example, where would i be able to find that there is a `github.event.action` that tells they type related to the `github.event_name`?

I recently have been struggling with triggering octoprint/docker image deployments from the github.com/octoprint/octoprint-docker repository based on `repository_dispatch` event payloads send by a workflow in github.com/octoprint/octoprint.   See full description and links in issue https://github.com/OctoPrint/octoprint-docker/issues/139.

I've felt like i'm in a redirect loop for a while now, with the [Context and Expression Syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions) constantly referring to the [Workflow Syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions) page, and vide-versa, but i couldn't figure out why it was bothering me, since the Events that trigger workflows page directs users to the relevant api docs to get the format of the payload.

However, i finally figured it out. There is no documentation _anywhere_ that `github.event.action` will tell me the `type` that happened on `github.event_name`.  The Events that trigger workflows page send you to the releases api, and that example object payload is _actually_ equivalent to the context `github.event.release`.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @LongLiveCHIEF! I'll get this triaged for the team to take a look 👀

**Comment by janiceilene** [comment]
👋 @LongLiveCHIEF Thanks for opening an issue! I've talked to team and some additional clarity would be helpful. Could you give an example of an event body and how we could change the docs to make it less confusing? Thanks!

**Comment by megbird** [comment]
👋  @LongLiveCHIEF let us know if you have any clarification for us! For now, I'll close this out and we can reopen it if you'd like to move forward 😄

**Comment by LongLiveCHIEF** [comment]
I gave you explicit examples in the original ticket.

**Comment by lee-dohm** [comment]
Hello @LongLiveCHIEF, thanks for reaching out.

Unfortunately, a few of us have taken a look at this now and none of us are understanding:

1. What exactly it is you're saying is not clear
2. What you propose we should do to make things more clear

Since the issue, as it currently stands, is not actionable, we have no choice but to leave it closed. If you can supply us with more information, details, or clarification that will help us understand what it is you need from us, we would be happy to take another look.

Thanks for working with us to make the GitHub Docs better!

**Comment by LongLiveCHIEF** [comment]
I'm looking for a complete schema in the documentation. Each context in the documentation lists the second-level objects, but no further.

For example, for the `github` context, `github.event` is documented, but `github.event.action` is not.  This is important because `github.event.action` has a dependency on `github.event_name`, and many examples in the docs leverage that, and other implied relationships, but there's nowhere I could ever find in the docs that `github.event.action` exists.

Furthermore, the links to api docs for each of these contexts links to objects that exist _deeper in the context tree_ than 2nd level keys.

That leaves me wondering what other second-level actionable keys exist that I can use in crafting actions that the docs don't hit on. 

If there was a schema that showed the complete potential graph of context keys, i'd be far more equipped to determine how to utilize the full potential of actions.

**Comment by lee-dohm** [comment]
Thanks for the extra detail and my apologies for the slow response.

You are correct that `github.event` is documented. The documentation states that it contains the full event payload. That payload is completely dependent upon which event occurred. The reason why we can't document `github.event.action` here in the `github` context documentation is that not every event payload contains an `action` key. For example, the [`issue_comment` payload](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#issue_comment) contains an `action` key whereas the [`create` payload](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#create) does not.

We do, however, link to the list of events that can trigger workflows and each of those events link to the documentation for the webhook payload that does a more comprehensive job of documenting the totality of what might be contained in the `github.event` object for each possible event type. By linking to these other sources of information, it eliminates the possibility of having to maintain duplicate information in separate locations. The reason why we can't link directly to the webhook payload documentation is that not every possible webhook event can trigger a workflow.

I will bring this up to the content design team as a pain point and see if there's a better way we can organize this information to improve the flow for this particular scenario. While I can't promise if or when we'll be able to improve the information access in this specific flow, please rest assured that your feedback has been delivered to the proper team.

Thanks again for taking the time to let us know and helping us understand better how people are using the documentation!

**Comment by LongLiveCHIEF** [comment]
For now, I mitigated by creating a job that just logged the context of the events I was interested in, then using that to design my action. (which is now being adopted by the docker actions as we speak, so exciting!)

That worked fine for me, and probably will for users, but my guess is this could cause technical debt down the road if those payload schemas change? Maybe?

/shrug
