### ISSUE TITLE
user profile header alignment

### ISSUE THREAD

**Issue by Mehul2410** [github/docs#2041]
### What is the current behavior?
![image](https://user-images.githubusercontent.com/62436745/101991469-db00e600-3cd2-11eb-8077-31989256c2d6.png)

### What changes are you suggesting?
The user image and user name in header should be aligned center  according to the header size.
align it to center the header would look great

### Additional information

The Dark mode is giving a great look to profile!

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @Mehul2410! This repo is only for the docs site, docs.github.com 💛 I can pass this feedback on to the right team, though.
