### ISSUE TITLE
Using internationalized domain for GitHub Pages

### ISSUE THREAD

**Issue by iamCristYe** [github/docs#20413]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

### What part(s) of the article would you like to see updated?

It's better to mention that for an internationalized domain name, one needs to enter the Punycode encoded version of it. I get the result from https://stackoverflow.com/questions/50066808/github-pages-does-not-work-properly-with-cyrillic-custom-domain, but it should be included in the official docs.

**Comment by cmwilson21** [comment]
@iamCristYe Thanks for creating an issue and linking it to your PR!
