### ISSUE TITLE
Typo on Copilot billing pt translation page

### ISSUE THREAD

**Issue by qsalatiel** [github/docs#20419]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/pt/billing/managing-billing-for-github-copilot/about-billing-for-github-copilot#pre%C3%A7os-de-github-copilot

### What changes are you suggesting?

Fix the typo on the word 'cpbradp'. It ment to be 'cobrado'.

### Additional information

"Cobrado" [Definition](https://www.linguee.com.br/portugues-ingles/traducao/cobrado.html)

**Comment by cmwilson21** [comment]
Closing per comment in [PR](https://github.com/github/docs/pull/20420#issuecomment-1238219898)
