### ISSUE TITLE
Update the UI elements in images to match the current elements

### ISSUE THREAD

**Issue by Verisimilitude11** [github/docs#20426]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews

https://github.com/github/docs/blob/main/content/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews.md

### What part(s) of the article would you like to see updated?

All images/screenshots

**Comment by cmwilson21** [comment]
@Verisimilitude11 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@Verisimilitude11 Could you give us a bit more information on what you would like to see updated in this article?

Thank you! 💛

**Comment by Verisimilitude11** [comment]
For example in this image:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/96280466/188766589-f836fcae-8a33-4923-9bcd-1d4868a932ca.png">
The icon for pull requests, buttons, and the general UI are different.

**Comment by Verisimilitude11** [comment]
Do you need any additional information?

**Comment by cmwilson21** [comment]
@Verisimilitude11 Thanks for checking in on this. It's is on our board and waiting for review. We appreciate your patience as we are working through our backlog 💛 

Just to clarify, you are requesting an update on the screenshots present in this article, correct?

**Comment by jc-clark** [comment]
👋 ✨ Great catch, @Verisimilitude11! Thank you for this issue and the effort to keep the docs updated. You, or anybody else, are welcome to submit a pull request updating the screenshots with current ones following our contributing guide for images and versioning:  

https://github.com/github/docs/blob/main/contributing/images-and-versioning.md
