### ISSUE TITLE
By default, dependabot only updates direct dependencies

### ISSUE THREAD

**Issue by deivid-rodriguez** [github/docs#20454]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file.

### What part(s) of the article would you like to see updated?

This sentence should be clarified

>  By default all dependencies that are explicitly defined in a manifest or lock file are kept up to date.

Lock files usually keep both direct and indirect dependencies, but dependabot only updates the former by default.

### Additional information

I will create a PR :)

**Comment by cmwilson21** [comment]
@deivid-rodriguez Thanks for opening an issue and linking it to your PR! ✨
