### ISSUE TITLE
Update self-hosted runners to support macOS ARM64

### ISSUE THREAD

**Issue by victorlin** [github/docs#20465]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#architectures

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/5a3a85ed840c7df9b0c61c16739f81802a4d799e/content/actions/hosting-your-own-runners/about-self-hosted-runners.md?plain=1#L121-L127

According to https://github.com/github/roadmap/issues/507 and the linked blog post, ARM64 should now support macOS.

**Comment by cmwilson21** [comment]
@victorlin Thanks for opening an issue and linking it to your PR!
