### ISSUE TITLE
Neither looks wrong and tags are expected, but it explain paths.

### ISSUE THREAD

**Issue by jinwookkk** [github/docs#20478]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore

### What part(s) of the article would you like to see updated?

Contents:
If you define only tags/tags-ignore or only branches/branches-ignore, the workflow won't run for events affecting the undefined Git ref. **If you define neither tags/tags-ignore or branches/branches-ignore, the workflow will run for events affecting either branches or tags.** **If you define both branches/branches-ignore and [paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), the workflow will only run when both filters are satisfied.**

This is a section for branchs and tags.
(subtitle: onpushbranchestagsbranches-ignoretags-ignore )

I wanna know how it works If I define both branches and tags.
So I expect that "If you define both branches/branches-ignore and **tags**, the workflow will only run when both filters are satisfied.".
or   "If you define both branches/branches-ignore and **tags**, the workflow will run for events affecting either branches or tags." (And by current policy, the latter is right.)
But it said about paths.

So I think **neither** is mistakes. It would be **both**.
it makes sense.

and remove about paths.
because below section include it.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

**Comment by cmwilson21** [comment]
@jinwookkk Thanks for opening an issue and linking it to your PR! ✨
