### ISSUE TITLE
clarify api usage limits in github actions

### ISSUE THREAD

**Issue by david-gang** [github/docs#20487]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

### What part(s) of the article would you like to see updated?

API requests - You can execute up to 1000 API requests in an hour across all actions within a repository. If exceeded, additional API calls will fail, which might cause jobs to fail.

It is not clear if it refers api calls to github api or general api calls to any service 

The content comes from here: https://github.com/github/docs/blob/main/data/reusables/actions/usage-api-requests.md

**Comment by cmwilson21** [comment]
@david-gang Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
This refers to calls to the GitHub API. You or anyone else is welcome to open a PR to update https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits to say something like  "1000 requests to the GitHub API" instead of "1000 API requests".
