### ISSUE TITLE
Missing information about workflow creation through the API's

### ISSUE THREAD

**Issue by rajbos** [github/docs#20489]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/automatic-token-authentication
https://docs.github.com/en/rest/overview/permissions-required-for-github-apps

### What part(s) of the article would you like to see updated?

I'm missing the information about the workflow scope you can give a GitHub App, whereas you cannot grant it to the GITHUB_TOKEN. This is confusing since it is not mentioned on either page.

For an APP you can give it write access to workflows, so it will be able to for example `git push` a file in the `.github/workflows` directory
![image](https://user-images.githubusercontent.com/6085745/189164448-e782de06-5c2d-4e8f-b2b3-431f9275d3b3.png)

For the GITHUB_TOKEN this is not allowed (AFAIK, which makes sense, for security reasons). 

I would like to see the scope added to the [Permissions required for GitHub Apps](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps) page, and at least mention it on the table here: [Permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)

**Comment by cmwilson21** [comment]
👋 @rajbos Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! We're working internally to improve the completeness and accuracy of the "Permissions required for GitHub Apps" article. After that internal project is complete, you should see "workflows" mentioned on that page. I think that the table in "Automatic token authentication" is meant to only indicate the permissions that you can specify and is not kept up to date permissions that do not apply to GITHUB_TOKEN. With that in mind, I'm going to close this issue out, but I hope to see more contributions from you in the future ✨
