### ISSUE TITLE
`fromJSON` should include an example of an array for `runs-on`

### ISSUE THREAD

**Issue by jsoref** [github/docs#20495]
### Maintainer's note

We researched the question raised by this issue and provided clarification in this comment: https://github.com/github/docs/issues/20495#issuecomment-1717383155

To open a PR against this issue, please add clarification of this syntax in the "[`jobs.<job_id>.runs-on`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on)" section of the "[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)" article.

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on

### What part(s) of the article would you like to see updated?

Add an `example-returning-a-runs-on-array` similar to https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object

### Additional information

Normally in JSON, the basic types are:

* null
* booleans
* numbers
* strings
* arrays
* maps

In GitHub Workflows, strings are strange in that, _maybe_? they don't need to be wrapped in quotes, some of the time?

Except, in the example https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object, keys and values are wrapped in quotes:
```yaml
        run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
```

When I tried to add some magic for a dynamic `runs-on` that would _sometimes_ be a string and sometimes be an array, I naively assumed that I'd need to wrap my array elements in quotes, but that didn't do the right thing.

See this PR:
https://github.com/commercialhaskell/stack/pull/5856#discussion_r966158231

We can't seem to get this to work...

[merge](https://github.com/commercialhaskell/stack/commits/1ed84345f3c2b02117829c08eb56a7f6d3c7f0a4) [change](https://github.com/commercialhaskell/stack/pull/5856/commits/61f0830192c0b0afd2eeaab039952eee0885070d) https://github.com/commercialhaskell/stack/runs/8254107160?check_suite_focus=true
```
Requested labels: [self-hosted, linux, ARM64]
Job defined at: commercialhaskell/stack/.github/workflows/integration-tests.yml@refs/pull/5856/merge
Waiting for a runner to pick up this job...
```

[merge](https://github.com/commercialhaskell/stack/commits/bb584ad65e5dd4c2c4302a525e760c3081ed3b19) [change](https://github.com/commercialhaskell/stack/commit/3c3140cc1baad9decf420b7d992ffd67557f632c)  https://github.com/commercialhaskell/stack/runs/8254719771?check_suite_focus=true
```
Requested labels: "[self-hosted, linux, ARM64]"
Job defined at: commercialhaskell/stack/.github/workflows/integration-tests.yml@refs/pull/5856/merge
Waiting for a runner to pick up this job...
```

[merge](https://github.com/commercialhaskell/stack/commits/114288d6311e6937134a841e2e312905c6e0961b) [change](https://github.com/commercialhaskell/stack/commit/5c9db84d1a57a3ad4200ad4644ca6105d94d01d6)  https://github.com/commercialhaskell/stack/runs/8255017367?check_suite_focus=true
```
Requested labels: ["self-hosted", "linux", "ARM64"]
Job defined at: commercialhaskell/stack/.github/workflows/integration-tests.yml@refs/pull/5856/merge
Waiting for a runner to pick up this job...
```

[merge](https://github.com/commercialhaskell/stack/commits/51ee319644e1f0c375c1861923c789aef0ca622c) [change](https://github.com/commercialhaskell/stack/commit/1305b24d561e72761a7e2a59ec644b95ebbdf7c0) https://github.com/commercialhaskell/stack/runs/8255163889?check_suite_focus=true
```
Requested labels: [self-hosted, linux, ARM64]
Job defined at: commercialhaskell/stack/.github/workflows/integration-tests.yml@refs/pull/5856/merge
Waiting for a runner to pick up this job...
```

The last output appears to match the output for the working world
[workflow](https://github.com/commercialhaskell/stack/blob/f43914631bbc2b3def04f4861f129350b732d3fe/.github/workflows/integration-tests.yml#L100) https://github.com/commercialhaskell/stack/runs/8255316015?check_suite_focus=true
```yaml
    runs-on: [self-hosted, linux, ARM64]
```

**Comment by jsoref** [comment]
The working example is apparently https://github.com/commercialhaskell/stack/pull/5856/commits/ba7008251f8bcec6ac0bd11f26031b760b7d68e6

https://github.com/commercialhaskell/stack/blob/ba7008251f8bcec6ac0bd11f26031b760b7d68e6/.github/workflows/integration-tests.yml#L115
```
          echo "::set-output name=arm64::['self-hosted', 'linux', 'ARM64']"
```
https://github.com/commercialhaskell/stack/blob/ba7008251f8bcec6ac0bd11f26031b760b7d68e6/.github/workflows/integration-tests.yml#L122
```
    runs-on: ${{ fromJSON(needs.configuration.outputs.arm64) }}
```

**Comment by cmwilson21** [comment]
👋 @jsoref Thanks for opening an issue. We appreciate all the details, too.

I'll get this triaged for review. ⚡

**Comment by sergcarpov** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
> 
> ### What part(s) of the article would you like to see updated?
> Add an `example-returning-a-runs-on-array` similar to https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object
> 
> ### Additional information
> Normally in JSON, the basic types are:
> 
> * null
> * booleans
> * numbers
> * strings
> * arrays
> * maps
> 
> In GitHub Workflows, strings are strange in that, _maybe_? they don't need to be wrapped in quotes, some of the time?
> 
> Except, in the example https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object, keys and values are wrapped in quotes:
> 
> ```yaml
>         run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
> ```
> 
> When I tried to add some magic for a dynamic `runs-on` that would _sometimes_ be a string and sometimes be an array, I naively assumed that I'd need to wrap my array elements in quotes, but that didn't do the right thing.
> 
> See this PR: [commercialhaskell/stack#5856 (comment)](https://github.com/commercialhaskell/stack/pull/5856#discussion_r966158231)
> 
> We can't seem to get this to work...
> 
> [merge](https://github.com/commercialhaskell/stack/commits/1ed84345f3c2b02117829c08eb56a7f6d3c7f0a4) [change](https://github.com/commercialhaskell/stack/pull/5856/commits/61f0830192c0b0afd2eeaab039952eee0885070d) https://github.com/commercialhaskell/stack/runs/8254107160?check_suite_focus=true
> 
> ```
> Requested labels: [self-hosted, linux, ARM64]
> Job defined at: commercialhaskell/stack/.github/workflows/integration-tests.yml@refs/pull/5856/merge
> Waiting for a runner to pick up this job...
> ```
> 
> [merge](https://github.com/commercialhaskell/stack/commits/bb584ad65e5dd4c2c4302a525e760c3081ed3b19) [change](https://github.com/commercialhaskell/stack/commit/3c3140cc1baad9decf420b7d992ffd67557f632c) https://github.com/commercialhaskell/stack/runs/8254719771?check_suite_focus=true
> 
> ```
> Requested labels: "[self-hosted, linux, ARM64]"
> Job defined at: commercialhaskell/stack/.github/workflows/integration-tests.yml@refs/pull/5856/merge
> Waiting for a runner to pick up this job...
> ```
> 
> [merge](https://github.com/commercialhaskell/stack/commits/114288d6311e6937134a841e2e312905c6e0961b) [change](https://github.com/commercialhaskell/stack/commit/5c9db84d1a57a3ad4200ad4644ca6105d94d01d6) https://github.com/commercialhaskell/stack/runs/8255017367?check_suite_focus=true
> 
> ```
> Requested labels: ["self-hosted", "linux", "ARM64"]
> Job defined at: commercialhaskell/stack/.github/workflows/integration-tests.yml@refs/pull/5856/merge
> Waiting for a runner to pick up this job...
> ```
> 
> [merge](https://github.com/commercialhaskell/stack/commits/51ee319644e1f0c375c1861923c789aef0ca622c) [change](https://github.com/commercialhaskell/stack/commit/1305b24d561e72761a7e2a59ec644b95ebbdf7c0) https://github.com/commercialhaskell/stack/runs/8255163889?check_suite_focus=true
> 
> ```
> Requested labels: [self-hosted, linux, ARM64]
> Job defined at: commercialhaskell/stack/.github/workflows/integration-tests.yml@refs/pull/5856/merge
> Waiting for a runner to pick up this job...
> ```
> 
> The last output appears to match the output for the working world [workflow](https://github.com/commercialhaskell/stack/blob/f43914631bbc2b3def04f4861f129350b732d3fe/.github/workflows/integration-tests.yml#L100) https://github.com/commercialhaskell/stack/runs/8255316015?check_suite_focus=true
> 
> ```yaml
>     runs-on: [self-hosted, linux, ARM64]
> ```

**Comment by ray2glicense** [comment]
new year new task here's to bigger, brighter and, how could it get any better guys.

**Comment by Mashudaamri** [comment]
Help me establish a link to github for an otp on the missing simcard

**Comment by hubwriter** [comment]
I've had a look at this but am not familiar enough with this area to know whether, where, and how this should be documented, so I've asked for some SME assistance. Hopefully we can move this issue along soon.

**Comment by hubwriter** [comment]
The answer I've had on this is that the strings provided as the value of `runs-on` can be quoted but don't need to be where a simple word is used, like:

```
runs-on: [self-hosted, linux, x64, gpu]
```

Expressions must be quoted:

```
runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
```

Perhaps to resolve this issue we could add some clarification of this to the syntax details for `runs-on`:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
