### ISSUE TITLE
Ready-to-use docs package

### ISSUE THREAD

**Issue by EAzari** [github/docs#205]
Hi there, 

Do you have any plan to build a ready-to-use version of current docs for those who want to use it individually?
An Easy-to-use docs package that anything can be controllable through some GraphQL or REST or JSON files and some folders?

Kind regards,
Ehsan

**Comment by simpsoka** [comment]
Hi @EAzari! That's definitely something that we've chatted about on the team. Providing an API to leverage content in various places would be fantastic & I can see this working for wanting to call the docs from your IDE, or if you're building a learning app and want to reference the content or use certain components from docs.github.com. 

What'cha thinking? :)

**Comment by EAzari** [comment]
Thanks @simpsoka, sounds great,
Thanks for the all the great job you all do

So, I close this issue then, wish you all the best
