### ISSUE TITLE
content error in shell example for GPG signing articles

### ISSUE THREAD

**Issue by sushiljainam** [github/docs#20508]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key 

### What part(s) of the article would you like to see updated?

Slight inconsistency in examples section of following article (Image attached)
https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key
in (3) and (4) point of Mac OS version
<img width="781" alt="Screen Shot 2022-09-09 at 4 52 58 PM" src="https://user-images.githubusercontent.com/13596814/189339600-712d511f-c12a-45ce-a190-6f32744815ce.png">

**Comment by cmwilson21** [comment]
@sushiljainam Thanks for opening an issue and linking it to your PR! ✨

**Comment by GodAlmighty777** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key 
> 
> ### What part(s) of the article would you like to see updated?
> 
> Slight inconsistency in examples section of following article (Image attached)
> https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key
> in (3) and (4) point of Mac OS version
> <img width="781" alt="Screen Shot 2022-09-09 at 4 52 58 PM" src="https://user-images.githubusercontent.com/13596814/189339600-712d511f-c12a-45ce-a190-6f32744815ce.png">
> 
> 
> ### Additional information
> 
> _No response_

**Comment by smuthr** [comment]
#22400
