### ISSUE TITLE
GitHub Copilot is now free for teachers

### ISSUE THREAD

**Issue by luc122c** [github/docs#20500]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- [About billing for GitHub Copilot](https://docs.github.com/en/copilot/overview-of-github-copilot/about-github-copilot#about-billing-for-github-copilot)
- [Getting started with GitHub Copilot in Visual Studio Code](https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-visual-studio-code)
- [Getting started with GitHub Copilot in Visual Studio](https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-visual-studio)
- [Getting started with GitHub Copilot in a JetBrains IDE](https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-a-jetbrains-ide)
- [Getting started with GitHub Copilot in Neovim](https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-neovim)

Likely many more

### What part(s) of the article would you like to see updated?

GitHub Copilot is now free for teachers, most of the docs say "Verified students and maintainers of popular open source projects on GitHub are eligible to use GitHub Copilot for free" or "GitHub Copilot is free to use for verified students and maintainers of popular open source projects." The copy should be updated to reflect this excellent new change.

### Additional information

- [Please provide free license of GitHub Copilot to teachers as well #92](https://github.com/community/Global-Campus-Teachers/discussions/92#discussioncomment-3598302)
- [GitHub Copilot is now free for teachers #118](https://github.com/community/Global-Campus-Teachers/discussions/118?mc_cid=b9e94c38ce&mc_eid=18aefff4d8#discussion-4375925)
- [Copilot is now available free for verified teachers](https://github.blog/2022-09-08-github-copilot-now-available-for-teachers/)

**Comment by cmwilson21** [comment]
@luc122c Thanks for opening an issue and linking it to your PR! ✨
