### ISSUE TITLE
Doc on CODEOWNERS has a broken link for #syntax-expections

### ISSUE THREAD

**Issue by mLuby** [github/docs#20540]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

"About code owners"
- public: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
- source: https://github.com/github/docs/blob/main/content/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners.md

### What part(s) of the article would you like to see updated?

The "with [some exceptions](https://github.com/github/docs/blob/main/content/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners.md#syntax-exceptions)" link should work.

**Comment by cmwilson21** [comment]
@mLuby Thanks for opening an issue and linking it to your PR! ✨
