### ISSUE TITLE
Removal of outlines on buttons in Github Docs Footer

### ISSUE THREAD

**Issue by vedantsinghania05** [github/docs#20545]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

No specific article, just the entire site (the footer of the site)

### What changes are you suggesting?

I am unsure if this is an error or a purposely implemented change on the Github Docs site, but the blue outline around the buttons seems misleading. I think it would make more sense if the buttons only had outlines when they are clicked. I have attached an image to show how it currently looks.

### Additional information

<img width="762" alt="Screenshot 2022-09-11 at 3 07 18 PM" src="https://user-images.githubusercontent.com/74111380/189550828-693ac310-c9f9-4b71-b4d4-dbb4874d3d31.png">

**Comment by cmwilson21** [comment]
@vedantsinghania05 Thanks for opening an issue and providing this feedback. I've brought it up with our team and we will be tracking it internally from this point. I'm going to go ahead and close the issue now.

Thanks again for your interest and passion for improving the docs! 💖
