### ISSUE TITLE
Webricks currently not included by default in homebrew's ruby, leading to issues.

### ISSUE THREAD

**Issue by AlDacMac** [github/docs#20562]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

### What part(s) of the article would you like to see updated?

When following this article with ruby installed via homebrew, I I encountered the following error when trying to locally test my site: `/Users/<user>/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)`.

As discussed on this stackoverflow article, the issue is that webrick is not being included when homebrew is used to install Ruby 3.1.2: https://stackoverflow.com/questions/69890412/bundler-failed-to-load-command-jekyll.

I would suggest adding a line mentioning this, and telling the user to run `bundle add webrick` if they have used homebrew to install an affected version of ruby. Alternately, this specific error could be added to the `troubleshooting jekyll errors` section.

---
[maintainer edit]

### Content plan [here](https://github.com/github/docs/issues/20562#issuecomment-1282085316)

**Comment by Pavankumar-Hegde** [comment]
yeah good idea.

**Comment by cmwilson21** [comment]
@AlDacMac Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by dojutsu-user** [comment]
Hi @cmwilson21,
Taking this issue up.

**Comment by Rambo250000000000** [comment]
https://www.paypal.com/pools/c/8OmsxaiDuZ
