### ISSUE TITLE
List followers of a user

### ISSUE THREAD

**Issue by vinijmoura** [github/docs#20595]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I'm using GitHub Api to list followers, but when return 200, I don't have the follower date (follower_at).
https://docs.github.com/en/rest/users/followers#list-followers-of-a-user

Is it possible to include this information on JSON?

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/rest/users/followers#list-followers-of-a-user

### Additional information

https://docs.github.com/en/rest/users/followers#list-followers-of-a-user

**Comment by cmwilson21** [comment]
@vinijmoura Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@vinijmoura Checking in again.. Are you requesting a change to the docs? If so, can you be a bit more specific on what you think should be added or changed? ✍️ 

If this is a support question, this would best be handled by our [support team](https://support.github.com/request). Please reach out to them. 💛

**Comment by vinijmoura** [comment]
Hello @cmwilson21 
I need 2 changes:

1. REST API return the date of follower
2. Documentation refresh with this new information.

**Comment by cmwilson21** [comment]
Thanks for getting back to me so quickly. This is not currently a supported feature. 💛 

The best place to send your feature request feedback is to https://support.github.com/contact/feedback 

We appreciate your interest in improving the docs! I'm going to go ahead and close this issue now. ✨
