### ISSUE TITLE
Include an observation and a link to PR templates at README.md

### ISSUE THREAD

**Issue by casals** [github/docs#206]
### What article on docs.github.com is affected?

File `README.md` at `github/docs`

### What part(s) of the article would you like to see updated?

After opening a multitude of PRs without realizing there was a template for it, I was warned about the situation. I hadn't found a link or a reference to a PR template when reading the `README.md` file, and I probably missed it right before the PR submission since I was rapid-firing PRs. IMHO adding a reference to PR templates (in the same manner that it's done to Issues templates) would be beneficial for other users.

### Additional information

None at this time.

**Comment by janiceilene** [comment]
Thanks for letting us know about this and opening a PR @casals 🌟
