### ISSUE TITLE
[GitHub Actions] Rename example section titles in "Workflow syntax for GitHub Actions"

### ISSUE THREAD

**Issue by martin389** [github/docs#2063]
### What article on docs.github.com is affected?

[Workflow syntax for GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions)

### What part(s) of the article would you like to see updated?

The example sections in this guide have adopted a convention of starting their titles with "Example [...]". e.g.
- ["Example including additional values into combinations"](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations)
- ["Example ignoring paths"](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths)
- ["Example running with more than one version of Node.js"](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-running-with-more-than-one-version-of-nodejs).

This convention sometimes makes it a bit challenging to construct a section title, since it's not beginning with a verb. 

To address this, we could adopt a new convention that renames all these section titles to begin with "Example: [verb]". e.g.:
Was: "Example including additional values into combinations"
Now: "Example:  Adding values to combinations"

Was: "Example ignoring paths"
Now: ""Example: Ignoring paths"

Was: "Example running with more than one version of Node.js"
Now: "Example: Running multiple versions of Node.js"

**Comment by Perkles** [comment]
Hello 👋
Can i take this one ?

**Comment by janiceilene** [comment]
Absolutely! I'll assign you to it 🎉
