### ISSUE TITLE
oauth redirect_uri documents a Host constraint that doesn't exist

### ISSUE THREAD

**Issue by antdking** [github/docs#20631]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls

### What part(s) of the article would you like to see updated?

The article talks about how the Host must match the defined Callback URI, however in the real world, `redirect_uri` appears to allow subdomains of the Host.

In the article is a truth table. I propose the table is extended to show support for providing a subdomain in the `redirect_uri`.
Hopefully this also gives a solid example of what I'm asking about.

```diff
CALLBACK: http://example.com/path

GOOD: http://example.com/path
GOOD: http://example.com/path/subdir/other
+GOOD: http://oauth.example.com/path
+GOOD: http://oauth.example.com/path/subdir/other
BAD:  http://example.com/bar
BAD:  http://example.com/
BAD:  http://example.com:8080/path
BAD:  http://oauth.example.com:8080/path
BAD:  http://example.org
```

### Additional information

Are there any gotchas that break this assumption?

From what I remember, I relied on this behaviour for another project a few years back, so there may be other projects in the wild that made the same discovery and rely on the undocumented functionality.

**Comment by cmwilson21** [comment]
@antdking Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@antdking Thanks for bringing this up! I spoke with the team and we'd be happy to accept this change and an additional edit:

1. Add the two two lines highlighted above.
2. Change the paragraph right above the call out and below the title to say
```
If provided, the redirect URL's host (excluding sub-domains) and port must exactly match the callback URL. The redirect URL's path must reference a subdirectory of the callback URL.
```

You, or anyone else, are welcome to submit a PR with this change.
