### ISSUE TITLE
Unclear how to get the ID value for pushActorIds in CreateBranchProtectionRuleInput

### ISSUE THREAD

**Issue by pawanks84** [github/docs#20654]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

In the below given github doc link, its not clear how to get the ID values for attribute **pushActorIds** in the section CreateBranchProtectionRuleInput. 
https://docs.github.com/en/graphql/reference/input-objects#updaterepositoryinput

<img width="727" alt="image" src="https://user-images.githubusercontent.com/25169926/190625819-3bc350e0-a5e9-4c06-a0b4-4010eb2536b7.png">
Many thanks in advance !!

### What part(s) of the article would you like to see updated?

Can you please tell how to obtain the ID value of an actor who should be authorized to push ? It would help if you can give correct usage for this attribute as well when using along with CreateBranchProtectionRuleInput using gh CLI.

Many thanks in advance !!

**Comment by cmwilson21** [comment]
👋 @pawanks84 This question would best be handled by our awesome [support team](https://support.github.com/request). I'm sure they can help. Please reach out to them. 

Thanks again for opening an issue. I'm going to close it now 💛
