### ISSUE TITLE
minor change but would help understanding how to do a code suggestion in a comment

### ISSUE THREAD

**Issue by CapitainFlam** [github/docs#20656]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

File affected : (the `{% pointers %}` I was unable to find)
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

That appears in : (original message's référence file)
https://github.com/github/docs/blob/main/content/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request.md

### What part(s) of the article would you like to see updated?

in the **Starting a review** part, 
in point 7 "**7 - Optionally, to suggest a specific change to the line or lines, click **[icon]**, then edit the text within the suggestion block.** "

Could you please : 
A/ update the icon, as it is not only a "plus over a minus", but a "plus over a minus enclosed in a double page layout".

B/ highlight the icon in the screenshoot (like you highlight the `'''suggestion'''` text, 'coz I found it ONLY after dozen of help re-readings and trial and errors in the UI.

the page code itself is only saying this : 
```
{% webui %}

{% data reusables.repositories.sidebar-pr %} {% data reusables.repositories.choose-pr-review %} {% data reusables.repositories.changed-files %} {% ifversion fpt or ghec or ghes > 3.3 or ghae %}
```

and I am unable to reach the destination file pointed by those `{% pointers %}`

### Additional information

![image](https://user-images.githubusercontent.com/31761317/190642379-8da88eed-d8ac-4126-b46c-e679a740aeea.png)

**Comment by CapitainFlam** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

Thanks, bot :)

**Comment by cmwilson21** [comment]
👋 @CapitainFlam - not a bot here 😉 

Thanks for opening an issue and for clearly defining the trouble point you have experienced and including the image. I will get this triaged for review! ⚡

**Comment by cmwilson21** [comment]
Also, slightly changed your post to include a link to the live article in addition to the file link you provided. Thanks for that! ✨

**Comment by CapitainFlam** [comment]
> Also, slightly changed your post to include a link to the live article in addition to the file link you provided. Thanks for that! ✨

And thanks for the direct link 👍😸

**Comment by rachaelrenk** [comment]
👋  @CapitainFlam - thank you for opening this issue! The inline icon in step 7 can be updated with this Octicon:

`{% octicon "file-diff" aria-label="The file diff icon" %}`

You, or anyone else, are welcome to replace the icon in the reusable and submit a pull request for this change.

**Comment by CapitainFlam** [comment]
@rachaelrenk Thank you for the icon ! 

@cmwilson21 Oupsy ! the file still contains many pointers, I still can not modify neither `(3) On the pull request, click _icon_ Files changed. ` nor `(7) Optionally, to suggest a specific change to the line or lines, click _icon_, then edit the text within the suggestion block. ` of the [page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review), because it's still pointers associated 😭 😭 

indeed, https://github.com/github/docs/blob/main/content/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request.md code is : 

(3)  On the pull request, click _icon_ Files changed.
```
Starting a review

{% webui %}

{% data reusables.repositories.sidebar-pr %} {% data reusables.repositories.choose-pr-review %} {% data reusables.repositories.changed-files %} {% ifversion fpt or ghec or ghes > 3.3 or ghae %}
```

and

(7) Optionally, to suggest a specific change to the line or lines, click _icon_, then edit the text within the suggestion block.

 ```
Optionally, filter the files to show only the files you want to review{% ifversion pr-tree-view %} or use the file tree to navigate to a specific file{% endif %}. For more information, see "[Filtering files in a pull request](https://github.com/github/docs/blob/main/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/filtering-files-in-a-pull-request)." {% data reusables.repositories.start-line-comment %} {% data reusables.repositories.type-line-comment %} {% data reusables.repositories.suggest-changes %}

When you're done, click Start a review. If you have already started a review, you can click Add review comment.```

...

...the 7th note is somewhere in `{% data reusables.repositories.start-line-comment %} {% data reusables.repositories.type-line-comment %} {% data reusables.repositories.suggest-changes %}`

Could someone explain me how to understand the `{% pointers %}` system / how it works ? A link to a help page will be perfect if it exist ! Thus, I'd be able to go deeper in the intricated tree and find the root of it 😸 

I'am OK for forking the help and do the pull, but first I need to know where to go ! 😅 

thanks!

**Comment by CapitainFlam** [comment]
Todo : 
- [ ] correct icon in (3) On the pull request, click _icon_ Files changed.
- [ ] correct icon in (7) Optionally, to suggest a specific change to the line or lines, click _icon_, then edit the text within the suggestion block.

**Comment by cmwilson21** [comment]
👋 @CapitainFlam - Glad you found the reusables and that you were able to update them. We appreciate you taking the time to dig through and contribute!

**Comment by cmwilson21** [comment]
Great question! As far as I know, there's no official guideline for how to highlight screenshots. We are currently discussing this practice internally, so don't worry about updating this image at this time. However, we do appreciate your willingness to do so!

If you'd like to find more ways to contribute, please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 

Thanks again! ✨
