### ISSUE TITLE
Hover states make the content very difficult to see 

### ISSUE THREAD

**Issue by simpsoka** [github/docs#20711]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This affects the main navigation plan and language toggles, so I believe it will show up for the majority of pages on docs.github.com including the main landing page. 

### What changes are you suggesting?

The text should probably be white instead of a dark grey which is similar to the hover and active states of the main button. 

### Additional information

This affects light mode. I did not test on docs dark mode. 

![CleanShot 2022-09-19 at 13 17 50](https://user-images.githubusercontent.com/704152/191110182-5164df37-5db1-4f68-95ae-9924155a0c93.gif)

**Comment by cmwilson21** [comment]
@simpsoka Thank you for opening this issue! We have logged this internally and are working on it. We really appreciate you taking the time to create an issue and upload the gif file. I'm going to go ahead and close this issue now. 💛 

Feel free to open another if you come across any more improvements. Thanks for your interest in improving the docs! ⚡
