### ISSUE TITLE
Incorrect link on About remote repositories page

### ISSUE THREAD

**Issue by s7m4b4** [github/docs#20720]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories

### What changes are you suggesting?

Under the _Cloning with SSH URLs_ header, `Authorizing an SSH key for use with SAML single sign-on` incorrectly links to the PAT SAML SSO page. 
I believe the correct link should instead be this - `/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-an-ssh-key-for-use-with-saml-single-sign-on`

**Comment by cmwilson21** [comment]
@s7m4b4 Thanks for opening an issue and linking it to your PR! ✨
