### ISSUE TITLE
github-event-types.md shows invalid attribute name

### ISSUE THREAD

**Issue by NightPlow** [github/docs#20744]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#event-object-common-properties

## Context

The doc shows a non-existing attribute called `repo` inside `github.event` object. This attribute is misspelled and called `repository`.

## How to fix

In the doc, replace the attribute name `repo` with `repository`.

**Comment by cmwilson21** [comment]
@NightPlow Thank you for opening an issue and linking it to your PR! ✨

**Comment by ROKONUJJAMA** [comment]
https://www.fiverr.com/share/646D9b
