### ISSUE TITLE
Add information about what happens with Gists after a username change

### ISSUE THREAD

**Issue by billythekid** [github/docs#20769]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/changing-your-github-username

### What part(s) of the article would you like to see updated?

Add a small section explaining the impact on Gists (PR incoming for this)

**Comment by Vero5025** [comment]
Dykggjllh. Xxc j

**Comment by cmwilson21** [comment]
@billythekid Thank you for opening an issue and linking it to your PR! ✨
