### ISSUE TITLE
Good 'contributing' *.md contents is not shown ?!

### ISSUE THREAD

**Issue by CapitainFlam** [github/docs#20761]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I think that : 
https://github.com/github/docs/blob/main/README.md
or
https://github.com/github/docs/blob/main/contributing/README.md
should be improved as described below

### What part(s) of the article would you like to see updated?

_TL;DR: It is NOT obvious where to find octicons icons, or where are hidden code of conducts, or even how to do a correct screenshot. And, if some guides are written, they can't be reached with the main/README, neither the contributing/README. Me proposal is to rework the contributing/README, and send the actual content in a lower page_

because of https://github.com/github/docs/issues/20656, I hardly struggled to understand octicons icons (...there is a page for it and I can't find it again!!!!), or how to generate screenshot (it's here : https://github.com/github/docs/blob/main/contributing/images-and-versioning.md)

The "[main/README](https://github.com/github/docs/blob/main/README.md)" is very general, and it's OK, 
but the "[contributing/README](https://github.com/github/docs/blob/main/contributing/README.md) contain very specific instructions to set a fork/install GitHub Desktop and so on. 

IMHO, the content of the ACTUAL [contributing/README](https://github.com/github/docs/blob/main/contributing/README.md) should be (mostly) in a "`Setup your environment to contribute`" section, or even a new `*.mb` file, and the FUTURE contributing/README.md should contain general links to, 

first : guidelines 

- guidelines for GitHub
- guidelines for Microsoft
- self review [contributing/self-review.md](https://github.com/github/docs/blob/main/contributing/self-review.md)
- stuff like [content-style-guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md)
- octicons are in [github.com/primer/octicons](https://github.com/primer/octicons) 
- etc ... It is (for some) requested to be respected when you commit a PR, but it's not in the contributing README ?!

And then, tutorial / how to / examples ; 

- for example, [Image and versioning](https://github.com/github/docs/blob/main/contributing/images-and-versioning.md), 
- or `How to create a screenshoot with highlight parts` (it doesn't exist, it may be part of GitHub or Microsoft Guideline ?).

So, it's an enhancement proposal, but, as a newcomer to GitHub, I believe that the level of the 'entry barrier' is very high for newcomers. 

I sincerely hope it helps, I don't want to flame anyone, I am just trying to avoid future "maze looking through". 😅 

EDIT : adding some good stuff that I think should be added to it. (and btw I finally found a good integrated dictionary module, it allows me to correct my trashy English to something more readable)

**Comment by ROKONUJJAMA** [comment]
https://www.fiverr.com/share/646D9b

**Comment by jenniferabowd** [comment]
If you all want me to work on this, I'm happy to pick up this issue.

**Comment by CapitainFlam** [comment]
I have no power here, but furthermore I have no knowledge... So i'd be happy to support you and give you my feedback, as I can't do it myself, as a noob in GitHut environment  & usages. 😅 

Thanks in advance for your help.

**Comment by cmwilson21** [comment]
@CapitainFlam Thanks for opening an issue and providing this great feedback. I apologize for the delay in response here. We are having internal discussions about this. I'm going to leave this open for now as we keep continue our internal conversations. 

Again, we appreciate this feedback!

**Comment by passrigh** [comment]
MORE information about the right thing to do with the system

**Comment by passrigh** [comment]
Thanks for the update on the system
