### ISSUE TITLE
Those PDF references both give me 404s. Is that the correct reference or has it just not been uploaded yet? Thanks!

### ISSUE THREAD

**Issue by ryul95** [github/docs#2076]
Those PDF references both give me 404s. Is that the correct reference or has it just not been uploaded yet? Thanks!

_Originally posted by @ATweedMITRE in https://github.com/CVEProject/cvelist/pull/292#issuecomment-744505674_

**Comment by productcert** [comment]
This was a bug in the exporter. Fixed.

**Comment by janiceilene** [comment]
@ryul95 This repo is for docs.github.com, so I'm going to close up. 

If you'd like to contribute, there are several issues with a [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label 💖
