### ISSUE TITLE
Explain how someone can sign the GitHub Marketplace Developer Agreement

### ISSUE THREAD

**Issue by christian-bromann** [github/docs#20784]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?
https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

https://docs.github.com/en/site-policy/github-terms/github-marketplace-developer-agreement

### What part(s) of the article would you like to see updated?

I am trying to publish a GitHub action and I can't because it says:

> ... must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.

There is no link to the agreement nor does the agreement in the docs say how to sign it. This is now the second time I have to go through this given in my last company the org admin was also confused and didn't know what to do.

Can you please clearly state what an org admin needs to do to sign this agreement?

----
## Explanation

When an organization owner opens a metadata file for an action and clicks **Draft a release**, the "Release Action" page contains a link to the GitHub Marketplace Developer Agreement. If you go to that page and no link is displayed, I suggest that you send a link to that page to the organization owner. They should be able to accept the agreement. Then, when you reload the page, you should find that publishing the action is no longer blocked.

<img width="1102" alt="Screenshot of the 'Release Action' page, showing the link to the agreement." src="https://github.com/github/docs/assets/1877141/6b110b80-219f-4190-b832-a7f1fda3d15a">

When the organization owner clicks on the link, a modal dialog box with the agreement is displayed. They can accept the agreement using that dialog box.

<img width="665" alt="Screenshot of the modal dialog box, showing the checkbox and 'Accept terms' button needed to accept the agreement." src="https://github.com/github/docs/assets/1877141/d8950dc7-ea27-416e-817b-7723ec5be4ca">

**Comment by christian-bromann** [comment]
To clarify: the experience for someone who is __not__ org admin can be improved here because I had nothing I could send to the admin for them to sign. Apparently only if the admin tries to draft a release, the agreement warning is a link which opens the right form.

**Comment by cmwilson21** [comment]
@christian-bromann Thanks for opening an issue! If you need immediate support, please reach out to our awesome [support team](https://support.github.com/request). Also, I've made a small edit to your post to include the link to the "[Publishing actions in GitHub Marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace)" article for reference.

I'll get this triaged for Docs review! ⚡

**Comment by felicitymay** [comment]
@christian-bromann - thanks for letting us know about this workflow problem.

We're raising it with the product team.

**Comment by felicitymay** [comment]
@christian-bromann - thank you for your patience.

I've been able to confirm how to sign the GitHub Marketplace Developer Agreement and will propose an update to the article to make this clear.

**Comment by felicitymay** [comment]
I raised a pull request to clarify the behavior:

- https://github.com/github/docs/pull/25778

You can see the proposed change in the [preview(https://docs-25778-ea4656.preview.ghdocs.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#publishing-an-action) for that pull request.

**Comment by htrgouvea** [comment]
Hi folks, where can I get the link to the "Github Marketplace GitHub Marketplace Developer Agreement"?

**Comment by nguyenalex836** [comment]
@htrgouvea Howdy! 👋 I think you might be looking for this [doc](https://docs.github.com/en/site-policy/github-terms/github-marketplace-developer-agreement)
