### ISSUE TITLE
AE documentation should be clarified to include repo size limits

### ISSUE THREAD

**Issue by gitstua** [github/docs#20810]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/github-ae@latest/repositories/working-with-files/managing-large-files/about-large-files-on-github#removing-files-from-a-repositorys-history

### What part(s) of the article would you like to see updated?

Add repo size limits to AE which show for GHEC

### Additional information

Customer seeks clarification as to size limits and I think this would help this customer and other users of AE. @pevd950 and I discussed this is the correct guidance in #ghae channel

**Comment by cmwilson21** [comment]
👋 @gitstua Thank you for opening an issue and linking it to your PR! ✨
