### ISSUE TITLE
Document new time zones feature

### ISSUE THREAD

**Issue by softcode589** [github/docs#20855]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile

### Add a "time zone" part

**Why should the docs be changed?**
Well, GitHub introduced this (if I recall correctly, 2 days ago), and this is a feature of the profile.

**What is the expected outcome?**
Showing how to enable and disable this feature.

**Comment by cmwilson21** [comment]
@softcode589 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by sabrowning1** [comment]
Hi @softcode589, thanks for bringing this to our attention! We've started work on this internally, so I'll go ahead and close this issue now. We appreciate your help in maintaining our docs! ✨
