### ISSUE TITLE
Remove `<em>` tags from code examples

### ISSUE THREAD

**Issue by skedwards88** [github/docs#20890]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All code examples that include `<em>` tags to emphasize text. For example:

````
```shell
git init <em>YOUR_REPO</em>
```
````

### What part(s) of the article would you like to see updated?

The `em` tag does not render correctly if you use a language other than `shell` or if you include a `copy` button. We have updated our [style guide](https://github.com/github/docs/blob/main/contributing/content-markup-reference.md#code-sample-syntax-highlighting) to instruct contributors to use all uppercase instead of `em` tags to indicate placeholder text.

You should update code examples to:
1. Ensure that any text currently within `em` tags is all uppercase
2. Remove the `em` tags

For example:

````
```shell
git init <em>your_repo</em>
```
````

will become

````
```shell
git init YOUR_REPO
```
````

**Comment by codewithdev** [comment]
Picking this up. Happy to work on this too.

**Comment by skedwards88** [comment]
> * Is this applicable to URLs enclosed with`em` tags ? For example _https://github.com/octo-org/octo-repo _

Good question, @codewithdev . It looks like there are only ~5 places where this happens. I think we can replace the URL with `URL`. In the text preceding the example, we can say something like "Replace `URL` with the URL of your repository. For example, `https://github.com/octo-org/octo-repo`."

**Comment by codewithdev** [comment]
Got it. Thanks @skedwards88 i will make changes accordingly. 🙌
