### ISSUE TITLE
Issue event: `converted_to_discussion`

### ISSUE THREAD

**Issue by yanyongyu** [github/docs#20908]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types

### What part(s) of the article would you like to see updated?

Current issue events docs do not include the `converted_to_discussion` event. The event appears in the issues tranferred to discussion. 

The event may should be added to the docs.

### Additional information

<details>
<summary>event example</summary>

```json
{
	"id": 1,
	"node_id": "",
	"url": "",
	"actor": {},
	"event": "converted_to_discussion",
	"commit_id": null,
	"commit_url": null,
	"created_at": "",
	"performed_via_github_app": null,
}
```

</details>

**Comment by cmwilson21** [comment]
@yanyongyu Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! You or anyone else is welcome to open a PR to address this.
