### ISSUE TITLE
Drafting an issue via `curl` uses non-escaped `"` marks

### ISSUE THREAD

**Issue by runningcode** [github/docs#20962]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects#adding-a-draft-issue-to-a-project

### What changes are you suggesting?

Add `\` in front of `"` marks inside the json body.

### Additional information

Without this change you will get this error:
```
{
  "message": "Problems parsing JSON",
  "documentation_url": "https://docs.github.com/graphql"
}
```

**Comment by cmwilson21** [comment]
@runningcode Thank you for opening an issue and linking it to your PR! ✨
