### ISSUE TITLE
Document permission required to `approve` ✅ a pull request

### ISSUE THREAD

**Issue by jsoref** [github/docs#20989]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role

### What part(s) of the article would you like to see updated?

[`Permissions for each role`](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role) lists many roles, including:

* Merge pull requests on protected branches, even if there are no approving reviews

Oddly, it doesn't document `approving` itself.

### Additional information

We have a repository where we wanted to give someone `triage` permission, it seemed like it should be enough for them to approve a PR w/o giving them write access.

[Repository roles for organizations](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#repository-roles-for-organizations) lists:

> Triage: Recommended for contributors who need to proactively manage issues and pull requests without write access

`Triage` _sounds_ like the right permission. And the general overview fits. But...

In testing, it appears that `triage` is insufficient to grant meaningful approval as shown here:
![image](https://user-images.githubusercontent.com/2119212/193033844-4046e6f4-e30a-41dc-9c4c-c4cef2449deb.png)

Given that a repository can easily choose who has write access and who has triage, and who has neither, it doesn't seem unreasonable to expect that someone who could triage could also approve, w/o themselves being able to push directly to a repository.

That said. It is unreasonable to not be able to figure out from the documentation which role is necessary to actually approve.

**Comment by eagleicatcher** [comment]
![Uploading Screenshot_2022-09-22-20-21-22-37_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by cmwilson21** [comment]
👋 @jsoref - Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by 99Edorde** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role
> 
> ### What part(s) of the article would you like to see updated?
> [`Permissions for each role`](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role) lists many roles, including:
> 
> * Merge pull requests on protected branches, even if there are no approving reviews
> 
> Oddly, it doesn't document `approving` itself.
> 
> ### Additional information
> We have a repository where we wanted to give someone `triage` permission, it seemed like it should be enough for them to approve a PR w/o giving them write access.
> 
> [Repository roles for organizations](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#repository-roles-for-organizations) lists:
> 
> > Triage: Recommended for contributors who need to proactively manage issues and pull requests without write access
> 
> `Triage` _sounds_ like the right permission. And the general overview fits. But...
> 
> In testing, it appears that `triage` is insufficient to grant meaningful approval as shown here: ![image](https://user-images.githubusercontent.com/2119212/193033844-4046e6f4-e30a-41dc-9c4c-c4cef2449deb.png)
> 
> Given that a repository can easily choose who has write access and who has triage, and who has neither, it doesn't seem unreasonable to expect that someone who could triage could also approve, w/o themselves being able to push directly to a repository.
> 
> That said. It is unreasonable to not be able to figure out from the documentation which role is necessary to actually approve.

my

**Comment by subatoi** [comment]
Hi @jsoref, thanks for raising this! I just wanted to update you that I'm investigating this internally, and I'll get back to you as soon as I have something substantive.

**Comment by subatoi** [comment]
Just going to unassign myself from this as someone will pick up the PR review and continuing discussion will happen there. Thanks for raising that!
