### ISSUE TITLE
Remove $ sign from code examples to avoid prompting errors/Improve the Docs

### ISSUE THREAD

**Issue by codewithdev** [github/docs#21060]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All docs pages where `shell` includes `$` (wherever applicable).

<img width="756" alt="image" src="https://user-images.githubusercontent.com/44609609/193677441-cb825e59-4c24-4f12-83c4-aaf3e1a97072.png">

### What part(s) of the article would you like to see updated?

The commands displayed within the docs pages contains the `$` sign in the first place. Since there is no copy button 📄  available next to the command, a user may copy the entire command along with the `$` and paste it into the shell or local terminal that prompts an error to the user. 

We should Remove the `$` from the commands.

https://github.com/github/docs/issues/21060#tasklist-block-5a673d88-8702-4200-af2b-62553f477804

**Comment by SandeSanthosh** [comment]
Which File Bro ?

**Comment by vicodevv** [comment]
I would love to work on this

**Comment by subatoi** [comment]
Thanks so much for raising an issue, @codewithdev! I agree this isn't a good experience as it currently is. As it happens we're already looking at this precise issue internally and it's being discussed within the team, so I'll close this issue out. 

Thank you for your interest and passion in improving the GitHub Docs :sparkling_heart:
