### ISSUE TITLE
Some cURL examples have non-escaped `"` marks

### ISSUE THREAD

**Issue by jc-clark** [github/docs#21089]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects#adding-a-draft-issue-to-a-project

### What part(s) of the article would you like to see updated?

Relates to: https://github.com/github/docs/issues/20962

All of the cURL examples need to follow the same syntax. To avoid JSON parsing errors, whenever the `"` is inside another set of `"`, we need to escape the `"` with `\`.  

Here is [one example from the current article that will need updating](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects#updating-a-custom-text-number-or-date-field).

We need to update the rest of the article to match. This involves searching through the rest of the cURL examples and making sure escapes (`\`) exist everywhere they are needed.

### Additional information

https://github.com/github/docs/pull/20963 fixed one example.

**Comment by bpires** [comment]
Hey @avincodes! As a general rule, GitHub team members _"don’t assign issues to anyone. If you find an issue to work on, you are welcome to open a PR with a fix."_ Check the [contributing guide](https://github.com/github/docs/blob/main/CONTRIBUTING.md#solve-an-issue).

**Comment by jc-clark** [comment]
Hey @avincodes! Thank you for asking ❤️ 

Normally I would say "yes" since this seems like a quick fix and a perfect issue to welcome more Open Source contributors for our documentation. But it looks like @progfay started a pull request for this fix over in https://github.com/github/docs/pull/21133. 

Let us know if/when you find any other issues or improvements you'd like to make to our documentation. We'd love to loop your contributions in!

**Comment by Alotibi11** [comment]
M

**Comment by avincodes** [comment]
Perfect thank you for the response @jc-clark!
