### ISSUE TITLE
New secret scanning public key has not been published to API

### ISSUE THREAD

**Issue by dangardner** [github/docs#21108]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/overview/secret-scanning-partner-program#create-a-secret-alert-service

### What part(s) of the article would you like to see updated?

The change in https://github.com/github/docs/commit/01519f151f8bd99a4ffe04241a505e92727873df updated the key id in the examples from 90a421169f0a406205f1563a953312f0be898d3c7b6c06b681aa86a874555f4a to f9525bf080f75b3506ca1ead061add62b8633a346606dc5fe544e29231c6ee0d. However, the new key id has not been published in the official list of signing keys at https://api.github.com/meta/public_keys/secret_scanning. This causes all the examples of signature validation to break because they can't find the f9525b... key in the list fetched from the API.

**Comment by subatoi** [comment]
Hi @dangardner, and thanks for opening this issue! I agree this was confusing: those values should not be hardcoded into the docs, and users should always fetch the keys from https://api.github.com/meta/public_keys/secret_scanning. We've just merged a change to https://docs.github.com/en/developers/overview/secret-scanning-partner-program#create-a-secret-alert-service, which should make this clearer. 

Many thanks for your interest and passion in improving the GitHub docs!

**Comment by dangardner** [comment]
Thanks @subatoi. The change in https://github.com/github/docs/commit/27b28afd98287c4779dc8479ea08129f8c8d386f looks good to me. Closing.
