### ISSUE TITLE
Ubuntu-latest is not 18.04 anymore

### ISSUE THREAD

**Issue by thibauds** [github/docs#2110]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners

### What part(s) of the article would you like to see updated?

`ubuntu-latest` is supposed to be Ubuntu 18.04 according to the documentation but I tried a workflow with `ubuntu-latest` and it launched a Ubuntu 20.04 instead.

**Comment by hubwriter** [comment]
Hi @thibauds - thank you for raising this documentation issue. 

Could you provide a little more information about the repo on which you set this up and got a Ubuntu 20.04 on a GitHub-hosted runner when specifying `runs-on: ubuntu-latest` in the workflow file? 

My reason for asking is that when I tried this out just now in a code-scanning workflow on a repo hosted on github.com I got Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/54933897/103526725-3dd04200-4e79-11eb-993b-d4cb73d866fe.png)

_(For reference: I also tried `macos-latest` and got macOS 10.15, as documented, no macOS 11.0.)_

Thanks again 👍

**Comment by thibauds** [comment]
Hi @hubwriter,
Here is a sample repo:
https://github.com/thibauds/test-workflow/blob/main/.github/workflows/blank.yml
Using `ubuntu-latest` and getting `Ubuntu 20.04.01` in the actions logs.
![image](https://user-images.githubusercontent.com/5623472/104062006-ebd14880-51f9-11eb-9c44-3a71e4369cdb.png)

**Comment by skedwards88** [comment]
Thank you for this contribution! 🙇 This change is still being rolled out (https://github.com/actions/virtual-environments/issues/1816). Once the roll out it complete, we will remove this notice entirely. I am going to close this issue, but I hope you will continue contributing in the future!
