### ISSUE TITLE
workflow_dispatch contains branch-specific wording

### ISSUE THREAD

**Issue by victorlin** [github/docs#21113]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

### What part(s) of the article would you like to see updated?

Wording under `workflow_dispatch` that references branches should be changed. The ref can be any git ref (e.g. branch, tag), not just branch name. For example, the doc for [gh workflow run](https://cli.github.com/manual/gh_workflow_run) describes `--ref` as:

> The branch or tag name which contains the version of the workflow file you'd like to run

I expect these two doc pages to have similar wording.

**Comment by felicitymay** [comment]
@victorlin - many thanks for flagging this discrepancy and raising a pull request to update this article ✨

**Comment by felicitymay** [comment]
I think that you're right about this, but I'm going to confirm with the team because [`workflow_dispatch`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-53) also mentions only branches.

**Comment by felicitymay** [comment]
@victorlin - thanks for flagging and fixing this. We're happy to accept your update ✨ 

It looks as if https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-53 needs the same change. Is this something you'd like to fix?

**Comment by victorlin** [comment]
@felicitymay yes! PR opened: https://github.com/github/docs/pull/21463
