### ISSUE TITLE
Translate a sidebar area in the spanish version

### ISSUE THREAD

**Issue by Franqsanz** [github/docs#21126]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Hello, I have seen that there is an area of ​​the sidebar that is not translated into Spanish, I leave you a screenshot:

![Captura de pantalla 2022-10-05 191051](https://user-images.githubusercontent.com/44296203/194173791-2676a3fa-523b-4f82-8ebd-4ff0a9a17f49.png)

If possible. I would like to work on this problem.

### What changes are you suggesting?

It would be good if it was translated, since the rest of the sidebar is almost translated.

Thank you very much!

**Comment by jsoref** [comment]
fwiw, https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations

**Comment by steveward** [comment]
Thanks for the issue @Franqsanz. Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service, where all translation activity happens. I'm going to close this out.

**Comment by Franqsanz** [comment]
I understand, thank you very much.
