### ISSUE TITLE
Create personal access token link is broken.

### ISSUE THREAD

**Issue by dhruv-porwal** [github/docs#21173]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Sir/Ma'am  kindly assign this task to me.

### What part(s) of the article would you like to see updated?

Create personal access token. 

### Additional information

Link is broken.

**Comment by subatoi** [comment]
Hi @dhruv-porwal, thanks for opening an issue. From [your PR](https://github.com/github/docs/pull/21172) it looks like you're suggesting the broken link in question is "[Creating a personal access token](https://docs.github.com/en/enterprise-cloud@latest/github/authenticating-to-github/creating-a-personal-access-token)" at the bottom of https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on. When testing this I'm seeing the link redirecting as expected with a 301 redirect, so I'm unsure what you mean by broken. If you can provide evidence of a bad response code then we'll be happy to take a look at this. Thanks!

**Comment by dhruv-porwal** [comment]
what is the reason for this error then?
 at link:


https://github.com/github/docs/blob/main/content/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on.md

The two highlighted links are showing error 404

**Comment by subatoi** [comment]
I see: the link you've shared is viewing the rich text preview of our docs in Markdown, in the repository that's used for the content served at docs.github.com. 

The link you highlighted as broken in your PR Is automatically set to redirect as part of the static site build for docs.github.com, which is why a 301 is returned as expected. However, you're right that when viewing this in the repo itself, it returns a 404. 

I've made a slight amendment in the form of a suggestion to your PR, to make it a relative URL. When that's resolved, we can get that merged for you. Thanks!

**Comment by dhruv-porwal** [comment]
Thank you for the clarification.

**Comment by dhruv-porwal** [comment]
sir kindly mark it hacktoberfest  accepted

https://github.com/github/docs/pull/21172

**Comment by DarkDose75** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> Sir/Ma'am  kindly assign this task to me.
> 
> ### What part(s) of the article would you like to see updated?
> 
> Create personal access token. 
> 
> ### Additional information
> 
> Link is broken.

![image](https://user-images.githubusercontent.com/115435360/195864176-05fda345-783d-4f44-97ff-89a1d9b7216d.jpeg)
