### ISSUE TITLE
Labels with periods do not render

### ISSUE THREAD

**Issue by aspaninks** [github/docs#21207]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#labels

### What part(s) of the article would you like to see updated?

Article states: 

> When referencing the URL of a label in Markdown, the label is automatically rendered.

My repo has labels with a period `.` in them, e.g.: `Thing.Abc`, `Thing.Xyz`, etc.
These labels do not render automatically via the described method.
I also tried an escape character `\.` and a unicode notation `&#0046;`

Expected outcome:
Update documentation to mention labels should not contain `.` 

### Additional information

See https://github.com/github/docs/issues/18704, it contains a good explanation and example, which I used to confirm it was not user-error. I was able to get non-period labels to render successfully.

**Comment by cmwilson21** [comment]
@aspaninks Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by sabrowning1** [comment]
Hi @aspaninks, thanks for opening this issue! 💛 This would be a helpful addition to the docs. You or anyone others are welcome to open a PR with this change 👍🏼

**Comment by ujjwal-shekhar** [comment]
Hi can I work on this
