### ISSUE TITLE
The menu nor breadcrumb works on a mobile phone view

### ISSUE THREAD

**Issue by atreeon** [github/docs#21210]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

all

### What changes are you suggesting?

show the breadcrumb and the menu when viewing the docs on a mobile phone

### Additional information

If I'm viewing the github docs on a mobile phone I do not see the sub menu items.

For example in desktop version I have the menu on the left with the sub entries and sub sub entries
``` 
Using workflows
 |-Using jobs
    |-Use jobs in a workflow 
```
but if I'm on mobile and I press the 'burger' button at the top right, all I see is the higher level menu items.

Also on desktop we are provided a breadcrumb navigation (although looking again that doesn't seem to display properly on desktop because it shows
GitHub Actions / Use jobs in a workflow
it should show
GitHub Actions / Using jobs / Use jobs in a workflow

This has the effect of not being able to navigate or even use the docs on a mobile phone.

_(hope I'm not missing something simple!)_

**Comment by cmwilson21** [comment]
@atreeon Thanks again for opening this. I spoke with our team and they are aware of this issue. Since it's something we are tracking internally, I'm going to go ahead and close this issue now.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by atreeon** [comment]
oh ok (personally I'd leave it open and close when it is fixed)

**Comment by atreeon** [comment]
Hi @cmwilson21.  This is still not functioning correctly but the issue says 'done' and 'closed'.  Do you have a link to the task where the work is happening.  Very frustrating as I basically can no longer use the documentation using my laptop!!!
