### ISSUE TITLE
REST quickstart and guide examples still have a v3 reference in them for examples

### ISSUE THREAD

**Issue by tanant** [github/docs#21327]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/quickstart
https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api

### What part(s) of the article would you like to see updated?

The docs linked (the quickstart and a getting started with the REST API) both have accept headers which include `v3` as part of the the examples - I was going through the docs and noticed that this is now flagged as no-longer-required:

> Note: In the past, we recommended including v3 in your Accept header. This is no longer required and will have no impact on your API requests.

(https://docs.github.com/en/rest/overview/media-types)

**Comment by cmwilson21** [comment]
@tanant Thank you for opening an issue and linking it to your PR! ✨
