### ISSUE TITLE
MacOS 12+ - Narrow Host definition in .ssh/config

### ISSUE THREAD

**Issue by ChrisKeefe** [github/docs#21333]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Generating a new SSH Key...](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

## Environment

Adding the recommended directive to `~/.ssh/config` breaks other necessary SSH connections on my company-managed Macbook running MacOS 12 (Monterey)

BREAKING:
```
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
```
OK:
```
Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
```

Restricting the recommended new behavior to `Host github.com` allows both connections to proceed as expected. As a general principle, recommending more tightly-scoped `Host` settings might be a safer bet.

**Comment by cmwilson21** [comment]
@ChrisKeefe Thank you for opening an issue and linking it to your PR! ✨

**Comment by cmwilson21** [comment]
Closing this as I believe the merged PR fixes it 💖
