### ISSUE TITLE
Creating a composite action - Creating an action metadata file is using deprecated "::set-output"

### ISSUE THREAD

**Issue by neilime** [github/docs#21341]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/main/content/actions/creating-actions/creating-a-composite-action.md?plain=1#L85

**Comment by fingolfin** [comment]
Also https://github.com/github/docs/blob/main/content/actions/using-jobs/defining-outputs-for-jobs.md does this... probably would be a good idea to grep this repository for `set-output` ?

**Comment by fingolfin** [comment]
(BTW I am surprised GitHub started to nag all projects about this a few days ago before even updating their own actions and documentations. Perhaps next time this should be the other way around?)

**Comment by cmwilson21** [comment]
@fingolfin Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Thanks for reporting this, @neilime! It took us a while to catch and version all of the docs mentions; and it was fixed in https://github.com/github/docs/commit/ad70a7012fc7d664cce60c12344a87cf85d780e3. 

Please let us know if we missed anything.
