### ISSUE TITLE
Description of when GitHub Actions are free is confusing.

### ISSUE THREAD

**Issue by hwine** [github/docs#2134]
### What article on docs.github.com is affected?

[GitHub Actions Usage Limits](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration)

### What part(s) of the article would you like to see updated?

In the [about billing](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#about-billing-for-github-actions) section, the description of what is considered free is ambiguous.

The text "free for public repositories and self-hosted runners" could be interpreted either as:
- "free for public repositories using self-hosted runners" - My incorrect reading
- "free for public repositories" and also "free when using self-hosted runners" - the correct reading per my sales rep

I expect this issue to facilitate acceptance of a forthcoming PR. :)

**Comment by pekis1** [comment]
> []() **

1. 

- [ ]  @#

1. 

- [ ] __

**

**Comment by pekis1** [comment]
> `
Duplicate of #`

**Comment by pekis1** [comment]
> Duplicate of #

@cadef #2314
