### ISSUE TITLE
'Locking conversations' article doesn't cover effect on reactions/votes

### ISSUE THREAD

**Issue by keunes** [github/docs#21343]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations

### What part(s) of the article would you like to see updated?

The paragraph starting with 'While a conversation is locked' - it doesn't describe that also reactions (e.g. thumbs-up) and votes (in discussions) are disabled when a thread is locked.

### Additional information

For me personally this behaviour is a bit unsuspected, hence I think it should be explicitly documented (I also registered a [request](https://github.com/orgs/community/discussions/36107) to make it possible to change this).

**Comment by cmwilson21** [comment]
@keunes Thank you for opening an issue and linking it to your PR! ✨
