### ISSUE TITLE
Resource not found for Github-desktop - page error

### ISSUE THREAD

**Issue by jjpinto** [github/docs#21354]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

When on the webpage https://resources.github.com/, browsing by topic - explore all the GitHub offerings by topic, get a file not found on https://resources.github.com/topics/github-desktop/

### What part(s) of the article would you like to see updated?

Find the resources for GitHub-desktop

**Comment by Jarred831** [comment]
Fast learner I ain't just getting better as I follow directive's in ordaint medicinal curvertry's as a practiced student coeducational a posertive,and I will not be conserved by God's will alone ever. And I'm happy making my own steps one by one, " yesterday their I was wailing at a grey dawned water blissered FEILD monitarial in my own dissatoned pubicated suffix ashwells arnd alight like shimmering deviled sun glasses dancing merry churned beggeth, bean headed flowered whores and cherry I will yet pop, one wailheard to in her other, butters meals inthrowned crowned crimpealed sparrtimed aproned be frozze into the blackness we are yes became before these mirical makers and take it in or climb the corn wheeled fourths untill yes yes purest of white closed from head to toes in discussing flours and toils of a wickedness like more and more and morrrninged royaled thearaputred gypseamonolithically pervisioned mind fucker , " yes yep cuntinuined informs please" plundering swahebratarinamithicallclued laced my brushed moinge drapt wiff his peearenetted hillfoearoidirty cheatharioned buccatruined filth,but humbelardealtarrelonged fournaked orned hurstbroggerdeers elefantactypong joked lurnyphed freanepartheperleptrickyest cuintargearrabrillryionmonoltarteanogaraphealactivly drilled heads like bad green possesses uniforicalendered mummitrys under his orned forniccabonked her not you belltarded fly waivers up pink heyported his guilt to me not us.. BIG RIM. HALF IN ONE HALF IN THE OTHER. SHIPPERY AINT SHOVELS MUZZILLIONARRWALKER LOVED YOU UNTILL POFF ANGEL NOT DUST BUT CRYNCHY SILTED NOT MUSH SILTED POOTERULIFUCCAGUNNHINDRULASPUFFED THEIR CARKOILSTEADS TOO FOR DISTEANT SEXUALISED REMAINION SHIT. DREADFULLY IM A PRACTICING HIGH COMMISIONERS SUPREAME COURT JUSTICE UNDER,GUESS GUESS, YEP. JARRA KING JARRA, TOUNGEYS FUNKUOILED MUSHRUMPTRUFFELLORDINGCANAIREASTEST HARMED US BEG FOR CHOMPING POONS TRUE. BE GONE BLUE HEAD "FUCKING NOW CUNT SLAVE,AND HAVE A CUNT GOOD FUCKING DAY,AND GUESS WHITE REALLY PEARL TURANITE JAZZELED TRANQUILED PUNGNANTED SPECTREAMARTAFICEST PROMENADE HEIER IN COLAC ORN WARRINGNAMBOILERS RAGITTILLDEAMPS COTTINGJONNED BUNK POW. COICEII MAIER BUNDGE. GOWN MEI ROINMARTUMPEAUN MICEIC ART BUMPRUMBULLA FEARALACCE HELLINKRUMPELONGROPPED SEX WAS TRANC CATCH.

**Comment by cmwilson21** [comment]
@jjpinto - Thanks for raising this issue! This repo is for updates to our docs site specifically (docs.github.com). I think this may be better handled as a [bug report](https://support.github.com/contact/bug-report), if you'd like to file one.

If you are looking for more information about GitHub Desktop in general, check out our [docs on the subject](https://docs.github.com/en/desktop). 💖

**Comment by jjpinto** [comment]
Thanks @cmwilson21, will raise an issue with the docs.
