### ISSUE TITLE
recovering-your-ssh-key-passphrase.md is outdated

### ISSUE THREAD

**Issue by lxjv** [github/docs#21366]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/troubleshooting-ssh/recovering-your-ssh-key-passphrase

### What part(s) of the article would you like to see updated?

Changing 

> ... [switch to HTTPS cloning](https://docs.github.com/en/github/getting-started-with-github/managing-remote-repositories) so you can use your GitHub **password** instead.

into

> ...[switch to HTTPS cloning](/github/getting-started-with-github/managing-remote-repositories) so you can use a **Personal Access Token** instead.

**Comment by cmwilson21** [comment]
@lxjv Thank you for opening an issue and linking it to your PR! ✨
