### ISSUE TITLE
Some pages say "the repository’s default branch (usually master)" despite it being "main" more often now.

### ISSUE THREAD

**Issue by HimbeersaftLP** [github/docs#21389]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/repos/contents#download-a-repository-archive-zip

### What part(s) of the article would you like to see updated?

The docs say "The branch name. Default: the repository’s default branch (usually master)" despite a new repo having instructions that would lead to a "main" branch being created instead.

### Additional information

Apparently this is from the OpenAPI definition so it can't be changed in this repository.

**Comment by cmwilson21** [comment]
@HimbeersaftLP Thanks for opening this issue and submitting a PR. Any changes in the `rest description` have to be done internally. Thanks for bringing this to our attention! ✨
