### ISSUE TITLE
Some words were conjugated incorrectly and with wrong meanings (pt-BR)

### ISSUE THREAD

**Issue by LucasHT22** [github/docs#21391]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/tree/main/translations/pt-BR/data/learning-tracks

### What part(s) of the article would you like to see updated?

Some words were conjugated incorrectly and with wrong meanings (pt-BR)

https://github.com/github/docs/issues/21391#tasklist-block-04bd1c55-5022-409e-90a0-7e26c3a2aba1

**Comment by cmwilson21** [comment]
Closed per comment [here](https://github.com/github/docs/pull/21392#issuecomment-1280907662)
