### ISSUE TITLE
raw `(% data variables.product.prodname_actions %}` in `run` object

### ISSUE THREAD

**Issue by jsoref** [github/docs#21400]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#run-object

### What part(s) of the article would you like to see updated?

This apparently didn't work:
> (% data variables.product.prodname_actions %} 

### Additional information

<img width="755" alt="image" src="https://user-images.githubusercontent.com/2119212/196058722-0476a7e6-6b10-4a8f-b7fc-3d72f1ceacab.png">

**Comment by robledo6** [comment]
Autentifica por favor

**Comment by cmwilson21** [comment]
👋 @jsoref - Thanks for catching this! I'll get it triaged for a writer to review ⚡

**Comment by felicitymay** [comment]
Thanks for flagging this typo @jsoref. It seemed quickest just to raise a PR to fix the variable: https://github.com/github/docs/pull/21451.
