### ISSUE TITLE
Make changes on a new branch in "Contributing to projects"

### ISSUE THREAD

**Issue by tobyhodges** [github/docs#21409]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[_Contributing to projects_](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) (https://docs.github.com/en/get-started/quickstart/contributing-to-projects)

### What part(s) of the article would you like to see updated?

The article describes a workflow of forking a project, cloning it locally, making changes, pushing them to the user's fork, and opening a pull request. This is clearly explained but I think could be improved by guiding the user to create a new branch after cloning, and making the changes on that branch. 

As it is currently written, a new user following the steps in the current version of [the _Contributing to projects_ guide](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) would be pushing their changes to the default branch of their fork, and making the pull request from there. 

In my view, it would be better practice to make changes on a new branch. It would avoid potential difficulties further down the line, e.g. when the user wants to suggest other changes before the changes they first made (on the default branch of their fork) have been merged upstream. It seems to fit better with [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow#following-github-flow) too.

### Additional information

I am suggesting a change to this specific section of the guide: [_Making and pushing changes_](https://docs.github.com/en/get-started/quickstart/contributing-to-projects#making-and-pushing-changes).

Happy to make a PR to address this if you agree that the steps in the guide should be modified.

**Comment by felicitymay** [comment]
@tobyhodges - thanks for raising this point. You're right to point out the discrepancy between this article and GitHub Flow. Looking at the article, I can see that it's overdue a review generally, and I will check that it is on our internal list of articles to refresh.

In the meantime, your suggestion to bring the article inline with the GitHub Flow is a great idea. The existing sections are intended to be quite brief, so I suggest that we add a new heading of "Creating a branch to work on", before "Making and pushing changes".
