### ISSUE TITLE
Clarify `$HOME` environment variable in Actions docs

### ISSUE THREAD

**Issue by w-bonelli** [github/docs#21424]
Although it's been removed from the default variables table, the docs [still describe `$HOME` as a default environment variable](https://github.com/github/docs/blob/main/content/actions/learn-github-actions/environment-variables.md#naming-conventions-for-environment-variables) in the naming conventions section. This initially gave me the impression that the runner will ensure it is set in all shells on all platforms. Is it maybe worth removing mention of `$HOME` from the naming conventions section, or clarifying that it is Unix-specific? Happy to create a PR if that would be helpful

_Originally posted by @w-bonelli in https://github.com/github/docs/issues/328#issuecomment-1280029793_

**Comment by cmwilson21** [comment]
👋 @w-bonelli - Thanks for opening this issue! I'll get it triaged for review 👀

**Comment by lucascosti** [comment]
Thanks for pointing this out, @w-bonelli!

> Is it maybe worth removing mention of `$HOME` from the naming conventions section

Yep, I think this is the best approach. Feel free for you (or anyone else) to open a PR! 🙇‍♂️
