### ISSUE TITLE
404 on links to GitHub Brand Guide in `contributing/content-styleguide.md`

### ISSUE THREAD

**Issue by HonkingGoose** [github/docs#21478]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The [`contributing/content-style-guide.md`](https://github.com/github/docs/blob/main/contributing/content-style-guide.md) file on the `github/docs` repository has broken links to the official GitHub Brand Guide. When I click on those links I get a `404` message.

I also can't get to the Brand guidelines anymore from the [official GitHub Brands homepage](https://brand.github.com/) anymore.

### What part(s) of the article would you like to see updated?

Expected outcome:

1. Have working links to GitHub brand guidelines
1. Or, copy/paste relevant parts into the `github/docs` files, so you're not relying on an outside resource anymore

### Additional information

Maybe the broken links problem should be raised at the [`github/brand` repository](https://github.com/github/brand) instead. So feel free to close my issue, and let a member of GitHub staff report the problem to the upstream repository. 😉

**Comment by cmwilson21** [comment]
@HonkingGoose Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by tuxtvixx** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> The [`contributing/content-style-guide.md`](https://github.com/github/docs/blob/main/contributing/content-style-guide.md) file on the `github/docs` repository has broken links to the official GitHub Brand Guide. When I click on those links I get a `404` message.
> 
> I also can't get to the Brand guidelines anymore from the [official GitHub Brands homepage](https://brand.github.com/) anymore.
> 
> ### What part(s) of the article would you like to see updated?
> 
> Expected outcome:
> 
> 1. Have working links to GitHub brand guidelines
> 1. Or, copy/paste relevant parts into the `github/docs` files, so you're not relying on an outside resource anymore
> 
> ### Additional information
> 
> Maybe the broken links problem should be raised at the [`github/brand` repository](https://github.com/github/brand) instead. So feel free to close my issue, and let a member of GitHub staff report the problem to the upstream repository. 😉

**Comment by cmwilson21** [comment]
👋 Thanks again for opening this issue! The brand guideline links have been removed in an internal PR, so I'm going to go ahead and close out this issue 💛
