### ISSUE TITLE
Authentication in workflow docs suggest to inject PAT into workflows. Doing so might be a security risk for the user's account.

### ISSUE THREAD

**Issue by grmpfhmbl** [github/docs#2147]
### What article on docs.github.com is affected?

[Authentication in a workflow - Permissions for the `GITHUB_TOKEN`](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token)

### What part(s) of the article would you like to see updated?

In the section explaining the permissions for the `GITHUB_TOKEN` underneath the permissions table it's suggested to create a *personal access token* if other permissions are needed in a workflow. I'd consider doing so a security risk for the user's account - especially for inexperienced users. At least there should be a warning that this might have unintended consequences especially if the token has write access, as the permission for the PAT will be for **all** repositories the user has access to. Not only the one that runs the workflow.

The documentation [Security hardening for GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions) states that very clearly in the section about [cross repository access](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#considering-cross-repository-access). I'd consider injecting a PAT into a workflow as a secret the last thing that should be done and only if it's the last available option. Please put at least a warning with a link to the security hardening documentation for explanation of the problem.

**Comment by janiceilene** [comment]
@grmpfhmbl Thanks for opening an issue! I'll get this triaged for the right team to take a look 👀

**Comment by shnoori7** [comment]
`conect`

**Comment by herackovalucka** [comment]
https://github.com/github/docs/issues/2147#issuecomment-778859065

**Comment by herackovalucka** [comment]
> `conect`

**Comment by janiceilene** [comment]
Thanks for opening an issue @grmpfhmbl! I've spoken to the team and the "Creating a personal access token" linked in the article has a red warning in step 9, so we're not going to update these docs right now.
