### ISSUE TITLE
Difficult to see Samples on low resolution PC

### ISSUE THREAD

**Issue by onein528** [github/docs#21480]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

![image](https://user-images.githubusercontent.com/62196528/196674874-d9d7af56-0f39-49d6-9636-13c88884c070.png)

### What changes are you suggesting?

Update UI to be able to expand them.

**Comment by cmwilson21** [comment]
@onein528 Thanks for opening an issue. Sorry for the delay here! 

I've reported this feedback to the team. ✨
