### ISSUE TITLE
PowerShell code is hidden when using anchors, as pwsh tab at the top is bypassed / Add tab to code itself instead of page

### ISSUE THREAD

**Issue by potatoqualitee** [github/docs#21503]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

workflow-commands-for-github-actions.md

### What changes are you suggesting?

I recently had to update my Actions to comply with the new `$GITHUB_OUTPUT` requirement. It took me forever to figure out that in PowerShell, it is `$env:GITHUB_OUTPUT`.

Your blog post, [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), only listed shell commands. So I followed the provided link to an anchor on the docs site at [Workflow commands for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) to see how to do it in PowerShell.

It was only shell. It took me about 30 minutes to figure out that I needed to use `$env:GITHUB_OUTPUT` and I wanted to save other people time, so I ended up cloning the docs site to add the PowerShell info under the shell code blocks. 

When I opened up VS Code to add the PowerShell code, I saw PowerShell was already there. What? So I went back to the page and did a Ctrl-F to find where PowerShell was mentioned and it was way at the top.

![image](https://user-images.githubusercontent.com/8278033/196902898-62295bca-981e-420c-925d-b1f209529716.png)

As I was writing this issue, it occurred to me that for clarity's sake, the PowerShell code would have been better placed right under the shell code, or my preference, as a tab within the code block itself like Microsoft docs. The tab at the top is neat (I like how it makes the whole page about PowerShell) and pretty but does not function as well as other alternatives when anchors are used.

### Additional information

Can  you please also update the blog post ([GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)) to mention pwsh?

**Comment by cmwilson21** [comment]
@potatoqualitee Thanks for opening an issue! We are actually working on this internally, so I've shared your feedback with the team and will go ahead and close this issue. 💛 

In the meantime, you can find out more about our tool-switcher in our [contributing docs](https://github.com/github/docs/blob/main/contributing/tool-switcher.md). 

Thank you so much for your interest in improving our docs! ✨
