### ISSUE TITLE
Updating docs to reflect use of `$GITHUB_OUTPUT` environment files

### ISSUE THREAD

**Issue by oliverjfletcher** [github/docs#21548]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions

### Creating a Docker container action

#Summary 

The [below](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#writing-the-action-code) should be updated to align with the `$GITHUB_OUTPUT` examples in the [changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples)

>Next, the script gets the current time and sets it as an output variable that actions running later in a job can use. In order for {% data variables.product.prodname_dotcom %} to recognize output variables, you must {% ifversion actions-save-state-set-output-envs %}write them to the ```$GITHUB_OUTPUT``` environment file:```echo "<output name>=<value>" >> $GITHUB_OUTPUT`{% else %}use a workflow command in a specific syntax: ```echo "::set-output name=<output name>::<value>"```{% endif %}. For more information, see "[Workflow commands for {% data variables.product.prodname_actions %}](/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter)."

### Workflow commands for GitHub Actions

The [below](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions) should be updated to align with the `$GITHUB_OUTPUT` examples in the [changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples)

> You can use the `set-output` command in your workflow to set the same value:

> run: echo '::set-output name=SELECTED_COLOR::green'

> run: Write-Output "::set-output name=SELECTED_COLOR::green"

> ::set-output name={name}::{value}

> Write-Output "::set-output name=action_fruit::strawberry"

> Enables or disables echoing of workflow commands. For example, if you use the `set-output` command in a workflow, it sets an output parameter but the workflow run's log does not show the command itself. If you enable command echoing, then the log shows the command, such as `::set-output name={name}::{value}`.

> echo '::set-output name=action_echo::disabled'
> echo '::echo::on'
> echo '::set-output name=action_echo::enabled'
> echo '::echo::off'
> echo '::set-output name=action_echo::disabled'

> write-output "::set-output name=action_echo::disabled"
> write-output "::echo::on"
> write-output "::set-output name=action_echo::enabled"
> write-output "::echo::off"
> write-output "::set-output name=action_echo::disabled"

> ::set-output name=action_echo::enabled

> Only the second `set-output` and `echo` workflow commands are included in the log because command echoing was only enabled when they were run. Even though it is not always echoed, the output parameter is set in all cases.

**Comment by cmwilson21** [comment]
@oliverjfletcher Thanks for opening and issue, providing such great information, and linking it to your PR! 💖

**Comment by cmwilson21** [comment]
Closing this issue per[ comment here](https://github.com/github/docs/pull/21550#issuecomment-1294253453) 💛
