### ISSUE TITLE
Use `$GITHUB_OUTPUT` environment file for Broken Doc Links workflow

### ISSUE THREAD

**Issue by oliverjfletcher** [github/docs#21549]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

N/A this affects the GitHub Action workflow for fixing broken links in the docs

### Summary 

Update [check-broken-links-github-github.yml](https://github.com/github/docs/blob/main/.github/workflows/check-broken-links-github-github.yml) to use $GITHUB_OUTPUT environment file per the [change log](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples)

### Cuurent State

```yaml
run: echo "::set-output name=title::$(head -1 broken_github_github_links.md)"
```
### Future State

```yaml
run: echo "title=$(head -1 broken_github_github_links.md)" >> $GITHUB_OUTPUT
```

**Comment by cmwilson21** [comment]
@oliverjfletcher Thanks for the issue. I've edited the PR slightly so it includes this issue, too. ✨

**Comment by oliverjfletcher** [comment]
> @oliverjfletcher Thanks for the issue. I've edited the PR slightly so it includes this issue, too. ✨

I reverted the push per this [comment](https://github.com/github/docs/pull/21550#issuecomment-1287652672), but let me know if I should push the change back to the branch, thanks!

**Comment by cmwilson21** [comment]
Closing this issue per [comment here](https://github.com/github/docs/pull/21550#issuecomment-1294253453). 💛
