### ISSUE TITLE
Codespaces Samples - Add SQL Sample 

### ISSUE THREAD

**Issue by cmaneu** [github/docs#21581]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces

### What part(s) of the article would you like to see updated?

Update the Code examples section with SQL examples.

**Comment by cmwilson21** [comment]
@cmaneu Thanks for opening an issue and linking it to your PR! 💖
