### ISSUE TITLE
Broken markup in OIDC docs

### ISSUE THREAD

**Issue by porridge** [github/docs#21606]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#requesting-the-jwt-using-environment-variables

### What part(s) of the article would you like to see updated?

The shell command should be:
```
        IDTOKEN=$(curl -H "Authorization: bearer ${{steps.script.outputs.TOKEN}}" ${{steps.script.outputs.IDTOKENURL}} -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
```

But the stuff inside `{{ }}` seems to be pre-processed out, leaving just `$` signs. See screenshot below.

### Additional information

![Screenshot from 2022-10-25 12-04-13](https://user-images.githubusercontent.com/489420/197745881-ac26f1bf-b592-42fb-9292-3ee34ae46ea1.png)

---
maintainer edit

### Content plan [here](https://github.com/github/docs/issues/21606#issuecomment-1292716025)

**Comment by cmwilson21** [comment]
@porridge Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for reporting this! All instances of `${{ ... }}` need to be wrapped with `{% raw %}`/{% endraw %}` in order to render properly. You or anyone else is welcome to open a PR to address this.
