### ISSUE TITLE
Update "Commits" API reference in "About protected branches" docs

### ISSUE THREAD

**Issue by fstavela** [github/docs#21608]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

### What part(s) of the article would you like to see updated?

The link in the [Require status checks before merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging) section of the [About protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) page says "Repositories", but refers to "Commits" part of the API docs.

I think it should say "Commits" instead of "Repositories". Also, I think we should update the link to more specific part of the docs - commits/statuses.

**Comment by cmwilson21** [comment]
@fstavela Thank you for opening an issue and linking it to your PR! ✨
