### ISSUE TITLE
Abuse to threatening Harrassment,They create my nude pictures and sent to my phone contact 

### ISSUE THREAD

**Issue by Smekbu** [github/docs#21605]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Frauds  application link below :https://apkfortreesescash.com/dl/25461/app-v3.14.007.apk

### What part(s) of the article would you like to see updated?

They Screenshot and sent to my family abuse 

### Additional information

Any hope to remove the data in their system

**Comment by cmwilson21** [comment]
Sorry, this is off topic for the Docs repo and will be closed. 💛

**Comment by Nhida2002** [comment]
Ok

Vào 20:08, Th 3, 25 thg 10, 2022 Courtney Wilson ***@***.***>
đã viết:

**Comment by Nhida2002** [comment]
pk

Vào 20:18, Th 3, 25 thg 10, 2022 Dung Phanduc ***@***.***>
đã viết:
