### ISSUE TITLE
Add GHES 3.7 Performance Numbers

### ISSUE THREAD

**Issue by susanzhang27** [github/docs#21612]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

getting-started-with-github-actions-for-github-enterprise-server.md

### What part(s) of the article would you like to see updated?

The performance numbers matrix for vCPU to connected runners should be now reflected for 3.7. GHES 3.7 numbers are the same as 3.6.

**Comment by cmwilson21** [comment]
👋 @susanzhang27 - Thanks for opening an issue and linking it to your PR! ✨
