### ISSUE TITLE
Correct issue with "Configuring rate limits" link pointing to wrong location

### ISSUE THREAD

**Issue by mzzmjd** [github/docs#21622]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.7/admin/release-notes#3.7.0

### What part(s) of the article would you like to see updated?

The section:

> To increase the security of the Management Console, site administrators can configure the rate limit for sign-in attempts, as well as the lockout duration after exceeding the rate limit. For more information, see "[Configuring rate limits](https://docs-internal-31313-d3cd3a.preview.ghdocs.com/enterprise-server@3.7/admin/configuration/configuring-your-enterprise/configuring-rate-limits#configuring-rate-limits-for-authentication-to-the-management-console)."

Refers to a location that is not available to the public.

**Comment by cmwilson21** [comment]
@mzzmjd Thank you for opening an issue and linking it to your PR! ✨
