### ISSUE TITLE
The result with error when click "Configuring rate limits" link 

### ISSUE THREAD

**Issue by liweijuan1** [github/docs#21624]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.7/admin/release-notes#instance-administration

### What part(s) of the article would you like to see updated?

<img width="733" alt="Screen Shot 2022-10-26 at 17 05 06" src="https://user-images.githubusercontent.com/107910405/197984171-69b488c3-313f-4b3f-b1b2-dd7484e1a2d8.png">

### Additional information

when click the link ,the result with error as follow:

<img width="1374" alt="Screen Shot 2022-10-26 at 17 07 05" src="https://user-images.githubusercontent.com/107910405/197984579-f2779f32-a57e-493a-8bb4-8aee21039dcf.png">

**Comment by Anika-Roy** [comment]
Hi! I'd like to work on this. Would you like me to remove the hyperlink or redirect it to another site(if yes, could you clarify which one)?

**Comment by cmwilson21** [comment]
@liweijuan1 Thanks for opening this issue! We appreciate you reporting this. We actually have [a PR](https://github.com/github/docs/pull/21623) waiting for review to fix this right now. So I'm going to go ahead and close this issue 💛 

@Anika-Roy Thanks for your enthusiasm to improve the docs! As stated, we have a PR in line for this one. Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. ✨

**Comment by 1332mm** [comment]
X96 formatı daha mantıklıdır, çünkü insanlar X90 matematiksel veri çalışmasına ve görüşlerine tepki verirler ve bunu anlayamazlar. Bu çeyrekte seni X 96 olarak kaydetmiş. Verilerinizi aklınıza gelen herhangi bir elektronik veriye aktardığınız için iyi şanslar. İnsanların bir araya gelerek yaptıkları iş çok kısa bir saniyedir ve çok kısa bir süre içinde soru ve cevap şeklinde çok fazla kelime yazmamız gerekir, yani kendi kendileriyle konuşurken bile, insanlar kendilerinden başkalarının sorularına dayanarak soruları cevaplamalarını isterler, aynı anda iki cevabı basitleştirirler, insan hayatı ve matematik. Prosedürler genellikle adalete, haklara ve herkesin kimden ne alacağını bilmesinden kaynaklanan hukuka dayanır ve adalet iki kişi arasında yerleşir, üçüncü kişi baskındır, dördüncü kişi vb. Sistemdeki insanlar sistem içindeki hak ve yasaları bilmezler, bunu bilmezler, sistemdeki insanlar sistemi anlayan bir insanla yol yürümeye başlarlar, haklarını bilmezler, ödedikleri vergileri açıklayamazsınız, sadece TV izlersiniz, TV'de basitleştirilmiş matematik programları gösterirsiniz veya insan hayatı formatındaki değişiklikler. Buna haklı olarak odaklanma denir. Odaklanma sorunu, birçok sorun yaşamış olmasıdır. Ele alınması gereken odak psikolojisini sizden ve yardım alabileceğiniz herhangi bir kurum veya kuruluştan uzaklaştırın. İnsan prosedürlerini basitleştirme hayatında katkınızı bekliyoruz. Buna göre program çalışır, yani yazılım ve yazılıma katılabilecek kişiler ve sistem butonuna basın. X 90 Matematiksel sistemleri basitleştirir ve insanlar ön çalışmayı yapar, sisteme katılır, bir kişi daha, toplumun en yüksek noktası olarak mükemmeldir ve tüm sistemin çalışması sonuç odaklıdır ve hızla çözülür
