### ISSUE TITLE
Parameter setup_url is missing from GitHub App Manifests

### ISSUE THREAD

**Issue by blakegearin** [github/docs#21659]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.6/developers/apps/building-github-apps/creating-a-github-app-from-a-manifest#github-app-manifest-parameters

### What part(s) of the article would you like to see updated?

The "GitHub App Manifest parameters" section should be updated to include all possible parameters, including `setup_url`. I have verified it can be passed in and set accordingly, but it's not documented as far as I can tell. Others may fall into this category as well.

### Additional information

Here's a comparison between the parameters listed in the manifest documentation versus the URL parameters documentation.

|Parameter|[URL parameters](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app-using-url-parameters#github-app-configuration-parameters)|Manifest parameters|
|--|:-:|:-:|
|`name`|✅|✅|
|`description`|✅|✅|
|`url`|✅|✅|
|`callback_urls`|✅|✅|
|`public`|✅|✅|
|`request_oauth_on_install`|✅|❌|
|`setup_url`|✅|❌|
|`setup_on_update`|✅|❌|
|`webhook_active`|✅|❌ see: `hook_attributes`|
|`webhook_url`|✅|❌ see: `hook_attributes`|
|`hook_attributes`|❌|✅|
|`events`|✅|❌ see: `default_events`|
|`default_events`|❌ see: `events`|✅|
|`single_file_name`|✅|❌|
|`single_file_paths`|✅|❌|
|`redirect_url`|❌|✅|
|`default_permissions`|❌ passed in as [key-value pairs](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app-using-url-parameters#github-app-permissions)|✅|

**Comment by blakegearin** [comment]
I haven't tried myself, but it seems likely that  `request_oauth_on_install` and `setup_on_update` are also supported and undocumented manifest parameters.

**Comment by cmwilson21** [comment]
@blakegearin After talking with the team, we think you may be right. Would you mind opening up a new issue and include both of those in it? Then we can triage and track it ✨

**Comment by Tanhy2505** [comment]
Ziai
