### ISSUE TITLE
Unclear instruction (incorrectly set variables in the text -> nonsense)

### ISSUE THREAD

**Issue by jklanica** [github/docs#21686]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Connect with SSH](https://docs.github.com/en/authentication/connecting-to-github-with-ssh)

### What part(s) of the article would you like to see updated?

When switching routes through the navigation on the left it happends that sometimes in the step where opening a terminal is a subject the text `Open TerminalTerminalGit Bash.` is displayed instead of a proper terminal name.

For example when beeing on [Add a new SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) and then switching to [Generate new SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) in the `#generating-a-new-ssh-key` section in the first step is this written.

It happendes not only on that switch but also in other cases in the Connect with SSH route. It seems that it happends only in certain cases because when going from [About SSH](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh) to [Generate new SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) it doesn't happened.

**Comment by cmwilson21** [comment]
@jklanica Thanks for opening an issue and sorry for the delay! I've had trouble trying to replicate this. Could you take a screen shot of what you are seeing?
