### ISSUE TITLE
action autoscaling-with-self-hosted-runners add cirun

### ISSUE THREAD

**Issue by mytting** [github/docs#21697]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners

### What part(s) of the article would you like to see updated?

action autoscaling-with-self-hosted-runners add [cirun](https://cirun.io/)

**Comment by cmwilson21** [comment]
@mytting Thanks for opening an issue! Could you give us a bit more information? Are you requesting we add a link to cirun to the article?

**Comment by mytting** [comment]
> Could you give us a bit more information?

Could you give us a bit more information?
There are some problems with the scheme in the existing documentation
`actions-runner-controller/actions-runner-controller`:
- AWS EKS Fargate does not support ARM64 architecture, you need to prepare nodes in advance, there is no way to spot
- AWS EKS Fargate does not support `generic-ephemeral-volumes`: no way to use
- There are certain construction and maintenance costs

`philips-labs/terraform-aws-github-runner`
Construction and maintenance costs are too high, and terrafrom is very unfriendly to many novices

Cirun is simple to use and configure, the platform does not require maintenance, there is no maintenance cost, and there is no cost for additional resources
Support AWS, GCP, Azure, OpenStack and other cloud platforms

`Are you requesting we add a link to cirun to the article?`
yes

**Comment by tarek295197** [comment]
Please stop action please I need original to my account and my cloud and my token بتاريخ ٠١‏/١١‏/٢٠٢٢ ٥:٣٠ ص، كتب jianchang ***@***.***>:

Could you give us a bit more information?

Could you give us a bit more information?
There are some problems with the scheme in the existing documentation
actions-runner-controller/actions-runner-controller:
AWS EKS Fargate does not support ARM64 architecture, you need to prepare nodes in advance, there is no way to spotAWS EKS Fargate does not support generic-ephemeral-volumes: no way to useThere are certain construction and maintenance costs
philips-labs/terraform-aws-github-runner
Construction and maintenance costs are too high, and terrafrom is very unfriendly to many novices
Cirun is simple to use and configure, the platform does not require maintenance, there is no maintenance cost, and there is no cost for additional resources
Support AWS, GCP, Azure, OpenStack and other cloud platforms
Are you requesting we add a link to cirun to the article?
yes

**Comment by mytting** [comment]
> 

？

**Comment by mytting** [comment]
> Please stop action please I need original to my account and my cloud and my token بتاريخ ٠١‏/١١‏/٢٠٢٢ ٥:٣٠ ص، كتب jianchang ***@***.***>: Could you give us a bit more information? Could you give us a bit more information? There are some problems with the scheme in the existing documentation actions-runner-controller/actions-runner-controller: AWS EKS Fargate does not support ARM64 architecture, you need to prepare nodes in advance, there is no way to spotAWS EKS Fargate does not support generic-ephemeral-volumes: no way to useThere are certain construction and maintenance costs philips-labs/terraform-aws-github-runner Construction and maintenance costs are too high, and terrafrom is very unfriendly to many novices Cirun is simple to use and configure, the platform does not require maintenance, there is no maintenance cost, and there is no cost for additional resources Support AWS, GCP, Azure, OpenStack and other cloud platforms Are you requesting we add a link to cirun to the article? yes —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

？？？

**Comment by cmwilson21** [comment]
@mytting Thank you for providing this additional detail! 💖 

I'll get this triaged for the team to take a look 👀

**Comment by cmwilson21** [comment]
@mytting Sorry for the delay, but I've checked in with the team, and we are not going to add cirun to the docs. 💛 

Thank you for your passion and interest in improving GitHub Docs! ✨
