### ISSUE TITLE
Document the minimum Neovim version for Copilot.

### ISSUE THREAD

**Issue by Kixunil** [github/docs#21725]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-neovim

### What part(s) of the article would you like to see updated?

Knowing the minimum version of Neovim can avoid wasted time on surprising "Vim version too old" message. Just add simple version number to Prerequisites section so that people can see it immediately instead of digging into the code.

**Comment by cmwilson21** [comment]
@Kixunil Thank you for opening an issue and linking it to your PR! ✨
