### ISSUE TITLE
add documentation to get github copilot sign out from multiple devices on VS code.

### ISSUE THREAD

**Issue by amirahad** [github/docs#21721]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

GitHub copilot

### What changes are you suggesting?

i want to to see a section on "how to sign out from GitHub copilot on vs code?" 

### Additional information

i have GitHub copilot signed in multiple devices. but now the devices don't belong to me and i don't have that device. so i want to sign out from all of the devices.

**Comment by cmwilson21** [comment]
@amirahad Thanks for opening an issue! I'll get this triaged for the team to take a look 👀 

In the meantime, try reaching out to our wonderful [support team](https://support.github.com/request) for guidance. 💛

**Comment by hubwriter** [comment]
@amirahad - Thanks for raising this issue.

We'll look at adding documentation. In the meantime, you can revoke the OAuth access for the GitHub Copilot Plugin, as follows:

1. Go to ([github.com/settings](http://github.com/settings).
2. Under Integrations in the left panel, click **Applications**.
3. Click the **Authorized GitHub Apps** tab. 
4. Click **Revoke** for the GitHub Copilot Plugin.

You can reauthorize this app later on a new device if you choose.

**Comment by hubwriter** [comment]
I've opened a GitHub-internal issue for this, to work on documentation of this, so I'm going to close this issue here.
