### ISSUE TITLE
Highlight that the SQL example just created is also applicable to Azure SQL

### ISSUE THREAD

**Issue by yorek** [github/docs#21732]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces

### What part(s) of the article would you like to see updated?

Highlight that the SQL example just created is also applicable to Azure SQL

**Comment by cmwilson21** [comment]
@yorek Thank you for opening an issue and linking it to your PR! ✨
