### ISSUE TITLE
Adding '+'  for creating unordered lists

### ISSUE THREAD

**Issue by ramvikrams** [github/docs#21736]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

### What part(s) of the article would you like to see updated?

the lists part where creation of unordered list is explained with `-` `*` but not with `+` . So it should be added with it's examples

**Comment by cmwilson21** [comment]
@ramvikrams Thanks for opening an issue! ⚡ 

You, or anyone else, are welcome to open a PR making that change ✨

**Comment by ramvikrams** [comment]
> @ramvikrams Thanks for opening an issue! ⚡
> 
> You, or anyone else, are welcome to open a PR making that change and add `+` to the first sentence under the [List](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#lists) paragraph. ✨

thanks i'll do it

**Comment by ramvikrams** [comment]
> I read the document posted in this issue, and it seems fitting that we organize with a "+" symbol. It is more efficient.

yeah
