### ISSUE TITLE
Add "addresses" as keyword to link pull request to issue

### ISSUE THREAD

**Issue by gkulin** [github/docs#21752]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### What changes are you suggesting?

**Suggestion**: Add "addresses" as a keyword to link a pull request to an issue

**Why**: It's a semi-common alternative to existing keywords (see #20362, #13682, #7683 for examples in this repo alone). People who might not know that they can use keywords to link issues might use "addresses" because it is more natural to them than the other keywords, so making it a keyword will provide a better experience to folks who were previously unaware of the feature

**Expected Outcome**: Link more issues than the current keywords

**Comment by cmwilson21** [comment]
@gkulin Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @gkulin, "addresses" isn't currently a keyword that links a pull request to an issue, so this is more of a feature request than a documentation update. The best place to send your feedback is https://github.com/orgs/community/discussions.  💛
