### ISSUE TITLE
MacOS instructions on Linux instructions for SSH authentication

### ISSUE THREAD

**Issue by RaphGL** [github/docs#21770]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

### What part(s) of the article would you like to see updated?

The *Adding your SSH key to the ssh-agent* section on Linux is mostly about MacOS and does not apply to Linux. 
Most of the section should probably be deleted and just leave the part about adding key to ssh-agent.

### Additional information

![image](https://user-images.githubusercontent.com/28673457/199825682-809f176f-f5a4-4fa6-9698-fb7b26457215.png)

**Comment by cmwilson21** [comment]
@RaphGL Thanks for opening an issue! ✨ 

I tried to reproduce this in the article, but when I clicked the Linux tab at the top of the page, the "[Adding your SSH key to the ssh agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux#adding-your-ssh-key-to-the-ssh-agent)" removed the macOS directions. I'm including a screenshot as well. 

<img width="714" alt="Screen Shot 2022-11-04 at 9 21 29 AM" src="https://user-images.githubusercontent.com/77312589/199998833-986c7f27-9699-4199-8cf2-8749736d21a8.png">

I hope this information is helpful. I'm going to go ahead and close this issue, but if you are still experiencing problems, please feel free to leave a comment and we will reopen it. 💛
