### ISSUE TITLE
"Viewing large files in pull requests" section is not correct

### ISSUE THREAD

**Issue by AlekSi** [github/docs#21798]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/working-with-files/managing-large-files/collaboration-with-git-large-file-storage#viewing-large-files-in-pull-requests

### What part(s) of the article would you like to see updated?

> GitHub does not render Git LFS objects in pull requests.

But it does render them (images, at least) just fine. For example, consider this PR: https://github.com/FerretDB/FerretDB/pull/1368/files You can see that it uses LFS: https://patch-diff.githubusercontent.com/raw/FerretDB/FerretDB/pull/1368.patch

**Comment by cmwilson21** [comment]
@AlekSi Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @AlekSi, I chatted with the team about this, and it sounds like Git LFS objects are _sometimes_ rendered and sometimes not. Rather than trying to explain the complicated criteria, let's just update that note to say this:

>GitHub does not render some Git LFS objects in pull requests.

You or anyone else is welcome to open a PR doing so!

**Comment by MahendraBishnoi29** [comment]
hey @lecoursen i would love to work on this 😀

**Comment by cmwilson21** [comment]
@MahendraBishnoi29 - You or anyone else is welcome to work on this 🎉

**Comment by knlkshyp** [comment]
Hello, created PR for the fix https://github.com/github/docs/pull/22740
Thank you
