### ISSUE TITLE
Raw markdown on Getting started with apps

### ISSUE THREAD

**Issue by jsoref** [github/docs#21803]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/getting-started-with-apps

### What part(s) of the article would you like to see updated?

<img width="727" alt="image" src="https://user-images.githubusercontent.com/2119212/199992575-a7bfc550-da84-44e9-9fd4-953c3f9a9617.png">

### Additional information

The content looks fine here:
https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps
<img width="718" alt="image" src="https://user-images.githubusercontent.com/2119212/199993183-825b5ef8-4304-477d-b4d9-c8102752c2fa.png">

I believe the code comes from here:
https://github.com/github/docs/blob/3bb798d625da8400c4c2a4a432be3bf8ce706bf9/content/developers/apps/getting-started-with-apps/about-apps.md

**Comment by cmwilson21** [comment]
👋 @jsoref Thanks for opening an issue! We appreciate the screenshots, too. I'll get this triaged for someone to take a look at this broken md. ✨

**Comment by lecoursen** [comment]
Thanks @jsoref for pointing this out! Our engineering team is now tracking this internally. 😊
