### ISSUE TITLE
Update instructions in [Configuring a subdomain] help article

### ISSUE THREAD

**Issue by peterjuma** [github/docs#2184]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

### What part(s) of the article would you like to see updated?

Current:

> To set up a `www` or custom subdomain, such as `www.example.com` or `blog.example.com`, you must create a _CNAME_ file in your site's repository and configure a `CNAME` record with your DNS provider.

It should probably be changed to something like:

> To set up a `www` or custom subdomain, such as `www.example.com` or `blog.example.com`, you must add your domain in the repository settings, which will create a _CNAME_ file in your site’s repository. After that, configure a `CNAME` record with your DNS provider.

### Additional information

Users should NOT create the CNAME file themselves, this is done automatically once they update their custom domain settings with the domain name and hence the need for this change.

If we can get the wording that would explicitly convey to users that they should NOT create the CNAME file, that will be even better

 CC for visibility
@github/support-technical
@github/business-support-all

**Comment by janiceilene** [comment]
@peterjuma Thanks for opening an issue! I'll get this triaged for the right team to take a look 👀

**Comment by Yuliadocs** [comment]
Hi, can I take this issue?

**Comment by katanakrypto** [comment]
Yes you can try to untangle the thraed

Yuliadocs <notifications@github.com> schrieb am Sa., 9. Jan. 2021, 21:45:

**Comment by janiceilene** [comment]
You're welcome to open a PR @Yuliadocs 💖

**Comment by felicitymay** [comment]
Hi @Yuliadocs - I'm just checking through issues and found the timeline on this one really confusing. None of the various pull requests listed in the issue history above are relevant. 

This issue is still available to work on.
