### ISSUE TITLE
Secrets for reusable workflows

### ISSUE THREAD

**Issue by pereriksson** [github/docs#21850]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/encrypted-secrets?tool=webui#using-encrypted-secrets-in-a-workflow

### What part(s) of the article would you like to see updated?

This article mentions using encrypted secrets in GitHub Actions. However, secrets are not automatically passed to reusable workflows. There is a separate article for reusable workflows describing this. My proposal is that a note on using secrets in reusable workflows, and a link to the separate article is mentioned in the article above as well.

**Comment by cmwilson21** [comment]
@pereriksson Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @pereriksson, I agree that would be helpful to add. You or anyone else is welcome to create a PR doing so!

**Comment by pereriksson** [comment]
Still no luck with getting a preview environment for this issue. Let's hope Github staff can fix at some point.
