### ISSUE TITLE
Recommend default global gitignore file

### ISSUE THREAD

**Issue by adamchainz** [github/docs#21863]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

### What part(s) of the article would you like to see updated?

The article recommends setting `core.excludesfile` and adding an ignore file to the user’s home directory.

This is unnecessary since [this change](https://github.com/git/git/commit/dc79687e0b70805894d1b4432cef7164ae86e033) in Git 1.7.12 (August 2012), which made Git default to reading the file `$HOME/.config/git/ignore`. Using this file is preferable as it avoids configuraiton and it’s the standard location for config, reducing bloat in the home directory.

**Comment by cmwilson21** [comment]
@adamchainz Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@adamchainz Thanks for opening this issue! I checked with the team, and this would be a great update for the docs. ✨ 

You or anyone else are welcome to submit a PR with this update 🔧

**Comment by adamchainz** [comment]
I’m too busy writing my own blog, [relevant post](https://adamj.eu/tech/2022/11/06/git-set-up-a-global-ignore-file/).

**Comment by 7ze** [comment]
Can I take this up?

**Comment by cmwilson21** [comment]
@7ze You or anyone else is welcome to submit a PR with this fix. 💖

**Comment by cmwilson21** [comment]
This issue is reserved for the MLH Fellowship program.

**Comment by Kajaman** [comment]
Xxxx

**Comment by Kajaman** [comment]
Xxx

**Comment by Kajaman** [comment]
Xxx

**Comment by Kajaman** [comment]
Xxx

**Comment by adamchainz** [comment]
not stale

**Comment by codewithdev** [comment]
> Little query here. The default value of `core.excludefiles` is `$XDG_CONFIG_HOME/git/ignore` and if this file is empty of not set, then it uses `$HOME/.config/git/ignore` automatically. 

However, in the article, it has been specified that the ignore files can be configured in Git globally. 

Do we need to remove the configuration part as the default value is already set to `$HOME/.config/git/ignore`.?
