### ISSUE TITLE
Audit Log event docs lack event schema information

### ISSUE THREAD

**Issue by mattsb42-aws** [github/docs#21893]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise

### What part(s) of the article would you like to see updated?

We would like to know what schemas to expect for each audit log event type. Similar to how the webhook events docs include schema information[1], having this information for audit log events would be very useful for understanding and processing these events.

[1] https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

**Comment by cmwilson21** [comment]
@mattsb42-aws Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @mattsb42-aws, I agree this would be useful and we actually have an issue open to track this internally, so I'm going to close this in favor of that issue. 💖
