### ISSUE TITLE
Screenshot out of date

### ISSUE THREAD

**Issue by matthewkennedy5** [github/docs#21897]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#renaming-a-branch

### What part(s) of the article would you like to see updated?

The screenshots and description of the "Branches" button is out of date with the current UI. Now the "Branches" button is inside the dropdown when you click on a branch.

**Comment by matthewkennedy5** [comment]
Yeah looks fine now, not sure what I was seeing before, my bad

**Comment by cmwilson21** [comment]
@matthewkennedy5 No worries! Thanks for your interest in helping us improve the docs!  👍
