### ISSUE TITLE
Fix typo in Configuring CodeQL CLI in your CI system

### ISSUE THREAD

**Issue by cyanboy** [github/docs#21919]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Configuring CodeQL CLI in your CI system](https://docs.github.com/en/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/configuring-codeql-cli-in-your-ci-system)

### What part(s) of the article would you like to see updated?

Typo in 4th step of [Creating codeql databases-to-analyze](https://docs.github.com/en/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/configuring-codeql-cli-in-your-ci-system#creating-codeql-databases-to-analyze).

Change databsae to database

**Comment by cmwilson21** [comment]
@cyanboy Thank you for opening an issue and linking it to your PR! ✨
