### ISSUE TITLE
Regression: The menu nor breadcrumb works on a mobile phone view 

### ISSUE THREAD

**Issue by atreeon** [github/docs#21917]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

all

### What changes are you suggesting?

show the breadcrumb and the menu when viewing the docs on a mobile phone

### Additional information

#21210 shows as closed and done but the problem has either reappeared or was not fixed.

> Additional information
> 
> If I'm viewing the github docs on a mobile phone I do not see the sub menu items.
> 
> For example in desktop version I have the menu on the left with the sub entries and sub sub entries
> 
> Using workflows
>  |-Using jobs
>     |-Use jobs in a workflow 
> 
> but if I'm on mobile and I press the 'burger' button at the top right, all I see is the higher level menu items.
> 
> 
> 
> Also on desktop we are provided a breadcrumb navigation (although looking again that doesn't seem to display properly on desktop because it shows
> GitHub Actions / Use jobs in a workflow
> it should show
> GitHub Actions / Using jobs / Use jobs in a workflow
> 
> This has the effect of not being able to navigate or even use the docs on a mobile phone.
> 
> (hope I'm not missing something simple!)

**Comment by cmwilson21** [comment]
@atreeon Thanks for checking in on this one. 👋 

I understand it’s frustrating not being able to see or track any updates. The work to remedy this is part of a bigger internal issue addressing other UX concerns. I’ve reported your feedback to the team. Since this is part of a bigger internal issue, there’s not a way to track this progress specifically in the OS repo.

Because of the internal components for this fix, I’m going to go ahead and close this issue. We appreciate your interest and passion in improving the Docs :yellow_heart:

**Comment by hoanglamcoin** [comment]
> @atreeon Thanks for checking in on this one. 👋 
> 
> 
> 
> I understand it’s frustrating not being able to see or track any updates. The work to remedy this is part of a bigger internal issue addressing other UX concerns. I’ve reported your feedback to the team. Since this is part of a bigger internal issue, there’s not a way to track this progress specifically in the OS repo.
> 
> 
> 
> Because of the internal components for this fix, I’m going to go ahead and close this issue. We appreciate your interest and passion in improving the Docs :yellow_heart:
![image](https://user-images.githubusercontent.com/114911937/200950302-8f4a1ba2-9162-43dd-ac93-67b25cdc98f6.png) I don't speak English so I don't know what people said my wallet before the conversion but now it's gone and when I go to any website the wallet link goes up and it says 1 sign in and it pops out.![image](https://user-images.githubusercontent.com/114911937/200950871-23fef6b2-1b40-4f60-b9f4-eac8bdf74852.png)
