### ISSUE TITLE
Navigating Code on GitHub: Rust language is not listed in supported tree-sitter languages table

### ISSUE THREAD

**Issue by neoncitylights** [github/docs#21944]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

"Navigating Code on GitHub" - https://docs.github.com/en/repositories/working-with-files/using-files/navigating-code-on-github

### What part(s) of the article would you like to see updated?

The Rust language is not in the table of supported languages via `tree-sitter`, which was recently announced in the latest GitHub Blog announcement: https://github.blog/changelog/2022-11-09-search-based-code-navigation-for-rust-projects/

![image](https://user-images.githubusercontent.com/4723983/201195334-69de3a87-a774-492b-b874-4606c32dc65f.png)

### Additional information

I'd be happy to fix this! <3

**Comment by banksaudi** [comment]
https://github.com/github/docs/issues/21944#issuecomment-1310836770

**Comment by cmwilson21** [comment]
@neoncitylights Thank you for opening an issue and linking it to your PR! ✨

**Comment by sabrowning1** [comment]
Closing as noted in https://github.com/github/docs/pull/21951#issuecomment-1314407209 🙂 thanks!
