### ISSUE TITLE
Missing period in GitHub Sponsors Additional Terms, section 7.2.

### ISSUE THREAD

**Issue by tecc** [github/docs#21961]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

"GitHub Sponsors Additional Terms".

### What part(s) of the article would you like to see updated?

Section 7.2. is (presumably) missing a period between the first sentence and what can be assumed to be the second sentence.

See following: `We reserve the right, at our sole discretion, to amend these Additional Terms at any time We will notify you of material changes to these Additional Terms...`.
It's missing a period (or some other separator) between the end of the first sentence and the start of the second.
It should be something like: `We reserve the right, at our sole discretion, to amend these Additional Terms at any time. We will notify you of material changes to these Additional Terms...`

**Comment by cmwilson21** [comment]
@tecc Thank you for opening an issue and linking it to your PR! ✨
