### ISSUE TITLE
macos-latest is macos-12, but `macOS Big Sur 11` is explained.

### ISSUE THREAD

**Issue by Hiroshiba** [github/docs#21990]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

> Supported runners and hardware resources

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

### What part(s) of the article would you like to see updated?

`macos-11` is explained as `macos-latest`.
It should be `macos-12` now.

### Additional information

I tried to send a pull request, but it was difficult to trace the relevant section to `{% data reusables.actions.supported-github-runners %}`, so I created an issue.

https://github.com/github/docs/issues/21990#tasklist-block-eb09ad52-3bdf-45e7-9010-504546e5d961

**Comment by cmwilson21** [comment]
@Hiroshiba Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
