### ISSUE TITLE
Fixed sentence error at Codespaces overview.md documentation

### ISSUE THREAD

**Issue by inth3wild** [github/docs#21991]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Github Codespaces overview.md documentation: [**Using organization-owned codespaces**](https://github.com/github/docs/blob/main/content/codespaces/overview.md#using-organization-owned-codespaces) section. 

### What part(s) of the article would you like to see updated?

* In the second paragraph of the "using organization owned codespaces" section, the sentence in the current documentation goes like this: `Codespaces that are billed to an organization, or its parent enterprise, are owned by the organization and can be deleted an organization owner`.

* It's missing the word **by** to make it a valid sentence. So I added that.

* My fix: `Codespaces that are billed to an organization, or its parent enterprise, are owned by the organization and can be deleted **by** an organization owner`

**Comment by cmwilson21** [comment]
@inth3wild Thank you for opening an issue and linking it to your PR! ✨

**Comment by ck815** [comment]
Thanks

**Comment by ck815** [comment]
Thanks
