### ISSUE TITLE
automated "Thanks very much for contributing!" comment is confusing @all-contributors bot

### ISSUE THREAD

**Issue by zeke** [github/docs#220]
The bots are confusing one another!  🤖 ⚡  🤖 

<img width="970" alt="Screen Shot 2020-10-07 at 5 07 19 PM" src="https://user-images.githubusercontent.com/2289/95400516-9fefca00-08bf-11eb-87b2-8fb6d02ddcbc.png">

cc @github/docs-engineering

**Comment by jeffmcaffer** [comment]
see also #218
