### ISSUE TITLE
Unneeded white space on `git remote rm` example output

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [github/docs#22004]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Managing remote repositories](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories)

### What part(s) of the article would you like to see updated?

[Removing a remote repository](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#removing-a-remote-repository)
- Theres an unneeded whitespace  on the [example](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#example-1) of the expected `git remote rm` output.

**Comment by cmwilson21** [comment]
@PeGaSuS-Coder Thank you for opening an issue and linking it to your PR! ✨
