### ISSUE TITLE
Searching for `security-events` does not work well

### ISSUE THREAD

**Issue by jsoref** [github/docs#22013]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens#security-events

### What part(s) of the article would you like to see updated?

I should be able to search docs.github.com for `security-events` and find pages that have the content `security-events`.

### Additional information

`security-events` is the value one enters into the `permissions` yaml tree to enable sarif reporting.

A justifiably concerned repository owner should be able to easily look for this permission and determine what it does.

At present, they can't because `security-events` doesn't appear in the text.

**Comment by jsoref** [comment]
Fwiw, searching for `open-pull-requests-limit` is worse.

> Search results for: "open-pull-requests-limit"
No results found.

> Search results for: open-pull-requests-limit
Results found: 983. Matches displayed: 10

> Search results for: open-pull-requests-limit dependabot
Results found: 996. Matches displayed: 10

> Search results for: open-pull-requests-limit dependabot limit
Results found: 996. Matches displayed: 10

This is the first one that has useful hits in the top 10.

**Comment by cmwilson21** [comment]
👋 @jsoref Thanks for opening an issue. We are tracking this internally, so I'm going to go ahead and close this issue 💛 

I have, however, shared your feedback directly with the team. Thanks! ✨

**Comment by peterbe** [comment]
Note-to-selfs; the internal Discussion https://github.com/github/docs-engineering/discussions/2458 takes over where this wonderful feedback started. 
Thank you so much @jsoref for starting this! Much appreciated!
