### ISSUE TITLE
Typo in `Developing in a codespace / Source control`

### ISSUE THREAD

**Issue by spenserblack** [github/docs#22016]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-codespaces/using-source-control-in-your-codespace#setting-your-codespace-to-automatically-fetch-new-changes

### What part(s) of the article would you like to see updated?

A step says to "slick settings", though it should probably say to "click settings"

### Additional information

I must admit that the VSCode's settings are pretty slick, though :laughing:

Edit: bisected to 543dc39bed97f70dde1d4f8bde73a40221916e33

**Comment by cmwilson21** [comment]
@spenserblack Thank you for opening an issue and linking it to your PR! ✨ 

The are pretty slick, but we would rather you click it 😆
