### ISSUE TITLE
Clarify assigning-permissions-to-jobs documentation

### ISSUE THREAD

**Issue by Youssef1313** [github/docs#22028]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

### What part(s) of the article would you like to see updated?

Add description to what every permission can do. For example, `contents`, what contents can be written exactly when it's write? id-token? etc for all permissions.

https://github.com/github/docs/issues/22028#tasklist-block-13b42f95-f9da-45cc-ba9e-e8f46cc9215c

**Comment by cmwilson21** [comment]
@Youssef1313 Thanks so much for opening an issue! We agree that this would be helpful information. We are actually already working on this internally. 

I'm going to go ahead and close this issue as we continue our internal work to update descriptions. 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
