### ISSUE TITLE
Provide clear, self-contained, motivated instructions for transitioning away from passwords

### ISSUE THREAD

**Issue by AllenDowney** [github/docs#2205]
Starting today, users will receive an email telling them to stop using passwords.

This will not be welcome news, because they are trying to get work done, and you are making them do something else instead.

So they are already in a bad mood.  However, let's assume they follow the link in the email to this page:

https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

The tone of this page is like a technical specification.  Instead, it should be an explanation of why you are asking the user to do something, and, in a prominent, central location, instructions for what you want them to do.

This page should contain fewer links to other pages.  The user who lands here does not want to navigate a tree of documents.

Suppose someone is still using a password.  What option do you think they are most likely to migrate to?  Instructions for that option should be on this page.

It looks like using a PAT is the most likely option.  So let's say the user clicks on that link:

https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/set-up-git#next-steps-authenticating-with-github-from-git

The destination of this link is not, as the user expected, an explanation of PAT.  Instead, it goes to the middle of a page about setting up git.  At this point, you have annoyed and lost the user.

However, suppose they persevere and click on this link:

https://docs.github.com/en/free-pro-team@latest/github/using-git/caching-your-github-credentials-in-git

Well, that's no help, but all the way at the bottom, there's "Further Reading" on creating a PAT.  At this point, your user is livid, but suppose they press on and read:

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

Ok, now the user knows how to create a PAT.  These instructions look pretty good.  I haven't tried them yet, but let's assume they work, and I generate a PAT and copy it.

Now what?  Where am I supposed to put it?  How do I synchronize it across machines?  Am I going to have to copy and paste this every time my cached credentials expire?  Where should I copy it from?

And why is this better than a good quality password?  I understand that it's better than bad, reused passwords, but if the user already has a good password -- which they remember -- it seems like using a PAT is worse in every way, and no more secure.

And remember that for your users this entire adventure is pure overhead -- it is not helping me get work done.  It is preventing me from getting work done.  

So please make it much easier, and maybe explain more clearly why it is worth the effect.

Thank you!

**Comment by janiceilene** [comment]
@AllenDowney Thanks for opening an issue! In this repo, we only maintain docs.github.com. We don't publish, write, or maintain the GitHub blog. I've passed along your feedback about the blog post. Most people are unavailable for the holidays, so it may be a while until someone looks at it 💛 

If you try out the [Creating a personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) article and notice anything that could use an update, feel free to open a new issue ✨

**Comment by hamelsmu** [comment]
Are there perhaps part of this that can be improved in the docs?  I'm thinking about this part of the comment above:

> https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token  Ok, now the user knows how to create a PAT. These instructions look pretty good. I haven't tried them yet, but let's assume they work, and I generate a PAT and copy it.

This feedback specifically: 

> Now what? Where am I supposed to put it? How do I synchronize it across machines? Am I going to have to copy and paste this every time my cached credentials expire? Where should I copy it from?

The question "Where am I supposed to put it" seems like it might be a good opportunity for inclusion in the docs.  What do you think?  I think changing the blog to at least have the correct link would go a long way, I'll see if I can open a PR for that (it is a private repo).

**Comment by hamelsmu** [comment]
I'm tagging the author of the blog post @fletchto99 for visibility. 

@fletchto99 - There might be a link that is incorrect in the blog post, it appears that 

> https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/set-up-git#next-steps-authenticating-with-github-from-git

Maybe should be replaced with 

> https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

In the section talking about PATs?   I don't know if there are other ideas you might have to mitigate the confusion the reader is having (read above), but just tagging you incase it is helpful

**Comment by AllenDowney** [comment]
Hi @janiceilene. It looks like you closed this issue because you concluded that I was asking about the blog, not the docs.

I would like to suggest that we reopen it because I think it is a problem with the docs, not the blog. And I think all of the problems I identified are still problems.

Again, here's an outline of my user experience:

I receive an email Deprecation notice telling me I need to stop using a password to access my repos and it contains a link to suggested workaround. The choice of "workaround" might not be ideal, because it suggests that we are mitigating the damage of a bad thing, not making things better. So as a user, my first question is, "Is this better? Why?"

The email contains a link to a blog article which, I have now learned, is not the responsibility of the people who maintain this repository. But I don't have access to the people who are responsible. So I appreciate that you forwarded my issue to them (six months ago), but it seems to have had no effect. It is still very difficult to figure out what I should do and how.

Of the many links in the blog post, the one that seems most relevant is this one: 

https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

Based on the URL, I assume that this page is part of the GitHub docs and so this is the right place to raise an issue. If so, my issue is the same as last time. It is not clear how to do what I want, which is to get back, as quickly as possible, to a productive work flow.

On this page, steps 1 through 5 are fine, but step 6 asks me to "Give my token a descriptive name", and the example is "My bash script". I don't understand. At this point, my mental model is that a personal token is a replacement for a password, and all I want to do is generate one and get back to work. What description should I give my token? And what would it mean for that description to be "My bash script"?

Step 7 is complicated. There are a lot of options. I don't know what most of them are. Again, I came to this page with one goal in mind: I want to generate a PAT and get back to work. So maybe this step should provide a common-case suggestion like, "If you just want something that behaves like a password, check all the boxes".

Step 9 is terrifying. So, I need to copy something into my clipboard and then save it somewhere. And if I lose it, what happens? It sounds like I would lose access to something. But I'm not sure what. One of my repos, all of my repos, my GitHub account? Now I am scared. If I copy this thing, close the page, and accidentally copy something else, I'm in big trouble? This is terrible.

Also, where am I supposed to put it? It seems like I'd better start putting copies of this thing all over the place, to make sure I can always access it when I need it, and I never lose it. But in terms of security, that seems like a terrible idea. Is this really making things more secure? I seems worse.

The next section is fine. I sounds like I can just use a PAT instead of a password. But do I have to, or will my password continue to work until the deadline? Or, once I generate a PAT, does my password become invalid immediately?

It sounds like I can cache my PAT, so that's good. That's what I do with my password, so I only type it about once a day. But if I do the same thing with my PAT, I will have to copy it from somewhere each time, which is a nuisance. I would love to know where people store these PATs.

Wait, it says I can store it in a plain text file that Git can read. Ok, that sounds like a terrible idea for security, but at least it sounds convenient. Great -- how do I do that? It says I should follow this link:

https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git

So I go to that page. But that page doesn't say a thing about storing PATs in a text file, or anywhere else. Why was I sent here? How do I put a PAT in a text file? I can't find an answer to this in the docs.

Well, there's one more link on this page, so let's try that:

https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-authentication-to-github

I don't know what to say about this page, but it did not help.

So, I am right back where I was in December. I am pretty happy using a password, and I think it provides an acceptable level of security. If I have to use a PAT instead, I will. But I really, really need some documentation that tells me how to do that in a way that is reasonably convenient and ideally at least as secure as using a password, if not better.

Help!

**Comment by chrisma** [comment]
Is there a specific reason why PATs are recommended as the best replacement for passwords going forward, instead of SSH access? PATs support scopes, but when using them for CLI access, all scopes should be activated, right?

**Comment by cooperrc** [comment]
I have be n using a PAT for the last ~3 months. 

I do not see any advantage over a good password manager (which is where I have to store the PAT anyway). 

It works via CLI, but my logins now default to 2FA and the PAT is ineffective for web access. 
> This will not be welcome news, because they are trying to get work done, and you are making them do something else instead.

I agree, this is a rabbit hole that I went down because of a warning. I was able to click through some resources and get to a workable solution, but it didn't feel straightforward and I feel like my account security is now out of my control.

**Comment by ramyaparimi** [comment]
@AllenDowney this is great feedback to give to https://support.github.com/contact/feedback :yellow_heart:

**Comment by AllenDowney** [comment]
@ramyaparimi Ok, I did that. Thanks.

**Comment by AllenDowney** [comment]
@ramyaparimi Should I expect to get a response?

**Comment by ramyaparimi** [comment]
@AllenDowney I believe that you should get an automated confirmation that your message was received 👍 As far as an official response from our product or engineering teams, I can’t promise when or if you’ll get a response to any feedback you supply to the teams 💛

**Comment by AllenDowney** [comment]
OK. Since the deadline is approaching, I decided to use SSH, and that has been working fine. This is contrary to the advice in the documentation, but since no rationale is provided, I guess I'll proceed. For anyone else reading this thread, I found these instructions helpful:

https://pandammonium.org/how-to-change-a-git-repository-from-https-to-ssh/
