### ISSUE TITLE
Point to the newer Clojure GitHub API client.

### ISSUE THREAD

**Issue by vollcheck** [github/docs#22082]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/libraries

### What part(s) of the article would you like to see updated?

I'd like to update the pointer for Clojure community client for interfacing GitHub API.

### Additional information

[Raynes/tentacles](https://github.com/Raynes/tentacles) is presented as a Clojure client for GH API although it is known that there is a [successor](https://github.com/clj-commons/tentacles), as per it's [README](https://github.com/clj-commons/tentacles#readme):

> This library is the continuation of [Raynes/tentacles](https://github.com/Raynes/tentacles). Sadly Raynes passed away in 2016 so the irresponsible clojure organisation has taken over maintenance of this excellent library to keep it alive.

**Comment by cmwilson21** [comment]
@vollcheck Thank you for opening an issue and linking it to your PR! ✨
