### ISSUE TITLE
Missing note on registry_package event firing multiple times for the same package

### ISSUE THREAD

**Issue by makkes** [github/docs#22091]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#registry_package

### What part(s) of the article would you like to see updated?

The paragraph doesn't state that merely having a workflow trigger on `registry_package` of type `published` might cause a workflow to be triggered more than once. This is the case when e.g. a multi-arch container image is pushed. The event is then emitted once per manifest, i.e. 3 times for a tagged image that supports two architectures (once per architecture and once more for the manifest list).

**Comment by cmwilson21** [comment]
@makkes Thank you for opening an issue and linking it to your PR! ✨

**Comment by erdawati6274** [comment]
hiiii

**Comment by erdawati6274** [comment]
hii

**Comment by erdawati6274** [comment]
hii

**Comment by erdawati6274** [comment]
hu

**Comment by makkes** [comment]
A PR has been issued which merely needs to be merged. I asked for any guidance on how to get there eventually.

**Comment by Oda206** [comment]
> A PR has been issued which merely needs to be merged. I asked for any guidance on how to get there eventually.

Ok

**Comment by Oda206** [comment]
Thank u much
