### ISSUE TITLE
Add mention of composite actions under "Types of actions" in about-custom-actions.md

### ISSUE THREAD

**Issue by mhucka** [github/docs#22096]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/actions/creating-actions/about-custom-actions.md

### What part(s) of the article would you like to see updated?

Change the first sentence of the paragraph under the heading "Types of Actions" to mention composite actions.

### Additional information

The first sentence of the paragraph under the heading "Types of Actions" only mentioned Docker and JavaScript actions, but the table right below that paragraph contains 3 types of actions. The first sentence of the paragraph could be modified to mention composite actions to make it more complete.

**Comment by cmwilson21** [comment]
@mhucka Thanks for opening an issue and submitting a PR! ✨
