### ISSUE TITLE
ubuntu 22 now ubuntu-latest, docs still reference 20 as -latest

### ISSUE THREAD

**Issue by markgoho** [github/docs#22132]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners

### What changes are you suggesting?

update -latest to 22

**Comment by cmwilson21** [comment]
@markgoho Thank you for opening an issue and linking it to your PR! ✨

**Comment by Aizmansor** [comment]
Dihantar daripada telefon saya-------- Mesej asal --------Daripada: "welcome[bot]" ***@***.***>Tarikh: Jum, 18 Nov 2022, 11:09 PTGKepada: github/docs ***@***.***>Sk: Subscribed ***@***.***>Tajuk: Re: [github/docs] ubuntu 22 now ubuntu-latest, docs still reference 20 as -latest (Issue #22132)
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the contributing guidelines.

**Comment by lucascosti** [comment]
Thanks for opening this issue, @markgoho!

The `ubuntu-latest` label is currently transitioning from 20.04 to 22.04, so people might see one or the other when using the `latest` label until the transition is complete (see this blog post for more information: https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

We've recently updated that page in https://github.com/github/docs/commit/cb39c15ab6ccfacf49f4b114b77e3b920fdddf70 to be more clear about this transition period.

Thanks again for the issue and the PR 🙇‍♂️
