### ISSUE TITLE
Broken row on table

### ISSUE THREAD

**Issue by mariofdezzz** [github/docs#22146]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#1-request-a-users-github-identity

### What changes are you suggesting?

Fix last table row by including spaces

**Comment by cmwilson21** [comment]
Closing per comment [here](https://github.com/github/docs/pull/22163#issuecomment-1322859537) 💖
