### ISSUE TITLE
Feathers Icons Incomplete/Out of date

### ISSUE THREAD

**Issue by AlexAtkinson** [github/docs#22150]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#brandingicon

### What part(s) of the article would you like to see updated?

The article outlines feathers icons v4.28.0, but this is incorrect, as the 'tool' icon for one is not available. This icon was released with [4.23.0](https://github.com/feathericons/feather/commit/5047ddb).

Perhaps someone just has to run an update job somewhere...

### Additional information

This the warning when attempting to create an action with the tool icon defined.

![Screenshot_20221118_141107](https://user-images.githubusercontent.com/2965366/202784069-325e81fd-d4e4-40d1-851e-3c1e240510a4.png)

```yml
branding:
  icon: tool
  color: white
```

**Comment by lucascosti** [comment]
👋 @AlexAtkinson Thanks for opening this issue!

The doc you linked (https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#brandingicon) states that although Actions uses Feather icons v4.28.0, some icons are specifically omitted, and `tool` is one of those omitted.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/4434330/203234344-be658218-806a-4c12-b88d-6780047a2b1e.png">
