### ISSUE TITLE
Documentation for "Restrict who can push to matching branches" erroneously suggests feature is not for free plan

### ISSUE THREAD

**Issue by Marcono1234** [github/docs#22181]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#restrict-who-can-push-to-matching-branches

### What part(s) of the article would you like to see updated?

Both pages say the following regarding the "Restrict who can push to matching branches" setting:
> if your repository is owned by an organization using GitHub Team or GitHub Enterprise Cloud

This suggests the feature is not available for the "GitHub Free" plan. However, that does not seem to be true, this setting also seems to be available for organizations using GitHub Free (please check this yourself as well to be sure).

Though it looks like this setting is not available for personal (non-organization) projects, so maybe the documentation should only mention that and not refer to any pricing plan.

**Comment by chrissygem42** [comment]
Thank you!

________________________________________
From: Marcono1234 ***@***.***>
Sent: Sunday, November 20, 2022 5:40:22 PM
To: github/docs
Cc: Subscribed
Subject: [github/docs] Documentation for "Restrict who can push to matching branches" erroneously suggests feature is not for free plan (Issue #22181)

Code of Conduct

  *    I have read and agree to the GitHub Docs project's Code of Conduct<https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md>

What article on docs.github.com is affected?

  *   https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule
  *   https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#restrict-who-can-push-to-matching-branches

What part(s) of the article would you like to see updated?

Both pages say the following regarding the "Restrict who can push to matching branches" setting:

if your repository is owned by an organization using GitHub Team or GitHub Enterprise Cloud

This suggests the feature is not available for the "GitHub Free" plan. However, that does not seem to be true, this setting also seems to be available for organizations using GitHub Free (please check this yourself as well to be sure).

Though it looks like this setting is not available for personal (non-organization) projects, so maybe the documentation should only mention that and not refer to any pricing plan.

Additional information

No response

**Comment by cmwilson21** [comment]
@Marcono1234 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by janiceilene** [comment]
Thanks so much for catching this one @Marcono1234! You or anyone else is welcome to open a PR with the fix! Let's make the following changes:

- In [Managing a branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule), let's change step 15 to:
  > `Optionally, in public repositories owned by a {% data variables.product.prodname_free_user %} organization and in all repositories owned by an organization using {% data variables.product.prodname_team %} or {% data variables.product.prodname_ghe_cloud %}, enable branch restrictions.`

- In [About protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#restrict-who-can-push-to-matching-branches), let's change the line to: 
  > `You can enable branch restrictions in public repositories owned by a {% data variables.product.prodname_free_user %} organization and in all repositories owned by an organization using {% data variables.product.prodname_team %} or {% data variables.product.prodname_ghe_cloud %}.`

**Comment by dostonnabotov** [comment]
Hey, there! If it isn't resolved yet, I would be happy to pick this up and fix it

**Comment by cmwilson21** [comment]
@dostonnabotov Thanks for reaching out! You or anyone else is welcome to submit a PR with this fix 💛
