### ISSUE TITLE
Complete new use method for copilot

### ISSUE THREAD

**Issue by Freed-Wu** [github/docs#22201]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

<https://github.com/github/docs/blob/main/content/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-neovim.md>

Copilot can be used in (neo)vim by <https://github.com/yuki-yano/coc-copilot>

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-neovim

**Comment by Aizmansor** [comment]
Dihantar daripada telefon saya-------- Mesej asal --------Daripada: "welcome[bot]" ***@***.***>Tarikh: Isn, 21 Nov 2022, 9:41 PTGKepada: github/docs ***@***.***>Sk: Subscribed ***@***.***>Tajuk: Re: [github/docs] Complete new use method for copilot (Issue #22201)
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the contributing guidelines.

**Comment by cmwilson21** [comment]
@Freed-Wu Thanks for opening an issue! Would you mind explaining the changes you are requesting in a little more detail? 

Are you suggesting `yuki-yano/coc-copilot` as an alternative installation?

**Comment by Freed-Wu** [comment]
> Are you suggesting yuki-yano/coc-copilot as an alternative installation?

Right. :+1:

**Comment by cmwilson21** [comment]
@Freed-Wu Thanks for opening an issue! I spoke with the team, and we are not going to add this to the docs. 💛 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
