### ISSUE TITLE
Document resource limits (or absence of limits) e.g. Labels attached to an Issue

### ISSUE THREAD

**Issue by DazWilkin** [github/docs#22215]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/issues/labels

### What part(s) of the article would you like to see updated?

It would be helpful if resource limits were documented even if there is no limit.

I'm using the API to create Issues and -- absent user-definable issue metadata -- I'm planning to use Labels to represent a limited but unbounded set of values.

It would be helpful if the documentation described e.g. limits on the number of Labels that may be attached to an Issue and the number of Labels that may be created within a repo.

If there is no feasible limit, this is useful information too.

**Comment by cmwilson21** [comment]
@DazWilkin Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@DazWilkin Thanks again for opening an issue. I spoke with the team and we are not going to make this update at this time. 💛 

Thank you for your interest in and passion for improving GitHub Docs! :sparkling_heart:
