### ISSUE TITLE
The Authorizing OAuth Apps doesn't mention the access_token endpoint doesn't support CORS

### ISSUE THREAD

**Issue by baywet** [github/docs#22270]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github

### What part(s) of the article would you like to see updated?

There should be a mention that CORS pre-flights are not supported on this endpoint (OPTIONS requests). This, and the fact that implicit flow is not supported, effectively means that authenticating from a SPA is impossible without a service relay.
That's unless PKCE is supported, but there are no mentions of it. https://espressocoder.com/2019/10/28/secure-your-spa-with-authorization-code-flow-with-pkce/

**Comment by cmwilson21** [comment]
@baywet Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by baywet** [comment]
Thanks! For information after investigating the issue further I also established that PKCE isn't supported today. This should probably be detailed in the docs as well.
I've added a "feature request" [here](https://github.com/orgs/community/discussions/40077) which contains additional details.

**Comment by steveward** [comment]
Cross-referencing https://github.com/github/docs/pull/24965 which is a PR to mention that PKCE is not supported.

**Comment by skedwards88** [comment]
@github/ecosystem-apps-reviewers could you review this from a technical perspective?

**Comment by jamesmartin** [comment]
@skedwards88 just to clarify, are you asking for review of the [cross-referenced PR](https://github.com/github/docs/issues/22270#issuecomment-1505490294)? Or something else?

**Comment by jamesmartin** [comment]
Thanks for clarifying, @skedwards. I think #24965 only covers [the additional discovery that PKCE is not supported](#issuecomment-1327726265). The fact that we block `OPTIONS` requests, and therefore CORS preflight requests don't work, could also be documented to help developers of SPAs that depend on this type of authorization code flow.

**Comment by skedwards88** [comment]
Thanks for confirming!

@baywet you or anyone else is welcome to open a PR to document [this info](https://github.com/github/docs/issues/22270#issuecomment-1530197560).

**Comment by baywet** [comment]
Thanks for providing more clarity.
Documenting the feature gap is a first step in the right direction, but ultimately I'd like to see the gap addressed in the service.
Before I make any documentation change, how can I request the feature formally?

**Comment by jamesmartin** [comment]
> Before I make any documentation change, how can I request the feature formally?

We're tracking this feature internally and the discussion here has already been helpful to bring fresh perspectives to the issue. We don't have anything to announce right now as far as roadmaps go, however.

**Comment by Abdo00011** [comment]
Paymob

**Comment by baywet** [comment]
@jamesmartin great! Thank you for helping prioritize this set of features! Here is an additional PR to document the CORS gap. #25563
