### ISSUE TITLE
Clarify use of repository and context claims in OIDC setup

### ISSUE THREAD

**Issue by ghost** [github/docs#22283]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect

### What part(s) of the article would you like to see updated?

The article contains a list of possible claims [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token).

# Repository claim

One of these claims is `repository`, which corresponds to repository name _and_ the owner. However, the subject examples do not reference this claim name but rather `repo`:
```
repo:octo-org/octo-repo:environment:prod
```

In the above subject, `environment` is a claim listed in table of available claims but `repo` is not listed. Additionally, the API accepts `repo` but not `repository`. [This sample](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-granting-access-to-a-specific-repository) also only talks about `repo`.

A clarification of this claim would be nice.

# Context claim
This [section](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-requiring-a-reusable-workflow-and-other-claims) talks about using `context`.

It goes on to say:
> This example also demonstrates how to use "context" to define your conditions. This is the part that follows the repository in the [default sub format](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-subject-claims). For example, when the job references an environment, the context contains: environment:<environmentName>.

I can't piece this one together from the available informationl. What can `context`contain? If it is always everything after `repo`, what happens when I customize my token claims?

The default sub format then mentions the [job context](https://docs.github.com/en/actions/learn-github-actions/contexts#job-context), which in turn doesn't mention `environment` as a part of that context.

Some more samples to clarify the use of context would be nice.

**Comment by cmwilson21** [comment]
@johanredeploy Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by johanredeploy** [comment]
Sorry, I forgot to mention one thing above.

[Example: Granting access to a specific repository](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-granting-access-to-a-specific-repository) links to [Customizing the token URL for an enterprise](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-token-url-for-an-enterprise), which seems to lead nowhere.

**Comment by hubwriter** [comment]
I'm not sure what the hold up has been with this. I'll get some expert 👀 to take a look at this.

As regards this:

> [Example: Granting access to a specific repository](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-granting-access-to-a-specific-repository) links to [Customizing the token URL for an enterprise](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-token-url-for-an-enterprise), which seems to lead nowhere.

The link seems to have been fixed now.

**Comment by hubwriter** [comment]
An SME in this area has told me:

> `repo` is the same as `repository`. `repo` prefix in the subject claim contains NWO for the repository. `repository` claim in ID token would have the same data.

I don't personally know enough about this area to determine exactly what changes we need to make. If anyone reading this issue feels confident to suggest changes then it would be great if you can create a pull request and we can get a technical review of it.

Meanwhile I'll continue looking for some more assistance with this.

**Comment by TomChapple** [comment]
I see the documentation on this page has clarified the use of `repo:`, which is awesome, but I'm struggling to find examples or expectations regarding the `"context"` claim. As such, I'm not sure if the section of the original Issue on "context" was addressed or not.

I can see some examples that result in `environment:prod` being provided if `"context"` is given, but is that the limit to what it includes? If `"context"` isn't defined elsewhere, is this page a good place to define its purpose and contents? Otherwise, I'm inclined to assume it has nothing and use other claims in my tokens to guarantee it has what I require.

**Comment by nguyenalex836** [comment]
Hello @TomChapple 👋 !

> I can see some examples that result in environment:prod being provided if "context" is given, but is that the limit to what it includes? If "context" isn't defined elsewhere, is this page a good place to define its purpose and contents?

Given the age of this issue, we'd recommend opening a new one within this repo that includes the questions you mentioned above. This will also likely be the fastest way to get a response from the team 💛
