### ISSUE TITLE
Extra whitespace in the document actions-group-concurrency.md

### ISSUE THREAD

**Issue by diamante0018** [github/docs#22284]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/data/reusables/actions/actions-group-concurrency.md

Throughout the document, on three occasions, there is extra white space in front of `concurrency:`:
-  (concurrency:` `)

### What part(s) of the article would you like to see updated?

I would like the extra white space to be removed.

### Additional information

A fix would be nice because when I copied and pasted from this document, I did not notice the whitespace.

**Comment by cmwilson21** [comment]
@diamante0018 Thank you for opening an issue and linking it to your PR! ✨
