### ISSUE TITLE
Extra `>` character in 'Managing remote repositories'

### ISSUE THREAD

**Issue by Viicos** [github/docs#22291]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#adding-a-remote-repository

### What part(s) of the article would you like to see updated?

I don't think this is intentional but there's an extra `>` character in the example:

```shell
$ git remote add origin https://github.com/USER/REPO>.git  # Here
# Set a new remote

$ git remote -v
# Verify new remote
> origin  https://github.com/USER/REPO.git (fetch)
> origin  https://github.com/USER/REPO.git (push)
```

If not, I can open a PR to fix this.

**Comment by cmwilson21** [comment]
@Viicos Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Missionmunshi** [comment]
Ok
