### ISSUE TITLE
Parameters missing from GitHub App Manifests

### ISSUE THREAD

**Issue by blakegearin** [github/docs#22315]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.6/developers/apps/building-github-apps/creating-a-github-app-from-a-manifest#github-app-manifest-parameters

### What changes are you suggesting?

The "GitHub App Manifest parameters" section should be updated to include all possible parameters.

I haven't tried myself, but it seems likely that `request_oauth_on_install` and `setup_on_update` are supported and undocumented manifest parameters.

Request to open this issue: https://github.com/github/docs/issues/21659#issuecomment-1307841708

### Additional information

Here's a comparison between the parameters listed in the manifest documentation versus the URL parameters documentation.

|Parameter|[URL parameters](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app-using-url-parameters#github-app-configuration-parameters)|Manifest parameters|
|--|:-:|:-:|
|`name`|✅|✅|
|`description`|✅|✅|
|`url`|✅|✅|
|`callback_urls`|✅|✅|
|`public`|✅|✅|
|`request_oauth_on_install`|✅|❌|
|`setup_url`|✅|✅|
|`setup_on_update`|✅|❌|
|`webhook_active`|✅|❌ see: `hook_attributes`|
|`webhook_url`|✅|❌ see: `hook_attributes`|
|`hook_attributes`|❌|✅|
|`events`|✅|❌ see: `default_events`|
|`default_events`|❌ see: `events`|✅|
|`single_file_name`|✅|❌|
|`single_file_paths`|✅|❌|
|`redirect_url`|❌|✅|
|`default_permissions`|❌ passed in as [key-value pairs](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app-using-url-parameters#github-app-permissions)|✅|

**Comment by AgustinRamiroDiaz** [comment]
:point_up:  yes please!

**Comment by cmwilson21** [comment]
@blakegearin Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by OlayinkaAtobiloye** [comment]
Hi @cmwilson21 , Olayinka here! I started work on the project with a couple of issues from the project board. Made change to address this issue and raised a PR for it here - https://github.com/github/docs/pull/23736. Please check it out when chanced!
