### ISSUE TITLE
Actions workflow syntax: `if` without expression syntax `${{ }}` can result in YAML syntax error

### ISSUE THREAD

**Issue by victorlin** [github/docs#22392]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Anything that uses [`reusables.actions.expression-syntax-if`](https://github.com/github/docs/blob/4a1444675e5d477b91bdd958b64ecb681561c54a/data/reusables/actions/expression-syntax-if.md), which states:

> When you use expressions in an `if` conditional, you may omit the expression syntax (`${{ }}`) because GitHub automatically evaluates the `if` conditional as an expression.

So, at least the following:

1. https://docs.github.com/en/actions/learn-github-actions/expressions
2. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

### What changes are you suggesting?

These articles suggest that `${{ }}` can always be omitted from an `if` conditional. However, that is not the case since this results in a YAML syntax error ([evidence](https://github.com/victorlin/github-test/actions/runs/3587796774/workflow)):

```
if: !false || false
```

Wrapping it in `${{ }}` allows the expression to be evaluated properly ([evidence](https://github.com/victorlin/github-test/actions/runs/3587806232/workflow)):

```
if: ${{ !false || false }}
```

I suggest changing the wording to highlight this limitation.

**Comment by cmwilson21** [comment]
@victorlin Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Thanks for opening this issue, @victorlin!

Yep, as you discovered in [your comment](https://github.com/github/docs/issues/22392#issuecomment-1334156197), you can't begin YAML values with some special characters unless you quote them.

This applies to all YAML values, not just for GitHub Actions or the `if` key, so a doc update probably isn't required here.
