### ISSUE TITLE
Add callout that some contexts aren't available for use in the `jobs.<job_id>.if` conditional

### ISSUE THREAD

**Issue by MarkIannucci** [github/docs#22436]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

### What part(s) of the article would you like to see updated?

Please add a callout that certain contexts are not available for use in the `jobs.<job_id>.if` conditional.  If you attempt to use them, you get an `Unrecognized named-value: '<context>'.` error. 

Adding links to issues where people on the internet have learned about this the hard way:

* https://github.com/actions/runner/issues/1985
* https://github.com/actions/runner/issues/1189

**Comment by cmwilson21** [comment]
@MarkIannucci Thanks for opening an issue and linking it to your PR! ✨

**Comment by cognitiaclaeves** [comment]
This is a necro-post, but I wanted to point out, in case anyone sees this later, that I don't think that PR #22437 addresses issue #1189 at all -- it is now completely vague as to whether or not one can refer to variables in env from the job context.

**Comment by cmwilson21** [comment]
@cognitiaclaeves 👋 - Would you mind opening your concern as a new issue? That way I can triage it and make sure someone gets eyes on it for review 👀
