### ISSUE TITLE
Clarify that workflows can be reused within an org's private repo with appropriate settings

### ISSUE THREAD

**Issue by TannerPerrien** [github/docs#22434]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows

### What changes are you suggesting?

The current docs are misleading in suggesting the following:

> A reusable workflow can be used by another workflow if either of the following is true:
>
> * Both workflows are in the same repository.
> * The called workflow is stored in a public repository, and your organization allows you to use public reusable workflows.
>
> Source: https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-to-reusable-workflows

### Additional information

Go to a repository's Settings > Actions > General > [Bottom of page] **Access** -> `Accessible from repositories in the 'XYZ' organization`

So long as this access level is chosen, workflows in this private repo can be reused in other private repos own by the same org.

**Comment by TannerPerrien** [comment]
This may be covered in the [enterprise docs](https://docs.github.com/en/enterprise-cloud@latest/actions/creating-actions/sharing-actions-and-workflows-with-your-enterprise). However, I am able to set access permissions with a GitHub Team plan, so I still think the docs should receive some kind of update.

**Comment by cmwilson21** [comment]
@TannerPerrien Thanks for opening an issue and submitting a PR ✨

**Comment by lucascosti** [comment]
Thanks a lot for the issue and PR, @TannerPerrien!

This product change is still in the process of being fully rolled out, and we do have docs ready to go internally that will cover it. At the moment, we expect the official docs and announcement will be released publicly sometime next week.

Sorry for the confusion 🙇‍♂️

**Comment by TannerPerrien** [comment]
That's great news! Thanks!
