### ISSUE TITLE
About SAML and SCIM in OKTA page doesn't include clear instructions on enabling/setting up the OKTA GHEC -Org app integration.

### ISSUE THREAD

**Issue by adamrr724** [github/docs#22475]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/configuring-saml-single-sign-on-and-scim-using-okta

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/configuring-saml-single-sign-on-and-scim-using-okta

The 3rd party GitHub Enterprise Cloud- Organization App integration needs to be set-up in order for the instructions in this section to make any sense. I propose adding documentation on how to set up the app integration to add more clarity.

**Comment by cmwilson21** [comment]
👋 @adamrr724 Thank you for opening an issue and linking it to your PR! ✨

**Comment by janl3577** [comment]
I help pls
