### ISSUE TITLE
Fix example in "Adding your ssh key to the ssh agent"

### ISSUE THREAD

**Issue by skullbunnygalaxy** [github/docs#22480]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

### What part(s) of the article would you like to see updated?

The Mac portion of this article, specifically [Adding your ssh key to the ssh agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent), needs to be fixed. 

Currently, the example for adding to `~/.ssh/config` reads as:
> Host *.github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519

However, this does not work. Using `Host *.github.com` results in a `Permission denied (publickey)` error. 

Once adjusted to `Host github.com` it works. The documentation does have [a page for that error](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey), which I used when troubleshooting the issue, but the page does not list this as one of the potential causes. 

Expected outcome: Change the example from `Host *.github.com` to `Host github.com` in order for it to work as expected and not result in errors.

**Comment by cmwilson21** [comment]
@skullbunnygalaxy Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by sophietheking** [comment]
@skullbunnygalaxy thanks for opening this issue and contributing to our Docs! A PR was just merged that fixes this example: https://github.com/github/docs/pull/23513 🙌  I'll go ahead and close this issue.

If you're looking for your next contribution, check out our [help wanted issues](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) :zap:
