### ISSUE TITLE
`Maximum access by forked repos` is inaccurate

### ISSUE THREAD

**Issue by jsoref** [github/docs#22493]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

### What part(s) of the article would you like to see updated?

As noted in #22492, `Maximum access by forked repos` really means `Maximum access for pull requests from forked repos`.

But, beyond that, https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories says:

> Available to private repositories only, you can configure these policy settings for organizations, or repositories.
...
> Send write tokens to workflows from pull requests - Allows pull requests from forks to use a GITHUB_TOKEN with write permission.

Thus, the correct text would be `Maximum access for pull requests to public repositories from forked repos`.

I know that's a mouthful and too much to stick into a column heading, but the current text is fairly misleading and finding all the caveats is not fun.

### Additional information

https://github.com/PowerDNS/pdns/pull/12249#discussion_r1041069218

**Comment by nawed2611** [comment]
Hey, I would like to work on this

**Comment by lucascosti** [comment]
Thanks for pointing this out, @jsoref. Because this was slightly complicated to implement, i've opened a PR to fix in https://github.com/github/docs/pull/22730.
