### ISSUE TITLE
`has read-only permissions in forked repositories` is incorrect

### ISSUE THREAD

**Issue by jsoref** [github/docs#22492]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/6d25c89672596b801f4885eda80d043f7c568c56/data/reusables/developer-site/pull_request_forked_repos_link.md?plain=1#L5

### What part(s) of the article would you like to see updated?

The part that says:

> has read-only permissions in forked repositories.

It should _probably_ say

> has read-only permissions in _pull requests from_ forked repositories.

### Additional information

https://github.com/PowerDNS/pdns/pull/12249#discussion_r1041069218

**Comment by lucascosti** [comment]
👋 Yep, the suggested change sounds good. Anyone can feel free to open a PR to fix.
