### ISSUE TITLE
Remove unnecessary comma in private forks test

### ISSUE THREAD

**Issue by jsoref** [github/docs#22494]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories

### What part(s) of the article would you like to see updated?

> If you rely on using forks of your private repositories, you can configure policies that control how users can run workflows on pull_request events. Available to private repositories only, you can configure these policy settings for organizations, or repositories.

If you can set this knob for enterprises, the text should say so.

If you can't set it for enterprises, the text should say so.

### Additional information

#22493

**Comment by jsoref** [comment]
I suppose I should note that as-is the text has a `,` for a list of 2 items (`organizations` and `repositories`) which is wrong the comma will only apply once there's a third item (enterprises) 🙂 .

**Comment by lucascosti** [comment]
👋 @jsoref, thanks for opening this issue. The article does mention enterprises, but only if you are viewing the article for an enterprise product (we try not to mention enterprise options unless it's applicable to the docs someone is viewing):

<img width="958" alt="image" src="https://user-images.githubusercontent.com/4434330/206976321-4343560a-e663-40a1-b727-60a4c24694c3.png">

> I suppose I should note that as-is the text has a , for a list of 2 items (organizations and repositories) which is wrong the comma will only apply once there's a third item (enterprises) 🙂 .

Great pickup! The unnecessary comma there is fine on an enterprise page, but not on a non-enterprise page. That comma should be versioned only for viewing an enterprise page. I'll update the title of the issue. 

You can find that paragraph in this reusable: https://github.com/github/docs/blob/main/data/reusables/actions/private-repository-forks-overview.md#L0-L1

Feel free for you, or  anyone else, to open a PR to fix this 🙇‍♂️
