### ISSUE TITLE
Change "close repo" to "archive repo"

### ISSUE THREAD

**Issue by brccabral** [github/docs#22508]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/issues/planning-and-tracking-with-projects/managing-your-project/closing-and-deleting-your-projects.md

### What part(s) of the article would you like to see updated?

"close repo" has been changed to "archive repo"

![image](https://user-images.githubusercontent.com/130455/206070808-c5f6812a-6392-46f2-b804-3feac58da84d.png)

### Content plan
[maintainer edit]
Update the screenshot in "[Deleting a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository)" to reflect current UI. 
Tips for  [updating the screenshot](https://github.com/github/docs/blob/main/contributing/images-and-versioning.md).

**Comment by cmwilson21** [comment]
@brccabral Thanks for opening an issue! ✨ 

The page referenced links to "[Closing and deleting your projects](https://github.com/github/docs/blob/main/content/issues/planning-and-tracking-with-projects/managing-your-project/closing-and-deleting-your-projects.md)". The screenshot there is correct for that article. 

However, I did dig into the article for "[Deleting a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository)". That screenshot could be updated to reflect the current UI. 

You or anyone else are welcome to submit a PR with this fix by [updating the screenshot](https://github.com/github/docs/blob/main/contributing/images-and-versioning.md). I've updated the original post to include this information. 💖

**Comment by dostonnabotov** [comment]
Hey, there!

I would be happy to pick this issue if you assign it to me :)

As far as I understand, we only need to update the "[Deleting a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository)" article images to reflect the current UI. But, no update is required for "[Closing and deleting your projects](https://github.com/github/docs/blob/main/content/issues/planning-and-tracking-with-projects/managing-your-project/closing-and-deleting-your-projects.md)" article. Is that right?

**Comment by cmwilson21** [comment]
@dostonnabotov Thanks for your interest in improving the docs! You or anyone else is welcome to submit a PR with this update. ✨ 

Since this image is a reusable, updating the reusable itself should update it where ever that image exists 😄

**Comment by knlkshyp** [comment]
@cmwilson21 Thank you for your suggestion. I have raised one PR to update the image https://github.com/github/docs/pull/22738
