### ISSUE TITLE
"Reuse Workflows" article should explain how to share files across workflows

### ISSUE THREAD

**Issue by marcofugaro** [github/docs#22523]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows

### What part(s) of the article would you like to see updated?

In the **Overview** section, there is a little explaination about reusing workflows and there is this screenshot

<img width="747" alt="image" src="https://user-images.githubusercontent.com/7217420/206239820-1e5e89bf-61a9-45cd-8c02-f52549b8322d.png">

I want to replicate exactly that. Multiple deploy actions which depends on a single build action in my case.

However, reading the article, I wasn't able to find out how to share files across actions. The article ends with sharing strings only.

I think, since that screenshot has been shown as realistic example, the article needs to contain an explanation on how to share built files across workflows.

### Additional information

[maintainer edit]
Content plan [here](https://github.com/github/docs/issues/22523#issuecomment-1399886932)

**Comment by fadel420project** [comment]
fadel420project

**Comment by cmwilson21** [comment]
@marcofugaro Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
👋 @marcofugaro, I've flagged this issue for an SME to have a look at.

IIUC, there's no built-in way to share files between different workflows; it's is up to you to manage the artifacts between workflows.

One way, using artifact storage built into GitHub Actions, is to use the [upload-artifact action](https://github.com/marketplace/actions/upload-a-build-artifact) to upload an artifact, and then in a different workflow either use [the REST API](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#get-an-artifact) or [a third party action](https://github.com/marketplace/actions/download-workflow-artifact) to download that artifact. The GitHub-authored [download-artifact](https://github.com/marketplace/actions/download-a-build-artifact) action only works for artifacts uploaded in the same workflow.

**Comment by marcofugaro** [comment]
Thank you @lucascosti, I eventually figured it out.

I noticed there is now an [artifacts section](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) in the docs.
A mention to that section inside the Reuse workflow article would be enough.

**Comment by lucascosti** [comment]
> Thank you @lucascosti, I eventually figured it out.

Good to hear!

> I noticed there is now an [artifacts section](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) in the docs. A mention to that section inside the Reusing workflows article would be enough.

Yep, that article has always been there, but it's a good idea to link to it. 

We could probably add the link at the bottom of the [Using outputs from a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow) section to link there.

Feel free for yourself (or anyone else) to open a PR 🙇‍♂️
