### ISSUE TITLE
Transferring ownership article(s) should contain pointers to how/where transfer request can be approved

### ISSUE THREAD

**Issue by derisen** [github/docs#22565]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/managing-oauth-apps/transferring-ownership-of-an-oauth-app

### What part(s) of the article would you like to see updated?

The article should mention what happens when a transfer request is made and how/where the transfer request can be approved. 

Alternatively, it can contain a link to a resource that covers this information.

### Additional information

I'm trying to transfer the ownership of several OAuth apps to an organization. However, the organization admins are unsure where they can approve the request. It would be great if the article makes a mention of this.

----
_Maintainer update_

The proposed updates to fix this issue are in this comment: https://github.com/github/docs/issues/22565#issuecomment-1726051141.

**Comment by cmwilson21** [comment]
@derisen Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by RobertEllisClick55** [comment]
Thank you

**Comment by skedwards88** [comment]
Thanks for opening this issue! I am going to leave it here in the open source repo for anyone to contribute to, but I do not currently have the information to document. I am also making an internal note in our backlog to research and document this.

**Comment by derisen** [comment]
sounds great -thanks so much!

**Comment by Venkatreddy17** [comment]
@derisen I am interested taking this issue. I found about docs through friend.

**Comment by skedwards88** [comment]
Once you initiate the transfer, the new owner needs to navigate to their OAuth Apps page. From there, they should see the app listed under "Pending transfer requests". They need to click on the app name and then click **Complete transfer**.

**Comment by CBID2** [comment]
Hi @cmwilson21 and @isaacmbrown, I made PR for this issue. It's #29464
