### ISSUE TITLE
Update ubuntu-latest reference to 22.04

### ISSUE THREAD

**Issue by saracope** [github/docs#22572]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners

https://github.com/github/docs/blob/75b0d607dc81f8712165d3b5707b174e24bf7238/data/reusables/actions/supported-github-runners.md?plain=1#L46

### What part(s) of the article would you like to see updated?

The `ubuntu-latest` label is now defaulted to Ubuntu 22.04 but this page indicates that `ubuntu-latest` is 20.04. I think this info should be updated. [reference](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/)
It does mention the transition and links to an old blog post. This can probably be removed now.

### Additional information

<img width="821" alt="Screen Shot 2022-12-09 at 12 32 33 PM" src="https://user-images.githubusercontent.com/2197515/206759550-aff9090f-dd6c-4682-b0be-e0d5038ab11d.png">

**Comment by cmwilson21** [comment]
@saracope Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Hi @saracope, thanks for opening this issue.

The transition for the `ubuntu-latest` label (for both standard and larger GitHub-hosted) runners is still in progress, and we'll be updating the docs when it is complete. Depending on which pool of runners is assigned to a job, it may get a 22.04 or 20.04 runner.

Note that [the blog post you linked](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/) is for [Larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners), which may transition on a different timeline to the [standard runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

**Comment by saracope** [comment]
@lucascosti The blog post mentions "Ubuntu-22.04 is now the [default version](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/) for the ubuntu-latest label for GitHub Actions standard runners workflows." Which I think is the confusing part.

**Comment by lucascosti** [comment]
@saracope Yep, I totally understand 🙂. I'll pass the feedback onto our blog team; the messaging on this isn't very clear.
