### ISSUE TITLE
Add in definition of terms like "synchronize" for Github Action Activity types

### ISSUE THREAD

**Issue by logankilpatrick** [github/docs#2257]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request

### What part(s) of the article would you like to see updated?

This page references activity types like: "synchronize" but does not provide a definition of what this means. To my understanding, it means that a commit has been made to a pull request branch but it's not clear based on the docs if this is correct. 

### Additional information

It may be worth considering adding a definition for all of the "Activity Types" given it may not be fair to assume every user will know of the full GitHub functionality when reading the docs.

**Comment by janiceilene** [comment]
@logankilpatrick Thanks for opening an issue! I'll triage this so the right team can take a look 👀

**Comment by logankilpatrick** [comment]
Thank you @janiceilene!

**Comment by 0xdevalias** [comment]
In a recent GitHub support ticket, I was told the following about the `synchronize` event:

> A `synchronize` `pull_request` event it’s only triggered when the pull request’s tracking branch is synchronized with the source branch for the pull request, and that happens when the source branch is updated.
> 
> So every time someone pushes to the source branch of the pull request, the workflow will kick off again.

According to the following docs, I am assuming that the 'tracking branch' refers to the 'base branch' (eg. `main`), and the 'head branch' refers to the branch for the PR you currently have open:

- https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-branches
  - > Once you're satisfied with your work, you can open a pull request to merge the changes in the current branch (the head branch) into another branch (the base branch).

**Comment by janiceilene** [comment]
Thanks so much for that additional information and context @0xdevalias!

**Comment by skedwards88** [comment]
Regarding the specific question about the `synchronize` activity, I think this doc should give you more info: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/syncing-your-branch

Currently, the [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) article and the [Webhook events and payloads](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request) article (which is linked to from the former article) are both quite long, so we are going to avoid defining all of the activity types for now to keep the article from becoming too bloated.

Although we won't make a change immediately, it is really helpful to have feedback about this! 💖 I hope we continue to hear feedback from you about how we can improve the docs!

**Comment by 0xdevalias** [comment]
@skedwards88 I may just have missed it, as I only quickly skimmed through the article, but I don’t feel like it satisfies the needs/request of this issue in being clear about when the ‘synchronise’ event is fired within GitHub actions, and specifically ensuring that that information is linked from/easily findable from the actions docs sections.

The link you provided feels more like a high level ‘how to use git’ sort of article.

**Comment by polarathene** [comment]
I came across [this](https://github.community/t/what-is-a-pull-request-synchronize-event/14784/4) which seems to clarify what `synchronize` covers. The current docs mention and link about Pull Request docs elsewhere, but neither really covered this event either.

Deeming the present docs page as too long is totally understandable as a concern. But this shouldn't mean these events should not be documented properly anywhere else since they're presumably Github API specific? If they are clearly explained somewhere in Github docs, perhaps there should be a link to those for users to visit when they need additional clarification of what each event entails, especially when something like `synchronize` isn't immediately clear where that applies.

**Comment by logankilpatrick** [comment]
Agreed :)

**Comment by 0xdevalias** [comment]
@janiceilene / anyone else on the GH docs team: Can we please get this issue re-opened? As the content that @skedwards88 linked when they closed this issue is unrelated, and doesn't solve the need here.

**Comment by logankilpatrick** [comment]
Cc @janiceilene

**Comment by skedwards88** [comment]
Thanks for the feedback on this! I'm re-opening this issue. [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) links to [Webhook events and payloads](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request). [Webhook events and payloads](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request) might be a better place to note what `synchronize` means. (Similar to how we add details about the `closed` action.)

Anyone is welcome to open a PR to address this issue.

**Comment by jai** [comment]
Going off @skedwards88 comment on adding description for `synchronize` similar to how it was added for `closed` - I'm guessing we mean here: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request

> The action that was performed. Can be one of opened, edited, closed, assigned, unassigned, review_requested, review_request_removed, ready_for_review, converted_to_draft, labeled, unlabeled, synchronize, auto_merge_enabled, auto_merge_disabled, locked, unlocked, or reopened. If the action is closed and the merged key is false, the pull request was closed with unmerged commits. If the action is closed and the merged key is true, the pull request was merged.

I'm not sure it's scalable to add the description for `synchronize` here, although I guess we could turn it into a bulleted list similar to `action` under: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request_review

**Comment by jai** [comment]
I've drafted what the list would look like as bullets - see https://github.com/github/docs/pull/5945, screenshot 

<img width="775" alt="CleanShot 2021-05-02 at 12 07 02@2x" src="https://user-images.githubusercontent.com/1943284/116802686-03349880-ab3f-11eb-82d7-f6040bcb376e.png">

**Comment by jai** [comment]
Deploy preview: https://docs-5945--jaifix-2257.herokuapp.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request

Do we want to add descriptions for other terms, or address that in future PRs?

![CleanShot 2021-05-02 at 12 27 42](https://user-images.githubusercontent.com/1943284/116803434-d03fd400-ab41-11eb-8bc7-1ab8d5ab123f.png)

**Comment by logankilpatrick** [comment]
I like that a lot, it is plain and simple. The context make that section much more useful.

**Comment by jai** [comment]
@janiceilene @skedwards88 any idea who I would reach out to for a review on [the PR](https://github.com/github/docs/pull/5945)? Or will that happen in time?

**Comment by janiceilene** [comment]
@jai Thanks for opening the PR! It's been triaged and the writers will take a look at it as soon as possible 💛

**Comment by skedwards88** [comment]
I love your idea to turn this into a bulleted list! ⚡ 

> Do we want to add descriptions for other terms, or address that in future PRs?

I think just adding a description for `synchronize` is good. If users are confused about additional action types, we can address that in a separate issue/PR.

**Comment by rokcarl** [comment]
I came to this issue precisely because I wanted to know what `synchronize` means exactly, the documentation in its current form still doesn't give this answer. Or am I mistaken?

**Comment by logankilpatrick** [comment]
Looks like it was merged 4 months ago

**Comment by rokcarl** [comment]
I was reading the [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows) GitHub official documentation and it's not there. So I started Googling _github actions synchronize_ and came across this issue. A simple link from the doc I mentioned to the merged/deployed doc explaining this would suffice.

**Comment by 0xdevalias** [comment]
> A simple link from the doc I mentioned to the merged/deployed doc explaining this would suffice.

@janiceilene @logankilpatrick @skedwards88 @jai / anyone else on the GH docs team: Can we please get this issue re-opened? And the improvements mentioned in https://github.com/github/docs/issues/2257#issuecomment-916014423 made?

**Comment by jai** [comment]
I don't have permission to re-open. I think it would be valid to open a new issue? I'm happy to address in a new PR.

**Comment by cmwilson21** [comment]
Hey @0xdevalias! @jai is right, a new issue would be best so we can get it triaged and reviewed. ✨ 

Thanks for checking in!

**Comment by justinsteele** [comment]
Looks like this fix may have been removed unintentionally in https://github.com/github/docs/commit/b2e5d14036a700b781e91158a552f8c0b1f04839 roughly a year ago. If it was still being referenced via dynamic calling, this followup commit removed the file in question: https://github.com/github/docs/commit/890735a6320e780ae69f15797b5759aaeb2cbd47

**Comment by siloKalle** [comment]
Related: Why the documentation says that you can filter pull_request events based on files changed, but the fact is that the "paths" attribute does not do anything. 

I'm really lost with the documentation that does not explain how you create subfolder specific PR workflows in the monorepo case.

**Comment by tpensyl** [comment]
Just leaving a note for future googlers like myself, for which the resolution from above thread was not obvious: The action types are documented under the dropdown boxes [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request)

**Comment by bobvanderlinden** [comment]
Oof, that was suprising UX. I searched the page for `synchronize`, couldn't find anything, so concluded it's not the page I was looking for. @tpensyl Thanks for the heads up.

**Comment by VictorIreri** [comment]
> Just leaving a note for future googlers like myself, for which the resolution from above thread was not obvious: The action types are documented under the dropdown boxes [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request)
 
Not sure I'd have found it without this comment but it's definitely there. ¯\\\_(ツ)_/¯
Direct link: [pull_request > synchronize](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request)

<img width="500" src="https://github.com/user-attachments/assets/34bb45b8-5cb6-4685-ba16-311e63e7dc04" />
