### ISSUE TITLE
Typo in `data reusables.dependabot.supported-package-managers`

### ISSUE THREAD

**Issue by hsz** [github/docs#2259]
### What article on docs.github.com is affected?

22 articles that include:
```
{% data reusables.dependabot.supported-package-managers %}
```

https://github.com/github/docs/search?p=2&q=supported-package-managers

### What part(s) of the article would you like to see updated?

*Note* section contains a table, where we can read:

> -.gradle.**tks** files, for Kotlin projects (specify gradle)

Should be:

> -.gradle.**kts** files, for Kotlin projects (specify gradle)

**Comment by janiceilene** [comment]
@hsz Thanks for opening an issue! I'll get this triaged for the right team to take a look 👀

**Comment by HonkingGoose** [comment]
PR #2283 will fix this problem.
