### ISSUE TITLE
Small spelling mistake in creating webhooks page.

### ISSUE THREAD

**Issue by clxmente** [github/docs#22598]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks

### What part(s) of the article would you like to see updated?

You'll first need to set up what events  __you__ webhook should listen to. 

The you should be "your" :)

**Comment by cmwilson21** [comment]
@clxmente Thank you for opening an issue and linking it to your PR! ✨
