### ISSUE TITLE
GraphQL errors, and especially rate limit errors, are not documented

### ISSUE THREAD

**Issue by FiloSottile** [github/docs#22607]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql

### What part(s) of the article would you like to see updated?

There seems to be no documentation for what the GraphQL API returns on error conditions.

In particular, I can't find what error code to expect once the rate limit is exceeded. I see I can use the `rateLimit` query field to get information on how many points I have left _when a query succeeds_, but I can't rely on that alone as I might have a few points left and then make a very large request.

I assume a rate limit error will also provide a `resetAt` field, but I have no idea under what name or path. The only way I can see to develop an app that will handle rate limits gracefully is to burn 5000 points and hit the error to learn how it looks like.

**Comment by cmwilson21** [comment]
@FiloSottile Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
The response code will be 200, and the errors field will indicate that you have a rate error. Foe example:

With GitHub CLI, a rate limited response looks like:
```
% gh api graphql -f query='{
  viewer {
    login
    isSiteAdmin
  }
}'
{
  "errors": [
    {
      "type": "RATE_LIMITED",
      "message": "API rate limit exceeded for user ID 9961."
    }
  ]
}
gh: API rate limit exceeded for user ID 9961.
```

With curl, a rate limited response looks like:

```
curl -w "%{http_code}" https://api.github.com/graphql \
  -H "Authorization: token $GITHUB_TOKEN" \
  --compressed \
  --data-binary '{"query":"{\n\t__schema{\n queryType {\n fields{\n name\n }\n }\n }\n}"}'
{"errors":[{"type":"RATE_LIMITED","message":"API rate limit exceeded for user ID 9961."}]}
200
```

You or anyone else is welcome to add this info to the docs.

**Comment by FiloSottile** [comment]
Thank you. Is there a response header for the retryAt time or some other way to acquire it?

**Comment by mmrobins** [comment]
yes, there's an `x-ratelimit-reset`, along with some other useful headers

```
% curl -vvv https://api.github.com/graphql \
  -H "Authorization: token $GITHUB_TOKEN" \
  --compressed \
  --data-binary '{"query":"{\n\t__schema{\n queryType {\n fields{\n name\n }\n }\n }\n}"}' 2> >(grep x-ratelimit)
< x-ratelimit-limit: 5000
< x-ratelimit-remaining: 0
< x-ratelimit-reset: 1670985544
< x-ratelimit-used: 5000
< x-ratelimit-resource: graphql
```

**Comment by china170** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/graphql
> 
> ### What part(s) of the article would you like to see updated?
> There seems to be no documentation for what the GraphQL API returns on error conditions.
> 
> In particular, I can't find what error code to expect once the rate limit is exceeded. I see I can use the `rateLimit` query field to get information on how many points I have left _when a query succeeds_, but I can't rely on that alone as I might have a few points left and then make a very large request.
> 
> I assume a rate limit error will also provide a `resetAt` field, but I have no idea under what name or path. The only way I can see to develop an app that will handle rate limits gracefully is to burn 5000 points and hit the error to learn how it looks like.
> 
> ### Additional information
> _No response_

Hello are you there

**Comment by felicitymay** [comment]
@pgcd - you might find this article useful when you're doing future work using the GraphQL API: [Resource limitations - GitHub Docs](https://docs.github.com/en/graphql/overview/resource-limitations).
