### ISSUE TITLE
Example on how to pass secret to with workflow call is (incorrect) misleading

### ISSUE THREAD

**Issue by bkleinen** [github/docs#22602]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets

### What changes are you suggesting?

update: it's not incorrect, but it only gives an example for calling an action, and not a workflow, which I and all probably a lot of others did not realize, judging by the counter of the solution on stackoverflow. 

I've provided a pr: https://github.com/github/docs/pull/22603

### Additional information

found the solution here:
https://stackoverflow.com/questions/69521380/secret-interpolation-is-giving-syntax-error-in-caller-workflow-when-calling-a-re

**Comment by cmwilson21** [comment]
@bkleinen Thanks for opening an issue and PR!
