### ISSUE TITLE
Open links in new tab to let readers stay in the loop

### ISSUE THREAD

**Issue by anmolsahu2k** [github/docs#22613]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Multiple articles

### What changes are you suggesting?

On clicking on a certain URL in the articles, the link should open in a new tab rather than the current tab. This helps to let user continue the current article easily.

**Comment by cmwilson21** [comment]
@anmolsahu2k Thanks for opening an issue! I've passed this feedback along to the team. 

I'm going to go ahead and close this issue 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
