### ISSUE TITLE
"Adding organizations to your enterprise" does not warn about problems with transferring non-2fa accounts

### ISSUE THREAD

**Issue by scarletspiderfan** [github/docs#22633]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/user-management/managing-organizations-in-your-enterprise/adding-organizations-to-your-enterprise

### What part(s) of the article would you like to see updated?

The 'transferring an organization between enterprise accounts' section should have a warning to ensure customers are aware that non-2fa accounts being transferred into an enterprise that enforces 2fa policies will have issues (most likely getting removed from the org after transfer).

**Comment by cmwilson21** [comment]
👋 @scarletspiderfan Thanks for opening an issue and linking it to your PR! ✨

**Comment by arnelbenjamin** [comment]
why you can creat other PR? and boost the system area.?
