### ISSUE TITLE
Add link to best practices for pull_request_target

### ISSUE THREAD

**Issue by zkamvar** [github/docs#2264]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target

### What part(s) of the article would you like to see updated?

I was having trouble understanding the differences between `pull_request` and `pull_request_target`, and it appears that I wasn't the only one because [an explainer blog post was written on the Security Blog](https://securitylab.github.com/research/github-actions-preventing-pwn-requests) earlier this month to demonstrate the correct way to use both of these event triggers. 

I think having a link to that blog post would really help people (e.g. myself) construct their PR Actions in a safe manner. 

### Additional information

I was about to make a PR for this, but opened an issue after reading the CONTRIBUTING. If it's worth anything, here's the diff: https://github.com/github/docs/compare/main...zkamvar:patch-1

**Comment by janiceilene** [comment]
@zkamvar Thanks for opening an issue! I'll get this triaged for the right team to take a look 👀

**Comment by janiceilene** [comment]
Thanks so much for opening an issue and linking your diff @zkamvar! Sorry it's taken so long to get back to you. Your diff looks great! If you'd like to open a PR to make that change, we'd really appreciate it 💖
