### ISSUE TITLE
Client.js does not match the current version of redis npm module

### ISSUE THREAD

**Issue by ChoHadam** [github/docs#22661]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers

https://github.com/github/docs/blob/803715b128d5adf4f15e8e13bff2b0cfb86c66c1/content/actions/using-containerized-services/creating-redis-service-containers.md?plain=1#L279

### What part(s) of the article would you like to see updated?

Client.js, the example code for testing Redis service container, does not match the current version of  [redis](https://www.npmjs.com/package/redis) npm module. 

Currently, running `npm install redis` through terminal installs version 4.x(4.5.1) of redis by default. However, the Client.js code appears to have been written prior to redis v4.x. Comparing redis v4 and v3, the syntax and internal operation are completely different, as if creating a new package. For example, The redis v4 has been changed to operate asynchronously based on a promise object by default rather than based on a callback. More details can be found in the [v3 to v4 Migration Guide](https://github.com/redis/node-redis/blob/HEAD/docs/v3-to-v4.md).

Therefore, when the Client.js is executed on redis v4.x, the attached error occurs first, and other errors occur even if the legacy mode is applied like `createClient({ legacyMode: true })`. 

### Additional information

<img width="1164" alt="스크린샷 2022-12-13 오전 2 45 59" src="https://user-images.githubusercontent.com/35447878/207263394-87e87914-0436-4298-8ab7-a2f981dd78da.png">

**Comment by cmwilson21** [comment]
@ChoHadam Thank you for opening an issue and providing all this context. And for linking it to your PR! ✨

**Comment by Syed517** [comment]
Hi
***@***.***

**Comment by cmwilson21** [comment]
reopening as the PR is still waiting for review
