### ISSUE TITLE
For github organization, people page is not responsive for small screens

### ISSUE THREAD

**Issue by shaykhsiddique** [github/docs#2268]
### Current Condition

![bugorgs](https://user-images.githubusercontent.com/18369069/102819128-1c913f80-43fd-11eb-8f38-33c5549885e2.png)

The bug is on the organization people webpage, not properly handled for the small screens.

urlType: `https://github.com/orgs/{organization_name}/people`
urlExample: https://github.com/orgs/github/people

### Solution
Probably have to fix some `HTML` and `CSS`.

**Comment by janiceilene** [comment]
👋 @shaykhsiddique I'm sorry, we only take care of docs.github.com in this repo 💖 You can let the wonderful folks in [support](https://support.github.com/contact) know about the bug you've found though!
