### ISSUE TITLE
Add new note and warning admonitions to "Basic writing and formatting syntax"

### ISSUE THREAD

**Issue by HonkingGoose** [github/docs#22684]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

#### Detail to understand the change

GitHub now supports note and warning admonitions in Markdown. Here's a live preview of them:

> **Note**
> Note text

> **Warning**
> Warning text

I don't know if this feature is still in _beta_ (thus not documented), or if it's actually ready for production use.

If this feature is ready for production use, I would expect to find the new syntax in the linked article.

#### Why should the docs be changed?

The docs should match the current features for writing in Markdown on GitHub.

#### What is the expected outcome?

If feature in beta: keep issue around to remind you to fix it when it goes to production use.

If feature is ready for general use, close the issue with a PR with more documentation. Here's a rough todo list:

- [ ] Create new section "Admonitions"
- [ ] Show examples for Note and Warning admonition
- [ ] Show syntax for the admonition

**Comment by kiajfaty** [comment]
>

**Comment by cmwilson21** [comment]
👋 @HonkingGoose Thanks for opening an issue! We are checking on this internally, so I'll update when we have more information.

**Comment by 0823969789** [comment]
Ok

**Comment by 0823969789** [comment]
Duplicate of #

**Comment by HonkingGoose** [comment]
@cmwilson21 The stale bot is staling this automatically, but the issue still needs to be fixed. Can you please re-open my issue?

**Comment by cmwilson21** [comment]
@HonkingGoose Sure will! Sorry for the stale-bot closing it out. It seems to be acting a little wonky. Thank you for patience as we work through our backlog! 💖

**Comment by skedwards88** [comment]
Thanks for opening this issue! I agree we should document this, and I don't think we need a beta note. The only change I would make to your plan is to call the new section something like "Callouts" or "Notes and warnings" instead of "Admonitions" since "Admonitions" is a less common word.

You or anyone else is welcome to open a PR to address this issue.

**Comment by masterofimages** [comment]
This change is now live on Github but the docs still haven't been updated. What's going on? Surely updating the docs should be done alongside the change?
