### ISSUE TITLE
Caching on self-hosted runners

### ISSUE THREAD

**Issue by rajaie-sg** [github/docs#2271]
### What article on docs.github.com is affected?
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-circleci-to-github-actions#caching

### What part(s) of the article would you like to see updated?
Caching

### Additional information
The docs state that `GitHub Actions caching is only applicable to GitHub-hosted runners.` which seems to indicate we can't use caching on self-hosted runners, but I just tested caching on a self-hosted runner and it worked fine. Are the docs out of date?

**Comment by janiceilene** [comment]
@rajaie-sg Thanks for opening an issue! I don't know the answer to that question, so I'm going to triage this to have the right team take a look 👀

**Comment by akashshrimali** [comment]
Documentation

**Comment by antoniogamiz** [comment]
Any updates on this?

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the issues and PRs ✨

**Comment by janiceilene** [comment]
👋 @rajaie-sg I've gotten some answers from our engineering team and caching only works for repos hosted on github.com. 

We should update the line from `GitHub Actions caching is only applicable to GitHub-hosted runners.` to read `GitHub Actions caching is only applicable for repositories hosted on github.com`

You or anyone else is welcome to open a PR with that fix ✨

**Comment by ssabawissabawi** [comment]
https://github.com/github/docs/commit/2be566ca3e83cba9f3149f0a4fe28386a5a09885

**Comment by fishpen0** [comment]
Where does the cache actually live when using self-hosted runners?  Is it on the filesystem, github's servers, somewhere else?  Does caching do anything useful when also using the runner in `ephemeral` mode?

**Comment by ethomson** [comment]
> We should update the line from GitHub Actions caching is only applicable to GitHub-hosted runners. to read GitHub Actions caching is only applicable for repositories hosted on github.com

I think that a more precise statement would be that caching is only applicable for _workflows_ running on dotcom or GHEC. (In other words, caching does not work for GitHub Enterprise Server).

> Where does the cache actually live when using self-hosted runners? Is it on the filesystem, github's servers, somewhere else?

GitHub's servers.

At the moment `actions/cache` will only store caches on GitHub itself; this is true whether your runner is self-hosted or GitHub-hosted. Obviously the question about whether this makes sense for your self-hosted runners, network-wise, is an important one. If you're caching _computed data_ then it's probably a win! If you're caching to avoid network cost, then it may be that your cache restore is almost as expensive as running `npm install`.

> Does caching do anything useful when also using the runner in ephemeral mode?

No, it's no different than using static self-hosted runners.

**Comment by OmgImAlexis** [comment]
> At the moment actions/cache will only store caches on GitHub itself; this is true whether your runner is self-hosted or GitHub-hosted. Obviously the question about whether this makes sense for your self-hosted runners, network-wise, is an important one. If you're caching computed data then it's probably a win! If you're caching to avoid network cost, then it may be that your cache restore is almost as expensive as running npm install.

Can you please explain how this makes any sense at all to upload/download the data from github each time? Guessing this explains this... 
![image](https://user-images.githubusercontent.com/6525926/172959118-8d61d07e-6b19-456d-8e8a-840ecd63ecdc.png)

**Comment by OmgImAlexis** [comment]
This should be reopened.

**Comment by OmgImAlexis** [comment]
> 👋 @OmgImAlexis The best place to send your feedback is to [https://github.com/github/feedback/discussions 💛](https://github.com/github/feedback/discussions%C2%A0%F0%9F%92%9B)

Your link is broken btw. Managed to include the emoji in the link.

I've created a discussion for this as asked https://github.com/github-community/community/discussions/18549

**Comment by janiceilene** [comment]
🙈 Thanks for letting me know!

**Comment by ramonfritsch** [comment]
Just found out that you can use `MasterworksIO/action-local-cache@1.0.0` for this. It just like `actions/cache` but runs entirely local, very suitable for self hosted instances.

**Comment by maxnowack** [comment]
I had some trouble using `MasterworksIO/action-local-cache` as I need restoring multiple keys like it's possible with `actions/cache`.
I started my own solution, forked the `actions/cache` code and modified it to place a tarball on a local volume instead upload/download all the cache everytime.
You can use it as a drop-in replacement for `actions/cache@v3`: [maxnowack/local-cache](https://github.com/maxnowack/local-cache)

**Comment by LouisHaftmann** [comment]
We encountered an issue with custom cache actions not working when other actions (like `setup/node`) use the default `actions/cache`. Our solution was to ensure our custom cache is compatible with the default, eliminating the need to alter our workflow files. If anyone needs it, here you go: https://github.com/falcondev-it/github-actions-cache-server.

**Comment by wwwmdmorad230-wq** [comment]
https://github.com/github/docs/issues/new/choose
