### ISSUE TITLE
Unnecessary title mentioned after external webpage link

### ISSUE THREAD

**Issue by knlkshyp** [github/docs#22716]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Github Doc > [Fork a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)

### What part(s) of the article would you like to see updated?

There is an unncessary title ***at choosealicense.com*** mentioned after external webpage link [Choose an open source license](https://choosealicense.com/)

### Additional information

<img width="1436" alt="github-doc-fork-repo-unnecessary-title" src="https://user-images.githubusercontent.com/15921119/207931302-819c2841-be3f-4806-b430-ad56f339ab5c.png">

**Comment by cmwilson21** [comment]
@knlkshyp Thank you for opening an issue and linking it to your PR! ✨

**Comment by cmwilson21** [comment]
Closed via comment [here](https://github.com/github/docs/pull/22718#issuecomment-1354940952)
