### ISSUE TITLE
Restore payload examples for webhooks

### ISSUE THREAD

**Issue by wolfy1339** [github/docs#22726]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

### What part(s) of the article would you like to see updated?

I would like that payload examples be restored, it would help to model the whole webhook instead of just seeing the schema definitions.

In the docs for the REST api there is an example response, as well as the schema definitions.

**Comment by cmwilson21** [comment]
@wolfy1339 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for this feedback! We have an internal issue for this, so I'm going to close out this issue.

**Comment by tonyandbrenda2019** [comment]
Hi there could you please stop all the emails I don't won't any more I'm going into hospital so please stop Mr anthony william evans  ***@***.***

Get Outlook for Android<https://aka.ms/AAb9ysg>l
________________________________

**Comment by wolfy1339** [comment]
Hi, has any progress been made on this issue?
