### ISSUE TITLE
Bad German translation of "reference"

### ISSUE THREAD

**Issue by Simran-B** [github/docs#22737]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/de/graphql

### What part(s) of the article would you like to see updated?

The GraphQL `Reference` is translated as `Verweis` - which means referral or link in German. This makes no sense. It should be `Referenz`. The term might be badly translated in other places, too. I didn't check.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/7819991/208127771-67e73aef-0d07-4a29-a526-f5d58fa9c570.png">

**Comment by cmwilson21** [comment]
@Simran-B Thanks for reaching out! We use an internal automated solution for translations, so I've flagged this for our team to take a look.

I'm going to close this issue as we will be looking at it internally now 💛
