### ISSUE TITLE
Update Autoscaling Runner Docs Hyperlink

### ISSUE THREAD

**Issue by mitchell-liatrio** [github/docs#22742]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[autoscaling-with-self-hosted-runners](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners)

### What part(s) of the article would you like to see updated?

The URLs referencing https://github.com/actions-runner-controller/actions-runner-controller need to be updated to reference https://github.com/actions/actions-runner/controller

**Comment by cmwilson21** [comment]
@mitchell-liatrio Thank you for opening an issue and linking it to your PR! ✨
