### ISSUE TITLE
permissions: read-all|write-all does not work as an example

### ISSUE THREAD

**Issue by logankilpatrick** [github/docs#22769]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

### What changes are you suggesting?

The current example makes it seem like you can set the permissions to be both read and write but that shows an YAML error when you do so. I look but could not find the code for this section of the docs but it should be updated so people don't mistakenly try this.

----
_Maintainer update_

## Proposed changes to fix this issue

Under https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes.

We can make this example clearer by modifying the preceding paragraph to instead state:

> You can use the following syntax to choose one of `read-all` or `write-all` access for all of the available scopes

**Comment by ff999999999** [comment]
👀(❁´◡`❁)(感謝

**Comment by cmwilson21** [comment]
@logankilpatrick Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Thanks for opening this issue!

Most people should be able to recognize the meaning of the example, but I do agree that for less-experienced people we should be more explicit.

We could modify the preceding para to instead state:

```
You can use the following syntax to choose one of `read-all` or `write-all` access for all of the available scopes:
```

Similarly, for the earlier example showing all scopes, we should change

```
Available scopes and access values:
```

to

```
Shown below are the available scopes and access values. You can choose an access value as one of `read`, `write`, or `none`. 
```

You, or anyone else, are free to open a PR to fix.

Thanks!

**Comment by codewithdev** [comment]
Would be happy to pick this up. Let me know if you can assign this to me.

**Comment by cmwilson21** [comment]
👋 @codewithdev - Thanks for your interest in this one. We don't assign issues, but feel free to submit a PR!

**Comment by raymank26** [comment]
> Most people should be able to recognize the meaning of the example, but I do agree that for less-experienced people we should be more explicit.

A 10-year experience engineer here and I disagree. The docs explicitly say:

> You can use the following syntax to define read or write access for all of the available scopes:
> ```permissions: read-all|write-all```

If I see such a statement I presume that copy-pasting should work. I suggest rephrasing this section and providing clear examples instead.

**Comment by Adrian8115** [comment]
permissions: read-all|write-all
doesn't work?!

what todo?
