### ISSUE TITLE
Fix: Typo on GraphQL

### ISSUE THREAD

**Issue by alexis-opolka** [github/docs#22790]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[https://docs.github.com/en/graphql/guides/forming-calls-with-graphql](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql)

### What part(s) of the article would you like to see updated?

It's a simple typo on GraphQL, it's written `GrpahQL` but should be `GraphQL`.

### Additional information

A commit has been made on my fork, ready to be in a pull request.: [the commit](https://github.com/alexis-opolka/docs/commit/5aef58c58ea96dd44b362500e98c2c873b45ddf0)

**Comment by cmwilson21** [comment]
@alexis-opolka Great catch! Thanks for opening an issue! ✨ 

If you have a fix already, feel free to submit a PR with it. Then we can review it and merge it ⚡

**Comment by alexis-opolka** [comment]
PR submitted:  #22792 ^^
