### ISSUE TITLE
Example code should properly quote variables

### ISSUE THREAD

**Issue by ashirazi2** [github/docs#22794]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

### What part(s) of the article would you like to see updated?

Example bash shell code variables $GITHUB_OUTPUT an $GITHUB_ENV.

### Additional information

Reference: https://www.shellcheck.net/wiki/SC2086

**Comment by cmwilson21** [comment]
Thanks for opening an issue!

**Comment by 06121992** [comment]
R

**Comment by Thana9009** [comment]
ในวันที่ พฤ. 6 เม.ย. 2023 13:37 น. 06121992 ***@***.***>
เขียนว

**Comment by Smallibk** [comment]
On Thu, 9 Apr 2023 at 6 : 40 AM 06121992 ***@***.***> wrote:
***@***.***
