### ISSUE TITLE
Unclear directions for locating .bashrc or .profile file in Windows

### ISSUE THREAD

**Issue by victoremeka** [github/docs#22819]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-git-for-windows

### What part(s) of the article would you like to see updated?

The Windows portion of the article is unclear about where to find the `\.bashrc` or `\.profile` file in the Git shell.

Currently, the sentence reads as:

> You can run ssh-agent automatically when you open bash or Git shell. Copy the following lines and paste them into your ~/.profile or ~/.bashrc file in Git shell:

This may be unclear to someone without a bash/linux - based background.

Expected outcome: Add directions to locating the `\.bashrc` or `\.profile` for Windows users.

**Comment by cmwilson21** [comment]
@victoremeka Thank you for opening an issue and linking it to your PR! ✨

**Comment by cmwilson21** [comment]
Closing per comment [here](https://github.com/github/docs/pull/22822#issuecomment-1453608575) 💛
