### ISSUE TITLE
Add custom field support info for url parameters in issue creation

### ISSUE THREAD

**Issue by amandamartin-dev** [github/docs#22835]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query

### What part(s) of the article would you like to see updated?

This article does not mention that query parameters will work on custom fields in issue templates, however, in testing I found that this is possible.

This issue is requesting to add that query parameters will work with custom fields in issue templates and limitations (if any)

This supports the use case of auto-populating data from external sources to custom fields in issue tempaltes.

Example template with test parameter filling a custom field for reference: https://github.com/EddieHubCommunity/LinkFree/issues/new?assignees=&labels=testimonial&template=testimonial.yml&title=New+Testimonial&name=Amanda+Test

**Comment by cmwilson21** [comment]
@amandamartin-dev Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

We appreciate your patience during the holiday season 💖

**Comment by Wulan-hub** [comment]
Buka

**Comment by cowley86-cmd** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query
> 
> ### What part(s) of the article would you like to see updated?
> This article does not mention that query parameters will work on custom fields in issue templates, however, in testing I found that this is possible.
> 
> This issue is requesting to add that query parameters will work with custom fields in issue templates and limitations (if any)
> 
> This supports the use case of auto-populating data from external sources to custom fields in issue tempaltes.
> 
> Example template with test parameter filling a custom field for reference: https://github.com/EddieHubCommunity/LinkFree/issues/new?assignees=&labels=testimonial&template=testimonial.yml&title=New+Testimonial&name=Amanda+Test
> 
> ### Additional information
> _No response_

**Comment by sophietheking** [comment]
Thanks @amandamartin-dev 💖, we should add a sentence in the "Creating an issue from a URL query" section, clarifying that query parameters will work with custom fields in issue templates. You or anyone else can open a PR with a fix 🔨.

**Comment by amandamartin-dev** [comment]
> You or anyone else can open a PR with a fix 🔨.

I'll go ahead and do that later today.  Feel free to assign me if you think it's needed! Thanks for reviewing

**Comment by ifteneiftene** [comment]
bien ok
