### ISSUE TITLE
proposal: remove all test pass checkbox from PR template

### ISSUE THREAD

**Issue by HonkingGoose** [github/docs#2284]
### What article on docs.github.com is affected?

This affects the repository `github/docs`.

I want to propose a change to the pull request template at: https://github.com/github/docs/blob/main/.github/PULL_REQUEST_TEMPLATE.md

### What part(s) of the article would you like to see updated?

Is there a reason for having this line in the PR template?

```markdown
- [ ] All of the tests are passing.
```

I don't see why a contributor is supposed to tick off a box that says: "All tests are passing", when we have a lot of good CI running automatically on the PR.

I propose we remove the line, and instead use branch protection rules to enforce that all tests pass on incoming PRs.
This way we're not spending a contributors time to watch over the test progress, and tick off the box if the tests pass. 

If the tests fail you get a notice of that trough the GitHub notifications system anyways. If you really want a message to remind contributors that all tests must pass, maybe put it in a Markdown comment instead?

**Comment by janiceilene** [comment]
Thanks for the suggestion and opening an issue @HonkingGoose! That perspective absolutely makes sense and you're welcome to open a PR to remove that line from the PR template 💖 I'll open a PR internally to remind our team to double check that tests are passing when they're merging a PR instead ⚡

**Comment by HonkingGoose** [comment]
Thanks for the permission to remove the line. 🎉

PR #2291 will close this issue. 😄
