### ISSUE TITLE
Missing `{% raw %}` tags on caching page

### ISSUE THREAD

**Issue by anno1985** [github/docs#22864]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

### What part(s) of the article would you like to see updated?

markdown is rendered incorrectly due to missing raw tags - in particular, GitHub Action expressions are not rendered: instead of `${{ ... }}` there's only `$` displayed in the last example on that page - likely because LiquidJS templating engine thinks those are output tags that it can't parse.

### Additional information

PR to follow

**Comment by cmwilson21** [comment]
@anno1985 Thank you for opening an issue and linking it to your PR! ✨

**Comment by Danday999** [comment]
- -
