### ISSUE TITLE
Typo fix in Differences between GitHub apps and OAuth apps

### ISSUE THREAD

**Issue by janiceilene** [github/docs#2287]
In the section "Differences between GitHub Apps and OAuth Apps", under the "Webhooks" chart, it states "they needs to", which should be "they need to".

URL:

https://docs.github.com/en/free-pro-team@latest/developers/apps/differences-between-github-apps-and-oauth-apps#who-can-install-github-apps-and-authorize-oauth-apps

Screenshot:

![image](https://user-images.githubusercontent.com/40512107/97114263-27f21400-16b5-11eb-97be-843173b8b611.png)

**Comment by gsonly** [comment]
I've made a PR to fix this.
