### ISSUE TITLE
Typo in Authorizing OAuth apps

### ISSUE THREAD

**Issue by janiceilene** [github/docs#2288]
There is a duplicated set of words in the section "**Authorizing OAuth Apps**". The words "There is a" have been typed twice. They should be stated just once.

URL:

https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#device-flow

Path for finding the file at the Spanish LATAM localization project:

main/content/developers/apps/authorizing-oauth-apps.md	

Screenshot:

![image](https://user-images.githubusercontent.com/40512107/97119486-1ec56f00-16d6-11eb-9b4a-a3d99131d257.png)

**Comment by Deepak-suresh14** [comment]
can I fix this ?

**Comment by mrsadiya** [comment]
Gboard ক্লিপবোর্ডে স্বাগতম, আপনার কপি করা যেকোনও টেক্সট এখানে সেভ করা হবে।

**Comment by mrsadiya** [comment]
Gboard ক্লিপবোর্ডে স্বাগতম, আপনার কপি করা যেকোনও টেক্সট এখানে সেভ করা হবে।

**Comment by Deepak-suresh14** [comment]
I have created a pull request please check

**Comment by TheOtterlord** [comment]
I think this issue can be closed now. The website is updated 🎉

**Comment by janiceilene** [comment]
Thanks for letting us know @TheOtterlord!
