### ISSUE TITLE
There is no country Brazil in authentication SMS

### ISSUE THREAD

**Issue by JohnatanLicar** [github/docs#22898]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Add the code +55 (Brazil) to the authentication SMS list](https://github.com/settings/two_factor_authentication/setup/intro)

### What part(s) of the article would you like to see updated?

Country code, where there is no code BRAZIL +55

### Additional information

Add the code +55 (Brazil) to the authentication SMS list

**Comment by cmwilson21** [comment]
Thanks for starting an issue! We’re only able to offer SMS authentication in countries where our SMS providers can guarantee a high deliverability rate. I’m sorry to say their service is not reliable enough in Brazil at this point in time, so we’re unable to offer SMS authentication as an option for users in Brazil.

While we won’t be able to offer SMS as an option for you, you might consider enabling two-factor authentication using a TOTP application. If you’re interested, we have a guide that will walk you through setting this up:
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-totp-mobile-app

With 2FA enabled, be sure to set up some of these additional fallback recovery methods as well:
- **Download your recovery codes.** This is by far the best way to make sure you don’t get locked out of your account.
- **Add a security key.** You’ll still have access to your account if you have a FIDO U2F security key added to your account
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication-recovery-methods

I apologize for the inconvenience, and rest assured, we’re actively working to improve the situation.
