### ISSUE TITLE
Typo in Finding and customizing actions

### ISSUE THREAD

**Issue by janiceilene** [github/docs#2290]
There is a sentence that has odd wording in the file "**main/content/actions/learn-github-actions/finding-and-customizing-actions.md**"

Link to the GitHub Help Documents where this can be found:

https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/finding-and-customizing-actions#using-release-management-for-your-custom-actions

Screenshot:

![image](https://user-images.githubusercontent.com/40512107/97132204-d7f26c00-170b-11eb-919a-7e28d840bc35.png)

Suggested:

"[...] that the action will always include the latest updates [...]"

**Comment by gsonly** [comment]
I would like to help with this issue and make a PR

**Comment by janiceilene** [comment]
@gsonly That sounds great ✨ You're welcome to open a PR!

**Comment by gsonly** [comment]
I think its already fixed

**Comment by martindes01** [comment]
Hi all,

The typo was corrected from "use include" to "use" by commit https://github.com/github/docs/commit/09aaf2cf9376d736a7a662f311f72970cdcac5f7, which wasn't linked to this issue.

Although PR https://github.com/github/docs/pull/2320 changes this to "include" as suggested, I feel the sentence could be rephrased to better convey its meaning, as well as to follow the style guides more closely.

I might open a pull request if I come up with a nicer way to phrase this.

**Comment by janiceilene** [comment]
Thanks for the clarification @martindes01! I transferred this issue from an internal report and didn't realize it had been fixed already.

**Comment by DozerKatDC10** [comment]
Janice Hi hope i didn't mess this up Thanks Mike
