### ISSUE TITLE
GitHub Advanced Security Trophy Not Reflected Under https://learn.microsoft.com/ 

### ISSUE THREAD

**Issue by vinod-soni-microsoft** [github/docs#22904]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### Pre-requisites

- [X] My application to the GitHub Technology Partner Program is approved.

### Tasks

- [X] MUST follow our [general contributing guidelines](CONTRIBUTING.md) for voice and markup format.
- [X] MUST emphasize how the third-party product works with GitHub.
- [X] MUST be written in Markdown format, using [one of the templates provided](contributing/github-partners/README.md#templates).
- [X] MUST include the name and URL of the GitHub technology partner responsible for maintenance of the documentation being contributed. This should be added via the `contributor.name` and `contributor.URL` properties in the template's YAML frontmatter.
- [X] MUST be proposed via a pull request to this repo following [the GitHub Flow](https://guides.github.com/introduction/flow/).
- [X] MUST be located in the root of [the `content` folder](content). Your filename MUST match the GitHub technology partner name, and use the `.md` file extension.

### Pull Request

- [X] MUST reference this issue, e.g. via `closes [this issue number]`.
- [X] MUST pass the automated CI checks.
- [X] MUST include links to supporting material demonstrating the functionality being documented (this can be a link to a public GitHub repo, _or_ a video / screencast walkthrough).

**Comment by vinod-soni-microsoft** [comment]
Dear Team,

GitHub Advanced Security Trophy Not Reflected Under https://learn.microsoft.com/ even I have completed all the modules listed in learning path. I have performed the exercise and completed knowledge check of each module.  Check the screenshot for more details. 

![Github Issue2-Screenshot 2022-12-30 094357](https://user-images.githubusercontent.com/117770765/210082653-f95d70c8-2a53-4b10-9bfc-9029022870d6.png)
![Github Issue-Screenshot 2022-12-30 094357](https://user-images.githubusercontent.com/117770765/210082656-1d55b246-3f58-4b1f-a876-313bdc28540e.png)

**Comment by cmwilson21** [comment]
👋 @vinod-soni-microsoft - This appears to be related to Microsoft Learn and not something we cover under the Docs. If you have any suggestions for GitHub Docs, please feel free to open an issue ✨ 

I'm going to go ahead and close this issue now 💛

**Comment by kikalok** [comment]
No what could mean close this been happening  over 2 years no
