### ISSUE TITLE
Add Staff Badge to #displaying-badges-on-your-profile

### ISSUE THREAD

**Issue by WebSnke** [github/docs#22965]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile#displaying-badges-on-your-profile

### What part(s) of the article would you like to see updated?

- Add the "STAFF" badge to possible badges on a profile.

**Comment by cmwilson21** [comment]
@WebSnke - Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by sophietheking** [comment]
@WebSnke Thank you so much for opening this issue ✨ We're not interested in making this change and I'm going to close this issue. We appreciate your interest in improving the GitHub Docs 💖

Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md) to learn how to contribute in this repo. You can open a discussion if you have any questions or check out issues with the help wanted label. ✨
