### ISSUE TITLE
Github Actions `format(...)` Expression Examples are Inconsistent

### ISSUE THREAD

**Issue by norwd** [github/docs#22991]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#format

### What part(s) of the article would you like to see updated?

The two examples of how to use `${{ format(...) }}` are inconsistent, one is a simple inline code block while the other has full syntax highlighting. See screenshot.

![image](https://user-images.githubusercontent.com/106889957/210654864-c3cfe3ee-2382-4145-94fb-39c653ff1ad6.png)

**Comment by cmwilson21** [comment]
@norwd Thank you for opening an issue and linking it to your PR! ✨
