### ISSUE TITLE
Some translated documentaion break code blocks

### ISSUE THREAD

**Issue by fnordfish** [github/docs#23003]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/de/authentication/managing-commit-signature-verification/associating-an-email-with-your-gpg-key

Has a literal ` ```shell{:copy} ` block, probably due to missing new lines.

I would have liked to use the "Make a contribution" button, but that's missing on translated pages.

### What part(s) of the article would you like to see updated?

Fix the markdown in the translated version.

### Additional information

Same issue here: https://docs.github.com/de/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

**Comment by cmwilson21** [comment]
@fnordfish Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
👋 I've reported this to the team. We use an internal automated solution for translations so will be making a ticket to get this fixed ⚒️ 

Since we'll be tracking this internally, I'm going to go ahead and close this issue 💛 Thanks again for reporting!
