### ISSUE TITLE
viewing-and-updating-dependabot-alerts markdown format error in Chinese translation version

### ISSUE THREAD

**Issue by z0z0r4** [github/docs#23038]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/zh/code-security/dependabot/dependabot-alerts/viewing-and-updating-dependabot-alerts#supported-ecosystems-and-manifests-for-dependency-scope
code-security/dependabot/dependabot-alerts/viewing-and-updating-dependabot-alerts

### What part(s) of the article would you like to see updated?

the table in viewing-and-updating-dependabot-alerts
```

| 语言 | 生态系统 | 清单文件 | 支持的依赖项范围 | |:---|:---:|:---:|:---| | Dart | pub | pubspec.yaml | ✔ | | Dart | pub | pubspec.lock | ✔ | | Go | Go 模块 | go.mod | 否，默认为运行时 | | Go | Go 模块 | go.sum | 否，默认为运行时 | | Java | Maven | pom.xml | ✔ test 映射到开发，否则范围默认为运行时 | | JavaScript | npm | package.json | ✔ | | JavaScript | npm | package-lock.json | ✔ | | JavaScript | yarn v1 | yarn.lock | 否，默认为运行时 | | PHP | Composer | composer.json | ✔ | | PHP | Composer | composer.lock | ✔ | | Python | Poetry | poetry.lock | ✔ | | Python | Poetry | pyproject.toml | ✔ | | Python | pip | requirements.txt | ✔ 如果文件名包含 test 或 dev，范围则为开发，否则为运行时 | | Python | pip | pipfile.lock | ✔ | | Python | pip | pipfile | ✔ | | Ruby | RubyGems | Gemfile | ✔ | | Ruby | RubyGems | Gemfile.lock | 否，默认为运行时 | | Rust | Cargo | Cargo.toml | ✔ | | Rust | Cargo | Cargo.lock | 否，默认为运行时 | | YAML | GitHub Actions | - | 否，默认为运行时 | | .NET (C#, F#, VB, etc.) | NuGet | .csproj / .vbproj .vcxproj / .fsproj | 否，默认为运行时 | | .NET | NuGet | packages.config | 否，默认为运行时 | | .NET | NuGet | .nuspec | ✔ 当标记 != 运行时时 |

```

### Additional information

the format of that table in English translation version is right...
plz preview what you write before public

**Comment by cmwilson21** [comment]
@z0z0r4 Thanks for opening an issue. We use an internal automated solution for translations but sometimes the markdown still breaks. I'll flag this for our team to check out. Thanks for reporting it! ✨

**Comment by cmwilson21** [comment]
👋 I've reported this to the team. We use an internal automated solution for translations so will be making a ticket to get this fixed ⚒️ 

Since we'll be tracking this internally, I'm going to go ahead and close this issue 💛 Thanks again for reporting!
