### ISSUE TITLE
public action example main.yml needs correction.

### ISSUE THREAD

**Issue by shailesh-vaidya** [github/docs#23055]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#example-using-a-public-action

The `.github/workflows/main.yml file`  Action version is not mentioned. If someone copy-pastes this in their own repository it throws an error. 

 `uses: actions/hello-world-docker-actionv2`

Should be 

 `uses: actions/hello-world-docker-action@v2`

it's mentioned to use tag name v1 in the above steps. We should use the same in the next steps also.

**Comment by cmwilson21** [comment]
@shailesh-vaidya Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
