### ISSUE TITLE
Some docs makes reference to non-existent `packages:read` permission

### ISSUE THREAD

**Issue by heaths** [github/docs#23127]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Several, since it's in shared data, including but not limited to:

* https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages
* https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
* https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

### What part(s) of the article would you like to see updated?

```diff
To authenticate to a GitHub Packages registry within a GitHub Actions workflow, you can use:

* `GITHUB_TOKEN` to publish packages associated with the workflow repository.
-* a personal access token (classic) with at least `packages:read` scope to install packages associated with other private repositories (which `GITHUB_TOKEN` can't access).
+* a personal access token (classic) with at least `read:packages` scope to install packages associated with other private repositories (which `GITHUB_TOKEN` can't access).
```

### Additional information

Not only does this permission as written not work e.g., `gh auth refresh -s packages:read`, but your [docs about permissions](https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages) mention the correct permission, `read:packages`.

I already have a PR for this, but your PR template mentions that opening a bug will improve the chances of getting it merged.

**Comment by cmwilson21** [comment]
@heaths Thank you for opening an issue and linking it to your PR! ✨ 

It definitely helps us while reviewing!
