### ISSUE TITLE
Typo: regex's should be surrounded by forward slashes, not backslashes

### ISSUE THREAD

**Issue by atenni** [github/docs#23123]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax

### What part(s) of the article would you like to see updated?

Regular expressions should be surrounded by _forward slashes_, but this doc referred to them as both "forward slashes" and "backslashes" in different places.

I'll submit a PR updating "backslashes" -> "forward slashes".

**Comment by Itsacad** [comment]
You make for some imagelation or u did real thinks getting send me full more detail on my chat page fb.
