### ISSUE TITLE
Example action seems to be referring to an older version of Azure/static-web-apps-deploy

### ISSUE THREAD

**Issue by oms5** [github/docs#23126]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-to-azure-static-web-app.md

### What part(s) of the article would you like to see updated?

In the example the 

Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9 action is referencing an old version that no longer uses `app_artifact_location` but `app_location` as in the [Microsoft docs](https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#build-configuration) for Azure/static-web-apps-deploy@v1. This initial misled us to use app_artifact_location.

### Content plan [here](https://github.com/github/docs/issues/23126#issuecomment-1421713022)

**Comment by cmwilson21** [comment]
@oms5 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! You or anyone else is welcome to open a PR to update this example workflow to use a newer version of the Azure/static-web-apps-deploy action. 

To whoever picks this up: When you submit your PR, if you have a publicly available workflow run log that demonstrates that the new example workflow runs without error, please link it in your PR. That will help us provide a faster review.
