### ISSUE TITLE
SSH doesn't use passphrase stored in keychain on MacOS Monterey, after following directions

### ISSUE THREAD

**Issue by oC-n** [github/docs#23159]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

### [Adding your SSH key to the ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent)
After following the directions given in this section, to store the passphrase in keychain, I continued to be prompted for the passphrase on every `git push`. I am using MacOS 12.6.2.

After reading some forums on related issues on recent MacOS versions, I found that copying the command given at step 3(`ssh-add --apple-use-keychain ~/.ssh/id_{% ifversion ghae %}rsa{% else %}ed25519{% endif %}`) into `~/.zshrc` gave correct behaviour.

Use case: Mac users encountering problems with SSH connections using a stored passphrase.

Expected outcome: a note to suggest a fix to this problem, if encountered.

I suggest adding to the note at step 3 that this extra step may be required, e.g.:

> If you continue to be prompted for your passphrase, you may need to add the above command to your `~/.zshrc` file (or `.bashrc` for bash).

### Additional information

`~/.ssh/config` is as per the instructions given, with no other contents.

**Comment by cmwilson21** [comment]
@oC-n Thanks for opening an issue and providing all the helpful context ✨ 

I'll get this triaged for review! :zap:

**Comment by hagould** [comment]
This is a safe/sane adjustment to make to the macOS docs 👍

**Comment by cmwilson21** [comment]
@oC-n Thanks for raising this issue! You, or anyone else, are welcome to submit a PR with this fix ✨

**Comment by oC-n** [comment]
Thanks Anne-Marie, and apologies for not getting the PR sorted myself - a
bit overwhelmed in a new job!

**Comment by Ngocnu29** [comment]
https://33win00.com/
