### ISSUE TITLE
Add Spellcheck in build process (and fix spelling issues)

### ISSUE THREAD

**Issue by SeanKilleen** [github/docs#23188]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The overall GitHub docs site; no one particular article

### What changes are you suggesting?

* Fix spelling errors that currently exist
* Introduce spellcheck for every docs PR build

### Additional information

This issue is to ensure there's an associated issue for the PR I'm proposing.

**Comment by cmwilson21** [comment]
@SeanKilleen - Thank you for opening an issue and linking it to your PR! ✨

**Comment by SeanKilleen** [comment]
Adding a comment to bump this as the PR and associated work is still in active development and discussion is happening there.

**Comment by SeanKilleen** [comment]
Glad that during the course of this issue we were able to make 80 changes to the docs. I hope they prove helpful!
