### ISSUE TITLE
Empty repo clone - missing information

### ISSUE THREAD

**Issue by Abhijit2505** [github/docs#232]
### What article on docs.github.com is affected?
There is a small bug in cloning an empty repository to the local machine, that has not been included in GitHub documentations.

### What is the bug?
Steps to check,

* Create an empty repository in Github.
* Clone it into the local system.
* Add some files to it.
* Open git bash and type `git add . ` then `git commit -m`
* Finally `git push origin main`

It raises an error because the `main` is not working in case of cloning an empty repo.
If instead of `git push origin main`, you try `git push origin master`, it will work.

The bug is - remove the `master` word and replace it with `main`, as the `master` keyword has been removed officially while creating an empty repo.

### Additional information
We may have two solutions,
* Adding this to the documentation page
* Solving the bug

----

After the discussions below, we realized that the docs don't currently remind you to check what the default branch name is when you clone a repository. You need this information to know where to push the first files. The content design plan below is designed to address this omission.

### Content design plan

Proposed content design plan to address this issue.

Topics to update:

[Cloning an empty repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository) - in the section "Cloning an empty repository":

- Add a new step 2, after the first step (`{% data reusables.repositories.navigate-to-repo %}`) to note the name of the default branch for the repository, shown on the branch selector on the left of the screen.
- Include a screenshot with the branch selector highlighted.

I've attached a screenshot with the branch selector highlighted. This should be added to the `/assets/images/help/repository/` directory with a suitable name, for example: `branch-selector.png`.
![branch-selector](https://user-images.githubusercontent.com/1877141/106131173-422b0a80-615a-11eb-80cc-1fdf80b35203.png)

**Comment by thinkverse** [comment]
Is this perhaps a misunderstanding of how git works? 🤔&nbsp; When git clones an empty repository there isn't a branch added because there are no files that are tracked.

For instance, when I create a new empty repository on GitHub and clone it. I don't have a local branch, only when I start tracking files does it create the branch. And that branch will be named whatever the `default` is set to.

I believe the default for git is still `master` but that can be changed by setting the git `init.defaultBranch` config key as of git v2.28. And you cannot add files from one branch directly into another. So if your system names the branch `master` and you try to `push origin main`, yes it's going to throw and error. But I don't think that would be a bug.

**Comment by Abhijit2505** [comment]
> Is this perhaps a misunderstanding of how git works? 🤔  When git clones an empty repository there isn't a branch added because there are no files that are tracked.
> 
> For instance, when I create a new empty repository on GitHub and clone it. I don't have a local branch, only when I start tracking files does it create the branch. And that branch will be named whatever the `default` is set to.
> 
> I believe the default for git is still `master` but that can be changed by setting the git `init.defaultBranch` config key as of git v2.28. And you cannot add files from one branch directly into another. So if your system names the branch `master` and you try to `push origin main`. Yeah, it's going to throw an error but, I don't think that would be a bug.

Maybe you are correct!
I believe the default is still `master`.

It is not a misunderstanding of how git works, but it is probably a confusion.

**Comment by janiceilene** [comment]
👋 @Abhijit2505 Is there a particular article you'd like to see updated?

**Comment by Abhijit2505** [comment]
@janiceilene I would really like this thing to be added somewhere inside the docs as a snippet.

**Comment by janiceilene** [comment]
That's definitely something we can consider! Let us know if you find an existing article that makes sense for this update and we can look into it 💛

**Comment by felicitymay** [comment]
Hi @Abhijit2505 - thanks for raising this issue. I've been looking in docs.github.com to see if I could work out which page you were using when you ran into this problem.

I can't find a page that includes all the steps from your description, but wonder if you started with [Cloning an empty repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository#cloning-an-empty-repository) and then, after following that procedure, continued by adding files locally.

I think that the best answer here might be to add an extra step to each of the procedures on the page, after _"On GitHub, navigate to the main page of the repository."_. The new step could remind people to look at the branch selector and take note of the default branch name for the repository. Do you think this would have helped you?

**Comment by felicitymay** [comment]
### Content design plan

Proposed content design plan to address this issue.

Topics to update:

[Cloning an empty repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository) - in the section "Cloning an empty repository":

- Add a new step 2, after the first step (`{% data reusables.repositories.navigate-to-repo %}`) to note the name of the default branch for the repository, shown on the branch selector on the left of the screen.
- Include a screenshot with the branch selector highlighted.

**Comment by felicitymay** [comment]
I'm attaching a screenshot with the branch selector highlighted. This should be added to the `/assets/images/help/repository/` directory with a suitable name, for example: `branch-selector.png`.
![branch-selector](https://user-images.githubusercontent.com/1877141/106131173-422b0a80-615a-11eb-80cc-1fdf80b35203.png)

**Comment by tsadarsh** [comment]
> That's definitely something we can consider! Let us know if you find an existing article that makes sense for this update and we can look into it yellow_heart

Can this update be referenced in this article: [Adding an existing project to github using the command line](https://docs.github.com/en/github/importing-your-projects-to-github/adding-an-existing-project-to-github-using-the-command-line) also.

Following **step 4**: `git init -b main` I get:
> error: unknown switch `b'

So, I just did `git init` and continued the remaining steps. I had to `git push origin master` in **step 9**.

**Comment by thinkverse** [comment]
> Following **step 4**: `git init -b main` I get:
> 
> > error: unknown switch `b'

Your local git version might be out-of-date then, the `-b` flag was added in git 2.28. The current latest version at the time of writing is 2.30.2.

**Comment by tsadarsh** [comment]
> > Following **step 4**: `git init -b main` I get:
> > 
> > > error: unknown switch `b'
> 
> Your local git version might be out-of-date then, the `-b` flag was added in git 2.28. The current latest version at the time of writing is 2.30.2.
> 

Yes, my git version is out-of-date. Thanks for the information 😀

**Comment by fluesvamp** [comment]
> Steps to check,
> - Create an empty repository in Github.
> - Clone it into the local system.
> - Add some files to it.
> - Open git bash and type `git add .` then `git commit -m`
> - Finally `git push origin main`

git commit -m "First commit"
git branch -M main
git push -u origin main

**Comment by Abhijit2505** [comment]
@felicitymay so my issue is accepted right ?

**Comment by felicitymay** [comment]
@Abhijit2505 - yes, your issue is accepted. I wrote a content design plan for the docs update based on my best guess for the article that needed to be updated and on what might have helped you out. See https://github.com/github/docs/issues/232#issuecomment-762785984 and the next two comments.

It would be great if you could look at the plan. Do you think this change would help you? If not, I'm very happy to discuss the suggested plan and update it.

**Comment by Abhijit2505** [comment]
@felicitymay, no I am very happy that after using GitHub continuously for more than a year, I am able to contribute a tiny part for the development of our ecosystem and this day to day used application.

Your plan is good ✔✔

**Comment by felicitymay** [comment]
I've updated the issue summary with details of the content design plan to update the docs so it's clearer to anyone looking at this issue what changes are needed.

**Comment by jules-p** [comment]
Upon further investigation, the website appears to be functioning correctly and the UI seen at e.g. `github.com/USERNAME/EMPTY-REPOSITORY` is providing accurate instructions for adding files to an empty repository and pushing them to GitHub. 

Keep in mind that an empty repository does not have a set default branch until a file is added to it. When a file is added the default branch will be whatever you set it to, either with `git branch -M [BRANCH NAME]` through the command line, or, if adding a file through the UI, whatever your default branch name has been set to in https://github.com/settings/repositories.

The relevant documentation is also correct and up-to-date, so no changes will be made at this time, but thank you again for reaching out 💖 ✨ . If you have any further questions, please let us know 🙏🏻
