### ISSUE TITLE
Improve Workflow Reuse Docs around Passing Values

### ISSUE THREAD

**Issue by feanil** [github/docs#23207]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows

### What part(s) of the article would you like to see updated?

The example for how values are passed.  It looks like maybe the wrong value name is used in the calling workflow.

**Comment by cmwilson21** [comment]
@feanil Thank you for opening an issue and linking it to your PR! ✨

**Comment by lucascosti** [comment]
Docs are correct, explained in https://github.com/github/docs/pull/23208#issuecomment-1399869120 🙇‍♂️
