### ISSUE TITLE
Remove Beta language for Dormancy Report

### ISSUE THREAD

**Issue by adamrr724** [github/docs#23275]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/user-management/managing-users-in-your-enterprise/managing-dormant-users#downloading-the-dormant-users-report-from-your-enterprise-account

### What part(s) of the article would you like to see updated?

Remove (beta) from language in Part 4 of this walkthrough.

### Additional information

Dormancy Report is no longer in Beta, and is generally available: https://github.blog/changelog/2022-12-14-dormant-users-report-for-enterprise-accounts/

**Comment by cmwilson21** [comment]
Closing it per #23276
