### ISSUE TITLE
Add information about outside collaborators on Dormant Users report

### ISSUE THREAD

**Issue by adamrr724** [github/docs#23286]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Managing Dormant Users documentation](https://docs.github.com/en/enterprise-cloud@latest/admin/user-management/managing-users-in-your-enterprise/managing-dormant-users)

### What part(s) of the article would you like to see updated?

Recently Outside Collaborators were added to the dormant users report via this tracked ticket: https://github.com/github/github/pull/239719

But there is no mention of outside collaborators on the report in the [Managing Dormant Users documentation](https://docs.github.com/en/enterprise-cloud@latest/admin/user-management/managing-users-in-your-enterprise/managing-dormant-users)

We should add documentation that mentions outside collaborators are included in the results pulled in the dormant users report. 

### Additional information

N/A

**Comment by cmwilson21** [comment]
👋 @adamrr724 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @adamrr724, we should add a sentence in the "About dormant users" section, clarifying that both members and outside collaborators will be included in the report. You or anyone else is welcome to open a PR doing so! ⚡

**Comment by adamrr724** [comment]
Hi there, I opened this PR for this ticket.  https://github.com/github/docs/pull/23330

Thanks!

**Comment by lecoursen** [comment]
This was closed by https://github.com/github/docs/pull/23330!
