### ISSUE TITLE
What happened to the `Allow specified actors to bypass pull request requirements` option?

### ISSUE THREAD

**Issue by marcofugaro** [github/docs#23295]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/

### What part(s) of the article would you like to see updated?

What happened to the "Allow specified actors to bypass pull request requirements" option mentioned in the article? Can't find it in the settings.
It would be really useful for my usecase.

### Additional information

Context: I am trying to make a github action that updates the version of a package.json and pushes the changes to the `dev` branch via a bot (I am using a github application via a [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)). 

However, the `dev` branch is protected so people won't push directly to it but rather make PRs.
I want the bot to bypass that rule and push directly to the branch. However I don't find that option mentioned in the article.

**Comment by cmwilson21** [comment]
@marcofugaro Thanks for opening an issue! The article referenced above is a GitHub blog post announcing the feature. We don't maintain the blog from the Docs team, but I've found this article in the Docs that may be useful - "[Creating a branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule)." 👍 

If you are still having trouble with this, it may be best be handled by our awesome [support team](https://support.github.com/request). Please reach out to them. ✨ 

I'm going to go ahead and close this issue for now, but if there's anything in the documents that you have suggestions for updating, please feel free to open another one. 💛
