### ISSUE TITLE
Documentation for jobs matrix strategy seems incorrect.

### ISSUE THREAD

**Issue by techupskills** [github/docs#23322]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations

### What part(s) of the article would you like to see updated?

The text notes that:

“For example, this matrix:

strategy:

  matrix:

    fruit: [apple, pear]

    animal: [cat, dog]

    include:

      - color: green

      - color: pink

        animal: cat

      - fruit: apple

        shape: circle

      - fruit: banana

      - fruit: banana

        animal: cat

will result in six jobs with the following matrix combinations:

·         {fruit: apple, animal: cat, color: pink, shape: circle}

·         {fruit: apple, animal: dog, color: green, shape: circle}

·         {fruit: pear, animal: cat, color: pink}

·         {fruit: pear, animal: dog, color: green}

·         {fruit: banana}

·         {fruit: banana, animal: cat}”

But when I run this through a workflow like this:

 

name: Test matrix as doc'd
 
on:
  push:
  
 
jobs: 
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
 
    steps:
      - run: | 
          echo ${{ matrix.fruit }}, ${{ matrix.animal }}, ${{ matrix.color }}, ${{ matrix.shape }}
 

I actually get 6 different jobs… with only the main two variables.  See output in attached screenshot.
![image001](https://user-images.githubusercontent.com/82771267/213447356-e17eb04d-9012-4929-89a5-7ed96aa8e0cd.png)

### Additional information

Was trying this out for the new GitHub Actions book working on with GitHub and O'Reilly, so would appreciate any clarity that I can take back and put in the book. Thanks.

**Comment by Mohammedalanizi92** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
> 
> ### What part(s) of the article would you like to see updated?
> The text notes that:
> 
> “For example, this matrix:
> 
> strategy:
> 
> matrix:
> 
> ```
> fruit: [apple, pear]
> 
> animal: [cat, dog]
> 
> include:
> 
>   - color: green
> 
>   - color: pink
> 
>     animal: cat
> 
>   - fruit: apple
> 
>     shape: circle
> 
>   - fruit: banana
> 
>   - fruit: banana
> 
>     animal: cat
> ```
> 
> will result in six jobs with the following matrix combinations:
> 
> · {fruit: apple, animal: cat, color: pink, shape: circle}
> 
> · {fruit: apple, animal: dog, color: green, shape: circle}
> 
> · {fruit: pear, animal: cat, color: pink}
> 
> · {fruit: pear, animal: dog, color: green}
> 
> · {fruit: banana}
> 
> · {fruit: banana, animal: cat}”
> 
> But when I run this through a workflow like this:
> 
> name: Test matrix as doc'd
> 
> on: push:
> 
> jobs: test-matrix: runs-on: ubuntu-latest strategy: matrix: fruit: [apple, pear] animal: [cat, dog] include: - color: green - color: pink animal: cat - fruit: apple shape: circle - fruit: banana - fruit: banana animal: cat
> 
> ```
> steps:
>   - run: | 
>       echo ${{ matrix.fruit }}, ${{ matrix.animal }}, ${{ matrix.color }}, ${{ matrix.shape }}
> ```
> 
> I actually get 6 different jobs… with only the main two variables. See output in attached screenshot. ![image001](https://user-images.githubusercontent.com/82771267/213447356-e17eb04d-9012-4929-89a5-7ed96aa8e0cd.png)
> 
> ### Additional information
> Was trying this out for the new GitHub Actions book working on with GitHub and O'Reilly, so would appreciate any clarity that I can take back and put in the book. Thanks.

**Comment by Mohammedalanizi92** [comment]
> ### Code of Conduct
> * [x]   I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
> 
> ### What part(s) of the article would you like to see updated?
> The text notes that:
> 
> “For example, this matrix:
> 
> strategy:
> 
> matrix:
> 
> ```
> fruit: [apple, pear]
> 
> animal: [cat, dog]
> 
> include:
> 
>   - color: green
> 
>   - color: pink
> 
>     animal: cat
> 
>   - fruit: apple
> 
>     shape: circle
> 
>   - fruit: banana
> 
>   - fruit: banana
> 
>     animal: cat
> ```
> 
> will result in six jobs with the following matrix combinations:
> 
> · {fruit: apple, animal: cat, color: pink, shape: circle}
> 
> · {fruit: apple, animal: dog, color: green, shape: circle}
> 
> · {fruit: pear, animal: cat, color: pink}
> 
> · {fruit: pear, animal: dog, color: green}
> 
> · {fruit: banana}
> 
> · {fruit: banana, animal: cat}”
> 
> But when I run this through a workflow like this:
> 
> name: Test matrix as doc'd
> 
> on: push:
> 
> jobs: test-matrix: runs-on: ubuntu-latest strategy: matrix: fruit: [apple, pear] animal: [cat, dog] include: - color: green - color: pink animal: cat - fruit: apple shape: circle - fruit: banana - fruit: banana animal: cat
> 
> ```
> steps:
>   - run: | 
>       echo ${{ matrix.fruit }}, ${{ matrix.animal }}, ${{ matrix.color }}, ${{ matrix.shape }}
> ```
> 
> I actually get 6 different jobs… with only the main two variables. See output in attached screenshot. ![image001](https://user-images.githubusercontent.com/82771267/213447356-e17eb04d-9012-4929-89a5-7ed96aa8e0cd.png)
> 
> ### Additional information
> Was trying this out for the new GitHub Actions book working on with GitHub and O'Reilly, so would appreciate any clarity that I can take back and put in the book. Thanks.

**Comment by cmwilson21** [comment]
@techupskills Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Hi @techupskills!

Yes, the documentation looks correct.

Using your workflow, if you click into each job, you can see the output of your `echo` command, including the combination of other matrix values that didn't result produce a job: 

<img width="875" alt="image" src="https://user-images.githubusercontent.com/4434330/213974520-388fe289-351c-4d8b-a847-802a97e85255.png">

The logic for which jobs are generated is explained [in the section that you linked](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations), under the workflow code block:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/4434330/213975202-69e22055-0112-437e-9db9-46b670a945c5.png">

**Comment by brentlaster** [comment]
So your documentation says 


will result in six jobs with the following matrix combinations:

· {fruit: apple, animal: cat, color: pink, shape: circle}

· {fruit: apple, animal: dog, color: green, shape: circle}

· {fruit: pear, animal: cat, color: pink}

· {fruit: pear, animal: dog, color: green}

· {fruit: banana}

· {fruit: banana, animal: cat}”

Those are not the six jobs that were produced.  How is this correct?

**Comment by lucascosti** [comment]
> Those are not the six jobs that were produced. How is this correct?

@brentlaster They are the six jobs that were produced; you can see them [in this test run](https://github.com/lucascosti/actions-public-playground/actions/runs/3983738600/jobs/6829302198).

If you are just looking at the job labels, they only show the values of the original matrix inputs (`fruit` and `animal`), but if you echo the values for each job, then the combinations shown in the docs are the correct matrix combinations.
