### ISSUE TITLE
Runner tool cache is used for pre-installed *and* actively installed tools

### ISSUE THREAD

**Issue by me-and** [github/docs#23338]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context

Specifically, this reusable: https://github.com/github/docs/blob/main/data/reusables/actions/runner-tool-cache-description.md

### What part(s) of the article would you like to see updated?

The documentation for `runner.tool_cache` says that it's used for "preinstalled tools". This is true, but not complete: some actions, including official GitHub actions like [actions/setup-python](https://github.com/actions/setup-python), will install new tools in that directory as well.

I'd like the documentation to better reflect how this directory is intended to be used: should it only be for genuinely preinstalled tools (in which case other GitHub repositories aren't in keeping with this intent), only for GitHub provided tools (so it's appropriate for setup-python to install there, but not, say [cygwin/cygwin-install-action](https://github.com/cygwin/cygwin-install-action)), or is it an appropriate place for any tooling to install itself?

I suspect it's not appropriate to significantly expand the text in the reusable itself, as that's short to fit into a small table cell. I do think it would be useful to have the intent of this directory documented _somewhere_, however; I wasn't able to find out how GitHub intends the directory to be used either in docs.github.com or from digging around some relevant-looking repositories. This sort of information about expected behaviour and best practices is really useful for folk working on published custom actions.

**Comment by cmwilson21** [comment]
@me-and Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
