### ISSUE TITLE
The ignore version specification for Docker is not clear

### ISSUE THREAD

**Issue by dannystaple** [github/docs#23340]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

### What part(s) of the article would you like to see updated?

The article mentions that "If you want to define a range, use the standard pattern for the package manager". However for Dockerfiles and docker containers, there doesn't seemed to be a defined syntax for this, including in the Docker/Dockerfile documentation. After much experimentation, the following was found to work:

```yaml
versions:
          - "~> 1.3.0, < 1.3.6"
```

This should be documented, with a reference to the versioning this uses, or an example like the above.

**Comment by cmwilson21** [comment]
@dannystaple Thank you for opening an issue and linking it to your PR! ✨

**Comment by cmwilson21** [comment]
Closing this issue based on response [here](https://github.com/github/docs/pull/23341#issuecomment-1408619581)
