### ISSUE TITLE
button =>  "change to private" bug

### ISSUE THREAD

**Issue by ramiiil** [github/docs#23377]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

this error is on github.com, I don't know which <issue> to write it here

### What part(s) of the article would you like to see updated?

if I'm also a contributor to github.com :)

### Additional information

![InkedСнимок_LI](https://user-images.githubusercontent.com/89657343/213875437-be527e59-a7c1-436c-a0cd-f9457e5994c3.jpg)

**Comment by cmwilson21** [comment]
@ramiiil Thanks for opening an issue! We don't maintain the .com site, would you mind filing a [bug report](https://support.github.com/contact/bug-report) for this one? 💖

**Comment by ramiiil** [comment]
> @ramiiil Thanks for opening an issue! We don't maintain the .com site, would you mind filing a [bug report](https://support.github.com/contact/bug-report) for this one? 💖
> 
> I'm going to go ahead and close this issue in favor of a bug report 💛


where can i post this error please guide me

**Comment by Clss930** [comment]
Thanks forget

COSME LUIS SOUZA SANTOS

Em seg, 23 de jan de 2023 13:59, Ramil ***@***.***> escreveu:
