### ISSUE TITLE
Fix .md table formatting in about-github-connect.md

### ISSUE THREAD

**Issue by ieshreya** [github/docs#23385]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[about-github-connect.md](https://github.com/github/docs/blob/main/content/admin/configuration/configuring-github-connect/about-github-connect.md) 

### What changes are you suggesting?

Fix markdown table formatting that currently exist in [about-github-connect.md](https://github.com/github/docs/blob/main/content/admin/configuration/configuring-github-connect/about-github-connect.md)

**Comment by cmwilson21** [comment]
@ieshreya Thanks for opening an issue and submitting a PR! ✨
