### ISSUE TITLE
Running job with dependabot/fetch-metadata@v1.1.1 gets warning message

### ISSUE THREAD

**Issue by neko314** [github/docs#23383]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

### What part(s) of the article would you like to see updated?
Parts are `dependabot/fetch-metadata@v1.1.1`.

It's better to modify sample code not to return any warning messages as possible as it can.

GitHub released to duplicate using `set-output` without env vars.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

dependabot/fetch-metadata@v1.1.1 is old version, witch does not yet fix to apply this security fix.
So, I get warning message: `The 'set-output' command is deprecated and will be disabled soon.` when I run a job with this dependabot/fetch-metadata@v1.1.1.

dependabot/fetch-metadata already fixed this warning at v1.3.5 and released it.
issue: https://github.com/dependabot/fetch-metadata/issues/277
release: https://github.com/dependabot/fetch-metadata/releases/tag/v1.3.5
 

I expect to sample code not to get any warning messages as possible as it can.
I suggest to update doc like this

```diff
 steps:
  - name: Dependabot metadata
  id: metadata
-  uses: dependabot/fetch-metadata@v1.1.1
+  uses: dependabot/fetch-metadata@v1
```

**Comment by cmwilson21** [comment]
@neko314 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by am-stead** [comment]
Thank you for this contribution! 💛  
I have approved a [PR](https://github.com/github/docs/pull/23566) to fix this, so I will close this issue out. ✨

**Comment by neko314** [comment]
@cmwilson21 @am-stead 
Thank you✨
