### ISSUE TITLE
Update documentation shown upon creating a new repository, as HTTPS access (aka password authentication) has been shut down

### ISSUE THREAD

**Issue by kirisakow** [github/docs#23403]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

documentation shown upon creating a new repository:

![image](https://user-images.githubusercontent.com/11773604/214084835-a2a11909-abd1-42d4-b0b8-3440b02a20ea.png)

### What part(s) of the article would you like to see updated?

As HTTPS access (aka password authentication) [has been shut down since August 13, 2021](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/), the documentation shown upon creating a new repository should be updated accordingly: there cannot be two options (HTTPS-prefixed remote or SSH-prefixed remote), only one: SSH.

As of today, following the HTTPS option (as shown on the screenshot I provided), ie adding an HTTPS-prefixed remote with username and password authentication will cause a fatal error ("Authentication failed") upon push:
```sh
cd ./api-py
git remote add origin https://github.com/kirisakow/${PWD##*/}.git
git branch -M main
git push -u origin main 
 Username for 'https://github.com': kirisakow
 Password for 'https://kirisakow@github.com': 
 remote: Support for password authentication was removed on August 13, 2021.
 remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
 fatal: Authentication failed for 'https://github.com/kirisakow/api-py.git/'
```

**Comment by cmwilson21** [comment]
@kirisakow Thanks for opening an issue! We maintain docs.github.com, this report should be directed towards the github.com website. You can fill out a bug report [here](https://support.github.com/contact/bug-report). 👍 

I'm going to go ahead and close this issue in favor of a bug report 💛
