### ISSUE TITLE
Wrong information in docs for `defaults.run`

### ISSUE THREAD

**Issue by j1elo** [github/docs#23465]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Workflow syntax for `jobs.<job_id>.defaults.run`:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun

### What part(s) of the article would you like to see updated?

1. Text mentions a nonexistent key `jobs.defaults.run`.

2. Text says that "*You cannot use contexts or expressions in this keyword.*", however the [Context availability](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability) docs state that `jobs.<job_id>.defaults.run` should be able to access a variety of contexts. Empirically tested and the runner does in fact not fail when using the `inputs` context within a `jobs.<job_id>.defaults.run` entry.

### Additional information

I'm sending a PR with proposed changes; only reason for this issue is that PR instructions ask for creating an issue before opening a PR.

**Comment by cmwilson21** [comment]
@j1elo Thanks for opening an issue and connecting it to your PR! It definitely helps us when issues are opened, as well! 💖

**Comment by grcspace311** [comment]
Closed check
