### ISSUE TITLE
Clarify information on excluding results from searches

### ISSUE THREAD

**Issue by felicitymay** [github/docs#23461]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Understanding the search syntax](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax)

### What part(s) of the article would you like to see updated?

The existing section on "Exclude certain results" is misleading because it starts with the `NOT` syntax first and this can be used only for string keywords. Information about how to negate qualifiers is easy to miss within this section (see https://github.com/github/docs/issues/22902).

## Recommended changes

1. Create a new section called "Exclude results that match a qualifier" and move the information about using `-` into this section. The content will need a small amount of rewording for the new location. I can also see that the formatting of the table needs to be adjusted.
2. Rename the existing section to "Exclude results with specific keywords"

### Additional information

This is a follow up to https://github.com/github/docs/issues/22902.

**Comment by dxodja** [comment]
UQA-egmP2MYu1HGys7OK5YX7lnl3d4-0dE_02VG_JBgUHQsd

**Comment by dxodja** [comment]
> UQA-egmP2MYu1HGys7OK5YX7lnl3d4-0dE_02VG_JBgUHQsd
