### ISSUE TITLE
Automatically publish package to NPM on release.

### ISSUE THREAD

**Issue by santosned** [github/docs#23487]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/actions/publishing-packages/publishing-nodejs-packages.md

### What part(s) of the article would you like to see updated?

# Summary

The event trigger in the following example does not perform the function described in the [docs](https://github.com/github/docs/blob/main/content/actions/publishing-packages/publishing-nodejs-packages.md#publishing-packages-to-the-npm-registry
). I experimented after looking for various event triggers and was able to do what was suggested by using 'published' instead of 'created'.

## Current example

```yml
# ...
on:
  release:
    types: [created]
# ...
```

## Suggested changes

```yml
## ...
on:
  release:
    types: ['published']
## ...
```

## Other changes

If this change is applied I also suggest to update the following:

```markdown
## Publishing packages to the npm registry

Each time you create a new release, you can trigger a workflow to publish your package. The workflow in the example below runs when the `release` event triggers with type `created`. The workflow publishes the package to the npm registry if CI tests pass.
```

To:

```markdown
## Publishing packages to the npm registry

You can trigger a workflow to publish your NPM package every time you [publish a new release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release). The process in the following example is executed when the release event of type 'published' is triggered. If the CI tests pass, the process uploads the package to the npm registry.
```

### Additional information

You can see a working example in [this project](https://github.com/santosned/unbyted). Before [this commit](https://github.com/santosned/unbyted/commit/158b19532b13b3ea4d942a5d10d67e601a7203a6) I used the exact same example as suggest in the docs, but after creating the releases the workflow was not triggered. The NPM package was only published after I change the event trigger as mentioned previously.

**Comment by cmwilson21** [comment]
@santosned Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! Your proposed changes sound good to me. You or anyone else is welcome to open a PR to address this issue.
