### ISSUE TITLE
Outing s

### ISSUE THREAD

**Issue by E5393Zm** [github/docs#2350]
Outing s

_Originally posted by @E5393Zm in https://github.com/cli/cli/issues/2690#issuecomment-751352302_

**Comment by Bolek719** [comment]
#2336

**Comment by Geno2tattedXXX** [comment]
#TNB #GANGGANG#GENO2DTATTEDXXX#

**Comment by Bolek719** [comment]
Ja--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.12.20, 16:27 schrieb Geno Genaro <notifications@github.com>:

   #TNB #GANGGANG#GENO2DTATTEDXXX#
