### ISSUE TITLE
Manage default profile 

### ISSUE THREAD

**Issue by Sunnytee0231** [github/docs#23517]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Code of conduct and defaulted profile account editor 

### What part(s) of the article would you like to see updated?

Professional terminology should be used

### Additional information

None at the moment

**Comment by Sunnytee0231** [comment]
For me if all point as regards to changes are met, then, the repository is superb and good to go.

**Comment by cmwilson21** [comment]
This seems to have been opened accidentally, I am going to close it now :yellow_heart: 

Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions or check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. :sparkles:

**Comment by Sunnytee0231** [comment]
Is fine, no issues.
