### ISSUE TITLE
Adding your SSH key to the ssh-agent instructions are incorrect

### ISSUE THREAD

**Issue by simonw** [github/docs#23512]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

This bit: https://github.com/github/docs/blob/5c6e71548effcc4e43dacf80dfbc4eb39aea7679/content/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md#L128

### What part(s) of the article would you like to see updated?

The instructions say that you should edit `~/.ssh/config` and add this to it:

```
Host *.github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
```
I tried that, but when I ran `git clone git@github.com:simonw/sqlite-utils` I still had to enter my password.

When I changed it to this my command worked correctly as expected, without asking for my password:

```
Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
```

**Comment by cmwilson21** [comment]
@simonw Thank you for opening an issue and linking it to your PR! ✨
