### ISSUE TITLE
Update org team sync docs to include more detail about enterprise team sync limitations

### ISSUE THREAD

**Issue by adamrr724** [github/docs#23539]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/managing-team-synchronization-for-your-organization

### What part(s) of the article would you like to see updated?

Based on [this customer ticket](https://github.zendesk.com/agent/tickets/1982581), where they were confused that they could not set up team sync for an individual organization, as they had SAML set up in Azure AD at the enterprise level.

We need to be more clear that if you are setting up team sync and you have SAML set up at the enterprise level, team sync must be enabled at the enterprise level and is not available (literally will not show up in the UI) for individual orgs.

**Comment by cmwilson21** [comment]
👋 @adamrr724 Thank you for opening an issue and linking it to your PR! ✨
