### ISSUE TITLE
Dependabot example auto-label does not work

### ISSUE THREAD

**Issue by Rotzbua** [github/docs#23568]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Example from:

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#label-a-pull-request

Problem:
Example fails because token for permission is missing.

### What changes are you suggesting?

Add missing:

> GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

**Comment by cmwilson21** [comment]
@Rotzbua Thank you for opening an issue and linking it to your PR! ✨
