### ISSUE TITLE
JumpCloud now has an Identity Connector for Github Enterprise Cloud SCIM

### ISSUE THREAD

**Issue by elliotnichols** [github/docs#23578]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/about-scim-for-organizations#supported-identity-providers

JumpCloud isn't shown as a supported IdP for SCIM under the title "Supported identity providers"

### What changes are you suggesting?

JumpCloud has support to do the SCIM Provision/ Deprovision via their Identity Connectors functionality. 
https://support.jumpcloud.com/s/article/Identity-Management-with-GitHub

**Comment by cmwilson21** [comment]
@elliotnichols Thank you for opening an issue and linking it to your PR! ✨
