### ISSUE TITLE
Clarity on github context usage in Workflows vs. in custom JS action as well as attribute names in docs vs. actual event.

### ISSUE THREAD

**Issue by ftclausen** [github/docs#23589]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[github-context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)

## Introduction

From Workflows we have `github.event_name` but, when *creating an action* in JS, the payload JSON is `github.context.eventName`. I was trying to use `github.event_name` in JS which gave undefined. Also note one is camel case and the other snake case. 

This is confusing. 

A small code example of the action (index.js) I am experimenting with:

```js
const core = require('@actions/core');
const github = require('@actions/github');

async function run() {
  try {
    core.info(`This event is a: ${github.context.eventName}`);
    core.info(`This event's action is ${github.context.action}`);
  } catch (error) {
    core.setFailed(error.message);
  }
}

run();
```

Should usage from within a Workflow versus using from JS/TS be called out in the docs?

## More details

The [Github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) action has examples as follows:

- `github.event`
- `github.event_name`
- ... and many others

These seem to be directly useable in a Workflow situation. [From this example](https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner#example-workflow) we have:

```
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
```

Where `github.head_ref` matches [the docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).

**However**, from within JS, we need to use (for example) `github.context.eventName` otherwise these are undefined. See example above.

I suppose _using a workflow_ and _creating a custom action_ are two different things but the language is almost exactly the same as well as the data being operated on (notwithstanding the subtle differences highlighted above).

As mentioned above, should usage from within a Workflow versus using from JS/TS be called out in the docs?

### Additional information

Referenced in [this discussion](https://github.com/github/docs/discussions/23569)

**Comment by Allah-O-Akbar** [comment]
zainmotorsofficial

**Comment by cmwilson21** [comment]
@ftclausen Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
