### ISSUE TITLE
'cleanup caches' example workflow is wrong and harmful!

### ISSUE THREAD

**Issue by andreasabel** [github/docs#23600]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

Lifted from:
- https://github.com/github/docs/pull/23530

The workflow that is supposed to delete PR-caches deletes caches from `master`/base branch:
https://github.com/github/docs/blob/4f054920abd101e3c059195642e04c0901e9490a/content/actions/using-workflows/caching-dependencies-to-speed-up-workflows.md?plain=1#L330-L347
This looks logical, but seems to be wrong.  If invoked by a closing PR, BRANCH ends up to be the base branch, e.g. `master`. This job will then remove exactly the wrong caches.

Should be fixed immediately by some knowledgeable person.  Or at least add the disclaimer I suggested in the PR.

Evidence here: https://github.com/agda/agda/actions/runs/4025940394/jobs/6919801891#step:3:5
(Note: these logs will be removed by github after some time.)

### What part(s) of the article would you like to see updated?

See above.

**Comment by JacobKlipper** [comment]
Labels yesterday seems like the best of choices after reading this article highly agree

**Comment by lucascosti** [comment]
Looks like this was fixed in another PR recently: https://github.com/github/docs/pull/23612

Thanks for the issue!
