### ISSUE TITLE
GITHUB_ACTION_REPOSITORY not available in Actions

### ISSUE THREAD

**Issue by myrrc** [github/docs#23646]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/variables

### What part(s) of the article would you like to see updated?

The one about the variable

### Additional information

Using `${GITHUB_ACTION_REPOSITORY}`, `${{GITHUB_ACTION_REPOSITORY}}`, or `$GITHUB_ACTION_REPOSITORY`
results in an empty variable during workflow run, see
https://github.com/myrrc/sws/actions/runs/4069743614/jobs/7009808824
Other variables are available.

**Comment by myrrc** [comment]
Using `${{github.action_ref}}` works correctly

**Comment by cmwilson21** [comment]
@myrrc Thanks so much for opening an issue! And for providing the extra info 👍  

I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Hi @myrrc, thanks for opening this issue, and for helpfully including the workflow you were using for testing.

The description for `GITHUB_ACTION_REPOSITORY` says:

> For a step executing an action, this is the owner and repository name of the action. For example, actions/checkout.

This variable is only applicable for steps executing an action (i.e. a step that has the [`uses` key](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses)). In your workflow, you are using a [`run` step](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun), which is not executing an action, so the variable is not set.
