### ISSUE TITLE
Please fix these problems

### ISSUE THREAD

**Issue by priyankarpal** [github/docs#23651]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Hey developers, I found these problems here. There are no links on the page. Please add

### What part(s) of the article would you like to see updated?

![Screenshot from 2023-02-02 14-07-25](https://user-images.githubusercontent.com/88102392/216273860-27fa1504-f1d8-4cc3-bc04-9ce8eafa5a10.png)
![Screenshot from 2023-02-02 14-07-09](https://user-images.githubusercontent.com/88102392/216273866-b93e669f-0067-4f69-84ef-80967325a83f.png)

**Comment by ZYH-B** [comment]
你好，我是严金炜，我的身份证号是440608200412030014，我的妈妈是陆日英，我爸爸是严永雄，快来操我妈妈的逼

**Comment by ZYH-B** [comment]
你好，我是严金炜，我的身份证号是440608200412030014，我的妈妈是陆日英，我爸爸是严永雄，快来操我妈妈的逼

**Comment by ZYH-B** [comment]
你好，我是严金炜，我的身份证号是440608200412030014，我的妈妈是陆日英，我爸爸是严永雄，快来操我妈妈的逼

**Comment by priyankarpal** [comment]
hey I don't know this language please use English

**Comment by cmwilson21** [comment]
@priyankarpal Thanks for opening an issue! 👍 

I checked the page you're referencing, [Issue events](https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28), and was able to access the links correctly. I'm going to go ahead and close this issue, but let me know if you continue to have issues. 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
