### ISSUE TITLE
ui: contact support banner needs an alignment

### ISSUE THREAD

**Issue by kamaroolkarim** [github/docs#237]
#### 1. the section is not align correctly with the docs content on the big screen. 
<img width="2198" alt="image" src="https://user-images.githubusercontent.com/6109672/95420482-18ad5f80-096e-11eb-994a-dd2ca73700e7.png">

#### 2. the button position is a little bit off on mobile
<img width="436" alt="image" src="https://user-images.githubusercontent.com/6109672/95420776-ae48ef00-096e-11eb-83e5-5d069502d7f6.png">

#### 1. expected result
<img width="2186" alt="image" src="https://user-images.githubusercontent.com/6109672/95420602-50b4a280-096e-11eb-87cf-cfdeeb44b23c.png">

i added this class on the contact support banner
<img width="694" alt="image" src="https://user-images.githubusercontent.com/6109672/95421010-15ff3a00-096f-11eb-98d9-da39f452624b.png">

#### 2. expected result on mobile view
<img width="430" alt="image" src="https://user-images.githubusercontent.com/6109672/95420867-d20c3500-096e-11eb-86b4-240e01aede54.png">

fix it by replacing the classes into this
<img width="603" alt="image" src="https://user-images.githubusercontent.com/6109672/95421144-65456a80-096f-11eb-8b7c-25fe799e68cb.png">

**Comment by saideepesh000** [comment]
Can I work on this

**Comment by kamaroolkarim** [comment]
> Can I work on this

**Comment by chiedo** [comment]
Thanks for volunteering @saideepesh000 but it looks like @Arhell got to it first in https://github.com/github/docs/pull/248! 😄
