### ISSUE TITLE
Add permissions information to the 'deleting an organization' page.

### ISSUE THREAD

**Issue by adamrr724** [github/docs#23737]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/managing-organization-settings/deleting-an-organization-account

### What part(s) of the article would you like to see updated?

This document doesn't note which permissions are required for deleting an organization. This should be listed as part of the documentation.

**Comment by adamrr724** [comment]
Proposed this change in PR https://github.com/github/docs/pull/23738

**Comment by cmwilson21** [comment]
👋 @adamrr724 Thanks for opening an issue and a PR ⚡
