### ISSUE TITLE
Incorrect code block language

### ISSUE THREAD

**Issue by willsawyerrrr** [github/docs#23751]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization)

### What part(s) of the article would you like to see updated?

Step 4 under the 'Creating a starter workflow' heading contains a JSON code block which is labelled as YAML.

This label should be changed to reflect the fact that the code block contains JSON.

**Comment by cmwilson21** [comment]
@willsawyerrrr Thank you for opening a PR and linking it to your issue! ✨
