### ISSUE TITLE
Inconsistent quoting in the Filter pattern cheat sheet

### ISSUE THREAD

**Issue by bplessis-swi** [github/docs#23782]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths

### What changes are you suggesting?

Some patterns are quoted like
- '*'
- '*.jsx?'
- '*feature'

 some aren't, like
- docs/*
- docs/**
- feature/*

**Comment by cmwilson21** [comment]
@bplessis-swi Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
