### ISSUE TITLE
Note about environment availability is confusing/contradictory

### ISSUE THREAD

**Issue by jsoref** [github/docs#23784]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#about-environments

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/ef82ef29daa7c29b121349444c4e1129cce11600/content/actions/deployment/targeting-different-environments/using-environments-for-deployment.md?plain=1#L28-L30

>  **Note:** You can only configure environments for public repositories. If you convert a repository from public to private, any configured protection rules or environment secrets will be ignored, and you will not be able to configure any environments. If you convert your repository back to public, you will have access to any previously configured protection rules and environment secrets. 
> 
> Organizations with {% data variables.product.prodname_team %} and users with {% data variables.product.prodname_pro %} can configure environments for private repositories. For more information, see "[{% data variables.product.prodname_dotcom %}'s products](/get-started/learning-about-github/githubs-products)." 

The first "paragraph" here says "You can only ... for public repositories". The second paragraph says "oh, actually, some organizations can do it for private repositories".

The text should be unified to list the kinds of repositories that can do it in a single sentence, or to not use `only` for a sentence that only covers a subset of the repositories that support the feature. Only after the kinds of repositories that can use the feature are listed should the effects of transitioning a repository to a kind that can't be listed.

### Additional information

@JacobWeisenburger asked about environments in https://github.com/github/docs/discussions/22691

**Comment by cmwilson21** [comment]
@jsoref Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by jsoref** [comment]
@cmwilson21: I was on vacation last week ...

**Comment by jsoref** [comment]
@cmwilson21 ?

**Comment by SiaraMist** [comment]
Thanks for opening this @jsoref, I definitely see how the way this note is phrased is confusing. You or anyone else is free to open a PR that updates the note to use clearer language, such as:

> **Note:** Users with {% data variables.product.prodname_free_user %} plans can only configure environments for public repositories. If you convert a repository from public to private, any configured protection rules or environment secrets will be ignored, and you will not be able to configure any environments. If you convert your repository back to public, you will have access to any previously configured protection rules and environment secrets. 
>  
> Organizations with {% data variables.product.prodname_team %} and users with {% data variables.product.prodname_pro %} can configure environments for private repositories. For more information, see "[{% data variables.product.prodname_dotcom %}'s products](/get-started/learning-about-github/githubs-products)."
