### ISSUE TITLE
Improve doc.github.com site 

### ISSUE THREAD

**Issue by Flyerrebel** [github/docs#23804]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Chrome bowser off of github app ath. No errors . If ur asking to make it better . Sum pop and vedo chat from github customer service after u click in add from a affiliate marketer a vedo chat pops up with a github export talking to u directly .

### What changes are you suggesting?

An ad that the customer click from a affiliate marker to ur own repertory and a vido chat pops up from a github export customer service or sponser directed u for learning or issues for more cloctivley both partners collecting web monzation and affiliated marketing strategy. "Vedo customer pipeline "

### Additional information

"Vedo pipeline " T2 =v 
P=<78>

**Comment by Flyerrebel** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).
> 

Thank u

**Comment by ankr6517** [comment]
> ### Davranış kodu
> * [x] [GitHub Docs projesinin Davranış Kurallarını](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md) okudum ve kabul ediyorum[](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### docs.github.com'daki hangi makale etkilenir?
> github uygulamasından Chrome bowser kapalı. Hata yok . Daha iyi hale getirmeyi soruyorsan. Bir ortak pazarlamacıdan ekle'yi tıkladıktan sonra github müşteri hizmetlerinden Sum pop ve vedo sohbeti, sizinle doğrudan konuşan bir github dışa aktarma ile bir vedo sohbeti açılır.
> 
> ### Ne gibi değişiklikler öneriyorsunuz?
> Müşterinin bir satış ortağı işaretçisinden kendi repertuarına tıkladığı bir reklam ve github ihracat müşteri hizmetlerinden veya sponsordan bir video sohbet açılır ve her iki ortak da web monzasyonu ve bağlı pazarlama stratejisi toplayarak öğrenme veya daha fazla sorun yaşamanız için sizi yönlendirir. "Vedo müşteri hattı"
> 
> ### Ek Bilgiler
> "Vedo boru hattı" T2 =v P=<78>

**Comment by cmwilson21** [comment]
Thanks for opening an issue. We maintain the Docs site for GitHub, so the best place to send your feedback is to https://github.com/community/community/discussions 💛
