### ISSUE TITLE
Include Keeper in references to password managers

### ISSUE THREAD

**Issue by craiglurey** [github/docs#23825]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/organizations/managing-saml-single-sign-on-for-your-organization/accessing-your-organization-if-your-identity-provider-is-unavailable.md
content/organizations/managing-saml-single-sign-on-for-your-organization/downloading-your-organizations-saml-single-sign-on-recovery-codes.md
content/admin/user-management/managing-users-in-your-enterprise/best-practices-for-user-security.md
content/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication-recovery-methods.md
content/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication.md
content/authentication/keeping-your-account-and-data-secure/updating-your-github-access-credentials.md
content/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token.md
content/authentication/keeping-your-account-and-data-secure/creating-a-strong-password.md
content/rest/quickstart.md
content/rest/quickstart.md
content/rest/guides/getting-started-with-the-rest-api.md
content/rest/guides/getting-started-with-the-rest-api.md
content/rest/guides/scripting-with-the-rest-api-and-javascript.md
content/rest/overview/other-authentication-methods.md

### What part(s) of the article would you like to see updated?

Include link to Keeper (https://keepersecurity.com) when 1Password or LastPass is mentioned

**Comment by cmwilson21** [comment]
@craiglurey Thanks for opening an issue and submitting a PR! 👍

**Comment by conradivy** [comment]
#23825

**Comment by cmwilson21** [comment]
Closing this issue as we are working on an internal solution per comment [here](https://github.com/github/docs/pull/23821#issuecomment-1440438186) 💛
