### ISSUE TITLE
How to specify `@me` to self-assign new issues by default using Issue Forms?

### ISSUE THREAD

**Issue by barabo** [github/docs#23838]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms.md

### What part(s) of the article would you like to see updated?

I am not able to specify `@me` as a new issue assignee.  The new issue seems to ignore this parameter.

### Additional information

I would like the created issue to default to assigning the requester as the assignee.

**Comment by cmwilson21** [comment]
@barabo Thanks for opening an issue! Sorry to hear you are experiencing trouble here. This sounds like it _might_ be a bug? This question would best be handled by our [support team](https://support.github.com/request). Please reach out to them.

I'm going to go ahead and close this for now. If there's anything in the documents that you have suggestions for updating, please feel free to open an issue. 💛
