### ISSUE TITLE
Add a guide on how to use the .NET Octokit SDK

### ISSUE THREAD

**Issue by skedwards88** [github/docs#23845]
The GitHub docs now include a guide about how to use GitHub's JavaScript Octokit SDK to use the REST API: https://docs.github.com/rest/guides/scripting-with-the-rest-api-and-javascript

We would like to add a similar guide for the [.NET Octokit SDK](https://github.com/octokit/octokit.rb).

The guide should:

- Follow the same format as https://docs.github.com/rest/guides/scripting-with-the-rest-api-and-javascript. You can copy this guide to use as a template, but please be sure to update all JavaScript-specific content.
- Follow best practices for .NET, including adhering to a standard .NET linter
- Not recommend OAuth Apps, but instead recommend [GitHub Apps](https://docs.github.com/en/apps/creating-github-apps/setting-up-a-github-app/about-creating-github-apps)

**Comment by Manas-Kenge** [comment]
Can I work on this issue?

**Comment by skedwards88** [comment]
Yes, anyone is welcome to work on issues labeled as `help-wanted`! For this issue, we'd especially like you to follow the format of the [JavaScript guide](https://docs.github.com/rest/guides/scripting-with-the-rest-api-and-javascript), and replace the JavaScript-specific content with .NET-specific content. (You can find the contents of that file to copy [here](https://github.com/github/docs/blob/main/content/rest/guides/scripting-with-the-rest-api-and-javascript.md).

**Comment by KhushiSharma0313** [comment]
Here is my attempt, I have attached a word file for reference- 
[.NET guide.docx](https://github.com/github/docs/files/13199885/default.NET.guide.docx)

**Comment by RichardValerosoUniverse** [comment]
🌍
