### ISSUE TITLE
[GitHub Actions] Fail fast from the default shells (bash/sh) in Linux/macOS

### ISSUE THREAD

**Issue by iamazeem** [github/docs#23853]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

The [`jobs.<job_id>.steps[*].shell`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell) lists the default shell commands for **Linux/macOS** under **Command run internally** column:

| shell             | command                                              |
|:-----------------:|:---------------------------------------------------|
| unspecified  | `bash -e {0}`                                           |
| `bash`          | `bash --noprofile --norc -eo pipefail {0}` |
| `sh`              | `sh -e {0}`                                               |

Screenshot of a test run from `ubuntu-latest`/`ubuntu-22.04` runner:

![image](https://github.com/github/docs/assets/7128328/e5d80af4-84d3-4e95-b8a8-727681f51cac)

All these variants have `-e` and according to its description under  [The Set Builtin](https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin) section form the [Bash manual](https://www.gnu.org/software/bash/manual/bash.html):

> `-e`: Exit immediately if a pipeline (see [Pipelines](https://www.gnu.org/software/bash/manual/bash.html#Pipelines)), which may consist of a single simple command (see [Simple Commands](https://www.gnu.org/software/bash/manual/bash.html#Simple-Commands)), a list (see [Lists of Commands](https://www.gnu.org/software/bash/manual/bash.html#Lists)), or a compound command (see [Compound Commands](https://www.gnu.org/software/bash/manual/bash.html#Compound-Commands)) returns a non-zero status.

Which is equivalent to the [fail fast](https://en.wikipedia.org/wiki/Fail-fast) behavior.

But, according to the [Exit codes and error action preference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference):

> `bash`/`sh`: Fail-fast behavior using `set -eo pipefail`: This option is set when `shell: bash` is _explicitly specified_. **It is not applied by default.**

And, that is not the case. This only applies to the `-o pipefail` part (Bash only) because `-e` is applied by default.

The `-o pipeline` only affects the returning of the exit status from [Pipelines](https://www.gnu.org/software/bash/manual/bash.html#Pipelines) in Bash:

> `pipefail`: If set, the return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.

The docs should be revised to avoid contradiction when both these sections are read in conjunction.

- `-e` is applied by default to `sh` and `bash` both.
- `-o pipefail` is applied to `bash` only (i.e. `bash -e -o pipefail`) when `shell: bash` is specified; and, not to `shell: sh`.
- ~~`sh` command should also have `pipefail` but at the moment it doesn't. Also, it has a different syntax i.e. `sh -e -pipefail`.~~

**Comment by cmwilson21** [comment]
@iamazeem Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by norwd** [comment]
No wait! Don't mark this as stale!

**Comment by ms-ati** [comment]
So is this going to be updated? I just spent too long digging through the internet to find this

**Comment by iamazeem** [comment]
@ms-ati: This was originated from this StackOverflow [question](https://stackoverflow.com/questions/75419587/does-a-github-action-step-use-set-e-semantics-by-default).
If you are blocked by this or need to discuss it, you are welcome to [ask a question](https://stackoverflow.com/questions/ask) on SO under [github-actions](https://stackoverflow.com/questions/tagged/github-actions) tag until this is updated.

**Comment by jmarshall** [comment]
> sh command should also have pipefail but at the moment it doesn't. Also, it has a different syntax i.e. sh -e -pipefail.

What version of plain `sh` has a `-pipefail` option spelt thus?

The reason why the plain `sh` entry doesn't have this option is that traditionally plain `sh` has no equivalent of the pipefail behaviour. (Answers to and comments on [this SO question](https://unix.stackexchange.com/questions/654885/who-is-responsible-for-providing-set-o-pipefail) note that `-o pipefail` is more widespread than it used to be and has been added to an upcoming POSIX revision.)

**Comment by iamazeem** [comment]
@jmarshall: Thank you for your input! :+1: 

`sh` (`sh` -> `dash`) seems to accept `-pipefail` flag for version `0.5.8-2.10` (Ubuntu 18.04) and `0.5.11+git20210903+057cd650a4ed-3build1` (Ubuntu 22.04).

Tested both with docker:

`ubuntu:18.04`

```shell
$ docker run -it --rm ubuntu:18.04
root@0ee43bcb3993:/# ls -l $(which sh)
lrwxrwxrwx 1 root root 4 Apr  1  2022 /bin/sh -> dash
root@0ee43bcb3993:/# dpkg -s dash | grep 'Version'
Version: 0.5.8-2.10
root@0ee43bcb3993:/# sh -o pipefail
sh: 0: Illegal option -o pipefail
root@0ee43bcb3993:/# 
root@0ee43bcb3993:/# sh -e -pipefail
# echo test | false | true
# echo $?
0
# exit
root@0ee43bcb3993:/# bash -e -o pipefail
root@0ee43bcb3993:/# echo test | false | true
root@0ee43bcb3993:/# echo $?
1
root@0ee43bcb3993:/# exit
exit
```

`ubuntu:22.04`

```shell
$ docker run -it --rm ubuntu:22.04
root@47bdd8723e19:/# ls -l $(which sh)
lrwxrwxrwx 1 root root 4 Mar 23  2022 /usr/bin/sh -> dash
root@47bdd8723e19:/# dpkg -s dash | grep 'Version'
Version: 0.5.11+git20210903+057cd650a4ed-3build1
root@47bdd8723e19:/# sh -o pipefail
sh: 0: Illegal option -o pipefail
root@47bdd8723e19:/# 
root@47bdd8723e19:/# sh -e -pipefail
# echo test | false | true
# echo $?
0
# exit
root@47bdd8723e19:/# bash -e -o pipefail
root@47bdd8723e19:/# echo test | false | true
root@47bdd8723e19:/# echo $?
1
root@47bdd8723e19:/# exit
exit
```

However, `-pipefail` doesn't seem to be working as Bash's `-o pipefail` flag does.
The same is also clear from above tests in the docker containers.

I have updated my original description and struck the last line.
The original intent was to have clarification in the docs i.e. the default `-e` is both for `sh` and `bash` whereas `-o pipefail` is only for `bash` when specified in addition to `-e`.

**Comment by hubwriter** [comment]
@iamazeem - Thank you for raising this. It would be good to clarify this in https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions as per the initial description to this issue.

I've marked this issue `help-wanted`. If you (or anyone else reading this) would like to raise a pull request to update the docs accordingly that would be great.

Information about contributing to the docs:
https://docs.github.com/en/contributing

**Comment by iamazeem** [comment]
@hubwriter: PR #27583 created. Please review. Thanks!
