### ISSUE TITLE
I am a beginner on open source, as i need to contribute to open source so if you would suggest me how to contribute than this is beneficial for me as well as for open source.

### ISSUE THREAD

**Issue by Natthdia** [github/docs#2385]
I am a beginner on open source, as i need to contribute to open source so if you would suggest me how to contribute than this is beneficial for me as well as for open source.

_Originally posted by @himanshu211raj in https://github.com/github/docs/issues/1571#issuecomment-733835732_

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
