### ISSUE TITLE
[REST] Activity Types list for pull_request appears stale

### ISSUE THREAD

**Issue by jsoref** [github/docs#23909]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

### What part(s) of the article would you like to see updated?

The list of activity types appears stale:

- assigned
- unassigned
- labeled
- unlabeled
- opened
- edited
- closed
- reopened
- synchronize
- converted_to_draft
- ready_for_review
- locked
- unlocked
- review_requested
- review_request_removed
- auto_merge_enabled
- auto_merge_disabled

At least `milestoned` is missing...

### Additional information

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request

assigned
auto_merge_disabled
auto_merge_enabled
closed
converted_to_draft
demilestoned
dequeued
edited
enqueued
labeled
locked
milestoned
opened
ready_for_review
reopened
review_request_removed
review_requested
synchronize
unassigned
unlabeled
unlocked

<img width="517" alt="image" src="https://user-images.githubusercontent.com/2119212/218670968-9e8ba19b-e6e9-41e8-98d8-2aca8e9bc701.png">

**Comment by jsoref** [comment]
@cmwilson21: the stale bot appears to have become considerably ruder.

**Comment by flying-sheep** [comment]
The `milestoned` event is definitely being triggered for pull requests.

**Comment by flying-sheep** [comment]
please reopen and pin

**Comment by flying-sheep** [comment]
@cmwilson21 can you please reopen and add a label that prevents your bots from closing it again?

**Comment by mark-mxwl** [comment]
Thx for spotting this @jsoref! 👏 I've opened a PR with the fix. Seems that `milestoned` and `demilestoned` were added at some point, so there were just a couple other additions needed to bring it up to date.
