### ISSUE TITLE
How to disable/enable "All Workflows" at once?

### ISSUE THREAD

**Issue by ElYusubov** [github/docs#23903]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I was not able to find any information on how to disable [All Workflows] under the Actions menu.
This is a really important feature, as any user who forks from https://github.com/Azure/ResourceModules repo will get more than 255+ emails with the header "Run failed: XYZ Description - main".

And if I want to disable those 255+ workflows it will take me close to 50 minutes to do that :(
In addition, this is a waste of GitHub resources to run those automated workflows on each new fork.

Thus, I propose to introduce/enable functionality on the "All Workflows" level that could basically, disable and enable all workflows.
Plus, disable all workflows on newly forked repositories to save the processing power of the GitHub platform,

Please, let me know where to raise this concern, as it is very beneficial for the community, and for GitHub. Thanks!

### What changes are you suggesting?

I suggest to introduce/enable functionality on the "All Workflows" level that could basically, disable and enable all workflows.
Plus, disable all workflows on newly forked repositories to save the processing power of the GitHub platform,

### Additional information

Please, let me know where to raise this concern, as it is very beneficial for the community, and for GitHub. Thanks!

**Comment by cmwilson21** [comment]
@ElYusubov Thanks for opening an issue! We maintain the Docs site, so if you have any suggestions for how we can update the Docs, please let us know. 👍 

Otherwise, the best place to send your feedback is to https://github.com/community/community/discussions 💖

I'm going to go ahead and close this issue now 💛
