### ISSUE TITLE
A typo in "Using contexts to access variable values"

### ISSUE THREAD

**Issue by iwill** [github/docs#23970]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Variables](https://docs.github.com/en/actions/learn-github-actions/variables)

### What part(s) of the article would you like to see updated?

Using contexts to access variable values

### Additional information

`DAYS_OF_WEEK` should be `DAY_OF_WEEK` in [Using contexts to access variable values](https://docs.github.com/en/actions/learn-github-actions/variables#using-contexts-to-access-variable-values).

**Comment by janl3577** [comment]
Thanks

**Comment by cmwilson21** [comment]
@iwill Thank you for opening an issue and linking it to your PR! ✨
