### ISSUE TITLE
Update the quickstart.md docs

### ISSUE THREAD

**Issue by Shivam7-1** [github/docs#240]
### What article on docs.github.com is affected?

 https://github.com/github/docs/blob/main/content/actions/quickstart.md

### Additional information

Update some typos on quickstart.md

**Comment by Shivam7-1** [comment]
https://github.com/github/docs/pull/241

**Comment by janiceilene** [comment]
Thanks for opening the issue @Shivam7-1! Closing this with the listed PR.
