### ISSUE TITLE
TOTP option missing bug

### ISSUE THREAD

**Issue by xgqfrms** [github/docs#24017]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/changing-your-preferred-two-factor-authentication-method

### What part(s) of the article would you like to see updated?

TOTP option missing bug

> docs desciption

![image](https://user-images.githubusercontent.com/7291672/219922017-f7b7b466-9b1c-45ba-850a-2eb1646f6fd1.png)

> actually

![image](https://user-images.githubusercontent.com/7291672/219922034-5fd3044b-ae10-4405-8f6e-a030b32c8a82.png)

**Comment by xgqfrms** [comment]
authenticator app

https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-totp-mobile-app

**Comment by cmwilson21** [comment]
@xgqfrms Thanks for opening an issue! As you stated, this may be a bug. I suggest reaching out to our awesome [support team](https://support.github.com/request). 💻 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue. As this likely won't affect any of the documentation, I'm going to go ahead and close this issue. 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
