### ISSUE TITLE
Table of Contents under "In this article" is missing entries

### ISSUE THREAD

**Issue by bewuethr** [github/docs#24043]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

only has the "Available events" heading, but the individual events aren't listed:

![image](https://user-images.githubusercontent.com/8521043/220213420-7f7a4f09-32e1-4bef-8d41-3c63a404d3c9.png)

They used to be listed, and it makes sense for them to be.

### What changes are you suggesting?

Make level 3 headings appear in the sidebar under "In this article" again. It looks like commit 4cd28fd73522e65b6428fd5424cf5e6e3018effd caused them to disappear.

**Comment by cmwilson21** [comment]
@bewuethr Thanks for opening and issue and linking to the commit. Great detective work! 🔍 

I'm checking with the team on this one. 💛

**Comment by cmwilson21** [comment]
@bewuethr Just dropping in to report that the individual events are now listed in the side bar again 🎉 

Closing this issue out now 💖
