### ISSUE TITLE
Branch protection check text changed

### ISSUE THREAD

**Issue by jean** [github/docs#24052]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule.md

### What part(s) of the article would you like to see updated?

> Optionally, to require someone other than the last person to push to a branch to approve a pull request prior to merging, select Require approval from someone other than the last pusher. [ref](https://github.com/github/docs/blame/main/content/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule.md#L72)

This text has changed, in my interface, I see: "Require approval of the most recent reviewable push", with description referencing "someone other than the person who pushed it".

**Comment by cmwilson21** [comment]
@jean Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by myarb** [comment]
👋 @jean thank you for opening this issue! Could share a screenshot of your interface with the updated text? Then we can set this issue as ready for contribution ✨

**Comment by jean** [comment]
Hi @myarb 

It looks like the docs have been reorganized: [old](https://github.com/github/docs/blob/main/content/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule.md) has moved to [new](https://github.com/github/docs/blob/main/content/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule.md). I'll edit the original issue.

Here's a screenshot of my interface:
![image](https://github.com/github/docs/assets/84800/261f8e93-0725-4973-84fb-92cbac741b63)

Text in the screenshot:
> Require approval of the most recent reviewable push

Text in the docs:
> Require approval from someone other than the last pusher.

**Comment by cmwilson21** [comment]
Thanks for providing the screenshot to confirm the text! I took another look at the article and I'm seeing the correct text now. So I'm going to go ahead and close this issue 💛 

If you notice something else or if this hasn't been corrected and I've missed it, please feel free to reopen this issue.

Thank you again for opening an issue and letting us know about this text change! ✨
