### ISSUE TITLE
Example inputs context for GitHub Actions workflow_dispatch article is invalid

### ISSUE THREAD

**Issue by sayhiben** [github/docs#24070]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context

### What part(s) of the article would you like to see updated?

The section labeled "Example usage of the inputs context in a manually triggered workflow" contains an example of the  `workflow_dispatch` trigger. In this example, the `workflow_dispatch` event has an input of type `number`. 

However, according to [the schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json), actual behavior, and [syntax documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype), `on.workflow_dispatch.inputs.<input-name>.type` does not allow for the type `number`.

Please correct this example, as it has caused us rework and deployment issues.

**Comment by cmwilson21** [comment]
@sayhiben Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Thanks for letting us know about this, @sayhiben. Fix is in https://github.com/github/docs/pull/24217. 

The number input type is [allowed for reusable workflows (the workflow_call event)](https://github.com/SchemaStore/schemastore/blob/b4eccc2fb5ad76fd9c0a70fa67228e5d65e2b562/src/schemas/json/github-workflow.json#L1533-L1537) for that context, but [not for workflow_dispatch events](https://github.com/SchemaStore/schemastore/blob/b4eccc2fb5ad76fd9c0a70fa67228e5d65e2b562/src/schemas/json/github-workflow.json#L1608-L1611).
