### ISSUE TITLE
Installing the Neovim extension via Windows

### ISSUE THREAD

**Issue by ramesh2051** [github/docs#24079]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-neovim?platform=windows#installing-the-neovim-extension

### What part(s) of the article would you like to see updated?

The one that is now in Docs is listed below, and it cannot execute the following command in `Git Bash`. But, `Power Shell` seems to be operating fine.

```
git clone https://github.com/github/copilot.vim.git `
   $HOME/AppData/Local/nvim/pack/github/start/copilot.vim 
```
If it wishes to run on Git Bash, it should change with the command below.

```
git clone https://github.com/github/copilot.vim.git \
   $HOME/AppData/Local/nvim/pack/github/start/copilot.vim 
```
Instead, replace `Git Bash` with `Power Shell`.

**Comment by Jackpoot** [comment]
)

**Comment by cmwilson21** [comment]
@ramesh2051 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by isaacmbrown** [comment]
Hi @ramesh2051, thanks for opening this issue! You're right, we should use the `\` escape character here for Git Bash. I think the easiest is just to substitute the backtick for a `\` here. 

If you (or anyone else) would be willing to open a PR to fix this, that would be great! Here's the relevant file: https://github.com/github/docs/blob/main/content/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-neovim.md

**Comment by ramesh2051** [comment]
Hi @isaacmbrown PR was opened, look here https://github.com/github/docs/pull/24085
