### ISSUE TITLE
GPG Docs are partially outdated

### ISSUE THREAD

**Issue by Andre601** [github/docs#24095]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
- https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

#### Maintainer edit: updates required

I had a look into this and followed the instructions using GPG Suite for Mac. I also noticed a slightly different output, but I suspect this depends on the GPG software you use, because my output was also different to yours. I don't think the risk of confusion to users is too great, so I would recommend we keep the output as it is.

As for step 11 in https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account, the UI has indeed changed. I think we should update as follows:
- Before step 4, add a new step saying: `In the "Title" field, type a name for your GPG key.`
- In step 4, remove the screenshot, as this is not a difficult field for the user to find.
- Also remove the screenshot in step 5.
- Change step 6 to `To confirm the action, authenticate to your {% data variables.product.prodname_dotcom %} account.`

I'll add the `help wanted` label to this issue, and you or anyone else is welcome to create a PR to make the fix outlined above 🚀 

#### Original post

Step 11 lists an example output of the `gpg --list-secret-keys --keyid-format=long` shell command.

This output, however, seems to no longer be completely accurate, at least when using Gpg4win as the GPG software.

The command now outputs the following (I'm using wrong characters to avoid any accidental matches):
```shell
$ gpg --list-secret-keys --keyid-format=long
/c/Users/Someone/.gnupg/pubring.gpg
-----------------------------------
sec   rsa4096/=ABCD1234ABCD123 2023-02-22 [SC]
      =ABCD1234ABCD1234ABCD1234ABCD1234ABCD123
uid                 [ultimate] Someone (A GPG Key) <someone@example.com>
ssb   rsa4096/4321DCBA4321DCBA 2023-02-22 [E]
```

The above also applies to the example in https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key

----

https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

Step 4 displays an outdated image. The current modal is having a "Title" summary field which the screenshot is not displaying.

Additionally does step 6 only mention to "enter your GitHub password" while Users with GitHub Mobile may use the app to authorize the action.

**Comment by cmwilson21** [comment]
@Andre601 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by isaacmbrown** [comment]
Hi @Andre601, I had a look into this and followed the instructions using GPG Suite for Mac. I also noticed a slightly different output, but I suspect this depends on the GPG software you use, because my output was also different to yours. I don't think the risk of confusion to users is too great, so I would recommend we keep the output as it is.

As for step 11 in https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account, the UI has indeed changed. I think we should update as follows:
- Before step 11, add a new step saying: `In the "Title" field, type a name for your GPG key.`
- In step 11, remove the screenshot, as this is not a difficult field for the user to find.

I'll add the `help wanted` label to this issue, and you or anyone else is welcome to create a PR to make the fix outlined above 🚀

**Comment by sarkar868** [comment]
Tell

**Comment by alexis-opolka** [comment]
Hi, is it okay if I work on this issue and submit a PR afterward?

**Comment by cmwilson21** [comment]
👋 @alexis-opolka - you, or anyone else, are welcome to submit a PR addressing this issue 💖

**Comment by alexis-opolka** [comment]
Hi @isaacmbrown, Can you help me? I'm a bit confused about which screenshots should be removed in step 4 and step 5 as I don't see any.
![image](https://github.com/github/docs/assets/53085471/d1e7890a-9557-4c57-93fe-f7fe3daef5f2)

**Comment by isaacmbrown** [comment]
Hi @alexis-opolka, we've been updating a lot of screenshots on our site recently, so it looks like those ones were removed already. So no need to worry about those steps, but feel free to submit a PR with the update to what is now **step 7**. 🚀
