### ISSUE TITLE
Publishing Java packages with Maven/Gradle pages erroneously reference "Working with the npm registry" resource

### ISSUE THREAD

**Issue by ghost** [github/docs#24092]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This affects the [Publish Java packages with Gradle](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle) and [Publish Java packages with Maven](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven) pages.

### What part(s) of the article would you like to see updated?

In the Prerequisites section of each affected page, the first link under "You may also find it helpful to have a basic understanding of the following:" erroneously points to ["Working with the npm registry"](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry"). The link should point to ["Working with the Apache Maven registry"](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) in the "Publish Java packages with Maven" resource, and the link should point to ["Working with the Gradle registry"](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry) in the "Publish Java packages with Gradle" resource.

**Comment by ssssttp** [comment]
ش

**Comment by Froz1980** [comment]
0:13, 23 февраля 2023 г., ssssttp ***@***.***>:
ش

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by ssssttp** [comment]
@

**Comment by ssssttp** [comment]
@

**Comment by lucascosti** [comment]
Yes, the suggested change is a good one 👍
