### ISSUE TITLE
Right table of contents no longer showing event types

### ISSUE THREAD

**Issue by wheelerlaw** [github/docs#24125]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

### What part(s) of the article would you like to see updated?

There used to be a sidebar on the right that listed all of the event types and had anchors that would navigate directly to the event section. 

I noticed that it is missing. 

### Additional information

![image](https://user-images.githubusercontent.com/3081566/221031742-f64c4bf4-b73a-4bb7-8864-96446b49880c.png)

**Comment by cmwilson21** [comment]
@wheelerlaw Thanks for opening a PR and providing the screenshot! That's super helpful ⚡ 

We do have another issue currently open with this same report, so I'm going to go ahead and close this one. Please take a look at https://github.com/github/docs/issues/24043 for updates. 💛

**Comment by Michaelanna1** [comment]
1. @cmwilson21 

- [ ] 

> []() **__**

**Comment by Michaelanna1** [comment]
#22831

**Comment by Michaelanna1** [comment]
`fix problem `

**Comment by MsNash55** [comment]
#15324

**Comment by cmwilson21** [comment]
@wheelerlaw Just dropping in to report that the individual events are now listed in the side bar again 🎉
