### ISSUE TITLE
The link to the list of contributors in doc might be out of date

### ISSUE THREAD

**Issue by Kirikx** [github/docs#24136]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors

### What part(s) of the article would you like to see updated?

The link `https://github.com/REPO-OWNER/REPO-NAME/community_contributors` for any repository leads to a 404 page. Please check that it is not outdated. Thank you

Perhaps the pattern should look like this: `https://github.com/REPO-OWNER/REPO-NAME/graphs/contributors`

**Comment by Kirikx** [comment]
Examples 
- `https://github.com/MarcGiffing/bucket4j-spring-boot-starter/community_contributors` - other repo
- `https://github.com/Kirikx/bucket4j-spring-boot-starter/community_contributors` - my repo

**Comment by cmwilson21** [comment]
@Kirikx Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by sophietheking** [comment]
Thanks @Kirikx, it looks like the URL is indeed out of date and should be changed to `https://github.com/REPO-OWNER/REPO-NAME/graphs/contributors`. 👍 
You or anyone else is welcome to open a PR for that!

**Comment by Kirikx** [comment]
Thank you for watching.
Created PR: https://github.com/github/docs/pull/24198
