### ISSUE TITLE
The example match patterns for file match are misleading/incorrect

### ISSUE THREAD

**Issue by jlai403** [github/docs#24132]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths

### What part(s) of the article would you like to see updated?

For the following repo structure
```
.
├── index.js
└── index.jsx
    └── src/
        ├── file.js
        └── flie.jsx
```

the `'**.js'` match example doesn't return `.js` files in subdirectories, only to the root. I had to use `'**/**.js` for it to return all matches from the root and subdirectories in my repo.

the `?` character doesn't seem match for the preceding character.  `*.jsx?` does not return any matches and `*.js?` only returned `index.jsx`

**Comment by cmwilson21** [comment]
@jlai403 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
