### ISSUE TITLE
Explicitly state that changes to base permissions impact both new and existing members. 

### ISSUE THREAD

**Issue by adamrr724** [github/docs#24144]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.8/organizations/managing-user-access-to-your-organizations-repositories/setting-base-permissions-for-an-organization

### What part(s) of the article would you like to see updated?

Add a note explicitly stating changes will occur on both new and existing members.

**Comment by OlaAnobi** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/enterprise-server@3.8/organizations/managing-user-access-to-your-organizations-repositories/setting-base-permissions-for-an-organization
> 
> ### What part(s) of the article would you like to see updated?
> Add a note explicitly stating changes will occur on both new and existing members.
> 
> ### Additional information
> _No response_
. #24144

**Comment by Pavel-padev** [comment]
I am pleased to join you, mainly for the diversity of personality and culture, religion, beliefs, gender. The codes are put in place for good reason.
But we are all very different with different situations, desires and qualities, and talents.
I have a project I feel will be of great benefit. But I have many other resources and responsibilities. I have been very slow in starting, here, but the information I am gathering could not wait.
I look forward meeting everyone, and have a great respect for your organization.
Pavel

**Comment by kajflajf** [comment]
50 $   please  give me ❤️  5375411419566356

сб, 25 лют. 2023, 23:58 користувач Pavel-padev ***@***.***>
пише:

**Comment by Author10105905** [comment]
I had an issue in hydra trying to download the Enterprise 3.8 but I ran into a problem with the connection string on a line
Stopping the program from being excited.
So I had to load up 3.7 version up..

**Comment by DAVIDKARGBO** [comment]
Ok that nice

**Comment by Author10105905** [comment]
You welcome ! I think it's best to inscribe also ..
