### ISSUE TITLE
Pull Request 'converted_to_draft' action is missing from the webhook payload documentation

### ISSUE THREAD

**Issue by recurser** [github/docs#2416]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-object-31

### What part(s) of the article would you like to see updated?

There is an `action` called `converted_to_draft` that is not documented here:

> Can be one of `opened`, `edited`, `closed`, `assigned`, `unassigned`, `review_requested`, `review_request_removed`, `ready_for_review`, `labeled`, `unlabeled`, `synchronize`, `locked`, `unlocked`, or `reopened`.

This is the reverse of the `ready_for_review` action that is already documented - triggered when a pull request is converted back to a draft.

This has a follow-on effect in the [octokit/webhooks.js](https://github.com/octokit/webhooks.js/pull/399) library since the Typescript types are generated from Github documentation.

### Additional information

I originally filed a PR in [webhooks.js](https://github.com/octokit/webhooks.js/pull/399) that got closed, and following the chain ended up here.

I've filed #2417 to address this.

**Comment by recurser** [comment]
See #2417 for a PR to address this.

**Comment by chiedo** [comment]
Thanks @recurser! We'll have someone dig in!

**Comment by skedwards88** [comment]
Closed by https://github.com/github/docs/pull/2417
