### ISSUE TITLE
Added more info to Handling skipped but required checks

### ISSUE THREAD

**Issue by cb-shivamagarwal** [github/docs#24181]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

### What part(s) of the article would you like to see updated?

In the section `handling-skipped-but-required-checks`, the docs do not shed any light for the case mentioned below:

When someone sends a pull request that changes the files listed under `paths` and also changes a file that is not listed under `paths-ignore` in the other workflow. In such a case, both workflows must be executed and the associated status checks must pass in order to merge the PR.

**Comment by cmwilson21** [comment]
@cmwilson21 Thank you for opening an issue and linking it to your PR! ✨

**Comment by nov511** [comment]
> ``meth_00

**Comment by Alfredo415** [comment]
#25442
