### ISSUE TITLE
some of codeblocks in Japanese translation of "Authentication" docs are broken

### ISSUE THREAD

**Issue by Cj-bc** [github/docs#24190]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/ja/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key
- https://docs.github.com/ja/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
- https://docs.github.com/ja/authentication/managing-commit-signature-verification/associating-an-email-with-your-gpg-key

### What part(s) of the article would you like to see updated?

First of all, thank you to hosts Japanese document. It helps me a lot.
However, it looks like some code-block is not working properly.
I found several similar problems, and all of them was happening in all platform documentation (macOS, Windows, Linux)

### [gitへgpgキーを伝える](https://docs.github.com/ja/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key?platform=linux#git-へ-gpg-キーを伝える)

![github-docs-wrong-fence-1](https://user-images.githubusercontent.com/16875061/221740505-a2ea4855-5895-4042-8b64-8ef5930ff17c.png)

### [gitにsshキーについて知らせる](https://docs.github.com/ja/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key?platform=linux#git-に-ssh-キーについて知らせる)

![github-docs-wrong-fence-ssh](https://user-images.githubusercontent.com/16875061/221741939-858653ed-f24f-4d64-81aa-6dd4c9c6af6f.png)

### [GPGキーの生成](https://docs.github.com/ja/authentication/managing-commit-signature-verification/generating-a-new-gpg-key?platform=linux#generating-a-gpg-key)

![github-docs-wrong-fence-generate-key](https://user-images.githubusercontent.com/16875061/221742964-0bce54e8-e290-4a40-bf25-bffd36d42f97.png)

## "associating-an-email-with-your-gpg-key" page

![github-docs-wrong-fence-associate-email](https://user-images.githubusercontent.com/16875061/221744151-664a698f-0a43-4284-8906-e12df8405ab1.png)

**Comment by blessingaisosa** [comment]
![Uploading F463DDE2-369B-49AE-8BA0-BDC9F2A2488F.png…]()

**Comment by blessingaisosa** [comment]
Payment

**Comment by cmwilson21** [comment]
@Cj-bc Thank you for opening an issue and for your kind words about using the translations! 💖 

Thank you, also, for reporting the broken table. We have an internal process for our translations, so I will raise this feedback internally and we will address it there. I'll go ahead and close this issue ✨
