### ISSUE TITLE
dotnet cli guide does not have an example of how to publish with github actions and GITHUB_TOKEN

### ISSUE THREAD

**Issue by tandeday** [github/docs#2421]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-dotnet-cli-for-use-with-github-packages

### What part(s) of the article would you like to see updated?

I am learning on the job on migrating our .NET library build+publish to Github Actions and Github Packages.  I can generate and push a library from the command line on my own machine, but I would like to do it using Github actions where I am told to use GITHUB_TOKEN instead, but without an actual example on the recommended way to do it, and there is no dotnet documentation for Github Actions.

Also a bit of clarification on what the suggested changes actually _do_ would be nice for further learning.  Just links to the official documentation and a note on why.

**Comment by janiceilene** [comment]
Thanks for opening an issue @tandeday! I'll get this triaged for the team to take a look 👀

**Comment by hubwriter** [comment]
@tandeday - Many thanks for raising this. Sorry it's taken us a while to review this issue.

I've raised an internal issue for this, using the information you've provided, and with a link back to this issue. We'll discuss this internally and see what needs done. Thanks again for bringing this to our attention. I hope you managed to figure it out and that you've got Actions working well for you now.

I'm going to close this issue, and we'll work on the internal issue. If this is something that the community can document for us we'll reopen this issue.
