### ISSUE TITLE
YAML configuration file examples not previewing because of template expression

### ISSUE THREAD

**Issue by Matthieu-ui** [github/docs#24214]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Quickstart.md](https://github.com/github/docs/tree/main/content/rest/quickstart.md)
Line 229-262
Line 354-378

### What part(s) of the article would you like to see updated?

YAML parser needs to ignore the first line of code or it will not show the example!

Both sections can be fixed if this template expression is commented out with '#'
 # {% indented_data_reference reusables.actions.actions-not-certified-by-github-comment spaces=1 %}

**Comment by cmwilson21** [comment]
@Matthieu-ui, checking the documentation [here](https://docs.github.com/en/rest/quickstart?apiVersion=2022-11-28), the example is rendering just fine for me. Is it still breaking for you?

**Comment by Matthieu-ui** [comment]
I think I am looking at this wrong the markdown document renders on a separate page is that correct? If so this issue can close! When I ran across this document it was showing a blank but I must have not been looking in the right place.

**Comment by cmwilson21** [comment]
@Matthieu-ui Correct! ⚡ 

Everything in the md files in our content folders in our [repo](https://github.com/github/docs) will render on our production docs site, [GitHub Docs](https://docs.github.com/en). We use all sorts of Liquid syntax and different variables and reusables in the md files that render nicely on the site. I hope this information is helpful! I'm closing this issue now but please reach out if you come across any issues 💖
