### ISSUE TITLE
Contradictory information about workflow_dispatch inputs

### ISSUE THREAD

**Issue by MSutt** [github/docs#24225]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
https://docs.github.com/en/actions/learn-github-actions/contexts

### What part(s) of the article would you like to see updated?

This [section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs) of the article `workflow-syntax-for-github-actions` mention that `on.workflow_dispatch.inputs.<input_id>.type` "must be one of: `boolean`, `choice`, `environment`, or `string`."

And the [example](https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-inputs-context-in-a-manually-triggered-workflow) of the context article sets `type: number` for the `build_id` input.

Either the example or the available values for `type` are incorrect.

### Additional information

Are the objects schemas used in workflows defined in the code somewhere?
I briefly looked at the [actions/runner](https://github.com/actions/runner) repo but I did not find schemas. Although I am not sure that this the place to search.

**Comment by cmwilson21** [comment]
@MSutt Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by saudkamal1** [comment]
how to DNS promble solve

**Comment by randi274** [comment]
Looks like this was fixed with #24271 (https://github.com/github/docs/commit/6d33187adcdbe97601196a6eae8fcc6c905188e0), and the type: number was incorrect.

**Comment by cmwilson21** [comment]
@randi274 Great catch! Thanks for letting us know. ✨ 

@MSutt I'm going to go ahead and close this issue now, but please feel free to message here or open another one if you still encounter the program. 💛
