### ISSUE TITLE
steps missing in "Synchronizing a team with an identity provider group"

### ISSUE THREAD

**Issue by MichaelSp** [github/docs#24226]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.7/organizations/organizing-members-into-teams/synchronizing-a-team-with-an-identity-provider-group

### What changes are you suggesting?

The guide misses at least one step between 5 and 6.

5. go to team-settings
6. your done  ❓ 😕 ❓ 

What I should find/do there?

**Comment by cmwilson21** [comment]
@MichaelSp Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @MichaelSp! I think I probably broke this myself. 😅 I'll figure out what I did wrong and open a PR to fix now. 🙇🏻‍♀️

**Comment by lecoursen** [comment]
Closing this issue as we're going to track and update internally. Thanks again for letting us know @MichaelSp!

**Comment by MichaelSp** [comment]
Thanks @lecoursen
