### ISSUE TITLE
Provide a link to the context documentation on inputs when relevant

### ISSUE THREAD

**Issue by gbakeman** [github/docs#24243]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs

### What part(s) of the article would you like to see updated?

When the contexts subject is referred to, it would be helpful if the relevant documentation article is hyperlinked. I'll open a PR shortly that does this.

**Comment by cmwilson21** [comment]
@gbakeman Thank you for opening an issue and linking it to your PR! ✨
