### ISSUE TITLE
Don't talk about Environment protection rules in Free, Pro and Team documentation

### ISSUE THREAD

**Issue by Sharpe49** [github/docs#24302]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-protection-rules
https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments

### What part(s) of the article would you like to see updated?

This documentation appears on the Free, Pro and Team pages while this feature (Environment protection rules) is not available with those plans.

**Comment by cmwilson21** [comment]
@Sharpe49 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by jc-clark** [comment]
Hey @Sharpe49, thank you for bringing this up! 

My current understanding is that environment protection rules are available for FPT but for public repos only. We do qualify this in our documentation in the note in "[About environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#about-environments)" 

> Note: You can only configure environments for public repositories. If you convert a repository from public to private, any configured protection rules or environment secrets will be ignored, and you will not be able to configure any environments. If you convert your repository back to public, you will have access to any previously configured protection rules and environment secrets.

Is that understanding incorrect?

**Comment by Sharpe49** [comment]
You're right. I was looking at one of the private repositories of one of my teams.

Then, the documentation should be clearer because it's talking about configuring environments (which you can do with private repositories), but not about configuring environment protection rules.

**Comment by jc-clark** [comment]
I see what you're saying. I'll check in with our Actions docs team about this and see what sort of improvements might work best here.

**Comment by James-Firth** [comment]
I'd like to add a +1 to this.

I was looking at using Environments as part of a manual approval process for my Pro team, but I was confused when I couldn't see that option until I found this.

**Comment by jc-clark** [comment]
Thanks for the discussion! I didn't format the `Closes` tag in the PR for these changes correctly, so this issue was left open although the changes are now in production. Closing this now! ✨
