### ISSUE TITLE
[REST] "List requested reviewers for a pull request" does not paginate

### ISSUE THREAD

**Issue by gr2m** [github/docs#2433]
Follow up to https://github.com/octokit/rest.js/issues/1978 /cc @nikclayton-dfinity 

### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#list-requested-reviewers-for-a-pull-request

### What part(s) of the article would you like to see updated?

Remove `per_page` and `page` parameters

### Additional information

I didn't verify that the parameters do not have any effect, because it's rather hard to setup a pull request with multiple review requests without bothering anyone else. If you could check in with the API team I'd appreciate it

**Comment by felicitymay** [comment]
Hi @gr2m 👋🏻 

Thanks for flagging this issue and for including the link to the detailed information in the Octokit repository. 🙇🏻‍♀️ 

I checked with the ecosystem API team and they agree with you. The source files for the API docs are maintained in a different repository, so I'm going to open an internal issue for this change and close this.

**Comment by gr2m** [comment]
@felicitymay the docs still include the `per_page` and `page` parameters. Will these be removed eventually? I still have an open issue at https://github.com/octokit/rest.js/issues/33 and I'd like to give the Octokit user an update on their question
