### ISSUE TITLE
Grammatical error in delete branches topic

### ISSUE THREAD

**Issue by adityaraute** [github/docs#24410]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository

### What part(s) of the article would you like to see updated?

Point number 3 in the section 'Deleting a Branch'

The sentence is grammatically incorrect. Needs rewriting.

**Comment by cmwilson21** [comment]
@adityaraute Thank you for opening an issue and linking it to your PR! ✨
