### ISSUE TITLE
Two curl examples missing forward slash

### ISSUE THREAD

**Issue by emmjohnson** [github/docs#24424]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation#generating-an-installation-access-token
- https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation#authenticating-with-an-installation-access-token

### What part(s) of the article would you like to see updated?
<img width="639" alt="Screenshot 2023-03-13 at 11 44 39 PM" src="https://user-images.githubusercontent.com/51918476/224895554-7885cab4-8398-49e8-92b0-74e6d657c65b.png">
<img width="603" alt="Screenshot 2023-03-13 at 11 44 47 PM" src="https://user-images.githubusercontent.com/51918476/224895559-2fc612a1-3b77-452b-96dd-807b18dcf40c.png">

Both curl examples missing forward slash after base url

**Comment by cmwilson21** [comment]
@emmjohnson Thank you for opening an issue and linking it to your PR! ✨
