### ISSUE TITLE
clarify that `if` operates before `matrix`

### ISSUE THREAD

**Issue by jsoref** [github/docs#24441]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

### What part(s) of the article would you like to see updated?

> You can use the jobs.<job_id>.if conditional to prevent a job from running unless a condition is met. You can use any supported context and expression to create a conditional. For more information on which contexts are supported in this key, see "[Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)."

Add a paragraph noting that [`matrix`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) operates after `if`.

### Additional information

https://github.com/community/community/discussions/48705

**Comment by cmwilson21** [comment]
👋 Hey @jsoref - Thanks for the issue! I'll triage it for review 👀

**Comment by jsoref** [comment]
@cmwilson21 😢

**Comment by jsoref** [comment]
@cmwilson21 😞

**Comment by cmwilson21** [comment]
@jsoref got it! Sorry about that!

**Comment by hubwriter** [comment]
@jsoref - Thanks for raising this issue based on the community post. I think this is worth clarifying in https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif.

Markdown file: 
https://github.com/github/docs-internal/blob/main/data/reusables/actions/jobs/section-using-conditions-to-control-job-execution.md?plain=1

I've marked this issue `help-wanted`. A PR for this, based on the information provided about, would be gratefully received. 👍

**Comment by jsoref** [comment]
@cmwilson21 I've created https://github.com/github/docs/pull/27168 which would probably result in me being slightly less frustrated with this repository. I understand that some other bot will shoot it, but I'm hoping that you can see about applying some similar change to the workflow.
