### ISSUE TITLE
Improve workflow performance of GitHub Actions for Node.js App Service

### ISSUE THREAD

**Issue by horihiro** [github/docs#24449]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-nodejs-to-azure-app-service

### What part(s) of the article would you like to see updated?

The configuration has a possibility which makes GitHub Actions slower because the workflow uploads many files as an artifact which are installed by `npm install`.

So let me suggest the following to improve the GitHub Actions performance:

  1. Add `npm prune --production` command after `npm run test --if-present` to remove files installed as `devDependencies` modules and which are unnecessary for production environment
  1. Add zip command step (like `zip release.zip ./* -qr`) to archive deployment files before `upload artifact` step, and change `upload artifact` step in `build` job and `Deploy to Azure Web App` step in `deploy` job to use the zip file
 
The workflow applied the above improving points to is:
https://github.com/horihiro/20220504-githubactions-test/blob/main/.github/workflows/main_app-githubactions-test.yml

**Comment by cmwilson21** [comment]
@horihiro Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
