### ISSUE TITLE
Typo in github docs under article "Showing your private contributions and achievements on your profile"

### ISSUE THREAD

**Issue by FENETMULER** [github/docs#24462]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/showing-your-private-contributions-and-achievements-on-your-profile#changing-the-visibility-of-your-private-contributions

### What part(s) of the article would you like to see updated?

![image](https://user-images.githubusercontent.com/85392410/225365500-fe169b94-6f6c-4fbc-b77c-488a16fce914.png)

**Replace** the underlined word with '**contributions**'. Since '**contributions**' is the topic and not '**contributors**'.

**Comment by cmwilson21** [comment]
@FENETMULER Thank you for opening an issue and linking it to your PR! ✨

**Comment by conradivy** [comment]
#24463

**Comment by giolicer** [comment]
```

```
