### ISSUE TITLE
Use node16 for actions

### ISSUE THREAD

**Issue by WaterLemons2k** [github/docs#24539]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs
- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-ruby
- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-swift
- https://docs.github.com/actions/creating-actions/about-custom-actions
- https://docs.github.com/actions/creating-actions/creating-a-javascript-action
- https://docs.github.com/actions/creating-actions/metadata-syntax-for-github-actions
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-docker-to-azure-app-service
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-java-to-azure-app-service
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-net-to-azure-app-service
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-nodejs-to-azure-app-service
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-php-to-azure-app-service
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-python-to-azure-app-service
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-to-azure-kubernetes-service
- https://docs.github.com/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine
- https://docs.github.com/actions/examples/using-the-github-cli-on-a-runner
- https://docs.github.com/actions/learn-github-actions/expressions
- https://docs.github.com/actions/learn-github-actions/finding-and-customizing-actions
- https://docs.github.com/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added
- https://docs.github.com/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards
- https://docs.github.com/actions/managing-issues-and-pull-requests/scheduling-issue-creation
- https://docs.github.com/actions/migrating-to-github-actions/manual-migrations/migrating-from-circleci-to-github-actions
- https://docs.github.com/actions/publishing-packages/publishing-docker-images
- https://docs.github.com/actions/publishing-packages/publishing-java-packages-with-gradle
- https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions
- https://docs.github.com/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
- https://docs.github.com/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions
- https://docs.github.com/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
- https://docs.github.com/packages/working-with-a-github-packages-registry/working-with-the-container-registry
- https://docs.github.com/rest/quickstart

### What part(s) of the article would you like to see updated?

Update actions that're still using `node12` to `node16`.

### Additional information

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by cmwilson21** [comment]
@WaterLemons2k Thank you for opening an issue and linking it to your PR! ✨
