### ISSUE TITLE
Expand description of configuring Copilot

### ISSUE THREAD

**Issue by 403-html** [github/docs#24549]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/quickstart

### What part(s) of the article would you like to see updated?

The configuration process when a user has two licenses. A private one and one from the organization where he works. I wanted to use the business copilot in business workspaces and use my private license for the rest of my private projects. But I couldn't find information on this topic.

### Additional information

Just found out that Github cancel the private license when organization provide copilot license. It should be in there I think.

**Comment by cmwilson21** [comment]
@403-html Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
