### ISSUE TITLE
Update Copilot Neovim docs to include Vim as well

### ISSUE THREAD

**Issue by ychin** [github/docs#24624]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/overview-of-github-copilot/about-github-copilot-for-individuals
https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-neovim
https://docs.github.com/en/copilot/configuring-github-copilot/configuring-github-copilot-in-neovim
https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-github-copilot-in-neovim

### What part(s) of the article would you like to see updated?

Add Vim-specific information alongside Neovim ones. Rename most other references of "Neovim" to "Vim/Neovim".

**Comment by AS0820075980** [comment]
Chaiwat oppo A16

ในวันที่ พฤ. 23 มี.ค. 2023 18:32 น. welcome[bot] ***@***.***>
เขียนว่า:

**Comment by cmwilson21** [comment]
@ychin Thank you for opening an issue and linking it to your PR! ✨

**Comment by ychin** [comment]
Still waiting for the pull request to be merged.
