### ISSUE TITLE
Add new procedural article "Filtering the assignment overview" for GitHub Classroom docs

### ISSUE THREAD

**Issue by sabrowning1** [github/docs#24637]
This issue is reserved for our MLH Fellowship program ✅ 

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This will be a new article in the GitHub Classroom section of the docs site called "Filtering the assignment overview."

This article could be placed in the "Teach with GitHub Classroom" topic, under "Edit an assignment."

### What part(s) of the article would you like to see updated?

This issue is reserved for the MLH Fellowship program.

#### Why

Currently, the only information about the assignment overview page in the GitHub Classroom docs exists in the "[Monitoring students' progress](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment#monitoring-students-progress)" sections of "[Create an individual assignment](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment)" and "[Create a group assignment - GitHub Docs](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-a-group-assignment)." While these sections are useful for understanding the assignment overview page at a glance, they don't include any procedural information on filtering the assignment overview page for specific criteria. Creating a new procedural content on filtering the assignment overview page will provide teachers with more tools and showcase another useful feature in GitHub Classroom.

#### Use cases and audience

This article is needed to show teachers how they can filter the assignment overview for specific criteria so they can better track their students' progress. It also showcases a useful feature in GitHub Classroom, potentially generating interest for prospective users.

#### Getting started

You can get started by learning more about [procedural content](https://github.com/github/docs/blob/main/contributing/content-model.md#procedural) in our content model.

You can then view our [Procedural content template](https://github.com/github/docs/blob/main/contributing/content-templates.md#procedural) and follow it to create the article.

The article should be created in the [education/managing-your-coursework/teach-with-github-classroom](https://github.com/github/docs/tree/main/content/education/manage-coursework-with-github-classroom/teach-with-github-classroom) directory.

The “Filtering the assignment overview” article should have the following sections, at least:

- **About filtering the assignment overview**: this should be a brief [conceptual](https://github.com/github/docs/blob/main/contributing/content-model.md#conceptual) intro to filters on the assignment overview page. We can introduce the assignment overview page and explain why a teacher might filter it.
- **Applying filters to the assignment overview**: this should be a procedural section with instructions on filtering the assignment view. We should include instructions on using the dropdown menu filters available next to the search bar, and on filtering with the search bar itself. Feel free to reach out to me with any questions on available filters/testing 🙂

### Additional information

This is for a special project and not currently available for contributors to work on.

**Comment by sabrowning1** [comment]
👋🏼 @OlayinkaAtobiloye, here's the issue for the article I mentioned earlier! Let me know if you have any questions 🙂

**Comment by dy214** [comment]
Yea, no clue wtf to do with any of this

**Comment by dy214** [comment]
Still don’t understand

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sabrowning1** [comment]
We completed this internally, so I'll close it out now 🙂
