### ISSUE TITLE
Host key is incorrect in the testing SSH connections page

### ISSUE THREAD

**Issue by dalemyers** [github/docs#24646]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection

### What changes are you suggesting?

Update host key to `SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s`

**Comment by cmwilson21** [comment]
Thanks for opening an issue and linking it to your PR! Closing this issue per comment [here](https://github.com/github/docs/pull/24647#issuecomment-1485151945). 💖
