### ISSUE TITLE
`filename:` qualifier does not work anymore.

### ISSUE THREAD

**Issue by Vyom-Yadav** [github/docs#24666]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/searching-on-github/searching-code#search-by-filename

### What changes are you suggesting?

Modify the file https://github.com/github/docs/blob/main/content/search-github/searching-on-github/searching-code.md#search-by-filename and other files which have this content.

`filename:` searching no longer works.

Link of example from docs: https://github.com/search?utf8=%E2%9C%93&q=filename%3Alinguist&type=Code

Output:
![Screenshot from 2023-03-25 09-25-02](https://user-images.githubusercontent.com/73882557/227691255-85a31474-4f36-4c19-8ab9-c71da513d0ee.png)

**Comment by Elenore23** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/search-github/searching-on-github/searching-code#search-by-filename
> 
> ### What changes are you suggesting?
> Modify the file https://github.com/github/docs/blob/main/content/search-github/searching-on-github/searching-code.md#search-by-filename and other files which have this content.
> 
> `filename:` searching no longer works.
> 
> Link of example from docs: https://github.com/search?utf8=%E2%9C%93&q=filename%3Alinguist&type=Code
> 
> Output: ![Screenshot from 2023-03-25 09-25-02](https://user-images.githubusercontent.com/73882557/227691255-85a31474-4f36-4c19-8ab9-c71da513d0ee.png)
> 
> ### Additional information
> _No response_

**Comment by cmwilson21** [comment]
@Vyom-Yadav Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by roiros** [comment]
The example for searching by file-size doesn't work as well.
https://docs.github.com/en/search-github/searching-on-github/searching-code#search-by-file-size

The [search example link](https://github.com/search?q=function+size%3A%3E10000+language%3Apython&type=Code)
gets
```
Possible unrecognized qualifier, searching for this term literally
function size:>10000 language:python
```

**Comment by subatoi** [comment]
@Vyom-Yadav @roiros Please accept our apologies for the delay in getting back to you. I looked at the [referenced issue](https://github.com/checkstyle/checkstyle/issues/13059) and I think you may have already reached the correct conclusion, but just in case not: 

The documentation you've linked to (everything under https://docs.github.com/en/search-github/searching-on-github/searching-code) is for a legacy implementation of code search. I think this may not have been the case when you first encountered this problem; the functionality you'd need is in any case described under https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#path-qualifier. 

We'll see if we can do anything to improve the experience with the legacy documentation, but for now I'll close this issue. Please feel free to add another comment if there's anything outstanding you'd like to raise.

Thank you for your interest in helping to improve our docs! ✨
