### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Eiygyveyron** [github/docs#2468]

**Comment by thantkyaw1** [comment]
Open

**Comment by thantkyaw1** [comment]
Close

**Comment by thantkyaw1** [comment]
Opened this issue

**Comment by thantkyaw1** [comment]
gi

**Comment by mohdjuwaiser** [comment]
open

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
