### ISSUE TITLE
10005> ### چه مقاله ای در docs.github.com تحت تأثیر قرار می گیرد؟

### ISSUE THREAD

**Issue by amein0** [github/docs#2470]
> ### چه مقاله ای در docs.github.com تحت تأثیر قرار می گیرد؟
> مقاله مربوط به [جستجوی درخواست های کشش](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-based-on-whether-a-pull-request-is-merged-or-unmerged) دارای اطلاعات و مثالهای گسترده ای در مورد چگونگی جستجوی درخواستهای کشش است ، از جمله توانایی جستجو برای روابط عمومی ادغام شده (یا نشده). هیچ مقاله ای معادل برای جستجوی شعب وجود ندارد. به نظر می رسد که جستجوی شعبه پشتیبانی نمی کند `is:unmerged`یا موارد مشابه (اگرچه اگر این پشتیبانی شود بسیار خوب است) ، اما هیچ اسنادی برای توضیح نحو جستجوی شاخه وجود ندارد.
> 
> ### دوست دارید کدام قسمت از مقاله را به روز کنید؟
> من می خواهم اسنادی را در مورد نحوه جستجوی شاخه ها ببینم ، یعنی نحو پرس و جو برای چیست:
> `https://github.com/myorganization/myrepo/branches/all?query=???`
> 
> ### اطلاعات تکمیلی

پرونده هنوز احتیاج به برسی دارد کمی زمان  بر است و باید به دقت مرور شود نگران نباشید ما به صورت روح در حال برسی هستیم

_Originally posted by @amein0 in https://github.com/github/docs/issues/1880#issuecomment-752151892_

**Comment by janiceilene** [comment]
This is off topic and will be closed.
