### ISSUE TITLE
mention dependency-name for docker image tags

### ISSUE THREAD

**Issue by cvirtucio** [github/docs#24735]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

### What part(s) of the article would you like to see updated?

The section about the `dependency-name` section talks about the format of a few dependency types, notably Java. I think a brief mention about the format for docker image tags would help developers attempting to use the `ignore` field in `dependabot.yml` on docker builds. I've mentioned an example [here](https://github.com/dependabot/dependabot-core/issues/6909#issuecomment-1487346279), but I think this information has persistent value.

Expected outcome is the `dependency-name` having a sentence or two to the effect of:

```txt
For docker image tags, the format is the full name of the repository; for example, given an image tag of <account ID>.dkr.ecr.us-west-2.amazonaws.com/base/foo/bar/ruby:3.1.0-focal-jemalloc, enter base/foo/bar/ruby.
```

### Additional information

I mentioned an example [here](https://github.com/dependabot/dependabot-core/issues/6909#issuecomment-1487346279) and [it was suggested that I open a PR to update the docs](﻿https://github.com/dependabot/dependabot-core/issues/6909#issuecomment-1487355986).

**Comment by cmwilson21** [comment]
@cvirtucio Thanks for opening an issue and linking it to your PR! ⚡ 

We also appreciate all the extra context included here! 💖
