### ISSUE TITLE
Minor grammatical issue in CodeQL CLI extractor options documentation

### ISSUE THREAD

**Issue by marcransome** [github/docs#24757]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/extractor-options

### What part(s) of the article would you like to see updated?

There is a missing space character in the opening paragraph of the [About extractors](https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/extractor-options#about-extractors) section of the CodeQL CLI extractor options documentation, immediately following the tool name ('CodeQL CLI'):

> The CodeQL CLIuses special programs...

**Comment by cmwilson21** [comment]
@marcransome Thank you for opening an issue and linking it to your PR! ✨
