### ISSUE TITLE
Replace CodeQL product name with CodeQL CLI command name in examples

### ISSUE THREAD

**Issue by marcransome** [github/docs#24777]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/creating-codeql-databases

### What part(s) of the article would you like to see updated?

Several example CodeQL CLI commands in the [Creating CodeQL databases](https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/creating-codeql-databases) page use the CodeQL product name in place of the CLI command name (i.e. `CodeQL` instead of `codeql`). Such commands may only work on case-insensitive filesystems. For consistency, the actual CodeQL CLI command casing should be used (`codeql`), which is also used in many other pages.

**Comment by cmwilson21** [comment]
@marcransome Thank you for opening an issue and linking it to your PR! ✨
