### ISSUE TITLE
Fix multiple grammatical issue in CodeQL CLI extractor options documentation

### ISSUE THREAD

**Issue by jaychaturvedi** [github/docs#24781]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/extractor-options

### What part(s) of the article would you like to see updated?

There are minor grammatical issues which includes missing fullstop, commas throughout the document.
**1. Missing fullstop**
<img width="741" alt="Screenshot 2023-03-31 at 12 52 44 AM" src="https://user-images.githubusercontent.com/89414182/228942124-c6f37381-6c2b-440a-92f4-15862ad761b9.png">

**2. Typo at the end of sentence can be fixed** 
From: `appear on the command line, then`  
To: `appear on the command line.`
<img width="740" alt="Screenshot 2023-03-31 at 12 54 22 AM" src="https://user-images.githubusercontent.com/89414182/228942473-1e2a414b-ea4e-486c-acf8-ae4ba1622647.png">

**3. Use of capital character in middle of sentence can be fixed** 
From: `special `__allow_unknown_properties` Boolean field.` 
To: `special `__allow_unknown_properties` boolean field.`
<img width="755" alt="Screenshot 2023-03-31 at 12 57 31 AM" src="https://user-images.githubusercontent.com/89414182/228943299-b2208de9-c71b-4463-a8d3-721beeb90192.png">

**Comment by cmwilson21** [comment]
@jaychaturvedi Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by keshavcodex** [comment]
I Appreciate your efforts @jaychaturvedi 
> 1. Missing fullstop

but i think these are points so making a full stop there won't be much suitable.
> 2. Typo at the end of sentence can be fixed

This is about the executions step of yaml file so, keeping it as it is seems better to me.

> 3. Use of capital character in middle of sentence can be fixed

Here Boolean is in upper case because it is referencing to Object and naming convention of Object is to keep it in upper case.

If this was your first open source work don't get dishearted keep up the good work.

**Comment by jaychaturvedi** [comment]
@keshavcodex Thanks for your input.
@cmwilson21 Will like to know your point of view on below listing
I agree with your opinion on 3rd point 'Use of capital character in middle of sentence can be fixed'
However I cross checked with the other CODEQL documentation format and found below observation respectively 
1. Other subpoints have fullstop at the end
<img width="734" alt="Screenshot 2023-04-03 at 2 21 58 AM" src="https://user-images.githubusercontent.com/17979760/229379098-f5dab6c6-c0b5-4804-bbda-42ded433f23d.png">

2. The `, then ` at the end executions steps are unnecessary as per correct gram. Also the title clearly mentions that steps are processed in order.
<img width="791" alt="Screenshot 2023-04-03 at 2 40 26 AM" src="https://user-images.githubusercontent.com/17979760/229379196-d05d9beb-b4fe-47b8-9388-30cfe26582bf.png">
mar

**Comment by MdAmiruddin** [comment]
Good work @jaychaturvedi.
