### ISSUE TITLE
Yarn3 publish command

### ISSUE THREAD

**Issue by hindicator** [github/docs#24811]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content\actions\publishing-packages\publishing-nodejs-packages.md

### What part(s) of the article would you like to see updated?

// For Yarn3 use -
// yarn npm publish
- run: yarn publish

lines 180 - 183

### Additional information

I should fork the repo only for such a small suggestion instead of branch push and PR ?
I believe the comment fits, your choice.
Have a great day =).

**Comment by cmwilson21** [comment]
@hindicator Thanks for opening an issue! We have instructions for Yarn included. Would you mind clarifying the change you are suggesting?

**Comment by hindicator** [comment]
@cmwilson21 
Yarn 3 command for publish is
`yarn npm publish`
Unlike the written command `yarn publish`

**Comment by cmwilson21** [comment]
Gotcha! Thank you for clarifying! I see the difference now 😄 

I'll get this triaged for review! :zap:

**Comment by skedwards88** [comment]
Thanks for opening this issue! It [looks like](https://github.com/yarnpkg/yarn#%E2%84%B9%EF%B8%8F-important-note) Yarn 1 is not being maintained, so I would be ok with updating this example to use `yarn npm publish` (which was introduced in Yarn 2), and adding a comment to use `yarn publish` for Yarn 1. (Basically just the inverse of what you recommended.) e.g. something like

```yml
      - run: yarn
      - run: yarn npm publish // for Yarn version 1, use `yarn publish` instead
```

You or anyone else is welcome to open a PR with this change.
