### ISSUE TITLE
Explain what conditions must be met to show hover icon to create issue behind tasklist items

### ISSUE THREAD

**Issue by HonkingGoose** [github/docs#24862]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

### What part(s) of the article would you like to see updated?

The docs say:

> If a task requires further tracking or discussion, you can convert the task to an issue by hovering over the task and clicking _button-icon-here_ in the upper-right corner of the task.

The docs don't explain if there are any rules you need to follow to allow GitHub to show that hover icon, like:

- only put issue or PR link after the tasklist
- don't use special characters like `(` or `)`
- don't do ...

Or maybe this is a "rights" issue where you need a certain level of access to the repository before you see that button?

### Additional information

Why I'm asking about any possible rules: @viceice (maintainer of the repository) is **not** seeing the hover icon behind items in their tasklist:

- https://github.com/containerbase/base/issues/875

With the current docs I can't determine if this is:

- bad formatting of the tasklist
- a problem with access rights to the repository
- bug in GitHub

----
_Update from a maintainer_

## Content change suggested to fix this issue

We need to make it clearer to users how to convert a tasklist item to an issue. We'll do this by adding a brief new section to the article [About task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists).

1. After the section "Reordering tasks", add a new heading level 2 "Converting tasks into issues".
2. Add a brief explanation of how to convert a task into an issue.
3. Add the following screenshot to the folder for images about writing: https://github.com/github/docs/tree/main/assets/images/help/writing.
    ![task-list-convert](https://github.com/github/docs/assets/1877141/5c074ac2-2252-4f3f-b99e-edda28dc8255)
4. Include the image below the explanation and make sure you add suitable alt text (see [Images](https://docs.github.com/en/contributing/writing-for-github-docs/style-guide#images)). 
 
You may find it useful to look at the alt text for other images on the page for inspiration, for example: 
    https://github.com/github/docs/blob/275f369a2b5e01bfd108f8f957383d61ba5746f2/content/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists.md?plain=1#L64

**Comment by cmwilson21** [comment]
👋 @HonkingGoose Thanks so much for opening an issue! And thanks for the extra context and providing the example case. 

I'll triage this for the team to take a look :eyes:

**Comment by omerbensaadon** [comment]
Hey @HonkingGoose, PM here, I would recommend you use the new [tasklists](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists) as they are meant to replace this version and resolve many of the UX sharp edges you're running into :)

**Comment by HonkingGoose** [comment]
@omerbensaadon Here's where I found the text: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists#creating-tasklists-with-markdown, search for `full link`. That same page also shows a "finished tasklist" that only uses the full link:

```
### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```

**Comment by omerbensaadon** [comment]
Gotcha, I'll submit an edit to that doc which shows a shorthand link to make it clearer we can expect both

**Comment by felicitymay** [comment]
Hi @HonkingGoose

I was checking through open issues and wondered if this one is now resolved. 

I can see that you've worked with another Hubber to improve the documentation for the new tasklists - thank you 💖 

Is there anything else we should consider before we close this issue?

**Comment by HonkingGoose** [comment]
@felicitymay the docs for the current iteration of task lists are still lacking information.

But if the plan is that everyone migrates to the new task lists that's in beta, we would need to check those docs.

So the short answer is: I don't really know. 🙂

**Comment by felicitymay** [comment]
Hi @HonkingGoose - apologies for dropping the ball on this issue 😞 

Using a test account that doesn't have access to the private beta for task lists, I copied in some of the text from the issue that you linked in your summary above. As far as I can tell, there is no problem with your syntax and this ought to work as expected for anyone who has access to create issues. The repository owner, `@viceice`, should have access to this functionality.

<img width="858" alt="image" src="https://github.com/github/docs/assets/1877141/6e7fea66-89a3-4722-91ac-83ac0d139b90">

It sounds as if we should add a brief section to [About task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists) that includes a screenshot with the "Convert to issue" icon displayed.

**Comment by HonkingGoose** [comment]
> It sounds as if we should add a brief section to [About task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists) that includes a screenshot with the "Convert to issue" icon displayed.

Sounds good to me. 😄

**Comment by CBID2** [comment]
I'll work on this @cmwilson21! :)
