### ISSUE TITLE
PowerShell examples does not follow best practices

### ISSUE THREAD

**Issue by bjompen** [github/docs#24883]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/actions/using-workflows/workflow-commands-for-github-actions.md

### What part(s) of the article would you like to see updated?

PowerShell / pwsh examples does not follow best practices on a number of things on how to write good PowerShell code.
Some examples are
- Stream redirects (>>) instead of using commands ( | Out-File )
- Aliases used in code (for example `rm` -> `Remove-Item` and `set` -> `Set-Variable`)
- Positional parameters instead of named

This makes them not only harder to read and understand, but also leads to decreased code quality and increased risk of unexpected behaviours.

**Comment by cmwilson21** [comment]
@bjompen Thanks for opening an issue and submitting a PR! ✨

**Comment by hosein6666** [comment]
-pull-request-reviews.md
