### ISSUE TITLE
Adding Link to Environment Page for "Actions / Permission Statement Secrets Environments"

### ISSUE THREAD

**Issue by aatmmr** [github/docs#24908]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-environment

### What part(s) of the article would you like to see updated?

The **Environment** option visibility in the settings depends on the repository visibility and product subscription. In order to help users understand why the option might not be visible, a link to the "[Using Environments for Deployment](https://docs.github.com/en/enterprise-cloud@latest/actions/deployment/targeting-different-environments/using-environments-for-deployment)" page would help to identify the reason.

**Comment by cmwilson21** [comment]
@aatmmr Thank you for opening an issue and linking it to your PR! ✨
