### ISSUE TITLE
Curl basis authentication example to authorize user not working

### ISSUE THREAD

**Issue by MartinStenzig** [github/docs#24920]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/rest/overview/authenticating-to-the-rest-api.md

### What part(s) of the article would you like to see updated?

The basic authentication curl example does not work I simply get a response 
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}

**Comment by 5HT2** [comment]
You should read further and look at the following in the docs: 
![image](https://user-images.githubusercontent.com/17222512/230531783-0821a43a-66c9-4513-ad48-141b78b2b0f0.png)

It works just fine for me. 
![image](https://user-images.githubusercontent.com/17222512/230531727-a5aea27b-5602-424c-a2cf-c4e7da876773.png)

**Comment by 5HT2** [comment]
Oh, you meant the basic github app example. I seem to get a 401: 
![image](https://user-images.githubusercontent.com/17222512/230533194-e313ce9e-bbb5-42bb-b032-fcd9887140ac.png)

**Comment by 5HT2** [comment]
This also seems to be the only place in the docs that `--user` is ever mentioned, which is shorthand for `-H "Authorization: Basic $(echo -n $CLIENT_ID:$CLIENT_SECRET | base64 -w0)"`

**Comment by skedwards88** [comment]
I think there are a few things going on here:

- It looks like the `/authorizations` endpoint is only available on GHES now. We should update this example to use an endpoint that is available for all versions. e.g. the endpoints on [this page](https://docs.github.com/en/rest/apps/oauth-applications?apiVersion=2022-11-28#delete-an-app-token)
- It looks like the example is missing a `\` after the `--url` line
- (Maybe) it looks like quotes are missing around `CLIENT_ID:CLIENT_SECRET`

Anyone is welcome to open a PR to address these issues.
