### ISSUE TITLE
> …s-and-teams/managing-access-to-your-organizations-repositories.md to المحتوى/جيثب/إنشاء وإدارة المنظمات والفرق/managing-access-to-your-organizations-repositories.md

### ISSUE THREAD

**Issue by jace4511** [github/docs#2494]
> …s-and-teams/managing-access-to-your-organizations-repositories.md to المحتوى/جيثب/إنشاء وإدارة المنظمات والفرق/managing-access-to-your-organizations-repositories.md
> 
> ### Why:
> ### What's being changed:
> ### Check off the following:
> * [x]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

_Originally posted by @jace4511 in https://github.com/github/docs/pull/2492#issuecomment-753469257_

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
