### ISSUE TITLE
The Markdown formatting is not ignored in the issue title using the escape character. Example: \`test\`.

### ISSUE THREAD

**Issue by 5AbhishekSaxena** [github/docs#24940]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

File: https://github.com/github/docs/blob/main/content/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md#ignoring-markdown-formatting

Page: https://github.com/github/docs/blob/main/content/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md#ignoring-markdown-formatting

The above-mentioned section talks about how one can tell Github to ignore the Markdown by using `\` but using this character. This works everywhere but not in the title of the issue and I am assuming in the title of the PRs.

An example of the issue is in the title of _this_ issue itself.

### What changes are you suggesting?

The Github should acknowledge the escape character (`\`) as it does at the other places and allow the users to ignore the Markdown formatting in the title of the issues.

**Comment by steveward** [comment]
Thanks for the issue @5AbhishekSaxena, I'll get this triaged for 👀

**Comment by 5AbhishekSaxena** [comment]
No problem @steveward, happy to contribute 😁.

**Comment by skedwards88** [comment]
Thanks for opening this issue! You or anyone else is welcome to note this exception in the docs.

**Comment by 5AbhishekSaxena** [comment]
I was thinking instead of adding this exception in the docs, the issue should be fixed in the code itself where the backticks are processed which formats the title of the issue/pull but acknowledge the escaping character, and skip the formatting.

**Comment by 5AbhishekSaxena** [comment]
I have raised a PR which adds a note informing the user about the issue.  I have also started a discussion on the community page which can be found here: https://github.com/orgs/community/discussions/54689.
