### ISSUE TITLE
Docs do not list `internal` as a `visibility` option for the `POST /orgs/{org}/repos` REST API endpoint

### ISSUE THREAD

**Issue by ataylorme** [github/docs#24990]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-an-organization-repository

### What changes are you suggesting?

`visibility` is listed as `private` or `public`. `internal` should be included as GitHub organizations can have `internal` visibility set for repositories.

Additionally, calling the `POST /orgs/{org}/repos` REST API endpoint with `visibility` set as `internal` does work, making the documentation inaccurate.

### Additional information

I am using TypeScript and the GitHub Octokit NodeJS SDK for a project, which is giving a TypeScript type error when trying to set the `visibility` to `internal` for the `POST /orgs/{org}/repos` REST API endpoint.

The incorrect type is generated and can be found in https://raw.githubusercontent.com/octokit/openapi-types.ts/v16.0.0/packages/openapi-types/types.d.ts at line `97636`, where it is declared as `visibility?: "public" | "private";`

I believe the GitHub API needs to be updated, which will also update the generated documentation and TypeScript types.

**Comment by steveward** [comment]
Thanks for the issue @ataylorme, I'll get this triaged for review!

**Comment by lecoursen** [comment]
👋🏻 @ataylorme, internal repositories are only available in GitHub Enterprise Cloud and GitHub Enterprise Server. The corresponding versions of that article ([GHEC](https://docs.github.com/en/enterprise-cloud@latest/rest/repos/repos?apiVersion=2022-11-28), [GHES](https://docs.github.com/en/enterprise-server@3.8/rest/repos/repos)) do list internal as an option. Let me know if you have any questions about that!

**Comment by ataylorme** [comment]
Thanks for the reply @lecoursen. I’m using https://github.com/octokit/types.ts and internal is not a valid type for visibility on the create repo in org endpoint. I’m assuming the TypeScript type repo is generated. Any idea how to have it show the proper types for enterprise cloud?

**Comment by lecoursen** [comment]
Hm, I'm not sure @ataylorme! I'd suggest opening an issue in https://github.com/octokit/openapi-types.ts about that.
