### ISSUE TITLE
Fix link in creating-a-personal-access-token.md

### ISSUE THREAD

**Issue by d-lamb** [github/docs#25000]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

### What part(s) of the article would you like to see updated?

The link that has the text "command line" in the first paragraph of the subject article contains a same-page link to  #using-a-token-on-the-command-line

but it should be to
#using-a-personal-access-token-on-the-command-line

**Comment by dostonnabotov** [comment]
Hi, there! I would be happy to pick and fix this issue.

**Comment by steveward** [comment]
@dostonnabotov feel free to submit a PR with this fix, thanks!

**Comment by 60355322264** [comment]
Github tüm hesabı devre dışı bırakmak istiyorum

**Comment by 60355322264** [comment]
Benimle ilgili silin

**Comment by 60355322264** [comment]
Hesap silin

**Comment by 60355322264** [comment]
Android silin
