### ISSUE TITLE
Mention that domain verification is available for non-Enterprise organizations.

### ISSUE THREAD

**Issue by teo-tsirpanis** [github/docs#25020]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization

### What part(s) of the article would you like to see updated?

The article says that domain verification is only available for Enterprise organizations, which is not true; I managed to verify a domain for an organization of mine which certainly is not in an enterprise. The article should be updated.

**Comment by lecoursen** [comment]
👋🏻 @teo-tsirpanis, would you mind sharing the non-GHEC organization where you were able to verify a domain? Thanks!

**Comment by teo-tsirpanis** [comment]
It's https://github.com/farkle-parser.

**Comment by lecoursen** [comment]
Thanks! We're going to track and fix this internally, so I'll close this OS issue. Thanks for bringing it to our attention!
