### ISSUE TITLE
All the description of available scope is squashed in French version of scopes-for-oauth-apps.md 

### ISSUE THREAD

**Issue by MarionPlt** [github/docs#25048]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/fr/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps

### What part(s) of the article would you like to see updated?

**Description**
The French version of this article presents some typo problems : all the description of "available scope" is squashed in one big sentence. 

**Why should the docs be changed ?** 
It's difficult to read it and we have to switch in English to get a clearer page. 

**Expected outcome**
The same typo than the English version.

**Comment by alexis-opolka** [comment]
@cmwilson21 Sorry for the ping, but would it be possible for me to work on this issue?
I would only need to know where I can modify the French version. ^-^

**Comment by cmwilson21** [comment]
@alexis-opolka Thanks for your interest here! Unfortunately we don't accept contributions to our translated content. We use an internal translation service, so all changes need to be made internally. I'll raise this issue with the team for review 💖 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your interest in improving GitHub Docs! ✨
