### ISSUE TITLE
Command typo in get-started/using-git/pushing-commits-to-a-remote-repository

### ISSUE THREAD

**Issue by fei6409** [github/docs#25052]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository#deleting-a-remote-branch-or-tag

### What part(s) of the article would you like to see updated?

To delete a remote branch, `git push REMOTE-NAME:BRANCH-NAME` should be `git push REMOTE-NAME :BRANCH-NAME`.

**Comment by phetchaiphet6669-prog** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository#deleting-a-remote-branch-or-tag
> 
> ### What part(s) of the article would you like to see updated?
> To delete a remote branch, `git push REMOTE-NAME:BRANCH-NAME` should be `git push REMOTE-NAME :BRANCH-NAME`.
> 
> ### Additional information
> _No response_

"'i'"
