### ISSUE TITLE
"Discussion(s) Answered" badge included in section "Displaying badges on your profile" despite being replaced

### ISSUE THREAD

**Issue by altruisticnode** [github/docs#25069]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Article on the site: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile#displaying-badges-on-your-profile

Markdown permalink at time of writing: https://github.com/github/docs/blob/36a4641103ef482d8ec3e60db94718f22b87e223/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md

### What part(s) of the article would you like to see updated?

There are [various entries](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile#displaying-badges-on-your-profile) listed which appears under the "Highlights" section of a user's profile. The **"Discussion answered"** badge seems to have been replaced completely with the addition of the Galaxy Brain Achievement. A user in [this discussion](https://github.com/orgs/community/discussions/31629#discussioncomment-3542839) notes that support had confirmed for them that the badge has been removed in lieu of Galaxy Brain's addition. This is also evident by simply viewing the profiles of users who have had marked answers in discussions: [Example 1](https://github.com/airtower-luna) and [Example 2](https://github.com/Akash1134).

The documentation should be modified to reflect this change. A simple removal of the badge and it's description. I could do a quick Pull Request, but I wanted to double check if this change is in the green and perhaps if this might've been left there intentionally.

### Additional information

Relevant discussions speaking about the missing/removed badge:
https://github.com/orgs/community/discussions/28450
https://github.com/orgs/community/discussions/31629

**Comment by cmwilson21** [comment]
@altruisticnode Thank you for opening an issue and offering to submit the PR! I'll get this triaged for review! :zap:

**Comment by skedwards88** [comment]
Thanks for taking the time to open an issue about this! It looks like it is an oversight in the docs. You or anyone else is welcome to open a PR to update the docs to reflect this change.
