### ISSUE TITLE
Misleading wording regarding permissions and access to secrets in `pull_request` workflows

### ISSUE THREAD

**Issue by monholm** [github/docs#25117]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#accessing-secrets

### What part(s) of the article would you like to see updated?

The phrase `Workflows triggered using the pull_request event have read-only permissions and have no access to secrets` is incorrect, as this is only the case for workflows triggered from a fork.

The phrase should be updated to clarify that this is not the case for pull requests from a branch within the repository.

**Comment by cmwilson21** [comment]
@Simon-TechForm Thank you for opening an issue and linking it to your PR! ✨

**Comment by MFEAlzhrani** [comment]
حين تكون الاجراءات اللامركزية حاضرة في التواصل مع الاخرين فان الاعدادات المركزيه ... سيي
