### ISSUE TITLE
Is `choice` single or multiselect?

### ISSUE THREAD

**Issue by randi274** [github/docs#25125]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Both of these articles were not clear on if there was a single or multi pick choice available: 
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
- https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context

### What changes are you suggesting?

After testing, I realized it was single select. I'd just like to add a note that the choice resolves to a singular string.

**Comment by cmwilson21** [comment]
👋 @randi274 - Thank you for opening an issue and submitting a PR! ✨

**Comment by oliveselow87** [comment]
#
