### ISSUE TITLE
crates.io is not listed as a supported secrets scanning partner

### ISSUE THREAD

**Issue by lopopolo** [github/docs#25138]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/secret-scanning/secret-scanning-patterns#supported-secrets

### What part(s) of the article would you like to see updated?

The table in the _Supported secrets_ section does not list crates.io, the Rust package registry, as a supported partner.

I believe crates.io supports secret scanning, as it was implemented in late 2022 and has seen continued iteration recently:

- https://github.com/rust-lang/crates.io/issues/3400
- https://github.com/rust-lang/crates.io/pull/5638
- https://github.com/rust-lang/crates.io/pull/5639

### Additional information

cc @Turbo87, crates.io team co-lead, who worked on this feature.

@Turbo87 I'm not sure what the current state of the GitHub secrets scanning integration is and I hope I'm not jumping the gun on asking the GitHub folks to add crates.io as a supported secrets scanning partner.

I do want to defer to you on whether this ticket should be actioned on / is appropriate. I opened this ticket because I wasn't sure if the integration was complete and the documentation step got missed.

Thanks for making this happen!

**Comment by Turbo87** [comment]
yep, it's implemented and running in production. according to our logs we already revoked a couple of tokens due to that.

**Comment by cmwilson21** [comment]
@Turbo87 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by mchammer01** [comment]
Thanks, I'll talk to the secret scanning folks 😃

**Comment by mchammer01** [comment]
@lopopolo 👋🏻 - we're fixing this omission internally, and you should see crates.io in the table of supported partner tokens later today in https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/secret-scanning-patterns#supported-secrets. Thanks for spotting this ✨ 
I am going to close this issue.

**Comment by lopopolo** [comment]
Thanks everyone! 🦀💪🔒
