### ISSUE TITLE
Go version as number instead of string in yaml example

### ISSUE THREAD

**Issue by SHA65536** [github/docs#25145]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

### What part(s) of the article would you like to see updated?

The first YAML example has the go version as a number, which is a problem when the version is 1.20, as it will convert to number (1.2) and then back to string, making the action use the wrong Go version.

**Comment by cmwilson21** [comment]
@SHA65536 Thank you for opening an issue and linking it to your PR! ✨
