### ISSUE TITLE
Update Sudo Mode documentation to include session timeout length

### ISSUE THREAD

**Issue by adamrr724** [github/docs#25141]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/authentication/keeping-your-account-and-data-secure/sudo-mode

### What part(s) of the article would you like to see updated?

Just need to update "a few hours" wording to explicitly state 2 hours session timeout. 

### Additional information

https://github.com/github/authnd/issues/1895#issuecomment-1516968032

**Comment by cmwilson21** [comment]
👋 @adamrr724 - Thank you for opening an issue and linking it to your PR! ✨
