### ISSUE TITLE
Using the vars context to access configuration variable values example vulnerable to script injection

### ISSUE THREAD

**Issue by jessehouwing** [github/docs#25163]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

* https://docs-25162-41b74f.preview.ghdocs.com/en/actions/learn-github-actions/variables#using-the-vars-context-to-access-configuration-variable-values

### What part(s) of the article would you like to see updated?

Using the vars context to access configuration variable values - Example YAML

**Comment by Nguyenpham89** [comment]
![Uploading IMG_1768.![IMG_1707](https://github.com/github/docs/assets/125356525/74258535-2b7c-4e48-aae7-dd1eaf4bc607)
