### ISSUE TITLE
Incorrect rendering of the translated "Supported package ecosystems" table

### ISSUE THREAD

**Issue by lennis-dev** [github/docs#25170]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I noticed that the table at https://docs.github.com/de/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems (german) is rendered incorrectly in all translated versions (English excluded). 

I use the browsers Firefox and Chrome on Linux, both version 112.

### What changes are you suggesting?

That the problem is fixed and the table is rendered without errors.

**Comment by cmwilson21** [comment]
@lennis-dev Thank you for reporting this! We use an internal automated solution for translations, so I'll report this feedback internally and file an issue. I'm going to go ahead and close out this issue 💛
