### ISSUE TITLE
With @nat's [announcement today](https://github.blog/2020-12-17-no-cookie-for-you/), it appears the [GitHub Subprocessors/Cookies page](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-subprocessors-and-cookies) needs updating. Or this still accurate and processing simply moved server-side?

### ISSUE THREAD

**Issue by stevenans9859** [github/docs#2522]
With @nat's [announcement today](https://github.blog/2020-12-17-no-cookie-for-you/), it appears the [GitHub Subprocessors/Cookies page](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-subprocessors-and-cookies) needs updating. Or this still accurate and processing simply moved server-side?

_Originally posted by @riverar in https://github.com/github/docs/discussions/2197_

**Comment by riverar** [comment]
What's going on here? Why did you take over the issue?

**Comment by stevenans9859** [comment]
> What's going on here? Why did you take over the issue?

Due to some security issues so I had  to re analyse my repo for fair usage to all the hard work contributor and all user.

**Comment by riverar** [comment]
@stevenans9859 And what does that have to do with *my* issue?

**Comment by stevenans9859** [comment]
Well nothing actually just my issues, what wrong Sent from my Huawei phone-------- Original message --------From: Rafael Rivera <notifications@github.com>Date: Mon, 4 Jan 2021, 17:51To: github/docs <docs@noreply.github.com>Cc: Global Management Agency <stevenans5895@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [github/docs] With @nat's [announcement today](https://github.blog/2020-12-17-no-cookie-for-you/), it appears the [GitHub Subprocessors/Cookies page](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-subprocessors-and-cookies) needs updating. Or this still accurate and processing simply moved server-side? (#2522)
@stevenans9859 And what does that have to do with my issue?

**Comment by mislav** [comment]
Flagged for spam.

@riverar I'm sorry for the nuisance.
