### ISSUE TITLE
Missing various REST API endpoints related to GitHub Team memberships

### ISSUE THREAD

**Issue by Brend-Smits** [github/docs#25239]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#members

### What part(s) of the article would you like to see updated?

[Members section](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#members) is missing information about the new non-legacy `/orgs/{org}/teams/{team_slug}/membership/{username}` endpoints as documented here: https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28

### Additional information

Perhaps the above documentation should also mention that some API endpoints are Legacy/Deprecrated like on this documentation described here: https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#get-team-member-legacy

**Comment by cmwilson21** [comment]
@Brend-Smits Thank you for opening an issue and linking it to your PR! ✨
