### ISSUE TITLE
light theme interface invisible menu

### ISSUE THREAD

**Issue by Alena-dino** [github/docs#25235]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

![Screenshot 2023-04-26 153610](https://github.com/github/docs/assets/131392536/24836e66-7a79-4c9b-9f8f-78c92c5a8ba0)
https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages
i use chrome browser on win 11 with default dark system theme. after i changed github theme to light, interface become almost invisible 
all the docs articles have this issue 

### What changes are you suggesting?

fix theme

**Comment by cmwilson21** [comment]
@Alena-dino Thanks for opening an issue! We have an ongoing internal issue where we are working on this. It seems to happen most when someone's system settings are on dark mode and the GitHub page on light mode. 💡 🕶️ 

I'm going to go ahead and close this as we are aware and working on it internally. But thanks for your interest in improving the docs site! 💖
