### ISSUE TITLE
Account overview activity bug

### ISSUE THREAD

**Issue by ilonaholovii** [github/docs#2523]
### What is the current behavior?
Once I open an user overview page I see the activity from year before. Check the link https://github.com/gaearon. Activity from 2020 is shown instead of 2021

### What changes are you suggesting?
When url query parameters are set everything works fine https://github.com/gaearon?tab=overview&from=2021-01-01&to=2021-01-03. I suggest to display the activity from current year by default.

### Additional information

I'm not sure where I had to create the issue, maybe it should be moved to the right project issues

**Comment by janiceilene** [comment]
👋 @ilonaholovii Is there a particular article in docs.github.com you'd like to see updated? If you are experiencing a problem with GitHub, unrelated to our documentation, please contact [GitHub Support directly](https://support.github.com/contact).

**Comment by janiceilene** [comment]
👋 I'm going to close this now, feel free to open a new issue if there's a docs.github.com article you'd like to see updated!
