### ISSUE TITLE
The list of GitHub-hosted macOS runners is out of date

### ISSUE THREAD

**Issue by ZhongRuoyu** [github/docs#25254]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software

### What part(s) of the article would you like to see updated?

The list of GitHub-hosted runners on ["About GitHub-hosted runners", section "Preinstalled software"](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software) is out of date. macOS 10.15 support has been dropped (actions/runner-images#5583), and macOS 13 runner is now available (actions/runner-images#6426).

**Comment by cmwilson21** [comment]
@ZhongRuoyu Thank you for opening an issue and linking it to your PR! ✨
