### ISSUE TITLE
Mention that ssh hardware keys can't be used on macOS to sign commits

### ISSUE THREAD

**Issue by nathanblair** [github/docs#25278]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent

### What part(s) of the article would you like to see updated?

> When adding your SSH key to the agent, use the default macOS ssh-add command, and not an application installed by [macports](https://www.macports.org/), [homebrew](http://brew.sh/), or some other external source

This can't be true while also [suggesting](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key-for-a-hardware-security-key)

> If you are using macOS or Linux, you may need to update your SSH client or install a new SSH client prior to generating a new SSH key. For more information, see "[Error: Unknown key type](https://docs.github.com/en/authentication/troubleshooting-ssh/error-unknown-key-type)."

They are incompatible with each other for the case of `ssh-sk` keys.

This should be called out in the documentation that `-sk` keys aren't supported for `git` signing on macOS.

### Additional information

I think the recommendation may have more to do with the interaction of the macOS `ssh-agent` being able to access the macOS Keychain, which can then cache the key's passphrase. If that's the case, perhaps there's a way to get around this limitation? Like adding the ssh key to the updated `ssh-agent` but accepting it not being able to access the macOS Keychain.

This probably means needing to type a passphrase for each signing, along with the `-sk` security prompts. This may be desirable or a suitable workaround for some but I'm not convinced that route is possible either.

I've been wholly unsuccessful in getting anything to work to use `ssh-sk` keys for signing `git` commits.

**Comment by cmwilson21** [comment]
@nathanblair Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by nathanblair** [comment]
Ha.

Turns out - you have to accurately reference which ssh key is present on the security key 😬 

I did not do that - spent _hours_ trying to figure out why none of this documentation was working for me.

In the end, I prove myself a bonehead once more.

Thanks @cmwilson21 for taking a peek and kicking this off but I'm going to close because I think this report doesn't have merit for changing the documentation in the recommended way.

There may still be some merit in mentioning special case information for `-sk`-type SSH keys but that probably belongs in a separate request 😇

I'll close this out for now but if we want to expand on the macOS Security Key case for the documentation - I've been through the ringer with it and could potentially submit a PR with my findings for what I believe to be a simple approach.

**Comment by cmwilson21** [comment]
@nathanblair 😄 Thanks so much for coming back and letting us know! I'm glad you were able to get it figured out! 

We appreciate your offer for submitting a separate PR as well. I'll take that feedback to the team. 

Thanks again, @nathanblair! ✨
