### ISSUE TITLE
Update node version examples from 10 - 16x to 14 - 20x

### ISSUE THREAD

**Issue by Rylab** [github/docs#25313]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

### What changes are you suggesting?

The node versions used in this build guide are severely out of date and no longer supported. For users creating a new project, they'd be much better off with a more recent default example set to base off.

https://github.com/github/docs/pull/25312

### Additional information

https://nodejs.dev/en/about/releases/

I used this as a guide for which versions to use as examples when making my update recs PR.

**Comment by cmwilson21** [comment]
@Rylab Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Rylab** [comment]
Happy to help!

I also pasted the updated example yaml into an action in my own public personal repo, running NextJS. The 14.x build failed, expectedly (like the 10.x and 12.x would have in most new repos trying to use this example too). Works with 16, 18, 20.

https://github.com/Rylab/Rylab/pull/44/files

**Comment by cmwilson21** [comment]
Thanks for providing the extra context and linking to your tests!
