### ISSUE TITLE
Issue while searching for an issue

### ISSUE THREAD

**Issue by kshitiz305** [github/docs#25330]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

With the following query sting as mentioned in the 
`https://github.com/issues?page=7&q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+language%3Apython`
![image](https://github.com/github/docs/assets/38988779/340188de-e3ba-470b-8e7c-5fb5f682b3d6)

### What changes are you suggesting?

When clicking the `https://github.com/issues?page=1559&q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+language%3Apython` page 1559 it provides with an error despite being the page shown in the page

<img width="960" alt="image" src="https://github.com/github/docs/assets/38988779/eac778df-5694-46f2-b98e-5a05ab8bcde6">

![image](https://github.com/github/docs/assets/38988779/dead4ff3-625a-4902-bd1c-d34c080ebc78)

### Additional information

I would like to know the search query to get it solved.

**Comment by cmwilson21** [comment]
@kshitiz305 Thanks for opening an issue! This sounds like it may be a bug, though. You can report bugs [here](https://support.github.com/contact/bug-report). I'm going to go ahead and close this issue 💛 

If there's any change to the documentation you'd like to suggest, please feel free to open another issue.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
