### ISSUE TITLE
Update about-slash-command.md with example

### ISSUE THREAD

**Issue by nishantp15** [github/docs#25389]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/tracking-your-work-with-issues/about-slash-commands

### What part(s) of the article would you like to see updated?

Additional information is required on how to use the command to make it beginner friendly.

<img width="450" alt="Screenshot (174)" src="https://github.com/github/docs/assets/111297080/d67e0686-bace-41ca-8d79-90d4a804632b">

The above table does not provide any additional information

**Comment by cmwilson21** [comment]
@nishantp15 Thank you for opening an issue and linking it to your PR! ✨

**Comment by cmwilson21** [comment]
Closing per https://github.com/github/docs/pull/25391#issuecomment-1536306809
