### ISSUE TITLE
Bad display of information

### ISSUE THREAD

**Issue by a10pepo** [github/docs#25395]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/es/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes

### What part(s) of the article would you like to see updated?

Available scope table is not correctly rendered

**Comment by cmwilson21** [comment]
@a10pepo Thank you for opening an issue and linking it to your PR! ✨

**Comment by sreyans853** [comment]
_i am praising and inspired from the command_

**Comment by cmwilson21** [comment]
Closing per comment https://github.com/github/docs/pull/25396#issuecomment-1536278870
