### ISSUE TITLE
[GitHub Actions] Typo in the supported inputs types (`environment` should be `number`)

### ISSUE THREAD

**Issue by iamazeem** [github/docs#25435]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Article:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

Heading:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype

### What part(s) of the article would you like to see updated?

[`on.workflow_dispatch.inputs.<input_id>.type`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype) reads:

> The value of this parameter is a string specifying the data type of the input. This must be one of: `boolean`, `choice`, `environment`, or `string`.

The `environment` is not a valid type. It should be `number` as correctly listed under [`inputs` context](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context).

**Comment by cmwilson21** [comment]
@iamazeem Thank you for opening an issue and linking it to your PR! ✨

**Comment by nathanchapman** [comment]
`environment` **_is_** a valid type, I'm not sure why this change was accepted by the GitHub team 😕 
https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/

Is `number` even valid? Are they not treated as strings?
I can't find a changelog entry or any documentation for `number` before this issued was opened.

See #25938
