### ISSUE TITLE
Duplicated step in "Applying for GitHub Octernships" article

### ISSUE THREAD

**Issue by Basit-Balogun10** [github/docs#25437]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/education/explore-internship-projects-with-github-octernships/applying-for-github-octernships

### What part(s) of the article would you like to see updated?

There is a duplicated step under the [Finding and applying for a Github Octernship](https://docs.github.com/en/education/explore-internship-projects-with-github-octernships/applying-for-github-octernships#finding-and-applying-for-a-github-octernship) section - particularly, Step 5 is duplicated in the 7th Step.

### Additional information

Screenshot here: https://prnt.sc/yMtZca7_fG2t

**Comment by cmwilson21** [comment]
@Basit-Balogun10 Thank you for opening an issue and linking it to your PR! ✨

**Comment by Basit-Balogun10** [comment]
@cmwilson21 It’s an absolute pleasure 😄 We’re here to contribute 🤞🏾
