### ISSUE TITLE
Organization secret scanning setting not available

### ISSUE THREAD

**Issue by PatMyron** [github/docs#2547]
### What article on docs.github.com is affected?

[Managing secret scanning for your organization](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/managing-secret-scanning-for-your-organization)

### What part(s) of the article would you like to see updated?

`Note: Secret scanning for private repositories is currently in beta and subject to change.`

---

This setting is not present in [our organization settings](https://github.com/organizations/aws-cloudformation/settings/security_analysis). Does beta mean this feature is not available to all organizations?

**Comment by hubwriter** [comment]
Hi @PatMyron - thanks for getting in touch. 

Secret scanning is only available in public repositories, and in private repositories owned by organizations with an Advanced Security license. The Secret scanning controls should be displayed on the Security & analysis page for your organization if you have public repositories, or you have private repositories and you have an Advanced Security license.

I don't have access to your organization settings (linked above). Could you provide a little more information about whether you have public repos or an Advanced Security license? Thanks.
