### ISSUE TITLE
Missing line continuation in REST API authentication docs

### ISSUE THREAD

**Issue by fearnoeval** [github/docs#25482]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Authenticating to the REST API: Authenticating with a token generated by an app](https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api?apiVersion=2022-11-28#using-basic-authentication)

### What changes are you suggesting?

Add a line continuation to the example `curl` command's `--url` line.

**Comment by cmwilson21** [comment]
@fearnoeval Thank you for opening an issue and linking it to your PR! ✨
