### ISSUE TITLE
[GitHub Actions] secrets and env contexts not working with jobs.<job_id>.container or jobs.<job_id>.container.image

### ISSUE THREAD

**Issue by iamazeem** [github/docs#25520]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Article: **Contexts**
https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

Subheading: **Context Availability**
https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

### What part(s) of the article would you like to see updated?

According to [context availability](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability), `secrets` and `env` contexts should be available under [`jobs.<job_id>.container`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer) [[commit](https://github.com/github/docs/commit/b4dbc7aaa9b8a5c0c6f15eff9c47d7951c0cd8e2)]:

![image](https://github.com/github/docs/assets/7128328/ed8e19bb-b2a9-49df-a009-0af54beee83d)

However, both `secrets` and `env` contexts are not recognized under `container` or `container.image`.

For example, all of these render a workflow invalid:

- using `secrets` context

```yml
    container: ${{ secrets.IMAGE }}:latest
```

or,

```yml
    container:
      image: ${{ secrets.IMAGE }}:latest
```

Error:

![image](https://github.com/github/docs/assets/7128328/db8cc1d1-3de0-4fc6-9334-a8c1c03660c2)

- using `env` context

```yml
    env:
      IMAGE: ubuntu

    container: ${{ env.IMAGE }}:latest
```

or,

```yml
    container:
      image: ${{ env.IMAGE }}:latest
```

Error:

![image](https://github.com/github/docs/assets/7128328/74f0cb4a-e41b-40a1-a316-4950115d2a34)

---

Either the implementation or the docs needs to update accordingly. Thanks!

**Comment by cmwilson21** [comment]
@iamazeem Thanks so much for opening an issue! We appreciate the screenshots and tests.

I'll triage this for the team to take a look :eyes:

**Comment by Edsonkillian** [comment]
Edson Arontes Killian South Africa ZAR Hawston Dukeweg C70 Capitec Bank reference number 1484690018

**Comment by hubwriter** [comment]
@iamazeem - Thanks for opening this issue! 

It would be good to clarify this in the docs. I've added details 👆 of a couple of changes it would be good to make. 

You or anyone else is welcome to open a PR to make these updates.
Thanks again.
👍

**Comment by iamazeem** [comment]
@hubwriter: Thank you!

As for the docs, this change looks good. 👍

Any idea why it is not possible to specify an image even with `secrets` or `vars`?
That seems like a valid use case that I have seen in StackOverflow multiple threads also.

**Comment by KittyChiu** [comment]
Hello @hubwriter Today, I have tried `needs` on top of `github` context also work for `jobs.<job_id>.container.image`.

**Comment by iamazeem** [comment]
Looks like only `env` and `secrets` contexts are not available under `container` and `container.image`.

Need to test the rest of the contexts as well.
I'll try to test those too and update here.

**Comment by iamazeem** [comment]
Tested and verified with `vars`, `github`, `matrix`, and `inputs` contexts. Worked fine. 
`strategy` doesn't have any nested key to test it with e.g. `matrix` so that's not verified.

**Comment by iamazeem** [comment]
@hubwriter: Please review PR #26152. Thanks!

**Comment by hubwriter** [comment]
@iamazeem - That's great - many thanks for the PR.
I'll get that merged/published.
🙇
