### ISSUE TITLE
New code search and code view

### ISSUE THREAD

**Issue by orwagodfather** [github/docs#25586]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Hello 

Can we have a update about new code search issue 

**1** 
new code search just open first 5 pages and mostly the most old 5 pages codes 

**2** 
no recently indexed option in code search

**3**
the date of repo not printed out the repo in ui 

so i just wanna know if github look for this as real issues or false issue 
and if that a real issues when we can have the new fixing - no need to back to old ui if this issues fixed 

Thanks 

Orwa 

### What changes are you suggesting?

add recently indexed in code search as start 

### Additional information

theres a lot of comments and open tickets about this and no response at all about this

**Comment by Kaminem2021** [comment]
00989025012929

**Comment by cmwilson21** [comment]
@orwagodfather Thanks for opening an issue! However, we maintain the Docs site and documentation. For any bugs or requests for GitHub products and features, please leave your feedback [here](https://github.com/orgs/community/discussions).

Closing this issue now 💛 

If you have suggestions for updating the docs, please feel free to open a new issue ✨

**Comment by lim84210** [comment]
Update 25586
