### ISSUE TITLE
Responsivness Problem

### ISSUE THREAD

**Issue by Emad-Eldin-G** [github/docs#25596]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The problem is all across the Github website, the right sidebar interferes with some content when resizing browser, blocks some links and buttons. 
Browser: Firefox
Device: Macbook Pro 14

### What changes are you suggesting?

Return everything back to normal, the responsiveness was perfect like a week ago, now it gets messed up sometimes.

**Comment by cmwilson21** [comment]
@Emad-Eldin-G Thanks for opening an issue. Are the problems you are experiecing within the Docs site or the GitHub UI? We maintain the Docs site and the documentation within. For bugs or feedback related to GitHub site or products, please leave your feedback [here](https://github.com/orgs/community/discussions)
