### ISSUE TITLE
Code snippets in "Telling Git about your signing key" are not rendering properly

### ISSUE THREAD

**Issue by dbetancurdev** [github/docs#25618]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

There seems to be a problem with the translation on the [Telling Git about your signing key](https://docs.github.com/es/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key?platform=linux) section that affects the code snippets:

![evidence](https://github.com/github/docs/assets/125151874/2e5ad919-b9d5-4ab9-b179-121972aec93f)

Other languages have the same issue. Platforms(Mac, Windows and Linux) do not make any difference.

### What changes are you suggesting?

Check how the translation works in that specific section to fix the code snippets.

**Comment by cmwilson21** [comment]
@dbetancurdev Thanks for bringing this to our attention! We use an internal automated solution for translations, so I'l get this flagged for our team. I'm going to go ahead and close this issue. Thank you for reporting it! 💖

**Comment by Njbabyyyy** [comment]
> @dbetancurdev Thanks for bringing this to our attention! We use an internal automated solution for translations, so I'l get this flagged for our team. I'm going to go ahead and close this issue. Thank you for reporting it! 💖
