### ISSUE TITLE
[GitHub Actions] Output from called reusable workflows via env context or GITHUB_ENV is not supported

### ISSUE THREAD

**Issue by iamazeem** [github/docs#25620]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

**Reusable Workflows**
https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Reusable Workflows: Limitations**
https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

**Reusable Workflows: Using outputs from a reusable workflow**
https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow

### What part(s) of the article would you like to see updated?

According to the [Limitations](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations):

> Any environment variables set in an `env` context defined at the workflow level in the caller workflow are not propagated to the called workflow.

The opposite is also not supported but it's not listed under the [Limitations](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations) section.

[Using outputs from a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow) also does not mention anything about `env` context or `GITHUB_ENV` as it's mainly focused on the [output parameters](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter).

Adding this (i.e. `env` context or `GITHUB_ENV` cannot be used to set env vars for output purposes) under the **Limitations** section would be helpful.

Thanks!

**Comment by cmwilson21** [comment]
@iamazeem Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by hubwriter** [comment]
@iamazeem - Thanks for raising this. Would the following fix this issue?

In [Limitations](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations), after the existing bullet point "Any environment variables set in an `env` context defined at the workflow level in the caller workflow are not propagated to the called workflow." add:

> - Similarly, environment variables set in the `env` context defined in the called workflow are not accessible in the `env` context in the caller workflow. Instead you must use outputs of the reusable workflow. For more information, see "`[AUTOTITLE](/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow)`."

Then at the end of the list of limitations, add:

> - Reusable workflows are called directly within a job, and not from within a job step. You cannot, therefore, use `GITHUB_ENV` to pass values to job steps in the caller workflow.

**Comment by iamazeem** [comment]
@hubwriter: LGTM. :+1:  That would definitely help.

**Comment by hubwriter** [comment]
@iamazeem - Thanks for confirming.

Feel free for yourself (or anyone else) to open a PR to make this change.  🙇‍♂️

If you haven't contributed to the docs before, please take a look at our [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by iamazeem** [comment]
@hubwriter: PR #25700 created.
