### ISSUE TITLE
Broken link and missing documentation around API management of global webhooks.

### ISSUE THREAD

**Issue by rt-jknepley** [github/docs#25638]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/exploring-user-activity/managing-global-webhooks

and/or

https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin#global-webhooks

### What part(s) of the article would you like to see updated?

From `https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/exploring-user-activity/managing-global-webhooks`

> You can also use the APIs to manage global webhooks. For a complete list of actions, see "GitHub Enterprise administration."

...which links to `https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin#global-webhooks`, but the target page doesn't contain that anchor.

I can't find any documentation regarding managing clobal webhooks via API.

**Comment by megamanics** [comment]
With this update

# REST API link shows for GHES & GHAE only
<img width="1164" alt="image" src="https://github.com/github/docs/assets/10250297/932176a2-664d-485c-9898-1b65ac2ee91b">

# REST API link is not shown for GHEC
<img width="1045" alt="image" src="https://github.com/github/docs/assets/10250297/6491fd09-4b39-41d4-840f-ae64f7718830">

**Comment by Uddeshya08** [comment]
Hi team, I would like to work on this issue.
