### ISSUE TITLE
GitHub's main page breaking

### ISSUE THREAD

**Issue by KhushPatibandha** [github/docs#25636]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

when you visit [GitHub](/../../..) the main page breaks for "For you" section but is fine with "Following" section on the main page.
<img width="692" alt="image" src="https://github.com/github/docs/assets/104303438/5ebbedca-b8f2-4b48-bdf9-791c44f0d856">
<img width="700" alt="image" src="https://github.com/github/docs/assets/104303438/24455624-9ffd-4d4a-bd8c-5ed997c9181e">

### What part(s) of the article would you like to see updated?

"For you" section

### Additional information

I have tried refreshing the page and trying to re-open it. But the issue stays the same. Also I am on default browser size at 100%

**Comment by KhushPatibandha** [comment]
After a while I have realized that this repo might not be the one I should post this issue on. Do anybody know where should this issue be posted or if it is alright to post it here?

**Comment by cmwilson21** [comment]
@KhushPatibandha Thanks for opening an issue! We appreciate you bringing this up, however, as you stated, this is not the correct repo for it. We handle the Docs site and the documentation within. 

It sounds like this is a bug. Please report it [here](https://support.github.com/contact/bug-report).

Thanks again!
