### ISSUE TITLE
Side-navigation menu items are unreadable when using a light theme with Firefox 

### ISSUE THREAD

**Issue by jordojordo** [github/docs#25660]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I have noticed this issue all over the documentation, the side-navigation menu items appear to be using the incorrect colors while using a light theme provided by the User theme preferences. This issues happens with each light theme, and does not happen when using a dark theme.

_Docs example - light theme - Firefox_
![git-docs-light-ff](https://github.com/github/docs/assets/40806497/2cd72fda-6ad5-4bab-8ed8-e315b69c56d3)

_Appearance preferences_
![git-appearance-light-ff](https://github.com/github/docs/assets/40806497/57b1ac55-e233-4d5a-ad97-68c1922a53f6)

_Docs example - dark theme - Firefox_
![git-docs-dark-ff](https://github.com/github/docs/assets/40806497/20d3a607-4181-4677-809f-fbd92dc7242a)

Note, this does ___not___ happen with Chrome.

_Docs example - light theme - Chrome_
![git-docs-light-chrome](https://github.com/github/docs/assets/40806497/23c8e352-5643-4bcd-91f6-2569af6a5681)

### What changes are you suggesting?

The menu items should be readable when using a light theme regardless of browser.

### Additional information

I tested this using Firefox `112.0.1` and `113.0.1` for archlinux, with private windows and no extensions installed.

![ff-about](https://github.com/github/docs/assets/40806497/26e11b98-c1f0-48bc-b0da-049a23ffa237)

**Comment by jordojordo** [comment]
Closing this as there appears to be an internal discussion with this issue: https://github.com/github/docs/issues/25235#issuecomment-1525704931

**Comment by cmwilson21** [comment]
@jordojordo Thanks for the issue! We appreciate the leg work and finding the other comment about the internal issue 💖 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. We would love to have a PR from you sometime!

Thank you for your interest in improving GitHub Docs! ✨
