### ISSUE TITLE
Double comma in "Enforcing security settings in your Enterprise account"

### ISSUE THREAD

**Issue by janiceilene** [github/docs#2571]
### What article on docs.github.com is affected?

 https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-enterprise/enforcing-security-settings-in-your-enterprise-account#managing-your-enterprise-accounts-ssh-certificate-authorities

### What part(s) of the article would you like to see updated?

There is a double comma in a paragraph within:

 https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-enterprise/enforcing-security-settings-in-your-enterprise-account#managing-your-enterprise-accounts-ssh-certificate-authorities

There should only be one comma after the word "resources".

Screenshot:

![image](https://user-images.githubusercontent.com/40512107/98431440-eed57e80-207a-11eb-8727-8751b2512303.png)

**Comment by Manikanta05** [comment]
I can rectify it!
