### ISSUE TITLE
allows github actions relative links

### ISSUE THREAD

**Issue by nicola-lunghi** [github/docs#25742]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes.md

### What part(s) of the article would you like to see updated?

document the feature that we can use relative link for github actions badges

```
[![Build  SW app](/../../actions/workflows/sw-build.yaml/badge.svg?branch=main)](/../../actions/workflows/sw-build.yaml)
```

### Additional information

maybe add this to the generator.
This allows to have on forked repo the badge to actually point to the current repo

**Comment by cmwilson21** [comment]
@nicola-lunghi Thanks for opening an issue! Could you explain a bit more about the content you are asking us to add? Are you meaning the [Relative links in image paths](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#relative-links-and-image-paths-in-readme-files)?
