### ISSUE TITLE
Add Typescript example to "Securing your webhooks"

### ISSUE THREAD

**Issue by tycrimm** [github/docs#25789]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/webhooks-and-events/webhooks/securing-your-webhooks

### What part(s) of the article would you like to see updated?

It would be great to add a Typescript example to make it easier for people to mindlessly implement webhook verification rather than skip it completely.

### Additional information

PR coming a few moments after this issue is created

**Comment by Nadaa00** [comment]
Engineering Scorecard for nedaa could not be generated. Please check the repository name & make sure it is part of github organization

**Comment by Nadaa00** [comment]
> @tycrimm Thank you for opening an issue and linking it to your PR! ✨
