### ISSUE TITLE
Adding different themes in website

### ISSUE THREAD

**Issue by VGandhi27** [github/docs#25801]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/ef413e42793ad589c537407f21eda8868b880c7b/CONTRIBUTING.md

### What part(s) of the article would you like to see updated?

apply different themes and need to add more information

### Additional information

https://docs.github.com/en/pages/quickstart
![Screenshot (46)](https://github.com/github/docs/assets/93124166/19e30b0a-eef0-4135-8ac5-d3ecf8b56b34)

**Comment by cmwilson21** [comment]
@VGandhi27 Thanks for opening an issue! ✨ 

So we can get a better understanding of your report, what sort of information would you like to see added to the docs? Please provide additional context or an example and we will get this up for review ⚡
