### ISSUE TITLE
Remove empty bullet in log streaming documentation (for GHES versions)

### ISSUE THREAD

**Issue by adamrr724** [github/docs#25824]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.7/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/streaming-the-audit-log-for-your-enterprise

### What part(s) of the article would you like to see updated?

In the GHES versions of the docs, there is an empty bullet point in the about section:

https://docs.github.com/en/enterprise-server@3.7/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/streaming-the-audit-log-for-your-enterprise

**Comment by cmwilson21** [comment]
👋 @adamrr724 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by sophietheking** [comment]
@adamrr724  Thanks for opening an issue! ⚡

You, or anyone else, are welcome to open a PR removing that empty bullet point from [About audit log streaming](https://docs.github.com/en/enterprise-server@3.7/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/streaming-the-audit-log-for-your-enterprise#about-audit-log-streaming). ✨
