### ISSUE TITLE
Misaligned Viewed Button in the Review process [ Big Issue ]

### ISSUE THREAD

**Issue by XeroDays** [github/docs#25838]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

When  reviewing  files in the pull request, the Viewed  Toggle button is at the top, which is not in the 

appropriate location..
it should be at the bottom of the viewed page so the viewer should not scroll back to the top in order to check the toggle button.   

### What part(s) of the article would you like to see updated?

<img width="632" alt="image" src="https://github.com/github/docs/assets/38852291/c6507556-072e-4f3b-b37a-b6ba932c20d1">

This "Viewed" Button should be in the end of the file.

**Comment by cmwilson21** [comment]
@XeroDays Thanks so much for opening an issue! However, here we maintain the GitHub Docs site and the documentation within. For this kind of issue, please leave your feedback [here](https://github.com/orgs/community/discussions) ✨ 

If there's something in the docs that need to be updated, let us know. Closing this now 💛

**Comment by XeroDays** [comment]
@cmwilson21  I am not sure where should i generate this issue? who maintian the Github core web app?

**Comment by cmwilson21** [comment]
@XeroDays I think the best place would to be to leave feedback in the link above [here](https://github.com/orgs/community/discussions). That's where feedback and suggestions are made.

Thanks again! ✨
