### ISSUE TITLE
.github repository visibility in Enterprise Cloud organizations

### ISSUE THREAD

**Issue by donovanmuller** [github/docs#25836]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/598b5694e6afa545ecf4cb60ea309ad2f96403e3/content/actions/using-workflows/creating-starter-workflows-for-your-organization.md?plain=1#LL44C33-L44C100

### What changes are you suggesting?

Following the guide to [create Starter workflows](https://github.com/github/docs/blob/598b5694e6afa545ecf4cb60ea309ad2f96403e3/content/actions/using-workflows/creating-starter-workflows-for-your-organization.md?plain=1#LL44C33-L44C100) for an Enterprise Cloud Organization and it mentions that the `.github` repository needs to be _public_.

For a private Organisation, it feels wrong that this repository must be public. The custom Starter workflows do not appear when the `.github` repository is private, so this is a prerequisite unless I'm missing something.

**Comment by cmwilson21** [comment]
@donovanmuller Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by donovanmuller** [comment]
@mattpollard The question is why a _private_ Organization must have the `.github` repository with public visibility. This repository could contain sensitive information or references to other private/internal repositories in a private Organization. that should not be visible outside that Organization.

**Comment by kanoshin** [comment]
I think there is actually a mistake in the document. [Here](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization#creating-a-starter-workflow) it says the following:
> Starter workflows created by users can only be used to create workflows in public repositories. Organizations using GitHub Enterprise Cloud can also use starter workflows to create workflows in private repositories.

But if you try to create a private `.github` repository for GitHub Enterprise Cloud organization with a starter workflow, it will not be visible during Action creation.
