### ISSUE TITLE
Code blocks in document for `jobs.<job_id>.runs-on` are not highlighted

### ISSUE THREAD

**Issue by rhysd** [github/docs#25845]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on

### What part(s) of the article would you like to see updated?

Some YAML code blocks are not highlighted.

**Comment by cmwilson21** [comment]
@rhysd Thank you for opening an issue and linking it to your PR! ✨
