### ISSUE TITLE
clarity on whether secret-to-public gist is possible

### ISSUE THREAD

**Issue by PaoloJr90** [github/docs#25874]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists

### What part(s) of the article would you like to see updated?

The section `After creating a gist, you cannot convert it from public to secret.`, is not clear whether the reverse is true; that is, a secret gist can/cannot be converted to public. 

After checking numerous forums (with dated information), this `docs` repo's `Issues` and `Discussions`, it is not clear if an initially-created secret gist can be converted to public later on.

Suggesting to include some mention if a secret gist can/cannot be converted to public.

### Additional information

First-time contributing here ;)

**Comment by cmwilson21** [comment]
@PaoloJr90 Thanks for opening an issue! I'll get this triaged for review ✨ 

>First-time contributing here ;)

And welcome to the docs community!

**Comment by sophietheking** [comment]
@PaoloJr90 PaoloJr90 👋 Thanks so much for opening this issue to improve the docs! ✨ 
I tested whether I could convert a gist from secret to public and found out that it is possible. After you create a secret gist, you can click the edit button, and then "make public":

![secret-gist](https://github.com/github/docs/assets/29382425/bdb14e75-e3be-4540-9a16-f57986a7453f)

I suggest adding a line to `content/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists.md`. You or anyone else is welcome to open a PR with this change.
