### ISSUE TITLE
[GitHub Actions] `environment` type missing in workflow input types documentation

### ISSUE THREAD

**Issue by mikelei8291** [github/docs#25938]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype

https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context

### What part(s) of the article would you like to see updated?

`environment` type should be added to the list of allowed types.

This type had been in the list of allowed types before #25435 was opened and it was considered as a typo of "number". The `environment` type is indeed not listed in the table of all available types in the [`inputs` context documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context), but it is used in an example in the [`on.workflow_dispatch.inputs` documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-onworkflow_dispatchinputs), and in real world applications as mentioned by @nathanchapman in this [comment](https://github.com/SchemaStore/schemastore/pull/2966#issuecomment-1587897802).

Therefore, I don't think this is a typo, but a miss in the documentations linked above, and would like it to be added back to the documentations.

Someone familiar with the action runner code could also clarify whether the `environment` type is allowed, or is it about to be removed.

**Comment by Obeda1995** [comment]
يمكن ان تحضر لي المستندات اطلع عليها اريد ترسل لي الي الى هنا على الجيميل
وشكرا لك وساقوم بالبحث عن المستندات ان كان شيئا خطا ام كان شيئا صح وساخبرك
بعدها عن الاطلاع على هذه الاوراق

في الثلاثاء، ١٣ يونيو ٢٠٢٣, ٣:٢٧ ص welcome[bot] ***@***.***>
كتب:

**Comment by nathanchapman** [comment]
Agreed, the input unification was great 👏 
Was just wanting to make sure `number` wasn't fabricated by the author of #25435 since I couldn't find any documentation for it prior to https://github.com/github/docs/pull/25436 being merged.

**Comment by githubcopyrightdoctor** [comment]
#844147
@githubcopyrightdoctor

**Comment by githubcopyrightdoctor** [comment]
https://github.com/Google.Electron.ZTE
@githubcopyrightdoctor
#9146FF
![Uploading th-1.jpg…]()

>awaka<

**Comment by githubcopyrightdoctor** [comment]
https://github.com/Google.Electron.ZTE
@githubcopyrightdoctor
#9146FF
![Uploading th-1.jpg…]()

>awaka<

**Comment by mikelei8291** [comment]
Wait what? @cmwilson21 This should be fixed, any updates?

**Comment by thiago-marafeli-VBL** [comment]
It would be great...
I'm trying to understand better how "environment" works... what's the difference from a "string" type, for example

**Comment by FidelusAleksander** [comment]
I'm fixing this https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype 
In https://github.com/github/docs/pull/29781

**Comment by FidelusAleksander** [comment]
> It would be great... I'm trying to understand better how "environment" works... what's the difference from a "string" type, for example

Environment is most similar to `choice` but the `options` are automatically populated with `name` of all environments in a repository

**Comment by SiaraMist** [comment]
Thank you for opening this issue, @mikelei8291! I've approved the PR that @FidelusAleksander opened to address this, and we'll get that merged next week once our repo is unfrozen.

**Comment by n-badtke-cg** [comment]
Hi,

I just see that in the note block at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onworkflow_dispatchinputs it mentions that choice type will result in string input. It would be also helpful to mention the environment type in the very same sentence :)
