### ISSUE TITLE
Navigating Code on GitHub: Add R support 

### ISSUE THREAD

**Issue by jananiravi** [github/docs#25970]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/repositories/working-with-files/using-files/navigating-code-on-github.md

### What part(s) of the article would you like to see updated?

Adding R support

**Comment by cmwilson21** [comment]
@jananiravi Thanks for opening an issue! Just to clarify, are you wanting to add R to the table of supported languages? Or somewhere else in the article?
