### ISSUE TITLE
The  workflow_run payload docs is incomplete

### ISSUE THREAD

**Issue by sbrunner** [github/docs#2599]
### What is the current behavior?

Here there https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run the workflow_run property is missing, she contains at least pull_requests as in check_suite https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#check_suite

### What changes are you suggesting?

Add all the missing property

### Additional information

Example of job that runs on workflow_run: https://github.com/camptocamp/tilecloud/runs/1653892847?check_suite_focus=true

**Comment by IAM-db** [comment]
Nineteenlayout7@paypal.me
MELISSA WOOD 

    On Wednesday, January 6, 2021, 01:35:46 AM PST, Stéphane Brunner <notifications@github.com> wrote:  
 
 


I can't contribute because I don't know from where reusables.webhooks.check_run_properties comes from.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @sbrunner! Here is the reusable you're looking for https://github.com/github/docs/blob/main/data/reusables/webhooks/check_run_properties.md if you'd like to open a PR ⚡ I'm also triaging this for the team to take a look at 👀
