### ISSUE TITLE
Configuring custom domain for github pages site that was built remotely

### ISSUE THREAD

**Issue by brianwaithaka** [github/docs#26014]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

### Details
- When deploying to github-pages environment using a GitHub Actions workflow, current docs do not describe a way to authenticate the **subdomain**
- Current docs method (point 8) creates a CNAME file, it only covers use case of deploying GitHub Pages from a branch

### Supported use case
- Using a static site generator and GitHub Actions workflow to build and remotely publish to github-pages environment for GitHub Pages

### Outcome
- After testing, I got it to work by authenticating just the subdomain in user settings as stated here https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-for-your-user-site
- To build and deploy files with GitHub Actions workflow, create cname record with dns provider, then authenticate subdomain in user settings

**Comment by cmwilson21** [comment]
@brianwaithaka Thank you for opening an issue and linking it to your PR! ✨

**Comment by benb24-cloud** [comment]
No on

**Comment by Kingodbug** [comment]
#reyelcidbugarinabetria
