### ISSUE TITLE
Enterprise Team Synchronization - Incorrect invite information

### ISSUE THREAD

**Issue by spektrixadmin** [github/docs#26048]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-saml-for-enterprise-iam/managing-team-synchronization-for-organizations-in-your-enterprise#managing-whether-team-synchronization-can-invite-non-members-to-organizations

### What part(s) of the article would you like to see updated?

The documentation in the article suggests that there should be a "Do not allow Team Sync to invite non-members to organizations."
![image](https://github.com/github/docs/assets/14344773/471686d3-a816-458f-8e1d-3621fb88e73d)

Under "Team synchronization" there is no checkbox for "Do not allow Team Sync to invite non-members to organizations.".

I see the following:
![image](https://github.com/github/docs/assets/14344773/0643b88a-74ec-4a86-af9a-9d9fa63ea1f5)

I don't know it this is a limitation of an enterprise account or simply incorrect documentation. This is blocking us from getting our SAML enabled Enterprise account setup from automatically inviting users to organisations where they are members of teams.

### Additional information

I am currently using an Enterprise Trail account and am configuring Team Synchronization at an Enterprise level.

**Comment by cmwilson21** [comment]
@spektrixadmin If this is still blocking you and while this is waiting for review, please reach out to our awesome [support team](https://support.github.com/request). 

Someone will review if there's a need to documentation update soon ✨

**Comment by lecoursen** [comment]
Thanks @spektrixadmin! I dug into this and found a PR where we changed the wording of this setting to the following:

>Do not allow Team Sync to re-invite past members to organizations that were removed by an organization owner

You or anyone else is welcome to open a PR updating the procedure accordingly. ⚡

**Comment by electron97** [comment]
Hey @lecoursen,

I started looking into this issue and I found that issue is already resolved in https://github.com/github/docs/pull/27105.
Could you please let me know if there is anything more needed here that is needed to be done? 
Otherwise I think we can close this issue as done.

Thanks!
cc: @cmwilson21
