### ISSUE TITLE
hashFiles documentation links to misleading description of pattern matching

### ISSUE THREAD

**Issue by textbook** [github/docs#26051]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

GitHub Actions / Learn GitHub Actions / Expressions, specifically for [`hashFiles`](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles)

### What part(s) of the article would you like to see updated?

The documentation claims:

> You can use pattern matching characters to match file names. Pattern matching is case-insensitive on Windows. For more information about supported pattern matching characters, see "[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)."

However, the filter pattern cheatsheet does **not** reflect the matching used by `hashFiles` in `@actions/glob`. For example, the cheat sheet says:

> - `?`: Matches zero or one of the preceding character.

but you can't get "all JS and JSX files" with `**.jsx?`. The implementation uses [Minimatch](https://www.npmjs.com/package/minimatch) (in which it would be `.js?(x)` rather than `.jsx?`, except that extended globbing is [explicitly disabled](https://github.com/actions/toolkit/blob/a6bf8726aa7b78d4fc8111359cca5d538527b239/packages/glob/src/internal-pattern.ts#L124-L134)).

**Comment by SiaraMist** [comment]
Hey @textbook, thank you so much for catching this and reporting the issue! And for your patience with us as we work through our backlog. 💛 

We recently updated this [here](https://github.com/github/docs/commit/9ce2cecbfadf1604b851987a3de0a1237481a47a), so I'm going to go ahead and close this issue. Thank you again!
