### ISSUE TITLE
Typo in `introduction-to-github-packages.md` in Japanese: nmp → npm

### ISSUE THREAD

**Issue by taigakiyokawa** [github/docs#26078]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/ja/packages/learn-github-packages/introduction-to-github-packages

Only Japanese doc is affected.

### What part(s) of the article would you like to see updated?

I found a typo at https://docs.github.com/ja/packages/learn-github-packages/introduction-to-github-packages#:~:text=GitHub%20Packages%E3%81%AF%E3%80%81-,nmp,-%E3%80%81RubyGems%E3%80%81Apache%20Maven. Please fix "nmp" in the sentence to "npm".

### Screenshot

![image](https://github.com/github/docs/assets/40013676/d0a6632a-c59c-4c0d-93ab-720a6c75c350)

### Notes

The same doc in English ( https://github.com/github/docs/blob/main/content/packages/learn-github-packages/introduction-to-github-packages.md ) is no typos.

**Comment by msgirly79** [comment]
H

**Comment by msgirly79** [comment]
G

**Comment by cmwilson21** [comment]
@taigakiyokawa Great catch! Thanks for opening this 👍 

Our translations are handled via an internal process, so I'm going to go ahead and close this issue and raise it for review internally. 💖 

Thank you for your interest in improving GitHub Docs! ✨ :
