### ISSUE TITLE
Environment variable ACTIONS_RUNNER_CONTAINER_HOOK is not correct

### ISSUE THREAD

**Issue by mhuijgen** [github/docs#26156]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/customizing-the-containers-used-by-jobs#triggering-the-customization-script

### What part(s) of the article would you like to see updated?

Environment variable ACTIONS_RUNNER_CONTAINER_HOOK is not correct and the hooks will not be triggered by the runner.

The correct env var is ACTIONS_RUNNER_CONTAINER_HOOKS

See also https://github.com/actions/runner/blob/main/docs/adrs/1891-container-hooks.md

After using ACTIONS_RUNNER_CONTAINER_HOOKS my self-hosted runner started executing the hooks.

**Comment by cmwilson21** [comment]
@mhuijgen Thank you for opening a PR and linking it to your issue! ✨

**Comment by Edison478** [comment]
Please everyone I need help here

**Comment by Edison478** [comment]
My device have been hack and I need a solution to it please
