### ISSUE TITLE
CODEOWNERS displays error to anonymous

### ISSUE THREAD

**Issue by dan2k3k4** [github/docs#26167]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

If you visit https://github.com/github/docs/blob/main/.github/CODEOWNERS, you'll notice the linting error visible:

```
Unknown owner on line 10: make sure the team @github/oidc exists, is publicly visible, and has write access to the repository

…hardening-your-deployments/** @github/oidc
```

It is visible whether you're logged in or out of GitHub.

<img width="1256" alt="image" src="https://github.com/github/docs/assets/158704/bc1f2db0-be21-4cf8-a75b-a0a282f22b57">

### What changes are you suggesting?

Suggestion:
- Hide linting errors unless you're either logged in to GitHub or have write access to the file

Perhaps, also set the team `@github/oidc` as public to fix the initial linting error.

**Comment by cmwilson21** [comment]
@dan2k3k4 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by rsese** [comment]
👋 !  That's expected with our setup:

https://github.com/github/docs/blob/b0b1a121f20a49ad3e97a010a4ee048333015043/README.md#L5

So internally in the private repo we might have some teams that will review particular changes but those teams won't be publicly visible.

**Comment by cmwilson21** [comment]
Closing this issue per comment above 💛 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
