### ISSUE TITLE
Missing quotes in file paths patterns

### ISSUE THREAD

**Issue by miguelsousa** [github/docs#26172]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

### What part(s) of the article would you like to see updated?

The patterns that start with `*` and `!` in the [Patterns to match file paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths) section need to be wrapped in quotes.

**Comment by cmwilson21** [comment]
@miguelsousa Thank you for opening an issue and linking it to your PR! ✨
