### ISSUE TITLE
clarity on GitHub Pages docs mentioning repo sub-folder-projects unique URLs

### ISSUE THREAD

**Issue by PaoloJr90** [github/docs#26174]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site

and/or

https://docs.github.com/en/pages/getting-started-with-github-pages/using-submodules-with-github-pages

and/or 

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

### What part(s) of the article would you like to see updated?

More clarity on GitHub Pages capability to host multiple static-sites within nested folders of the selected repository. 

This can be achieved by simply entering the sub-folder's unique URL (after `build` is complete).

For example:
```
my-test-projects/
├── project-a/
├── project-b/
└── project-c/
````
each project is a sub-folder of the `my-test-projects`, and can be accessed by appending the folder-name in the address URL

Entered multiple articles that may be updated. Not sure if any  one (or all) are appropriate for this mention.

### Additional information

The following discussions mention this capability. I followed the instructions and it works well!

GitHub Docs discussion --> #26012

GitHub Community discussion --> https://github.com/orgs/community/discussions/58276#discussion-5306408

Indeed, I posed the question in both places 👍

**Comment by sophietheking** [comment]
@PaoloJr90 Thanks so much for your patience. I spoke with the team and we're not interested in making this change. I'm going to close this issue. We appreciate your interest in improving the GitHub Docs 💖

Take a look at the `contributing.md` to learn how to contribute in this repo. You can open a discussion if you have any questions or check out issues with the help wanted label. ✨
