### ISSUE TITLE
Job queue/dispatch order is not described/documented

### ISSUE THREAD

**Issue by jsoref** [github/docs#26207]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-jobs

### What part(s) of the article would you like to see updated?

Add a page/section that explains how jobs are dispatched to runners.

It should include an explanation of things like:
* how multiple jobs that are triggered from different repositories in the same organization are dispatched to runners
* an explanation of how queuing works -- is it first come first served? (it isn't); 
* an explanation of how large runners, self-hosted runners, and default runners fight for jobs
* how jobs interact with limits / how macos limits interact with generic limits -- https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

### Additional information

I'm told that there was a workflow that created 92 jobs many of which were queued: https://github.com/Habbie/openwrt-feeds/actions/runs/5355423916 and then another workflow was triggered later while there were still jobs queued https://github.com/Habbie/dnsdist-ansible/actions/runs/5357700666 and it finished before the first workflow finished.

**Comment by cmwilson21** [comment]
👋 Hey @jsoref! Thanks for the issue. I'll get it up for review! 👀

**Comment by benny-png** [comment]
Just use port-forwarding services like NGROK lol SUPER easy three line of shell commands https://ngrok.com/download
you can use this for reference https://youtu.be/AhiXVaWst24

**Comment by G2cme** [comment]
#30399

**Comment by G2cme** [comment]
#30699 #30700

**Comment by jc-clark** [comment]
Hey @jsoref! Thank you for this issue and for thinking critically about this. We checked in with our engineering teams and there are a lot of factors that affect how and when jobs are dispatched to runners. Since we can't guarantee these factors, there's no way for us to document this on the docs site. Closing this one out!
