### ISSUE TITLE
Update methodology for enabling Dependabot security updates

### ISSUE THREAD

**Issue by hamirmahal** [github/docs#2625]
### What article on docs.github.com is affected?
https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-dependabot-security-updates

### What part(s) of the article would you like to see updated?
[Managing Dependabot security updates for your repositories](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-dependabot-security-updates#managing-dependabot-security-updates-for-your-repositories)

### Additional information
I think the current methodology for enabling Dependabot security updates, part of which is in [`assets/images/help/repository/enable-dependabot-security-updates-drop-down.png`](https://github.com/github/docs/blob/main/assets/images/help/repository/enable-dependabot-security-updates-drop-down.png), is out of date. I think I might have a fix for this.

![image](https://user-images.githubusercontent.com/43425812/103831464-fe4c5600-5030-11eb-8be9-8a283edad9f3.png)

**Comment by rin1611** [comment]
> ### Bài viết nào trên docs.github.com bị ảnh hưởng?
> https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-dependabot-security-updates
> 
> ### Bạn muốn xem (những) phần nào của bài viết được cập nhật?
> [Quản lý các bản cập nhật bảo mật Dependabot cho kho lưu trữ của bạn](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-dependabot-security-updates#managing-dependabot-security-updates-for-your-repositories)
> 
> ### Thông tin thêm
> Tôi nghĩ rằng phương pháp hiện tại để kích hoạt các bản cập nhật bảo mật Dependabot, một phần của bản cập nhật này, đã [`assets/images/help/repository/enable-dependabot-security-updates-drop-down.png`](https://github.com/github/docs/blob/main/assets/images/help/repository/enable-dependabot-security-updates-drop-down.png)lỗi thời. Tôi nghĩ rằng tôi có thể có một sửa chữa cho điều này.
> 
> ![hình ảnh](https://user-images.githubusercontent.com/43425812/103831464-fe4c5600-5030-11eb-8be9-8a283edad9f3.png)

**Comment by chiedo** [comment]
@hamirmahal  Thanks for opening an issue! I’ll triage this for the right team to take a look 👀

**Comment by hamirmahal** [comment]
@chiedo You're welcome. Happy to help.

**Comment by hamirmahal** [comment]
@chiedo You're welcome! Happy to help.
