### ISSUE TITLE
bug(actions-cache-docs): Example workflow to delete all caches on PR closure does not delete all caches on PRs with many caches

### ISSUE THREAD

**Issue by erezrokah** [github/docs#26251]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

Specifically 
![image](https://github.com/github/docs/assets/26760571/fdeaf1c2-0c59-4d16-8c99-d4c468f792e3)

### What part(s) of the article would you like to see updated?

`gh actions-cache list` returns up to a limit of 30 caches by default, and one can pass `-L 100` to have a limit of 100, so stating the workflow deletes all caches can be incorrect for PRs with many caches.

### Additional information

- Feature request to add pagination to `gh actions-cache list` https://github.com/actions/gh-actions-cache/issues/75
- `gh actions-cache list` docs https://github.com/actions/gh-actions-cache#list
- Workaround is to use `gh api`, e.g. `cacheKeysForPR=$(gh api /repos/$REPO/actions/caches?ref=$BRANCH --paginate | jq -r '.actions_caches[].key' )`

**Comment by cmwilson21** [comment]
@erezrokah Thank you for opening an issue and linking it to your PR! ✨
