### ISSUE TITLE
Improving the formatting on the Testing custom queries (CodeQL) page

### ISSUE THREAD

**Issue by nicholas-keers** [github/docs#26277]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/testing-custom-queries

### What part(s) of the article would you like to see updated?

I would like to see the Java code block updated and the formatting below it fixed, they appear in pre / code-blocks when they shouldn't.

### Additional information

![2023-06-27 13 07 47 docs github com e925902cb69c](https://github.com/github/docs/assets/94363953/a2f232d4-acd5-41d4-abaf-7cf036f7d55b)

**Comment by cmwilson21** [comment]
@nicholas-keers Thank you for opening an issue and linking it to your PR! ✨
