### ISSUE TITLE
Change wording in enterprise team synchronization documentation from "organization" to "enterprise".

### ISSUE THREAD

**Issue by adamrr724** [github/docs#26290]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-saml-for-enterprise-iam/managing-team-synchronization-for-organizations-in-your-enterprise

### What part(s) of the article would you like to see updated?

Step 5 says:

> Confirm that SAML SSO is enabled for your organization. For more information, see "[Managing SAML single sign-on for your organization](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization)."

It should read: 

"Confirm that SAML SSO is enabled for your **_enterprise_**"... 

and then link to enterprise SSO documentation like this page:
https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-saml-for-enterprise-iam/configuring-saml-single-sign-on-for-your-enterprise

instead of linking to org level SAML docs.

**Comment by cmwilson21** [comment]
👋  @adamrr724 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @adamrr724! I actually don't think we need a link in that step at all, since we already link to that article in the prerequisites:

>You must enforce SAML single sign-on for organizations in your enterprise account with your supported IdP. For more information, see "[Configuring SAML single sign-on for your enterprise](https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-saml-for-enterprise-iam/configuring-saml-single-sign-on-for-your-enterprise)."

Let's just replace that reusable with "Confirm that SAML SSO is enabled for your enterprise." You or anyone else is welcome to open a PR doing so! ⚡
