### ISSUE TITLE
Add documentation for `workflow_run` event payload properties

### ISSUE THREAD

**Issue by rebwill** [github/docs#26319]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run

### What part(s) of the article would you like to see updated?

The `workflow_run` event payload documentation is lacking any reference for the `workflow_run` object.

About two weeks ago, I briefly saw a dropdown [here](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run) under the `workflow_run object`. The dropdown was similar to what appears under the dropdown properties of `workflow_job.deployment`. However the `workflow_run` dropdown disappeared the next time I reloaded the page, and I have not seen it again. I tried in Firefox and Chrome in case it was a browser issue, but no luck. In the attached screenshot you can see a blank space at the bottom, below the `workflow_run` body parameter.

I have not been able to find an official (or even unofficial!) documentation for what the `workflow_run` event payload contains. This has made what should have been a simple use case (a Slack integration for notifications for failed workflow runs) rather frustrating. I've seen a few issues related to this topic. In https://github.com/github/docs/issues/23257 I was encouraged to open a new issue for this specifically. 

**Expected outcome:**
Detailed documentation of the properties that the `workflow_run` event payload object contains.

### Additional information

<img width="916" alt="image" src="https://github.com/github/docs/assets/47540675/4a6d6ed6-e59f-4747-9df1-f72b0dab17a1">

**Comment by cmwilson21** [comment]
:wave: @rebwill - Thanks for opening the issue! :sparkles:

I'll get this triaged for review! :zap:

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by cmwilson21** [comment]
@rebwill Just a heads up, any changes with the `/webhook-events-and-payloads` docs have to be made internally. The issue has been transferred and will be reviewed soon ✨

**Comment by skedwards88** [comment]
Thanks for raising this issue! While we fix this bug, I just want to drop a note that you can find details about this property if you look at the docs for the `requested` action: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=requested#workflow_run

**Comment by rebwill** [comment]
Wow, thanks for the heads up @skedwards88, that would explain why I _swore_ I had actually seen the properties before -- it must have actually been at that link you shared.
