### ISSUE TITLE
Add option to hide the banner suggesting that a page is available in another language

### ISSUE THREAD

**Issue by DerEchtePilz** [github/docs#26379]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I am assuming every page is affected, at least any page that supports multiple languages.

### What changes are you suggesting?

![image](https://github.com/github/docs/assets/81232921/fac19cc5-c2a7-4431-b43e-bb1c64628314)
This banner appears when not using the local language.
Although German is my native language I prefer reading these articles in English and I would like to see a button that hides this banner because it's kinda annoying.

**Comment by DerEchtePilz** [comment]
So, I've opened this ten days ago and haven't heard anything.
What's the deal with this?

**Comment by cmwilson21** [comment]
@DerEchtePilz My apologies on this! Several teams were out for the US holiday but are back now, so I'll get this in front of the them. I left it open as a reminder to track this down, as I wasn't 100% sure which team it best fits within.

Again, my apologies for failing to communicate that with you earlier. 💛

**Comment by cmwilson21** [comment]
@DerEchtePilz Checked in with the team and we have an internal issue open with this same feedback. As we are discussing this internally, I'm going to go ahead and close this issue, but I've grabbed a link to it for further reference 💛
