### ISSUE TITLE
GitHub Actions expressions example is misleading

### ISSUE THREAD

**Issue by kbattocchi** [github/docs#26381]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#example-of-literals

### What part(s) of the article would you like to see updated?

Unfortunately, everything in `env` is apparently converted to a string (see https://github.com/orgs/community/discussions/25645), though as far as I can tell this isn't documented anywhere (but it should be!).

This makes the section where literals of various types are being assigned to environment variables especially misleading - you can use those literal expressions in the `env` section, but the values that are actually stored are the converted strings, which may then break downstream logic that uses the values while expecting them to have the correct type.  This is especially true of boolean values, since the string `'false'` is truthy.

**Comment by cmwilson21** [comment]
@kbattocchi Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by mmu094** [comment]
Ruby is copyrighted free software by Yukihiro Matsumoto <matz@netlab.jp>.
You can redistribute it and/or modify it under either the terms of the
2-clause BSDL (see the file BSDL), or the conditions below:

  1. You may make and give away verbatim copies of the source form of the
     software without restriction, provided that you duplicate all of the
     original copyright notices and associated disclaimers.

  2. You may modify your copy of the software in any way, provided that
     you do at least ONE of the following:

       a) place your modifications in the Public Domain or otherwise
          make them Freely Available, such as by posting said
	  modifications to Usenet or an equivalent medium, or by allowing
	  the author to include your modifications in the software.

       b) use the modified software only within your corporation or
          organization.

       c) give non-standard binaries non-standard names, with
          instructions on where to get the original software distribution.

       d) make other distribution arrangements with the author.

  3. You may distribute the software in object code or binary form,
     provided that you do at least ONE of the following:

       a) distribute the binaries and library files of the software,
	  together with instructions (in the manual page or equivalent)
	  on where to get the original distribution.

       b) accompany the distribution with the machine-readable source of
	  the software.

       c) give non-standard binaries non-standard names, with
          instructions on where to get the original software distribution.

       d) make other distribution arrangements with the author.

  4. You may modify and include the part of the software into any other
     software (possibly commercial).  But some files in the distribution
     are not written by the author, so that they are not under these terms.

     For the list of those files and their copying conditions, see the
     file LEGAL.

  5. The scripts and library files supplied as input to or produced as
     output from the software do not automatically fall under the
     copyright of the software, but belong to whomever generated them,
     and may be sold commercially, and may be aggregated with this
     software.

  6. THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
     IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
     PURPOSE.


Thanks Dearest @mmu094

**Comment by hubwriter** [comment]
@kbattocchi - Thanks for raising this issue.

> as far as I can tell this isn't documented anywhere (but it should be!).

You're right, stringifying the contents of the `env` context is something we should have documented. However, we added this quite recently [here](https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions):

> Using the `${{ }}` expression syntax turns the contents into a string, and strings are truthy. For example, `if: true && ${{ false }}` will evaluate to true.

I'm going to close this issue. 
Thanks again for pointing this out. 👍
