### ISSUE TITLE
Fix curl request in rest code samples

### ISSUE THREAD

**Issue by pietervdheijden** [github/docs#26396]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All rest articles containing code samples with header X-GitHub-Api-Version. For example:

- https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28
- https://docs.github.com/en/rest/repos/autolinks?apiVersion=2022-11-28
- https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

Line:

`-H "Authorization: Bearer <YOUR-TOKEN>"\`

Doesn't have a space between `"` and `\`. As a result, the cURL request does not work correctly.

To fix this, the line should be replaced by:

`-H "Authorization: Bearer <YOUR-TOKEN>" \`

### Additional information

![image](https://github.com/github/docs/assets/7749051/a66e32e6-fc74-448f-b65d-67293a8126d9)

**Comment by NTA-MAX** [comment]
PLEASE  FIX IT

**Comment by jessjump143** [comment]
> PLEASE FIX IT

# GitHub CLI api
# https://cli.github.com/manual/gh_api

gh api \
  --method PATCH \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /repos/OWNER/REPO/import \
  -f vcs='tfvc' \
 -f tfvc_project='project1' \
 -f human_name='project1 (tfs)'

**Comment by cmwilson21** [comment]
@pietervdheijden Per the bot above, these kind of changes will need to be made in [/rest-api-description](https://github.com/github/rest-api-description). I just saw your PR, so will close it in favor of this transfer 💛

**Comment by pietervdheijden** [comment]
@cmwilson21 Are you sure this change has to be done in /rest-api-description? It seems that repository contains the OpenAPI reference, whereas the bug I reported is in the code sample block. Also, I can't find `<YOUR-TOKEN>` in repository /rest-api-description...

**Comment by NTA-MAX** [comment]
Ok so where do I fix th

**Comment by pietervdheijden** [comment]
@cmwilson21 can you still reply to my comment?

**Comment by cmwilson21** [comment]
@pietervdheijden Sorry for the delay, we had several out and I missed your comment. Code samples and example responses are [updated internally](https://github.com/github/rest-api-description#contributing) and I believe this example fits that. 

On a different note, it doesn't look like the automation to transfer this to the right repo pushed through, so I've manually opened [it here](https://github.com/github/rest-api-description/issues/2737). I'm going to go ahead and close this out but will happily reopen if it I am mistaken 💛

**Comment by NTA-MAX** [comment]
how and thank u
