### ISSUE TITLE
Add an example for custom shells

### ISSUE THREAD

**Issue by JJ** [github/docs#2646]
The documentation on [custom shells](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#custom-shell), unlike the rest of the shells, some of which are pretty obvious, does not include a good example with a real use case.

### What article on docs.github.com is affected?

Article on [workflow syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions).

### What part(s) of the article would you like to see updated?

As indicated above, the sub section on "Custom shells"

### Additional information

I found that as a solution to [this problem I had](https://github.community/t/trying-to-create-perl-actions-and-finding-some-errors/154131/2), where I wanted to use perl as a shell.

**Comment by chiedo** [comment]
@JJ  Thanks for opening an issue! I’ll triage this for the right team to take a look 👀
