### ISSUE TITLE
Adding notes on concurrency setup of reusable workflow

### ISSUE THREAD

**Issue by mahdiar-naufal-shyftplan** [github/docs#26518]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows

### What part(s) of the article would you like to see updated?

By adding this note, it will prevent misconfiguration on concurrency of reusable workflow that cause immediate cancel on the called workflow

### Additional information

Related discussion on this issue: https://github.com/orgs/community/discussions/30708

**Comment by cmwilson21** [comment]
@cmwilson21 Thank you for opening an issue and linking it to your PR! ✨

**Comment by cmwilson21** [comment]
Reopening as the PR is still waiting for review
