### ISSUE TITLE
Quickstart for GitHub Packages has broken formatting

### ISSUE THREAD

**Issue by eyalch** [github/docs#26529]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The [_Quickstart for GitHub Packages_](https://docs.github.com/en/packages/quickstart) article seems to have broken formatting and the ordinal indicators of the steps are out of order.

To make a wild guess, this issue seems to be caused by one of the recent commits that modified this file. Here are 2 commits that caught my attention:

- 1dfa5c251e99d2a91cc15cb8685db1007f7f5502
- a8a6e4554a5ac974417dd45dadb9972902a6f35c

# Screenshots

The following content seem like rendered Markdown but it's actually just screenshots 😄

```
<screenshots>
```

![image](https://github.com/github/docs/assets/5116133/e920eb17-1961-45b9-8529-b9fdf531ccff)
![image](https://github.com/github/docs/assets/5116133/aa81b8f9-0857-49ee-b810-b330681ec474)
![image](https://github.com/github/docs/assets/5116133/4a97c050-cd50-43ba-9298-e4a33612aac8)
![image](https://github.com/github/docs/assets/5116133/a587c9ee-cad1-439c-b8b9-c85af31e45ef)

```
</screenshots>
```

### What changes are you suggesting?

I suggest to fix the formatting of the _Quickstart for GitHub Packages_ docs.

**Comment by mohamadamin224** [comment]
V2RAYNG

**Comment by cmwilson21** [comment]
@eyalch Thanks for opening an issue and reporting this! ✨ 

And thanks for the extra work digging around in the commits 👍 

I'll get it triaged for review.

**Comment by sophietheking** [comment]
@eyalch 👋 Thanks for opening an issue to improve our Docs. This is a great catch, really appreciate you taking the time to open an issue! ✨ 

I noticed a PR has already been opened to fix this issue. 🚀  So I'll remove the `waiting for review` label.
