### ISSUE TITLE
pull_request_target avoid clarification

### ISSUE THREAD

**Issue by kevingentile** [github/docs#26535]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

### What part(s) of the article would you like to see updated?

Clarify `pull_request_target` avoid:

> Avoid using this event if you need to build or run code from the pull request.

**Comment by cmwilson21** [comment]
@kevingentile thanks for opening an issue and submitting a PR! ✨

**Comment by Dxd77** [comment]
I am so amused how you responded so breavlly and helpfully to me while I number one making enough troble to all 
I am rally so speechless

**Comment by Dxd77** [comment]
When the doc was speeded out so wiled didn’t deal sorry or shamed of my self 
However helping me back after all I did to all it  really got me deep
I oow you all my life 
Thanks
