### ISSUE TITLE
Confusing directions on the "Expressions" page in the github actions documentation

### ISSUE THREAD

**Issue by fsgreco** [github/docs#26539]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

It's about this article: https://docs.github.com/en/actions/learn-github-actions/expressions

<img width="711" alt="immagine" src="https://github.com/github/docs/assets/22715417/a0c71235-c1da-4675-b1ef-44747415d8dd">

### What changes are you suggesting?

This section of the documentation says clearly that GitHub automatically evaluates the IF conditional as an expression so "you may omit the expression syntax `${{ }}`.  

However right after that direction it shows an example with expression syntax inside an IF.

**Comment by cmwilson21** [comment]
@fsgreco Thank you for opening an issue and linking it to your PR! ✨ 

We appreciate the context and screenshot, too 👍
