### ISSUE TITLE
Missing information about pull_request object

### ISSUE THREAD

**Issue by Mikilll94** [github/docs#26564]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=opened#pull_request

![Screenshot 2023-07-10 at 15 54 08](https://github.com/github/docs/assets/17653648/b3b963c7-1266-4250-ae77-7f675baaf0ab)

As you can see the `pull_request` object structure is not documented. It is documented for the `synchronize` action type.

### What part(s) of the article would you like to see updated?

`pull_request` object structure should be documented for `opened` action type.

**Comment by cmwilson21** [comment]
@Mikilll94 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
