### ISSUE TITLE
Audit Log Streaming to Splunk - clarify expected IP ranges

### ISSUE THREAD

**Issue by twuytens** [github/docs#26569]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/streaming-the-audit-log-for-your-enterprise#setting-up-streaming-to-splunk

### What part(s) of the article would you like to see updated?

Clarify which IP address range from the meta endpoint will be responsible to send the audit logs.
This is currently not mentioned anywhere explicitly, and we needed to request confirmation from GitHub expert services to be able to whitelist the correct range on our HEC endpoint.
Turns out this would be the addresses mentioned in the `hooks` section of the [meta](https://api.github.com/meta) API endpoint.

**Comment by cmwilson21** [comment]
@twuytens Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @twuytens! It sounds like we should add a sentence to that second, linking to the "[Get GitHub meta information](https://docs.github.com/en/rest/meta/meta?apiVersion=2022-11-28#get-github-meta-information)" and clarifying that you must allow HEC to access the IP addresses listed in the `hooks` section of the response. You or anyone else is welcome to open a PR doing so!
