### ISSUE TITLE
PAT creation section: possible incorrect info

### ISSUE THREAD

**Issue by niraj8** [github/docs#2660]
### What article on docs.github.com is affected?

This one -> https://docs.github.com/en/free-pro-team@latest/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry

### What part(s) of the article would you like to see updated?
[Authenticating with the container registry](https://docs.github.com/en/free-pro-team@latest/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry)

The article mentions create a PAT with `write:packages` but without `repo` access

<img width="686" alt="Screenshot 2021-01-08 at 12 08 19 AM" src="https://user-images.githubusercontent.com/8666468/103931010-a18e8f80-5145-11eb-9e5d-0220cb62286c.png">

This is not possible right now👇
<img width="555" alt="Screenshot 2021-01-08 at 12 09 32 AM" src="https://user-images.githubusercontent.com/8666468/103931126-cb47b680-5145-11eb-918a-088bfe15f750.png">

**Comment by chiedo** [comment]
@niraj8  Thanks for opening an issue! I’ll triage this for the right team to take a look 👀

**Comment by thatInfrastructureGuy** [comment]
The workaround I used was to create PAT with `repo` and `write:packages` permissions. Once the PAT was created I updated the permissions and removed the non-essential `repo` permissions. I was still able to build and push docker image to ghcr.io registry with the reduced permissions.

**Comment by dgholz** [comment]
> Once the PAT was created I updated the permissions and removed the non-essential `repo` permissions.

I don't see how to edit a PAT's scope once it's created, I can only delete it. How did you remove the permission?

**Comment by niraj8** [comment]
> I don't see how to edit a PAT's scope once it's created, I can only delete it. How did you remove the permission?

Clicking on the title of a token should allow you to edit its scopes
On this page https://github.com/settings/tokens

**Comment by giovannidegani** [comment]
Now for me even when editing the repo permissions are selected and greyed out.

**Comment by amrwc** [comment]
> > Once the PAT was created I updated the permissions and removed the non-essential `repo` permissions.
> 
> I don't see how to edit a PAT's scope once it's created, I can only delete it. How did you remove the permission?

It doesn't work anymore, at least as of today, and the comment above also mentions that it's greyed out:

> Now for me even when editing the repo permissions are selected and greyed out.

Screenshot from `https://github.com/settings/tokens/<token_id>`:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/42574496/109419770-038da780-79c7-11eb-9a9e-c2ee0f61a5ee.png">

**Comment by janiceilene** [comment]
👋 Hey folks, if you're having any confusion related to what you're seeing in your individual accounts, you should check in with our wonderful [support team](https://support.github.com/contact)!

**Comment by philipreimer** [comment]
@janiceilene there is no confusion. The docs state to
>  deselect the repo scope when creating the PAT. 

But this is currentyl not possible. Selecting the `write:packages` scope for a PAT will automatically select the `repo` scope.
And the `repo` scope cannot be **de**selected **unless** you also **de**select the `write:packages` scope.

According to the docs your PAT needs the `write:packages` scope to push docker images to the new "improved container registry".

So either the docs are wrong and must be fixed or there is a serious bug in the Create PAT page.

**Comment by jmarlena** [comment]
Hey folks! I confirmed this behavior is new. I've surfaced this to the packages engineering team. We can update our docs in the meantime! ❤️

**Comment by philipreimer** [comment]
@jmarlena any status update from the packages engineering team? The bug still exists on the Create PAT page. Is there an issue for this, which we can upvote and follow?

Also, the docs still haven't been updated.

**Comment by Draya007** [comment]
Errors?

**Comment by jmarlena** [comment]
Sorry for the wait everyone. We have a proposed workaround from the engineering team. I'll follow-up once it's live.

**Comment by jmarlena** [comment]
Heads up about these workarounds:  
A) Use this url `https://github.com/settings/tokens/new?scopes=write:packages`, which allows you to avoid the automatic `repo` scope selection in the UI. 
B) Now GitHub Container Registry supports using the `GITHUB_TOKEN` for GitHub Actions workflows so you don't have to use a PAT in a workflow anymore to push docker images to `ghcr.io` anymore.
