### ISSUE TITLE
Add information on how to merge pull requests on the GitHub mobile app

### ISSUE THREAD

**Issue by CBID2** [github/docs#26617]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Merging Pull Requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request)

### What part(s) of the article would you like to see updated?

It took me a while to figure out how to merge PRs on the GitHub mobile app, so I think it would be beneficial to add this information in a separate tab titled "Mobile app". It'll help people who are new to the app.  

### Additional information

I would like to work on this if allowed.

**Comment by cmwilson21** [comment]
@CBID2 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@CBID2 No problem! In the meantime, if you'd like to find other ways to contribute, check out our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. ✨

**Comment by CBID2** [comment]
> @CBID2 No problem! In the meantime, if you'd like to find other ways to contribute, check out our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. ✨ 
> 
> 

Thanks @cmwilson21, but I want to work on this one as I mentioned in the additional information section.

**Comment by Vinzaldehydes** [comment]
The encrypted messages

**Comment by Abrarhaj** [comment]
ok

**Comment by Tlmw6Xa5QyOYx0102Zg** [comment]
![AI art](https://github.com/github/docs/assets/102624764/7ecb7476-3f99-44a1-af3c-d2110624e963)

**Comment by jules-p** [comment]
Hi @CBID2 👋🏻 I've left you a comment in the [PR](https://github.com/github/docs/pull/26822#issuecomment-1638291998) but just wanted to reiterate our thanks for you being a part of the docs OS community. ✨
