### ISSUE TITLE
fix: remove extra space in remote url

### ISSUE THREAD

**Issue by Namnika** [github/docs#26625]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Thank you for this great docs! 
I found extra space in remote urls in this [getting started topic](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#switching-remote-urls-from-https-to-ssh)

```
$ git remote -v
# Verify new remote URL
> origin  git@github.com: OWNER/REPOSITORY.git (fetch) <--extra space
> origin  git@github.com: OWNER/REPOSITORY.git (push) <--extra space
```

### What part(s) of the article would you like to see updated?

I would like to remove those extra spaces from those remote URLs
I have already shared this #26622

**Comment by Namnika** [comment]
#26622

**Comment by cmwilson21** [comment]
@Namnika Thanks! and thanks so much for opening an issue! ✨
