### ISSUE TITLE
Content has wrong formats

### ISSUE THREAD

**Issue by charmian01** [github/docs#26629]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.9/admin/enterprise-management/configuring-clustering/evacuating-a-cluster-node-running-data-services

The below command shows wrong format that display the HTML and CSS codes.
<img width="716" alt="Screenshot 2023-07-12 at 15 12 58" src="https://github.com/github/docs/assets/23711238/5763c61b-d9c7-4464-aea5-2e963477e0fd">

<img width="678" alt="Screenshot 2023-07-12 at 15 13 12" src="https://github.com/github/docs/assets/23711238/d40b2d50-e7a7-481b-8eb9-49c7f11e7c56">

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/enterprise-server@3.9/admin/enterprise-management/configuring-clustering/evacuating-a-cluster-node-running-data-services
https://docs.github.com/en/enterprise-server@3.8/admin/enterprise-management/configuring-clustering/evacuating-a-cluster-node-running-data-services
https://docs.github.com/en/enterprise-server@3.7/admin/enterprise-management/configuring-clustering/evacuating-a-cluster-node-running-data-services
https://docs.github.com/en/enterprise-server@3.6/admin/enterprise-management/configuring-clustering/evacuating-a-cluster-node-running-data-services
https://docs.github.com/en/enterprise-server@3.5/admin/enterprise-management/configuring-clustering/evacuating-a-cluster-node-running-data-services

Excepted outcome:
<img width="668" alt="Screenshot 2023-07-12 at 15 31 03" src="https://github.com/github/docs/assets/23711238/6254d0d6-0c04-46f0-becf-bbba73222e90">

**Comment by cmwilson21** [comment]
@charmian01 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @charmian01! It looks like there are a few issues with formatting in this article. I'll open a PR to fix them now. ⚡
