### ISSUE TITLE
Quotes missing in YAML issue form template 

### ISSUE THREAD

**Issue by larsmaxfield-asml** [github/docs#26640]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

### What part(s) of the article would you like to see updated?

The YAML issue form template (which is the conversion of the Markdown template) is missing quotes around the individual labels Bug and Needs Triage: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#yaml-issue-form-template

![image](https://github.com/github/docs/assets/129512384/ace17259-f89f-406f-b929-d39848c91363)

The consequence is that if users directly copy the template, then the issue form won't add those labels to the issues it creates.

The solution is to add quotes to those labels.

**Comment by cmwilson21** [comment]
@larsmaxfield-asml Thank you for opening an issue and linking it to your PR! ✨
