### ISSUE TITLE
Missing permissions for deleting a discussion

### ISSUE THREAD

**Issue by megbird** [github/docs#2665]
### What article on docs.github.com is affected?

[Repository permission levels for an organization](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) 

### What part(s) of the article would you like to see updated?

We need to add a new row in the table, near the other GitHub Discussions content, for deleting a discussion. 

### Additional information

People with Maintain and Admin permissions can delete a discussion ⚡ 

/cc @evi-liu

**Comment by hubwriter** [comment]
PR https://github.com/github/docs/pull/2680 merged.
