### ISSUE TITLE
Can't find the REST API docs for creating runner groups

### ISSUE THREAD

**Issue by rajbos** [github/docs#26680]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I can't seem to find the API calls for creating / configuring runner groups in the docs: https://docs.github.com/en/rest/actions?apiVersion=2022-11-28
Luckily I asked Copilot for Docs and found that I create a POST call to `https://api.github.com/orgs/ORG/actions/runner-groups` and that works. Am I overlooking it in the docs? 

I would expect it to show up here, but there is nothing shown: https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

Fix the reason why this is missing 😺

**Comment by habeebhossin34** [comment]
> 
> 
> 
>

**Comment by Beet1998** [comment]
🤦‍♂️

**Comment by jc-clark** [comment]
Hey @rajbos, thanks for calling this out! I'm taking a closer look at this one and will get back to you once I find an answer/next steps!

**Comment by SiaraMist** [comment]
Hey @rajbos, it looks like we do have docs for this, but they are only visible in the Enterprise versions of the docs: https://docs.github.com/en/enterprise-cloud@latest/rest/actions/self-hosted-runner-groups?apiVersion=2022-11-28. 

I'm going to open an issue internally to update this so people using GitHub Team can also easily find these docs. Thank you for raising this! ⚡
