### ISSUE TITLE
Fine-Grained token links to invalid doc.github.com url

### ISSUE THREAD

**Issue by CaedenPH** [github/docs#26684]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The url https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens
Shows lots of useful information about each individual permission, with each permission having an id set to the permission name, for example `organization-permissions-for-administration`. This allows users to visit a url such as https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens#organization-permissions-for-administration with the id appending to the end of the url, in order to see that particular permission.

However, when creating a new fine-grained token from https://github.com/settings/personal-access-tokens/new and viewing the permissions, the info icon directs to a docs.github.com link **with the wrong id**. 
This can be seen when clicking the first permission, `blocking`.
The info icon directs to https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#blocking whereas the correct url is https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#organization-permissions-for-blocking-users
The id should be `organization-permissions-for-blocking-users`, not `blocking`, hence a broken link

### What changes are you suggesting?

I'm not sure if this is the correct place to make this issue, it may not be a fault with the docs, but rather the internal github settings. Either the docs or the github settings needs to change the id/link in order to direct to the correct heading

**Comment by cmwilson21** [comment]
@CaedenPH Thanks for opening an issue. This is an interesting one. I'm not sure where is best to handle it, so I'm going to go ahead and triage it and run it by the docs team, but I suspect you may right in that it may be an issue for an internal repo.

In the mean time, perhaps filing a [bug report](https://support.github.com/contact/bug-report) could be helpful? 

Thanks again for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by saritai** [comment]
@CaedenPH Thank you so much for highlighting this! ✨ As you stated above, this is something that will need to be fixed internally. I've notified the team about this so that we can get that fixed! I'm going to go ahead and close this issue since there are no changes needed on the docs side 👍
