### ISSUE TITLE
Docu missing bsd-4-clause from the list of license keys

### ISSUE THREAD

**Issue by mattseaborn** [github/docs#26702]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

### What part(s) of the article would you like to see updated?

The list of licenses in the section [Searching GitHub by license type](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type) needs to have bsd-4-clause added with the name `BSD 4-clause "Original" or "Old" license`

**Comment by Amirko29** [comment]
Sent from Yahoo Mail on Android 
 
  On الثلاثاء, يوليو ١٨, ٢٠٢٣ at ٦:١٦ م, Felicity ***@***.***> wrote:   


Closed #26702 as completed via #26703.
