### ISSUE TITLE
The cURL code samples in the API docs have a typo in the Authorization Header line

### ISSUE THREAD

**Issue by WhiteFruit** [github/docs#26708]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Seemingly all instances of cURL code samples in the API docs include the below typo. I have only spot-checked, but tracking the source of the issue leads me to believe all instances would have the same problem.

<img width="618" alt="Screenshot 2023-07-14 at 10 30 13 AM" src="https://github.com/github/docs/assets/57506040/f6203a83-4fee-4cb9-ae32-dc38ec9d88f0">

If you copy/paste that full command (replacing the necessary variables "\<YOUR-TOKEN\>", "OWNER", and "REPO" with valid values), you will get a cURL error:

```
curl: (3) URL using bad/illegal format or missing URL
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```

### What changes are you suggesting?

The authorization header line in the cURL code samples should have a space before the backslash escape character at the end of the line:
`-H "Authorization: Bearer <YOUR-TOKEN>"\` should be `-H "Authorization: Bearer <YOUR-TOKEN>" \`

<img width="606" alt="Screenshot 2023-07-14 at 10 30 52 AM" src="https://github.com/github/docs/assets/57506040/be930995-a508-4d01-a61d-01026ae86c75">

I opened [PR #26706](https://github.com/github/docs/pull/26706) to address this, but the [file](https://github.com/github/docs/blob/main/src/rest/components/get-rest-code-samples.ts#L91) is restricted since it's in the src directory.

**Comment by cmwilson21** [comment]
@WhiteFruit Thanks for opening an issue! As you stated, we don't accept changes to those files in that repo. We had a similar issue reported recently that I transferred over to the [/rest-api-description](https://github.com/github/rest-api-description) repo, so I'm going to go ahead and add this issue there, as well. Here's [the link](https://github.com/github/rest-api-description/issues/2737) to it.

I'm going to go ahead and close this issue. But thanks for opening and for your interest in improving the docs! 💖
