### ISSUE TITLE
Create a review comment for a pull request issue with subject_type

### ISSUE THREAD

**Issue by vanya20074** [github/docs#26844]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request

### What changes are you suggesting?

In the description of `subject_type` defined that it can be one of: `LINE, FILE `. At the same time API call return error:
```
{
    "message": "Invalid request.\n\nNo subschema in \"oneOf\" matched.\n\"position\" wasn't supplied.\n\"in_reply_to\" wasn't supplied.\n\"subject_type\" is not a permitted key.\n\"line\" wasn't supplied.\nFILE is not a member of [\"line\", \"file\"].",
    "documentation_url": "https://docs.github.com/rest/pulls/comments#create-a-review-comment-for-a-pull-request"
}
```
When I use `subject_type` with a lowercase value `file` it's working fine. I think docs need to be changed with lowercase values for  `subject_type: line, file` instead of `LINE, FILE`

<img width="518" alt="image" src="https://github.com/github/docs/assets/2856781/f4edb5ce-c8e0-437c-a78f-ad203b24c53b">

**Comment by cmwilson21** [comment]
@vanya20074 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cmwilson21** [comment]
@vanya20074 Sorry, I'm not able to confirm that info. These types of changes need to be made internally, so that is where the review will take place as well. It's been transferred to our internal board. I'll reference your question in the issue, though. 💛

**Comment by EnricoMi** [comment]
Note that the API indicates that `side` and `start_side` expect uppercase strings. This is counter-intuitive.

Please harmonize those to be lowercase or uppercase across all attributes, or case-insensitive ideally.

**Comment by telaviv** [comment]
I'm still having this issue in 2024. "LINE" and "position" resolve the issue even though the docs say otherwise. I'm using api version `2022-11-28` because that's what the docs say is the latest https://docs.github.com/en/rest/about-the-rest-api/api-versions

**Comment by nguyenalex836** [comment]
> I'm still having this issue in 2024. "LINE" and "position" resolve the issue even though the docs say otherwise. I'm using api version `2022-11-28` because that's what the docs say is the latest https://docs.github.com/en/rest/about-the-rest-api/api-versions

@telaviv Thank you for raising a flag on this! ✨ Given the age of this issue, would you be able to open a new issue in this repo and include the contents of your comment? We'll then have the appropriate team investigate on our end 💛
