### ISSUE TITLE
Incorrect response shown in REST API for GHES

### ISSUE THREAD

**Issue by rajbos** [github/docs#26904]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This [document](https://docs.github.com/en/enterprise-server@3.8/rest/dependency-graph/dependency-review) still says that the response will have a filled field for 'license', which is does not have on GHES (the field contains `null`). This support has been removed from the server it seems and the field is now empty. This lowers the usage of things like the dependency-review-action and should be clear in the docs that the field is empty. Same for the field `source_repository_url`.

Example response:
``` json
[
  {
    "change_type": "removed",
    "manifest": "package.json",
    "ecosystem": "npm",
    "name": "helmet",
    "version": "4.6.0",
    "package_url": "pkg:npm/helmet@4.6.0",
    "license": "MIT",
    "source_repository_url": "https://github.com/helmetjs/helmet",
    "vulnerabilities": []
  },
  {
    "change_type": "added",
    "manifest": "package.json",
    "ecosystem": "npm",
    "name": "helmet",
    "version": "5.0.0",
    "package_url": "pkg:npm/helmet@5.0.0",
    "license": null,
    "source_repository_url": null,
    "vulnerabilities": []
  },
  {
    "change_type": "added",
    "manifest": "Gemfile",
    "ecosystem": "rubygems",
    "name": "ruby-openid",
    "version": "2.7.0",
    "package_url": "pkg:gem/ruby-openid@2.7.0",
    "license": null,
    "source_repository_url": null,
    "vulnerabilities": [
      {
        "severity": "critical",
        "advisory_ghsa_id": "GHSA-fqfj-cmh6-hj49",
        "advisory_summary": "Ruby OpenID",
        "advisory_url": "https://github.com/advisories/GHSA-fqfj-cmh6-hj49"
      }
    ]
  }
]
```

### What part(s) of the article would you like to see updated?

The field in the response should be empty for the GHES versions where it is empty (not sure how far back this goes)

**Comment by cmwilson21** [comment]
Hey @rajbos 👋 

Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! Looking at the response schema, it looks like this field is defined as string or null, indicating that the field value can be either. Are you expecting that the response schema (and therefore the corresponding example) to say that this value can _only_ be null?

<img width="660" alt="image" src="https://github.com/github/docs/assets/25328854/7bf615d6-a94a-47d5-b741-ac46a4b2a0bd">

**Comment by Bellchel** [comment]
# GitHub CLI api
# https://cli.github.com/manual/gh_api

gh api \
  --method DELETE \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /repos/OWNER/REPO/actions/artifacts/ARTIFACT_ID

**Comment by Artyrchan** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> This [document](https://docs.github.com/en/enterprise-server@3.8/rest/dependency-graph/dependency-review) still says that the response will have a filled field for 'license', which is does not have on GHES (the field contains `null`). This support has been removed from the server it seems and the field is now empty. This lowers the usage of things like the dependency-review-action and should be clear in the docs that the field is empty. Same for the field `source_repository_url`.
> 
> 
> 
> Example response:
> 
> ``` json
> 
> [
> 
>   {
> 
>     "change_type": "removed",
> 
>     "manifest": "package.json",
> 
>     "ecosystem": "npm",
> 
>     "name": "helmet",
> 
>     "version": "4.6.0",
> 
>     "package_url": "pkg:npm/helmet@4.6.0",
> 
>     "license": "MIT",
> 
>     "source_repository_url": "https://github.com/helmetjs/helmet",
> 
>     "vulnerabilities": []
> 
>   },
> 
>   {
> 
>     "change_type": "added",
> 
>     "manifest": "package.json",
> 
>     "ecosystem": "npm",
> 
>     "name": "helmet",
> 
>     "version": "5.0.0",
> 
>     "package_url": "pkg:npm/helmet@5.0.0",
> 
>     "license": null,
> 
>     "source_repository_url": null,
> 
>     "vulnerabilities": []
> 
>   },
> 
>   {
> 
>     "change_type": "added",
> 
>     "manifest": "Gemfile",
> 
>     "ecosystem": "rubygems",
> 
>     "name": "ruby-openid",
> 
>     "version": "2.7.0",
> 
>     "package_url": "pkg:gem/ruby-openid@2.7.0",
> 
>     "license": null,
> 
>     "source_repository_url": null,
> 
>     "vulnerabilities": [
> 
>       {
> 
>         "severity": "critical",
> 
>         "advisory_ghsa_id": "GHSA-fqfj-cmh6-hj49",
> 
>         "advisory_summary": "Ruby OpenID",
> 
>         "advisory_url": "https://github.com/advisories/GHSA-fqfj-cmh6-hj49"
> 
>       }
> 
>     ]
> 
>   }
> 
> ]
> 
> ```
> 
> 
> 
> ### What part(s) of the article would you like to see updated?
> 
> The field in the response should be empty for the GHES versions where it is empty (not sure how far back this goes)
> 
> ### Additional information
> 
> _No response_
