### ISSUE TITLE
Rest documentation response boxes are overflowing

### ISSUE THREAD

**Issue by aanzolaavila-meli** [github/docs#26914]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28

Using Google Chrome Version 114.0.5735.198 (Official Build) (x86_64)
Also used Firefox Developer Edition 116.0b5

![image](https://github.com/github/docs/assets/119542057/9235562d-70b0-4170-ac3d-ae4cab6bf8cb)

### What changes are you suggesting?

The response text should be contained within the boxes.

**Comment by slimwilbard** [comment]
Help me verify my account

**Comment by cmwilson21** [comment]
@aanzolaavila-meli Thanks for opening an issue! I _believe_ this has been fixed now, so I'm going to go ahead and close it. If you are still seeing these problems on your side, let me know 👍
