### ISSUE TITLE
Incorrect image instructions for viewing and managing subscriptions

### ISSUE THREAD

**Issue by kimichenn** [github/docs#26957]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions

### Issue
The images on [Viewing your subscriptions](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions) and [Managing your subscriptions](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions) are outdated and does not follow the current UI layout.

### Expected
<img width="342" alt="Screenshot 2023-07-22 073555" src="https://github.com/github/docs/assets/66824523/7db3f16a-2fba-40dc-998e-d463f480d2b3">

### Actual
![image](https://github.com/github/docs/assets/66824523/ea2acbdf-1829-4ae5-b607-e4cfa6fb77f5)

**Comment by cmwilson21** [comment]
@kimichenn Thank you for opening an issue and linking it to your PR! ✨

**Comment by felicitymay** [comment]
Hi @kimichenn 👋🏻 

As discussed in your pull request to update the image, you're right that this area of the interface is changing, but the change is not yet visible to all users. 

The change is available as a [feature preview for a beta release](https://docs.github.com/en/get-started/using-github/exploring-early-access-releases-with-feature-preview#exploring-beta-releases-with-feature-preview), which people can opt out of and provide feedback about any problems they find. Sometimes the engineering or design team make changes to the interface or behavior before making the change permanently visible to all users (generally available).

We wait to update the docs until a change is generally available. This means that the interface is stable and agreed before we revise the screenshots. It also means that during a feature preview the documentation will only match what some users see. 

We will update this image, and many more, when the changes to global navigation move out of the feature preview and are made generally available.
