### ISSUE TITLE
Update Copilot Chat images to be more obvious

### ISSUE THREAD

**Issue by mdeeks** [github/docs#26952]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/github-copilot-chat/using-github-copilot-chat?tool=vscode

### What part(s) of the article would you like to see updated?

The existing images for VSCode show a generic search tab and only have a small non-obvious rectangle to indicate what the user should click. We had multiple people confused by the docs as we ran through onboarding.
![image](https://github.com/github/docs/assets/2966467/556d3d58-0768-43ce-af8f-1dacf2d57214)
![image](https://github.com/github/docs/assets/2966467/feb94dbf-7a02-4d1a-80e5-f50a56696d22)

I have a PR here to update the images: https://github.com/github/docs/pull/26949

**Comment by cmwilson21** [comment]
@mdeeks Thank you for opening an issue and linking it to your PR! ✨

**Comment by sineels** [comment]
>

**Comment by cmwilson21** [comment]
Closing per https://github.com/github/docs/pull/26949#issuecomment-1649419914
