### ISSUE TITLE
docs: Remove duplicate ssh-keygen command in Github AE documentation

### ISSUE THREAD

**Issue by valxntine** [github/docs#26967]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/github-ae@latest/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

### What part(s) of the article would you like to see updated?

Step 2 of `Generated a new SSH key` currently shows the user needs to run two of the same commands to generate a new key. The code block in step 2 should just contain one command, removing the duplicate.

### Additional information

![image](https://github.com/github/docs/assets/24855366/21622809-6895-4346-ab64-2f1a17ffb926)

**Comment by cmwilson21** [comment]
@valxntine Thank you for opening an issue and linking it to your PR! ✨
