### ISSUE TITLE
Page header says "GPG key" instead of "SSH key" in French translation

### ISSUE THREAD

**Issue by xefyrdev** [github/docs#26976]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/fr/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

### What part(s) of the article would you like to see updated?

The 2nd header of the page says
> Génération d’une nouvelle clé GPG

It should say
> Génération d'une nouvelle clé SSH

**Comment by cmwilson21** [comment]
@xefyrdev Thanks for reporting this! We use an internal automated solution for translations. I'll flag this for our team. 👍 

Since we will be looking at this internally, I'm going to go ahead and close the issue now 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
