### ISSUE TITLE
Hyperlink on GitHub event types page points to incorrect resource

### ISSUE THREAD

**Issue by sandormatyas** [github/docs#27058]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/webhooks-and-events/events/github-event-types#event-payload-object-for-releaseevent

### What part(s) of the article would you like to see updated?

The hyperlink on the release object. 

Right now it is pointing to https://docs.github.com/en/rest/repos#get-a-release which I believe to be incorrect, since the object is not about repos and the anchor does not exists on the page.

In my opinion it should point to https://docs.github.com/en/rest/releases/releases#get-a-release.

I think the current link is confusing and slows down navigating the docs.

### Additional information

![image](https://github.com/github/docs/assets/53257021/e9ee09a9-5c0b-49a8-a0d9-662cd71fcf0c)

**Comment by cmwilson21** [comment]
@sandormatyas Thank you for opening an issue and linking it to your PR! ✨
