### ISSUE TITLE
Undocumented event "PullRequestReviewEvent"

### ISSUE THREAD

**Issue by lowlighter** [github/docs#2709]
### What article on docs.github.com is affected?

* https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/github-event-types

### What part(s) of the article would you like to see updated?

Seems that while both *PullRequestEvent* and *PullRequestReviewCommentEvent* are referenced, but *PullRequestReviewEvent* is not.

### Additional information

Below is an extract of what the event looks like.
```js
  {
    id: '14732962106',
    type: 'PullRequestReviewEvent',
    actor: {...},
    repo: {...},
    payload: {
      action: 'created',
      review: {
        user: {...},
        body: '',
        state: 'approved',
      },
      pull_request: {
        user: {...},
        body: '',
        head: {...},
        base: {...},
        _links: {...},
      }
    },
    public: true,
    created_at: '2021-01-06T16:45:16Z'
  }
```

**Comment by adamhayrettin11** [comment]
Tesekkur

9 Oca 2021 Cmt 13:55 tarihinde Simon Lecoq <notifications@github.com> şunu
yazdı:

**Comment by adamhayrettin11** [comment]
A

9 Oca 2021 Cmt 13:55 tarihinde welcome[bot] <notifications@github.com> şunu
yazdı:

**Comment by kiepngheonha** [comment]
> Cảm ơn bạn đã mở vấn đề này. Một thành viên trong nhóm tài liệu GitHub nên sớm đưa ra phản hồi. Trong thời gian chờ đợi, vui lòng xem các [nguyên tắc đóng góp](https://github.com/github/docs/blob/main/CONTRIBUTING.md) .

https://github.com/github/docs/issues/2722#issue-782642522

**Comment by chiedo** [comment]
@lowlighter Thanks for opening an issue! I’ll triage this for the right team to take a look 👀

**Comment by runleonarun** [comment]
Thanks for opening this issue, @lowlighter! 

Looks like the issue is we need to add the reusables found here:
https://github.com/github/docs/blob/main/data/reusables/webhooks/pull_request_review_properties.md
https://github.com/github/docs/blob/main/data/reusables/webhooks/pull_request_review_short_desc.md
https://github.com/github/docs/blob/main/data/reusables/webhooks/events_api_payload.md

To this page:
https://github.com/github/docs/blob/main/content/developers/webhooks-and-events/github-event-types.md

We also need to create a reusable for `pull_request_review_event_api_properties.md` and add it to the above file. I'd need to test this to see what it should include.

**Comment by runleonarun** [comment]
To @lowlighter or anyone who wants to fix this, I just wanted to add some more details:

To fix this issue and add  `PullRequestReviewEvent` to the [GitHub Event Types](https://docs.github.com/en/developers/webhooks-and-events/github-event-types) page, you would add a new section with headings and content from reusable files.

For example, you would add the following to the [github-event-type.md](https://github.com/github/docs/blob/main/content/developers/webhooks-and-events/github-event-types.md) file after `PullRequestEvent` and before`PullRequestReviewCommentEvent`

```
 ### PullRequestReviewEvent

{% data reusables.webhooks.pull_request_review_short_desc %}
{% data reusables.webhooks.events_api_payload %}

#### Event `payload` object

{% data reusables.webhooks.pull_request_review_properties %}

```

**Comment by lowlighter** [comment]
So something like https://github.com/github/docs/compare/main...lowlighter:main ?

I assume that there are more actions than just `created` but seems you're already experimenting on it.
If not I can test from my side and add the one I found 🙂

**Comment by lowlighter** [comment]
@runleonarun 

I tried all three actions available for pull requests reviews: 
<img src="https://user-images.githubusercontent.com/22963968/110222592-9cdf2100-7ed3-11eb-9160-0e0d08529252.png" width="700">

And it seems that the only action possible for `PullRequestReviewEvent` payload is `created` (like [`CommitCommentEvent`](https://docs.github.com/en/developers/webhooks-and-events/github-event-types#commitcommentevent)), as review state is located deeper in the payload: 

```js
{
  action: 'created',
  review: {
    id: 605791516,
    node_id: 'MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NjA1NzkxNTE2',
    state: 'approved',
  },
}
{
  action: 'created',
  review: {
    id: 605791495,
    node_id: 'MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NjA1NzkxNDk1',
    state: 'changes_requested',
  },
}
{
  action: 'created',
  review: {
    id: 605791475,
    node_id: 'MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NjA1NzkxNDc1',
    state: 'commented',
}
```

So I guess that PR #4330 is fine, though not sure why the YAML tables are not merged like the other events:

<img src="https://user-images.githubusercontent.com/22963968/110222788-22af9c00-7ed5-11eb-8f11-a80df7127d96.png" width="400">

Also, I noticed some actions were already defined in `data reusables.webhooks.pull_request_review_properties`, but these does not seems to match what the API actually returns ([examples of event](https://api.github.com/repos/lowlighter/debug-metrics/events?per_page=1))

**Comment by runleonarun** [comment]
@lowlighter Thanks for being patient on this! I will try to come back to this by the ned of the week. I'm guessing `data reusables.webhooks.pull_request_review_properties` was copy and paste error 🍝  and perhaps would have been caught had we added the PullRequestReviewEvent."

**Comment by lecoursen** [comment]
Hi there! I just dug into this for Leona. It doesn't look like we'll be able to use this reusable after all. Currently, the reusable is being used in `webhook-events-and-payloads.md` and from my testing, the content is accurate there. I did get `submitted`, etc for `action` in a webhook payload. However, the payload for the Events API is only returning `created`, as you discovered. For that reason, the `changes[body][from]` key (which, as the reusable states, is only included when the `action` is `edited`) will never be shown. So, 50% of the keys in the reusable only apply to webhook payloads.

@lowlighter, that means we should delete the reusable, replace the reference to the reusable in `webhook-events-and-payloads.md` with the reusable's current content, and create a new table in `github-event-types.md` that contains the appropriate keys for the Events API payload.
