### ISSUE TITLE
`Create a repository using a template`'s parameter description has no data

### ISSUE THREAD

**Issue by zunda-pixel** [github/docs#27104]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Create a repository using a template API](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-using-a-template)

### What part(s) of the article would you like to see updated?

Path parameters Description

## Current

|Name|Type| Required | Description |
|--|--|--|--|
|template_owner| string| Required||
|template_repo| string| Required||

## Example

|Name|Type| Required | Description |
|--|--|--|--|
|template_owner| string| Required|The account owner of the template repository. The name is not case sensitive.|
|template_repo| string| Required|The name of the template repository without the .git extension. The name is not case sensitive.|

**Comment by Hann532** [comment]
> 

https://github.com/github/docs/issues/27104#issuecomment-1653468423

**Comment by cmwilson21** [comment]
@zunda-pixel Thanks for opening an issue! Just to confirm, you're requesting that we add descriptions to these two parameters?

**Comment by zunda-pixel** [comment]
Yes!

**Comment by cmwilson21** [comment]
@zunda-pixel Thanks for confirming! I'll triage for review 👀
