### ISSUE TITLE
`watch` event's activity type `starred` is wrong. The correct activity type is `started`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [github/docs#27129]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#watch

### What part(s) of the article would you like to see updated?

<img width="797" alt="image" src="https://github.com/github/docs/assets/13323303/f6137e1b-5575-497c-8f5e-eb6b739efe53">

`watch` event's action type `starred` is wrong. The correct action type is `started`.
The example code doesn't trigger workflows even if a repository is starred.

### Additional information

I created a repository to reproduce the issue.

https://github.com/suzuki-shunsuke/github-docs-27127

I created a pull request to resolve this issue.

- https://github.com/github/docs/pull/27127

The webhook action is not `starred` but `started`.

https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#watch

> Webhook payload object for watch
> Someone started watching the repository.
> Webhook request body parameters
> Name, Type, Description
> action string Required
> Value: started

<img width="374" alt="image" src="https://github.com/github/docs/assets/13323303/2635352d-1759-46f9-b3a3-f9b123833932">

**Comment by suzuki-shunsuke** [comment]
Previously, the action type was correct.
But the action type was changed wrongly by this pull request.

- https://github.com/github/docs/pull/25021

@steveward pointed out it, but the pull request was merged. I'm not sure why the pull request was merged.

- https://github.com/github/docs/pull/25021#issuecomment-1508705322

**Comment by cmwilson21** [comment]
@suzuki-shunsuke Thank you for opening an issue and linking it to your PR! ✨
