### ISSUE TITLE
Formatting is not applied correctly on 'Adding ssh-key steps ..'

### ISSUE THREAD

**Issue by Mallikarjunople** [github/docs#27153]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I am noticing the issue in [this article](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=windows). When I switched the tab to `Windows` I faced this issue in the formatting for steps in the `Adding your SSH key to the ssh-agent` section. I have attached the screenshot and video recording of the same. I also tried refreshing the browser but issue persists.
**Screenshot:**
![github-docs-issue](https://github.com/github/docs/assets/45136568/ae0c6fb3-960a-4b35-872f-90b2aff89720)
**Video:**
https://github.com/github/docs/assets/45136568/7c270f0e-b7d0-4aa0-8a72-bfd7c680e72c

I am using a mac mini with macOS Venture 13.4 and my browser is Google chrome (Version 115.0.5790.114 (Official Build) (arm64)). 

For macOS and linux, the formatting for the steps looks correct but for `windows` tab, the formatting is not correct. 

### What changes are you suggesting?

I suggest that the issue should be fixed as soon as possible. The formatting should be seen equivalent for all macOS, windows and linux platform tabs in the docs. 

This is required as new readers might get bad UI experience when referring the docs.
Fixing this issue will help the readers of the docs to be able to refer the docs smoothly.

**Comment by dane** [comment]
@Mallikarjunople this should be fixed as of today in github/docs#27174.

**Comment by cmwilson21** [comment]
@Mallikarjunople Thanks for opening an issue! As @dane stated, this was fixed internally. If you are still having issues with it, let me know and I'll reopen, but going ahead and closing it now 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
