### ISSUE TITLE
Button text is different than what a step describes in "Adding your project to a repository" doc

### ISSUE THREAD

**Issue by agentolivia** [github/docs#27248]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/adding-your-project-to-a-repository

### What changes are you suggesting?

Step 3 says "Click Add project", but the button is actually dropbutton with the default option "Link a project". The subsequent steps are still accurate.

The docs should be changed to reflect the current UI of a repository's project page.

**Comment by cmwilson21** [comment]
@agentolivia Thanks for opening an issue and submitting a PR! ⚡
