### ISSUE TITLE
@MarcPow you can do this with the JSON output and `jq` or some other tool that speaks JSON. As an example:

### ISSUE THREAD

**Issue by ronzkiey** [github/docs#27251]
@MarcPow you can do this with the JSON output and `jq` or some other tool that speaks JSON. As an example:

```
gh projects item-list --org <YOUR_ORG> <PROJECT_NUMBER> --format=json | jq '.items[] | select(.status=="In Progress"  and .content.type == "Issue")’
```

_Originally posted by @mntlty in https://github.com/github/gh-projects/issues/93#issuecomment-1577165339_

**Comment by cobertvc** [comment]
Me podrías apoyar con la trasferencia Paypal  $6,700  gracias
