### ISSUE TITLE
Typo in docs for Enterprise Server 3.8- Check organization membership for a user 

### ISSUE THREAD

**Issue by natashamm** [github/docs#27266]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Under [Check organization membership for a user](https://docs.github.com/en/enterprise-server@3.8/rest/orgs/members#check-organization-membership-for-a-user) for Enterprise server 3.8 - the status code I get when using the API is different from the docs.

According to the docs you would expect a 302 status code if `requester is not an organization member`

<img width="605" alt="docs" src="https://github.com/github/docs/assets/22650546/1f13f29b-8887-439c-8b95-c2082dabba4e">

However, when making a get request /orgs/{org}/members/{username} (where `org` is an organization I am not a member of and `username` is that of a user in the organization), I get a 404 status code, along with the message `User does not exist or is not a member of the organization` - which leads me to believe that the 404 status code is the expected one.

### What part(s) of the article would you like to see updated?

Update the [HTTP response status codes for "Check organization membership for a user"](https://docs.github.com/en/enterprise-server@3.8/rest/orgs/members#check-organization-membership-for-a-user--status-codes) in the docs.

**Comment by cmwilson21** [comment]
@natashamm Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by benCoomes** [comment]
👋 Hi @natashamm! I was looking into this and believe that the endpoint is working as documented. At first, I thought I was seeing the behavior you described, but then realized my API client was following the redirect to the public members endpoint: https://docs.github.com/en/enterprise-server@3.8/rest/orgs/members#check-public-organization-membership-for-a-user

The 404 message is slightly different there: "User does not exist or is not a _public_ member of the organization".
