### ISSUE TITLE
Hello World - conditional content update - Making and committing changes section

### ISSUE THREAD

**Issue by wickahead** [github/docs#27294]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Hello World](https://docs.github.com/en/get-started/quickstart/hello-world)

### What part(s) of the article would you like to see updated?

# Background
[Making and committing changes](https://docs.github.com/en/get-started/quickstart/hello-world#making-and-committing-changes) is different than what I experience (in my browser).

# Steps to reproduce
What I see when I view  [Hello World](https://docs.github.com/en/get-started/quickstart/hello-world) quickstart tutorial (experience/content is same in Chrome and Safari; whether I am logged in to GH in browser or not):
![image](https://github.com/github/docs/assets/12748090/31c21a82-f079-4ac5-a499-00b4e26b8250)

When I follow along tutorial, and to [Making and committing changes](https://docs.github.com/en/get-started/quickstart/hello-world#making-and-committing-changes) section, I see this "Commit changes" box (not "Propose changes" box).
![image](https://github.com/github/docs/assets/12748090/02fab0fc-8b0b-4d56-963e-1cdf0834e955)

# Expected Behavior
I expect the instructions to reflect "Commit changes" box (and button) language.

# Why
This document should be updated to reflect actual(/current) user experience and to reduce confusion over differing language which will lead to improve user satisfaction when learning GH.

### Additional information

Rationale for submitting (why am I doing this): I am getting back into coding and am (re-learning) GH and all the goodness around the workflows and interacting with the system. 

I am going thru the process of submitting the document improvement (a VERY minor tweak, IMO) to understand the PR process and how to contribute as a team member in a larger developer pond.

I did review the [existing open Issues](https://github.com/github/docs/issues), and did not see one that was related to this new issue. I plan on submitting a Pull Request shortly after this issue is submitted.

[maintainer edit]
### Content plan
 You, or anyone else, are welcome to submit a PR, updating the directions from "Propose changes" in steps 5 and 6 to "Commit changes".

**Comment by LuisLopez44431** [comment]
Ok thank you for that help

**Comment by cmwilson21** [comment]
@wickahead Thanks for opening an issue! Great catch! I agree, the directions should be updated to reflect the current UI. 

I'm going to put this on our `help wanted` board. You, or anyone else, are welcome to submit a PR, updating the directions from "Propose changes" in steps 5 and 6 to "Commit changes". 

If you are looking for more ways to contribute, take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. We'd love to see some PRs from you!

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by nekumartins** [comment]
i can work on this

**Comment by cmwilson21** [comment]
@nekumartins Thanks for the interest! It's on our help wanted board so you, or anyone else, are welcome to work on it!

**Comment by Shikha1234** [comment]
Is this issue still open. Can i work on this ?

**Comment by Shikha1234** [comment]
I have raised my first PR for this issue Fix - #27464. Please review and let me know if you have any question Thanks
