### ISSUE TITLE
Wrong Backslash Added To .bashrc

### ISSUE THREAD

**Issue by farzadso** [github/docs#27302]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key?platform=linux

### What changes are you suggesting?

In the link above, there is a section for the Linux platform claiming you should run the following command to add `GPG_TTY` to our `.bashrc` file.

```bash
[ -f ~/.bashrc ] && echo -e '\nexport GPG_TTY=\$(tty)' >> ~/.bashrc
```

This adds an extra backslash which is unnecessary and needs to be removed for it to work.

When running the script above, the result in the `.bashrc` file is as follows :

```bash
export GPG_TTY=\$(tty)
```

### Additional information

I've tried reproducing it both on WSL2 and Git Bash and the results are the same.

**Comment by farzadso** [comment]
I can open a PR which fixes this if my raised issue is valid.

**Comment by cmwilson21** [comment]
@farzadso Thanks for opening an issue! We have an [approved PR](https://github.com/github/docs/pull/27175) fixing something similar in the same article. Would this PR fix this issue as well?

**Comment by farzadso** [comment]
Yes. the approved PR you sent covers this issue to some extent, but it's missing a change.

I'll propose the missed change in the PR.

**Comment by cmwilson21** [comment]
Perfect! Thanks @farzadso! 💖 

If you are interested in other contribution opportunities to the docs, check out the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thanks again! 🎉

**Comment by farzadso** [comment]
Will do!

Thanks for notifying me of this section.
