### ISSUE TITLE
Project "Social Preview" tip says the opposite of the interface

### ISSUE THREAD

**Issue by epreston** [github/docs#27309]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

`content/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview.md`

content:

> Tip: Your image should be a PNG, JPG, or GIF file under 1 MB in size. For the best quality rendering, we recommend keeping the image at 640 by 320 pixels

### What part(s) of the article would you like to see updated?

> Tip: Your image should be a PNG, JPG, or GIF file under 1 MB in size. For the best quality rendering, we recommend keeping the image at 640 by 320 pixels

https://github.com/github/docs/blob/cc03f596ca5cf0632717a363adb0a51e84e6c7d2/content/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview.md?plain=1#L25C1-L26C1

The interface and screenshot below say the opposite.

### Additional information

I'd be interested to know which is correct.

**Comment by cmwilson21** [comment]
@epreston Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by epreston** [comment]
@stevecat thank you, I'll put in a PR this afternoon.
