### ISSUE TITLE
Duplication of two words phrase

### ISSUE THREAD

**Issue by oakinb** [github/docs#27311]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

GitHub Corporate Terms of Service

### What part(s) of the article would you like to see updated?

Section B: Account Terms, Sub-section 2. Account Requirements, line 3 of Unordered list three.

The phrase "to comprehensive" was duplicated twice successively.

One of them should be deleted.

**Comment by clairecharles** [comment]
Hi @oakinb  I'd love to work on this

**Comment by clairecharles** [comment]
Hi @oakinb  I'd love to work on this

**Comment by cmwilson21** [comment]
@oakinb Thanks for opening an issue with this! ✨
