### ISSUE TITLE
Add a couple of inline links to the Reusables and variables section of content-style-guide.md

### ISSUE THREAD

**Issue by hamirmahal** [github/docs#2732]
### What article on docs.github.com is affected?
This issue actually isn't in relation to an issue with docs.github.com. I'd like to improve [the "Reusables and variables" section of `contributing/content-style-guide.md`](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#reusables-and-variables) by adding a couple of inline links for convenience.

### What part(s) of the article would you like to see updated?
I would like to change the final sentence of the section I just mentioned, 

> For more information, see the data directory in the github/docs repository and the “Product names” section of this document.

so that "data directory" and "Product names" have links to the appropriate sections for faster access.

### Additional information
I think this would make it easier for first-time contributors to this repository to find the information they need. I may have a fix for this.

**Comment by chiedo** [comment]
@hamirmahal Thanks for opening an issue! Triaging this now so someone can dig in!

**Comment by emilyistoofunky** [comment]
👍🏻 Thanks @hamirmahal! You or anyone else are welcome to open a PR to make this improvement. 🔧

**Comment by MeetYourCreator** [comment]
Hi @emilyistoofunky! I've been wanting to contribute to the github docs for a while now. Can I open a pull request for this issue?

**Comment by chiedo** [comment]
Thank you @MeetYourCreator! 

We appreciate you hopping in and opening a pull request for the first time.

It looks like you opened the Pull Request on your fork rather than on this repo. Can you give it another shot but this time open the Pull Request [here](https://github.com/github/docs/pulls) instead (using your repo as a base)?

[More docs on Pull requests](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#:~:text=Use%20the%20base%20branch%20dropdown,review%2C%20click%20Create%20Pull%20Request.) if they're helpful!

**Comment by MeetYourCreator** [comment]
Hi @chiedo! Thanks so much for the quick reply. And thank you for being patient and understanding. I think I did it correctly this time. My pull request number is #2828.

Please let me know if I need to make any additional changes. Thanks again @chiedo ! -Rami

**Comment by chiedo** [comment]
I responded in the PR!

**Comment by MeetYourCreator** [comment]
Hi @chiedo, Let me start by saying THANK YOU THANK YOU THANK YOU for being so patient and helpful. I looked over the pull request documentation again, and opened up a new pull request #2829. I double-checked to make sure that I was trying to merge to the main branch for gitub-docs and that there were Files showing in the Files tab:

<img width="1356" alt="Screen Shot 2021-01-12 at 2 54 58 PM" src="https://user-images.githubusercontent.com/57572988/104366092-da808880-54e6-11eb-9b6f-7a4cc001e139.png">

I really hope I got it right this time. Thank you so much for helping to guide me along :)

**Comment by emilyistoofunky** [comment]
Hi @MeetYourCreator! Thanks so much for taking a look at this issue - it looks like the author of this issue opened a PR (#2751) earlier than you did, so we're going to merge that one. We appreciate you getting set up to contribute to this repo and look forward to working with you on future issues. ⚡

**Comment by MeetYourCreator** [comment]
Hi @emilyistoofunky! Thanks so much for letting me know. And thanks again @chiedo for the very helpful guidance :)
