### ISSUE TITLE
TeamMemberEdge is missing the node field

### ISSUE THREAD

**Issue by scribbo** [github/docs#27327]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

/graphql/reference/objects#teammemberedge
https://docs.github.com/en/graphql/reference/objects#teammemberedge
https://docs.github.com/en/enterprise-cloud@latest/graphql/reference/objects#teammemberedge
https://docs.github.com/en/enterprise-server@3.10/graphql/reference/objects#teammemberedge
https://docs.github.com/en/enterprise-server@3.9/graphql/reference/objects#teammemberedge
https://docs.github.com/en/enterprise-server@3.8/graphql/reference/objects#teammemberedge
https://docs.github.com/en/enterprise-server@3.7/graphql/reference/objects#teammemberedge
https://docs.github.com/en/enterprise-server@3.6/graphql/reference/objects#teammemberedge
https://docs.github.com/en/github-ae@latest/graphql/reference/objects#teammemberedge

### What changes are you suggesting?

the node field is missing in document even though it's present in the schema and it's standard for all such *edge articles. it needs to be displayed

**Comment by cmwilson21** [comment]
@scribbo Thanks for opening an issue! I noticed you had opened a PR for it as well, however these changes will likely need to be made internally. I'll get this issue triaged for review! ✨
