### ISSUE TITLE
Grammar mistake in "About authentication as a GitHub App installation" docs

### ISSUE THREAD

**Issue by lukemartin** [github/docs#27408]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation

### What part(s) of the article would you like to see updated?

In the GraphQL section, it reads:

> For GraphQL requests, you should test **you app to ensure that your app** has the required permissions for the GraphQL queries and mutations that you want to make.

**Comment by cmwilson21** [comment]
@lukemartin Thank you for opening an issue and linking it to your PR! ✨
