### ISSUE TITLE
Incorrect markup in the description of the `projects_v2` webhook

### ISSUE THREAD

**Issue by nikpivkin** [github/docs#27417]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#projects_v2

### What part(s) of the article would you like to see updated?

<img width="756" alt="image" src="https://github.com/github/docs/assets/100182843/67e94581-6710-44be-ab69-1609223e9c73">

**Comment by cmwilson21** [comment]
@nikpivkin Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

We appreciate you pointing out this markdown issue.
