### ISSUE TITLE
Incomplete/confusing bulleted list in Project tasklist docs

### ISSUE THREAD

**Issue by kevindamm** [github/docs#27419]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist

### What part(s) of the article would you like to see updated?

In the section about creating/editing tasklists with markdown, there is a bulleted list:

* A draft task. Draft tasks are text that can later be converted into issues.
* The full link to an issue or pull request or, if the issue or pull request is in the same repository as your tasklist, you can use the #ISSUE-NUMBER shorthand syntax. For example, https://github.com/octo-org/octo-repo/issues/45 or #45.
* If an issue or pull request is in the same repository

The second bullet has two examples and the third bullet is an incomplete phrase

**Comment by tttttir** [comment]
هذا هو الى على هون بداء التعليم

**Comment by tttttir** [comment]
لقد تم سرقتى

**Comment by cmwilson21** [comment]
@kevindamm Thank you for opening an issue and linking it to your PR! ✨
