### ISSUE TITLE
Repository Contents API Token Scope Requirement is Misleading

### ISSUE THREAD

**Issue by AdnaneKhan** [github/docs#27413]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#create-or-update-file-contents

### What part(s) of the article would you like to see updated?

The documentation for the repository contents API states that a token with the `workflow` scope is needed. This is misleading because a token with `workflow` scope is _only_ needed if you are making changes to files within `.github/workflows/`. This could lead to end-users generating over-provisioned tokens when they do not need them. A workflow scoped PAT has repo write access and can trivially access all repo/org shared secrets.

It would be good if the documentation specified that `workflow` scope is only needed if the use case requires changes to workflow files. If not, then a `repo` scoped token is sufficient.

**Comment by cmwilson21** [comment]
@AdnaneKhan Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
