### ISSUE TITLE
bug: documentation on saved searches may be out of date

### ISSUE THREAD

**Issue by schalkneethling** [github/docs#27444]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/github-code-search/using-github-code-search#creating-and-managing-saved-searches

### What part(s) of the article would you like to see updated?

Currently, step 4 (more on this a little later 😄) reads as follows:

> If you click again on the search bar, you can now see your saved search in the "Saved searches" section under the search bar. Clicking on a saved search entry will add the query to the search bar and filter the suggestions accordingly.
To edit a saved search, in the "Saved searches" section, click to the right of the saved search.
To delete a saved search, click to the right of the saved search.

This does not match the recently updated UI. When I first focus on the search field, the saved search is listed as a suggestion by default.

![Screenshot that shows the saved search as an autocomplete suggestion in the suggestions list.](https://github.com/github/docs/assets/10350960/14e0cd44-4962-4cf3-b1f9-480620619122)

When I type `saved:` the UI updates to only show my saved searches and surfaces the "Manage saved searches" option.

![Screenshot demonstrating the updated UI with an option to manage saved searches.](https://github.com/github/docs/assets/10350960/6a852ab2-36c5-48c0-83e6-efd7ea4cfc5c)

It does not show the edit or delete options as mentioned in the docs. To access these, users must select the option to manage their saved searches.

![Screenshot of the manage saved searches modal. This list the users saved searches, and for each entry, it shows options to edit or delete a saved search.](https://github.com/github/docs/assets/10350960/bf6e4065-1839-4674-ae0c-4b8272e8235c)

> Related: I opened this discussion because a saved search I have shows up under saved searches, but selecting the saved search triggers an error. https://github.com/orgs/community/discussions/63708

## Sidenote

Concerning step 4. Steps one to three are concerned with creating a saved search, and step four is concerned with managing an existing saved search. These feel like separate workflows and are not part of the same sequential steps. It will become clearer with the suggested updates above, so I recommend separating them into two separate ordered lists.

> NOTE: Please let me know if I should separate some of the above into separate issues. Thanks! I am also happy to open a pull request to address the documentation updates mentioned.

### Additional information

[maintainer edit]
Anyone can work on this by following the content plan [here](https://github.com/github/docs/issues/27444#issuecomment-1691696133)

**Comment by cmwilson21** [comment]
👋 Hey @schalkneethling! Thanks for opening an issue and reporting this change in the UI and the mention of the order of the steps ✨ 

I'll get this triaged for review ⚡

**Comment by benny-png** [comment]
Just use port-forwarding services like NGROK lol SUPER easy three line of shell commands https://ngrok.com/download
you can use this for reference https://youtu.be/AhiXVaWst24

**Comment by sophietheking** [comment]
@schalkneethling 👋 Thanks for opening this issue and contributing to our docs! 💖  It does look like that procedure it out of date. 👀  To fix this, you can open a PR that modifies [this file](https://github.com/github/docs/blob/main/content/search-github/github-code-search/using-github-code-search.md). If possible, I think it'd be good to keep this as one procedure. I would maybe suggest the following edit:  

```
## Creating and managing saved searches

1. In the top navigation of {% data variables.product.prodname_dotcom_the_website %}, click the search bar and type `saved:`.
1. Under the search bar, the "Saved queries" section should now appear. Click {% octicon "plus-circle" aria-hidden="true" %} **Manage saved searches**.
1. In the pop-up window, fill out the name you want for your query and the query that you want to save. Click **Create saved search**.
1. If you click again on the search bar, you can now see your saved search in the "Saved queries" section under the search bar. Clicking on a saved search entry will add the query to the search bar and filter the suggestions accordingly.
1. To edit or delete a saved search,  type `saved:` in the search bar, and click {% octicon "plus-circle" aria-hidden="true" %} **Manage saved searches**. In the pop-up window to the right of the saved search, click {% octicon "pencil" aria-label="The pencil icon" %}  to edit the search, or click {% octicon "trash" aria-label="The trash icon" %} to delete the search.
```

You (or anyone else) is welcome to open a PR with a fix.  🔨
