### ISSUE TITLE
REST API - Create an Organization Repository Ruleset - inconsistent/misleading instructions

### ISSUE THREAD

**Issue by Sam-Hecht-18** [github/docs#27492]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Create an Organization Repository Ruleset](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset)

Screenshot:

<img width="1237" alt="Screenshot 2023-08-15 at 5 56 01 PM" src="https://github.com/github/docs/assets/121143818/89b93d46-1c5e-4bc3-9e27-b0b94811cd02">

### What changes are you suggesting?

As can be seen in the screenshot, the documentation is inconsistent with regards to the `conditions` input. On the left hand side of the screenshot (the parameters) you can see that it suggests that both `repository_name_and_ref_name` and `repository_id_and_ref_id` are required objects (along with the `repository_name` object), while on the right hand side only the `ref_name` object is given inside of the `conditions` object.

These inconsistencies make it difficult to determine the correct way to perform a REST API query to [Create an Organization Repository Ruleset](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset), and I was not able to figure out the correct way to do so through trial and error. I often received the error: 

> {
  "message": "Invalid request.\n\nInvalid property /conditions: data matches no possible input. See `documentation_url`.",
  "documentation_url": "https://docs.github.com/rest/orgs/rules#create-an-organization-repository-ruleset"
}
which was unfortunately of little help.

The docs should be updated to be consistent between the parameters and the example and reflect the correct syntax to perform the [Create an Organization Repository Ruleset](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset) query.

### Additional information

My queries were all run through `cURL` using a bash script with a PAT who was an organization owner.

**Comment by cmwilson21** [comment]
@Sam-Hecht-18 Thanks for opening an issue and for providing such great context and screenshots. That really helps in the review process.

I'll get this triaged for review! :zap:

**Comment by Sam-Hecht-18** [comment]
Hi @cmwilson21! Thanks for helping to get this issue copied to an internal issue. Is there any way I can track the progress of my issue now that it has been made internal?

Thanks so much for your help!

**Comment by cmwilson21** [comment]
@Sam-Hecht-18 No problem! I wasn't entirely sure if the issue is with the description or in the schema, so I did have to transfer it internally for the team to check. I'll add a note requesting to update this issue with progress. Will try our best to!

Thanks again for submitting this ✨
