### ISSUE TITLE
Add 404 response to Create a Repository Dispatch docs

### ISSUE THREAD

**Issue by angelod1as** [github/docs#27534]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Create a repository dispatch event](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event)

### What part(s) of the article would you like to see updated?

The responses listed are:

<h3 class="mt-4 mb-3 pt-3 h4" id="create-a-repository-dispatch-event--status-codes"><a href="https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event--status-codes">HTTP response status codes for "Create a repository dispatch event"</a></h3>

Status code | Description
-- | --
204 | No Content
422 | Validation failed, or the endpoint has been spammed.

But calling the endpoint today, I got a `404`:

```
Response body

{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/repos/repos#create-a-repository-dispatch-event"
}
```

So, I'd love to see a proper explanation of _what_ is not found — I suppose the event I called was not found, but that's unclear.

**Comment by Axelwiest** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by Axelwiest** [comment]
Error 404 found at Lloyd's of London and Vodacom apps

**Comment by cmwilson21** [comment]
@angelod1as Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by angelod1as** [comment]
@cmwilson21 what's funny is that I found the error: the `User-Agent` was invalid. It missed a hyphen. E.g., `User-Agent: invalid name` instead of `User-Agent: valid-name`. So, the 404 error is even more cryptical.

**Comment by hubertlepicki** [comment]
For those who end up here searching for answers: this may as well mean that you have Fine-grained access token generated, with no "Read and write" access to repository's "Contents". I don't know why it is required to trigger dispatch, but it seems to be a requirement.

If the token exists, is valid, even has access to this repository but does not have write permission to Contents, it will return 404.

**Comment by dennisvang** [comment]
This should be reopened. 

The [docs] now mention the 404, they still do not provide any explanation whatsoever:

![Image](https://github.com/user-attachments/assets/0d23df76-9f76-4664-a4f5-99a09a08c681)

[docs]: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event--status-codes
