### ISSUE TITLE
REST API docs for "Download job logs for a workflow run" are incorrect

### ISSUE THREAD

**Issue by Sebastian-0** [github/docs#27558]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Download job logs for a workflow run](https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#download-job-logs-for-a-workflow-run)

### What part(s) of the article would you like to see updated?

The section on "Download job logs for a workflow run" says that a temporary link is generated and returned in the `Location` header together with status 302. All of this is incorrect and should be replaced.

The endpoint actually responds with 200 and returns the log in the response body. There is no link generated at all.

**Comment by cmwilson21** [comment]
@Sebastian-0 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by cdb** [comment]
Hi @Sebastian-0 - the documentation is actually correct. The endpoint does return a redirect to a time-limited URL. I wonder if you are using a client that is automatically following the redirect making it appear like it's a 200 response?

If you were to use Curl and pass in the `-I` flag then you'll see evidence of the redirect, similar to this:

```
❯ curl https://api.github.com/repos/<org>/<repo>/actions/jobs/<job-id>/logs -H "Authorization: Bearer <token>"  -I
HTTP/2 302
server: GitHub.com
...
location: https://<redirect-url-shown-here>
....<various other response headers>...
```

If you would rather have the redirect URL, you should investigate whether the http client you are using exposes a way to disable following redirects?

Hope that helps! Thanks for filing the issue.
