### ISSUE TITLE
Displaying a sponsor button in a repository

### ISSUE THREAD

**Issue by samsonmobisa** [github/docs#27594]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

### What part(s) of the article would you like to see updated?

sponsor button
More should be explained in details on how to add a FUNDING.yml sponsor button on each and every open source repositories.
This will provide a more clear procedure to new developers joining in the platform.
The only things well explained is adding of a sponsor button, it will be better if more will be told on adding of a sponsor button in all repositories. Also talking of FUNDING.yml file, less is described on it, how does one connect the FUNDING.yml with repositories. 

### Additional information

![Screenshot_20230821-022207](https://github.com/github/docs/assets/92422271/ece9071b-8452-4c3a-892e-e71e0fef4480)
![Screenshot_20230821-022107](https://github.com/github/docs/assets/92422271/135ec530-cdd3-4c81-9a83-e01619bde0c3)

**Comment by samsonmobisa** [comment]
How does one Displaying a sponsor button in all repository.
How does one use the FUNDING.yml to display sponsor button

**Comment by cmwilson21** [comment]
@samsonmobisa Thanks for opening an issue! I checked with the team and you can add the `funding.yml` file at the organization or user level, which will make the button appear by default on every repository. Check out more about our community default health files [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file). 👍 

You can also find out more about Funding files [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository). 

I'm going to go ahead and close this issue out. If you need more support, check out our [Sponsors community](https://github.com/orgs/community/discussions/categories/sponsors). 💛
