### ISSUE TITLE
The footer should be centered to improve the UI

### ISSUE THREAD

**Issue by NnajiChimuanya** [github/docs#27664]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

No article is particularly affected, This is to improve the UI

![gitbubOpen](https://github.com/github/docs/assets/79623263/3e146de8-232c-48be-98c2-fd5c61f1a30c)

### What changes are you suggesting?

To center the footer

**Comment by cmwilson21** [comment]
@NnajiChimuanya Thanks for opening an issue! However, after checking with the team, we are not going to perform any actions on this issue. I'm going to go ahead and close it now 💛 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
