### ISSUE TITLE
Docs on `fail-fast` doesn't indicate that it can be an expression

### ISSUE THREAD

**Issue by kenodegard** [github/docs#27840]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

### What part(s) of the article would you like to see updated?

`jobs.<job_id>.strategy.fail-fast` appears to accept expressions (not just booleans) per the [context availability docs](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability). It would be much appreciated if the `fail-fast` docs are further clarified to avoid confusion.

See examples in the wild: https://github.com/search?q=path%3A.github%2Fworkflows+%22fail-fast%3A+%24%7B%7B%22&type=code

### Additional information

[maintainer update]
Follow the content plan [here](https://github.com/github/docs/issues/27840#issuecomment-1721741209)

**Comment by skedwards88** [comment]
Thanks for opening this issue and for including examples to verify your statement! You or anyone else is welcome to open a PR to update the documentation around `fail-fast` (e.g. `content/actions/learn-github-actions/contexts.md` and `data/reusables/actions/jobs/section-using-a-build-matrix-for-your-jobs-failfast.md`).
