### ISSUE TITLE
Missing "Single file" section

### ISSUE THREAD

**Issue by flavioheleno** [github/docs#27855]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#single-file

### What part(s) of the article would you like to see updated?

The section for "Single file" repository permission is missing in the docs, but is being linked in the GitHub App settings page, under "Permissions & events".

**Comment by cmwilson21** [comment]
@flavioheleno Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for reporting this! It looks like this needs to be fixed in the GitHub UI instead of in the docs, so I'm going to close this issue and open an internal issue for the owning team.

**Comment by aph3rson** [comment]
Almost a year later, this issue still exists. The "Single File" section exists in the GitHub App permissions UI, and there's no matching documentation.

Is this something we should try perusing the REST API for more details on?

**Comment by nguyenalex836** [comment]
@aph3rson Thank you for the heads up! 💛 I'll try to rundown some input from the team on what the next best steps would be.

**Comment by nguyenalex836** [comment]
@aph3rson I've nudged the owning team regarding the issue that was opened internally. Having the owning team resolve this directly is the best path forward 💛

**Comment by joebowbeer** [comment]
I was just about to report this, but I see it was already reported a year ago.

While this is pending resolution in the UI, can someone provide a description of this permission here?

**Comment by aph3rson** [comment]
@skedwards88 @nguyenalex836 Given that this hasn't actually been resolved, could this issue at-least be reopened while we wait for the appropriate team to come own this?

**Comment by nguyenalex836** [comment]
@aph3rson Hello! 👋 As this issue currently lives in the GitHub Docs repo, keeping this issue open wouldn't contribute effectively toward getting this resolved. 

While we've nudged the owning team regarding this issue, you or anyone else is welcome to open a community discussion post in https://github.com/github/feedback/discussions 💛

**Comment by tnm** [comment]
Would very much love documentation anywhere about this feature. e.g., the path input field looks like it might be able to take directories, or even wildcards? 

The link: https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-single-file refers to an empty anchor tag.

**Comment by DCjanus** [comment]
I think this is still not fully solved.

`single_file` / `single_file_paths` are documented in URL-parameter docs, but there is still no clear permission/capability mapping in the main GitHub App permissions docs.

In practice, it’s unclear which REST/GraphQL write APIs are expected to work with **Single file** scope (for example, `createCommitOnBranch` can fail with `Resource not accessible by integration`).

Could docs add a small compatibility table for Single file scope:
- supported REST endpoints
- supported/unsupported GraphQL mutations
- recommended API path for updating exactly one file

That would make least-privilege app setup much easier.

**Comment by ShellXploit** [comment]
The issue is still valid.
> It looks like this needs to be fixed in the GitHub UI instead of in the docs
@skedwards88 @nguyenalex836 would it be possible to share the relevant doc content about "Single file" permission on this issue itself for everyone to go through instead of waiting on the UI to be fixed?
