### ISSUE TITLE
Moodle reference in Canvas section

### ISSUE THREAD

**Issue by sebacea** [github/docs#27856]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/connect-a-learning-management-system-course-to-a-classroom

### What part(s) of the article would you like to see updated?

[Linking a Canvas course with a classroom](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/connect-a-learning-management-system-course-to-a-classroom#linking-a-canvas-course-with-a-classroom)

**Comment by cmwilson21** [comment]
@sebacea Thank you for opening an issue and linking it to your PR! ✨
