### ISSUE TITLE
pull_request actionType=closed data type missing

### ISSUE THREAD

**Issue by Jasguerrero** [github/docs#27869]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=closed#pull_request

### What part(s) of the article would you like to see updated?

The field "pull_request" does not state the data type

![Screenshot from 2023-08-30 13-05-42](https://github.com/github/docs/assets/11179159/58e45230-0ffd-413f-9fa3-d3cd861d1eac)

**Comment by Shchaslivchik** [comment]
![image](https://github.com/github/docs/assets/140857263/3fe5ac2a-b7fd-4192-a0cb-77bb5e12327c)

**Comment by cmwilson21** [comment]
@Jasguerrero Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
