### ISSUE TITLE
Add `blockquote` to `Basic writing and formatting syntax`

### ISSUE THREAD

**Issue by jsoref** [github/docs#27902]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

### What changes are you suggesting?

1. Add `blockquote` to the article
2. Ensure that searching for `note+warning+blockquote+markdown` finds the article (and not on page 9/10).

### Additional information

In https://github.com/orgs/community/discussions/16925#discussioncomment-6876291, I wrote:

> there's [no sign of documentation for this feature](https://docs.github.com/en/search?query=note+warning+blockquote+markdown)

The feature announcement https://github.com/orgs/community/discussions/16925 is titled `[Markdown] An option to highlight a "Note" and "Warning" using blockquote`

It's reasonable to expect a search for `note+warning+blockquote+markdown` to turn it up. Indeed, 3/4 of those search terms are present on https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax -- only `blockquote` is missing.

**Comment by cmwilson21** [comment]
@jsoref Thanks for opening an issue! I'll get it triaged 👍

**Comment by felicitymay** [comment]
On reflection, I opened a PR because we already have a help-wanted issue for this section of the article and it would be good to avoid OS contributors have conflicts in their work.

- https://github.com/github/docs/pull/28140

**Comment by Technocv** [comment]
technocraftic
