### ISSUE TITLE
"Specifying recommended secrets in the dev container configuration": `secrets: {}` is not allowed property in `devcontainer.json`

### ISSUE THREAD

**Issue by tiffehr** [github/docs#27913]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/configuring-dev-containers/specifying-recommended-secrets-for-a-repository#specifying-recommended-secrets-in-the-dev-container-configuration

### What part(s) of the article would you like to see updated?

Specifically the subhead ["Specifying recommended secrets in the dev container configuration"](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/configuring-dev-containers/specifying-recommended-secrets-for-a-repository#specifying-recommended-secrets-in-the-dev-container-configuration) -- it shows adding a 
```js
"secrets": {
  "NAME_OF_SECRET_1": {
    "description": "This is the description of the secret.",
    "documentationUrl": "https://example.com/link/to/info"
  },
  "NAME_OF_SECRET_2": { }
}
```
property to an existing `devcontainer.json`.  But when you do that with an existing file in a Codespace, it throws a linter(?) error: `Property secrets is not allowed`.  Without that property, the "Recommended Secrets" extended panel cannot be seen when working with a Codespace for a repo, under the "new with options" item.   

Could be just a linter misconfiguration for a bit?  Or has this feature been dropped?

### Additional information

![Screenshot 2023-08-31 15 47 00](https://github.com/github/docs/assets/60173/06c033cc-7275-4a62-a8b0-d0432327476b)

**Comment by cmwilson21** [comment]
@tiffehr Thanks so much for opening an issue! We appreciate the details and screenshot!

I'll triage this for the team to take a look :eyes:

**Comment by hubwriter** [comment]
Ah, no, ignore the previous comment.

Editing the `devcontainer.json` in a codespace in VS Code I get the same thing. I'll raise a engineering issue for this.

This isn't a documentation issue, so I'll close this. Thanks again for bringing this to our attention.
