### ISSUE TITLE
weird bug: page scrolls up when you type in the search bar

### ISSUE THREAD

**Issue by dragoncoder047** [github/docs#27965]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All of them. It's a bug with the search bar.

### What changes are you suggesting?

Whenever I type any key in the search bar, the page scrolls up.

https://github.com/github/docs/assets/101021094/5f2616be-429d-488d-bed0-fbf5da930615

### Additional information

Browser: Chrome 114.0.5735.119 (Official Build) (64-bit)  on a chromebook.

**Comment by AyushSinghRawat-hub** [comment]
Assign to me

**Comment by AtulPatidar1709** [comment]
Hello 👋 @dragoncoder047 , I want to work on this issue, can you please assign it to me.

**Comment by dragoncoder047** [comment]
@AyushSinghRawat-hub @AtulPatidar1709 I don't work at GitHub, I can't do that.

**Comment by cmwilson21** [comment]
@dragoncoder047 Thanks for opening this issue! And for providing the video. 👍 

I'll get it triaged for review. ⚡

**Comment by cmwilson21** [comment]
👋 @dragoncoder047 I just spoke with the team and it is a known bug they are working. Since it's being worked on internally, I'm going to go ahead and close out this issue 💛 

Thanks again for reporting it! ✨
