### ISSUE TITLE
Superfluous newlines found in some code blocks

### ISSUE THREAD

**Issue by muzimuzhi** [github/docs#27989]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group

### What part(s) of the article would you like to see updated?

The `on.merge_group` example contains a superfluous trailing newline.
![image](https://github.com/github/docs/assets/6376638/c51a0eef-e313-4d1e-87ce-046f55083f73)

Compared to examples without trailing newline(s):
![image](https://github.com/github/docs/assets/6376638/2e9db1ad-7ec1-42aa-b431-437d955f3dc3)
![image](https://github.com/github/docs/assets/6376638/f0d26c7e-5abc-44a2-ae95-a7111a38ce89)

**Comment by cmwilson21** [comment]
@muzimuzhi Thank you for opening an issue and linking it to your PR! ✨
