### ISSUE TITLE
Misspelled Page [Deploying with GitHub Actions]

### ISSUE THREAD

**Issue by elvisdasilva** [github/docs#28007]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/pt/actions/deployment/about-deployments/deploying-with-github-actions

### What part(s) of the article would you like to see updated?

In the pt-br translation, below the title "Implantando com GitHub Actions" contains the texto "Aprenda a controlar imolantações com funcionalidades como ambientes e simultaneidade." I think the correct word should be "implantações".

### Additional information

![image](https://github.com/github/docs/assets/26262318/5be1e845-cda1-46c1-8c90-02c3a127c409)

**Comment by cmwilson21** [comment]
@elvisdasilva Thanks for reporting this! I'll open an internal ticket to request this fix, so I'm going to go ahead and close the issue now 💛
