### ISSUE TITLE
2-core codespace currently has 4 GB RAM (instead of 8 GB)

### ISSUE THREAD

**Issue by nathanweeks** [github/docs#28019]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/f2d5443613d0980cea4ad7dd763cf32a8358d964/content/codespaces/overview.md?plain=1#L24

### What part(s) of the article would you like to see updated?

> ...from 2 cores, 8 GB RAM...

should be

>...from 2 cores, 4 GB RAM...

**Comment by cmwilson21** [comment]
@nathanweeks Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by nathanweeks** [comment]
Closing; as of today the 2-core codespace now has the 8 GB RAM advertised in the docs.
