### ISSUE TITLE
Github App docs should refer to official auth action

### ISSUE THREAD

**Issue by avx-rvandegrift** [github/docs#28078]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow#authenticating-with-a-github-app

### What part(s) of the article would you like to see updated?

this article refers to a third-party action, `tibdex/github-app-token` - this seems dangerous since there's an official action for handling Gihub App authentication.  I tried to evaluate the third party action for security, but it uses obfuscated javascript.

Please remove all mentions of this action and replace it with the official one https://github.com/marketplace/actions/create-github-app-token

**Comment by cmwilson21** [comment]
@avx-rvandegrift Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thank you for pointing out that we should use this newer, GitHub-owned action! I've opened a PR internally to update the docs.

**Comment by enderwert** [comment]
Dne pá 8. 9. 2023 18:50 uživatel Courtney Wilson ***@***.***>
napsal:
