### ISSUE TITLE
Document format error in i18n

### ISSUE THREAD

**Issue by SnowballXueQiu** [github/docs#28110]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- In page [Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), I found that when I use Chinese or any of the languages listed below, there is a Markdown formatting error in step 2 of part [Adding your SSH key to the ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent).
![image](https://github.com/github/docs/assets/97330394/9c73fdf8-2d6c-4310-ba54-7d119d559774)
![image](https://github.com/github/docs/assets/97330394/bf731ecc-bac0-44d8-b370-857d3b5b748e)
![image](https://github.com/github/docs/assets/97330394/10d68a28-3de2-4b08-832c-cdaeac59ca16)
![image](https://github.com/github/docs/assets/97330394/e5d6d5f2-1331-47bd-a47d-f3cc933dd542)
![image](https://github.com/github/docs/assets/97330394/0f99ab98-50a0-48a4-bce3-a9a83ac91838)
![image](https://github.com/github/docs/assets/97330394/398e72c9-7d8a-4dc7-ae2b-5d509fd3a8b9)
- Errors List: 简体中文, Español, Português do Brasil, 日本語, Français, Deutsch
- I suspect there may be similar issues on other pages, so please check **carefully**.

### What changes are you suggesting?

- Correct Format:
![image](https://github.com/github/docs/assets/97330394/3517b5ea-f558-4fe6-89a0-4b919cf4b2c7)

### Additional information

Thanks

**Comment by cmwilson21** [comment]
@SnowballXueQiu Thank you for reporting this! Our translations are handled via an internal process. I'm going to go ahead and close this issue and open a ticket 👍 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
