### ISSUE TITLE
GraphiQL API Explorer broken due to Content-Security-Policy

### ISSUE THREAD

**Issue by RDIL** [github/docs#2814]
### What is the current behavior?

GraphQL explorer (GraphiQL instance) located at https://docs.github.com/en/free-pro-team@latest/graphql/overview/explorer doesn't work for me.  Using latest stable firefox build, it seems the CSP blocks the requests, rendering it nonfunctional.

![graphiql-errors-console](https://user-images.githubusercontent.com/34555510/104331840-89a86a00-54bd-11eb-9c4d-efaaaf6112d6.PNG)

### What changes are you suggesting?

Fix the CSP!

### Additional information

I am signed in to the explorer.

**Comment by chiedo** [comment]
Thanks for reporting this! @sarahs can you take a look? 🙏🏿

**Comment by chiedo** [comment]
@RDIL this is a known issue and a fix is underway. We'll report back when something is ready!

**Comment by chiedo** [comment]
@RDIL are you still experiencing the issue now?

**Comment by RDIL** [comment]
I'll give it a shot.

**Comment by RDIL** [comment]
It still isn't working.

**Comment by chiedo** [comment]
🤔  we'll report back when we figure out the cause.

**Comment by chiedo** [comment]
@RDIL sadly we're not able to reproduce the issue. Could you do us a favor and try clearing your cache and trying again? If you still have an issue, we'll have to keep looking and get back to you.

**Comment by adonisj910** [comment]
##-- Security policy update
