### ISSUE TITLE
Invalid YAML example

### ISSUE THREAD

**Issue by priyanuj-gogoi** [github/docs#28197]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Syntax for GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

### What part(s) of the article would you like to see updated?

I'd like to see an updated YAML example in [About GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema) (Example \#1)

The reason why it should be changed is that, the current YAML example is invalid. It shows this error:

```
Nested mappings are not allowed in compact mappings at line 5, column 18
```

The expected outcome is to contain a valid YAML example.

**Comment by cmwilson21** [comment]
@priyanuj-gogoi Thank you for opening an issue and linking it to your PR! ✨
