### ISSUE TITLE
Grzejuwow

### ISSUE THREAD

**Issue by palejana** [github/docs#2820]
- [x]

**Comment by palejana** [comment]
[](url)

**Comment by palejana** [comment]
[
](url)

**Comment by hashem213** [comment]
![60433638_833770463649413_6813128693481734144_n](https://user-images.githubusercontent.com/76513427/104407739-6213d900-5573-11eb-9bbc-d403474fa24e.jpg)

**Comment by hashem213** [comment]
[Uploading ‏‏dana3&4&7 - نسخة (2).xlsx…]()
