### ISSUE TITLE
update `gh clone` command for `Cloning a repository`

### ISSUE THREAD

**Issue by brignano** [github/docs#28236]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Cloning a repository](https://docs.github.com/en/github-cli/github-cli/quickstart#cloning-a-repository)

<img width="693" alt="image" src="https://github.com/github/docs/assets/9291621/1bfb37f0-5c24-4668-9342-b0144a6323bb">

### What part(s) of the article would you like to see updated?

`gh clone` should be `gh repo clone`

### Additional information

I will create a pull request with this change.

**Comment by cmwilson21** [comment]
@brignano Thank you for opening an issue and linking it to your PR! ✨
