### ISSUE TITLE
Code block malformed (Translations?)

### ISSUE THREAD

**Issue by opusdeits** [github/docs#28243]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/es/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux#adding-your-ssh-key-to-the-ssh-agent

### What part(s) of the article would you like to see updated?

https://docs.github.com/es/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux#adding-your-ssh-key-to-the-ssh-agent

The subsection [Agregar tu clave SSH al ssh-agent](https://docs.github.com/es/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent), the step 2 has the code block malformed, I guess there is a problem with single back quotes but I'm not sure. English version is ok. 

![image](https://github.com/github/docs/assets/9250381/8d07e7dc-486a-4677-b417-e91f54c66e8a)

### Additional information

There are three OS tabs, it is wrong in Windows and Linux tabs.

Thanks!

**Comment by cmwilson21** [comment]
@opusdeits Thanks for opening an issue and letting us know about this error. I'm going to open an internal ticket to address this, so will go ahead and close this issue. 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:
