### ISSUE TITLE
Improve table for HTTPs examples of assets in HTML files

### ISSUE THREAD

**Issue by Andre601** [github/docs#2825]
### What article on docs.github.com is affected?
This doesn't generally has to do with a single article, but a most prominent example would be [Securing your GitHub Pages site with HTTPS](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https)

### What part(s) of the article would you like to see updated?
Please refer to #2686 for the full context about what the actual problems are.

Essentially does the table under [Examples of assets referenced in an HTML file](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https#examples-of-assets-referenced-in-an-html-file) look horrible due to a combination of long text and inline code.

Unfortunately do I not know of a possible and better-looking alternative for this situation so input on this is requested.

**Comment by janiceilene** [comment]
Thanks so much for opening a discussion and then an issue @Andre601! I've triaged this for the team to take a look 👀

**Comment by fnise-urt** [comment]
Currently user and organization sites require enforced HTTPS.

**Comment by fnise-urt** [comment]
@janiceilene

Please unmark my above comment.

The page in question refers to a no longer available option to enforce HTTPS.

**Comment by janiceilene** [comment]
We're having conversations about how to better present this type of information internally right now! We'll keep this one in mind for future improvements 💛
