### ISSUE TITLE
Erroneous example Ruby code snippet

### ISSUE THREAD

**Issue by ameuret** [github/docs#28258]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/webhooks/using-webhooks/securing-your-webhooks#ruby-example

### What changes are you suggesting?

The first argument of the call to `OpenSSL::HMAC.hexdigest` should be just a string describing the requested algorithm. Diff is pretty self-explanatory. 😁

**Comment by cmwilson21** [comment]
@ameuret Thanks for opening an issue and submitting a PR! ✨

**Comment by skedwards88** [comment]
Closing based on https://github.com/github/docs/pull/28259#issuecomment-1724112534
