### ISSUE TITLE
May251989

### ISSUE THREAD

**Issue by may251989** [github/docs#28286]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Methi Yaowala นายเมธี เยาวลา

### What part(s) of the article would you like to see updated?

141020080533

### Additional information

[0981241725[](url)](url)

**Comment by 0932167501** [comment]
https://www.facebook.com/nagham.khaled.148?mibextid=LQQJ4d
