### ISSUE TITLE
Add PowerShell Examples to Actions

### ISSUE THREAD

**Issue by potatoqualitee** [github/docs#283]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/quickstart

#### Actions Quickstart
As a PowerShell developer, I find GitHub Actions wildly useful and very straightforward. PowerShell is built into each of the runner images, and is supported out of the box.  PowerShell has a strong CI/CD community and it makes a ton of sense to include it in the quickstart.

https://github.com/github/docs/pull/284

#### Actions Cache Example
Add PowerShell to the examples.md and include all appropriate directories for each OS.

https://github.com/actions/cache/pull/431

#### Actions Workflow Examples

I understand that the repository states that GitHub is not adding new workflows at this time, but I believe PowerShell was overlooked in the original documentation, which is a common problem in our community. Fortunately, PowerShell was not looked over in the runners 🤩

GitHub documentation just went public, I am updating GitHub Action Documentation with a PowerShell example. This workflow will help me create more complete documentation for the community. GitHub has provided runners with PowerShell's testing framework, Pester, built-in and accepting this pull request will help complete the documentation for my proposed PR for adding sample.

https://github.com/actions/starter-workflows/pull/661

**Comment by janiceilene** [comment]
Thanks for the issue and accompanying PR 😍 I'll get these over to the @github/docs-content-ecosystem team for review!

**Comment by runleonarun** [comment]
:wave: @potatoqualitee It looks like the docs issue was fixed in 
https://github.com/github/docs/pull/284 So I'm going to close this issue out. Thank you for helping to improve our docs!
