### ISSUE TITLE
Clarify how to use a negated expression in an if statement

### ISSUE THREAD

**Issue by hubwriter** [github/docs#28308]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions

### What part(s) of the article would you like to see updated?

The documentation for `if` statements needs checked.

We should clarify how to write an if statement with a negated expression.

### Additional information

I've opened this issue as a result of @fransf-wtax's comment on this already-closed issue:

https://github.com/github/docs/issues/3001#issuecomment-1702464558

> This seems to have regressed as data/reusables/actions/expression-syntax-if.md no longer contains the changes made for this issue. To make matters worse, the current text seems to discourage surrounding expressions in ${{ and }} since they are then supposedly treated as a string; but no solution is given for the scenario described in this ticket where the expression starts with !.

See my comment on that issue that gives the context of what we currently have in the docs.

### Content design plan

- [ ] In the "About expressions" section of the Expressions article (https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions):

  - [ ] Remove `{% data reusables.actions.expression-syntax-if %}` - see the Markdown file [here](https://github.com/github/docs/blob/main/content/actions/learn-github-actions/expressions.md?plain=1#L26C1-L26C50).

  - [ ] Move the "For more information..." from that line 👆 into a note box:

    ```
    {% note %}

    **Note**: The exception to this rule is when you are using expressions in an `if` clause, where, optionally, you can usually omit {% raw %}`${{`{% endraw %} and {% raw %}`}}`{% endraw %}. For more information about `if` conditionals, see "[AUTOTITLE](/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif)."

    {% endnote %}
    ```

  - [ ] Remove the `if` example [here](https://github.com/github/docs/blob/main/content/actions/learn-github-actions/expressions.md?plain=1#L30-L36).

- [ ] In the `expression-syntax-if` reusable https://github.com/github/docs/blob/main/data/reusables/actions/expression-syntax-if.md?plain=1:

  - [ ] In the first paragraph, change "you may omit" to "you can, optionally, omit".

  - [ ] In the first paragraph, change "However, this rule does not" to "However, this exception does not".

  - [ ] In the second paragraph, change "You must use the" to "You must always use the".

  - [ ] At the end of the second paragraph, add: "For example:" followed by:

    ````
    [blank line]
    ```yaml
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    ```
    [blank line]
    ````

  - [ ] Delete the third paragraph, beginning "Using the..."

**Comment by fransf-wtax** [comment]
Thank you for opening this, @hubwriter ! Let me know if I can help in any way.

**Comment by hubwriter** [comment]
I'm seeking SME input on what we need to change here in the light of recent changes to the article.

**Comment by hubwriter** [comment]
We made some changes to the text around the use of `${{ }}` in an if clause, which I think substantially clarifies this. The original text added about alway having to use `${{ }}` if you used an expression was incorrect, hence that was removed.

However, I think there a little more we could do here.

After the sentence: "You must use the `${{ }}` expression syntax or escape with `''`, `""`, or `()` when the expression starts with `!`, since `!` is reserved notation in YAML format."

I think it would be useful to add this as an example of negating an expression:
```
if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
```

I also think we still need some clarification around the statement: 

> Using the `${{ }}` expression syntax turns the contents into a string, and strings are truthy. For example, `if: true && ${{ false }}` will evaluate to true.

This seems to suggest that everything within  ${{ and }}  in an if clause is always evaluated as true, which is clearly not the case, or it would render if clauses useless.

I'll get some clarity around that and comment here when I do.

**Comment by hubwriter** [comment]
Some more details about this. The following is overly complex for the docs, but provides useful background:

> When the entire value is enclosed with `${{ }}`, then the runtime value is the result of the expression. The result may be any supported type: null, boolean, number, string, array, or dictionary
> 
> When `${{ }}` is embedded within a string, then the runtime value is always a string. The value `true && ${{ false }}` is syntax sugar for `${{ format('true && {0}', false) }}`
> 
> Some additional nuance here since we're dealing with `if`, which is special in multiple ways: 
> 
> - We allow the omission of `${{ }}` only for `if`. The rationale for this is that what follows `if` is always an expression. Some examples:
>   - `if: true` is equivalent to `if: ${{ true }}`
>   - `if: true && false` is equivalent to `if: ${{ true && false }}`
>   - `if: true && ${{ false }}` is equivalent to `if: ${{ format('true && {0}', false) }}`
> 
> - `if` is the only place where we coerce any non-boolean value to a boolean. Again, this feels like a mistake to be inconsistent here. Everywhere else within a workflow, we only coerce primitives to strings.

**Comment by hubwriter** [comment]
Some more details about this. The following is overly complex for the docs, but provides useful background:

> When the entire value is enclosed with `${{ }}`, then the runtime value is the result of the expression. The result may be any supported type: null, boolean, number, string, array, or dictionary
> 
> When `${{ }}` is embedded within a string, then the runtime value is always a string. The value `true && ${{ false }}` is syntax sugar for `${{ format('true && {0}', false) }}`
> 
> Some additional nuance here since we're dealing with `if`, which is special in multiple ways: 
> 
> - We allow the omission of `${{ }}` only for `if`. The rationale for this is that what follows `if` is always an expression. Some examples:
>   - `if: true` is equivalent to `if: ${{ true }}`
>   - `if: true && false` is equivalent to `if: ${{ true && false }}`
>   - `if: true && ${{ false }}` is equivalent to `if: ${{ format('true && {0}', false) }}`
> 
> - `if` is the only place where we coerce any non-boolean value to a boolean.

**Comment by hubwriter** [comment]
OK, I've had more expert help on this. I think we can clarify things and avoid overcomplicating matters by trying to over-explain. Here's what I propose doing, if someone from the community would care to pick this up and make these changes in a PR. (I'll mark this issue `help-wanted`.)

### Content design plan

- [ ] In the "About expressions" section of the Expressions article (https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions):

  - [ ] Remove `{% data reusables.actions.expression-syntax-if %}` - see the Markdown file [here](https://github.com/github/docs/blob/main/content/actions/learn-github-actions/expressions.md?plain=1#L26C1-L26C50).

  - [ ] Move the "For more information..." from that line 👆 into a note box:

    ```
    {% note %}

    **Note**: The exception to this rule is when you are using expressions in an `if` clause, where, optionally, you can usually omit {% raw %}`${{`{% endraw %} and {% raw %}`}}`{% endraw %}. For more information about `if` conditionals, see "[AUTOTITLE](/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif)."

    {% endnote %}
    ```

  - [ ] Remove the `if` example [here](https://github.com/github/docs/blob/main/content/actions/learn-github-actions/expressions.md?plain=1#L30-L36).



- [ ] In the `expression-syntax-if` reusable https://github.com/github/docs/blob/main/data/reusables/actions/expression-syntax-if.md?plain=1:

  - [ ] In the first paragraph, change "you may omit" to "you can, optionally, omit".

  - [ ] In the first paragraph, change "However, this rule does not" to "However, this exception does not".

  - [ ] In the second paragraph, change "You must use the" to "You must always use the".

  - [ ] At the end of the second paragraph, add: "For example:" followed by:

    ````
    [blank line]
    ```yaml
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    ```
    [blank line]
    ````

  - [ ] Delete the third paragraph, beginning "Using the..."

**Comment by albbus-stack** [comment]
@hubwriter In the current PR the last code block fails the `content-linter` with: 

```bash
Error name:    "ParseError"
Error message: "unexpected token at \"! startsWith(...\", line:6, col:6"
```
