### ISSUE TITLE
Code scanning: Clarify the descriptions of some SARIF fields

### ISSUE THREAD

**Issue by felicitymay** [github/docs#28305]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[SARIF support for code scanning - GitHub Docs](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#reportingdescriptor-object)

### What part(s) of the article would you like to see updated?

Update the descriptions for:
- `properties.security-severity`
- `defaultConfiguration.level`

### Additional information

An open source contributor raised an issue because the information about the behavior of these fields was unclear. This caused them problems creating an action to generate SARIF output.

- https://github.com/github/docs/issues/21221

Since the discussion in the original issue resulted in changes that can be made by and OS contibutor and some that are better suited to an internal update, I've opened this issue.

## Changes required to fix this issue

In the [reportingDescriptor object](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#reportingdescriptor-object) section, clarify the descriptions for the following two fields:

1. Update the description for `properties.security-severity` to include:
    > (Recommended only for security rules) If you include a value for this field, results for the rule are treated as a security results.

2. Update the description for `defaultConfiguration.level` to include the valid values of: `note`, `warning`, `error` and be clear that you can set an alert to override this default level for the rule by setting the `level` attribute in the `result` object.

**Comment by jsoref** [comment]
For (1), I wouldn't end the sentence with "query". To an end user it's a report. That many of them will be generated by CodeQL queries is an implementation detail.

**Comment by felicitymay** [comment]
Great point. Updated accordingly.

**Comment by npiyush97** [comment]
@felicitymay 

1)  
![Screenshot from 2023-09-21 16-45-09](https://github.com/github/docs/assets/43876655/c2d5579c-c425-4092-9ea3-e2fa744cbfc3)


2)
 ![Screenshot from 2023-09-21 16-45-09](https://github.com/github/docs/assets/43876655/4b59749a-8537-45b3-9e4d-568755ceae1e)

**Comment by npiyush97** [comment]
@felicitymay 
1)
![Screenshot from 2023-09-21 16-45-35](https://github.com/github/docs/assets/43876655/bdddb15f-a2b5-457e-b1d1-a161cabf3092)
2)
![Screenshot from 2023-09-21 16-49-02](https://github.com/github/docs/assets/43876655/4cc7b766-7202-4bdd-a111-7d721e698aca)
