### ISSUE TITLE
API endpoints including search/repositories have undefined values for items[].license.spdx_id

### ISSUE THREAD

**Issue by fulldecent** [github/docs#28331]
### Maintainer's note

To open a PR against this issue, please update the table [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type) to match the casing on https://spdx.org/licenses/. 

See fuller context in https://github.com/github/docs/issues/28331#issuecomment-1736422147.

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

GitHub's known licenses are defined at:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

The identifiers are all lower case.

However the value returned by in the repository object with license.spdx_id is not matching this formatting.

### What changes are you suggesting?

1. Document the returned format (i.e. the actual values and capitalization returned)
2. Change the output to match the existing specified `spdx_id`s

**Comment by skedwards88** [comment]
@fulldecent can you tell us more about the changes you want to make to the docs? I'm not sure I am understanding fully. It looks like the `gh api "/search/repositories?q=License:MIT"` and `gh api "/search/repositories?q=License:mit"` return the same output regardless of the license capitalization, and it looks like `spdx_id` has a value in the results.

**Comment by fulldecent** [comment]
Thank you. I'm just noting about the repository object that is returned. 

That returned object includes a key for spdx_ids. And the values are not lowercase. 

My understanding from the docs is that spdx_ids are lowercase.

So when I was parsing them I though the docs are wrong and that is in fact a "SPDX name" or something. So I started looking for a "SPDX name" to spdx_id mapping.

But actually there is no such mapping documented. It is just that the API end point spits out SPDX ids with "random" casing. 

So the improvement could be in the API itself to make the spdx_id come out in the expected format (lowercase). Or the page linked above could add a column to the table to show the alternate not-lower-case representation.

**Comment by XoL1507** [comment]
im sorry, really i try myself how to level myself to all of you. i try to learn what you operate and also my english i am trying to right a correct word. please  advise  me when i have mistake or wrong sentence.

**Comment by skedwards88** [comment]
Thanks for clarifying! I think we should probably update the table [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type) to match the casing on https://spdx.org/licenses/. It looks like that is the casing that our API returns. (e.g.  `gh api "/search/repositories?q=License:apache-2.0"` returns objects with `"spdx_id": "Apache-2.0"`, which matches the mixed casing of https://spdx.org/licenses/.)

You or anyone else is welcome to open a PR with this change.

**Comment by fulldecent** [comment]
Thank you @skedwards88, PR sent at https://github.com/github/docs/pull/28592
