### ISSUE TITLE
Update "getting started" articles for code security to use monospace font for file/directory names consistently

### ISSUE THREAD

**Issue by felicitymay** [github/docs#28393]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Historically, our style guide recommended using italic font to format file names and directory names in our documentation. Our current guidelines recommend using monospace font and it would be good to update more articles to follow the current guidelines. For more information, see: "[File names and directory names](https://docs.github.com/en/contributing/writing-for-github-docs/style-guide#file-names-and-directory-names)"

### What part(s) of the article would you like to see updated?

Files to review and check for file names and directory names that should be reformatted:

- [ ] [GitHub security features](https://docs.github.com/en/code-security/getting-started/github-security-features)
- [ ] [Securing your repository](https://docs.github.com/en/code-security/getting-started/securing-your-repository)
- [ ] [Securing your organization](https://docs.github.com/en/code-security/getting-started/securing-your-organization)
- [ ] [Adding a security policy to your repository](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)
- [ ] [Auditing security alerts](https://docs.github.com/en/code-security/getting-started/auditing-security-alerts)
- [ ] [Best practices for preventing data leaks in your organization](https://docs.github.com/en/code-security/getting-started/best-practices-for-preventing-data-leaks-in-your-organization)

**Comment by ATREAY** [comment]
hey @felicitymay, if this issue is still open can I work on it?

**Comment by Jegan-Kunniya** [comment]
@ATREAY, @cmwilson21 - I am already on it and will be submitting a PR in some time. Please let me know if you are all in the same league as me. Thank you
