### ISSUE TITLE
Clarify how Gravatar profile pictures work on GitHub and how to update them

### ISSUE THREAD

**Issue by meowius** [github/docs#28553]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- "[Personalizing your profile](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile)"

#### Content plan

Add a short final paragraph to the intro section, "Changing your profile picture."

- Tell readers that if they have a Gravatar image associated with the email they use for GitHub, it will be shown as their GitHub profile picture by default (rather than an identicon).
- Explain that to change their GitHub profile picture drawn from Gravatar, they can either update their Gravatar account, or they can upload a new image to GitHub, which will override the Gravatar image.

#### Problem to solve

Some people see their Gravatar image on GitHub and don't know where the image is coming from or how to change it. In some cases, they may have forgotten that they have an image associated with their Gravatar account.

GitHub users have expressed some confusion in the discussion posts below:

- [Where is my profile picture taken from? · community · Discussion #32845](https://github.com/orgs/community/discussions/32845)
- [How can I use Gravatar as my profile picture? · community · Discussion #38110](https://github.com/orgs/community/discussions/38110)

#### Who this affects

People who have an image associated with their Gravatar account and are confused about why this image is showing up on GitHub, and don't know how to change it.

#### How Gravatar images work on GitHub

- If you have a Gravatar image, it will automatically show up as your GitHub profile picture. 
- To change a GitHub profile picture that's drawn from Gravatar, users can either update their Gravatar account to have a new image, _or_ they can upload a new image to GitHub, which will override the Gravatar image.

**Comment by CBID2** [comment]
Hi there! :) Can I create a pull request on this? I see that there’s a `help wanted` and `needs triage` label on this issue, so I want to be sure that PRs can be created for it.

**Comment by cmdaltctr** [comment]
I uploaded the new image, it does take a while (20mins or so) for it to be updated across the github profile. So your uploaded image will overide the gravatar image.

**Comment by nithin-mk** [comment]
I think the docs need a little more clarity when there are multiple email addresses attached to the GitHub account. In that case, contrary to expectation, GitHub does not use the primary email address to fetch the Gravatar; instead it uses the first listed email address. Probably because of this, I still cannot see the Gravatar of my primary email address on my GitHub profile. 😓

Reference:
1. https://webapps.stackexchange.com/a/28160/372743
