### ISSUE TITLE
Document how to set an organization profile picture using Gravatar

### ISSUE THREAD

**Issue by meowius** [github/docs#28557]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

"[Customizing your organization's profile](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile)"

### What part(s) of the article would you like to see updated?

There are two ways to set an organization profile picture:

- Upload an image.
- Enter an email address associated with a Gravatar, in the field labeled "Gravatar email (private)." GitHub will use the Gravatar image associated with that email. This is currently not documented, and the purpose of this field isn't self-explanatory.

### Content plan

1. At the end of the article, add a new h2 heading: `## Changing your organization's profile picture`
2. In this section, add an h3 subsection: `### Uploading an image`, containing the following content.

   ```
   {% data reusables.profile.access_org %}
   {% data reusables.profile.org_settings %}
   1. Under your profile picture, click **Upload new picture**, then select an image.
   ```
3. Add another h3 subsection `### Using a Gravatar image`, containing the following content.

   ```
   {% data reusables.profile.access_org %}
   {% data reusables.profile.org_settings %}
   1. In the "Gravatar email (Private)" field, enter the email address associated with your Gravatar image.
   1. Click **Update profile**.
   ```

### Related issue

https://github.com/github/docs/issues/28553

### Additional information

The screenshot below is for reference, but does not need to be included in the article:

![Screenshot of an organization settings screen in GitHub. A form field labeled "Gravatar email (private)" is highlighted, with the rest of the screen in shadow.](https://github.com/github/docs/assets/10839362/1fc165e4-07fe-403a-9e69-6cef3fd33e47)

### Who does this affect?

Organization owners

### What is the impact to users?

Organization owners might be confused what this field is or how to use it, especially if they are not familiar with Gravatar. This question recently generated customer confusion with Support.

**Comment by 2481842N** [comment]
کمک

**Comment by 2481842N** [comment]
Tajdate ```
- `~~@2481842N <!-- Error while uploading 1695031619722.jpg --><!-- Error while uploading adjoe -->~~`
````

**Comment by 2481842N** [comment]
Taj~~[]()@2481842N **__**~~

**Comment by pratiksardar** [comment]
Hi, Can you please assign me this task. I would like to work on this.

**Comment by CBID2** [comment]
> @pratiksardar Thanks for your interest in improving the docs!
> 
> We don't assign issues, so you, or anyone else, are free to submit a PR with this fix! 💖

Made the PR @cmwilson21! :) It's #28870! :)

**Comment by isaacmbrown** [comment]
Note: I've updated the OP because the original article referenced was about changing a _team's_ image, not an organization's. cc @CBID2 if you'd like to take another crack at the PR 🙂

**Comment by CBID2** [comment]
> Customizing your organization's profile

On it

**Comment by CBID2** [comment]
Made the changes @isaacmbrown! :)
