### ISSUE TITLE
Docs should mention `gpg.ssh.allowedSignersFile`

### ISSUE THREAD

**Issue by jsoref** [github/docs#28577]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-ssh-key

should talk about `allowedSignersFile` otherwise, `git show --show-signature HEAD` will show:

```
error: gpg.ssh.allowedSignersFile needs to be configured and exist for ssh signature verification
commit d40f005f2393dce9a535d6929dcc360f84eb6935 (HEAD)
No signature
Author: Josh Soref <2119212+jsoref@users.noreply.github.com>
Date:   Thu Sep 28 13:47:41 2023 -0400

    spelling: can
    
    Signed-off-by: Josh Soref <2119212+jsoref@users.noreply.github.com>
```

(Which is itself a lie, but that's a ticket for another repository.)

### Additional information

https://docs.gitlab.com/ee/user/project/repository/signed_commits/ssh.html#verify-commits-locally talks about setting this up (as do other places) -- the specific file location for the thing isn't consistent, I don't have a preference but didn't use this suggestion.

**Comment by isaacmbrown** [comment]
Hi @jsoref, thanks for the issue. The `allowedSignersFile` is only a requirement for verifying a commit's signature locally, right?

This section of the docs is really about getting commits verified on github.com. As far as I can tell, we don't mention the `git show --show-signature` command or anything about verifying commits locally. I think we should be wary about including more info than people need to get started, and try to keep this section focused on GitHub. I'll close this issue, but let me know if you have more context to provide. 🙂

**Comment by jsoref** [comment]
Shrug. It seems weird to tell people to half configure a feature such that if they try to locally validate their product, they'll get an error.

**Comment by ChristopherA** [comment]
There are a number of problematic (or at least half-implemented)  issues with GitHub's implementation of SSH signing. I have submitted a support incident about these problems with no response. I don't see a place to post these issues publicly in a repo.

See https://github.com/dolmen/github-keygen/issues/54#issuecomment-1875907350 for some of them.

**Comment by nguyenalex836** [comment]
Hi @ChristopherA 👋 Would you be able to provide a link or reference number to the support incident you submitted? I can assist with routing to ensure it gets in front of the right audience.

**Comment by ChristopherA** [comment]
Thanks @nguyenalex836, the ticket is at https://support.github.com/ticket/personal/0/2398911, which they archived without a response. 

To recap, NIST, FIDO2, international standards, etc., recommend keeping auth keys & signing keys separate, but the practice of making the auth keys available via username.keys, and signing keys only via API results in bad practices (as you can't verify that username signed something unless you know their key, so devs have been adding their signing key into their auth keys list). GitHub does at least let you store both separately.

There are four possible solutions to this:

* username.keys shows auth keys, and maybe username.sign shows signingkeys (easiest, doesn't break people already using username.keys
* usename.keys shows both kinds of keys in a name json array if there are both, otherwise just shows the auth keys like it does now. (breaks some uses of username.keys that don't expect array.
* Stop putting auth keys in username.keys, only put signing keys. (breaks some current uses of username.keys)
* Deprecate username (as auth keys probably should not be shared) and do username.sign instead.

**Comment by nguyenalex836** [comment]
Thank you, @ChristopherA! I'm working on following up with our team on that ticket now 👍 Will update you once I have more info.

**Comment by nguyenalex836** [comment]
Hi @ChristopherA! Our team informed me they responded to your ticket - would you be able to check that ticket again to see if there's a response?

**Comment by ChristopherA** [comment]
You are correct, I misunderstood their response. I thought the URL they gave required authentication first, but apparently it does not require it.

So testing on my account:

https://api.github.com/users/ChristopherA/ssh_signing_keys

Does return my correct signing key(s) in a JSON array:

```json
[
  {
    "id": 184891,
    "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINTazxjqxsdh3Sv/7fxSTgr3qlCVByYoGDHHe428Fubp",
    "title": "eurynome.local/sign_id_25519_christophera@github.com",
    "created_at": "2023-10-26T06:28:34.882Z"
  }
]
```

Still remaining is to document this, talk about best practices, and correct those places in docs about under name.keys that they are not signing keys.

**Comment by nguyenalex836** [comment]
@ChristopherA Thank you for checking the ticket again! I don't have visibility on support tickets, so I appreciate you verifying.

With respect to what you mentioned regarding testing on your account, talking about best practices, documenting, etc. - were you able to share this with the support team as well? Their guidance on these topics would be greatly beneficial ✨ 

Regarding anything related to GitHub Docs, you are welcome to raise a [new issue](https://github.com/github/docs/issues/new/choose) to this repo. Raising a new, separate issue for this specific topic will ensure the content you are discussing is addressed efficiently 💛

**Comment by bric3** [comment]
Fore reference this issue also happens when the git log format has [`%G?`](https://git-scm.com/docs/git-log#Documentation/git-log.txt-emGem).
