### ISSUE TITLE
Update notifications reusable from bell to inbox

### ISSUE THREAD

**Issue by meowius** [github/docs#28578]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- "[Viewing your subscriptions](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions)" and other articles with the same reusable

### What part(s) of the article would you like to see updated?

Several GitHub Docs readers have recently noted that the UI for notifications has changed, which makes some articles on our site confusing.

In the past, notifications were indicated by a bell (at the top right of every logged-in page, next to the settings menu with the profile picture). Now, the icon is an inbox instead of a bell. We should update the reusable with this content so folks aren't confused.

The reusable `access_notifications.md` should be updated as follows:

- Replace the bell octicon with the inbox octicon in the text
- Replace the screenshot
- Update the alt text for the new screenshot

In the new screenshot, the profile picture should be replaced with an Octocat, and the screenshot should be taken in light mode. I've prepped and am attaching a new image here that can be used as a base image to apply an orange outline. [See instructions for applying the orange outline here.](https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots#highlighting-elements-in-screenshots)

![Screenshot of the right corner of the header of GitHub. An inbox icon has a blue dot, indicating that there are unread notifications, is outlined in dark orange.](https://github.com/github/docs/assets/10839362/aae1d4ee-d476-4376-80f0-7663a5d1d6de)

The new reusable will read like so:

```
1. In the upper-right corner of any page, click {% octicon "inbox" aria-label="You have (no) unread notifications" %}.

   ![Screenshot of the right corner of the header of GitHub. An inbox icon has a blue dot, indicating that there are unread notifications.](/assets/images/help/notifications/notifications-general-existence-indicator.png)
```

**Comment by Kyawgyi99999** [comment]
Thank

**Comment by Kota-Karthik** [comment]
Hello @meowius 
I am interested in solving this issue
so kindly assign me this issue
Thank You : )

**Comment by gonmmarques** [comment]
Hello @meowius

I have added the suggested changes and tried my best to make sure the image is complying with what is expected.

Let me know if there is anything else missing. Thank you.
