### ISSUE TITLE
Some variables in "Migrating from GitLab CI/CD to GitHub Actions" aren't resolved

### ISSUE THREAD

**Issue by ionicsolutions** [github/docs#28602]
### Maintainer's note

See comment below for the fix for this issue, https://github.com/github/docs/issues/28602#issuecomment-1741323276

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Migrating from GitLab CI/CD to GitHub Actions](https://docs.github.com/en/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions)

generated from [content/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions.md](https://github.com/github/docs/blob/c793d974c47b176cfee18cf4e0a1a7e31f798a5c/content/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions.md)

### What changes are you suggesting?

Some, but not all template inclusions show up as bare source code in the rendered output:

![image](https://github.com/github/docs/assets/32523967/98a2442b-c3ee-4a41-9c49-9f88d3e8181e)
![image](https://github.com/github/docs/assets/32523967/bf04610b-4b09-4809-905e-10f6bac159e8)
![image](https://github.com/github/docs/assets/32523967/bca69825-d083-4453-9092-e9c3961d9d9d)

A cursory check suggests that the referenced templates do exist. 

It doesnt't seem to be a general problem. For example, `{% data reusables.actions.action-cache %}` is correctly substituted:
![image](https://github.com/github/docs/assets/32523967/4d796ba0-513e-4624-91d9-8ac16f217f9e)

**Comment by Mistiterane** [comment]
```javascript

```

**Comment by lecoursen** [comment]
Thanks @ionicsolutions for pointing this out! It looks like we just need to remove the `{% raw %}` tags around the offending code examples. You or anyone else is welcome to open a PR to do so!

**Comment by meowius** [comment]
Thanks so much for spotting this @ionicsolutions! We're checking with our engineering team, as there isn't anything obvious amiss with the reusables themselves.

**Comment by ionicsolutions** [comment]
> Thanks @ionicsolutions for pointing this out! It looks like we just need to remove the `{% raw %}` tags around the offending code examples. You or anyone else is welcome to open a PR to do so!

Do these serve any purpose at all? They've been added with the [original version](https://github.com/github/docs/commit/729fc74a2c810f7b9c8593d4f45096d705b00172), which made use of HTML tables ([removed here](https://github.com/github/docs/commit/f0b4475d23538b17acda61484b47a68b0fa64667)) and should probably go completely? I don't see anything there that needs escaping.

As is also mentioned in [your own guidelines for contributing to docs](https://github.com/github/docs/blob/c793d974c47b176cfee18cf4e0a1a7e31f798a5c/contributing/troubleshooting.md#liquid-processing), these tags should only be used right where they are needed, not to escape entire sections.
