### ISSUE TITLE
Suggest using `gh cache` instead of `gh actions-cache`

### ISSUE THREAD

**Issue by spenserblack** [github/docs#28748]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches

### What part(s) of the article would you like to see updated?

The article suggests installing the `gh-actions-cache` extension for the GitHub CLI. However, recent versions of the GitHub CLI have the `gh cache` extension (https://github.com/cli/cli/pull/7403), which can be used instead installing the extension. Currently, the extension seems a bit out of date ([it appears to have trouble with the CLI's new token storage](https://github.com/actions/gh-actions-cache/issues/77)), so it's probably best to use the `gh cache` subcommand instead of the `gh actions-cache` extension.

### Additional information

[Maintainer edit]
Anyone can make the update to use `gh cache` but include the information that they should make sure to have version >= 2.32.0 of the CLI (https://github.com/cli/cli/releases/tag/v2.32.0) installed if they are doing this manually.

**Comment by skedwards88** [comment]
Thanks for suggesting this! I think this change sounds like a good idea. We will just want to tell people that they should make sure to have version >= 2.32.0 of the CLI (https://github.com/cli/cli/releases/tag/v2.32.0) installed if they are doing this manually.

You or anyone else is welcome to open a PR with this update.
