### ISSUE TITLE
CreateEvent docs missing ref_type=repository and pusher_type properties

### ISSUE THREAD

**Issue by nanodeath** [github/docs#28994]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The table around here: [Event payload object for CreateEvent](https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28#event-payload-object-for-createevent)

### What changes are you suggesting?

1. ref_type should include `repository`.
2. `ref` is null if ref_type is `repository`.
3. `pusher_type` is undocumented, but also, always `user` it looks like.

**Comment by steveward** [comment]
Thanks for opening an issue! We really appreciate all the details and added information ✨

I'll get this triaged for review! ⚡

**Comment by nanodeath** [comment]
Lastly, I should mention this is based on data I retrieved from https://www.gharchive.org/ for 2023/10/7, so if there's any reason that's somehow not representative of live GitHub events, that could be relevant.
