### ISSUE TITLE
Adding Shield Badges to the Readme.md file

### ISSUE THREAD

**Issue by mohitd404** [github/docs#29013]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Adding shield badges to a repository can provide several benefits, both for the maintainers of the repository and for potential users and contributors. Shield badges are small, informative images or icons that can be embedded in the repository's README or documentation

Shield badges can provide at-a-glance information about the status of the repository. For example, you can use badges to display build status, test coverage, code quality, and more. This helps users quickly assess the health and reliability of the project.

### What part(s) of the article would you like to see updated?

Shield badges are embedded in the repository's README or documentation, typically generated dynamically from various sources.

### Additional information

Ex:1   ![shie b](https://github.com/github/docs/assets/146939900/45913502-6757-4e75-b5e5-a70aaadacc2c)
Ex:-2  ![shield badges](https://github.com/github/docs/assets/146939900/eb55f2ff-ff03-4929-a048-0cb186cfca23)

@cmwilson21  Kindly assign me this issue, I would love to work on it thank you!

**Comment by mohitd404** [comment]
@cmwilson21 Kindly assign me this issue, I would love to work on it thank you!

**Comment by shontaredmond** [comment]
[https://fictional-funicular-wp5wgg46x66h9p6v.github.dev/]() 

Yes I will love to for you to work on it with me  #28994

**Comment by shontaredmond** [comment]
Config file not present. Please add config file at .github/engineering-scorecard.yaml in repository: docs

**Comment by steveward** [comment]
Thanks for the issue @mohitd404! At this time we aren't planning to add badges to the repository, but I appreciate the interest!
