### ISSUE TITLE
Typo error in Simplified Chinese

### ISSUE THREAD

**Issue by Mai-Ooizumi** [github/docs#29099]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/zh/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github#rebasing-and-merging-your-commits

### What part(s) of the article would you like to see updated?

The "git-revert" at the end of the second paragraph should be "git-rebase".

### Additional information

This error is highlighted in the screenshot.
![image](https://github.com/github/docs/assets/10705767/cd78678b-ae0d-4385-90e2-24bd801cf181)

**Comment by steveward** [comment]
Thanks for the issue @Mai-Ooizumi! Translations are handled through an internal process, so I'm going to go ahead and close this issue as I will be raising it with the internal team. 

We appreciate your heads up on this. Thank you for your interest in improving GitHub Docs!
