### ISSUE TITLE
Update reusable variables with new route

### ISSUE THREAD

**Issue by megbird** [github/docs#2919]
We currently use the following three steps to point a user to org settings:

`{{ site.data.reusables.profile.access_profile }}` 
   - file path =  `data/resuables/profile`
`{{ site.data.reusables.profile.access_org }}` 
   - file path = `data/resuables/profile` 
`{{ site.data.reusables.organizations.org_settings }}` 
   - file path = `data/resuables/org_settings` 

However, there is a slightly cleaner route of:

1. In the top right corner of GitHub, click your profile photo, then click "Your Organizations".
2. Click settings next to the org in the list.

We should update the reusables to use the simpler route.

### Content strategy and implementation

| Item | Core | DSP | Ecosystem/API |
| --- | --- | --- | --- |
| Unified content strategy plan | | | |

**Please link any in-flight PRs to this issue.**

**Comment by Chiramate1993** [comment]
> We currently use the following three steps to point a user to org settings:
> 
> `{{ site.data.reusables.profile.access_profile }}`
> 
> * file path =  `data/resuables/profile`
>   `{{ site.data.reusables.profile.access_org }}`
> * file path = `data/resuables/profile`
>   `{{ site.data.reusables.organizations.org_settings }}`
> * file path = `data/resuables/org_settings`
> 
> However, there is a slightly cleaner route of:
> 
> 1. In the top right corner of GitHub, click your profile photo, then click "Your Organizations".
> 2. Click settings next to the org in the list.
> 
> We should update the reusables to use the simpler route.
> 
> ### Content strategy and implementation
> Item	Core	DSP	Ecosystem/API
> Unified content strategy plan			
> **Please link any in-flight PRs to this issue.**

**Comment by OXmenEmily23** [comment]
#3031

**Comment by OXmenEmily23** [comment]
#523

**Comment by Nimmi597** [comment]
> We currently use the following three steps to point a user to org settings:
> 
> `{{ site.data.reusables.profile.access_profile }}`
> 
> * file path =  `data/resuables/profile`
>   `{{ site.data.reusables.profile.access_org }}`
> * file path = `data/resuables/profile`
>   `{{ site.data.reusables.organizations.org_settings }}`
> * file path = `data/resuables/org_settings`
> 
> However, there is a slightly cleaner route of:
> 
> 1. In the top right corner of GitHub, click your profile photo, then click "Your Organizations".
> 2. Click settings next to the org in the list.
> 
> We should update the reusables to use the simpler route.
> 
> ### Content strategy and implementation
> Item	Core	DSP	Ecosystem/API
> Unified content strategy plan			
> **Please link any in-flight PRs to this issue.**

https://github.com/github/docs/issues/2919#issue-787016956

**Comment by lumenCodes** [comment]
Hi, I would like to take up this issue, but I am confused on the file that will be affected  (where the change will be made).

**Comment by janiceilene** [comment]
👋  @lumenCodes You're welcome to take this on! Two of the files (`access_profile` and `access_org`) are located in the reusables directory, in the profiles folder https://github.com/github/docs/tree/main/data/reusables/profile. The third one (`org_settings`) is in the organizations folder https://github.com/github/docs/blob/main/data/reusables/organizations/org_settings.md.

@megbird Are you looking for each of the three reusables to be updated to follow the two steps you outlined?
>  1. In the top right corner of GitHub, click your profile photo, then click "Your Organizations".
> 2. Click settings next to the org in the list.

**Comment by lumenCodes** [comment]
Thank you so much!

**Comment by megbird** [comment]
So sorry I haven't given any guidance for this! 

We use reusable files that we can use as variables all over the site. This issue suggests that we update three reusable and condense them down to two. 

For this PR, let's make the following updates:

- [ ] Update file `data/resuables/profile/access_org` to say: 
> 1. In the top right corner of GitHub, click your profile photo, then click "Your Organizations".
- [ ] Update data/reusables/profile/org_settings.md to say:
> 2.  Click **Settings** next to the organization. 

- [ ] Find instances where this occurs in the docs and replace 
```
{% data reusables.profile.access_profile %}
{% data reusables.profile.access_org %}
{% data reusables.organizations.org_settings %}
```
with this 

```
{% data reusables.profile.access_org %}
{% data reusables.organizations.org_settings %}
```

☝️ make sure to only replace instances where all three reusable are used in this sequence, so that the procedure is still in order 😄 

@lumenCodes I know you've already started a PR, ping me in if you have any questions! 💛

**Comment by DevAStar08** [comment]
May I try to resolve this issue #2919 @megbird

**Comment by DevAStar08** [comment]
I m bit of confused for changes to be made for replacing instance .Can I get help for this??

**Comment by hamedtayeban** [comment]
[]()https://www.blockchain.com/btc/address/3BSF9sjD9ksocwSPrswRKnZdRCp5A4HcL9 #2991 @hamedtayeban22

**Comment by janiceilene** [comment]
@lumenCodes I see your two PRs and they look 👍 The last piece of this issue is the docs to find all the places where the three reusables are used

```
{% data reusables.profile.access_profile %}
{% data reusables.profile.access_org %}
{% data reusables.organizations.org_settings %}
```
and replace them with
```
{% data reusables.profile.access_org %}
{% data reusables.organizations.org_settings %}
```
as described in https://github.com/github/docs/issues/2919#issuecomment-784556744. Searching in the repo on github.com will give you a bunch of partial results, so you'll want to use your editor to search instead.

**Comment by StarTrooper08** [comment]
ok I will do it  👍

**Comment by StarTrooper08** [comment]
@janiceilene I have made a PR for #2919 issue . Please have a review.
I have reviewed from my side but still it is major fixture so its better to review it ones more.
Thank you that was fun and exciting work.
And sorry for the delay I was having my college work.
