### ISSUE TITLE
EMU username considerations should move under EMU category

### ISSUE THREAD

**Issue by cringdahl** [github/docs#29312]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/managing-iam-for-your-enterprise/username-considerations-for-external-authentication

### What part(s) of the article would you like to see updated?

This article contains information only useful to Enterprise Managed Users. It should be moved to the EMU map here:

https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-enterprise-managed-users-for-iam/

**Comment by arujjval** [comment]
@cringdahl please assign me this problem.

**Comment by sophietheking** [comment]
@cringdahl 👋 I'm checking your proposed change with the relevant team. Will report back once I know more! ✨
