### ISSUE TITLE
Typo on labels and milestones/milestone progress

### ISSUE THREAD

**Issue by ThatsNasu** [github/docs#29321]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Reading through the documentation for milestones, i stumbled upon a typo on the [viewing your milestones progress](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/viewing-your-milestones-progress) page.

### What part(s) of the article would you like to see updated?

On Section 3. it states "In the upper-left corner, click Milestones", referencing the example image below it where the highlight for the Milestone button is in the upper-right corner.

### Additional information

![docs github typo](https://github.com/github/docs/assets/38265230/4515d394-f3bb-406c-846a-d2efb6eaa615)

**Comment by arujjval** [comment]
@ThatsNasu  I want to work on this issue. Please assign me this issue.
