### ISSUE TITLE
https://github.com/github/docs/issues/2825#issuecomment-758903674Thanks so much for opening a discussion and then an issue @Andre601! I've triaged this for the team to take a look 👀

### ISSUE THREAD

**Issue by DannyBhoy82** [github/docs#2954]
Thanks so much for opening a discussion and then an issue @Andre601! I've triaged this for the team to take a look 👀

_Originally posted by @janiceilene in https://github.com/github/docs/issues/2825#issuecomment-758903674_

**Comment by DannyBhoy82** [comment]
> Thanks so much for opening a discussion and then an issue @Andre601! I've triaged this for the team to take a look 👀
> 
> _Originally posted by @janiceilene in https://github.com/github/docs/issues/2825#issuecomment-758903674_

[]()

**Comment by Andre601** [comment]
Can you stop wasting everyones time here?
You're not cool nor funny and this will only get you banned from GitHub altogether.
(Yes I'm aware that this might be an automated account, but it's still worth a try)

**Comment by DannyBhoy82** [comment]
> Thanks so much for opening a discussion and then an issue @Andre601! I've triaged this for the team to take a look 👀
> 
> _Originally posted by @janiceilene in https://github.com/github/docs/issues/2825#issuecomment-758903674
