### ISSUE TITLE
Leave a reply

### ISSUE THREAD

**Issue by jraah555** [github/docs#29589]
Leave a reply

_Originally posted by @jraah555 in https://github.com/bc-game-project/bcgame-crash/pull/15#discussion_r1377006428_

**Comment by githraj** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).

_issue_:
That's great. Is it possible to follow all guidelines without issues
