### ISSUE TITLE
`github` context usage in composite actions is unclear

### ISSUE THREAD

**Issue by rsenden** [github/docs#29615]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/actions/learn-github-actions/contexts.md

### What part(s) of the article would you like to see updated?

`{% data reusables.actions.composite-actions-unsupported-refs %}` generates the following text, which I think is unclear:

---

Do not use in the run context. To make this context work with composite actions, reference it within the env context of the composite action.

---

Which `env` context is this referring to exactly? There is no global `env:` section in composite actions, so is this:

1. Referring to the `env:` section on the individual run-steps inside a composite action? For example:

        runs:
          using: composite
          steps:
            - run: echo SOMEVAR=${REPO}:${REF} >> $GITHUB_ENV
              shell: bash
              env:
                 REPO: ${{ github.action_repository }}
                 REF: ${{ github.action_ref }}

2. Referring to the `env:` section of the caller of the composite action?

        uses: org/composite-action@v1
        env:
            REPO: ${{ github.action_repository }}
            REF: ${{ github.action_ref }}
 
3. Something else?

Obviously, \#1 would be preferred to have self-contained composite actions, and this seems to work fine for at least the scenarios that I've tested, but is this officially supported?

Can the documentation please be improved to explicitly describe how to use the `github` context in composite actions?

**Comment by scoubasteve** [comment]
if (typeof action === 'function') {
  return action(dispatch, getState);
}
const { promise, actions, ...rest } = action;
if (!promise) {...

**Comment by nguyenalex836** [comment]
@rsenden Howdy! 👋 Apologies for our delay in getting back to you. Since a significant amount of time has passed since this was initially posted, can you elaborate on your asks here, including what you mean by "run context"?

Would it clarify this to instead call this the `run` keyword to match the workflow syntax documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun ?
