### ISSUE TITLE
Schedule.cron validation does not allow valid intervals of days of the week

### ISSUE THREAD

**Issue by rlueder** [github/docs#29634]
[maintainer update - check the latest comment [here](https://github.com/github/docs/issues/29634#issuecomment-1789705971) for review needs]

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The documentation on Github workflows for the `onschedule` property of jobs:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule

### What changes are you suggesting?

The regex from https://json.schemastore.org/github-workflow.json does not allow for valid cron job syntax of day of the week intervals e.g.

[0 0 * * SUN-TUE,THU-SAT](https://crontab.guru/#0_0_*_*_SUN-TUE,THU-SAT) or [0 0 * * 0-2,4-6](https://crontab.guru/#0_0_*_*_0-2,4-6) which both translate to:

> “At 00:00 on every day-of-week from Sunday through Tuesday and every day-of-week from Thursday through Saturday.”

The validation displays the following error:

> String does not match the pattern of "^(((\d+,)+\d+|((\d+|\*)/\d+|((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)(-(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))?))|(\d+-\d+)|\d+(-\d+)?/\d+(-\d+)?|\d+|\*|(MON|TUE|WED|THU|FRI|SAT|SUN)(-(MON|TUE|WED|THU|FRI|SAT|SUN))?) ?){5}$".yaml-schema: GitHub Workflow

My use case is a Github workflow that skips Wednesdays (which can be defined in other ways ie. THU-TUE but the one above is the most intuitive). The website used as a reference on the documentation ([crontab.guru](https://crontab.guru/)) correctly validates the intervals above.

**Comment by rlueder** [comment]
@cmwilson21 thanks for getting back to me!

I'm sorry I wasn't clear, I think the regex used for pattern matching cron jobs is not comprehensive enough.

If updating the regex is not an option I think a note on the docs stating that not all valid cron patterns are accepted would be helpful, I spent some time trying the pattern on my example above until I decided to test the regex pattern below separately.

```
{
  "schedule": {
    "$comment": "https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule",
    "description": "You can schedule a workflow to run at specific UTC times using POSIX cron syntax (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07). Scheduled workflows run on the latest commit on the default or base branch. The shortest interval you can run scheduled workflows is once every 5 minutes.\nNote: GitHub Actions does not support the non-standard syntax @yearly, @monthly, @weekly, @daily, @hourly, and @reboot.\nYou can use crontab guru (https://crontab.guru/). to help generate your cron syntax and confirm what time it will run. To help you get started, there is also a list of crontab guru examples (https://crontab.guru/examples.html).",
    "type": "array",
    "items": {
      "properties": {
        "cron": {
          "$comment": "https://stackoverflow.com/a/57639657/4044345",
          "type": "string",
          "pattern": "^(((\\d+,)+\\d+|((\\d+|\\*)/\\d+|((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)(-(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))?))|(\\d+-\\d+)|\\d+(-\\d+)?/\\d+(-\\d+)?|\\d+|\\*|(MON|TUE|WED|THU|FRI|SAT|SUN)(-(MON|TUE|WED|THU|FRI|SAT|SUN))?) ?){5}$"
        }
      },
      "additionalProperties": false
    },
    "minItems": 1
  }
}

```

**Comment by rlueder** [comment]
Actually now that I read the docs more carefully they do specifically call out POSIX cron syntax which would explain why my attempt didn't work.

> You can use on.schedule to define a time schedule for your workflows. You can schedule a workflow to run at specific UTC times using [POSIX cron syntax](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07).

I think mentioning [crontab.guru](https://crontab.guru/) added to the confusion as it accepts syntaxes other than POSIX. 

Feel free to close if you think it's appropriate. Thanks again!

**Comment by lecoursen** [comment]
Hi @rlueder, thanks for all your help in getting to the bottom of this!

>I think mentioning [crontab.guru](https://crontab.guru/) added to the confusion as it accepts syntaxes other than POSIX, perhaps a note along the lines of keep in mind crontab.guru and other tools might accept syntaxes other than POSIX would help others. 
>
>Feel free to close if you think it's appropriate. Thanks again!

The section about using cron syntax in "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#scheduled-events)" is already quite long, with detailed explanations and callouts, so I'm worried that adding yet another nuance will make the section less readable without a big enough payoff. I'm going to close this issue as you suggest, but thanks again for the time you put into helping us understand your situation!
