### ISSUE TITLE
Correction for "Enabling OAuth app access restrictions for your organization"

### ISSUE THREAD

**Issue by hermandr** [github/docs#29660]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/enabling-oauth-app-access-restrictions-for-your-organization

### What part(s) of the article would you like to see updated?

![image](https://github.com/github/docs/assets/10177608/0d9c1696-c0e6-4995-bbfe-68707a68bce5)

Needs to be updated.
The sidebar looks like this at Organisation Settings:
![image](https://github.com/github/docs/assets/10177608/bb456643-33ab-4ca6-b851-2e0a6eef9f57)

OAuth Apllication Policy is under "Third-party Access" and not under "Integrations"

Looking at the github docs code...
```
{% data reusables.profile.access_org %} {% data reusables.profile.org_settings %} {% data reusables.organizations.oauth_app_access %}

Under "Third-party application access policy," click Setup application access restrictions.
After you review the information about third-party access restrictions, click Restrict third-party application access.
```
* The re-usable include needs to be changed. - remove the `Under Integrations`
* `Under "Third-party application access policy," click Setup application access restrictions.` -> `Under "Third-party access" click Setup application access restrictions.` 

### Additional information

Nothing else

**Comment by lecoursen** [comment]
Thanks for pointing this out @hermandr! We should update step 3 to say this:

>In the "Third-party Access" section of the sidebar, click **OAuth application policy.**

Step 4 is still accurate though. That step is not referring to language in the sidebar, but to to the heading of the page you're taken to after you click **OAuth application policy** in the sidebar, which is still "Third-party application access policy."

You are anyone else is welcome to open a PR making that change to step 3!

**Comment by SoundaryaKoutharapu** [comment]
Hi @lecoursen,
I'd like to work on this.
I couldn't locate the source file or the original document where they are re-usable are defined 
can you please point me to the file?

**Comment by lecoursen** [comment]
Sure @SoundaryaKoutharapu! The reusable is here:

https://github.com/github/docs/blob/main/data/reusables/organizations/oauth_app_access.md

**Comment by SoundaryaKoutharapu** [comment]
Thank you so much @lecoursen!
I've fixed the issue and made a pr.
