### ISSUE TITLE
`Further reading` item in `About READMEs` links to an archived repository

### ISSUE THREAD

**Issue by error9900** [github/docs#29828]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[About READMEs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)

### What part(s) of the article would you like to see updated?

In the [Further reading](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#further-reading) section, the bullet point for '18F's "[Making READMEs readable](https://github.com/18F/open-source-guide/blob/18f-pages/pages/making-readmes-readable.md)"' links to a file in an archived repository.

In the file in the archived repository, in the section titled [A description of what the project is for.](https://github.com/18F/open-source-guide/blob/18f-pages/pages/making-readmes-readable.md#a-description-of-what-the-project-is-for), there is a link to [README for 18F's Midas project](https://github.com/18f/midas), as an example README, but that link is dead.

I suppose an argument could be made that there is still other useful information in that file, but, at a minimum, I think a warning that you're linking to an archived repository would be helpful as I immediately started reading the document without noticing the `This repository has been archived by the owner...` at the top.

Additionally, if there is some other up-to-date/active `README` that would be a useful example, adding that to the `Further reading` section would be helpful.

----
_Maintainer addition_

## Recommended content changes to fix this issue

Replace the link to the archived 18F repository with a link to a recent blog post on writing an accessible `README` file: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/

**Comment by felicitymay** [comment]
@error9900 - many thanks for highlighting this issue 💖 

I suggest that we replace the old link with a link to a recent [blog post on writing an accessible `README` file](https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/).

I'll update the issue summary with this suggestion and add a `help-wanted` label to your issue. Then it will be clear to contributors how to fix this issue.
