### ISSUE TITLE
Steps to start SSH agent in "Generate new SSH key" provide incorrect information

### ISSUE THREAD

**Issue by cinnamondev** [github/docs#29847]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Authentication -> Generate new SSH key

### What part(s) of the article would you like to see updated?

Under the heading "Adding your SSH key to the ssh-agent", Step 1 of the process tells the reader they can execute the commands listed below in either an elevated PowerShell or elevated CMD. The commands in question use PowerShell cmdlets and cannot be used in cmd.exe.

It would be better that this is either rephrased to exclusively use PowerShell, or alternatively the example can be rewritten to use `sc.exe`.

**Comment by 3118939810fa187e** [comment]
AI Infrastructure ML and DL Model Training
Options for every business to train deep learning and machine learning models cost-effectively.

**Comment by thusieblessed23** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> Authentication -> Generate new SSH key
> 
> ### What part(s) of the article would you like to see updated?
> 
> Under the heading "Adding your SSH key to the ssh-agent", Step 1 of the process tells the reader they can execute the commands listed below in either an elevated PowerShell or elevated CMD. The commands in question use PowerShell cmdlets and cannot be used in cmd.exe.
> 
> 
> 
> It would be better that this is either rephrased to exclusively use PowerShell, or alternatively the example can be rewritten to use `sc.exe`.
> 
> ### Additional information
> 
> _No response_
