### ISSUE TITLE
[Copilot Pre-release License terms] Unclear what data is collected

### ISSUE THREAD

**Issue by nikwen** [github/docs#29886]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/site-policy/github-terms/github-copilot-pre-release-license-terms

### What part(s) of the article would you like to see updated?

* I would love to know which data Github collects during the Github Copilot "Chat in Jetbrains" beta.
* Specifically, since these pre-release terms supersede the other Copilot terms, I would like to know whether Github uses my code snippets and the contents of my conversations with Github Copilot Chat for training purposes.

**Comment by Harrisbaig7** [comment]
Hi @nikwen ,

Thank you for bringing up this important question and for your interest in GitHub Copilot.

I understand your concerns about data collection during the "Chat in JetBrains" beta. To provide accurate information, I recommend reaching out directly to GitHub Support or the GitHub Copilot team. They are best equipped to answer questions about data usage and privacy concerns.

You can contact them by [GitHub Community forum](https://github.community/) and (https://support.github.com/contact). They will be able to provide you with detailed and up-to-date information regarding data collection practices during the beta.

If there's anything else I can help you with or if you have further questions, feel free to let me know.

Best regards,
@Harrisbaig7

**Comment by nikwen** [comment]
Thank you for your comment, @Harrisbaig7! I've posted a [request](https://github.com/orgs/community/discussions/69250#discussioncomment-7540243) in the community forum.

**Comment by nikwen** [comment]
Any updates, @cmwilson21?

**Comment by myarb** [comment]
👋🏼 @nikwen Thanks for following up! This is on our team's review board, and a writer will take a look at it soon ✨

**Comment by nikwen** [comment]
Thanks you, @myarb! :)

**Comment by hubwriter** [comment]
Hi @nikwen - I reached out to Copilot product management for help with this. They've now got back to me. Thanks for your patience.

I hope the following information answers your questions.

<hr>

### What types of data does GitHub Copilot Chat beta use to provide the service? 

GitHub Copilot Chat beta uses three types of data to provide the service:

1. _User Engagement Data:_ User Engagement Data is data about user interactions with the service and overall usage data, which includes pseudonymous identifiers. A pseudonymous identifier is like a code name for a person. It's a privacy tool allowing data collection without directly linking it to a specific individual. 
1. _Contextual Prompts:_  A Contextual Prompt is the combination of a summary of contextual information gleaned from the user as well as the question submitted in the chat interface
1. _Suggestions:_ A Suggestion is one or more lines of proposed text returned to the GitHub Copilot Chat beta extension after a Contextual Prompt is received and processed by the AI-model. It is the output provided by the chat system to answer a user's query or engage in a conversation with the user. 

### What data does GitHub use to create a Contextual Prompt? 

GitHub Copilot Chat beta creates a Contextual Prompt by combining (1) a “context summary” with (2) the question you submit to your editor. 

For instance, if you submit “what does this method do” the client for GitHub Copilot Chat beta will automatically gather context from your active documents in the editor to determine what you mean by the word “this.” It will then compose a suitable question to pose to the GitHub Copilot Chat beta model that automatically includes that selection, without you needing to copy and paste code into the chat window, saving you time and delivering a hopefully useful response.

Depending on the question you ask, the GitHub Copilot Chat beta client will automatically use appropriate aspects of your context to form the question. The information it uses may include:

- The code file open in your active document
- Your selection (or “code blocks for the current cursor position”) in the document
- Summaries of related documents open in your editor or from the workspace
- Information about errors/warnings/messages/exceptions in your error list
- General workspace information, such as frameworks, languages, and dependencies
- Parts of related files in your workspace/project/repo

### Does GitHub Copilot Chat beta retain, collect or store data by default? 

The data handling details depend on whether you are using GitHub Copilot Chat beta as a GitHub Copilot for Business or GitHub Copilot for Individuals user and your settings if you are a Copilot for Individuals user. 

- Contextual Prompts and Suggestions are not stored at rest for Copilot for Business users
- If you use Copilot for Individuals, your Contextual Prompts and Suggestions from your interactions with Copilot Chat beta will be retained unless you’ve disabled such collection in your [current Copilot settings](https://github.com/settings/copilot) 
- User Engagement Data is collected and retained from all users, regardless of product type, for 2 years.

### Does GitHub Copilot Chat beta use Contextual Prompts or Suggestions to train its Large Language Model (LLM) by default? 

No. For GitHub Copilot for Business users, GitHub does not store Contextual Prompts or Suggestions from use of Copilot Chat beta at rest and hence such data is not used to train models. For GitHub Copilot for Individual users, GitHub retains this data from use of Copilot Chat beta unless the user disables such collection in their [current Copilot settings](https://github.com/settings/copilot).

### Will my Contextual Prompts or Suggestions be shared with other users?

GitHub does not store Contextual Prompts or Suggestions from use of GitHub Copilot Chat beta for Copilot for Business users. GitHub only stores Contextual Prompts and Suggestions from use of Copilot Chat beta for GitHub Copilot for Individual users that have opted to enable such collection in their Copilot settings. Regardless, GitHub does not share that data with other users.

**Comment by nikwen** [comment]
@hubwriter Thank you so much for your reply! That's exactly the information that I was looking for. You've answered my question perfectly. Huge thanks! :heart:

**Comment by hubwriter** [comment]
I think we can close this.
