### ISSUE TITLE
Specifying credentials for service containers

### ISSUE THREAD

**Issue by ndench** [github/docs#29914]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-containerized-services/about-service-containers

### What part(s) of the article would you like to see updated?

The docs don't show how to specify credentials when using service containers. Credentials may be necessary to pull images from private registries or to authenticate with DockerHub in order to increase rate limits.

**Comment by Jessica844** [comment]
Awesome
