### ISSUE TITLE
Add pure shell script example

### ISSUE THREAD

**Issue by traed** [github/docs#29925]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#example-using-python-to-generate-a-jwt

### What part(s) of the article would you like to see updated?

I would like a pure shell script example of how the JWT is supposed to be generated (that can be used inside a docker container). I don't want to depend of python or ruby just to generate a token and the examples don't work well inside a container. My latest attempt looks like this but for some reason the JWT is invalid:

```
#!/bin/bash

app_id=$1
pem=$2

header='{
	"typ": "JWT",
	"alg": "RS256",
	"iss": "$app_id"
}'

header=$(
	echo "${header}" | jq --arg time_str "$(date +%s)" \
	'
	($time_str | tonumber) as $time_num
	| .iat=$time_num
	| .exp=($time_num + 1)
	'
)

base64_encode()
{
	declare input=${1:-$(</dev/stdin)}
	printf '%s' "${input}" | base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n'
}

json() {
	declare input=${1:-$(</dev/stdin)}
	printf '%s' "${input}" | jq -c .
}

hmacsha256_sign()
{
	declare input=${1:-$(</dev/stdin)}
	printf '%s' "${input}" | openssl dgst -binary -sha256 -sign $pem
}

header_base64=$(echo "${header}" | json | base64_encode)
signature=$(echo "${header_base64}" | hmacsha256_sign | base64_encode)

echo "${header_base64}.${signature}"
```

### Content plan
Once a working shell script has been provided, update to include the new example

**Comment by skedwards88** [comment]
Thanks for opening this issue! I think adding a shell script example sounds great. We can't help you with your shell script, but you might find help by posting in the [GitHub Community](https://github.com/orgs/community/discussions).

You or anyone is welcome to open a PR to add this example once you/another contributor has a working script.

**Comment by mark-mxwl** [comment]
Hey there! I've created a PR for this issue with a working shell script. Thx @traed for your amazing suggestion. I took a slightly different approach, but your initial script was very helpful and inspiring! Would love to hear any feedback you or @skedwards88 might have on the new script. This was a fun one 🚀
