### ISSUE TITLE
Additional help on getting the installation ID of an App

### ISSUE THREAD

**Issue by vandanrohatgi** [github/docs#30063]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app#generating-an-installation-access-token

The current docs only describe ways to get the Installation ID of the app using a REST API call. I recently wanted to get the ID and didn't have the permissions to make the REST API call as I was not the Org admin. I didn't want to make the admin make the API calls and was hoping to grab the ID just from somewhere on the UI.

This can be achieved by
`Profile -> Settings -> Integrations -> Applications -> Your app -> Configure -> ID in the URL`

### Additional information

Happy to make the PR :)

**Comment by skedwards88** [comment]
Thanks for this issue! I agree that it would be good to add this info to the article. Since the steps are different for user-owned vs organization-owned apps, I think we can say something like this:

> You can also find the app ID on the settings page for your app. The app ID is different from the client ID. For more information about navigating to the settings page for your {% data variables.product.prodname_github_app %}, see "[AUTOTITLE](/apps/maintaining-github-apps/modifying-a-github-app-registration#navigating-to-your-github-app-settings)."

You or anyone else is welcome to open a PR to add this.
