### ISSUE TITLE
Pages: misleading description about deprecated code highlighter `pygments`

### ISSUE THREAD

**Issue by muzimuzhi** [github/docs#30152]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#syntax-highlighting

### What part(s) of the article would you like to see updated?

Currently the section "[Syntax highlighting](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#syntax-highlighting)" says

> By default, code blocks on your site will be highlighted by Jekyll. Jekyll uses the [Rouge](https://github.com/jneen/rouge) highlighter, which is compatible with [Pygments](https://pygments.org/). Pygments has been deprecated and not supported in Jekyll 4.

This may mislead readers that GitHub Pages already uses Jekyll 4, while actually it still uses Jekyll 3.9.3. See
- Dependency versions | GitHub Pages https://pages.github.com/versions/
- https://github.com/github/pages-gem/issues/651

### Additional information

What "Pygments has been deprecated and not supported in Jekyll 4." (added in https://github.com/github/docs/commit/724a274245fa9e90df3f5d19114e4efb91de506f) said is true, but it's not the appropriate reason. `pgyments` was deprecated because GitHub Pages wanted to, not because the version of Jekyll used by GitHub Pages dropped support for it.

Pygments support was dropped 
- by GitHub Pages in https://github.com/github/pages-gem/commit/10b6ca7cb889188c7afb51010a52cfcc633ff1e5 committed on 2015-10-27 and shipped with `github-pages` gem package [v44](https://github.com/github/pages-gem/releases/tag/v44) on 2016-02-02 and
- by Jekyll in https://github.com/jekyll/jekyll/commit/4707017936ce0dd600bf6e0c339960058c524edf committed on 2018-09-27 and shipped with Jekyll [v4.0.0](https://github.com/jekyll/jekyll/releases/tag/v4.0.0) on 2019-08-20, which is 3.5 years later.

**Comment by janiceilene** [comment]
👋 @muzimuzhi Thanks so much for opening an issue! I'll get this triaged for review ✨

**Comment by Alexx65we39** [comment]
Ok

**Comment by Alexx65we39** [comment]
Ok

**Comment by sophietheking** [comment]
@muzimuzhi 👋 Thanks for opening this issue and contributing to our Docs, we really appreciate it. It looks like these two sentences can be removed completely:

> Jekyll uses the [Rouge](https://github.com/jneen/rouge) highlighter, which is compatible with [Pygments](https://pygments.org/). Pygments has been deprecated and not supported in Jekyll 4.

You or anyone else is welcome to open a PR. 🔨

**Comment by NavinPa** [comment]
Help

**Comment by janbrasna** [comment]
@sophietheking Actually I think the compatibility bit is important, so I've kept it in #31808 — otherwise agree.

**Comment by muzimuzhi** [comment]
@janbrasna Agreed with you. And thank you.
