### ISSUE TITLE
Markdown syntax / Alerts section: incorrect number of alert types

### ISSUE THREAD

**Issue by zcahana** [github/docs#30163]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Basic writing and formatting syntax
](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

### What part(s) of the article would you like to see updated?

The [Alerts section](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) mentions that "_Three types of alert are available_" but then describes five types of alerts (Note, Tip, Important, Warning, Caution).

I believe that originally there were indeed 3 types (Note, Important, Warning), but then additional types were added but the "Three" remained in place. Practically, the exact number doesn't matter much, but rather the distinction that there are multiple types available.

Hence, the suggested fix is simply to change "_Three_" to "_Multiple_".

**Comment by janiceilene** [comment]
@zcahana Thank you for opening an issue and linking it to your PR! ✨
