### ISSUE TITLE
CodeQL CLI setup docs don't cover warning messages from `codeql resolve qlpacks`command

### ISSUE THREAD

**Issue by bradykelly** [github/docs#30161]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Code security/CodeQL CLI/Getting Started/Setting up the CodeQL CLI](https://docs.github.com/en/code-security/codeql-cli/getting-started-with-the-codeql-cli/setting-up-the-codeql-cli)

### What part(s) of the article would you like to see updated?

Under section 3 [Launch codeql](https://docs.github.com/en/code-security/codeql-cli/getting-started-with-the-codeql-cli/setting-up-the-codeql-cli#3-launch-codeql), the topic [Testing the CodeQL CLI configuration](https://docs.github.com/en/code-security/codeql-cli/getting-started-with-the-codeql-cli/setting-up-the-codeql-cli#testing-the-codeql-cli-configuration) tells the reader to run `codeql resolve qlpacks`.

Then the article says, "ÿou should see output similar to the extract below, if successful:", and shows an example of output if the command succeeds. Following the articles instructions to the letter, I downloaded the _codeql-bundle-win64.tar.gz_ bundle and extracted it, and ran the `codeql resolve qlpacks` command.

My output contained several messages like this one:
> codeql/controlflow is found in 5 same-priority locations, so attempts to resolve it will fail:
   C:\dev\New folder\CodeQL\qlpacks\codeql\controlflow\0.1.3
   C:\dev\New folder\CodeQL\qlpacks\codeql\csharp-examples\0.0.0\.codeql\libraries\codeql\controlflow\0.1.3
   C:\dev\New folder\CodeQL\qlpacks\codeql\csharp-queries\0.8.3\.codeql\libraries\codeql\controlflow\0.1.3
   C:\dev\New folder\CodeQL\qlpacks\codeql\ruby-examples\0.0.0\.codeql\libraries\codeql\controlflow\0.1.3
   C:\dev\New folder\CodeQL\qlpacks\codeql\ruby-queries\0.8.3\.codeql\libraries\codeql\controlflow\0.1.3
   
I looked at the docs for the `codeql resolve qlpacks` command and took a lucky guess that because the bundle contains nested folders, I should use the `--no-recursive` option for the command. Other readers may not be as lucky and not understand why the command given in the instructions does not work as expected.

I expect everyone will get the same attached output using the same CLI bundle, so either the bundle should contain a README explaining how to avoid the warning messages, or your setup docs should contain a link to the docs for the command, with a hint to try the `--no-recursive` option if they see messages like I did.

[resolve-qlpacks-output.txt](https://github.com/github/docs/files/13451512/resolve-qlpacks-output.txt)

### Additional information

I am able to reproduce the problem, as its cause lies with the structure of the CLI bundle I used, `codeql-bundle-win64.tar.gz`. Running the `codeql resolve qlpacks` command without the `--no-recursive` option always produces the same output for the same bundle contents.

I am more than happy to submit a PR to add a hint to the CLI setup docs, but I think the problem is bundle dependent, so I'm not sure where to add the advice.

**Comment by janiceilene** [comment]
@bradykelly Thanks so much for opening an issue! I'll get this triaged for review ⚡

**Comment by felicitymay** [comment]
@bradykelly - thanks for raising this issue and letting us know about this discrepancy between the docs and the bundle. I'm going to check with the engineering team whether the change is intentional or not. Then we can decide on whether or not to update the docs.

**Comment by felicitymay** [comment]
It sounds as if there's a newer command that should work better for this case: `codeql resolve library-packs`.

Would you be able to test that this works better? Then we can convert this into a "help wanted" issue with details of the docs updates needed to fix the problem.

**Comment by felicitymay** [comment]
Reopening to give @bradykelly time to respond. Our `stale` process doesn't respect holidays.
