### ISSUE TITLE
Graphql API search query docs doesn't show how to sort results

### ISSUE THREAD

**Issue by aliok** [github/docs#30204]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/reference/queries#search

### What part(s) of the article would you like to see updated?

I understand that the "Search" Graphql query is just a wrapper around the Search REST API, but I wasn't able to find a way to sort the results.

In Slack @zkoppert helped me and told me that I can use this search query `kag sort:followers-desc`. (thanks!)

However, it is not obvious in the documentation.

The [REST API syntax](https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-users) is a bit different where you define 2 separate parameters: `q` and `sort` (and `order`). So, I couldn't make that connection myself.

**Comment by steveward** [comment]
Thanks for the issue @aliok, I'll get this triaged for someone on the team to take a look.

**Comment by skedwards88** [comment]
Thanks for opening this issue! I'm checking with the API team about a couple of things before we determine the resolution.

(Internal note: check in is [here](https://github.slack.com/archives/C1042T6MS/p1701450738285619))

**Comment by user8104988254885** [comment]
Uploading 9cdbf5e7393b749e183371470cc6a598 (1).mp4…

**Comment by aliok** [comment]
> Thanks for opening this issue! I'm checking with the API team about a couple of things before we determine the resolution.

To clarify, this is just about updating the docs to reflect that it is possible to sort search results.

**Comment by skedwards88** [comment]
Thanks again for this issue! We'll update the GraphQL search docs to make it clear that the GitHub search syntax is supported there and link to docs about the syntax (e.g. [Understanding the search syntax - GitHub Docs](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax), [Sorting search results - GitHub Docs](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/sorting-search-results), and [Searching on GitHub - GitHub Docs](https://docs.github.com/en/search-github/searching-on-github)). This change needs to be made internally, so I'm going to add a label that will transfer this work to our internal process.
