### ISSUE TITLE
Incorrect code samples on the `Render a Markdown document` page

### ISSUE THREAD

**Issue by nikpivkin** [github/docs#30222]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/markdown/markdown?apiVersion=2022-11-28#render-a-markdown-document-in-raw-mode

### What part(s) of the article would you like to see updated?

The code samples don't work.

### Additional information

The article gives an example of markdown rendering:
```bash
gh api \
  --method POST \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /markdown \
  -f text='Hello **world**' 
```

But I'm getting an error from the server:
```bash
{
gh: Invalid request media type (expecting 'text/plain') (HTTP 415)
  "message": "Invalid request media type (expecting 'text/plain')",
  "documentation_url": "https://docs.github.com/rest/markdown/markdown#render-a-markdown-document-in-raw-mode"
}
```

I get the same error and for the example `Render a Markdown document in raw mode`.

I think this is also true for the `cli` and `js` examples.

The `Content-Type: text/plain` header must be specified:
```bash
gh api \
  --method POST \
  -H "Content-Type: text/plain" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /markdown/raw \
  -f text='Hello **world**'
```
___

Also:
A query to `/markdown/raw` with payload `Hello **world**` returns the following response: `<p>{"text":"Hello <strong>world</strong>"}</p>`. Why does the response contain curly braces? Is this a server error? In the example, a similar query returns `"<p>Hello <strong>world</strong></p>"`

**Comment by steveward** [comment]
Thanks for the issue @nikpivkin, I'll get this triaged for review!

**Comment by SHHuang178818** [comment]
Good

**Comment by nguyenalex836** [comment]
Internal: followed up [here](https://github.slack.com/archives/C73985URG/p1707518958689839)

**Comment by skedwards88** [comment]
Apologies for the delay, and thanks for this report! Although we document the required header in the endpoint description, you are correct that the autogenerated examples are missing this information. We have a feature request to support this, so I will add your report to that internal request and then close out this issue.
