### ISSUE TITLE
Offer github.com ssh key fingerprints as a .txt file on a dedicated webpage

### ISSUE THREAD

**Issue by oregonpillow** [github/docs#30226]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

### What part(s) of the article would you like to see updated?

Instead of only listing the keys on the aforementioned page, offer the fingerprint keys on a dedicated page as well, for example: github.com/ssh-key-fingerprints.txt

This change would make it significantly easier for people provisioning systems to auto add the keys to their known_hosts file. 
(in similar fashion to how user keys are available at https://github.com/<user>.keys)

**Comment by steveward** [comment]
Thanks for the issue @oregonpillow! The keys are accessible via the API, so you could use that to add them automatically:

https://docs.github.com/en/rest/meta/meta?apiVersion=2022-11-28#get-github-meta-information

I hope that helps!
