### ISSUE TITLE
Creating a support ticket advice is wrong

### ISSUE THREAD

**Issue by jsoref** [github/docs#30272]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/support/contacting-github-support/creating-a-support-ticket

### What part(s) of the article would you like to see updated?

1. Navigate to the [GitHub Support portal](https://support.github.com/).
2. In the bottom-left corner of the page, click Contact us.
3. Select the Select personal account, enterprise account or organization dropdown menu and click the name of the account your support ticket is regarding.

### Additional information

After 2, there is nothing that resembles the instructions for 3:
<img width="1141" alt="image" src="https://github.com/github/docs/assets/2119212/46925f7a-8273-4d1f-9127-c7d8004a8373">

If you click:
<img width="294" alt="image" src="https://github.com/github/docs/assets/2119212/0db90f67-cec1-40ee-821b-114d47afce04">

Then that stuff is available.

**Comment by steveward** [comment]
Thanks for the issue @jsoref, I'll get this triaged for review! ⚡

**Comment by am-stead** [comment]
hi @jsoref, 
I'm checking internally about the expected behaviour and will update shortly ✨

**Comment by myarb** [comment]
Cross-linking that this was also raised in https://github.com/github/docs/issues/30337, though with the Report a Bug option not available.

**Comment by am-stead** [comment]
Closing this in favour of the internal issue I have opened to track the docs updates.
