### ISSUE TITLE
Viewing and updating support tickets instructions are wrong

### ISSUE THREAD

**Issue by jsoref** [github/docs#30285]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/support/contacting-github-support/viewing-and-updating-support-ticketsX{

### What part(s) of the article would you like to see updated?

[Viewing your recent support tickets](https://docs.github.com/en/support/contacting-github-support/viewing-and-updating-support-tickets#viewing-your-recent-support-tickets)

1. Navigate to the [GitHub Support Portal](https://support.github.com/).
2. In the header, click My Tickets.
3. Optionally, to view tickets associated with an organization or enterprise account, select the My Tickets drop-down menu and click the name of the organization or enterprise account.

I'm a member of multiple organizations. There is no `My Tickets drop-down menu`:

<img width="715" alt="image" src="https://github.com/github/docs/assets/2119212/c674b05e-9866-4c5a-8f5e-d3937e52917d">

**Comment by am-stead** [comment]
Hi @jsoref, 
I checked this one internally as I couldn't recreate this. The feedback was that it's possibly a bug with your user account. If you are a member of multiple organizations, you should be able to see them. I opened a issue internally with the relevant team to report this, but perhaps you want to report it too, so you can track remediation? 
I hope that helps. I will close out this docs issue, as the docs are correct based on expected behaviour. ✨

**Comment by jsoref** [comment]
@am-stead: I had a coworker (in my organization) file a ticket and he doesn't see it either.

You can see from https://github.com/jsoref that I'm in a number of organizations:
<img width="312" alt="image" src="https://github.com/github/docs/assets/2119212/fd7bfce3-1a80-44bd-9a37-444b1dc27dab">

I'm not an owner of any enterprises, but I'm even in at least one enterprise org (and can file tickets via it, I think I even tried once to see if it'd improve my response time -- it didn't).

Can you provide a screenshot showing what you see? (feel free to censor as necessary)

**Comment by jsoref** [comment]
For my records, I filed https://support.github.com/ticket/personal/0/2467486

**Comment by jsoref** [comment]
For the record, here's what support wrote back:
> Taking a look I do see that our documentation is very confusing and we will be performing a rewrite of that documentation to resolve that.
 
> The organization popdown will only appear when two conditions are met; you must be a member of an enterprise and have the enterprise support entitlement, and you must have already filed a ticket using the enterprise support entitlement.
 
> We'll be tracking the progress of the rewrite of the referenced documentation and will let you know when this has been completed.

n.b. they archived the ticket, so I don't believe they'll actually let me know when the documentation is updated.

**Comment by am-stead** [comment]
👋 @jsoref, 

Thanks for your contributions to this! 🙏
I'll make a note to update this issue once the changes are shipped.

**Comment by am-stead** [comment]
👋 @jsoref, 
Just a note to say that we've amended the documentation on this for Free, Pro, & Team users. 
Thanks again for originally raising this. 🙏

**Comment by jsoref** [comment]
https://docs.github.com/en/enterprise-cloud@latest/support/contacting-github-support/viewing-and-updating-support-tickets#viewing-your-recent-support-tickets

> Note: You must have an enterprise support entitlement to view tickets associated with an organization or enterprise account. For more information, see "[Managing support entitlements for your enterprise](https://docs.github.com/en/enterprise-cloud@latest/admin/user-management/managing-users-in-your-enterprise/managing-support-entitlements-for-your-enterprise)."

I think I kinda understand what it's trying to say. But, I'm pretty sure I've _technically_ created unentitled tickets that were _associated_ with an organization -- maybe there's a distinction between a ticket associated with an organization and a ticket associated with an organization account -- but if there is, that's pretty confusing and probably needs more words.

Consider:
> [Job stuck in pending](https://support.github.com/ticket/personal/0/2522393)
> #2522393 closed created 3 weeks ago for check-spelling-sandbox updated 2 weeks ago

Surely that ticket is `associated with an organization`, no?

**Comment by am-stead** [comment]
Thanks @jsoref, is the organization linked to an enterprise account in this case?

**Comment by jsoref** [comment]
Nope.

I did at one point file one or two tickets that were and the same general experience applied. (The key being that while the org was enterprise linked -- github.com/apache, it had standard support.)

<img width="401" alt="image" src="https://github.com/github/docs/assets/2119212/8cf9d497-0ce2-4240-b5d1-3c79b173c0e6">

But the point is that more words need to be spilled to accurately convey the intent.

I guess some questions are in order:
1. Say I'm a member of JQEnterprise and I have a JQOrg which is part of the enterprise
2. The enterprise pays for a support entitlement and assigns it to me.
3. I file a ticket in JQOrg
4. A peer of mine, also a member of JQOrg, but without an entitlement files a ticket in JQOrg
5. Presumably I can see my ticket.
6. Can I see their ticket? (maybe?)
7. Can they see my ticket? (probably not?)
8. The enterprise removes my support entitlement (but retains the support contract)
9. Can I see the ticket I filed? (presumably?)
10. Can I see the ticket my peer filed (presumably not?)
11. Can my peer see my ticket? (presumably not?)
12. The enterprise assigns the support entitlement to my peer
13. Can my peer see my ticket? (maybe?)

My guess is that the support entitlement lets me see tickets filed by others in my enterprise support enabled organization. But I have no idea, and don't know of an enterprise with a support entitlement that's willing to let me play with this feature.

**Comment by am-stead** [comment]
👋 @jsoref, I'll dig for more information.
