### ISSUE TITLE
extend doc about reusable workflows containing several jobs

### ISSUE THREAD

**Issue by SimonHeimberg** [github/docs#30296]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow

### What part(s) of the article would you like to see updated?

reusable workflows seem to support containing several jobs (mentioned at the start)
please extend documentation
- ~that this is not possible (in limitations, except if it is)~
- [ ] Add example code for a job depending on a workflow containing several jobs.
- ~how to depend on the result of one job which in inside of the reusable workflow
      (maybe with job name: calling-job-name/reusalable-job-name)~ Directly depending on an "inner" job is not possible, job outputs can be used instead
- [ ] Please explain how the results of "inner" jobs influence the result of the calling job. (any fails -> fail, most pass but some skipped -> pass, all skipped ->?s?p ) , failure probably depends on [jobs.<job_id>.continue-on-error](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error)
- [ ] Mention "branch protection rules" (or rulesets) can only depend on "leave" jobs. (Not the caller job.)

### Additional information

I tried out to have several jobs in a reusable workflow in a test repo https://github.com/SimonHeimberg/temp_test_github_merge/actions/runs/7065558500/job/19235804814

Looks like my test is somehow wrong. How it is displayed indicates that this is supported, as the documentation. ~But after hours I still wait for the jobs to be picked up by a runner. So running seems to be NOT be supported.~ But I did not get any result because I used a wrong runner name. :see_no_evil:

**Comment by SimonHeimberg** [comment]
I was wrong, the doc shows at top that multiple jobs can be included. I suggest to show this as well in a *code example*.

**Comment by SiaraMist** [comment]
Hey @SimonHeimberg, thank you so much for opening this issue! ✨ 

I really like your idea -- I actually already have an internal issue open to add more code examples relating to reusable workflows. To address this, I'm going to link the issue you opened to the one I have open internally and close out this one. As soon as our team has time, we will work on adding more examples to the docs. Thank you again!
