### ISSUE TITLE
Regarding presentation of the docs

### ISSUE THREAD

**Issue by Jassi10000** [github/docs#3032]
### What is the current behavior?

I was reading this documentation

![github1](https://user-images.githubusercontent.com/64856348/105200120-810efe00-5b65-11eb-8469-3fc0819e1a5b.PNG)

And came across this , in the second line I see a      "  4.   "  written , so this puts me to confusion that are these all organised in points and if yes then I can't see the  " 1. "  , " 2. " or  " 3. " or even after  " 4. "

### What changes are you suggesting?

I would like to suggest to plss present this information in form of points as it would be easier for those who are new to Github or don't have a good habit of reading documentation , I think this documentation in the form of points would look more presentable and understandable

### Additional information

NO

**Comment by ajs256** [comment]
If you're reading on GitHub.com, then that's expected, since its Markdown processor doesn't know about reusables. If you're reading on docs.github.com, then that should not be happening.

**Comment by janiceilene** [comment]
@Jassi10000 The file in this repo https://github.com/github/docs/blob/main/content/packages/guides/configuring-npm-for-use-with-github-packages.md#installing-a-package is the source that's rendered on docs.github.com

If that's the right file ☝️  then this is the corresponding article for the screenshot you listed above https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#installing-a-package, which appears to have correctly numbered steps 😄

**Comment by Jassi10000** [comment]
Ohh!!  , Thanks guys 😄 @ajs256  and @janiceilene for providing me a presentable link

**Comment by janiceilene** [comment]
🎉 You're welcome! I'm going to close this out now 🎉
