### ISSUE TITLE
Help our team improve GitHub Docs!

### ISSUE THREAD

**Issue by janiceilene** [github/docs#3035]
Hello from the GitHub Docs team!

We’re looking to learn more about your experience with [GitHub Docs](https://docs.github.com/en) and will be holding feedback sessions next week, January 25-27. These will be one-hour interview sessions, and we'll provide you with a gratuity as a thank you for your time!

Qualifications:
* Must be a GitHub user (beginners are welcome!)
* Must have used [GitHub Docs](https://docs.github.com/en) in the past two weeks

To participate, fill out our quick survey [here](https://www.surveymonkey.com/r/8M3GSJB). We’ll reach out if you’re a fit for the study. Thank you!

**Comment by lokera07** [comment]
Gracias por este gran trabajo

**Comment by lokera07** [comment]
Ayúdame a canjear mis bitcoin que gane por favor

**Comment by NEEHITGOYAL** [comment]
will you send a mail for timings

**Comment by browncloud69** [comment]
Yes

**Comment by NEEHITGOYAL** [comment]
I have entered my GitHub I'd as 44130067 is it okk or I have to enter username

**Comment by Ruth-ikegah** [comment]
Hi, @janiceilene is this still open? I just saw this. I am filling the survey right now though

**Comment by NEEHITGOYAL** [comment]
@janiceilene  is it closed ??i have filled this form on 23rd there is no mail regarding timing

**Comment by janiceilene** [comment]
Thank you so much to everyone who filled out the survey! We've filled our interview slots, but will reach out to those who have filled out the survey if we need more participants 💖

**Comment by unnitd** [comment]
Xin lỗi các bạn.mình nghe thấy các bạn rồi.mắt của mình kém không thể nhìn thẳng vào màn hình hiển thị.mình sử dụng các biện pháp đọc màn hình hiển thị sáu đó chuyển sang ngôn ngữ địa phương mới hiểu được những gì mà các bạn bình luận.mình sẽ cố gắng giáo tiếp trực tuyến với các bạn.sẽ không lâu nữa đâu.
