### ISSUE TITLE
Typos in log file names in self-hosted runner docs

### ISSUE THREAD

**Issue by pyrtsa** [github/docs#30366]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/monitoring-and-troubleshooting-self-hosted-runners

### What changes are you suggesting?

The log filenames are prefixed `Runner_` and `Worker_`, not `_Runner__` and `_Worker__`. The style guide also suggests using code markup for these.

**Comment by myarb** [comment]
@pyrtsa Thank you for opening an issue and linking it to your PR! I'll get the PR triaged to our review board so someone from the team can take a look! ✨
