### ISSUE TITLE
Fix Zh-CN Translation content typo

### ISSUE THREAD

**Issue by HackettYu** [github/docs#3039]
### What article on docs.github.com is affected?

- [metadata-syntax-for-github-actions.md](https://github.com/github/docs/blob/bb41ce4f19a60ebf27d1a96287a21bffbcd3ab90/translations/zh-CN/content/actions/creating-actions/metadata-syntax-for-github-actions.md)
- [command-line-utilities.md](https://github.com/github/docs/blob/bb41ce4f19a60ebf27d1a96287a21bffbcd3ab90/translations/zh-CN/content/admin/configuration/command-line-utilities.md)
- [workflow-syntax-for-github-actions](https://docs.github.com/cn/actions/reference/workflow-syntax-for-github-actions)

### What part(s) of the article would you like to see updated?

- [Query: 开关](https://github.com/github/docs/search?q=%E5%BC%80%E5%85%B3)

```diff
# (https://github.com/github/docs/blob/bb41ce4f19a60ebf27d1a96287a21bffbcd3ab90/translations/zh-CN/content/actions/creating-actions/metadata-syntax-for-github-actions.md 开关->开头
- **必要** 要与输入关联的 `string` 识别符。 `<input_id>` 的值是输入元数据的映射。 `<input_id>` 必须是 `inputs` 对象中的唯一识别符。 `<input_id>` 必须以字母或 `_` 开关，并且只能包含字母数字、`-` 或 `_`。
+ **必要** 要与输入关联的 `string` 识别符。 `<input_id>` 的值是输入元数据的映射。 `<input_id>` 必须是 `inputs` 对象中的唯一识别符。 `<input_id>` 必须以字母或 `_` 开头，并且只能包含字母数字、`-` 或 `_`。

# https://github.com/github/docs/blob/bb41ce4f19a60ebf27d1a96287a21bffbcd3ab90/translations/zh-CN/content/admin/configuration/command-line-utilities.md 开关->开头
- 要回滚补丁版本，请使用带 `--allow-patch-rollback` 开关的 `ghe-upgrade` 命令。 {% data reusables.enterprise_installation.command-line-utilities-ghe-upgrade-rollback %}
+ 要回滚补丁版本，请使用带 `--allow-patch-rollback` 开头的 `ghe-upgrade` 命令。 {% data reusables.enterprise_installation.command-line-utilities-ghe-upgrade-rollback %}

# https://docs.github.com/cn/actions/reference/workflow-syntax-for-github-actions ApI->API
- 如果需要查找在工作流程运行中运行的作业的唯一标识符，可以使用 GitHub ApI。 更多信息请参阅“工作流程作业”。
+ 如果需要查找在工作流程运行中运行的作业的唯一标识符，可以使用 GitHub API。 更多信息请参阅“工作流程作业”。
```

### Additional information

- [X] [earth_asia-translations](https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations)

**Comment by janiceilene** [comment]
Thanks for opening this issue! Unfortunately, we are not able to create pull requests for translated content in this repo. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

I'll let the team know about this typo and close this out 💛
