### ISSUE TITLE
Adding screenshot of checkbox in "Allowing changes to a pull request branch created from a fork"

### ISSUE THREAD

**Issue by jakirkham** [github/docs#30407]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork.md

### What part(s) of the article would you like to see updated?

It would be nice to have a screenshot of where the checkbox is so readers know where to find it and check it (especially if they haven't noticed it before)

**Comment by sabrowning1** [comment]
👋🏼 @jakirkham, thanks so much for raising this issue! ✨ A screenshot here sounds great; you or anyone else is welcome to create a PR adding that in. For guidelines on taking and using screenshots in our docs, see "[Creating screenshots](https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots)".

**Comment by CBID2** [comment]
> 👋🏼 @jakirkham, thanks so much for raising this issue! ✨ A screenshot here sounds great; you or anyone else is welcome to create a PR adding one in. For guidelines on screenshots in our docs, see "[Creating screenshots](https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots)."

Hi @sabrowning1! :) I made a PR to solve this issue. It's #30597.
