### ISSUE TITLE
Broken link to "Code of Conduct" in this issue template

### ISSUE THREAD

**Issue by jakirkham** [github/docs#30408]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This is actually an issue with this repo itself. Namely the issue template

https://github.com/github/docs/blob/149305706491a30b8dfab194393f5ff0d43d1a9c/.github/ISSUE_TEMPLATE/improve-existing-docs.yaml

### What part(s) of the article would you like to see updated?

The [Code of Conduct link on this line of the issue template]( https://github.com/github/docs/blob/149305706491a30b8dfab194393f5ff0d43d1a9c/.github/ISSUE_TEMPLATE/improve-existing-docs.yaml?plain=1#L21 ) points to a file that does not exist. So one gets a 404 when clicking it

<img width="1840" alt="Screenshot 2023-12-06 at 4 27 02 PM" src="https://github.com/github/docs/assets/3019665/70322d2e-f1b3-43ca-b321-60f34054604a">

Think we want to update it to [`.github/CODE_OF_CONDUCT.md`]( https://github.com/github/docs/blob/149305706491a30b8dfab194393f5ff0d43d1a9c/.github/CODE_OF_CONDUCT.md )

**Comment by nguyenalex836** [comment]
@jakirkham Thank you for diligence in finding that broken link! You are correct - the correct link in the [issue template](https://github.com/github/docs/blob/main/.github/ISSUE_TEMPLATE/improve-existing-docs.yaml) should be https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md 💛 

Feel free to open a PR to make this update, and link the PR to this issue! ✨

**Comment by mark-mxwl** [comment]
Thx for raising this issue @jakirkham, and for providing the correct link @nguyenalex836! I've fixed the link and have created a PR #30442.
