### ISSUE TITLE
Github docs search button does not work

### ISSUE THREAD

**Issue by SoltauFintel** [github/docs#30435]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en search field

### What changes are you suggesting?

fix it

### Additional information

https://docs.github.com/en

If you enter something in the search field and press enter it works. But if you press the search button nothing happens.

Win11, Chrome browser 119

**Comment by nguyenalex836** [comment]
Thank you for your diligence in finding the broken search button! ✨ Our engineering team will be reviewing this issue. In the meantime, if you have any suggestions for this particular bug, you are welcome to open your own PR and link to this issue 💛

**Comment by gracepark** [comment]
Hi all. Thank you for the report. This has now been resolved. If you find that it is not the case, it's most likely due to caching. It should eventually update.

**Comment by nguyenalex836** [comment]
Confirming the search button on https://docs.github.com/en is now working on my end - thanks for the fix, @gracepark ✨ 

Thank you again @SoltauFintel for reporting this bug and improving GitHub Docs! 💛
