### ISSUE TITLE
Missing `)` leads to broken / incomplete link

### ISSUE THREAD

**Issue by mauricewbr** [github/docs#30471]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api

### What part(s) of the article would you like to see updated?

HTTP method section, following sentence:
```
For example, the HTTP method for the ["List repository issues" endpoint]([Issues](https://docs.github.com/en/rest/issues/issues#list-repository-issues) is GET."
```

**Comment by nguyenalex836** [comment]
@mauricewbr Thank you for opening a PR and linking it to your issue! ✨

**Comment by nguyenalex836** [comment]
@mauricewbr Thanks so much for opening a PR! I'll get this triaged for review ✨
