### ISSUE TITLE
Improve GitHub Actions concurrency documentations

### ISSUE THREAD

**Issue by rvesse** [github/docs#30645]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-jobs/using-concurrency

### What part(s) of the article would you like to see updated?

There are a couple of common confusions that seem to arise from this piece of the documentation:

1. Whether `cancel-in-progress` allows expressions (yes it does)
2. That even with `cancel-in-progress: false` (or an expression that evaluates to `false`) pending jobs can still be cancelled as concurrency groups are limited to 1 running and 1 pending job

E.g. see

- https://github.com/orgs/community/discussions/69704
- https://github.com/orgs/community/discussions/49963

**Comment by nguyenalex836** [comment]
@rvesse Thanks for opening an issue! I’ll get this triaged for review ✨

**Comment by erfan125** [comment]
hello.go

**Comment by kartkbhalodiya** [comment]
love my self
