### ISSUE TITLE
Zambia is'nt included for 2FA

### ISSUE THREAD

**Issue by TamaniPhiri** [github/docs#30668]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

No article but am concerned as a senior developer in zambia having no 2FA, we will be disabled from account actions just because sms is not available in zambia, please look into that and consider us zambian developers who rely on github for source control, please

### What part(s) of the article would you like to see updated?

we need to be considered as zambian developers please

### Additional information

we need to be considered as zambian developers please

**Comment by ayatweb** [comment]
I’m from Morocco 🇲🇦
