### ISSUE TITLE
https://youtube.com/@user-np1ev4pu5g?si=3laj1rtBq2UNY70R

### ISSUE THREAD

**Issue by jmalmhmwdj64** [github/docs#30696]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://youtube.com/@user-np1ev4pu5g?si=3laj1rtBq2UNY70R

### What part(s) of the article would you like to see updated?

https://youtube.com/@user-np1ev4pu5g?si=3laj1rtBq2UNY70R

### Additional information

https://youtube.com/@user-np1ev4pu5g?si=3laj1rtBq2UNY70R

**Comment by ThuyaSan** [comment]
12102001san

Thuyasan2001
