### ISSUE TITLE
Fix Python CodeQL queries page's query table

### ISSUE THREAD

**Issue by Elkiwa** [github/docs#30701]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Code security/Code Scanning/Manage code scanning/Python queries for CodeQL analysis](https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/python-built-in-queries)

### What part(s) of the article would you like to see updated?

The [Built-in queries for Python analysis](https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/python-built-in-queries#built-in-queries-for-python-analysis) section lists the C and C++ queries instead

**Comment by 0968927272** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> [Code security/Code Scanning/Manage code scanning/Python queries for CodeQL analysis](https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/python-built-in-queries)
> 
> ### What part(s) of the article would you like to see updated?
> The [Built-in queries for Python analysis](https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/python-built-in-queries#built-in-queries-for-python-analysis) section lists the C and C++ queries instead
> 
> ### Additional information
> _No response_
