### ISSUE TITLE
Update Actions `Creating a composite run steps action` for windows users

### ISSUE THREAD

**Issue by raiden-e** [github/docs#3072]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action#prerequisites

As a windows user, i found it confusing to apply `chmod` and stumbled over a permission denied error, when I tried to run anyways. For windows users, the solution is to tell git this way:
>git update-index --chmod=+x ./goodbye.sh

---
[maintainer edit]
### Content plan

1. The "[Prerequisites](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action#prerequisites)" step 4 could be replaced by echo "echo Goodbye" > goodbye.sh

2. To make the file executable from windows, it looks like the preference is to use git add --chmod=+x -- goodbye.sh. It might be clearer if we create a separate tab for the Windows instructions, similar to approach taken here: https://docs.github.com/en/actions/hosting-your-own-runners/monitoring-and-troubleshooting-self-hosted-runners. See [Operating system tags](https://github.com/github/docs/blob/main/contributing/content-markup-reference.md#operating-system-tags) for more information. 

For more information, see the comments in the closed PR here - (https://github.com/github/docs/pull/3073#issuecomment-811635797)

**Comment by LaCalin08** [comment]
connecting-to-github-with-ssh.md 

[GTA.is](https://one.apple.com/us/?itscg=10000&itsct=one-NA-local_nv-lp-apl-avl-102020) title	intro	redirect_from	mapTopic	versions
Connecting to GitHub with SSH
You can connect to {% data variables.product.product_name %} using SSH.---
title: Connecting to GitHub with SSH
intro: 'You can connect to {% data variables.product.product_name %} using SSH.'
redirect_from:
  - /key-setup-redirect/
  - /linux-key-setup/
  - /mac-key-setup/
  - /msysgit-key-setup/
  - /articles/ssh-key-setup/
  - /articles/generating-ssh-keys/
  - /articles/generating-an-ssh-key/
  - /articles/connecting-to-github-with-ssh
mapTopic: true
versions:
  free-pro-team: '*'
  enterprise-server: '*'
  github-ae: '*'
---

**Comment by ramyaparimi** [comment]
[This comment](https://github.com/github/docs/pull/3073#issuecomment-811635797) has some additional information for anyone who is interested in opening a PR ✨
