### ISSUE TITLE
[UI Issue] : Guides are not center aligned on Mobile View

### ISSUE THREAD

**Issue by TartejBrothers** [github/docs#30757]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- I am using Google Chrome. 
- It is on the [Get Started Page](https://docs.github.com/en/get-started)
<img width="391" alt="image" src="https://github.com/github/docs/assets/112921727/23b6b48a-7863-4352-9377-64880e90922c">

- The Guide Section is not center aligned in Mobile View.

### What changes are you suggesting?

The section should be center aligned.
It just works as a better UI element.

**Comment by nguyenalex836** [comment]
@TartejBrothers Thanks so much for opening this issue! ✨ You, or anyone else, are welcome to submit a PR with this fix. 💛

**Comment by adsingh14** [comment]
I will look into it.

**Comment by adsingh14** [comment]
@nguyenalex836 I fix the issue but unable to test it locally. Can you please respond to [this discussion](https://github.com/github/docs/discussions/30787)?

**Comment by adsingh14** [comment]
@TartejBrothers If you open that page on bigger screen, you'll get it that they don't want to block the card element text under 'Scroll to top' button.

This is what happens after you see it **center aligned**. Check the scroll to top (blue color) button blocking the text.
![image](https://github.com/github/docs/assets/35252877/32e6c50b-5443-4638-b206-dcec12df3cea)

**Comment by nguyenalex836** [comment]
Hi @adsingh14! Regarding that discussion you linked, your question best be handled by our [support team](https://support.github.com/request). Please reach out to them for assistance 💛

**Comment by adsingh14** [comment]
@nguyenalex836 Please read my reply regarding this issue in my previous reply.

**Comment by TartejBrothers** [comment]
@adsingh14 If thats the case then ok, but there are other places where this thing is not followed. 
Example : 
![image](https://github.com/github/docs/assets/112921727/b6931545-ee2c-45d5-8b35-7115b9da644c)

**Comment by nguyenalex836** [comment]
Thanks, @adsingh14! As I noted above and in the discussion you linked, your question regarding being unable to test this locally would best be handled by our [support team](https://support.github.com/request). Please reach out to them for assistance 💛

**Comment by adsingh14** [comment]
@nguyenalex836 My question was also regarding the a11y, please check the images I shared. I was asking about it.

**Comment by adsingh14** [comment]
@nguyenalex836 My question was also regarding the a11y, please check the replied images above.

**Comment by nguyenalex836** [comment]
Thanks, @adsingh14! You are welcome to submit a PR with what you have, even if those changes will not look good in terms of a11y. If you add a note with your PR highlighting the issues you ran into related to a11y, our team can provide input on the best next steps 💛

**Comment by adsingh14** [comment]
@nguyenalex836 Please check out this PR. I hope the referenced issue will clarify the whole context in brief.
