### ISSUE TITLE
Leading ~ character (and maybe others?) cause a 404 error with GH pages

### ISSUE THREAD

**Issue by ghfields** [github/docs#30779]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/pages/getting-started-with-github-pages/troubleshooting-404-errors-for-github-pages-sites.md

### What part(s) of the article would you like to see updated?

An additional cause of a 404 is a directory or filename starting with the `~` character (I tested that `~` in the middle and end of filenames are acceptable).  I am unsure what other characters would cause this to occur, but would be helpful if a complete acceptable naming guideline section was added to this document.

**Comment by nguyenalex836** [comment]
@ghfields Thanks for opening this issue! I’ll get this triaged for review ✨

**Comment by ghfields** [comment]
Thanks.  Honestly, I'd be happy if those were valid, since I have a use case for that, but if not, documenting the limitation is the next best thing.

**Comment by sophietheking** [comment]
@ghfields 👋 Thanks for opening this issue! I checked internally whether it should be possible to use the `~` character at the start of a directory or field name with GitHub Pages, and it should work. Based on my colleague's testing, they suspect Jekyll is the issue. Anytime there is something odd with a file name Jekyll is the usual suspect (you cannot have a file name starting with `_` with Jekyll for example).

If you continue having difficulty, please reach out to GitHub Support. We really appreciate you contributing to the community. 🎇

**Comment by ghfields** [comment]
I appreciate the feedback. I am assuming your colleague confirmed the issue.  I believe you are also saying since it is a bug, it won't be documented in the github docs hopes Jekyll is is fixed and will leave the concern undocumented in the meantime.  As I don't see any references in this issue, I assume there has not been a Jekyll issue opened.  I will do so now.
