### ISSUE TITLE
Fix typo in Linux path - Generating SSH key

### ISSUE THREAD

**Issue by Martin005** [github/docs#30774]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux)

### What part(s) of the article would you like to see updated?

The Linux path, in the [Generating a new SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux#generating-a-new-ssh-key) section, states that you can write the newly generated SSH key to a specific location by the following:
`> Enter a file in which to save the key (/home/YOU/.ssh/ALGORITHM):[Press enter]`

The issue is that there is only `ALGORITHM`, but it should read `id_ALGORITHM` as the description above states. This is also the case for Mac and Windows paths, but Linux one has this typo.

**Comment by Fajar1901** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> [Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux)
> 
> ### What part(s) of the article would you like to see updated?
> The Linux path, in the [Generating a new SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux#generating-a-new-ssh-key) section, states that you can write the newly generated SSH key to a specific location by the following: `> Enter a file in which to save the key (/home/YOU/.ssh/ALGORITHM):[Press enter]`
> 
> The issue is that there is only `ALGORITHM`, but it should read `id_ALGORITHM` as the description above states. This is also the case for Mac and Windows paths, but Linux one has this typo.
> 
> ### Additional information
> _No response_

curl https://api.gitbook.com/v1/
{"version":"10.9.128","build":"2022-07-19T13:00:05.548Z"}

**Comment by nguyenalex836** [comment]
@Martin005 Sending this retroactively - thanks for opening this issue and linking to your PR! ✨
