### ISSUE TITLE
Improve flow for REST issues

### ISSUE THREAD

**Issue by jsoref** [github/docs#30782]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/issues/new?assignees=&labels=content&projects=&template=improve-existing-docs.yaml

### What changes are you suggesting?

There should be text that explains when people should visit https://github.com/github/rest-api-description and use https://github.com/github/rest-api-description/issues/new/choose

### Additional information

I've filed quite a few tickets to docs, and i understand that REST isn't handled there, but i have not learned, and it isn't remotely obvious from https://github.com/github/docs/issues/new?assignees=&labels=content&projects=&template=improve-existing-docs.yaml where one should go to file them.

(I apparently have directly filed one ticket there -- fixed -- and indirectly filed two tickets there -- neither has been fixed yet although one was moved today...)

Fwiw, I'm not actually sure if I'd have chosen to file my most recent ticket there based on the current workflow: https://github.com/github/rest-api-description/issues/new?assignees=&labels=Inaccuracy&projects=&template=schema-inaccuracy.md&title=%5BSchema+Inaccuracy%5D+%3CDescribe+Problem%3E as it isn't so much that the schema is wrong, as the example responses look wrong -- and I doubt that those responses are part of the schema.

**Comment by nguyenalex836** [comment]
@jsoref Thank you for raising this issue, and providing feedback on this topic ✨ 'll get this triaged for review 💛

**Comment by nguyenalex836** [comment]
@jsoref Hello! Here's a response from our team -

While REST issues do need to be fixed internally, either opening an issue in [docs](https://github.com/github/docs) or in [rest-api-description](https://github.com/github/rest-api-description) will get the info to the right place.

- The `rest-schema` label is used to transfer issues opened in [docs](https://github.com/github/docs) to [rest-api-description](https://github.com/github/rest-api-description) when needed.

- Conversely, if an issue is opened in [rest-api-description](https://github.com/github/rest-api-description) and the API team thinks that the Docs team can best solve for the issue, the API team will add the appropriate documentation label to copy the issue to Docs. 

We are discussing internally how to alleviate some of the confusion this process may cause, and appreciate you raising this topic ✨
