### ISSUE TITLE
Is GHAS trial available only for _enterprise accounts_?

### ISSUE THREAD

**Issue by solvaholic** [github/docs#30838]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/billing/managing-billing-for-github-advanced-security/setting-up-a-trial-of-github-advanced-security

### What part(s) of the article would you like to see updated?

This doc currently mentions "enterprise account" without disambiguation.

As a user who's a member of a GitHub Enterprise Cloud org, I think my user account is an enterprise account. And I think the GHEC org I'm a member of is also an enterprise account. And I'm aware that GitHub also offers a separate thing explicitly called an [_enterprise account_](https://docs.github.com/en/enterprise-cloud@latest/admin/overview/about-enterprise-accounts).

An owner of a GHEC org may arrive at this page thinking their org is an enterprise account, and find that they can't follow the instructions. Their apparent options, at that point, will be to contact Sales, contact Support, or stop trying to buy GitHub Advanced Security.

If GHAS is available only for [_enterprise accounts_](https://docs.github.com/en/enterprise-cloud@latest/admin/overview/about-enterprise-accounts), please make that clear in the docs and suggest how a user without an _enterprise account_ should proceed.

### Additional information

The problem I'm hoping to address is confusion resulting from ambiguous product name choices. This would affect any GHEC customer who wishes to try GHAS in their GHEC org and is unaware that their enterprise accounts are not [_enterprise accounts_](https://docs.github.com/en/enterprise-cloud@latest/admin/overview/about-enterprise-accounts).

**Comment by nguyenalex836** [comment]
Thanks for the opening this issue, @solvaholic! I'll get this triaged for review ✨

**Comment by am-stead** [comment]
Hi @solvaholic, docs team first responder here 👋

This looks like an improvement request. Please open an issue in the `github/docs-content` repo, using the 'improve existing docs' template, so we can plan and track the work. Thank you!
