### ISSUE TITLE
GitHub REST API documentation Overview Button goes to a broken/dead link

### ISSUE THREAD

**Issue by frankpengau** [github/docs#30836]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

GitHub REST API index.md has an "Overview" button that is linked to `https://docs.github.com/en/rest/overview/about-the-rest-api` which is a dead link.

### What changes are you suggesting?

Change it to the equivalent page after the refactor, which seems to be: `https://docs.github.com/en/rest/about-the-rest-api/about-the-rest-api`

**Comment by pritz35** [comment]
.github/workflows/test-changed-content.yml

**Comment by pritz35** [comment]
.github/workflows/test-changed-content.yml
