### ISSUE TITLE
Wrong variable value {% data variables.copilot.cfi_price_per_year %} for french version of Copilot individual overview page

### ISSUE THREAD

**Issue by Ptitet** [github/docs#30865]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/fr/copilot/overview-of-github-copilot/about-github-copilot-individual#understanding-the-differences-between-copilot-individual-and-copilot-business

### What part(s) of the article would you like to see updated?

The part of the article that is incorrect is the yearly pricing for Copilot Individual in the first line of the table, but only for the french version of the page. All the others versions (English, German, ...) are displaying the correct price.

In the french version of the article, as shown on the screenshot below, it is written that the yearly price for Copilot individual is _10 USD_ :
![image](https://github.com/github/docs/assets/95184938/2a746f8d-5d2d-4f5b-bb07-fa2abd01933f)

On all other versions of the page, the price is correct :
![image](https://github.com/github/docs/assets/95184938/f9fa503d-c1c0-42cd-961f-a9bafc7ccc74)

**Comment by nguyenalex836** [comment]
Thanks for reaching out! We will flag this request for our team. ✨ 

For additional information on translations, see [this page](https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations). I will go ahead and close out this issue. 💛

**Comment by nguyenalex836** [comment]
This has been fixed ✅
