### ISSUE TITLE
Typos for Hyperlinks

### ISSUE THREAD

**Issue by VinayR-GitHub** [github/docs#30876]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-to-azure-kubernetes-service

### What part(s) of the article would you like to see updated?

Incorrect hyperlink appearance.

### Additional information

![image](https://github.com/github/docs/assets/153238516/a5d7e8b2-ce24-4211-9b6c-913cbdeedad3)

**Comment by nguyenalex836** [comment]
@VinayR-GitHub Hello! 👋 It looks like you closed the PR linked to this issue by deleting the head repository. I'll go ahead and close this issue as well 💛
