### ISSUE TITLE
.github/workflows/sync-search-pr.yml doesn't work for PRs from forks

### ISSUE THREAD

**Issue by jsoref** [github/docs#30896]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

`.github/workflows/sync-search-pr.yml`

### What changes are you suggesting?

There are a couple of options, none are particularly great.

1. Change this workflow so that it doesn't run if it can't access the secret (possibly adding an extra thing that includes a warning explaining that this workflow was skipped and flagging the PR so that an internal makes their own check...)
2. Change this workflow so that it uses pull_request_target and lots of carefully reviewed code when it is triggered for a PR from a fork.

Offhand, I think the first option is slightly better.

### Additional information

https://github.com/github/docs/actions/runs/7388726590/job/20100113239?pr=30895#step:3:1
```
Run actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
  with:
    repository: github/docs-internal.popular-pages
    path: popular-pages
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    show-progress: true
    lfs: false
    submodules: false
    set-safe-directory: true
  env:
    ELASTICSEARCH_URL: http://localhost:9200
    HYDRO_ENDPOINT: 
    HYDRO_SECRET: 
Error: Input required and not supplied: token
```

**Comment by jsoref** [comment]
Note that the file itself isn't allowed to be changed by non hubbers which seems to support not running it for non hubbers:  https://github.com/github/docs/pull/30895#issuecomment-1874344664

**Comment by nguyenalex836** [comment]
@jsoref Howdy! Our team prefers that contributions and issues are raised only for docs, rather than workflows or other non-docs content. We appreciate your willingness to contribute as always 💛 I'll go ahead and close this issue.

**Comment by jsoref** [comment]
@nguyenalex836: I opened this because the workflow failed in #30895 and it's clear (based on its logic and your message) that it's broken since the goal is for people like me not to trip on workflows like this.

**Comment by nguyenalex836** [comment]
@jsoref We will have the team review this 👍

**Comment by nguyenalex836** [comment]
@jsoref Hello! Our engineering team has reconditioned that workflow to only run internally 💛 I'll go ahead and close this issue - thanks!
