### ISSUE TITLE
Transferring ownership of repositories.

### ISSUE THREAD

**Issue by alanschwarz** [github/docs#30965]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization

### What part(s) of the article would you like to see updated?

It is unclear which prerequisites must be fulfilled in order to transfer a repository out of an organization and into a personal account. It is necessary to explain that the success of the transfer depends on the visibility of the repository.

### Additional information

When you try to transfer a repository from an organization to a personal account - and the repository is INTERNAL, following error message appears:

Internal repositories can only be transferred to an organization in the enterprise.

It is misleading. It does not accurately reflect that the visibility is the problem. A sentence in the docs would have saved me some time.

**Comment by nguyenalex836** [comment]
@alanschwarz Thank you for opening this issue! I've linked this issue to the corresponding [PR](https://github.com/github/docs/pull/30966) 💛
