### ISSUE TITLE
Document how files can be created with a constructed URL

### ISSUE THREAD

**Issue by drok** [github/docs#30967]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/working-with-files/managing-files/creating-new-files

### What part(s) of the article would you like to see updated?

The information contained at https://stackoverflow.com/questions/27778095/github-url-to-create-new-file-with-specific-name should be included in this article.

Or maybe that info exists elsewhere? It should be linked then.

**Comment by nguyenalex836** [comment]
@drok Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by drok** [comment]
Thank you for responding to my issue.

**Comment by supergranular** [comment]
Hello, and thanks for your submission! We think this isn't a wide enough use case for us to document, but are glad you find it useful. We'll close this issue but please reply if you think we've made a mistake.
