### ISSUE TITLE
Substitute arbitrary username examples with built-in system environment variables

### ISSUE THREAD

**Issue by loonaticx** [github/docs#30970]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

### What part(s) of the article would you like to see updated?

The guide provides an arbitrary username when it could instead refer to a built-in system variable that asserts the correct path required.
%USERPROFILE% will point to the current users profile, whereas C:\Users\YOU\ is far less sufficient to use from the end-user trying to read and troubleshoot their issue with the article.

The most prominent example that needs to be changed is [here](https://github.com/github/docs/blob/main/content/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md?plain=1#L181), in which the user would need to make extraneous modifications to the command before running it.
By replacing arbitrary username placeholders with built-in system environment variables as substitutes, it will slightly improve the convenience of the end-user following the instructions in the article. It makes it much faster to troubleshoot problems

**Comment by nguyenalex836** [comment]
@loonaticx Thank you for opening an issue and linking it to your PR! ✨

**Comment by uzairhassan375** [comment]
Dont know how to solve this

**Comment by nguyenalex836** [comment]
Closing this issue - linked PR has been closed for inactivity 💛
