### ISSUE TITLE
Broken quotes around link

### ISSUE THREAD

**Issue by minding-myown-business** [github/docs#30984]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[GitHub Pages/Set up site with Jeykll/About GitHub Pages and Jeykll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll)

### What part(s) of the article would you like to see updated?

The second link of the second paragraph under [the heading "Themes"](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#themes)

### Additional information

The link only shows the second quotation mark, and the quotation mark itself is part of the hyperlink.
![Screenshot 2024-01-08 at 16-09-19 About GitHub Pages and Jekyll - GitHub Docs](https://github.com/github/docs/assets/150592702/4adbb68d-4fff-4038-b0c2-6e90ec6f454a)
I have made a pull request regarding this: #30985

**Comment by nguyenalex836** [comment]
@minding-myown-business Thank you for opening an issue and linking it to your PR! ✨
