### ISSUE TITLE
Unclear wording in "Removing a profile README" section at https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme

### ISSUE THREAD

**Issue by raspberri05** [github/docs#30992]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme

### What part(s) of the article would you like to see updated?

I believe the "Removing a profile README" section at https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme should be reworded to represent that these are instructions are to voluntarily remove a profile README.
For example:

The profile README can be removed from your GitHub profile if any of the following apply:

* The README file is removed or made empty
* The repository is made private
* The repository name no longer matches your username due to a change in either or both names

Alternatively, it could be reworded to serve more as a warning in order to not accidentally remove a profile README.

By making this change, I believe that somebody who sees this part of the documentation will more clearly understand how to remove a profile README or understand how to avoid accidentally removing a profile README.

### Additional information

If this is something that the Github Docs team believes should be changed, I would be more than happy to open a pull request with these changes.

**Comment by nguyenalex836** [comment]
@raspberri05 Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@raspberri05 Thanks so much for opening this issue! 💛 You, or anyone else, are welcome to submit a PR with this fix. ✨

**Comment by raspberri05** [comment]
Great! I've gone ahead and submitted a PR with the fix!
