### ISSUE TITLE
Mention that workflow needs to exist on default branch to use `workflow_dispatch`

### ISSUE THREAD

**Issue by jsoref** [github/docs#31007]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch

### What part(s) of the article would you like to see updated?

Add more text explaining requirements relating to presence on default branch

### Additional information

https://github.com/orgs/community/discussions/25746#discussioncomment-8067852

### Content design plan:

Add a sentence to the `on.worklfow_dispatch` section of [Workflow Syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch) that says something like:

``` copy
This trigger only receives events when the workflow file is on the default branch.
```

**Comment by jsoref** [comment]
Some prose should probably also be added near https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onevent_nametypes explaining which events are handled by the workflow in the default branch and which are handled by other versions of the workflow (which I believe is basically `push`, `pull_request*`, and `workflow_dispatch` if someone with write(?) permissions asks a workflow present on the default branch to run from a non-default branch).

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening this issue, and providing the discussion this stemmed from 💛 I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@jsoref Thanks again for raising this flag on this! ✨ We've discussed with the team, and would appreciate if you could send over some snippets for what you hand in mind regarding - 

> Add more text explaining requirements relating to presence on default branch
> 
> Some prose should probably also be added near https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onevent_nametypes 

CC @SiaraMist @jc-clark

**Comment by jsoref** [comment]
Here's a sample workflow with some runs: https://github.com/jsoref/on.event-name.types/actions/workflows/issue-labeled.yml

I'm not sure how many types this applies to, but at least for on.issue.types, only workflows on the default branch at the time the event is dispatched are consulted.

```diff
-Some events have activity types that give you more control over when your workflow should run.
+Some events have activity types that give you more control over when your workflow should run.
+Generally these events are only dispatched to workflows on the default branch.
```

The reason for this text is that there is a workflow https://github.com/jsoref/on.event-name.types/commit/3bbb2e6484c51908dcd3ee44c7a4258ce55f464c which is on the `main` branch, and it did not run when the `invalid` label was added to https://github.com/jsoref/on.event-name.types/issues/3 -- *because* at the time of that event, the default branch was [`test`](https://github.com/jsoref/on.event-name.types/tree/test) not [`main`](https://github.com/jsoref/on.event-name.types/tree/main).

**Comment by nguyenalex836** [comment]
@jsoref Thanks for sending that over! Going to loop in @SiaraMist and @jc-clark to give this a quick review 💛

**Comment by jsoref** [comment]
For the title item, https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch 
```diff
-When using the workflow_dispatch event, you can optionally specify inputs that are passed to the workflow.
+When using the workflow_dispatch event, you can optionally specify inputs that are passed to the workflow.
+
+This event is only received by workflows on the default branch.
```

It's documented, but not here, where a reader is likely to look for it.

Instead, you have to be in:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

> This event will only trigger a workflow run if the workflow file is on the default branch.

I'm not wed to my text. It's just to point out roughly where I'd expect content and roughly what I think is needed.

**Comment by SiaraMist** [comment]
Thanks for opening this @jsoref! I agree that we should add this information to the Workflow Syntax article as well.

I'd suggest adding a sentence to [this section you linked](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch) that says something like:

``` copy
This trigger only receives events when the workflow file is on the default branch.
```

You or anyone else is welcome to open a PR to add this information.

**Comment by huyz** [comment]
Is it true that the workflow needs to exist on the default branch?

It seems it's possible to trigger the registration of `workflow_dispatch` without touching the default branch. See https://stackoverflow.com/a/71057825/161972 and other answers.

Plus, when I click on the `Run workflow` button, I get to choose the workflow version by ref:
![screenshot 2024-09-02T090017Z@2x](https://github.com/user-attachments/assets/2063bc0f-d6c5-447d-b18f-722b7943e95d)

**Comment by nguyenalex836** [comment]
@huyz Hello! 👋 Your specific question would best be handled by our wonderful [support team](https://support.github.com/request) ✨ Please feel free to reach out to them for assistance!

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue 💛
