### ISSUE TITLE
Incorrect Documentation: Configuring Resharper

### ISSUE THREAD

**Issue by C0derPr0** [github/docs#31013]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/configuring-github-copilot/configuring-github-copilot-in-your-environment

### What part(s) of the article would you like to see updated?

Step 1 under Configuring ReSharper for {% data variables.product.prodname_copilot %} is incorrect. Step 2 and forward are not available from the Visual Studio options menu. What the author intended to say in step 1 was Extensions => Reshaper => Options.

**Comment by nguyenalex836** [comment]
@C0derPr0 Thanks so much for opening this issue! You, or anyone else, are welcome to submit a PR with this fix. ✨

**Comment by MoostafaMagdi** [comment]
Mm
