### ISSUE TITLE
Documentation needed about how to display Account selection page during every OAuth (or what option to use in OAuth request)

### ISSUE THREAD

**Issue by vineeththomasalex** [github/docs#31038]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps.md

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/main/content/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps.md#1-request-a-users-github-identity

Docs do not mention how to force a new login during OAuth. Currently, if LoginId1 is already logged in to the browser, and OAuth is triggered for user1 always. This happens even on repeated OAuth flows. LoginId1 just repeats the authentication step for OAuth flow automatically (and receive a different access token). 

Expected behavior should be that GitHub displays the "account selection" page during every OAuth authentication (or at least provide a way to specify this option as part of the OAuth request). This way, the OAuth will not be auto-assumed to be for Login1(which is the only user logged in to the browser), and the user has the option to login to a different id in this selection page.
Since GitHub now supports multiple accounts [https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/managing-multiple-accounts], there should be an option to trigger OAuth for a new user (not for a specific user by using the "login" field in step 1).

I imagine this is a missing documentation problem, if not, please redirect this issue to the right repository. 
Thanks!

**Comment by nguyenalex836** [comment]
Hello @vineeththomasalex 👋 ! The best place to send this feedback regarding GitHub is to https://github.com/github/feedback/discussions ✨ I'll go ahead and close this issue 💛
