### ISSUE TITLE
transfer discussion should list more of the constraints

### ISSUE THREAD

**Issue by jsoref** [github/docs#31057]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#transferring-a-discussion

### What part(s) of the article would you like to see updated?

The current text says in paragraph form:
> To transfer a discussion, you must have permissions to create discussions in the repository where you want to transfer the discussion.
> If you want to transfer a discussion to an organization, you must have permissions to create discussions in the source repository for the organization's discussions.
> You can only transfer discussions between repositories owned by the same user or organization account.
> You can't transfer a discussion from a private repository to a public repository.

1. It's incomplete
2. It really shouldn't be in paragraph form as it's really hard to determine if something is eligible in this for.

### Additional information

https://github.com/orgs/community/discussions/3381#discussioncomment-2648205
https://github.com/orgs/community/discussions/3381#discussioncomment-2656034

It'd be better if it was written like this:
1. The destination repository must have discussions enabled.
2. The discussion being transferred cannot be an "Announcement format" (with a link to a picture like https://user-images.githubusercontent.com/6379424/165794923-31209021-ba53-490a-8212-7a6815bb0deb.png) or a topic that covers it -- ideally, once https://github.com/github/docs/issues/31056 is resolved, that'd create a good destination for the link.
3. An explanation about transferring discussions to repositories of different [visibility](https://docs.github.com/en/enterprise-cloud@latest/repositories/creating-and-managing-repositories/about-repositories#about-repository-visibility). I don't actually know the full rules. I know that a discussion in a private repository can't be transferred to a public repository, but I don't know about transferring to/from internal repositories.
4. There must be a matching category type in the destination repository.
5. You must have permissions to create discussions in the repository where you want to transfer the discussion.
6. If the discussion is in an organization, it can't be transferred outside the organization without jumping through [hoops](https://github.com/orgs/community/discussions/17669#discussioncomment-8097604).

Note: I can't recall if you need permissions to do something in the source repository. If you do, it should be mentioned. Frankly, if you don't, that should be mentioned too, and what happens if you're missing that permission should be mentioned.

**Comment by nguyenalex836** [comment]
@jsoref Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by Duncun76918** [comment]
> ### 行為守則
> * [x] 我已閱讀並同意 GitHub Docs 專案的[行為準則](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### docs.github.com 上的哪些文章受到影響？
> https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#transferring-a-discussion
> 
> ### 您希望更新文章的哪一部分？
> 當前文本以段落形式表示：
> 
> > 要轉移討論，您必須有權在要轉移討論的儲存庫中建立討論。
> > 如果要將討論轉移到組織，您必須有權在組織討論的來源儲存庫中建立討論。
> > 您只能在同一使用者或組織帳戶擁有的儲存庫之間轉移討論。
> > 您無法將討論從私人儲存庫轉移到公共儲存庫。
> 
> 1. 這是不完整的
> 2. 它確實不應該採用段落形式，因為很難確定某些內容是否符合此要求。
> 
> ### 附加資訊
> [https://github.com/orgs/community/discussions/3381#discussioncomment-2648205 ](https://github.com/orgs/community/discussions/3381#discussioncomment-2648205) https://github.com/orgs/community/discussions/3381#discussioncomment-2656034
> 
> 如果這樣寫就更好了：
> 
> 1. 目標儲存庫必須啟用討論
> 2. 正在傳輸的討論不能是「公告格式」（帶有連結到類似[https://user-images.githubusercontent.com/6379424/165794923-31209021-ba53-490a-8212-7a6815bb0deb.png-](https://user-images.githubusercontent.com/6379424/165794923-31209021-ba53-490a-8212-7a6815bb0deb.png)理想情況下，一旦[討論格式實際上沒有記錄](https://github.com/github/docs/issues/31056)[ #31056](https://github.com/github/docs/issues/31056)得到解決，這將為連結創建一個好的目的地。[](https://github.com/github/docs/issues/31056)
> 3. [關於將討論轉移到不同可見性](https://docs.github.com/en/enterprise-cloud@latest/repositories/creating-and-managing-repositories/about-repositories#about-repository-visibility)的儲存庫的解釋。我實際上不知道完整的規則。我知道私人存儲庫中的討論無法轉移到公共存儲庫，但我不知道如何轉移到內部存儲庫或從內部存儲庫轉移。
> 4. 目標儲存庫中必須有相符的類別類型
> 5. 您必須有權在要傳輸討論的儲存庫中建立討論。
> 6. 如果討論是在組織內進行的，則無法將其轉移到組織外，除非經過[重重困難](https://github.com/orgs/community/discussions/17669#discussioncomment-8097604)
> 
> 注意：我不記得您是否需要權限才能在來源儲存庫中執行某些操作。如果這樣做，應該提及。坦白說，如果您不這樣做，也應該提及這一點，並且應該提及如果您缺少該許可證會發生什麼。

#30802

**Comment by Remyortiz10** [comment]
```shell

```

**Comment by jsoref** [comment]
Note the constraint about announcements is now listed in https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions#creating-a-category as part of https://github.com/github/docs/commit/c211dc56a0c340c6195de0c26fbba976472318e0 (noted in https://github.com/github/docs/issues/31056#issuecomment-1934642642).

But you can't link to that, so prose will be needed here.

**Comment by nguyenalex836** [comment]
Given https://github.com/github/docs/pull/31540, closing this issue!
