### ISSUE TITLE
Tables are broken in the translated pages

### ISSUE THREAD

**Issue by kawarimidoll** [github/docs#3114]
### What article on docs.github.com is affected?

- https://docs.github.com/ja/rest/overview/libraries
- https://docs.github.com/cn/rest/overview/libraries
- https://docs.github.com/pt/rest/overview/libraries

### What part(s) of the article would you like to see updated?

Tables are broken in these pages.
See screenshots below.

#### original(valid):
![en](https://user-images.githubusercontent.com/8146876/105627218-d22a3500-5e78-11eb-905d-bd3e248fbfef.png)

#### ja:
![ja](https://user-images.githubusercontent.com/8146876/105627225-dfdfba80-5e78-11eb-8711-06a6e198558e.png)

#### pt:
![pt](https://user-images.githubusercontent.com/8146876/105627231-f0903080-5e78-11eb-9724-f6d7fadc625e.png)

#### cn:
![cn](https://user-images.githubusercontent.com/8146876/105627235-fbe35c00-5e78-11eb-9711-e0dd2ba87fb2.png)

**Comment by janiceilene** [comment]
Thanks so much for reporting this @kawarimidoll! Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

In the meantime, I've reported this to be fixed internally 💛
