### ISSUE TITLE
Add Pakistan phone number to its system

### ISSUE THREAD

**Issue by Jin-2895** [github/docs#31140]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

![image](https://github.com/github/docs/assets/37734603/26376738-90c1-4b27-a2a9-c63d2fb4e50f)

### What part(s) of the article would you like to see updated?

kindly add support for Pakistan for 2F authentication. Also i have no idea where to report this so i am bringing the issue here.

**Comment by nguyenalex836** [comment]
@Jin-2895 Thanks for opening this issue! We’re only able to offer SMS authentication in countries where our SMS providers can guarantee a high deliverability rate. I’m sorry to say their service is not reliable enough in Pakistan at this point in time, so we’re unable to offer SMS authentication as an option for users in Pakistan.

While we won’t be able to offer SMS as an option for you, you might consider enabling two-factor authentication using a TOTP application. If you’re interested, we have a guide that will walk you through setting this up:
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-totp-mobile-app

With 2FA enabled, be sure to set up some of these additional fallback recovery methods as well:
- **Download your recovery codes.** This is by far the best way to make sure you don’t get locked out of your account.
- **Add a security key.** You’ll still have access to your account if you have a FIDO U2F security key added to your account
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication-recovery-methods

I apologize for the inconvenience, and rest assured, we’re actively working to improve the situation. 

I'm going to go ahead and close this issue now 💛
