### ISSUE TITLE
Document Maximum Number of 6 Pinned Repositories

### ISSUE THREAD

**Issue by michaelkpfeifer** [github/docs#31159]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Pinning items to your profile](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile)

### What part(s) of the article would you like to see updated?

The "Pinning items to your profile" document describes the conditions under which a repository can be pinned to a profile very well. However, it does not explain that there is a maximum number of 6 pinned repositories.

I wasn't able to pin the seventh repository. It took me quite some time to find out that the reason is that there is a limit to the number of pinned repositories.

### Additional information

In case the document should be updated, I'm happy to provide a pull request.

**Comment by nguyenalex836** [comment]
@michaelkpfeifer Thanks so much for opening this issue! I see in the [doc](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile) the following is explained on step 5 -

> Select up to six repositories and gists, combined.

![image](https://github.com/github/docs/assets/150945400/7cb6b6b5-087b-490a-816d-7f12fbc9fe9d)

We appreciate your willingness to contribute to GitHub Docs, however! If you're looking for any issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues ✨ I'll go ahead and close out this issue!

**Comment by michaelkpfeifer** [comment]
No idea why I overlooked that. Thanks for you fast response.

**Comment by nguyenalex836** [comment]
Happens to the best of us! 💛

**Comment by Dwbjc** [comment]
I don’t know what’s going on I’m not receiving information somewhere solidity and it’s assets I had started back in September or October never heard lost the password thought it just didn’t happen now I received an Audit paper and went to see it testingSent from my iPhoneOn Jan 18, 2024, at 5:05 PM, Alex Nguyen ***@***.***> wrote:﻿
@michaelkpfeifer Thanks so much for opening this issue! I see in the doc the following is explained on step 5 -

Select up to six repositories and gists, combined.

image.png (view on web)
We appreciate your willingness to contribute to GitHub Docs, however! If you're looking for any issues to work on, take a look at our help wanted section to find open issues ✨ I'll go ahead and close out this issue!
