### ISSUE TITLE
Wrong keyboard combination for VS Code Command Palette for Windows/Linux

### ISSUE THREAD

**Issue by ljcr84** [github/docs#31213]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[content/codespaces/getting-started/deep-dive.md](https://docs.github.com/en/codespaces/getting-started/deep-dive)

### What part(s) of the article would you like to see updated?

Wrong keyboard command to bring up the VS Code Command Palette in Windows/Linux:

<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> instead of <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>

**Comment by nguyenalex836** [comment]
@ljcr84 Thank you for opening an issue and linking it to your PR! ✨
