### ISSUE TITLE
Specify how environments are implicitly created in Actions

### ISSUE THREAD

**Issue by timruffles** [github/docs#3126]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/environments

### What part(s) of the article would you like to see updated?

I'd like the docs to specify how environments are automatically created and named. The docs only explain how referencing environments that don't yet exist create them, yet it seems they can be created by other means. I've not used the 'environments' feature before, but when I opened the page I nevertheless saw a couple already there. I'm guessing that they were based on branch name, but only some branches seem to have an environment. 

It'd be also be great if the docs explained what an environment is at a high level.

### Additional information

I'm a xhubber, used to work on Actions.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @timruffles! I thought your name looked familiar 😄 I'll get this triaged for the team to take a look ⚡

**Comment by skedwards88** [comment]
Thanks for opening this issue @timruffles! Would add the following info (bolded) to the paragraph at the bottom of [Creating an environment](https://docs.github.com/en/actions/reference/environments#creating-an-environment) address what you are looking for?

> Running a workflow that references an environment that does not exist will create an environment with the referenced name. **Similarly, using the REST API to create a deployment that references an environment that does not exist will create an environment with the referenced name.** The newly created environment will not have any protection rules or secrets configured. **Anyone with permission to edit workflows or create deployments in the repository can create environments,** but only repository admins can configure the environment.

**Comment by timruffles** [comment]
There seems to be some other process that creates environments. e.g on [my blog](https://github.com/timruffles/timruffles.github.io), I have only recently written a [workflow](https://github.com/timruffles/timruffles.github.io/commits/master/.github/workflows/deploy.yml) (it did previously have a `.workflow`, but that was for the original HCL version of Actions), and it's either had no `environment` key or `gh-pages` when run. However, on the environment tab I have the following environments:

![image](https://user-images.githubusercontent.com/249800/106388399-47948900-63d6-11eb-90cc-4446f391d4ee.png)

I'm unsure where they came from - they don't appear to be [branches](https://github.com/timruffles/timruffles.github.io/branches/all).

**Comment by skedwards88** [comment]
I checked in with the engineering team about this. These environments were created back in 2018/2019 with the deployment status API. The environments UI displays previously created environments (even if the environment was created before the UI was built). 

I think this should solve this issue, so I'm going to close it, but feel free to re-open it if not!
