### ISSUE TITLE
Fork a repo article has text left in from a merge conflict

### ISSUE THREAD

**Issue by tomstrong64** [github/docs#31298]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#next-steps
Merge conflict text remains in the document

**Comment by nguyenalex836** [comment]
@tomstrong64 Thanks so much for opening this issue! You, or anyone else, are welcome to submit a PR with this fix. 💛

**Comment by nguyenalex836** [comment]
@tomstrong64 Thank you for opening an issue and linking it to your PR! ✨
