### ISSUE TITLE
Code generation after prompt to reply in markdown bug 

### ISSUE THREAD

**Issue by RicardoGEsteves** [github/docs#31301]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

copilot chat

### What part(s) of the article would you like to see updated?

Copilot chat.

### Additional information

![vscode-copilot](https://github.com/github/docs/assets/30535937/af6aa78c-a1cc-494c-9d7e-600dae57a42e)

After being prompt to generate code in markdown it fails to render all the code in markdown after the first block of 
```bash 
code
```

**Comment by nguyenalex836** [comment]
Hi @RicardoGEsteves 👋 welcome to GitHub Docs, where we maintain the docs for GitHub! Is there a certain update to a specific doc you were hoping to make? Or are you running into an issue with using Copilot? 

If it is the latter, this would be handled best by our fantastic [support team](https://support.github.com/request) 💛 please reach out to them if this is the case!

**Comment by RicardoGEsteves** [comment]
> Hi @RicardoGEsteves 👋 welcome to GitHub Docs, where we maintain the docs for GitHub! Is there a certain update to a specific doc you were hoping to make? Or are you running into an issue with using Copilot? 
> 
> If it is the latter, this would be handled best by our fantastic [support team](https://support.github.com/request) 💛 please reach out to them if this is the case!

Ok, I will do that than.
Was looking for copilot chat repo to open the issue, but it should be private so I opened here.
Thanks for your reply.

**Comment by nguyenalex836** [comment]
My pleasure! Will go ahead and close this issue 💛
