### ISSUE TITLE
Wrong example regarding dollar sign in mathematical expressions article

### ISSUE THREAD

**Issue by alinkedd** [github/docs#31312]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-dollar-signs-in-line-with-and-within-mathematical-expressions

### What part(s) of the article would you like to see updated?

Now:

```
This expression uses `\$` to display a dollar sign: $\sqrt{\$4}$
```
This expression uses `\$` to display a dollar sign: $\sqrt{\$4}$

***

Should be:

```
This expression uses `\$` to display a dollar sign: $`\sqrt{\$4}`$
```
This expression uses `\$` to display a dollar sign: $`\sqrt{\$4}`$

***

In this case, the expression contains characters that overlap with markdown syntax so the `$``$` syntax should be used instead.

**Comment by nguyenalex836** [comment]
@alinkedd Thank you for raising this issue! I'll get this triaged for review ✨ Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by subatoi** [comment]
Thanks, @alinkedd, you're absolutely right—you or anyone else is very welcome to open a PR to fix this! ✨ 

And thank you for raising this as an issue before going ahead and raising a PR: we really appreciate it!
