### ISSUE TITLE
The workflow named "cleanup caches by a branch" is not working as expected

### ISSUE THREAD

**Issue by Mogyuchi** [github/docs#31321]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

### What part(s) of the article would you like to see updated?

Modify the workflow example in [Managing caches > Force deleting cache entries](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries)

Why:
When triggered by the `pull_request` event, the `GITHUB_TOKEN` does not have permission to delete the cache of the base repository in a cross-repository pull request. This results in the error `Error: Resource not accessible by integration`.

### Additional information

This always happens for cross-repository pull requests.

**Comment by nguyenalex836** [comment]
@Mogyuchi Thank you for opening an issue and linking it to your PR! ✨

**Comment by corneliusroemer** [comment]
I can confirm that I ran into this exact issue myself, so this should be addressed urgently.

At the same time, it might make sense to replace `gh-actions-cache` with `gh cache` as was started in https://github.com/github/docs/pull/28850
