### ISSUE TITLE
[REST] Document `/code-scanning/analysis/status`

### ISSUE THREAD

**Issue by jsoref** [github/docs#31331]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-code-scanning-alerts

### Additional information

This is the only thing nearby, but it isn't technically the same api:

[GET /repos/{owner}/{repo}/code-scanning/analyses](https://docs.github.com/en/rest/code-scanning/code-scanning#list-code-scanning-analyses-for-a-repository) | read | [UAT](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-with-a-github-app-on-behalf-of-a-user) [IAT](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation) | ✖️
-- | -- | -- | --

All I know is that it's possible to _not_ have enough permission to access the endpoint: https://github.com/github/codeql/issues/15462

**Comment by aibaars** [comment]
I believe `/code-scanning/analysis/status` is an internal API for telemetry purposes, it's not part of the public API. I wonder why it fails for you though. Perhaps GitHub Advanced Security / CodeScanning is not enabled for the repository for some reason.

**Comment by nguyenalex836** [comment]
Note: asking about this [internally](https://github.slack.com/archives/C73985URG/p1706628204194329) 💛

**Comment by angelapwen** [comment]
I'm on the owning team 👋 can confirm that this is not meant to be externally documented. We'll follow up on why it's returning a 403/404 sometimes though...

**Comment by angelapwen** [comment]
This issue can be closed as we're not planning to document this internal-only API. I'll write more detail in https://github.com/github/codeql/issues/15462 but we're planning on making sure failures from this endpoint don't fail the entire code scanning workflow, given that they are telemetry errors and unrelated to the actual analysis.
