### ISSUE TITLE
The table says `pull_request` whilst the section and examples are dedicated to `pull_request_target ` in "events-that-trigger-workflows" doc

### ISSUE THREAD

**Issue by devourer66** [github/docs#31366]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target 

### What part(s) of the article would you like to see updated?

It seems that there is a typo in https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target  The table says `pull_request` whilst the section and examples are dedicated to `pull_request_target `

**Comment by idme-developers** [comment]
Every five minutes every two minutes what's being mailed when the negative cam op people used to do you don't know how many years you've been with my mail or what's mine with this system.  How much negative work has been done, now they are engaged in this cycle of just being attached to him and this is up jo hai apna jo hai they are emailing every two to five minutes to think of the benefit that it happened like this.  It's happening like you are the people who are very successful and supportive of other people and do good things for them. You are fools. Shame on you.  Have you shown me any benefits so far? In all these years, have you shown me half a dollar or even one dollar from my payment? The corrupt logos of the corrupt system are those who run the corrupt company.  How much do you earn in the cycle of the issue and fooling others and collecting your money? You just take five dollars seven dollars and subscribe to your channel or your apps, whatever it is, and that's it.  Apart from people's community of our families, people leak their data, what are their things, what are they transferring from here to there, and how do you run the system, Shame on you, what is the investigation  If you open your investigation, you will find outOn 1/31/24, 5:43 PM devourer66 ***@***.***> wrote:

   
  Closed #31366 as not planned.
