### ISSUE TITLE
Missing permissions for "Permissions required for GitHub Apps"

### ISSUE THREAD

**Issue by timmeinerzhagen** [github/docs#31369]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Permissions required for GitHub Apps](https://docs.github.com/en/enterprise-cloud@latest/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28)

### What part(s) of the article would you like to see updated?

Not all scopes available for [new GitHub Apps](https://github.com/settings/apps/new) are documented.

I noticed these are missing on the documentation page:

* Repository: Discussions
* Repository: Packages
* Repository: Merge Queues
* Repository: Single File
* Organization: Plan

This one exists in the docs but can not be chosen when creating a GitHub App:

* User: Notifications

**Comment by skedwards88** [comment]
Thanks for this issue! I've asked our SME team about this internally.

(Internal note: Asked [here](https://github.com/github/ecosystem-apps/discussions/5119).)

**Comment by Jiskra33** [comment]
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
        include:
          - arch: amd64
            CC: x86_64-linux-gnu
          - arch: arm64
            CC: aarch64-linux-gnu
    runs-on: ubuntu-22.04
    env:
      AR: ${{ matrix.CC }}-ar
      CHOST: ${{ matrix.cc }}
      CC: ${{ matrix.cc }}-gcc
      CPP: ${{ matrix.cc }}-cpp
      CXX: ${{ matrix.cc }}-g++

**Comment by nguyenalex836** [comment]
@timmeinerzhagen Apologies for the delay in response! 💛 After review on our end, our team determined there are a number of variables in play regarding these permissions. We will need to continue review and address this internally, but wanted to thank you for raising the flag on this! ✨ 

Our team is grateful for your desire to improve GitHub Docs - thank you again!

**Comment by harshita-gupta** [comment]
checking back in on this - `Merge Queues` Github App permissions are still not documented in the `Permissions required for Github Apps` doc.

**Comment by maxious** [comment]
Also still unresolved - This one exists in the docs but can not be chosen when creating a GitHub App:

User: Notifications

**Comment by subatoi** [comment]
Hi folks—apologies for the delay and thank you for your patience. Unfortunately I don't have an update for you, but please rest assured that the issue is still being tracked internally by the relevant product team.
