### ISSUE TITLE
OAuth2: Sample verification_uri is wrong

### ISSUE THREAD

**Issue by yaakov-h** [github/docs#31380]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps

### What part(s) of the article would you like to see updated?

Under [Step 1: App requests the device and user verification codes from GitHub](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#step-1-app-requests-the-device-and-user-verification-codes-from-github) there is a sample response:

> device_code=3584d83530557fdd1f46af8289938c8ef79f9dc5&expires_in=900&interval=5&user_code=WDJB-MJHT&verification_uri=https%3A%2F%github.com%2Flogin%2Fdevice

The `verification_uri` value here is `https%3A%2F%github.com%2Flogin%2Fdevice`, which unescapes to `https:/%github.com/login/device`. This is not a valid URL.

**Comment by nguyenalex836** [comment]
@yaakov-h Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@yaakov-h Thank you for opening an issue and linking it to your PR! ✨
