### ISSUE TITLE
Mistake in sentence

### ISSUE THREAD

**Issue by roaddust2** [github/docs#31408]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Migrating from GitLab CI/CD to GitHub Actions](https://docs.github.com/ru/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions#artifacts)

### What part(s) of the article would you like to see updated?

Second sentence in Artifacts paragraph, space between words "Actions" and "артефакты" missed.

**Now:**
`В GitHub Actionsартефакты можно использовать для сохранения данных из нескольких заданий.`

**Should be:**
`В GitHub Actions артефакты можно использовать для сохранения данных из нескольких заданий.`

**Comment by nguyenalex836** [comment]
@roaddust2 Thanks for reaching out, and pointing out that extra space! I'll flag this for our team as we use an internal, automated solution for translation files 💛 

For more information on our translated docs, see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
