### ISSUE TITLE
Property description for "label" in section "labeled" is confusing due to shared template

### ISSUE THREAD

**Issue by axel-h** [github/docs#31438]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/using-the-rest-api/issue-event-types?apiVersion=2022-11-28#labeled

### What part(s) of the article would you like to see updated?

Section "labeled"

### Additional information

The template `label-properties.md` is shared between the sections describing the events "unlabled" and "labled". It seems it was initially just for "unlabled" only and thus describes the property `label` as "The label removed from the issue". This is a bit odd to read in the "labled" section.

**Comment by nguyenalex836** [comment]
@axel-h Thank you for opening an issue and linking it to your PR! ✨
