### ISSUE TITLE
Document /diffview endpoint

### ISSUE THREAD

**Issue by jlm0x017** [github/docs#31457]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

pulls -- https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28

Using the 'toggle whitespace' checkbox:
![whitespace checkbox](https://github.com/github/docs/assets/119697277/2ed430a6-9093-4020-a551-e8a3e447c031)

results in this POST back to github:
![whitespace post](https://github.com/github/docs/assets/119697277/383bd77f-68f6-42b6-8d34-d150ae698a47)

### What changes are you suggesting?

Please document how to invoke this feature for end users.

Toggling whitespace is a very helpful feature when reviewing.  Often, large amounts of clean-up (especially from auto-formatters) can obscure real changes.  This functionality has been available on github for some years.  However, it is not available as part of the api.

Clearly the functionality is there; I'd like to see it documented so I can engage the feature programmatically.

### Additional information

I ran the following command to access the feature myself:
```
$ gh api -X POST repos/ORG/REPO/pull/74/diffview
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}
gh: Not Found (HTTP 404)
```

My suspicion is that the functionality is not available because it's not a part of the official documentation, on the assumption that the docs tie into the schema checking done by the API endpoint.

**Comment by nguyenalex836** [comment]
@jlm0x017 We appreciate your willingness to provide feedback for GitHub! Given the feature you're referencing is not available, the best place to send your feedback on this particular feature request is to [https://github.com/github/feedback/discussions ✨](https://github.com/github/feedback/discussions%C2%A0%E2%9C%A8)

I'll go ahead and close this issue 💛
