### ISSUE TITLE
`GITHUB_ACTION`: `__self` isn't documented

### ISSUE THREAD

**Issue by jsoref** [github/docs#31458]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

### What part(s) of the article would you like to see updated?

> The name of the action currently running, or the [id](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsid) of a step. For example, for an action, __repo-owner_name-of-action-repo. GitHub removes special characters, and uses the name `__run` when the current step runs a script without an `id`.

### Additional information

https://github.com/check-spelling-sandbox/sub-actions-0/actions/runs/7790252174/job/21243707001

`GITHUB_ACTION: __self`

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening this issue! I'll get this triaged for review ✨

**Comment by ericsciple** [comment]
Personally I'm not too worried about this. I'm wondering whether this will complicate the docs. I would advise against depending on generated default IDs. If customers want stable/predictable IDs then I would suggest explicitly setting IDs. Unless there is some existing patterns or use cases I'm overlooking. Thoughts?

**Comment by nguyenalex836** [comment]
@ericsciple Thank you weighing in here! It sounds like we would prefer not to document this 💛 I'll go ahead and close out this issue.
