### ISSUE TITLE
Possible mistranslation to Japanese (and vague original English text) about auto-merging Dependabot PRs

### ISSUE THREAD

**Issue by whitphx** [github/docs#31518]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

En: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
Ja: https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

### What part(s) of the article would you like to see updated?

En:
> Here is an example that auto merges all patch updates to `my-dependency`

Ja:
> すべてのパッチ更新プログラムを `my-dependency` に自動マージする例を次に示します。

---

The translated Japanese text means something like "Here is an example that auto merges all __patch update (programs)__ to __(a branch named)__ `my-dependency`".

There seem to be two mistranslations.
* The word "patch" here means the patch-level updates in terms of semver, not programs applying patch updates.
* `my-dependency` is a name of the updated package, not the merge target branch.

So it should be something like this:
>  `my-dependency` （という名前の依存パッケージ）に対する全てのpatchレベルの更新を自動マージする例を次に示します。

I also think the original English text is vague and the reader and the translator can misunderstand like that.

**Comment by nguyenalex836** [comment]
@whitphx Thanks for reaching out, and letting us know about this! While we don't accept changes to our translated files as we use an internal, automated solution for translations - we will flag your request for our team 💛 

See this [page](https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations) for more information on translations ✨
