### ISSUE TITLE
Explain how rebuild works with with docker build cache

### ISSUE THREAD

**Issue by sansmoraxz** [github/docs#31517]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/rebuilding-the-container-in-a-codespace

### What part(s) of the article would you like to see updated?

Docker has a nifty little feature called [cache mounts](https://docs.docker.com/build/guide/mounts/#add-a-cache-mount).

The current explanation says that it will reuse build layers while using custom `Dockerfile`. However no explanation is provided on how cache mounts work if at all, their constrains and such when triggering a normal rebuild.

**Comment by nguyenalex836** [comment]
@sansmoraxz Thanks for opening this issue! I'll get this triaged for review ✨

**Comment by hubwriter** [comment]
@sansmoraxz - thanks for raising this issue. I feel that this is not a level of detail we need to go into in the "[Rebuilding the container in a codespace](https://docs.github.com/en/codespaces/developing-in-a-codespace/rebuilding-the-container-in-a-codespace)" article. However, I'll run this by product management for a second opinion.

**Comment by GoOd91BoY** [comment]
I am not interested in Email please

**Comment by nguyenalex836** [comment]
Just wanted to check in on this issue 💛 @hubwriter has product management been able to provide their opinion on this?

**Comment by hubwriter** [comment]
@nguyenalex836 - Thanks for the bump. I'll check again.

**Comment by hubwriter** [comment]
Thanks for raising this PR. However, I'm going to close this out as this isn't a level of detail we want to go into in this article.
