### ISSUE TITLE
Clarify case-insensitivity for code search

### ISSUE THREAD

**Issue by jsoref** [github/docs#31530]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax

### What part(s) of the article would you like to see updated?

Add a section explaining that code search is case-insensitive. Using enough SEO words to ensure that people looking for `uppercase`, `lowercase`, and similar find the block explaining this.

### Additional information

https://github.com/orgs/community/discussions/106798

**Comment by nguyenalex836** [comment]
@jsoref Thank you for raising this issue! I'll get this triaged for review ✨ Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
@jsoref We appreciate your patience while our team discussed this internally 💛 The team would welcome a section explaining case-insensitivity to the docs. You, or anyone else is welcome to submit a PR adding this section ✨

**Comment by gsosm0760** [comment]
Emeğinize sağlık
