### ISSUE TITLE
Redundant searching of blank string on landing page of docs.github.com

### ISSUE THREAD

**Issue by ChiragKr04** [github/docs#3154]
Fixes #3153 

### What is the current behavior?

While searching on docs.github.com below "Need Help?" searching is being done even on a blank string (passing only spaces) -

### What changes are you suggesting?

If statement check of blank query before sending a query to the API. PR has been raised stating "Searching on blank string fix"

**Comment by ChiragKr04** [comment]
Possible Fix
https://github.com/github/docs/pull/3153

**Comment by janiceilene** [comment]
It looks like this was fixed https://github.com/github/docs/pull/3153#issuecomment-767073165 🎉  Feel free to reopen the issue if that's not right!
