### ISSUE TITLE
`Create a review for a pull request` doesn't talk about 

### ISSUE THREAD

**Issue by jsoref** [github/docs#31550]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#create-a-review-for-a-pull-request

### What part(s) of the article would you like to see updated?

Talk about this:
> github.GithubException.GithubException: 422 {"message": "Unprocessable Entity", "errors": ["GitHub Actions is not permitted to approve pull requests."], "documentation_url": "https://docs.github.com/rest/pulls/reviews#create-a-review-for-a-pull-request"}

### Additional information

My org is set not to allow this, but the api docs should mention this is possible

https://github.com/check-spelling-sandbox/decidim/actions/runs/7845810145/job/21411091535

**Comment by nguyenalex836** [comment]
@jsoref Thanks for raising this issue! ✨ This will need to be addressed internally, and I've flagged this for our team to review. I'll go ahead and close out this issue 💛
