### ISSUE TITLE
Comparing commits may require more than 7 SHA chars

### ISSUE THREAD

**Issue by cdoublev** [github/docs#31581]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits

### What part(s) of the article would you like to see updated?

The following paragraph may need a precision about the required number of characters from the SHA code...:

  > For example, this URL uses the shortened seven-character SHA codes to compare commits f75c570 and 3391dcc: https://github.com/github-linguist/linguist/compare/f75c570..3391dcc.

... because users may need to use more than 7 characters.

### Additional information

Comparing https://github.com/w3c/webref/commit/f34bc51e16ab802ecb0a06dc26e8ed69b7cd07e0 with a branch, tag, commit, etc... requires to use its first 8 SHA chars in the url:

  - [seven-character SHA code](https://github.com/w3c/webref/compare/f34bc51..main): fail
  - [eight-character SHA code](https://github.com/w3c/webref/compare/f34bc51e..main): success

**Comment by nguyenalex836** [comment]
Thank you for raising this issue! I'll get this triaged for review ✨ Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
@cdoublev Thank you for raising this issue! I'll get this triaged for review ✨ Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by gsosm0760** [comment]
Emeğinize sağlık

**Comment by stevecat** [comment]
Hi @cdoublev, thanks for opening this issue, you've raised a good point! ✨ 

I think there's an easy fix here, to remove any potential confusion about shortened-SHA length without getting sidetracked explaining why they might be different lengths: let's just remove "seven-character" from the paragraph.

You, or anyone else, is very welcome to open a PR to make this change! :tada:

**Comment by cdoublev** [comment]
I guess "shortened" is not strictly required either. I am also not sure whether "hash" may be more appropriate than "SHA code", as I learned that Git offers a more secure way to create commit identifiers than SHA-1.

But overall it sounds good to me.
