### ISSUE TITLE
Repo permitted actions should link to Org permitted actions

### ISSUE THREAD

**Issue by jsoref** [github/docs#31590]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-and-reusable-workflows-to-run

### What part(s) of the article would you like to see updated?

[Allowing select actions and reusable workflows to run](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-and-reusable-workflows-to-run) should have text that says "if this section is locked, it's probably because the of https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#allowing-select-actions-and-reusable-workflows-to-run

### Additional information

https://github.com/orgs/community/discussions/108098

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening this issue! I'll get this triaged for review ✨

**Comment by 0336406603** [comment]
taxi 🚍 yên phonghttps://taxibacninh247.vinadigtech.vn/ 🚀 liên tỉnh🚀du lịch🚀đưa đón sân bay
0878_265_228

**Comment by gsosm0760** [comment]
Emeğinize sağlık

**Comment by jc-clark** [comment]
Thanks for the suggestion @jsoref! I went ahead and merged some changes, adding the note from the previous header to this header as well. 

We found that folks don't often read a whole page if a Google search (or some other link) lands them directly into a specific header for an article. So including this information in both places is probably really helpful.
