### ISSUE TITLE
`/code-scanning/analysis/status` endpoint links to generic `/rest` url which does _not_ have _any_ documentation on the endpoint

### ISSUE THREAD

**Issue by jsoref** [github/docs#31592]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

Well, in theory I'd like to be told what the api mentioned in https://github.com/check-spelling-sandbox/codeql/actions/runs/7878376704/job/21496502528#step:17:9

is doing:
```json
    url: 'https://api.github.com/repos/check-spelling-sandbox/codeql/code-scanning/analysis/status',
    status: 403,
...
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest'
    }
```

But, I know it's private. So, what I'd like updated is a page that says something like "you've found an undocumented api. we're sorry, it isn't documented. if you need more information, please reach out to github support/engineering." Or something. I don't know. I don't like being dumped at a main page that doesn't do anything useful.

Yes, this'd require someone to change the endpoint to return a different URL instead of a generic /rest -- just that would be a good improvement.

Note: the url returned for cases like this is going to start being much more visible as a result of a number of changes that I've either merged or am in the process of having merged.

### Additional information

https://github.com/check-spelling-sandbox/codeql/actions/runs/7878376704/job/21496502528#step:17:9

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening this issue! I'll get this triaged for review ✨

**Comment by skedwards88** [comment]
([Internal clarification](https://github.slack.com/archives/C017M6T23GA/p1707870172062929))

**Comment by skedwards88** [comment]
As per https://github.com/github/docs/issues/31331, we don't document this endpoint because it is for internal usage. It sounds like you want a more informative error message. The best place to send your feedback about this is to https://github.com/github/feedback/discussions 💛

**Comment by jsoref** [comment]
Well, I'm more interested in a page that the error message can point to that isn't a total dead end.

**Comment by jsoref** [comment]
- Cross posted to https://github.com/community/community/discussions/108351
