### ISSUE TITLE
When changing authentication from password to SSH, clarify that the remote origin URL must be updated

### ISSUE THREAD

**Issue by snarton** [github/docs#3160]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

### What part(s) of the article would you like to see updated?

When I change authentication from password to SSH, I followed the roadmap at https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh. However, I later found that I had failed to change my remote origin URL from password to SSH. It would be helpful to users to remind them that they need to take this final step to use SSH authentication. 

### Additional information

I followed the instructions at https://help.learn.co/en/articles/493023-how-to-switch-github-remote-from-https-to-ssh to do this.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @snarton! I'll get this triaged for the team to look 👀

**Comment by janiceilene** [comment]
👋 These articles aren't really about changing your SSH, so I don't see any specific article to update. If you find an article or step that could use updating to resolve the confusion you're seeing, let us know!
