### ISSUE TITLE
Let us know what you think of the new guides section!

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#31611]
### Discussed in https://github.com/github/docs/discussions/2779

<div type='discussions-op-text'>

<sup>Originally posted by **simpsoka** January 11, 2021</sup>
![CleanShot 2021-01-11 at 15 34 09](https://user-images.githubusercontent.com/704152/104250451-82804e00-5422-11eb-88b4-f926d0114446.png)

The docs team has been busy iterating on the new landing page system for products, and we've added an [all guides section](https://docs.github.com/en/free-pro-team@latest/actions/guides) that breaks down the content in a new way: **paths**. 

Think of paths like a Spotify playlist, they're there to help guide you through a learning experience, but you can still skip around to your favorite guides(tracks) or something new. We also offer multiple ways to navigate and find what you're looking for based on who you are as a developer. 

[Check out the demo of this new feature](https://www.loom.com/share/b9b0a9d1e0db4c1e8eea33211f1a5e87), and please let us know what you think about this new page by replying in this discussion. What's coming next is an all guides section towards the bottom of the page for the more CYOA (choose your own adventure) folks </div>

**Comment by Sultan0901** [comment]
[![Remove PRs from FR project v2 when FR label is removed](https://github.com/github/docs/actions/workflows/remove-fr-label-remove-from-fr-v2.yml/badge.svg)](https://github.com/github/docs/actions/workflows/remove-fr-label-remove-from-fr-v2.yml)
