### ISSUE TITLE
Inaccible tab is Bug in GitHub

### ISSUE THREAD

**Issue by imvickykumar999** [github/docs#31654]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

When I shrink window, and open list to open profile or repo option, and resize window to full tab, github page becomes inaccesible, don't know if it's fault of browser or GitHub!

### What part(s) of the article would you like to see updated?

Video Explaination:
https://twitter.com/imvickykumar999/status/1758036611349279083

**Comment by nguyenalex836** [comment]
Hi @imvickykumar999 👋  This question would best be handled by our [support team](https://support.github.com/request). Please reach out to them for assistance!

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue 💛
