### ISSUE TITLE
Searching Issues and Pull Requests: Any Assignee

### ISSUE THREAD

**Issue by jrchamp** [github/docs#31663]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

### What part(s) of the article would you like to see updated?

The article says "You cannot search for issues and pull requests that have any assignee", but this is incorrect or at least incomplete. It is possible to write a qualifier that will will only return items that have an assignee using the asterisk wildcard symbol.

### Additional information

Given that the article already claims this is impossible, I'm guessing this question has come up multiple times in the past.

**Comment by nguyenalex836** [comment]
@jrchamp Thank you for opening an issue and linking it to your PR! ✨

**Comment by gsosm0760** [comment]
Emeğinize sağlık
