### ISSUE TITLE
Searching Issues and Pull Requests: Missing Metadata qualifiers don't work with the Exclusion/Minus Symbol

### ISSUE THREAD

**Issue by jrchamp** [github/docs#31664]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

### What part(s) of the article would you like to see updated?

In "Tips", it says "Use a minus (hyphen) symbol to exclude results that match a qualifier."
In "Search by missing metadata", it makes no mention of the minus (hyphen) symbol.

The missing metadata qualifiers cannot be combined with the minus (hyphen) symbol.

### Additional information

All the time, any user who uses the qualifiers.

**Comment by nguyenalex836** [comment]
@jrchamp Thank you for opening an issue and linking it to your PR! ✨

**Comment by gsosm0760** [comment]
Emeğinize sağlık
