### ISSUE TITLE
Once Discussions close, issue templates need to stop mentioning them

### ISSUE THREAD

**Issue by janbrasna** [github/docs#31684]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What content on docs.github.com is affected?

Issue templates contain instructions to turn to Discussions to ask questions. Once the discussions close as per #31666 all similar references need to be removed.

### What changes are you suggesting?

> ![Screen Shot 2024-02-16 at 19 45 09](https://github.com/github/docs/assets/1784648/c01007e8-d985-4aea-bd06-dbbeb27aa823)

**Comment by nguyenalex836** [comment]
@janbrasna Awesome callout - thank you for the flag on this! 💛 We have an internal task set now to remind us of this once discussions closure commences ✨ thanks again!

**Comment by janbrasna** [comment]
@nguyenalex836 Sure thing, anytime! There's one more location that might be easily overlooked, it's the `@docs-bot` replying [i. e. on bogus issues](https://github.com/github/docs/issues/31741#issuecomment-1955808669):

> ![Screen Shot 2024-02-21 at 21 07 28](https://github.com/github/docs/assets/1784648/3442ea57-2b13-4c17-a2b3-f51f901efac9)

**Comment by nguyenalex836** [comment]
@janbrasna Another amazing callout! 😄 💛 We have an internal issue filed for this now - thank you! ✨
