### ISSUE TITLE
docs: Notifications REST API missing `security_advisory_credit` reason 

### ISSUE THREAD

**Issue by setchy** [github/docs#31696]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

Add the reason `security_advisory_credit`

### Additional information

<img width="1066" alt="Screenshot 2024-02-17 at 8 47 46 AM" src="https://github.com/github/docs/assets/386277/05a8672c-3d60-46d8-b7ed-f719ce2e2a8c">

**Comment by nguyenalex836** [comment]
@setchy Thank you for opening an issue and linking it to your PR! ✨
