### ISSUE TITLE
docs: Notifications REST API missing `member_feature_requested` reason

### ISSUE THREAD

**Issue by setchy** [github/docs#31697]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

Add the reason `member_feature_requested`

### Additional information

<img width="1066" alt="Screenshot 2024-02-17 at 8 47 46 AM" src="https://github.com/github/docs/assets/386277/3fad90a8-34ba-48a9-9f49-386437a0d0e8">

**Comment by Saleemfarheen** [comment]
Thanks
