### ISSUE TITLE
Mention of `docs-strategy` repository probably only for staff?

### ISSUE THREAD

**Issue by janbrasna** [github/docs#31690]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#buttons

### What part(s) of the article would you like to see updated?

> "If a button encourages people to navigate away from the GitHub Docs site, follow the call to action (CTA) button guidelines. If you want to include another type of button on a landing page or article, open an issue in the `docs-strategy` repository to share your use case for approval by the Content Strategy team."

This is either outdated, or unavailable to outside collaborators. There is no public `@github/docs-strategy` repository to file an issue with. If this is only for Hubbers there might be a note it's not available publicly — with instructions for outside collaborators how to proceed(?); or if outdated/superseded new instructins might be needed.

**Comment by nguyenalex836** [comment]
@janbrasna Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by ethanpalm** [comment]
Thanks for highlighting this, @janbrasna. This is unavailable to outside collaborators, so I've opened an internal issue to update this section of the style guide and I'm going to close this one out. Thank you for helping make the GitHub Docs better!
