### ISSUE TITLE
Inconsistent punctuation when sentence ends with quoted text

### ISSUE THREAD

**Issue by itecompro** [github/docs#31712]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

There are _many_ places that don't follow the style guides on punctuation.

### What part(s) of the article would you like to see updated?

Anywhere that has:

> For more information, see "something." # note the period _inside_ the quotation mark

to:

> For more information, see "something". # note the period _outside_ the quotation mark

### Additional information

I've done a rudimentary search in `*.md` files in VS Code:

* `".` -> 470 instances
* `."` -> 8,341 instances

Seeing a huge number of `."` usage despite being against the style guides prevented me from raising a pull request myself (maybe I've misunderstood the style guide? 🤔).

_**Style guide:** [Punctuation](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#punctuation)_

> _When referencing a UI element in quotation marks, place any subsequent punctuation **outside** of the quotation marks_

Maybe it's specific to "UI elements" as opposed to "links"? 🤔

But, this 👇️ is also a "link", why is the punctuation _outside_ the quotation mark? 🤔

_[Building and testing Java with Gradle](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle)_

![image](https://github.com/github/docs/assets/16090309/835afc27-cda1-4f4a-b272-d90847e4c3da)

Compare that 👆️ with its sister page "[Building and testing .NET](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net)":

![image](https://github.com/github/docs/assets/16090309/525e329f-4073-4fbe-8b2c-0466f3d74e09)

**Comment by Caheomini272** [comment]
Vào 7:17, CN, 18 thg 2, 2024 welcome[bot] ***@***.***> đã
viết:

**Comment by Gtnail11** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> There are _many_ places that don't follow the style guides on punctuation.
> 
> ### What part(s) of the article would you like to see updated?
> Anywhere that has:
> 
> > For more information, see "something." # note the period _inside_ the quotation mark
> 
> to:
> 
> > For more information, see "something". # note the period _outside_ the quotation mark
> 
> ### Additional information
> I've done a rudimentary search in `*.md` files in VS Code:
> 
> * `".` -> 470 instances
> * `."` -> 8,341 instances
> 
> Seeing a huge number of `."` usage despite being against the style guides prevented me from raising a pull request myself (maybe I've misunderstood the style guide? 🤔).
> 
> _**Style guide:** [Punctuation](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#punctuation)_
> 
> > _When referencing a UI element in quotation marks, place any subsequent punctuation **outside** of the quotation marks_
> 
> Maybe it's specific to "UI elements" as opposed to "links"? 🤔
> 
> But, this 👇️ is also a "link", why is the punctuation _outside_ the quotation mark? 🤔
> 
> _[Building and testing Java with Gradle](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle)_
> 
> ![image](https://private-user-images.githubusercontent.com/16090309/305676467-835afc27-cda1-4f4a-b272-d90847e4c3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzY1MjUsIm5iZiI6MTcwODI3NjIyNSwicGF0aCI6Ii8xNjA5MDMwOS8zMDU2NzY0NjctODM1YWZjMjctY2RhMS00ZjRhLWIyNzItZDkwODQ3ZTRjM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE3MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkOGI2MTBmNWE5ZjdkNzM3N2YwNDljMjk3ZjFkN2IwMTM4ZTU3NzI2MGQzNDAwOGU0YjQxNzY2MzdhODY0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HTnMvbtz6Y3DtRMMVTlucmr8Qyd2QGlLwvJBdrrcM9A)
> 
> Compare that 👆️ with its sister page "[Building and testing .NET](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net)":
> 
> ![image](https://private-user-images.githubusercontent.com/16090309/305676873-525e329f-4073-4fbe-8b2c-0466f3d74e09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzY1MjUsIm5iZiI6MTcwODI3NjIyNSwicGF0aCI6Ii8xNjA5MDMwOS8zMDU2NzY4NzMtNTI1ZTMyOWYtNDA3My00ZmJlLThiMmMtMDQ2NmYzZDc0ZTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE3MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZmJmYmI1OGNmOWU4Nzg3MDVmYjhlMjc1Y2ZjMWEzZWNlZjM3YWQyNzQxNjlmMDdmN2UyYzJjNzYyM2E0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.faliVaO8vXCv_OiL_cl8qDYDP8BIDF5OEx36Ea-U220)

**Comment by nguyenalex836** [comment]
@itecompro Thanks so much for opening this issue! I'll get this triaged for review ✨

**Comment by janbrasna** [comment]
FYI:

> Maybe it's specific to "UI elements" as opposed to "links"? 🤔

Exactly that.

So there will be both instances — page titles like `…, see "[AUTOTITLE]."` should include the punctuation inside the quoted title, whereas exact reference to an element or similar item has the quoted text exactly match like `…is "push" or "pull_request".`

Yes, there are issues with both, as demonstrated above. Fixing needs to be done contextually thou, not a mass find&replace.

**Comment by itecompro** [comment]
@janbrasna,

References to _UI elements_ are consistent and they have the punctuation outside; no problem there ✅

I do, however, see inconsistencies with _links_ themselves (I've already put an example in my original request, but here is [another one](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository)):

![image](https://github.com/github/docs/assets/16090309/04104e76-79bb-4811-99b6-fead6e8df3e2)

> should include the punctuation inside the quoted title

I don't want to be the pedantic one here (or maybe I do, otherwise why did I open the issue in the first place 😂), but it's not _grammatically_ correct 🤓

Periods/Punctuation belong to the _sentence_, not the _link_ (which is why it's not hyperlinked, i.e. outside markdown's link `[]()`).

Putting a period inside quotation marks (which is just _part_ of the sentence) doesn't justify _not completing the sentence_; the sentence is `Please see SOMTHING.`; now `SOMETHING` happens to be a link: `"Some link"`

But yes, I agree. It's gonna cause problems with a mass find/replace. Best to be fixed on a case-by-case basis.

Thanks guys 🙏
