### ISSUE TITLE
devcontainer default value for recommended secrets

### ISSUE THREAD

**Issue by agardnerIT** [github/docs#31719]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/configuring-dev-containers/specifying-recommended-secrets-for-a-repository

### What part(s) of the article would you like to see updated?

# Default Value

Is it possible to provide a default value for a recommended secret? Ie. The input box is prefilled to a sensible value.

I want to enforce a secret but also only if the user actually needs to change. 99% of my users will use a value of `foo` and those that won't, will know they need to use `bar` or `bar2` so I just want to default to `foo`.

This is a UX decision because without this, they need to go into settings, create the `foo` key **then** create the codespace. It's clunky.

I've also raised [this issue](https://github.com/devcontainers/spec/issues/430) to discuss on the spec.

# Link to devcontainer spec

To assist with the above (and any future missing docs) it would be helpful to link directly to the GitHub devcontainer spec so that even if the docs are behind, we can find answers in the live spec.

# Undocumented Checkbox option

How do we recreate this `Associate with repository` checkbox? What is the JSON key?

![image](https://github.com/github/docs/assets/26523841/cd522050-dc43-4188-bd92-03553e48733f)

# description and documentationUrl Typo

```
You can omit description and documentationUrl, as shown by NAME_OF_SECRET_2 in the previous code example.
```

This should read `NAME_OF_SECRET_1`

**Comment by nguyenalex836** [comment]
@agardnerIT Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
Hi @agardnerIT 👋 !

This question would best be handled by our [support team](https://support.github.com/request), as we are the team that handles creating / updating GitHub documentation. Please reach out to them for assistance regarding whether it is possible to provide default values for recommended secrets 💛

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue ✨ I'll go ahead and close this issue.
