### ISSUE TITLE
Clarify "PAT" in the userinfo subcomponent when authenticating to repos.

### ISSUE THREAD

**Issue by ObjectOops** [github/docs#31718]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/troubleshooting/troubleshooting-authentication-to-a-repository

### What part(s) of the article would you like to see updated?

The purpose of the string "PAT" in the username field when using this method of authentication isn't very clear.

> You can clone the repository with a URL that includes the access token. Replace YOUR-VARIABLE with the name of the environment variable or secret you created.
> `git clone https://PAT:$YOUR-VARIABLE@github.com/OWNER/REPO`

It may be assumed that the username field must be set as "PAT", when it can actually take any value as long as it doesn't malform the URL.
There could also be confusion as to where the access token should be inserted.
Replacing "PAT" with a less ambiguous value like "USERNAME" may be more appropriate.

**Comment by nguyenalex836** [comment]
@ObjectOops Thanks for opening this issue! I'll get this triaged for review ✨

**Comment by gsosm0760** [comment]
Emeğinize sağlık

**Comment by hubwriter** [comment]
@ObjectOops - Thank you for raising this. It would be good to clarify this in https://docs.github.com/en/codespaces/troubleshooting/troubleshooting-authentication-to-a-repository, as per the details you've given above.

I've marked this issue `help-wanted`. If you (or anyone else reading this) would like to raise a pull request to update the docs accordingly that would be great.

Information about contributing to the docs:
https://docs.github.com/en/contributing
