### ISSUE TITLE
Typo in privacy policy

### ISSUE THREAD

**Issue by samuelcolvin** [github/docs#31721]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[github-general-privacy-statement.md](https://github.com/github/docs/blob/6415c00c11eb55bf199ab319e0ce4568969aea4d/content/site-policy/privacy-policies/github-general-privacy-statement.md)

### What part(s) of the article would you like to see updated?

See

https://github.com/github/docs/blob/6415c00c11eb55bf199ab319e0ce4568969aea4d/content/site-policy/privacy-policies/github-general-privacy-statement.md?plain=1#L61

I'm pretty sure "this" should be a link to "What are your cookie choices and controls?"

### Additional information

These documents are great, thank you for making them available under a permissive license.

**Comment by nguyenalex836** [comment]
@samuelcolvin Thank you for raising this issue! I'll get this triaged for review ✨ Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by mchammer01** [comment]
@samuelcolvin 👋 - thanks for spotting that there is a link missing 🦅 👀 

I agree with your suggestion for the section to link to.
Would you be happy to make the fix yourself in a pull request, or shall I open this to the OS community and let someone help?

**Comment by samuelcolvin** [comment]
You go for it.

**Comment by mchammer01** [comment]
I've added the `help wanted` label to this issue which means that it's up for grabs ⚡

**Comment by code-Gambler** [comment]
I would like to fix it!, can you assign it to me
