### ISSUE TITLE
'Connecting an Azure subscription' is mentioning only EA, however you can also link an MCA

### ISSUE THREAD

**Issue by glavman** [github/docs#31720]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-the-plan-for-your-github-account/connecting-an-azure-subscription

"If you use GitHub through a Microsoft Enterprise Agreement, you can enable and pay for usage-based billing on GitHub.com by connecting an Azure subscription." 

This also works with an MCA (Microsoft Customer Agreement) 

### What part(s) of the article would you like to see updated?

The intro segment under 'Connecting an Azure Subscription'

**Comment by nguyenalex836** [comment]
@glavman Thank you for raising this issue! I'll get this triaged for review ✨ Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by gsosm0760** [comment]
Emeğinize sağlık

**Comment by isaacmbrown** [comment]
Thank you for spotting this @glavman! I looked into this internally and can confirm that no specific agreement is required to connect an Azure subscription, so we can simply remove this part:

> If you use GitHub through a Microsoft Enterprise Agreement, 

I'll open this up for contributions, so you or anyone else is welcome to submit a PR with the fix 🙂
