### ISSUE TITLE
`state` missing from List notifications REST API response schema

### ISSUE THREAD

**Issue by setchy** [github/docs#31783]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#list-notifications-for-the-authenticated-user

### What part(s) of the article would you like to see updated?

The API response schema is missing an optional field called `state` within the `subject` object.

This might also be missing from the response schemas for other Notification API endpoints...

**Comment by nguyenalex836** [comment]
@setchy Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@setchy It looks like the team will need to address this one internally, so I've copied this issue over to our internal repo. I'll go ahead and close this out 💛 thanks again for raising this issue!

**Comment by setchy** [comment]
@nguyenalex836 - i've done some more research and it looks like I was mistaken and raised this in error.  No further action is required :)

**Comment by nguyenalex836** [comment]
@setchy No problem - appreciate the update here! 🟡
