### ISSUE TITLE
Issues template button could be more clear

### ISSUE THREAD

**Issue by totally-not-frito-lays** [github/docs#31792]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

### What part(s) of the article would you like to see updated?

![image](https://github.com/github/docs/assets/30853424/d81dda3a-507c-4d12-9fd4-b50ee5456edc)

List item 3 could use a clarifying screenshot to show where the "issues" live in the repo settings.

**Comment by nguyenalex836** [comment]
@totally-not-frito-lays Hello! 👋 I went ahead and linked the [related PR](https://github.com/github/docs/pull/31793) you submitted to this issue

**Comment by koyemyatoo2020** [comment]
run

**Comment by gsosm0760** [comment]
Emeğinize sağlık

**Comment by nguyenalex836** [comment]
Adding `help wanted` label on this given last PR to address this issue was closed 💛

**Comment by Shayankashi** [comment]
> ### ضابطہ اخلاق۔
> * [x] میں نے گٹ ہب دستاویزات پروجیکٹ کے [ضابطہ اخلاق] (https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md) کو پڑھا اور اس سے اتفاق کیا ہے۔
>
> ### docs.github.com پر کیا مضمون متاثر ہوا ہے؟
> https://docs.github.com/en/communities/using-templents-to-motivate-useful-issues-and-pull-requests/configurning-issue-for-your-repository۔
>
> ### مضمون کا کون سا حصہ (حصہ) آپ اپ ڈیٹ دیکھنا چاہیں گے؟
> ![image](https://private-user-images.githubusercontent.com/30853424/307180134-d81dda3a-507c-4d12-9fd4-b50ee5456edc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODIzODcsIm5iZiI6MTcxMTI4MjA4NywicGF0aCI6Ii8zMDg1MzQyNC8zMDcxODAxMzQtZDgxZGRhM2EtNTA3Yy00ZDEyLTlmZDQtYjUwZWU1NDU2ZWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDEyMDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNjEzOTA3YWU2MmRhOWM2YzA2OWM0OGEzOGE2YWRlYjkwMjFlN2I3N2VmYjYwZWUzYTg0NDA1YzJmMzkzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ty-cYzgHJQG_UQkfgaj9AwcvHWmcxy0iofO-XbCRO6o)
>
> فہرست آئٹم 3 استعمال کرسکتا ہے۔#32193 32193

**Comment by Shayankashi** [comment]
https://github.com/github/docs/issues/31792#issue-2150091939

**Comment by Atunde-SS** [comment]
Can you translate that to english please! trying to follow up on what's addressed vs what's left
