### ISSUE TITLE
Update Python Publishing to package registries example

### ISSUE THREAD

**Issue by vinicius-oa** [github/docs#31824]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

### What part(s) of the article would you like to see updated?

The YAML provided must be updated at `uses: pypa/gh-action-pypi-publish@v1` to `uses: pypa/gh-action-pypi-publish@release/v1`, otherwise the workflow will fail because it won't find version _v1_

### Additional information

**Error**: 
![image](https://github.com/github/docs/assets/139140185/b7da91bc-8047-4198-9b70-13dde7857fa4)

**gh-action-pypi-publish's branches**:
![image](https://github.com/github/docs/assets/139140185/e23581f9-e434-43a0-b409-5b075b94b216)

[Pypa's docs](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi):
![image](https://github.com/github/docs/assets/139140185/6733ecee-9bfd-4e96-89f0-7ebc9967ab1f)

**Comment by gsosm0760** [comment]
Emeğinize sağlık
