### ISSUE TITLE
[AUTOTITLE] to #fragment uses article title only?

### ISSUE THREAD

**Issue by janbrasna** [github/docs#31829]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I had the impression that AUTOTITLE linking to another page's (sub)heading would render the section heading, but just recently discovered it fills in the page title instead.

Is that intended behavior? It leads to issues as #31789 where the link is correct, but the autotitle makes it seem it's going in circles…

It produces some weird results in context — for example in [configuring an apex domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) there's a link to [Types of GitHub Pages sites](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites), but is titled by the page title as "About GitHub Pages" that is somewhat misleading.

The hovercard also displays the main page title+intro, not the deeplink where it leads.

### What changes are you suggesting?

Is there any chance that the AUTOTITLE referencing only certain heading would be rendered with the heading name instead of page name?

**Comment by nguyenalex836** [comment]
@janbrasna Good to see you again! 👋 

This is a great question, but not one our team can best speak to. Our fantastic [support team](https://support.github.com/request) would be best equipped to address this one! ✨ 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue 💛

**Comment by towerofnix** [comment]
Just mentioning we came across this under the "Further Reading" section for ["Syncing your branch in GitHub Desktop"](https://docs.github.com/en/desktop/working-with-your-remote-repository-on-github-or-github-enterprise/syncing-your-branch-in-github-desktop):

<img width="399" alt="Further Reading. Three list items, that all say the exact same thing: 'GitHub glossary' in the GitHub glossary." src="https://github.com/github/docs/assets/9948030/bfb2b733-ca9a-4931-9c46-9253b11109ac">

**Comment by nguyenalex836** [comment]
@towerofnix Thank you for the heads up! 💛

**Comment by janbrasna** [comment]
There is an improvement now that the hovercard previewing the target page shows at least the anchor ID — but not always(?)

I see it here https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker

> ![Screen Shot 2024-07-10 at 13 08 49](https://github.com/github/docs/assets/1784648/9f30f30f-ccb1-44fa-a01b-dbc54cf35c44)

But nothing here https://docs.github.com/en/desktop/working-with-your-remote-repository-on-github-or-github-enterprise/syncing-your-branch-in-github-desktop#further-reading

> ![Screen Shot 2024-07-10 at 13 08 19](https://github.com/github/docs/assets/1784648/2c4e2952-be5a-4f27-af6c-b675b3b0850f)

**Comment by towerofnix** [comment]
It looks like this condition is the one that's not going through:

```js
(/* <a> */).href.startsWith("".concat(window.location.href.split("#")[0], "#"))
```

This really just means "if it goes to a hash, and the hash *is elsewhere on the current page*" - the stuff inside the `if` block this is part of involves a `document.getElementById` with the same hash and works with that.

It never applies to a hash link on a different page. (Unfortunately, imo!)
