### ISSUE TITLE
content-linter-rules GH011 is probably GHD011

### ISSUE THREAD

**Issue by janbrasna** [github/docs#31830]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[`data/reusables/contributing/content-linter-rules.md#L55`](https://github.com/github/docs/blob/8a1957cec6af1098b410f31cc54853f52ba6686f/data/reusables/contributing/content-linter-rules.md?plain=1#L55)

`<!-- This file is automatically generated. Manual changes will be overwritten by a 🤖 -->`

### What changes are you suggesting?

https://github.com/github/docs/blob/8a1957cec6af1098b410f31cc54853f52ba6686f/data/reusables/contributing/content-linter-rules.md?plain=1#L55

GH011 doesn't exist in https://github.com/github/markdownlint-github/tree/main/docs/rules

It's probably supposed to be GHD011. But since the file is generated this must be fixed somehwere upstream, most likely private repo.

**Comment by mchammer01** [comment]
@github/docs-engineering 👋 - can you take a look at this?
We'll probably need to fix this internally.

**Comment by peterbe** [comment]
Tracked internally.
https://github.com/github/docs-engineering/issues/4069 for those with access.

**Comment by mchammer01** [comment]
Thanks @peterbe 🎉 

Thanks for raising this inconsistency @janbrasna ✨ 

We will look at this internally, so I am going to close this open source issue.
