### ISSUE TITLE
Need to update setup-node version in the docs

### ISSUE THREAD

**Issue by seungwonleee** [github/docs#31846]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#create-an-example-workflow

### What changes are you suggesting?

This article makes reference to actions/setup-node@v3.
The most recent published version is actions/setup-node@v4.

**Comment by gsosm0760** [comment]
Emeğinize sağlık
