### ISSUE TITLE
Permissions required to change secrets are inconsistent

### ISSUE THREAD

**Issue by jyasskin** [github/docs#31866]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

* https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role:~:text=Create%2C%20update%2C%20and%20delete%20GitHub%20Actions%20secrets
* https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository

### What part(s) of the article would you like to see updated?

The [Repository roles for an organization](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role:~:text=Create%2C%20update%2C%20and%20delete%20GitHub%20Actions%20secrets) document says that participants with `write` access can "Create, update, and delete [GitHub Actions secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)", but the [Using secrets in GitHub Actions](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository) document says "you must have `admin` access."

I believe `admin` is correct, although it might be `maintain`.

**Comment by nguyenalex836** [comment]
@jyasskin Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛
