### ISSUE TITLE
ARC permissions for GitHub App registration misleading

### ISSUE THREAD

**Issue by collinmcneese** [github/docs#31883]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api#authenticating-arc-with-a-github-app

### What part(s) of the article would you like to see updated?

Currently the docs for authenticating with a GitHub App for Actions Runner Controller indicates that Repository permissions of scope `Administration: Read and write` are required.  This is misleading because this scope is _only_ required when registering ARC at the repository level and is not needed for Organization-scoped ARC registrations

### Additional information

I'll update this in a PR

**Comment by rachaelrenk** [comment]
This is in the actions docset and it looks like the actions team has the linked PR covered with a review, so I'm going to remove this from the enterprise board 🙇‍♀

**Comment by Alexx20x** [comment]
من دو ساله از طریق این سایت هک شده ام یکی کمکم کنه لطفا
