### ISSUE TITLE
I found a translation error in a document.

### ISSUE THREAD

**Issue by KenoChou** [github/docs#31900]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

While going through the beginner's material, I noticed an error in the document title; the operating system being used is Ubuntu 22.04.4, and the web browser in question is Microsoft Edge.
![截图 2024-02-29 15-17-57](https://github.com/github/docs/assets/75463608/3f6853f2-f38b-45de-bf9c-e73bed27d47e)
![截图 2024-02-29 15-23-06](https://github.com/github/docs/assets/75463608/f8fd0fbf-bf7f-423e-a61b-3c16027277c6)

### What changes are you suggesting?

The Chinese document title translation is not appropriate compared to the English document translation; the title should be '创建账户' instead of '创建客户'.

**Comment by KenoChou** [comment]
> Muka mu kacau , kasian banget cuma ngeluarin isue tentang gue agar dapat simpati dari Agensy gue , kasian banget , ambil itu agensy gue , nih gue punya eksekutor , gue kasih keluar eksekutor gue , elu semua yang sok tau banget tentang gue, siap siap elu pada di eksekusi , cambuk dan gantung. Pikirkan kah gue , waktu gue susah aja gak ada yang mikirkan .

i can not undestand what are u saying  can u using einglish?

**Comment by nguyenalex836** [comment]
@KenoChou Thanks for reaching out, and flagging this! Since we us an internal, automated solution for translations, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
