### ISSUE TITLE
`git` command example is incorrect on Authenticating as a GitHub App installation page

### ISSUE THREAD

**Issue by dom111** [github/docs#31901]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation

### What part(s) of the article would you like to see updated?

In the first section [About authentication as a GitHub App installation](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation#about-authentication-as-a-github-app-installation) there is an example that has an erroneous `"` character: `git clone https://x-access-token:TOKEN@github.com/owner/repo.git"`

**Comment by nguyenalex836** [comment]
@dom111 Thank you for opening an issue and linking it to your PR! ✨
