### ISSUE TITLE
Event API docs mention field which does not exist for CommitCommentEvent

### ISSUE THREAD

**Issue by wayofthepie** [github/docs#3190]
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/github-event-types#commitcommentevent

### What part(s) of the article would you like to see updated?
The docs mention that a `CommitCommentEvent` should contain an action when retrieved via the events API's. However, the action is only available on webhooks and never appears when you are retrieving from an events API. I'm not sure if this is an issue with the docs, and the docs should say this field is only available in webhooks, or if this is a bug in the model for this event in the events API. Thanks.

### Additional information
Example event from `/events`:
```json
{
  "id": "14949432760",
  "type": "CommitCommentEvent",
 
  "payload": {
    "comment": {
      
    }
  },
  "public": true,
  "created_at": "2021-01-26T11:31:43Z"
}
```
The `payload` field has no action. Example from webhooks:
```json
{
  "action": "created",
  "comment": {
    
  }
}
```
This does have the action.

**Comment by janiceilene** [comment]
@wayofthepie Thanks for opening an issue! I'll triage this for the team to take a look 👀

**Comment by janiceilene** [comment]
Thank so much @wayofthepie! Sorry about the delayed response, I talked to some folks and it sounds like this would be best handled by our wonderful [support team](https://support.github.com/contact)!
