### ISSUE TITLE
Theme 'Minima' no longer valid as supported themes.

### ISSUE THREAD

**Issue by 46319943** [github/docs#31913]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll

### What part(s) of the article would you like to see updated?

In this document, it says the support themes can be directly used in configuration.
However, the '[Minima](https://github.com/jekyll/minima)', which is listed in the https://pages.github.com/themes/, can not be directly used by setting `theme: jekyll-theme-minima`.

The error message is shown below:
![image](https://github.com/github/docs/assets/17161318/137c7e7d-6821-4d5a-a6bd-44b2cbf297bc)

**Comment by 46319943** [comment]
In the dependence page https://pages.github.com/versions/, 'minima' is included instead of jekyll-theme-minima. So the instruction in the document is misleading.
![image](https://github.com/github/docs/assets/17161318/885ea46e-f4ce-450f-8836-0c0132024e9a)

**Comment by nguyenalex836** [comment]
@46319943 Thank you for raising this issue! I'll get this triaged for review ✨ Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by janbrasna** [comment]
So the issue here is that every other theme listed on https://pages.github.com/themes/, even if not made by GH, is being maintained under `@pages-themes/*` repos and published to gems with the name `jekyll-theme-*` and all the subsequent instructions rely on this.

That's not the case of `minima`, that exists only under `jekyll/minima` and therefore its gem name is only `minima`.

**Comment by janbrasna** [comment]
The fix would be forking the repo under @github org and publishing its gem like all the other themes, and also update the pages-gem dependencies (probably having both @jekyll and @github provided theme gems side-by-side not to break any users of `theme: minima` while adding the support to `theme: jekyll-theme-minima` …)

The other option would be adding a note about this inconsistence (and that the instructions are not 100% valid for all themes listed) and keeping it around in all the needed places for posterity:/…

**Comment by skedwards88** [comment]
Thanks for reporting this and for your detailed comments! This sounds like more of a bug than something that we would document, so I'm going to close this issue and report this to the Pages team.
