### ISSUE TITLE
“get a reference” API does not accept SHAs as documented (`/repos/{owner}/{repo}/git/ref/{ref}`)

### ISSUE THREAD

**Issue by flying-sheep** [github/docs#31914]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The docs for this endpoint say [`/repos/{owner}/{repo}/git/ref/{ref}`](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#get-a-reference):

> `ref` string Required
>
> The commit reference. *Can be a commit SHA*, branch name (`heads/BRANCH_NAME`), or tag name (`tags/TAG_NAME`). For more information, see "[Git References](https://git-scm.com/book/en/v2/Git-Internals-Git-References)" in the Git documentation.

(emphasis mine)

Yet the `ref` API responds with 404 when used with a (valid) commit SHA:

``` console
$ gh api repos/scverse/anndata/git/ref/a4786471ee4d4e894fec150e426c3551db0f31e0
gh: Not Found (HTTP 404)
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/git/refs#get-a-reference"
}
```

whereas the `commits` API works:

```console
$ gh api repos/scverse/anndata/commits/a4786471ee4d4e894fec150e426c3551db0f31e0
{
  "sha": "a4786471ee4d4e894fec150e426c3551db0f31e0",
  "node_id": "C_kwDOBfZ26doAKGE0Nzg2NDcxZWU0ZDRlODk0ZmVjMTUwZTQyNmMzNTUxZGIwZjMxZTA",
  "commit": {...},
  ...
}
```

using the `ref` API with e.g. branch also works as documented:

```console
$ gh api repos/scverse/anndata/git/ref/heads/main
{
  "ref": "refs/heads/main",
  "node_id": "MDM6UmVmMTAwMDM4Mzc3OnJlZnMvaGVhZHMvbWFpbg==",
  "url": "https://api.github.com/repos/scverse/anndata/git/refs/heads/main",
  "object": {
    "sha": "a4786471ee4d4e894fec150e426c3551db0f31e0",
    "type": "commit",
    "url": "https://api.github.com/repos/scverse/anndata/git/commits/a4786471ee4d4e894fec150e426c3551db0f31e0"
  }
}
```

### What part(s) of the article would you like to see updated?

Either the documentation for the `ref` path parameter needs to be updated or the `ref` API needs to start working with commits as documented.

**Comment by nguyenalex836** [comment]
@flying-sheep Thanks for opening this issue! I'll get this triaged for review ✨

**Comment by flying-sheep** [comment]
What will the fix be? Will the definition of the `ref` parameter change or the behavior of the API? Where can I track this?

**Comment by flying-sheep** [comment]
The documentation now reads

> ref string Required
> 
> The Git reference. For more information, see "[Git References](https://git-scm.com/book/en/v2/Git-Internals-Git-References)" in the Git documentation.

So I assume that means “commit sha” isn’t supposed to be a valid option?

Can you please clarify what the resolution here is?

**Comment by skedwards88** [comment]
The description for that endpoint says

>  The :ref in the URL must be formatted as heads/<branch name> for branches and tags/<tag name> for tags. If the :ref doesn't match an existing ref, a 404 is returned.

So I think that the SHA is not accepted. I'll open an internal issue to move that info into the `ref` parameter description to make it more discoverable.

**Comment by flying-sheep** [comment]
I think the endpoint description you quote stayed the same, but the parameter description changed since I filed this:

```diff
 ref string Required

-The commit reference. Can be a commit SHA, branch name (heads/BRANCH_NAME), or tag name (tags/TAG_NAME).
+The Git reference.
 For more information, see "Git References" in the Git documentation.
```

I’m just confused why there’s nobody responding in this thread confirming that this change means that it was a mistake that one option for “ref” was a commit SHA.
