### ISSUE TITLE
Missing field in Event API docs for DeleteEvent

### ISSUE THREAD

**Issue by wayofthepie** [github/docs#3192]
### What article on docs.github.com is affected?
https://docs.github.com/en/developers/webhooks-and-events/github-event-types#deleteevent

### What part(s) of the article would you like to see updated?
The docs for `DeleteEvent` mention two fields, `ref`, and `ref_type`. However, there is a third field which appears in API calls, `pusher_type`. It seems `pusher_type` should also appear in the docs. Thanks!

### Additional information
Example payload for `DeleteEvent`, calling `/events`:
```json
{
  "id": "14950205875",
  "type": "DeleteEvent",
  
  "payload": {
    "ref": "dependabot/npm_and_yarn/examples/electron-react/faker-5.2.0",
    "ref_type": "branch",
    "pusher_type": "user"
  },
}
```

**Comment by janiceilene** [comment]
@wayofthepie Thanks for opening an issue! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
Thanks for pointing this out! I have asked our support team for more information about this property. It looks like it is present in other events as well (e.g. `CreateEvent`).

**Comment by skedwards88** [comment]
More info about this:
- `pusher_type` is in the payload for `DeleteEvent` and `CreateEvent`
- The value can be `user` or a deploy key

You or anyone else is welcome to open a PR to add this info to the docs.

**Comment by DevAStar08** [comment]
Can I contribute to this issue #3192

**Comment by Vivek-Hotti** [comment]
Please see PR #4348

**Comment by janiceilene** [comment]
@Vivek-Hotti I see that your PR has been closed and I don't see any changed files. Did you have a PR ready for review?

If not, @StarTrooper08 you're welcome to work on this!

**Comment by Vivek-Hotti** [comment]
@janiceilene I'm working on it. I am sorry, was working with the issue #1668 . (Refer PR #4362 that you approved today)

I am working on this issue and will issue a PR in a bit. Sorry for the delay.

**Comment by Vivek-Hotti** [comment]
Hey @janiceilene please see my PR #4570 . Required changes are made. Open to suggestions.
