### ISSUE TITLE
Subscribe button on scroll down display the element bellow.

### ISSUE THREAD

**Issue by RicardoGEsteves** [github/docs#31927]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

subscribe button at https://github.com/mona-sans in the footer.

![github-bug](https://github.com/github/docs/assets/30535937/9106b956-2491-4542-83ac-385d7454d872)

![github-bug2](https://github.com/github/docs/assets/30535937/5bd1cab2-61fa-41cc-a934-f8fb664de871)

### What changes are you suggesting?

Navigate to the end of the page, hover over the button and you will see some pixels display around the button.

**Comment by Shikha1234** [comment]
Can you please explain what is exact issue here. I would like to work on this. Thanks

**Comment by Shikha1234** [comment]
![image](https://github.com/github/docs/assets/11242283/887effed-faa6-4443-8684-9aefacf4e35d)
I am not able to reproduce this issue. It is showing fine for me. Thanks

**Comment by RicardoGEsteves** [comment]
If you scroll to the end on the page and hover the button you can reproduce that style issue. It displays some pixels, looks like that is other element showing behind.
- How to reproduce: 
1-scroll down to the footer
2-hover the button 
3-scroll up keeping the button in the view 
and you will be able to see it.

It's a minor think, but just decided to share it anyway.

**Comment by nguyenalex836** [comment]
@RicardoGEsteves Hello! 👋 We appreciate you pointing this out! Since our team only owns the pages within [GitHub Docs](https://docs.github.com/en), we would recommend sending this feedback to https://github.com/github/feedback/discussions 💛

**Comment by RicardoGEsteves** [comment]
> @RicardoGEsteves Hello! 👋 We appreciate you pointing this out! Since our team only owns the pages within [GitHub Docs](https://docs.github.com/en), we would recommend sending this feedback to [https://github.com/github/feedback/discussions 💛](https://github.com/github/feedback/discussions%C2%A0%F0%9F%92%9B)

Sure will do that.
