### ISSUE TITLE
Lowercase keyboard shortcuts if they're lowercase

### ISSUE THREAD

**Issue by westurner** [github/docs#31933]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://github.com/github/docs/blob/main/content/get-started/accessibility/keyboard-shortcuts.md

### What part(s) of the article would you like to see updated?

- [ ] DOC: use lowercase when the keyboard shortcut does not require pressing shift or capslock
  - for example, https://docs.github.com/en/get-started/accessibility/keyboard-shortcuts#source-code-browsing has:
    ```
    T	Activates the file finder
    ```
    But it is `t` that activates the file finder (which used to list all files, preventing unnecessary HTTP requests) not `T`, so it should read:
    ```
    t	Activates the file finder
    ```
    because `t` is the shortcut that activates the file finder.

**Comment by nguyenalex836** [comment]
@westurner Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by janbrasna** [comment]
This is according to the current style guides:
- https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#usage-highlights
  > "Always capitalize letter keys for general references and keyboard shortcuts."
- https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts#key-names
  > "Capitalize letter keys in general references. […] Lowercase and bold a letter key when instructing customers to enter the letter (unless you're instructing them to enter a capital letter)."

So the only flexibility here is — is it a general keyboard shortcut, or "entering a letter"?;)

**Comment by janbrasna** [comment]
Why I'm mentioning the latter is that the UI itself actually indicates using the lowercase letter:

![Screen Shot 2024-03-06 at 0 27 56](https://github.com/github/docs/assets/1784648/411d3a47-b06c-45ac-a829-9946f1b93abc)

![Screen Shot 2024-03-06 at 0 28 48](https://github.com/github/docs/assets/1784648/3d313449-228a-47a2-8b08-e76ca66a7f91)

![Screen Shot 2024-03-06 at 0 31 36](https://github.com/github/docs/assets/1784648/cf0d6177-0348-41c7-aeeb-b88ac238ec5d)

(but that doesn't have to necessarily mean much for actual docs content style… as it uses its own format of modifier keys and system shortcuts aswell…)

**Comment by skedwards88** [comment]
Thanks for this issue! You or anyone else is welcome to open a PR to make this change.

**Comment by CBID2** [comment]
> Thanks for this issue! You or anyone else is welcome to open a PR to make this change.

Hi @skedwards88! :) I made the pull request for this issue. It's #32059. Feel free to give your feedback too @janbrasna.
