### ISSUE TITLE
Helping clarify where to find the "Delete Repository" section in Settings

### ISSUE THREAD

**Issue by dev-coder** [github/docs#31930]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository

### What part(s) of the article would you like to see updated?

Step 3 - reason stated in title

**Comment by nguyenalex836** [comment]
@dev-coder Thank you for opening an issue and linking it to your PR! ✨

**Comment by Princejaw** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository
> 
> ### What part(s) of the article would you like to see updated?
> Step 3 - reason stated in title
> 
> ### Additional information
> _No response_
