### ISSUE TITLE
alternate text should be between 40-150 characters but is 251 on about-searching-on-github.md

### ISSUE THREAD

**Issue by jsoref** [github/docs#31971]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/search-github/getting-started-with-searching-on-github/about-searching-on-github.md

https://github.com/github/docs/pull/25285/commits/a7cc2e976dbb734724dcb2c5dc99da07360b0939

### What part(s) of the article would you like to see updated?

> Images alternate text should be between 40-150 characters
> Image alternate text is 251 characters long.

### Additional information

<img width="1338" alt="image" src="https://github.com/github/docs/assets/2119212/0f305f2a-987c-4e72-b5a0-35c7f45e27d9">

https://github.com/github/docs/blob/9ce845c7fdda430cf699652cbc54c963aec252b3/content/search-github/getting-started-with-searching-on-github/about-searching-on-github.md?plain=1#L73

**Comment by jsoref** [comment]
[Images alternate text should be between 40-150 characters: content/actions/security-guides/security-hardening-for-github-actions.md#L376](https://github.com/github/docs/pull/31970/files#annotation_18947633487)
Image alternate text is 195 characters long.

https://github.com/github/docs/blob/9ce845c7fdda430cf699652cbc54c963aec252b3/content/actions/security-guides/security-hardening-for-github-actions.md?plain=1#L376

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening this issue! I'll get this triaged for review ✨

**Comment by Juancanico5** [comment]
> ### Código de conducta
> * [x] He leído y acepto el [Código de conducta del proyecto GitHub Docs](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### ¿Qué artículo de docs.github.com se ve afectado?
> content/search-github/empezando-con-la-búsqueda-en-github/about-search-on-github.md
> 
> [a7cc2e9](https://github.com/github/docs/commit/a7cc2e976dbb734724dcb2c5dc99da07360b0939)
> 
> ### ¿Qué parte(s) del artículo le gustaría que se actualizara?
> > El texto alternativo de las imágenes debe tener entre 40 y 150 caracteres. 
> > El texto alternativo de las imágenes debe tener entre 40 y 150 caracteres.
> 
> ### Información adicional
> <img alt="imagen" width="1338" src="https://private-user-images.githubusercontent.com/2119212/310522573-0f305f2a-987c-4e72-b5a0-35c7f45e27d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3Njg0NzIsIm5iZiI6MTcxMDc2ODE3MiwicGF0aCI6Ii8yMTE5MjEyLzMxMDUyMjU3My0wZjMwNWYyYS05ODdjLTRlNzItYjVhMC0zNWM3ZjQ1ZTI3ZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTMyMjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU2MWQwNDQ1OWFkMzQ2ZTQ2OThmYjNmYWRjZTRhNzI0ZmQwOTlkYjA1NDhjOGQ4N2JmZWY2ZmNmYmIwYTM5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D-W_co2HGhN-Avf1veNO0HYE_i-TNkwZd6Wit6eBdmM">
> https://github.com/github/docs/blob/9ce845c7fdda430cf699652cbc54c963aec252b3/content/search-github/getting-started-with-searching-on-github/about-searching-on-github.md?plain=1#L73

**Comment by nguyenalex836** [comment]
@jsoref Thank you for raising a flag on this, and your patience while our team reviewed ✨ I've written a version of the alternate text (149 characters)

> Advanced Search page. Top search bar holds "kittens user:octocat" query. Under "Advanced options", "From these owners" text box holds term "octocat".

You, or anyone else, is welcome to update that alternate text 💛

**Comment by nguyenalex836** [comment]
@jsoref Thank you for raising a flag on this, and your patience while our team reviewed ✨ I've written a shortened version of the alternate text (149 characters)

Advanced Search page. Top search bar holds "kittens user:octocat" query. Under "Advanced options", "From these owners" text box holds term "octocat".

You, or anyone else, is welcome to update that alternate text 💛

**Comment by yongyutt0805** [comment]
ในวันที่ พ. 6 มี.ค. 2024 23:43 น. Josh Soref ***@***.***>
เขียนว่า:

**Comment by ahujaesh** [comment]
If nobody has opened a PR for this, I would be happy to make one to close this issue
