### ISSUE TITLE
Concurrency examples are inconsistent with English text around them

### ISSUE THREAD

**Issue by strugee** [github/docs#31988]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

### What part(s) of the article would you like to see updated?

This section is just generally very confusing; see this issue's title. Every example uses `group:` and `cancel-in-progress:`. However, the latter isn't even supposed to be introduced - AFAICT - until the section labeled "Example: Using concurrency to cancel any in-progress job or run". It's extremely confusing that the first example uses both of these keys but they haven't been introduced yet. As another example, one of the examples talks about specifying `concurrency: ci-${{ github.ref }}`, and then the following example does not use this expression - it uses `group: ci-${{ github.ref }}`.

**Comment by FR4NKWest** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
> 
> ### What part(s) of the article would you like to see updated?
> This section is just generally very confusing; see this issue's title. Every example uses `group:` and `cancel-in-progress:`. However, the latter isn't even supposed to be introduced - AFAICT - until the section labeled "Example: Using concurrency to cancel any in-progress job or run". It's extremely confusing that the first example uses both of these keys but they haven't been introduced yet. As another example, one of the examples talks about specifying `concurrency: ci-${{ github.ref }}`, and then the following example does not use this expression - it uses `group: ci-${{ github.ref }}`.
> 
> ### Additional information
> _No response_

`erta`

**Comment by jc-clark** [comment]
Thanks for the feedback @strugee. We took a look into the issues you raised. A couple considerations/ideas: 

### Cancel in progress

> This section is just generally very confusing; see this issue's title. Every example uses `group:` and `cancel-in-progress:`. However, the latter isn't even supposed to be introduced - AFAICT - until the section labeled "Example: Using concurrency to cancel any in-progress job or run". It's extremely confusing that the first example uses both of these keys but they haven't been introduced yet. 

A paragraph immediately before the examples (under the "[`concurrency`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)" header) does explain `cancel-in-progress`.  

> To also cancel any currently running job or workflow in the same concurrency group, specify `cancel-in-progress: true`. To conditionally cancel currently running jobs or workflows in the same concurrency group, you can specify `cancel-in-progress` as an expression with any of the allowed expression contexts.

So, in this sense, the `cancel-in-progress` concepts used in the examples are already introduced. 

Since this concept is covered in the overview paragraphs, maybe it makes most sense to completely delete the "[Example: Using concurrency to cancel any in-progress job or run](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run)" section. 

### Expression

> As another example, one of the examples talks about specifying concurrency: `ci-${{ github.ref }}`, and then the following example does not use this expression - it uses `group: ci-${{ github.ref }}`.

In the example you highlight, `group` is nested under the `concurrency` key. So, I believe the intention of this example is mainly to highlight that you can use the `ci-${{ github.ref }}` expression. Perhaps it would make sense to update the sentence as follows: 

change: 

> using a dynamic expression such as concurrency: ci-${{ github.ref }} in your workflow

to: 

> using a dynamic expression such as `ci-${{ github.ref }}` within the `concurrency` key in your workflow

**Comment by strugee** [comment]
> In the example you highlight, `group` is nested under the `concurrency` key. So, I believe the intention of this example is mainly to highlight that you can use the `ci-${{ github.ref }}` expression.

Ok, sure, but if you make the suggested change now the problem is that `concurrency: <some value or expression>` isn't documented _anywhere_. I came to these docs having already seen that construct in the wild when I couldn't confirm from the docs my guess that these two snippets are semantically equivalent:

```yaml
concurrency: foo
```

```yaml
concurrency:
  group: foo
```

> So, in this sense, the `cancel-in-progress` concepts used in the examples are already introduced.

Fair enough, I must've misremembered or something. But I still think the example would be clearer if it wasn't included, because it doesn't have anything to do with "Using concurrency and the default behavior".

**Comment by wilsommary676** [comment]
Please stay away from this investing online with these fake platforms . One really need to be careful of what they do online. I was a victim to this platform they made me lose all my funds and I was blocked by them and I was unable to reach them on Skype, But am glad I took the risk of working with Mr Jeff Silbert after I have heard so many review about her. She thought me a lot and with her guidance I was able to recover my funds which I lost to this platform. I can’t thank you enough Jeff by saving me from worst mistake is something I will forever be grateful for.  I highly recommend anyone in help on how to get your funds recovery Em ail.  jeffsilbert39  g m a il . c o m  I hope this reach out well to any victim.
