### ISSUE TITLE
CSV rendering fooled by quoted values that include commas

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [github/docs#32025]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This part of the documentation gives instruction as to how to make CSV files beautiful and searchable:

https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files#rendering-csv-and-tsv-data

Alas, csv data that includes quoted field values which themselves contains commas breaks the beauty, and nowhere does the documentation mention that GitHub's CSV rendering is so naive that it ignores quoted values.

### What changes are you suggesting?

The least viable change would be to acknowledge that GitHub's CSV renderer only supports the most simplistic CSV file format imaginable, and does not support quoted values.

```
1,this line has three values,foo
2,"this line also has three values, though GitHub thinks it has four",bar
```

A very beneficial change would be to recognize quoted values, and that both lines above do, in fact, contain three values.

### Additional information

Here is an example file that does not render properly in GitHub: https://github.com/os-climate/witness-core/blob/main/parameters_glossary.csv

**Comment by nguyenalex836** [comment]
@MichaelTiemannOSC Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by stevecat** [comment]
Hi @MichaelTiemannOSC! Thanks for opening this. I wasn't sure if this was something to document or a bug to fix in GitHub.

I had a look at your example file and I think the error shown is accurate:

> It looks like row 226 should actually have 6 columns, instead of 5. in line 225.

I forked the repository, added the missing column ("unit") to row 226, and it renders:

https://github.com/stevecat/witness-core/blob/main/parameters_glossary.csv

I also tested commas within quoted text and that appears to function as expected too:

https://github.com/stevecat/witness-core/blob/main/example.csv (check the first column in the first row).

The example you gave ("this line also has three values, though GitHub thinks it has four") renders too. 

Hopefully this is good news and we can close the issue. Can you let me know if I've misunderstood? ✨

**Comment by MichaelTiemannOSC** [comment]
@stevecat you win--and thanks for that!  I've updated my CSV file accordingly.
