### ISSUE TITLE
Add Persian language to docs

### ISSUE THREAD

**Issue by amiria703** [github/docs#32030]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All of them.

### What part(s) of the article would you like to see updated?

All of them.

### Additional information

Many Persian-speaking users are currently using GitHub but GitHub docs doesn't support their langauge.
It's so bad that community cannot translate GitHub docs.
Ability to translate public (not internal ones) documentations in other languages by community can be very impressive.
Please make it happen.

**Comment by codespearhead** [comment]
For reference: https://github.com/maboloshi/github-chinese
