### ISSUE TITLE
The opening "{" was missing of section title about GitHub Actions page

### ISSUE THREAD

**Issue by kkml4220** [github/docs#32063]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

## English version

![image](https://github.com/github/docs/assets/58053010/ca2a38f8-d7be-44f6-a60d-411140ba89e6)
<https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#differences-between-github-hosted-and-self-hosted-runners>

## Japanese version
![image](https://github.com/github/docs/assets/58053010/b2eb2e2c-960a-4b83-a70c-189c75188367)
<https://docs.github.com/ja/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#differences-between--data-variablesproductprodname_dotcom--hosted-and-self-hosted-runners>

### What changes are you suggesting?

I found a bug where a variable was supposed to be embedded in a section title, but the opening { was missing. So, you should start with the opening "{". When it works correctly, it shows "GitHub-ホステッド ランナー" in Japanese.

### Additional information

I apologize for my poor English. Thank you for always providing the best service.

**Comment by nguyenalex836** [comment]
@kkml4220 Thanks for reaching out, and flagging this! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
