### ISSUE TITLE
Troubleshooting required checks doesn't explain skipped check behaviour with 'needs'

### ISSUE THREAD

**Issue by innomatics** [github/docs#32065]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks

### What part(s) of the article would you like to see updated?

The warnings about skipped checks don't explain that jobs skipped because dependent jobs in their 'needs' clause won't cause required checks to fail.

This is important because user may believe their branches are protected when they are not.

**Comment by nguyenalex836** [comment]
@innomatics Thank you for opening an issue and linking it to your PR! ✨
