### ISSUE TITLE
Slight errata for token documentation

### ISSUE THREAD

**Issue by joshuatcasey** [github/docs#32084]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

(A) https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/refreshing-user-access-tokens#configuring-your-app-to-use-user-access-tokens-that-expire
(B) https://docs.github.com/en/rest/apps/oauth-applications?apiVersion=2022-11-28#check-a-token

### What part(s) of the article would you like to see updated?

(A) The value I see for `refresh_token_expires_in` is always `15897600`, not `15811200`
(B) The text description clearly says Basic Authentication (and this is what works for me) but the examples show Bearer Authentication

**Comment by ijesneo191** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> (A) https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/refreshing-user-access-tokens#configuring-your-app-to-use-user-access-tokens-that-expire (B) https://docs.github.com/en/rest/apps/oauth-applications?apiVersion=2022-11-28#check-a-token
> 
> ### What part(s) of the article would you like to see updated?
> (A) The value I see for `refresh_token_expires_in` is always `15897600`, not `15811200` (B) The text description clearly says Basic Authentication (and this is what works for me) but the examples show Bearer Authentication
> 
> ### Additional information
> _No response_

<(JES)_500=PT ON THE POCKET CASH AND ENGLISH IS E AND DASH US UNDER LANGUAGE ARE THEY IN G ALSO START ALL HTTP ACTPSIS WITH URL PLS CODEX IS NOT RUNNING PLEASE AND.,,

**Comment by ijesneo191** [comment]
urlpl must be at it in the beginning of any HTTP or https paper text Page which codex isn't running and also you need to start signing the end of your letters with your own initials also the beginning if you're a guide of the page with your initials line one always thanks.

**Comment by skedwards88** [comment]
A) Thanks for this issue! You or anyone else is welcome to open a pull request to change the `refresh_token_expires_in` value.

B) The example that you mentioned is autogenerated and needs to be fixed internally, so I'll let the team know about this. (This issue can be closed once point A is fixed since we'll track point B internally.)
