### ISSUE TITLE
Add link to OIDC claim debugger

### ISSUE THREAD

**Issue by Eldrick19** [github/docs#32128]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect

### What part(s) of the article would you like to see updated?

At the bottom or somewhere in the article, having a link to the https://github.com/github/actions-oidc-debugger action would be helpful

**Comment by Royallove5** [comment]
content/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue.md https://www.instagram.com/healthy_supplement_zinzino_ae_?igsh=YmU1MWFseXlxMGx3

**Comment by Royallove5** [comment]
https://www.zinzino.com/shop/2014565577/AE/en-US/enrollmentshophttps://www.instagram.com/healthy_supplement_zinzino_ae_?igsh=YmU1MWFseXlxMGx3https://www.zinzino.com/2014565577/AE/en-US/partnerweb/https://www.zinzino.com/shop/2014565577/UZ/en-US/products/premier-kits

**Comment by Royallove5** [comment]
https://www.zinzino.com/2014565577/AE/en-US/partnerweb/

**Comment by Royallove5** [comment]
https://www.instagram.com/healthy_supplement_zinzino_ae_?igsh=YmU1MWFseXlxMGx3

**Comment by Ahmhottt** [comment]
Hi
