### ISSUE TITLE
UI and docs don't match for "Required to be up to date" check

### ISSUE THREAD

**Issue by brian-armory** [github/docs#3215]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/administering-a-repository/about-protected-branches

### What part(s) of the article would you like to see updated?

The UI doesn't use `-` for the label

### Additional information

![image](https://user-images.githubusercontent.com/53799971/105914101-b17dee80-5fe2-11eb-8439-46124f19977f.png)

**Comment by HonkingGoose** [comment]
@janiceilene as far as I can tell this issue should be closed because PR #3216 fixed the hyphen issue.

**Comment by janiceilene** [comment]
Thanks for catching that @HonkingGoose!

@brian-armory fixed this in https://github.com/github/docs/pull/3216 and I'm going to close this 🎉
