### ISSUE TITLE
Document the character limit of label names

### ISSUE THREAD

**Issue by matthewhughes-uw** [github/docs#32156]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

* https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#create-a-label
* https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#create-a-label

### What part(s) of the article would you like to see updated?

Note that when creating a label the name must be shorter than 50 characters

### Additional information

This limitation is noted in the response when trying to create a label:

```shell
$ curl \
    --request POST \
    --header "Authorization: Bearer $GITHUB_TOKEN" \
    --header 'Accept: application/vnd.github+json' \
    --data '{"name": "my-very-log-label-that-is-definitely-over-50-chars-long"}' \
    'https://api.github.com/repos/my-org/my-repo/labels'
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Label",
      "code": "custom",
      "field": "name",
      "message": "name is too long (maximum is 50 characters)"
    }
  ],
  "documentation_url": "https://docs.github.com/rest/issues/labels#create-a-label"
}
```

But not when adding a new label to an existing issue:

```shell
curl \
    --request POST \
    --header "Authorization: Bearer $GITHUB_TOKEN" \
    --header 'Accept: application/vnd.github+json' \
    --data '{"labels": ["my-very-log-label-that-is-definitely-over-50-chars-long"]}' \
    'https://api.github.com/repos/my-org/my-repo/issues/123/labels'
{
  "message": "Validation Failed",
  "errors": [
    {
      "value": "my-very-log-label-that-is-definitely-over-50-chars-long",
      "resource": "Label",
      "field": "name",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://docs.github.com/rest/issues/labels#add-labels-to-an-issue"
}
```

**Comment by nguyenalex836** [comment]
@matthewhughes-uw Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛
