### ISSUE TITLE
Info about security-and-quality query suite missing

### ISSUE THREAD

**Issue by woeterman94** [github/docs#32160]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/codeql-query-suites

### What changes are you suggesting?

There should be a section about the security-and-quality query suite. Only **default** and **security-extended** are mentioned

### Additional information

See: https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#excluding-specific-queries-from-analysis
where security-and-quality is mentioned

**Comment by nguyenalex836** [comment]
@woeterman94 Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by wilsommary676** [comment]
Please stay away from this investing online with these fake platforms . One really need to be careful of what they do online. I was a victim to this platform they made me lose all my funds and I was blocked by them and I was unable to reach them on Skype, But am glad I took the risk of working with Mr Jeff Silbert after I have heard so many review about her. She thought me a lot and with her guidance I was able to recover my funds which I lost to this platform. I can’t thank you enough Jeff by saving me from worst mistake is something I will forever be grateful for.  I highly recommend anyone in help on how to get your funds recovery Em ail.  jeffsilbert39  g m a il . c o m  I hope this reach out well to any victim.

**Comment by Nnn253600** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/codeql-query-suites
> 
> ### What changes are you suggesting?
> There should be a section about the security-and-quality query suite. Only **default** and **security-extended** are mentioned
> 
> ### Additional information
> See: https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#excluding-specific-queries-from-analysis where security-and-quality is mentioned

**Comment by Nnn253600** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/codeql-query-suites
> 
> ### What changes are you suggesting?
> There should be a section about the security-and-quality query suite. Only **default** and **security-extended** are mentioned
> 
> ### Additional information
> See: https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#excluding-specific-queries-from-analysis where security-and-quality is mentioned

**Comment by faysal00009** [comment]
theme: jekyll-theme-minimal
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!

**Comment by Mythando** [comment]
I want to make an advice
not trade with platform you don't know I about and even if you are sure of it don't trade more than you can afford to loss.
I lost a lot trading with a scam broker who I tend to give a better profit return 
Ooo was able to recover $28,500 from them with the guidance of Jeff silbert a recovery expert. Reach out to Jeff for assistance into a better trade and how tao recover from previous loses 
Watspp + 84 94 767 1524.
Email: jeffsilbert39 g mail com.

**Comment by felicitymay** [comment]
👋 @woeterman94 

Many thanks for raising this discrepancy.

I believe these tables are intended just to show the two query suites that are available for default setup, but we should check this with the product team (SME review label added).

**Comment by Tarhanshop** [comment]
Hi

**Comment by nguyenalex836** [comment]
@felicitymay Howdy! 😄👋 Any luck with tracking down a response from the product team? I'm happy to take over following up with them if you can provide the link where their review was requested 💛

**Comment by nguyenalex836** [comment]
Note for the record - I am currently working on tracking down a review from our product team

**Comment by nguyenalex836** [comment]
SME review received! 

> That's intentional. At this point, we would rather not drive new usage to the quality queries, which includes not advertising them in the docs. They're an advanced use case for now.
> 
> This is part of our efforts to focus 100% on security, and making CodeQL the best security tool it can be. Many of the quality queries aren't maintained, are broken, or are even disabled.

**Comment by nguyenalex836** [comment]
Hi @woeterman94 👋 Thank you for your patience while our SME team reviewed this issue! 

We received confirmation from them that these tables are intended just to show the two query suites that are available for default setup. For this reason, I'll go ahead and close this issue 💛 

If you're looking for an issue to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on ✨ thanks again!

**Comment by imnasnainaec** [comment]
@nguyenalex836 It's reasonable to have started with just the default setup suites, but at some point, it'd be really helpful for the documentation to also (at least) mention what other built-in suites are available. Could the SME team please reconsider this issue?

**Comment by imnasnainaec** [comment]
Never mind, I see it in https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#using-queries-in-ql-packs

**Comment by Nicksisw** [comment]
🍆🍆

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________
