### ISSUE TITLE
Documentation - searching for files

### ISSUE THREAD

**Issue by liquidcarbon** [github/docs#32182]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github

### What part(s) of the article would you like to see updated?

How to search a file in the root of the repo

### Additional information

Hello,  I was trying to do something that I thought was rather simple - find all repositories with a specific file in their root.
The advanced search query builder offers this: `path:/ path:**/pixi.toml`
But it clearly does not do what's intended.

![image](https://github.com/github/docs/assets/47034358/b3a788f0-fbc0-4684-ba85-0265658609a7)

The simple `path:pixi.toml` might be the closest, but it still returns results that include files in nested folders:

![image](https://github.com/github/docs/assets/47034358/5172b758-6ec6-47bd-9fd7-7ec252b74856)

Note that these searches don't return any result for repositories.

It seems like a relatively common use case for search - would you please update the docs on how to do that?  Or point me to the right place.  Thank you!

**Comment by liquidcarbon** [comment]
Seems like what I'm looking for is
`path:/^pixi.toml/`
or more precisely
`path:/^pixi\.toml$/`

Seems like it would be useful to call out in the docs on path and regex. https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#using-regular-expressions

This message was most helpful in getting there:
![image](https://github.com/github/docs/assets/47034358/635dc8f7-fda0-4713-a19d-328f6ffd9b6d)

**Comment by nguyenalex836** [comment]
@liquidcarbon Thanks for opening this issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@liquidcarbon Hi 👋 ! Thank you for your patience while our team reviewed! 

We wanted to mention that using regexes is described in the `path:` [documentation](https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#path-qualifier) already, and wanted to ensure you were aware of this ✨ 

If you were, can you specify exactly what it is you would like to add / update in the docs? 💛
