### ISSUE TITLE
Fix GitHub Copilot CLI Powershell Alias instructions

### ISSUE THREAD

**Issue by mpusch88** [github/docs#32187]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/github-copilot-in-the-cli/using-github-copilot-in-the-cli

### What part(s) of the article would you like to see updated?

What needs to be fixed:

The alias creation section for PowerShell.

Why:

The instructions provided add a new line to the PowerShell profile every time PowerShell is opened.

Expected Results:

Instructions should be updated to avoid adding a new line to the PowerShell profile every time PowerShell is opened.

**Comment by mklement0** [comment]
To add some context:

The code shown in the linked instruction is _setup code_, meant to be run _once_ in order to _programmatically add_ the aliases (which are actually _functions_) to the profile / initialization files of supported shells, whereas the instructions, e.g. "Add the following to your PowerShell profile:", mistakenly suggest that this setup code _itself_ should be added to the profile / initialization file.

**Comment by nguyenalex836** [comment]
@user Thank you for opening this issue! I've linked the related PR ✨

**Comment by nguyenalex836** [comment]
@mpusch88 Thank you for opening this issue! I've linked the related PR ✨

**Comment by mpusch88** [comment]
I closed the PR as the fix was not correct.

I'd be happy to update the instructions, but need someone to fix the alias for Windows PowerShell first.

**Comment by nguyenalex836** [comment]
@mpusch88 

> but need someone to fix the functions generated by the alias command for Windows PowerShell first.

I'll get this triaged for the team to review ✨

**Comment by isaacmbrown** [comment]
I noticed that this has been fixed now. The commands are now provided as commands to be run, rather than lines to add to a configuration file.

https://docs.github.com/en/copilot/github-copilot-in-the-cli/configuring-github-copilot-in-the-cli
