### ISSUE TITLE
Connecting to a private network docs appear to reference archived gh-cli extension

### ISSUE THREAD

**Issue by srudolph-credera** [github/docs#32221]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Codespaces/Developing in a codespace/Connecting to a private network](https://docs.github.com/en/codespaces/developing-in-a-codespace/connecting-to-a-private-network)

### What part(s) of the article would you like to see updated?

The [Using the GitHub CLI extension to access remote resources](https://docs.github.com/en/codespaces/developing-in-a-codespace/connecting-to-a-private-network#using-the-github-cli-extension-to-access-remote-resources) section references a [GitHub CLI extension](https://github.com/github/gh-net#codespaces-network-bridge) that has been archived with a last code change back in September 2022, but in the docs, it's cited as still being in beta. 

I'm hoping there's a new recommended approach that could be mentioned in the documents. If not, maybe a removal of the section about the extension altogether or at least a changing of the disclaimer from 'beta' to 'no longer supported' would be appropriate.

Thanks!

**Comment by nguyenalex836** [comment]
@srudolph-credera Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
Hi @srudolph-credera 👋 Thank you for waiting while we reviewed your issue! While we currently do not have a new, recommended approach to add to this documentation, your suggestion - 

> changing of the disclaimer from 'beta' to 'no longer supported' would be appropriate.

would be a great update ✨ You, or anyone else, is welcome to submit a PR with this change.
