### ISSUE TITLE
REST API files in commits lost patch field

### ISSUE THREAD

**Issue by BaumiCoder** [github/docs#32223]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[REST API endpoints for commits - Get a commit](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit)

### What part(s) of the article would you like to see updated?

The query parameter `per_page`  has currently the following documentation:
>The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
Default: 30

But without giving a value for this parameter, I get over 30 files, even over 100 (e.g., [here](https://api.github.com/repos/Dexels/navajo/commits/3fde56e37d6446e1f705c3a0a41ba1833fe0e686) I get 177 files). So the default and the maximum are wrong documented (or implemented) here.
The default seems to be, that there is no limitation at the numbers of listed files. Similar for the maximum, but maybe 121 is (or should be) the maximum, because the files from 0 to 120 have a patch field and at the files from 121 to 177 (in my example) the patch field is missing. (The files from 121 to 177 have a patch field if I use pagination like [here](https://api.github.com/repos/Dexels/navajo/commits/3fde56e37d6446e1f705c3a0a41ba1833fe0e686?per_page=121&page=2))

### Additional information

The problem can be reproduced at my side and occurs always. I encounter the problem with my python script [here](https://github.com/BaumiCoder/Improving-Source-Code-Readability-Theory-and-Practice/tree/b08f976c52d77be0f972ce3e00fde1aff7de90e1), when you reach about row 1717 of the csv file.

**Comment by nguyenalex836** [comment]
@BaumiCoder Thank you for opening this issue! I'll get this triaged for review ✨
