### ISSUE TITLE
Reasons of exposing GHES url on public internet

### ISSUE THREAD

**Issue by sameerjethvani-alation** [github/docs#32243]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.11/admin/github-actions/enabling-github-actions-for-github-enterprise-server/enabling-github-actions-with-amazon-s3-storage
https://docs.github.com/en/enterprise-server@3.11/admin/configuration/hardening-security-for-your-enterprise/configuring-tls
https://docs.github.com/en/enterprise-server@3.11/admin/identity-and-access-management/using-saml-for-enterprise-iam/configuring-user-provisioning-with-scim-for-your-enterprise

### What changes are you suggesting?

What are all reasons for exposing GHES URL on public internet
Few of reasons , which I can infer directly/indirectly while setting up GHES on aws & going through few of GHES docs .

_Reason 1)_ Configuring s3 provider for Github Actions through OIDC way , which requires exposing urls like
https://HOSTNAME/_services/token/.well-known/openid-configuration , https://HOSTNAME/_services/token/.well-known/jwks to Public internet
https://docs.github.com/en/enterprise-server@3.11/admin/github-actions/enabling-github-actions-for-github-enterprise-server/enabling-github-actions-with-amazon-s3-storage

_Reason 2)_ Configuring TLS with let's encrypt certs. Generation & renewal of it requires your GHES URL available on public internet
https://docs.github.com/en/enterprise-server@3.11/admin/configuration/hardening-security-for-your-enterprise/configuring-tls

Are there any other reasons ? , which I am missing . 
For-ex (_May be Reason 3_) Configuring SCIM (in case of SAML configured with IDP , in our case okta) , enabling SCIM through Github Personal Access Token may require GHES host url available on public internet .

Though nothing has been written in straight words here https://docs.github.com/en/enterprise-server@3.11/admin/identity-and-access-management/using-saml-for-enterprise-iam/configuring-user-provisioning-with-scim-for-your-enterprise

Having these scenarios listed in separate doc/refining existing affected articles would surely help someone to better plan architecture & deal with issue of rearchitecting in middle of long journey of implementing GHES.

### Additional information

The only thing , I am suggesting here is to have some thing either in existing docs or separate article mentioning list of scenarios/configurations which would only work when your GHES host url is publicly exposed. I have already listed out few scenarios here & expecting you guys with your expertise to further enhance that list.

**Comment by nguyenalex836** [comment]
@sameerjethvani-alation Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by isaacmbrown** [comment]
Thank you @sameerjethvani-alation! 👋 As it happens we had an internal issue raised for the same topic last week, so I'm going to copy the context you added here into that internal issue, and close this one as a duplicate. We'll keep you updated here as we make progress. Thanks again for the issue!
