### ISSUE TITLE
Default `run-name` of workflow run triggered by `pull_request`

### ISSUE THREAD

**Issue by muzimuzhi** [github/docs#32266]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name

### What part(s) of the article would you like to see updated?

`run-name`

> GitHub displays the workflow run name in the list of workflow runs on your repository's "Actions" tab. If `run-name` is omitted or is only whitespace, then the run name is set to event-specific information for the workflow run. For example, for a workflow triggered by a `push` or `pull_request` event, it is set as the commit message.

But from what I seen in "Actions" tab, the default `run-name` of workflow runs triggered by `pull_request` is the corresponding PR title, not commit message.

For example
- https://github.com/muzimuzhi/hello-github-actions/actions?query=event%3Apull_request
- https://github.com/latex3/latex3/actions?query=event%3Apull_request

**Comment by nguyenalex836** [comment]
@muzimuzhi Thank you for opening an issue and linking it to your PR! ✨
