### ISSUE TITLE
Commit count limit is 10,000

### ISSUE THREAD

**Issue by JasonWHowell** [github/docs#32295]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[content/repositories/creating-and-managing-repositories/repository-limits.md](https://docs.github.com/en/repositories/creating-and-managing-repositories/repository-limits#commit-listings-limits)

### What part(s) of the article would you like to see updated?

The commit limits count - we are seeing 10,000 limit on the count of commits in a pull request. The actual number of commits can be much higher in the underlying branch itself. 
![image](https://github.com/github/docs/assets/5067358/4461be73-1c12-4b11-810d-8a30f2758d95)

**Comment by nguyenalex836** [comment]
@JasonWHowell Thank you for opening an issue and linking it to your PR! ✨
