### ISSUE TITLE
Misleading guidance on workflow filters

### ISSUE THREAD

**Issue by DavidSlayback** [github/docs#32291]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Using Filters](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters)

### What part(s) of the article would you like to see updated?

I didn't submit this as a PR because I don't know if the mistake is in Docs or in GitHub Actions.

In the docs, it states:

> If you define both branches/branches-ignore and [paths/paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), the workflow will only run when both filters are satisfied.

However, this is not true. Both in my own experience writing Actions for my company and in StackOverflow threads, it's clear that GitHub uses a logical OR instead of the implied AND from above. E.g., if I specify in a workflow:
```yaml
on: 
  push:
    branches:
      - main
    paths:
      - "src/**"
```
I expect that the above should only trigger on a push to the `main` branch that alters files under `src`. However, it actually triggers on BOTH any push to `main` and any push to another branch that changes `src` files.

If this is the desired behavior, then the docs should be changed to reflect it. If it's not the desired behavior, then Actions should be changed to reflect the docs

**Comment by nguyenalex836** [comment]
@DavidSlayback Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by DavidSlayback** [comment]
Any updates on this? We wound up using a 3rd-party Github Action, but it'd be much cleaner to incorporate into the `on` trigger

**Comment by nguyenalex836** [comment]
@DavidSlayback Hello! 👋 Thank you for your patience while our engineering team reviewed! 

They are asking if you are able to replicate this in a public environment. Having an example they can look at, rather than needing to fabricate that repository structure and any user initiated changes would help them investigate further 💛
