### ISSUE TITLE
Proposed Snyk Security guides for GitHub Actions Documentation

### ISSUE THREAD

**Issue by tomgonzo** [github/docs#3229]
@josepalafox @jleopdx 

### What article on docs.github.com is affected?

We created guides for the Snyk GitHub Actions following the format on this site: https://docs.github.com/en/actions/guides

### What part(s) of the article would you like to see updated?

I'd like to submit three new guides, please! No revisions to existing content.

### Additional information

@josepalafox opening a GitHub issue as requested. Zip with MD files attached. :)
[Snyk-GH-Actions-Guides.zip](https://github.com/github/docs/files/5879540/Snyk-GH-Actions-Guides.zip)

**Comment by Rafael450363** [comment]
Revisiones del equipo

**Comment by Rafael450363** [comment]
Actuaciones

**Comment by Rafael450363** [comment]
CONTRIBUTING.md

**Comment by mcclure69** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

Hi

**Comment by swinton** [comment]
Hey @tomgonzo :wave:

Thanks for opening this issue. We have a new process to follow here. Would you mind opening a new issue [here](https://github.com/github/docs/issues/new?template=partner-contributed-documentation.md), that has a few steps to guide you through the process.

I'll close this one. Thanks!
