### ISSUE TITLE
Broken callout example code-block formatting

### ISSUE THREAD

**Issue by sventec** [github/docs#32300]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#formatting-callouts

### What part(s) of the article would you like to see updated?

In the `Formatting callouts` section of the style guide, the Markdown formatting for the `Tip` code-block is broken, causing it to display incorrectly on the docs site. This should be updated to have the opening and closing fences for this block on individual lines.

### Additional information

It seems this change was introduced [here](https://github.com/github/docs/commit/18b43b94f5d08ae32f2248b386f6941c7874100a#diff-17d205674566dd4f9d7dbed2a15988b4e9bdda279e6f17b5cb6f7639107ab8b8R94).

Here is a screenshot of the render issue:

![image](https://github.com/github/docs/assets/18218761/615f0c77-33e4-4d48-b150-fc0b2e989b2a)

**Comment by sventec** [comment]
I have created a PR to resolve this issue here: #32301

**Comment by nguyenalex836** [comment]
@sventec Thank you for opening an issue and linking it to your PR! ✨
