### ISSUE TITLE
Remove specific directory reference from the creating-a-github-pages-site-with-jekyll page

### ISSUE THREAD

**Issue by revolter** [github/docs#32347]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll#creating-your-site

- A shell command uses a `REPOSITORY-NAME` placeholder, but the results comment uses a specific directory reference
- A Ruby code block is using the shell syntax instead

**Comment by nguyenalex836** [comment]
@revolter Thank you for opening an issue and linking it to your PR! ✨
