### ISSUE TITLE
Configuring content exclusions for GitHub Copilot looks different

### ISSUE THREAD

**Issue by StefMa** [github/docs#32396]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Its this one https://docs.github.com/en/copilot/managing-github-copilot-in-your-organization/configuring-content-exclusions-for-github-copilot
It doesn't contain a "In this article" section on the right.
Also it looks a bit different to the other sites.

I guess the problem is that the site has a `layout: inline` property. But I'm not sure with that 😅 

### What changes are you suggesting?

Make the site look like the others 🙃 

See diff:
<img src="https://github.com/github/docs/assets/10229883/90e87e7e-43f8-484b-a773-e685a9264257" width=380/>
<img src="https://github.com/github/docs/assets/10229883/ef25ad33-81d0-45a3-a1dd-befac57d4981" width=380/>
<img src="https://github.com/github/docs/assets/10229883/39c94a6d-c0e8-4420-a9e4-4465070e32d0" width=380/>

**Comment by nguyenalex836** [comment]
@StefMa Thanks so much for opening this issue! I'll get this triaged for review ✨

**Comment by hubwriter** [comment]
@StefMa - Thanks for raising this.

You're absolutely right, the difference here is the `layout: inline` property. This layout, with the "In this article" section pulled into the body text column, is to allow the text column to be wider to allow for the side-by-side code sample and explanation further down the page.

I'm going to close this as it's working as designed.

However, the screenshot you helpfully provided did allow me to see that the spacing above the "In this article" section is wrong, so I'll raise an internal issue to get that fixed.

Thanks again.
