### ISSUE TITLE
Minor typo: missing `>` in docs

### ISSUE THREAD

**Issue by roy-work** [github/docs#32401]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform#requesting-the-access-token

### What part(s) of the article would you like to see updated?

The article currently reads:

> `<example-workload-identity-provider>`: Replace this with the path to your identity provider in GCP. For example, `projects/<example-project-id>/locations/global/workloadIdentityPools/<name-of-pool/providers/<name-of-provider>`

In the portion after "For example", the text `<name-of-pool` lacks a closing `>`.

**Comment by nguyenalex836** [comment]
@roy-work Thanks so much for opening this issue! ✨ You, or anyone else, are welcome to submit a PR with this fix.

**Comment by conorheffron** [comment]
Successfully deployed changes

**Comment by nguyenalex836** [comment]
Apologies - it looks like we do not accept changes to content/actions/deployment/security-hardening-your-deployments. Going to close out this issue and file an issue for an internal fix 💛

**Comment by roy-work** [comment]
@nguyenalex836 There are a few more errors in this file that I've encountered:

* The article currently reads:

  > `<example-workload-identity-provider>`: Replace this with the path to your identity provider in GCP. For example, `projects/<example-project-id>/locations/global/workloadIdentityPools/<name-of-pool/providers/<name-of-provider>`
  
    AFAICT, `<example-project-id>` is wrong, and using the project ID will result in errors. That should read `<example-project-number>`, and I'd add additional prose to stress that fact, since the project ID is what most other interfaces to GCP use as input, so the requiring the project _number_ is inherently unusual. I spent a few hours tripped up on that …
    
* The example uses the action `google-github-actions/auth@v0.3.1`; this causes the workflow to log warnings similar to the following:
  > Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: google-github-actions/auth@v0.3.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

  `v2.1.2` of this action appears to exist, and doesn't log the warning. Perhaps it is time to update the example?

Could I trouble you to update that internal bug to include these, as well?

**Comment by nguyenalex836** [comment]
@roy-work Thank you for flagging those! I've just copied those notes over to our internal issue 💛
