### ISSUE TITLE
Correct mistranslation of 'folder' to 'file' in Japanese translation of Viewing a file page

### ISSUE THREAD

**Issue by nekonado** [github/docs#32415]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

### What part(s) of the article would you like to see updated?

- I would like to see the Japanese translation of the section titled "#ignore-commits-in-the-blame-view" to be updated.
- In the English version, it states: "In the root directory of your repository, create a file named .git-blame-ignore-revs." However, in the Japanese translation, it inaccurately translates "file" as "フォルダー (folder)" instead of "ファイル (file)."
- This change is important for accuracy and clarity. The correct translation will prevent confusion for Japanese-speaking users and ensure they follow the correct steps to create a file (.git-blame-ignore-revs) instead of a folder.
- The expected outcome is that the Japanese translation accurately reflects the English version, helping users understand and follow the instructions correctly. This will improve the usability and reliability of the documentation for Japanese-speaking users.

### Additional information

<details><summary>target</summary>
<p>

<img width="1912" alt="demo" src="https://github.com/github/docs/assets/94698042/61ecee1b-29dc-4cfa-b605-35a3d5e43493">

</p>
</details>

**Comment by nguyenalex836** [comment]
@nekonado Thanks for reaching out, and flagging this! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨
