### ISSUE TITLE
Need a better example for adding a project card using gh api

### ISSUE THREAD

**Issue by bernhold** [github/docs#32416]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/rest/projects/cards.md

### What part(s) of the article would you like to see updated?

There needs to be a better example of how to use gh api to add a project card that illustrates the differences between -F and -f arguments.  For example, adding an issue or pull request where the id number needs to be passed with a -F.

It took me several days of trial and error experimentation and googling before I hit on an example that even suggested that the integer id had to be passed with -F.  Extremely time consuming and frustrating.

**Comment by nguyenalex836** [comment]
@bernhold Thank you for opening this issue! I'll get this triaged for review ✨
