### ISSUE TITLE
Fixed language dropdown to navbar

### ISSUE THREAD

**Issue by warioddly** [github/docs#32438]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All pages
Chrome: Version123.0.6312.106 (64x)

### What changes are you suggesting?

Since dropdown has a static position, we need to replace them with position: fixed;
From:
![image](https://github.com/github/docs/assets/53710487/b1ec3dfe-a4b8-4e4e-abbb-3b64ea2f0991)

To
![image](https://github.com/github/docs/assets/53710487/3d6b3ebc-e0a9-41f2-9117-9caf3ed1b0a1)

**Comment by nguyenalex836** [comment]
@warioddly Thank you for opening this issue! ✨ Since we will need to fix this on our end, I have copied this issue internally. 

If you're looking for issues to work on, check out our [help wanted issues](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) 💛
