### ISSUE TITLE
Example to filter iteration by range is wrong

### ISSUE THREAD

**Issue by pscraire-philips** [github/docs#32431]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects#filtering-number-date-and-iteration-fields

### What changes are you suggesting?

What's in the doc:
> iteration:"Iteration 1".."Iteration 4" will show items in "Iteration 1", "Iteration 2", "Iteration 3", and "Iteration 4."

What's working: 
> iteration:"Iteration 1..Iteration 4" will show items in "Iteration 1", "Iteration 2", "Iteration 3", and "Iteration 4."

**Comment by sophietheking** [comment]
@pscraire-philips Thanks for catching this! This edit will need to be made to the `content/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects.md` file, you can make the edit as described in your issue.

You or anyone else is welcome to open a PR to make this change. 🔨

**Comment by pscraire-philips** [comment]
PR created: https://github.com/github/docs/pull/32470
