### ISSUE TITLE
Update documentation for GitHub Actions `runner` context to include the `environment` property

### ISSUE THREAD

**Issue by maskati** [github/docs#32443]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[GitHub Actions Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context)

### What part(s) of the article would you like to see updated?

The section for [runner context](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context) does not document the `environment` property which is:
- `github-hosted` for GitHub hosted runners
- `self-hosted` for self-hosted runners

**Comment by nguyenalex836** [comment]
@maskati Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
Hello @maskati 👋 ! Thank you for your patience while our team reviewed! Our team agrees it would be good to document this ✨ You, or anyone else, is welcome to submit a PR with updates to the documentation 💛

**Comment by Vijaykv5** [comment]
is this issue still opened?
if so I would love to contribute towards it!

**Comment by nguyenalex836** [comment]
@Vijaykv5 It is! Feel free to open a PR whenever you have some time 💛

**Comment by SoundaryaKoutharapu** [comment]
Hi @nguyenalex836,
I'd like to work on this issue, it would be great help if you could point me to the reusable file of runner context.

**Comment by nguyenalex836** [comment]
@SoundaryaKoutharapu You can find the folder of relevant reusables [here](https://github.com/github/docs/tree/main/data/reusables/actions) 💛

**Comment by Shamirdx** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> [GitHub Actions Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context)
> 
> ### What part(s) of the article would you like to see updated?
> The section for [runner context](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context) does not document the `environment` property which is:
> 
> * `github-hosted` for GitHub hosted runners
> * `self-hosted` for self-hosted runners
> 
> ### Additional information
> _No response_

Official Website
