### ISSUE TITLE
The workflow guide does not explicitly state that the .github directory must be in repository root.

### ISSUE THREAD

**Issue by anttilaiti** [github/docs#32458]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

### What changes are you suggesting?

Change "GitHub searches the .github/workflows directory in your repository for workflow files that are present in the associated commit SHA or Git ref of the event." to "GitHub searches the `.github/workflows` directory in the root of your repository for workflow files that are present in the associated commit SHA or Git ref of the event."

**Comment by anttilaiti** [comment]
Pull request here: https://github.com/github/docs/pull/32459

**Comment by nguyenalex836** [comment]
@anttilaiti Thank you for opening an issue and linking it to your PR! ✨
