### ISSUE TITLE
Issue with changing commit dates on GitHub

### ISSUE THREAD

**Issue by Mirzoev-Parviz** [github/docs#32502]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I've encountered an issue with the functionality of changing commit dates and times on GitHub. When a user changes the date and time on their computer and makes a commit, these changes are accepted without any errors, even if they are dated in the past. As a result, the user's profile displays incorrect information about the dates and times of their commits, which can lead to misunderstandings regarding the user's activity.

You can check a years of activity in my account: https://github.com/Mirzoev-Parviz

### What changes are you suggesting?

**Steps to reproduce**:
1. Set an incorrect date and time on the computer.
2. Make a commit in a repository on GitHub.

**Expected behavior**:
- The system should check the dates and times of commits and reject commits that are dated in the past.

**Actual behavior**:
- Commits dated in the past are accepted without any warnings or errors.

**Comment by sarbazvatanatan** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> I've encountered an issue with the functionality of changing commit dates and times on GitHub. When a user changes the date and time on their computer and makes a commit, these changes are accepted without any errors, even if they are dated in the past. As a result, the user's profile displays incorrect information about the dates and times of their commits, which can lead to misunderstandings regarding the user's activity.
> 
> You can check a years of activity in my account: https://github.com/Mirzoev-Parviz
> 
> ### What changes are you suggesting?
> **Steps to reproduce**:
> 
> 1. Set an incorrect date and time on the computer.
> 2. Make a commit in a repository on GitHub.
> 
> **Expected behavior**:
> 
> * The system should check the dates and times of commits and reject commits that are dated in the past.
> 
> **Actual behavior**:
> 
> * Commits dated in the past are accepted without any warnings or errors.
> 
> ### Additional information
> _No response_

**Comment by Moazzem-Hossain-pixel** [comment]
Thanks for your cooperation

**Comment by nguyenalex836** [comment]
Hi @Mirzoev-Parviz 👋 ! Thank you for reaching out to GitHub Docs!

Your question would best be handled by our wonderful [support team](https://support.github.com/request). Please reach out to them for assistance ✨ 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue 💛
