### ISSUE TITLE
Editing 'Creating a pull request' doc for clarity and flow

### ISSUE THREAD

**Issue by lilventi** [github/docs#3250]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

### What part(s) of the article would you like to see updated?

I would like to improve the writing for clarity and flow. A bit of technical editing could make the page more user-friendly and help it read better. 
### Additional information

[see page]

**Comment by ajs256** [comment]
Hey there @lilventi! You can open a pull request to improve the page. The simplest way to do this is to use [the web editor](https://github.com/github/docs/edit/main/content/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request.md) to make your changes. Feel free to mention me if you have any questions 😃

**Comment by janiceilene** [comment]
It looks like we forgot to close this one with the accompanying PR 💛
