### ISSUE TITLE
GitHub Actions: Building and testing Ruby – hash or tag in in "uses" step?

### ISSUE THREAD

**Issue by dentarg** [github/docs#3252]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/guides/building-and-testing-ruby

### What part(s) of the article would you like to see updated?

The article, in its examples, is using both `uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0` (full SHA) and `uses: ruby/setup-ruby@v1` (tag), which one should it be?

### Additional information

I think using the `v1` tag in all examples would be the best. This was recently touched on in https://github.com/actions/starter-workflows/pull/758. It was also discussed at length in https://github.com/actions/starter-workflows/pull/448 a while back.

**Comment by dentarg** [comment]
There's also discussion about full SHA vs tag in https://github.com/actions/starter-workflows/pull/709

**Comment by eregon** [comment]
I agree `@v1` is what most users should use, and if they really care about security they should probably pin everything down to a sha, but that seems very extreme and inconvenient, so I guess <1% users would do that.

**Comment by FelipeF1198** [comment]
Fffg

**Comment by FelipeF1198** [comment]
Rrrrrf

**Comment by lee-dohm** [comment]
Hello @dentarg, thanks for reaching out!

It appears that this has been corrected in the intervening time between when you opened this and now. I'm going to go ahed and close this, but feel free to let me know if I missed something!

Thanks again!
