### ISSUE TITLE
Link to .NET NuGet caching recommendations via setup-dotnet

### ISSUE THREAD

**Issue by SeanKilleen** [github/docs#32538]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

`content/actions/using-workflows/caching-dependencies-to-speed-up-workflows.md`

### What part(s) of the article would you like to see updated?

Adding the existing references for .NET's NuGet manager via `setup-dotnet`, like the other libraries.

**Comment by nguyenalex836** [comment]
@SeanKilleen Thank you for opening an issue and linking it to your PR! ✨
