### ISSUE TITLE
Lack of clarity re: reusable workflow `outputs`

### ISSUE THREAD

**Issue by APCBoston** [github/docs#32543]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow

### What part(s) of the article would you like to see updated?

The existing text is not clear that the workflow level `outputs:` may be mapped to job-level, but not step-level outputs.  The example workflow maps step-level outputs to job-level outputs, then to workflow-level outputs, but the text does not explain that this is needed and that attempting to map workflow-level outputs directly to step-level outputs won't work.  Attempts to use step-level outputs do not generate an error but pass an empty output to the caller, compounding the confusion.

### Additional information

A proposed clarification will follow momentarily in the form of a PR.

**Comment by nguyenalex836** [comment]
@APCBoston Thank you for opening an issue and linking it to your PR! ✨
