### ISSUE TITLE
Callouts outdated formatting in Style Guide

### ISSUE THREAD

**Issue by johnnygerard** [github/docs#32554]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

In the [Formatting Callouts](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#formatting-callouts) section of the Style Guide, the code snippets seem to use an outdated format that does not currently render.

Here is a test to see how it currently renders:

Tip:
> [!TIP] Here's a suggestion.

Note:
> [!NOTE] Keep this in mind.

Warning:
> [!WARNING] Be careful.

Danger:
> [!DANGER] Be extremely careful.

Now with correct format (multiple lines instead of one and CAUTION instead of DANGER):

Tip:
> [!TIP]
> Here's a suggestion.

Note:
> [!NOTE]
> Keep this in mind.

Warning:
> [!WARNING]
> Be careful.

Caution:
> [!CAUTION]
> Be extremely careful.

### What changes are you suggesting?

Update format:

Replace

```markdown
> [!TIP] Here's a suggestion.
```

with

```markdown
> [!TIP]
> Here's a suggestion.
```

and replace

```markdown
> [!DANGER] Be extremely careful.
```

with

```markdown
> [!CAUTION]
> Be extremely careful.
```

**Comment by nguyenalex836** [comment]
@johnnygerard Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by sophietheking** [comment]
@johnnygerard 👋 Thanks for opening this issue and contributing to our Docs. Interesting, it seems like the snippet from the Style Guide does work on our docs.github.com, but not on github.com. 🤔 But both work on the Docs site, so I think we should make the change you suggested! ✨ 

We welcome you (or anyone else) to open a pull request to make these changes! Check out our [contributing documentation](https://docs.github.com/en/contributing/collaborating-on-github-docs/about-contributing-to-github-docs) for help along the way if needed. 🔨
