### ISSUE TITLE
Inconsistent usages of `ACTIONS_ID_TOKEN_REQUEST_TOKEN` and `ACTIONS_RUNTIME_TOKEN`

### ISSUE THREAD

**Issue by jiasli** [github/docs#32573]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers

### What part(s) of the article would you like to see updated?

First it says using environment variable `ACTIONS_ID_TOKEN_REQUEST_TOKEN`:

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings

> Using environment variables on the runner (`ACTIONS_ID_TOKEN_REQUEST_URL` and `ACTIONS_ID_TOKEN_REQUEST_TOKEN`).

Later on, it says using `ACTIONS_RUNTIME_TOKEN`:
 
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#using-custom-actions

> Alternatively, you can use the following environment variables to retrieve the token: `ACTIONS_RUNTIME_TOKEN`, `ACTIONS_ID_TOKEN_REQUEST_URL`.

I checked in an actual run and saw they contain the same value, but the document should be consistent on which environment variable should be used.

**Comment by nguyenalex836** [comment]
@jiasli Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by azanhayat** [comment]
https://vt.tiktok.com/ZSFvVeFws/

**Comment by A111one** [comment]
Thanks for

**Comment by t-me-c-2093488272-77** [comment]
👌

**Comment by t-me-c-2093488272-77** [comment]
Thanks

**Comment by t-me-c-2093488272-77** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers
> 
> ### What part(s) of the article would you like to see updated?
> First it says using environment variable `ACTIONS_ID_TOKEN_REQUEST_TOKEN`:
> 
> https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
> 
> > Using environment variables on the runner (`ACTIONS_ID_TOKEN_REQUEST_URL` and `ACTIONS_ID_TOKEN_REQUEST_TOKEN`).
> 
> Later on, it says using `ACTIONS_RUNTIME_TOKEN`:
> 
> https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#using-custom-actions
> 
> > Alternatively, you can use the following environment variables to retrieve the token: `ACTIONS_RUNTIME_TOKEN`, `ACTIONS_ID_TOKEN_REQUEST_URL`.
> 
> I checked in an actual run and saw they contain the same value, but the document should be consistent on which environment variable should be used.
> 
> ### Additional information
> _No response_

**Comment by lucavallin** [comment]
`ACTIONS_ID_TOKEN_REQUEST_URL`([results](https://github.com/search?q=org%3Agithub+ACTIONS_ID_TOKEN_REQUEST_URL&type=code)) and `ACTIONS_ID_TOKEN_REQUEST_TOKEN` ([results](https://github.com/search?q=org%3Agithub+ACTIONS_ID_TOKEN_REQUEST_TOKEN&type=code)) seem the most common to me based on how they're used in the code and docs. `ACTIONS_RUNTIME_TOKEN` is used less often and seemingly more for "internal stuff".

I'd like @github/actions-runtime opinion on this to double-check.
