### ISSUE TITLE
allow_forking field is missing from the example response for get_repository

### ISSUE THREAD

**Issue by clbouton** [github/docs#32571]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository

### What part(s) of the article would you like to see updated?

In the example response and schema provided, there is no `allow_forking` field, despite this being a field returned by the api. For example, check the [api query](https://api.github.com/repos/github/docs) for this repo. `allow_forking` is provided and set to `true`.

**Comment by kamjes** [comment]
Hi all


-- 
Karol Jesionka aka KAMJE

Włącz 18 kwietnia 2024 w 02:42:05, clbouton ***@***.***)
Napisał:

**Comment by nguyenalex836** [comment]
@clbouton Thank you for submitting this issue, and raising a flag on this! ✨ This portion of the documentation will need to be fixed internally. I've created an internal issue for our team to review, and will close out this issue 💛
