### ISSUE TITLE
docs(github actions): steps context not listed in job environment url

### ISSUE THREAD

**Issue by johnnygerard** [github/docs#32603]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Under [jobs.<job_id>.environment](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment), it says:

> The value of url can be an expression. Allowed expression contexts: [github](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), [inputs](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context), [vars](https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context), [needs](https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context), [strategy](https://docs.github.com/en/actions/learn-github-actions/contexts#strategy-context), [matrix](https://docs.github.com/en/actions/learn-github-actions/contexts#matrix-context), [job](https://docs.github.com/en/actions/learn-github-actions/contexts#job-context), [runner](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context), and [env](https://docs.github.com/en/actions/learn-github-actions/contexts#env-context).

The steps context is not listed despite being used in the example below:

```yaml
environment:
  name: production_environment
  url: ${{ steps.step_id.outputs.url_output }}
```

### What changes are you suggesting?

Add **steps** to the list of allowed expression contexts.

**Comment by nguyenalex836** [comment]
@johnnygerard Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by SiaraMist** [comment]
Thank you for opening this issue @johnnygerard! ✨ This update to the docs makes sense to me. You are anyone else is free to open a pull request to make these changes.
