### ISSUE TITLE
About GitHub-hosted runners article contains wrong information about the macOS version of `macos-latest`

### ISSUE THREAD

**Issue by Brezak** [github/docs#32618]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

### What part(s) of the article would you like to see updated?

Specifically the [table](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) in Standard GitHub-hosted runners for Public repositories says that `macos-latest` uses the macOS 14 runner image. This seems to be wrong as the [table](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners) in the documentation for `runs-on` specifies that `macos-latest` is actually using the macOS 12 runner image.

**Comment by nguyenalex836** [comment]
@Brezak Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by SiaraMist** [comment]
Hey @Brezak, thank you for opening this issue!

You are right, the information in these articles does not match. 👍 However, the documentation for `runs-on` that you linked is the article that is out of date. I'm going to open a PR to address this, and will come back and update you when those changes are live. Thank you again!

**Comment by SiaraMist** [comment]
The [`runs-on` doc](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners) has been updated to use the right image for `macos-latest`.
