### ISSUE TITLE
Please provide a sub-command for gh (GitHub CLI) to check the integrity and health of a given repo

### ISSUE THREAD

**Issue by Nefcanto** [github/docs#32625]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://cli.github.com/manual/gh_repo

### What part(s) of the article would you like to see updated?

I need to run `gh repo check` command and get a yes/no or a boolean answer that makes sure this repo is clone completely (for large repos internet outage can mean partial cloning sometimes), and it's not tampered with and other health stuff.

**Comment by nguyenalex836** [comment]
Hi @Nefcanto 👋 ! This question would best be handled by our wonderful [support team](https://support.github.com/request). Please reach out to them for assistance ✨ 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue 💛
