### ISSUE TITLE
GitHub warning when leaving page doesn't work on Firefox when moving back page

### ISSUE THREAD

**Issue by S5NC** [github/docs#32646]
### What article on docs.github.com is affected?

Lost so much work due to this, open file in repository, edit it in web, press back arrow in Firefox, Firefox asks "This page is asking you to confirm that you want to leave — information you’ve entered may not be saved.", I press "Stay on Page", options were that or "Leave Page", GitHub then asks "You have unsaved changes. Do you want to discard them?", I say "Cancel", options were that or "OK" but the page leaves anyway, losing entered work. No options can prevent loss in this case. GitHub shouldn't ask to leave the page if Firefox prevents it. There is an issue here.

### What part(s) of the article would you like to see updated?

Warn of this issue or fix it.

**Comment by nguyenalex836** [comment]
@S5NC We're sorry you experienced this issue! This would best be handled by our wonderful [support team](https://support.github.com/request). Please reach out to them, and they'll be happy to assist you 💛 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue ✨
