### ISSUE TITLE
Go action version is out of date and emits warnings

### ISSUE THREAD

**Issue by topfunky** [github/docs#32684]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Documentation on this page include code snippets for `actions/setup-go@v4`. Using this version emits warnings when the action runs (about outdated Node.js). Upgrading to `v5` fixes the warnings so that it runs cleanly.

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

### What changes are you suggesting?

Upgrade documentation to mention `v5` instead of `v4`

### Additional information

The boilerplate Go action that is suggested on GitHub when starting Go projects is also outdated.

**Comment by nguyenalex836** [comment]
@topfunky Thank you for opening an issue and linking it to your PR! ✨

**Comment by bulutuu** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).
>
