### ISSUE TITLE
No list of permissions

### ISSUE THREAD

**Issue by manchicken** [github/docs#32715]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I'm reporting content which is missing

### What part(s) of the article would you like to see updated?

There are a number of different permissions systems in GitHub:

- Webhooks
- Apps
- OAuth apps
- Fine-grained PATs
- Classic PATs
- Webhooks
- Actions

There are no documents specifically explaining each of the permissions. The impact of this is that administrators of various orgs need to spend an awful lot of time trying to fully understand the impact of the permissions that they're looking at.

For example, if I make a Classic PAT token which can read the contents of a private repository, I have to keep digging in order to know that this same PAT with that permission could also be used to read issues and PRs. This is made even more confusing by the fact that the different permissions schemes have overlap.

I recommend adding a new page for each permission scheme, outlining which permissions are available, what they grant access to (comprehensively), and maybe a short set of bullet-points for potential unintended consequences.

### Additional information

Right now all of the apps permissions documents speak to the UI to create them (e.g. "Pull Requests" » "Read"), but not the code presentation of them (e.g. `pull_requests: read`).

I have personally spent hours trying to understand the full implication of permissions-related requests and decisions, and the document I'm recommending here would have saved me so much time. I doubt I'm the only one.

**Comment by nguyenalex836** [comment]
@manchicken Thank you for opening this issue! Quick question - did you mean to list "webhooks" twice in our list? Was one meant to reference a specific type of webhook? In the meantime, I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@manchicken Thank you for opening this issue! Quick question - did you mean to list "webhooks" twice in your list? Was one meant to reference a specific type of webhook? In the meantime, I'll get this triaged for review ✨

**Comment by manchicken** [comment]
Hah! There are a lot of permissions associated with Webhooks, and I would be surprised if there were only two sets of them, but I didn't mean to duplicate the items in the list.

This is a multitasking fail.

**Comment by nguyenalex836** [comment]
@manchicken No problem! Just thought I'd check - thanks for clarifying 😄

**Comment by skedwards88** [comment]
Thanks for this issue! This is a big issue that is probably better for us to tackle internally, so I'm going to close it and pass it to the team. However, some context to help you out:

- GitHub Apps: For the REST API, the documentation for each endpoint as well as [Permissions required for GitHub Apps](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps) should help. 
- Fine-grained PATs: For the REST API, the documentation for each endpoint as well as [Permissions required for fine-grained personal access tokens](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens) should help. 
- Webhooks: I don't think that webhooks have permissions. (Although the permissions of a GitHub App determine which webhook events the app can subscribe to. These permission requirements are listed in [Webhook events and payloads](https://docs.github.com/en/webhooks/webhook-events-and-payloads))
- OAuth apps: These use scopes which are poorly and broadly defined. This is one of the reasons that we encourage you to use GitHub Apps instead.
- Classic PATs: These use scopes which are poorly and broadly defined. This is one of the reasons that we encourage you to use fine-grained PATs instead.
- Actions: (Presumably the built-in GITHUB_TOKEN) This is something that we are working to define better

**Comment by manchicken** [comment]
I appreciate that. Please understand that not having a comprehensive and complete list of permissions seems likely to result in miscalculation and confusion on the part of security professionals, and security-minded engineers. It just takes so much work to investigate a permissions change, and you have to try to guess which APIs the apps will call, or the jobs responding to Webhooks would need.

It's just a lot.

Especially since fine-grained PATs are still in beta, and they're not terribly well understood, it's unlikely that many will find them terribly useful.

I do hope that GitHub will commit to making a comprehensive and definitive table of permissions—and what they mean—available shortly, and I look forward to reading it.
