### ISSUE TITLE
Getting started with Github Copilot extension 

### ISSUE THREAD

**Issue by ransagy** [github/docs#32761]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/using-github-copilot/getting-started-with-github-copilot

### What part(s) of the article would you like to see updated?

The extension was renamed on the product level from "Github Copilot" to "Github Copilot Completions" and thus the text and images refer to a non-existing name.

**Comment by nguyenalex836** [comment]
@ransagy Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by mdell-seradex** [comment]
I noticed this as well, along with the fact that there is another extension named "GitHub Copilot Chat".
It also seems that both of these extensions will not be needed to be installed if VS 17.10 or higher is used.

**Comment by hubwriter** [comment]
Thank you @ransagy and @mdell-seradex 

Yes, the Visual Studio information in the article "[Getting started with GitHub Copilot](https://docs.github.com/en/copilot/using-github-copilot/getting-started-with-github-copilot?tool=visualstudio)" needs to be updated.

From Visual Studio 2022 version 17.10 Preview 3, GitHub Copilot (both completions and chat) is included as a recommended component - details here: https://learn.microsoft.com/en-us/visualstudio/ide/visual-studio-github-copilot-install-and-states?view=vs-2022#get-github-copilot-for-visual-studio-2022-version-1710-preview-3-or-later

For 17.8 and 17.9, to get both completions and chat, you need to download both of these from the marketplace and install them:

* GitHub Copilot Completions (https://marketplace.visualstudio.com/items?itemName=GitHub.copilotvs)
* GitHub Copilot Chat (https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.VSGitHubCopilot)
