### ISSUE TITLE
"Contributing to a project" documentation is not clear what to do if your fork already exists.

### ISSUE THREAD

**Issue by EdwardLaird1** [github/docs#32780]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

### What changes are you suggesting?

Add instructions what to do if you have forked the repository in the past (i.e., don't make a new fork because you can't; instead sync your existing fork.). The current doc doesn't explain this.

**Comment by nguyenalex836** [comment]
@EdwardLaird1 Thank you for opening an issue and linking it to your PR! ✨
