### ISSUE TITLE
updating the document Add a repository to an app installation - rest api

### ISSUE THREAD

**Issue by githubofkrishnadhas** [github/docs#32792]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This is the url: https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#add-a-repository-to-an-app-installation

so basically this end point is used when a folk is trying to porgrammatically add a repo or multiple repos to github app.

![image](https://github.com/github/docs/assets/108367225/e2610e82-1a82-4dea-b330-3180b7d72b25)

This hasn't specified what methods of authentication will work for this end point : PUT
/user/installations/{installation_id}/repositories/{repository_id}

### What part(s) of the article would you like to see updated?

i would really appreciate if you can add 
* use personal access token with repos permissions

This particular missing piece caused me weeks of hardship trying to find out what i am missing or what i am doing wrong or a bug or what.

### Additional information

The above piece could help other developers life much easy

**Comment by githubofkrishnadhas** [comment]
i have tried to understand the automatic ways of setting up the documentation for github docs. still needs improvement on an everest level.

This can definitely help out many developers who reads the docs 💯

**Comment by nguyenalex836** [comment]
@githubofkrishnadhas Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by 2-1984-iam** [comment]
I need advice and genuine support

**Comment by githubofkrishnadhas** [comment]
> @githubofkrishnadhas Thank you for opening this issue! I'll get this triaged for review ✨

Thanks. really appreciate it

**Comment by githubofkrishnadhas** [comment]
Hello @nguyenalex836  hope you are doing good. let me know if you have any updates

**Comment by nguyenalex836** [comment]
@githubofkrishnadhas Hello! 👋 No new updates yet, but you will be the first to know once our team has reviewed 💛
