### ISSUE TITLE
Team names required syntax when used for CODEOWNERS file

### ISSUE THREAD

**Issue by OsirisTerje** [github/docs#32812]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This one about creating a team doesn't state the allowed syntax for a team name:  https://docs.github.com/en/organizations/organizing-members-into-teams/creating-a-team
And this page on CODEOWNERS, https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax, doesn't mention it either.

### What part(s) of the article would you like to see updated?

A section on syntax for team names should be added.

A team name with '.' included is not allowed in a CODEOWNERS file, resulting in the following error:
![image](https://github.com/github/docs/assets/203432/a902cbfa-5006-40b8-8873-b52f47391b7f)

and the error description points to the characters from the dot to the end.

I would assume that casing of the team name is also critical.  There might also be other non-allowed characters besides those mentioned on the CODEOWNERs page.

### Additional information

This would affect all organizations that are using team names with dots.  

This syntax is correct:
![image](https://github.com/github/docs/assets/203432/8e571fc4-2584-4146-91b9-35d84dec10e8)

**Comment by nguyenalex836** [comment]
@OsirisTerje Thank you for opening this issue! I'll get this triaged for review ✨
