### ISSUE TITLE
github repository names are, in fact, not case-sensitive

### ISSUE THREAD

**Issue by jsoref** [github/docs#32838]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors#check-your-spelling

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/03e61d2414c57977d533255060fa59d375ee4421/content/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors.md?plain=1#L101

>  Typos happen, and repository names are case-sensitive.  If you try to clone `git@{% data variables.command_line.codeblock %}:user/repo.git`, but the repository is really named `User/Repo` you will receive this error. 

This is false. 

### Additional information

```sh
% git clone git@github.com:community/community.git --depth 1 --no-tags
Cloning into 'community'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 52 (delta 20), reused 21 (delta 7), pack-reused 0
Receiving objects: 100% (52/52), 32.60 KiB | 1.36 MiB/s, done.
Resolving deltas: 100% (20/20), done.
```

```sh
% git clone git@github.com:cOmMuNiTy/CoMmUnItY.git --depth 1 --no-tags
Cloning into 'CoMmUnItY'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 52 (delta 20), reused 21 (delta 7), pack-reused 0
Receiving objects: 100% (52/52), 32.61 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (20/20), done.
```

**Comment by nguyenalex836** [comment]
@jsoref Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by P3k0pl** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors#check-your-spelling
> 
> ### What part(s) of the article would you like to see updated?
> https://github.com/github/docs/blob/03e61d2414c57977d533255060fa59d375ee4421/content/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors.md?plain=1#L101
> 
> > Typos happen, and repository names are case-sensitive.  If you try to clone `git@{% data variables.command_line.codeblock %}:user/repo.git`, but the repository is really named `User/Repo` you will receive this error.
> 
> This is false.
> 
> ### Additional information
> ```shell
> % git clone git@github.com:community/community.git --depth 1 --no-tags
> Cloning into 'community'...
> remote: Enumerating objects: 52, done.
> remote: Counting objects: 100% (52/52), done.
> remote: Compressing objects: 100% (44/44), done.
> remote: Total 52 (delta 20), reused 21 (delta 7), pack-reused 0
> Receiving objects: 100% (52/52), 32.60 KiB | 1.36 MiB/s, done.
> Resolving deltas: 100% (20/20), done.
> ```
> 
> ```shell
> % git clone git@github.com:cOmMuNiTy/CoMmUnItY.git --depth 1 --no-tags
> Cloning into 'CoMmUnItY'...
> remote: Enumerating objects: 52, done.
> remote: Counting objects: 100% (52/52), done.
> remote: Compressing objects: 100% (44/44), done.
> remote: Total 52 (delta 20), reused 21 (delta 7), pack-reused 0
> Receiving objects: 100% (52/52), 32.61 KiB | 1.42 MiB/s, done.
> Resolving deltas: 100% (20/20), done.
> ```

**Comment by P3k0pl** [comment]
% git clone git@github.com:cOmMuNiTy/CoMmUnItY.git --depth 1 --no-tags
Cloning into 'CoMmUnItY'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 52 (delta 20), reused 21 (delta 7), pack-reused 0
Receiving objects: 100% (52/52), 32.61 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (20/20), done.

**Comment by Tinneke40** [comment]
Ik begrijp het niet ik ken er Nils van ik weet alleen dat mijn gsm heel raar doet bv als ik op trackingsbeveiliging druk doet mijn gsm niets en iemand anders blijft zich inloggen op mijn google account hoe veel ik mijn paswoord ook verander het helpt niet

**Comment by Tinneke40** [comment]
Ik begrijp er niets van

Op wo 8 mei 2024 05:55 schreef P3k0pl ***@***.***>:

**Comment by yasser01147310161** [comment]
gh repo clone Shopify/hydrogen

**Comment by stevecat** [comment]
Hey @jsoref, thanks for opening this! ✨ It looks like this *was* the case at some point many years ago but the docs were never updated when this changed.

I think we can just remove that entire line from the article. You (or anyone else!) is very welcome to open a PR to make this change!

**Comment by stevecat** [comment]
I think the existing content, once the first line is removed, serves this section well:

> To avoid this error, when cloning, always copy and paste the clone URL from the repository's page. For more information, see "[Cloning a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository)."
> 
> To update the remote on an existing repository, see "[Managing remote repositories](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories)".

A homograph would be two words that sound the same but are spelt differently (close/close). I understand what you mean about characters that can look alike and be confusing (I, l, and 1 as you suggested) but I think the existing suggestion to copy/paste covers this. We're usually wary of adding more content than is necessary. If I've misunderstood, feel free to open your PR with the example and we can review it! ✨

**Comment by jsoref** [comment]
Sorry. I meant homoglyph.

**Comment by Pegasusc4** [comment]
Loveyou😍😍😍😍
