### ISSUE TITLE
Add Known Limitation for github.dev exceeding GraphQL rate limits 

### ISSUE THREAD

**Issue by 1fabi0** [github/docs#32854]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[the-githubdev-web-based-editor.md](https://github.com/github/docs/blob/main/content/codespaces/the-githubdev-web-based-editor.md)

### What part(s) of the article would you like to see updated?

Known Limitations don't list the exceeding of the github GraphQL Rate Limit.
This often happens when intesively write documentation on the web-editor or write code. 

### Additional information

![image](https://github.com/github/docs/assets/58549442/680abba0-a0b9-47a4-9067-7c3ff6bb2633)
the result is that sometimes commits can't be done and a fix is to wait a few minutes for the api rate limit to reset

**Comment by nguyenalex836** [comment]
@1fabi0 Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by wyatterp365** [comment]
![share (5)](https://github.com/github/docs/assets/166349624/43dd23dc-5ae5-4355-ad3c-105a0e2bdfb7)

**Comment by skedwards88** [comment]
Thanks for this issue! You or anyone else is welcome to open a PR to add this to the "[Known limitations](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor#known-limitations)" section.

**Comment by CBID2** [comment]
> Thanks for this issue! You or anyone else is welcome to open a PR to add this to the "[Known limitations](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor#known-limitations)" section.

Hi @skedwards88! :) I just made a PR for this. It's #33140.
