### ISSUE TITLE
response schema provided as a sapmle and actual api output is differnt

### ISSUE THREAD

**Issue by githubofkrishnadhas** [github/docs#32884]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

i was going through https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories 

i was doing an automation on enabling codeql analysis on repos https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28, which are not enabled. for that i was running repositories api first to check for the repo dependabot, secret scanning are enabled or not.

i see the sample api response back like 
![image](https://github.com/github/docs/assets/108367225/a079e629-1dcf-488f-94f1-a8e5d2693f56)

`
 "security_and_analysis": {
      "advanced_security": {
        "status": "enabled"
      },
      "secret_scanning": {
        "status": "enabled"
      },
      "secret_scanning_push_protection": {
        "status": "disabled"
      }
    }
    
 
`
but the actual response getting back is differnt

`
    "security_and_analysis": {
        "secret_scanning": {
            "status": "disabled"
        },
        "secret_scanning_push_protection": {
            "status": "disabled"
        },
        "dependabot_security_updates": {
            "status": "disabled"
        },
        "secret_scanning_validity_checks": {
            "status": "disabled"
        }
    }
`

i donot see this `"advanced_security": {
        "status": "enabled"
      },` instead `,
        "secret_scanning_validity_checks": {
            "status": "disabled"
        }, "secret_scanning": {
            "status": "disabled"
        },` are available. I urge you to adjust these as these can mislead developers.

### What part(s) of the article would you like to see updated?

Please make necessary changes on the response section 
* example response 
* response schema

![image](https://github.com/github/docs/assets/108367225/e4e4d7a4-8943-468f-9343-1b051c5fd630)

### Additional information

Hope the above details are good enough.

**Comment by nguyenalex836** [comment]
@githubofkrishnadhas Thank you for submitting this issue, and raising a flag on this! ✨ This portion of the documentation will need to be fixed internally. I've created an internal issue for our team to review, and will close out this issue 💛

**Comment by githubofkrishnadhas** [comment]
Thanks.i would be happy if you can add the issue id on pr 😉
