### ISSUE TITLE
Understanding GitHub Actions

### ISSUE THREAD

**Issue by ivanwalsh** [github/docs#32927]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#the-components-of-github-actions

### What part(s) of the article would you like to see updated?

Minor typo. In second sentence, an is missing after For example,.
Current
An event is a specific activity in a repository that triggers a workflow run. For example, activity can etc. 
Suggested Text
An event is a specific activity in a repository that triggers a workflow run. For example, an activity can etc.

### Additional information

Just a minor typo on that page.

**Comment by nguyenalex836** [comment]
@ivanwalsh Thank you for opening this issue! ✨ You, or anyone else, is welcome to open a PR to fix this 💛

**Comment by Hanyxhzuz** [comment]
Good

**Comment by Hanyxhzuz** [comment]
Good
