### ISSUE TITLE
Add missing `CNAME` DNS record creation instruction

### ISSUE THREAD

**Issue by revolter** [github/docs#32932]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain-and-the-www-subdomain-variant

**Comment by nguyenalex836** [comment]
@revolter Thank you for opening an issue and linking it to your PR! ✨
