### ISSUE TITLE
Markdown syntax alerts section blockquote nested in list [unexpected behavior bug or feature?]

### ISSUE THREAD

**Issue by souovan** [github/docs#32959]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Markdown Syntax section [Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)

Hi y'all i don't know if this is a bug or a feature but i tried to use Alerts on a nested blockquote section and it didn't work as expected

code:

```md
* Recomendado usar UUID quando configurar montagem automática no `/etc/fstab`

  >[!IMPORTANT]
  > ```bash
  > # Exemplo de configuração /etc/fstab (note que é preciso adicionar defaults,x-systemd.requires=stratisd.service)
  > UUID=<id>	/camadas/fs1	xfs	defaults,x-systemd.requires=stratisd.service	0 0
  > 
  > # Após adicionar entrada do stratis no arquivo /etc/fstab utilizar
  > systemctl daemon-reload
  > ```
```

result:
![image](https://github.com/github/docs/assets/42985246/3884948c-7019-4b7c-885f-8d47201ed2a9)

### What changes are you suggesting?

* Inform in the docs what behavior to expect when using blockquote nested in a list

**Comment by nguyenalex836** [comment]
@souovan Hello! 👋 Thank you for opening this issue! 

This question would best be handled by our wonderful [support team](https://support.github.com/request). Please reach out to them, and they'll be happy to assist with the expected behavior regarding those alerts 💛
