### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by omvjro** [github/docs#32976]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

<details>
<summary>Collapsed</summary>
https://github.com/github/docs/blob/main/content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller.md
https://github.com/github/docs/blob/main/content/actions/migrating-to-github-actions/automated-migrations/automating-migration-with-github-actions-importer.md
https://github.com/github/docs/blob/main/content/actions/migrating-to-github-actions/automated-migrations/migrating-from-circleci-with-github-actions-importer.md
https://github.com/github/docs/blob/main/content/apps/github-marketplace/listing-an-app-on-github-marketplace/deleting-your-app-listing-from-github-marketplace.md
https://github.com/github/docs/blob/main/content/apps/oauth-apps/using-oauth-apps/connecting-with-third-party-applications.md
https://github.com/github/docs/blob/main/content/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning.md
https://github.com/github/docs/blob/main/content/code-security/dependabot/working-with-dependabot/managing-dependabot-on-self-hosted-runners.md
https://github.com/github/docs/blob/main/content/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-security-and-analysis-settings-for-your-organization.md
https://github.com/github/docs/blob/main/data/reusables/actions/creating-a-runner-group-for-an-organization.md</details>

### What part(s) of the article would you like to see updated?

There are some duplicated words to be deleted, e.g. _for, and, to_.
Also, in content/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning.md, `a additional` → `an additional`.

### Additional information

There are such typos in non-markdown files, I'm not sure whether to fix them but I'm willing to commit changes if necessary.

**Comment by nguyenalex836** [comment]
@omvjro Apologies on behalf of our bot! Thank you so much for opening this issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
Closing this issue as https://github.com/github/docs/issues/32977 appears to have been opened in its place 💛
