### ISSUE TITLE
[feature request] allow readers to ask inline questions on docs

### ISSUE THREAD

**Issue by hamirmahal** [github/docs#32986]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All of them

### What changes are you suggesting?

I think it'd be useful if readers could select specific lines in an article, and ask questions about them, kind of like we can select specific lines in code review and comment on them.

A Google Docs-style comments interface could be helpful here, where readers sign in via their GitHub account to make comments or answer other people's questions.

**Comment by nguyenalex836** [comment]
Hi @hamirmahal! 👋 The best place to send your feedback regarding this feature request is to https://github.com/github/feedback/discussions ✨ 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue in this repo 💛
