### ISSUE TITLE
Remove unnecessary ellipses at the end of step

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33027]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/start-your-journey/hello-world#step-3-make-and-commit-changes

### What part(s) of the article would you like to see updated?

> Click **Commit changes...**.

The ellipses at the end of this step should be removed as it is unnecessary

**Comment by SHREERAAM-sys** [comment]
@nguyenalex836 I will contribute to this issue

**Comment by Saurabh-Daware** [comment]
Please close this issue as it is fixed in #33047.

**Comment by nguyenalex836** [comment]
Great catch @Saurabh-Daware ✨
