### ISSUE TITLE
Outdated note

### ISSUE THREAD

**Issue by Denis-GH** [github/docs#33078]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-assignment-from-a-template-repository#:~:text=In%20January%202024%2C%20GitHub%20Classroom%20will%20change%20the%20way%20student%20repositories%20are%20created%20from%20starter%20code%20repositories

### What part(s) of the article would you like to see updated?

Here is a sentence, "In January 2024, GitHub Classroom **will** change the way...".
But January 2024 has already passed, so we can't talk about it in the future tense

### Additional information

it uses a reusable file - https://github.com/github/docs/blob/main/data/reusables/classroom/note-on-assignment-changes.md

**Comment by nguyenalex836** [comment]
@Denis-GH Apologies for our overzealous bot - thanks so much for opening this issue! I'll get this triaged for review ✨

**Comment by subatoi** [comment]
Thanks for raising this, @Denis-GH—you're correct and the text in the reusable should be changed to the past tense. You or anyone else is welcome to open a PR with this change.
