### ISSUE TITLE
bash block in `Adding a system path` seems errant

### ISSUE THREAD

**Issue by jsoref** [github/docs#33084]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path

### What part(s) of the article would you like to see updated?

```bash
echo "{path}" >> $GITHUB_PATH
```

### Additional information

This block seems errant. It's incorrect. It won't do what the user is trying to achieve and won't do the other thing that the user could be interested in considering.

The simplest resolution would be to remove the block entirely.

I'm not sure what was intended, and I have a headache, so I'm going to leave things at that.

**Comment by jsoref** [comment]
quite a few examples in this file use `{value}` instead which would be less confusing, as it would be slightly more obvious to a user that it's a thing that should be substituted, whereas `{path}` is very close to `${path}` which is a bash notation for an expansion of a variable named `path`.

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening a PR! I'll get this triaged for review ✨

**Comment by derbo1** [comment]
echo "{path}" >> $GITHUB_PATH لا اله الا الله محمد رسول الله

**Comment by subatoi** [comment]
@jsoref 👋 Thanks for your contribution and as ever, thanks for opening an issue first. You're correct about that block and I agree with you that the simplest solution would be to remove it. For the sake of keeping this issue on the named topic, you or anyone else is welcome to open a PR with that change.

I agree with you in principle about the placeholders in the rest of the article, but I'd prefer to handle that separately, and we're happy to discuss that with you in a new issue if you're interested. This article doesn't conform to our new(ish) guidance on placeholders, so we'd look to update it to do that: https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#placeholders
