### ISSUE TITLE
doc: fix secret availability wording in codespace docs

### ISSUE THREAD

**Issue by zisuu** [github/docs#33121]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/codespaces/developing-in-a-codespace/creating-a-codespace-for-a-repository.md

### What part(s) of the article would you like to see updated?

there are some sentences what make no sense because two times the word "be" is missing, I will provide a PR to improve this.

**Comment by nguyenalex836** [comment]
@zisuu Thank you for opening an issue and linking it to your PR! ✨
