### ISSUE TITLE
In a devcontainer, the `postCreate` command will not execute without being assigned the execute permission

### ISSUE THREAD

**Issue by saikatdas0790** [github/docs#33165]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/rebuilding-the-container-in-a-codespace

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/codespaces/developing-in-a-codespace/rebuilding-the-container-in-a-codespace#persisting-data-over-a-rebuild

```json
{
    "image": "mcr.microsoft.com/devcontainers/base:alpine",
    "postCreateCommand": ".devcontainer/postCreate.sh"
}
```

**Comment by nguyenalex836** [comment]
@saikatdas0790 Thank you for opening an issue and linking it to your PR! ✨
