### ISSUE TITLE
Remove unnecessary second period from creating-gists#about-gists

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33161]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists#about-gists

### What part(s) of the article would you like to see updated?

> After creating a gist, you cannot convert it from public to secret..

Remove unnecessary second period

**Comment by DevJSter** [comment]
.take
