### ISSUE TITLE
Change link for consistency in uploading-a-project-to-github.md

### ISSUE THREAD

**Issue by adiati98** [github/docs#33169]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/start-your-journey/uploading-a-project-to-github#conclusion

### What changes are you suggesting?

The link to the "Hello World" in:

> For a reminder of how to do this, see "[Hello World](https://docs.github.com/en/get-started/quickstart/hello-world)."

is pointing to "quickstart" instead of "start your journey".
Although this link works as expected, it's not consistent with the links throughout the articles.

Change the path in the link from `quickstart` to `start-your-journey` for consistency.

**Comment by nguyenalex836** [comment]
@adiati98 Thanks so much for raising this issue! ✨ You, or anyone else, is welcome to submit a PR to update that path 💛
