### ISSUE TITLE
Artigo de 2 fatores 

### ISSUE THREAD

**Issue by LarissaSilvaFernandes** [github/docs#33176]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Mesmo não sendo necessário para minha conta os banners solicitando a minha inscrição de 2 fatores como está no artigo: “marcando o início de um período de inscrição 2FA de 45 dias, e verá banners solicitando a inscrição em 2FA no GitHub.com. Então você não faz parte de um grupo necessário para ativar o 2FA, embora seja altamente recomendável". Eu estou com dificuldade para fazer minha solicitação de benefícios gratuitos do **GitHub Education**, pois é necessário essa verificação.
![Screenshot_20240525-151142_Chrome](https://github.com/github/docs/assets/67764947/414771e7-fc6c-4946-9de8-6ec9796be37d).
E para fazer essa autenticação de 2FA li o artigo, mas não está claro como eu posso resolver meu problema e me direcionando logo para a resolução dos dois fatores [artigo](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa) 

### What changes are you suggesting?

Excesso de artigo porém sem nenhum específico direcionando para resolver o problema de 2FA

### Additional information

Um link direto para resolver o problema de dois fatores

**Comment by nguyenalex836** [comment]
@LarissaSilvaFernandes Hello! :wave: Sorry to hear about the issue you are encountering with 2FA! Your question would best be handled by our wonderful [support team](https://support.github.com/request). 

Please reach out to them, and they'll be happy to assist 💛
