### ISSUE TITLE
Remove unnecessary period in why-is-git-always-asking-for-my-password#further-reading

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33214]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/why-is-git-always-asking-for-my-password#further-reading

### What part(s) of the article would you like to see updated?

> - "[About remote repositories](https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories)."

Remove unnecessary period

**Comment by devesh-2002** [comment]
May I take this issue?

**Comment by nguyenalex836** [comment]
@devesh-2002 Go for it! Anyone is welcome to submit a PR for this issue 💛
