### ISSUE TITLE
Remove unnecessary period in set-up-git#next-steps

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33213]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/set-up-git#next-steps

### What part(s) of the article would you like to see updated?

> For more information, see "[Quickstart for repositories](https://docs.github.com/en/repositories/creating-and-managing-repositories/quickstart-for-repositories).".

Remove unnecessary second period

**Comment by bejbybox** [comment]
Odesláno z Proton Mail pro Android

-------- Původní zpráva --------
28.05.24 23:31, Alex Nguyen  napsal/a:
