### ISSUE TITLE
markdown rendering issue

### ISSUE THREAD

**Issue by ZZH-Finalize** [github/docs#33315]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

It is hard to recognize the checkbox is checked or not.

![image](https://github.com/github/docs/assets/33342565/7f89960d-b566-4ee1-8b9f-11e250ef6df3)

### What changes are you suggesting?

Modify the checkbox style like this.

![image](https://github.com/github/docs/assets/33342565/8343a29c-672a-49e3-90e9-68008bad0a8c)

**Comment by nguyenalex836** [comment]
@ZZH-Finalize Hello 👋 ! The best place to send your feedback regarding updates to markdown rendering is to https://github.com/github/feedback/discussions 💛
