### ISSUE TITLE
Move period inside quotation marks in pushing-commits-to-a-remote-repository#remotes-and-forks

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33344]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository#remotes-and-forks

### What part(s) of the article would you like to see updated?

> For more information on working with forks, see "[Syncing a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)".

Move period inside quotation marks to maintain consistency with other docs (and [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide))

**Comment by Dragankamil6** [comment]
śr., 5 cze 2024, 01:56 użytkownik Alex Nguyen ***@***.***>
napisał:
