### ISSUE TITLE
Update placeholder formatting per style guide in adding-locally-hosted-code-to-github#adding-a-local-repository-to-github-with-github-cli

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33399]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github#adding-a-local-repository-to-github-with-github-cli

### What part(s) of the article would you like to see updated?

> If you want your project to belong to an organization instead of your user account, specify the organization name and project name with `organization-name/project-name`.

Replace `organization-name/project-name` with `ORGANIZATION-NAME/PROJECT-NAME` - all caps kebab-case, per [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#placeholders)

**Comment by gagan-bhullar-tech** [comment]
@nguyenalex836 can you please assign this to me.
