### ISSUE TITLE
Remove periods from list in about-your-personal-dashboard#staying-updated-with-activity-from-the-community

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33401]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/about-your-personal-dashboard#staying-updated-with-activity-from-the-community

### What part(s) of the article would you like to see updated?

> For example, you'll see updates when someone you follow:
> 
> - Stars a repository.
> - Follows another user.
> - Creates a public repository.
> - Opens an issue or pull request with help wanted or good first issue label on a repository you're watching.
> - Pushes commits to a repository you watch.
> - Forks a public repository.
> - Publishes a new release.

Periods should be removed from this list, as each line is not a complete sentence (per our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists))

**Comment by gagan-bhullar-tech** [comment]
@nguyenalex836 Request you to please assign this to me.
