### ISSUE TITLE
GitHub App permissions - GraphQL permissions

### ISSUE THREAD

**Issue by nbaju1** [github/docs#33451]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/apps/creating-github-apps/registering-a-github-app/choosing-permissions-for-a-github-app#choosing-permissions-for-graphql-api-access

### What part(s) of the article would you like to see updated?

The docs gives no information or help with finding the correct permissions required for GraphQL queries and mutations. This makes finding the correct permissions a crude "trial-and-error" process.

**Comment by nguyenalex836** [comment]
@nbaju1 Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by slawek402** [comment]
Howard

**Comment by skedwards88** [comment]
Thanks for this feedback. We've passed this along internally but can't address this in the docs at this time.
