### ISSUE TITLE
Wrong possible id-token permissions types listed

### ISSUE THREAD

**Issue by cmaster11** [github/docs#33483]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

### What part(s) of the article would you like to see updated?

In the [Defining access for the GITHUB_TOKEN scopes](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-scopes) section, the `id-token` permission is listed with `read|write|none`, but that permission cannot be set to `read`.

Trying to do so will produce:

<img width="848" alt="image" src="https://github.com/github/docs/assets/3482407/4a892e05-e992-4001-8e72-09a42fa7906e">

Probably you want to list `write|none`?

I see in https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token that it also lists the `read` permission and a [thread](https://github.com/github/docs/issues/14626) that mentions it. Is the read permission available ONLY in specific conditions?

**Comment by nguyenalex836** [comment]
@cmaster11 Thank you for opening this issue! I'll get this triaged for review ✨

**Comment by TrickTurner** [comment]
I wish I could be with Zac! I miss him so fucking much.. fuck my life

**Comment by debug784** [comment]
thnku for opening the issue.

**Comment by debug784** [comment]
> thnku for opening the issue.

**Comment by Sa-su121** [comment]
@

**Comment by janbrasna** [comment]
My guess is that it can become `"read"` implicitly in some scenarios, but can't be set to `"read"` by the authors deliberately. See https://github.com/github/docs/issues/26481#issuecomment-2227396046

**Comment by janbrasna** [comment]
@joshmgross 🤙 Yo, thanks for confirming! May I ask what happens if one sets `permissions: read-all`? Does that skip over those that can't be set to `read`, or will still try setting the `id-token` too to `"read"` and fail?

**Comment by janbrasna** [comment]
Now it is clear it can't be **set** to "read", but there's still the confusion about why it is documented (and confirmed by staff on several occasions) to **default** to "read" in some cases, see: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token _("Maximum access for pull requests from public forked repositories")_

**Comment by joshmgross** [comment]
👋 Hey @janbrasna, sorry for the confusion there.

`permissions: read-all` effectively means that `id-token` is set to `none` since `read` is not a valid permission.

That "Maximum access for pull requests from public forked repositories" section should list `none` for `id-token`.

**Comment by joshmgross** [comment]
> (and https://github.com/github/docs/issues/32320#issuecomment-2065295887 on https://github.com/github/docs/issues/14626#issuecomment-1047422844)

> For reusable workflows outside the org and also for pull requests from public forked repos , default value issued to id-token is "read" to be safe and restrictive. Users could change it to "write" if they want to explicitly grant permissions for the workflow to request an OIDC JWT.

That should be "default value issued to `id-token` is "none""

> There is no difference between a workflow having `id-token: read` and `id-token: none`.
https://github.com/github/docs/issues/14626#issuecomment-1047422844

There's no *functional* difference between these two because there are no `id-token` resources to read, so the permission is just `none`. That being said, you can't explicitly set `id-token` to `read`.
