### ISSUE TITLE
Adding another point in Github Docs, about when contributions are not counted.

### ISSUE THREAD

**Issue by aditi5926** [github/docs#33525]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Link to the Github Doc page which can be improved](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile)

## Problem I faced maybe the same problem many users might be facing.
* As sometimes user may be confused why their contributions are not counted, when they fork some repository but if any issue happens he/she might have to delete that repository and create the fork again. We don't get our contributions counted for the deleted repository.
- This should be mentioned in this doc clearly stating this rule as well that they don't count this as contribution.

### Additional information

Many users might be confused due to this ambiguity. So, assign this issue to me, I would like to improve this.
```[tasklist]
### Tasks
```

**Comment by nguyenalex836** [comment]
@aditi5926 Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@aditi5926 Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by aditi5926** [comment]
I can also fix this issue can you assign this to me?
