### ISSUE TITLE
Remove periods from list in personalizing-your-profile#setting-your-location-and-time-zone

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33586]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile#setting-your-location-and-time-zone

### What part(s) of the article would you like to see updated?

> Your location and time zone will be visible:
> 
> - On your GitHub profile page.
> - When people hover over your username or avatar on GitHub.

Remove periods from this list, as each line is not a complete sentence.

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by GuiOliweira** [comment]
Olá, gostaria de trabalhar nesta issue. Posso assumir esta tarefa?

**Comment by nguyenalex836** [comment]
Hi @GuiOliweira 👋 ! You or anyone else is welcome to submit a PR for this issue 💛
