### ISSUE TITLE
Commit schema incorrect; all values can be omitted

### ISSUE THREAD

**Issue by SamWilsn** [github/docs#33599]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-commits-on-a-pull-request
- https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit

Likely more pages.

### What part(s) of the article would you like to see updated?

The response schema for these endpoints lists, for example, `login` as a required non-null field. The actual endpoints can return a completely empty object.

### Additional information

Here is a commit that doesn't match the schema: https://api.github.com/repos/ethereum/ERCs/commits/fb8277911c110491bf3610b5e0298c4f4cb70a3f

See https://github.com/XAMPPRocky/octocrab/pull/656#discussion_r1647610254for more discussion.

**Comment by nguyenalex836** [comment]
@SamWilsn Thanks so much for opening this issue! ✨ I've created an issue internally for this as our team will need to address this portion of the documentation. Thank you again for raising the flag on this 💛
