### ISSUE TITLE
Fix row headers on Footnotes style guidance

### ISSUE THREAD

**Issue by streats** [github/docs#33603]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#footnotes

### What part(s) of the article would you like to see updated?

The first column of the example table in the Footnotes section should be row headers but it's missing the necessary markup, so they render as data. 

### Additional information

I'll happily open a PR 💜

**Comment by nguyenalex836** [comment]
@streats Annie!! ✨ 😄 So good to hear from you! You or anyone else is welcome to open a PR with this fix 💛 🤓
