### ISSUE TITLE
Show the _actual_ permission property name in list of "Permissions for GitHub Apps"

### ISSUE THREAD

**Issue by tonglil** [github/docs#33611]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#organization-permissions-for-webhooks

And possibly

https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28

### What changes are you suggesting?

In addition to showing the "pretty name" for permissions, the docs need to also show the actual permission property name slug for each permission so users know which permission to pass when creating an Installation Access Token with permissions.

---

For example:
> [Repository permissions for "Webhooks"](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-webhooks)

Fails to describe any where on this page, or in any of the pages related to the webhook docs ([example](https://docs.github.com/en/rest/repos/webhooks?apiVersion=2022-11-28#create-a-repository-webhook)), that the actual `permission` value is called `repository_hooks`.

All that is (insufficiently) shown is:

> <img width="771" alt="image" src="https://github.com/github/docs/assets/3250776/25a8737e-506d-4482-9824-867bdc8727e5">

> <img width="529" alt="image" src="https://github.com/github/docs/assets/3250776/2de31e0c-bb6f-4858-970b-68ebfe7e7ec2">

---

### To be clear, I want to see `repository_hooks` somewhere on either one or both of those pages.

Right now the list of permissions are hidden in [this endpoint's documentation](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-scoped-access-token) in a collapsed expandable that is hard to search for and does not pull up on Google search when searching for `"permissions available for github apps"`.

### Additional information

Thanks

**Comment by nguyenalex836** [comment]
@tonglil Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by Dropkick13** [comment]
[]()

**Comment by felicitymay** [comment]
@tonglil - many thanks for raising the difficulty with finding the permissions information in its current location of a collapsed section ✨ 

I can see that this is a problem. These articles are in our documentation and are automatically generated, so we'll need to raise an internal issue to investigate how best to improve this situation.
