### ISSUE TITLE
Add period to end of line in configuring-notifications#benefits-of-the-notifications-inbox

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33640]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#benefits-of-the-notifications-inbox

### What part(s) of the article would you like to see updated?

> - Group notifications in your inbox by repository or date to get a quick overview with less context switching

Add a period to the end of this line in the list as it is a complete sentence

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by Xf9s** [comment]
.
