### ISSUE TITLE
Virtual assistant on "why are contributions not showing up" uses i.e instead of e.g

### ISSUE THREAD

**Issue by jacks0n9** [github/docs#33659]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

### What part(s) of the article would you like to see updated?

The virtual assistant, upon clicking the "run a public contribution check button" uses i.e instead of e.g. Given that the link it gives is an example, e.g should be used.

**Comment by nguyenalex836** [comment]
@jacks0n9 Thank you very much for opening this issue! ✨ You are absolutely right - that "i.e." should be replaced with an "e.g.". As we will need to fix this internally, I'll file an issue to have this updated on our end, and close out this issue.

Thank you again for raising the flag on this 💛
