### ISSUE TITLE
Fix GHES docs for PAT as SSO not available

### ISSUE THREAD

**Issue by amarvin** [github/docs#33696]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens.md

### What part(s) of the article would you like to see updated?

Personal access tokens (PATs) screenshot shows "configure SSO" even for GitHub Enterprise Server (GHES), but GHES doesn't have SSO for PATs.

**Comment by nguyenalex836** [comment]
@amarvin Thank you for opening an issue and linking it to your PR! ✨
