### ISSUE TITLE
Not too sure about how to mention a secret team

### ISSUE THREAD

**Issue by programarivm** [github/docs#33720]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams

### What part(s) of the article would you like to see updated?

Can the owner of an organization mention a secret team?

> Secret teams are only visible to the people on the team and people with owner permissions. They're great for hiding teams with sensitive names or members, such as those used for working with external partners or clients. Secret teams cannot be nested under parent teams or have child teams.

I can't draw any conclusion from the docs about whether or not certain roles would be allowed to mention secret teams.

Thanks for the help, it is very much appreciated!

**Comment by nguyenalex836** [comment]
Hi @programarivm 👋 ! That's a great question!

This would actually be best handled by our wonderful [support team](https://support.github.com/request). Please reach out to them, and they'll be happy to assist! ✨ 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue 💛
