### ISSUE TITLE
GitHub didn't prompt me to re-authenticate when adding a new GPG key

### ISSUE THREAD

**Issue by YanisaHS** [github/docs#33750]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

### What changes are you suggesting?

Suggesting that "If prompted, " be added to the last step to account for situations where someone isn't prompted to re-authenticate.

### Additional information

I will submit a PR for this momentarily

**Comment by nguyenalex836** [comment]
@YanisaHS Thank you for opening an issue and linking it to your PR! ✨
