### ISSUE TITLE
Improve "involves" filter

### ISSUE THREAD

**Issue by KornevNikita** [github/docs#33766]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Article - [Search by a user that's involved in an issue or pull request](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-a-user-thats-involved-in-an-issue-or-pull-request)

### What changes are you suggesting?

I hope that's the right repo to file an issue to. Please redirect me if I'm wrong.

I'm trying to find all issues in some repo, which were updated by me - created, opened, and so on. In this case I'm using the "involves:@me" filter. This filter works fine, but it doesn't show the issues, where I added a label. I mean - I made no changes, just added some label without commenting or so. I'd be great if you can improve the API to also find this kind of issues. Thanks.

**Comment by nguyenalex836** [comment]
Hi @KornevNikita! 👋 The best place to send your feedback regarding this feature request is to https://github.com/github/feedback/discussions ✨

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue in this repo 💛
