### ISSUE TITLE
Irrelevant link to npm registry in pages about publishing Java packages in GitHub

### ISSUE THREAD

**Issue by carlos-quintero** [github/docs#33776]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

* Publishing Java packages with Gradle: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
* Publishing Java packages with Maven: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

### What part(s) of the article would you like to see updated?

Both articles, the "Prerequisites" section, say:

> You may also find it helpful to have a basic understanding of the following:
> 
>     "Working with the npm registry"

The npm registry is irrelevant for Java packages, the prerequisite should be about the Apache Maven registry (https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry)

**Comment by nguyenalex836** [comment]
@carlos-quintero Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by hubwriter** [comment]
@carlos-quintero - Thank you for raising this. It would be good to correct those articles, as per the details you've given above.

I've marked this issue `help-wanted`. If you (or anyone else reading this) would like to raise a pull request to update the docs accordingly that would be great.

Information about contributing to the docs:
https://docs.github.com/en/contributing

**Comment by hubwriter** [comment]
I've now review the PR that will close this issue:
https://github.com/github/docs/pull/33784
