### ISSUE TITLE
Contradictory explanations of question mark filter pattern

### ISSUE THREAD

**Issue by MetRonnie** [github/docs#3377]
### What is the current behavior?

In the "Workflow syntax for GitHub Actions" docs page, it says, in the [filter pattern cheat sheet](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet):

> `?`: Matches zero or one single character. For example, `Octoc?t` matches `Octocat`

whereas, [a bit further down](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-file-paths), it says:

> `'*.jsx?'` The `?` character matches zero or one of the **preceding** character. E.g. `page.js`, `page.jsx`

(copied out of the table, emphasis mine)

### What changes are you suggesting?

I would expect the latter behaviour is the correct one, as that would be consistent with regexes, but I have not tested the behaviour of the question mark in GitHub Actions.

**Comment by janiceilene** [comment]
Thanks for opening an issue @MetRonnie! I'll get this triaged for the team to take a look 👀

**Comment by martin389** [comment]
Thanks for letting us know about this issue. 💯 
It does like the docs need to be updated -- I'll check with the devs to confirm what the expected behavior should be.

**Comment by martin389** [comment]
The devs have confirmed that this is a bug, and it's currently being reviewed internally. I'm not sure if/when this will be resolved, but thanks again for letting us know 👍
