### ISSUE TITLE
Mismatch between explanation and code about triggers used

### ISSUE THREAD

**Issue by carlos-quintero** [github/docs#33777]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Publishing Docker images (https://docs.github.com/en/actions/publishing-packages/publishing-docker-images) 

### What part(s) of the article would you like to see updated?

1) In the section "[Publishing images to Docker Hub](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub)" it says:

> The workflow in the example below runs when the release event triggers with the **created** activity type.

while the code uses the **published** activity type:

```
on:
  release:
    types: [published]
```

2) In the section [Publishing images to GitHub Packages](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages) is says:

> The workflow in the example below runs when the release event triggers with the created activity type. 

while the code uses a push trigger:

```
on:
  push:
    branches: ['release']

```

**Comment by nguyenalex836** [comment]
@carlos-quintero Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by hubwriter** [comment]
@carlos-quintero - Thank you for raising this. It would be good to correct the workflow triggers in the https://docs.github.com/en/actions/publishing-packages/publishing-docker-images article, as per the details you've given above.

I've marked this issue `help-wanted`. If you (or anyone else reading this) would like to raise a pull request to update the docs accordingly that would be great.

Information about contributing to the docs:
https://docs.github.com/en/contributing

**Comment by hubwriter** [comment]
I've now reviewed the PR that will close this issue:
https://github.com/github/docs/pull/33783
