### ISSUE TITLE
No reference to PayPal end-of-support in entire directory tree of GitHub Sponsors program

### ISSUE THREAD

**Issue by Yewzir** [github/docs#33785]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[About payment methods for sponsorships](https://docs.github.com/en/sponsors/sponsoring-open-source-contributors/about-sponsorships-fees-and-taxes#about-payment-methods-for-sponsorships)

### What part(s) of the article would you like to see updated?

Two weeks ago, I decided I'd sponsor the owner of the repository where I spend most of my time online. Not knowing what billing methods were supported and hoping there was PayPal support, I was relieved when I saw the PayPal button in my user settings. However, since I hadn't used my wallet for a long time, regaining access to the account turned out to be rather challenging.

Actually, you will not believe the trouble I went through until I eventually managed to access the account. It's mine, don't worry. Practically everything that could go wrong, did. Password recovery, two-factor authentication resets, dying phone refusing to charge, relinking financial institution, etc. Hours later and all set up, what'd I see? PayPal's no longer supported and the only announcement was the next image.

![image](https://github.com/github/docs/assets/116750824/cdb0e196-e95c-48cf-bdcb-7b14c3228dd7)

Correct, it was announced in the changelog but that ain't the first place to go looking for that kind of notice. The announcement's already preceded by dozens of other posts. Let it be said that the general user would assume PayPal to be functional in the event of no or minimal triggers.

What astonished me most was the lack of the PayPal company name in the entire directory tree of the program, especially since it's not dead and only affects GitHub Sponsors. Until now, and I went for it straight away because I'm positive that many users encountered similar situations before.

### Additional information

The occurrence frequency is permanent. The issue will direct to a PR momentarily, and vice-versa.

**Comment by nguyenalex836** [comment]
@Yewzir Thank you for opening an issue and linking it to your PR! ✨

**Comment by Hobbs187** [comment]
**I HAVE ANOTHER DIGITAL PAYMENT PLATFORM THAT COULD BE ADDED TO THE PLATFORM , SKRILL IM NOT SAYING THAT IT MUST BE **USE ITS A SUGGESTION 😀
