### ISSUE TITLE
Event API docs for MemberEvent changes are incorrect

### ISSUE THREAD

**Issue by wayofthepie** [github/docs#3378]
### What article on docs.github.com is affected?
https://docs.github.com/en/developers/webhooks-and-events/github-event-types#memberevent

### What part(s) of the article would you like to see updated?
The docs mention that the `changes` field in a `MemberEvent` is structured as `changes[old_permission][from]`. But in reality the changes field looks as follows for a webhook event of type `edited`:

```json
"changes": {
    "permission": {
        "from": "triage",
        "to": "read"
    }
}
```
The key is `permission` not `old_permission`, and there is also a `to` field for the new permission. Note that this is also an issue in the webhook docs https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#member. Second to this, the field also appears when the event is type `added`, but the docs only mention its appearance in `edited` events. There is no `from` field when the event is type `added`, just a `to` field:

```json
"changes": {
    "permission": {
        "to": "read"
    }
}
```
Maybe that should also be added to the docs? Thanks.

**Comment by janiceilene** [comment]
@wayofthepie Thanks for opening an issue! I'll triage this for the team to take a look 👀

**Comment by heiskr** [comment]
Hi @wayofthepie! So `[old_permission]` would need to be replaced with whatever the name of the permission you'd like to change.
