### ISSUE TITLE
GitHub Sponsors tax document link description is incorrect

### ISSUE THREAD

**Issue by halostatue** [github/docs#33802]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-personal-account.md, via https://github.com/github/docs/blob/main/data/reusables/sponsors/tax-form-information-dev.md

### What part(s) of the article would you like to see updated?

The tax form information indicates the the `W-8BEN` is for non-US residents, which is incorrect. It is for non-US residents *and citizens*, whereas `W-9` is for US residents and non-resident US citizens (it may also apply to non-US citizens with resident status even if they are currently non-resident, but that is an odd situation).

US expats must use `W-9`, not `W-8BEN`.

**Comment by nguyenalex836** [comment]
@halostatue Thank you for opening an issue! I'll get this triaged for review ✨
