### ISSUE TITLE
[autotitle] not rendered on page

### ISSUE THREAD

**Issue by rajbos** [github/docs#33818]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/accessibility/github-command-palette

### What part(s) of the article would you like to see updated?

The header shows unrendered info:

```` 
The GitHub Command Palette is deactivated by default. You can enable the GitHub Command Palette with feature preview. See "[AUTOTITLE](/get-started/using-github/exploring-early-access-releases-with-feature-preview)."
```

### Additional information

It's not directly on the page itself, seems to be an embed and I do not have a clue how those are rendered :-D

**Comment by rajbos** [comment]
Seems like the `AUTOTITLE` keyword does not get rendered from here: https://github.dev/github/docs/blob/main/data/reusables/command-palette/default.md, either because of the use in a subpage or the link, but links in other locations do work, like [here](https://github.com/github/docs/blob/main/content/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions.md) in the markdown leads to this page [here](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions).

**Comment by Ell1116** [comment]
<script type="module" src="https://get.microsoft.com/badge/ms-store-badge.bundled.js"></script>
<ms-store-badge
	productid="9pktq5699m62"
	productname="iCloud"
	window-mode="direct"
	theme="dark"
	language="en-au"
	animation="on">
</ms-store-badge>
Batch Installation ID: DDB1A24E-9B13-48FC-B301-FE8C4ACC592D

**Comment by nguyenalex836** [comment]
@rajbos Great catch! ✨ I've added the `help wanted` label so that you, or anyone else, can help assess the issue and submit a PR with a fix 💛
