### ISSUE TITLE
Fix GitHub CLI sample code about 'create a ruleset for a repository'

### ISSUE THREAD

**Issue by yasuhiroki** [github/docs#33821]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#create-a-repository-ruleset

### What part(s) of the article would you like to see updated?

The current GitHub CLI sample code for creating a ruleset in a repository does not work correctly. The conditions field for targeting branches cannot be defined properly.

## Currently, it is written as follows: 

```bash
gh api \
  --method POST \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /repos/OWNER/REPO/rulesets \
   -f "name=super cool ruleset" -f "target=branch" -f "enforcement=active" -F "bypass_actors[][actor_id]=234" -f "bypass_actors[][actor_type]=Team" -f "bypass_actors[][bypass_mode]=always" -f "ref_name[include[]]=refs/heads/main" -f "ref_name[include[]]=refs/heads/master" -f "ref_name[exclude[]]=refs/heads/dev*" -f "rules[][type]=commit_author_email_pattern" -f "rules[][parameters][operator]=contains" -f "rules[][parameters][pattern]=github"
```

### Problem

With this configuration, the conditions field remains empty, making it impossible to specify target branches in the created ruleset.

## The correct way to write this is as follows:

```bash
gh api \
  --method POST \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /repos/OWNER/REPO/rulesets \
   -f "name=super cool ruleset" -f "target=branch" -f "enforcement=active" -F "bypass_actors[][actor_id]=234" -f "bypass_actors[][actor_type]=Team" -f "bypass_actors[][bypass_mode]=always" -f "conditions[ref_name][include][]=refs/heads/main" -f "conditions[ref_name][include][]=refs/heads/master" -f "conditions[ref_name][exclude][]=refs/heads/dev*" -f "rules[][type]=commit_author_email_pattern" -f "rules[][parameters][operator]=contains" -f "rules[][parameters][pattern]=github"
```

### changes:

- `ref_name[include[]]=refs/heads/main` → `conditions[ref_name][include][]=refs/heads/main`
- `ref_name[include[]]=refs/heads/master` → `conditions[ref_name][include][]=refs/heads/master`
- `ref_name[exclude[]]=refs/heads/dev*` → `conditions[ref_name][exclude][]=refs/heads/dev*`

### Additional information

My GitHub CLI version is `gh version 2.52.0 (2024-06-24)`

**Comment by Savannaha83** [comment]
I want to update my systems

**Comment by nguyenalex836** [comment]
@yasuhiroki Thank you so much for raising the flag on this! ✨ This portion of the docs will need to be fixed internally, and I have transferred this issue to our internal teams. I'll go ahead and close this issue 💛
