### ISSUE TITLE
Incorrect permissions/access-tokens documentation for packages API 

### ISSUE THREAD

**Issue by erikburt** [github/docs#33900]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#list-package-versions-for-a-package-owned-by-an-organization

Content:

> [Fine-grained access tokens for "List package versions for a package owned by an organization"](https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#list-package-versions-for-a-package-owned-by-an-organization--fine-grained-access-tokens)
>
> This endpoint works with the following fine-grained token types:
>
>    [GitHub App user access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app)
>    [GitHub App installation access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app)
>    [Fine-grained personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token)
> 
> The fine-grained token does not require any permissions.

### What part(s) of the article would you like to see updated?

Correct guidance for tokens. Fine-grained access tokens do not have `packages:read` permissions, even when empty.

This is noted here: https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages#about-scopes-and-permissions-for-package-registries

> GitHub Packages only supports authentication using a personal access token (classic). For more information, see "[Managing your personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)."

### Additional information

Example:

```
gh api \
      -H "Accept: application/vnd.github+json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -H "Authorization: Bearer <fgat>" \
      /orgs/paradigmxyz/packages/container/reth/versions


{
  "message": "You need at least read:packages scope to get a package's versions.",
  "documentation_url": "https://docs.github.com/rest/packages/packages#list-package-versions-for-a-package-owned-by-an-organization",
  "status": "403"
}
```

**Comment by erikburt** [comment]
Related to this roadmap item: https://github.com/orgs/github/projects/4247/views/1?filterQuery=is%3Aopen+packages&pane=issue&itemId=10457947

**Comment by nguyenalex836** [comment]
@erikburt Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by felicitymay** [comment]
@erikburt - many thanks for raising this discrepancy between what the two different articles say about PAT requirements.

At an initial look, I think that this will require input from a subject matter expert, so I'll request their input.

**Comment by nguyenalex836** [comment]
@erikburt Hello! 👋 We received confirmation from an SME that GitHub Packages supports the legacy PAT and GITHUB_TOKEN, but no fine-grained access tokens.

For this reason, I've added the `help wanted` label to this issue. You, or anyone else, is welcome to open a PR to resolve this discrepancy 💛

**Comment by gagan-bhullar-tech** [comment]
@nguyenalex836 i am trying to find out how to contribute to rest API documentation. It looks like I cannot directly modify the json files. Can you please point me in the right direction.

**Comment by nguyenalex836** [comment]
@gagan-bhullar-tech Thank you for the heads up! Upon review, it looks like this portion of the documentation will need to be updated internally. I have filed an internal issue to have this discrepancy addressed 💛 

Thanks again for raising a flag on this ✨
