### ISSUE TITLE
Remove periods from list in managing-notifications-from-your-inbox#custom-filter-limitations

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33902]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/viewing-and-triaging-notifications/managing-notifications-from-your-inbox#custom-filter-limitations

### What part(s) of the article would you like to see updated?

> Custom filters do not currently support:
> 
> - Full text search in your inbox, including searching for pull request or issue titles.
> - Distinguishing between the `is:issue`, `is:pr,` and `is:pull-request` query filters. These queries will return both issues and pull requests.
> - Creating more than 15 custom filters.
> - Changing the default filters or their order.
> - Search [exclusion](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#exclude-certain-results) using `NOT` or `-QUALIFIER`.

Remove periods from this list, as each line is not a complete sentence

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by MadGanGithub** [comment]
Hey @nguyenalex836 
I would like to work on this issue
Can you assign me?

**Comment by TheGiraffe3** [comment]
@MadGanGithub it looks like @SeanAverS has already taken it, so the answer is probably no.

**Comment by nguyenalex836** [comment]
@MadGanGithub Hello! 👋 While we don't generally assign issues to contributors - if you find an issue to work on, you are welcome to open a PR with a fix 💛
