### ISSUE TITLE
Move period inside quotation marks in managing-your-subscriptions#benefits-of-unsubscribing-from-the-subscriptions-page

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33907]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions#benefits-of-unsubscribing-from-the-subscriptions-page

### What part(s) of the article would you like to see updated?

> When you unsubscribe from notifications on the subscriptions page, you can see more of the notifications you're subscribed to and sort them by "Most recently subscribed" or "Least recently subscribed".

Move period inside quotation marks to align with our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide)

**Comment by Venki1402** [comment]
I think this does it #33914
