### ISSUE TITLE
Remove periods from list in customizing-a-workflow-for-triaging-your-notifications#checking-your-highest-notification-priorities

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#33903]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/viewing-and-triaging-notifications/customizing-a-workflow-for-triaging-your-notifications#checking-your-highest-notification-priorities

### What part(s) of the article would you like to see updated?

> For example, you may decide to check your notifications in this order in the morning during your daily planning time:
> 
> - Pull requests where your review is requested. (filter by `reason:review-requested`)
> 
> - Events where your username is @mentioned, also called direct mentions. (filter by `reason:mention`)
> 
> - Events where a team you're a member of is @mentioned, also called team mentions. (filter by `reason:team-mention`)
> 
> - CI workflow failures for a specific repository. (filter by `reason:ci-activity` and `repo:owner/repo-name` and ensure you've enabled CI activity notifications for workflow failures in your notification settings)

Remove periods from this list, as each line is not a complete sentence

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by devesh-2002** [comment]
May I take this issue?

**Comment by TheGiraffe3** [comment]
> May I take this issue?

Sure!

**Comment by nguyenalex836** [comment]
@devesh-2002 Anyone is welcome to submit a PR for this issue 💛
