### ISSUE TITLE
Wrong URL for Tags on Repository

### ISSUE THREAD

**Issue by sampoder** [github/docs#33923]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#get-a-tag

### What part(s) of the article would you like to see updated?

https://api.github.com/repos/owner/repo/git/tags -> https://api.github.com/repos/owner/repo/tags

### Additional information

https://api.github.com/repos/hackclub/sprig/git/tags seems to be 404-ing but https://api.github.com/repos/hackclub/sprig/tags works.

**Comment by nguyenalex836** [comment]
@sampoder Thanks so much for opening an issue! I'll get this triaged for review ✨

**Comment by sampoder** [comment]
Thanks!

**Comment by felicitymay** [comment]
Thanks for your clear explanation and examples 💖 

The REST API docs are automatically generated from the schema, so this will have to be fixed by a PR to an internal repository. I'm going to add a label to indicate this and create a copy of your issue in the relevant repository.

**Comment by jschnapper** [comment]
Hey @sampoder, thanks for the report 🔍 !  To clarify, https://api.github.com/repos/[owner]/[repo]/tags is a different endpoint https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-tags from https://api.github.com/repos/[owner]/[repo]/git/tags https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#get-a-tag

Additionally, the `git/tags` endpoint only supports annotated tags (see [here](https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#about-git-tags)), not lightweight tags. Could you verify if you're getting the 404s on annotated tags?
