### ISSUE TITLE
Style in the creating-a-team.md page

### ISSUE THREAD

**Issue by TheGiraffe3** [github/docs#33937]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/organizing-members-into-teams/creating-a-team#

### What part(s) of the article would you like to see updated?

Switch ", to ," the way English works.

### Additional information

I am PRing a fix.

**Comment by nguyenalex836** [comment]
@TheGiraffe3 Thank you for opening an issue and linking it to your PR! ✨
