### ISSUE TITLE
GitHub Bug Bounty Program Legal Safe Harbor: site policy typo issue

### ISSUE THREAD

**Issue by Yewzir** [github/docs#33944]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[GitHub Bug Bounty Program Legal Safe Harbor](https://docs.github.com/en/site-policy/security-policies/github-bug-bounty-program-legal-safe-harbor)

### What part(s) of the article would you like to see updated?

> ## [Site policy](https://docs.github.com/en/contributing/collaborating-on-github-docs/about-contributing-to-github-docs#site-policy)
> If you find a typo in the site policy section, you can open a pull request to fix it.

**Comment by nguyenalex836** [comment]
@Yewzir Thank you for opening an issue and linking it to your PR! ✨
