### ISSUE TITLE
Inaccurate explanation of date range queries

### ISSUE THREAD

**Issue by ageorgou** [github/docs#33953]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Understanding the search syntax](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax)

### What part(s) of the article would you like to see updated?

The [Query for dates](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#query-for-dates) section contains the example:

> [cats created:2012-04-30..*](https://github.com/search?utf8=%E2%9C%93&q=cats+created%3A2012-04-30..*&type=Issues) matches issues created after April 30th, 2012 containing the word "cats."

However, the range syntax is inclusive on both sides, so the above example would be more accurately phrased as "created **on or after** April 30th, 2012". This would make it match the description for the `created:>=YYYY-MM-DD` syntax in the same section.

The same applies to the example for `created:*..YYYY-MM-DD`.

The other examples of `*..n` and `n..*` on the page already follow this pattern in their descriptions, making it clear that the range is inclusive.

### Additional information

I can open a PR addressing this.

**Comment by nguyenalex836** [comment]
@ageorgou Thank you for opening an issue and linking it to your PR! ✨
