### ISSUE TITLE
Ruff call syntax has changed for Python linting

### ISSUE THREAD

**Issue by howroyd** [github/docs#33950]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-ruff-to-lint-code

### Additional information

PR incoming!

**Comment by nguyenalex836** [comment]
@howroyd Thank you for opening an issue and linking it to your PR! ✨

**Comment by howroyd** [comment]
My pleasure. Hope it helps others when they're blindly copy and pasting like I did earlier!

**Comment by Malik5703** [comment]
03106308422
