### ISSUE TITLE
bash instructions for creating jwt for github app do not work with client id but work with app id

### ISSUE THREAD

**Issue by paololazzari** [github/docs#33989]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#example-using-bash-to-generate-a-jwt

### What part(s) of the article would you like to see updated?

Running the script with the client id results in a token which when used throws the following error:

```
{
  "message": "A JSON web token could not be decoded",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}
```

Running the script with the app id results in a valid token.

**Comment by nguyenalex836** [comment]
@paololazzari Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@paololazzari Apologies for the delay! We recently merged a https://github.com/github/docs/pull/33859 that I believe resolves the issue this PR is attempting to fix. Many apologies for not being able to get to this sooner 💛

I'll go ahead and close out this issue - thank you!

**Comment by nguyenalex836** [comment]
@paololazzari Apologies for the delay! We recently merged https://github.com/github/docs/pull/33859 that I believe resolves the problem this issue is raising. Many apologies for not being able to get to this sooner 💛

I'll go ahead and close out this issue - thank you!
