### ISSUE TITLE
Pages build limits

### ISSUE THREAD

**Issue by janbrasna** [github/docs#34003]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/pages/getting-started-with-github-pages/about-github-pages.md#usage-limits

### What part(s) of the article would you like to see updated?

> {% data variables.product.prodname_pages %} sites have a soft limit of 10 builds per hour. This limit does not apply if you build and publish your site with a custom {% data variables.product.prodname_actions %} workflow.

### Additional information

Now the builds are only run using actions infrastructure. Does the limit of numbers of runs still apply? Or is it limited by available runner minutes only?

(Or that limit of runs is solely for the implicit pages builds in actions without an explicit workflow file?)

**Comment by janbrasna** [comment]
(Honestly I still don't know if having just .md files and not final .html output still counts as needing "building with legacy pagesworker" or that's only explicitly for the jekyll builds — haven't found any content around this, but the published docs still mention it _"will look for an `index.html`, `index.md`, or `README.md` file as the entry file for your site"_ so I guess plain MDs still sort of "build" to html deployment, or? …)

**Comment by janbrasna** [comment]
There are still "implicit" builds being run even without own actions defined, just tested it — sorry, I understood the changelog announcement somewhat different than what it really was.

**Comment by janbrasna** [comment]
Actually no, I would still love some clarification for that.

As the build limits were for non-action builds. Builds with actions, no matter if implicit or custom workflow all incur minutes against the allotment:

> Your GitHub Pages site is built and deployed with a GitHub Actions workflow. For more information, see "Viewing workflow run history".
> Note: GitHub Actions is free for public repositories. Usage charges apply for private and internal repositories that go beyond the monthly allotment of free minutes. For more information, see "Usage limits, billing, and administration".

So with the legacy _pagesworker_ gone and all builds now happening via actions infrastructure, any build limits are now imposed via runner minutes. Does the quoted "10 builds per hour" limit apply in addition to any actions allotment?

**Comment by nguyenalex836** [comment]
@janbrasna Thanks so much for opening an issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@janbrasna Hello! Thank you for your patience while our SME team reviewed ✨  

Our SMEs would like to keep the information documentation you highlighted regarding the soft limits as is. They are defined to set the baseline for what we consider "abuse" and give us permission to take down a site causing troubles. For this reason, I'll be closing this issue 💛

**Comment by janbrasna** [comment]
Sure, just wanted to ping if they are still current with the recent worker sunset. Thanks for taking the time to confirm it is indeed still valid and sorry for raising this unnecessarily!

**Comment by nguyenalex836** [comment]
@janbrasna No need to apologize! 💛
