### ISSUE TITLE
Environments on implicit builds have branch source

### ISSUE THREAD

**Issue by janbrasna** [github/docs#34005]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment

### What part(s) of the article would you like to see updated?

> "Running a workflow that references an environment that does not exist will create an environment with the referenced name. The newly created environment will not have any protection rules or secrets configured. Anyone that can edit workflows in the repository can create environments via a workflow file, but only repository admins can configure the environment."

Environments created from running implicit page builds (i.e. from branch/folder source) will have the source branch added as a protection to the environment.

### Additional information

It's a nitpick, maybe just too subtle to sort out, i.e. "running a workflow" could mean here that the implicit runs don't really run any explicit workflow etc. — just wanted to bring this into attention, that it bit me a few times when the implicit runs created environments that had some default source protections baked in them from the beginning…

**Comment by nguyenalex836** [comment]
@janbrasna Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by jc-clark** [comment]
Thanks for catching this @janbrasna! I think that in this situation, it would make sense to call out the implicit builds scenario you're referencing. 

We could update this paragraph to something like: 

> Running a workflow that references an environment that does not exist will create an environment with the referenced name. If the environment is created from running implicit page builds (for example, from a branch or folder source), the source branch will be added as a protection rule to the environment. Otherwise, the newly created environment will not have any protection rules or secrets configured. Anyone that can edit workflows in the repository can create environments via a workflow file, but only repository admins can configure the environment.

You or anyone else is welcome to open a PR with this fix. See our [contributing guide](https://github.com/github/docs/blob/main/.github/CONTRIBUTING.md) for more information.
