### ISSUE TITLE
Repo topics URL points to GitHub.com in GHES docs

### ISSUE THREAD

**Issue by IAmHughes** [github/docs#34006]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.13/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#about-topics

### What part(s) of the article would you like to see updated?

Specifically, there is a mention of finding top topics and it points to GitHub.com:

> To browse the most used topics, go to https://github.com/topics/.

However on GHES, this should be the hostname of the GHES instance.

![image](https://github.com/user-attachments/assets/ce1dd9cf-3d1e-451b-8b7b-cefef57e2b31)

### Additional information

This is on all GHES docs that I can find.

**Comment by IAmHughes** [comment]
I'm working on this in #34007

**Comment by nguyenalex836** [comment]
@IAmHughes Thank you for opening an issue and linking it to your PR! ✨
