### ISSUE TITLE
`organization_actions_variables` permission is missing from the documentation

### ISSUE THREAD

**Issue by vmasutin** [github/docs#34014]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-scoped-access-token

### What part(s) of the article would you like to see updated?

[create a scoped access token](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-scoped-access-token) is missing description for `organization_actions_variables` permission, this permission is supported by a REST API but not listed in the documentation.

**Comment by nguyenalex836** [comment]
@vmasutin Thanks so much for opening an issue! I'll get this triaged for review ✨
