### ISSUE TITLE
OIDC hardening token customisation anchor absolute instead of local

### ISSUE THREAD

**Issue by janbrasna** [github/docs#34017]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-token-claims

### What part(s) of the article would you like to see updated?

`* You can define granular OIDC policies by using additional OIDC token claims, such as `repository_id` and `repository_visibility`. For more information, see "[AUTOTITLE](/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token)".`

linking itself, but with autotitle seems like a circular reference, should be just inpage with custom title.

### Additional information

_(one of the typical #31829 issues…)_

**Comment by janbrasna** [comment]
To make the list complete for hubbers, the occurences are:

![Screen Shot 2024-07-19 at 18 02 49](https://github.com/user-attachments/assets/812a1342-fdd5-4dc3-baab-7efcae39b1bd)
![Screen Shot 2024-07-19 at 18 02 57](https://github.com/user-attachments/assets/1d201ca1-1174-45b5-8f23-d15d03d7912d)
![Screen Shot 2024-07-19 at 18 03 10](https://github.com/user-attachments/assets/49f9f024-d8c1-4a8f-9ebc-c9a3c8f06f6e)
![Screen Shot 2024-07-19 at 18 03 17](https://github.com/user-attachments/assets/b679e4cc-6cf2-4098-96e0-67b114c8cd5d)

**Comment by nguyenalex836** [comment]
Thank you, @janbrasna! I'll move the screenshots over to the internal issue 💛
