### ISSUE TITLE
Add period in quotation marks in `Apps` page

### ISSUE THREAD

**Issue by ntagky** [github/docs#34039]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Apps - About authentication as a GitHub App installation](https://github.com/github/docs/blob/main/content/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation.md#about-authentication-as-a--data-variablesproductprodname_github_app--installation)

### What part(s) of the article would you like to see updated?

Period should be added inside quotation marks to maintain consistency with [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#links-to-specific-sections-of-articles).

Existing:

> For more information about authenticating as an app on behalf of a user instead of as an app installation, see "[Authenticating with a GitHub App on behalf of a user](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/identifying-and-authorizing-users-for-github-apps)".

Expected:

> For more information about authenticating as an app on behalf of a user instead of as an app installation, see "[Authenticating with a GitHub App on behalf of a user](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/identifying-and-authorizing-users-for-github-apps)."

**Comment by Josh4031** [comment]
Wacha Go

**Comment by Jellyman447** [comment]
Approved

**Comment by nguyenalex836** [comment]
@ntagky Thank you for opening an issue and linking it to your PR! ✨

**Comment by Jellyman447** [comment]
Automatic connect with thresholds and bind the supply chain all in one package
