### ISSUE TITLE
Contexts available for jobs.<job_id>.defaults.run.shell

### ISSUE THREAD

**Issue by phdru** [github/docs#34046]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

The section [jobs.<job_id>.defaults.run.shell](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell) says

> This keyword can reference several contexts. For more information, see "[Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)."

But the page "Contexts" doesn't mention keyword "shell" at all.

Please update the page "[Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)" to include context(s) available for `jobs.<job_id>.defaults.run.shell`.

If no contexts are available (I tried `matrix` and `runner`, both failed) please document that at the page [jobs.<job_id>.defaults.run.shell](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell).

**Comment by nguyenalex836** [comment]
@phdru Thanks so much for opening an issue! I'll get this triaged for review ✨

**Comment by mabokor865** [comment]
Maxamed raamos

**Comment by mabokor865** [comment]
> [_****_](url)

**Comment by phdru** [comment]
And BTW, page [jobs.<job_id>.steps[*].shell](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell) doesn't mentions any contexts at all. It should IMO.

To explain what I want: I need to calculate system-specific shell:
```yaml
    shell: ${{ matrix.os-name == 'w32' && 'cmd /C call {0}' || 'bash -el {0}' }}
```
or
```yaml
    shell: ${{ runner.os == 'Windows' && 'cmd /C call {0}' || 'bash -el {0}' }}
```
Neither work so I want to know what contexts are available.

**Comment by felicitymay** [comment]
Hi @phdru 👋🏻 

The table on [Context availability](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#context-availability) shows the field where a context is available. The context will also be available for any subfields of that field.

In this case, `jobs.<job_id>.defaults.run` and all subfields can access the following contexts: `github, needs, strategy, matrix, env, vars, inputs`.

**Comment by phdru** [comment]
Ok, thank you for explanation!
