### ISSUE TITLE
GitHub CLI sample for “Upload a release asset” does not work

### ISSUE THREAD

**Issue by YDX-2147483647** [github/docs#34086]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset--code-samples

```shell
# GitHub CLI api
# https://cli.github.com/manual/gh_api

gh api \
  --method POST \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  --hostname HOSTNAME \
  /repos/OWNER/REPO/releases/RELEASE_ID/assets?name=example.zip \
   -f "@example.zip"
```

### What changes are you suggesting?

- `/repos/…` → `https://uploads.github.com/repos/…`

  Otherwise `gh api` will request api.github.com and get 404 Not Found.

- `-f "@example.zip"` → `--input example.zip`

  `-f "@…"` is invalid. Ref: [Manual of `gh api`](https://cli.github.com/manual/gh_api).

- `?name=example.zip` can be changed to `-f "name=example.zip"`

  Just to be clearer.

### Additional information

I can make a PR but I need help on how to change the code sample… It looks that they're generated?

**Comment by nguyenalex836** [comment]
@YDX-2147483647 Thank you so much for opening this issue! I have filed an internal issue to fix this internally, as this portion of the documentation will need to be updated by our team 💛

Thanks again for raising a flag on this ✨

**Comment by YDX-2147483647** [comment]
A pleasure!

Besides, for end users, [`gh release upload <tag> <name>#<label>`](https://cli.github.com/manual/gh_release_upload) is more straight forward.
