### ISSUE TITLE
Docs for ghe-repl-start-all and ghe-repl-stop-all

### ISSUE THREAD

**Issue by jianghao0718** [github/docs#34093]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

upgrading-github-enterprise-server.md

### What part(s) of the article would you like to see updated?

For the part of [Upgrading an instance with multiple nodes using a hotpatch](https://docs.github.com/en/enterprise-server@3.13/admin/monitoring-managing-and-updating-your-instance/updating-the-virtual-machine-and-physical-resources/upgrading-github-enterprise-server#upgrading-an-instance-with-multiple-nodes-using-a-hotpatch) we have a new process which calls `ghe-repl-start-all` and `ghe-repl-stop-all` to stop or start all replication in one shot instead of repeating.

**Comment by Hesham-atta** [comment]
Sound  and  audio  boost
And thank you
