### ISSUE TITLE
Remove period from list line in removing-sensitive-data-from-a-repository#about-sensitive-data-exposure

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34106]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#about-sensitive-data-exposure

### What part(s) of the article would you like to see updated?

> - Through any pull requests that reference them.

Remove period from this list line, as it is not a complete sentence

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by shashwatpathak98** [comment]
Hi @nguyenalex836, created a PR above to fix this issue, please let me know if you have any feedback. :)
