### ISSUE TITLE
Secret names must not start with GITHUB_.

### ISSUE THREAD

**Issue by RSS1102** [github/docs#34107]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret

### What part(s) of the article would you like to see updated?

Can the docs`Secret names must not start with GITHUB_` be reflected in the document? Why is this so?

Can you provide a more detailed explanation here, including an explanation about `Secret names must not start with GITHUB_.`
(Or perhaps there is an explanation that I haven't found?)

### Additional information

![image](https://github.com/user-attachments/assets/c3459fb1-8d95-447d-a428-cffc47afda25)

**Comment by 03don** [comment]
Ronaldoo c Tumpang

**Comment by nguyenalex836** [comment]
@RSS1102 Thanks for opening an issue! I'll get this triaged for review ✨

**Comment by subatoi** [comment]
Hi @RSS1102, and thank you for raising an issue—

Apologies if I've misinterpreted, but regarding the text in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret, the important point is that the `GITHUB_TOKEN` secret is automatically created:

> At the start of each workflow job, GitHub automatically creates a unique GITHUB_TOKEN secret to use in your workflow. You can use the GITHUB_TOKEN to authenticate in the workflow job.

Where we state "Secret names must not start with `GITHUB_`", that means that _users_ cannot create tokens themselves with that pattern.

We'll close this in a few days if we don't hear from you: please let us know if I haven't answered your question and thanks again for your issue.

**Comment by defidefi5** [comment]
This is a rather annoying requirement, given that prefixing env vars with a vendor name such as `GITHUB_` is common to make it clear what vendor the env var comes from and to essentially scope all env vars for a particular vendor. I hope it's reconsidered.

**Comment by gltched-usr** [comment]
@subatoi Any update on this? 

I agree with @defidefi5 and with many others that it makes more sense to allow `GITHUB_` prefix.

**Comment by gimlichael** [comment]
> This is a rather annoying requirement, given that prefixing env vars with a vendor name such as `GITHUB_` is common to make it clear what vendor the env var comes from and to essentially scope all env vars for a particular vendor. I hope it's reconsidered.

Agree. It smells of poor design choice.
