### ISSUE TITLE
Move period inside quotations in managing-your-personal-access-tokens#personal-access-tokens-classic

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34102]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#personal-access-tokens-classic

### What part(s) of the article would you like to see updated?

> ...see "Endpoints available for fine-grained personal access tokens".

Move period inside quotation marks to maintain consistency with other docs (and [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide))

**Comment by ishon19** [comment]
Hey @nguyenalex836, created the PR linked above which should close the issue, let me know if you have any feedback! :)
