### ISSUE TITLE
Move period inside quotation marks in token-expiration-and-revocation#token-revoked-by-the-oauth-app

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34105]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation#token-revoked-by-the-oauth-app

### What part(s) of the article would you like to see updated?

> For more information about revoking individual tokens for your OAuth app, see "REST API endpoints for OAuth authorizations".

Move period inside quotation marks to maintain consistency with other docs (and [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide))

**Comment by shashwatpathak98** [comment]
Hi @nguyenalex836, created a PR above to fix this issue, please let me know if you have any feedback. :)
