### ISSUE TITLE
[New Feature] embedded alerts callout in the rendered markdown

### ISSUE THREAD

**Issue by 1chooo** [github/docs#34121]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

### What part(s) of the article would you like to see updated?

We have the highlight of the callout - `alert`; however if I have the `tip` in the `note`, it cannot render successfully,

> [!NOTE]
> Highlights information that users should take into account, even when skimming.
> 
> > [!TIP]
> > Optional information to help a user be more successful.

Can we add the feature to improve the writing in Markdown?

### Additional information

related: https://github.com/github/markup/issues/1837

**Comment by nguyenalex836** [comment]
@1chooo 👋 The best place to send your feedback regarding this feature request is to https://github.com/github/feedback/discussions ✨

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue in this repo 💛

**Comment by 1chooo** [comment]
> @1chooo 👋 The best place to send your feedback regarding this feature request is to https://github.com/github/feedback/discussions ✨
> 
> If there's anything in the documents that you have suggestions for updating, please feel free to open an issue in this repo 💛

Yeah sure, thank you!
