### ISSUE TITLE
Document describes functions that are no longer possible

### ISSUE THREAD

**Issue by max-allan-cgr** [github/docs#34128]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/managing-issues-and-pull-requests/using-github-actions-for-project-management

### What part(s) of the article would you like to see updated?

Mentions of things you can only do on Projects V1 boards should be removed. 

Or at least clarified to say that they only apply to V1 boards.

As Projects v1 is being turned off in ~24 days and this functionality will be completely lost, I feel removing it is most appropriate.

**Comment by nguyenalex836** [comment]
@max-allan-cgr Thank you for opening an issue and linking it to your PR! ✨
