### ISSUE TITLE
adding thanks.dev as a sponsor button option 

### ISSUE THREAD

**Issue by nehzatarmin** [github/docs#34135]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Is it possible to add thanks.dev to the list of sponsor options https://github.com/github/docs/blob/a9a9dd1f948b6e0257ed5da0a9b94cc1be2aa097/content/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository.md

### What changes are you suggesting?

add the option for thanks.dev

Platform: [thanks.dev](https://thanks.dev/home)
Syntax: thanks_dev USERNAME

**Comment by nguyenalex836** [comment]
@nehzatarmin Hello! 👋 The best place to send your feedback regarding this feature request is to https://github.com/github/feedback/discussions ✨

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue in this repo 💛
