### ISSUE TITLE
Fix inconsistency between kubernetes label/annotation to activate attestation policy 

### ISSUE THREAD

**Issue by uwehdaub** [github/docs#34170]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/enforcing-artifact-attestations-with-a-kubernetes-admission-controller

### What part(s) of the article would you like to see updated?

First code box below heading [enable-the-policy-in-your-namespace](https://docs.github.com/en/actions/security-guides/enforcing-artifact-attestations-with-a-kubernetes-admission-controller#enable-the-policy-in-your-namespace)

You activate the policy by adding a _label_ and not an _annotation_.
The following code block with the kubectl command is correct.

**Comment by nguyenalex836** [comment]
@uwehdaub Thanks so much for opening an issue! I'll get this triaged for review ✨
