### ISSUE TITLE
Clarify the effects of SAML SSO settings in Docs

### ISSUE THREAD

**Issue by micimize** [github/docs#3421]
### What article on docs.github.com is affected?

* [About identity and access management with SAML single sign-on](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-identity-and-access-management-with-saml-single-sign-on)
* [Enabling and testing SAML single sign-on for your organization](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/enabling-and-testing-saml-single-sign-on-for-your-organization)
* [Enabling SAML single sign-on for organizations in your enterprise account](https://docs.github.com/en/github/setting-up-and-managing-your-enterprise/enabling-saml-single-sign-on-for-organizations-in-your-enterprise-account)
* [Preparing to enforce SAML single sign-on in your organization](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/preparing-to-enforce-saml-single-sign-on-in-your-organization)

### What part(s) of the article would you like to see updated?

In all of these docs, the consequences of "enabling" versus those of "enforcing" are not properly specified, and there are specific sections that actively cause confusion. The fact that Enterprise and Organization level SAML configurations have dramatically different behavior compounds the issue.

In [Enabling and testing SAML single sign-on for your organization](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/enabling-and-testing-saml-single-sign-on-for-your-organization), the docs state:
> If you enable but don't enforce SAML SSO, organization members who choose not to use SAML SSO can still be members of the organization.

The mechanisms for how exactly this works, and how the behavior can be observed by an administrator, should be documented. A paragraph such as:
> Users who have not yet linked their SAML provider will see the a banner like the following prompting them to link their account:
>  ![Screen Shot 2021-02-02 at 10 33 17 AM](https://user-images.githubusercontent.com/8343799/106631303-3d8f9900-6542-11eb-8e6d-d41c35101bfe.png)
>
> After linking their SAML identity, users will not be able access any organization resources without an active SSO session. To see the banner again, for testing purposes or otherwise, go to your user SSO details page within the organization at `https://github.com/orgs/{my-enterprise-org}/people/{my-github-username}/sso` and press the "revoke" button:
> ![Screen Shot 2021-02-02 at 10 30 54 AM](https://user-images.githubusercontent.com/8343799/106630772-be9a6080-6541-11eb-9253-570241d71559.png)
> You will now be able to observe resources and go through the authentication flow again.

With details on the differences in configuration between enterprise and org level SAML noted somewhere as well:
> **Note:** Enterprise-level SAML SSO differently from Organization-level SSO. At the Enterprise level, there is only a single "SSO Enabled" state, where all enterprise members must pass through SSO to access resources, but no members are removed from the organization for neglecting to do so.

I'd also recommend tuning the phrasing in [Enabling SAML single sign-on for organizations in your enterprise account](https://docs.github.com/en/github/setting-up-and-managing-your-enterprise/enabling-saml-single-sign-on-for-organizations-in-your-enterprise-account) where the docs refer to "enforcing the setting," to avoid the term "enforce" in a context where its technical sense might be expected.

I linked all articles that I think should should note or link to a more detailed description of the effects of these settings.

### Additional information

I'll just say that having more rigorous docs on these features would have saved a lot of overhead and confusion, and that I believe this should be a priority as it will help other users avoid troubleshooting security settings for production systems.

**Comment by janiceilene** [comment]
@micimize Thanks so much for opening an issue! I'll triage this for the team to take a look 👀

**Comment by janiceilene** [comment]
👋 I've been chatting with some folks, if you've had any conversations in the GitHub community or with our awesome support folks, could you link or copy that into this issue. That way, we'll have all of the information as we continue to review this issue. Thanks so much!

**Comment by micimize** [comment]
Sure – there was a significant amount of discussion in [enterprise issue 903169](https://enterprise.githubsupport.com/hc/en-us/requests/903169), not all of which is relevant, as a large amount of the discussion was on [whether it was possible to access enterprise-level SAML mappings with a GitHub App](https://github.com/github/platform-samples/issues/168#issuecomment-740170370). 

In fact, my support contact also seemed confused about the behavior differences between enterprise and org level SSO. For instance, at the enterprise level, there is no "enabled" vs "enforced" distinction. Relevant excerpts:

> While your Enterprise does have SAML SSO enabled, it is not enforced. When it is only enabled, users have the option to ignore the SAML SSO prompts and can log into your enterprise or organizations without it. If you do enforce it, then all your members will be forced to authenticated against SAML SSO and anyone who hasn't will be removed for the organizations and enterprise.
>
> > That is all quite helpful! I'm a bit confused when you say that our Enterprise's Members aren't required to have SAML SSO. If I invite an alternate account, I cannot accept the invitation without going through the "Authenticate to Join" SAML flow. Some members do not have their SAML identity linked, but I believe that is because they have never logged in to github.
> 
> You could ignore that SAML SSO flow by just going directly to the GitHub organization you were invited to if SAML SSO is only enabled but not enforced. There will be a banner asking, but the resources will be available. This gives the option for the GitHub user to authenticated to the SAML SSO or not. Do note, if at any time SAML SSO is turned to enforced, these members will be removed from the organization.
>
> > Is there any way/configuration to add non-SAML mapped users to a SAML-enabled github org?
>
> Since your enterprise is only SAML SSO enabled, that shouldn't be a problem at this time given the method I stated above.

My response:
> I think the issue is that there is no difference between SSO being enabled and enforced at the Enterprise level. There's no configuration for it, so as the docs you linked says, "Enterprise owners can also enforce SAML SSO for all organizations." I think we'll have to have some internal conversations on the importance of internal SSO enforcement.

It was in large part because of this confusion that makes me say "how the behavior can be observed by an administrator." In fact, there is a mistake in my copy above, where I direct users to "go to `https://github.com/orgs/{my-enterprise-org}/people/{my-github-username}/sso`" which is only visible to admins, but that I mistakenly thought would be visible to users for their own username.

**Comment by mattpollard** [comment]
@micimize 👋🏻 Thanks again for this issue. We appreciate your observations and suggestions!

I'm putting together a small plan to improve this documentation. I'm also communicating with a team at GitHub to suggest changes to the UI copy that might help clarify the difference between the SAML SSO configurations at the organization and enterprise levels.

I'll communicate further here as soon as I know more. Thanks for your patience in the meantime 🙇🏻

**Comment by githubnew-pro** [comment]
> ### چه مقاله ای در docs.github.com تحت تأثیر قرار می گیرد؟
> * [درباره مدیریت هویت و دسترسی با ورود به سیستم SAML](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-identity-and-access-management-with-saml-single-sign-on)
> * [فعال کردن و آزمایش ورود به سیستم SAML برای سازمان شما](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/enabling-and-testing-saml-single-sign-on-for-your-organization)
> * [فعال کردن ورود به سیستم SAML برای سازمانها در حساب سازمانی شما](https://docs.github.com/en/github/setting-up-and-managing-your-enterprise/enabling-saml-single-sign-on-for-organizations-in-your-enterprise-account)
> * [آماده شدن برای اجرای ورود به سیستم SAML در سازمان شما](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/preparing-to-enforce-saml-single-sign-on-in-your-organization)
> 
> ### دوست دارید کدام قسمت از مقاله را به روز کنید؟
> در همه این اسناد ، عواقب "امکان پذیری" در مقابل عواقب "اجرا" به درستی مشخص نشده است و بخشهای خاصی وجود دارد که به طور فعال باعث سردرگمی می شوند. این واقعیت که پیکربندی های SAML در سطح Enterprise و Organization دارای رفتار کاملاً متفاوتی هستند ، مسئله را پیچیده می کند.
> 
> در [فعال کردن و آزمایش ورود به سیستم SAML برای سازمان شما](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/enabling-and-testing-saml-single-sign-on-for-your-organization) ، اسناد بیان می کنند:
> 
> > اگر SAML SSO را فعال کنید اما آن را اجرا نکنید ، اعضای سازمانی که استفاده از SAML SSO را انتخاب نمی کنند همچنان می توانند عضو سازمان باشند.
> 
> سازوکارهای دقیقاً چگونگی این کار و نحوه مشاهده رفتار توسط یک مدیر باید مستند باشد. پاراگرافی مانند:
> 
> > کاربرانی که هنوز ارائه دهنده SAML خود را مرتبط نکرده اند ، بنری مانند تصویر زیر را مشاهده می کنند که باعث می شود حساب خود را پیوند دهند:
> > ![صفحه نمایش 2021-02-02 ساعت 10 33 17 صبح](https://user-images.githubusercontent.com/8343799/106631303-3d8f9900-6542-11eb-8e6d-d41c35101bfe.png)
> > After linking their SAML identity, users will not be able access any organization resources without an active SSO session. To see the banner again, for testing purposes or otherwise, go to your user SSO details page within the organization at `https://github.com/orgs/{my-enterprise-org}/people/{my-github-username}/sso` and press the "revoke" button:
> > ![صفحه نمایش 2021-02-02 ساعت 10 30 54 صبح](https://user-images.githubusercontent.com/8343799/106630772-be9a6080-6541-11eb-9253-570241d71559.png)
> > You will now be able to observe resources and go through the authentication flow again.
> 
> With details on the differences in configuration between enterprise and org level SAML noted somewhere as well:
> 
> > **Note:** Enterprise-level SAML SSO differently from Organization-level SSO. At the Enterprise level, there is only a single "SSO Enabled" state, where all enterprise members must pass through SSO to access resources, but no members are removed from the organization for neglecting to do so.
> 
> I'd also recommend tuning the phrasing in [Enabling SAML single sign-on for organizations in your enterprise account](https://docs.github.com/en/github/setting-up-and-managing-your-enterprise/enabling-saml-single-sign-on-for-organizations-in-your-enterprise-account) where the docs refer to "enforcing the setting," to avoid the term "enforce" in a context where its technical sense might be expected.
> 
> I linked all articles that I think should should note or link to a more detailed description of the effects of these settings.
> 
> ### Additional information
> I'll just say that having more rigorous docs on these features would have saved a lot of overhead and confusion, and that I believe this should be a priority as it will help other users avoid troubleshooting security settings for production systems.

**Comment by mattpollard** [comment]
@micimize, thanks for your patience while we worked on this 🙏🏻 https://github.com/github/docs/commit/1fdb14ff0aef333cd15914449c995f2f4d136d03 introduces changes to reinforce that enterprise-level SAML SSO involves enforcement across organizations.

**Comment by enoseva** [comment]
I'm really shocked by the mistakes that have been made, a tough thing to
say is that I got into cloudflare by mistake at all, it really looks like a
jack!  Unfortunately, I am Iranian and I was recovering with a thousand
different problems of Apple Id that was locked when I fell on the site!
Now I think about it, I'm laughing and I'm ashamed that I upset my friends,
but I really have some hard information to retrieve!  I had a stressful
week and I did not understand what happened!  Now I would really like to
learn how to work with cloudflare, but these small changes have further
disrupted the entire IP address, location and network system, and you know
that Iran is under sanctions and the innocent people of Iran, captivated by
the foolish policies of their government, have a hard life!  How does it
feel to lose information and research after years of studying, which is the
only happiness of us Iranian youth!  Can you please help me learn about
cloudflare?

**Comment by mattpollard** [comment]
👋🏻 @micimize, https://github.com/github/docs/commit/05434201541972fa96afc112ecfeba2b598277d9 incorporated a few more improvements here. Please let us know if you have any further feedback by reopening this issue or creating a new issue or pull request ⚡

**Comment by micimize** [comment]
Thanks @mattpollard – this is indeed a significant improvement! I still think the difference in user eviction behavior between org and enterprise is important to note – I've opened #8650 to mention it.
