### ISSUE TITLE
Reword `maintainer with write access may need to approve any workflow runs`

### ISSUE THREAD

**Issue by jsoref** [github/docs#34218]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks

### What part(s) of the article would you like to see updated?

The page description says:
> When an outside contributor submits a pull request to a public repository, a maintainer with write access may need to approve any workflow runs.

The article then continues to say:
> Note: Workflows triggered by pull_request_target events are run in the context of the base branch. Since the base branch is considered trusted, workflows triggered by these events will always run, regardless of approval settings. For more information about the pull_request_target event, see "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)."

A normal reader would _not_ assume that `may need to approve any workflow runs` would mean `some dangerous workflow runs may run without approval`

I believe the simplest fix is to change `any` to `some`.

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening an issue! I'll get this triaged for review ✨

**Comment by subatoi** [comment]
Hi @jsoref and thanks for opening an issue—

> I believe the simplest fix is to change any to some.

I agree with you: you or anyone else is welcome to make that change, so I'll go ahead and mark this appropriately. 

Thank you!
