### ISSUE TITLE
Talk about `Warning: Skip output 'secret' since it may contain secret.`

### ISSUE THREAD

**Issue by jsoref** [github/docs#34216]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/defining-outputs-for-jobs#overview

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/427d2bf003da7e4a8667fd1c0b8ae54ab93f0b22/data/reusables/actions/jobs/section-defining-outputs-for-jobs.md?plain=1#L5

Should:
1. Include the current message from [github/runner](https://github.com/actions/runner/blame/43d67e46db3fedfd8247d8d6fb968a4e11765643/src/Runner.Worker/JobExtension.cs#L565) to improve SEO so that people will find the documentation
2. Link to the advice on what to do:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-masking-and-passing-a-secret-between-jobs-or-workflows

### Additional information

Users complain about this: https://github.com/actions/runner/issues/475#issuecomment-2270367948

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening an issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@jsoref Thank you for your patience while our SME team reviewed! 💛 

> Should:
> 
> - Include the current message from [github/runner](https://github.com/actions/runner/blame/43d67e46db3fedfd8247d8d6fb968a4e11765643/src/Runner.Worker/JobExtension.cs#L565) to improve SEO so that people will find the documentation
> - Link to the advice on what to do: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-masking-and-passing-a-secret-between-jobs-or-workflows

Our SME team agrees with your guidance. You, or anyone else, is welcome to open a PR to make this update ✨
