### ISSUE TITLE
Update note in about-two-factor-authentication.md

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34221]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/about-two-factor-authentication

### What part(s) of the article would you like to see updated?

> Note: Starting in March 2023 and through the end of 2023, GitHub will gradually begin to require all users who contribute code on GitHub.com to enable one or more forms of two-factor authentication (2FA). If you are in an eligible group, you will receive a notification email when that group is selected for enrollment, marking the beginning of a 45-day 2FA enrollment period, and you will see banners asking you to enroll in 2FA on GitHub.com. If you don't receive a notification, then you are not part of a group required to enable 2FA, though we strongly recommend it.

Note needs to be updated to past tense as 2023 has passed

**Comment by jyotisharma04021989** [comment]
All public block

**Comment by jyotisharma04021989** [comment]
All public policy block
