### ISSUE TITLE
Move period inside ending quotations in accessing-github-using-two-factor-authentication#using-a-security-key

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34224]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/accessing-github-using-two-factor-authentication#using-a-security-key

### What part(s) of the article would you like to see updated?

> To trigger the security key prompt from your operating system, select "Use security key".

Move period inside ending quotations to align with our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide)

**Comment by yaodada123** [comment]
Hi, I think I can finish this task
