### ISSUE TITLE
Move period inside ending quotations in hanging-your-two-factor-authentication-method#adding-a-totp-app

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34225]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/changing-your-two-factor-authentication-method#adding-a-totp-app

### What part(s) of the article would you like to see updated?

> On GitHub, type the code into the field under "Verify the code from the app".

Move period inside ending quotations to align with our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide)

**Comment by prashant3286** [comment]
I would like to take this issue and put up the PR.

**Comment by nguyenalex836** [comment]
@prashant3286 Hello! 👋 Thank you for interest in contributing to GitHub Docs! While we don't generally assign issues to contributors, if you find an issue to work on, you are welcome to open a PR with a fix.

With that said, it looks like @iamAyushChamoli has already reviewed submitted a PR for this issue! Feel free to search for other issues labeled `good first issue` or `help wanted` to see what's available to work on 💛
