### ISSUE TITLE
Mention how to handle `GitHub Container Registry` when using `gh actions-importer configure`

### ISSUE THREAD

**Issue by jsoref** [github/docs#34236]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/migrating-to-github-actions/automated-migrations/migrating-from-circleci-with-github-actions-importer#configuring-credentials

### What part(s) of the article would you like to see updated?

There's a block that suggests the experience will look like this:

> $ gh actions-importer configure
✔ Which CI providers are you configuring?: CircleCI
Enter the following values (leave empty to omit):
✔ Personal access token for GitHub: ***************
✔ Base url of the GitHub instance: https://github.com
✔ Personal access token for CircleCI: ********************
✔ Base url of the CircleCI instance: https://circleci.com
✔ CircleCI organization name: mycircleciorganization
Environment variables successfully updated.

When I ran it, I saw something closer to this:
> % gh actions-importer configure                             
✔ Which CI providers are you configuring?: CircleCI
Enter the following values (leave empty to omit):
✔ GitHub handle used to authenticate with the GitHub Container Registry: 
✔ Personal access token to authenticate with the GitHub Container Registry: 
✔ Personal access token for GitHub: 
✔ Base url of the GitHub instance: https://github.com
✔ Personal access token for CircleCI: 
✔ Base url of the CircleCI instance: https://circleci.com
✔ CircleCI organization name: mycircleciorganization
Environment variables successfully updated.

There's a section before that block that talks about each of the questions and how to prepare answers for them, it includes:
> Create a GitHub personal access token (classic). For more information, see "[Managing your personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic)."
>
> Your token must have the `workflow` scope.

It should have a step for setting up a GHCR credential too.

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening an issue! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@jsoref Thank you for your patience while our SME team reviewed! 💛 

One of our SMEs tried running the configure command but came up with different results:

```
☁  gh-gei [github-api-upload] gh actions-importer configure
✔ Which CI providers are you configuring?: CircleCI
Enter the following values (leave empty to omit):
✔ Personal access token for GitHub: ****
✔ Base url of the GitHub instance: https://github.com/
✔ Personal access token for CircleCI: ****
✔ Base url of the CircleCI instance: https://circleci.com/
✔ CircleCI organization name: test
Environment variables successfully updated.
```

They were unable to find the `GitHub handle used to authenticate with the GitHub Container Registry` reference in our CLI codebase either - would you be able to provide additional info on the origin of that reference?

**Comment by jsoref** [comment]
Fwiw, here's the output of `gh actions-importer version`:
```
gh actions-importer version
gh version 2.57.0 (2024-09-16)
gh actions-importer	github/gh-actions-importer	v1.0.1
actions-importer/cli	v1.3.22130
```

**Comment by jsoref** [comment]
So, here's a proper link to the code:
https://github.com/github/gh-actions-importer/blob/c3865c04bc43d7ea00d32fe98d32597c2d81142b/src/ActionsImporter/Constants.cs#L9

This appears to be a case of a tool not having a provision to warn users that it's woefully out of date ([v1.0.1](https://github.com/github/gh-actions-importer/releases/tag/v1.0.1)). The current version is apparently [v1.3.6](https://github.com/github/gh-actions-importer/releases/tag/v1.3.6).

**Comment by nguyenalex836** [comment]
@jsoref Bot poked 💛 Thank you for the additional info! I'll have the SME team review and provide their insight.

**Comment by nguyenalex836** [comment]
@jsoref 👋 Hello! Our SMEs reviewed again, your guess was correct - running the current version of the tool produces a different than the what you initially noted. 

> This appears to be a case of a tool not having a provision to warn users that it's woefully out of date ([v1.0.1](https://github.com/github/gh-actions-importer/releases/tag/v1.0.1)).

We'll raise this with the relevant owning team to see what our options are for addressing 💛 Thanks again for raising a flag on this!
