### ISSUE TITLE
clarify issue templates doc

### ISSUE THREAD

**Issue by jeffmcaffer** [github/docs#3423]
### What article on docs.github.com is affected?
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

### What part(s) of the article would you like to see updated?

The current text includes the following:
> You can customize the templates that are available for contributors to use when they open new issues in your repository.
>
>You can create default issue templates and a default configuration file for issue templates for your organization or user account. For more information, see "Creating a default community health file."

For someone new to the setup of having config files in the repo and/or in the org this is ambiguous. It should more directly say, "you can customize the templates for a specific repo or for all repos in an org"

### Additional information

I attempted to propose a change but hitting *Make a contribution* opened a PR on a file that does not include the problematic text (second sentence quoted above). So don't know where the text actually lives.

**Comment by adonisj910** [comment]
> https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
> 
> 
> 
> > You can customize the templates that are available for contributors to use when they open new issues in your repository.
> > You can create default issue templates and a default configuration file for issue templates for your organization or user account. For more information, see "Creating a default community health file."
> 
> For someone new to the setup of having config files in the repo and/or in the org this is ambiguous. It should more directly say, "you can customize the templates for a specific repo or for all repos in an org"
> 
> 
> I attempted to propose a change but hitting _Make a contribution_ opened a PR on a file that does not include the problematic text (second sentence quoted above). So don't know where the text actually lives.

**Comment by janiceilene** [comment]
👋 Thanks for opening an issue @jeffmcaffer! The reusable you referenced is in https://github.com/github/docs/blob/main/data/reusables/repositories/issue-template-config.md. You're welcome to open a PR if you'd like! 

That article lives in the "Building a strong community" category, so the intended audience is maintainers of a project, instead of the users. With that in mind, I wonder if something like 👇 might be clearer than the original sentence, but still a good fit for the audience?

> You can customize the templates that are available for contributors to use when they open new issues in your repository or all repositories in your organization.

**Comment by jeffmcaffer** [comment]
That sounds fine but it feels funny with two sentences saying roughly the same thing. So I guess it depends on which sentence(s) you are intending to update with that suggestion. In the end I'm not super fussed as long as the reader understands that in this article they'll be shown how to set up a template in a repo and they can ALSO do a similar thing in their org to affect all their repos (and here's where to go to get that info).

**Comment by janiceilene** [comment]
👍  Sounds good! I'll triage this for the team to take a look 👀

**Comment by janiceilene** [comment]
After chatting with the team, if you or anyone  else would like to open a PR with some clarifying language, you're more than welcome to!
