### ISSUE TITLE
Add an "open issue" or "go to GitHub" button/link

### ISSUE THREAD

**Issue by jeffmcaffer** [github/docs#3424]
### What is the current behavior?

Currently if you look at any doc page, there appears to be a Make a contribution button at the bottom but no obvious way to get to the docs repo.  

### What changes are you suggesting?

Classically websites that have a backing GitHub repo have a button somewhere that takes you to that repo. This is super useful. Without that people are left to guess where they should open an issue.

**Comment by janiceilene** [comment]
That's something we could definitely consider! @simpsoka is a GitHub repo link or button planned for any of the next iterations?

**Comment by simpsoka** [comment]
Yeah, we could add something like this in the nav or footer. 

The make a contribution button takes you right to the repo, though, so we do have this functionality right now. The difference is that the make a contribution button takes you to that file in edit mode. I think the use case you're talking about, @jeffmcaffer is more for opening an issue, and that may be a little more of a global UX. 

But I like it! Just need to figure out where to put the button, and where the button takes you.

**Comment by jeffmcaffer** [comment]
Depending on what you want, perhaps instead of (or near) the feedback button? As an open source project it feels better for "feedback" to go to the project rather than the associated product. There should be a first class way to get to "the project" (see the readme, understand the roadmap, read the contributing doc, open an issue, ...), that's my main point

**Comment by simpsoka** [comment]
Yeah, I think that could easily go into our header. "Goto repo" button, basically

**Comment by shades-7** [comment]
> Yeah, I think that could easily go into our header. "Goto repo" button, basically

@siminapasat can I work on this?

**Comment by siminapasat** [comment]
> > Yeah, I think that could easily go into our header. "Goto repo" button, basically
> 
> @siminapasat can I work on this?

@simpsoka I think that is for you ☝️

**Comment by shades-7** [comment]
pardon the inconvenience caused @siminapasat 
@simpsoka can I work on this issue?

**Comment by FishermanTradingCompany** [comment]
Go ahead

**Comment by fnise-urt** [comment]
@simpsoka

One could change the link on sidebar's svg icon to point to the repository?

`href="/en"`

`href="https://github.com/github/docs"`

**Comment by fnise-urt** [comment]
@jeffmcaffer

> One could change the link on the sidebar's svg icon to point to the repository?

That svg icon's colour could furthermore be changed to #2AA650.

**Comment by janiceilene** [comment]
@fnise-urt Thanks for the suggestion! We don't want to update the svg to direct folks to the repo, we need that to continue sending users back to the docs home page when they click.

**Comment by fnise-urt** [comment]
@janiceilene

FWIW, the link on GitHub Docs sends users back to the home page when they click.

**Comment by fnise-urt** [comment]
> super useful

@lee-dohm

Do the svg icon and proximal text both really need to link to the docs home page?

**Comment by janiceilene** [comment]
> Do the svg icon and adjacent text both really need to link to the docs home page?

For right now we're going to keep both the icon and text pointed to the homepage 💛

**Comment by fnise-urt** [comment]
Not my favourite solution, but this would locate a link to the repo on the docs pages.

**Help us make these docs great!**

All GitHub docs are [open source](https://github.com/github/docs).

**Comment by janiceilene** [comment]
👋 @fnise-urt I chatted with the team and we don't feel like there's an ideal solution for this issue right now, so I'm going to close it. Thank you so much for your interest in improving the GitHub docs!
