### ISSUE TITLE
Missing information in "Generate Installation Access Token"

### ISSUE THREAD

**Issue by robinroy03** [github/docs#34258]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://github.com/github/docs/blob/main/data/reusables/apps/generate-installation-access-token.md

### What part(s) of the article would you like to see updated?

[Authenticating as a GitHub App installation](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation) - I've created a GitHub App following this, but the steps in this blog take me down a rabbit hole of (circular references of) links. It does not clearly explain how to generate an Installation Access Token and confuses the reader with App ID and Client ID.

### Additional information

I was able to generate the Access Token following [this StackOverflow post](https://stackoverflow.com/q/77325437/14405384), which links to [this discussions post](https://github.com/orgs/community/discussions/48186). A reference to the discussions post could clear up all the confusion.

**Comment by nguyenalex836** [comment]
@robinroy03 Thank you for opening an issue and linking it to your PR! ✨

**Comment by ayanwaar** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> * https://github.com/github/docs/blob/main/data/reusables/apps/generate-installation-access-token.md
> 
> ### What part(s) of the article would you like to see updated?
> [Authenticating as a GitHub App installation](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation) - I've created a GitHub App following this, but the steps in this blog take me down a rabbit hole of (circular references of) links. It does not clearly explain how to generate an Installation Access Token and confuses the reader with App ID and Client ID.
> 
> ### Additional information
> I was able to generate the Access Token following [this StackOverflow post](https://stackoverflow.com/q/77325437/14405384), which links to [this discussions post](https://github.com/orgs/community/discussions/48186). A reference to the discussions post could clear up all the confusion.

ok

**Comment by ayanwaar** [comment]
[AllProblemReportingMechanismsReport.csv](https://github.com/user-attachments/files/16568440/AllProblemReportingMechanismsReport.csv)
