### ISSUE TITLE
"Reporting an issue or pull request", the documented feature does not exist on GitHub

### ISSUE THREAD

**Issue by HenkPoley** [github/docs#34260]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam

### What part(s) of the article would you like to see updated?

It says there is a menu item "Report content" under the 3 dots. This does not exist.

Either update the documentation, or fix the feature (that would be better, as I am trying to report spam).

https://github.com/github/docs/blob/main/content/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam.md#reporting-an-issue-or-pull-request

**Comment by nguyenalex836** [comment]
@HenkPoley Thank you for opening an issue! 👋 Can you send a screenshot of what you see after clicking the three dots? For reference, here is a screenshot of what I see -

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/92393708-221a-4fe6-a030-2dadfcfa1ae9">

**Comment by janbrasna** [comment]
The feature exists, but the menu item disappears intermittently (for some repos? haven't spotted any pattern in that…). It's a known bug, I've raised that with support before, it would be helpful to open a support ticket anytime you see that happen with details what repo etc. is that, if it reproduces for you in another browser or private session etc. …

**Comment by nguyenalex836** [comment]
Ah thank you for the insight @janbrasna! ✨ 

@HenkPoley We appreciate you raising a flag on this issue! As @janbrasna mentioned, please feel free to open a [support ticket](https://support.github.com/contact) with the appropriate details whenever you have a moment!

I'll go ahead and close out this issue. If there's anything in the documents that you have suggestions for updating, please feel free to open another issue 💛

**Comment by HenkPoley** [comment]
![image](https://github.com/user-attachments/assets/13f0e315-6192-4a9e-97ed-82f1af2bee30)

**Comment by janbrasna** [comment]
Confirmed, I can't _"Report content"_ on said issue, any issue on `benfred/github-analysis`, or any other `@benfred` repo for that matter (e. g. none in `benfred/py-spy` can be reported, too).

I never got confirmed the culprit, but it behaved like this for me before, only being able to report the exact same content some time later. 🤷 

Like I said, this is better to be directed to GitHub Support, as it might be a glitch (or a some kind of a feature… which if it is, and there's a rule why the menu item is not always available, feel free to reopen this issue with any info to be added to the docs to explain why it's not always visible. Thanks.)

**Comment by HenkPoley** [comment]
I wrote to them about this and the spam at benfred's repo before, as far as I remember, but the spam and the issue is still there.

**Comment by janbrasna** [comment]
To rephrase that: I'm currently unable to _"Report content"_ in many repos, both personal and org, unless they are "rather popular" (whatever that might mean from my current perception), and even some of those, yet without recent activity, don't show that option, even for the same owners, e.g.:

* ✅ [sindresorhus/Gifski](https://github.com/sindresorhus/Gifski/issues): enabled
* ❌ [sindresorhus/System-Color-Picker](https://github.com/sindresorhus/System-Color-Picker/issues): disabled
* ❌ [mozilla/cipherscan](https://github.com/mozilla/cipherscan/issues): disabled
* ✅ [mozilla/kitsune](https://github.com/mozilla/kitsune/issues): enabled

Once anyone knows the culprit or rule, that can be added to the docs to let users know it's not universally available.

**Comment by HenkPoley** [comment]
At **none** of those 4 repos I can report the current newest issue.

**Comment by HenkPoley** [comment]
This useful feature still effectively does not exist for me.
