### ISSUE TITLE
The current info on default community health files are not detailed enough to precedence of some of the community files

### ISSUE THREAD

**Issue by MariusStorhaug** [github/docs#34271]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

### What part(s) of the article would you like to see updated?

I would like to see the list of where GitHub looks for community files in order of precedence.

### Additional information

I have tested this in an org that is under an enterprise, so not sure that changes the order of processing, but it can be seen here: https://github.com/msx-demo.

**Comment by 92022608531** [comment]
Let's go , alless kla

**Comment by nguyenalex836** [comment]
@MariusStorhaug Thank you for opening an issue and linking it to your PR! ✨
