### ISSUE TITLE
Clarification needed for pushing changes to a feature branch with git push

### ISSUE THREAD

**Issue by TDila** [github/docs#34282]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project?platform=linux&tool=webui

## Why Should the Docs Be Changed?
The current documentation lacks specific guidance on pushing changes to a remote repository when working with feature branches. Users may not be aware of the importance of switching to the correct branch or setting the upstream tracking branch, leading to potential mistakes and confusion. By providing these details, the documentation becomes more user-friendly and reduces the risk of errors.

## Use Cases Supported:
1. Working with Feature Branches:
Developers often work on feature branches to isolate new work from the main branch. The updated documentation ensures that they correctly switch to their feature branch before pushing changes.

2. First-Time Setup of Remote Tracking:
The use of the -u flag is crucial when pushing a branch for the first time. It automatically links the local branch to the remote branch, simplifying future pushes. This is particularly helpful for new users or those unfamiliar with remote tracking.

3. Preventing Errors:
By following the updated steps, users avoid common mistakes such as pushing from the wrong branch or missing the setup of an upstream branch, which can lead to more complex issues down the line.

## Expected Outcome or Behavior:
1. Correct Branch Usage:
Users will be guided to switch to the appropriate feature branch, ensuring that they are pushing the correct changes to the remote repository.

2. Streamlined Workflow:
The git push -u origin BRANCH_NAME command will set the upstream tracking, simplifying future push operations. Users will no longer need to manually specify the branch name for subsequent pushes.

3. Reduced User Confusion:
The documentation will be clearer and more comprehensive, reducing the likelihood of user errors and improving overall workflow efficiency.

4. Improved Adoption and Confidence:
Users, especially those new to Git, will find the documentation more accessible and easier to follow, leading to greater confidence in using Git for version control.

**Comment by nguyenalex836** [comment]
@TDila Thank you for opening an issue and linking it to your PR! ✨

**Comment by nguyenalex836** [comment]
Closing per comment [here](https://github.com/github/docs/pull/34283#issuecomment-2285614206) 💛
