### ISSUE TITLE
Confusing verification step in "Installing Git Large File Storage"

### ISSUE THREAD

**Issue by aledefault** [github/docs#34292]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/repositories/working-with-files/managing-large-files/installing-git-large-file-storage

### What part(s) of the article would you like to see updated?

Step 6: Verify that the installation was successful.

This step, where it uses `git lfs install` is misleading since it's necessary not for the installation verification, but to update the global (or system if wanted) git config. Brew (Mac) doesn't do it automatically, neither the install.sh (Linux).

For just check if lfs is installed in the system would be enough with:
`git lfs version`

**Comment by nguyenalex836** [comment]
@aledefault Thanks so much for opening an issue! I'll get this triaged for review ✨

**Comment by kdotmanoj** [comment]
@aledefault @nguyenalex836 if this issue gets triaged, could you please assign it to me? Thanks!

**Comment by nguyenalex836** [comment]
> @aledefault @nguyenalex836 if this issue gets triaged, could you please assign it to me? Thanks!

Hello @kdotmanoj!👋 We don't generally assign issues to contributors. However, once this issue has been reviewed, you are welcome to submit a PR ✨

**Comment by subatoi** [comment]
Hi @aledefault, thanks for raising an issue before going ahead and raising a PR. We really appreciate it.

I agree this is misleading—

I'd suggest we change [line 116](https://github.com/github/docs/blob/main/content/repositories/working-with-files/managing-large-files/installing-git-large-file-storage.md?plain=1#L116) to say something like "Next, update your global Git config:" 

I think we can safely assume advanced users who may not want to run that step will be able to make that judgement independently (hence my suggestion to not use absolute language like "you _must_")

Once we're agreed, I'm happy to add a `help wanted` label to this PR.

**Comment by aledefault** [comment]
Hi @subatoi, you're welcome.

Quoting the [official site](https://git-lfs.com):
`Download and install the Git command line extension. Once downloaded and installed, set up Git LFS for your user account by running...`

In their [GitHub](https://github.com/git-lfs/git-lfs?tab=readme-ov-file) they used:

`Git LFS requires global configuration changes once per-machine. This can be done by running: git lfs install`
...
`Run git lfs install to perform required global configuration changes.`

I think your proposition is good. And maybe not "a must" but add something like "required global Git config". It implies that the config it's actually required for it to work, but you could add it manually (rare case I suppose).

**Comment by subatoi** [comment]
That sounds good to me—let's change [line 116](https://github.com/github/docs/blob/main/content/repositories/working-with-files/managing-large-files/installing-git-large-file-storage.md?plain=1#L116) to something like:

> Next, make required changes to your Global git config:

I've opened that up to contributors now with the `help wanted` label so it's ready for contributors.

Thank you again!

**Comment by kdotmanoj** [comment]
> > @aledefault @nguyenalex836 if this issue gets triaged, could you please assign it to me? Thanks!
> 
> Hello @kdotmanoj!👋 We don't generally assign issues to contributors. However, once this issue has been reviewed, you are welcome to submit a PR ✨

As this issue is now 
open for contributions I'll be working on it!

**Comment by kdotmanoj** [comment]
Hi @subatoi, @nguyenalex836, and @aledefault,

I have submitted a PR addressing the discussion points related to this issue. Please review the changes and let me know if you have any further suggestions or comments.

Thank you!
