### ISSUE TITLE
`Repository limits` - `Commit listings limits` says `Github.com`

### ISSUE THREAD

**Issue by jsoref** [github/docs#34321]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/creating-and-managing-repositories/repository-limits#commit-listings-limits

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/28b01c3319b9386b17be46b5acdfde0ac9da2132/content/repositories/creating-and-managing-repositories/repository-limits.md?plain=1#L35

> The maximum count of commits displayed on the Commits tab of Github.com is 10,000.

### Additional information

* `github` is the standard lowercase form
* `GitHub` is the standard fancy-case
* there are some brand variables for things -- Sometimes github docs favor using brand variables or something else instead of writing github.com when they're trying to say  something like _a github instance_ as opposed to "The GitHub instance at github.com".

It's possible that the right correction is just:
https://github.com/github/docs/compare/main...jsoref:github-docs:brand-github?expand=1

But, I'm not going to make that PR w/o confirmation...

**Comment by nguyenalex836** [comment]
@jsoref Thanks for opening an issue! I'll get this triaged for review ✨
