### ISSUE TITLE
Jekyll GFM processor claims it "will always match the results you see on GitHub"

### ISSUE THREAD

**Issue by janbrasna** [github/docs#34334]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll

### What part(s) of the article would you like to see updated?

_Originally posted by @rectalogic in https://github.com/actions/jekyll-build-pages/issues/106_
            
> "only our GFM processor will always match the results you see on GitHub"

That is not true, GFM hasn't added the newer dotcom features as callouts, diagrams, ToC etc. so this sounds too bold given the discrepancies.

### Additional information

Additional info https://github.com/github/docs/issues/32988#issuecomment-2117744517 and below wrt differences in products +link to Jekyll-only specific issue in the past.

**Comment by nguyenalex836** [comment]
@janbrasna Thank you for your patience while our team reviewed! They are in agreement with you that the wording should changed to reflect reality 💛 

I've added the `help wanted` label so that you, or anyone else, may make this update ✨
