### ISSUE TITLE
Explicitly state that at least one job is required for a workflow

### ISSUE THREAD

**Issue by MizouziE** [github/docs#34337]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow

### What part(s) of the article would you like to see updated?

Slightly altering to something like:

A workflow run is made up of at least one or more `jobs`, which run in parallel by default. Without any jobs to run, a workflow will fail. To run jobs sequentially, you can define dependencies on other jobs using the `jobs.<job_id>.needs` keyword.

**Comment by nguyenalex836** [comment]
@MizouziE Thank you for opening an issue and linking it to your PR! ✨

**Comment by Echefuna** [comment]
### ****
