### ISSUE TITLE
Mismatching types descriptions

### ISSUE THREAD

**Issue by fornazierr** [github/docs#34351]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/rest/using-the-rest-api/github-event-types.md

### What part(s) of the article would you like to see updated?

In the section "Event object common properties", the Event API attribute name `id` of the objects `repo`, `actor` and `org` describes the that the relative types are presented as `string` instead of `integer`.

The doc should be change to be a representation of the real scenario of these attribute types.

---
_Update by a maintainer_

## Updates needed to fix this issue

1. Edit https://github.com/github/docs/blob/main/content/rest/using-the-rest-api/github-event-types.md.
2. In the table under: [Event object common properties](https://docs.github.com/en/rest/using-the-rest-api/github-event-types?apiVersion=2022-11-28#event-object-common-properties), change the type for `actor.id`, `org.id`, and `repo.id` from `string` to `integer`.

**Comment by Mehran0029** [comment]
⚡️ Received Bonus

**Comment by Mehran0029** [comment]
EQBClCK3uH9OsYgTgiABIDSLbm9JqakxQXu1ZA4LrXlfcSGs

**Comment by nguyenalex836** [comment]
@fornazierr Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by felicitymay** [comment]
Hi @fornazierr 👋🏻 

Thanks for flagging this discrepancy. I looked in the schema and you're right about these three identifiers. The Event API attribute `id` of the objects `repo`, `actor` and `org` are all of type integer.
