### ISSUE TITLE
Document search syntax "and"s and "or"s

### ISSUE THREAD

**Issue by jidanni** [github/docs#3436]
https://docs.github.com/en/github/searching-for-information-on-github/understanding-the-search-syntax doesn't seem to mention how to do "and"s and "or"s.
OK, at least I was able to reverse engineer (from Advanced Search tests) that an  "and" is apparently:
```
commenter:pnorman commenter:mmd-osm commenter:bhousel
```
(which would have +'s instead of spaces when used in a URL.)
(I'm Not sure what an or is though.)

**Comment by Huzaifaaa** [comment]
Or

**Comment by lee-dohm** [comment]
Thanks for reaching out.

There is no "OR" mechanism in the search syntax. All operators are additive.

I hope that helps!

Additionally, in the future please fill out the template. Like syntax highlighting for code, it helps us skim and classify issues quickly by seeing that all the required information is there without having to read the entire issue.

**Comment by jidanni** [comment]
OK, however my point was not asking a question. I already figured out the answer, or at least half of it. My point was shouldn't you guys document it somewhere?

**Comment by jidanni** [comment]
Also here, on the Advanced Search page, I see evidence of ORs.,

So my first example was actually three items ORed together not ANDed together.

Well I'm just working back from The URL that the advanced search page creates. And here we see on the advanced search page that we can use more than one creator separated by commas, therefore it must be an OR, at least for creator.

Anyway, all the more reason to document this.

**Comment by jidanni** [comment]
![Screenshot_20210204-122313_1](https://user-images.githubusercontent.com/1230959/106845110-2dfc8580-66e5-11eb-940f-0eeab38736d3.jpg)
