### ISSUE TITLE
Fix link and improve information about topics in the contributing docs

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34378]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/contributing/style-guide-and-content-model/about-topics

### What part(s) of the article would you like to see updated?

The first link in https://docs.github.com/en/contributing/style-guide-and-content-model/about-topics points to https://github.com/github/docs/tree/main/content#topics. It should point to https://docs.github.com/en/contributing/writing-for-github-docs/using-yaml-frontmatter#topics.

However, there is also scope to clarify what topics are and how they are defined in Markdown. The first paragraph of the article could be rewritten to explain that an article can be defined as being relevant to one or more topics by having those topics listed in the article's frontmatter - i.e. the metadata at the top of an article's Markdown file.

It would be more helpful to provide information about where to define the topics for an article, directly within the "About topics" article (with an example of a topics entry in the frontmatter), rather than linking away to other resources in the opening paragraph.

**Comment by Omarsalvado** [comment]
Recuperar mi cuenta de worldcoin

**Comment by CBID2** [comment]
Hi @nguyenalex836. I made a PR for this issue. It's #34491. I also pointed a section where I'm struggling, so check that out during your code review please. :)

**Comment by Koki1610** [comment]
.
