### ISSUE TITLE
Mention new "OWNER:REPO:BRANCH" pattern in "Comparing across forks"

### ISSUE THREAD

**Issue by muzimuzhi** [github/docs#34381]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits#comparing-across-forks

### What part(s) of the article would you like to see updated?

The section _[Comparing across forks](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits#comparing-across-forks)_ only mentions the `OWNER:BRANCH` pattern to specify a `compare` branch in a three-dot comparison, but recently GitHub started using a new `OWNER:REPO:BRANCH` pattern.

> To compare branches on different repositories, preface the branch names with user names. For example, by specifying `octocat:main` for `base` and `octo-org:main` for `compare`, you can compare the `main` branch of the repositories respectively owned by `octocat` and `octo-org`.
>
> Here's an example of a [comparison between two repositories](https://github.com/github-linguist/linguist/compare/master...octocat:master).

The new pattern can be found in the URL of "Open pull request" pages. Such pages can be opened by visiting `https://github.com/OWNER/REPO/pull/new/BRANCH` or by clicking the "Open pull request" button in the page of a branch ahead of upstream default branch.

For example, 
- https://github.com/muzimuzhi/docs/pull/new/gh34381-update-basehead-form jumps to https://github.com/github/docs/compare/main...muzimuzhi:docs:gh34381-update-basehead-form?expand=1 which consists of `muzimuzhi:docs:gh34381-update-basehead-form` pattern.
- Clicking the "Open Pull Request" button opens the same URL https://github.com/github/docs/compare/main...muzimuzhi:docs:gh34381-update-basehead-form?expand=1.
  ![image](https://github.com/user-attachments/assets/1433f404-002a-409d-ac42-06cdaab5f371)

### Additional information

The old form `OWNER:BRANCH` still works, though I don't know which one is preferable by the GitHub.

For example, https://github.com/github/docs/compare/main...muzimuzhi:gh34381-update-basehead-form?expand=1 still works.

**Comment by nguyenalex836** [comment]
@muzimuzhi Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by muzimuzhi** [comment]
The corresponding API docs need a similar update, for example the doc of `basehead` path parameter of REST API endpoint for "[Compare to commits](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#compare-two-commits)". 

Not sure if there are any similar GraphQL APIs.

**Comment by nguyenalex836** [comment]
@muzimuzhi Thank you for your patience while our SME team reviewed! Upon review, our SMEs found we should add the following sentence to this section https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits#comparing-across-forks: 

> You can also preface the branch name with a user name and a repository name. For example, specifying octocat:awesome-app:main would use the main branch in the octocat/awesome-app repository. This can be useful in large organisations, where you might have an upstream repository and a fork both owned by the organisation. For more information, see "[AUTOTITLE](/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks)."

I've added the `help wanted` label so that you, or anyone else can open a PR for this update 💛
