### ISSUE TITLE
Remove mention of Live Share from the Codespaces docs

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34390]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace

### What part(s) of the article would you like to see updated?

The following article will need to be deleted -
"[Working collaboratively in a codespace](https://docs.github.com/en/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace)"

as well as the references to it:

- `content/codespaces/developing-in-a-codespace/index.md`
- `content/codespaces/guides.md`
- `content/codespaces/overview.md`

**Comment by Webzeez** [comment]
Websters styles ss_1shot  photog _X_X~*
![image](https://github.com/user-attachments/assets/790988e6-7a39-46eb-b2fb-4b9c6bf4c618)
📸✖️™️_X hello 👋 
![IMG_1418](https://github.com/user-attachments/assets/4bc1b6ce-5861-437d-b3ab-713bf165d02b)

**Comment by CBID2** [comment]
Hi @nguyenalex836. I created a PR for this issue. It's #34507.

**Comment by nguyenalex836** [comment]
Removing `help wanted` label for now as it is unclear whether we still need a PR to resolve this issue 💛 attempting to get more info, will update once received

**Comment by hubwriter** [comment]
Closing. 
See https://github.com/github/docs/pull/34507#issuecomment-2333445582
