### ISSUE TITLE
Dead anchor links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Simran-B** [github/docs#344]
### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/CONTRIBUTING.md#keep-contributing-as-you-use-github-docs

### What part(s) of the article would you like to see updated?

There are a couple of dead anchor links, for which no content appears to exist.

```
- [Resolving merge conflicts](#resolving-merge-conflicts)
  - [In the GitHub user interface](#in-the-github-user-interface)
    - [Editing the file and committing the changes](#editing-the-file-and-committing-the-changes)
- [Troubleshooting](#troubleshooting)
  - [Failed status checks](#failed-status-checks)
- [Draft pull requests](#draft-pull-requests)
```

The content should either be added or the links be removed.

### Additional information

Originally reported in PR #249, but making it an issue as requested.

**Comment by janiceilene** [comment]
Thank you so much for opening this @Simran-B! Anyone is welcome to pick this up and remove any links from the table of contents that are missing. The doc was restructured and content moved around, but the links weren't removed.

**Comment by janiceilene** [comment]
This was resolved in https://github.com/github/docs/pull/382, so I'm going to close this out. Thanks everyone!
