### ISSUE TITLE
Typo in the "Skipping workflow runs" article

### ISSUE THREAD

**Issue by heyajulia** [github/docs#34402]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs

### What part(s) of the article would you like to see updated?

In explaining how to use the `skip-checks` trailer, the article says (emphasis mine):

> The trailers section should be included at the end of your commit message and be **proceeded** by two empty lines.

The correct term is "preceded," meaning two empty lines should *come before* the trailer section.

### Additional information

This typo is present in static text, meaning it appears every time the page is loaded and affects everyone who reads the article.

**Comment by nguyenalex836** [comment]
@heyajulia Thank you so much for raising this issue! ✨ I've added the `help-wanted` label so that you, or anyone else, may open a PR to fix this 💛

**Comment by nguyenalex836** [comment]
@heyajulia Thank you for opening an issue and linking it to your PR! ✨

**Comment by heyajulia** [comment]
Hi @nguyenalex836! I opened #34403 😊
