### ISSUE TITLE
'Bamboo' is hard-coded in all CI/CD providers migration

### ISSUE THREAD

**Issue by hsnabszhdn** [github/docs#34455]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

* [Migrating from **Azure DevOps** with GitHub Actions Importer](https://docs.github.com/en/actions/migrating-to-github-actions/using-github-actions-importer-to-automate-migrations/migrating-from-azure-devops-with-github-actions-importer)
* [Migrating from **Bitbucket Pipelines** with GitHub Actions Importer](https://docs.github.com/en/actions/migrating-to-github-actions/using-github-actions-importer-to-automate-migrations/migrating-from-bitbucket-pipelines-with-github-actions-importer)
* [Migrating from **CircleCI** with GitHub Actions Importer](https://docs.github.com/en/actions/migrating-to-github-actions/using-github-actions-importer-to-automate-migrations/migrating-from-circleci-with-github-actions-importer)
* [Migrating from **GitLab** with GitHub Actions Importer](https://docs.github.com/en/actions/migrating-to-github-actions/using-github-actions-importer-to-automate-migrations/migrating-from-gitlab-with-github-actions-importer)
* [Migrating from **Jenkins** with GitHub Actions Importer](https://docs.github.com/en/actions/migrating-to-github-actions/using-github-actions-importer-to-automate-migrations/migrating-from-jenkins-with-github-actions-importer)
* [Migrating from **Travis CI** with GitHub Actions Importer](https://docs.github.com/en/actions/migrating-to-github-actions/using-github-actions-importer-to-automate-migrations/migrating-from-travis-ci-with-github-actions-importer)

### What part(s) of the article would you like to see updated?

In all of the pages above, the CI/CD provider is hard-coded to **Bamboo**:

![image](https://github.com/user-attachments/assets/622d2a12-e8dc-470c-9cf6-7731b34449d6)

### Additional information

All those pages load a reusable, [gai-inspect-audit.md](https://github.com/github/docs/blob/13ed8cf1aa5227b75359b298980c7719eb1c55e2/data/reusables/actions/gai-inspect-audit.md), and it's hard-coded there instead of a variable. If there is an example in the repo for calling a reusable and passing a parameter/variable, happy to raise a PR myself, but I just couldn't find any,

**Comment by nguyenalex836** [comment]
@hsnabszhdn Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by subatoi** [comment]
Thanks for opening an issue @hsnabszhdn!

This is obviously an error, so thank you for spotting it. At the moment, we don't have a reusable system of the type you're talking about that would solve this for us in our docs. To my mind, the simplest solution would be to change the text in the [reusable you already noted, on line 15,](https://github.com/github/docs/blob/main/data/reusables/actions/gai-inspect-audit.md?plain=1#L15) from:

> The pipeline was misconfigured and not valid in Bamboo.

to:

> The pipeline was originally misconfigured and not valid.

If you agree, or have a similar suggestion you prefer, then I'm happy to open this up to contributions with a `help wanted` label.

**Comment by hsnabszhdn** [comment]
Sounds good to me :ok_hand:
