### ISSUE TITLE
Contradicting information about port mappings in service containers

### ISSUE THREAD

**Issue by hsnabszhdn** [github/docs#34459]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

* [About service containers](https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers)
* [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions)

### What part(s) of the article would you like to see updated?

In both pages linked about, it says that if you don't specify the port, it maps the **host port** to a randomly chosen **port on the container**:

[About service containers / Mapping Docker host and service container ports](https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers#mapping-docker-host-and-service-container-ports)

> ❌ `8080/udp` Map a randomly chosen UDP port **in the container** to UDP port 8080 **on the Docker host**.

I _think_, it's the other way around: "Map a randomly chosen port **on the Docker host** to UDP port 8080 **in the container**"

[Workflow syntax for GitHub Actions / `jobs.<job_id>.services` / Example: Using localhost](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-localhost)

> ❌ When you **specify the Docker host port** but **not the container port**, the container port is randomly assigned to a free port.

I _think_, it should be: "When you **specify the container port** but **not the Docker host port**, the container port is randomly assigned to a free port."

### Additional information

In the following page, I think the correct statement is used:

[Accessing contextual information about workflow runs / `job` context / Example usage of the job context](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-usage-of-the-job-context)

> ✅ This example workflow configures a PostgreSQL service container, and automatically maps **port 5432 in the service container** to a **randomly chosen available port on the host**.

**Comment by Jamilwel** [comment]
content/account-and-profile/setting-up-and-managing-your-github-profile/index.md

**Comment by Jamilwel** [comment]
Ok

**Comment by nguyenalex836** [comment]
@hsnabszhdn Thank you for raising this issue! I'll get this triaged for review ✨  Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
@hsnabszhdn Thank you so much for your patience while our SME team reviewed! 

> I think, it's the other way around: "Map a randomly chosen port on the Docker host to UDP port 8080 in the container"

> I think, it should be: "When you specify the container port but not the Docker host port, the container port is randomly assigned to a free port."

Our SME team confirms you are correct 💛 I've added the `help wanted` label so that you, or anyone else, can open a PR to make these updates!
