### ISSUE TITLE
Issues with "Authenticating with a GitHub App"

### ISSUE THREAD

**Issue by adsr** [github/docs#34460]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/guides/scripting-with-the-rest-api-and-ruby?apiVersion=2022-11-28#authenticating-with-a-github-app

### What part(s) of the article would you like to see updated?

Hello, I'm having some issues with this section. The most important is that I can't get the example to work. I've followed the instructions and sub-instructions as closely as I can, and I've tried different combinations of values where it's unclear (see below), but continue getting 401s or 404s, e.g.:

```
# on app.create_app_installation_access_token
POST https://api.github.com/app/installations/.../access_tokens: 401 - A JSON web token could not be decoded

# on octokit.create_contents
PUT https://api.github.com/repos/.../.../contents/test.txt: 404 - Not Found 
```

The example is a bit confusing as it's calling `Octokit::Client.new` twice. I think I understand that one client is used to generate an access token and the other client uses this access token, but it's unclear why the first client can't be reconfigured. An explanation would help IMO.

> Instead of requiring octokit, create an instance of Octokit::Client ...

Surely octokit is required to use the `Octokit` module?

> replace `APP_ID` with your app's ID

In app settings, it recommends using client id ("Using your App ID to get installation tokens? You can now [use your Client ID instead](https://docs.github.com/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app)."), so there's a conflict of advice there.

> `PRIVATE_KEY` with your app's private key

Is this meant to be a file path or key contents? If contents, which format? The source code [suggests](https://github.com/octokit/octokit.rb/blob/301bb57668bc1632e0cc93cbb5212a35668f4a76/lib/octokit/client.rb#L247-L249) `client_secret` is supposed to be a 40 character client secret, so I feel like I'm missing something.

> You can get an installation ID with the `GET /users/{username}/installation`, `GET /repos/{owner}/{repo}/installation`, or `GET /orgs/{org}/installation` endpoints.

Are these different `installation_id`s? How does one decide which one to use?

> `octokit = Octokit::Client.new(bearer_token: app.create_app_installation.access_token)`

`app.create_app_installation.access_token` doesn't appear to exist, at least in v9.1.0. I guess this is supposed to be `app.create_app_installation_access_token`?

### Additional information

Always reproducible

**Comment by adsr** [comment]
I was able to get this working by reading the REST API docs, but it looks different from the example:

https://github.com/adsr/repogist/blob/face155fa481fe20adfc88b5158e17ba8bfda9f3/repogist.rb#L177-L182

Is Octokit supposed to handle the JWT stuff for you?

**Comment by nguyenalex836** [comment]
@adsr Thank you for opening this issue! These are great questions that our [support team](https://support.github.com/request) would be best equipped to answer ✨ Please reach out to them for clarification on the examples you highlighted!

If after discussing the examples with them you feel there's anything in the documents we should update, please feel free to open an issue 💛
