### ISSUE TITLE
some click on GitHub point to links that are currently 404

### ISSUE THREAD

**Issue by heygsc** [github/docs#34488]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

some click on GitHub point to links that are currently 404.

When entering `/action/new` path of any repo, as shown in the image below, click on the left side pointing to the link:
[https://docs.github.com/actions/getting-started-with-github-actions](https://docs.github.com/actions/getting-started-with-github-actions), which is 404.
<hr/>
<img width="1223" alt="test" src="https://github.com/user-attachments/assets/d651168c-e736-4bf9-9c59-57e66e807c26">
<hr/>
It seems that this requires modifying the click from GitHub, or restoring the 404 link in the docs to the previous webpage?

### What part(s) of the article would you like to see updated?

When clicked, jump to a right link.

**Comment by nguyenalex836** [comment]
@heygsc Thank you for flagging the broken link! ✨ It looks like that article no longer exists and was likely intended to be replaced by [newer Actions article(s)](https://docs.github.com/en/actions). 

As we will need to fix this internally, I'l flag this for our team 💛 thank you again for submitting an issue!
