### ISSUE TITLE
Fix typos in Creating Diagrams

### ISSUE THREAD

**Issue by bgrzesiak-fetch** [github/docs#34480]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams

### What part(s) of the article would you like to see updated?

Just some grammatical typos

**Comment by nguyenalex836** [comment]
@bgrzesiak-fetch Thank you for opening an issue and linking it to your PR! ✨
