### ISSUE TITLE
Angle brackets are missing in the on-behalf-of CLI instructions

### ISSUE THREAD

**Issue by hacker1024** [github/docs#34497]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-on-behalf-of-an-organization

### What part(s) of the article would you like to see updated?

The [command-line instructions](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-on-behalf-of-an-organization#creating-commits-with-an-on-behalf-of-badge-on-the-command-line) are missing angle brackets around the email address, and are inconsistent with the rest of the page.

**Comment by nguyenalex836** [comment]
@hacker1024 Thank you for opening an issue and linking it to your PR! ✨
