### ISSUE TITLE
Mention that adding codeowners will likely spam lots of users very quickly

### ISSUE THREAD

**Issue by jsoref** [github/docs#34503]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What part(s) of the article would you like to see updated?

[CODEOWNERS and branch protection](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-and-branch-protection) or a section thereafter should be updated to say something like:

> If you have many open PRs or will have many PRs that touch the files you're protecting with a group, then unless you have already made the group secret, you will probably be triggering a lot of email to the team when you add the group to CODEOWNERS. This will probably not be welcome. You should probably make the team secret before you apply these changes. See [!AUTOTITLE](/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#configuring-team-notifications)

The relevant page:
https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#configuring-team-notifications

### Additional information

We just added `CODEOWNERS` to a repository that had a handful of open PRs with a rule to require any changes to be approved by a group that contains most of our staff. Upon merging the file and enabling the rule, we almost immediately got a number of emails for random changes to random PRs in the repository. This isn't technically wrong, but it was absolutely unwelcome and I was going to get yelled at very quickly for making the change I made. -- The documentation here was the right place to warn me to prevent the flack for such a change.

**Comment by nguyenalex836** [comment]
@jsoref Thank you for opening an issue! I'll get this triaged for review ✨

**Comment by VIVAGLEN** [comment]
Ok

**Comment by nguyenalex836** [comment]
@jsoref 👋 Thank you for your patience while our team reviewed! After reviewing your issue, we've determined the best place to send your feedback regarding this feature is to https://github.com/orgs/community/discussions/categories/repositories ✨

If there's anything else in the documents that you have suggestions for updating, please feel free to open an issue in this repo 💛
