### ISSUE TITLE
Correct text to match URL ID example in project automation documentation

### ISSUE THREAD

**Issue by asmecher** [github/docs#34527]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Automating Projects using Actions
https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions

### What part(s) of the article would you like to see updated?

There is a typo re: IDs in the following:
> In the following workflow, replace YOUR_ORGANIZATION with the name of your organization. For example, octo-org. Replace YOUR_PROJECT_NUMBER with your project number. To find the project number, look at the project URL. For example, https://github.com/orgs/octo-org/projects/5 has a project number of 1. In order for this specific example to work, your project must also have a "Date posted" date field.

**Comment by nguyenalex836** [comment]
@asmecher Thank you for opening an issue and linking it to your PR! ✨
