### ISSUE TITLE
Remove periods from list in managing-deploy-keys#pros-of-installation-access-tokens

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34522]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#pros-of-installation-access-tokens

### What part(s) of the article would you like to see updated?

> Pros of installation access tokens
> 
> - Tightly-scoped tokens with well-defined permission sets and expiration times (1 hour, or less if revoked manually using the API).
> - Dedicated rate limits that grow with your organization.
> - Decoupled from GitHub user identities, so they do not consume any licensed seats.
> - Never granted a password, so cannot be directly signed in to.

Periods need to be removed from each list line, as each line is not a complete sentence (per our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists))

**Comment by Abebayew** [comment]
Hello

**Comment by nguyenalex836** [comment]
Closing as the following PR will address this issue once merged (when repo freeze ends on 9/16) - https://github.com/github/docs/pull/34540
