### ISSUE TITLE
Wrong sub-title in the French version of `authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent`

### ISSUE THREAD

**Issue by Ptitet** [github/docs#34531]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/fr/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key

### What part(s) of the article would you like to see updated?

The sub-title linked above in wrong in the french version. In english, it is about creating an SSH key, but in french it is about creating a GPG key. Only the title is affected, the article itself is correctly translated.
In the french version, GPG shoud be replaced with SSH.

**Comment by nguyenalex836** [comment]
@Ptitet Thanks for reaching out, and flagging this! Since we us an internal, automated solution for our translated docs, I will flag your request for our team 💛

For more information on translations, please see https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations ✨

**Comment by Abdallahalowi** [comment]
.github/CODE_OF_CONDUCT.md

**Comment by Abdallahalowi** [comment]
content/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/managing-your-cookie-preferences-for-githubs-enterprise-marketing-pages.md
