### ISSUE TITLE
Fix an incorrect spelling in 'Quickstart for writing on GitHub'

### ISSUE THREAD

**Issue by word-wiz** [github/docs#34552]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/quickstart-for-writing-on-github

### What part(s) of the article would you like to see updated?

One small incorrect spelling, 'expandible', in section 'Adding a collapsed section'.

**Comment by nguyenalex836** [comment]
@word-wiz Thank you for opening an issue and linking it to your PR! ✨
