### ISSUE TITLE
Coverage.py doesn't appear as an option for additional feature in codespace vscode tutorial

### ISSUE THREAD

**Issue by simtheverse** [github/docs#34580]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/setting-up-your-python-project-for-codespaces

### What part(s) of the article would you like to see updated?

In the step that says:

`A list of additional features is displayed. We'll install Coverage.py, a code coverage tool for Python. To install this tool, type py, select Coverage.py (via pipx), then click OK.`

I have followed along in the tutorial. Coverage.py doesn't appear as an option for me when I type py. I tried typing Coverage.py directly and it also didn't appear.

**Comment by nguyenalex836** [comment]
Hello @simtheverse 👋 !

This question would best be handled by our wonderful [support team](https://support.github.com/request) ✨ Please reach out to them for assistance!

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue 💛

**Comment by nguyenalex836** [comment]
Hello @simtheverse 👋 !

This question would best be handled by our wonderful [support team](https://support.github.com/request) ✨ Please reach out to them for assistance!

If there's anything in the documents that you have suggestions for updating after speaking with them, please feel free to open an issue 💛

**Comment by simtheverse** [comment]
I don't need support <3 just drawing attention that this step isn't how it is illustrated.
