### ISSUE TITLE
No mention of status: filtering for PR search

### ISSUE THREAD

**Issue by PowerfulBacon** [github/docs#34585]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests.md

### What part(s) of the article would you like to see updated?

There is no mention of the status: filters when browsing PRs. `status:success` is valid, and filters PRs down to those which have passing workflows. `status:failure` is also a valid search term.

I am not sure what other terms are valid.

### Additional information

Note that this is explicitly not to do with review-status, status is about CI checks.

**Comment by nguyenalex836** [comment]
@PowerfulBacon Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by subatoi** [comment]
Hi @PowerfulBacon, thanks for raising an issue before raising a PR—we really appreciate it.

In this case, I would point you to https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests, which is linked to under "Further reading" on the page you highlighted. 

I do think you've highlighted a poor user experience here that should be improved. Unfortunately, given the complexity involved across multiple pages (and likely, coordination with internal stakeholders), it's not something we'd be able to coordinate as an open-source issue, and open to contributors.

I'm sorry I can't give you a better answer here, but please be assured that I'll highlight this internally. I'll leave this open temporarily in case you have any further questions.

**Comment by PowerfulBacon** [comment]
Thank you, that's perfect.

**Comment by Shahrulluqman77** [comment]
Shahrul Luqman
