### ISSUE TITLE
Link to webhook event for `pull_request_target` uses a non-existent anchor

### ISSUE THREAD

**Issue by muzimuzhi** [github/docs#34583]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target

### What part(s) of the article would you like to see updated?

In docs for the `pull_request_target` event, the link to the corresponding webhook event uses a non-existent `pull_request_target` webhook event as the anchor, `pull_request_target`. So clicking on the link and it simply stays at the top of the doc page "Webhook events and payloads".

> For information about each activity type, see "[Webhook events and payloads](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_target)."

<img width="719" alt="image" src="https://github.com/user-attachments/assets/3c07e60b-acf2-4aab-a864-92475749315a">

According to the doc pages [Events that trigger workflows](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows) and [Webhook events and payloads](https://docs.github.com/en/webhooks/webhook-events-and-payloads), there is no separate `pull_request_target` webhook event. Events `pull_request` and `pull_request_target` trigger the same `pull_request` webhook event.

**Comment by tawhidnazari57** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
> 
> ### What part(s) of the article would you like to see updated?
> In docs for the `pull_request_target` event, the link to the corresponding webhook event uses a non-existent `pull_request_target` webhook event as the anchor, `pull_request_target`. So clicking on the link and it simply stays at the top of the doc page "Webhook events and payloads".
> 
> > For information about each activity type, see "[Webhook events and payloads](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_target)."
> 
> <img alt="image" width="719" src="https://private-user-images.githubusercontent.com/6376638/367566142-3c07e60b-acf2-4aab-a864-92475749315a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTcxMjgsIm5iZiI6MTcyNjQxNjgyOCwicGF0aCI6Ii82Mzc2NjM4LzM2NzU2NjE0Mi0zYzA3ZTYwYi1hY2YyLTRhYWItYTg2NC05MjQ3NTc0OTMxNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMTYxMzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM4NjFlZjJiYzdhMDk4ZGIyZmFlODkzNzA5MmZmYTUyNGY0MGVkN2ZmZjJlZjQwOGU3NTkwZGRhMjUwN2RjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0P9WqMjarLLB7LFh8QFJcq7SsaHu0g5sBu2WqFLOPo4">
> According to the doc pages [Events that trigger workflows](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows) and [Webhook events and payloads](https://docs.github.com/en/webhooks/webhook-events-and-payloads), there is no separate `pull_request_target` webhook event. Events `pull_request` and `pull_request_target` trigger the same `pull_request` webhook event.
> 
> ### Additional information
> _No response_
