### ISSUE TITLE
Github Education for Homeschoolers

### ISSUE THREAD

**Issue by zanderlewis** [github/docs#34595]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Github Education

### What part(s) of the article would you like to see updated?

Details on how to apply to Github Education as a homeschooler. Especially homeschoolers who homeschool at their house.

**Comment by nguyenalex836** [comment]
@zanderlewis Hello! 👋 Thank you for opening an issue! We're reaching out to our GitHub Education SME team regarding your question, and will update once we have more info 💛

**Comment by zanderlewis** [comment]
> @zanderlewis Hello! 👋 Thank you for opening an issue! We're reaching out to our GitHub Education SME team regarding your question, and will update once we have more info 💛 

Thank you for the update :)

**Comment by AdityaSrivastava185** [comment]
can i work on the issue ?

**Comment by nguyenalex836** [comment]
@AdityaSrivastava185 Hello! 👋 This issue is still being reviewed by our GitHub Education SME team. Once we have a clear idea of what the next steps should be regarding this issue, we'll update here 💛

**Comment by nguyenalex836** [comment]
@zanderlewis Thank you so much for your patience while our GitHub Education team reviewed! 💛 They wanted to point you toward the following information and docs regarding [applying as a homeschooler](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-education-for-students/apply-to-github-education-as-a-student#requirements) -

> The short answer is yes, homeschoolers can apply for and get access to Student benefits (Student Developer Pack).
> 
> - [Student Developer Pack - Common Rejection Reasons](https://github.com/orgs/community/discussions/111352)
> - [About the Student Developer Pack](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-education-for-students/about-github-education-for-students)
> - [How to apply](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-education-for-students/apply-to-github-education-as-a-student)
> - [What if my application isn’t approved?](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-education-for-students/why-wasnt-my-application-to-github-education-for-students-approved)
> - [Student Developer Pack Partner offer FAQs & full list](https://github.com/education/Student-Developer-Pack-Current-Partners-FAQ/blob/main/README.md)
> - [What is the GitHub Community Exchange](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-education-for-students/about-github-community-exchange)
> - [GitHub Education Overview for Students](https://youtu.be/HIVFdN9VGgw?feature=shared)
> - [Getting started in open source](https://www.twitch.tv/videos/2138897966?collection=0UAVKpQ2jBbFzg)
> - [Not-ternships](https://www.twitch.tv/videos/2138897966)
> - [Managing your profile ReadMe](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme)
> - [How to Create a GitHub Profile READ ME](https://youtu.be/ktN5tDfQ_g8?feature=shared)
> 
> > Yes, home-schooled students can apply for the GitHub Student Developer Pack. To apply, you'll need to provide documentation that verifies your current enrollment status as a home-schooled student, such as:
> > A current transcript
> > A pdf from your school board that verifies you are home-schooled
> > GitHub has established eligibility requirements to prevent abuse of the program. While the pack is primarily intended for students enrolled in educational institutions, GitHub also considers applications from homeschooled students and learners from non-traditional learning environments.

We hope this information helps!
