### ISSUE TITLE
Add Jetbrains Writeside to the liste of the jetbrains compatible IDE with Copilot

### ISSUE THREAD

**Issue by MrArnaudMichel** [github/docs#34625]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot?tool=jetbrains#prerequisites

### What changes are you suggesting?

JetBrains Writeside is an IDE specifically designed for creating technical documentation and structured text content. As more developers and technical writers use this IDE to write, manage, and organize their documentation, adding Writeside to the list of IDEs compatible with GitHub Copilot allows users to leverage Copilot's intelligent code completion when creating documentation. This can greatly improve productivity, enhance documentation quality, and reduce errors.

**Comment by nguyenalex836** [comment]
@MrArnaudMichel Thank you for opening an issue and linking it to your PR! ✨
