### ISSUE TITLE
Installing Actions Runner Controller - Issue

### ISSUE THREAD

**Issue by seilorjunior** [github/docs#34636]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller.md

### What part(s) of the article would you like to see updated?

Installing Actions Runner Controller
To install the operator and the custom resource definitions (CRDs) in your cluster, do the following.

In your Helm chart, update the NAMESPACE value to the location you want your operator pods to be created. This namespace must allow access to the Kubernetes API server.
Install the Helm chart.
The following example installs the latest version of the chart. To install a specific version, you can pass the --version argument along with the version of the chart you wish to install. You can find the list of releases in the [GitHub Container Registry](https://github.com/actions/actions-runner-controller/pkgs/container/actions-runner-controller-charts%2Fgha-runner-scale-set-controller).

NAMESPACE="arc-systems"
helm install arc \
    --namespace "{% raw %}${NAMESPACE}{% endraw %}" \
    --create-namespace \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
For additional Helm configuration options, see [values.yaml](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/values.yaml) in the ARC documentation.

To enable ARC to authenticate to {% data variables.product.company_short %}, generate a {% data variables.product.pat_v1 %}. For more information, see [AUTOTITLE](https://github.com/github/docs/blob/main/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api#deploying-using-personal-access-token-classic-authentication).

### Additional information

The first part the process does not work.

If we just run the helm install, we get this error.
helm install arc --namespace arc-systems --create-namespace oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
Error: INSTALLATION FAILED: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden

**Comment by seilorjunior** [comment]
is need to add in the docs that is need to run the gh auth token | helm registry login ghcr.io -u propyless --password-stdin first.

**Comment by nguyenalex836** [comment]
@seilorjunior Thank you for opening an issue and linking it to your PR! ✨

**Comment by Link-** [comment]
@seilorjunior - the reason why you're getting the 403 is due to rate limiting not authentication problems. If you're using a shared public IP with other users, you might hit into this issue.

Authentication is not a requirement to pull the package as it is public. If other users choose to authenticate, they will have their own ways of doing so and we do not wish to be opinionated in that regard.

Thank you for opening this issue and creating the PR but we will not be proceeding with this change.

**Comment by seilorjunior** [comment]
@Link- 

> @seilorjunior - the reason why you're getting the 403 is due to rate limiting not authentication problems. If you're using a shared public IP with other users, you might hit into this issue. You can read more about it in: [Primary rate limit for unauthenticated users](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users)
> 
> Authentication is not a requirement to pull this helm chart package since it is public. If other users choose to authenticate, they will have their own ways of doing so and we do not wish to be opinionated in that regard.
> 
> Thank you for opening this issue and creating the PR but we will not be proceeding with this change.

@Link- i dont think that was regarding rate, my issue was when helm needs to download the image. 
https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden

**Comment by Link-** [comment]
@seilorjunior - that package is downloadable without authentication.
