### ISSUE TITLE
remove incorrect reference to `redirect_uri`

### ISSUE THREAD

**Issue by akorzynski** [github/docs#34651]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app

### What part(s) of the article would you like to see updated?

`redirect_uri` is **not** a parameter to the call that exchanges the OAuth2 code for the token. It's a parameter to an earlier call: the one that redirects the user back to the app.

**Comment by nguyenalex836** [comment]
@akorzynski Thank you for opening an issue and linking it to your PR! ✨
