### ISSUE TITLE
Model picker is VS Code Insiders only

### ISSUE THREAD

**Issue by digitarald** [github/docs#34668]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Not mentioned in https://docs.github.com/en/copilot/using-github-copilot/asking-github-copilot-questions-in-your-ide?tool=vscode#changing-your-ai-model and already causes confusion.

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/copilot/using-github-copilot/asking-github-copilot-questions-in-your-ide?tool=vscode#changing-your-ai-model

**Comment by nguyenalex836** [comment]
Leaving the `waiting for review` label off of this issue as a linked PR has been opened for review internally 💛

**Comment by nguyenalex836** [comment]
Was unable to link corresponding PR, but as that PR has been merged, closing this issue 💛
