### ISSUE TITLE
Remove periods from list in about-billing-for-github-codespaces#storage-costs-for-prebuilds

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34675]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces#storage-costs-for-prebuilds

### What part(s) of the article would you like to see updated?

> The total storage costs associated with a prebuild configuration will depend on the following factors.
> 
> - The price of storage per GB. See the table earlier in this article.
> - The size of the generated prebuild in GB.
> - The number of regions in which the prebuild is available (because a copy of the prebuild is stored in each region).
> - The number of older versions of the prebuild that are retained.

Periods should be removed from this list as each line as not a complete sentence per our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists). 

Should look like the following after the update - 

> The total storage costs associated with a prebuild configuration will depend on the following factors.
> 
> - The price of storage per GB (see the table earlier in this article)
> - The size of the generated prebuild in GB
> - The number of regions in which the prebuild is available (because a copy of the prebuild is stored in each region)
> - The number of older versions of the prebuild that are retained

**Comment by Paulitos** [comment]
Stop removing the 'triage' label, it appears after when you submit the pull request. I don't know how to pin staff but I won't keep contributing to whatever issue you open.

**Comment by nguyenalex836** [comment]
@Paulitos Hello! 👋 I think there's some confusion - I am part of GitHub staff and a maintainer in this repo 💛 Removing the `triage` label that's auto-applied to the issue upon creation gives the community the green light to tackle this issue.

I see you've submitted a PR for this issue - thank you! I'll be reviewing it shortly ✨

**Comment by nguyenalex836** [comment]
@Paulitos Hello! 👋 I think there's some confusion - I am part of GitHub staff and a maintainer in this repo 💛 Removing the `triage` label that's auto-applied to the issue upon creation gives the community the green light to tackle this issue.
