### ISSUE TITLE
Move period inside quotations in connecting-an-azure-subscription#message-need-admin-approval

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34674]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-the-plan-for-your-github-account/connecting-an-azure-subscription#message-need-admin-approval

### What part(s) of the article would you like to see updated?

> For more information, review "[Prerequisites](https://docs.github.com/en/billing/managing-the-plan-for-your-github-account/connecting-an-azure-subscription#prerequisites)".

Move period inside quotation marks to maintain consistency with other docs (and [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide))

**Comment by tonnyhawk111-code** [comment]
Delete my account please!

Dne st 27. 8. 2025 22:16 uživatel amr01060 ***@***.***>
napsal:

**Comment by Edgarruiz8585** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> @Edgarruiz8585
> ### What article on docs.github.com is affected?
> 
> https://docs.github.com/en/billing/managing-the-plan-for-your-github-account/connecting-an-azure-subscription#message-need-admin-approval
>  https://github.com/Edgarruiz8585 
> ### What part(s) of the article would you like to see updated?
> 
> > For more information, review ruizariasedgarmanuel@gmail.com "[Prerequisites](https://docs.github.com/en/billing/managing-the-plan-for-your-github-account/connecting-an-azure-subscription#prerequisites)".
> ruizariasedgarmanuel@gmail.com
> Move period inside quotation marks to maintain consistency with other docs (and [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide))
> 
> ### Additional information
> 
> _No response_

**Comment by Edgarruiz8585** [comment]
+ > ruizariasedgarmanuel@gmail.com
