### ISSUE TITLE
404 error on actions getting started article

### ISSUE THREAD

**Issue by ChehST** [github/docs#34679]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/actions/getting-started-with-github-actions

### What changes are you suggesting?

Link doesn't work. It throws 404 error.

Preconditions:
Fresh repository with empty actions

I've met this problem at GitHub.com/{user}/{repo}/ + actions/new
As I've understood: if no workflow was created /action endpoint will redirect to /actions/new endpoint
<img width="870" alt="Screenshot 2024-09-21 at 12 08 27" src="https://github.com/user-attachments/assets/b1809bae-0c74-4454-9e06-5a5cd9259e0e">

There are three blocks at the bottom of the page in section "Learn more about GitHub Actions"
The first block contain this link

<img width="1031" alt="Screenshot 2024-09-21 at 12 12 09" src="https://github.com/user-attachments/assets/58d6f3e5-1e53-4214-870a-a5e52c4b42af">

**Comment by nguyenalex836** [comment]
@jamesericdavidson Thank you for the nudge! Our team is aware and will address as soon as we can 💛
