### ISSUE TITLE
`jobs.<job_id>.steps[*].timeout-minutes` doesn't describe input `< 1`, or give examples

### ISSUE THREAD

**Issue by hamirmahal** [github/docs#34685]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes

### What part(s) of the article would you like to see updated?

1. The docs should say what happens if users try to set `timeout-minutes` to a value less than `1`, like `0.01`.
2. The docs should give correct example usage for that property.

**Comment by hamirmahal** [comment]
For 2, something like
```yml
my-job:
 runs-on:         ubuntu-latest
 timeout-minutes: 30
```
from https://stackoverflow.com/questions/59073731/set-default-timeout-on-github-action-pipeline would work well.

**Comment by nguyenalex836** [comment]
@hamirmahal Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by hamirmahal** [comment]
@nguyenalex836 You're welcome!

**Comment by Nmt112** [comment]
> ### کد رفتار
> * [x] [من قوانین رفتار](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md) پروژه GitHub Docs را خوانده ام و با آن موافقم[](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### کدام مقاله در docs.github.com تحت تأثیر قرار گرفته است؟
> https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes
> 
> ### دوست دارید کدام بخش از مقاله به روز شود؟
> 1. `timeout-minutes`اگر کاربران سعی کنند مقداری کمتر از `1`، مانند را تنظیم کنند، اسناد باید بگویند چه اتفاقی می‌افتد `0.01`.
> 2. اسناد باید استفاده صحیح از آن ویژگی را ارائه دهند.
> 
> ### اطلاعات تکمیلی
> _بدون پاسخ_

20₹100%50

**Comment by hamirmahal** [comment]
@nguyenalex836 You're welcome! Would you like any other changes to #34879?

**Comment by hamirmahal** [comment]
Out of curiosity, where can I find metrics for https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions?

It'd be interesting to see how many views that page gets, and how much usage docs.github.com gets in general.

**Comment by nguyenalex836** [comment]
> @nguyenalex836 You're welcome! Would you like any other changes to https://github.com/github/docs/pull/34879?

Your changes look perfect ✨ getting that merged now!

> Out of curiosity, where can I find metrics for https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions?

Let me do some digging, and I'll get back to you! 💛
