### ISSUE TITLE
Enhance Documentation on Theme-Specific Image Display with Illustration and <img> Tag Clarification

### ISSUE THREAD

**Issue by syed-ateeb-naveed** [github/docs#34694]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### Article Affected

[Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

### Section Affected

[Specifying the theme an image is shown to](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)

### Issue Description

The current section lacks an illustration of the image behaviour based on the theme, and the purpose of the `<img>` tag is not clearly defined. These additions would improve understanding and clarity for readers.

### Screenshot Of The Section

![image](https://github.com/user-attachments/assets/c27d31d4-6284-48e9-8fc1-5261ed7ed833)

### What part(s) of the article would you like to see updated?

The section titled [“Specifying the theme an image is shown to”](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) should be updated. Specifically:

1. **Add an Illustration**: Include images to demonstrate how the sun appears in light mode and the moon in dark mode.
2. **Clarify the `<img>` Tag**: Explain the purpose of the `<img>` tag as a fallback for browsers that don’t support the `prefers-color-scheme` feature.

### Why should the docs be changed? What use cases does it support?

These updates will make the documentation clearer and more practical. Visual aids help users quickly understand the concept, and clarifying the `<img>` tag’s role will reduce confusion for developers implementing theme-specific images.

### What is the expected outcome or behavior?

Users will better understand how to apply theme-specific images with confidence, improving their projects’ appearance across light and dark modes.

**Comment by nguyenalex836** [comment]
@syed-ateeb-naveed Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
@syed-ateeb-naveed Thank you for opening an issue and linking it to your PR! ✨
