### ISSUE TITLE
Clarify use of OAuth credential helpers in local Git installation

### ISSUE THREAD

**Issue by JDLH** [github/docs#34710]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git

### What part(s) of the article would you like to see updated?

Instead of telling readers to "install and use GitHub CLI" or "install and use Git Credential Manager" with no explanation of authentication, instead also mention the option of other Git credential helpers. And, mention that OAuth authentication is happening behind the scenes.  Add a tip about the need for organization approval of OAuth apps not pre-approved by GitHub.

This is based on my difficulties understanding how to get OAuth authentication from my local Git installation. The current content does not mention OAuth, or the need for organisation approval of OAuth apps not pre-approved by GitHub. Both those omissions caused obstacles for me. 

### Additional information

I have a pull request with suggested improvements all ready to go: #34712 .

[Edited to add PR number.]

**Comment by nguyenalex836** [comment]
@JDLH Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
@JDLH Thank you for opening an issue and linking it to your PR! ✨

**Comment by AdityaSrivastava185** [comment]
@JDLH  I would like to contribute to the issue byt before contributing to it ,i would like to ask that you want to include the clear explanation of the OAuth and OAuth in local git installations ?

**Comment by JDLH** [comment]
@AdityaSrivastava185 , thank you for the offer. My inclination is to separate the changes. Let this one get included, then make a second change to improve it even more.  If we tie them together, they may get bogged down and neither will get accepted.

But there is no harm in planning ahead. Assume that my PR #34712 gets accepted. What specific changes would you suggest for it?  If you would you like me to suggest better wording, then what is not clear to you about the wording in #34712?

**Comment by AdityaSrivastava185** [comment]
I understand @JDLH  , I can't suggest anything specific before seeing your changes but  make sure to add all the details which could be little bit confusing for the beginners such as including use cases and troubleshooting tips because , i have found this common things either missing or not clear in the documentations 
I hope it will help you 
Thank you

**Comment by JDLH** [comment]
> I can't suggest anything specific before seeing your changes

You can see my proposed changes in pull request #34712 . See especially the links in the **Content directory changes** section. e.g. the [preview of the page reads with my changes](https://docs-34712-17710b.preview.ghdocs.com/get-started/getting-started-with-git/caching-your-github-credentials-in-git) compared to [the current page](https://docs.github.com/get-started/getting-started-with-git/caching-your-github-credentials-in-git).

Does that help?

**Comment by AdityaSrivastava185** [comment]
Yes , it's helpful 🙂

**Comment by victorinojeffrey** [comment]
JDLH:patch-34710-caching-credentials-oauth - Start your journey - GitHub Docs - https://github.com/victorinojeffrey/dev.g.jeffreyvictorino.git - https://g.dev/jeffreyvictorino92
