### ISSUE TITLE
Need to add more email details

### ISSUE THREAD

**Issue by llvee** [github/docs#34756]
👋 Hello GH users & team members, thank you all for considering these changes.

Today I decided to explore collaborating, communicating with other users more. 

While studying the documentation for inviting others to repositories I considered the security implications of the invite feature specifically. 

While thinking more about security implications I noticed that there was not enough information in the docs page to fully understand or know them. 

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository.md

### What part(s) of the article would you like to see updated?

The article mentions sending emails, falls short when it comes to sharing an exact template or message used to invite others. This is important for security as it's currently impossible to ascertain whether inviting another person to a repository shares the login email for the account with them or not. 

### Additional information

This affects anyone who uses the invitation docs to understand the feature better. Adding more information about exact emails sent can help prevent lots of unauthorised account accesses, data leaking. 

🚀 How Docs/Skills can be:
<br>
<img height="400px" width="400px" src="https://github.com/user-attachments/assets/673708e0-bdd8-4c83-9e80-80edec49d279" />

🧔 Not Me: 
<br>
<img height="400px" width="400px" src="https://github.com/user-attachments/assets/e05577ae-145e-4193-95ed-b7a30c46f067" />

Please: 

💡 View my other Github issues, community discussions (updating with links soon.) 
💡 Follow my account  
💡 Fork repositories
💡 Star repositories
💡 Comment here for further networking
💡 Reach out if you'd like to support me on Buymeacoffee, Ko-fi & similar channels

What are your thoughts on the above?

Did you notice any other improvements that can be made to documentation or skills?

**Comment by nguyenalex836** [comment]
@nguyenalex836 Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by phionex2** [comment]
Hi @nguyenalex836,

Thank you for your quick response and for triaging this issue! I appreciate your efforts in addressing the concerns regarding the email invitation process for collaborators.

I believe including an example email template in the documentation would greatly enhance clarity and security for users. It would help them understand what information is shared when inviting collaborators and alleviate concerns about potential data leakage.

suggested template for the invitation email that could be added to the documentation:

Subject: Invitation to collaborate on the repository <REPOSITORY_NAME>

Hello,

You have been invited by <INVITER_USERNAME> to collaborate on the repository "<REPOSITORY_NAME>" on GitHub.

To accept the invitation, click the link below:
<INVITATION_LINK>

Best regards,
The GitHub Team

In addition to the template, it might be useful to mention that the inviter's email address is not shared with the invitee, which could provide an extra layer of reassurance for users.

Thank you for considering this suggestion, and I look forward to any further feedback!

**Comment by nguyenalex836** [comment]
@phionex2 Thank you for the suggestion! Our writers will review your template once they've had a chance to look into this issue 💛

**Comment by phionex2** [comment]
I appreciate the opportunity to network further with engineers like yourself, and I’m always eager to connect and collaborate!

@llvee Thank you for sharing the email template. I agree that updating the documentation with the current email format will help users understand security risks better. I also support the idea of removing usernames from the email for added privacy.

**Comment by subatoi** [comment]
Hello, I'm not sure what changes you're proposing exactly—which article specifically do you mean? You've put https://github.com/github/docs/tree/main/content/account-and-profile/setting-up-and-managing-your-personal-account-on-github in the original issue, but this is a series of articles rather than one specifically. Also: our team doesn't control what text is sent when a user is invited to collaborate on a repository and I'm afraid I'm not seeing what help a template would be. One of the mechanisms for inviting users is via their email address, but if this is done via a username (as the documentation states is one of the options) then there's no reason the inviter should see the invitee's email address as part of that process. 

I'll defer back to @nguyenalex836 and I'll circle back if there's something I'm missing.

**Comment by nguyenalex836** [comment]
@llvee Let us know your thoughts regarding @subatoi's last comment, and we can determine next best steps after 💛

**Comment by subatoi** [comment]
Thank you for your reply—

> Adding the current invite to repo template to the docs is a must in order for engineers to fully understand the security risks associated with inviting others to repositories.

I'm afraid I still don't see how this would be helpful for users. The text is subject to change but simply states something along the lines of "<USER> has invited you to collaborate..." which is described on the page you've linked to: "The user will receive an email inviting them to the repository."

I simply don't see enough reason to action this particular request so I'm going to close this issue.

Thank you for your interest in the GitHub Docs! Please feel free to look at our issues marked `help wanted`.
