### ISSUE TITLE
Add links to Git Bash resources for troubleshooting GitHub Docs tutorials

### ISSUE THREAD

**Issue by jlduchaney** [github/docs#34764]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

### What part(s) of the article would you like to see updated?

I'm on the "Creating a branch to work on" step. When I try to follow the instructions, Git Bash says, "fatal: not a valid object name: 'master'". Since the article provides no guidance on troubleshooting Git Bash, the reader's left stranded at a dead end.

Can you please add links for where users can go for any Git Bash errors they might encounter in this tutorial?

![2024-09-28](https://github.com/user-attachments/assets/8852e1da-643a-4845-a2e3-49e646757336)

### Additional information

I'm teaching myself how to code and was referred to GitHub Docs via MDN Learning Area/Guides. [Contributing to a project](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project) is the third out of five links they recommend in their [Git and GitHub](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/GitHub) article. 

Since I suspect many other learners are arriving at this tutorial in the same way, it might be helpful to note whether any prior Git Bash knowledge is prerequisite to successfully complete the steps (via the above recommended solution).

**Comment by nguyenalex836** [comment]
@jlduchaney Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
@jlduchaney Thank you for your patience while our team reviewed!

I appreciate this is frustrating and I’m sorry you’ve had that experience. Generally we take an “opinionated” approach when it comes to the docs content, so we’ll always focus on the core experience, and in this case, that’s the “[GitHub flow](https://docs.github.com/en/get-started/using-github/github-flow)“. As we can’t be sure how the Git Bash experience will change and it’s not our product, it isn’t something we can help with at this time 💛 

What I will say is that we’re aware we need to address some issues in the “Getting started” content as a whole, and I’ll make a note of your feedback in the internal conversations around that initiative.

**Comment by nguyenalex836** [comment]
@jlduchaney Thank you so much for sharing this insight! We appreciate you taking the time to piece this all together for our team 💛 happy Hacktoberfest to you as well! 🎃
