### ISSUE TITLE
The notification icon is not a bell anymore

### ISSUE THREAD

**Issue by adriancuadrado** [github/docs#34798]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/viewing-and-triaging-notifications/managing-notifications-from-your-inbox

### What part(s) of the article would you like to see updated?

![image](https://github.com/user-attachments/assets/5cea1d69-75d4-47e3-8172-2cb1390c0941)

**Comment by nguyenalex836** [comment]
@adriancuadrado Thank you for opening an issue and linking it to your PR! ✨
