### ISSUE TITLE
Add "...doesn't work" to the end of syntax rules for gitignore files examples in about-code-owners.md

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34805]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What part(s) of the article would you like to see updated?

> {% warning %}
> 
> **Warning:** There are some syntax rules for gitignore files that _do not work_ in CODEOWNERS files:
> * Escaping a pattern starting with `#` using `\` so it is treated as a pattern and not a comment
> * Using `!` to negate a pattern
> * Using `[ ]` to define a character range
> 
> {% endwarning %}

Per [this issue](https://github.com/github/docs/issues/19818#issuecomment-2378169597), each of the examples in this list should have "doesn't work" appended to the end for clarity - 

> {% warning %}
> 
> **Warning:** There are some syntax rules for gitignore files that _do not work_ in CODEOWNERS files:
> * Escaping a pattern starting with `#` using `\` so it is treated as a pattern and not a comment doesn't work
> * Using `!` to negate a pattern doesn't work
> * Using `[ ]` to define a character range doesn't work
> 
> {% endwarning %}

**Comment by SirJosh1987** [comment]
Is this on me?

**Comment by nguyenalex836** [comment]
@SirJosh1987 Apologies, can you clarify what you mean by your last message? Are you asking if you can submit a PR for this issue? 💛

**Comment by SirJosh1987** [comment]
My friend all I know is I get a lot of notifications from git and all I do it start clicking on things never really doing anything I feel like

**Comment by nguyenalex836** [comment]
@SirJosh1987 I see, thank you for explaining! 

If you're looking to have those notification issues solved, we'd recommend checking out this doc regarding [configuring notifications](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications) or reaching out to our wonderful [support team](https://support.github.com/request) to see if they can assist 💛

**Comment by TheGiraffe3** [comment]
* #34814 will fix this
