### ISSUE TITLE
Typo: URI when it should be URL

### ISSUE THREAD

**Issue by TheGiraffe3** [github/docs#34812]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request

### What part(s) of the article would you like to see updated?

Fix the typo.

### Additional information

I've a linked PR for this.
```[tasklist]
### Tasks
- [ ] https://github.com/github/docs/pull/34813
```

**Comment by nguyenalex836** [comment]
Closing per comment [here](https://github.com/github/docs/pull/34813#issuecomment-2388914185) 💛

**Comment by TheGiraffe3** [comment]
Could you close this as not planned?

**Comment by nguyenalex836** [comment]
> Could you close this as not planned?

Of course, thanks for the nudge! 💛
