### ISSUE TITLE
sarif-support-for-code-scanning.md:runAutomationDetails fix  calendar use

### ISSUE THREAD

**Issue by SwuduSusuwu** [github/docs#34819]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#runautomationdetails-object

### What changes are you suggesting?

https://github.com/github/docs/compare/main...SwuduSusuwu:docs:patch-1
https://github.com/SwuduSusuwu/docs/commit/3217aa571c9f0caac5b476050a914d68aa457f3c
> The previous example was "2021-02-01 == February 2, 2021" which is not normal calendar use.
The new example fixes this.

**Comment by nguyenalex836** [comment]
@SwuduSusuwu Thank you for opening an issue and linking it to your PR! ✨

**Comment by SwuduSusuwu** [comment]
https://github.com/github/docs/compare/main...SwuduSusuwu:docs:patch-1 has 1 new commit; new commit is [notice that calendar format is for Europe/US, whereas your system locale can replace this](https://github.com/github/docs/commit/50cd3b9a7df9ab693811d867301162df85489b99)

**Comment by nguyenalex836** [comment]
> #34820 has 1 new commit; new commit is [notice that calendar format is for Europe/US, whereas your system locale can replace this](https://github.com/github/docs/commit/50cd3b9a7df9ab693811d867301162df85489b99)

Hi @SwuduSusuwu! I wanted to point out @subatoi's last comment to you on the linked PR - https://github.com/github/docs/pull/34820#issuecomment-2396133676 💛
