### ISSUE TITLE
Unclear text in the pull request information page

### ISSUE THREAD

**Issue by TheGiraffe3** [github/docs#34811]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### What part(s) of the article would you like to see updated?

It's unclear whether it is possible to have an issue-type pull request template, or if there can only be one type.

### Additional information

_No response._

**Comment by nguyenalex836** [comment]
@TheGiraffe3 Thanks for opening an issue! ✨ 

> It's unclear whether it is possible to have an issue-type pull request template, or if there can only be one type.

Can you clarify what you mean by an issue-type pull request template? Are you referring to a pull request template that's more similar in structure to an issue template? 💛

**Comment by TheGiraffe3** [comment]
The question I was wondering about is if it's possible to set up pull request creation like issue creation - you click the "New Issue" button and are given several options to choose from.

**Comment by nguyenalex836** [comment]
@TheGiraffe3 Ah great question! Let me see if I can get answer from one of our SMEs

**Comment by nguyenalex836** [comment]
@TheGiraffe3 Thanks for your patience while our team reviewed! It looks like [this section](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template) of the docs explains how to set up multiple PR templates, similar to how there can be multiple issues templates:

> * To create multiple pull request templates and use the `template` query parameter to specify a template to fill the pull request body, type _.github/PULL_REQUEST_TEMPLATE/_, then the name of your pull request template. For example, `.github/PULL_REQUEST_TEMPLATE/pull_request_template.md`. You can also store multiple pull request templates in a `PULL_REQUEST_TEMPLATE` subdirectory within the root or `docs/` directories. For more information, see "[AUTOTITLE](/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request)."

Thank you for raising this issue! I'll go ahead and close this, but feel free to comment if there's anything you'd like to add to either the docs or this conversation 💛

**Comment by TheGiraffe3** [comment]
My problem was that the way it's worded is somewhat unclear.
