### ISSUE TITLE
gh cli not implemented "copilot" command?

### ISSUE THREAD

**Issue by ashish-desai-simplisafe** [github/docs#34825]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-in-the-command-line
States that "gh copilot" works.
However, https://cli.github.com/manual/gh does not list it as a valid command.
Additionally validating, in build
```
gh version 2.58.0 (2024-10-01)
https://github.com/cli/cli/releases/tag/v2.58.0
```
does not have it either. So not sure if "gh copilot" is implemented in main branch or something is missing.

### What part(s) of the article would you like to see updated?

Update https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-in-the-command-line to be accurate.

**Comment by nguyenalex836** [comment]
@ashish-desai-simplisafe Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
@ashish-desai-simplisafe Thank you for your patience while our team reviewed! Can you ensure you've checked you have met the prerequisites [here](https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-in-the-command-line)? 💛

**Comment by alphachart** [comment]
???
