### ISSUE TITLE
Improve collapsible section content by adding example of one that is open by default

### ISSUE THREAD

**Issue by mjbear** [github/docs#34836]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections

### What part(s) of the article would you like to see updated?

Add a section detailing how to create a collapsible section that is open by default.

I've created a PR #34837.

### Additional information

This is to add content.

**Comment by ratchanonsuttawas** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections
> 
> ### What part(s) of the article would you like to see updated?
> 
> Add a section detailing how to create a collapsible section that is open by default.
> 
> I've created a PR #34837.
> 
> ### Additional information
> 
> This is to add content.

**Comment by Sexymanyyy** [comment]
Pls delete my acct and unsubscribe me. Idk how I'm on this site even.

**Comment by nguyenalex836** [comment]
@mjbear Thank you for opening an issue and linking it to your PR! ✨
