### ISSUE TITLE
documentation on `on.workflow_dispatch` is not correct/complete

### ISSUE THREAD

**Issue by tomsit-ionos** [github/docs#34884]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch

> This event will only trigger a workflow run if the workflow file is on the default branch.

Note that this text is defined on 1 place (`{% data reusables.actions.workflow-dispatch %}`) and used in several places.
It might be that it is correct in some use cases.

### What part(s) of the article would you like to see updated?

it is possible to run WFs via  `workflow-dispatch`  event on branches other than the default (thru the API, maybe not UI)
there are some ramifications though
  - the WF must have run at least once, otherwise GH doesnt seem to know it's _name_
  - i do this via `GH CLI` by also adding an `on.push` while on a feature branch

see 
- https://github.com/cli/cli/issues/5268
- https://stackoverflow.com/a/71057825/405749

### Additional information

https://github.com/cli/cli/issues/5268

**Comment by nguyenalex836** [comment]
@tomsit-ionos Thank you very much for raising an issue! ✨ While we appreciate the method you've shared to run WFs via the `workflow-dispatch` event on branches other than the default, this method isn't officially supported.

For that reason, we are unable to add this to our docs. We still thank you for your willingness to contribute 🙇 

If you're looking for issues to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on 💛

**Comment by tomsit-ionos** [comment]
hm, that is unfortunate. 
But how do u test a new/modified WF definition before it is merged to main ?

**Comment by nguyenalex836** [comment]
> how do u test a new/modified WF definition before it is merged to main

This question would best be handled by our wonderful [support team](https://support.github.com/request) - please feel free to reach out to them 💛

**Comment by tomsit-ionos** [comment]
hi, 
i think i u might want to reopen this issue, as the API clearly states to be able to pass in a tag/branch name.
![image](https://github.com/user-attachments/assets/c3162b3e-4006-4c27-ad1d-4122bef8ed99)


see https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event

**Comment by nguyenalex836** [comment]
@tomsit-ionos Thank you! We're reviewing this now, and will provide an update after 👍
