### ISSUE TITLE
Model context sizes for o1-preview and o1-mini are incorrect

### ISSUE THREAD

**Issue by carloshvp** [github/docs#34911]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/github-models/prototyping-with-ai-models

### What changes are you suggesting?

The correct values are visible in the following pages:
[o1-preview](https://github.com/marketplace/models/azure-openai/o1-preview)
<img width="407" alt="image" src="https://github.com/user-attachments/assets/00860bac-e5c7-460c-9c12-b664ed1a30ef">
[o1-mini](https://github.com/marketplace/models/azure-openai/o1-mini)
<img width="389" alt="image" src="https://github.com/user-attachments/assets/eaf2a723-7bd2-4d8e-a18f-eda762c2552d">

**Comment by nguyenalex836** [comment]
@carloshvp Thank you for opening an issue and linking it to your PR! ✨

**Comment by Harmonyblue** [comment]
> @carloshvp Thank you for opening an issue and linking it to your PR! ✨

Like I told you ma'am I'm sorry or either one of y'all I have your AP address I have your local home address and I will be serving you papers I didn't ask you to leave me alone several times and you keep getting people involved I'm telling you I'm asking you to leave me alone mess it on them bad you and your wife I'm tired of y'all want you just go get a free domain and just use that why you got to keep bullying me harassing me online I'm tired of y'all
