### ISSUE TITLE
Add documentation for case-sensitive code search / regex mode modifiers

### ISSUE THREAD

**Issue by victorlin** [github/docs#34933]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax

### What part(s) of the article would you like to see updated?

I found out through [StackOverflow](https://stackoverflow.com/a/76229408/4410590) that case-sensitive search can be accomplished with the `(?-i)` mode modifier. The official docs should note this instead of stating "You cannot do case-sensitive searches", which is not true.

Additionally, it would be nice if the section on regular expressions described which mode modifiers are supported by code search. There are [many](https://www.regular-expressions.info/refmodifiers.html), and different flavors of regex are known to support different modifiers.

**Comment by nguyenalex836** [comment]
@victorlin Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by subatoi** [comment]
Hi @victorlin 👋 

> I found out through [StackOverflow](https://stackoverflow.com/a/76229408/4410590) that case-sensitive search can be accomplished with the (?-i) mode modifier. The official docs should note this instead of stating "You cannot do case-sensitive searches", which is not true.

Thanks for bringing that to our attention. I think the best thing to do would be to delete the whole section on "Case sensitivity". 

Before I open that to contributors, I'd like to give you first refusal if you'd like to open a PR yourself?

> Additionally, it would be nice if the section on regular expressions described which mode modifiers are supported by code search. There are [many](https://www.regular-expressions.info/refmodifiers.html), and different flavors of regex are known to support different modifiers.

However, this isn't typically something we'd document. I'd recommend opening a Discussion on this so we can see what kind of traction it gets.

Could I also take a moment to thank you for raising an issue before going ahead and raising a PR—it's much appreciated and makes the experience better for everyone ✨
