### ISSUE TITLE
Sponsorship Webhook Events - Docs show "monthly_price_in_dollars" as a number, but actually arrives as string.

### ISSUE THREAD

**Issue by lucent-sea** [github/docs#3493]
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#sponsorship

### What part(s) of the article would you like to see updated?

The docs show "monthly_price_in_dollars" for sponsorship events as a number:

```
      "monthly_price_in_cents": 500,
      "monthly_price_in_dollars": 5,
```

But they actually arrive as a string (this is from my Recent Deliveries on my sponsors page):

```
      "monthly_price_in_cents": 500,
      "monthly_price_in_dollars": "5.0",
```

**Comment by janiceilene** [comment]
Thanks so much for letting us know @lucent-sea! I've spoken with the engineering team and it looks like it's a bug on their end, not in the docs. They're going to work on a fix and I'll let you know when it's done 💛

**Comment by lucent-sea** [comment]
Thanks for the quick response!  :)  Much appreciated.

**Comment by cheshire137** [comment]
Sorry for the auto-close! I deployed a fix for this, can you confirm you're getting a number back now instead of a string?

**Comment by lucent-sea** [comment]
Is there any way to simulate a sponsor sign-up event?  If not, I'll have to wait for one.  :D

**Comment by cheshire137** [comment]
I think there's not a way to simulate a new sponsor event, but that might be a useful thing to have; I'll mention it to the team!

I'll go ahead and close this issue, but please reopen if the field is still coming back as a string!

**Comment by cheshire137** [comment]
> Is there any way to simulate a sponsor sign-up event?

I learned you may be able to do this via your webhook settings page. The page should show a list of all deliveries and there should be a button to redeliver them.

**Comment by cheshire137** [comment]
Actually, that won't work here I believe because the payload of the webhook should be the same as the first time, so it would still have a string instead of a number.

**Comment by lucent-sea** [comment]
>so it would still have a string instead of a number.

Thanks for the follow-up.  The above statement indeed appears to be correct, though.  :)
