### ISSUE TITLE
The is:archived filter doesn't work as documented

### ISSUE THREAD

**Issue by dannystaple** [github/docs#34940]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#is-qualifier

### What part(s) of the article would you like to see updated?

The article suggests that the term `is:archived` can be used to search. However, this doesn't seem to work when seraching repos or issues (I've not tried it in other places). A `NOT` will clear all  repos shown even though only one is archived.
However, the `archived:true` or `archived:false` filters do work in both repo and issue use cases, and should be documented here. 
This also cross references with https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-based-on-whether-a-repository-is-archived.

**Comment by nguyenalex836** [comment]
@dannystaple Thank you for opening this issue! ✨ 

> However, this doesn't seem to work when seraching repos or issues (I've not tried it in other places).

Before we making changes to the docs, can you reach out to our [support team](https://support.github.com/request) to have them review this? 

They would have the best insight on whether there are other factors affecting the expected behavior of that filter that we should include in any update to the docs 💛

**Comment by BarteJK99** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#is-qualifier
> 
> ### What part(s) of the article would you like to see updated?
> The article suggests that the term `is:archived` can be used to search. However, this doesn't seem to work when seraching repos or issues (I've not tried it in other places). A `NOT` will clear all repos shown even though only one is archived. However, the `archived:true` or `archived:false` filters do work in both repo and issue use cases, and should be documented here. This also cross references with https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-based-on-whether-a-repository-is-archived.
> 
> ### Additional information
> _No response_

![Uploading Screenshot_2024-10-17-23-59-09-745_com.opera.gx.jpg…]()
