### ISSUE TITLE
Add periods to list in persisting-environment-variables-and-temporary-files#for-all-codespaces-for-a-repository

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34948]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/persisting-environment-variables-and-temporary-files#for-all-codespaces-for-a-repository

This issue is intended for newcomers to the OS Docs repo! 💛 

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)✨

### What part(s) of the article would you like to see updated?

> There are three ways that you can set persistent custom environment variables for all codespaces that you create for a repository:
> 
> - You can edit the devcontainer.json configuration file for the repository
> - You can use a custom Dockerfile
> - You can use development environment secrets

Add periods to the end of each list line, as each line is a complete sentence

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by dr0er** [comment]
Hello, can I work on this issue?

**Comment by dr0er** [comment]
Done, waiting for review :)
