### ISSUE TITLE
Remove periods from list in developing-in-a-codespace#about-development-with-github-codespaces

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34947]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/developing-in-a-codespace#about-development-with-github-codespaces

This issue is intended for newcomers to the OS Docs repo! 💛 

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)✨

### What part(s) of the article would you like to see updated?

> You can develop code in a codespace using your choice of tool:
> 
> - A command shell, via an SSH connection initiated using GitHub CLI.
> - One of the JetBrains IDEs, via the JetBrains Gateway.
> - The Visual Studio Code desktop application.
> - A browser-based version of Visual Studio Code.

Remove periods from this list, as each line is not a complete sentence

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by dr0er** [comment]
Hi, can I work on this issue?

**Comment by Reterics** [comment]
Hi @nguyenalex836 

I am new to this repo, can I work on this?

**Comment by dr0er** [comment]
Done, waiting for review :)
