### ISSUE TITLE
Replace colon with a period in persisting-environment-variables-and-temporary-files#preventing-temporary-files-from-being-automatically-deleted

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#34949]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/persisting-environment-variables-and-temporary-files#preventing-temporary-files-from-being-automatically-deleted

This issue is intended for newcomers to the OS Docs repo! 💛 

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)✨

### What part(s) of the article would you like to see updated?

> You can add files or make changes to files outside the `/workspaces` directory: for example...

Replace colon with a period and capitalize the "f" in "for"

**Comment by dr0er** [comment]
Hi, can I work on this issue? :)

**Comment by dr0er** [comment]
Done, waiting for review :)
