### ISSUE TITLE
Update to ordered list in using-github-codespaces-in-your-jetbrains-ide#the-jetbrains-remote-development-connection-process

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#35002]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/using-github-codespaces-in-your-jetbrains-ide#the-jetbrains-remote-development-connection-process

This issue is intended for newcomers to the OS Docs repo! 💛

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ✨

### What part(s) of the article would you like to see updated?

> The basic process behind using a codespace in your JetBrains IDE is as follows.
> 
> - In the JetBrains Gateway application you select one of your active or stopped codespaces.
> - You then choose which JetBrains IDE you want to use.
> - The selected JetBrains IDE is then downloaded to the remote virtual machine that hosts your codespace and source code.
> - The JetBrains thin client application is then downloaded to your local machine and started.
> - The client application connects to the full backend IDE.
> - You can work on your code in the client application in just the same way you would in a local environment.

Update this unordered list to an ordered list

**Comment by JP-sDEV** [comment]
Hi could I attempt to fix this issue?

**Comment by nguyenalex836** [comment]
> Hi could I attempt to fix this issue?

@JP-sDEV Of course! 💛
