### ISSUE TITLE
Remove periods from list in using-github-codespaces-in-your-jetbrains-ide#prerequisites

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#35003]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/using-github-codespaces-in-your-jetbrains-ide#prerequisites

This issue is intended for newcomers to the OS Docs repo! 💛

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ✨

### What part(s) of the article would you like to see updated?

> To work in a codespace in a JetBrains IDE you need:
> 
> - A valid JetBrains license.
> - The JetBrains Gateway application, versions 2023.3.* or 2024.1.*.
> - An existing codespace running on a virtual machine that has at least 4 cores. The codespace must also be running an SSH server. For more information, see "[Codespace running an SSH server](https://docs.github.com/en/codespaces/developing-in-a-codespace/using-github-codespaces-in-your-jetbrains-ide#codespace-running-an-ssh-server)."

Remove periods from first two lines of this list, as they are not complete sentences

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by 5AIPAVAN** [comment]
i am a beginner to opensource can i take this @nguyenalex836 :-)

**Comment by 5AIPAVAN** [comment]
can you please assign me this  @nguyenalex836

**Comment by nguyenalex836** [comment]
@5AIPAVAN Hello! 👋 We don't generally assign issues to contributors - if you find an issue to work on, you are welcome to open a PR with a fix 💛

**Comment by 3406Momo** [comment]
#****
