### ISSUE TITLE
Make reference consistent in getting-started-with-github-codespaces-for-machine-learning#opening-your-codespace-in-jupyterlab

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#35001]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/getting-started-with-github-codespaces-for-machine-learning#opening-your-codespace-in-jupyterlab

This issue is intended for newcomers to the OS Docs repo! 💛

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ✨

### What part(s) of the article would you like to see updated?

> For more information about the default image, see "[Introduction to dev containers](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers#using-the-default-dev-container-configuration)" and [the devcontainers/images repository](https://github.com/devcontainers/images/tree/main/src/universal).

Remove hyperlink from the words "the" and "repository" to maintain consistency with other references to repositories in this doc. It should look like the following -

> For more information about the default image, see "[Introduction to dev containers](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers#using-the-default-dev-container-configuration)" and the [devcontainers/images](https://github.com/devcontainers/images/tree/main/src/universal) repository.

**Comment by 5AIPAVAN** [comment]
please assign me this @nguyenalex836 :-)

**Comment by nguyenalex836** [comment]
@5AIPAVAN Hello! 👋 We don't generally assign issues to contributors - if you find an issue to work on, you are welcome to open a PR with a fix 💛

**Comment by Bi744** [comment]
![scanning_logos](https://github.com/user-attachments/assets/930cdd40-f2aa-4e55-8525-e94f693ed25c)
