### ISSUE TITLE
Outdated/invalid file links in content/README.md

### ISSUE THREAD

**Issue by muzimuzhi** [github/docs#35015]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Sorry the reported file doesn't contribute to the docs.github.com content.

https://github.com/github/docs/blob/main/content/README.md

### What part(s) of the article would you like to see updated?

Some internal file links are outdated or invalid.

- Outdated links due to structure adjustments, for example
  https://github.com/github/docs/blob/d6ce5e50071781bceadc51c2605dc0cc6debf6b7/content/README.md?plain=1#L53
  The linked `frontmatter.js` was renamed by d4f345e4afbde4160d07c1511f584b59c998c094, `{lib => src/frame/lib}/frontmatter.js`.
- Invalid link target
  https://github.com/github/docs/blob/d6ce5e50071781bceadc51c2605dc0cc6debf6b7/content/README.md?plain=1#L57
  It was wrongly modified by https://github.com/github/docs/commit/3f94bb2dcf0fb4291d9bf39233609c9d32e70bda
  ```diff
  -- Purpose: Indicates the [versions](../lib/all-versions.js) to which a page applies.
  +- Purpose: Indicates the [versions](#src/versions/lib/all-versions.js) to which a page applies.
  ```

**Comment by nguyenalex836** [comment]
@muzimuzhi Thank you for opening an issue and linking it to your PR! ✨
