### ISSUE TITLE
permission needed for creating commit comment is wrong

### ISSUE THREAD

**Issue by kj-9** [github/docs#35024]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/commits/comments?apiVersion=2022-11-28#create-a-commit-comment

specifically,
https://arc.net/l/quote/xyiivuna

### What part(s) of the article would you like to see updated?

currently:

```
The fine-grained token must have the following permission set:
- "Contents" repository permissions (read)
```

but I think correctly:

```
The fine-grained token must have the following permission set:
- "Contents" repository permissions (**write**)
```

it requires write permmison.

### Additional information

because in my repo, i need `content: write` to create commit comment.

- [that commit](https://github.com/kj-9/click-app-copier/commit/e38f67275a5a267748c1c5c3cf2c22b9b988f710)
- [gha run](https://github.com/kj-9/click-app-copier/actions/runs/11427114807/job/31790865142#step:8:21)

before that, create commit comment failed in gha, with `content: read` (although it exits 0)
- [gha run failed](https://github.com/kj-9/click-app-copier/actions/runs/11427020598/job/31790679662#step:8:22)

**Comment by nguyenalex836** [comment]
@kj-9 Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by felicitymay** [comment]
Many thanks for including such clear details of the bug you found in the docs 💖 

Since the REST API docs are automatically generated from the OpenAPI schema, which is maintained internally, we'll have to fix this with an internal pull request.
