### ISSUE TITLE
Deprecated `gh-actions-cache` is referenced in docs

### ISSUE THREAD

**Issue by bayandin** [github/docs#35030]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

### What changes are you suggesting?

`actions/gh-actions-cache` has been deprecated in favour of `gh cache`

Ref https://github.com/actions/gh-actions-cache/pull/86

So we need to replace `actions/gh-actions-cache` usage in docs with `gh cache` analogue

**Comment by nguyenalex836** [comment]
@bayandin Thank you for opening an issue and linking it to your PR! ✨
