### ISSUE TITLE
When issues are created, two identical issues appear in the list

### ISSUE THREAD

**Issue by yaolifeng0629** [github/docs#35054]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

GitHub platform, create issues page issues

### What part(s) of the article would you like to see updated?

1. Click the "Create Issues" button
2. Enter the title and specific content
3. Add two tags
4. Determine
5. Return to the issues list page, where there are identical issues

### Additional information

![c893bfd337aa610a6bb89da8a793a6d](https://github.com/user-attachments/assets/238a0b4f-7d15-4ab1-b223-fbd180b027f8)

**Comment by yaolifeng0629** [comment]
The approximate time is between 10:50 and 11.20. I can confirm that I only clicked the button once and did not make any violent clicks

**Comment by nguyenalex836** [comment]
Hi @yaolifeng0629 👋 ! I'm sorry you're having problems with creating issues! 

This question would best be handled by our wonderful [support team](https://support.github.com/request). Please reach out to them for assistance ✨ 

If there's anything in the documents that you have suggestions for updating, please feel free to open an issue 💛
