### ISSUE TITLE
Instruction is out-dated

### ISSUE THREAD

**Issue by jmz3** [github/docs#35073]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/159ac36116fdeb3eaef6c8572861fc8908ae0b1f/content/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-education-for-students/apply-to-github-education-as-a-student.md?plain=1#L48

### What part(s) of the article would you like to see updated?

The Expiration and Renewals section

### Additional information

This instruction is out-dated. There is no longer "Reverify your academic affiliation" in the drop down menu.

**Comment by nguyenalex836** [comment]
@jmz3 Thank you so much for your patience while our SME team reviewed your issue! We just received the following guidance from our GitHub Education SMEs:

> the wording in the dropdown menu has changed from `reverify your academic affiliation` to `your benefits application` and appears for everyone, not just users close to expiration or needing renewal. However, the functionality is exactly the same as before, it takes them straight to the application to reverify their academic status.

I've added the `help wanted` label so that you, or anyone else, may submit a PR for this update 💛 Thank you again for raising a flag on this!
