### ISSUE TITLE
Remove periods from list in using-the-github-codespaces-plugin-for-jetbrains#using-the-github-codespaces-tool-window

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#35109]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

in https://docs.github.com/en/codespaces/reference/using-the-github-codespaces-plugin-for-jetbrains#using-the-github-codespaces-tool-window

This issue is intended for newcomers to the OS Docs repo! 💛

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ✨

### What part(s) of the article would you like to see updated?

> The GitHub Codespaces tool window shows:
> 
> - The repository from which you created this codespace.
> - The display name of the codespace.
> - The current branch.
> - The machine specifications.
> - The time for which this codespace can remain idle before it is automatically stopped.
> - The age of the codespace.
> - The period for which a stopped codespace will be retained before it is automatically deleted.

Periods should be removed from this list, as each line is not a complete sentence

### Additional information

Style guide [reference](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists)

**Comment by 5AIPAVAN** [comment]
can i work on this @nguyenalex836 :-)

**Comment by nguyenalex836** [comment]
@5AIPAVAN Hello! Someone else has already submitted a PR for this which is slated to be merged after our repo freeze 💛 

Feel free to check out other issues labeled [`good first issue`](https://github.com/github/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or [`help wanted`](https://github.com/github/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) to find issues you can work on! ✨
