### ISSUE TITLE
Command for gpg signing all tags by default 

### ISSUE THREAD

**Issue by sih4sing5hong5** [github/docs#35185]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Telling Git about your signing key

### What part(s) of the article would you like to see updated?

6. Optionally, to configure Git to sign all commits by default, enter the following command:

### Additional information

For convenience, like #21497 . I will send the PR.

**Comment by nguyenalex836** [comment]
@sih4sing5hong5 Thank you for opening an issue and linking it to your PR! ✨
