### ISSUE TITLE
Inconsistent labeling of Note/Warning blocks

### ISSUE THREAD

**Issue by akordowski** [github/docs#35195]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Reading the GitHub Actions documentation I have noticed that the labeling of `Note/Warning` blocks is inconsistent through the documentation. Is that intentional or can be this seen as a `bug`?

```
>[!NOTE]
```
![note_1](https://github.com/user-attachments/assets/3697360e-3ca3-4720-8dbb-5241edd19b8d)

```
**Note:** or **Notes:**
```
![note_2](https://github.com/user-attachments/assets/fa4d382e-ab61-45be-b515-7e2ab10c49c3)

![note_3](https://github.com/user-attachments/assets/b9a722ea-ab5c-4072-adbe-4e836c1c20a8)

```
>[!WARNING]
```
![warning_1](https://github.com/user-attachments/assets/ddf261d2-cc0c-4846-9197-c6ba7cc16cbe)

```
**Warning:**
```
![warning_2](https://github.com/user-attachments/assets/852b347f-fe26-42ee-b5f8-ffd962c7f6b4)

### What part(s) of the article would you like to see updated?

My first search in the repository indicates that it affects other docs as well. It would be nice if the docs would have a consistent way to display the blocks (preferably the `>[!NOTE] / >[!WARNING]` notation), and not have different kinds even in same article.

### Additional information

If whished I could provide a PR to fix this issue.

**Comment by nguyenalex836** [comment]
@akordowski Thank you for catching this inconsistency! ✨ Notes and warnings should be consistent with the formatting laid out by our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#alert-types) 💛 

Please feel free to open a PR to update this whenever you have a chance - thank you!

**Comment by Piyush-r-bhaskar** [comment]
Hi @akordowski 

I would like to work to fix this inconsistency. Would it be fine for you if I take this one if you are not already about to open a PR.

Thanks

**Comment by akordowski** [comment]
@Piyush-r-bhaskar I already started with the work, so maybe next time.

**Comment by akordowski** [comment]
PR is available #35216. This was lot of work :relieved:

**Comment by akordowski** [comment]
@nguyenalex836 I have further questions for clarification.

1. There were several cases where the docs contained alerts as the following example:

	```md
	{% tip %}
	**Note:** description
	{% endtip %}
	
	// or
	
	{% warning %}
	**Note:** description
	{% endwarning %}

    // or other combinations
    ```

    For this cases I always prefered the prefix (`**Note:**`) for the Markdown notation (`> [!NOTE]`) over the liquid (`{% tip %}`) notation. Is that correct?

2. And there are cases where the docs contain alerts without any prefix in the description:

	```md
	{% note %}
	Descriiption
	{% endnote %}
    ```
	These cases I didn't changed and kept them as the are. Is that correct or should I change them to the corresponding Markdown notation (`> [!NOTE]`) as well?

Looking forward for your feedback. Thank you!

**Comment by nguyenalex836** [comment]
@akordowski 👋 

> For this cases I always prefered the prefix (**Note:**) for the Markdown notation (> [!NOTE]) over the liquid ({% tip %}) notation. Is that correct?

Great catch - yes, this is correct! ✨ A snippet from our style guide confirms this -
> Liquid syntax for alerts is still supported and may still appear in older articles, but should not be used for new alerts.

-----------------------

> And there are cases where the docs contain alerts without any prefix in the description

Go ahead and leave leave those as they are - good call 💛

**Comment by akordowski** [comment]
@nguyenalex836 As discussed I splited the original PR #35216 into 4 new ones:

- #35220
- #35221
- #35222
- #35223

I will close the original PR.

**Comment by nguyenalex836** [comment]
Given the [final PR](https://github.com/github/docs/pull/35223) in this series has been merged, I'll go ahead and close this issue ✨  

An incredible undertaking by @akordowski - thank you so much for lending your time and expertise to our community 💛

**Comment by akordowski** [comment]
@nguyenalex836 It was my pleasure! Thank you also for your time to review all the changes.
