### ISSUE TITLE
Sub-Issue button does not exist but the documentation points to it

### ISSUE THREAD

**Issue by tjgurwara99** [github/docs#35204]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues

### What changes are you suggesting?

The documentation suggests that there is a publicly available feature which is able to create sub issues that could be tracked by the project board. However, I do not see this in any of the issues I have triage access to. Could this have been published before this was published before it was rolled out to people?

**Comment by nguyenalex836** [comment]
Hi @tjgurwara99 👋 ! Thanks for opening an issue!

It looks like sub-issues are currently in an opt-in public preview for organizations, as noted in the doc 💛 

> Issue types, sub-issues, and advanced issue search are currently in an opt-in public preview for organizations. To learn more and add your organization to the waitlist, see the "[GitHub Blog](https://github.blog/changelog/2024-10-01-evolving-github-issues-public-preview)."

While previewing, I can see sub-issues are present -

<img width="950" alt="image" src="https://github.com/user-attachments/assets/a664555f-4b94-4a5e-992f-86476b53a1db">

I hope this clarifies things! I'll go ahead and close this issue, but feel free to ping here if you have any other questions ✨
