### ISSUE TITLE
Inconsistent layout type for GitHub Actions pages

### ISSUE THREAD

**Issue by akordowski** [github/docs#35217]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Reading the GitHub Actions documentation I have noticed that only 4 pages have an `layout: inline` type, where other pages don't have any `layout` type. Is that intentional or can be this seen as a bug?

The pages are:

* [About workflows](https://docs.github.com/en/actions/writing-workflows/about-workflows)
* [About Actions Runner Controller](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller)
* [Publishing Docker images](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images)
* [Creating an example workflow](https://docs.github.com/en/actions/use-cases-and-examples/creating-an-example-workflow)

### What part(s) of the article would you like to see updated?

Remove the `layout: inline` type to have a consistent layout type for GitHub Actions pages.

**Comment by akordowski** [comment]
I made a search in the `/content/**/*.md` files and there a 18 file in total that have the `layout: inline`. It affacts also other pages as well.

**Comment by nguyenalex836** [comment]
@akordowski Thank you for raising this issue! ✨ We checked in with the original authors of this doc, and they stated `layout: inline` was deliberate to avoid a table rendering poorly 💛

Thank you very much for discussing with us before raising the PR! We appreciate your contributions to our community 🙇

**Comment by akordowski** [comment]
Ok, I see. This page contains indeed a large table. but what about the other pages? As I have seen some of them could be aligned with the default layout.
