### ISSUE TITLE
Fix a jq option to get a TODO_OPTION_ID

### ISSUE THREAD

**Issue by ywonchae1** [github/docs#35227]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- [‎content/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions.md](https://github.com/ywonchae1/docs/commit/8a28307a9b3c8e484546d625a8a654abf037eb93#diff-1b0d88c51c189ce2a1c622cc1cf02333f6d6b5c808b01455208b62893a81abbb)
- 2 workflow YAML files

### What part(s) of the article would you like to see updated?

The description of these YAML files said that `This workflow assumes that you have a project with a single select field called "Status" that includes an option called "Todo"`.
But the jq code in the YAML file means `Find a single select field called "Todo" that includes an option called "Todo"`.
So I failed to find "Todo" option when I test the same code, so please review my suggestion's correctness.

**Comment by nguyenalex836** [comment]
@ywonchae1 Thank you for opening an issue and linking it to your PR! ✨
