### ISSUE TITLE
Add a star/pin option for files uploaded in the code section

### ISSUE THREAD

**Issue by Ayush-D2004** [github/docs#35248]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Managing files in a repository : This article covers how GitHub organizes files and how repositories are structured. GitHub arranges the files list in alphabetical order but there are certain files that are more important and need to be shown at top irrespective of their name like "main.file" the issue can be seen in my repository in the provided link : `https://github.com/Ayush-D2004/Cargo-Shipment-Management-System`

This can be resolved by adding a feature to star/pin a file at the top

### What part(s) of the article would you like to see updated?

I understand that GitHub lists repository files in alphabetical order by default, but I would like to see a feature where users can pin files at the top of the file list without having to rename or restructure files.

Currently, the only workaround is renaming files with prefixes like ( A_ or 01 ), which can lead to inconsistent naming conventions and is not ideal in some cases.

It would be helpful to have an option to pin or "star" specific files or make them appear at the top of the file list, even if they're not alphabetically first. This would be especially useful for files like "main.c", which are central to the functionality of the project.

### Additional information

I think every developer might have faced this issue already but are fine with the way-around of renaming file or restructuring the repository. The update can be added easily that can help save a lot of efforts.
![Screenshot (78)](https://github.com/user-attachments/assets/8c9d639b-8f9f-4d15-93f8-1662eb0599b2)

**Comment by nguyenalex836** [comment]
@Ayush-D2004 👋 The best place to send your feedback regarding this feature request is to https://github.com/github/feedback/discussions ✨

If there's anything specifically in the docs that you have suggestions for updating, please feel free to open an issue in this repo 💛
