### ISSUE TITLE
Repository visibility docs for GHES are misleading with references to GitHub.com

### ISSUE THREAD

**Issue by sparrowt** [github/docs#35262]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.12/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility

### What part(s) of the article would you like to see updated?

Both of these sections [Changing from private to public](https://docs.github.com/en/enterprise-server@3.12/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility#changing-from-private-to-public) and [Changing from internal to public](https://docs.github.com/en/enterprise-server@3.12/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility#changing-from-internal-to-public) say:
> The code will be visible to everyone who can visit GitHub.com.

which is not true or relevant for GitHub Enterprise Server which is self-hosted and not linked to github.com

**Comment by sparrowt** [comment]
Ah I've found in the [source](https://github.com/github/docs/blob/main/content/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility.md?plain=1#L88) it uses `{% data variables.product.prodname_dotcom_the_website %}` but seemingly on GHES docs that is still github.com so that may need changing or replacing based on some `{% ifversion ghes or ghec %}` or `{% ifversion ghes %}` at a guess?

**Comment by Tadmanakub3** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).

**Comment by nguyenalex836** [comment]
@sparrowt Thank you for raising this issue (and for the context regarding that source)! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
@sparrowt Howdy! 👋 Our SMEs confirmed we should replace `{% data variables.product.prodname_dotcom_the_website %}` with `{% data variables.location.product_location %}` 💛 

Let us know if you'd like to open a PR to make this update!

**Comment by Jojo-1972** [comment]
[rel="next](url)

**Comment by nguyenalex836** [comment]
@janbrasna I'll go ahead and merge the PR you linked above 💛

**Comment by sparrowt** [comment]
Thanks folks!
