### ISSUE TITLE
Incorrect example repo in note about repo organisations needing to match

### ISSUE THREAD

**Issue by chrismear** [github/docs#35274]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/prebuilding-your-codespaces/allowing-a-prebuild-to-access-other-repositories

### What part(s) of the article would you like to see updated?

In the note about how the "owner of the target repository must be the same as the owner of the repository for which you're creating a prebuild", the two example repos given have _different_ organisations: `octo-org/octocatrepository` and `asocto-org/octodemo`.

**Comment by nguyenalex836** [comment]
@chrismear Thank you for opening an issue and linking it to your PR! ✨
