### ISSUE TITLE
More info on per-user pricing please - Mix and match licenses possible?

### ISSUE THREAD

**Issue by haneef95** [github/docs#3527]
### What article on docs.github.com is affected?
https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-per-user-pricing

### What part(s) of the article would you like to see updated?
Would like to know if licenses can be mixed and matched, e.g.: some users on free, some on team and some on Enterprise licenses.

Thanks

**Comment by janiceilene** [comment]
👋 @haneef95 I'm not sure what the answer is to that question! I think that would be a question our awesome [support team](https://support.github.com/contact) ✨

**Comment by JoeGT2000** [comment]
Did you get an answer on this through support?

**Comment by grcspace311** [comment]
CAn someone help me with my account 😫  the radio frequency and 🛰  positioning is starting to get me confused again. I want to know what's my next step. I'm all over the place.   Thanks

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by grcspace311** [comment]
Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

**Comment by grcspace311** [comment]
Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>''Iam George Clapps my info isin need of updating I in usa
