### ISSUE TITLE
Update recommendations for adjusting resources on GHES when Actions or Codespaces is enabled.

### ISSUE THREAD

**Issue by Faisal78123** [github/docs#35281]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Hello.

The document that would be affected would be this one : 

https://docs.github.com/en/enterprise-server@3.15/admin/installing-your-enterprise-server/setting-up-a-github-enterprise-server-instance/installing-github-enterprise-server-on-google-cloud-platform

And all it's variants for other platforms (VMWare, Azure, AWS, etc...)

### What part(s) of the article would you like to see updated?

The part that I would like to see updated is the part where we say : 

>If you plan to enable GitHub Actions or GitHub Advanced Security for the users of your instance, more resources are required.
>**GitHub Actions - increase CPU and memory by 25%**
>**GitHub Advanced Security - increase CPU and memory by 15%**

I believe the documentation should be changed here because it implies that a customer who will simply add more resources will be fine in all cases.
I believe that the customers here should first make the change in terms of resources (CPU and Memory), but once this is done, they should monitor the appliance for resource utilisation, and make appropriate changes as required.
This is also documented in another article where we ask customers to first monitor their appliance in order to establish a baseline in terms of resource utilisation, and make the necessary adjustments after.
That document implies that the baseline should be around 60% of all available resources (this assumption is made based on the recommended threshold for alerts).
The document in question is this one : https://docs.github.com/en/enterprise-server@3.15/admin/monitoring-and-managing-your-instance/monitoring-your-instance/recommended-alert-thresholds#monitoring-cpu-and-load-average-usage

This is the reason why I would like to see this changed.
The change I would like to see would be something along the lines of : 

>**GitHub Actions - increase CPU and memory by 25% and monitor as further adjustments may be required** (with a link to https://docs.github.com/en/enterprise-server@3.15/admin/monitoring-and-managing-your-instance/monitoring-your-instance/recommended-alert-thresholds#monitoring-cpu-and-load-average-usage)
>**GitHub Advanced Security - increase CPU and memory by 15% and monitor as further adjustments may be required** (with a link to https://docs.github.com/en/enterprise-server@3.15/admin/monitoring-and-managing-your-instance/monitoring-your-instance/recommended-alert-thresholds#monitoring-cpu-and-load-average-usage)

I do expect that the outcome will be that we will have less customer running GHES on resource-constrained environment, leading to a better user/customer experience, better satisfaction, and overall less support ticket for this type of issues.

**Comment by Faisal78123** [comment]
I have created this pull request for this topic :  https://github.com/github/docs-internal/pull/53100

**Comment by nguyenalex836** [comment]
@Faisal78123 Thank you for opening an issue and linking it to your PR! ✨

**Comment by nguyenalex836** [comment]
Closing as https://github.com/github/docs-internal/pull/53100 has been merged 💛
