### ISSUE TITLE
Move periods inside quotation marks in why-are-my-commits-linked-to-the-wrong-user#commits-are-linked-to-another-user

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#35299]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-linked-to-another-user

This issue is intended for newcomers to the OS Docs repo! 💛

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ✨

### What part(s) of the article would you like to see updated?

> To change the email address in your local Git configuration, follow the steps in "[Setting your commit email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git)".

> Add the email address from step 2 to your account settings by following the steps in "[Adding an email address to your GitHub account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account)".

Move periods inside quotation marks to maintain consistency with other docs (and [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide))

**Comment by Dusch4593** [comment]
Hi @nguyenalex836! I created a PR for this issue in https://github.com/github/docs/pull/35366. This is my first contribution to GitHub Docs, super happy to help! 😄
