### ISSUE TITLE
typo in https://docs.github.com/en/rest/reference/billing#get-github-packages-billing-for-an-organization

### ISSUE THREAD

**Issue by cpanato** [github/docs#3532]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/billing#get-github-packages-billing-for-an-organization

### What part(s) of the article would you like to see updated?

typo in
`Gets the free and paid storage usued for GitHub Packages in gigabytes.`

should be
`Gets the free and paid storage used for GitHub Packages in gigabytes.`

**Comment by janiceilene** [comment]
👋 Thanks for opening an issue @cpanato! This content is autogenerated and the change will need to be made in an internal repo. I've opened an issue internally for a fix, so I'm going to close this out! Thanks so much for letting us know!
