### ISSUE TITLE
Wrong settings section description in **Code security** docs

### ISSUE THREAD

**Issue by akordowski** [github/docs#35324]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- Code security / Getting started / Dependabot quickstart / [Enabling Dependabot for your repository](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide#enabling-dependabot-for-your-repository)
- Code security / Getting started / Secure repository quickstart / [Managing the dependency graph](https://docs.github.com/en/code-security/getting-started/quickstart-for-securing-your-repository#managing-the-dependency-graph)

#### Article **Enabling Dependabot for your repository**

The article describes the `Settings / Security / Code security and analysis` section:

![grafik](https://github.com/user-attachments/assets/18f41665-8444-42bc-bc08-76196c219247)

#### Article **Managing the dependency graph**

The article describes the `Security & analysis` section:

![grafik](https://github.com/user-attachments/assets/d8ea8111-b4cf-46d2-ae3e-cbebae8802fe)

But in GitHub Settings the section is just named `Code security`:

![grafik](https://github.com/user-attachments/assets/393cfae3-f2b2-4a69-8247-9ce25fd02b7a)

**EDIT**:
There a actually muliple occurrences of the described issues in the docs.

### Additional information

I could provide a PR to fix this issues.

**Comment by nguyenalex836** [comment]
@akordowski Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by akordowski** [comment]
@subatoi As this issue will be done by the team I close this issue.

**Comment by subatoi** [comment]
Thank you!

**Comment by subatoi** [comment]
@akordowski For the issues concerning this naming error, I just wanted to let you know that I'll be shipping fixes shortly

I tried to add you as co-committer but it didn't work—apologies about that (I'll investigate why but I think it may have been a transient availability issue). Please rest assured we really appreciate your contributions!

**Comment by akordowski** [comment]
> I tried to add you as co-committer but it didn't work

@subatoi No worries, I provided so many PRs so its fine with me :laughing:
Thank you for letting me know.
