### ISSUE TITLE
Improve OIDC provider JWT retrieval documentation

### ISSUE THREAD

**Issue by NeoCat** [github/docs#35340]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Requesting the JWT using environment variables](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#requesting-the-jwt-using-environment-variables)

### What part(s) of the article would you like to see updated?

The current documentation for manually requesting a JSON Web Token (JWT) from the GitHub OIDC provider has several issues:
1. The name of environment variable in the script is not valid ( `ACTIONS_RUNTIME_TOKEN` must be `ACTIONS_ID_TOKEN_REQUEST_TOKEN ` )
2. The whole node script step is redundant.
3. `jq` availability is checked after it is actually used.
4. Printing tokens / signature to logs has potential security risks and is not useful.

**Comment by nguyenalex836** [comment]
@NeoCat Thank you for opening an issue and linking it to your PR! ✨
