### ISSUE TITLE
Inconsistent bullet list style

### ISSUE THREAD

**Issue by akordowski** [github/docs#35344]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Multiple articles

### What part(s) of the article would you like to see updated?

I noticed that some lists have inconsistent style, even in the same article. One list uses the `**Keyword**: Text` format, other the `**Keyword**—Text`.

See here:
- [How secret scanning works](https://docs.github.com/en/code-security/secret-scanning/introduction/about-secret-scanning#how-secret-scanning-works) vs. [About the benefits of secret scanning](https://docs.github.com/en/code-security/secret-scanning/introduction/about-secret-scanning#about-the-benefits-of-secret-scanning)
- [About secret scanning patterns](https://docs.github.com/en/code-security/secret-scanning/introduction/supported-secret-scanning-patterns#about-secret-scanning-patterns) vs. [Supported secrets](https://docs.github.com/en/code-security/secret-scanning/introduction/supported-secret-scanning-patterns#supported-secrets)

There are other few occurrences of the `**Keyword**—Text` style in other articles as well.

As the lists rather using the `**Keyword**: Text` style this should be unified.

### Additional information

I could provide a PR for this issue.

**Comment by nguyenalex836** [comment]
@akordowski Thank you for catching this inconsistency! I _believe_ we would want to unify our docs to use the `**Keyword**: Text` style given it is more prominent, but I will put this up for review to get a second opinion from the team 💛

**Comment by subatoi** [comment]
Thank you @akordowski! I agree with @nguyenalex836 so I will let him open it to you to contribute accordingly.

**Comment by akordowski** [comment]
@nguyenalex836 It's my pleasure! 😊 Let my know when you got feedback from the team.

**Comment by nguyenalex836** [comment]
@akordowski Oh, @subatoi's comment above was actually the feedback we were looking for! 💛 

We should go ahead and unify our docs to use the `**Keyword**: Text` style - feel free top open PRs for this whenever you have time ✨
