### ISSUE TITLE
Unnecessary spaces between words

### ISSUE THREAD

**Issue by akordowski** [github/docs#35379]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Multiple articles.

### What part(s) of the article would you like to see updated?

There are multiple occurrences where between words are unnecessary spaces. Although they are barely visible, they are still rendered.

**Comment by akordowski** [comment]
Hi @nguyenalex836!

According to the PRs I can not edit following files, but they contain unnecessary spaces between words. Maybe the team could fix it :wink:

- `content/code-security/code-scanning/managing-code-scanning-alerts/responsible-use-autofix-code-scanning.md`
- `content/support/learning-about-github-support/about-copilot-in-github-support.md`
- `data/reusables/rai/copilot-dotcom-feedback-collection.md`
- `data/reusables/rai/copilot/about-copilot-chat-in-mobile.md`

This is the RegEx I used for finding the occurrences. I hope it help.

```
[^\s]([ ]{2,})[^\s]
```

**Comment by nguyenalex836** [comment]
@akordowski Thank you so much for including your regex! ✨ I'll file an issue internally for these as well 💛 

Currently reviewing your linked PRs - stay tuned!

**Comment by nguyenalex836** [comment]
@akordowski Thank you so much for combing through all of those files and removing those unnecessary spaces! ✨ 

We now have an internal issue to update those protected files 💛 thanks again!
