### ISSUE TITLE
Empty `if` statement in article

### ISSUE THREAD

**Issue by akordowski** [github/docs#35384]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Sharing actions and workflows with your organization](https://docs.github.com/en/actions/sharing-automations/sharing-actions-and-workflows-with-your-organization#about-github-actions-access-to-private-repositories)

### What part(s) of the article would you like to see updated?

The line 17 displayed below contains a empty `if` statement:

`access a private {% ifversion internal-actions %}  {% endif %}repository`

https://github.com/github/docs/blob/92260b1541114e2294b2a927a6bb9eed53cb27fd/content/actions/sharing-automations/sharing-actions-and-workflows-with-your-organization.md?plain=1#L16-L18

I think it could be removed.

### Additional information

I could provide a PR to fix it.

**Comment by chan731126** [comment]
> ### 行为守则
> * [x] 我已阅读并同意 GitHub Docs 项目的[行为准则](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### docs.github.com 上的哪篇文章受到了影响？
> [与您的组织共享操作和工作流程](https://docs.github.com/en/actions/sharing-automations/sharing-actions-and-workflows-with-your-organization#about-github-actions-access-to-private-repositories)
> 
> ### 您希望更新文章的哪一部分？
> 下面显示的第 17 行包含一个空`if`语句：
> 
> `access a private {% ifversion internal-actions %} {% endif %}repository`
> 
> https://github.com/github/docs/blob/92260b1541114e2294b2a927a6bb9eed53cb27fd/content/actions/sharing-automations/sharing-actions-and-workflows-with-your-organization.md?plain=1#L16-L18
> 
> 我认为它可以被删除。
> 
> ### 附加信息
> 我可以提供 PR 来修复它。

**Comment by nguyenalex836** [comment]
@akordowski I agree with you! Feel free to submit that PR whenever you have time 💛

**Comment by kai952700** [comment]
別來煩我了！

從 Gmail 行動版傳送


Alex Nguyen ***@***.***>於 2024年11月26日 週二，01:25寫道：
