### ISSUE TITLE
support banner without container

### ISSUE THREAD

**Issue by Arhell** [github/docs#354]
### What is the current behavior?
give this block a container
On large monitors, this block remains on the left edge, which will come to life just like the template

### What changes are you suggesting?
![1](https://user-images.githubusercontent.com/26163841/95609455-622da580-0a67-11eb-845b-8b1014934299.jpg)

### Additional information
I will do it soon

**Comment by janiceilene** [comment]
Thanks for opening an issue @Arhell! I'll let the engineering team respond ✨

**Comment by Arhell** [comment]
done https://github.com/github/docs/pull/388

**Comment by simpsoka** [comment]
Thanks, @Arhell! From a product perspective, I think this cleans things up nicely to align with the rest of the content on the page. cc @heiskr for review on #388 (the review app is 👍 from my side)
