### ISSUE TITLE
GitHub Deceased User Successor policy and target settings

### ISSUE THREAD

**Issue by ShaneCurcuru** [github/docs#35407]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/maintaining-ownership-continuity-of-your-personal-accounts-repositories

### What part(s) of the article would you like to see updated?

How can a user submit either a GH **Organization** as a successor, or submit **more than one** GH User account as a successor?

When making succession planning, it's often helpful to be able to choose multiple successors - for example a traditional will/trust will have successor executors in case the first one is unable to serve.  Ensuring that an ordered list of GH Successor users could be added to a single account would better mirror traditional estate planning norms.

Similarly, many open source projects start with one person, but grow to have a major impact on software organizations.  Being able to list an Organization object, where any Admin from that Organization could then apply to become the successor (either as the Organization or as an individual) would be immensely valuable for many FOSS Foundations and the like. 

Apologies if this is a policy question that should best be answered elsewhere; please feel free to redirect me to the right place!

**Comment by nguyenalex836** [comment]
@ShaneCurcuru Hello! 👋 That is a great question!

While our team is unfamiliar with the details of that process, our wonderful [support team](https://support.github.com/request) is best equipped to assist ✨ They'll be happy to help!

If there's anything else in the documents that you have suggestions for updating, please feel free to open an issue 💛

**Comment by campos13924** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/maintaining-ownership-continuity-of-your-personal-accounts-repositories
> 
> ### What part(s) of the article would you like to see updated?
> How can a user submit either a GH **Organization** as a successor, or submit **more than one** GH User account as a successor?
> 
> When making succession planning, it's often helpful to be able to choose multiple successors - for example a traditional will/trust will have successor executors in case the first one is unable to serve. Ensuring that an ordered list of GH Successor users could be added to a single account would better mirror traditional estate planning norms.
> 
> Similarly, many open source projects start with one person, but grow to have a major impact on software organizations. Being able to list an Organization object, where any Admin from that Organization could then apply to become the successor (either as the Organization or as an individual) would be immensely valuable for many  Foundations and the like.
> 
> Apologies if this is a policy question that should best be answered elsewhere; please feel free to redirect me to the right place!
> 
> ### Additional information
> _No response_

content/site-policy/index.md
