### ISSUE TITLE
UI Doesn't look good

### ISSUE THREAD

**Issue by shailjaatkotiya** [github/docs#35431]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

![image](https://github.com/user-attachments/assets/347c1645-6c4e-4d75-8d4b-d5abcb9d01dc)

### What part(s) of the article would you like to see updated?

Above given image, text should be white for better readability. 
Or did your UI-UX quit ?

**Comment by nguyenalex836** [comment]
@shailjaatkotiya Hello! 👋  The best place to send your feedback regarding the UI is to https://github.com/github/feedback/discussions ✨

If there's anything specifically in the docs that you have suggestions for updating, please feel free to open an issue in this repo 💛
