### ISSUE TITLE
Alerts without header

### ISSUE THREAD

**Issue by akordowski** [github/docs#35445]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Multiple articles.

### What part(s) of the article would you like to see updated?

There are still alerts in the documentation which are using the following notation:

```
{% note %}
Text
{% endnote %}

// same for tip and warning
```

These alerts don#t have any header (Note, Tip, Warning) and are rendered just with the colored strip.

Examples:
- [Note](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-environments-to-manually-trigger-workflow-jobs)
- [Tip](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authenticating-to-the-rest-api-with-an-oauth-app)
- [Warning](https://docs.github.com/en/apps/github-marketplace/using-the-github-marketplace-api-in-your-app/handling-new-purchases-and-free-trials)

### Additional information

Maybe some are ment to be that way. If not I could provide a PR with fixes.

**Comment by akordowski** [comment]
A list of affected files:

## Note

- content\actions\hosting-your-own-runners\managing-self-hosted-runners-with-actions-runner-controller\deploying-runner-scale-sets-with-actions-runner-controller.md
- content\actions\writing-workflows\choosing-when-your-workflow-runs\triggering-a-workflow.md
- content\admin\managing-iam\iam-configuration-reference\saml-configuration-reference.md
- content\apps\creating-github-apps\authenticating-with-a-github-app\authenticating-as-a-github-app-installation.md
- content\authentication\managing-commit-signature-verification\telling-git-about-your-signing-key.md
- content\billing\managing-billing-for-your-products\managing-billing-for-github-packages\about-billing-for-github-packages.md
- content\code-security\adopting-github-advanced-security-at-scale\introduction-to-adopting-github-advanced-security-at-scale.md
- content\code-security\adopting-github-advanced-security-at-scale\phase-1-align-on-your-rollout-strategy-and-goals.md
- content\code-security\adopting-github-advanced-security-at-scale\phase-2-preparing-to-enable-at-scale.md
- content\code-security\adopting-github-advanced-security-at-scale\phase-3-pilot-programs.md
- content\code-security\adopting-github-advanced-security-at-scale\phase-4-create-internal-documentation.md
- content\code-security\adopting-github-advanced-security-at-scale\phase-5-rollout-and-scale-code-scanning.md
- content\code-security\adopting-github-advanced-security-at-scale\phase-6-rollout-and-scale-secret-scanning.md
- content\code-security\code-scanning\introduction-to-code-scanning\about-code-scanning-with-codeql.md
- content\code-security\code-scanning\managing-code-scanning-alerts\tracking-code-scanning-alerts-in-issues-using-task-lists.md
- content\code-security\codeql-cli\getting-started-with-the-codeql-cli\analyzing-your-code-with-codeql-queries.md
- content\code-security\security-advisories\working-with-repository-security-advisories\adding-a-collaborator-to-a-repository-security-advisory.md
- content\code-security\security-overview\filtering-alerts-in-security-overview.md
- content\codespaces\getting-started\understanding-the-codespace-lifecycle.md
- content\codespaces\setting-up-your-project-for-codespaces\configuring-dev-containers\adding-features-to-a-devcontainer-file.md
- content\communities\maintaining-your-safety-on-github\blocking-a-user-from-your-personal-account.md
- content\communities\using-templates-to-encourage-useful-issues-and-pull-requests\syntax-for-issue-forms.md
- content\get-started\writing-on-github\editing-and-sharing-content-with-gists\creating-gists.md
- content\graphql\guides\forming-calls-with-graphql.md
- content\graphql\guides\using-the-explorer.md
- content\issues\organizing-your-work-with-project-boards\managing-project-boards\changing-project-board-visibility.md
- content\issues\planning-and-tracking-with-projects\managing-your-project\managing-access-to-your-projects.md
- content\pages\getting-started-with-github-pages\changing-the-visibility-of-your-github-pages-site.md
- content\repositories\managing-your-repositorys-settings-and-features\customizing-your-repository\displaying-a-sponsor-button-in-your-repository.md
- content\repositories\managing-your-repositorys-settings-and-features\enabling-features-for-your-repository\managing-security-and-analysis-settings-for-your-repository.md
- content\sponsors\sponsoring-open-source-contributors\sponsoring-an-open-source-contributor-through-github.md
- contributing\translations-for-translators.md

#### Reusables

- data\reusables\cli\cli-learn-more.md
- data\reusables\codeql-cli\download-codeql-cli.md
- data\reusables\codeql-cli\man-pages-version-note.md
- data\reusables\enterprise\rate_limit.md
- data\reusables\organizations\team-discussions-api-deprecation.md
- data\reusables\package_registry\packages-classic-pat-only.md
- data\reusables\pages\visit-site.md
- data\reusables\user-settings\classic-projects-api-classic-pat-only.md
- data\reusables\user-settings\enterprise-admin-api-classic-pat-only.md
- data\reusables\user-settings\imports-api-classic-pat-only.md
- data\reusables\user-settings\notifications-api-classic-pat-only.md

## Tip

- content\apps\oauth-apps\building-oauth-apps\authenticating-to-the-rest-api-with-an-oauth-app.md
- content\authentication\connecting-to-github-with-ssh\using-ssh-agent-forwarding.md
- content\authentication\keeping-your-account-and-data-secure\about-anonymized-urls.md
- content\authentication\keeping-your-account-and-data-secure\updating-your-github-access-credentials.md
- content\authentication\troubleshooting-ssh\using-ssh-over-the-https-port.md
- content\get-started\accessibility\github-command-palette.md
- content\get-started\working-with-subversion-on-github\what-are-the-differences-between-subversion-and-git.md
- content\graphql\guides\forming-calls-with-graphql.md
- content\issues\tracking-your-work-with-issues\using-issues\filtering-and-searching-issues-and-pull-requests.md
- content\issues\using-labels-and-milestones-to-track-work\associating-milestones-with-issues-and-pull-requests.md
- content\migrations\importing-source-code\using-the-command-line-to-import-source-code\importing-an-external-git-repository-using-the-command-line.md
- content\pull-requests\committing-changes-to-your-project\creating-and-editing-commits\changing-a-commit-message.md
- content\repositories\managing-your-repositorys-settings-and-features\enabling-features-for-your-repository\disabling-issues.md
- content\site-policy\site-policy-deprecated\amendment-to-github-terms-of-service-applicable-to-us-federal-government-users.md

#### Reusables

- data\reusables\pages\build-failure-email-server.md

## Warning

- content\apps\github-marketplace\using-the-github-marketplace-api-in-your-app\handling-new-purchases-and-free-trials.md
- content\apps\github-marketplace\using-the-github-marketplace-api-in-your-app\testing-your-app.md
- content\get-started\using-git\using-git-rebase-on-the-command-line.md
- content\pull-requests\committing-changes-to-your-project\creating-and-editing-commits\changing-a-commit-message.md
- content\pull-requests\committing-changes-to-your-project\troubleshooting-commits\why-are-my-commits-linked-to-the-wrong-user.md
- content\rest\licenses\licenses.md

#### Reusables

- data\reusables\actions\jobs\section-defining-outputs-for-jobs.md
- data\reusables\apps\deprecating_auth_with_query_parameters.md
- data\reusables\repositories\legacy-issue-template-tip.md

**Comment by nguyenalex836** [comment]
@akordowski Thank you for putting this list of inconsistencies together! Reviewing the list of files now 💛
