### ISSUE TITLE
Capitalize list items in committing-changes-to-a-pull-request-branch-created-from-a-fork.md

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#35455]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

This issue is intended for newcomers to the OS Docs repo! 💛

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ✨

### What part(s) of the article would you like to see updated?

> You can only make commits on pull request branches that:
> 
> - are opened in a repository that you have push access to and that were created from a fork of that repository
> - are on a user-owned fork
> - have permission granted from the pull request creator
> - don't have [branch restrictions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#restrict-who-can-push-to-matching-branches) that will prevent you from committing

Capitalize the first letter in each line of this list to maintain consistency with other docs (and [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#lists))

**Comment by TzivyaFireman** [comment]
I would like to take this issue and work on it.
