### ISSUE TITLE
Move period inside quotation marks in about-comparing-branches-in-pull-requests#about-three-dot-comparison-on-github

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#35454]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#about-three-dot-comparison-on-github

This issue is intended for newcomers to the OS Docs repo! 💛

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ✨

### What part(s) of the article would you like to see updated?

> Since the three-dot comparison compares with the merge base, it is focusing on "what a pull request introduces".

Move periods inside quotation marks to maintain consistency with other docs (and [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide))

**Comment by Johnpicker** [comment]
EQD8TJ8xEWB1SpnRE4d89YO3jl0W0EiBnNS4IBaHaUmdfizE

**Comment by Justnfaith** [comment]
Go jggnkk
