### ISSUE TITLE
Use backticks to format file reference in resolving-a-merge-conflict-using-the-command-line#competing-line-change-merge-conflicts

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#35456]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line#competing-line-change-merge-conflicts

This issue is intended for newcomers to the OS Docs repo! 💛

If you are veteran of the OS Docs repo and are looking for issues to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ✨

### What part(s) of the article would you like to see updated?

> Generate a list of the files affected by the merge conflict. In this example, the file styleguide.md has a merge conflict.

Use backticks to format references to the file names, per our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#file-names-and-directory-names)

**Comment by annegentle** [comment]
I'd like to work on this issue 👋
