### ISSUE TITLE
content/rest/README.md references files that don't exist

### ISSUE THREAD

**Issue by gsnedders** [github/docs#35457]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

N/A (this is a README.md file in the repo)

[content/rest/README.md](https://github.com/github/docs/blob/main/content/rest/README.md)

### What part(s) of the article would you like to see updated?

As of writing, this page says:

https://github.com/github/docs/blob/b68cb60117832e1b3d4b85a011b36745caecde23/content/rest/README.md?plain=1#L5-L6

However, of the three paths mentioned here, two do not exist: 

* [`/content/rest/overview`](https://github.com/github/docs/tree/b68cb60117832e1b3d4b85a011b36745caecde23/content/rest/overview) doesn't exist, since https://github.com/github/docs/commit/3e136b615bb1932fbeecc3d5d1344029aaba9d91 (https://github.com/github/docs/pull/30626), and
* [`/content/rest/reference`](https://github.com/github/docs/tree/b68cb60117832e1b3d4b85a011b36745caecde23/content/rest/reference) doesn't exist, since https://github.com/github/docs/commit/b98c83e9243efc35a2c41742c9ccfeeba8822926 (https://github.com/github/docs/pull/17240).

**Comment by nguyenalex836** [comment]
@gsnedders Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by nguyenalex836** [comment]
[Slack convo](https://github.slack.com/archives/C017M6T23GA/p1732785017045439) for reference

**Comment by nguyenalex836** [comment]
@gsnedders Thank you for your patience while our SME team reviewed! 💛 Our team is proposing the following update to [content/rest/README.md](https://github.com/github/docs/blob/main/content/rest/README.md)

---------------------------

# REST

The `/content/rest` directory is where the GitHub REST API docs live!

* The `/content/rest/about-the-rest-api`, `/content/rest/guides` and `/content/rest/using-the-rest-api` directories contain regular articles. These are human-editable.
* The remaining directories contain an article for each group of endpoints in the GitHub REST API. Most of the content in this directory is rendered using `include` tags.

  The content rendered by `include` tags is sourced from the `/src/rest/data` directory, which is automatically generated from the API source code internally in GitHub, and should not be edited by a human. For more information, see the [`/src/rest/README.md`](/src/rest/README.md).

  **We cannot accept changes to content that is rendered by `include` tags. However, you can open an issue describing the changes you would like to see.**

---------------------------

Thank you again for raising a flag on this issue! Would you be willing to open a PR to make this update? ✨

**Comment by nguyenalex836** [comment]
@gsnedders I've went ahead and added the `help wanted` label so that you, or anyone else, may open a PR to make this update 💛
