### ISSUE TITLE
Correct example/output discrepancy

### ISSUE THREAD

**Issue by PunderfulThymes** [github/docs#35473]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

### What part(s) of the article would you like to see updated?

The [Styling text](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#styling-text) section has a discrepancy between the example and the output for the underline. Creating issue per pull request template instructions.

**Comment by Suliamanshirsad** [comment]
content/organizations/managing-organization-settings/managing-pull-request-reviews-in-your-organization.md

**Comment by Suliamanshirsad** [comment]
-pull-request-reviews-in-your-organization.md

**Comment by nguyenalex836** [comment]
@PunderfulThymes Thank you for opening an issue and linking it to your PR! ✨

**Comment by Sexymanyyy** [comment]
Can I he unsubscribed and deleted from github pls. Idk why I'm even
connected to this.  I let someone use my phone and now I get all these
emails amd I am not a computer coder.
