### ISSUE TITLE
Wrong alert header

### ISSUE THREAD

**Issue by akordowski** [github/docs#35519]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[About OAuth app access restrictions](https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/about-oauth-app-access-restrictions#about-oauth-app-access-restrictions)

### What part(s) of the article would you like to see updated?

The following alert should be rather a note (or maybe even a warning) then a tip.

![grafik](https://github.com/user-attachments/assets/c2447a0a-58d7-4bea-bfbd-603a23b729a2)

### Additional information

I could provide a PR with a fix.

**Comment by nguyenalex836** [comment]
@akordowski Agreed 💛 feel free to open a PR when you have the time!

**Comment by akordowski** [comment]
@nguyenalex836 I think a warning is more appropriate here (then a note) because of the `can also access the organization's private resources` statement. What do you think?

**Comment by nguyenalex836** [comment]
@akordowski You're spot on - I meant to add that to my last reply, but looks like I left that out. Appreciate you doing this update! 💛
