### ISSUE TITLE
Wrong 'OAuth app policy' menu description

### ISSUE THREAD

**Issue by akordowski** [github/docs#35520]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- [About custom organization roles](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/about-custom-organization-roles#permissions-for-organization-access)
- [Enabling OAuth app access restrictions for your organization](https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/enabling-oauth-app-access-restrictions-for-your-organization) and others
-  every article using the `data\reusables\organizations\oauth_app_access.md` reusable

### What part(s) of the article would you like to see updated?

The UI **OAuth app policy** menu is described in the following articles as **OAuth application policy**:

![grafik](https://github.com/user-attachments/assets/c0ff6634-7833-413b-af36-f4a296ee7d62)

### [About custom organization roles](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/about-custom-organization-roles#permissions-for-organization-access)

![grafik](https://github.com/user-attachments/assets/e74e42a9-b06c-47d9-9a79-327669465a48)

### [Enabling OAuth app access restrictions for your organization](https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/enabling-oauth-app-access-restrictions-for-your-organization)

Here is also the icon wrong, it rather should be used this [icon](https://primer.style/foundations/icons/person-24).

![grafik](https://github.com/user-attachments/assets/1e9e9710-d14b-427a-a46e-d968c70a2a0c)

### Additional information

I could provide a PR with a fix.

**Comment by nguyenalex836** [comment]
@akordowski Hello! 👋 I am in agreement with you, but just in case, we'll get a second opinion from the team 💛

**Comment by sophietheking** [comment]
@akordowski 👋 Looks like the menu item needs to be updated indeed!  I've added the help wanted label to this issue so that you, or anyone else, can open a PR to update the docs. 🔨 Thank you for raising a flag on this.
