### ISSUE TITLE
`Allow specified actions and reusable workflows` doesn't mention separator

### ISSUE THREAD

**Issue by jsoref** [github/docs#35564]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#allowing-select-actions-and-reusable-workflows-to-run

### What part(s) of the article would you like to see updated?

Some text in `Allow specified actions and reusable workflows` should specify that the separator between actions is `,`.

### Additional information

If you edit a repository/organization that already has items in the list, you won't see the hint that items in the list need to be `,` separated and the error you get when you try to use an action that you think you've allowed (by adding it after a space) isn't helpful.

For my reference, [I spoke to support about this](https://support.github.com/ticket/personal/0/3114026) and they agreed it wouldn't be unreasonable to adjust the docs.

**Comment by nguyenalex836** [comment]
@jsoref Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by subatoi** [comment]
Many thanks @jsoref — if you're happy to go ahead and raise a contribution for this, please go ahead: it obviously does need documenting and I agree with your suggested placement. I don't expect to have many suggestions in a PR you'd raise for this, if any, but in any case that's the best path forward at this point.

Thanks as ever for opening an issue first!
