### ISSUE TITLE
Incorrect information regarding registering GitHub apps as an app manager

### ISSUE THREAD

**Issue by scottwn** [github/docs#35563]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app

### What part(s) of the article would you like to see updated?

Consider this line https://github.com/github/docs/blob/1f977dfc35197f147bddd84e92db5806ab2e9d2c/content/apps/creating-github-apps/registering-a-github-app/registering-a-github-app.md?plain=1#L28

I am an app manager in the aliro-technologies org. Following the [settings steps](https://github.com/github/docs/blob/1f977dfc35197f147bddd84e92db5806ab2e9d2c/content/apps/creating-github-apps/registering-a-github-app/registering-a-github-app.md?plain=1#L38), when I go to https://github.com/settings/organizations, there is no "settings" button to the right of the aliro-technologies org. There is a "settings" button on another org where I'm an owner. This suggests to me that the documented steps don't work if a user is an app manager. They only work if a user is an owner.

### Additional information

![image](https://github.com/user-attachments/assets/e56991d0-be79-4f93-b9fb-07fae36a5a15)
![image](https://github.com/user-attachments/assets/439b521d-303b-4b3e-ae95-f53da4d3448e)
see also https://github.com/orgs/community/discussions/146391

**Comment by nguyenalex836** [comment]
@scottwn Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by Wepah** [comment]
Alright now I see that I took it to a new level of saying to Yamaha like maybe call it Hulk but still like saying to Yamaha what are you going to do with this power

**Comment by Wepah** [comment]
[Scan - 2024-12-07 20_39_47.pdf](https://github.com/user-attachments/files/18055507/Scan.-.2024-12-07.20_39_47.pdf)
[Scan - 2024-12-07 20_38_58.pdf](https://github.com/user-attachments/files/18055511/Scan.-.2024-12-07.20_38_58.pdf)
[Scan - 2024-12-07 20_38_37.pdf](https://github.com/user-attachments/files/18055513/Scan.-.2024-12-07.20_38_37.pdf)
[Scan - 2024-12-07 20_38_20.pdf](https://github.com/user-attachments/files/18055514/Scan.-.2024-12-07.20_38_20.pdf)
[Scan - 2024-12-07 20_37_59.pdf](https://github.com/user-attachments/files/18055515/Scan.-.2024-12-07.20_37_59.pdf)
[Scan - 2024-12-07 20_37_31.pdf](https://github.com/user-attachments/files/18055518/Scan.-.2024-12-07.20_37_31.pdf)
[Scan - 2024-12-07 20_37_03.pdf](https://github.com/user-attachments/files/18055520/Scan.-.2024-12-07.20_37_03.pdf)
[Scan - 2024-12-07 20_36_12.pdf](https://github.com/user-attachments/files/18055521/Scan.-.2024-12-07.20_36_12.pdf)
[Scan - 2024-12-07 20_35_40.pdf](https://github.com/user-attachments/files/18055522/Scan.-.2024-12-07.20_35_40.pdf)
[Scan - 2024-12-07 20_35_12.pdf](https://github.com/user-attachments/files/18055523/Scan.-.2024-12-07.20_35_12.pdf)
[Scan - 2024-12-07 20_34_47.pdf](https://github.com/user-attachments/files/18055525/Scan.-.2024-12-07.20_34_47.pdf)
[Scan - 2024-12-07 20_33_38.pdf](https://github.com/user-attachments/files/18055526/Scan.-.2024-12-07.20_33_38.pdf)
[Scan - 2024-12-07 20_32_45.pdf](https://github.com/user-attachments/files/18055527/Scan.-.2024-12-07.20_32_45.pdf)
[Scan - 2024-12-07 20_32_17.pdf](https://github.com/user-attachments/files/18055528/Scan.-.2024-12-07.20_32_17.pdf)
[Scan - 2024-12-07 20_31_52.pdf](https://github.com/user-attachments/files/18055529/Scan.-.2024-12-07.20_31_52.pdf)
[Scan - 2024-12-07 20_31_04.pdf](https://github.com/user-attachments/files/18055536/Scan.-.2024-12-07.20_31_04.pdf)
[Scan - 2024-12-07 20_30_49.pdf](https://github.com/user-attachments/files/18055537/Scan.-.2024-12-07.20_30_49.pdf)
[Scan - 2024-12-07 20_30_22.pdf](https://github.com/user-attachments/files/18055539/Scan.-.2024-12-07.20_30_22.pdf)
[Scan - 2024-12-07 20_29_12.pdf](https://github.com/user-attachments/files/18055540/Scan.-.2024-12-07.20_29_12.pdf)
[Scan - 2024-12-07 20_28_49.pdf](https://github.com/user-attachments/files/18055541/Scan.-.2024-12-07.20_28_49.pdf)
[Scan - 2024-12-07 20_17_27.pdf](https://github.com/user-attachments/files/18055544/Scan.-.2024-12-07.20_17_27.pdf)
[Scan - 2024-12-07 20_16_18.pdf](https://github.com/user-attachments/files/18055548/Scan.-.2024-12-07.20_16_18.pdf)
[Scan - 2024-12-07 20_15_16.pdf](https://github.com/user-attachments/files/18055549/Scan.-.2024-12-07.20_15_16.pdf)
[Scan - 2024-12-07 20_14_31.pdf](https://github.com/user-attachments/files/18055550/Scan.-.2024-12-07.20_14_31.pdf)
[Scan - 2024-12-07 20_14_00.pdf](https://github.com/user-attachments/files/18055551/Scan.-.2024-12-07.20_14_00.pdf)
[Scan - 2024-12-07 19_57_18.pdf](https://github.com/user-attachments/files/18055557/Scan.-.2024-12-07.19_57_18.pdf)
[Scan - 2024-12-07 19_58_42.pdf](https://github.com/user-attachments/files/18055558/Scan.-.2024-12-07.19_58_42.pdf)
[Scan - 2024-12-07 20_06_08.pdf](https://github.com/user-attachments/files/18055560/Scan.-.2024-12-07.20_06_08.pdf)
[Scan - 2024-12-07 20_04_29.pdf](https://github.com/user-attachments/files/18055561/Scan.-.2024-12-07.20_04_29.pdf)
[Scan - 2024-12-07 20_06_31.pdf](https://github.com/user-attachments/files/18055562/Scan.-.2024-12-07.20_06_31.pdf)
[Scan - 2024-12-07 20_07_14.pdf](https://github.com/user-attachments/files/18055563/Scan.-.2024-12-07.20_07_14.pdf)
[Scan - 2024-12-07 20_08_19.pdf](https://github.com/user-attachments/files/18055564/Scan.-.2024-12-07.20_08_19.pdf)
[Scan - 2024-12-07 20_07_57.pdf](https://github.com/user-attachments/files/18055566/Scan.-.2024-12-07.20_07_57.pdf)
[Scan - 2024-12-07 20_08_43.pdf](https://github.com/user-attachments/files/18055567/Scan.-.2024-12-07.20_08_43.pdf)
[Scan - 2024-12-07 20_09_29.pdf](https://github.com/user-attachments/files/18055568/Scan.-.2024-12-07.20_09_29.pdf)
[Scan - 2024-12-07 20_10_04.pdf](https://github.com/user-attachments/files/18055569/Scan.-.2024-12-07.20_10_04.pdf)

**Comment by Wepah** [comment]
In the notes everything the same

**Comment by scottwn** [comment]
Is there an ETA for the technical review? Not being able to register apps is causing business delays for my team, so I'd appreciate some information about how to register apps properly.

**Comment by nguyenalex836** [comment]
@scottwn Hello! 👋 We are unable to provide an ETA for SME review - apologies for the inconvenience. We would recommend reaching out to our [support team](https://support.github.com/contact) if you are looking for quicker assistance 💛

**Comment by nguyenalex836** [comment]
@scottwn Hello! Thank you for your patience while our SMEs reviewed 💛 They responded with the following -

> I believe this is a bug due to the fact that the organization does not have any existing integrations.
I am currently an App Manager of a single App on an org and am able to view the `Settings` tab, so the claim that `They only work if a user is an owner` is false.

They've opened a bug report on their end to investigate why apps managers are not shown `Settings` tab when the organization does not own any Integrations. While we are unable to provide a timeline on resolution, we can assure you our team is aware of this issue, and thanks your for bringing this to our attention 🙇 

I'll go ahead and close this issue. If you have other suggestions for updating our docs, please let us know!

**Comment by scottwn** [comment]
thanks @nguyenalex836 . After getting the integrations set up, I still don't see "settings" to the right of the organization name as the docs say. I *can* access the "Settings" tab on the organization landing page, even without an integration, which is where support directed me. So, at least in my case, the issue isn't not owning integrations. The issue is that the docs describe the wrong location for the "Settings" tab. The doc should direct app managers to access "Settings" from the organization landing page.
![Screenshot 2024-12-23 at 4 59 36 PM](https://github.com/user-attachments/assets/a086c254-8778-4e0e-ae23-539c5fed15e0)
![Screenshot 2024-12-23 at 4 58 41 PM](https://github.com/user-attachments/assets/36c6cbe5-253a-4556-816f-a4c0558f3b6f)

**Comment by nguyenalex836** [comment]
@scottwn Thank you for the update, and including that screenshot! ✨ Before we make an update to the docs, I'm going touch base with our SMEs for their input on your last comment.

Given the proximity to the holidays, we may not receive a response for a while. If you need any assistance additional assistance with registering apps / integrations, Support will continue to be the best resource 💛 

Once our SMEs have had a chance to review your latest comment, we'll update you here!

**Comment by lrotschy** [comment]
It looks like we've got two issues here.

1. The organization list page doesn't show the settings button for app managers.

We have a PR up to show the settings button for app managers in the org list view, so that should be handled shortly.

2. The docs are unclear about what an app manager is able to manage.

The linked community discussion points to two docs that seem to be contradictory. I think the key is [this sentence in the public docs](https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/adding-and-removing-github-app-managers-in-your-organization): "GitHub App managers can manage the settings of some or all of the GitHub App registrations that are owned by the organization. The GitHub App manager role does not grant users access to install and uninstall GitHub Apps on an organization." 

App managers have the ability to register new apps that will be owned by the organization, and they are able to edit settings for existing apps that are owned by the organization. You can see those under Settings > Developer settings > GitHub Apps. From there you are able to install the app on organizations where you are an owner if the app is public.

App managers do not have the ability to manage apps that are actually installed for use in the org. You can find those in Settings > GitHub Apps (under Third-party Access) if you have access. 

Please let me know if that's still unclear or if there is anything we've missed!
