### ISSUE TITLE
Typo in `searching-users.md`

### ISSUE THREAD

**Issue by mhashim6** [github/docs#35589]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/searching-on-github/searching-users#search-by-account-name-full-name-or-public-email

### What part(s) of the article would you like to see updated?

The `org:name` example, it’s saying `type:users` instead of `type:user`:

Qualifier | Example
-- | --
user:name | user:octocat matches the user with the username "octocat".
**org:name** | org:electron **type:users** matches the Electron organization's account name.
in:login | kenya in:login matches users with the word "kenya" in their username.
in:name | bolton in:name matches users whose real name contains the word "bolton."
fullname:firstname lastname | fullname:nat friedman matches a user with the full name "Nat Friedman." Note: This search qualifier is sensitive to spacing.
in:email | data in:email matches users with the word "data" in their email.

**Comment by nguyenalex836** [comment]
@mhashim6 Thank you for opening an issue and linking it to your PR! ✨
