### ISSUE TITLE
`ruleId` is written as `ruleID` in a couple of places

### ISSUE THREAD

**Issue by jsoref** [github/docs#35709]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#providing-data-to-track-code-scanning-alerts-across-runs

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#providing-data-to-track-code-scanning-alerts-across-runs

> Each time the results of a new code scan are uploaded, the results are processed and alerts are added to the repository. To prevent duplicate alerts for the same problem, code scanning uses fingerprints to match results across various runs so they only appear once in the latest run for the selected branch. This makes it possible to match alerts to the correct line of code when files are edited. The [`ruleID`](#) for a result has to be the same across analysis.

* Note that this instance has **ruleID** instead of **ruleId**

https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#result-object

Name | Required | Description
-- | -- | --
[ruleId](#)	||	The unique identifier of the rule (reportingDescriptor.id). For more information, see the [reportingDescriptor object](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#reportingdescriptor-object). Code scanning uses the rule identifier to filter results by rule on GitHub.

> Note that this instance has **ruleId**

https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#example-with-minimum-required-properties

```json
...
          "ruleId": "R01",
          "message": {
            "text": "Specifying both [ruleIndex](1) and [ruleID](2) might lead to inconsistencies."
          },
...
```

* Note that this last instance has **ruleID** instead of **ruleId**

---
_Maintainer update_

## Content change needed to fix this issue

Open the [source file](https://github.com/github/docs/blob/main/content/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning.md) and replace the two instances of `ruleID` with `ruleId`.

**Comment by nguyenalex836** [comment]
@jsoref Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by felicitymay** [comment]
Hi @jsoref 👋🏻 

Thanks for flagging this typo in the docs. I checked in the [schema for SARIF](https://github.com/oasis-tcs/sarif-spec/blob/123e95847b13fbdd4cbe2120fa5e33355d4a042b/Schemata/sarif-schema-2.1.0.json#L2042) and it definitely should be the camel case version.

I'll add a brief note on how to fix this to the issue summary and flag this as `help wanted`.
