### ISSUE TITLE
Using ✔️ / 𐌢 is cognitively painful -- consider using Yes/No

### ISSUE THREAD

**Issue by jsoref** [github/docs#35710]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Each of the pages with this: https://github.com/search?q=repo%3Agithub%2Fdocs%20%2Focticon%20%22check%22%20aria-label%3D%22Required%22%2F&type=code

A rendered example is:
https://docs.github.com/en/actions/migrating-to-github-actions/using-github-actions-importer-to-automate-migrations/migrating-from-bamboo-with-github-actions-importer#configuring-credentials

Note that this page is *not* affected because it uses the word `No` which I can read and understand:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-a-notice-message

It's based on https://github.com/github/docs/blob/3e1dad37ec62eb2963348790f72d1fd301ce34b8/data/reusables/actions/message-parameters.md

### What changes are you suggesting?

Don't use fancy ✔️ / 𐌢 for required/not required.

Consider using `Yes` and `No`.

I'm used to a lot of places that use _some marker_ (that could be a ✔️ or an 𐌢) for required and the absence of a marker for optional.

Note that the current code does not have any alt/title text which means people who hover over things but aren't using screen readers won't get the aria hint (it didn't occur to me to try asking a screen reader for help, and while I do intend to ask some screen reader friends how they feel about tables with lots of cells with `Required/Not required` or `Included`/`Not included` I fully expect that I'll owe them a couple of beers after they are tortured by the respective web pages and their selected screen readers -- I'll need the beers too from the headache I'll get and I have one just trying to file this ticket).

### Additional information

GitHub's pricing thing does something _similar_, but it has a huge number of differences:
https://github.com/pricing#compare-features
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/3be8c147-d048-4ad7-ab42-10714341d6e9" />
<img width="1207" alt="image" src="https://github.com/user-attachments/assets/40d487bd-8ec6-45ff-a28e-08c73cd441bf" />
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/cf61dcf1-012d-4e1c-989e-f19ffe62045a" />

1. The first n times one encounters anything it's a ✔️ (Included) not an 𐌢 (Not included)
2. The first time one encounters an 𐌢 (Not included) there's also at least one ✔️ (Included) in plain view which gives the reader at least some context if they somehow missed the first n ✔️ (Included) items
3. It uses Alt text instead of aria which means even people not paying for a screen reader can get a better experience and maybe figure out what's going on.

For context, I implemented sarif support for check-spelling over the span of many many months, and I totally failed to understand from looking at the top of:
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#result-object
<img width="769" alt="image" src="https://github.com/user-attachments/assets/b6966c20-468a-4f35-a78e-a94c131f3722" />

that I probably shouldn't include a `ruleIndex` -- so, I included it even though it actually made a mess of things.

It's possible all of this stems from my concussion, but in talking to other developers, I'm not alone in not really expecting a plain 𐌢 not to be the opposite of blank.

**Comment by nguyenalex836** [comment]
@jsoref Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by felicitymay** [comment]
Hi @jsoref 👋🏻 

Thanks for raising this point about readability, especially for people who aren't using a screenreader.

> I'm used to a lot of places that use some marker (that could be a ✔️ or an 𐌢) for required and the absence of a marker for optional.

  * We previously used the absence of a marker to indicate items that were optional. However, this caused its own accessibility problem. My understanding is that screen readers expect all cells in a table to be populated.

> Note that the current code does not have any alt/title text which means people who hover over things but aren't using screen readers won't get the aria hint (it didn't occur to me to try asking a screen reader for help, and while I do intend to ask some screen reader friends how they feel about tables with lots of cells with Required/Not required or Included/Not included I fully expect that I'll owe them a couple of beers after they are tortured by the respective web pages and their selected screen readers -- I'll need the beers too from the headache I'll get and I have one just trying to file this ticket).

 * Clearly we had no intention of making the experience worse for sighted users. I'm going to raise an issue internally for our docs PMs to review this - especially the point about aria text not being available without a screen reader.
 * I'll raise a second internal issue for us to review the tables in the SARIF support article and look at how we can be clearer about what's required.

**Comment by felicitymay** [comment]
@jsoref - I've opened the two internal issues I mentioned above. I'm going to close this issue as there are no further actions to take in the `docs` repository.

Thanks for raising this concern with detailed examples. Much appreciated. ✨

**Comment by jsoref** [comment]
@felicitymay fwiw I spoke w/ @aibaars [about the SARIF item](https://ghsecuritylab.slack.com/archives/CQUMTHL1M/p1734575615056329) and was going to file a ticket (after opening this one) suggesting that the SARIF specific page encourage people to use `ruleId` instead of `ruleIndex`...
* at present there's virtually no value in using `ruleIndex` (if you're compressing things you'd want to compress other things (`rules`) which would make the cost of calculating `ruleIndex` pretty high, and in the end you're going to compress the file which would probably defeat the win you'd get in on disk size; but once you've done this you lose the ability to track things across runs -- as noted in the docs -- which is a real usability downside)
* as well as some other amusing details about what is documented (you can technically according to the docs specify a 2^63-1 index, but in practice you'll hit either a file size exception or likely a timeout in uploads/processing -- so while bleeding the internal implementation detail is nice, it's actually not really good advice since anyone trying will not be happy with the result -- there's already advice elsewhere in sarif to limit most things to `5000` or some multiplier of that, whereas this is many many orders of magnitude beyond that -- and again, see minification note).

Since you're going to tackle this internally, I'm just leaving this additional note for you to cary over instead of filing a ticket about it.

**Comment by felicitymay** [comment]
Many thanks for the additional information. I'll copy that across to the internal issue. 💖
