### ISSUE TITLE
`moda-ci.yaml` triggers an error in forks for anyone who doesn't have access to github/docs-internal

### ISSUE THREAD

**Issue by jsoref** [github/docs#35731]
This guard https://github.com/github/docs/blob/190a7a5f33b3a1359ce00eb56ac4ce3d24f37fed/.github/workflows/moda-ci.yaml#L39

did not prevent: 
[Invalid workflow file: .github/workflows/moda-ci.yaml#L86](https://github.com/jsoref/github-docs/actions/runs/12431941269/workflow)
```
error parsing called workflow
".github/workflows/moda-ci.yaml"
-> "github/internal-actions/.github/workflows/docker_security.yml@main"
: workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.
```

I think it might be possible to avoid this structure by using a combination of a `workflow_call` with a `jobs:` / `if:` _condition that guards against the user from tripping on the problem_ e.g. `${{ github.repository == 'github/docs-internal' }} ` and then have the `on: workflow_call` on the internal side be responsible for using the reusable workflow.

_Originally posted by @jsoref in https://github.com/github/docs/issues/34562#issuecomment-2557006698_

**Comment by nguyenalex836** [comment]
@jsoref Thank you for raising the flag on this! ✨ Given the referenced file, I'll create an issue to have this reviewed internally 💛 

I'll close this issue, but if you find anything else that might be relevant, feel free to ping me here and I'll copy over to the internal issue!

**Comment by jsoref** [comment]
Please note that the `if`'s added in https://github.com/github/docs/commit/2a39a952aeaf3c28c82e4055ca01a2ecf081a0e7 did *not* fix the issue here:

https://github.com/jsoref/github-docs/actions/runs/13528339007

**Comment by jsoref** [comment]
<details><summary>Here's a quick sample of forks wasting resources on this</summary>

Based on the first page of results in https://github.com/search?q=path%3A.github%2Fworkflows%2Fmoda-ci.yaml+is%3Afork&type=code:

https://github.com/Judecoin/docs/actions/workflows/moda-ci.yaml
https://github.com/fieropheonix6/docs-1/actions/workflows/moda-ci.yaml
https://github.com/cclauss/docs-1/actions/workflows/moda-ci.yaml
https://github.com/Hitgub01/docs/actions/workflows/moda-ci.yaml
https://github.com/acardoz/docs/actions/workflows/moda-ci.yaml
https://github.com/wutthichai46/docs/actions/workflows/moda-ci.yaml
https://github.com/peteos123/docs/actions/workflows/moda-ci.yaml
https://github.com/83kk11/docs/actions/workflows/moda-ci.yaml
https://github.com/Joramtech/docs/actions/workflows/moda-ci.yaml
https://github.com/razor4u/docs/actions/workflows/moda-ci.yaml
https://github.com/DausAdy/docs/actions/workflows/moda-ci.yaml
https://github.com/xjc90s/docs/actions/workflows/moda-ci.yaml
https://github.com/tonylikestoburns2020/docs-1/actions/workflows/moda-ci.yaml
https://github.com/linwilai918/docs/actions/workflows/moda-ci.yaml
https://github.com/seanb95531/docs/actions/workflows/moda-ci.yaml
https://github.com/ScorpiusDraconis83/docs/actions/workflows/moda-ci.yaml
https://github.com/Hadiismanto11/docs/actions/workflows/moda-ci.yaml
https://github.com/PcjsCorp/docs/actions/workflows/moda-ci.yaml
https://github.com/DarkMan8/docs/actions/workflows/moda-ci.yaml
https://github.com/3M-com/docs/actions/workflows/moda-ci.yaml
https://github.com/Akshit1025/github-docs/actions/workflows/moda-ci.yaml
https://github.com/TeamWaggles/docs/actions/workflows/moda-ci.yaml
https://github.com/rimajl2020/docs/actions/workflows/moda-ci.yaml
https://github.com/DonnyMann88/docs/actions/workflows/moda-ci.yaml
https://github.com/JhovanEscobidal/docs/actions/workflows/moda-ci.yaml
https://github.com/Scot-Ringa/docs/actions/workflows/moda-ci.yaml
https://github.com/Mindii13/docs/actions/workflows/moda-ci.yaml
https://github.com/mark-mxwl/docs/actions/workflows/moda-ci.yaml
https://github.com/Gand0r/docs/actions/workflows/moda-ci.yaml
https://github.com/NickPirs/docs/actions/workflows/moda-ci.yaml
https://github.com/irthomasthomas/docs/actions/workflows/moda-ci.yaml
https://github.com/Benzayb014/docs-1/actions/workflows/moda-ci.yaml
https://github.com/WEEDAVIE1990/docs/actions/workflows/moda-ci.yaml
https://github.com/SoundaryaKoutharapu/docs/actions/workflows/moda-ci.yaml
https://github.com/alexsio274limitedd/docssss/actions/workflows/moda-ci.yaml
https://github.com/OctopusDeploy/github-docs/actions/workflows/moda-ci.yaml
https://github.com/Unity-for-manufacturing-assets-of-Unity/docs-1/actions/workflows/moda-ci.yaml
https://github.com/Melissa1181/docs/actions/workflows/moda-ci.yaml
https://github.com/kattakaha/docs/actions/workflows/moda-ci.yaml
https://github.com/Ucg2c3/docs/actions/workflows/moda-ci.yaml
https://github.com/Tkelley325/docs/actions/workflows/moda-ci.yaml
https://github.com/odenizo/docs/actions/workflows/moda-ci.yaml
https://github.com/kosai-ksdfounder/docs/actions/workflows/moda-ci.yaml
https://github.com/blacktatty-multi/Readme.txt/actions/workflows/moda-ci.yaml
https://github.com/tr4200812/hubhub/actions/workflows/moda-ci.yaml
https://github.com/mattsk123/docs/actions/workflows/moda-ci.yaml
https://github.com/psyberjunkie/docs/actions/workflows/moda-ci.yaml
https://github.com/zuzulenka95111/docs/actions/workflows/moda-ci.yaml
https://github.com/Mrlove5/docs/actions/workflows/moda-ci.yaml
https://github.com/Scissors-And-Bleach/Riaan-Van-Wyngaardt-/actions/workflows/moda-ci.yaml
https://github.com/razeljoy29/docs/actions/workflows/moda-ci.yaml
https://github.com/MISTERNEGATIVE21/docs/actions/workflows/moda-ci.yaml
https://github.com/echemmara/docs/actions/workflows/moda-ci.yaml
https://github.com/bot-webhook/docs/actions/workflows/moda-ci.yaml
https://github.com/paulinek13/docs/actions/workflows/moda-ci.yaml
https://github.com/Dividivnoe/docs/actions/workflows/moda-ci.yaml
https://github.com/asd2025-alt/docs/actions/workflows/moda-ci.yaml
https://github.com/Weera1234/docs/actions/workflows/moda-ci.yaml
https://github.com/kumgangofficial/Kumgangofficial/actions/workflows/moda-ci.yaml
https://github.com/Veeezo/docs-1/actions/workflows/moda-ci.yaml
https://github.com/Shakacro/docs/actions/workflows/moda-ci.yaml
https://github.com/seanb95531/docs/actions/workflows/moda-ci.yaml
https://github.com/wutthichai46/docs/actions/workflows/moda-ci.yaml
https://github.com/Judecoin/docs/actions/workflows/moda-ci.yaml
https://github.com/farshadjanu1/docs/actions/workflows/moda-ci.yaml
https://github.com/Etilmetilketilvinil/docs/actions/workflows/moda-ci.yaml
https://github.com/kkkkKKeeyyyYYYYY/docs/actions/workflows/moda-ci.yaml
https://github.com/Cari0909/docs/actions/workflows/moda-ci.yaml
</details>
