### ISSUE TITLE
Improve auto-merge documentation by explaining what is that

### ISSUE THREAD

**Issue by okainov** [github/docs#3607]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/administering-a-repository/managing-auto-merge-for-pull-requests-in-your-repository and https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request

### What part(s) of the article would you like to see updated?

I really miss information here about what auto-merge _actually is_, what _does it do_? Will it automatically rebase the changes every time (if rebase strategy is set)? Will it update the branch every time (if correponding option is set)? If multiple PRs have auto-merge enabled, will it build some kind of "merge train" behind the scenes to ensure the correct order and minimize extra CI workload?

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @okainov! I'll triage this for the team to take a look 👀

**Comment by mateopotvin** [comment]
DESOLER JASAILLE TOUJOUR DE COMPRENDRE
JAI HATE DE FULL COMPRENDRE AVEC ,AVOIR AUCUNNE PEUR
DALLER SUR GITBUT 
MERCI

**Comment by janiceilene** [comment]
👋 Auto merge just uses whatever merge strategy you choose when you hit the button and doesn't do any additional magic, so I don't think there are any updates needed in the docs right now. If you find anything else, let us know!

**Comment by okainov** [comment]
@janiceilene  how does it behave when there are.multiple PRs and each of them has auto-merge enabled?

**Comment by janiceilene** [comment]
I believe it merges the first PR and then you need to update the branches for all the subsequent ones, so they don't merge.

**Comment by okainov** [comment]
> then you need to update the branches for all the subsequent ones,

oO????? What is the point of this auto-merge then at all if it doesn't do it??? I thought idea was to reduce amount of manual work and clicking buttons, but it doesn't really change anything then!

**Comment by marc-hb** [comment]
>  If multiple PRs have auto-merge enabled, will it build some kind of "merge train" behind the scenes to ensure the correct order and minimize extra CI workload?

I'm not sure what situation you're referring to here but if you and I submit PRs totally unrelated to each other then I would probably prefer my changes to be tested in isolation at some point in the flow.

> I believe it merges the first PR and then you need to update the branches for all the subsequent ones, so they don't merge.

Strange, why? Does "subsequent" here imply some kind of relationship between the PRs or does it just mean "not the first merged"?

Either way I couldn't find anything like this in the documentation, is there?

**Comment by janiceilene** [comment]
I don't have insight into why the feature works the way it does. The best place to send your feedback is to https://support.github.com/contact/feedback 💛
