### ISSUE TITLE
baptiste preview does not work on geting individual repo or list of repos

### ISSUE THREAD

**Issue by ahmadnassri** [github/docs#3630]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/repos

### What part(s) of the article would you like to see updated?

currently the document lists examples of `template_repository` in the response objects of the following endpoints:

- `GET /repos/{owner}/{repo}`
- `GET /users/{username}/repos`
- `GET /orgs/{org}/repos`
 
and hints at needing the `application/vnd.github.baptiste-preview+json` Accept header for enabling these properties.

However, this doesn't work, none of the endpoints return `template_repository` values for repositories that should.

### Additional information

```bash
http https://api.github.com/orgs/{org}/repos?per_page=100 "Authorization: token $GH_TOKEN" "Accept: application/vnd.github.baptiste-preview+json" | jq .[].template_repository
```

![image](https://user-images.githubusercontent.com/183195/107722670-77347280-6cad-11eb-9ce3-d543e286346d.png)

**Comment by janiceilene** [comment]
@ahmadnassri Thanks so much for opening an issue! I'll triage this for the team to take a look 👀

**Comment by janiceilene** [comment]
Thanks @ahmadnassri I've checked in with folks and it sounds like this is a question better suited to our [support team](https://support.github.com/contact)!
