### ISSUE TITLE
Document Auto-Merge and GH Actions

### ISSUE THREAD

**Issue by phish108** [github/docs#3707]
### What article on docs.github.com is affected?

[Automatically merging a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request)

### What part(s) of the article would you like to see updated?

The article is good for getting started, but it leaves many aspects in relation to GH Actions unclear. With this respect the article should be a bit more verbose. 

For example: 
- will automerge trigger an GH Actions event if GH actions already ran during the the checks phase? 
- What would be the event? 
- Where would we find more documentation? 

Normally GH Actions will not trigger a secondary action if an event is the result of an action. This is important information, because this feature is tightly coupled to GH Actions. 

From the Documentation I would assume NO secondary action would be triggered.

### Additional information

I did not run any experiments to check this behaviour. 

In my repos I have steps that have to get performed **after** the merge took place. Given the documentation I don't feel confident to refactor my actions.

**Comment by simpsoka** [comment]
Thanks for opening this issue, @phish108! 

Auto-merge and GitHub Actions are two separate features, however, they work together in the CI/CD workflow. Once all of your tests pass, if you have auto-merge enabled, then the PR will merge automatically. If the tests don't pass, then you'll get a failed notification and you'll have to investigate and then re-run your actions. 

This is best documented at the [top of this article](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request): 

> If you enable auto-merge for a pull request, the pull request will merge automatically when all required reviews are met and status checks have passed. Auto-merge prevents you from waiting around for requirements to be met, so you can move on to other tasks.
> 
> Before you can use auto-merge with a pull request, auto-merge must be enabled for the repository.

Also, note that auto-merge works for other things like required reviews as well as Actions. 

If you're interested in seeing if auto-merge would work for a particular workflow you have, I'd love to see that and we can pass along any product feedback you may have to the product team that works on the feature here at GitHub. Testing out your workflow would be a great place for you to start.

**Comment by phish108** [comment]
Thanks @simpsoka 

This is what the docu states and this was already clear. But neither the docs nor your answer state whether auto-merge will trigger a gh action if auto-merge is activated by another GH action. 

There are workflows that depend steps that must run *after* the merge has completed. Now with other GH events it is the case that these events are *not* triggered to downstream workflows if another GH action was involved at some point in the process. The only work around in this case are calls to `workflow_dispatch` with a special token and this depends on not leaving the inital workflow. Now, this would be no longer possible with auto-merge because of not being part of an  action workflow. 

Simple scenario: 

- Dependabot triggers a PR
- all tests pass (via GH workflows)
- auto merge applies the PR
- a new release is published and deployed (via a different GH workflow). 

Until now the second workflow  would  not get triggered. 

From the docs I would expect that "prevents you from waiting" implies triggering  the second workflow, but then the agency is with the user not with a workflow. 

To be sure I have to test this, but it would be better if the docs could be a wee bit more explicit on the point if auto-merge responds differently to "side effects" of workflows than the rest of GH - or not.

**Comment by F22038299** [comment]
Good

**Comment by simpsoka** [comment]
That's definitely an interesting workflow, and I don't think this is functionally of the auto-merge feature, but rather an action you're triggering after the PR is merged. 

There isn't a way to trigger a workflow based on the merge event, but because a merge results in a push, you could set up a workflow that triggers an action on push after the pr is merged. 

However this functionality is all for actions, not auto merge. If you test it out for your specific workflow, would love to see it. This may help with your testing: https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/3 

I'm going to go ahead and close this issue since the functionality is specific to a workflow related to GitHub actions and not auto merge.
