### ISSUE TITLE
Specifying email address for web-based Git operations

### ISSUE THREAD

**Issue by joel-coffman** [github/docs#3745]
### What article on docs.github.com is affected?

[Setting your commit email address](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)

### What part(s) of the article would you like to see updated?

"[Setting your commit email address on GitHub](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-on-github)" indicates that the primary email address will be used for web-based Git operations, but this statement does not appear to be correct. At least, web-based Git operations are not being associated with my primary email address. Moreover, the associated text no longer mentions web-based Git operations as shown in the screenshot in the documentation and instead indicates the email "will be used for account-related notifications and can be used for password resets".

**Comment by janiceilene** [comment]
👋 Thanks for opening an issue @joel-coffman! You're right, that screenshot is out of date. We'll work on tracking down some more information about what the best fix for this article might be.

**Comment by janiceilene** [comment]
👋 @joel-coffman I've spoken to a few different teams and agree that these docs need updating! We need to do some additional digging to figure out the best changes to make, so I'm going to close this issue and open one internally for the team to take a look at. Thanks so much for bringing this to our attention!
