### ISSUE TITLE
API changes to support internal repository visibility link to Internal is dangling

### ISSUE THREAD

**Issue by jsoref** [github/docs#3761]
### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/github/creating-cloning-and-archiving-repositories/creating-a-new-repository.md

### What part(s) of the article would you like to see updated?

There's a picture:
![with internal](https://docs.github.com/assets/images/help/repository/create-repository-public-private.png)
... but there's no text and no anchor for `internal`.

### Additional information

https://developer.github.com/changes/2019-12-03-internal-visibility-changes/ by @iolsen has a link to https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-an-internal-repository#about-internal-repositories
> Customers with an enterprise account using GitHub Enterprise Cloud and GitHub Enterprise Server 2.20+ have access to a third visibility option beyond public and private, called _internal_. We've made some recent API changes to support this option.

I tried the various non github.com versions of the doc (e.g. GHE3.0/GHE2.20), but they don't have this anchor either.

**Comment by janiceilene** [comment]
👋 @jsoref I'm not totally sure I'm understanding your request. When I open [Creating a new repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-new-repository), I see the image you added above in step 6 with the text, `Choose a repository visibility. For more information, see "About repository visibility."`

When I click "About repository visibility," it takes me to https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-repository-visibility. The second section of that page is [About internal repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-repository-visibility#about-internal-repositories).

Is there any update you'd like to see in the docs?

For the blog post https://developer.github.com/changes/2019-12-03-internal-visibility-changes/, I'd guess that our articles were structured a bit differently when it was posted, but we don't own those posts.

**Comment by FishermanTradingCompany** [comment]
I have no idea what any of that means

**Comment by jsoref** [comment]
Well, @iolsen is on staff.

The blog post is still quite reachable. And it talks about internal and links to a page which supposedly describes internal, but doesn't.

The `nebula-preview` documentation explicitly links to the blog post as the official announcement for this feature. So it's a pretty rooted in GitHub.

https://www.google.com/search?q=https%3A%2F%2Fdeveloper.github.com%2Fchanges%2F2019-12-03-internal-visibility-changes%2F

If you don't want to fix the page to talk about internal, then please either get the blog post changed or get someone to write a new iteration of the nebula blog post documentation.

For reference, I found that page by reading https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml

**Comment by FishermanTradingCompany** [comment]
Okay I just also don’t understand why I have one

**Comment by janiceilene** [comment]
@jsoref This repo is only the source for docs.github.com. We have a page about what internal repos are, linked directly from the article in the blog post, so I don't think the docs need any updating right now. 

The docs team doesn't own or update any blog posts. It looks like you can open a new issue in https://github.com/github/rest-api-description/issues/new/choose using the "Schema inaccuracy" template. That would probably be the best place to ask for an update and explain the confusion you're seeing 💛
