### ISSUE TITLE
Update "Verify a Domian" Documentation

### ISSUE THREAD

**Issue by Mentors4EDU** [github/docs#3834]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/setting-up-and-managing-your-enterprise/verifying-your-enterprise-accounts-domain

### What part(s) of the article would you like to see updated?

Hi, the current documentation for domain verification doesn't work at all for Namecheap or Google Domains. I haven't been able to verify my domains for years, and finally realized that is should be:
```
Host: _github-challenge-<YOUR_GITHUB_ORG_NAME>
Value: <GITHUB_VERIFICATION_CODE>
TTL: Automatic
```
Instead of ```Host: _github-challenge-<YOUR_GITHUB_ORG_NAME>.domain```
This article on Medium summarizes the problem well: https://medium.com/@derekfong/verify-github-organizations-domain-on-namecheap-9b2af148679a

It would create a lot less confusion if the docs also offered an alternative step where you remove ```.domain``` part if you have trouble verifying.
### Additional information

Just wanted to make you all aware of this slight glitch. On a sidenote, thanks for making GitHub so awesome :)

**Comment by janiceilene** [comment]
Thanks so much @Mentors4EDU! Our current documentation is intended to be useable for as many providers as possible, you can refer to your individual registrar for details. If you find any errors with the existing documentation, let us know!
