### ISSUE TITLE
Parameter `per_page` in `List matching references` didn't work as expected

### ISSUE THREAD

**Issue by conwnet** [github/docs#3863]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/git#list-matching-references

### What part(s) of the article would you like to see updated?

The [Parameters](https://docs.github.com/en/rest/reference/git#list-matching-references--parameters) block says we can add a parameter named `per_page` to limit the length of response array, but it seems didn't work now.
For example:
https://api.github.com/repos/microsoft/vscode/git/matching-refs/heads?per_page=30

we may should remove the `per_page` and `page` parameters in this doc.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @conwnet! I'll triage this for the team to take a look 👀

**Comment by janiceilene** [comment]
👋 @conwnet I've spoken to the team and it sounds like this is a bug. You can open a ticket with our wonderful [support team](https://support.github.com/contact)!

**Comment by cmwilson21** [comment]
@andreiv1992 Thanks for bringing this up! This sounds as though it may need our awesome [support team](https://support.github.com/contact) to check into it. Please reach out to them to report this bug. 

Thank you! 💛

**Comment by palfrey** [comment]
@cmwilson21 I've just opened a support ticket as I'm hitting this as well.

**Comment by a-shaforostov** [comment]
2024 coming. Every year someone new comes here and asks to fix it. 
We are aging together with this bug.
