### ISSUE TITLE
Duplicate Contributors on README

### ISSUE THREAD

**Issue by Ruth-ikegah** [github/docs#389]
### What file is affected?
The README has duplicate contributors, it seems the all-contributors bot appears to have a bug. 

### Additional information

![Screenshot 2020-10-10 134956_LI](https://user-images.githubusercontent.com/62059002/95655757-67d7c980-0b01-11eb-9fb1-21362852cfad.jpg)

**Comment by janiceilene** [comment]
Thanks for letting us know @Ruth-ikegah!

**Comment by Ruth-ikegah** [comment]
Is there a way to solve this. I will love to take it up!

**Comment by Ruth-ikegah** [comment]
> Is there a way to solve this. I will love to take it up! @janiceilene

ohh i see someone has solved it!

**Comment by Ruth-ikegah** [comment]
I will close it then!
