### ISSUE TITLE
Clarify the `sender` property of the `CodeScanningEvent` webhook

### ISSUE THREAD

**Issue by wolfy1339** [github/docs#3906]
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#code_scanning_alert

### What part(s) of the article would you like to see updated?

The description of the `sender` property.

In the docs it says that the sender property is `github` for the `created`, `fixed`, `reopened`, `appeared_in_branch` actions.
But, what are the values for the sender property?
Currently the example uses the values from the [`GET /orgs/github` REST endpoint](https://api.github.com/orgs/github) while the other webhooks use similar values to the [`GET /user/github` REST endpoint](https://api.github.com/users/github)

### Additional information

I'm a contributor to [`octokit/webhooks`](https://github.com/octokit/webhooks), and a staffer sent a PR (octokit/webhooks#366) with some updates to the `CodeScanningAlert` event that were currently in progress.
The other day, we have another staffer send us [a PR](https://github.com/octokit/webhooks/pull/371) that doesn't match the `sender` field in the example payload in the docs and that uses values pulled from the [`GET /users/github`](https://api.github.com/users/github) enpoint.

My understanding of the docs right now is that the sender property is the user that triggered the event.
And for the actions `reopened`, `fixed`, `created`, `appeared_in_branch`, the user that triggered the event is `github`

ref: octokit/webhooks#379; octokit/webhooks#371

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @wolfy1339! I'll get this triaged for the team to take a look 👀

**Comment by wolfy1339** [comment]
This has been confirmed that this is an issue in #3855
