### ISSUE TITLE
👋🏻 Hi @daminebenq - thanks for taking the time to open this PR.

### ISSUE THREAD

**Issue by tonydeane666** [github/docs#3914]
👋🏻 Hi @daminebenq - thanks for taking the time to open this PR. 

You're right to say that GitHub now supports mp4 attachments. It was announced as a beta feature: https://github.blog/changelog/2020-12-16-video-upload-public-beta/ and https://github.blog/changelog/2021-02-01-expanded-support-for-video-uploads/.

It looks as if someone else has also opened a PR to update to this page. Since that PR also adds the limit on file sizes, I'm closing your PR in favor of: https://github.com/github/docs/pull/3571.

_Originally posted by @felicitymay in https://github.com/github/docs/issues/3710#issuecomment-783969278_

**Comment by ruksina25** [comment]
😊

**Comment by ruksina25** [comment]
♥️
