### ISSUE TITLE
Typo in Discussions GraphQL API docs

### ISSUE THREAD

**Issue by radekmie** [github/docs#3943]
### What article on docs.github.com is affected?

[Using the GraphQL API for Discussions](https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions#repositorydiscussion), added in 87699fd119211756b05dabfee535830af92d1082.

### What part(s) of the article would you like to see updated?

Right now it says:

> Get a discussion. Returns null if discussion with the specified ID **exists**.

While I believe it should say:

> Get a discussion. Returns null if discussion with the specified ID **does not exist**.

**Comment by janiceilene** [comment]
@radekmie Thank you so much for opening an issue 💖 You're right! That should say `Get a discussion. Returns null if discussion with the specified ID does not exist.` 

You or anyone else is welcome to open a PR to make that fix!
