### ISSUE TITLE
Device flow: clarify that responses are based on "Accept" header

### ISSUE THREAD

**Issue by gr2m** [github/docs#3944]
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/authorizing-oauth-apps

### What part(s) of the article would you like to see updated?

1. [`POST https://github.com/login/device/code` response section](https://docs.github.com/en/developers/apps/authorizing-oauth-apps#response-1)
2. [`POST https://github.com/login/oauth/access_token` response section](https://docs.github.com/en/developers/apps/authorizing-oauth-apps#response-2)

### Additional information

By default, all responses to `POST https://github.com/login/*` are a form query, as it is already documented for the [`POST https://github.com/login/oauth/access_token ` response](https://docs.github.com/en/developers/apps/authorizing-oauth-apps#response) of the OAuth web flow. All endpoints optionally accept the `Accept` header to be set to `application/json` or `application/xml` to alter the response type. The two sections for the device flow need to be updated to reflect that. They currently imply that the response is JSON by default, which is incorrect

**Comment by Alway7761820662** [comment]
1$>  What article on docs.github.com is affected?
2$>https://docs.github.com/en/developers/apps/authorized-oauth-apps.
3$>  What part(s) of the article would you like to see updated?
4$> 1. [`POST https://github.com/login/device/code` response section](https://docs.github.com/en/developers/apps/authorized-oauth-apps#response-1)
5$> 2. [`POST https://github.com/login/oauth/access_token` response section](https://docs.github.com/en/developers/apps/authorized-oauth-apps#response-2)
6$> Additional information.
7$> By default, all responses to `POST https://github.com/login/*` are a form query, as it is already documented for the [`POST https://github.com/login/oauth/access_token ` response].
8$(https://docs.github.com/en/developers/apps/authorized-oauth-apps#response) of the oauth web flow. All endpoints optionally accept the `Accept` header to be set to `application/json` or `application/` to alter the response type. The two sections for the device flow need to be updated to reflect that. They currently imply that the response is JSON by default, which is incorrect.

**Comment by Alway7761820662** [comment]
🙏🙏🙏☀️☀️

**Comment by gr2m** [comment]
fyi @github/docs I tried to report both contents above but got a "Not Found" error

<img width="327" alt="image" src="https://user-images.githubusercontent.com/39992/128970611-45c9340d-2207-4854-a408-113c952d1ff7.png">

**Comment by lucascosti** [comment]
Thanks heaps for reporting this @gr2m, and apologies for the delay in addressing this. 🙇‍♂️  PR opened to fix in https://github.com/github/docs/pull/10426
