### ISSUE TITLE
Give some advice or best practise around action arrangement

### ISSUE THREAD

**Issue by mambax** [github/docs#3953]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses

### What part(s) of the article would you like to see updated?

I asked [this question on SO](https://stackoverflow.com/questions/66107901/should-actions-be-stored-in-a-separate-repo-or-nested-in-another) and it turns out that not a single soul cared or dared to answer.

I (as a beginner back then) would really like to see some insight about the different options. Read my SO entry, I even tried to answer myself and still am not sure what is the best practice.

I would welcome it if the GH Team could shed some light on the topic like so:

He, these are the [options](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-versioned-actions) a, b, c. In practice, the most suitable approach for this is that because of this.
For local development we recommend LMO and after point X it makes sense to move it into P.

I mean it becomes only really relevant at a certain "size" so you want to start off right and not, in the end, adapt 20 actions and 200 workflows.

### Additional information

I would not hesitate to make a PR if I knew the answer to the best practice questions 🤣 🙊

**Comment by janiceilene** [comment]
👋 Thanks for opening an issue @mambax! I think our wonderful [support team](https://support.github.com/contact) would be the best folks to answer your question 💖 If you think the docs should be updated after that conversation, definitely let us know! Thank you!

**Comment by mambax** [comment]
@janiceilene it just got closed? 😭 Or is it my task to go to the support team?

**Comment by janiceilene** [comment]
👋 @mambax Yes, you should definitely chat with support and see what they have to say about best practices, they'll have the best answers! After that, if you have some thoughts on updates to the docs that would be helpful, feel free to come back and open an issue with that additional context 💛
