### ISSUE TITLE
Description of parameters are swapped for creating a scoped access tokens

### ISSUE THREAD

**Issue by stof** [github/docs#3961]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/apps#create-a-scoped-access-token--parameters

### What part(s) of the article would you like to see updated?

The descriptions for `repositories` and `repository_ids` are swapped, documenting `repository_ids` as expecting names.

### Additional information

![image](https://user-images.githubusercontent.com/439401/109008377-8ce26880-76ad-11eb-90ef-261275efdfe2.png)

**Comment by skedwards88** [comment]
Thank you for catching this error! 🕵️ ✨ The API docs are generated in a separate repo, so I will open an issue for this in that repo.

**Comment by skedwards88** [comment]
Thanks again for finding this! A fix is now live.

**Comment by stof** [comment]
@skedwards88 I know they are generated in a separate repo (the readme in the `content/rest` folder says it), but AFAIK, this separate repo is not public so that's why I opened the issue here.

**Comment by skedwards88** [comment]
@stof What you did (opening an issue here) was 100% correct! I wanted to keep you posted that a fix was made as a result of the issue that you opened.
