### ISSUE TITLE
Please update help document on using a PAT for git

### ISSUE THREAD

**Issue by plastikfan** [github/docs#3975]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token#using-a-token-on-the-command-line

### What part(s) of the article would you like to see updated?

Please see the ticket I raised about this:

https://support.github.com/ticket/personal/0/1033425

**Comment by janiceilene** [comment]
👋 @plastikfan Thanks so much for opening an issue! Since folks in this open source repo don't have access to see your support ticket, could you describe what it is you'd like to see updated in the docs? Thank you!

**Comment by plastikfan** [comment]
Sorry I made the assumption that you could see the ticket, because I can. Ive copied the text for you to see the issue:

Please can you update this article for essential required information regarding use of a personal access token to authenticate to git over https [Creating a personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).

Having created a new PAT, I had no idea what to do with it as this article doesnt explain. I found an equivalent article for using an ssh key and in that article you do say that to use the newly generated ssh key, you use ssh-add. We need equivalent information for PAT on https, for windows, linux and mac).

---
So to be clear, what is https/PAT equivalent of this page:

https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

In that page there is a section that says how to add an ssh key to the ssh agent.

We need the same for https/PAT.

You also need to explain the Windows Credential manager (and equivalent on mac/linux). If the user is not currently being prompted for credentials, it because the credential manager has this already cached and the user needs to know what to do with the credntial manager in order to be re-prompted.

**Comment by janiceilene** [comment]
Thanks for the clarification @plastikfan! If you've got a suggestion that will work for all Windows users out of the box, you're welcome to open a pull request to make the fix. Thank you!

**Comment by plastikfan** [comment]
reply, I havent got the time to do a pull request. I searched for an official windows explanation of the windows credential manager, but the officiall link I found in MS documents was really quite deficient. I better explanation would be soemthime like:

https://www.digitalcitizen.life/credential-manager-where-windows-stores-passwords-other-login-details/
