### ISSUE TITLE
Grammar in education/apply for a student developer pack

### ISSUE THREAD

**Issue by fluteds** [github/docs#3997]
### What article on docs.github.com is affected?

[Education/apply for a student developer pack](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/apply-for-a-student-developer-pack).

### What part(s) of the article would you like to see updated?

Requirement for student pack bullet points. 

### Additional information

Small grammar errors but the bullet points do not end with full stops like other bullet points in the docs and look out of place. 
Opening a pull request now to fix this.

**Comment by shati-patel** [comment]
Related PR closed
