### ISSUE TITLE
Outdated SSO instructions

### ISSUE THREAD

**Issue by ChildishGiant** [github/docs#4139]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on
([Source](https://github.com/github/docs/blob/main/content/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on.md))

### What part(s) of the article would you like to see updated?

The "Enable SSO or Disable SSO" dropdown doesn't seem to exist any more.

**Comment by janiceilene** [comment]
👋 @ChildishGiant Our wonderful [support team](https://support.github.com/contact) team would be the best folks to explain what you're seeing! From there, if we need a docs update, feel free to open a new issue 💖
