### ISSUE TITLE
Apps authentication example sets `iat` to `now`

### ISSUE THREAD

**Issue by bitwiseman** [github/docs#4155]
### What is the current behavior?

content/developers/apps/authenticating-with-github-apps.md uses an example the sets `iat` to `now`.  This is fine if the client and server clocks are both synchronized to UTC perfectly.  In the somewhat common case that the client system is out of sync with UTC and is ahead of UTC, setting `iat` to `now` will result in an authentication error.  Users not aware of this potential issue will have difficulty tracking down the error. 

### What changes are you suggesting?

The example should set `iat` to some arbitrary time slightly in the past, 60 seconds ago for instance.   This will allow for some harmless clock drift from UTC without causing hard to diagnose errors.

**Comment by thomasvel863** [comment]
`"(http://robinhood.com)"`export private.command=server.command.config.update/*`[@config.new_server.admin.acess](http://robinhood.com)
