### ISSUE TITLE
Small rewording required to a sentence about the `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by hubwriter** [github/docs#4283]
Small change required to this file: content/actions/learn-github-actions/security-hardening-for-github-actions.md

<hr>

The following sentence in the section "Considering cross-repository access" in [this article](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#considering-cross-repository-access) is not clear. At first I thought there was a typo and I had to read it a couple of times before I realised what it meant:

> Users have specific permissions for each repository, so having the `GITHUB_TOKEN` for one repository grant access to another would impact the GitHub permission model if not implemented carefully.

Change this to:

> Users have specific permissions for each repository, so allowing the `GITHUB_TOKEN` for one repository to grant access to another would impact the GitHub permission model if not implemented carefully.

**Comment by MeetYourCreator** [comment]
Hi all,

I created a pull request for this issues. Please see PR # #4289.
Please ket me know if anything else is needed.

Thanks so much everyone!

**Comment by MeetYourCreator** [comment]
Thanks so much @janiceilene!
