### ISSUE TITLE
Clarify which point in each branch is compared in a pull request

### ISSUE THREAD

**Issue by megbird** [github/docs#430]
Some users are confused about the difference in the commits displayed shown on the compare page and what's shown in a PR.

We talk about what a compare page shows in "[About comparing branches in pull requests](https://help.github.com/articles/about-comparing-branches-in-pull-requests/);" we can add some simple to "[About pull requests](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#about-pull-requests)."

> Compare pages show a compare between the tip of the head ref and the current common ancestor (i.e. merge base) of the head and base ref. On the other hand, pull request pages show a compare between the tip of the head ref and the common ancestor of the head and base ref **at the time when the pull request was created**. In other words, the merge base used for the comparison might be different.

**Comment by Ruth-ikegah** [comment]
I want to take this up!
