### ISSUE TITLE
Add Slack to list of GitHub-created apps

### ISSUE THREAD

**Issue by megbird** [github/docs#432]
### Issue overview

As noted in a related issue:

> The one thing we could do for core docs is add the Slack app to the list of GitHub-created integrations in "[GitHub extensions and integrations](https://help.github.com/articles/github-extensions-and-integrations/)." 

Slack isn't on our list of GitHub-created apps in "[GitHub extensions and integrations](https://help.github.com/articles/github-extensions-and-integrations/)."

Let's add the Slack integration to the article and also 💅 existing content:
- Fix the formatting in the TOC
- ✂️ the repetitive "To streamline your workflow..." sentences under each header

The Slack app is already live so we can update the article anytime; because this is a small enhancement to existing content, I'm tracking this as a user-reported issue.

### Products affected by this issue

- [x] Dotcom
- [ ] GitHub Enterprise end user docs
- [ ] GitHub Enterprise admin docs
- [ ] Desktop

/cc @github/product-docs-core https://github.com/github/ecosystem-integrations/issues/147

**Comment by ParkourKarthik** [comment]
I would love to pick this up. I believe that I should wait for docs team review.

**Comment by janiceilene** [comment]
@ParkourKarthik Feel free to open a pull request and address this issue ✨ Thanks for contributing 🎉

**Comment by felicitymay** [comment]
@ParkourKarthik raised https://github.com/github/docs/pull/542 to fix this issue - thanks 😄

I've just merged the PR and the updated content is already public: [Project management tools](https://docs.github.com/en/free-pro-team@latest/github/customizing-your-github-workflow/github-extensions-and-integrations#project-management-tools). ✨
