### ISSUE TITLE
Incorrect code examples in SCIM APIs

### ISSUE THREAD

**Issue by otsu81** [github/docs#4374]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/scim#get-scim-provisioning-information-for-a-user

### What part(s) of the article would you like to see updated?

The syntax for the javascript code example is incorrect. SCIM requires arrays of attributes to be treated as individual JSON objects. Example:

```json

[
  {
    "subattribute1": "value1"
  },
  {
    "subattribute2": "value2"
  }
]
```

Currently, the examples given for
1. https://docs.github.com/en/rest/reference/scim#update-a-provisioned-organization-membership
2. https://docs.github.com/en/rest/reference/scim#provision-and-invite-a-scim-user 
... are not possible to run because the array of e-mail attributes is incorrectly formatted.

A correct javascript code example to provision and invite SCIM user would be:
```javascript
await octokit.request('POST /scim/v2/organizations/{org}/Users', {
  org: 'org',
  userName: 'userName',
  name: {
    givenName: 'givenName',
    familyName: 'familyName',
    formatted: 'formatted'
  },
  emails: [
   {
     'value': 'octocat@github.com'
   }
  ]
})
```

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @otsu81! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
@otsu81 Thank you for pointing out this error! This will need to be fixed internally, so I will close this issue and open an internal one to fix it.
