### ISSUE TITLE
2.22.5 GHES release notes - Clarify wording for auth redirect bug to indicate it is only for built-in auth

### ISSUE THREAD

**Issue by stacycarter** [github/docs#4385]
Hi 👋 

I would like to propose changing this in the 2.22.5 release notes:

> When signing in after attempting to visit a specific page, people were sent to the home page instead of their intended destination.

To this:

> When signing in with a local username and password (built-in authentication) after attempting to visit a specific page, the user was sent to the home page instead of their intended destination.

Thanks!

cc/ @oreoshake

**Comment by janiceilene** [comment]
Thanks for opening an issue @stacycarter! I've triaged this for the team to take a look 👀
