### ISSUE TITLE
Code Owners and Code Review Assignment warnings incorrect

### ISSUE THREAD

**Issue by micimize** [github/docs#4420]
### What article on docs.github.com is affected?

* [About code owners](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#about-code-owners)
* [Managing code review assignment for your team](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team#about-code-review-assignments)

### What part(s) of the article would you like to see updated?

Both [About code owners](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#about-code-owners) and [Managing code review assignment for your team](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team#about-code-review-assignments) have very explicit warnings about the mutual incompatibility of CODEOWNERS with review assignment. From the former:
> If a team has enabled code review assignments, the individual approvals won't satisfy the requirement for code owner approval in a protected branch. For more information, see "Managing code review assignment for your team."

From the latter:
> When code owners are automatically requested for review, the team is still removed and replaced with individuals. The individual approvals don't satisfy the requirement for code owner approval in a protected branch. For more information, see "About code owners."

Based on our internal testing, **this is no longer correct.** The team is not removed from the PR, and the round robin reviewer can approve the PR successfully. Additionally, if code review assignment is enabled and set not to notify the team, only the single reviewer will be requested as intended.

<details>
<summary> Branch protection settings </summary>

![image](https://user-images.githubusercontent.com/8343799/110523392-a9cc6200-80d7-11eb-940f-514b93a022e6.png)

</details>

<details>
<summary> Team Review Settings </summary>

![image](https://user-images.githubusercontent.com/8343799/110523423-b18c0680-80d7-11eb-9ad9-b9f984ec69f2.png)

<details>

**Comment by micimize** [comment]
There are other users for whom this would be a significant update – https://github.community/t/team-based-notifications-or-rework-codeowners-notification-system/1004/12

**Comment by micimize** [comment]
I have also confirmed that assigning a specific reviewer while opening the PR prevents the routing algorithm from assigning another user, which is another feature worth documenting.

**Comment by janiceilene** [comment]
@micimize Thanks for opening an issue and giving such great details of what you're seeing! I'll triage this for the team to take a look 👀

**Comment by micimize** [comment]
I've run another test and it seems that if a user in a team is specified before the team, they will be added, superseding round-robin assignment just like in my comment above. i.e: `README.md @memberofmyteam @org/myteam` will assign `@memberofmyteam` and not go through round robin. This also allows for a single user to be an "owner" but still have review requests fall through to the rest of the team when they are the PR opener.

Additionally, with a rule like `README.md @org/team @org/team-2`, reviews from only one team are necessary, meaning that reviews are required from _any_ code owner rather than _all_ specified codeowners. This is another Good Thing that is not clear in the docs.

Also, the warning in the docs is actually still  correct in the case where "Require review from Code Owners" is not checked (the team identifier is removed from the review).

**Comment by janiceilene** [comment]
👋 @micimize! I've chatted with some folks and it sounds like the best option would be to report the behavior your seeing to our wonderful [support team](https://support.github.com/contact)! If there are documentation updates that should be made after you chat with them, come back and let us know. Thanks so much!

**Comment by micimize** [comment]
Thanks @janiceilene – I have created a support ticket. I guess the idea is to have support verify the behavior, after which I'll comment here and we'll re-open and proceed?

**Comment by janiceilene** [comment]
That's exactly right @micimize! You can either open a new issue or comment here and we can reopen this issue ⚡ Thank you so much!

**Comment by micimize** [comment]
Ok – support has confirmed behavior and eng validated it is expected. There are also "a few feature requests actively being worked on that should make CODEOWNERS features more clear and helpful." So, I think it makes sense to re-open this ticket, and use it for the tracking ticket for the doc changes?

Thanks a ton!

<details>

<summary> Full quote from ticket
</summary>

> Thank you for your patience here. Our Engineering team has confirmed the behaviors you're experiencing is expected based on our current code, however, we acknowledge there are some details missing from our documentation on CODEOWNER functionality.
>
> There are a few feature requests actively being worked that should make CODEOWNERS features (and what is happening behind the scenes) more clear and helpful.
> 
> Keep an eye on the GitHub Blog for more details when new features related to CODEOWNERS is available.
> 
> You can reopen your Issue whenever you're ready. Thank you for reporting this!

</details>

**Comment by janiceilene** [comment]
@micimize Thanks so much for coming back and letting us know how that conversation went! You or anyone else are welcome to open a PR to update the language to match the current behavior 💖 

Any feature requests updates from the engineering team will come through to us internally, so we'll update those when they let us know what's coming down the pipeline ⚡

**Comment by micimize** [comment]
This is not done or stale, the warning is still present in the docs

**Comment by lecoursen** [comment]
Hi @micimize, sorry for the long delay here! Based on what you heard back from support, we can remove those warnings! You or anyone else is free to do that.

**Comment by jsoref** [comment]
This appears to have been resolved by 9311748452a1ebb7e961a34404d2620fa925f4c5

**Comment by micimize** [comment]
indeed it is
