### ISSUE TITLE
GITHUB_SHA is incorrectly documented or not functioning properly

### ISSUE THREAD

**Issue by actual-nh** [github/docs#4422]
### What article on docs.github.com is affected?

<https://docs.github.com/en/actions/reference/environment-variables>

And possibly: <https://docs.github.com/en/actions> (for a clearer issue link).

### What part(s) of the article would you like to see updated?

Either:

- It is incorrect about the GITHUB_SHA variable being (supposed to be) that of the commit, and fails to say what the proper environment variable is for the SHA hash of the commit; or
- The GITHUB_SHA environment variable is not being set correctly (and where to put in an issue for this is inadequately documented).

### Additional information

I am attempting to do a test seed that will be consistent across various CI tests, including different architectures at Github and between Github and Travis. The only variable identifiable to enable this is the SHA of the commit (treated as a hex number and modulo an appropriate number to keep it within the range of the seed variable). On Travis, this is working properly with the `TRAVIS_COMMIT` variable, as can be seen at <https://travis-ci.org/github/CleverRaven/Cataclysm-DDA/jobs/762182900#L1246>. However, using the GITHUB_SHA environment variable, it is not working for Github, as can be seen at <https://github.com/CleverRaven/Cataclysm-DDA/pull/47791/checks?check_run_id=2069095563#step:10:585> - compare to both the commit ID at the top of the page and the identical one used by Travis.

(The build script in use can be seen at <https://github.com/actual-nh/Cataclysm-DDA/blob/weariness_order/build-scripts/build.sh>, BTW.)

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @actual-nh! I think this would be best resolved by our wonderful [support team](https://support.github.com/contact) ✨ After you chat with them, if there are any docs updates needed, feel free to comment in this issue and let us know!

**Comment by actual-nh** [comment]
@janiceilene: None of the support team categories seem appropriate; which would you advise?

**Comment by janiceilene** [comment]
Hm, I'd try https://github.community/search?q=actions

**Comment by actual-nh** [comment]
@janiceilene: That's not the support team, sorry.

**Comment by janiceilene** [comment]
I'm sorry @actual-nh, I don't think I understood your question then. Could you clarify or add a screenshot?
