### ISSUE TITLE
Improve 'Managing a branch protection rule' docs around how to use fnmatch to match multiple branches (without using *)

### ISSUE THREAD

**Issue by 0xdevalias** [github/docs#4428]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule

### What part(s) of the article would you like to see updated?

The sections about `fnmatch` and how we can use that syntax, because `fnmatch` supports a LOT more flags/features than we are actually allowed to use.

Eg. see this StackOverflow of confusion and workarounds:

- https://stackoverflow.com/questions/53135414/how-to-apply-github-branch-rules-to-two-branches

### Additional information

While it's definitely out of scope of a docs request.. the ability to use more of the `fnmatch` features would be great; even if it was only the ability to specify 'OR' of patterns, that would make it infinitely easier to specify multiple matching branches in a readable/maintainable way:

- https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch
  - ![image](https://user-images.githubusercontent.com/753891/110570171-9db0d500-81a9-11eb-9a5d-911c01d87924.png)

**Comment by janiceilene** [comment]
👋 Thanks so much for opening an issue @0xdevalias! I think our wonderful [support team](https://support.github.com/contact) would be the best folks to clear up any confusion 💛 After chatting with them, please feel free to come back and let us know what updates you'd like to see!
