### ISSUE TITLE
GitHub Actions: add more details for "workflow_run" event

### ISSUE THREAD

**Issue by Morriz** [github/docs#4435]
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run

### What part(s) of the article would you like to see updated?

The properties that are exposed on `github.event.workflow_run`.

From examples on the web I have learned about the existence of 
`github.event.workflow_run.conclusion`
`github.event.workflow_run.head_branch`

And these are not documented. I expect there to be many more props available. Why don't you guys automate this process and offer generated reference documentation?

### Additional information

Another request exists for this which was closed: https://github.com/github/docs/issues/799

**Comment by katanakrypto** [comment]
Ehrlich gesagt kenne ich mich garnicht wirklich aus in dieser matetie-ich
wollte weder props noch leute kennenletnen-bin aber auf zufall auf etwas
gestossen was ich persöhnlich gut fande,und eben nur mich geäussert
dazu-ich habe dann zu hören bekommen das es niemanden meine meinung
interrissietrt und ich sie nicht áussern soll-und da wurde ich etwas sauer

Maurice Faber <notifications@github.com> schrieb am Mi., 10. März 2021,
15:12:

**Comment by janiceilene** [comment]
Thanks for opening an issue @Morriz! I'll triage this for the team to take a look 👀

**Comment by hubwriter** [comment]
@Morriz - Many thanks for raising this issue.

We've just (yesterday) updated the page (https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run) adding more details for the `workflow_run` event. 

PR: https://github.com/github/docs/pull/2767

I'm going to close this issue.
Thanks again.

**Comment by Morriz** [comment]
Really? After adding this little bit:

```
Many workflow_run keys, such as head_branch, conclusion, and pull_requests are the same as those in a check_suite object.
```

 you deem this issue closed?

**Comment by 3F51B5** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

https://github.com/behaviorbot/welcome/pull/19#issue-260303297

**Comment by Morriz** [comment]
Since this is a bigger issue of not having reference documentation on topics like this one I started another issue here: https://github.com/github/docs/issues/4612
