### ISSUE TITLE
Fix Zh-CN Translation content of list-keys-with-note.md

### ISSUE THREAD

**Issue by yin1999** [github/docs#4446]
### What article on docs.github.com is affected?

- [list-keys-with-note.md](https://github.com/github/docs/blob/main/translations/zh-CN/data/reusables/gpg/list-keys-with-note.md)

### What part(s) of the article would you like to see updated?

`gpg --list-secret-key--keyid-form LONG` is an error command, it should be `gpg --list-secret-key --keyid-form LONG`  
Adding a space after `--list-secret-key`

This [line](https://github.com/github/docs/blob/ebe6aa348221b3cb5218cbed1a4ea1d5698a662c/translations/zh-CN/data/reusables/gpg/list-keys-with-note.md#L2)

```diff   
-1. 使用 `gpg --list-secret-key--keyid-form LONG` 命令列出您拥有其公钥和私钥的 GPG 密钥。 签名提交或标记需要私钥。
+1. 使用 `gpg --list-secret-key --keyid-form LONG` 命令列出您拥有其公钥和私钥的 GPG 密钥。 签名提交或标记需要私钥。
  ```shell
  $ gpg --list-secret-keys --keyid-format LONG
```

### Additional information

The English Version of Doc [here](https://github.com/github/docs/blob/ebe6aa348221b3cb5218cbed1a4ea1d5698a662c/data/reusables/gpg/list-keys-with-note.md#L2).

```markdown
1. Use the `gpg --list-secret-keys --keyid-format LONG` command to list GPG keys for which you have both a public and private key. A private key is required for signing commits or tags.
```

**Comment by janiceilene** [comment]
Thanks for opening an issue and giving so much information to help us make this fix 💖 I've reported this internally!
