### ISSUE TITLE
Change in text fragment.

### ISSUE THREAD

**Issue by yair-rodriguez** [github/docs#448]
### What article on docs.github.com is affected?
[https://github.com/github/docs/blob/main/translations/es-XL/content/github/developing-online-with-codespaces/about-codespaces.md](url)

### What part(s) of the article would you like to see updated?
![image](https://user-images.githubusercontent.com/18104175/95769892-2d476b80-0c7e-11eb-803a-66c1f1c99a3d.png)

### Additional information
The fragment of text "cad acodespace" needs to be changed to "cada codespace".

**Comment by janiceilene** [comment]
Thank you so much for opening an issue and PR for this fix @yair-rodriguez 💖 

Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

I'll open an issue internally for our translators to look at.
