### ISSUE TITLE
Page links to itself

### ISSUE THREAD

**Issue by SiddharthShyniben** [github/docs#4553]
### What article on docs.github.com is affected?

[About Apps](https://docs.github.com/en/developers/apps/about-apps)

### What part(s) of the article would you like to see updated?

In the second paragraph of the article about apps, there is a link which links to itself.

>... For information on choosing a type of app, see "[About Apps](https://docs.github.com/en/developers/apps/about-apps)
" and ... "

### Additional information

None

**Comment by janiceilene** [comment]
Good catch @SiddharthShyniben and thanks so much for opening an issue! The link to "About Apps" can be removed and we should update the title of the second linked article from "Differences between apps" to "Differences between GitHub Apps and OAuth Apps."

You or anyone else are welcome to open a PR for this fix ⚡

**Comment by SiddharthShyniben** [comment]
Yes. I'll see if I can change it. I'm a bit new to Git and GitHub, but I'll try

**Comment by lucalves** [comment]
Hello @SiddharthShyniben, I opened PR #4590 to fix this.

**Comment by SiddharthShyniben** [comment]
> Hello @SiddharthShyniben, I opened PR #4590 to fix this.

Great! You can close this once it's merged.
