### ISSUE TITLE
[REST API]: Duplicated "Required. Required. " in parameter description

### ISSUE THREAD

**Issue by gr2m** [github/docs#4579]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/apps#create-a-scoped-access-token

### What part(s) of the article would you like to see updated?

![image](https://user-images.githubusercontent.com/39992/111375067-122cbd80-865b-11eb-803e-32b860fad3d0.png)

**Comment by janiceilene** [comment]
Thanks so much for letting us know @gr2m!

Anyone is welcome to open a PR to remove the extra "Required" from the `access_token` row ✨

**Comment by gr2m** [comment]
I looked into the source of the page, but the description is not there. I assume that the `**Required.** ` needs to be removed from the OpenAPI description as the `token` parameter is marked as required by the schema, but I'm not 100% sure

![image](https://user-images.githubusercontent.com/39992/111393927-ec151680-8676-11eb-9efc-43c46f789a18.png)

**Comment by janiceilene** [comment]
Thanks @gr2m! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
Thank you for bringing this to our attention! We will need to fix this internally, so I will close this issue out and open an internal issue.
