### ISSUE TITLE
Undocumented path parameter in Repo Commits API

### ISSUE THREAD

**Issue by stackptr** [github/docs#4580]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/repos#commits

### What part(s) of the article would you like to see updated?

In the reference page for [Repositories](https://docs.github.com/en/rest/reference/repos) there is a [List Commits](https://docs.github.com/en/rest/reference/repos#list-commits) section that shows how to retrieve some set of commits based on the supplied parameters:

```
GET /repos/{owner}/{repo}/commits
```

However, this seems to also accept a `commit_sha` path parameter to retrieve a single commit in the repository, in the form:

```
GET /repos/{owner}/{repo}/commits/{commit_sha}
```

If this is intentionally supported as part of the API, I suggest that it is either documented via the `Parameters` table....

| Name | Type | In | Description |
| --- | --- | --- | --- |
| `commit_sha` | string | path | Retrieve a single commit matching the given commit SHA.

... or, alternatively, document it in an adjacent section in the reference page.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @stackptr! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
Thanks for pointing this out! This needs to be fixed internally, so I will close this issue and open an internal one.
