### ISSUE TITLE
Improvements to text of webhooks articles (small changes)

### ISSUE THREAD

**Issue by hubwriter** [github/docs#4625]
### What article on docs.github.com is affected?

* https://docs.github.com/en/developers/webhooks-and-events/about-webhooks
* https://docs.github.com/en/actions/reference/events-that-trigger-workflows

### What part(s) of the article would you like to see updated?

Three small improvements it would be good to make:

1
In the "Events" section here:
https://docs.github.com/en/developers/webhooks-and-events/about-webhooks#events
file: content/developers/webhooks-and-events/about-webhooks.md

Change the last sentence from:
```
See "Webhook event payloads" for the list of available webhook events and their payloads.
```
to:
```
For a complete list of available webhook events and their payloads, see "[Webhook events and payloads](/developers/webhooks-and-events/webhook-events-and-payloads)."
```

<hr>

In the "Webhook events" section here:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#webhook-events
file: content/actions/reference/events-that-trigger-workflows.md

2
In the first paragraph, change:
```
when webhook events are created
```
to:
```
when webhook events are generated
```

3
After the existing first paragraph (i.e. before the "check_run" subsection) add a new paragraph:
```
Not all webhooks events trigger workflows. For the complete list of available webhook events and their payloads, see "[Webhook events and payloads](/developers/webhooks-and-events/webhook-events-and-payloads)." 
```

**Comment by Vivek-Hotti** [comment]
I'm working on this.

**Comment by Vivek-Hotti** [comment]
@hubwriter , please see my PR #4629

**Comment by Nawaz-Malik143** [comment]
i work very hard

**Comment by hubwriter** [comment]
Reviewed and approved. Thanks @Vivek-Hotti. This issue will be closed when we get the PR merged.
