### ISSUE TITLE
Confusing parameter description in REST API docs for /users

### ISSUE THREAD

**Issue by abhijit-hota** [github/docs#472]
### What is the current behavior?
I was browsing through the [REST API docs for Users](https://docs.github.com/en/free-pro-team@latest/rest/reference/users) and I couldn't quite get [this piece of description](https://docs.github.com/en/free-pro-team@latest/rest/reference/users#list-users--parameters) (bordered in orange):
![](https://user-images.githubusercontent.com/8116174/95584276-0e1cc400-0a5b-11eb-8765-2883a7d0ea5a.png)

### What changes are you suggesting?

I think the parameter description for `since` is confusing/wrong and should be corrected.

### Additional information
Opened a discussion [here](https://github.com/github/docs/discussions/341) and came to know that it was an issue.
Edit: As @felicitymay described [here](https://github.com/github/docs/discussions/341#discussioncomment-96013), the type pf `since` might also be wrong.

**Comment by abhijit-hota** [comment]
Thanks!

> The `since` parameter should be an `integer` and it should say something like, "The ID of the user where you want to begin the list of users."

Yep. Got it. My two cents:

The word `since` is used in context of time and that's the reason I did not doubt the timestamp type.  
But, the input is an ID. So IMO, it should be something like `from` or `fromID` to avoid confusion. (I'm not suggesting the change to the docs team but to the API developers although changing the API may break some applications that use this param. 😅)

> but we will report back here when its fixed!

Great!

**Comment by skedwards88** [comment]
https://github.com/github/docs-content/issues/3116 will address this as well as the other places where the `since` parameter is mis-documented. I am closing this issue to avoid duplication. Thank you for bringing it to our attention!

>The word since is used in context of time and that's the reason I did not doubt the timestamp type.
>But, the input is an ID. So IMO, it should be something like from or fromID to avoid confusion. (I'm not suggesting the change to the docs team but to the API developers although changing the API may break some applications that use this param. 😅)

Great suggestion! I I have [created an issue](https://github.com/github/ecosystem-api/issues/2148) for the API team.
