### ISSUE TITLE
Incorrect data type of the check_run_id

### ISSUE THREAD

**Issue by k-a-il** [github/docs#4720]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/checks#get-a-check-run

### What part(s) of the article would you like to see updated?

Data type of the `check_run_id` parameter has to be `long` instead of `integer`. 

### Additional information

My example: the check run id of [this check run](https://github.com/github/docs/pull/4716/checks?check_run_id=2165604353) is `2165604353` which is `long`.

**Comment by janiceilene** [comment]
Thanks for opening an issue @k-a-il! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
Thanks for starting a conversation about this! GitHub uses the OpenAPI schema to describe its REST API. In OpenAPI, `integer` includes `long` (https://swagger.io/docs/specification/data-models/data-types/).
