### ISSUE TITLE
Stray space

### ISSUE THREAD

**Issue by alisonjo315** [github/docs#473]
### What article on docs.github.com is affected?
[About comparing branches in pull requests](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-comparing-branches-in-pull-requests)

### What part(s) of the article would you like to see updated?
The stray space is in the last sentence of the [Three-dot and two-dot Git diff comparisons](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons) section, in the link inside quotes:
> For more information about Git commands to compare changes, see "[Git diff options ](https://git-scm.com/docs/git-diff#git-diff-emgitdiffemltoptionsgtltcommitgtltcommitgt--ltpathgt82308203)" from the Pro Git book site.

### Additional information
Screenshot (because, the way the text happened to wrap on my screen is the only reason I noticed the stray space):

![image](https://user-images.githubusercontent.com/2660348/95835382-249d7680-0d0c-11eb-885d-77043b390663.png)

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @alisonjo315!

**Comment by Simran-B** [comment]
Speaking of which... I noted that there's usually no space between the code fence start and the highlighting language in `` ```bash ``, but sometimes there is (`` ``` bash ``, ~600 vs
 ~100 occurrences).

I guess it doesn't make a difference here, but some markdown parsers are picky and the [markup reference](https://github.com/github/docs/blob/main/contributing/content-markup-reference.md#usage-1) page gives an example without space.

Is that something that should be unified?

**Comment by janiceilene** [comment]
@Simran-B I'm not sure whether that's something that should be consolidated or not 🤔 If you want to opening an engineering issue about it, the docs engineering team can weigh in!
