### ISSUE TITLE
Using correct blog url for `pull_request_target`

### ISSUE THREAD

**Issue by flaxel** [github/docs#4756]
### What article on docs.github.com is affected?

[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)

### What part(s) of the article would you like to see updated?

url for the blog article does not work

### Additional information

This is the current message:

<img width="779" alt="Bildschirmfoto 2021-03-23 um 12 21 49" src="https://user-images.githubusercontent.com/19373153/112138939-68a57900-8bd2-11eb-950a-078a83fffd4a.png">

**Comment by LEBATRUNG** [comment]
Tkanhs
