### ISSUE TITLE
Github Actions context variables data format not precise

### ISSUE THREAD

**Issue by tillepille** [github/docs#476]
### What article on docs.github.com is affected?

<https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions>

### What part(s) of the article would you like to see updated?

Be more precise about the data format on `github.ref` like on <https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables>

I thought I could use it as a tag for a docker build but this does not work. 

### Additional information

[PR](https://github.com/github/docs/pull/400) already opened

**Comment by janiceilene** [comment]
Thank you for opening an issue @tillepille!
