### ISSUE TITLE
Provide instructions for how to allow non admins to see dependabot security alerts

### ISSUE THREAD

**Issue by jsoref** [github/docs#4760]
### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/supply-chain-security/viewing-and-updating-vulnerable-dependencies-in-your-repository

### What part(s) of the article would you like to see updated?

`Viewing and updating vulnerable dependencies`

Doesn't explain how a non admin can view security alerts, it appears to assume that everyone is an admin of all repositories.

There is no documentation for an admin explaining how to let non admins see the security alerts.

This leads to two problems:
1. Admins see alerts and don't understand why others can't see them
2. Others get urls that don't work and don't understand what to do

### Additional information

The current public facing information for this is here:
https://github.community/t/cant-see-the-access-to-alerts-for-dependabot-settings/157526

It does not include pictures, it isn't maintained, and it is not discoverable.

---

### Content design plan

1. Change to the [Viewing and updating vulnerable dependencies in your repository](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/viewing-and-updating-vulnerable-dependencies-in-your-repository) article:

    - In the metadata at the top of the file, update the `permissions` statement. It should mention users with explicit access to security alerts.

2. Change to the reusable that defines step 3 of the procedure.
    - After the text, before the `{% ifversion ftp %}` condition, add a brief sentence explaining that if the option is missing, they should ask for access to security alerts. Then add a "For more information..." link to [Managing security and analysis settings for your repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-security-and-analysis-settings-for-your-repository#granting-access-to-security-alerts)

**Comment by janiceilene** [comment]
👋 @jsoref Thanks for opening an issue. I think the information you're looking for is in a different article https://docs.github.com/en/github/administering-a-repository/managing-security-and-analysis-settings-for-your-repository#granting-access-to-security-alerts. Does that look right?

**Comment by jsoref** [comment]
Yes, but that's not the flow we have.

A user is told to look at a security report and then gets stuck trying to find it. They're going to look at this page which does not appear to link to that page.

(Plus notes that the ux is inconsistent with all the other admin lists, but, that's just a bug.)

**Comment by janiceilene** [comment]
Thanks for further explaining what you're hoping to see! I'll get the PR associated with this issue up for review.

**Comment by felicitymay** [comment]
@jsoref - thank you for raising this difficulty that users are having. It's particularly helpful to have the link to the community forum discussion for reference ✨ 

I agree that it's not currently obvious to a user why they can't see alerts when they navigate to the **Security** tab. I'm going to add a content design plan to the issue summary to make the existing information for repository owners easier to find.
