### ISSUE TITLE
ada yoplayalım ben gönlümü verdim aday

### ISSUE THREAD

**Issue by CuneytMutlu** [github/docs#4764]
ada yoplayalım ben gönlümü verdim aday

_Originally posted by @CuneytMutlu in https://github.com/github/docs/issues/4757#issuecomment-805113438_

**Comment by CuneytMutlu** [comment]
bugun kafam biraz dakgında kusura bakma kapatmak zorunda kaldım

**Comment by janiceilene** [comment]
This issue appears to be off topic and will be closed.
