### ISSUE TITLE
some eror for opening website

### ISSUE THREAD

**Issue by jambu7-mahi** [github/docs#4782]

**Comment by ajs256** [comment]
Hey there @jambu7-mahi!

Thanks for opening an issue. Could you please edit your initial comment and fill out the issue template so the team can know what the problem is?

> Please note that I am not affiliated with the GitHub docs team.

**Comment by janiceilene** [comment]
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!

**Comment by jambu7-mahi** [comment]
why this was invalid

**Comment by ajs256** [comment]
You didn't clarify what you meant by filling out the template. If this is still a problem, open another issue and fill out the template.
