### ISSUE TITLE
Spelling mistake on github/using-git/ignoring-files

### ISSUE THREAD

**Issue by edwardASavage** [github/docs#4789]
https://docs.github.com/en/github/using-git/ignoring-files 

Under the section "Further Reading":
the second list item ".gitignore in the **man** pages for Git"
should be  ".gitignore in the **main** pages for Git".

**Comment by ajs256** [comment]
See #3898, this is not a typo.

**Comment by edwardASavage** [comment]
A man page is short form for manual page, which would be the second time someone has attempted to correct this. The possible mistake of adding the "i" leaves it ambiguous to either "main" or the true "manual".

Should this not be expanded to "manual" at the very least?

**Comment by janiceilene** [comment]
Thanks for pointing out this duplication @ajs256! It's called a man page because `man` is the command from unix, so unfortunately we can't change it to "manual" either @edwardASavage 💛
