### ISSUE TITLE
renaming-an-organization.md should contain info about just changing character case (e.g. github.com/Org to github.com/org)

### ISSUE THREAD

**Issue by peterdd** [github/docs#4794]
### What article on docs.github.com is affected?

https://github.com/github/docs/edit/main/content/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization.md

https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization

### What part(s) of the article would you like to see updated?

I hoped to get information about side effects if I just rename the case of an organisation, e.g. github.com/Org to github.com/org

Does it can have side effects on any project/issue/git stuff or people working with repositories?

**Comment by janiceilene** [comment]
👋 @peterdd Our wonderful [support team](https://support.github.com/contact) would be the best folks to answer that question! If you feel like there's a specific section of the docs that could use an update after you chat with them, please feel free to come back and let us know 💛

**Comment by peterdd** [comment]
I think adding a hint or section in that document would be really helpful as this is a question every organisation on github.com has to answer itself. Should I name the path /Org or /org or kann I change the case anytime without side effects.

**Comment by janiceilene** [comment]
> Should I name the path /Org or /org or can I change the case anytime without side effects.

I'm not sure of the answer to that question. If you check in with the [support team](https://support.github.com/contact) to get an answer, then come back and open a new issue (or comment in this one!) we can absolutely consider adding some clarifying information ✨
