### ISSUE TITLE
Missing github actions default environment variable

### ISSUE THREAD

**Issue by tonyhallett** [github/docs#4819]
### What is the current behavior?

[Page](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables) is missing GITHUB_JOB
The equivalent context is on this [page](https://github.com/github/docs/blob/main/content/actions/reference/context-and-expression-syntax-for-github-actions.md)

### What changes are you suggesting?

Add the missing variable.
You can see it is present and public by looking at this [code](https://github.com/actions/toolkit/blob/4bf916289e5e32bb7d1bd7f21842c3afeab3b25a/packages/github/src/context.ts#L43)

**Comment by 1SatoshiNakamoto** [comment]
Hope merged
Sent from Yahoo Mail on Android

**Comment by 1SatoshiNakamoto** [comment]
Sent from Yahoo Mail on Android

**Comment by Abhishek577270** [comment]
Viva my serene

**Comment by 1SatoshiNakamoto** [comment]
https://linksharing.samsungcloud.com/ucRLqvHxx5OvValid until Apr 15, 2021Sent from my Galaxy

**Comment by 1SatoshiNakamoto** [comment]
Shared from Word for Androidhttps://office.com/getwordSent from my Galaxy

**Comment by 1SatoshiNakamoto** [comment]
Sent from my Galaxy
