### ISSUE TITLE
github actions Job status check functions - apply to jobs with needs as well as steps

### ISSUE THREAD

**Issue by tonyhallett** [github/docs#4821]
### What is the current behavior?

[Job status check functions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions) is not clear enough that these functions are equally valid for dependent jobs as well as steps.

### What changes are you suggesting?

( equally for failure )
change
```
success
Returns true when none of the previous steps have failed or been canceled.
```
to
```
success
Returns true when none of the previous steps have failed or been canceled. Also returns true when a dependent job or all dependent jobs are successful.
```

There should be an example of using in steps as well as withing a job with needs.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @tonyhallett! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
@tonyhallett I think what you are saying is technically true, but I am having trouble envisioning a situation where this is relevant. (i.e. if a dependent job fails, then the depending job is skipped, so it doesn't matter if `success()` evaluates.) Can you share an example?

**Comment by tonyhallett** [comment]
The example was just an example of changes.  

Perhaps success is not as important as failure as it is the default behaviour.  Nevertheless, it is true that the definition of success and the behaviour of it is the same for steps and dependent jobs.

> if a dependent job fails, then the depending job is skipped, so it doesn't matter if success() evaluates.

I would say that when a dependent job fails the depending job is skipped because of an implicit sucess is evaluated.
Of course this is not what you would do but this job can choose to do the following
```
...
not-success:
    runs-on: windows-2019
    needs: job-that-fails
    if: ${{!success()}}
    steps: 
      - name: dependent job failed
        run: echo "dependent job failed"
```

The point is these functions do apply to jobs as well as steps and that is apparent with always and cancelled but not for success and failure.

Please can you re-open this issue
https://github.com/github/docs/issues/4823#issuecomment-809610241

> Looking at the example in the issue that you linked, it seems that job_c was skipped because it needs job_b, which was skipped. I am going to close this issue, but feel free to re-open it if you disagree.

I understand the reason why the job was skipped but this is not due to the documentation being clear in this regard.  By looking at the workflow output you can see the implicit success() being ANDed with your condition.
The behaviour mentioned in https://github.com/actions/runner/issues/491#issuecomment-660122693

The op thinks that the documentation could be improved upon and I agree and that is why have linked to that issue.

**Comment by skedwards88** [comment]
It sounds to me like you're looking for us to document that `success()` and `failure()` apply to dependent jobs as well as steps. 

For failure, it seems reasonable to change the text to:
> Returns `true` when any previous step or dependent job of a job fails.

For success, I have trouble envisioning an example where this is useful to our users. If you can provide an example where using success in a dependent job is useful for more than simply documenting the inner workings of the machinery.

**Comment by tonyhallett** [comment]
> For success, I have trouble envisioning an example where this is useful to our users. If you can provide an example where using success in a dependent job is useful for more than simply documenting the inner workings of the machinery, that will help justify the same addition to the success() function.

It is useful in the same way that it is useful currently.  It is the definition of success that is used in the absence of another job status check function to determine if the job runs.
I have already given you an example that demonstrates that it can be used for jobs.  
`${{!success()}}` but if you would like another `if: ${{success() && someothercondition}}`.  If I wanted to be explicit that someothercondition being true does not guarantee that job runs.

Documenting the success function for dependent jobs is no different from documenting for steps - in both cases it is implicitly considered and using the success function is unnecessary aside from being explicit.

Please can you re-open this issue
#4823 (comment)

> Looking at the example in the issue that you linked, it seems that job_c was skipped because it needs job_b, which was skipped. I am going to close this issue, but feel free to re-open it if you disagree.
> 
> I understand the reason why the job was skipped but this is not due to the documentation being clear in this regard. By looking at the workflow output you can see the implicit success() being ANDed with your condition.
> The behaviour mentioned in actions/runner#491 (comment)
> 
> The op thinks that the documentation could be improved upon and I agree and that is why have linked to that issue.

**Comment by lee-dohm** [comment]
Thanks for the feedback.

First, let me state that the place to discuss https://github.com/github/docs/issues/4823 is in that issue.

With regard to this issue, as a general rule we don't document bugs. Since the behavior in https://github.com/actions/runner/issues/491 has been marked by the team maintaining actions/runner as a bug, we feel that creating official documentation of that behavior would unduly increase our maintenance burden. For this reason, I'm going to go ahead and close this issue.

Thanks for taking the time to explain the problem in detail and working with us to make the GitHub documentation better!
