### ISSUE TITLE
Improve context about forks

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4844]
### What article on docs.github.com is affected?

"[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)"

### What part(s) of the article would you like to see updated?

This is a getting started article, and it would be great to share the additional information we have about forks with the new users. Let's link to "[Working with forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks)" somewhere within the article.

### Additional information

This issue is for a special project and not currently available for contributors to work on.

**Comment by codewithdev** [comment]
I want to work on this particular issue.

**Comment by githubnew-pro** [comment]
> ### چه مقاله ای در docs.github.com تحت تأثیر قرار می گیرد؟
> " [چنگال یک repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) "
> 
> ### دوست دارید کدام قسمت از مقاله را به روز کنید؟
> این یک مقاله برای شروع است ، و بسیار خوب است که اطلاعات اضافی را که در مورد چنگال داریم با کاربران جدید به اشتراک بگذارید. بیایید به مقاله " [کار با چنگال](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks) " پیوند دهیم.
> 
> ### اطلاعات تکمیلی
> این شماره مربوط به یک پروژه خاص است و در حال حاضر برای مشارکت کنندگان در دسترس نیست.

O

**Comment by githubnew-pro** [comment]
> ### چه مقاله ای در docs.github.com تحت تأثیر قرار می گیرد؟
> " [چنگال یک repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) "
> 
> ### دوست دارید کدام قسمت از مقاله را به روز کنید؟
> این یک مقاله برای شروع است ، و بسیار خوب است که اطلاعات اضافی را که در مورد چنگال داریم با کاربران جدید به اشتراک بگذارید. بیایید به مقاله " [کار با چنگال](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks) " پیوند دهیم.
> 
> ### اطلاعات تکمیلی
> این شماره مربوط به یک پروژه خاص است و در حال حاضر برای مشارکت کنندگان در دسترس نیست.

**Comment by githubnew-pro** [comment]
> دوست دارم روی این موضوع خاص کار کنم. emilyistoofunky آیا باید این دو مقاله را در یک ادغام کنم؟

**Comment by emilyistoofunky** [comment]
Thanks @codewithdev! We'll keep these articles separate—"Fork a repo" is an article for new users in our getting started content, and "Working with forks" is a longer article meant for all users. Let's limit the scope of this issue to improving "Fork a repo" by linking to "Working with forks" and any other small changes you think would help new users understand forks better.

**Comment by codewithdev** [comment]
> Thanks @codewithdev! We'll keep these articles separate—"Fork a repo" is an article for new users in our getting started content, and "Working with forks" is a longer article meant for all users. Let's limit the scope of this issue to improving "Fork a repo" by linking to "Working with forks" and any other small changes you think would help new users understand forks better.

I got understand, thanks :)

**Comment by ethanpalm** [comment]
Closed by https://github.com/github/docs/pull/6614
