### ISSUE TITLE
Update article on the GitHub CLI

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4845]
### What article on docs.github.com is affected?

"[GitHub CLI](https://docs.github.com/en/github/getting-started-with-github/github-cli)"

### What part(s) of the article would you like to see updated?

- Improve the article intro to make it friendlier to new users and more useful for all readers
- In the “About GitHub CLI” section, make the list of features more general and evergreen, so it doesn’t become out of date when more features are shipped to the CLI. For example, before the list, change the wording to something like “The GitHub CLI includes features like…”

### Additional information

This issue is for a special project and not currently available for contributors to work on.

**Comment by eidn122** [comment]
JavaScript ( @ octokit / core.js )

**Comment by thepushkarp** [comment]
I'd like to work on this issue

**Comment by emilyistoofunky** [comment]
@thepushkarp Great, thanks! Feel free to open a PR and let us know if you have any questions. ⚡
