### ISSUE TITLE
Update the GitHub glossary article

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4846]
### What article on docs.github.com is affected?

"[GitHub glossary](https://docs.github.com/en/github/getting-started-with-github/github-glossary)"

### What part(s) of the article would you like to see updated?

- Improve the intro to make it friendlier to new users and use less awkward phrasing.
- Remove capitalization from these headers
  - check
  - code frequency graph
  - contributors graph
  - dashboard
  - dependents graph
  - dependencies graph (also change to “dependency graph”)
  - enterprise account
  - gist
  - management console
  - markup
  - members graph
  - network graph
  - news feed
  - pulse graph
  - punch graph
  - status checks
  - traffic graph
- Delete this entry
  - Works with GitHub

### Additional information

This issue is for a special project and not currently available for contributors to work on.

**Comment by codewithdev** [comment]
I would like to work on this Issue.

**Comment by emilyistoofunky** [comment]
Great, thanks @codewithdev!

**Comment by codewithdev** [comment]
@emilyistoofunky There are some other term such as "Commit graph"

> ### What article on docs.github.com is affected?
> "[GitHub glossary](https://docs.github.com/en/github/getting-started-with-github/github-glossary)"
> 
> ### What part(s) of the article would you like to see updated?
> * Improve the intro to make it friendlier to new users and use less awkward phrasing.
> * Remove capitalization from these headers
>   
>   * check
>   * code frequency graph
>   * contributors graph
>   * cashboard
>   * dependents graph
>   * dependencies graph (also change to “dependency graph”)
>   * enterprise account
>   * gist
>   * management console
>   * markup
>   * members graph
>   * network graph
>   * news feed
>   * pulse graph
>   * punch graph
>   * status checks
>   * traffic graph
> * Delete this entry
>   
>   * Works with GitHub
> 
> ### Additional information
> This issue is for a special project and not currently available for contributors to work on.

Hi @emilyistoofunky I didn't found the term "cashboard" in the Glossary .  🤔 Please review it.

**Comment by emilyistoofunky** [comment]
Ooh, looks like you caught a typo there @codewithdev! 😆 `dashboard` is definitely the right term to fix. I'll update the original post in the issue.

**Comment by codewithdev** [comment]
> Ooh, looks like you caught a typo there @codewithdev! 😆 `dashboard` is definitely the right term to fix. I'll update the original post in the issue.

Thanks for Improving! 👌

**Comment by codewithdev** [comment]
One More question, Updating the terms in the Glossaries would be fine, but I can see the GitHub Enterprise Server is updated to ver 3.1 However, it has been written that merging is not allowed to the `external.yml`.  Should I have to continue with the updation and create a PR or ignore the last Commit Comments?

**Comment by emilyistoofunky** [comment]
@codewithdev  The only file you'll need to update is https://github.com/github/docs/blob/main/content/github/getting-started-with-github/github-glossary.md. Other versions of the page will automatically update after your change is merged to https://github.com/github/docs/blob/main/content/github/getting-started-with-github/github-glossary.md. 👍🏻

**Comment by codewithdev** [comment]
@emilyistoofunky The File is not Opening. 🤔

**Comment by codewithdev** [comment]
@emilyistoofunky The file  https://github.com/github/docs/blob/main/content/github/getting-started-with-github/github-glossary.md is not opening.

**Comment by emilyistoofunky** [comment]
Ah sorry @codewithdev! We shipped an update to change paths in earlier today but I also think I misunderstood your question. 

Looking at https://github.com/github/docs/blob/main/data/glossaries/external.yml, the message `[DO NOT MERGE] GitHub Enterprise Server 3.1 release candidate megabranch` is the commit message for the latest commit to the file. You can go ahead and make the changes there without problems. 👍🏻

**Comment by codewithdev** [comment]
> Ah sorry @codewithdev! We shipped an update to change paths in earlier today but I also think I misunderstood your question.
> 
> Looking at https://github.com/github/docs/blob/main/data/glossaries/external.yml, the message `[DO NOT MERGE] GitHub Enterprise Server 3.1 release candidate megabranch` is the commit message for the latest commit to the file. You can go ahead and make the changes there without problems. 👍🏻

Thank You for the clarification. I will proceed with the updation in the file.
