### ISSUE TITLE
Update the Git cheatsheet article

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4847]
### What article on docs.github.com is affected?

"[Git cheatsheet](https://docs.github.com/en/github/getting-started-with-github/git-cheatsheet)"

### What part(s) of the article would you like to see updated?

- Add an intro
- Update the phrasing in the second sentence to be less awkward
- Update third sentence because several cheatsheets are now available in multiple languages

### Additional information
This issue is for a special project and not currently available for contributors to work on.

**Comment by xBugs-dot** [comment]
@555 cat 679015

**Comment by xBugs-dot** [comment]
@bugsFlwo

**Comment by xBugs-dot** [comment]
> @bugsFlwo

Flow

**Comment by ShreyaPrasad1209** [comment]
I would like to work on this issue

**Comment by emilyistoofunky** [comment]
@ShreyaPrasad1209 Great question! The intro actually goes in [frontmatter](https://github.com/github/docs/tree/main/content#intro) and that will control its location. Thanks for picking this up! ⚡

**Comment by ShreyaPrasad1209** [comment]
Oh that's great! I have another doubt. In the issue description you'll see this change needed - **_Update third sentence because several cheatsheets are now available in multiple languages_** But I can already see that this change has been made in the Git cheatsheet web page. Can you clarify what exactly you're looking for here?

**Comment by ShreyaPrasad1209** [comment]
Also, I noticed that in the third line, "Using Git" uses double quotes, which makes it a bit awkward. I feel that this line can be rephrased. Please let me know your thoughts on this.

**Comment by janiceilene** [comment]
> I can already see that this change has been made in the Git cheatsheet web page.

It could have been updated since this issue was created! We'll take a look in the PR 💖
