### ISSUE TITLE
Update quickstart footers in getting started category

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4849]
### What article on docs.github.com is affected?

- [ ] "[Set up Git](https://docs.github.com/en/github/getting-started-with-github/set-up-git)"
- [ ] "[Create a repo](https://docs.github.com/en/github/getting-started-with-github/create-a-repo)
- [ ] "[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)"
- [ ] "[Be social](https://docs.github.com/en/github/getting-started-with-github/be-social)"

### What part(s) of the article would you like to see updated?

**Problem:** Each article in the Quickstart map topic (https://docs.github.com/en/github/getting-started-with-github/quickstart) has a footer that links to each article in the category. These footers are inconsistently formatted and their purpose is unclear. A new user may think they have to go through these articles in a prescribed order or be confused that each footer asks “What do you want to do next?” when they do not know what they want to do.
- The footer also links to https://github.community/ and implies that it’s a social hangout area of the site, this should be updated

**Solution:** 
- Create a content design plan [using this template](https://github.com/github/docs-content/blob/main/contributions/open-source-content-design-template.md) and post it in this issue.
- Update the footer to give the quickstart audience a better understanding of what to click next. 
- Remove incorrect/outdated information.

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by codewithdev** [comment]
Would like to work on this.

**Comment by janiceilene** [comment]
Thanks @codewithdev 🎉

**Comment by codewithdev** [comment]
Just curious 🤔 about the Content Design Template before working on this particular issue. I found that the link mentioned in the Issue (https://github.com/github/docs-content/blob/main/contributions/open-source-content-design-template.md) is not working.

**Comment by Ti6** [comment]
Real pictures in phone number please hola world

**Comment by janiceilene** [comment]
Whoops, sorry about that broken link @codewithdev! Here's the template:

```
We use a content design process to create project plans that clearly communicate user needs and product goals, and outline how documentation for a specific project will meet both. Creating a project plan also ensures that we aren't duplicating any content or efforts, and that the right places are updated.

## Content plan

Briefly summarize the problem and its impact on GitHub's users, or describe the new content and the problem it solves for customers.
- What's the goal of documentation for this project?
- What will customers need from docs to be successful?

### Audiences

Describe the groups of people who will be using these docs.

### Documentation plan

Create a detailed list of the articles to create or update. Tip: Make sure to consider audit log and permissions content.

### Questions

If you have any questions after writing a plan, ask them here!
```

**Comment by codewithdev** [comment]
## Content Plan 
The Footer created for each Map topic in the Quickstart articles is inconsistently formatted. Generally, the user may find the footer articles as another category of topics that is already present in the given article or they will get confused what they should do next.
However, Structuring the footer in such a way that each linked content would help users to explore more about GitHub and its product. It should be consistent from the user's perspective and must focus on what information users can expect from the article.


## Audiences
For New users, QuickStart topics may sound insightful and quite informative. They can use it to set up Git, fork a repo, and find more information on how they can collaborate with others.

## Documentation Plan

Here is the set of changes that I prefer to frame the footers in Map topics.
  - Footers in [Set up Git](https://docs.github.com/en/github/getting-started-with-github/quickstart/set-up-git) may contain information about [Creating a Repo](https://docs.github.com/en/github/getting-started-with-github/quickstart/create-a-repo) or alternatively, user can [Fork a Repository](https://docs.github.com/en/github/getting-started-with-github/quickstart/fork-a-repo) to contribute or understand the codebase of projects.
  - [Create a Repo](https://docs.github.com/en/github/getting-started-with-github/quickstart/create-a-repo) demonstrate how repositories are created. Another way to create a repository that enables the user to contribute locally from the computer is to  [Clone a Repo](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository).
  - Summarizing how users can [Connect with people](https://docs.github.com/en/github/getting-started-with-github/quickstart/be-social) and collaborating with others.  
  - Summarizing how [GitHub Community Support](https://github.community/) can be a great platform to discuss and get the help of others.

**Comment by janiceilene** [comment]
👏 Congrats on your first content design @codewithdev! I'll triage this for review :zap:

**Comment by felicitymay** [comment]
Hi @codewithdev - thanks for writing a content design plan for this issue and for your pull request to update the docs accordingly 💖 

As you have already raised a pull request with your changes based on this plan, I'm going to go and review the pull request instead of the plan. 👀 

----

General background, for future reference.

The aim of writing a content design plan is to explain the changes that you plan to make to the docs. This allows you to talk through the changes before you edit the docs. That way we can ensure that you don't waste time making changes that we can't accept. Usually, you would not start to edit the docs until your plan has been approved. 

We've only recently started asking OS contributors if they'd like to design content changes, so the expected workflow might not be clear in our contributing docs. I'll ask our OS contributors team to take a look at this.

**Comment by codewithdev** [comment]
> Hi @codewithdev - thanks for writing a content design plan for this issue and for your pull request to update the docs accordingly 💖
> 
> As you have already raised a pull request with your changes based on this plan, I'm going to go and review the pull request instead of the plan. 👀

> The aim of writing a content design plan is to explain the changes that you plan to make to the docs. This allows you to talk through the changes before you edit the docs. That way we can ensure that you don't waste time making changes that we can't accept. Usually, you would not start to edit the docs until your plan has been approved.


@felicitymay Thanks for the clarification ✨. I'll make sure to wait first until my content design plan gets approved.
