### ISSUE TITLE
Write or improve intros for getting started map topics

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4850]
### What article on docs.github.com is affected?

- [ ] "[Quickstart](https://docs.github.com/en/github/getting-started-with-github/quickstart)"
- [ ] "[Learning about GitHub](https://docs.github.com/en/github/getting-started-with-github/learning-about-github)"
- [ ] "[Signing up for GitHub](https://docs.github.com/en/github/getting-started-with-github/signing-up-for-github)"
- [ ] "[Using GitHub](https://docs.github.com/en/github/getting-started-with-github/using-github)"
- [ ] "[Exploring projects on GitHub](https://docs.github.com/en/github/getting-started-with-github/exploring-projects-on-github)"
- [ ] "[Getting started with Git](https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git)"
- [ ] "[Using Git](https://docs.github.com/en/github/getting-started-with-github/using-git)"

### What part(s) of the article would you like to see updated?

These map topics (pages that group articles) either don't have intros or have intros that could be improved to be friendlier to our audience of new users. Here are some guidelines on writing good intros.

> Intros are displayed in search results and provide contextual information to help readers choose a result. Within a page, intros allow readers to quickly decide if the category, map topic, or article is relevant to them.
>
> Map topic and category intros should be one sentence long, and general and high-level enough to scale with future changes without needing to be frequently updated. Avoid lists of features or article content, and focus on the more evergreen overall task the category or map topic describes.

### Additional information
This issue is for a special project and is not currently available for contributors to work on.

**Comment by codewithdev** [comment]
I would like to work on this issue. :)

**Comment by emilyistoofunky** [comment]
Thanks @codewithdev! ⚡
