### ISSUE TITLE
Provide context on cloning for new users

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4851]
### What article on docs.github.com is affected?

"[Create a repo](https://docs.github.com/en/github/getting-started-with-github/create-a-repo)"

### What part(s) of the article would you like to see updated?

We got feedback in our helpfulness survey that this article should explain what it means to clone a repo to one's computer. While the article doesn't focus on what happens after creating a repo on GitHub, we can include a link to our "[About repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-repositories)" article to give more context, and to "[Cloning a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository)" for next steps.

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by Modusto253** [comment]
https://api.blockchair.com/dashboards/{:btc_chain}/{:height},...,{:height}[] https://api.bockchair.com/{:dashboards/{:hash},...,{:hash}[]

**Comment by Modusto253** [comment]
https://api.blockchair.com/bitcoin

https://api.blockchair.com/bitcoin cash

https://api.blockchair.com/ethereum

https://api.blockchair.com/litecoin

https://api.blockchair.com/bitcoin-sv

https://api.blockchair.com/dogecoin

https://api.blockchair.com/dash

https://api.blockchair.com/ripple

https://api.blockchair.com/groestlcoin

https://api.blockchair.com/stellar

https://api.blockchair.com/monero

https://api.blockchair.com/cardano

https://api.blockchair.com/zcash

https://api.blockchair.com/mixin

https://api.blockchair.com/tezos

https://api.blockchair.com/eos

https://api.blockchair.com/bitcoin-abc

https://api.blockchair.com/bitcoin/omni

https://api.blockchair.com/ethereum/erc-20/stats

https://api.blockchair.com/stats

https://api.blockchair.com/{:btc_chain}/stats

https://api.blockchair.com/{:eth_chain}/stats

https://api.blockchair.com/{:xrp}/stats

https://api.blockchair.com/{:xlm}/stats

https://api.blockchair.com/{:xmr}/stats

https://api.blockchair.com/{:ada}/stats

https://api.blockchair.com/{:xin}/stats

https://api.blockchair.com/{:xtz}/stats

https://api.blockchair.com/{:eos}/stats

https://api.blockchair.com/{:btc_chain}/dashboards/block/{:height}[]

https://api.blockchair.com/{:btc_chain}/dashboards/blocks/{:hash}/[],...,{:height}[]

https://api.blockchair.com/{:btc_chain}/dashboards/blocks/{:hash}[],...,{:hash}[] 

https://api.blockchair.com/{:btc_chain}/raw/block/{:height}[]

https://api.blockchair.com/{:btc_chain}/raw/block/{:hash}[]

https://api.blockchair.com/{:btc_chain}/blocks?{:query}

https://api.blockchair.com/{:eth_chain}/dashboards/block{:height}[],...,{:height}[]

https://api.blockchair.com/{:eth_chain}/dashboards/blocks/{:hash}[],...,{:hash}][

https://api.blockchair.com/{:eth_chain}/raw/block/{:hash}][

https://api.blockchair.com/{:eth_chain}/blocks?{:query}

https://api.blockchair.com/{:xrp_chain}/raw/ledger/{:height}[]

https://api.blockchair.com/{:xrp_chain}/raw/ledger/{:hash}[]

https://api.blockchair.com/{:xlm_chain}/raw/ledger/{:height}[]

https://api.blockchair.com/{:xlm_chain}/raw/ledger/{:height}[]

https://api.blockchair.com/{:xmr_chain}/raw/block/{:height}[]

https://api.blockchair.com/{:xmr_chain}/raw/block/{:hash}[]

https://api.blockchair.com/{:ada}/raw/block/height/[]

https://api.blockchair.com/{:ada_chain}/raw/block/{:hash}[]

https://api.blockchair.com/{:xin_chain}/raw/snapshot/{:height}

https://api.blockchair.com/{:xin_chain}/raw/snapshot?{:query}

https://api.blockchair.com/{:xtz_chain}/raw/block/{:hash}[]

https://api.blockchair.com/{:xtz_chain}/raw/block{:query}

https://api.blockchair.com/{:eos_chain}/raw/block{:height}[]

https://api.blockchair.com/{:btc_chain}/dashboards/transaction/{:hash}[]

https://api.blockchair.com/{:btc_chain}/dashboards/transactions/{:hash}[],...,{hash}[]

https://api.blockchair.com/{:btc_chain/raw/transaction/{:hash}[]

https://api.blockchair.com/{:btc_chain}/phsh/transaction(post)

https://api.blockchair.com/{:btc_chain}/transaction?{:query}

https://api.blockchair.com/{:btc_chain}/mempool/transaction?{:query}

https://api.blockchair.com/{:eth_chain}/dashboards/transaction/{:hash}[],...{:hash}[]

https://api.blockchair.com/{:eth_chain}/raw/transaction/{:hash}[]

https://api.blockchair.com/{:eth_chain}/push/transaction(post)

https://api.blockchair.com/{:eth_chain}/transaction?{:query}

https://api.blockchair.com/{:eth_chain}/mempool/transaction?{:query}

https://api.blockchair.com/{:xrp_chain}/raw/transaction/{:hash}[]

https://api.blockchair.com/{:xlm_chain}/raw/transaction/{:hash}

https://api.blockchair.com/{:xmr_chain}/raw/transaction/{:hash}[]

https://api.blockchair.com/{:ada_chain}/raw/transaction/{:hash}[]

https://api.blockchair.com/{:xin_chain}/raw/transaction/{:hash}

https://api.blockchair.com/{:xin_chain}/push/transaction/(post)

https://api.blockchair.com/{:xtz_chain}/raw/operation/{:hash}[]

https://api.blockchair.com/{:eos_chain}/raw/transaction/{:hash}[]

https://api.blockchair.com/{:eos_chain}/raw/transaction/{:block_height},{:hash}

https://api.blockchair.com/{:btc_chain}/dashboards/address/{:address}[]

https://api.blockchair.com/{:btc_chain}/dashboards/adress/{:address}[],...,{:address}ฯ

https://api.blockchair.com/{:btc_chain}/dashboards/address/{:address}[]

https://api.blockchair.com/{:btc_chain}/addresses/balances(post mass balance check)

https://api.blockchair.com/{:btc_chain}/dashboards/xpub/{:extended_key}

https://api.blockchair.com/{:btc_chain}/addresses?{:query}

https://api.blockchair.com/{:eth_chain}/dashboards/address/{:address}[]

https://api.blockchair.com/{:xrp_chain}/raw/account/{:address}[]

https://api.blockchair.com/{:xlm_chain}/raw/account/{:address}[]

https://api.blockchair.com/{:ada_chain}/raw/address/{:addresses}[]

https://api.blockchair.com/{:xtz_chain}/raw/account/{:address}[]

https://api.blockchair.com/{:eos_chain}/raw/account/{:addresse}[]/multi/dashboards/addresses/{:address}[],...,{:address}[]

https://api.blockchair.com/{:btc_chain}/outputs?{query}

https://api.blockchair.com/{:btc_chain}/mempool/outputs?{:query}

https://api.blockchair.com/{:eth_chain}/dashboards/uncle/{:hash}[]

https://api.blockchair.com/{:eth_chain}/dashboards/uncles/{:hash}[],...,{:hash}[]

https://api.blockchair.com/{:eth_chain}/uncle?{:query}

https://api.blockchair.com/{:eth_chain}/calls?{:query}

https://api.blockchair.com/{:xmr_chain}/outputs?{:query}

https://api.blockchair.com/{zcash_chain}/raw/validate?paymentdisclosure=zpd:...

https://api.blockchair.com/{:xin_chain}/raw/round/{:hash}/round/{:hash}

https://api.blockchair.com/{:xin_chain}/raw/node/{:hash}

https://api.blockchair.com/{:xin_chain}/raw/graph

https://api.blockchair.com/{:xin_chain}/raw/mintings?{:query}

https://api.blockchair.com/{:xin_chain}/raw/nodes?{:query}

https://ali.blkvkchair.com/bitcoin/omni/stats

https://api.blockchair.com/bitcoin/omni/dashboards/property/{:property_id}

https://api.blockchair.com/bitcoin/omni/propertys

https://api.blockchair.com/ethereum/erc-20/{:token_address}/stats

https://api.blockchair.com/ethereum/erc-20/{:token}

**Comment by ShreyaPrasad1209** [comment]
I would like to work on this issue

**Comment by janiceilene** [comment]
@ShreyaPrasad1209 It looks like you're assigned to a few other issues. I'm going to leave this one unassigned for now to let everyone have an opportunity to pick up a `bite sized` issue 💛

**Comment by Modusto253** [comment]
Help me with my bitcoins can you

**Comment by ShreyaPrasad1209** [comment]
Hi @janiceilene, I have completed my last 2 issues and now would like to work on this issue 😊

**Comment by janiceilene** [comment]
That sounds great @ShreyaPrasad1209 🎉 I've assigned it to you.

**Comment by ShreyaPrasad1209** [comment]
@janiceilene @emilyistoofunky can you specify the position in the webpage where you want the context?

**Comment by Modusto253** [comment]
What's up can I gets some advice here

**Comment by Modusto253** [comment]
Ready to learn some stuff here lady's is there any to show me wasssup

**Comment by Modusto253** [comment]
> ### What article on docs.github.com is affected?
> 
> "[Create a repo](https://docs.github.com/en/github/getting-started-with-github/create-a-repo)"
> 
> ### What part(s) of the article would you like to see updated?
> 
> We got feedback in our helpfulness survey that this article should explain what it means to clone a repo to one's computer. While the article doesn't focus on what happens after creating a repo on GitHub, we can include a link to our "[About repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-repositories)" article to give more context, and to "[Cloning a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository)" for next steps.
> 
> ### Additional information
> 
> This issue is for a special project and is not currently available for contributors to work on.
> 

Can we work with me here what is the next thing I should do here

**Comment by emilyistoofunky** [comment]
> can you specify the position in the webpage where you want the context?

@ShreyaPrasad1209 Sure! 

> we can include a link to our "About repositories" article to give more context, 

Let's add a sentence under the "Create a repository" header to link to "About repositories." Our style guide has information on how to format links [here](https://github.com/github/docs-internal/blob/main/contributing/content-style-guide.md#links).

> and to "Cloning a repository" for next steps.

We can add this link under the "Celebrate" header. 👍🏻

**Comment by ShreyaPrasad1209** [comment]
> > can you specify the position in the webpage where you want the context?
> 
> @ShreyaPrasad1209 Sure!
> 
> > we can include a link to our "About repositories" article to give more context,
>
> Let's add a sentence under the "Create a repository" header to link to "About repositories." Our style guide has information on how to format links [here](https://github.com/github/docs-internal/blob/main/contributing/content-style-guide.md#links).
> >This link is showing 404, did you mean [featuresLinks](https://github.com/github/docs-internal/blob/main/contributing/content-style-guide.md) frontmatter?
>
> > and to "Cloning a repository" for next steps.
> 
> We can add this link under the "Celebrate" header. 👍🏻
>> Sounds great! 👍🏻

**Comment by emilyistoofunky** [comment]
Oops sorry about that @ShreyaPrasad1209. Here's a correct link: https://github.com/github/docs/blob/main/contributing/content-style-guide.md#links.
