### ISSUE TITLE
Add headers to quickstart articles

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4852]
### What article on docs.github.com is affected?

- "[Set up Git](https://docs.github.com/en/github/getting-started-with-github/set-up-git)"
  - New header: Using Git
- "[Create a repo](https://docs.github.com/en/github/getting-started-with-github/create-a-repo)"
  - New header: Create a repository
- "[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)"
  - New header: About forks (add right before 

### What part(s) of the article would you like to see updated?

There's not currently a header above the initial information in the articles, so the information isn't represented or linkable in the article's table of contents. Add H3 headers to the beginning of the articles (see suggested header titles above).

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by Anita-ihuman** [comment]
I will like to take on this issue

**Comment by emilyistoofunky** [comment]
Hi @Anita-ihuman! Thanks so much for your offer. This issue is part of a special project and isn't available to be assigned to you, but we'd love for you to find another issue to work on!

Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions or check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label to find another issue to take on. :sparkles:

**Comment by Terrica12** [comment]
> I will like to take on this issue

**Comment by down4some1** [comment]
.docx.lovehasno.beaconscan.levit

**Comment by iiqrah** [comment]
Heya, I'd like to take this issue. I am a GitHub Campus Expert.

**Comment by emilyistoofunky** [comment]
Great, thanks @iiqrah! Let us know if you have any questions as you work on your PR.

**Comment by down4some1** [comment]
im sorry, but if i talk to my wife, you can have a random image, i will still always be ment to her. if monogamic features are a problem, im out. dont ask but smile that its over.

**Comment by down4some1** [comment]
github.exe/offfeature

**Comment by aitemour79** [comment]
***@***.*** com
