### ISSUE TITLE
Update "Saving repositories with stars"

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4854]
### What article on docs.github.com is affected?

"[Saving repositories with stars](https://docs.github.com/en/github/getting-started-with-github/saving-repositories-with-stars)"
This issue was written/reported by @ethanpalm. ✨ 

### What part(s) of the article would you like to see updated?

The article "[Saving repositories with stars](https://docs.github.com/en/github/getting-started-with-github/saving-repositories-with-stars)" does not follow our current style guide for procedural articles. The procedural sections "Searching stars" and "Sorting and filtering stars" should be rewritten with procedural steps. To learn how we write procedural steps, see the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#procedural-steps). We can also remove the outdated "Browsing your friends' stars" section.

Audiences: New GitHub users and anyone who hasn't used stars. 

#### Content to update

- [ ] Rewrite "Searching stars" and "Sorting and filtering stars" as procedural steps
  - [ ] Follow the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#procedural-steps)
  - [ ] Add new images if needed
- [ ] Remove "Browsing your friends' stars" section

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by gitkit13** [comment]
steps:
  - uses: actions/checkout@main
  - uses: codecov/codecov-action@v5
    with:
      fail_ci_if_error: true # optional (default = false)
      files: ./coverage1.xml,./coverage2.xml # optional
      flags: unittests # optional
      name: codecov-umbrella # optional
      token: ${{ secrets.CODECOV_TOKEN }}
      verbose: true # optional (default = false)
