### ISSUE TITLE
Update "Following people" article, part one

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4855]
This issue was reported/written by @ethanpalm. ✨ 

### What article on docs.github.com is affected?

"[Following people](https://docs.github.com/en/github/getting-started-with-github/following-people)"

### What part(s) of the article would you like to see updated?

The article "[Following people](https://docs.github.com/en/github/getting-started-with-github/following-people)" doesn't follow our current [content style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md) and is missing information. This article can be improved by adding an "About followers on GitHub" section, rewriting the existing content for following someone as procedural steps in new sections, and adding a new section "Viewing followed users and followers."

Audience: New users of the followers features on GitHub.

### Content to update

"[Following people](https://docs.github.com/en/github/getting-started-with-github/following-people)"
- [x] Add "About followers on GitHub" section
  - [x] Include the existing information "When you follow people, you'll see their public activity in the activity view of your news feed. If someone you follow stars a public repository, GitHub may recommend the repository to you in the discovery view of your news feed."
  - [x] Add information about where and how to find people new users may want to follow
- [ ] Add "Viewing followed users and followers"
  - [ ] Write procedural steps for viewing all users that someone is following
  - [ ] Write procedural steps for viewing someone's followers
  - [ ] Include screenshots for the procedurals

For more information on writing procedural steps, see the [content style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#procedural-steps).

### Additional information
This issue is for a special project and is not currently available for contributors to work on.

Companion issue: https://github.com/github/docs/issues/4855

**Comment by thepushkarp** [comment]
Hello, can I take this issue?

**Comment by emilyistoofunky** [comment]
Sure thing @thepushkarp, thanks! ⚡

**Comment by thepushkarp** [comment]
@emilyistoofunky I'm sorry for taking so long. This completely went off my mind.

I've added the changes as described above. Can you please take a look?
