### ISSUE TITLE
Update "Finding ways to contribute to open source on GitHub"

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4857]
### What article on docs.github.com is affected?

"[Finding ways to contribute to open source on GitHub](https://docs.github.com/en/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github)"

### What part(s) of the article would you like to see updated?

- [ ] Remove this section, which isn’t helpful for the new user audience: https://docs.github.com/en/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github#open-source-projects-with-mirrors-on-github 
- [ ] Add any context to the rest of the article that you think would be helpful

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by ShreyaPrasad1209** [comment]
I would like to work on this issue

**Comment by emilyistoofunky** [comment]
Great, thank you @ShreyaPrasad1209! Let us know if you have any questions as you work on your PR.

**Comment by Jlk20** [comment]
I as well

**Comment by ShreyaPrasad1209** [comment]
@emilyistoofunky you can close this issue as my PR has been merged!✨
