### ISSUE TITLE
Explain disposable email services

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#4858]
### What article on docs.github.com is affected?

"[Verifying your email address](https://docs.github.com/en/github/getting-started-with-github/verifying-your-email-address)"

### What part(s) of the article would you like to see updated?

We received some helpfulness survey feedback that we should define what a disposable domain is in the warning box.

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by lee-dohm** [comment]
The wording currently is:

> You cannot verify email addresses from disposable domains.

If I'm understanding the warning correctly, I feel like "disposable domains" is something of a misnomer here. It's not the domain that's disposable, it's the email address. So maybe a rewording to something like "disposable email services" would be more clear and not require a protracted explanation?

**Comment by guaxy94** [comment]
Hellow, what do i have to do, can someone guide me or Take My seat

**Comment by Fradulentus** [comment]
Одноразовый профиль это часть общих проблем и пробелом современности.Данный проект участвует в поддержке нашей чистоты нашего интернета.
Прошу продолжить обсуждение данной темы.

**Comment by Fradulentus** [comment]
> Одноразовый профиль это часть общих проблем и пробелом всей единный цифровой современности.
> Прошу продолжить обсуждение данной темы.

**Comment by Ala619** [comment]
في الجمعة، ٢٦ مارس ٢٠٢١ ١١:١٩ م Emily Gould ***@***.***> كتب:

**Comment by kindavishal** [comment]
Hey! I'd like to work on this!

**Comment by janiceilene** [comment]
@kindavishal I've assigned you to the issue!
