### ISSUE TITLE
Current topic not shown

### ISSUE THREAD

**Issue by harshcut** [github/docs#4922]
### What article on docs.github.com is affected?

"[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)"

### What part(s) of the article would you like to see updated?

The topic list doesn't show the current topic in bold.

[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)

![image](https://user-images.githubusercontent.com/66206863/112985490-e131aa00-917d-11eb-8a18-816333d49fe0.png)

### Additional information

These current topics can be seen in bold on [Set up Git](https://docs.github.com/en/github/getting-started-with-github/set-up-git), [Create a repo](https://docs.github.com/en/github/getting-started-with-github/create-a-repo) or [Be social](https://docs.github.com/en/github/getting-started-with-github/be-social).

![image](https://user-images.githubusercontent.com/66206863/112986034-9d8b7000-917e-11eb-9aa8-3e0a2566cc36.png)

**Comment by milkly1235** [comment]
Use
