### ISSUE TITLE
[/rest/reference/pulls] Add GitHub CLI examples to all 'Code samples' sections

### ISSUE THREAD

**Issue by 0xdevalias** [github/docs#4972]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/pulls

### What part(s) of the article would you like to see updated?

There are a number of 'Code samples' sections for each of the various endpoints. Eg.

- https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request--code-samples

There are multiple examples in each of these code sections, generally seeming to be:

- Shell
- JavaScript (@octokit/core.js)

Given the release and push of the GitHub CLI tool, and how quick/easy it makes it to interact with GitHub's APIs, it would be awesome if we were able to get GitHub CLI examples added to each of the 'Code samples' sections.

eg. for https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request--code-samples

- Ref: https://cli.github.com/manual/gh_api

```bash
gh api /repos/:owner/:repo/pulls/{pull_number}/comments \
  -H "Accept: application/vnd.github.v3+json" \
  --field 'body=body'
```

---

Ideally this would be across the entire docs site for every example, but it would also be fine to just start with this one page (and potentially progressively update other pages over time)

Looking at the source of this page it seems like it is built up from various other 'data sources' using liquid templates:

- https://github.com/github/docs/blob/main/content/rest/reference/pulls.md

eg.
```
{% for operation in currentRestOperations %}
  {% if operation.subcategory == 'comments' %}{% include rest_operation %}{% endif %}
{% endfor %}
```

I'm not familiar enough with how the docs site works to know where `currentRestOperations` is defined/comes from, and searching for it in the repo just seemed to show up usages in various `content/*` and `translations/*` files, not the 'source' of it.

My assumption is that this 'data set' would likely contain the information used to create the code samples (assuming they are generated), or at least the data for the examples (if they are manual). If so, this request may be more in line with a "Improve the docs.github.com site" request rather than a "Improve existing docs" request.

### Additional information

Screenshot of current 'Code samples' section:

- https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request--code-samples
  - ![image](https://user-images.githubusercontent.com/753891/113218325-0da70c80-92cb-11eb-99d7-d2d1de10ade5.png)

**Comment by janiceilene** [comment]
Thanks @0xdevalias! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
Great suggestion @0xdevalias! I'm a big fan of the GitHub cli as well 😄 We are actually working on this internally, so I will share your post with that project. 💖 

The REST API documentation is generated from a separate repo, so I will close this issue out since an open source contributor can't work on this.

**Comment by 0xdevalias** [comment]
Cool, thanks for the info :) Can’t wait to see the updates flow through from that project! :)
