### ISSUE TITLE
"Creating a personal access token" has a malformed link

### ISSUE THREAD

**Issue by ericmartinezr** [github/docs#5033]
This may be a duplicate, but I don't even know how to search for a duplicate of this issue.

### What article on docs.github.com is affected?

https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

### What part(s) of the article would you like to see updated?

```
9. To use your token to authenticate to an organization that uses SAML SSO, 
[authorize the token for use with a SAML single-sign-on organization](/articles/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on
```

This section should contain a link and not just text.

### Additional information

An image of how it looks right now

![image](https://user-images.githubusercontent.com/13039652/113493648-b0bc7980-94b7-11eb-87af-84ae6b81b94b.png)

Thank you

**Comment by janiceilene** [comment]
Thanks so much for opening an issue to let us know about that @ericmartinezr! You (or anyone else) are welcome to open a PR to fix that link ⚡ While we're fixing it, let's update the link to the new url structure (anything with `/articles` is old). This should be the updated link: `https://docs.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on`.
