### ISSUE TITLE
Github new system

### ISSUE THREAD

**Issue by Br0wJamEs** [github/docs#5036]

**Comment by Br0wJamEs** [comment]
New update system

**Comment by Tloco959** [comment]
None! I made a bad mistake getting on this site in the first place.
My phone is so screwed up now.
Anyway you can help me out? My internet Browser was Google,  but it seem
like this Github site has really messed up things like my email, My apps.
I believe that my phone is infected with a virus or something?
I don't know alot about computers and how they work!
Can you please help me? Get off this Site GITHUB!
