### ISSUE TITLE
Hard reset ios

### ISSUE THREAD

**Issue by Calnimptewa2** [github/docs#5038]
A configuration change would be something outside of our code that we change with our production environment, such as environment variables, virtual machine tier or quantity, or service providers.

- _Primary person_:
- _Second person_:
- _When_:
- _Zoom URL_:

### If an issue happens, how do we roll back?

Once the change is verified good, please close this issue.

**Comment by Deepiestwound** [comment]
> `[open http://localhost:3000]() `
