### ISSUE TITLE
export all or some of the docs to pdf to read offline

### ISSUE THREAD

**Issue by aCSAficia064** [github/docs#5123]
### What is the current behavior?
no option to export to pdf for certain docs or all docs. no ability to export for people with high latency or want to read offline except for
1 (on mobile) tapping the three vertical dots on the top right corner of the browser
2 then tapping the down arrow that has a platform under it
3 repeat for every page you want to download
1 (on desktop) At the top right, click the three vertical dots on the top right
2 and then click More Tools 
3 and then click Save page as.
4 Choose where you want to save the page.
5 Click Save
6 repeat for any additional page you want to read offline

### What changes are you suggesting?
making an option to export the entire or sections of the ghdocs site to paper (meaning to print it), pdf, epub (as an archive zip file), and more

the docs should be changed somewhat to reflect on people who have high network latency, just want to read offline, or any other reason that someone or some organization or some company may have

### Additional information
i can't think of any additional information except that some sites already can export the documentation onto other platforms/offline/any other use
(please don't worry about my comments) i personally also like having the ability to download documentation because i think it is more convenient
and it would be a lot easier to just "export to pdf or ..." (with options below)

**Comment by aCSAficia064** [comment]
thanks for all the help, it has been really appreciated

**Comment by aCSAficia064** [comment]
are you looking into the new feature @chiedo i just want an update

**Comment by chiedo** [comment]
Hi @aCSAficia064, @myarb will be in touch with an update as soon as she has the chance! Thanks for your patience and sorry for the delay.

**Comment by myarb** [comment]
👋🏼 @aCSAficia064 thanks for opening this issue and sharing your suggestion! This is currently possible in our existing UI by clicking the _Print this article_ icon (see screenshots below), which then allows you to open the page in a PDF. 

![docs-to-pdf](https://user-images.githubusercontent.com/11952755/114201423-298e5c00-9924-11eb-8ce3-ae9fa3017f29.gif)

I hope that helps! If so, please feel free to close this issue out as completed ✨ We appreciate your passion for GitHub docs 🎉

**Comment by aCSAficia064** [comment]
i was thinking of along with the print button, you could just directly download a pdf of the page

**Comment by aCSAficia064** [comment]
like what if the print to pdf feature on some devices or just completely disabled
theyd have to turn that feature back on and then print to pdf
this doesn't mean that i've had any problems where disabling that was the best i could do
i'm just saying it would be a lot easier to have pdf files of the docs downloadable alongside the print option

**Comment by aCSAficia064** [comment]
thanks
