### ISSUE TITLE
Update images on the "Transferring a repository" page

### ISSUE THREAD

**Issue by cjbraun** [github/docs#5134]
### What article on docs.github.com is affected?
[Transferring a repository](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)

### What part(s) of the article would you like to see updated?
The screenshots in steps 5 and 6 of [Transferring a repository owned by your user account](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) and steps 6 and 7 of [Transferring a repository owned by your organization](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-organization) are outdated.

### Additional information

**This is the image from the docs:**
<img width="449" alt="Screen Shot 2021-04-07 at 8 15 44 AM" src="https://docs.github.com/assets/images/help/repository/repo-transfer-free-plan-warnings.png">

**This is what it actually looks like:**
<img width="449" alt="Screen Shot 2021-04-07 at 8 15 44 AM" src="https://user-images.githubusercontent.com/55156127/113865752-51819200-9761-11eb-822c-f3dc2b3a4541.png">

**Comment by janiceilene** [comment]
@cjbraun Thanks so much for opening an issue to let us know about the images! You're (or anyone else is) welcome to open a PR to replace the existing image files with new ones. It looks like the steps are in this reusable https://raw.githubusercontent.com/github/docs/main/data/reusables/repositories/transfer-repository-steps.md, which shows that the images that need to be replaced are in: 
  - https://github.com/github/docs/blob/main/assets/images/help/repository/repo-transfer-free-plan-warnings.png 
  - https://github.com/github/docs/blob/main/assets/images/help/repository/repo-transfer-complete.png.

**Comment by lucalves** [comment]
Hello @cjbraun, how are you? I worked to resolve this in PR #5243. Let's wait for a review! :)
