### ISSUE TITLE
Do `installation` and `installation_repository` payloads have the property `installation` 100% of the times?

### ISSUE THREAD

**Issue by dominguezcelada** [github/docs#516]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads

### What part(s) of the article would you like to see updated?

* https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#installation

* https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#installation_repositories

### Additional information

https://github.com/github/docs/blob/d51685810027d8071e54237bbfd1a9fb7971941d/content/developers/webhooks-and-events/webhook-events-and-payloads.md#L446-L448

and 

https://github.com/github/docs/blob/20fa34e57c100da8662917ef682f98587a5761db/content/developers/webhooks-and-events/webhook-events-and-payloads.md#L470-L472

Checking the description of `installation` property, it denotes it could exist or not:

https://github.com/github/docs/blob/d51685810027d8071e54237bbfd1a9fb7971941d/data/reusables/webhooks/app_desc.md#L1

but due to the nature of the events, it should always have `installation` property right?

---

### Context:

`@octokit/webhook-definition` [is working](https://github.com/octokit/webhooks/pull/195) to improve typing of installation property in Payloads so it becomes an optional property (when necessary)

**Comment by lucascosti** [comment]
👋 @dominguezcelada To answer your question:

> Do `installation` and `installation_repository` payloads have the property `installation` 100% of the times?

The `installation` property is used in many webhooks, and has this description: 

> The GitHub App installation. Webhook payloads contain the installation property when the event is configured for and sent to a GitHub App.

This means that if the event for the webhook involves a GitHub App, it will contain the `installation` property.

Because the webhooks `installation` and `installation_repository` _always_ relate to a GitHub App, they will contain the property 100% of the time.

Comparing it other webhooks, such as [`repository`](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#repository),  the payload will only contain the `installation` property if the event for the webhook is configured for and sent to a GitHub App. 

I hope this makes sense! 🙂

**Comment by dominguezcelada** [comment]
> 👋 @dominguezcelada To answer your question:
> 
> > Do `installation` and `installation_repository` payloads have the property `installation` 100% of the times?
> 
> The `installation` property is used in many webhooks, and has this description:
> 
> > The GitHub App installation. Webhook payloads contain the installation property when the event is configured for and sent to a GitHub App.
> 
> This means that if the event for the webhook involves a GitHub App, it will contain the `installation` property.
> 
> Because the webhooks `installation` and `installation_repository` _always_ relate to a GitHub App, they will contain the property 100% of the time.
> 
> Comparing it other webhooks, such as [`repository`](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#repository), the payload will only contain the `installation` property if the event for the webhook is configured for and sent to a GitHub App.
> 
> I hope this makes sense! 🙂

Has totally sense @lucascosti . Thanks for the clear explanation 💪🏽 

I was thinking... would have sense to improve a little bit the way is expressed so, in case of webhooks like `installation` and `installation_repository` where the property appears 100% of the times to rewrite it from:

```
The {% data variables.product.prodname_github_app %} installation. Webhook payloads contain the `installation` property when the event is configured for and sent to a {% data variables.product.prodname_github_app %}. 
```

to

```
The {% data variables.product.prodname_github_app %} installation. 
```

only for this kind of events.

---

Do you think it could have sense this improvement?

Thanks for your time!

**Comment by lucascosti** [comment]
> to
> 
> ```
> The {% data variables.product.prodname_github_app %} installation. 
> ```
> 
> only for this kind of events.

@dominguezcelada 👍  I think that makes sense. For those endpoints, we could remove the `{% data reusables.webhooks.app_desc %}` variable and just add a normal table row with that simple description. Feel free to reopen this issue and submit a PR to the docs 🙂

**Comment by dominguezcelada** [comment]
> > to
> > ```
> > The {% data variables.product.prodname_github_app %} installation. 
> > ```
> > 
> > 
> > only for this kind of events.
> 
> @dominguezcelada 👍 I think that makes sense. For those endpoints, we could remove the `{% data reusables.webhooks.app_desc %}` reusable and just add a normal table row with that simple description. Feel free to reopen this issue and submit a PR to the docs 🙂

Cool! I will be happy to open a PR for this.

Should I create a new issue linking to this one? Seems I'm not able to re-open the issue myself.

Thanks @lucascosti

**Comment by lucascosti** [comment]
> Seems I'm not able to re-open the issue myself.

My bad, I forgot that external contributors can't reopen 😊 . Reopened for you 🚀

**Comment by lucascosti** [comment]
👋 @Kerruba! This docs repository is not the best place to troubleshoot product issues not directly related to the documentation. Better places to get help would be the [GitHub Support Community](https://github.community/) forums, or [contacting GitHub Support](https://support.github.com/contact). 🙂

**Comment by Pongsuk11** [comment]
Thank you very much I learned to play. I do not understand the language of use.

ดาวน์โหลด Outlook for iOS<https://aka.ms/o0ukef>
________________________________
จาก: Janice <notifications@github.com>
ส่ง: Wednesday, November 4, 2020 6:38:15 AM
ถึง: github/docs <docs@noreply.github.com>
สำเนาถึง: Subscribed <subscribed@noreply.github.com>
ชื่อเรื่อง: Re: [github/docs] Do `installation` and `installation_repository` payloads have the property `installation` 100% of the times? (#516)


Closed #516<https://github.com/github/docs/issues/516>.

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by dominguezcelada** [comment]
@lucascosti I ended up opening a PR for this after a long time! Would it be possible to re-open this issue? I think it was closed by mistake or by its inactivity

https://github.com/github/docs/pull/1948
