### ISSUE TITLE
Clarify Gist API limit

### ISSUE THREAD

**Issue by thdoan** [github/docs#5163]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/gists#truncation
https://docs.github.com/en/rest/reference/gists#list-public-gists

### What part(s) of the article would you like to see updated?

Under #truncation:
_"In addition to a specific file's contents being truncated, the entire files list may be truncated if the total number exceeds 300 files."_

Under #list-public-gists:
_"Note: With pagination, you can fetch up to 3000 gists."_

Can you please clarify whether we can retrieve up to 3000 private gists using pagination?

**Comment by janiceilene** [comment]
👋 @thdoan Thank so much for opening an issue! That question would be best answered by our wonderful [support team](https://support.github.com/contact) 💛 After chatting with them, if you think there's a docs update that should be made, feel free to come back and open a new issue. Thanks!
