### ISSUE TITLE
Mention how to escape ":" in searches

### ISSUE THREAD

**Issue by jidanni** [github/docs#5178]
https://github.com/github/docs/blob/main/content/github/searching-for-information-on-github/understanding-the-search-syntax.md does not mentions how to escape ":".

For instance no matter if one uses
- https://github.com/tats/w3m/search?q=http%3A
- https://github.com/tats/w3m/search?q=%22http%3A%22

all still include plain "http" with no colon following it in the results.

The user wants to search for the string "http:" and wants the ":" to simply be part of the string and not be treated magically, alas the secret to achieve such a feat is not documented. 

It perhaps boils down to

> Some non-alphanumeric symbols, such as spaces, are dropped from code search queries within quotation marks, so results can be unexpected.

I.e., GitHub has shot its own foot, leaving no way to do exact search for many things.

Compounding the problem is that there is just a single text string "Omnibox" approach on
https://github.com/search/advanced
with no "exact match" checkbox, nor a exact match box, like [Google](https://www.google.com/advanced_search).

[Google's syntax](https://support.google.com/websearch/answer/2466433) says

> Search for an exact match
> Put a word or phrase inside quotes. For example, "tallest building".

Which is apparently thankfully not tampered with further.

**Comment by janiceilene** [comment]
👋 @jidanni I think our wonderful [support team](https://support.github.com/contact) would be the best folks for providing clarity about whether or not it's possible to escape special characters in searches. After chatting with them, if you feel a docs update would be beneficial, feel free to come back and let us know. Thanks!
