### ISSUE TITLE
Unclear repository_ids parameter value

### ISSUE THREAD

**Issue by williamdes** [github/docs#5184]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app

### What part(s) of the article would you like to see updated?

The part about repository_ids is unclear, the example is not good at all.

It should be better to replace
```js
repositories: [
    'repositories'
  ]
```
By
```js
repositories: [
    'myRepositoryName'
]
```

And make it clear that you should not put the repository slug into it but only the name part

Thank you in advance

**Comment by janiceilene** [comment]
Thanks for opening an issue @williamdes! I'll triage this for the team to take a look 👀

**Comment by skedwards88** [comment]
Thanks for opening this issue! 💖 These examples are generated automatically, so we can't accept external contributions on them. We do have an internal issue to generate better examples like the one you suggested. I shared your feedback on that internal issue.
