### ISSUE TITLE
document in CONTRIBUTING.md that REST content is autogenerated and should not be modified by mortals

### ISSUE THREAD

**Issue by jsoref** [github/docs#5224]
### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/CONTRIBUTING.md

### What part(s) of the article would you like to see updated?

document that REST content is autogenerated and should not be modified by mortals 

### Additional information

https://github.com/github/docs/issues/3765#issuecomment-816542523

**Comment by janiceilene** [comment]
Thanks so much for opening this issue @jsoref! I think a new section in https://github.com/github/docs/blob/main/CONTRIBUTING.md#hammer_and_wrench-pull-requests would be perfect.

Anyone is welcome to make this change 💖

**Comment by chapodaddy42** [comment]
@

> apache 2.0

**Comment by yashhd** [comment]
Hello. This is my first ever open source contribution. I have opened a pull request. Could anyone of y'all check it? @janiceilene @jsoref

**Comment by yashhd** [comment]
take
