### ISSUE TITLE
link "markup reference guide" is broken or missing

### ISSUE THREAD

**Issue by rajputvishwas** [github/docs#524]
### What article on docs.github.com is affected?
In README.md, while clicking on the link "markup reference guide" it throws 404 page not found error.

https://github.com/github/docs/blob/main/content/README.md#versions

**Comment by Anita-ihuman** [comment]
I want to tackle this issue, please.

**Comment by shati-patel** [comment]
Thank you for [fixing this issue](https://github.com/github/docs/pull/550) @Anita-ihuman! ✨:blush:
