### ISSUE TITLE
Inconsistency between documentation and github page about connecting a package with a code repository

### ISSUE THREAD

**Issue by carlosbuenosvinos** [github/docs#5244]
### What article on docs.github.com is affected?

https://docs.github.com/en/packages/guides/connecting-a-repository-to-a-container-image#connecting-a-repository-to-a-container-image-on-the-command-line

### What part(s) of the article would you like to see updated?

In the documentation, the message says to use ```LABEL org.opencontainers.image.source=https://github.com/OWNER/REPO```

but on Github organization packages page can be seen without the equal sign ```=```

### Additional information

<img width="748" alt="Screenshot 2021-04-11 at 00 09 51" src="https://user-images.githubusercontent.com/351553/114285900-f26e9680-9a5a-11eb-84d5-8180a25a419f.png">

<img width="750" alt="Screenshot 2021-04-11 at 00 10 28" src="https://user-images.githubusercontent.com/351553/114285901-f39fc380-9a5a-11eb-9de7-2dcdd86cb942.png">

**Comment by janiceilene** [comment]
👋 @carlosbuenosvinos Thanks so much for opening an issue! The best folks to clarify whether or not the `=` is needed would be our wonderful [support team](https://support.github.com/contact) ✨ If you feel there's a need for a docs update after chatting with them, we'd love it if you came back here and let us know in this issue (then we can re-open it) or a new issue.

Thanks for your interest in improving GitHub's docs!

**Comment by carlosbuenosvinos** [comment]
Hi @janiceilene, in the dockerfile LABEL reference documentation that you can find [https://docs.docker.com/engine/reference/builder/#label](), the correct way to do it is with "=". So I guess the documentation is right, but the GitHub feature explanation is the one that should change. How do you want me to proceed?

![image](https://user-images.githubusercontent.com/351553/114504211-cefc4500-9c2e-11eb-955e-c7d4d95925b3.png)

**Comment by janiceilene** [comment]
If the feature explanation should be updated, a message to https://support.github.com/contact/feedback would be really helpful! Thank you so much for digging into this and figuring out what's going on 💖
