### ISSUE TITLE
Incorrect ref of blob custom media type in git database page

### ISSUE THREAD

**Issue by estepona** [github/docs#5246]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/git

### What part(s) of the article would you like to see updated?

"these custom media types" ref under [Blob](https://docs.github.com/en/rest/reference/git#blobs) section points to an incorrect section. It should be `#custom-media-types-for-blobs` instead of current `#custom-media-types`.

**Comment by estepona** [comment]
PR: https://github.com/github/docs/pull/5247

**Comment by Text-only** [comment]
#5253 

> ### Declare ### **Service**

_components_

**Comment by yasmanuel** [comment]
@bruce

**Comment by P-DUBB** [comment]
1143562


On 4/10/21, Binghuan Zhang ***@***.***> wrote:
> PR: https://github.com/github/docs/pull/5247
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/github/docs/issues/5246#issuecomment-817213623


-- 
P__

**Comment by estepona** [comment]
@janiceilene lol why would people spam GitHub docs?

**Comment by janiceilene** [comment]
@eaftan 😆 I really wish I knew why they spam us _so hard_!
