### ISSUE TITLE
Blue link text in notices is unreadable due to blue background

### ISSUE THREAD

**Issue by zeke** [github/docs#5349]
### What is the current behavior?

<img width="1387" alt="Screen Shot 2021-04-13 at 7 05 58 PM" src="https://user-images.githubusercontent.com/2289/114644056-a8b8c280-9c8b-11eb-96c0-244e82e0adff.png">

### What changes are you suggesting?

Use a more visible link color in notices.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue to let us know @zeke! I've triaged it for the engineering team to take a look 👀

**Comment by adityadees** [comment]
> Thanks so much for opening an issue to let us know @zeke! I've triaged it for the engineering team to take a look

is it still open?

**Comment by zeke** [comment]
I still see this issue at https://docs.github.com/cn

**Comment by chiedo** [comment]
We've got it added to our short-term list of bugs to fix as of today!

**Comment by lucalves** [comment]
I would like to work on that. What is the ideal color to include in the notice links? @chiedo @janiceilene

**Comment by lucalves** [comment]
> I still see this issue at https://docs.github.com/cn

This problem with the link and the blue background, is repeated in all other notices. Look at the docs in Portuguese, Japanese and Chinese.

I can work on this if it is defined what will be the new color for the links in the notices.

**Comment by chiedo** [comment]
Thank you @lucalves! @janiceilene and @myarb, @emilyistoofunky and I are thinking that maybe we just set the background to a lighter blue so we don't have to change the link color? --color-bg-info from https://primer.style/css/support/color-system#backgrounds

What do you think?

@lucalves do you want to spike that change?

**Comment by lucalves** [comment]
> Thank you @lucalves! @janiceilene and @myarb, @emilyistoofunky and I are thinking that maybe we just set the background to a lighter blue so we don't have to change the link color? --color-bg-info from https://primer.style/css/support/color-system#backgrounds
> 
> What do you think?
> 
> @lucalves do you want to spike that change?

I can try to make that change. If everyone agrees that it will be this color :)

**Comment by lee-dohm** [comment]
Thanks for being willing to assist @lucalves! We're investigating whether the suggestion that @chiedo mentions is the right way to go. Would you mind opening a PR with the suggested change so that we can take a look and see if it works?

Let me know if you have any questions!

**Comment by lucalves** [comment]
Hello @lee-dohm , I opened PR #5781, to solve this. I don't know why, but when deploying Heroku, I can't verify the pages other than the English page.

**Comment by chiedo** [comment]
I'll see if I can get `cn` working on the staging branch. One sec!

**Comment by chiedo** [comment]
You should be good to continue @lucalves! 

https://docs-5781--hotfixnotices-link.herokuapp.com/cn works.

**Comment by zeke** [comment]
Thanks for the fix @lucalves ✨

**Comment by chiedo** [comment]
Thanks @lucalves for working with us on this!

**Comment by myarb** [comment]
This looks great! 🎉 Thanks, @lucalves ✨

**Comment by lucalves** [comment]
Thank you all, now it really got a lot better! @zeke @chiedo @myarb
