### ISSUE TITLE
CNAME configuration lacks missing trailing dots

### ISSUE THREAD

**Issue by tomayac** [github/docs#5358]
### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#:~:text=anotherexample.com%20to-,%3Corganization%3E.github.io,-.%20The%20CNAME%20record

### What part(s) of the article would you like to see updated?

Add trailing dots to *"If you want to use the subdomain www.anotherexample.com for your organization site, create a CNAME record that points www.anotherexample.com to <organization>.github.io. The CNAME record should always point to <user>.github.io or <organization>.github.io, excluding the repository name."*

### Additional information

https://stackexchange.github.io/dnscontrol/why-the-dot

**Comment by Edord99** [comment]
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#:~:text=anotherexample.com%20to-,%3Corganization%3E.github.io,-.%20The%20CNAME%20record
> 
> ### What part(s) of the article would you like to see updated?
> Add trailing dots to _"If you want to use the subdomain [www.anotherexample.com](http://www.anotherexample.com) for your organization site, create a CNAME record that points [www.anotherexample.com](http://www.anotherexample.com) to .github.io. The CNAME record should always point to .github.io or .github.io, excluding the repository name."_
> 
> ### Additional information
> https://stackexchange.github.io/dnscontrol/why-the-dot

**Comment by janiceilene** [comment]
This was a change we decided not to make. See https://github.com/github/docs/pull/5359#issuecomment-834852572 for more details 💛
