### ISSUE TITLE
link not working on specific page translated into japanese

### ISSUE THREAD

**Issue by KisaragiEffective** [github/docs#5368]
### What is the current behavior?

In [this page](https://docs.github.com/ja/graphql/guides/using-the-explorer), a link which supposed to jump to https://github.com/skevy/graphiql-app won't work, because following paragraph was also interpreted as a part of link:
![image](https://user-images.githubusercontent.com/48310258/114744521-c029a580-9d88-11eb-86ed-c98ba4f62d1b.png)

### What changes are you suggesting?
separate paragraph and link text, like:
```md
GraphiQLアプリケーションを使うには、https://github.com/skevy/graphiql-app からダウンロードしてインストールしてください。
```

**Comment by janiceilene** [comment]
Thanks for opening this issue! Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

In the meantime, I'll open an internal issue to let the team know 💛
