### ISSUE TITLE
Missing `pull_request_target` case in base_ref and head_ref ctx

### ISSUE THREAD

**Issue by Yikun** [github/docs#5457]
### What is the current behavior?

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts
> The head_ref or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is a pull_request.
> The base_ref or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is a pull_request.

### What changes are you suggesting?
The `base_ref` or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run are `pull_request` **and `pull_request_target`**.

 The `head_ref` or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run are `pull_request` **and `pull_request_target`**.

### Additional information

No more info.

**Comment by Tylorriviere** [comment]
This is the only thing I can come to think of

**Comment by fayez2021** [comment]
Fayez m f Abueida

**Comment by fayez2021** [comment]
- [ ] @fayez2021 **_[8]+(5)=13_**
