### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by manula2004** [github/docs#551]
### What is the current behavior?
Github docs website does not have a dark mode

### What changes are you suggesting?
A lot of people, including myself prefer dark mode over light mode in a website . I think It makes the docs more comfortable to read for a user. So it would be really great to have a dark mode to the website. 

### Additional information
...

**Comment by kishore007k** [comment]
I would love to work on this issue. If it is still open and available. @manula2004

**Comment by manula2004** [comment]
@kishore007k  yes, the issue is still open and available. It would be really great if you could work on this

**Comment by kishore007k** [comment]
@manula2004 Yes, I'm up for it. I came across the Readme file and found that the issue that has the triage lable is still not yet verified by the reviewers. @janiceilene If you would can you remove the `triage` label so that I could work on the issue?

**Comment by ESSA760** [comment]
Nice

**Comment by janiceilene** [comment]
@kishore007k It hasn't been verified yet, thank you for checking! A member of the team will review it soon 💛

**Comment by kishore007k** [comment]
Looking forward to work on this issue. @janiceilene

**Comment by simpsoka** [comment]
This is exciting. :) 

I'd be happy to review what you're thinking @kishore007k! We are going through a little bit of a redesign - which you see us doing on the GitHub Actions pages. It's iterative, so if you want to start there, I think that'd be good.

**Comment by RubyDevil** [comment]
hi i want to work :(

**Comment by kazuhitonakayama** [comment]
It's an honor to meet you all!
How is the issue progressing here?
I'm contacting you because I'd like to help!✨
@simpsoka @janiceilene @manula2004

**Comment by GroovinChip** [comment]
Hello, is there any movement on this? The docs are super blinding to me and my dark mode browser extension doesn't work with the docs for some reason (Dark Reader).

**Comment by simpsoka** [comment]
Thanks for asking, @GroovinChip! We're going through a redesign on the site right now and as that reaches a solid state we'll look into dark mode.

**Comment by GroovinChip** [comment]
> Thanks for asking, @GroovinChip! We're going through a redesign on the site right now and as that reaches a solid state we'll look into dark mode. 

Thanks for the response! Do you have a general timeframe for when we can expect this? I know that's a hard question, sorry 😅 

Would you know why Dark Reader doesn't work with the site? Is it something I can fix on my end?

**Comment by simpsoka** [comment]
> Thanks for the response! Do you have a general timeframe for when we can expect this? I know that's a hard question, sorry 😅

No problem! We're not looking at adding dark mode any time soon - though that could change if we're able to get through the new design earlier. I'm going to go ahead and close this issue out, though, since it's not on our immediate roadmap. 

> Would you know why Dark Reader doesn't work with the site? Is it something I can fix on my end?

I'm not sure why it's not working, I haven't had a chance to play around with it myself. I recommend opening up a discussion and seeing of others have played around with it?
