### ISSUE TITLE
Make GitHub better

### ISSUE THREAD

**Issue by GetItBac92** [github/docs#5815]

**Comment by GetItBac92** [comment]
Upgrades won't load 
My password was reset and I can't log in

**Comment by ajs256** [comment]
Hey there @GetItBac92!
I think the best place to get help with your account would be [contacting GitHub Support](https://support.github.com). The people who watch this repo probably won't be able to help.

> Please note I am not affiliated with the GitHub team.

**Comment by Ice991** [comment]
"
