### ISSUE TITLE
Fix link is broken in Japanese translation

### ISSUE THREAD

**Issue by knsh14** [github/docs#5826]
### What article on docs.github.com is affected?

https://docs.github.com/ja/github-ae@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent

### What part(s) of the article would you like to see updated?

in this document, MacPort and Homebrew's links are broken.

### Additional information
I already forked and fixed doc, so I can create PR soon.
https://github.com/github/docs/compare/main...knsh14:main

**Comment by janiceilene** [comment]
Thank so much for opening an issue @knsh14! You're welcome to open a PR with your fix 💖
