### ISSUE TITLE
GitHub Actions does for how specific shells are run does not match the internal command run

### ISSUE THREAD

**Issue by brettcannon** [github/docs#5839]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

### What part(s) of the article would you like to see updated?

The listed commands that the selected shell execute seem wrong. For instance, `python {0}` does not work if you set `run` in a step to `print('hi')` (it gets interpreted as a file path). It probably should be `python -c {0}`.

But then the `bash` and `sh` examples don't make sense either. If the strings from `run` are being piped to the commands then those examples make sense, but that isn't what the docs or the examples are suggesting is occurring.

**Comment by janiceilene** [comment]
Thanks for opening an issue @brettcannon! I'll triage this for the team to take a look 👀

**Comment by lecoursen** [comment]
Hi there! Can you please contact our wonderful [support team](https://support.github.com/contact) and ask them to help you understand these examples? If they let you know that docs updates are needed, please reopen this issue to let us know!

**Comment by brettcannon** [comment]
I actually don't need help understanding, there was just a sense of disconnect between the string from the YAML configuration being passed in to the shell and how the command is listed (it's more like a file path).

So maybe that's the better ask: document that the examples assume what you set in `run` are saved to a temporary file.

**Comment by janiceilene** [comment]
@brettcannon Could you open a new issue with the docs update you're looking for? That'll help us to better triage your request! Thanks for helping us to improve the GitHub docs 💖
