### ISSUE TITLE
Provide More Detail On How To Authenticate With Personal Access Token On Command Line

### ISSUE THREAD

**Issue by munnellg** [github/docs#5841]
### What article on docs.github.com is affected?

[Creating a personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)

https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

### What part(s) of the article would you like to see updated?

The final section on the page, [Using a token on the command line](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token#using-a-token-on-the-command-line), should provide more information about how to store credentials locally. I think this is especially important given Github's aim to deprecate basic auth with a password by August this year.

An improved concluding section would detail how to use git cache, git store, and password management software to handle storage and use of a personal access token. The existing documentation suggests that the only recourse is to copy/paste the token in response to a request for a password. This is echoed by the only StackOverflow post I could find on the subject of authenticating with a personal access token:

https://stackoverflow.com/questions/18935539/authenticate-with-github-using-a-token

This update will be critical for smoothing the deprecation of password authentication with minimal disruption to people's workflows.

**Comment by janiceilene** [comment]
Thanks for opening an issue @munnellg! I'll triage this for the team to take a look 👀

**Comment by munnellg** [comment]
Thanks @janiceilene! Just as an FYI, I'm happy to fork the repo and write the section for Linux myself, but the contribution guidelines said to open an issue first.

**Comment by lecoursen** [comment]
Hi there! We do have an article about caching your credentials in Git, "[Caching your GitHub credentials in Git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git)". It would be a great idea to add a link to that article in the section you point out. Please fell free to open a PR doing so!

**Comment by munnellg** [comment]
Hi @lecoursen! Fantastic! I'll add that link to the page now.

I've noticed that [Caching your GitHub credentials in Git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git) does not describe how to use git store to permanently save your token, rather than caching it with a timeout.

Ideally, all the information available in [this article](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) would be available in the github docs. Should I open a new issue to discuss this, or do you think an edit to [Caching your GitHub credentials in Git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git) is also necessary?

**Comment by lecoursen** [comment]
I think opening a new issue is a great idea! We don't want to completely duplicate content that's already available elsewhere, so we need to figure out (1) which caching method(s) we want to recommend and (2) how much of those instructions we should include in the docs vs linking to Pro Git instead. A new issue would let us do that without holding up your PR to add that link! ⚡

**Comment by munnellg** [comment]
Cool! That's what I was thinking RE duplication. I wasn't sure if GitHub's documentation takes a similar approach to StackOverflow i.e don't link to third-party sources. You should copy/paste relevant extracts into your answer.

Thanks for all the help! :slightly_smiling_face:
