### ISSUE TITLE
http://developer.github.com/v3/#user-agent-required doesn't redirect correctly

### ISSUE THREAD

**Issue by Ethan-Arrowood** [github/docs#5842]
### What is the current behavior?

While using the github api I hit the missing user-agent issue and received this link to find more info: http://developer.github.com/v3/#user-agent-required - when I navigated to this link it redirects to https://docs.github.com/en/rest#user-agent-required instead of https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required

### What changes are you suggesting?

Fix the redirect

**Comment by janiceilene** [comment]
👋 @Ethan-Arrowood It sounds like the link you're clicking isn't on docs.github.com. Since we only update the docs themselves in this repo, it sounds like the best place to send your feedback is to https://support.github.com/contact/feedback 💛

Let me know if I'm misunderstanding!
