### ISSUE TITLE
Add headers to Git articles, part 1

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#5848]
### What article on docs.github.com is affected?

- "[Setting your username in Git](https://docs.github.com/en/github/getting-started-with-github/setting-your-username-in-git)"
   - New header: About Git usernames
- "[Configuring git to handle line endings](https://docs.github.com/en/github/getting-started-with-github/setting-your-username-in-git)
  - New header: About line endings
- "[Pushing commits to a remote repository](https://docs.github.com/en/github/getting-started-with-github/pushing-commits-to-a-remote-repository)"
  - New header: About `git push`

### What part(s) of the article would you like to see updated?

There's not currently a header above the initial information in the articles, so the information isn't represented or linkable in the article's table of contents. Add H3 headers to the beginning of the articles (see suggested header titles above).

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by khattakdev** [comment]
I'll take this issue. I'm a `Campus Expert`

**Comment by emilyistoofunky** [comment]
Thanks @khattakdev! Let us know if you have any questions as you're working on your PR.

**Comment by khattakdev** [comment]
@emilyistoofunky  I was off-track for a while but I started working on this Issue, It should have a Pull request pretty soon.
Just a question 
> There's not currently a header above the initial information in the articles, so the information isn't represented or linkable in the article's table of contents. Add H3 headers to the beginning of the articles (see suggested header titles above).

I am not sure which place is this context referring to? As much as I know, there is a heading **Getting started with Git**

![image](https://user-images.githubusercontent.com/37709578/122668024-8f724c00-d1cf-11eb-8d1b-bd19278bb721.png)
Any clarifications would be helpful.

**Comment by emilyistoofunky** [comment]
👋🏻 Hi @khattakdev! Sorry for the lack of clarity here. Looking at the source for the articles, we want to add an H2 `##` [header](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#headers) after the end of the frontmatter, before the content starts. Otherwise, it's not possible to directly link to that section of the article. 

For example in [this article](https://raw.githubusercontent.com/github/docs/main/content/get-started/getting-started-with-git/setting-your-username-in-git.md), you could add something like`## About usernames in Git` right after the frontmatter, before the first paragraph that starts "You can change the name that is associated with...".

![image](https://user-images.githubusercontent.com/4822039/122821051-f829f900-d2a1-11eb-9b65-2987b2960873.png)
