### ISSUE TITLE
Add headers to Git articles, part 2

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#5849]
### What article on docs.github.com is affected?

- "[Getting changes from a remote repository](https://docs.github.com/en/github/getting-started-with-github/getting-changes-from-a-remote-repository)"
  - New header: Options for getting changes
- "[About Git subtree merges](https://docs.github.com/en/github/getting-started-with-github/about-git-subtree-merges)" 
  - New header: About subtree merges
- "[Using Git rebase on the command line](https://docs.github.com/en/github/getting-started-with-github/using-git-rebase-on-the-command-line)"
  - New header: Using Git rebase

### What part(s) of the article would you like to see updated?

There's not currently a header above the initial information in the articles, so the information isn't represented or linkable in the article's table of contents. Add H3 headers to the beginning of the articles (see suggested header titles above).

### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by Blakelist7** [comment]
@emilyistoofunky If no one is working, can a newbie like me try this ?

**Comment by tusharbhadak** [comment]
Hi,
I'd love to add headers to git articles.

**Comment by emilyistoofunky** [comment]
Hi @tusharbhadak! Thanks so much for your interest in contributing! This issue is part of a special project and isn't available to be fixed at this time. We'd love it if you took a look at our [help-wanted](https://github.com/github/docs/projects/1#column-11564194) issues and fixed one of those! ✨

**Comment by tusharbhadak** [comment]
Ya Sure @emilyistoofunky , I'd also love to solve help-wanted issues.

**Comment by emilyistoofunky** [comment]
Great @tusharbhadak, feel free to assign yourself to one of those!

**Comment by youthtrouble** [comment]
I'll work on this issue, I'm a campus expert.
