### ISSUE TITLE
Add keyboard shortcut for discussions

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#5850]
### What article on docs.github.com is affected?

The "Repositories" section in "[Keyboard shortcuts](https://docs.github.com/en/github/getting-started-with-github/keyboard-shortcuts#repositories)"

### What part(s) of the article would you like to see updated?

Add `g` `g` as the shortcut to go to Discussions within a repository.

![image](https://user-images.githubusercontent.com/4822039/116615468-f62a6600-a900-11eb-8eca-e1ac4fc9794b.png)

### Additional information

This issue is for a special project and not currently available for contributors to work on.

**Comment by dixon-kun** [comment]
google vitral keyboard `g.v.k.`

**Comment by StarTrooper08** [comment]
Can I work on this issue?

**Comment by StarTrooper08** [comment]
And one more thing should I give link similar to this!!
![image](https://user-images.githubusercontent.com/72031540/117630244-9fdae400-b198-11eb-89ce-4b9fba8b06eb.png)

Discussion link should be given in the description of g g keyboard shortcut(discussion shortcut).

**Comment by emilyistoofunky** [comment]
Hi @StarTrooper08! Thanks for your interest in contributing to GitHub Docs. This issue is for a special project and not currently available for contributors to work on. Feel free to take a look at issues with the [`help wanted` label](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) and assign yourself to anything that's not already being worked on. ✨

**Comment by FlyteWizard** [comment]
Hey! Can I work on this ticket? I am apart of the `Campus Experts + Docs Program`.

---

For the link, will we be using this link? 
`https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions` and if so how do we add this link? Would it be `/discussions/collaborating-with-your-community-using-discussions/about-discussions`?
