### ISSUE TITLE
No guide on how to add Dependabot

### ISSUE THREAD

**Issue by iHildy** [github/docs#5946]
### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/supply-chain-security/upgrading-from-dependabotcom-to-github-native-dependabot

### What part(s) of the article would you like to see updated?

I would like a section on how to add the bot to a repository that did not have dependabot-preview in the past. Maybe it's hidden in there somewhere but I can't seem to find it at all. The dependabot website just links to the article above so that's no use.

### Additional information

Trying to add it to: https://github.com/iHildy/next-tailwind-template

**Comment by HonkingGoose** [comment]
I agree it's hard to find the docs for Dependabot... if you go to the docs homepage and enter "dependabot" none of the hits are about enabling Dependabot...

---

@iHildy This document explains how to setup Dependabot. But I'll do you one better and create a PR for you on your repo to get you setup. 😉 

https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates
