### ISSUE TITLE
External link icons used in few Products link is creating confusions.

### ISSUE THREAD

**Issue by ArunRaj6** [github/docs#6014]
### What is the current behavior?

External link icons are used in few Products. But while clicking on those links the new page is getting loaded on the same view.

### What changes are you suggesting?

Expecting to load the triggered pages in a new browser tab.

`or`

Remove the external link icons from those links to make it in a consistent way like other links.

### Additional information

![Screenshot 2021-05-04 at 12 23 18](https://user-images.githubusercontent.com/22270737/116970882-568d1f00-acd6-11eb-8e52-777df83fb863.png)

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @ArunRaj6! All of the links you've underlined, have the external link icon because they send you to sites outside of docs.github.com. Do you think they should also open in a new tab?

**Comment by ArunRaj6** [comment]
@janiceilene  Yes. As a user when I saw these external link icons, I thought they will be load in a new browser tab.

**Comment by ArunRaj6** [comment]
@janiceilene  I have opened a PR for the same [6025](https://github.com/github/docs/pull/6025).

**Comment by tweak26** [comment]
Ghh

adrian
