### ISSUE TITLE
Missing text in "Working with the Apache Maven registry"

### ISSUE THREAD

**Issue by giovannivelludo** [github/docs#6023]
### What article on docs.github.com is affected?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

### What part(s) of the article would you like to see updated?

The first [`if` statement at line 34](https://github.com/github/docs/blame/main/content/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry.md#L34) of the corresponding Markdown file causes nothing to appear between "Replace" and ", and *OWNER*", effectively resulting in the paragraph being

> In the repositories tag, configure a repository by mapping the id of the repository to the id you added in the server tag containing your credentials. Replace , and OWNER with the name of the user or organization account that owns the repository. Because uppercase letters aren't supported, you must use lowercase letters for the repository owner even if the GitHub user or organization name contains uppercase letters.

**Comment by haniyehy** [comment]
0xBEBedeF0B8844e3406E8D3a803Bf0c61E586005C

**Comment by janiceilene** [comment]
That is wonky @giovannivelludo! You or anyone else are welcome to open a PR with a fix 💖
