### ISSUE TITLE
Fix formatting in article

### ISSUE THREAD

**Issue by skedwards88** [github/docs#6026]
### What article on docs.github.com is affected?

[About status checks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks)

### What part(s) of the article would you like to see updated?

- The two code blocks in this article should include closing quotation marks.
-  `followed by skip-checks: true` should add `"` at the end (`followed by skip-checks: true"`)
- The second bullet point under the "Skipping and requesting checks for individual commits" section should have one less indent

**Comment by lucalves** [comment]
Hi @skedwards88, I made the necessary changes on #6027. I was left with a doubt only in the second point, if it includes the `"` in the correct place. Can you check in the PR?
