### ISSUE TITLE
Inconsistent but insignificant list item indentation

### ISSUE THREAD

**Issue by Simran-B** [github/docs#6045]
### What article on docs.github.com is affected?

I noticed that at least one Markdown file uses inconsistent list indentation. This does not affect rendering, but I would still like to know whether you consider it best practice to uses consistent indentation and if it's worth opening PRs to correct such whitespace issues.

![image](https://user-images.githubusercontent.com/7819991/117134148-7ccdc000-ada5-11eb-80e7-33fa8da70967.png)

Page: https://docs.github.com/en/code-security/secure-coding/troubleshooting-the-codeql-workflow
Source: https://github.com/github/docs/blob/main/content/code-security/secure-coding/troubleshooting-the-codeql-workflow.md

### What part(s) of the article would you like to see updated?

Example (using `|` as orientation line):

````
   |
1. Ordered list
2. Text spanning
   multiple lines
   indented with 3 spaces
   |
  * Nested list that should be indented with 3 spaces as well
   |but only uses 2 spaces
   |
  ```
  fenced code block, also using one space too little
  ```
   |
  More text belonging to the 2nd list item,
  but still using one space too few.
   |
````

Suggestion:

````
   |
1. Ordered list
2. Text spanning
   multiple lines
   indented with 3 spaces
   |
   * Nested list that should be indented with 3 spaces as well
   | but only uses 2 spaces
   |
   ```
   fenced code block, also using one space too little
   ```
   |
   More text belonging to the 2nd list item,
   but still using one space too few.
   |
````

### Additional information

You may want to add the decision to the [Content Style Guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md)

**Comment by janiceilene** [comment]
👋 @Simran-B Good to see you around! 

Making the white space changes could lead to additional localization costs, so we shouldn't worry about that. Lately we've been working to make sure that our style guide and review guidelines (and a bunch of other docs!) really focus on user impact (Does this update make it easier/harder for a user to understand the content? Is a change going to make for a better docs user experience). With that in mind, I'd lean towards not adding white space guidelines to the style guide.

@emilyistoofunky What do you think?

**Comment by emilyistoofunky** [comment]
👋🏻 Hi @Simran-B! Nice catch here, you must have 🦅 👀. Even though we technical writers are sticklers for consistency 😆, for the reasons that @janiceilene mentioned and to keep the style guide streamlined, I agree that we wouldn't add this. I'm going to close this out but we look forward to seeing you around again!

**Comment by Simran-B** [comment]
Thanks for the clarification! It's indeed just a pedantic thing with no user impact. I basically look at Markdown documentation all day, so this is second nature to me.
