### ISSUE TITLE
Space between backticks of fenced code block and language for highlighting

### ISSUE THREAD

**Issue by Simran-B** [github/docs#6046]
### What article on docs.github.com is affected?

There are 149 occurrences in .md files where there is a single space after the start of a fenced code block and before the indicated code language, e.g. `` ``` shell ``  (regex: `` ``` \w ``), whereas there is no space in 1660 other cases, e.g. `` ```shell ``.

### What part(s) of the article would you like to see updated?

I suggest unifying this to no space and to add a remark to the [Content Style Guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### Additional information

I also noticed that in 11 cases the indicated language is `yml` and in 487 cases it is `yaml`. I suggest unifying it to `yaml`.

I'm happy to open a PR that implements the suggested changes.

**Comment by janiceilene** [comment]
Since there's no difference in the way a user interacts with `` ```shell`` and `` ``` shell`` let's not worry about that one. I do think (if someone's looking at the source) that there could be confusion over `yml` and `yaml` especially for super new folks. A PR changing those 11 instances would be great!

**Comment by Simran-B** [comment]
The parser luckily accepts a space in that place. I know that some others do not, although IIRC then there was also a particular one that required a space... Anyway, here's a PR: #6109
