### ISSUE TITLE
Update Python package build and upload example

### ISSUE THREAD

**Issue by jamescurtin** [github/docs#6089]
### What article on docs.github.com is affected?

https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

### What part(s) of the article would you like to see updated?

The [Python Packaging Authority](https://www.pypa.io/en/latest/) (PyPA)--the working group responsible for `pip` and `PyPI`, among other packaging tools--maintains an action for uploading Python packages to PyPI. The example for building and publishing a Python package does not use the PyPA-maintained action. 

### Additional information

I have submitted https://github.com/actions/starter-workflows/pull/900 to make the same change in the `actions/starter-workflows` repo.

**Comment by umit01** [comment]
Ok
