### ISSUE TITLE
Some Japanese docs are not accessible (HTTP 404)

### ISSUE THREAD

**Issue by sarisia** [github/docs#6106]
### What is the current behavior?

Some Japanese docs are not accessible (HTTP 404).
![image](https://user-images.githubusercontent.com/33576079/117414446-1a65f280-af52-11eb-8f89-655263369095.png)

Some can, and some cannot. 
e.g.
https://docs.github.com/ja/github/developing-online-with-codespaces
https://docs.github.com/ja/github/supporting-the-open-source-community-with-github-sponsors

I've reached these pages from Google Search and Google has cached pages for them,
so I think this is accidentally happened (== not intended).

FYI: English pages for these 404 pages are accessible, like:
https://docs.github.com/en/github/developing-online-with-codespaces
https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors

### What changes are you suggesting?

Please recover these pages.
At least redirect users to English docs, instead of showing 404.

**Comment by janiceilene** [comment]
Thank you so much for opening an issue @sarisia! That's really not a great experience, I'm sorry that those pages are 404ing for you 💛 I'll triage this for our engineering team to take a look at.

**Comment by chiedo** [comment]
Hi @sarisia !

Both of the URLs you shared seem to work on my end:

- https://docs.github.com/ja/github/developing-online-with-codespaces
- https://docs.github.com/ja/github/supporting-the-open-source-community-with-github-sponsors

Can you let me know if they work for you now?

**Comment by sarisia** [comment]
Hi, @chiedo 

Thank you for letting me know.
I’ve confirmed these 2 urls are working on my end now.

**Comment by chiedo** [comment]
Great! Glad we got it fixed!
