### ISSUE TITLE
`$RUNNER_OS`/etc environment variables not documented (GitHub Actions)

### ISSUE THREAD

**Issue by jmarshall** [github/docs#6127]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

### What part(s) of the article would you like to see updated?

This [StackOverflow answer](https://stackoverflow.com/a/57948488) claims that GitHub Actions workflow steps are provided with an environment variable `$RUNNER_OS` that contains the value of `${{ runner.os }}`.

This is confirmed by a simple workflow that just prints out `env | sort`:

```
…
RUNNER_OS=Linux
RUNNER_PERFLOG=/home/runner/perflog
RUNNER_TEMP=/home/runner/work/_temp
RUNNER_TOOL_CACHE=/opt/hostedtoolcache
RUNNER_TRACKING_ID=github_069548eb-c4f3-4542-baac-43ed0d140801
RUNNER_USER=runner
RUNNER_WORKSPACE=/home/runner/work/pysam
…
```

It also appears to be confirmed by the runner source code; see https://github.com/actions/runner/blob/419ed24c1ee8c70eeb096570980e700e833f81f6/src/Runner.Worker/RunnerContext.cs#L13

The affected web page lists environment variables available to workflow steps, including `$CI` and many variables of the form `$GITHUB_xyz`. If (some of) these `$RUNNER_xyz` environment variables are also supported for use by workflow steps, it would be useful if they were added to this listing.

### Additional information

This is somewhat related to the previously-reported #2031, but that issue was interpreted as being about the context expression `${{ runner.os }}` rather than the environment variable `$RUNNER_OS`.

**Comment by janiceilene** [comment]
Thanks for opening an issue @jmarshall and looking for related issues 💖 I'll triage this for the team to take a look 👀

**Comment by straves16** [comment]
Thanks for reviewing docs related to my workflow api 💷💷💷💷💷💷💷💳

**Comment by BrucieBoy38** [comment]
I'm trying to locate some compound send from my Coinbase wallet address to my Coinbase trading wallet.  It never went through and cb isn't helping much or it's me.  If someone would be kind to help me retrieve my compound; I would donate some of it 100%.  Ty. 🤞🤞🤙

**Comment by lecoursen** [comment]
Hi there! Thanks for pointing this out. We should add that environment variable to https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables as you suggest. You or anyone else is welcome to open a PR doing so! ⚡

**Comment by jmarshall** [comment]
Only GitHub staff are in a position to confirm which of the seven `RUNNER_*` environment variables observed are supported for use in workflows.

Note that only three of the [corresponding `runner` context properties](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#runner-context) are documented.

**Comment by BrucieBoy38** [comment]
On Thu, May 13, 2021 at 1:10 PM John Marshall ***@***.***>
wrote:

> What does this mean? Or what should I do?
>



Only GitHub staff are in a position to confirm which of the seven RUNNER_*

**Comment by janiceilene** [comment]
@jmarshall That's a good call! Could you check with our wonderful [support team](https://support.github.com/contact) about whether or not that variable should be documented? If it is, you can either comment here and we'll reopen this issue or open a new issue 💖 

Thanks so much for helping to improve the GitHub docs!

**Comment by jmarshall** [comment]
@janiceilene: I don't understand why you've closed this. @lecoursen agreed that changes are warranted (but didn't clarify which particular variables are supported). No additions have been made to _environment-variables.md_ so the issue remains unresolved.

**Comment by janiceilene** [comment]
@jmarshall Sorry about the confusion! I closed this issue because it isn't something the team can take action on right now. If you want to check in with our [support team](https://support.github.com/contact) to find out with variables are supported, you can come back and let us know! At that point we can either re open this issue or you can open a new one 💛

**Comment by martin389** [comment]
Reopening based on discussion in PR https://github.com/github/docs/pull/6740

**Comment by martin389** [comment]
Changes are now live:

| Published article  | Changes |
| --- | --- | 
“[Default environment variables](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)” |  Adds entries to table for `RUNNER_OS`, `RUNNER_TEMP`, and `RUNNER_TOOL_CACHE `
"[Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#runner-context)"| Moved descriptions into reusables for consistency.
