### ISSUE TITLE
Docsaid I'm dying soon . I didn't have much longer he told me. I've been so naive. Sorry if this is not good link . I'm trying to help figure this out., Help and criticism is appreciated.... so what is this? And Experian  said I was reported as deceased in 2018? I need help in every area I know it's a bit much but I can't do it alone it's mind blowing...

### ISSUE THREAD

**Issue by tipp2** [github/docs#6155]
[https://github.com/github/docs/blob/7b99fd054abd0dfb02c6f88e73fc45ed68935cce/.devcontainer.json](https://docs.google.com/document/d/1vRF7jAv35HuEbKB7sd-RNl69g0HF-aInBRQWuIEsJHg/edit?usp=drivesdk) 

>   @#`https://github.com/github/docs/blob/7b99fd054abd0dfb02c6f88e73fc45ed68935cce/.editorconfig#L9

**Comment by Evavic44** [comment]
> [https://github.com/github/docs/blob/7b99fd054abd0dfb02c6f88e73fc45ed68935cce/.devcontainer.json](https://docs.google.com/document/d/1vRF7jAv35HuEbKB7sd-RNl69g0HF-aInBRQWuIEsJHg/edit?usp=drivesdk)
> 
> > @#`https://github.com/github/docs/blob/7b99fd054abd0dfb02c6f88e73fc45ed68935cce/.editorconfig#L9

So sorry about that, I can't imagine what you're going through. Just popped in to let you know that `You got this!` the reports from the doctor `is not the end`. I strongly believe `you'll come out of this healthier and better`. ❤️ Do send me a message when you read this.

**Comment by lee-dohm** [comment]
Hello @tipp2.

I'm sorry to hear about what you're going through. I can't imagine what that would be like to have to deal with. Unfortunately, none of what you mention is something that the GitHub Docs project or even GitHub as a company can assist you with. If you need help and support with regard to your diagnosis, I would recommend talking to your doctor about hospice care or counseling. They would best be able to direct you to the resources available to you.

If you're asking a question about the [GitHub Docs site or project](https://docs.github.com), please [open a new issue](https://github.com/github/docs/issues/new/choose) and fill in the template most appropriate to what you're suggesting or asking about and we'll help however we can.

I hope that helps clarify things. Please let us know if there's any questions we can answer about the GitHub Docs project.
