### ISSUE TITLE
Skip CI / skip workflow documentation clarity

### ISSUE THREAD

**Issue by Rochet2** [github/docs#6162]
### What article on docs.github.com is affected?

Skip CI announcement: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
Skip CI documentation: https://docs.github.com/en/actions/guides/about-continuous-integration#skipping-workflow-runs

### What part(s) of the article would you like to see updated?

At least to me, the announcement seemed to have misleading information.
The announcement claims the following:
> If any commit message in your push ... contains the strings [skip ci], ... workflows ... will be skipped.

A push can contain several commits and the announcement says that if any commit message has the tag, then the workflows will be skipped.
However, that is not true as only the latest commit in a batch of commits was evaluated for the tag when I tested the feature.

Furthermore, the documentation of the feature is also not clear on what exactly happens when you push multiple commits as seen in the following:
> Workflows ... won't be triggered if you add any any of the following strings to the commit message in a push

The documentation talks about "the commit message", which could be possibly assumed to mean the latest commit in a push of several commits, but it is ultimately unclear.

In addition, there is a typo in the documentation saying `any any`, that should be corrected.

**Proposed solution:**
The misleading text about "any commit" should be removed from the announcement.
The typo should be corrected.
The announcement and the documentation could be modified to more clearly state what actually happens when you push multiple commits.
The announcement could link to the documentation.

### Additional information

The announcement is the first result on search engines to me when searching with `github actions skip ci`, so I feel it is important to correct the information that it gives.
The documentation was harder to find. Especially since the announcement does not link to it and it did not seem to be anywhere in search engine results outside of GitHub. I only found it by searching Github docs with `skip ci`.

PS. github support directed me here.

**Comment by janiceilene** [comment]
👋 @Rochet2 Thanks for opening an issue! We don't own the GitHub blog, just the documentation you see on docs.github.com so the updates you'd like to see in the docs are the ones we can address here 💛 

> the documentation could be modified to more clearly state what actually happens when you push multiple commits.

Do you have any thoughts on how that section should be updated to make what's happening clearer? What language would you replace and what would you say there?

**Comment by Rochet2** [comment]
The main issue would be the blog post, so I guess I will get back to support on that.

For the documentation, I would probably try to just clarify that the skip instruction must be on the HEAD commit of a push.
I'm not sure if the `HEAD commit` is the correct terminology for a push though. Removing the double "any" is probably also a good idea.

So I would suggest changing
> Workflows that would otherwise be triggered on: push or on: pull_request, won't be triggered if you add any any of the following strings to the commit message in a push, or the HEAD commit of a pull request:

to something along the lines of

> Workflows that would otherwise be triggered on: push or on: pull_request, won't be triggered if any of the following strings are present in the HEAD commit message of a push or a pull request:

**Comment by janiceilene** [comment]
Thanks for that clarification @Rochet2! I'll triage this for someone to take a look 👀

**Comment by lee-dohm** [comment]
Hello @Rochet2, thanks for reaching out about this.

I've reviewed this with the team and we want to be clear on what it is you want changed and why. Would you mind opening a new issue specifically for the documentation change you're proposing so that we can be certain that we evaluate it properly? Let me know if you have any questions.

Thanks for helping make the GitHub documentation better!
