### ISSUE TITLE
Mars 2020 project list: Version of log4j inconsistent

### ISSUE THREAD

**Issue by TobiX** [github/docs#6165]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/personalizing-your-profile#list-of-qualifying-repositories-for-mars-2020-helicopter-contributor-badge

### What part(s) of the article would you like to see updated?

The list of qualifying projects for the Mars 2020 Helicopter Contributor badge lists log4j 2.11, but links to the tag for log4j 1.2.11. If the listed version is indeed correct, the correct link would be https://github.com/apache/logging-log4j2/releases/tag/log4j-2.11.0.

### Additional information

Since this is a different repository then log4j1, the eligibility for the badge might need to be reevaluated, if the data for the badge contains the same error.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue with this discrepancy @TobiX! I'll triage this for the team to take a look 👀

**Comment by admin10145** [comment]
Hello

**Comment by dmc8013** [comment]
https://github.com/apache/logging-log4j2/releases/tag/log4j-2.11.0
