### ISSUE TITLE
Ruby example for Securing your Webhook contain errors

### ISSUE THREAD

**Issue by raccube** [github/docs#6211]
### What article on docs.github.com is affected?
[Securing your Webhooks](https://docs-6209--patch-1.herokuapp.com/en/developers/webhooks-and-events/securing-your-webhooks)

### What part(s) of the article would you like to see updated?

Both of the Ruby code snippets on this page should get the payload from `request.body` instead of `params[:payload]`

### Additional information

_Not required._

**Comment by mspaansen** [comment]
Ok
