### ISSUE TITLE
Fix procedure about configuring a learning management system

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#6273]
### What article on docs.github.com is affected?

The “Creating a roster for your classroom” section of “[Manage classrooms](https://docs.github.com/en/education/manage-coursework-with-github-classroom/manage-classrooms#creating-a-roster-for-your-classroom)”

### What part(s) of the article would you like to see updated?

Update step 5 to clarify that there are two options here and show the time-saving option first.
```
5. Choose whether to import a roster or create a roster manually.
  - To upload a file containing the identifiers, click **Upload a CSV or text file**. 
  - Otherwise, to create a roster manually, type your student identifiers.
```
### Additional information

This issue is for a special project and is not currently available for contributors to work on.

**Comment by AlexandraMMR** [comment]
Hallo 👋🏼 could I have this one please? ✨

**Comment by emilyistoofunky** [comment]
Sure thing @AlexandraMMR! Let us know if you have any questions as you work on your PR.

**Comment by AlexandraMMR** [comment]
> Sure thing @AlexandraMMR! Let us know if you have any questions as you work on your PR.

Thank you, I'll try to get the PR in tomorrow!

**Comment by AlexandraMMR** [comment]
@emilyistoofunky I raised the PR, just waiting to see the heroku deployment 👍🏼 
I edited the text slightly for clarity by adding a reference to the import, let me know if that's ok!

**Comment by emilyistoofunky** [comment]
Great, thank you @AlexandraMMR! We'll have someone from GitHub Docs review the PR. Sorry about the deployment trouble, that should be fixed now.

**Comment by AlexandraMMR** [comment]
> Great, thank you @AlexandraMMR! We'll have someone from GitHub Docs review the PR. Sorry about the deployment trouble, that should be fixed now. 

No worries, it happens sometimes 😊
