### ISSUE TITLE
Intros for profile and user account categories

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#6285]
### What article on docs.github.com is affected?

Two categories of articles:
- “[Setting up and managing your GitHub profile](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile)
- “[Setting up and managing your GitHub user account](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account)”

### What part(s) of the article would you like to see updated?

Write intros to help orient users to the content in each category. Intros are also displayed in search results. Intros should be one sentence long. For more information on writing intros, see:
- [Information about categories](https://github.com/github/docs/blob/main/contributing/content-model.md#category) in the GitHub Docs content model
- [Information about writing intros](https://github.com/github/docs/blob/main/contributing/content-model.md#intro) in the GitHub docs content model
- [Information about the `intro` frontmatter property](https://github.com/github/docs/tree/main/content#intro) in the GitHub Docs content directory README
- Make sure your intro is general enough to cover the content in each version of the page (use the version picker in the upper-right corner of the page to see what’s included on the page for different versions of GitHub)

### Additional information

This issue is for the Campus Experts + Docs program and is not available for contributors outside the program to work on.

**Comment by iiqrah** [comment]
I'd like to take this one next :)
