### ISSUE TITLE
Broken link in the document: getting-started-with-your-dotnet-project.md

### ISSUE THREAD

**Issue by Saggiehaim** [github/docs#6306]
### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/codespaces/getting-started-with-codespaces/getting-started-with-your-dotnet-project.md

### What part(s) of the article would you like to see updated?

On line #20, you will see the following line:

You should have an existing C# (.NET) project in a repository on {% data variables.product.prodname_dotcom_the_website %}. If you don't have a project, you can try this tutorial with the following example: https://github.com/2percentsilk/dotnet-quickstart.

the link to the GitHub repo is broken.

### Additional information

I tried to find the right URL, but looks like the repo is no longer exists..

**Comment by ajs256** [comment]
Looks like @2percentsilk forgot to make the repo public.

**Comment by 2percentsilk** [comment]
Apologies! It should be fixed now :)

**Comment by Jlk20** [comment]
I need so much help

**Comment by Saggiehaim** [comment]
Its working now :) 
Thanks all !
