### ISSUE TITLE
Add new conceptual article 'About assignments' for GitHub Classroom docs

### ISSUE THREAD

**Issue by saritai** [github/docs#6326]
[maintainer edit]
This issue is reserved for the MLH Fellowship program.

### What article on docs.github.com is affected?

This will be a new article in the GitHub Classroom part of the docs site, called "About assignments".

The "About assignments" article can be placed as the second article in the "Teach with GitHub Classroom" map topic, under 'Manage classrooms'. 

#### Why

Currently, the GitHub Classroom docs include a few articles about creating assignments - “[Creating individual assignments](https://docs.github.com/en/education/manage-coursework-with-github-classroom/create-an-individual-assignment)” and “[Creating group assignments](https://docs.github.com/en/education/manage-coursework-with-github-classroom/create-a-group-assignment)”. 

However, there isn’t a conceptual article about assignments, introducing users to what they are, how they work in GitHub Classroom, the different types, and next steps for getting started with assignments. So we want to add one. 

#### Use cases and audience

This page is needed to give an introduction to how assignments work to prospective teachers, students, or even school or organization administrators. It provides one place for them to go to learn about the different types of assignments and how they work in GitHub Classroom. 

#### Getting started 

You can get started by learning more about [conceptual  content](https://github.com/github/docs/blob/main/contributing/content-model.md#conceptual) in our content model.

You can then view our [Conceptual content template](https://github.com/github/docs/blob/main/contributing/content-templates.md#conceptual) and follow it to create the article.

The article should be created in the [education/managing-your-coursework](https://github.com/github/docs/tree/main/content/education/manage-coursework-with-github-classroom) directory.

The “About assignments” article should have the following sections, at least: 
  - **About assignments** - this should introduce users to what assignments are in GitHub, and give a high level overview of the prerequisites and features. We can reuse content from “[Creating individual assignments](https://docs.github.com/en/education/manage-coursework-with-github-classroom/create-an-individual-assignment)” and “[Creating group assignments](https://docs.github.com/en/education/manage-coursework-with-github-classroom/create-a-group-assignment)”, particularly the ‘About’ and prerequisites sections, plus some of the information on features we might want to highlight, such as choosing and configuring an IDE, providing starter code in a template repository and providing feedback. We should only briefly mention the two types of assignments, then perhaps link to the below section on “Types of assignments” for more information - so try not to go too much into depth in this section on the specific group vs. individual features. We can also mention the prerequisite to creating assignments is creating a classroom, and link to “[Creating a classroom](https://docs.github.com/en/education/manage-coursework-with-github-classroom/manage-classrooms#creating-a-classroom)” section of the “Manage classrooms” article. 
  - **Types of assignments** - this is where we should discuss the different types of assignments, individual versus group. We should clarify the differences between them, and give uses cases or examples of what each might be best used for. We can also reuse content from “[Creating individual assignments](https://docs.github.com/en/education/manage-coursework-with-github-classroom/create-an-individual-assignment)” and “[Creating group assignments](https://docs.github.com/en/education/manage-coursework-with-github-classroom/create-a-group-assignment)”, particularly the About section, to explain how each works
  - **Further reading (or Next Steps)**: We should have a section here that tells users where to go for next steps or further reading. We should definitely link to  “[Creating individual assignments](https://docs.github.com/en/education/manage-coursework-with-github-classroom/create-an-individual-assignment)” and “[Creating group assignments](https://docs.github.com/en/education/manage-coursework-with-github-classroom/create-a-group-assignment)”. We can also link to “[Manage classrooms](https://docs.github.com/en/education/manage-coursework-with-github-classroom/manage-classrooms)”, which is a prerequisite before creating assignments, and link to “Configure GitHub Classroom with an IDE(https://docs.github.com/en/education/manage-coursework-with-github-classroom/integrate-github-classroom-with-an-ide)”. Note that you can also include some of these specific links to notable features in the earlier sections when you mention them, then you may not need them in this section.

You will also need to update the "[Manage coursework with GitHub Classroom](https://raw.githubusercontent.com/github/docs/main/content/education/manage-coursework-with-github-classroom/index.md)" index file with a link to the article. It can be after ‘Manage classrooms’ and before ‘Creating an individual assignment”, in the “Teach with GitHub Classroom” map topic. 

### Additional information

This issue is for a special project and not currently available for contributors to work on.

**Comment by Perkles** [comment]
Hey ! I love Classroom. It will be a challenge, but can i have this one ?

**Comment by janiceilene** [comment]
Absolutely ⚡ Let us know if you have any questions! Also, feel free to ping me into your PR if you'd like a writer to give a [30% review](https://42floors.com/blog/startups/thirty-percent-feedback) as you work on it.

**Comment by Dziuniekhm** [comment]
> Hey ! I love Classroom. It will be a challenge, but can i have this one ?

**Comment by Luimoll** [comment]
[lighthouse-master.zip](https://github.com/github/docs/files/7270465/lighthouse-master.zip)

**Comment by cmwilson21** [comment]
Looks like stalebot closed this a bit early, so reopening it
