### ISSUE TITLE
The download links for GitHub destktop is not clear.

### ISSUE THREAD

**Issue by a0m0rajab** [github/docs#6346]
### What article on docs.github.com is affected?

[GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-github-desktop)

### What part(s) of the article would you like to see updated?

The download option is not showing anything when touching it. it goes to nowhere.

### Additional information

I got to that link by typing `GitHub desktop linux` on google. 
I know there is no linux version yet, but the link that I Have provided is not clearly specifying it and the link to download option is unvalid.

**Comment by a0m0rajab** [comment]
Choosing windows/mac would solve the problem but that's not such a great UX.

**Comment by janiceilene** [comment]
👋 @a0m0rajab I'm not sure I'm understanding. When I go to https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-github-desktop, I go down to the "Downloading and installing GitHub Desktop" section. Step 1 has a link that says, "download page for GitHub Desktop." When I click that link in Mac or Windows, it directs me to https://desktop.github.com/.

Is that what you're experiencing? Is something else not working for you?

**Comment by a0m0rajab** [comment]
I am a Linux user, when I get into the page it does not show anything as steps, maybe we could just write that it's still not available for linux. 

Here is a video related to that problem.

https://user-images.githubusercontent.com/18273833/118057929-a71b1100-b395-11eb-89ba-84f0c23d692d.mp4

**Comment by a0m0rajab** [comment]
if GitHub docs website detects the user operating system we could just add Linux tag in the website saying that's it's coming soon! this way would make it easier to understand. 

For me I was expecting to go somewhere when I saw the headers, did not think about it as anchors for the page.

**Comment by janiceilene** [comment]
@a0m0rajab That video was so helpful, thank you! I'll check in with the team about what the best option would be here 💖

**Comment by ajs256** [comment]
Hey there @a0m0rajab! I've just opened pull request #6595. It adds a note to the article you mentioned explaining that Desktop isn't available for Linux. If you could check out [the article in staging](https://docs-6595--patch-2.herokuapp.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/installing-github-desktop) and let me know what you think, that'd be great.
