### ISSUE TITLE
Confusing URLs in example gist responses for GitHub Enterprise

### ISSUE THREAD

**Issue by kpaulisse** [github/docs#6430]
### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@2.22/rest/reference/gists

### What part(s) of the article would you like to see updated?

The example response for "Create a gist" (and possibly others).

The URL in the example even for GHE is `https://api.github.com/gists/aa5a315d61ae9438b18d`

However, on a real GHE server, this is something more like: `https://github.example.com/api/v3/gists/aa5a315d61ae9438b18d`

The `html_url` is similarly confusing. `https://gist.github.com/aa5a315d61ae9438b18d` should be something more like `https://github.example.com/gist/some-user/aa5a315d61ae9438b18d`.

### Additional information

N/A

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @kpaulisse! This is something that we'll have to look into internally. I'll relay your comments to the team and close this out, thanks so much!
