### ISSUE TITLE
Provide Information About Additional Caching Options in "Caching Your GitHub Credentials in Git"

### ISSUE THREAD

**Issue by munnellg** [github/docs#6431]
### What article on docs.github.com is affected?
[Caching Your GitHub Credentials in Git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git)

https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git

### What part(s) of the article would you like to see updated?

This issue is related to #5841. Given that GitHub is migrating to token-based authentication for HTTPS Git requests, GitHub's documentation needs to provide more details on how to store and use Personal Access Tokens. This will be essential for minimising the disruption to peoples' workflows when username/password authentication is deprecated.

The existing "Caching Your GitHub Credentials in Git" article documents how to temporarily cache a PAT, but it does not explain that you can also store you PAT in a plain text file which a Git client can read. Ideally this article should contain most of (or all) the information in [this section](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) from Pro Git. The proposed solution is to either duplicate some of Pro Git's information into [Caching Your GitHub Credentials in Git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git), or provide a link to [Pro Git Section 7.14 Git Tools - Credential Storage](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) at the end of the article.

**Comment by githubnew-pro** [comment]
> ### چه مقاله ای در docs.github.com تحت تأثیر قرار می گیرد؟
> [در حال ذخیره اعتبارنامه GitHub در Git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git)
> 
> [https://docs.github.com/fa/github/getting-started-with-github/caching-yith-github-credentials-in-git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git)
> 
> ### دوست دارید کدام قسمت از مقاله را به روز کنید؟
> این شماره مربوط به [شماره 5841 است](https://github.com/github/docs/issues/5841) . با توجه به اینکه GitHub در حال انتقال به تأیید اعتبار مبتنی بر رمز برای درخواستهای HTTPS Git است ، اسناد GitHub باید جزئیات بیشتری در مورد نحوه ذخیره و استفاده از نشانه های دسترسی شخصی را ارائه دهد. این امر برای به حداقل رساندن اختلال در روند کار افراد هنگام تأیید اعتبار نام کاربری / گذرواژه ضروری است.
> 
> مقاله موجود "Caching Your GitHub Credentials in Git" نحوه ذخیره موقت یک PAT را مستند می کند ، اما توضیح نمی دهد که شما همچنین می توانید PAT خود را در یک فایل متنی ساده که مشتری Git می تواند بخواند ذخیره کنید. در حالت ایده آل ، این مقاله باید حاوی بیشتر (یا همه) اطلاعات [این بخش](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) از Pro Git باشد. راه حل پیشنهادی این است که یا برخی از اطلاعات Pro Git را به [Caching اعتبارنامه GitHub خود در Git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git) کپی کنید ، یا پیوندی به [Pro Git بخش 7.14 ابزارهای Git - ذخیره اعتبار](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) در پایان مقاله ارائه دهید.

**Comment by Rodgerscolby** [comment]
Jljg

**Comment by janiceilene** [comment]
@munnellg Thanks so much for opening an additional/followup issue! I'll get this triaged for the team to take a look 👀

**Comment by munnellg** [comment]
Great stuff! Thanks for that!

**Comment by lecoursen** [comment]
Hi again @munnellg! In order to avoid unnecessarily duplicating information, let's link to the Pro Git page with something like "For more options for storing your credentials, see..." We could also restrict the link to the Linux version of the page, since the Mac and Windows versions both suggest permanent storage options (oskeychain helper and wincred) rather than cache. You or anyone else is welcome to pick this up!

**Comment by munnellg** [comment]
Hi @lecoursen! Sounds good! I'll do exactly that and I'll open a pull request.
