### ISSUE TITLE
Incorrect statement for the permission of re-running workflow

### ISSUE THREAD

**Issue by BrightRan** [github/docs#644]
Associated GitHub Community topic: https://github.community/t/github-actions-permission-to-rerun-workflows/137683

According to the description in the docs about "[**Re-running a workflow**](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/re-running-a-workflow)",
> **Read** access to the repository is required to perform these steps.

But according to our tests, the fact is that if a collaborator is the “**`Read`**” or “**`Triage`**” role in a repository, he can't run, re-run, cancel and delete workflow runs. He can only view workflow runs in the repository.
Only when the collaborator is at least the “**`Write`**” role (**`Write`**, **`Maintain`** or **`Admin`**) can run, re-run, cancel and delete workflow runs in a repository.
This means that the collaborator must have the **write** access to re-run the workflow in the repository. It is obviously not consistent with the statement in the docs.
![roles](https://user-images.githubusercontent.com/46307996/96411471-17f0b500-121b-11eb-9f00-746c9e4f93e6.PNG)

**Comment by lucascosti** [comment]
Yep, you are correct @BrightRan! Anyone can feel free to open a PR to fix this 👍

**Comment by shati-patel** [comment]
@dianalogan fixed this in https://github.com/github/docs/pull/1182 😊
