### ISSUE TITLE
@ShreyaPrasad1209 It looks like you're assigned to a few other issues. I'm going to leave this one unassigned for now to let everyone have an opportunity to pick up a `bite sized` issue 💛

### ISSUE THREAD

**Issue by Modusto253** [github/docs#6484]
@ShreyaPrasad1209 It looks like you're assigned to a few other issues. I'm going to leave this one unassigned for now to let everyone have an opportunity to pick up a `bite sized` issue 💛

_Originally posted by @janiceilene in https://github.com/github/docs/issues/4851#issuecomment-840169939_

**Comment by ShreyaPrasad1209** [comment]
@emilyistoofunky please close this issue as this has been opened by some spam account!

**Comment by Modusto253** [comment]
Well yeah if you have the time I'd love your help personally babe I need
help slot with all my cryptos babe serious I need hella fucking help can ya
fo this with me!!
