### ISSUE TITLE
[Improvement]: Wrong code samples for the management console REST API docs

### ISSUE THREAD

**Issue by megbird** [github/docs#6485]
### What article(s) is affected?

https://docs.github.com/en/enterprise-server@3.0/rest/reference/enterprise-admin#management-console

### Briefly summarize the problem with the docs and its impact on GitHub's users.

All code samples for the Management Console API have the `/api/v3` which is unnecessary

### Describe the desired docs changes and the problem they solve for customers.

Let's take this as an example.

https://docs.github.com/en/enterprise-server@3.0/rest/reference/enterprise-admin#get-the-configuration-status--code-samples

The `shell` code sample is

```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  http(s)://{hostname}/api/v3/setup/api/configcheck
```

This is wrong. The correct endpoint URL is

```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  http(s)://{hostname}/setup/api/configcheck
```

All code samples in [this section](https://docs.github.com/en/enterprise-server@3.0/rest/reference/enterprise-admin#management-console) has the same error.

**Comment by Meegada-Mahesh** [comment]
hey @megbird. I have resolved the improvement suggested by you. But github action hook is throwing me error in PR, stating that The complete list of files we can't accept are: lib/rest/static/** .

I am a newbie to open source, i have followed guidelines for this contributions. Please let me know if any changes required.

**Comment by megbird** [comment]
👋  I'm so sorry, I mistook a small typo for a much larger issue. We'll have to fix this internally but are so grateful you gave it a shot! Closing this out and linking your PR so we can use it in our updates ❤️
