### ISSUE TITLE
workflows: multiline `if` conditions not working properly with `${{ }}`

### ISSUE THREAD

**Issue by nbusseneau** [github/docs#6508]
### What is the current behavior?

In the GitHub Actions documentations regarding workflows, the following is mentioned:

> When you use expressions in an `if` conditional, you may omit the expression syntax (`${{ }}`) because GitHub automatically evaluates the `if` conditional as an expression, unless the expression contains any operators. If the expression contains any operators, the expression must be contained within `${{ }}` to explicitly mark it for evaluation.

in two places:

- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
- https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions

#### I observed strange behaviour with multiline `if` conditions.

To demonstrate, here is a minimal repository reproducing the issues: https://github.com/nbusseneau/gh-workflows-if-demo
There are two workflows: [`not-working.yaml`](https://github.com/nbusseneau/gh-workflows-if-demo/blob/main/.github/workflows/not-working.yaml) and [`working.yaml`](https://github.com/nbusseneau/gh-workflows-if-demo/blob/main/.github/workflows/working.yaml).
As you may notice, the only difference between them is the `if` condition:

- `not-working.yaml` has `${{ }}` markers:
```yaml
    if: |
      ${{ (github.event.issue.pull_request && startsWith(github.event.comment.body, 'run-ci')) ||
      github.event_name == 'push' ||
      github.event.label.name == 'run-ci' }}
```

- `working.yaml` does not:
```yaml
    if: |
      (github.event.issue.pull_request && startsWith(github.event.comment.body, 'run-ci')) ||
      github.event_name == 'push' ||
      github.event.label.name == 'run-ci'
```

#### Expected

Both workflows are setup to be triggered by `push`, `issue_comment` (filtered by `run-ci` at beginning of comment), and `pull_request` (filtered by label name `run-ci`) events.

According to the documentation linked above, I would expect either of these to happen:

- Only the version with `${{ }}` markers works (because the `if` condition has operators).
- Both work (because maybe multiline `if` is implicitly wrapped in `${{ }}` at execution time).

But this is not what happens.

#### Observed behaviour

Look at this PR: https://github.com/nbusseneau/gh-workflows-if-demo/pull/1
There are two comments (`run-ci` and `Should not run CI, but does.`) and two labels (`run-ci` and `dont-run-ci`).
Now look at the Actions: https://github.com/nbusseneau/gh-workflows-if-demo/actions
Here is a screenshot for convenience:

![image](https://user-images.githubusercontent.com/4659919/118487041-9ca4a280-b71a-11eb-93c1-ef63d62a4475.png)

As we can see:

- Comments:
  - `run-ci` correctly triggered both workflows, and both got through.
  - `Should not run CI, but does.` correctly triggered both workflows, but only `working.yaml` got properly skipped as per the `if` condition. `not-working.yaml` seems to have ignored the `if` condition.
- Labels:
  - `run-ci` correctly triggered both workflows, and both got through.
  - `dont-run-ci` correctly triggered both workflows, but only `working.yaml` got properly skipped as per the `if` condition. `not-working.yaml` seems to have ignored the `if` condition.

This means that contrary to expectations, the `${{ }}` markers must NOT be provided for the multiline `if` condition to work as intended.

### What changes are you suggesting?

It depends.

- Is this considered a bug because it should NOT be working without `${{ }}` and should be working with the markers?
  - Bug should be fixed.
  - Ideally an announcement / breaking change log should be published so that workflows in the wild that currently are missing the markers get updated.
- Is this considered a bug because it should be working both with and without `${{ }}`?
  - Bug should be fixed.
- Is this considered not a bug, but working as intended?
  - Properly document how to work with multiline `if` conditions.
  - Ideally, also explain why, not only how, because in this instance the multiline `if` actual behaviour would be the exact opposite of what the docs currently states the `if` behaviour should be. Thus, more context around the inner implementation of `if` evaluation would be appreciated 😄 

### Additional information

I had first reported this to GH support (ticket 1114850).
They said this:
> I had a meeting with the Actions team and it does seem like it should have worked with `${{ }}` as well. However, they mentioned it is most likely not a bug, but more likely unclear or incorrect documentation.

which I found a bit confusing considering the two sentences seem to be in opposition.
But since they also recommended I open an issue on the public repo instead, here we are 🙏🏻

**Comment by janiceilene** [comment]
Thanks so much for opening an issue with so much detail @nbusseneau 😍 I'm not sure where an update should happen either, but I'll triage this for the team to take a look 👀

**Comment by ericsciple** [comment]
This looks like a bug to me, i will open an issue internally. I would expect both to work the same - i.e. with/without `${{ }}`

**Comment by lecoursen** [comment]
Thanks @ericsciple! @nbusseneau, thank you very much for brining this to the team's attention! Since we now have an internal issue to track this as a bug, I'm going to close this docs issue. ⚡

**Comment by nbusseneau** [comment]
@lecoursen Thanks. Do you want me to keep the minimal reproduction repository at https://github.com/nbusseneau/gh-workflows-if-demo up, or can I delete it?

**Comment by lecoursen** [comment]
I think you can deleted it. Thanks for checking!
