### ISSUE TITLE
Improvement: Add Keeper as a suggested service to a couple more articles

### ISSUE THREAD

**Issue by felicitymay** [github/docs#6535]
### What article on docs.github.com is affected?

- [Creating a strong password](https://docs.github.com/en/github/authenticating-to-github/creating-a-strong-password)
- [Configuring two-factor authentication](https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication)

### What part(s) of the article would you like to see updated?

Several of the docs articles list Keeper as a possible place to store passwords and secrets (for example, [Updating your GitHub access credentials](https://docs.github.com/en/github/authenticating-to-github/updating-your-github-access-credentials)). It would make sense to mention Keeper in these remaining two articles.

**Comment by StarTrooper08** [comment]
I would surely like to work on this issue . But can I get more on this issue!!

**Comment by janiceilene** [comment]
👋 @StarTrooper08 Thanks for picking up this issue! In these two articles:

- [Creating a strong password](https://docs.github.com/en/github/authenticating-to-github/creating-a-strong-password)
- [Configuring two-factor authentication](https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication)

find any place that already includes 1Password and add Keeper. Include a link, just like in [Updating your GitHub access credentials](https://docs.github.com/en/github/authenticating-to-github/updating-your-github-access-credentials). We're just letting users know that Keeper is another service they can use, along with 1Password and a few others.

Let me know if you have any additional questions!

**Comment by StarTrooper08** [comment]
Thanks @janiceilene 👍 .
I should start working on this issue.

**Comment by janiceilene** [comment]
@StarTrooper08 You're welcome to open a PR! Thank you 🎉

**Comment by craiglurey** [comment]
@StarTrooper08 I went ahead and made a pull request,  https://github.com/github/docs/pull/6814

**Comment by StarTrooper08** [comment]
Ok np .
I will take another issue.

**Comment by Lookin33** [comment]
Thank you guys. Any additional info would be awesome. Thanks gor the great work!
