### ISSUE TITLE
> > @lexis0291

### ISSUE THREAD

**Issue by lexis0291** [github/docs#6562]
> > @lexis0291 
> 
> _Originally posted by @lexis0291 in https://github.com/lexis0291/github-slideshow/pull/8#issuecomment-843572651_

_Originally posted by @lexis0291 in https://github.com/github/docs/issues/6561#issuecomment-843573600_

**Comment by jan1304** [comment]
Szia

**Comment by lexis0291** [comment]
> > > @lexis0291 
> > 
> > _Originally posted by @lexis0291 in https://github.com/lexis0291/github-slideshow/pull/8#issuecomment-843572651_
> 
> 
> 
> _Originally posted by @lexis0291 in https://github.com/github/docs/issues/6561#issuecomment-843573600_
