### ISSUE TITLE
Add a deprecation warning on the 'Available for hire' docs page

### ISSUE THREAD

**Issue by rlaphoenix** [github/docs#6574]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/what-does-the-available-for-hire-checkbox-do

### What part(s) of the article would you like to see updated?

The page gives a great explanation of what the checkbox does, great! But what if the user doesn't head to jobs.github.com to see that the entire point of the checkbox and the docs' explanation didn't matter as It's shutting down? Now that's a problem.

It would be ideal for the page to be reflected with information stating it's currently deprecated, and again when its fully shut down.

### Additional information

EDIT: After further research, another two locations which may benefit from a similar change could be https://docs.github.com/en/github/getting-started-with-github/github-glossary#github-jobs and https://docs.github.com/en/github/finding-talent-with-github-jobs

**Comment by 61004jack** [comment]
*
