### ISSUE TITLE
Missing user/password deprecation note 

### ISSUE THREAD

**Issue by ojacques** [github/docs#658]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/using-git/changing-a-remotes-url#switching-remote-urls-from-ssh-to-https

### What part(s) of the article would you like to see updated?

Despite the [deprecation notice](https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/) for username / password schemes, the article above still uses username / password.

The issue is about adding the deprecation notice.

### Additional information

Other parts of the documentation already refer to the deprecation notice using a macro such as [why-is-git-always-asking-for-my-password article](https://github.com/github/docs/blob/main/content/github/using-git/why-is-git-always-asking-for-my-password.md)

**Comment by djmareewish** [comment]
#951

**Comment by 5tvs04397** [comment]
ค

**Comment by janiceilene** [comment]
This was closed in https://github.com/github/docs/pull/659 🎉
