### ISSUE TITLE
Add information on how to connect Google Classroom to other IDEs

### ISSUE THREAD

**Issue by itko** [github/docs#6593]
### What article on docs.github.com is affected?

https://docs.github.com/en/education/manage-coursework-with-github-classroom/integrate-github-classroom-with-an-online-ide

### What part(s) of the article would you like to see updated?

Currently, the GitHub Classroom docs have information on working with Repl.it and MakeCode. It would be great to have a small section which mentions other IDEs that instructors can work with. By this, I mean IDEs which may not be natively supported within GitHub Classroom, but which can be manually integrated with Google Classroom relatively easily.

I work at Deepnote, so will use that as an example, but there are some other IDEs in this space. Deepnote is an online IDE for data science. It's free for everyone and integrates with GitHub, so it's quite popular in educational circles. We sometimes find that instructors try to use Deepnote in combination with Github Classroom and end up reaching out to us for assistance. Although we are working on our own documentation for this, it would be helpful for educators to find the information they need via the GitHub Classroom documentation. 

I think there are two ways to go about this:

- **Option 1**: Add a small section called _Other IDEs_ which includes links to different IDEs' documentation for integrating with GitHub Classroom. Something along the lines of `Besides these natively supported IDEs, there are other online IDEs which you can use: [bullet list with links to IDEs' documentation]`

- **Option 2**: Instead of linking externally to other IDEs' documentation, create individual pages for using different IDEs. Just like [this](https://docs.github.com/en/education/manage-coursework-with-github-classroom/integrate-github-classroom-with-an-ide/about-using-replit-with-github-classroom) and [this](https://docs.github.com/en/education/manage-coursework-with-github-classroom/integrate-github-classroom-with-an-ide/about-using-makecode-arcade-with-github-classroom)

Since I'm also working on Deepnote's own documentation for this, I would be happy to support this endeavor.

**Comment by janiceilene** [comment]
👋 @itko Thanks so much for opening an issue! We're not interested in adding any additional IDEs to the classroom docs at this time.

Thanks so much for your interest in improving the GitHub docs.
