### ISSUE TITLE
Unclear where to obtain `repositoryId` in GitHub GraphQL API's UpdateRepositoryInput

### ISSUE THREAD

**Issue by bodokaiser** [github/docs#6631]
### What article on docs.github.com is affected?

GitHub GraphQL API:

* [UpdateRepositoryInput](https://docs.github.com/en/graphql/reference/input-objects#updaterepositoryinput)

### What part(s) of the article would you like to see updated?

The input object `UpdateRepositoryInput` requires a property `repositoryId`.
However, it is unclear what `repositoryId` is or where to obtain `repositoryId`.

The [`Repository`](https://docs.github.com/en/graphql/reference/objects#repository) object has a property `databaseId`, maybe `databaseId = repositoryId`?

**Comment by janiceilene** [comment]
👋 @bodokaiser Thanks so much for opening an issue! Can you check in with our wonderful [support team](https://support.github.com/contact) about where to obtain `repositoryId` in GitHub GraphQL API's UpdateRepositoryInput? After you get an answer from them, please feel free to come back and comment in this issue or open a new one for the docs update 💖 

Thanks so much for your interest in improving the GitHub docs!

**Comment by bodokaiser** [comment]
@janiceilene Thank you for your respond. I don't see how any of these (see image) categories are suited for my support request?

<img width="759" alt="Screen Shot 2021-05-22 at 13 48 57" src="https://user-images.githubusercontent.com/1780466/119225515-7741db00-bb04-11eb-90d0-149f4ba526e8.png">

**Comment by hubwriter** [comment]
@bodokaiser - I believe `repositoryId` is simply the ID of the repository you want to update.
You can query for the repository's ID. For instance the following will return the ID of the github/docs repo:

```
repository(owner: "github", name: "docs") {
  id
}
```

**Comment by alannzi** [comment]
في ثلاثاء، ٢٥ مايو، ٢٠٢١ في ١١:١٥ ص، كتب hubwriter ***@***.***
>:

> @bodokaiser - I believe repositoryId is simply the ID of the repository
> you want to update.
> You can query for the repository's ID. For instance the following will
> return the ID of the github/docs repo:
>
> repository(owner: "github", name: "docs") {
>   id
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>
-- 
Google

**Comment by peeraw** [comment]
เมื่อ 25 พ.ค. 2021 15:27 น. Abode ***@***.***> เขียนว่า

في ثلاثاء، ٢٥ مايو، ٢٠٢١ في ١١:١٥ ص، كتب hubwriter ***@***.***

>:



> @bodokaiser - I believe repositoryId is simply the ID of the repository

> you want to update.

> You can query for the repository's ID. For instance the following will

> return the ID of the github/docs repo:

>

> repository(owner: "github", name: "docs") {

>   id

> }

>

> —

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly, view it on GitHub, or unsubscribe.

>

-- 

Google

**Comment by qoomon** [comment]
@bodokaiser @hubwriter actually the repository id is the `databaseId` in graphql API.
```graphql
query {
	repository(owner: "john-doe", name: "sandbox") {
	  databaseId
	} 
}
```
 In github actions it can also be obtained b< reading `GITHUB_REPOSITORY_ID´ environment variable.
