### ISSUE TITLE
SSH (backticks and absent command)

### ISSUE THREAD

**Issue by fluesvamp** [github/docs#6642]
### What article on docs.github.com is affected?

[Generating a new SSH key and adding it to the ssh-agent
](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

### What part(s) of the article would you like to see updated?

_Reduce the amount of provided OS specific information in the file._

Mac and Linux
```
$ eval "$(ssh-agent -s)"
> Agent pid 59566
```
Windows (uses backticks)  

_The command could be the same as on the above OSes._
```
# start the ssh-agent in the background
$ eval `ssh-agent -s`
> Agent pid 59566
```
[Adding your SSH key to the ssh-agent](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent)

_For Linux and Windows another line could be added accessing a new kill_ssh_agent.md file._

`4. {% data reusables.command_line.kill_ssh_agent %}`

kill_ssh_agent.md (proposed)

``````
Kill the current agent (given by the SSH_AGENT_PID environment variable).
```shell
$ eval "$(ssh-agent -k)"
> Agent pid 59566 killed
```
``````

Here's the sole reference to killing the agent PID.

```
$ grep -nr ssh-agent content | grep kill
content/github/authenticating-to-github/connecting-to-github-with-ssh/working-with-ssh-key-passphrases.md:84:The `ssh-agent` process will continue to run until you log out, shut down your computer, or kill the process.
$ 
```

_Perhaps the OS specific content regarding keychain could be hosted by the vendor and linked to._

<hr>

["Working with SSH key passphrases"](https://docs.github.com/en/articles/working-with-ssh-key-passphrases)

working-with-ssh-key-passphrases.md

[Mac version of the page]
Saving your passphrase in the keychain

_This content is perhaps dated._

[Windows version of the page]
Auto-launching `ssh-agent` on Git for Windows

_Perhaps this content could be shifted to a Wiki page._

### Additional information

If GitHub Inc. wants to hire me to review the entire repository send me an e-mail.

**Comment by janiceilene** [comment]
@fluesvamp Thanks for opening an issue! Please update your OP to use the [issue template](https://github.com/github/docs/blob/main/.github/ISSUE_TEMPLATE/improve-existing-docs.md), this helps us to triage issues to the right folks.

Can you also clarify why you'd like to see the changes you're suggesting? Thank you!

**Comment by fluesvamp** [comment]
@janiceilene

> ["Working with SSH key passphrases"](https://docs.github.com/en/articles/working-with-ssh-key-passphrases)
>
> Auto-launching `ssh-agent` on Git for Windows
>
> _Perhaps this content could be shifted to a Wiki page._

The translations of the Windows version of this page are also affected by #6753.

English

`<a href="#auto-launching-ssh-agent-on-git-for-windows">Auto-launching <code>ssh-agent</code> on Git for Windows</a>`

`<h3 id="auto-launching-ssh-agent-on-git-for-windows"><a href="#auto-launching-ssh-agent-on-git-for-windows">Auto-launching <code>ssh-agent</code> on Git for Windows</a></h3>`

Japanese

`<a href="#">Git for Windows で <code>ssh-agent</code> を自動的に起動する</a>`

`<h3 id=""><a href="#">Git for Windows で <code>ssh-agent</code> を自動的に起動する</a></h3>`

**Comment by janiceilene** [comment]
Thanks for the update @fluesvamp! I'll triage this for the team to take a look 👀

**Comment by lecoursen** [comment]
Hi @fluesvamp, thanks for all of these ideas! Let's unify the command for starting the ssh-agent in "Generating a new SSH key and adding it to the ssh-agent" across OSes, as you suggest. However, we'll keep "Working with SSH key passphrases" as is.

Could you please provide a bit more explanation of your proposed `new kill_ssh_agent.md` file? Thanks!

**Comment by fluesvamp** [comment]
@lecoursen

generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

```diff
- $ eval `ssh-agent -s`
+ $ eval "$(ssh-agent -s)"
```

I presume you concur on the above change.

generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

`1. {% data reusables.command_line.start_ssh_agent %}`

The above line appears in both the mac and linux content; it accesses start_ssh_agent.md.

> `4. {% data reusables.command_line.kill_ssh_agent %}`

The new file would close the socket and unset the shell variables.

**Comment by fluesvamp** [comment]
@lecoursen

> Perhaps the OS specific content regarding keychain could be hosted by the vendor and linked to.

I've sent an enquiry today to the macOS devs.

**Comment by lecoursen** [comment]
> I presume you concur on the above change.

Yes! 

> The new file would close the socket and unset the shell variables.

Thanks! Feel free to add that to https://github.com/github/docs/pull/6994 if you like! 😊

**Comment by fluesvamp** [comment]
@lecoursen

Created another branch for a separate PR.

Is it sufficiently unambiguous (with the changes) that one leaves the process running until one no longer needs it?

**Comment by lecoursen** [comment]
I'll link to that question in the PR, which someone on the team will review soon!

**Comment by fluesvamp** [comment]
@lecoursen

Can you ask a reviewer to look at this?

generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

```diff
  3. Add the SSH key to your account on {% data variables.product.product_name %}. For more information, see "[Adding a new SSH key to your {% data variables.product.prodname_dotcom %} account](/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account)."
  
+ {% note %}
+ 
+ **Note:** The ssh-agent will continue to run until you kill the process.
+ 
+ {% endnote %}
+  
  {% endwindows %}
```

<hr>

```diff
  3. Add the SSH key to your account on {% data variables.product.product_name %}. For more information, see "[Adding a new SSH key to your {% data variables.product.prodname_dotcom %} account](/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account)."
  
+ {% note %}
+ 
+ **Note:** The ssh-agent will continue to run until you kill the process.
+ 
+ {% endnote %}
+ 
  {% endlinux %}
```

**Comment by P-DUBB** [comment]
AIR/©®*~44216
