### ISSUE TITLE
Github Pages documentation does not detail step for changing master to main

### ISSUE THREAD

**Issue by ironandstee1** [github/docs#665]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site

### What part(s) of the article would you like to see updated?

As documented [here](https://github.com/github/renaming), github pages can be now be deployed from any branch. However, when making a google pages site today, I encountered a situation that can use clarifying. 

![image](https://user-images.githubusercontent.com/59491492/96516965-aa9a4f80-122d-11eb-92ba-b9ae25738968.png)

The repo defaults to deploying from master, at least on my end. Since the default name is now "main" instead of "master", if these instructions are followed by a newer user, they will likely spend time troubleshooting why their website doesn't appear. 

A step added to the section in the image below would clarify this for users and help in troubleshooting should their page not be available when following these instructions.

![image](https://user-images.githubusercontent.com/59491492/96517095-e6cdb000-122d-11eb-81e0-ea9f2710dbf3.png)

### Additional information

N/A

**Comment by janiceilene** [comment]
👋 @ironandstee1 Thanks for opening an issue! 

I'm not seeing anything in that particular article about choosing a branch to deploy your GitHub Pages site from, so I don't think there was much updated there around default branches. In the "[Creating your site](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site#creating-your-site)" section, there's a link in step 5 to the "[Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)" article. Do you think that article clarifies the new options to publish from any branch?

**Comment by janiceilene** [comment]
I didn't get an answer to this question and it's not in a state where we can take action right now. So I'm going to close this. If you have any other docs needs, let us know!
