### ISSUE TITLE
Why is GITHUB_BASE_REF and GITHUB_HEAD_REF set for PRs in non-forked repositories?

### ISSUE THREAD

**Issue by delenamalan** [github/docs#673]
# What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables

### What part(s) of the article would you like to see updated?

The documentation for `GITHUB_BASE_REF` and `GITHUB_HEAD_REF` says that they're both _"only set for forked repositories"_. However, when I create a create a pull request in a repository that is not forked, they are set to the base branch and branch to be merged in, respectively. See an example [here](https://github.com/delenamalan/github-actions-test/pull/1/checks?check_run_id=1280226900#step:3:15).

Is this expected behaviour? If yes, should the docs not be updated to reflect this?

![screenshot](https://user-images.githubusercontent.com/4767109/96572679-6a8aa980-12cd-11eb-80f6-a3b582c32a1a.png)

**Comment by StephanBijzitter** [comment]
Whether the docs are wrong, or this is a bug, I'm happy they are set.

 `refs/pull/{id}/merge` is quite useless if you just want to grab the branch name quickly.

**Comment by lucascosti** [comment]
👋 Thanks for opening this issue!

I suspect this is a docs bug, and that it should probably say something like "Only set for pull request events". I'll double-check with our engineering team to make sure that this is the intended behavior 👍

**Comment by lucascosti** [comment]
Yep, confirmed this is a docs bug! 🐛  Those environment variables are intended to be available for all PRs. I'll get the docs updated.

**Comment by delenamalan** [comment]
Thanks @lucascosti !

**Comment by lucascosti** [comment]
Just to close the loop, the fix is now live in production ✅ 🎉: https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
