### ISSUE TITLE
Link to GitHub Classroom content in other docs articles

### ISSUE THREAD

**Issue by saritai** [github/docs#6738]
[maintainer edit]
This issue is reserved for the MLH Fellowship program.

### What article on docs.github.com is affected?

This could effect a variety of GitHub articles, since we want to add links in articles, where it makes sense, to GitHub Classroom articles. 

### What part(s) of the article would you like to see updated?

Here are 4 examples of articles that could benefit from a link to GitHub Classroom articles: 
- “[Creating a template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository)” - To this article about template repositories, we can add a link to this GitHub Classroom article “[Create an assignment from a template repository](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-assignment-from-a-template-repository)” so that those learning how to create a template repository are aware they can be used in GitHub Classroom. 
- “[Create an individual assignment](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment#creating-a-pull-request-for-feedback)” - To this page in GitHub Classroom, the section “[Creating a pull request for feedback](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment#creating-a-pull-request-for-feedback)” which is specifically about enabling feedback pull requests to be automatically created for each student submission, we can add a link to this article, “[Leave feedback with pull requests](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/leave-feedback-with-pull-requests)” , which goes into more detail about how to leave feedback in those pull requests. 
- To either “[About integrations](https://docs.github.com/en/github/customizing-your-github-workflow/exploring-integrations/about-integrations)” or “[GitHub extensions and integrations](https://docs.github.com/en/github/customizing-your-github-workflow/exploring-integrations/github-extensions-and-integrations)”, we can link out to “[Integrate GitHub Classroom with an IDE](https://docs.github.com/en/education/manage-coursework-with-github-classroom/integrate-github-classroom-with-an-ide)”, in the context of giving an example of an integration with GitHub specific to education, allowing students to develop in an online IDE. 
- This is a bit more vague, but we could add a link in some page about GitHub Actions, such as “[About continuous integration](https://docs.github.com/en/actions/guides/about-continuous-integration)” to “[Use autograding](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/use-autograding)” as an example of one way continuous integration and GitHub Actions is used, in an education/classroom context. 

There may be other articles out there that could also use links to GitHub Classroom articles (including GitHub Classroom articles themselves) - feel free to explore and find other places! 

### Additional information

When you add the link, you would usually want to add it a new paragraph or a "Further reading" section if it doesn't fit in any of the existing sections. When we link to other articles, we often start with "For more information, see [link]". In this case, you could also say something like "To see an example of how [feature] is used in GitHub Classroom, see [link]" - whatever wording makes clear why they might find it useful or of interest to go to that link. 

For more information on how to add links to docs, see our [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#links).

**Comment by ShreyaPrasad1209** [comment]
> ### What article on docs.github.com is affected?
> This could effect a variety of GitHub articles, since we want to add links in articles, where it makes sense, to GitHub Classroom articles.
> 
> ### What part(s) of the article would you like to see updated?
> Here are 4 examples of articles that could benefit from a link to GitHub Classroom articles:
> 
> * “[Creating a template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository)” - To this article about template repositories, we can add a link to this GitHub Classroom article “[Create an assignment from a template repository](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-assignment-from-a-template-repository)” so that those learning how to create a template repository are aware they can be used in GitHub Classroom.
> * “[Create an individual assignment](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment#creating-a-pull-request-for-feedback)” - To this page in GitHub Classroom, the section “[Creating a pull request for feedback](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment#creating-a-pull-request-for-feedback)” which is specifically about enabling feedback pull requests to be automatically created for each student submission, we can add a link to this article, “[Leave feedback with pull requests](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/leave-feedback-with-pull-requests)” , which goes into more detail about how to leave feedback in those pull requests.
> * To either “[About integrations](https://docs.github.com/en/github/customizing-your-github-workflow/exploring-integrations/about-integrations)” or “[GitHub extensions and integrations](https://docs.github.com/en/github/customizing-your-github-workflow/exploring-integrations/github-extensions-and-integrations)”, we can link out to “[Integrate GitHub Classroom with an IDE](https://docs.github.com/en/education/manage-coursework-with-github-classroom/integrate-github-classroom-with-an-ide)”, in the context of giving an example of an integration with GitHub specific to education, allowing students to develop in an online IDE.
>> Under which heading do you want this to be added?
> * This is a bit more vague, but we could add a link in some page about GitHub Actions, such as “[About continuous integration](https://docs.github.com/en/actions/guides/about-continuous-integration)” to “[Use autograding](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/use-autograding)” as an example of one way continuous integration and GitHub Actions is used, in an education/classroom context.
>> could you add link of GitHub Actions page where you want to see the change?
> * There may be other articles out there that could also use links to GitHub Classroom articles (including GitHub Classroom articles themselves) - feel free to explore and find other places!
> 
> ### Additional information
> When you add the link, you would usually want to add it a new paragraph or a "Further reading" section if it doesn't fit in any of the existing sections. When we link to other articles, we often start with "For more information, see [link]". In this case, you could also say something like "To see an example of how [feature] is used in GitHub Classroom, see [link]" - whatever wording makes clear why they might find it useful or of interest to go to that link.
> 
> For more information on how to add links to docs, see our [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#links).

**Comment by harrycheng8** [comment]
#9182

**Comment by KamilJanLip** [comment]
g
i

**Comment by local-developer** [comment]
`arakanteam`

**Comment by Devarshini** [comment]
What You Will Need

Because GitHub classroom is built on GitHub and git infrastructure, it is important to understand some git and GitHub basics before using GitHub classroom. You and your students can get started with a working knowledge of just a few features, and we’ll summarize them here. Before starting, you should have the following:

   1. A GitHub Account: You and your students will each need a GitHub account.
    2.A git installation: Most Linux distributions have a package manager through which you can install a git client. There is a Git Bash utility for Windows that you can download and install as well. In these examples, I’ll be using Cygwin, a POSIX layer for Windows that provides a Linux-like shell terminal along with common GNU and Open Source tools like git. The commands used here will work in other environments, too. You can also use TortoiseGit on Windows for a graphical tool that integrates with Windows Explorer.
   3. Basic Experience with git: For an overview of git as a version control system, see my article on using Git with GitHub.

Using GitHub Classroom:

The basic workflow of GitHub classroom allows you to create a boilerplate repository that contains your assignment starter code and instructions, and to associate that boilerplate repository with an assignment. The assignment is then cloned as individual student repositories by your class, without requiring you to coordinate all the repositories and which students have which repositories. The workflow looks like this:

GitHub Classroom Workflow:

GitHub in the classroom provides a number of benefits with minimal setup requirements that you can re-use from class to class. These benefits include:

   1. It’s backed up, less worry about losing files
    Files can be cloned on other devices - this is nice for working at home or outside the classroom/lab
   2. Version history allows for rolling back and experimentation (can use branching in more advanced environments)
    3.Collaboration is facilitated with shared repositories, and you can track contributions to ensure mutual collaboration
   4. Students can ask for and receive help through Pull Requests
   5. Students can practice with industry standard tools and workflows

**Comment by abdrahmanovamir** [comment]
https://github.com/github/docs/projects/2#card-60913203

**Comment by abdrahmanovamir** [comment]
Super

**Comment by tracute3107** [comment]
yes !

**Comment by tracute3107** [comment]
> > ### Bài viết nào trên docs.github.com bị ảnh hưởng?
> > Điều này có thể ảnh hưởng đến nhiều bài viết trên GitHub, vì chúng tôi muốn thêm liên kết vào các bài viết, nếu nó có ý nghĩa, vào các bài viết trên GitHub Classroom.
> > ### Bạn muốn xem (những) phần nào của bài viết được cập nhật?
> > Dưới đây là 4 ví dụ về các bài viết có thể được hưởng lợi từ liên kết đến các bài viết trên GitHub Classroom:
> > 
> > * “ [Tạo kho lưu trữ mẫu](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository) ” - Đối với bài viết này về kho lưu trữ mẫu, chúng ta có thể thêm liên kết đến bài viết GitHub Classroom này “ [Tạo bài tập từ kho lưu trữ mẫu](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-assignment-from-a-template-repository) ” để những người đang học cách tạo kho lưu trữ mẫu biết chúng có thể được sử dụng trong Lớp học GitHub.
> > * “ [Tạo bài tập cá nhân](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment#creating-a-pull-request-for-feedback) ” - Đối với trang này trong Lớp học GitHub, phần “ [Tạo yêu cầu phản hồi cho phản hồi](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment#creating-a-pull-request-for-feedback) ” cụ thể là về việc cho phép tự động tạo yêu cầu phản hồi cho mỗi bài gửi của học sinh, chúng tôi có thể thêm liên kết đến bài viết này, " [Để lại phản hồi với các yêu cầu kéo](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/leave-feedback-with-pull-requests) ", đi sâu hơn về cách để lại phản hồi trong các yêu cầu kéo đó.
> > * Đối với “ [Giới thiệu về tích hợp](https://docs.github.com/en/github/customizing-your-github-workflow/exploring-integrations/about-integrations) ” hoặc “ [Tiện ích mở rộng và tích hợp GitHub](https://docs.github.com/en/github/customizing-your-github-workflow/exploring-integrations/github-extensions-and-integrations) ”, chúng tôi có thể liên kết đến “ [Tích hợp Lớp học GitHub với IDE](https://docs.github.com/en/education/manage-coursework-with-github-classroom/integrate-github-classroom-with-an-ide) ”, trong bối cảnh đưa ra ví dụ về tích hợp với GitHub cụ thể cho giáo dục, cho phép học sinh phát triển IDE trực tuyến.
> > 
> > > Bạn muốn điều này được thêm vào dưới tiêu đề nào?
> > 
> > 
> > 
> > * Điều này hơi mơ hồ hơn, nhưng chúng tôi có thể thêm một liên kết trong một số trang về Hành động GitHub, chẳng hạn như “ [Giới thiệu về tích hợp liên tục](https://docs.github.com/en/actions/guides/about-continuous-integration) ” để “ [Sử dụng tự động đăng ký](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/use-autograding) ” làm ví dụ về một cách tích hợp liên tục và Hành động GitHub được sử dụng, trong giáo dục / bối cảnh lớp học.
> > 
> > > bạn có thể thêm liên kết của trang Hành động GitHub nơi bạn muốn xem thay đổi không?
> > 
> > 
> > 
> > * Có thể có các bài viết khác cũng có thể sử dụng liên kết đến các bài viết trên GitHub Classroom (bao gồm cả chính các bài viết trên GitHub Classroom) - hãy khám phá và tìm các địa điểm khác!
> > 
> > ### Thông tin thêm
> > Khi bạn thêm liên kết, bạn thường muốn thêm vào nó một đoạn mới hoặc một phần "Đọc thêm" nếu nó không phù hợp với bất kỳ phần nào hiện có. Khi chúng tôi liên kết đến các bài viết khác, chúng tôi thường bắt đầu bằng "Để biết thêm thông tin, hãy xem [liên kết]". Trong trường hợp này, bạn cũng có thể nói điều gì đó như "Để xem ví dụ về cách [tính năng] được sử dụng trong Lớp học GitHub, hãy xem [liên kết]" - bất kỳ từ ngữ nào nói rõ lý do tại sao họ có thể thấy hữu ích hoặc quan tâm khi truy cập liên kết đó .
> > Để biết thêm thông tin về cách thêm liên kết vào tài liệu, hãy xem [hướng dẫn kiểu](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#links) của chúng tôi .

**Comment by Chubinne3** [comment]
Ok

**Comment by Roshan2401** [comment]
sir u writing accourding to youbi want in8wnwhat tonwtlrit3 n .  
cy; b

**Comment by Roshan2401** [comment]
k

**Comment by Roshan2401** [comment]
-
