### ISSUE TITLE
The sample response of the REST API pulls.listCommits is wrong

### ISSUE THREAD

**Issue by KengoTODA** [github/docs#674]
### What article on docs.github.com is affected?

- https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#list-commits-on-a-pull-request

### What part(s) of the article would you like to see updated?

The `Default response` is an array which contains `id: string` and `tree_id: string`, however, actual response does not have these properties.

Seems that [the old document](https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request) has proper response body. The interface of `octokit` also keeps consistency with the old document.

I cannot find which file I need to change, so I report this issue instead of sending a PR.

**Comment by lucascosti** [comment]
Thanks for reporting this, @KengoTODA. It looks like you are correct. Our API docs are generated from the API code, so we will have to fix this internally.

**Comment by lucascosti** [comment]
The fix for this should now be rolling out: https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#list-commits-on-a-pull-request 🎉

**Comment by KengoTODA** [comment]
Confirmed, thank you!
