### ISSUE TITLE
Problems with Table of Contents links in Japanese

### ISSUE THREAD

**Issue by book000** [github/docs#6753]
Before creating this issue, I was advised create an issue in #6653.

### What is the current behavior?

![20210525-141731-0vEtCje90d](https://user-images.githubusercontent.com/8929706/119443133-013baf00-bd64-11eb-902b-1e4ede204bfc.gif)

I am reading the github docs in Japanese. In some pages, the links in the table of contents seem to be broken. (For example, the [依存関係の更新の設定オプション (configuration-options-for-dependency-updates)](https://docs.github.com/ja/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates) in `package-ecosystem`).
The GIF image actually shows the situation where the link is not working properly and the href is not set correctly.

My guess is that the table of contents is generated automatically. So I don't know how to fix this.

### What changes are you suggesting?

You need to fix it in some way so that the table of contents link works properly.

### Additional information

- #6653

**Comment by fluesvamp** [comment]
> generated automatically

/translations/README.md

files in this directory are managed

<hr>

The original and translations of that page. 

English

In this article
package -ecosystem
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

简体中文 (Simplified Chinese)

本文内容
package-ecosystem
https://docs.github.com/cn/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#

日本語 (Japanese)

ここには以下の内容があります:
package-ecosystem
https://docs.github.com/ja/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#

Português do Brasil (Portuguese)

Neste artigo
package-ecosystem
https://docs.github.com/pt/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#

**Comment by book000** [comment]
Hmm ... I'm having trouble with the broken links in the table of contents, isn't it auto-generated?

**Comment by fluesvamp** [comment]
> auto-generated

The files in the /translations directory excepting the README are not manually edited.

Your GIF image indicates (under ここには以下の内容があります: ) you right-clicked on package-ecosystem and from the appearing context menu then clicked on Inspect element (Q).

English element

`<a href="#package-ecosystem"><code>package-ecosystem</code></a>`

Simplified Chinese, Japanese, and Portuguese elements

`<a href="#"><code>package-ecosystem</code></a>`

**Comment by book000** [comment]
I see, I overlooked that the `/translations` directory wasn't manually editable. I am very sorry.

I would like to issue a pull request to resolve this, if possible, for others as well. Can I solve this? Or should I wait for someone else to resolve it?

**Comment by fluesvamp** [comment]
The triage label is still on this issue.

**Comment by fluesvamp** [comment]
[OAuth アプリケーションの認可](https://docs.github.com/ja/github/authenticating-to-github/keeping-your-account-and-data-secure/authorizing-oauth-apps)

`<a href="#">OAuth Appのアクセス</a>`

`<h3 id=""><a href="#">OAuth Appのアクセス</a></h3>`

`<a href="#">OAuth App と Organization</a>`

`<h3 id=""><a href="#">OAuth App と Organization</a></h3>`

**Comment by janiceilene** [comment]
Thanks so much for opening the issue @book000! I've triaged it for our engineering team to take a look 👀
