### ISSUE TITLE
GitHub Actions on this repo are stuck

### ISSUE THREAD

**Issue by nschonni** [github/docs#678]
### What is the current behavior?

Currently the backlog is growing https://github.com/github/docs/actions?query=is%3Aqueued
There appears to be 2 jobs that stalled that seem to be blocking the queue https://github.com/github/docs/actions?query=is%3Ain_progress

### What changes are you suggesting?

Manually cancel the stuck jobs

/cc @chiedo

**Comment by chiedo** [comment]
Based on https://www.githubstatus.com/incidents/k46g5dn2c4lt I think we can close this out! And just restart actions as needed

**Comment by nschonni** [comment]
Yup, there is one from yesterday that still won't stop https://github.com/github/docs/actions?query=is%3Ain_progress but the rest of the queue has drained now
