### ISSUE TITLE
Intros for map topics on search

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#6793]
### What article on docs.github.com is affected?

Two map topics (task-based groupings of articles):
- “[Getting started with searching on GitHub](https://docs.github.com/en/github/searching-for-information-on-github/getting-started-with-searching-on-github)”
- “[Searching on GitHub](https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github)”

### What part(s) of the article would you like to see updated?

Each of these map topics needs an intro to help orient users to the content on the page. Intros should be one sentence long. For more information on writing intros, see:
- [Information about map topics](https://github.com/github/docs/blob/main/contributing/content-model.md#map-topic)” in the GitHub Docs content model, including guidance on map topic intros
- [Information about writing intros](https://github.com/github/docs/blob/main/contributing/content-model.md#intro) in the GitHub docs content model
- [Information about the `intro` frontmatter property](https://github.com/github/docs/tree/main/content#intro) in the GitHub Docs content directory README
- Make sure your intro is general enough to cover the content in each version of the page (use the version picker in the upper-right corner of the page to see what’s included on the page for different versions of GitHub)

### Additional information

This issue is for the Campus Experts + Docs program and is not available for contributors outside the program to work on.

**Comment by AnilSeervi** [comment]
The intros for the above stated pages were added in commit ae5d4137ede77716538ef30fb26080e0cd4611c7.
This issue can be closed now.

**Comment by ramyaparimi** [comment]
@AnilSeervi Thanks so much for letting us know. I am going to close this now  as this was fixed in ae5d4137ede77716538ef30fb26080e0cd4611c7 💖
