### ISSUE TITLE
Intros for articles on commits

### ISSUE THREAD

**Issue by emilyistoofunky** [github/docs#6797]
### What article on docs.github.com is affected?

Two articles:
- "[Comparing commits](https://docs.github.com/en/github/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits)"
- "[Differences between commit views](https://docs.github.com/en/github/committing-changes-to-your-project/viewing-and-comparing-commits/differences-between-commit-views)"

### What part(s) of the article would you like to see updated?

Each of these articles needs an intro to help orient users to the content on the page. Intros should be one sentence long. For more information on writing intros, see:
- [Information about writing intros](https://github.com/github/docs/blob/main/contributing/content-model.md#intro) in the GitHub docs content model
- [Information about the `intro` frontmatter property](https://github.com/github/docs/tree/main/content#intro) in the GitHub Docs content directory README
- Make sure your intro is general enough to cover the content in each version of the page (use the version picker in the upper-right corner of the page to see what’s included on the page for different versions of GitHub)

### Additional information

This issue is for the Campus Experts + Docs program and is not available for contributors outside the program to work on.

**Comment by FlyteWizard** [comment]
@emilyistoofunky Hello! I would like to take on this issue if possible! 😄

**Comment by janiceilene** [comment]
@FlyteWizard It's all yours!
