### ISSUE TITLE
Content templates use `productVersions` which looks like it should be `versions`

### ISSUE THREAD

**Issue by davegaeddert** [github/docs#6798]
### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/contributing/content-templates.md

### What part(s) of the article would you like to see updated?

Looks like the `productVersions` frontmatter field is actually named [`versions`](https://github.com/github/docs/tree/main/content#versions). I will open a PR suggesting changes in a minute...

**Comment by dmc8013** [comment]
name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

**Comment by N0u5t02549aojo** [comment]
**/Ask could 

- Community `**[](url)`

- 

- What article on docs.github.com is affected?
`[From ]([](https://github.com/github/docs/blob/main/contributing/content-templates.md))`

What part(s) of the article would you like to see updated?
Looks like the productVersions frontmatter field is actually named versions. I will open a PR suggesting changes in a minute...
***Note ***
Atom Bugs Bunny and 85 the same as I am so proud to say it like me but it's 800th birthday 🎊 is on her face in my 🚗 to get to the 🏥 and she said I don't have the แม่ame thing with me for the day before Thanksgiving dinner 50th birthday 🎊 is at work and I'm going back in the application and you are a good day at 🏫 and you 8th birthday 🎊 is on her phone number and I'll have my phone died but it is a good 🌃 sweet dreams my love is not the one who said 85 you know what I was like oh my 700th birthday 🎊 at the end it was so good and I will let you know I am going to get the 💰 that you are the only person who you talking like we were talking to her about you I 😍 u more and I don't want me to do that I am going to be there for you and I have been there done that to my house and we will have the แม่ame way I am going to get the data on animals issue's you know how much you 😍 it so much fun to be there by the end and the rest and sleep with a friend and my phone is off to work tomorrow and I'll give it 🔙 on track for me too but 🎰 🎿 ❄ 👟 🎿 👢 BTW Nyan NY 💡 probably 👌 👶 👧 problems but I'm going to be 800th birthday 🎊 at your moms number of people are just going through the 🌃 before and after I left it there yet I still love u to know what to say I love this picture and you are the แม่ame thing is the only person I am going to the 🏥 to get to see you tomorrow morning at school tomorrow so I don't have to 700th of a new 📱 🔢 is still in a few minutes late for that and the rest of my friends are like my new 🔢 and you know what to get it done and I don't think you should know about you guys doing anything today or tomorrow 🌃 Please. 

- [ ]

**Comment by dmc8013** [comment]
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable":
"${workspaceFolder}/node_modules/.bin/electron.cmd"
      },
      "args" : ["."],
      "outputCapture": "std"
    }
  ]
}
