### ISSUE TITLE
Possibly incorrect examples for content attachments / content references

### ISSUE THREAD

**Issue by dtakahas** [github/docs#6823]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/apps#create-a-content-attachment

### What part(s) of the article would you like to see updated?

We have a GitHub App that creates content attachments and we received an email that the `content_references` URL path was changing to have the repository owner and repository name prefixed to it:
```
https://api.github.com/content_references/1512/attachments

becomes

https://api.github.com/OWNER/REPOSITORY/content_references/1512/attachments
```
The examples in [the article](https://docs.github.com/en/rest/reference/apps#create-a-content-attachment) appear to have been updated that way. However when I tried to update our app, I was receiving 404s. My colleague had a hunch and it began working again when we added the prefix `/repos/` before the owner/repo part (e.g. `https://api.github.com/repos/OWNER/REPOSITORY/content_references/1512/attachments`)

Does that article possibly need to be corrected to have that prefix in the URLs?

**Comment by janiceilene** [comment]
Thanks for opening an issue @dtakahas! I'll triage this for the team to take a look 👀

**Comment by lucascosti** [comment]
Thanks for noticing and reporting this, @dtakahas 🙇‍♂️ 

Yep, you are correct; this was an error with that recent update 🙁.  It has been fixed internally, and the docs have recently been updated: https://docs.github.com/en/rest/reference/apps#create-a-content-attachment
