### ISSUE TITLE
Clarify secret limits

### ISSUE THREAD

**Issue by jsoref** [github/docs#6911]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/encrypted-secrets#limits-for-secrets

### What part(s) of the article would you like to see updated?

```diff
-You can store up to 1,000 secrets per organization, 100 secrets per repository, and 100 secrets per environment. A workflow may use up to 100 organization secrets and 100 repository secrets. Additionally, a job referencing an environment may use up to 100 environment secrets.
+Each organization can store up to 1,000 organization secrets, each repository 100 repository secrets, and each environment 100 environment secrets. A workflow may use up to 100 organization secrets and 100 repository secrets. Additionally, a job referencing an environment may use up to 100 environment secrets.
```

### Additional information

https://github.community/t/limits-for-secrets/159633/3

**Comment by janiceilene** [comment]
Thanks for opening an issue @jsoref! I'll triage this for the team to take a look 👀

**Comment by lucascosti** [comment]
Thanks for this suggestion, @jsoref! We are actually in the middle of rewording this content internally to make the limits more clear, and the changes should be published soon. 🚀
