### ISSUE TITLE
Maven caching dependencies not working.

### ISSUE THREAD

**Issue by ankur512512** [github/docs#6920]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven

### What part(s) of the article would you like to see updated?

This should change-->  restore-keys: ${{ runner.os }}-m2
To this--> restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

**Comment by Davidjaqi** [comment]
runner.os '-m2-'hashFiles('**/pom.xml')

**Comment by janiceilene** [comment]
We decided not to make this change. See more information in https://github.com/github/docs/pull/6921#issuecomment-853520723 💛
