### ISSUE TITLE
Add intros to GraphQL pages

### ISSUE THREAD

**Issue by ethanpalm** [github/docs#6969]
### What article on docs.github.com is affected?

- "[Input objects](https://docs.github.com/en/graphql/reference/input-objects)"
- "[Unions](https://docs.github.com/en/graphql/reference/unions)"
- "[Scalars](https://docs.github.com/en/graphql/reference/scalars)"
- "[Objects](https://docs.github.com/en/graphql/reference/objects)"

### What part(s) of the article would you like to see updated?

Each of these articles needs an intro to help orient users to the content on the page and what each data type in the GraphQL API schema can be used for. Intros should be one sentence long and define what the feature is.

For these four articles, the first sentence in the "About" sections can be cut and pasted for the intro (but do not include any hyperlinks).

For more information about writing intros, see:

- [Information about writing intros](https://github.com/github/docs/blob/main/contributing/content-model.md#intro) in the GitHub docs content model
- [Information about the `intro` frontmatter property](https://github.com/github/docs/tree/main/content#intro) in the GitHub Docs content directory README

**Comment by ajs256** [comment]
Hi, may I work on this for Hacktoberfest? I noticed the campus experts label was removed, but the issue description still mentions it. Is this issue only for campus experts?

**Comment by ramyaparimi** [comment]
@ajs256 Thank you for the question!! You can work on this one ✨ Please link your PR with this issue when ready 🐬 🔗
