### ISSUE TITLE
Document how to contain code blocks within code blocks

### ISSUE THREAD

**Issue by skedwards88** [github/docs#6981]
### What article on docs.github.com is affected?

[Creating and highlighting code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

### What part(s) of the article would you like to see updated?

We should document how to display triple backticks (indicating a code block) within code blocks. You can do this by encompassing the triple backtick code block with a quadruple backticks. For example, look at the raw markdown of this snippet:

````
```
Look! You can see my backticks.
```
````

**Comment by ShubhamPalriwala** [comment]
Hey @skedwards88, Would love to resolve this good small issue!
Let me know if I can proceed with it.

**Comment by skedwards88** [comment]
@ShubhamPalriwala That would be great! 💖

**Comment by ShubhamPalriwala** [comment]
Hey @skedwards88, I'm thinking of just adding this as a note under `Fenced Code Block` [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks).
The note would basically have a text about how you can include backticks too in a fenced block along with a standard markdown raw and an ouput.
Creating a separate section would just be redundant!

Pleasr let me know your thoughts on this

**Comment by skedwards88** [comment]
>  I'm thinking of just adding this as a note under Fenced Code Block here.

That's perfect!

**Comment by ShubhamPalriwala** [comment]
Okay so I have 2 ideas right now, I'd like to know your opinions on them:
- Option 1:
Note with code snippets
![image](https://user-images.githubusercontent.com/55556994/120694758-319fed80-c4c8-11eb-8595-aca55402a615.png)

- Option 2:
Just a note
![image](https://user-images.githubusercontent.com/55556994/120694831-41b7cd00-c4c8-11eb-982b-6eadd3c8407d.png)


I feel that just a note is enough for a user to figure it out.
Let me know which one to proceed with!

**Comment by portfine** [comment]
J U S T  N O T E.

Output,*,com,dir,"compiler" ! sometimes it's message in game but CDM doo nothing for user interface :

Yeah memory issues I've gotten words
 }
Compiler error option 1
Distribution cast option 2
{
#6880 
~~😝~~
```
Wiz ere 2021
```

**Comment by ShubhamPalriwala** [comment]
> Okay so I have 2 ideas right now, I'd like to know your opinions on them:
> 
> * Option 1:
>   Note with code snippets
>   ![image](https://user-images.githubusercontent.com/55556994/120694758-319fed80-c4c8-11eb-8595-aca55402a615.png)
> * Option 2:
>   Just a note
>   ![image](https://user-images.githubusercontent.com/55556994/120694831-41b7cd00-c4c8-11eb-982b-6eadd3c8407d.png)
> 
> I feel that just a note is enough for a user to figure it out.
> Let me know which one to proceed with!

@skedwards88 Can you let me know which one do we prefer?

**Comment by skedwards88** [comment]
> Okay so I have 2 ideas right now, I'd like to know your opinions on them:
> 
> * Option 1:
>   Note with code snippets
>   ![image](https://user-images.githubusercontent.com/55556994/120694758-319fed80-c4c8-11eb-8595-aca55402a615.png)
> * Option 2:
>   Just a note
>   ![image](https://user-images.githubusercontent.com/55556994/120694831-41b7cd00-c4c8-11eb-982b-6eadd3c8407d.png)
> 
> I feel that just a note is enough for a user to figure it out.
> Let me know which one to proceed with!

Thanks for brainstorming these ideas! I think both stating as well as giving an example will be most helpful. How about putting the text in the note as text above the example instead?

e.g. 

To display triple backticks in a fenced code block, wrap them inside quadruple backticks.

````
```
Look! You can see my backticks.
```
````

**Comment by ShubhamPalriwala** [comment]
Thanks for the feedback @skedwards88.
I've added the codeblock as well as the example png. Please have a look at my PR and let me know if any changes are needed!

**Comment by Arifulislamsourv** [comment]
OK no problem
