### ISSUE TITLE
Empty bullet point on Github index page

### ISSUE THREAD

**Issue by capablemonkey** [github/docs#6983]
Hi! I'd like to report a small typo. 😄  

### What article on docs.github.com is affected?

https://docs.github.com/en/github

### What part(s) of the article would you like to see updated?

The last bullet point in this index page is empty.

### Additional information

<img width="470" alt="Screen Shot 2021-06-01 at 1 51 53 PM" src="https://user-images.githubusercontent.com/1661310/120388874-8ed94a80-c2e0-11eb-828f-2971e684f3b3.png">

I'm not too familiar with this repo, but from skimming around, here's my guess for why this is happening.  Please forgive me if I'm way off!

It looks like this was introduced by #6586 as part of the new site tree content migration.  I think this empty bullet point is due to [/content/github/index.md:36](https://github.com/github/docs/blame/main/content/github/index.md#L36):

```
 - /site-policy-deprecated
```

The [index.md](https://github.com/github/docs/blame/main/content/github/site-policy-deprecated/index.md#L4) for `site-policy-deprecated` contains the frontmatter `hidden: true` which might have something to do with why the bullet on its parent index is blank.  

My guess is that we added `/site-policy-deprecated` in order to continue to honor the links in that subtree (the site will [only include paths](https://github.com/github/docs/blob/b0664474e648d8b515032d31228788b0486fa974/content/README.md#index-pages) defined as children) but did not want this section to be visible in the index and toc.  I don't know how children are turned into items in the list in question, but we might want to avoid making a new list item if the child has `hidden: true`.

Hope that helps!

**Comment by Roverclover** [comment]
I have no clue

**Comment by janiceilene** [comment]
Thanks so much for opening an issue and providing so much detail @capablemonkey! I'll triage this for the team to take a look 👀

**Comment by capablemonkey** [comment]
> Thanks so much for opening an issue and providing so much detail @capablemonkey! I'll triage this for the team to take a look 👀

Happy to help!  Thanks for triaging so quickly @janiceilene! 😊

**Comment by r-ush** [comment]
Hey @janiceilene, Would love to resolve this good small issue!

Let me know if I can proceed with it.

**Comment by r-ush** [comment]
Hey @janiceilene, Would love to resolve this issue!

Let me know if I can proceed with it.

**Comment by janiceilene** [comment]
Thank you so much for the offer @r-ush! I just spoke with our engineering team and they're already working on this one internally with a few other fixes. I'm going to close this issue now 💛

**Comment by sarahs** [comment]
@capablemonkey Just wanted to let you know this is fixed! Thanks again for reporting it. 👍

**Comment by capablemonkey** [comment]
> @capablemonkey Just wanted to let you know this is fixed! Thanks again for reporting it. 👍

Wow! That was fast!  My pleasure. Thanks for the update!  😄
