### ISSUE TITLE
Add Erlang/Elixir to supported dependabot package ecosystems

### ISSUE THREAD

**Issue by abangser** [github/docs#6998]
### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems

### What part(s) of the article would you like to see updated?

We currently use dependabot to support our application and I would like to see that reflected here to support conversations with auditors about how we handle patch updates for our tools.

### Additional information

Example use of dependabot in our app for [iso8601](https://github.com/erlsci/iso8601):
![image](https://user-images.githubusercontent.com/1557346/120457891-bb4ba000-c38e-11eb-8c8d-a44dd0f7ead0.png)

**Comment by silikona** [comment]
На ср, 2.06.2021 г., 12:52 ч. Lookin33 ***@***.***> написа:

> I know this if I wasn’t on my period right now gross… I would so fuck you
> at my shop right now I’m too tired to drive home and I’m just sitting here
>
> Sent from my iPhone
>

**Comment by janiceilene** [comment]
Thanks for opening an issue @abangser! I'll triage this for the team to take a look 👀

**Comment by felicitymay** [comment]
Hi @abangser 👋🏻 

> We currently use dependabot to support our application and I would like to see that reflected here to support conversations with auditors about how we handle patch updates for our tools.

It's great to hear that you use Dependabot to support your application. I think you can direct your auditors to the article about Dependabot version updates. This has a table showing which package managers are supported for Dependabot version updates: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates#supported-repositories-and-ecosystems. Hex provides support for Erlang and Elixir.

**Comment by abangser** [comment]
Doh! So sorry for the noise. I was in the wrong spot. Thanks so much for the prompt reply.

**Comment by felicitymay** [comment]
I'm glad that I was able to help and it's always good to hear from people who are using our products 😄
