### ISSUE TITLE
GPG Creation on linux

### ISSUE THREAD

**Issue by JakobMielke** [github/docs#7015]
### What article on docs.github.com is affected?

<a href="https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/telling-git-about-your-signing-key">Telling Git about your signing key</a>

### What part(s) of the article would you like to see updated?

I'm opening this issue in regards to step 5 in the Linux GPG guide.
> To add your GPG key to your bash profile, run the following command:
> <code>
> $ if [ -r ~/.bash_profile ]; then echo 'export GPG_TTY=$(tty)' >> ~/.bash_profile; \
>   else echo 'export GPG_TTY=$(tty)' >> ~/.profile; fi
> </code>

I think that it needs some elaboration since it only tells you to add your key to your <code>.bash_profile</code>, and doesn't give any explanation as to why one should do so.

**Comment by janiceilene** [comment]
👋 @JakobMielke Thanks for opening an issue! Do you have any thoughts about what we should add? Any thoughts on the specific language, use case, or phrasing?

**Comment by JakobMielke** [comment]
I think that some explanation for why you are supposed to add your GPG key to your <code>.bash_profile</code> would be nice. Personally I do not know why one should do so, which is why opened this issue.

**Comment by fluesvamp** [comment]
> In regards to step 5 in the Linux GPG guide.

[GnuPG](https://www.gnupg.org/documentation/manuals/gnupg/index.html)

• [Invoking GPG-AGENT](https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html):  How to launch the secret key daemon.

"`.bashrc` or whatever initialization file is used"

<hr>

For the result of the command `export GPG_TTY=$(tty)` one can type `printenv  | grep GPG_TTY`.

**Comment by dani3lcruise** [comment]
can I know which language you are writing code?

**Comment by kw4k10** [comment]
polish

czw., 3 cze 2021 o 11:44 Daniel Cruise ***@***.***>
napisał(a):

**Comment by janiceilene** [comment]
Thanks @JakobMielke I'll triage this for the team to take a look!

**Comment by felicitymay** [comment]
Hi @JakobMielke - thanks for asking about this.

I don't use Linux but it looks as if adding your GPG key to your bash profile is the best way to ensure that your GPG agent knows how you want to enter the passphrase for the key, otherwise you're likely to get an error. For more information, see: https://roelofjanelsinga.com/articles/how-to-setup-gpg-signing-keys-in-github/ and https://sabbour.me/setting-up-signed-git-commits-on-macos/.

**Comment by corneliusroemer** [comment]
If you add something specific for `bash`, please also add something for `zsh` (MacOS default). One should probably just add the following plugin as explained: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gpg-agent

**Comment by dani3lcruise** [comment]
@felicitymay thanks for the detailed explanation, I also don't know since I'm on a Linux backend.

**Comment by dani3lcruise** [comment]
Sorry didn't quite didn't catch up to your level of coding but will do so
like it, in the meantime check out my website also,
https://www.quillscriptures.business.site

Sorry for the inconvenience caused,

With Best Regards,
Daniel

**Comment by felicitymay** [comment]
@JakobMielke - Thanks for raising this. I hope that my explanation above (https://github.com/github/docs/issues/7015#issuecomment-856546986) helps. Since I can't test this, I'm going to close this issue. Do reopen this issue if you're able to confirm that my explanation is correct.
