### ISSUE TITLE
Marketplace action Verified action link is bad

### ISSUE THREAD

**Issue by jsoref** [github/docs#7026]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions
https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-actions

### What part(s) of the article would you like to see updated?

I think fixing the inbound link to point elsewhere is a better solution than "fixing" the content of `finding-and-customizing-actions`. But, alternatively, if this page really wants to have this content, it needs its own section and better content.

### Additional information

The page in question is:

> # Finding and customizing actions
> ### Actions are the building blocks that power your workflow. A workflow can contain actions created by the community, or you can create your own actions directly within your application's repository. This guide will show you how to discover, use, and customize actions.

### Steps

1. Visit https://github.com/marketplace/actions/setup-go-environment
2. See 
![image](https://user-images.githubusercontent.com/2119212/120578780-5b87e000-c3f4-11eb-9a06-c1799f091b29.png)
3. Click [Learn more about verified Actions](https://docs.github.com/actions/automating-your-workflow-with-github-actions/using-github-marketplace-actions).

### Actual Results

> #### In this article
> ##### Overview
> ##### Browsing Marketplace actions in the workflow editor
> ##### Adding an action to your workflow
> ##### Using release management for your custom actions
> ##### Using inputs and outputs with an action
> ##### Referencing an action in the same repository where a workflow file uses the action
> ##### Referencing a container on Docker Hub
> ##### Next steps

#### Problems

1. *NONE* of these section titles have the word `verified`.
There is a single hit for the word `verified` in the page:
   > 3 . To the right of the editor, use the GitHub Marketplace sidebar to browse actions. Actions with the  badge indicate GitHub has _verified_ the creator of the action as a partner organization.
   - Note that this doesn't relate to the page from which the user started.
2. This user experience is *Horrible*.
3. It doesn't actually explain to end users how GitHub verified creators.
4. There's actually a slightly better page: https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-actions

#### Suggested action

Ask the github.com/marketplace/actions team to change their link to point to: https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-actions

**Comment by janiceilene** [comment]
👋 @jsoref Thanks for opening an issue! The best place to send your feedback is to https://support.github.com/contact/feedback 💛 It'd be great to let them know where you're finding the inbound link and which doc you think would be a better fit! They can route that to the correct team ⚡

**Comment by jsoref** [comment]
@janiceilene: It's really expensive for me to use support.github.com, I do it multiple times per day, and on average nothing useful comes of it. Since it's your content that they're linking to, it'd be really helpful if your team pushed back at them instead of making the customer do it.
