### ISSUE TITLE
Search results don't handle images

### ISSUE THREAD

**Issue by jsoref** [github/docs#7029]
### What is the current behavior?

1. Visit https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions?query=verified+action
2. Scroll down to:

    #### About marketplace badges: For GitHub [action](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-actions)s
    Actions with the , or verified creator badge, indicate that GitHub has verified the creator of the action as a partner organization. For information on how to publish a GitHub action to GitHub Marketplace,
![image](https://user-images.githubusercontent.com/2119212/120579768-12d12680-c3f6-11eb-8ae2-bfd7b1d031f9.png)

3. Click the [result](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-actions) 
![image](https://user-images.githubusercontent.com/2119212/120580508-50827f00-c3f7-11eb-84f5-cc71b35176f4.png)
    #### For GitHub actions
    Actions with the <img alt="check in flower" src="https://user-images.githubusercontent.com/2119212/120580656-90496680-c3f7-11eb-92f8-c6a63b7f8c9b.png" width="14" height="14">, or verified creator badge, indicate that GitHub has verified the creator of the action as a partner organization.

**Comment by janiceilene** [comment]
Huh, that's an interesting bug! I'll triage this for the engineering team to take a look. Thanks @jsoref!

**Comment by chiedo** [comment]
Thank you for reporting this @jsoref! But for the time being we've decided to continue not rendering images in the search results.
