### ISSUE TITLE
Firefox allows image pasting, but it isn't documented.

### ISSUE THREAD

**Issue by KTibow** [github/docs#704]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

### What part(s) of the article would you like to see updated?

The part here:
![image](https://user-images.githubusercontent.com/10727862/96807555-b459b980-13cb-11eb-81dd-769fc188ce81.png)
I've tested this in Firefox, and it works just fine (that's how I put in that image). I think it should probably include Firefox in there.

**Comment by janiceilene** [comment]
Thanks for letting us know @KTibow!

**Comment by KTibow** [comment]
Fixed in #705
