### ISSUE TITLE
GHES GraphQL schema URLs are incorrect/missing

### ISSUE THREAD

**Issue by ShineyDev** [github/docs#709]
### What is the current behavior?

https://docs.github.com/public/enterprise-server@2.22/schema.docs-enterprise.graphql, along with the other GHES schemas, 404s. This URL is was found on [this page](https://docs.github.com/en/enterprise-server@2.22/graphql/overview/public-schema).

### What changes are you suggesting?

The URLs should be fixed or the articles should be removed.

### Additional information

N/A

**Comment by ChuVienTran** [comment]
Good

**Comment by ChuVienTran** [comment]
Good

**Comment by lucascosti** [comment]
Thanks for reporting this, @ShineyDev! It looks like the issue has already been fixed.

The URL on this page: https://docs.github.com/en/enterprise-server@2.22/graphql/overview/public-schema, now points to the proper file (https://docs.github.com/public/ghes-2.22/schema.docs-enterprise.graphql)
