### ISSUE TITLE
Github action defined as submodule in a repo are not checked out

### ISSUE THREAD

**Issue by PuneethaPai** [github/docs#713]
Apology for raising this issue here. Couldn't find a write forum for this.
I have already raised a query in Github Support Community: https://github.community/t/github-action-defined-as-submodule-in-a-repo/139204?u=puneethapai

Details:
---
`jobs.steps.uses` can refer to action defined over a public repo, docker, etc.

If action defined over a subdir you can refer to it like: `{owner}/{repo}/{path/to/action}@{ref}`

docs example: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-a-public-action-in-a-subdirectory
```yaml
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: actions/aws/ec2@main
```

### But this fails if `path/to/action` is actually a git sub-module to the repo defining the action.

I get following error like 
``` Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/PuneethaPai/checkout/submodule/.github/actions/checkout'. Did you forget to run actions/checkout before running your local action?```.

So I think when action is defined in a public repo, git-runner clones it, but doesn't clone the sub-modules defined in them. Hence I am getting above error.

Workaround is to check-in the whole action code in the path, but it's not a best way when you have advantages of adding it as sub-module thingy.

**Comment by janiceilene** [comment]
👋 Thanks for opening an issue @PuneethaPai! I'll triage this for review and the team can check out whether there's any clarity should add in the docs.

**Comment by lucascosti** [comment]
👋 @PuneethaPai. It looks like you troubleshooted this [in the community forum thread](https://github.community/t/github-action-defined-as-submodule-in-a-repo/139204). Yes, for the local subdirectory option for `uses:` the actual files for the action need to be present. Because submodules usually only contain a reference to the submodule repository (and not all the files), it won't work for actions.
