### ISSUE TITLE
[GitHub Packages registry] Missing "Using a package" with Apache Maven and Gradle registries

### ISSUE THREAD

**Issue by rachelcarmena** [github/docs#7142]
### What article on docs.github.com is affected?

* Working with a GitHub Packages registry
  * [Working with the Apache Maven registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry)
  * [Working with the Gradle registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry)  

### What part(s) of the article would you like to see updated?

Those pages have these sections:

* Authenticating to GitHub Packages
* Publishing a package
* Installing a package

And I missed this section:

* Using a package

because it's not necessary to install a package to use it.

### Additional information

I published artifacts into GitHub Packages registry and I could use them from another repository without installing them. Just adding the repository where the dependencies can be found. **It worked like a charm, congrats and thank you so much!!** :raised_hands: 

I think that missing section could be interesting for other users to simplify the use of Apache Maven and Gradle registries.

**Comment by legranchionew** [comment]
ok thank yuo

**Comment by skedwards88** [comment]
Thank for for this issue! I'm going to close it based on [this comment in the PR](https://github.com/github/docs/pull/7143#issuecomment-867806254).
