### ISSUE TITLE
Tooltip for "images are on" button can't be seen when resizing window (mobile also).

### ISSUE THREAD

**Issue by DetEMagic** [github/docs#7151]
### What is the current behavior?
The entire message is not visible when hovering the button when you resize the screen. Same for mobile. I am currently using chrome and have tested it on Firefox. However, this should be a cross browser issue.

Example page for where this is happening (scroll the entire way down): https://docs.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication-recovery-methods
## Picture
![image](https://user-images.githubusercontent.com/61417797/121082527-8308ef00-c7de-11eb-85fc-5b6ec7f3c007.png)

### What changes are you suggesting?
I want the entire message to be displayed.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @DetEMagic! That is wonky 🙃 I'll triage this for the team to take a look.

**Comment by janiceilene** [comment]
I just checked in with engineering and we're going to work on this one internally. Thanks so much for letting us know, I'll close this now ✨
