### ISSUE TITLE
Domains missing for self-hosted runners

### ISSUE THREAD

**Issue by paliwalvimal** [github/docs#7180]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github

### What part(s) of the article would you like to see updated?

sub-domains for *.actions.githubusercontent.com (artifactcache.actions.githubusercontent.com, pipelines.actions.githubusercontent.com) are CNAME records instead of A pointing to star-actions-githubusercontent-com.l-0007.l-msedge.net which further points to l-0007.l-msedge.net as a CNAME record. We have our infrastructure hosted on AWS and are using DNS firewall for restricting external traffic. That being said, it was quite hard to find the reason but I finally found it and once I added the mentioned two sub-domains self-hosted runners were able to pick up jobs

**Comment by legranchionew** [comment]
CNAME records instead of A pointing to star-actions-githubusercontent-com.l-0007.l-msedge.net which further points to l-0007.l-msedge.net as a CNAME record. I am change source of file .html for adress of view-source:star-actions-githubusercontent-com.l-0007.l-msedge.net

**Comment by lucascosti** [comment]
Closed per https://github.com/github/docs/pull/7181#issuecomment-867265545

**Comment by legranchionew** [comment]
***@***.***

Hi. Can you tell me the contract will be done for today or i have to wait
for tomorrow. I need to plan my time for organizational issues such as
translator, notary and translation of the contract into Ukrainian With
sincerely, Nazar.

чт, 24 июн. 2021 г. в 04:35, Lucas Costi ***@***.***>:
