### ISSUE TITLE
Add page level comments on docs.github.com

### ISSUE THREAD

**Issue by nschonni** [github/docs#721]
### What is the current behavior?

Users are directed to the general github.community or Support contact page
![image](https://user-images.githubusercontent.com/1297909/96903523-f20a2100-1463-11eb-8b14-2708d2df7c5e.png)

### What changes are you suggesting?

Add page-level commenting on individual pages for docs.github.com articles.

### Additional information

On the docs.microsoft.com site, there are sections on each page/docset that has this feature enabled that renders something like
![image](https://user-images.githubusercontent.com/1297909/96903331-b5d6c080-1463-11eb-8bba-0e0e2880d5d2.png)
I believe this is based of a modified version of https://github.com/utterance/utterances/

**Comment by janiceilene** [comment]
Hi @nschonni, sorry about the delay, this one must have slipped through my notifications 💛 

> Add page-level commenting on individual pages

Can you explain a little more about what you're looking for? Are you looking for something like the automatically included information added to an issue when you click **This page**?

**Comment by nschonni** [comment]
Sorry, it used to have in-page rendering of the issues created from those buttons, but I guess they might have disabled it sometime over the last few months.

You can see the metadata on an issue like https://github.com/MicrosoftDocs/azure-docs/issues/65249 that it pre-fills in the issue. That used to be combined with their version of utterances to also have an in-page multi issue threaded comment section that was backed by those issues.

Benifit of that, is that users can see the open/closed discussions on a particular page to see if someone already opened an issue with their same problem and what the discussions were. This can be a nicer flow that opening an issue (after searching) and maybe not finding the previous ones.

You can see how the previous setup worked over here https://docs.microsoft.com/en-ca/teamblog/a-new-feedback-system-is-coming-to-docs

**Comment by LawWon** [comment]
> ### What is the current behavior?
> Users are directed to the general github.community or Support contact page
> ![image](https://user-images.githubusercontent.com/1297909/96903523-f20a2100-1463-11eb-8b14-2708d2df7c5e.png)
> 
> ### What changes are you suggesting?
> Add page-level commenting on individual pages for docs.github.com articles.
> 
> ### Additional information
> On the docs.microsoft.com site, there are sections on each page/docset that has this feature enabled that renders something like
> ![image](https://user-images.githubusercontent.com/1297909/96903331-b5d6c080-1463-11eb-8bba-0e0e2880d5d2.png)
> I believe this is based of a modified version of https://github.com/utterance/utterances/

magnetikonline:fix-restrictions-access-cache-workflow

**Comment by janiceilene** [comment]
Thanks so much for this suggestion, we've discussed it more recently with our internal teams and have decided not to go in this direction 💛 

We appreciate your interest and passion in the GitHub docs!
