### ISSUE TITLE
More visible note about the risk of using community actions, referenced by tag/branch name instead of SHA, in combinations with secrets

### ISSUE THREAD

**Issue by mktcode** [github/docs#7216]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-release-management-for-your-custom-actions

### What part(s) of the article would you like to see updated?

I'd like to add a more visible note about the risk of using actions from the community, that might require a secret and then not referencing it via a SHA but a branch or tag name instead, as it is "suggested" everywhere else in the docs.

![image](https://user-images.githubusercontent.com/6792578/121344595-3c251180-c924-11eb-8980-8acf3da903dd.png)

### Additional information

I was exploring what is possible with GitHub Actions recently and that was what I was wondering about the whole time. Then I found this article: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
And I also just successfully posted the `GITHUB_TOKEN` in an issue (https://github.com/mktcode/test-action/issues/6) by force-pushing to the action's repo and overwriting the commit to which my `v1.0-maybe` tag was linked to.

**Comment by Ihsan-K** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
