### ISSUE TITLE
adding-an-existing-project-to-github-using-the-command-line "master" to "main"

### ISSUE THREAD

**Issue by NeroBlackstone** [github/docs#7263]
### What article on docs.github.com is affected?

https://docs.github.com/cn/github/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line

### What part(s) of the article would you like to see updated?

推送更改（本地仓库中）到 GitHub。
```
$ git push origin master
# Pushes the changes in your local repository up to the remote repository you specified as the origin
```
this "master" should be "main"

### Additional information

I'm ready to pull request

**Comment by janiceilene** [comment]
Thanks for opening this issue and offering to open a pull request! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

I've opened an internal issue for to update this article 💛
