### ISSUE TITLE
oEmbed / OpenGraph tags could not be found: description, image

### ISSUE THREAD

**Issue by jsoref** [github/docs#7268]
### What is the current behavior?

Compose a message in https://github.community/t/searching-filtering-forks-not-related-to-code-search-in-forks/184363/2 with:
https://docs.github.com/en/rest/reference/repos#list-forks

![image](https://user-images.githubusercontent.com/2119212/121563155-2711b680-c9e8-11eb-9687-a6669babc07e.png)
> Sorry, we were unable to generate a preview for this web page, because the following oEmbed / OpenGraph tags could not be found: description, image

### What changes are you suggesting?

_Add_ the following oEmbed / OpenGraph tags _that_ could not be found: description, image

**Comment by janiceilene** [comment]
Thanks for opening an issue @jsoref! I'm not sure I'm understanding what updates you're looking for. Are you asking that we add `description` and `image` as parameters to the "List forks" section of the [Repositories](https://docs.github.com/en/rest/reference/repos#list-forks) reference article?

**Comment by jsoref** [comment]
I'm not sure. Whatever is necessary to make that interface happy. I expect a technical person will know. They're both GitHub's.

**Comment by janiceilene** [comment]
@jsoref Which interface are you referring to? We don't own the GitHub community site or how it operates. Is there an update to a docs article that you're looking for?

**Comment by jsoref** [comment]
[The Open Graph protocol](https://ogp.me/)

> The four required properties for every page are:
> og:image - An image URL which should represent your object within the graph.

> The following properties are optional for any object and are generally recommended:
> og:description - A one to two sentence description of your object.

I'm suggesting that the github.community site would like your page much better if you included these two additional attributes in the `<head>` section of this page.

Most portions of GitHub seem to be quite friendly to github.community, but for whatever reason, this page is not. I'm not sure if that's a quirk of the page, the section, the generator, or something else.

**Comment by janiceilene** [comment]
Thanks for that clarification @jsoref! I'll triage this for the engineering team. It could be a neat addition, but we can't promise when or even if this will be prioritized.

**Comment by JamesMGreene** [comment]
@jsoref Thanks for reporting this issue! You are correct that we can definitely improve on the documentation site's OpenGraph metadata. We have added this issue to our backlog. 👍🏻

**Comment by janiceilene** [comment]
It looks like this has been added to an internal backlog, so I'm going to close this issue out!
