### ISSUE TITLE
inconsistent workflow branch language

### ISSUE THREAD

**Issue by rhettg** [github/docs#7278]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

### What part(s) of the article would you like to see updated?

The language around selecting a branch when manually running a workflow is inconsistent. 

The UI says:

![image](https://user-images.githubusercontent.com/50074/121610599-440bb100-ca0b-11eb-8120-584eb6811a2c.png)

The CLI docs say:

![image](https://user-images.githubusercontent.com/50074/121610625-4ec64600-ca0b-11eb-91c6-a17af54b7e63.png)

The CLI help strings are also different:

![image](https://user-images.githubusercontent.com/50074/121610654-5d146200-ca0b-11eb-954b-270b4a77638c.png)

It seems like these should indicate the same behavior, but the subtle differences in language seems like they could be interpreted different:

* "where"
* "from"
* "on"
* "at"

### Additional information

___
Plan for anyone who'd like to pick this up https://github.com/github/docs/issues/7278#issuecomment-868218907:

Change:

> Select the branch where the workflow will run and type the input parameters used by the workflow. Click Run workflow. 

to:

`Use the **Branch** dropdown to select the workflow's branch, and type the input parameters. Click **Run workflow**.`

**Comment by tipos197** [comment]
поехали

**Comment by Ti6** [comment]
Like I said I don't want nothing I never have nothing

**Comment by janiceilene** [comment]
Thanks so much for opening an issue and including so much context @rhettg! I'll get this triaged for the team to take a look 👀

**Comment by avsyanskiy75** [comment]
> поехали

**Comment by lucascosti** [comment]
Thanks, @rhettg. Yeah, this might be slightly confusing.

> Select the branch where the workflow will run and type the input parameters used by the workflow. Click Run workflow. 

We could reword it like this to be more clear:

`Use the **Branch** dropdown to select the workflow's branch, and type the input parameters. Click **Run workflow**.`

**Comment by amanjha8100** [comment]
Can I work on this, I am a first time contributor to github-docs, so I am not sure if this is the way to go to contribute? Please assign me this if possible!

**Comment by jjsanchz46** [comment]
Yes you can work on this helps make it consistent?

**Comment by amanjha8100** [comment]
I will start right away!

**Comment by amanjha8100** [comment]
Submitted the [PR](https://github.com/github/docs/pull/7939). I am open to any changes that you may suggest. Looking forward to your reply @jjsanchz46 or any other member of the team. Thank You!
