### ISSUE TITLE
Make it so that 9+ can use

### ISSUE THREAD

**Issue by Time-dragon** [github/docs#7287]
### What article on docs.github.com is affected?

Terms of Service

### What part(s) of the article would you like to see updated?

Make it so that 9+ is the age to use GitHub and not 13+

### Note for GitHub
I am a 13 year old.

**Comment by gmemstr** [comment]
Going to just leave this here. https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy-protection-rule

**Comment by ajs256** [comment]
This should be discussed in the [site-policy](https://github.com/github/site-policy/) repo.

**Comment by janiceilene** [comment]
Thanks for opening an issue @Time-dragon! We document existing policies in this repo, but don't influence policy changes. I'm going to close this issue now 💛
