### ISSUE TITLE
Tables written in markdown are broken in the translated content

### ISSUE THREAD

**Issue by uskey512** [github/docs#7312]
### What is the current behavior?

Tables written in markdown are broken in the translated content.

Original:

https://github.com/github/docs/blob/main/content/rest/overview/libraries.md

Translated:

https://github.com/github/docs/blob/main/translations/de-DE/content/rest/overview/libraries.md
https://github.com/github/docs/blob/main/translations/es-ES/content/rest/overview/libraries.md
https://github.com/github/docs/blob/main/translations/ja-JP/content/rest/overview/libraries.md
https://github.com/github/docs/blob/main/translations/ko-KR/content/rest/overview/libraries.md
https://github.com/github/docs/blob/main/translations/pt-BR/content/rest/overview/libraries.md
https://github.com/github/docs/blob/main/translations/ru-RU/content/rest/overview/libraries.md
https://github.com/github/docs/blob/main/translations/zh-CN/content/rest/overview/libraries.md

### What changes are you suggesting?

It should match the English version of the display.

### Additional information

I haven't checked the entire site, but there may be other pages similar to this one.

**Comment by otamachan** [comment]
Hi, I also found a table in another page seems broken.
Should I create another issue?

https://docs.github.com/ja/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization
https://github.com/github/docs/blob/main/translations/ja-JP/content/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization.md

**Comment by chiedo** [comment]
This issue is fine! Thanks. We'll get this addressed.

**Comment by ivan0117** [comment]
https://docs.github.com/ja/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization
https://github.com/github/docs/blob /main/translations/ja-JP/content/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization.md

**Comment by janiceilene** [comment]
We're working on our translated content internally, so I'm going to close this issue now. Thanks so much for letting us know about this specific problem!
