### ISSUE TITLE
No names on the links on the repository settings page Нет названий на ссылках на странице настроек репозитория

### ISSUE THREAD

**Issue by Nprofess** [github/docs#7319]
### What is the current behavior?
Не добавлен текст в ссылку
![image_2021-06-12_17-41-15](https://user-images.githubusercontent.com/65503421/121779663-7224f880-cba5-11eb-9889-036c3a23eec7.png)

Браузер Яндекс

### What changes are you suggesting?
В пустых ссылках не хватает:
<ya-tr-span data-index="108-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="......NAME......" data-translation="......NAME......" data-type="trSpan" data-selected="false">......NAME......</ya-tr-span>

![image](https://user-images.githubusercontent.com/65503421/121779745-eeb7d700-cba5-11eb-98e2-92ae3c3966d3.png)

**Comment by fnise-urt** [comment]
Create a new repository `https://github.com/Nprofess/Nprofess.github.io`.

Create a new file `index.html` in that repository with the following content. 

```html
<!DOCTYPE HTML>
<html lang="ru">
<head>
        <title>index</title>
</head>
<body>
        <h1>Петроград</h1>
</body>
</html>
```

In the address bar of a browser open `https://Nprofess.github.io`.

**Comment by fnise-urt** [comment]
> Create a new repository `https://github.com/Nprofess/Nprofess.github.io`.

`https://github.com/Nprofess/Nprofess.github.io/settings/pages`

The following text should then appear on the above page.

✓ Ваш сайт опубликован по адресу `https://Nprofess.github.io/`

If that solves the issue then please close!

**Comment by janiceilene** [comment]
👋 @Nprofess Thanks so much for opening an issue! This repository is the source for the code and content on docs.github.com. It looks like you're reporting a bug on github.com. The best place to send your feedback is to https://support.github.com/contact/feedback 💛

Let me know if you had a docs update request that I missed!

**Comment by fnise-urt** [comment]
> reporting a bug

I don't think it's a bug.

On June 13, 2021, no repo `Nprofess/Nprofess.github.io` existed.
