### ISSUE TITLE
Link to empty doc in project management page

### ISSUE THREAD

**Issue by thedonquixote** [github/docs#7415]
### What article on docs.github.com is affected?

https://docs.github.com/articles/managing-your-work-with-issues

### What part(s) of the article would you like to see updated?

I would like to see this page be given adequate explanation of the 
"basics of issues" as it says it links to from this page
https://github.com/features/project-management/

______
Plan for whoever would like to open a PR with a fix:

Add another redirect at the top of https://github.com/github/docs/edit/main/content/issues/tracking-your-work-with-issues/creating-issues/about-issues.md article for `/articles/managing-your-work-with-issues`.

**Comment by fnise-urt** [comment]
Learn the basics of issues →

https://docs.github.com/en/issues/tracking-your-work-with-issues

**Comment by janiceilene** [comment]
👋 @thedonquixote Thanks for opening an issue and pointing out this missing redirect! https://github.com/features/project-management/ is a page we don't maintain, but we can add a redirect at the top of https://github.com/github/docs/edit/main/content/issues/tracking-your-work-with-issues/creating-issues/about-issues.md article for `/articles/managing-your-work-with-issues`

You (or anyone else!) are welcome to open a PR to make that change ✨

**Comment by 1337-ishaan** [comment]
https://github.com/features/project-management/ 

This page does not exist.

**Comment by 1337-ishaan** [comment]
https://github.com/articles/managing-your-work-with-issues

Page not found

**Comment by StarTrooper08** [comment]
Hey I would like to work on this issue.
But can I get overview of this issue.
Like what we have to do exactly??

**Comment by 1337-ishaan** [comment]
@StarTrooper08 same

**Comment by StarTrooper08** [comment]
Hey , I would like to work on this issue!!

**Comment by 1337-ishaan** [comment]
Please explain me the issue, i'd like to work on this issue.

**Comment by janiceilene** [comment]
Anyone is welcome to pick up this issue! The top comment includes a "Plan for whoever would like to open a PR with a fix."

**Comment by StarTrooper08** [comment]
@1337-ishaan are you going to work on this issue??

Or else I can take over this issue.

@janiceilene I have to demonstrate live open source contribution to Open source organization and this one is easy contribution me to explain to my teammates from Udacity Cloud Native Scholarship who are new to Open Source Contribution.

Can I do this??👀

**Comment by 1337-ishaan** [comment]
Save yourself @StarTrooper08 , go for it man! Its importanr for you.

**Comment by janiceilene** [comment]
@StarTrooper08 You're welcome to open a PR for this issue!

**Comment by StarTrooper08** [comment]
> Save yourself @StarTrooper08 , go for it man! Its important for you.

Thanks @1337-ishaan ⭐

**Comment by fnise-urt** [comment]
@janiceilene

> a page we don't maintain

https://github.com/features/project-management/

now redirects to

https://github.com/features/issues

I think this issue can be closed.

**Comment by janiceilene** [comment]
Awesome! Thanks so much for letting us know @fnise-urt. I'll close this issue now ⚡
