### ISSUE TITLE
Job status check functions sentence is broken

### ISSUE THREAD

**Issue by jsoref** [github/docs#7416]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

### What part(s) of the article would you like to see updated?

> If your `if` expression does not contain any of the status functions it will automatically _&& your_ result with `success()`.

### Additional information

The current text isn't grammatically sound and is effectively meaningless / confusing / etc.

Note: I'm not saying that my suggestion is the correct one. I'd suggest getting someone to figure out what this thing is trying to say and rewrite it from scratch.

Refs: https://github.community/t/workflow-skips-steps-besides-if-condition/115956/2

**Comment by janiceilene** [comment]
Thanks for opening an issue @jsoref! I'll triage this for the team to take a look 👀

**Comment by jsoref** [comment]
It isn't good enough to quickly imply that it's included.

I think if you added the word (or concept) `applied` near:

> The default result of a status check is `success()` unless you include one of these functions

might work.

Something like:

> A default status check of `success()` is _applied_ unless you include one of these functions

**Comment by felicitymay** [comment]
I like your suggestion 👍🏻 

Is this something you'd like to open a pull request for, or shall we update the issue summary with the intended change and add the issue to the "help wanted" issues?
