### ISSUE TITLE
Example for Publishing Docker images to GitHub Packages broken

### ISSUE THREAD

**Issue by bananer** [github/docs#7424]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages

### What part(s) of the article would you like to see updated?

In the example file, the tag is specified like this:

    docker.pkg.github.com/${{ github.repository }}/octo-image:${{ github.ref }}

However, the variable `github.ref` resolved to something like `refs/heads/my_branch_name` (as [documented](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)).

This causes the step to fail: 

    error: invalid tag "docker.pkg.github.com/bananer/my-repo/mps:refs/heads/my_branch_name": invalid reference format
    Error: buildx call failed with: error: invalid tag "docker.pkg.github.com/bananer/my-repo/mps:refs/heads/my_branch_name": invalid reference format

### Additional information

My goal is to publish to a docker tag matching my branch name, assuming this is also the intent of the example. Seems like there is no official way to get the branch name without `refs/heads/` prefix in the official docs.

**Comment by janiceilene** [comment]
Thanks for opening an issue @bananer! I'll get this triaged for the team to take a look 👀

**Comment by skedwards88** [comment]
Thank you for opening this issue! ✨ We have an update (now live) that no longer uses `github.ref` in the tag name, so I believe this should be resolved.
