### ISSUE TITLE
Inconsistency regarding the availability of feature 'autolink references'

### ISSUE THREAD

**Issue by MichaelKetting** [github/docs#7475]
Hello,

I believe to have found an inconsistency in the documentation on what plans the 'autolink references' feature is available in:

The feature overview (https://docs.github.com/en/github/getting-started-with-github/learning-about-github/githubs-products) lists that all features are available for public repositories when using the free plan for organizations:

> With **GitHub Free for organizations**, you can work with unlimited collaborators on unlimited public repositories with **a full feature set**, or unlimited private repositories with a limited feature set.

The documentation for autolink (https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/configuring-autolinks-to-reference-external-resources) lists only paid options for this feature:

> **Autolinks are available in repositories with GitHub Pro**, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub’s products](https://docs.github.com/en/articles/github-s-products).

The autolink feature is not available for configuration with public repositories, so I guess the more restrictive documentation is correct, but it would be great if you could consolidate this information to clear up the confusion. Also, since the documentation on availability of the autolink feature explicitly links back to the first page with the **full feature set**, this makes things even more confusing.

In the docs repository, this refers to the following pages:
* https://github.com/github/docs/blob/main/content/github/getting-started-with-github/learning-about-github/githubs-products.md
* https://github.com/github/docs/blob/main/content/github/administering-a-repository/managing-repository-settings/configuring-autolinks-to-reference-external-resources.md

The guys over on Github community (https://github.community/t/autolink-references-and-free-plans/185389/4) also recommended opening a [feedback ticket](https://support.github.com/contact/feedback) for this, regarding the question if this feature is truely meant to be available only for paid support. Will do this depending on what the updated documentation's like.

Many thanks, Michael

**Comment by janiceilene** [comment]
👋 @MichaelKetting Thanks so much for opening an issue. Can you followup with support asking about the availability? Let us know what they say and we can consider potential docs updates! I'm going to close this issue in the meantime, but as soon as you get back to us here, we can reopen it.
