### ISSUE TITLE
Document primary email's role in web commit email

### ISSUE THREAD

**Issue by nihaals** [github/docs#748]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

### What part(s) of the article would you like to see updated?

I don't think the [Setting your commit email address on GitHub](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-on-github) section makes it clear what happens if you don't have email privacy enabled. I've had the option enabled for years and was surprised that after disabling it I was given the option to select which address to use when doing an action, even after reading this doc page multiple times. The related section:

> If you haven't enabled email address privacy, you can choose which verified email address to author changes with when you edit, delete, or create files or merge a pull request on GitHub.

One piece of information that simply isn't included here is that initial commits are always done with the primary email and the default email used is the primary email. Maybe a screenshot of the dropdown could be included along with a note about initial commits.

I've already given feedback on the ability to set a custom restricted email which would give a similar behaviour to email privacy being enabled.

**Comment by hubwriter** [comment]
@nihaals - Thanks for raising this issue. I think you're right that we could add some clarity here.

You say "initial commits are always done with the primary email" - however I'm not sure about this. When I go to a repo I haven't worked on before and make a change within GitHub I get the option to choose one of my email addresses from the drop-down. Maybe I'm not following what you mean here. Could you say a little more about this please?

I agree with you that a screenshot of the commit form - showing the drop-down that you get if you haven't enabled email privacy - would be useful. We'll have to do this in-house at GitHub as we haven't yet made it possible for external contributors to add/change screenshots.

Thanks again for raising this.

**Comment by hubwriter** [comment]
@nihaals - Thank you for clarifying that. 

Because this would benefit from a new screenshot, as you suggest, we'll need to do this in house, rather than allowing the community to make this change. I'm therefore going to close this issue and copy the information you've supplied above onto an internal issue. 

Many thanks again for raising this. Your help improving the GitHub documentation is much appreciated. 👍
