### ISSUE TITLE
The Japanese translation of creating-a-composite-run-steps-action.md is wrong

### ISSUE THREAD

**Issue by odanado** [github/docs#751]
### What article on docs.github.com is affected?
https://docs.github.com/ja/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action

### What part(s) of the article would you like to see updated?

The translation is wrong.
e.g. the internals of the code block has been translated as well.

### Additional information
current
<img width="779" alt=" 2020-10-23 22 19 49" src="https://user-images.githubusercontent.com/6040962/97009261-d8113100-157e-11eb-8ba7-24efeccae138.png">

**Comment by janiceilene** [comment]
Thanks so much for letting us know @odanado! Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

In the meantime, I've opened an issue internally for our translators and I'll close this one out.

**Comment by falsandtru** [comment]
@janiceilene Found the same problem.

https://docs.github.com/ja/free-pro-team@latest/actions/reference/encrypted-secrets

```
名前: 大きな

秘密を持つワークフロー: プッシュ

ジョブ
  : プッシュジョブ:
    名:のジョブ
    実行: ubuntu 最新
    ステップ:
      - 使用: アクション/checkout@v2
      - 名前: 大規模な秘密
        を復号化
        実行: ./.github/scripts/decrypt_secret.sh  env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      # このコマンドは、あなたの秘密が印刷されていることを示す例
      # あなたの印刷シークレットを削除します。 GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/my_secret.json
```

**Comment by MikeMitStudentHU8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Hi xx

Terrible sorry for the mistakes I made whilst trying to use the app,

Don’t look back lol in Anger- Oasis

Mike
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMitStudentHU8** [comment]
Hello X,

Very sorry for the confusing things I did when I used GitHub without reading the guide and information correctly and rushing in like a idio.

Yours sincerely
Mike Mckenzie
Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by janiceilene** [comment]
Thanks for letting us know @falsandtru! I added it to the internal issue ✨
