### ISSUE TITLE
underspecified text about repository and actions/checkout

### ISSUE THREAD

**Issue by jsoref** [github/docs#7539]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

### What part(s) of the article would you like to see updated?

> The workspace directory is a copy of your repository if your workflow uses the actions/checkout action.

It's fixable by adding `to check out your repository to the default location`, although I'd rather a doc writer consider the preferred text (possibly consulting with the dev team).

### Additional information

If for some strange reason I use `actions/checkout` to checkout some repository *other* than my repository, then this statement will be false.

An example of this can be found in the canonical documentation:
https://github.com/actions/checkout#Checkout-multiple-repos-side-by-side

**Comment by megbird** [comment]
To me, this update makes sense and should be fine. We're already driving at specificity in the statement `The workspace directory is a copy of your repository if your workflow uses the actions/checkout action` so the possibility of the added statement introducing inaccuracy doesn't worry me 😄 @jsoref please feel free to open a PR with this change and I can review it soon!
