### ISSUE TITLE
Inconsistent description of scope of env set via GITHUB_ENV 

### ISSUE THREAD

**Issue by tingzuge-dio** [github/docs#7553]
Description of GITHUB_ENV is inconsistent regarding if set envs are available across the workflow or only within a job.

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/environment-variables#about-environment-variables
https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

### What part(s) of the article would you like to see updated?

> You can also use the GITHUB_ENV environment file to set an environment variable that **_the following steps in a workflow can use_**. The environment file can be used directly by an action or as a shell command in a workflow file using the run keyword. For more information, see "Workflow commands for GitHub Actions."

> Creates or updates an environment variable for any actions running next in a job. The action that creates or updates the environment variable does not have access to the new value, but **_all subsequent actions in a job will have access_**. Environment variables are case-sensitive and you can include punctuation.

### Additional information

I am having some trouble finding docs that summarizes scopes of variables, workspaces, etc. in GitHub Actions. It seems like this would be a fairly relevant to many pipelines and should be addressed directly in the docs.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @tingzuge-dio! I'll triage this for the team to take a look 👀

**Comment by lucascosti** [comment]
Thanks for pointing this out, @tingzuge-dio. You are correct that these are inconsistent when they should be the same; it applies to all following steps in a job. 

These would be the correct wordings

> You can also use the GITHUB_ENV environment file to set an environment variable that **_the following steps in a job can use_**. The environment file can be used directly by an action or as a shell command in a workflow file using the run keyword. For more information, see "Workflow commands for GitHub Actions."

> Creates or updates an environment variable for any actions running next in a job. The action that creates or updates the environment variable does not have access to the new value, but **_all subsequent steps in a job will have access_**. Environment variables are case-sensitive and you can include punctuation.

Anyone can feel free to open a PR to change ☝️  🙂

**Comment by j-saurabh** [comment]
Is this still open to be fixed? I would like to take up this and make the changes.

**Comment by j-saurabh** [comment]
Is this still needs to be fixed? I would like to take this up and make the changes.

**Comment by ramyaparimi** [comment]
@j-saurabh Please feel free to open a PR 👍
