### ISSUE TITLE
GitHub Actions data transfer is not billed, but mentioned in the docs

### ISSUE THREAD

**Issue by Simran-B** [github/docs#7569]
### What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#calculating-minute-and-storage-spending

### What part(s) of the article would you like to see updated?

There is the following confusing sentence:

> At the end of the month, GitHub rounds your data transfer to the nearest GB.

The article does not mention data transfer (or ingress/egress/traffic for that matter) anywhere else. It might be copied from the corresponding [GitHub Packages page](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages). I'm not sure if it should say something about rounding to dollar-cent amounts instead, but the GitHub Packages page does not do that either. Maybe it should say "round to nearest minute"?

Also, consider adding a sentence that data transfer is free for GitHub Actions.

### Additional information

This issue came to light in https://github.community/t/does-gha-bill-for-data-transfer/180724.

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @Simran-B! I'll triage this for the team to take a look 👀

**Comment by lecoursen** [comment]
Good catch @Simran-B! Yes, that line should be removed. You or anyone else is welcome to create a PR to do that!
