### ISSUE TITLE
Make difference between content and engineering issues clearer in issue template chooser

### ISSUE THREAD

**Issue by Simran-B** [github/docs#7570]
### What article on docs.github.com is affected?

https://github.com/github/docs/tree/main/.github/ISSUE_TEMPLATE

### What part(s) of the article would you like to see updated?

I find the first two options in the issue template chooser quite confusing:

![image](https://user-images.githubusercontent.com/7819991/122900015-9ffc0100-d34c-11eb-908a-e0135bd0a921.png)

It's not clear what the difference is, especially because all the content is on the docs.github.com site. The intention becomes clear if you look at the labels:

- Improve existing docs -> `content`
- Improve the docs.github.com site -> `engineering`

I suggest changing the titles and descriptions to reflect that one is for content issues and one for technical issues (Markdown rendering etc.).

**Comment by janiceilene** [comment]
You're definitely right @Simran-B! Do you think the word "content" would be less confusing for folks? So maybe: 

> Improve existing content
> Make a suggestion to improve the content in an existing article

> Improve the docs.github.com site
> Make a suggestion to improve the technical implementation on docs.github.com

What do you think?

**Comment by Simran-B** [comment]
My gut feeling is that it should say

> technical implementation **of** docs.github.com

but I really like your suggestion!

**Comment by fnise-urt** [comment]
@janiceilene

Possibly this change to `improve-the-site.md` would suffice.

```diff
  <!-- Include links to articles where you're seeing a problem, screenshots, what browser you're using, etc. -->
  
- ### What changes are you suggesting?
+ - ### What engineering changes are you suggesting?

  <!-- Give as much detail as you can to help us understand the change you want to see. Why should the docs be changed? What use cases does it support? What is the expected outcome? -->
```

Rewriting the 2nd comment in the above so it is not identical to that found in `improve-existing-docs.md`, might provide some additional clarity.

**Comment by fnise-urt** [comment]
July reviews are slow (pinned issue).

improve-the-site.md

```diff
- <!-- Give as much detail as you can to help us understand the change you want to see. Why should the docs be changed? What use cases does it support? What is the expected outcome? -->
+ <!-- Give as much detail as you can to help us understand the changes you want to see. Why should the code be changed? What use cases do they support? What is the expected outcome? -->
```
