### ISSUE TITLE
Add info about transferring action repos, the marketplace `verified` badge and IDs

### ISSUE THREAD

**Issue by Simran-B** [github/docs#7573]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

### What part(s) of the article would you like to see updated?

It would be nice to have a section about transferring action repositories and another about some finer details regarding the marketplace:

- A repo can be transferred and actions will continue to work because there is a redirect in place (users of the action won't have to update their workflows)
- An action in the marketplace is linked to a repository by ID, allowing for new releases to be published under the same marketplace listing from the "new" repo
- If an action repository is deleted, so is the marketplace listing. The unique `name` identifier becomes available again.
- The `verified` status seen on GitHub org profiles is different from the marketplace `verified` badge. By transferring an action repo, the owner changes and the marketplace badge will be lost unless the new owner is a verified publisher too.

### Additional information

The above list is a brief summary of https://github.community/t/any-risks-of-moving-already-published-action-repository/163739

---
[maintainer edit]
### Content plan
Create new section in that article about the renaming/transferring Action repositories and include the above information.

**Comment by janiceilene** [comment]
Thanks for opening an issue @Simran-B! I'll triage this for the team to take a look 👀

**Comment by artursavin86** [comment]
[![Ping staging apps](https://github.com/github/docs/actions/workflows/ping-staging-apps.yml/badge.svg?branch=%23268-active-language-display)](https://github.com/github/docs/actions/workflows/ping-staging-apps.yml)

**Comment by artursavin86** [comment]
iAd

**Comment by lucascosti** [comment]
Thanks a lot for collating that info, @Simran-B!

This makes a lot of sense to me. A new section in that article about the renaming/transferring Action repositories would be a good place to put it.

**Comment by SoundaryaKoutharapu** [comment]
Hi @janiceilene 
 can I proceed to the issue, by creating a A new section in that article about the renaming/transferring Action repositories and include the above info of 4 points.?
is that four points enough.? Do I have include more info.?
