### ISSUE TITLE
Some filenames are too long for Git for Windows

### ISSUE THREAD

**Issue by Simran-B** [github/docs#7620]
### What article on docs.github.com is affected?

`translations/<lang>/content/github/setting-up-and-managing-your-enterprise-account/setting-policies-for-organizations-in-your-enterprise-account/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-enterprise-account.md`
(German, Japanese, Brazilian Portuguese, and Chinese translation)

### What part(s) of the article would you like to see updated?

Git for Windows may complain about the file paths being too long, e.g. if you attempt to checkout the latest main branch of this repo. The length of just the relative path is 244 characters, with the limit being 260, but the absolute path is what counts (so you have to include `C:\Users\<name>\Documents\...` or wherever your working copy is located at.

- Cloning the repo directly to `C:\` would shorten the path, but it's just a workaround.
- Shortening the folder names and the file name of the actual content would be possible, but alter doc URLs and would make the URL slug less self-descriptive and SEO-friendly.
- [Git supports long paths](https://stackoverflow.com/a/22575737/2044940) (apparently at the expense of compatibility), but it needs to be enabled manually, e.g. with `git config core.longpaths true` for the current repo. This worked for me. I suggest to add a remark about this to the `CONTRIBUTING.md`.

### Additional information

```
error: cannot stat 'translations/de-DE/content/github/setting-up-and-managing-your-enterprise-account/setting-policies-for-organizations-in-your-enterprise-account/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-enterprise-account.md': Filename too long
error: cannot stat 'translations/ja-JP/content/github/setting-up-and-managing-your-enterprise-account/setting-policies-for-organizations-in-your-enterprise-account/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-enterprise-account.md': Filename too long
error: cannot stat 'translations/pt-BR/content/github/setting-up-and-managing-your-enterprise-account/setting-policies-for-organizations-in-your-enterprise-account/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-enterprise-account.md': Filename too long
error: cannot stat 'translations/zh-CN/content/github/setting-up-and-managing-your-enterprise-account/setting-policies-for-organizations-in-your-enterprise-account/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-enterprise-account.md': Filename too long
```

**Comment by janiceilene** [comment]
Thanks for the issue @Simran-B! I'll triage this for the team to take a look 👀

**Comment by fnise-urt** [comment]
> `CONTRIBUTING.md`

In the [Windows](https://github.com/github/docs/blob/main/CONTRIBUTING.md#windows) section possibly add a `curl` command to download the .zip file.

**Comment by joe192** [comment]
curl

**Comment by JamesMGreene** [comment]
@Simran-B Thank you for reporting this and explaining some of the viable workarounds. We have added this issue to our backlog. 👍🏻

**Comment by I-Cat** [comment]
> Depending on your Windows Version
>> Steps: to fix  |-- > 
> Step A: 
> 1. Open: cmd.exe
> 2. Run: regedit.exe
> 3. Edit: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
> 4. Look: for LongPathsEnabled (If Value Missing) 
> |--> Do Step B:
> 4a. Right click : "FileSystem" Folder 
> 4b. Choose: New Dword Value
> 4c. Add: "LongPathsEnabled" text 
> Else: 
> 5. Change Value 0 To 1
> 6. Then : sound=Applause


Author: I-Cat <the_kat690@hotmail.com>
AuthorDate: 2021-July-29 12:52:00 -0500
Commit: I-Cat <the_kat690@hotmail.com>
CommitDate: 2021-July-29 12:52:00 -0500
Signed-off-by: I-CAT <the_kat690@hotmail.com>

**Comment by janiceilene** [comment]
We've added information about this to our contributing guide! https://github.com/github/docs-internal/blob/main/CONTRIBUTING.md#windows
