### ISSUE TITLE
CodeQL alerts:  Need to update documentation regarding permissions

### ISSUE THREAD

**Issue by larryclaman** [github/docs#763]
### What is the current behavior?

The page [Managing code scanning alerts for your repository](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/managing-code-scanning-alerts-for-your-repository) needs to clarify who can view code alerts

### What changes are you suggesting?

Currently, this documentation page says "People with write permission to a repository can resolve code scanning alerts."   This is accurate, but insufficient.  The documentation should explicitly call out that in order to VIEW code scanning results, you also need write permission as well, and that this is the same for both public and private repos.

Code scanning permissions should also be added to the table on this page:  [Repository permission levels for an organization](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization)

Note that the need for WRITE permission to view CodeQL alerts does not appear to be documented; I only discovered it through trial and error.

**Comment by 332406** [comment]
whatsapp.com/+60143324191

**Comment by hubwriter** [comment]
@larryclaman - Many thanks for raising this issue. Looks like a good catch and I agree that, as well as correcting and clarifying the required permissions we should add this to the "[Repository permission levels for an organization](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization)" topic.

**Comment by hubwriter** [comment]
The "[Managing code scanning alerts for your repository](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/managing-code-scanning-alerts-for-your-repository)" topic now says, at the start of the topic:

> People with write permission to a repository can manage code scanning alerts for the repository.

This is good, but I think it would be better to clarify that this whole page is designed for people with write permission. I suggest changing this to: 

> If you have write permission to a repository you can manage code scanning alerts for the repository from the **Security** tab.

Users without write permission to the repo don't see code scanning in the **Security** tab, so I think this wording makes it clearer that this is the part of the UI this topic relates to.

Further down the page, in the "Viewing an alert" section, we say:

> Anyone with read permission for a repository can see code scanning alerts on pull requests. However, you need write permission to view a summary of alerts for repository on the Security tab.

This is also fine, but it would be better to make it clear that this subsection relates to viewing alerts from alert summary and not from, or for, a specific pull request. So we could change this to say:

> Anyone with read permission for a repository can see code scanning alerts on pull requests. For more information, see "[Triaging code scanning alerts in pull requests](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/triaging-code-scanning-alerts-in-pull-requests)." To view the alerts for a repository, from the summary on the Security tab, you must have write permission to the repository.

**Comment by korzen78-code** [comment]
Translate for Polish

**Comment by felicitymay** [comment]
Thanks for raising this issue. It's great to know when the docs aren't clear.

I've just started work on a related, internal issue and plan to update these topics as part of the work. To avoid anyone duplicating the work, I suggest that we close this issue and I'll add an update here when the changes are live.

**Comment by felicitymay** [comment]
👋🏻 Hi @larryclaman 

We've just published some updates to the topics on code scanning to make the information about permissions clearer. In particular:

- [Repository access for each permission level](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) now includes code scanning.
- [Viewing the alerts for a repository](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/managing-code-scanning-alerts-for-your-repository#viewing-the-alerts-for-a-repository) now explains that `read` permission only gives you access to alerts on pull requests and that you need `write` permission to see all the alerts for the repository.

Thank you for raising the lack of clarity about permissions for code scanning alerts 😄
