### ISSUE TITLE
improve zh-cn translations

### ISSUE THREAD

**Issue by PassionPenguin** [github/docs#7664]
### What article on docs.github.com is affected?

[`translations/zh-CN/data/ui.yml`](https://github.com/github/docs/blob/translations/zh-CN/data/ui.yml)

### What part(s) of the article would you like to see updated?

![image](https://user-images.githubusercontent.com/41184947/123253686-4fd59800-d520-11eb-978e-cf2c437825b4.png)

### Additional information

修改的主要原因为：

1. 标点不符合规范
2. 多出来的空格
3. 句子关系

**Comment by janiceilene** [comment]
Thanks for opening an issue for this fix! Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

I've opened an internal issue for one of our translators to review 💛
