### ISSUE TITLE
"Mastering Markdown": Header example contains invalid characters

### ISSUE THREAD

**Issue by LinqLover** [github/docs#7666]
### What article on docs.github.com is affected?

Not really `docs.github.com` but rather `guides.github.com`:

https://guides.github.com/features/mastering-markdown/#syntax:~:text=%23%20This%20is%20an%20%3Ch1%3E%20tag

Unfortunately, I did not find any repository for these guides on GitHub, so I hoped you could accept this issue here!

### What part(s) of the article would you like to see updated?

Section Syntax guide/Headers:

> ### Headers
>
> ```md
> # This is an <h1> tag
> ## This is an <h2> tag
> ###### This is an <h6> tag
> ```

<i><small>(Btw, is the above-quoted snippet only rendered so awkwardly on my end?)</small></i>

Which in the current comment editor renders as:

![image](https://user-images.githubusercontent.com/38782922/123264106-fce8ea00-d4f9-11eb-9734-07c3476b8df3.png)

Instead, the snippet should be corrected to look like this:

```md
# This is an h1 tag
## This is an h2 tag
###### This is an h6 tag
```

(Yes, the tags could also be escaped instead, but this would seem less beginner-friendly to me. Escaping syntax is not even introduced at all in this guide.)

**Comment by janiceilene** [comment]
That is a frustrating bug @LinqLover! Unfortunately we don't maintain the GitHub guide and don't have the ability to change it 💛 I'll try to pass this info onto the right team though!
