### ISSUE TITLE
Probable typo in Security hardening article

### ISSUE THREAD

**Issue by gsrohde** [github/docs#769]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-secrets
### What part(s) of the article would you like to see updated?

The text under bullet point _Never use structured data as a secret_ starts out "Unstructured data can cause secret redaction within logs to fail, because redaction largely relies on finding an exact match for the specific secret value."  I think this should read "_Structured_ data can cause ...".

**Comment by janiceilene** [comment]
Thanks for letting us know @gsrohde!
