### ISSUE TITLE
Github Actions: Missing `github` Context Property (Documentation)

### ISSUE THREAD

**Issue by Sean12697** [github/docs#7691]
### What article on docs.github.com is affected?

[Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)

### What part(s) of the article would you like to see updated?

The "`github` context" table, which seems to be missing the `github.repository.name` property that is valid, but is not listed.

**Comment by Sean12697** [comment]
Researching how to gain a repositories name, without the owner / organisation within it, lead me to the `github.repository.name` property, through various Stack-overflow posts like the following. https://stackoverflow.com/questions/62803531/repository-name-as-a-github-action-environment-variable

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @Sean12697! I'll triage this for the team to take a look 👀

**Comment by Blacklion55** [comment]
# # # # # # #7688

**Comment by zaid1122** [comment]
> Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by gsteele178** [comment]
Ok

**Comment by skedwards88** [comment]
@Sean12697 Thanks for opening this issue! This context returns empty for me. Can you share an example workflow and workflow log where you use the `github.repository.name` context?
