### ISSUE TITLE
Modify section header in managing-your-github-enterprise-license doc

### ISSUE THREAD

**Issue by stacycarter** [github/docs#7696]
### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.1/admin/overview/managing-your-github-enterprise-license#uploading-a-new-license-to-github-enterprise-server

### What part(s) of the article would you like to see updated?

"How to download the license file" is often a top concern and I'm proposing that we reflect this in the section header. 

**Current section header:**

"Uploading a new license to GitHub Enterprise Server"

**Proposed new section header:**

"Downloading a new license file and uploading it to GitHub Enterprise Server"

**Comment by kaaid** [comment]
event = new TouchEvent(typeArg, touchEventInit);

**Comment by stacycarter** [comment]
Closed by https://github.com/github/docs/pull/7697.

**Comment by Sinamortazavian** [comment]
8920208f1550733f812afa3a5f6063cdebab5f0e
