### ISSUE TITLE
the mistake of Chinese translation

### ISSUE THREAD

**Issue by oslook** [github/docs#7735]
### What part(s) of the article would you like to see updated?

https://docs.github.com/cn/actions/using-github-hosted-runners/about-github-hosted-runners

### Additional information

Ubuntu 16.04 即将被启用 
->
Ubuntu 16.04 即将被弃用
#7736

**Comment by janiceilene** [comment]
Thanks for opening this issue and pull request! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

I've reported this internally for our translators to take a look 💛
