### ISSUE TITLE
BrowserThanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by Liz911** [github/docs#777]
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

_Originally posted by @welcome[bot] in https://github.com/github/docs/issues/771#issuecomment-715641203_

**Comment by janiceilene** [comment]
This issue appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
