### ISSUE TITLE
docs.github.com is broken if you disable the Beacon API. Is it really necessary?

### ISSUE THREAD

**Issue by fxbrit** [github/docs#7776]
### What is the current behavior?

When browsing to docs.github.com while using Firefox, LibreWolf or any other Firefox fork with `beacon.enabled` set to false, the website fails to load and the console displays `TypeError: navigator.sendBeacon is not a function`. This would probably be the same on any other web browser with that specific API disabled but I could not test it directly.

![b](https://user-images.githubusercontent.com/34379516/123713903-eed1fb00-d864-11eb-9f33-7a721890795e.png)

### What changes are you suggesting?

I know that's related to the [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) but I was wondering if it's really necessary (or maybe it's simply not intentional?) to prevent website access to those who decide to disable it.

Setting the preference back to true allows the website to work again, but in the end would it really break any website functionality to have it off? I would imagine not given that it's mostly used for analytics, but it would have to be confirmed what the use in this case is.
So yeah, unless it's strictly necessary can we make Beacon API not mandatory in order to access the website? Or in case that was unintentional, even better :-)

**Comment by danilabais** [comment]
hello everybody

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @fxbrit! I'll triage this for the team to take a look 👀

**Comment by JamesMGreene** [comment]
Thanks for submitting this issue! It was also reported to us via our Support team around the same time and was quickly resolved in https://github.com/github/docs/commit/0e90603d945aead0dc774dcf96c43a85c3397283 about 4 days after this issue was created. 🎉 

Sorry for the trouble but I hope this is now working great again for you. Please let us know if you're seeing any residual issues! 🙏🏻
