### ISSUE TITLE
Add CODEOWNERS usage details

### ISSUE THREAD

**Issue by sidletsky** [github/docs#7783]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#syntax-exceptions

### What part(s) of the article would you like to see updated?

Add usage details about:
- Excluding directories (using @ghost)
- Changing files under an author's ownership
- Appointing more than one CODEOWNER

**Comment by awang1996** [comment]
#7850

**Comment by felicitymay** [comment]
@sidletsky - thanks for flagging these omissions in the article about the `CODEOWNERS` file. It's clear it could do with some updates 👍🏻  

I had a few questions for you so that we can make sure that any changes we merge to the article are accurate for all users.

> Excluding directories (using @ghost)

I haven't seen this recommended before so I did a quick search and found a community thread that states that it no longer works: https://github.community/t/codeowners-file-with-a-not-file-type-condition/1423/3. Do you have a public repository where this is working?

> Changing files under an author's ownership

As far as I know, if you edit files that you are a code owner for, you won't be added as a pull request reviewer. Is that your experience too?

> Appointing more than one CODEOWNER

As far as I know, if a file has more than one code owner when you raise a pull request with changes to that file all code owners are added as reviewers. By default, code owner reviews are not required unless the repository has a branch protection rule that enables required reviews and also specifies that a code owner review is required.

**Comment by sidletsky** [comment]
Hi @felicitymay! 

Answering your questions:

On using @ghost:
>Do you have a public repository where this is working?

Not public, but a private one, it works. This is the code:
```
/.github/                                                                                                          @Company/some-team
/.github/CODEOWNERS                                                                                 @ghost
```
 It allows anyone to edit CODEOWNERS files without requiring @some-team to review it and github config files are still secured by the owners. 
 
 >As far as I know, if you edit files that you are a code owner for, you won't be added as a pull request reviewer. Is that your experience too?

What I meant is that if a user creates a PR to the code under their ownership, then, if the review is required by the repository configuration, the review can be provided by any person to make the PR mergable. 

For example, a user A is a part of `@Company/some-team`. The repository requires CODEOWNERS review to merge and the following CODEOWNERS file is setup in the repository:
```
/my_file                                                                                                           @Company/some-team
```
User A creates a PR with `my_file` edit. This PR can be merged if approved by anyone who is not in `@Company/some-team`, because the author is a part of the `@Company/some-team`.

 >As far as I know, if a file has more than one code owner when you raise a pull request with changes to that file all code owners are added as reviewers. 
 
 Interestig. Maybe some other configuration affected it. When I had two groups as CODEOWNERS, then approve from any of them will be enough to merge.

**Comment by felicitymay** [comment]
Hi @sidletsky 

Thank you for answering my questions. It's really helpful to have more information. I've split my comment into sections to make it easier to navigate our discussion. Now that I believe that I've understood you correctly, I've made a short plan for the best way to update the article.

I think it would be better to separate the information on how the `CODEOWNERS` file works when a repository requires reviews by a code owner. This is only relevant to some users. So it's best to avoid adding this extra detail to the main content.

#### Excluding files/directories from ownership

> Not public, but a private one, it works. This is the code:
>
> ```
> /.github/                @Company/some-team
> /.github/CODEOWNERS      @ghost
> ```
>
>  It allows anyone to edit CODEOWNERS files without requiring @some-team to review it and github config files are still secured by the owners. 

That seems like a great use case. It's interesting to hear that this is working for you. I've done some local testing and you can also get the same effect with:

```
/.github/            @example-org/some-team
/.github/CODEOWNERS 
```

I think it would be better to document something like this example as it doesn't rely on the @ghost account to work.

#### Editing files you own

>  > As far as I know, if you edit files that you are a code owner for, you won't be added as a pull request reviewer. Is that your experience too?
> 
> What I meant is that if a user creates a PR to the code under their ownership, then, if the review is required by the repository configuration, the review can be provided by any person to make the PR mergeable. 

Thanks for explaining. So effectively, if you create a PR that edits code you own, then the PR implicitly has code owner approval and there is no need for an explicit approval by a code owner for the change, even in a repository that has a requirement for a review by a code owner. I like your team example as this makes the meaning clear.

#### Editing files owned by multiple users/teams

>  >As far as I know, if a file has more than one code owner when you raise a pull request with changes to that file all code owners are added as reviewers. 
>  
> Interesting. Maybe some other configuration affected it. When I had two groups as CODEOWNERS, then approval from any of them will be enough to merge. 

My apologies for the lack of clarity in my comment. What I saw was all code owners were added to the PR as reviewers. When the repository had a branch protection rule that required reviews and also specified that a code owner review was required, only one of them needed to approve the PR.

### Plan for changes to the "About code owners" article

1. Excluding files/directories from ownership - Your pull request added an example to the [Example of a CODEOWNERS file](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#example-of-a-codeowners-file). I agree that this is a great place for this information but think this should use the alternative method described above.
2. Editing files you own and Editing files owned by multiple users/teams - I think it would be better to add a short new section to the article called "CODEOWNERS and branch protection". 
    - This would mention that you can add a branch protection rule to ensure that pull requests are always reviewed by the code owners of the changed files. 
    - Link to "[About protected branches](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)" for more information.
    - Give a short example CODEOWNERS file and explain the behavior for a code owner raising a pull request and for someone raising a pull request with two owners.

**Comment by sidletsky** [comment]
Hi @felicitymay!

Thank you for your feedback! 

I found your tip on leaving empty CODEOWNER quite useful, thank you! I've applied the changes, please let me know if anything else needs to be done.

**Comment by felicitymay** [comment]
Thanks for the great discussion about how this all works and for updating your PR to follow the plan suggested above 😄 ✨ 

I'm just waiting on the tests to run before merging your PR 🚀
