### ISSUE TITLE
Parental consent for kids

### ISSUE THREAD

**Issue by Time-dragon** [github/docs#7790]
### What article on docs.github.com is affected?

No link, but Terms of Use.

### What part(s) of the article would you like to see updated?

Account terms.

### Additional information
Parental consent means that parents take action for what they do on GitHub, similar to Replit Talk.

**Comment by janiceilene** [comment]
👋 @Time-dragon We publish the policy documents here but discussion of the site policies is done in the https://github.com/github/site-policy repository. Additionally, you will probably be interested in the discussion in https://github.com/github/site-policy/issues/42, especially https://github.com/github/site-policy/issues/42#issuecomment-315892026.
