### ISSUE TITLE
Workflow commands for GitHub Actions is stale

### ISSUE THREAD

**Issue by jsoref** [github/docs#7868]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions

### What part(s) of the article would you like to see updated?

> The following table shows which toolkit functions are available within a workflow:

### Additional information

The table isn't complete.

At the very least, it's missing:
https://github.com/actions/runner/blob/main/docs/adrs/0280-command-input-echoing.md
which added `echo '::echo::on'` and `echo '::echo::off'`.

It is probably missing a number of other things. It'd be nice if someone interviewed the team and got the documents current.

**Comment by Simran-B** [comment]
It might not be documented on purpose, as the recommended way for turning command echoing on is to create a secret `ACTIONS_RUNNER_DEBUG` with a value of `true`: [Enable debug logging](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging)

Other commands to potentially document:
- `::add-matcher` and `::remove-matcher`

Not to be documented:
- `::internal-set-repo-path`
- `::add-path` and `::set-env` ([deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/))

**Comment by jsoref** [comment]
In principle one is supposed to be able to turn toggle echo repeatedly (even w/in a single job step or action stage), which one couldn't do w/ the secret.

Anyway, the ADR is explicit, and I'll quote it:

https://github.com/actions/runner/blob/main/docs/adrs/0280-command-input-echoing.md#context
> Echo output in the user logs can be explicitly controlled by the new commands `::echo::on` and `::echo::off`.

And as secrets apply to all workflows in a repository, it really is a very large hammer for what may be potentially a tiny nail.

That said, if it shouldn't be documented, there should be an obvious place for doc writers to go to determine this.

At present, I'm fairly confident no such place exists.

**Comment by lucascosti** [comment]
Thanks for pointing this out, @jsoref!

I agree that we should document `echo '::echo::on'` and `echo '::echo::off'` as a new section in "[Workflow commands for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions)"

A new section titled something like "Echoing command outputs" that describes what  `::echo::on` and `::echo::off` do, along with examples like the existing sections. We should also mention the interaction/overlap with `ACTIONS_RUNNER_DEBUG` (how `ACTIONS_RUNNER_DEBUG` is a global setting, while these are more granular) and [link to and from its section](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging).

I'll tag this for anyone to open a PR to implement 👍

**Comment by jsoref** [comment]
Apparently I missed?
