### ISSUE TITLE
[GitHub Packages registry] Deprecated plugin in Gradle Registry guideline

### ISSUE THREAD

**Issue by rachelcarmena** [github/docs#7885]
### What article on docs.github.com is affected?

* Working with a GitHub Packages registry
  * [Working with the Gradle registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry)  

### What part(s) of the article would you like to see updated?

If I follow the guideline with latest Gradle version (`7.1`), this error raises when trying to run `mvn install`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Plugin [id: 'maven'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see 
  https://docs.gradle.org/7.1/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (plugin dependency must include a version number for this source)
```

Legacy Maven Plugin (**maven** plugin) is not included on the list of core plugins from Gradle 7.x:

* https://docs.gradle.org/7.0/userguide/plugin_reference.html
* https://docs.gradle.org/7.1/userguide/plugin_reference.html

If I try this link of **maven** plugin https://docs.gradle.org/7.1/userguide/maven_plugin.html redirects to **maven-publish** plugin https://docs.gradle.org/7.1/userguide/publishing_maven.html. However, **maven-publish** doesn't provide a task with the same behavior:

* `install` task from **maven** plugin publishes both the package under development and all the dependencies in the local Maven repository (`~/.m2/repository`).
* `publishToMavenLocal` from **mave-publish** plugin only publishes the package under development in the local Maven repository (`~/.m2/repository`).

### Additional information

I created #7142 and #7143 before. So sorry for the inconveniences, I was wrong! I made a mistake after using Gradle for a long time and forgetting the real behavior of `mvn install` command (I was thinking about the behavior of `publishToMavenLocal` task) :pray: 

I made the tests in [this repository](https://github.com/rachelcarmena/test-gh-packages). The results can be seen in [this console output](https://github.com/rachelcarmena/test-gh-packages/runs/2971927430).

GitHub Packages Registry workes like a charm, congrats and thank you so much!! :raised_hands:

**Comment by rachelcarmena** [comment]
### Additional information

I made the tests in [this repository](https://github.com/rachelcarmena/test-gh-packages). The results can be seen in [this console output](https://github.com/rachelcarmena/test-gh-packages/runs/2971927430).

**Comment by rachelcarmena** [comment]
I edited the **Additional information** in the description:

> I made the tests in [this repository](https://github.com/rachelcarmena/test-gh-packages). The results can be seen in [this console output](https://github.com/rachelcarmena/test-gh-packages/runs/2971927430).

**Comment by okeaguugochukwu** [comment]
good

**Comment by au844** [comment]
Help methank

**Comment by au844** [comment]
Thank you

**Comment by 89537065506** [comment]
чт, 8 июл. 2021 г., 23:36 au844 ***@***.***>:
