### ISSUE TITLE
Repository.ref example should be updated

### ISSUE THREAD

**Issue by jsoref** [github/docs#7958]
### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/reference/objects#repository

### What part(s) of the article would you like to see updated?

The default branch in new repositories is `main`, so, I'd suggest using either `main` or `example`

> ref (Ref) | Fetch a given ref from the repository.
> Arguments
> `qualifiedName` (`String!`)
> The ref to retrieve. Fully qualified matches are checked in order (`refs/heads/master`) before falling back onto checks for short name matches (`master`).

### Additional information

I believe this content is managed internally.

Also, this term could probably be updated site wide.

**Comment by Payaspx** [comment]
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/graphql/reference/objects#repository
> 
> ### What part(s) of the article would you like to see updated?
> The default branch in new repositories is `main`, so, I'd suggest using either `main` or `example`
> 
> > ref (Ref) | Fetch a given ref from the repository.
> > Arguments
> > `qualifiedName` (`String!`)
> > The ref to retrieve. Fully qualified matches are checked in order (`refs/heads/master`) before falling back onto checks for short name matches (`master`).
> 
> ### Additional information
> I believe this content is managed internally.
> 
> Also, this term could probably be updated site wide.

**Comment by ramyaparimi** [comment]
@jsoref  Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @jsoref, but the GraphQL docs are generated from the schema and therefore cannot be addressed in this repo.

**Comment by jsoref** [comment]
@lecoursen: I'm hoping someone can file it internally. I'm not expecting to fix it here.

**Comment by lecoursen** [comment]
Thanks for clarifying @jsoref! You can contact support at https://support.github.com about fixing issues that reside outside of this repo.
