### ISSUE TITLE
Activity type "converted_to_draft" is missing from Events that Trigger Workflows

### ISSUE THREAD

**Issue by westonpace** [github/docs#7975]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

### What part(s) of the article would you like to see updated?

In the "activity types" list for the "pull_request" trigger the activity type "converted_to_draft" is missing.  It is present on the webhook events and payloads page.  In addition, now that I compare the two directly, the following activity types also seem to be missing: auto_merge_disabled, auto_merge_enabled.

**Comment by westonpace** [comment]
In addition, these types seem to be missing from https://json.schemastore.org/github-workflow.json which causes red squiggles in my IDE.

**Comment by ramyaparimi** [comment]
@westonpace Thanks so much for opening this issue! I will triage this for review 👀

**Comment by trypod** [comment]
Delete delete delete all content with ave or try pod for slander immediately. Legal action is underway. Keep up the good work and see how much deeper it gets u

**Comment by skedwards88** [comment]
Thanks for opening this issue! You or anyone else is welcome to open a PR to add these missing types to the pull_request trigger. Note that the auto-merge types should be versioned using `{% ifversion fpt or ghes > 3.0 or ghae %}` since this feature is not available on older version of GitHub Enterprise.

**Comment by skedwards88** [comment]
> In addition, these types seem to be missing from https://json.schemastore.org/github-workflow.json which causes red squiggles in my IDE.

To address this, it looks like you can make a contribution to https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json
