### ISSUE TITLE
GET /user/repos does not return all repositories of an authenticated user

### ISSUE THREAD

**Issue by shasshsi** [github/docs#7981]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/rest/reference/repos#list-repositories-for-the-authenticated-user

According to the documentation, GET /user/repos should return all the repositories with these permissions (:read, :write, :admin).
This API was working fine some days back for me but now, it returns only the repositories that I am an owner of.

**Comment by ramyaparimi** [comment]
@shasshsi Thank you for opening this issue 👍 I will triage this for review ⚡

**Comment by lecoursen** [comment]
Thanks for letting us know, @shasshsi. This sounds like a bug. Can you please contact our support team at https://support.github.com to figure out why you're not experiencing the expected behavior? Thanks!
