### ISSUE TITLE
GitHub Actions: add more details for "workflow_run" event

### ISSUE THREAD

**Issue by BrightRan** [github/docs#799]
Associated GitHub Community: https://github.community/t/workflow-run-not-working-as-expected/139342

According to the docs about the [**`workflow_run`** event](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run), we can use the **`workflow_run`** event to trigger another workflow after a workflow run is requested or completed.

According to our tests, the **`workflow_run`** event can trigger the workflow only when the **`workflow file`** is on the **`default branch`**. However, we can't see any note about this point in the docs.

We can see the below note for some events (such as [**issues**](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issues), [**label**](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#label), etc.) in the docs:
> **Note:** This event will only trigger a workflow run if the workflow file is on the default branch.

But why you did not add the same **Note** for the **`workflow_run`** event. This **Note** also is applied to the **`workflow_run`** event.

**Comment by janiceilene** [comment]
👋 @BrightRan Thanks so much for opening an issue! Does this [Add more details about workflow_run](https://github.com/github/docs/pull/531) PR cover the information you're looking for?

**Comment by BrightRan** [comment]
Yes, that's what we want.
Thanks, @janiceilene .

**Comment by alexpapworth** [comment]
Hiya, I feel like this is still an issue. As of today (18th November) the `workflow_run` section doesn't explicitly state that it won't run until you've merged the workflow file into the default branch.

---

![Screenshot 2020-11-18 at 11 39 31](https://user-images.githubusercontent.com/25950768/99526602-5f41a100-2993-11eb-9004-99beb0717342.png)

---

Would be great if we can add the same "Note:" section, similar to what we have on the `check_run` event.

---

![Screenshot 2020-11-18 at 11 49 05](https://user-images.githubusercontent.com/25950768/99527130-340b8180-2994-11eb-97cd-01b9ff59cedb.png)

---

**Comment by janiceilene** [comment]
👋 @BrightRan I'll triage this for the team to take a look 👀

**Comment by lucascosti** [comment]
Default branch note has now been added: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run 🎉

**Comment by alexpapworth** [comment]
Thanks Lucas 😊

**Comment by Morriz** [comment]
Where can we find the documentation that describes the `github.event.workflow_run` object? It has many properties but I don't find docs on that.

**Comment by Morriz** [comment]
Of course I saw the https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run docs, but those fail to mention these extra properties. One I know of is:

`github.event.workflow_run.conclusion`

So what else exists on `github.event.workflow_run.`?
