### ISSUE TITLE
Update docker/build-push-action in "Publishing Docker images"

### ISSUE THREAD

**Issue by mmkal** [github/docs#808]
### What article on docs.github.com is affected?

[Publishing Docker images](https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images#publishing-images-to-github-packages) (and [markdown file](https://github.com/github/docs/blob/main/content/actions/guides/publishing-docker-images.md) on GitHub)

### What part(s) of the article would you like to see updated?

Update usage of `docker/build-push-action` to v2. The docs for build-push-action are very different from the usage listed here so it's not clear how v2 should be used, if at all.

**Comment by janiceilene** [comment]
Thanks for opening an issue @mmkal! I've spoken to the team and since the docs are still accurate, we aren't going to update anything. We may reevaluate that the next time we look at these docs 💖

**Comment by rajivshah3** [comment]
Hi, I opened a PR for this change in #6317 since I was initially confused by this as well
