### ISSUE TITLE
Wrong write (assign) action for triage collaborators

### ISSUE THREAD

**Issue by mxmvshnvsk** [github/docs#8098]
### What is the current behavior?

As collaborator I have a `triage` permission to repository and have assign privilege. In [documentation](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) option `Close, reopen, and assign all issues and pull requests` is available for `triage`:

<img width="736" alt="Screenshot 2021-07-11 at 21 59 05" src="https://user-images.githubusercontent.com/25287077/125205427-37d97480-e293-11eb-9fee-9276595a5acf.png">

But actually I can assign only when create a new issue, after that this functionality isn't available. With `write` permissions I can do it. In github app it with `triage` I have button for assign, but it work wrong (see attach). Where is the error and what behavior should be correct?

### What changes are you suggesting?

Fix documentations for `triage` or create new issue about a `triage` permission in in the corresponding repository.

### Additional information

App with `triage` permission:

https://user-images.githubusercontent.com/25287077/125205309-ab2eb680-e292-11eb-82c5-1ba55a170d77.mp4

**Comment by ramyaparimi** [comment]
@mxmvshnvsk Thank you for opening this issue!! Please check with the [GitHub support team](https://support.github.com/contact) for further information about what you are experiencing. Let us know if our docs could use some update regarding this after your conversation with the support ⚡ 

I am going to close this for now, let us know what you find out and we can reopen this issue!
