### ISSUE TITLE
Emoji is spelled incorrectly

### ISSUE THREAD

**Issue by IITII** [github/docs#8105]
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review_comment

### What part(s) of the article would you like to see updated?

* `emojji` -> `emoji`

![image](https://user-images.githubusercontent.com/33705067/125246026-d8777500-e323-11eb-8967-9c5f004a1d82.png)

**Comment by ramyaparimi** [comment]
@IITII Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by janiceilene** [comment]
This was fixed internally ✨ Closing this issue and thanks so much for reporting it @IITII!
