### ISSUE TITLE
Add clarification about glob chars in branch/tag matching

### ISSUE THREAD

**Issue by poikilotherm** [github/docs#8106]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

The filter pattern wasn't pointing out that chars in branch names like `+, ?, ...` need escaping, too. It sounds like `*` and `**` are the only ones. This bit me when doing an exact match for a branch with a `+` in it's named being ignored for no obvious reason.

### Additional information

See https://github.community/t/possible-bug-workflow-not-executed-for-pushes-to-pr-branch-when-base-branch-contains/189446

**Comment by Hatho86** [comment]
#8107

**Comment by Hatho86** [comment]
#8107

**Comment by Hatho86** [comment]
#8269
