### ISSUE TITLE
Remove note about systemctl

### ISSUE THREAD

**Issue by lecoursen** [github/docs#8114]
### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.0/admin/configuration/configuring-your-enterprise/command-line-utilities#ghe-service-list

### What part(s) of the article would you like to see updated?

The note about systemctl should be removed.

### Additional information

Since 2.22 services have begun to migrate to Nomad, and are no longer available with systemctl. Customers can't find many important services to restart. It doesn't look like there is anything about Nomad in the command line page, so this is best simply removed.

**Comment by ramyaparimi** [comment]
@lecoursen Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by capinoantonio** [comment]
Images and photos  videos
