### ISSUE TITLE
Update workflow-syntax-for-github-actions page with on.workflow_dispatch.inputs section

### ISSUE THREAD

**Issue by JulyBelost** [github/docs#8119]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on

### What part(s) of the article would you like to see updated?

There is no information about possibility of using inputs for workflow_dispatch event.

### Additional information

This possibility described here:
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

And here:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch

**Comment by ramyaparimi** [comment]
@JulyBelost Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by saan5** [comment]
public class MainActivity extends AppCompatActivity {

    TextView tvResult;
    ProgressDialog progressDialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        progressDialog = new ProgressDialog(this);
        progressDialog.setMessage("Loading...");
        progressDialog.setCancelable(false);
        progressDialog.setCanceledOnTouchOutside(false);
        progressDialog.create();
        progressDialog.show();

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                progressDialog.dismiss();
                tvResult.setVisibility(View.VISIBLE);
            }
        },2000);
    }
}
