### ISSUE TITLE
Typo in permission name for Dependabot Automation

### ISSUE THREAD

**Issue by fb55** [github/docs#8131]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token

### What part(s) of the article would you like to see updated?

The permission in the last example is called `contents`, not `content`; see https://github.com/fb55/entities/actions/runs/1024362370/workflow

**Comment by ramyaparimi** [comment]
@fb55 Thanks so much for opening this issue!! I will triage this for review 👀

**Comment by lucascosti** [comment]
This was fixed in https://github.com/github/docs/pull/8132
