### ISSUE TITLE
Not all Dependabot languages support private repos

### ISSUE THREAD

**Issue by ramyaparimi** [github/docs#8188]
### What article on docs.github.com is affected?

https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-and-analysis-settings-for-your-organization

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-dependencies

Not all languages (Ruby being one of them) supported by Dependabot support private dependencies. Adding this information to the docs could help give some clarity.

### Additional information

This created based on this https://github.com/github/docs/pull/7768
Also, this link could be some additional info https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

---

### Content design plan

We mention that you can use Dependabot with private repositories and registries in quite a few places, but you're right that we don't mention that private repositories are not supported for all ecosystems. I suggest that make the following changes to the docs:

1. Create a [reusable](https://github.com/github/docs/tree/main/data/reusables) that explains that private repositories are not supported for all ecosystems.
2. Replace the following text in [Enabling and disabling version updates](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates) with the new reusable.
    > Additionally, Dependabot doesn't support private GitHub dependencies for all package managers. For more information, see "[About Dependabot version updates](/github/administering-a-repository/about-dependabot-version-updates#supported-repositories-and-ecosystems)" and "[GitHub language support](/github/getting-started-with-github/github-language-support)."
3. Add the reusable to the following articles:
    - [Managing encrypted secrets for Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-encrypted-secrets-for-dependabot) 
    - [Managing security and analysis settings for your organization](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-dependencies)

**Comment by gsteele178** [comment]
I'll get right on it!

**Comment by felicitymay** [comment]
@ramyaparimi Thanks for the clear explanation and links to relevant articles ✨ 

I had a look at the articles you mentioned and have written a basic content design plan for the changes.

**Comment by Alsabti5810** [comment]
Okay I’m sorry 😍

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Felicity Chapman ***@***.***>
‏‏تم الإرسال: Thursday, July 29, 2021 8:25:41 PM
إلى: github/docs ***@***.***>
نسخة: Subscribed ***@***.***>
‏‏الموضوع: Re: [github/docs] Not all Dependabot languages support private repos (#8188)


@ramyaparimi<https://github.com/ramyaparimi> Thanks for the clear explanation and links to relevant articles ✨

I had a look at the articles you mentioned and have written a basic content design plan for the changes.

**Comment by Hussamsami** [comment]
hhh

**Comment by cmwilson21** [comment]
Looks like this one has been completed. I'm going to close the issue now.
