### ISSUE TITLE
Clarify usage of X.509 certificates to sign commits on Linux

### ISSUE THREAD

**Issue by ChristianCiach** [github/docs#8227]
### What article on docs.github.com is affected?

https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/telling-git-about-your-signing-key

### What part(s) of the article would you like to see updated?

On the "Linux" tab, the blue box at the top of the page states:

> Note: X.509 keys are not supported on Linux. You can configure gpgsm to provide encryption and signing services, however, this is not currently supported by GitHub. For more information, see the gpgsm topic in the GnuPG documentation.

Maybe I do not fully understand what you mean by "is not currently supported by GitHub", but I think this is wrong. I was just able to sign my commit using gpgsm on Linux without issues.

![grafik](https://user-images.githubusercontent.com/19341644/125675716-d54202c6-d28b-4156-9250-5b946a500549.png)

Maybe this note is outdated?

**Comment by ramyaparimi** [comment]
@ChristianCiach Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks @ChristianCiach! Sounds like it is outdated. You or anyone else is welcome to remove that note.

**Comment by thispsj** [comment]
I have done this in #8365

**Comment by phil-blain** [comment]
@ramyaparimi The outdated note was removed in #8365, but the docs still does not mention how to use X.509 certificates on Linux... Something like https://docs.gitlab.com/ee/user/project/repository/x509_signed_commits/#linux should be added, I think.

**Comment by ramyaparimi** [comment]
@phil-blain Ah, makes sense. I will re-triage this issue for a review 👀
