### ISSUE TITLE
Fix miscellaneous errors in GitHub Actions / Reference / Workflow syntax

### ISSUE THREAD

**Issue by gsrohde** [github/docs#825]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
### What part(s) of the article would you like to see updated?

1. Under the section `jobs.<job_id>.steps.run` in the subsection [Exit codes and error action preference](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference): Under the bullet point for `cmd`, the second item starts out "cmd.exe will exit with the error level of the last program it executed, and it will and return the error code to the runner."  The second "and" is extraneous and should be deleted.

2. The last sentence in the section [`jobs.<job_id>.steps.with.entrypoint`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswithentrypoint) reads "The entrypoint keyword is meant to use with Docker container actions, but you can also use it with JavaScript actions that don't define any inputs."  "to use" should be changed to "to be used".

3. This is a general comment about the _syntax_ of the syntax article: Since, for the most part, the YAML used in workflow files can be considered a form of JSON, it indeed makes some sense to use JavaScript-like syntax to refer to the parts of the YAML file.  For example, `jobs.<job_id>.timeout-minutes` clearly refers to the value corresponding to the `timeout-minutes` key in the hash value corresponding to the `<job_id>` key in the hash value corresponding to the `jobs` key, and this is precisely how you would refer to it in JavaScript.  Where it gets confusing is in notations such as `jobs.<job_id>.steps.timeout-minutes`.  This is because the value corresponding to the `steps` key is not another hash but rather an array (of steps).  Using the dot notation obscures the fact that in this case, `timeout-minutes` applies to a particular step and doesn't apply to the set of steps as a whole.  It would be clearer to write something like `jobs.<job_id>.steps[n].timeout-minutes` to make clear that `timeout-minutes` applies only to some particular step `n` and not to all steps.  The `[n]` here stands in for any step in the sequence analogously to the way `<job_id>` stands in for some particular key in the `jobs` hash.

**Comment by derek0911** [comment]
> ### docs.github.com上的哪篇文章受到影響？
> [https://docs.github.com/cn/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions)
> 
> ### 您希望看到文章的哪些部分進行了更新？
> 1. 在“[退出代碼和錯誤操作首選項](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)`jobs.<job_id>.steps.run`”小節的部分下：在的要點下，第二個項目以“ cmd.exe退出，並返回其執行的最後一個程序的錯誤級別，並將錯誤代碼返回給跑步者。” 第二個“和”是多餘的，應刪除。[](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)`cmd`
> 2. 本節的最後一句[`jobs.<job_id>.steps.with.entrypoint`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswithentrypoint)為“ entrypoint關鍵字旨在與Docker容器操作一起使用，但是您也可以將其與未定義任何輸入的JavaScript操作一起使用。” “使用”應更改為“使用”。
> 3. 這是對語法文章的_語法_的一般評論：由於在大多數情況下，可以將工作流文件中使用的YAML視為JSON的一種形式，因此使用類似JavaScript的語法來引用這些部分確實有意義。 YAML文件。例如，在哈希值中與鍵對應的哈希值中與鍵`jobs.<job_id>.timeout-minutes`相對應的`timeout-minutes`鍵中明確地引用了與該鍵相對應的`<job_id>`值`jobs`，這正是在JavaScript中引用它的方式。令人困惑的地方是諸如的符號`jobs.<job_id>.steps.timeout-minutes`。這是因為與`steps`鍵對應的值不是另一個哈希，而是一個（步驟）數組。使用點符號會掩蓋一個事實，在這種情況下，`timeout-minutes`適用於特定步驟，不適用於整個步驟集。寫類似`jobs.<job_id>.steps[n].timeout-minutes`澄清的東西會更清楚一些，`timeout-minutes`它只適用於某些特定步驟`n`，而不適用於所有步驟。在`[n]`這裡矗立在為序列類似的方式在任何一步`<job_id>`矗立在在一些特定的鍵`jobs`哈希值。

**Comment by janiceilene** [comment]
Thanks so much for opening an issue @gsrohde! I'll triage it for the right folks to take a look 👀

**Comment by lucascosti** [comment]
Thanks for pointing these out, @gsrohde!

1. and 2. should be easy fixes for anyone to pick up.

For 3., I do understand your description of the issue, but I think we'll need to discuss this one in the content team to maybe see if it's practical to implement for the improvement it would create. At the moment there are a lot of existing docs and product links to those sections, and if we were to update all the `steps.<something>` headings, those links everywhere will also need to be updated.

**Comment by janiceilene** [comment]
I'm going to add a `good first issue` label on this one and anyone is welcome to open a PR to fix 1 & 2 only 💛

**Comment by JBryceOrtiz** [comment]
I will fix 1 & 2 now!

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望
