### ISSUE TITLE
Missing field in doc of LanguageEdge (GraphQL API)

### ISSUE THREAD

**Issue by cicirello** [github/docs#8287]
### What article on docs.github.com is affected?

The GraphQL API documentation, specifically the page on objects:
https://docs.github.com/en/graphql/reference/objects

### What part(s) of the article would you like to see updated?

Two errors:
* LanguageEdge is missing the node field.
* LanguageConnection indicates that the totalSize field is the total size of "that language" when 
  it is actually the total size of all languages in the connection.

**Comment by ramyaparimi** [comment]
@cicirello Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Hi @cicirello, thanks for noticing this! Our GraphQL reference docs are generated from the schema and can't be addressed in this repo. Can you please report this to support at https://support.github.com instead? Thanks!
