### ISSUE TITLE
Jekyll tutorial, Gemfile.lock issues

### ISSUE THREAD

**Issue by Siphonophora** [github/docs#8292]
### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll#creating-your-site

### What part(s) of the article would you like to see updated?

Point 10 describes how to edit the `Gemfile`. After doing so, `bundle update` reported two dependency compatibility issues in the lock file. After a bunch of messing with this, I eventually deleted everything in `GEM specs:` and `DEPENDENCIES` from the lock file. After doing so, `bundle update` rebuilt the lock file and didn't have any errors. 

I am totally new to ruby and gem. If this is the right way to handle this, please add it or the correct version to the docs.

**Comment by Ferchoperedo** [comment]
> 
> ### What article on docs.github.com is affected?
> 
> https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll#creating-your-site
> ### What part(s) of the article would you like to see updated?
> 
> Point 10 describes how to edit the `Gemfile`. After doing so, `bundle update` reported two dependency compatibility issues in the lock file. After a bunch of messing with this, I eventually deleted everything in `GEM specs:` and `DEPENDENCIES` from the lock file. After doing so, `bundle update` rebuilt the lock file and didn't have any errors.
> 
> I am totally new to ruby and gem. If this is the right way to handle this, please add it or the correct version to the docs.

Thats, ok.

**Comment by Ferchoperedo** [comment]
Remove the GEM spec: and options from the lock file and update it.

**Comment by ramyaparimi** [comment]
@Siphonophora Thanks so much for opening an issue! I'll get this triaged for review :zap:

**Comment by lecoursen** [comment]
Thanks for letting us know you had difficultly following this procedure, @Siphonophora! 😕 To make sure we're updating the docs correctly, could you reach to our support team at https://support.github.com to verify that your solution was the right one? You can then re-open this issue with confirmation from them... or with another solution if that's what they provide! Thanks again!

**Comment by tmetz** [comment]
The consensus from Support and the Pages engineering team is that we suggest the best option would be to replace the command in step 7 with:

```
jekyll _3.9.1_ new . --skip-bundle
```

I will also note that this will work without specifying the Jekyll version, _as long as the `--skip-bundle` flag is included_, e.g.

```
jekyll new . --skip-bundle
```

Also, this only appears to be a problem with Windows, but the new command works fine on Mac if it's easier to just update all of the OS versions with the same command.

**Comment by hubwriter** [comment]
The instructions have now been updated. Closing this issue. 🎉
