### ISSUE TITLE
Link to GitHub event types documentation

### ISSUE THREAD

**Issue by OldSneerJaw** [github/docs#8295]
### What article on docs.github.com is affected?

[context-and-expression-syntax-for-github-actions.md](https://github.com/github/docs/blob/main/content/actions/reference/context-and-expression-syntax-for-github-actions.md) from the GitHub Actions docs.

### What part(s) of the article would you like to see updated?

The [`github` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)'s listing for the `event` field should include a link to the [GitHub event types page](https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types) so the reader can determine which fields are available on it. Otherwise, one is left to infer the intention and hunt down the correct documentation.

### Additional information

I intend to open an accompanying pull request to make this change shortly.

**Comment by ramyaparimi** [comment]
@OldSneerJaw Thanks so much for opening a PR! I'll get this triaged for review :zap:
