### ISSUE TITLE
Add table anchors in About billing for GitHub Actions

### ISSUE THREAD

**Issue by jsoref** [github/docs#8368]
### What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

### What part(s) of the article would you like to see updated?

Each of these should have a section so that one could easily link to it:
https://github.com/github/docs/blob/77e4e47c7460acbc0ff6a41897fd2854cc1bf5e3/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#L26-L32
https://github.com/github/docs/blob/77e4e47c7460acbc0ff6a41897fd2854cc1bf5e3/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#L36-L40
https://github.com/github/docs/blob/77e4e47c7460acbc0ff6a41897fd2854cc1bf5e3/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#L52-L56
https://github.com/github/docs/blob/77e4e47c7460acbc0ff6a41897fd2854cc1bf5e3/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#L64-L68
https://github.com/github/docs/blob/77e4e47c7460acbc0ff6a41897fd2854cc1bf5e3/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#L70-L75

### Additional information

I want to be able to link to the section that identifies macos runners as considerably more expensive than linux runners, but I can't because there are no sections for the tables.

**Comment by raunak6662** [comment]
@jsoref you want the updated doc to have the link that you have mentioned above with each section?

<img width="610" alt="pic_1" src="https://user-images.githubusercontent.com/61631789/126213731-25b97f6a-8610-4eb7-b9a0-215e9c771b32.png">

The above snip has one section with its link.

**Comment by jsoref** [comment]
@raunak6662: I have no idea what you're saying.

Here's what I want:
https://github.com/jsoref/github-docs/blob/billing-anchors/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#included-storage-and-minutes-per-month
https://github.com/jsoref/github-docs/blob/billing-anchors/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#operating-system-minute-multiplier
https://github.com/jsoref/github-docs/blob/billing-anchors/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#operating-system-per-minute-rate
https://github.com/jsoref/github-docs/blob/billing-anchors/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#sample-minutes-cost-calculation
https://github.com/jsoref/github-docs/blob/billing-anchors/content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md#sample-storage-cost-calculation

**Comment by raunak6662** [comment]
@jsoref am new to open source and just need a bit more help.
In the attached pic, you want to update the text to a link. right?

![image](https://user-images.githubusercontent.com/61631789/126219330-75327612-bf12-4b04-9d8a-7690d2e9def9.png)

If not, cayou please explain me a little more so that I can contribute to it.

**Comment by ramyaparimi** [comment]
@jsoref Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
I agree that this would be helpful for users and also for our own support team! You or anyone else is welcome to open a PR to add headers to those sections.
