### ISSUE TITLE
Missing translation for PT-BR

### ISSUE THREAD

**Issue by joaopedrocampos** [github/docs#8440]
### What article on docs.github.com is affected?

https://docs.github.com/pt/github/setting-up-and-managing-your-github-user-account/managing-user-account-settings/about-your-personal-dashboard#staying-updated-with-activity-from-the-community

### What part(s) of the article would you like to see updated?

There is a missing translation on the "Atualizações serão exibidas no feed de notícias quando um usuário que você segue" item.

There is one bullet in English, **"Follows another user."**, when it should be translated to Portuguese as **"Seguir outro usuário"**

### Additional information

<img width="677" alt="Screen Shot 2021-07-22 at 13 33 02" src="https://user-images.githubusercontent.com/20289185/126675439-c5075a4c-6e4a-466d-99a2-41107d54b9fb.png">

**Comment by ramyaparimi** [comment]
@joaopedrocampos Thanks for opening this issue! Unfortunately, we are not able to accept issues for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

**Comment by joaopedrocampos** [comment]
@ramyaparimi hey, thanks for the reply!

Actually I read some other issues and saw that translation contributions were not accepted since currently GitHub uses crowin for it, but in some of thes I saw that the problem found was reported to crowin so they could fix it, so the porpouse of this issue was similar, address them this problem so they could fix it.

There is another way to report translation problems found in the docs?

**Comment by Chynia828** [comment]
Sorry Today the mood is lousy, I think I will deal with this issue tomorrow.

пт, 23 июл. 2021 г., 15:29 Ramya Parimi ***@***.***>:

**Comment by janiceilene** [comment]
Thanks so much for letting us know @joaopedrocampos! @ramyaparimi is still getting access to all of the internal places 😅 so I reported this issue to our translators internally, in the meantime 💖

**Comment by joaopedrocampos** [comment]
Hey @janiceilene! No problem at all, thank you for the feedback and hope this was helpful for you there 🙏
