### ISSUE TITLE
Remove double 'and' in documentation

### ISSUE THREAD

**Issue by AdrianLThomas** [github/docs#846]
### What is the current behavior?

On this page: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/sharing-workflows-with-your-organization
>  allows you to centrally store **and** and manage secrets

### What changes are you suggesting?

Drop an 'and'.

### Additional information

N/A

**Comment by janiceilene** [comment]
Thanks for creating a PR and closing this issue out @AdrianLThomas! 🎉
