### ISSUE TITLE
Prerequisites for RubyGems registry are not flat

### ISSUE THREAD

**Issue by tnir** [github/docs#8499]
### What article on docs.github.com is affected?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry

### What part(s) of the article would you like to see updated?

Prerequisites for RubyGems registry should be flat.

![docs github com_en_packages_working-with-a-github-packages-registry_working-with-the-rubygems-registry](https://user-images.githubusercontent.com/10229505/126852331-3b16d1e6-f195-47da-9c2b-c7453b01739c.png)

### Additional information
n/a

**Comment by ramyaparimi** [comment]
@tnir Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
