### ISSUE TITLE
Code is corrupted in the translation.

### ISSUE THREAD

**Issue by kurehajime** [github/docs#8516]
### What article on docs.github.com is affected?

Page of `Working with SSH key passphrases` 

https://docs.github.com/ja/github/authenticating-to-github/connecting-to-github-with-ssh/working-with-ssh-key-passphrases

### What part(s) of the article would you like to see updated?

Code of `auto-launching-ssh-agent-on-git-for-windows`

### Additional information

It's not old code, it's probably corrupted.

[Code in English version.](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/working-with-ssh-key-passphrases)
It works.

```
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env
```

[Code in Japanese version.](https://docs.github.com/ja/github/authenticating-to-github/connecting-to-github-with-ssh/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-git-for-windows)
There is a `elif` but no `if`.

```
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && .

"$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi
```

[Code in Portuguese version.](https://docs.github.com/pt/github/authenticating-to-github/connecting-to-github-with-ssh/working-with-ssh-key-passphrases)
There is only `if`.

```
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ !

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env
```

[Code in German version.](https://docs.github.com/de/github/authenticating-to-github/connecting-to-github-with-ssh/working-with-ssh-key-passphrases)
The same code is repeated.

```
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=Agent wird mit Schluessel ausgeführt; 1=Agent ohne Schluessel; 2=Agent wird nicht ausgefuehrt
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env
```

**Comment by lucalves** [comment]
You're right, @kurehajime. I would like to work on this fix, but it seems that the content is automatically translated, so I don't know how to fix it. Let's wait for the triage of this Issue.

**Comment by ramyaparimi** [comment]
@kurehajime Thanks for opening this issue! Unfortunately, we are not able to accept issues for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

**Comment by kurehajime** [comment]
OK.

I know it's a difficult problem, but wrong code has more impact than wrong text, so I hope it will be fixed soon.

**Comment by janiceilene** [comment]
Thanks for calling that out @kurehajime! I'm going to reopen this and triage it to the engineering team since it looks like the English content is accurate 💛

**Comment by JamesMGreene** [comment]
@kurehajime Thank you for calling these out! I have manually fixed them for now. 🛠️

We are also discussing with another internal team how to ensure we prevent this from recurring. 🙇🏻‍♂️ 🤞🏻
