### ISSUE TITLE
Raw link doesn't appear to be documented

### ISSUE THREAD

**Issue by jsoref** [github/docs#8530]
### What article on docs.github.com is affected?

#8031

### What part(s) of the article would you like to see updated?

An explanation of how to view raw documents would be useful. I tried searching docs for `raw` and can't find anything

There's a widget in many pages for this:
![image](https://user-images.githubusercontent.com/2119212/126888185-e4888207-b523-4bd3-8ef6-fe8400ad3d90.png)
But, it doesn't appear to actually be documented. This leads to users reporting:

### Additional information

https://github.community/t/feature-request-allow-the-user-to-download-a-single-file/191964

**Comment by ramyaparimi** [comment]
@jsoref Where would you expect to see the information on the raw button?

**Comment by jsoref** [comment]
Dunno. I haven't done a complete read-through of the docs. But ideally it's somewhere such that searching for `download file` or `raw` in docs.github.com would find it. If there's a page that talks about viewing files, it should be there. If such a page doesn't exist, it probably should.

(I usually use `search` more-so than reading complete documentation, partially because docs tend to be too large to read _start to finish_.)

**Comment by jsoref** [comment]
https://docs.github.com/en/github/managing-files-in-a-repository/managing-files-on-github/getting-permanent-links-to-files

Seems to be a vaguely reasonable place to hang this. OR as a sibling to it.

**Comment by lecoursen** [comment]
Thanks @jsoref. Let's rename "[Tracking changes in a file](https://docs.github.com/en/github/managing-files-in-a-repository/managing-files-on-github/tracking-changes-in-a-file)" to "Viewing a file". The renamed article should include the current content plus a procedure for viewing the raw file. Let's also think about SEO when writing the intro, trying to include likely search terms like `raw` and `download file` there. You or anyone else is welcome to open that PR!

**Comment by BlizzyRaptor** [comment]
Sorry I'm not at all understanding. Do you have a like to install

**Comment by jsoref** [comment]
I hope people will pardon this offtopic thread...

<details><summary>@BlizzyRaptor, you're a "watcher"</summary>

According to https://github.com/github/docs/watchers?page=27:
![image](https://user-images.githubusercontent.com/2119212/152004292-c2929027-af86-43c4-aaa7-c5dde58ba340.png)

</details>

* Essentially, this means that you used [watch](https://docs.github.com/en/get-started/quickstart/be-social#watching-a-repository) at the top of this repository.
* There's documentation about [viewing and removing watches](
https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions).
* You can [configure which github events send email to you](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#customizing-your-email-notifications).

The above aside, I'm wondering why you would have subscribed to this repository in the first place. I regularly encounter people replying to email like the one you replied to, and it's a bit confusing to me.

If I were you, I probably wouldn't want to watch this repository (it's incredibly active) -- thus watching it would result in a constant stream of notifications and email messages.
