### ISSUE TITLE
https://nuxtjs.org/docs/2.x/get-started/installation 🐛🐞 cybersecurity 

### ISSUE THREAD

**Issue by Alilux** [github/docs#8541]

**Comment by Edord99** [comment]
> ### What article on docs.github.com is affected?
> ### What part(s) of the article would you like to see updated?
> ### Additional information
###632

**Comment by ramyaparimi** [comment]
@Alilux This issue is blank and appears to have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!
