### ISSUE TITLE
Fix miscellaneous errors in "Filter Pattern" section of GitHub Actions / Reference / Workflow syntax

### ISSUE THREAD

**Issue by gsrohde** [github/docs#855]
### What article on docs.github.com is affected?

This pertains to https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions.  (I could have updated issue #825 but chose to make a new issue instead.)

### What part(s) of the article would you like to see updated?

This issue has to do with the [File pattern cheat sheet](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) section of the article.

1.  The third sentence in the explanation of the meaning of `[]` is "For example, the range[0-9a-f] matches any digits or lowercase letter."  This, of course, is not true; it doesn't match "g" for example.  Either the range should be changed to `[0-9a-z]`, or the explanation should read "any digit or any of the lowercase letters `a` through `f`."  Note that in any case, strictly speaking, it should read "any digit", not "any digits", although I doubt anyone will be particularly confused by "any digits."
2. In the [Patterns to match branches and tags](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags) and [Patterns to match file paths](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-file-paths) (sub)sections, all of the example matches appear to start with a hyphen.  For example, the very first branch-matching pattern shown is `feature/*`, and the example matches given appear to be `-feature/my-branch` and `-feature/your-branch`, which don't actually match the given pattern.  I'm guessing that the initial hyphen is meant to serve the function of a bullet point and not meant to be considered as part of the matched text, but this is rather confusing, especially since the matches also contain internal hyphens.  In some cases, hyphens appear at the start of the patterns themselves, but pattern examples such as `-!README.md` suggest that the hyphen is not meant as part of the pattern.

**Comment by janiceilene** [comment]
Thanks for opening an issue @gsrohde! I'll get this triaged so someone can take a look ⚡

**Comment by lucascosti** [comment]
Thanks for this one too, @gsrohde!


> 1. ...  "For example, the range[0-9a-f] matches any digits or lowercase letter." This, of course, is not true; it doesn't match "g" for example. Either the range should be changed to [0-9a-z], or the explanation should read "any digit or any of the lowercase letters a through f."

😆 haha yep, you are totally correct. Maybe the original author was thinking in hex when they wrote that? (definitely could have been me 😁)

> 2. In the Patterns to match branches and tags and Patterns to match file paths (sub)sections, all of the example matches appear to start with a hyphen. 

I think your analysis of the hyphens supposing to represent bullet points is probably correct. I agree that it is confusing;  unfortunately markdown support in table cells is too great. I think we should probably remove the hyphens and just have each example on a separate line.

Anyone can feel free to pick up and implement ☝️ 🙂
