### ISSUE TITLE
docs.github.com pages are loaded and become blank immediately in Safari (In Firefox - Ok).

### ISSUE THREAD

**Issue by MykhailoMe** [github/docs#8564]
https://docs.github.com pages are loaded and become blank immediately in Safari Version 13.1.3 (15609.4.1). MacOS 10.15.7
In Firefox (68.9.0) - Ok.

For example:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github

There are 4 errors:

<img width="1238" alt="Screenshot 2021-07-26 at 19 23 52" src="https://user-images.githubusercontent.com/86655242/127024375-c1792c41-d120-4de1-a4b7-fd91d0d0225c.png">

1st:

> [Error] TypeError: o.addEventListener is not a function. (In 'o.addEventListener("change",n)', 'o.addEventListener' is undefined)
> 	uu (framework-92300432a1172ef1338b.js:1:82794)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:85233)
> 	fa (framework-92300432a1172ef1338b.js:1:48711)
> 	hu (framework-92300432a1172ef1338b.js:1:86491)
> 	Li (framework-92300432a1172ef1338b.js:1:103226)
> 	Li
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:129591)
> 	Ti (framework-92300432a1172ef1338b.js:1:99961)
> 	vi (framework-92300432a1172ef1338b.js:1:96047)
> 	vi
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:45200)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:129591)
> 	Ql (framework-92300432a1172ef1338b.js:1:45146)
> 	Hl (framework-92300432a1172ef1338b.js:1:45081)
> 	Fi (framework-92300432a1172ef1338b.js:1:104993)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:129591)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:104179)
> 	I (framework-92300432a1172ef1338b.js:1:128650)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:127372)
> 

2nd

> [Error] TypeError: o.addEventListener is not a function. (In 'o.addEventListener("change",n)', 'o.addEventListener' is undefined)
> 	me (main-9fba886f1a0d36fd1a02.js:1:7910)
> 	fn (main-9fba886f1a0d36fd1a02.js:1:9332)
> 	value (main-9fba886f1a0d36fd1a02.js:1:4970)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:85276)
> 	fa (framework-92300432a1172ef1338b.js:1:48711)
> 	hu (framework-92300432a1172ef1338b.js:1:86491)
> 	Li (framework-92300432a1172ef1338b.js:1:103226)
> 	Li
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:129591)
> 	Ti (framework-92300432a1172ef1338b.js:1:99961)
> 	vi (framework-92300432a1172ef1338b.js:1:96047)
> 	vi
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:45200)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:129591)
> 	Ql (framework-92300432a1172ef1338b.js:1:45146)
> 	Hl (framework-92300432a1172ef1338b.js:1:45081)
> 	Fi (framework-92300432a1172ef1338b.js:1:104993)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:129591)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:104179)
> 	I (framework-92300432a1172ef1338b.js:1:128650)
> 	(anonymous function) (framework-92300432a1172ef1338b.js:1:127372)

3rd:

> [Error] Error rendering page: 
> TypeError: undefined is not an object (evaluating 'e.cookies')
> b — _app-ee93e6e302f244349012.js:19:215074
> (anonymous function) — _app-ee93e6e302f244349012.js:19:217192
> l — main-9fba886f1a0d36fd1a02.js:1:76748
> (anonymous function) — main-9fba886f1a0d36fd1a02.js:1:76533
> o — _app-ee93e6e302f244349012.js:19:217867
> c — _app-ee93e6e302f244349012.js:19:218071
> promiseReactionJob
> 	promiseReactionJob

4th:

> [Error] Failed to load resource: the server responded with a status of 403 () (events, line 0)

**Comment by MykhailoMe** [comment]
Here is additional information about 403 error:
<img width="996" alt="Screenshot 2021-07-26 at 19 37 42" src="https://user-images.githubusercontent.com/86655242/127026455-e8000f73-540c-4f38-91e8-625552a3ca2e.png">
<img width="1221" alt="Screenshot 2021-07-26 at 19 38 53" src="https://user-images.githubusercontent.com/86655242/127026499-e92b50b7-3c2b-4895-b087-28471ce33e62.png">

**Comment by ramyaparimi** [comment]
@MykhailoMe Thanks so much for opening an issue! It looks like our systems had a little blip, but should be back up and running. I've checked all the pages you listed in Safari and I'm not seeing any trouble. I'm going to close this now, but please let us know if you're still seeing errors and we'll get this triaged to the engineering team :yellow_heart:

**Comment by MykhailoMe** [comment]
@ramyaparimi, thank you for the answer!

But unfortunately, I still see that problem in Safari.
<img width="1054" alt="Screenshot 2021-07-27 at 20 20 15" src="https://user-images.githubusercontent.com/86655242/127199468-5fc8df62-e513-48b1-9417-bc74ecaaacc9.png">

And only override helps me work with docs.github using Safari.

<img width="1047" alt="Screenshot 2021-07-27 at 20 23 30" src="https://user-images.githubusercontent.com/86655242/127199704-8224a19b-cf63-4469-9d05-4c09ccf60d3f.png">

**Comment by DaveSkender** [comment]
This has been a persistent problem for me too, Safari on iPad Mini iOS 12.5.2.  Not intermittent.  Blank screen, every page on the site.

**Comment by DaveSkender** [comment]
This is persistently happening to me too, for all pages in the site using Safari, Firefox, and Chrome, even in Incognito mode, on my iPad Mini 3 iOS 12.5.4.  It loads, then goes entirely blank.  It’s not intermittent and has been like this for a while.  Works fine on other devices and for other websites.

**Comment by ramyaparimi** [comment]
@MykhailoMe Thank you for letting us know about this. I am reopening this issue for review 👀

**Comment by ramyaparimi** [comment]
@DaveSkender @MykhailoMe May be there is a firewall or corporate network that is blocking some of the resources needed to load the page. Could you please try accessing the site from a different network?

**Comment by DaveSkender** [comment]
I’m on a home network, only happens on one device / screen size + does not happen for any other site on same network.  If I were to guess, it looks like a UI responsive design bug.

**Comment by MykhailoMe** [comment]
@ramyaparimi Hello, Ramya!

Thank you for the re-opening! 
As I stated in the title - in Firefox it is absolutely okay.
But just in case - I used tethering of my mobile. It is the same situation. (please have a look on fresh screenshots, also as it was earlier - "github" (185.199.110.154:443) returns 403 error for POST request (which was sent by _app-09b4f07abe41609b2213.js:1:60684))

In Firefox there is not such error.

Attachments:
<img width="1248" alt="Screenshot 2021-08-02 at 22 45 41" src="https://user-images.githubusercontent.com/86655242/127916142-9aa8821b-343d-4d1a-95cf-b7b4af211997.png">
<img width="998" alt="Screenshot 2021-08-02 at 22 53 24" src="https://user-images.githubusercontent.com/86655242/127916146-931bbcc9-88c7-4e11-ad2c-365aa00e1811.png">
<img width="951" alt="Screenshot 2021-08-02 at 22 53 48" src="https://user-images.githubusercontent.com/86655242/127916150-98bc4613-10d5-4458-8fd3-18023c2ef9ff.png">

@DaveSkender Thank you, Dave for your messages!

**Comment by thispsj** [comment]
Hey this happens even on older versions of Chrome.

**Comment by MykhailoMe** [comment]
@ramyaparimi I checked similar issue with another site:
https://github.com/primer/react/issues/1366

The problem is in "useTheme"?

**Comment by rachmari** [comment]
There is another report of this issue here: https://github.com/github/docs/issues/9120. We're waiting for this to get fixed in https://github.com/primer/react/issues/1366.

**Comment by ramyaparimi** [comment]
@MykhailoMe the team worked on a a fix for this. Could you let me know if you still have the issue?

**Comment by DaveSkender** [comment]
Works now on my old iPad mini.  Thank you!

**Comment by MykhailoMe** [comment]
@ramyaparimi Thank you and team! It works, no blank screens! No errors. That is a relief )

@DaveSkender @thispsj @rachmari @heiskr @gracepark  thank all of you!
Sincerely.

**Comment by ramyaparimi** [comment]
> @ramyaparimi Thank you and team! It works, no blank screens! No errors. That is a relief )
> 
> @DaveSkender @thispsj @rachmari @heiskr @gracepark thank all of you!
> Sincerely.

That is great to hear!!!!!!! 💖

**Comment by hamzamogni** [comment]
Hey,

I am experiencing this exact same bug in chrome (even in incognito), it works fine in firefox.

These errors comes out in browser console

`
DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
    at O (https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:62181)
    at https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:63455
    at _ (https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:63547)
    at https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:68145
    at Mu (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:125183)
    at t.unstable_runWithPriority (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:150037)
    at $l (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:65354)
    at Ou (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:124644)
    at Me (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:136963)
    at Xt (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:44052)
`

======================================

`
main-01c5fd917a69a18b1bf5.js:1 DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
    at O (https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:62181)
    at https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:63455
    at _ (https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:63547)
    at https://docs.github.com/_next/static/chunks/pages/_app-f6933939bae38985e31b.js:1:68145
    at Mu (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:125183)
    at t.unstable_runWithPriority (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:150037)
    at $l (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:65354)
    at Ou (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:124644)
    at Me (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:136963)
    at Xt (https://docs.github.com/_next/static/chunks/framework-2b8be631586cbbc6886e.js:1:44052)
`

=================================

`
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
`

==================================

`
main-01c5fd917a69a18b1bf5.js:1 Error rendering page:  TypeError: Cannot read property 'cookies' of undefined
    at p (_app-f6933939bae38985e31b.js:1)
    at _app-f6933939bae38985e31b.js:1
    at l (main-01c5fd917a69a18b1bf5.js:1)
    at Generator._invoke (main-01c5fd917a69a18b1bf5.js:1)
    at Generator.next (main-01c5fd917a69a18b1bf5.js:1)
    at a (_app-f6933939bae38985e31b.js:1)
    at c (_app-f6933939bae38985e31b.js:1)
`

**Comment by thispsj** [comment]
@hamzamogni this seems to an issue at your end. Can you check it on other browsers on the same device or maybe update Chrome ?
Because this issue is a bug on older Chrome Browsers and has been fixed.

See [this](https://crbug.org/490015) for more info.

**Comment by hamzamogni** [comment]
@thispsj I can confirm issue fixed after updating chrome to latest version. 

Thank You.
