### ISSUE TITLE
Incorrect dependency group in Dependabot setting docs

### ISSUE THREAD

**Issue by clifff** [github/docs#8575]
### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#allow

### What part(s) of the article would you like to see updated?

In the `production` dependency type, the docs mention 'Only dependencies in the "Product dependency group"', which I suspect should be the "Production dependency group" instead.

**Comment by MFirdausPutra1507111532** [comment]
Pada tanggal Sel, 27 Jul 2021 05:49, welcome[bot] ***@***.***>
menulis:
