### ISSUE TITLE
Incorrect Codespaces limit

### ISSUE THREAD

**Issue by thispsj** [github/docs#8590]
### What article on docs.github.com is affected?

[This Article](https://docs.github.com/codespaces/developing-in-codespaces/creating-a-codespace)

### What part(s) of the article would you like to see updated?

The article says there's a two codespaces limit for everyone during public beta. But this isn't the situation now I guess. I was able to create 3.

### Additional information
![More than 2 codespaces](https://user-images.githubusercontent.com/51746608/127186482-df12b4fa-91bd-4af9-a5a6-b7003af74e51.png)

**Comment by ramyaparimi** [comment]
@thispsj thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lecoursen** [comment]
Thanks for pointing that out @thispsj! I just confirmed with the team that the current limit is 5. You or anyone else is welcome to create a PR fixing that. ⚡

**Comment by thispsj** [comment]
Ok @lecoursen I'll send in a PR.
