### ISSUE TITLE
Quản trị oan ninh mạng quốc tế

### ISSUE THREAD

**Issue by TuanPm86** [github/docs#8599]

**Comment by ramyaparimi** [comment]
@TuanPm86 This issue is blank and appears to have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!

**Comment by TuanPm86** [comment]
International social network security administrator

**Comment by TuanPm86** [comment]
![Screenshot_2021_0816_214331](https://user-images.githubusercontent.com/85289861/129608391-9367095c-e828-4216-9628-5e947a834d14.png)

**Comment by TuanPm86** [comment]
![Screenshot_2021_0815_155850.png](https://user-images.githubusercontent.com/85289861/129610515-a3bffef9-fd5e-4fc3-aa49-4cf4909e4aaf.png)
