### ISSUE TITLE
Given how to create personal access token, but gives absolutely no clue what to do with it

### ISSUE THREAD

**Issue by foysalremon** [github/docs#8612]
### What article on docs.github.com is affected?

[Creating a personal access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)

### What part(s) of the article would you like to see updated?

[Using a token on the command line](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token#using-a-token-on-the-command-line)

### Additional information

After creating the token and going to [this](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token#using-a-token-on-the-command-line) chapter to use token on command line. It says to 

- Clone it
- Give the **username** as it is
- Give the token as **password**

But actually it's not asking for username or password and giving a fatal error says

> Password authentication is temporarily disabled as part of a brownout. Please use a personal access token instead.

So I believe there is information gap on this chapter of the article which need to be updated as early as possible.

**Comment by ramyaparimi** [comment]
@foysalremon Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by thispsj** [comment]
@foysalremon I guess that was a brownout for some maintenance. Though I can't see any such incident listed on [GitHub Status](https://githubstatus.com). I cloned a repository just yesterday using a PAT.

**Comment by foysalremon** [comment]
Okay, this time it's working for me. Maybe the problem was temporary.

**Comment by thispsj** [comment]
> Okay, this time it's working for me. Maybe the problem was temporary.

@foysalremon yes, a brownout is basically a temporary maintenance.
