### ISSUE TITLE
Consider whether call-to-action is applicable on non-English pages

### ISSUE THREAD

**Issue by jsoref** [github/docs#8630]
### What is the current behavior?

Visit any translation of any docs.github.com page, e.g.:
https://docs.github.com/pt/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/upgrading-from-dependabotcom-to-github-native-dependabot

Scroll to the bottom, and read:

Ajude-nos a tornar esses documentos ótimos!
Todos os documentos do GitHub são de código aberto. Você percebeu que algo que está errado ou não está claro? Envie um pull request.

Ou, aprenda como contribuir.

![image](https://user-images.githubusercontent.com/2119212/127419282-bbe68567-9b7a-4f05-9031-ef29334dc97b.png)

The equivalent text exists in the canonical English:
![image](https://user-images.githubusercontent.com/2119212/127419344-550da5db-534a-4ea6-a466-0d5df1c456cf.png)

### What changes are you suggesting?

Suppress the blurb about making contributions on translation pages.

It goes against the current text in: https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations

### Additional information

Admittedly, people don't appear to be trying to follow the text, since they manage to ask [questions](https://github.community/t/word-correction-in-documentation/192109) in [github.community](https://github.community), but even so, why not direct them to the correct answer directly instead?

n.b. the "Learn how to contribute" link could probably stay, but the paragraph and button above it should go.

**Comment by ramyaparimi** [comment]
@jsoref Thanks for opening this issue. We are looking into it 👍

**Comment by Mohsenghasemi12** [comment]
سلام

www.mohsenghasemi135

**Comment by ramyaparimi** [comment]
@jsoref I spoke with the team and we are not interested in this suggestion as many people speak multiple languages and their contributions are valuable.
