### ISSUE TITLE
Character reference is displayed instead of character

### ISSUE THREAD

**Issue by kittykat** [github/docs#8677]
### What is the current behavior?

On https://docs.github.com/en/actions/guides , in the list of tutorials in the page content, ampsand is displayed as a character reference ("&amp;") instead of the actual character ("&"):

![Screenshot from 2021-07-30 13-30-11](https://user-images.githubusercontent.com/51663/127653295-4c1715f8-e34f-4c7c-92d4-7ec148e87924.png)

### What changes are you suggesting?

The character should be displayed instead of the character reference

### Additional information

Using Chromium Version 91.0.4472.164 (Official Build) Arch Linux (64-bit)

**Comment by ramyaparimi** [comment]
@kittykat Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by stevecat** [comment]
Hi @kittykat! :cat: Thanks so much for reporting this problem, I'm able to reproduce it too ✨  This has been raised with our engineering team but will need to be addressed in our internal repository.

I'll leave this issue open while it's worked on.

**Comment by sksahalam786** [comment]
2222

**Comment by sksahalam786** [comment]
468

**Comment by sksahalam786** [comment]
536

**Comment by sksahalam786** [comment]
122113

**Comment by sksahalam786** [comment]
91272

**Comment by sksahalam786** [comment]
333

**Comment by sksahalam786** [comment]
666666

**Comment by sksahalam786** [comment]
12213

**Comment by sksahalam786** [comment]
127270

**Comment by sksahalam786** [comment]
13216

**Comment by stevecat** [comment]
Hi again @kittykat! Our engineering team has just shipped a fix for this. Thanks again for reporting it! ✨
