### ISSUE TITLE
Incorrect documentation regarding omitting the expression syntax for if conditionals

### ISSUE THREAD

**Issue by JojOatXGME** [github/docs#8700]
### What article on docs.github.com is affected?

* https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions
* https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
* https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif

### What part(s) of the article would you like to see updated?

All the sections linked above contain the following snippet:

> When you use expressions in an `if` conditional, you may omit the expression syntax (`${{ }}`) because GitHub automatically evaluates the `if` conditional as an expression, unless the expression contains any operators. If the expression contains any operators, the expression must be contained within `${{ }}` to explicitly mark it for evaluation.

However, according to my own experience (and a lot of examples I find on the web), the exception (*“unless the expression contains any operators”*) does not seem to be true. For example, the expression of the following `if` is evaluated.

    jobs:
      my-job:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

Note that `==` and `&&` are both operators. I think it is pretty confusing that a lot of examples on the web omit `${{ }}` while the documentation claims that it would not work.

**Comment by ramyaparimi** [comment]
@JojOatXGME Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by lucascosti** [comment]
Thanks for raising this, @JojOatXGME; I can confirm this behavior as well, but I'll double-check with engineering that the current behavior is intended.

**Comment by lucascosti** [comment]
Confirmed with engineering that it's not necessary 👍. PR opened here: https://github.com/github/docs/pull/8786

**Comment by JojOatXGME** [comment]
Thanks for fixing the documentation. Good to know that my confusion was not caused by some fundamental misconception on my site. :D
