### ISSUE TITLE
Issue forms page should mention whether pull requests can use the new issue form functionality

### ISSUE THREAD

**Issue by Calinou** [github/docs#8701]
### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

### What part(s) of the article would you like to see updated?

It's not clear whether pull requests can make use of the new issue forms functionality. We'd like to use it for https://github.com/godotengine/godot/pull/42431. That said, since it's most likely not the case, I've opened a pull request to document this.

### Additional information

N/A

**Comment by ramyaparimi** [comment]
@Calinou Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
