### ISSUE TITLE
Issue with readme that occurs in any repo

### ISSUE THREAD

**Issue by Jassi10000** [github/docs#8828]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's Code of Conduct.

### What article on docs.github.com is affected?

Maybe my issue is not intended for GitHub docs
but I was not able to find any repo to open this issue of mine

Issue is : when I create a new repo without any default README.md  , it's simply created

but when I clone that in my VS-Code I make the folders in the repo , also it's my routine to add a README.md in the root directory through commands and then push to the repo , but when  I check that repo on github  , it shows this 

![image](https://user-images.githubusercontent.com/64856348/128393879-3b94213f-5032-4717-9dbc-597b4ee5574f.png)

My question is : when I have already created the readme , why it doesn't showing me up and why it prompting to create a README.md when its already there

### What part(s) of the article would you like to see updated?

I would like to see this issue resolved as soon as possible

### Additional information

No

**Comment by ramyaparimi** [comment]
@Jassi10000 
Thanks for opening an issue. The best place to send your question is to [support team](https://support.github.com/contact)💛
