### ISSUE TITLE
Explain how to handle skipped required checks

### ISSUE THREAD

**Issue by jsoref** [github/docs#8926]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's Code of Conduct.

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/2289ca70c7ec7ec1b81eafdb333cd0157fafaa08/content/github/administering-a-repository/troubleshooting-required-status-checks.md

### What part(s) of the article would you like to see updated?

A section should be added that explains that if people use `paths` for a required check, they'll want to add a second copy of the check with `paths-ignore` for the same content that just returns `true`.

### Additional information

It's a FAQ in https://github.community

**Comment by Fadiabukhadrah** [comment]
Hello
I'm so sorry for the late.,my phone was infected by trojan hours. I have so
I didn't know how to fix it try downloa like 10 it program for antivru
dos't go what I can do?

**Comment by rolerider** [comment]
Subscribe my channel

**Comment by rolerider** [comment]
Hai frnd

**Comment by lecoursen** [comment]
> It's a FAQ in https://github.community

Hi @jsoref, could you link to one or more examples? Thanks!

**Comment by jsoref** [comment]
https://github.community/t/github-pull-request-is-waiting-for-required-status-checks-even-with-ci-skip-in-commit-message/827
https://github.community/t/github-actions-checks-when-not-in-triggers/194399
https://github.community/t/pr-stuck-waiting-for-checks-which-should-be-skipped/18485
https://github.community/t/feature-request-conditional-required-checks/16761/9
https://github.community/t/skip-ci-ci-skip-dont-work-if-a-repo-has-branch-protection-enabled-travis-ci-pull-request/15326
https://github.community/t/github-actions-and-required-checks-in-a-monorepo-using-paths-to-limit-execution/16586
https://github.community/t/dealing-with-checks-enforced-by-branch-protection-but-skipped-by-path-filter/18451
https://github.community/t/monorepos-and-limiting-workflows-by-changed-files-required-status-checks/136030
https://github.community/t/force-succeed-required-workflow-when-skipped/124055

**Comment by lecoursen** [comment]
Thanks @jsoref! This sounds like a great plan that will address a very common source of confusion. You or anyone else is welcome to open that PR! ⚡

**Comment by Fran-Rg** [comment]
Because I landed here from google search, the documented solution is here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

**Comment by TWiStErRob** [comment]
@jsoref I'm trying to research this topic, but all the links in https://github.com/github/docs/issues/8926#issuecomment-900516450 are dead. Where can I find those old forum topics?

**Comment by jsoref** [comment]
Dunno. They did a real number in github.community in their migration. It didn't occur to me when I filed this that I'd need to quote the full contents of each item here...

**Comment by TWiStErRob** [comment]
I tried searching for some slugs without dashes but no results, not even on Google.

**Comment by jsoref** [comment]
@TWiStErRob IA appears to have at least some of them..., here's an example: https://web.archive.org/web/20200928033538/https://github.community/t/github-pull-request-is-waiting-for-required-status-checks-even-with-ci-skip-in-commit-message/827

**Comment by TWiStErRob** [comment]
Oo nice, forgot about that.

**Comment by cb-shivamagarwal** [comment]
May someone please review and merge - https://github.com/github/docs/pull/24182 ?

**Comment by minherz** [comment]
The proposed solution introduce a confusion when changes in a pull request fit both filters (e.g. `paths` and `paths-ignore`). In this case the check list displays the same workflow / job names twice. It would be great to make the logic of "auto-completing" workflow in this case more coherent and less confusing instead of instructing users to use the mitigation method.

**Comment by jsoref** [comment]
Sadly, this repository is focused on documentation. For technical implementation details, there are two main paths that externals (like us) can take:

* https://support.github.com/
* https://github.com/community/community/discussions

I sympathize with your concerns, but it's much easier for me to get documentation added than to get implementation changed.

**Comment by JJ-connect** [comment]
The proposed solution has been removed (as of [this commit](https://github.com/github/docs/commit/bde1cc4f37b0a83cfafb8029cbc4d3cab0907d03)).

What is now the recommended way of dealing with this?

The docs seem to imply that using a conditional rather than path/branch filtering is the correct way to deal with this.
If this is recommended, could there be an example to show how it works?


PS: does anyone have a link for this issue (as a technical implementation) to follow up there too?

**Comment by jsoref** [comment]
> When a workflow is run as a required workflow it will ignore all the filters in the on: section, for example: branches, branches-ignore, paths, types etc. The required workflow will run only for the pull_request and pull_request_target default events. For more information on default activity types, see "Events that trigger workflows."

https://docs.github.com/en/actions/using-workflows/required-workflows#prerequisites

**Comment by minherz** [comment]
Great! If previously it was inconvenient, now it became a nonsense.

There are two problems with the document that @jsoref [referenced]:

1. There is no such thing as _required workflow_. At least I cannot find one when I am configuring setting for a branch. What it does allow me is to setup a _required **check**_. It is very confusing and misleading, especially when there are more than one check (a.k.a. job) in a workflow (a.k.a. file).
1. Ignoring any filters when a job is marked as required, means breaking a contract of the job configuration. It makes the "required check" feature confusing, introduces longer (than expected) check running times and may introduce extra costs.

Such decisions should be published for community feedback _before_ they make intro the product.

[referenced]: https://docs.github.com/en/actions/using-workflows/required-workflows#prerequisites

**Comment by TWiStErRob** [comment]
For 1), @minherz scroll up on the linked page for an explanation. Also notice the banner:

> Note: Required workflows for GitHub Actions are in private beta and are not available for new signups.

**Comment by jsoref** [comment]
@TWiStErRob I don't believe they existed when I opened this issue.

**Comment by srl295** [comment]
Post script: Note that the "how to handle" was removed in https://github.com/github/docs/pull/26591

**Comment by jsoref** [comment]
The repository evolves pretty fast, and certainly a lot over the span of 4 years. For anyone reading this now, the best advice is:

# If you have a required workflow, don't use conditions that would make it run only some of the time
