### ISSUE TITLE
Add More Information

### ISSUE THREAD

**Issue by Eldrick99** [github/docs#8928]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's Code of Conduct.

### What article on docs.github.com is affected?

https://docs.github.com/en/github/copilot

### What part(s) of the article would you like to see updated?

Empty, Add a link to this page ..https://copilot.github.com/

**Comment by ramyaparimi** [comment]
@Eldrick99 Could you provide some additional information on where you would like to see the link added in the page? 🐬

**Comment by Eldrick99** [comment]
Something like this-

[Learn More](https://copilot.github.com)

**Comment by Eldrick99** [comment]
Can I send a pull req

**Comment by Eldrick99** [comment]
It seems that I cant add a link so I'll close this Issue

**Comment by Elpasto28** [comment]
> ``
