### ISSUE TITLE
Broken Android Mirror Link

### ISSUE THREAD

**Issue by Trumeet** [github/docs#901]
### What article on docs.github.com is affected?

[Finding ways to contribute to open source on GitHub](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github)

### What part(s) of the article would you like to see updated?

[Open source projects with mirrors on GitHub](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github#open-source-projects-with-mirrors-on-github)

The link to Android mirror was moved some years ago. The original Android mirror (github.com/android) was migrated to github.com/aosp-mirror, but there is no according updates on this document.

### Additional information

N/A

**Comment by nschonni** [comment]
The Apache org is also no longer a mirror https://devclass.com/2019/04/30/apache-heads-to-github/
