### ISSUE TITLE
docs.github.com pages do not render on iPad

### ISSUE THREAD

**Issue by Paraphraser** [github/docs#9120]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I have tried several pages including [docs.github.com](https://docs.github.com) and [docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) on both iPad Safari and Chrome. On Safari, I get a blank white page. On Chrome a blank black page.

If I try the same thing on a Mac, both Safari and Chrome behave correctly so the problem appears to be peculiar to at least the iPad and, perhaps, to mobile devices generally (but I don't have any other types of mobile device to try). It also doesn't matter whether the iPad is in portrait or landscape mode (that can sometimes make a difference).

I just thought you should be aware of this.

![25395443-8683-4F45-AF87-BB1072E7ED6B](https://user-images.githubusercontent.com/34226495/129900090-d158a8a1-4700-4c8f-9172-24db58190f07.jpeg)

![790E0C90-E8A1-42B0-B964-B6320BF00B53](https://user-images.githubusercontent.com/34226495/129900129-1a61ee0d-fffb-41ad-b6bd-dfe24d8b7b22.png)

### What changes are you suggesting?

Ideally, GitHub docs should be device and browser agnostic.

**Comment by ramyaparimi** [comment]
@Paraphraser Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by thispsj** [comment]
Maybe this is the same as #9120 ??

**Comment by rachmari** [comment]
@Paraphraser this looks like a duplicate of #8565. Can you add the browser versions for FireFox and Safari that you're using on your iPad? 

@ramyaparimi should we close this out and carry and relevant information over to #8564?

**Comment by Paraphraser** [comment]
@rachmari i can't make sense of issue 8585 but 8564 sounds like it could be the same thing (maybe 8565 is a typo?). What I'm attaching here are version details for Chrome, Firefox and DuckDuckGo browsers. They all show the same "blank screen" problem. I could not find any way of getting the iPad or Safari to show me a version number for Safari. When I aimed at "whatsmybrowser", it said "Catalina 13.7".

![76F3E77D-BCD0-4210-BDA5-B8944E3E41DB](https://user-images.githubusercontent.com/34226495/130155017-934bc294-f133-43d4-b541-d553521791e8.jpeg)
![71CF4DB5-A0DD-4C51-9989-3681034CC0D4](https://user-images.githubusercontent.com/34226495/130155023-8333d132-e7e8-44be-b5e9-181191ffffdf.jpeg)
![E13627EC-E91B-4219-86A8-719CB0DA0D37](https://user-images.githubusercontent.com/34226495/130155026-f216ffc2-13dc-4c3e-9b16-051935041353.jpeg)

**Comment by rachmari** [comment]
@Paraphraser 

> i can't make sense of issue 8565 but 8564 sounds like it could be the same thing (maybe 8565 is a typo?)

Whoops, yes that was a typo. I've updated my comment to fix that. 

Thank you for posting this information for us!

**Comment by ramyaparimi** [comment]
> @Paraphraser this looks like a duplicate of ~#8565~ #8564. Can you add the browser versions for FireFox and Safari that you're using on your iPad?
> 
> @ramyaparimi should we close this out and carry and relevant information over to #8564?

Yes, that makes sense since both are related!

**Comment by Paraphraser** [comment]
Please see bottom-right corners of screenshots in [previous reply](https://github.com/github/docs/issues/9120#issuecomment-902308072). Those are the only version numbers I'm aware of for Chrome, DuckDuckGo and Firefox. iPad apps (mostly) have no separate "about box" dialogs or the equivalent that you might expect on desktop systems. And, as noted before, Safari, being "privileged" in the sense of not being a mundane App Store app, lacks even that basic info on the iPad itself. If that isn't enough information then I'm really sorry but I'm afraid that I simply don't know where to look.

**Comment by ramyaparimi** [comment]
@Paraphraser the team worked on a a fix for this. Could you let me know if you still have the issue?

**Comment by Paraphraser** [comment]
Perfectamundo!

Safari, Firefox, Chrome and DuckDuckGo all fixed.

Coffee & cake time for you and the team!! Thanks.

![Safari](https://user-images.githubusercontent.com/34226495/131416212-98892b7f-be78-47cd-ae54-f0141c81de0b.PNG)

![Firefox](https://user-images.githubusercontent.com/34226495/131416236-ff313471-fd5d-4452-b02c-aa0e8cddb891.PNG)

![Chrome](https://user-images.githubusercontent.com/34226495/131416250-e710224f-93d2-486d-b3ee-dbc52c7f2f77.PNG)

![DuckDuckGo](https://user-images.githubusercontent.com/34226495/131416274-21ff20ca-179b-4f08-b07e-340ce29a8b18.PNG)

**Comment by ramyaparimi** [comment]
> Perfectamundo!
> 
> Safari, Firefox, Chrome and DuckDuckGo all fixed.
> 
> Coffee & cake time for you and the team!! Thanks.
> 
> ![Safari](https://user-images.githubusercontent.com/34226495/131416212-98892b7f-be78-47cd-ae54-f0141c81de0b.PNG)
> 
> ![Firefox](https://user-images.githubusercontent.com/34226495/131416236-ff313471-fd5d-4452-b02c-aa0e8cddb891.PNG)
> 
> ![Chrome](https://user-images.githubusercontent.com/34226495/131416250-e710224f-93d2-486d-b3ee-dbc52c7f2f77.PNG)
> 
> ![DuckDuckGo](https://user-images.githubusercontent.com/34226495/131416274-21ff20ca-179b-4f08-b07e-340ce29a8b18.PNG)

Excellent!!! Thanks so much for your patience 💖
