### ISSUE TITLE
Discussions is now out of Beta.

### ISSUE THREAD

**Issue by thispsj** [github/docs#9130]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

According to [this](https://github.blog/changelog/2021-08-17-github-discussions-is-now-out-of-beta) GitHub Discussions is now out of Beta . But the docs still have the beta label on discussions everywhere.

### What part(s) of the article would you like to see updated?

Remove the beta label from Discussions docs.

### Additional information

N/A

**Comment by ramyaparimi** [comment]
@thispsj Can you share a couple of docs pages where the beta label is still used for discussions?

**Comment by thispsj** [comment]
> @thispsj Can you share a couple of docs pages where the beta label is still used for discussions?

@ramyaparimi ahem... It was there when I opened this issue but now it's disappeared from most of the pages. Here is the only article having it :

[The only article having beta label](https://docs.github.com/github/administering-a-repository/managing-repository-settings/enabling-or-disabling-github-discussions-for-a-repository)

**Comment by ramyaparimi** [comment]
@thispsj 😄 Aright! In that case, you or anyone can open an PR with a fix 🔨 

Thanks for opening this issue ✨
