### ISSUE TITLE
Add Action to close empty issue templates

### ISSUE THREAD

**Issue by nschonni** [github/docs#919]
### What is the current behavior?

This repo attracts lots of bots and learning users. People need to learn, but closing blank issues with a hint is better than spending maintainer time to do it.

### What changes are you suggesting?

Setup an action using something like https://github.com/peter-evans/close-issue to close (and comment) on issues that are opened without filling in the issue template.

### Additional information

Probably won't work for things like PRs, as opening them from IDEs automatically creates the PR with an empty template

**Comment by Suya159357** [comment]
3DxYARuZFpZsPEpWee1RSjuPMFktj2sy7y

**Comment by janiceilene** [comment]
😅 That would be really helpful! I'm wary of introducing too much automation to interact with contributors (talking with a human is just a better experience), but there's absolutely no benefit to having a human copy the same comment into every blank issue before closing it. 

Here's the language I've been using:

> This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!

**Comment by Mexicool** [comment]
diff --git a/content/github/setting-up-and-managing-your-github-profile/index.md b/content/github/setting-up-and-managing-your-github-profile/index.md

**Comment by chapo8707** [comment]
Sudo -i`

**Comment by janiceilene** [comment]
This has been resolved 🎉 Closing this issue 💖
