### ISSUE TITLE
Workflows should not generally run on forks or should fail gracefully

### ISSUE THREAD

**Issue by jsoref** [github/docs#9190]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The ability to contribute changes

### What changes are you suggesting?

`github.com/github/docs/.github/workflows/*.yml` should not generally run on forks or should fail gracefully

### Additional information

https://github.com/jsoref/github-docs/runs/3378739101?check_suite_focus=true

```
Add requests to board
failed 13 hours ago in 1m 8s
Run node .github/actions-scripts/fr-add-docs-reviewers-requests.js
#ERROR# HttpError: Bad credentials
Error: Process completed with exit code 1.
```

**Comment by L2021** [comment]
Really it is amazing

**Comment by Alkarar1122** [comment]
Vary happy

**Comment by heiskr** [comment]
I've created an internal issue to review.
