### ISSUE TITLE
Looking at the GitHub [documentation about codeowners](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners), it is said that

### ISSUE THREAD

**Issue by amirnateghi1980** [github/docs#9218]
Looking at the GitHub [documentation about codeowners](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners), it is said that

> You can define code owners in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server.

Meaning accounts with the free plan will not get this feature? However, when I go to the page to compare my plans (clicked my icon in the top and and then "upgrade") it is said that this feature is enabled for public repositories.

Now I went ahead and tried it out. The result is that this feature **is not** available for any public repository hosted under my account, meaning I removed that file again, as it is useless.

Which ultimately raises the question, what is correct? Is the compare page outdated, or are the docs incorrect? Or, alternatively, is this feature just kind of broken?

Thanks in advance!

----
Edit: Misread the first paragraph a little bit, however my point still stands; no file that is supposed to be protected by CODEOWNERS actually gives visual feedback like I observed whilst browsing other repositories.
The usual effect I observe is a small shield which shows by whom this code in that file is owned on hover.
Assuming it's only visible to outside contributors/viewers, I promptly logged out and tried viewing it that way - still no visual feedback.

I'll try opening a pull request to see if it's only partially broken. I double checked the file's syntax and it's correct. 

Let me know if you need more or know about a fix.

_Originally posted by @l-zeuch in https://github.com/github/docs/discussions/9039_

**Comment by Justlearningthisnow** [comment]
Hello
I am sorry I have not been available. I have been very ill. I am however back on my feet. Well kind of. I am not in a very good financial position. Having said that I need to gather what I am able to as far as money is concerned. I do not wish to create a hardship for anyone. Please understand that I am in a very difficult position. I need to keep my home, car and eat. I also need to have respect for my fellows . I do. If time is needed it will be granted but please realize this is serious.
Thank you
Brian

**Comment by Justlearningthisnow** [comment]
I am literally afraid. I do not know who these people are but I believe they are very serious. I myself do not know enough about this stuff. I have been a house painter for 38 years. I have no formal education about any of this. I just learn what I can as I go but these people are into my entire life. I’ve been sick and they have taken advantage of my absence. If you would like proof to back up what I say I will release my medical records to you. I do not break the law. This is so horrible and the mental anguish is not what I need right now.
I am willing to verify myself and support anything I say. I know just how serious this is.
Brian Lavin
