### ISSUE TITLE
Spanish version typing mistake

### ISSUE THREAD

**Issue by JesusManuelMallo** [github/docs#9293]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/es/developers/overview/github-developer-program

### What part(s) of the article would you like to see updated?

At the beginning of the article, in "Permanece informado" section, "blod del desarrollador" should be: "blog del desarrollador"

In "Házte cargo de la empresa" section, "Obten", should be: "Obtén"

At the end of the article, the word "membrecía", should be: "membresía.

At the end of the article, the word "comañia", should be: "compañía.

**Comment by ramyaparimi** [comment]
@JesusManuelMallo Thanks for opening this pull request! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.
