### ISSUE TITLE
How do I track this wallet address 161fS90Cz307pM4bowg7oqi8qBJVaQp8T2

### ISSUE THREAD

**Issue by andrewMcHale411** [github/docs#9301]
How do I track this wallet address 161fS90Cz307pM4bowg7oqi8qBJVaQp8T2

_Originally posted by @andrewMcHale411 in https://github.com/coinbase/assets/pull/12996#issuecomment-905183451_

**Comment by andrewMcHale411** [comment]
> How do I track this wallet address 161fS90Cz307pM4bowg7oqi8qBJVaQp8T2
> 
> _Originally posted by @andrewMcHale411 in https://github.com/wallet/assets/pull/12996#issuecomment-905183451_

**Comment by brycemg** [comment]
Repo. I o
