### ISSUE TITLE
Improved Task list not available on GHES

### ISSUE THREAD

**Issue by Shegox** [github/docs#9317]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/edit/main/content/issues/tracking-your-work-with-issues/about-task-lists.md

### What changes are you suggesting?

The information about the task list suggest that some of the new features (like automatic extension to full name, reordering tasks) are as well available in GHES (e.g. in 3.0: https://docs.github.com/en/enterprise-server@3.0/issues/tracking-your-work-with-issues/about-task-lists), while they are only available in beta on gtihub.com.

The documentation in my opinion should be updated to reflect that this things are currently only available on github.com and on GHES still the old plain markdown task list exists.

---

### Content design plan to fix this issue

A couple of small changes to the [About task lists](https://docs.github.com/en/enterprise-server@3.1/issues/tracking-your-work-with-issues/about-task-lists) article are needed:

1. [Reordering tasks](https://docs.github.com/en/enterprise-server@3.0/issues/tracking-your-work-with-issues/about-task-lists#reordering-tasks): Create an image or animated GIF showing how to reorder tasks on GitHub Enterprise Server, and show that in place of the current animated GIF (which shows the autoexpanding issue URLs, as you point out).
2. [Navigating tracked issues](https://docs.github.com/en/enterprise-server@3.0/issues/tracking-your-work-with-issues/about-task-lists#navigating-tracked-issues): Version this section for GitHub.com only.

**Comment by felicitymay** [comment]
@Shegox - thank you for raising this issue. We are always keen to ensure that the docs for each version of GitHub Enterprise Server only describe features that are available.

You're right to point out that the improved task list is not available in GitHub Enterprise Server yet, however, users can reorder items in basic tasks lists (tested in GHES 3.0 and 3.1). You need write access to reorder items in a task list. It looks as if the extra links to issues tracked in other issues are not available for GHES yet.

Overall, I think the changes needed to the docs are:

1. [Reordering tasks](https://docs.github.com/en/enterprise-server@3.0/issues/tracking-your-work-with-issues/about-task-lists#reordering-tasks): Create an image or animated GIF showing how to reorder tasks on GitHub Enterprise Server, and show that in place of the current animated GIF (which shows the autoexpanding issue URLs, as you point out).
2. [Navigating tracked issues](https://docs.github.com/en/enterprise-server@3.0/issues/tracking-your-work-with-issues/about-task-lists#navigating-tracked-issues): Version this section for GitHub.com only.

**Comment by felicitymay** [comment]
I've updated the issue summary with this plan and marked it as `help wanted`.

**Comment by Shegox** [comment]
@felicitymay you're absolutely right my bad. Reordering tasks works as well on GHES (tested it on our 2.22 as well).  👍 

But yeah the screenshot probably are a bit confusing.

**Comment by felicitymay** [comment]
@Shegox - I hadn't realized that you could reorder tasks on GHES until you mentioned it here, so I've learnt from you too 😁

**Comment by P-DUBB** [comment]
Try a "Lib Talent" in a 2 stack container....

**Comment by P-DUBB** [comment]
https://www.sfgate.com/travel/article/Bay-Area-Port-Costa-day-trip-16607354.php
