### ISSUE TITLE
v4 EnablePullRequestAutoMergeInput MERGE should be in backticks

### ISSUE THREAD

**Issue by jsoref** [github/docs#9345]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/reference/input-objects#enablepullrequestautomergeinput

### What part(s) of the article would you like to see updated?

'MERGE' should probably be `MERGE`.

### Additional information

(This occurs twice on this page, but it's the only content of this form on this page.)

**Comment by ramyaparimi** [comment]
@jsoref Thanks for opening this issue. We notified internal teams, we cant promise when it gets fixed.
