### ISSUE TITLE
v4 reference enums generally need whitespace around backtick'd items

### ISSUE THREAD

**Issue by jsoref** [github/docs#9346]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/reference/enums#issuetimelineitemsitemtype

### What part(s) of the article would you like to see updated?

Every item that has `<code>foo</code>` in, e.g. `IssueTimelineItemsItemType` and `PullRequestTimelineItemsItemType` probably needs some extra whitespace added.

It isn't precisely every item, there are a couple of instances where someone managed to include proper whitespace, here's one example:

![image](https://user-images.githubusercontent.com/2119212/130892719-4898fe31-207a-4306-a038-b6adf8c9a2d6.png)

Note that there's a leading space before `Closable` (there's also a leading space before `ReferencedSubject` above).

There should be both leading and trailing spaces around each of the primary items in each of these things, so:

Not:
> Represents a`ready_for_review`event on a given pull request.

But:
> Represents a `ready_for_review` event on a given pull request.

**Comment by janiceilene** [comment]
Thanks for opening an issue! This content is autogenerated and we're not going to update it at this time.
