### ISSUE TITLE
docs.github.com loads and the immediately produces black screen

### ISSUE THREAD

**Issue by henhal** [github/docs#9383]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Every page

### What changes are you suggesting?

Whenever I go to a docs.github.com page, it loads for a second, shows the content but then immediately turns all black/empty. The network logs shows that an error page is loaded dynamically, such as https://docs.github.com/_next/static/chunks/pages/_error-b90b5bfe49d4c23e9440.js

This has been so for a week or so.
Ubuntu 18.04, using dark theme, logged into github.com. Chrome 79.0.3945.130.

* Go to to https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
* After a split second, the page turns all black. In the console I see that https://docs.github.com/_next/static/chunks/pages/_error-b90b5bfe49d4c23e9440.js is loaded

![Skärmbild från 2021-08-27 13-40-29](https://user-images.githubusercontent.com/9608258/131122034-290af71b-fff1-466c-b779-0584f5d1d8e5.png)
[Screen-recording-2021-08-27.zip](https://github.com/github/docs/files/7066658/Screen-recording-2021-08-27.zip)

Screen recording attached.
Even if I go to https://docs.github.com/, it redirects to https://docs.github.com/en and then turns black.

When opened in Incognito tab, same result (except no dark theme).

**Comment by henhal** [comment]
> @henhal the team worked on a fix for this. Could you let me know if you still have the issue?

I do indeed!

**Comment by JamesMGreene** [comment]
@henhal Would you be able to test this out in a newer version of Chrome? The most recent version of Chrome is `92.0.4515.159`. ✨ 

The version you reported using (`79.0.3945.130`) is about 1.5 years old and may no longer be meeting expectations for supporting the latest web standards. 😬 

On Linux, you can update Chrome using your usual package manager. 📦 

Please let us know if you run into the same issues with an updated browser. 🙇🏻‍♂️

**Comment by henhal** [comment]
@JamesMGreene Wow, I feel stupid now. For some reason I had got into a dead-end chrome update channel. I thought I had verified I had the latest version but apparently not. 

After updating all is good. Thanks, and sorry for wasting your time.

**Comment by JamesMGreene** [comment]
@henhal Not a problem! It was a legitimate bug (see #9120, #8564) that we needed to fix in more updated browsers as well, so getting it working again for you still relied on our bug fix _plus_ upgrading your browser.

Glad to hear you can use the site again! 🎉

**Comment by sksahalam786** [comment]
> @henhal Would you be able to test this out in a newer version of Chrome? The most recent version of Chrome is `92.0.4515.159`. ✨
> 
> The version you reported using (`79.0.3945.130`) is about 1.5 years old and may no longer be meeting expectations for supporting the latest web standards and security practices. 😬
> 
> On Linux, you can update Chrome using your usual package manager. 📦
> 
> Please let us know if you run into the same issues with an updated browser. 🙇🏻‍♂️
