### ISSUE TITLE
Git Mirror instructions no longer work as they are due to http usage

### ISSUE THREAD

**Issue by Shimwell** [github/docs#9386]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Thanks for making such great docs, this is my first attempt to help improve them

I was just trying to mirror a repo and had a go at the examples in the docs.

Now that github no longer accepts http pushes the instructions might need a bit of an update

I would be keen to pitch in and help but there are a few different options to solve it

changing to ssh push will reply with repository doesn't exist error

So I can fix the instructions but it would mean a few extra steps which is not quite as elegant as it is now.

Any thoughts on this

### What part(s) of the article would you like to see updated?

stage 3 of this part https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/duplicating-a-repository#mirroring-a-repository suggests pushing with http which I believe no longer works

### Additional information

error from http push
```
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for
```

error from ssh push
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ramyaparimi** [comment]
@Shimwell Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by solvaholic** [comment]
> Now that github no longer accepts http pushes the instructions might need a bit of an update

@Shimwell do the current steps work ok if you use a [personal access token](https://docs.github.com/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) rather than a password?

**Comment by Shimwell** [comment]
Ah yes that helps. Thanks I looks like I was just a bit out of date with access tokens. Thanks for the help. I think this issue can be closed.
