### ISSUE TITLE
"Advanced search syntax" page doesn't include `@me` syntax

### ISSUE THREAD

**Issue by kospl** [github/docs#9403]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Searching issues and pull requests](https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests)

### What part(s) of the article would you like to see updated?

I would like to see a new part of searching manual related to advanced search variables, like `@me`.

### Additional information

1. Open issues search
![image](https://user-images.githubusercontent.com/26386660/131217473-e767ed4e-06de-443e-bc93-34ab1d8dc7da.png)

2. Open _Filters_ dropdown and click [**View advanced search syntax**](https://docs.github.com/articles/searching-issues) option
![image](https://user-images.githubusercontent.com/26386660/131217511-907c2fe2-50f2-4b41-8a7d-6c77d6f30e1e.png)

3. There is no information on help page about such advanced search option as `commenter:@me`
![image](https://user-images.githubusercontent.com/26386660/131217587-ea19a73f-d239-451e-a6ce-5872cd0a4219.png)

---
### Content design for changes to fix this issue

In the [Searching issues and pull requests](https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests) article:

- Create a new section "Searching for my issues and pull requests" after "[Search by a user that's involved in an issue or pull request](https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests#search-by-a-user-thats-involved-in-an-issue-or-pull-request)" as this is the last of a series of sections about filtering on usernames.
- Mention that you can view a list of all the issues and pull requests you created, are assigned, mentioned on, or are requested as a reviewer of (pull requests only) using the **Issues** and **Pull requests** links shown in the top menu bar when you're logged in.
- Explain that you can use `@me` with any of the fields that take a username to limit your search to issues or pull requests that you have interacted with.
- For more information, see "[Understanding the search syntax](https://docs.github.com/en/github/searching-for-information-on-github/getting-started-with-searching-on-github/understanding-the-search-syntax#queries-with-usernames)"
- Give a couple of examples, based on the examples in the sections above.

**Comment by ramyaparimi** [comment]
@kospl 
Thanks for opening a discussion! The best place to send your feedback is to https://support.github.com/contact/feedback 💛

**Comment by kospl** [comment]
Have a nice triage time!

**Comment by felicitymay** [comment]
@kospl - thanks for raising this issue and for including detailed information about the change that you propose. 💖 

It looks as if `@me` is mentioned in [Understanding the search syntax](https://docs.github.com/en/github/searching-for-information-on-github/getting-started-with-searching-on-github/understanding-the-search-syntax#queries-with-usernames), but I agree with you that it would be good to mention it in this article on searching issues and pull requests too.

We could add an example of using `@me` to every one of the search examples on this page where it's relevant. However, it might be better to add a new section "Searching for my issues and pull requests". This could cover:

- The ability to view all the issues and pull requests you created, are assigned, mentioned on, or are requested as a reviewer of (pull requests only) using the **Issues** and **Pull requests** links shown in the top menu bar when you're logged in.
- The option to use `@me` with any of the fields that take a username to limit your search to issues or pull requests that you have interacted with.
- Position this new section after "[Search by a user that's involved in an issue or pull request](https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests#search-by-a-user-thats-involved-in-an-issue-or-pull-request)" as this is the last of a series of sections about filtering on usernames.

**Comment by felicitymay** [comment]
@kospl - I've updated the issue summary with a content design plan based on my comment above. I'll add a `help wanted` label to indicate that we're looking for help fixing this issue.

**Comment by mark-mxwl** [comment]
Hi @kospl! I've created a PR that hopefully addresses all discussed changes and closes this issue. Thx @felicitymay for the wonderful content outline!
