### ISSUE TITLE
Add correct commands for steps on Creating a Docker container action page

### ISSUE THREAD

**Issue by avinal** [github/docs#9432]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

## The Parts that need modification
- https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#writing-the-action-code
- https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#commit-tag-and-push-your-action-to-github

## Context
Seven months ago I worked on an issue #974 and submitted PR #1256 and #2988. There was performance concern over making shell files executable explicitly inside the Docker. This 
https://github.com/github/docs/pull/1256#discussion_r542055469 has all the discussion. 

Ultimately it was decided to suggest the users to run `chmod +x entrypoint.sh` on their machine before pushing it to the remote. I was not convinced that this will work and there won't be any permission issue while running the script inside GitHub Actions and I am still not convinced.

## Root of the problem.
For the most part, the above method works fine. The problem occurs only when someone clones the repo and then make changes. The permission is reset and it no longer can be run inside GitHub Actions. And that is why you will see a lot of developers/organizations have explicitly made the shell executable inside GitHub Actions before running it. 

 ## What do I suggest
Git provides a way to explicitly change the permission mode of a file so that it doesn't get reset every time there is a clone/fork. The command works as below.
```bash
 git update-index --chmod=+x entrypoint.sh
```
This will change the permission mode of the file in the git index and it can be checked by running following command.
```bash
git ls-files --stage entrypoint.sh
# output
100755 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 0       entrypoint.sh
```
Here `755` denotes the executable permission. 

### Additional information

These lines here https://github.com/github/docs/blame/main/content/actions/creating-actions/creating-a-docker-container-action.md#L124-L128 have no use and can be removed if we opt for the above solution.

**Comment by ramyaparimi** [comment]
@avinal 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Kellyjo152** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
> 
> ### What part(s) of the article would you like to see updated?
> ## The Parts that need modification
> * https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#writing-the-action-code
> * https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#commit-tag-and-push-your-action-to-github
> 
> ## Context
> Seven months ago I worked on an issue #974 and submitted PR #1256 and #2988. There was performance concern over making shell files executable explicitly inside the Docker. This
> [#1256 (comment)](https://github.com/github/docs/pull/1256#discussion_r542055469) has all the discussion.
> 
> Ultimately it was decided to suggest the users to run `chmod +x entrypoint.sh` on their machine before pushing it to the remote. I was not convinced that this will work and there won't be any permission issue while running the script inside GitHub Actions and I am still not convinced.
> 
> ## Root of the problem.
> For the most part, the above method works fine. The problem occurs only when someone clones the repo and then make changes. The permission is reset and it no longer can be run inside GitHub Actions. And that is why you will see a lot of developers/organizations have explicitly made the shell executable inside GitHub Actions before running it.
> 
> ## What do I suggest
> Git provides a way to explicitly change the permission mode of a file so that it doesn't get reset every time there is a clone/fork. The command works as below.
> 
> ```shell
>  git update-index --chmod=+x entrypoint.sh
> ```
> 
> This will change the permission mode of the file in the git index and it can be checked by running following command.
> 
> ```shell
> git ls-files --stage entrypoint.sh
> # output
> 100755 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 0       entrypoint.sh
> ```
> 
> Here `755` denotes the executable permission.
> 
> ### Additional information
> These lines here https://github.com/github/docs/blame/main/content/actions/creating-actions/creating-a-docker-container-action.md#L124-L128 have no use and can be removed if we opt for the above solution.

**Comment by skedwards88** [comment]
Thank you for this detailed issue! You or anyone else is welcome to open a PR to address this.

**Comment by avinal** [comment]
Thanks @skedwards88, I would like to open a PR.

**Comment by noviicee** [comment]
Hi! Since there has been no recent updates, can I take it from here..?

**Comment by cmwilson21** [comment]
@noviicee Thanks for checking in! You or anyone else are welcome to work on this issue.

Thanks for your interest and passion for improving GitHub docs! 💖
