### ISSUE TITLE
Additional step required to enable Verified commits in Codespaces

### ISSUE THREAD

**Issue by Ignigena** [github/docs#9461]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/managing-your-codespaces/managing-gpg-verification-for-codespaces

### What part(s) of the article would you like to see updated?

The documentation instructs on how to enable GPG verification for commits made within Codespaces. At the top of the page, it states:

> Once you enable GPG verification, it will immediately take effect for all your codespaces

However, after following all instructions my commits from within Codespaces were still not signed as expected. After searching I discovered that an additional step is required to enable the `git.enableCommitSigning` in VS Code settings. Once this has been enabled, commits are signed as expected.

It would be great to clarify in this article the additional step required for those who don't already have the setting enabled in VS Code and may run into the same issue.

**Comment by lecoursen** [comment]
This was fixed in https://github.com/github/docs/pull/9277. Thanks for the report!
