### ISSUE TITLE
GET /users/{username}/repos: per_page has wrong max value

### ISSUE THREAD

**Issue by shapkarin** [github/docs#9467]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

URL https://docs.github.com/en/rest/reference/repos#list-repositories-for-a-user

Currently that max value 100 is not right.
<img width="489" alt="Screenshot 2021-09-01 at 06 00 28" src="https://user-images.githubusercontent.com/1463086/131604872-30e94079-87c8-49de-a46d-09d97e27aba3.png">

In some reason the request with param `per_page=100` I got only `62 repos`, but my account has `71`
<img width="197" alt="Screenshot 2021-09-01 at 06 15 16" src="https://user-images.githubusercontent.com/1463086/131605924-b0e56840-89cc-4ab8-adab-7dd2945c526e.png">

Codesandbox example – https://codesandbox.io/s/distracted-cookies-28w0i?file=/src/index.js

### What part(s) of the article would you like to see updated?

I want to updated that part – [List repositories for a user parameters](https://docs.github.com/en/rest/reference/repos#list-repositories-for-a-user--parameters) and that text `(max 100)`

Screenshot:
<img width="489" alt="Screenshot 2021-09-01 at 06 18 07" src="https://user-images.githubusercontent.com/1463086/131606180-9793e6a5-652c-4f2a-b4ae-af538ed17bea.png">

### Additional information

Maybe I use API in a wrong way, not sure.

**Comment by stevecat** [comment]
Hi @shapkarin, thanks for opening this! I think I can see what's happening with the request.

When you make an unauthenticated request to our API, we'll only return items that are publicly accessible. In the case of `GET /users/{username}/repos`, that means only public repositories owned by the account. If I take a look at your account, the number of public repositories you own matches the number returned by the API.

If you want the endpoint to return your private repositories too, I'd suggest [creating a personal access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) with the `repo` scope and using that to authenticate the request. You'll find some examples for authenticating the request here:

https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api#authentication

I hope that's helpful! I'm going to close this issue now. Let me know if I've misunderstood and if you have any questions about authenticating, I'd suggest reaching out on [community forums](https://github.community/) :cat:

**Comment by shapkarin** [comment]
@stevecat thank! make sense I have 63 public repos. UI prints: `63 results for public repositories sorted by last updated`
