### ISSUE TITLE
Suggestion: docs on changing project board visibility should mention that it's not avaliable on repo project boards

### ISSUE THREAD

**Issue by obtusedev** [github/docs#9523]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/changing-project-board-visibility

### What part(s) of the article would you like to see updated?

The doucmentation should mention that changing project boards visibility is not avaliable on *repo* based project boards.  
> unless if you link them to a *user* project board.  

The docs should mention that there are differences between repo, user, organization boards features.  

> repo project boards = Projects tab in an individual repo
> user project boards = Click profile pic -> Your projects

ex: repo project boards can't be made private however user/organization project boards can.

[Changing Project Board Visibility](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/changing-project-board-visibility)

### Additional information

Related to my last issue [9493](https://github.com/github/docs/issues/9493).
I figured out what went wrong.  
I was trying to change the visibility of a *repo* project board to private but the documentations are for *user* project boards.  
Github only allows changing project board visibility for *user* and *organization* boards.  
It **does not** allow changing project boards visibility on *repo* project boards.  
You would instead have to link the repo to the project board.  
Unfortunately this was not mentioned in the relavant documentations and it took me a while to figure it out.  

Perhaps a disclaimer ***Not avaliable on repo project boards*** on [doc](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/changing-project-board-visibility)

### Repo based boards
![Screenshot for repo based project boards](https://user-images.githubusercontent.com/66740598/131767252-4e644a87-ae05-44ff-bc56-db70f65b5868.png)
### Project based boards
![Screenshot for user based project boards](https://camo.githubusercontent.com/2fe68df838b5fb7af01122b8811fea6e37d2136757168806dbac52847801f335/68747470733a2f2f646f63732e6769746875622e636f6d2f6173736574732f696d616765732f68656c702f70726f6a656374732f70726f6a6563742d626f6172642d73657474696e67732e706e67)

**Comment by liannemarie** [comment]
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/changing-project-board-visibility
> 
> ### What part(s) of the article would you like to see updated?
> The doucmentation should mention that changing project boards visibility is not avaliable on _repo_ based project boards.
> 
> > unless if you link them to a _user_ project board.
> 
> The docs should mention that there are differences between repo, user, organization boards features.
> 
> > repo project boards = Projects tab in an individual repo
> > user project boards = Click profile pic -> Your projects
> 
> ex: repo project boards can't be made private however user/organization project boards can.
> 
> [Changing Project Board Visibility](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/changing-project-board-visibility)
> 
> ### Additional information
> Related to my last issue [9493](https://github.com/github/docs/issues/9493).
> I figured out what went wrong.
> I was trying to change the visibility of a _repo_ project board to private but the documentations are for _user_ project boards.
> Github only allows changing project board visibility for _user_ and _organization_ boards.
> It **does not** allow changing project boards visibility on _repo_ project boards.
> You would instead have to link the repo to the project board.
> Unfortunately this was not mentioned in the relavant documentations and it took me a while to figure it out.
> 
> Perhaps a disclaimer _**Not avaliable on repo project boards**_ on [doc](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/changing-project-board-visibility)
> 
> ### Repo based boards
> ![Screenshot for repo based project boards](https://user-images.githubusercontent.com/66740598/131767252-4e644a87-ae05-44ff-bc56-db70f65b5868.png)
> 
> ### Project based boards
> ![Screenshot for user based project boards](https://camo.githubusercontent.com/2fe68df838b5fb7af01122b8811fea6e37d2136757168806dbac52847801f335/68747470733a2f2f646f63732e6769746875622e636f6d2f6173736574732f696d616765732f68656c702f70726f6a656374732f70726f6a6563742d626f6172642d73657474696e67732e706e67)

This is a hacked acct please remive everything

**Comment by lecoursen** [comment]
Thanks @obtusedev for figuring this out! I agree that we should clarify this in that article. You or anyone else is welcome to create a PR doing so! ⚡
