### ISSUE TITLE
More details for newbies

### ISSUE THREAD

**Issue by AlexiyOrlov** [github/docs#974]
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action
### What part(s) of the article would you like to see updated?

As a total newbie to actions and Docker, I made a couple of silly mistakes when trying out the example.
First, in the `entrypoint.sh` file, I wrote `-1` instead of `-l`.
Second, the docker couldn't run the .sh file because of permissions, so I had to add `RUN chmod +x /entrypoint.sh` to the dockerfile.
Also line `uses: actions/hello-world-docker-action@v1` shows how to use published action. You should add that unpublished action is used via `uses: [username]/[reponame]@version`.
So I think these 3 things should be pointed out there.

**Comment by janiceilene** [comment]
Thanks for opening an issue @AlexiyOrlov! I'll triage this for the right team to take a look.

**Comment by runleonarun** [comment]
Hi @AlexiyOrlov! Thanks for this issue. I'd definitely like to smooth out the process for newbies! 

> Second, the docker couldn't run the .sh file because of permissions, so I had to add RUN chmod +x /entrypoint.sh to the dockerfile.

🤔 We do have that in [Step 2](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action#writing-the-action-code) where it tells you how to make the file executable.

Here are some suggestions for the other two ideas:

> First, in the entrypoint.sh file, I wrote -1 instead of -l.

Because we do use "l" and not "1" in the example, I don't think we need to add any explanatory text. One thought is that we could add `{:copy}` to this code snippet so the copy icon shows up like it does [here](https://docs.github.com/en/free-pro-team@latest/actions/quickstart#creating-your-first-workflow). For example:

```
```shell{:copy}

```


> Also line uses: actions/hello-world-docker-action@v1 shows how to use published action. You should add that unpublished action is used via uses: [username]/[reponame]@version.

This absolutely can be added to the docs! Thank you for suggesting it.

**Comment by avinal** [comment]
I would like to work on this issue if no one is working on it.

**Comment by janiceilene** [comment]
I don't see any open PRs for this issue, please feel free to open one @avinal 💖

**Comment by avinal** [comment]
I have added a pr please take a look.

**Comment by lostnco1** [comment]
@AlexiyOrlov  thanks for this issue, I think I need to try and get a template set up and find a way for me to file everything in the correct order.  I mostly use android and I need to figure out the right way to get the best results

**Comment by AlexiyOrlov** [comment]
Ah, no problem.

**Comment by himanshu211raj** [comment]
I like to work on this issue if no one working on it! As I am a beginner and need some guidance regarding how to contribute to open source.

**Comment by rectorhotel** [comment]
Also a newbie, super excited to learn all the ins and outs of the github

**Comment by janiceilene** [comment]
@rectorhotel It looks like there's already a [pull request](https://github.com/github/docs/pull/1256) opened and it's just waiting for review. There are lots more issues available with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label!

You can also take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo and open a [discussion](https://github.com/github/docs/discussions) if you have any questions ✨ 

We're excited you're here!

**Comment by rectorhotel** [comment]
Thank you so much Jenna!

**Comment by martin389** [comment]
Thanks for creating this issue!

> Second, the docker couldn't run the .sh file because of permissions, so I had to add `RUN chmod +x /entrypoint.sh` to the dockerfile.

I think it would be preferable to keep `chmod +x /entrypoint.sh` outside of the docker container, as this avoids having to create an extra layer for the `RUN` command. (This part is described in [step 2](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action#writing-the-action-code))

**Comment by avinal** [comment]
Hello @martin389, I have added a PR #2988.

**Comment by martin389** [comment]
Great, thank you @avinal!
