### ISSUE TITLE
Put the preview notice at the top of the subsection instead of at the bottom

### ISSUE THREAD

**Issue by gijswijs** [github/docs#980]
### What is the current behavior?

The preview notice is shown at the bottom of a subsection. This makes it very easy to overlook. (e.g: https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-using-a-template)

![image](https://user-images.githubusercontent.com/7912094/97844212-97a37700-1d25-11eb-90f8-894c8d5b8edb.png)

### What changes are you suggesting?

I suggest putting the preview notice on top of the subsection directly below the heading. This was also the behavior in the old documentation. See: https://developer.github.com/v3/repos/#create-a-repository-using-a-template

![image](https://user-images.githubusercontent.com/7912094/97844351-d9342200-1d25-11eb-85b3-89bf0f153772.png)

**Comment by runleonarun** [comment]
Hey @gijswijs Thank you for raising this issue! I agree that the preview note could use better visibility. We will look at this problem holistically and consider some different ideas including moving the note.

**Comment by janiceilene** [comment]
We're looking at this internally since it would be such an overarching change!
