### ISSUE TITLE
Docs seem to include old information on how to delete docker images from package registry.

### ISSUE THREAD

**Issue by simonholzapfel** [github/docs#982]
regarding https://docs.github.com/en/free-pro-team@latest/packages/managing-container-images-with-github-container-registry/deleting-a-container-image

### What is the current behavior?

how the actual manage versions page looks like:
![image](https://user-images.githubusercontent.com/38250977/97866859-07f1ce80-1d0d-11eb-83b7-324723244a01.png)

how the docs look like:
![image](https://user-images.githubusercontent.com/38250977/97866925-25bf3380-1d0d-11eb-802e-a532422d4173.png)

### What changes are you suggesting?
I suggest either fixing the docs, or fixing the manage versions page.

### Additional information
I am on the GitHub Education plan.

**Comment by Botfacke** [comment]
Cool

**Comment by janiceilene** [comment]
Thanks for opening an issue @simonholzapfel! I'll triage this for someone on the team to take a look at. Do you have admin privileges for the package you're trying to delete?

**Comment by simonholzapfel** [comment]
Yes, since I am the owner of the repository and the publisher of the container image.

**Comment by lucascosti** [comment]
🤔 I'm seeing the same thing for my docker images...

@jmarlena Do you know who to ping about this procedure?

**Comment by jmarlena** [comment]
I'd ping @github/support-package-registry-ombuds, which includes @jcansdale.

**Comment by jmarlena** [comment]
👋🏽  @simonholzapfel 

Looking closer at this issue and not just the last immediate question, here's two thoughts on this: 

1) Is your package public or private? Because public packages will not show the delete button option. 

2) Also, just for your information, I think the UI here could be a bit different if you have container registry enabled but I suspect the main issue here is that your package is public.

**Comment by lucascosti** [comment]
> Is your package public or private? Because public packages will not show the delete button option.


🤔 I don't see this mentioned in the article. The article says:

>> When deleting public packages, be aware that you may break projects that depend on your package.

 If public packages can't be deleted, we should probably update this and mention it. 🙂

**Comment by jcansdale** [comment]
> regarding https://docs.github.com/en/free-pro-team@latest/packages/managing-container-images-with-github-container-registry/deleting-a-container-image

They're referencing docs for the GitHub Container Registry, where deleting public container images is possible,

Once of the screenshots is for the npm registry:
![image](https://user-images.githubusercontent.com/11719160/99529490-cd886280-2997-11eb-898a-d00b0a29cf4b.png)

`You can delete a version of a private container image using GraphQL or on GitHub.`

We don't have a GraphQL API for deleting container images from the GitHub Container Registry. I think there are plans for a REST API, but not a GraphQL API like GitHub Packages has.

**Comment by simonholzapfel** [comment]
@jmarlena Thanks for the info, my package is indeed public!
But how can container images be deleted then?

**Comment by simonholzapfel** [comment]
I solved the issue by making the repo private, deleting the container images and making the repo public again, but this can't be the official way of solving this problem, right?

**Comment by jmarlena** [comment]
@simonholzapfel

I checked some test container images and I also didn't see the delete UI button but I learned that if you only have one container image version, the deletion button will be found in the options under "Danger zone." I wonder if this applies to you? 

Either way, I see the need to update the UI for the container article. 

1. 
![image](https://user-images.githubusercontent.com/6732600/99841205-a611d100-2b22-11eb-88f8-18d1e5719831.png)


2. 
![image](https://user-images.githubusercontent.com/6732600/99839403-8200c080-2b1f-11eb-9da0-b8f151367bd2.png)

**Comment by jmarlena** [comment]
Heads up, I've opened a PR to address the UI mismatching and confusing intro. Also, checking in on any related UI updates coming up to see how we can keep this evergreen. I'll delete this issue once the PR ships.

Someone is welcome to create a PR from this issue to fix the confusing intro as that doesn't seem to need more dialogue to fix. 🚀

**Comment by Marcono1234** [comment]
It appears the docs also don't match the current UI for packages: ["Deleting a version of a private package on GitHub"](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/deleting-a-package#deleting-a-version-of-a-private-package-on-github).
(And the "Package Settings" button on the top right seems to be broken; it just brings me back to the packages overview)

Do you want a separate issue for that?

**Comment by janiceilene** [comment]
@Marcono1234 If you could open a separate issue, that'd be super helpful, thank you!

**Comment by tsal** [comment]
The "updates" to this did absolutely nothing to clear up this issue. The current UI is so COMPLETELY out of whack with the document, one might think it was made for a different application entirely.

I am an admin (owner) of the repo and org, and I have no UI elements that match (rounded corners or otherwise) for managing packages. In fact, the only thing I can do is edit the description for any package version.

I get this is managed by open source, but this UI update has caused far, far more headaches than it has simplified anything.

This isn't on the community to fix, this is on GitHub to fix.

**Comment by jmarlena** [comment]
Hey @tsal, 

I'd like to better understand the UI you're seeing and what type of packages and Docker registry you're using.

The UI to delete versions of private GitHub packages published on GitHub using this URL `https://docker.pkg.github.com/OWNER/REPO/IMAGE-NAME `  should match the UI in this article: 
https://docs.github.com/en/free-pro-team@latest/packages/manage-packages/deleting-a-package#deleting-a-version-of-a-private-package-on-github

The UI to delete Docker container images published on GitHub using this URL `ghcr.io/OWNER/IMAGE-NAME` (This is part of the improved container support beta release, which you must [enable](https://docs.github.com/en/packages/guides/enabling-improved-container-support)) should match the UI in this article:  
https://docs.github.com/en/free-pro-team@latest/packages/guides/deleting-a-container-image

Does this clarify which UI you're expected to see? 

We're in the process of reorganizing these packages docs to better clarify which version of the Docker package docs users will need. I'm wondering if this will clear up the confusing UI expectations.

**Comment by tsal** [comment]
Thank you. The first link cleared up everything. I was expecting the UI to still be with the github packages interface, and did not find this updated documentation, despite a lot of searching, only this issue by virtue of another closed issue on this repo.

**Comment by jmarlena** [comment]
The changes to fix this issue were shipped months ago now but this public issue wasn't closed then. 😅 

Feel free to open up a new issue if you something else that needs clarity or a fix. 💟
