### ISSUE TITLE
Actions: Document "notice" workflow command

### ISSUE THREAD

**Issue by rcowsill** [github/docs#9873]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions

### What part(s) of the article would you like to see updated?

The section [Using workflow commands to access toolkit functions](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions) doesn't cover the `notice` command, but does include `warning` and `error`.

The equivalent `@actions/core` toolkit functions are all documented at: https://github.com/actions/toolkit/tree/main/packages/core#annotations. That suggests the `notice` feature is not intentionally being left undocumented.

I'd like to add the `notice` command to the workflow commands page, so its documented for people writing non-js actions.

**Comment by ramyaparimi** [comment]
@rcowsill 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:
