### ISSUE TITLE
Octokit example not working for "Update a webhook configuration for a repository"

### ISSUE THREAD

**Issue by fabzo** [github/docs#9900]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/repos#update-a-webhook-configuration-for-a-repository

### What part(s) of the article would you like to see updated?

The current example code reads as follows:
```Javascript
await octokit.request('PATCH /repos/{owner}/{repo}/hooks/{hook_id}/config', {
  owner: 'octocat',
  repo: 'hello-world',
  hook_id: 42,
  url: 'url'
})
```

But Octokit will interpret all first level attributes of the options object as configuration parameters if applicable. From my understanding it will take the 'url' attribute from the options object and ignore the request path. See https://github.com/octokit/endpoint.js/blob/master/src/merge.ts#L14 as well as https://github.com/octokit/endpoint.js/blob/master/src/parse.ts#L76

The example resulted in my code trying to send the request to the provided webhook URL instead of the GitHub API.

The working code looks as follows:
```Javascript
await octokit.request('PATCH /repos/{owner}/{repo}/hooks/{hook_id}/config', {
  owner: 'octocat',
  repo: 'hello-world',
  data: {
    hook_id: 42,
    url: 'url'
  }
})
```

Unfortunately I could not find the location of the code example in the documentation and thus was unable to propose a change directly.

**Comment by gr2m** [comment]
Hi 👋🏼 Octokit.js maintainer here

This endpoint is unfortunately a special case. It did not exist when I created `octokit.request` originally. I think it would make sense to change Octokit's behavior at this point, I created a follow up issue here so you can track it. https://github.com/octokit/request.js/issues/425

The Octokit examples are generated, some of them are not quite correct. Adding manual overwrites would introduce quite a lot of complexity and maintenance overhead, I'd rather not do that, but wait for me to address the problem with the `url` parameter in Octokit itself

**Comment by skedwards88** [comment]
Thanks for following up @gr2m and thanks for opening this issue @fabzo ! Since this will be fixed in the octokit repo, I am going to close out this issue.
