### ISSUE TITLE
Actions: Typo in workflow command table

### ISSUE THREAD

**Issue by rcowsill** [github/docs#9901]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions

### What part(s) of the article would you like to see updated?

The table at the end of the [Using workflow commands to access toolkit functions](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions) section has an error on its last line. 

The equivalent workflow command for the `core.warning` toolkit function is given as `warning file`. That should just be `warning`.

`file` is the name of one of the parameters to that command, so it shouldn't be shown as part of the command name. For example, the entry for `core.error` in the same table says the command is just `error`.

**Comment by ramyaparimi** [comment]
@rcowsill 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by abxhr** [comment]
I would love to work on this issue! 🙋‍♂️
