### ISSUE TITLE
Actions: Improve "stop-commands" example code

### ISSUE THREAD

**Issue by rcowsill** [github/docs#9919]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions

### What part(s) of the article would you like to see updated?

The section [Stopping and starting workflow commands](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#stopping-and-starting-workflow-commands) has an example of using `stop-commands`:

```Shell
echo "::stop-commands::pause-logging"
[...]
echo "::pause-logging::"
```

This example uses a hardcoded resume token, which is not best practice. Also, it's confusing that the command to resume processing is `::pause-logging::`

There's a much better example in this blog post: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

```Shell
# disable command workflow processing
echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

# log untrusted output
echo "untrusted output"

# enable workflow command processing
echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
```

This creates a resume token based on the GITHUB_TOKEN, so it's different on every workflow run. Doing this makes it almost impossible for the untrusted output to resume command processing.

UPDATE:
An example based on this code would be ideal: https://github.com/actions/runner/issues/807#issuecomment-916236648

It adds a mask for the resume token, so it can never appear in the workflow run logs.

**Comment by ramyaparimi** [comment]
@rcowsill 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by rcowsill** [comment]
Just noticed PR #9426, which relates to this issue.

**Comment by ramyaparimi** [comment]
@rcowsill Please link this issue and PR if the PR mentioned fixes this issue. That way, when the PR is merged, this issue will be closed 🐬
