### ISSUE TITLE
[Webhooks] Undocumented `workflow_job` event

### ISSUE THREAD

**Issue by wolfy1339** [github/docs#9964]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments

### What part(s) of the article would you like to see updated?

I would like to see documentation added for the `workflow_job` event.

### Additional information

I have some example payloads located [here in `octokit/webhooks`](https://github.com/octokit/webhooks/tree/master/payload-examples/api.github.com/workflow_job)

The webhook seems to fire for every job in a workflow

**Comment by ramyaparimi** [comment]
@wolfy1339 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by wolfy1339** [comment]
It seems the docs were just pushed out today.
That would close this issue.
👍

**Comment by lecoursen** [comment]
Thanks for the update @wolfy1339!
